### ISSUE TITLE
Remove leading pipe for one-line DU definitions

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1030]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAgmALwA6ATiQHYQA%2BYAGpADThQDOi66AlpQOZtUYANqsIoCJKgASLLiGRe6ZmMmRpANwCGAGwCuyNKKlSADCxNqAkpSSV0AZW4AvZBctgALKogBdVQC%2B7uI%2BMnKGUEoqlura%2BhHGHgCMwSaQALJaAB4AMryIOYj86AAW0ckATKah-lJBqhJpsjgRkABGsLA65VKxugZCiZYVqb0OiAC23HA6sJT46ACitgDyAGZ5lG6hEGu6HDWBqY29zfJo7Z3dozJxA0Y7YADMNxCQDtha0IgAQohrsDIiAACloyFoJpxEGQeiZ0GQDIc6sdQupwgoOl1YW9NP0Eo9PK8oB8vr9-oCCrAAO7Q6BaDg2DSwOk8ObYyTwxGWWqSepSE5qM6tTHXVG4%2BKDR4AViJ70%2B3z%2BAKBAFVsLgyHSGZQmSzuGyiXsdAduUcGmL0RcRey%2BhKHh4wAA2WUkhXkoEAYR09LY7rmbE50HQgPZu32iCRvJRMSFGKu1vF9xEjwA7M75WSlYh0pM2tCQ2BDcaTDyIHzJAKcRaoFabjbE0MTAAONOkxUU32zSj5wvhk3Is3RquXLG1hP4%2B0AThb33wa3Q0N9EwmWnznN7xdN-PNLVjI7Fd3HyXMjzlrbdiHGUxm%2BsePYjpajTSHNf3eMl9qSKRPLsQs-nZEvaYuhve013vMAyxCQcd0tONRwPd9KllGw7HQFZKAAFTITAAHVuFKbsw3AyCwArMIYOrODX1tJMPxeb903wMhYD0WwABFEB0bgpn-VcEXXKQSwgx9TiHKJ4LfO1kkJE9MiyKw1gwkoikWI0LxKQF0Dw%2BACKJTxqj7SMByfCjFHseMEKkywkhlWTshsNZuCyFZ1S0IMyEWLJsCBNg2D1LsiSlAyN37LdoPOSJzIkmiGykJInTsrIACVEDgMh4G03SCWCwTN3LbcIrM5RovrR4klTRKmPBTAVjIPJ-Uyso9JyyQhJIsi0VM8TqNKj9m0SgA1PEfl4eBeD4Rr8304iRMFMSop6w9rKnRKADFWMDfyRtscbJuambjNE0yX2jSzaI8KpZXSPQdB4Lith%2BWZoAAax%2BcEXs4Nh0IcCFEA7PQJgC28iMMh9Drm46qNOyTzuGL97UgAA5RAqXusl0BpIoMJaDjHMofD-PwWxswmXMyEEA0QZCoywpMwqTqaM7YskCoRhPABpRBEGwBSlKKGwfshTZtntO9QeE8HKy6hboZix4KnohG5NUqY2BKPbsoO2mjvpqHGZh5mIAqGSEacfgdF-Mg%2BABootMQNp0gQEWPDF6mwe1iHdb3WXeou2yEfwLi%2BEodbKE2uYnGDty9CBDDYBQ223P8wi1K1-LwuFPXTiZ%2BWEoD27oUoJONEpfgSbJ3HeAJv0U6LXLQvTunM%2B9-W5ftCoKtN%2BFpnQR2kFrgTWsCVhfHcRQ2FWvyhDvAIgA)

#### Code

```fsharp
type A =
  | X
```
            

#### Result

```fsharp
type A = | X
```
            
#### Problem description

Expected:

```fsharp
type A = X
```

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this. _(I'll help in any way I can except implementation; I don't have the capacity to ramp up on a new codebase now)_

#### Options

Fantomas Master at 08/21/2020 08:12:02 - 866535662e4cc286f84e893ef7ff5cc5cabae31c

Default Fantomas configuration

**Comment by nojaf** [comment]
`X` could be another type so that would make it a type alias instead of a DU.
The pipe is necessary to make sure it stays a DU.
See #641

**Comment by cmeeren** [comment]
I see, thanks for the clarification.
