### ISSUE TITLE
Allow line break after return to avoid excessive indenting/aligning

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1062]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzMAFAJRgC8AOgE7kB2EAhgM4CeN0YwVtEEmOAHmTAAmLnR6VsAV0p1GsALaIwlelgAWiSmHSwaAczAAfAHxhGWKbnwa1xs1MaJGYAA4BLDwftgssAORgSAp6FqpYyqa%2BmmDujIxSiGIQAL6QADTgUE5YWO4GjKhgANpZEKA8PJAAJFjMrshokPlYGWVV1QBu9OiJRaWVlQAMmYNVAJI0SDRYAMruAF7Io2NgACztEAC67Skr5ZtQtfWNUC1tYzXdvacDqwCM%2B4OQALL0-AAy%2BYgfiAYaFwewiGhx2lT27Qqz2ODSKkAARrBYOhAZUrj0%2Bmg7mNhE80bNEAp3HBdDQAIJYACiUwA8rgvjRlocILgek5QbsnlC0TDTgikSi8UdrpiSsywABmIUQSCzVz0aCIABCiFwsEkAAV6KolBFKKjBlhKIkOeCuYcanVYU1EciDTKuhjbuK1tKoHKFcrVeqfrAAO5aaBMRCTTqwIN5PT2nhGk1jME8CGVbkdK1822Ci2Om79cUAVjdsvlipVaskAFVXA1KEGnKHw2p3FG3az0Oz45zIVm03CM9H0TmseKAGyFj0l72SADC6CYjCnoVj0D8%2BpbbMQpsT5suvN7Av72dF2MGAHYx8WvWXEC9CfCtNGWevN6lt9Cezb90KB0fxQAOc%2BeqWPoLqSD54E%2BHZml2O7vlAfZfoezqrGAACcAGKmSuB6guCgKPQYGxhukFbtBb4nHudoISKSEPCM4pFoBk6IASRIks24qtu2gwJi%2BpE8rB-KUVm1G5sh9yPPR46IJheoscSyLschhHPmASY8CmDoCfBwlOqJQKFpM0xYDSNAACqUMwADq7gAmubZEdxnbJt25EfkJO4iUOYlSpJF5kpQsBSFMAAiiDoO4RJ6gRxoOZUPGqa%2B-GuWcMwHp5Ypia69FvPw4y4KZmg0JS9mzOo6pYNZ8C2S6ILEbxzkwclzSpVRuleQ8BbZe8ky4O4-A0tWajqpS-CuJI8RNjQYF5rVjlQQ1ZHWilrStYOGUPKOXX8AASogcCUPAlXVchayzXFTnqS5S3NStOlrcelT3GeW3%2BaozA0pQXwWEd6hgadKlqQcjXXecq0-mJ-5bQAak6Sr5PA%2BT6D9f1nTw8WAxwV18qDd3gw8aFbQAYkFy6TXDUyI8jbr-XVCV8amTXaR5bXrTidHIa8UjoHk4WMkqujQAA1kqqhC9gjAmbM9BKCBUgKFNdlced82XcD6afrjNE4hJHMAHKIH6vNelgAZ-KZJyhb1NA2ZNZJTDeCh3pQhSK7FaMXUDi3q%2B50LpQ9PDCLi9EANKIIgrh5QVfyTFLSgMkyyGcW72we5jatwjjzP3eKwg%2BRzOXFUSjDqFTNUA4lDPXUzvss-7EDCFlHPzAYmD%2Bfoct-BViDwi8CAJ6sSfl-TmmMxrWd4zinUc2S4X6DQxNsJGNDzHPagyIgpmwIZneNopA8QXNJELUlVdjzX2fIcIm3T9zWg0I2nS%2BgYDtO5b%2BQ26EYGD7TGMaUcWlnx5H7HOz0m5GmJFgXuSAv4H2VomLIWwVjNEYITRg7giiDxSEAA)

#### Code

```fsharp
let f () =
  async {
    let x = 2
    return some rather long |> stuff that |> uses piping |> to' demonstrate |> the issue
  }
```
            

#### Result

```fsharp
let f () =
    async {
        let x = 2

        return some rather long
               |> stuff that
               |> uses piping
               |> to' demonstrate
               |> the issue
    }

```

#### Better (IMHO)

```fsharp
let f () =
    async {
        let x = 2

        return
          some rather long
          |> stuff that
          |> uses piping
          |> to' demonstrate
          |> the issue
    }
```

            
#### Problem description

I find that excessive right-aligning damages the readability (see #657 for reasoning; other related issues are #658, #659).

IMHO it would be best if Fantomas avoided excessive right-aligning by default, but I'd be happy just to have the ability to configure this.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this. _(I'll help in any way I can except implementation; I don't have the capacity to ramp up on a new codebase now)_

#### Options

Fantomas Master at 08/31/2020 11:05:40 - 71328ceb18d4d9c8ee65d1aeac9972e3e166754c

Default Fantomas configuration

**Comment by nojaf** [comment]
Thanks for reporting @cmeeren, maybe we can do the same thing here as we do with multi line `yield!`.
See https://github.com/fsprojects/fantomas/pull/1001
