### ISSUE TITLE
Format code twice in unit tests

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1091]
In order to further guarantee the correctness of the formatted code, it would interesting that code in unit tests are formatted twice before asserting the result.

**Comment by auduchinok** [comment]
What if the formatted code is not correct after the first run and is correct after the second one? 🙂
Could it check that formatted code is correct after the first run and is the same after the second one?

**Comment by nojaf** [comment]
Good thinking, after the first format code, should already be valid and the expected output.

**Comment by josh-degraw** [comment]
Added in #2898
