### ISSUE TITLE
Extra whitespace lines added in fsi files at the end of a nested module declaration

### ISSUE THREAD

**Issue by vsinha** [fsprojects/fantomas#1105]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAogB4CG6ADngDoBOVAdrQ5vLvgGKyxgC8YT9CBBZswAIRI1e-OoKHyALgE9y%2BBdIBGXHAPnyAbiRxgcsHGiz0AluoC0APjBazuoa4jLVYdXyv0F7mCGxjjoJLAW1naOzjqyAgIieGCcsABMvIFJ%2BBJSPIGKKmqa2gmyekLBJmaRNmAOTqXxzQyFXj5gfgEtchBVoeG10Y0uspAANOBQAM6ICgp%2BAObTqGAA2lMQoBWQACSeyGiQXRObQnvBWIfrZ-IADJMVEJAAkvRI-gDKVgBeyI9PAAstzAAF0zgBfAFbEF7A6rY7%2BU47XaXa4bJ5gACM0L0kAAsiQiAAZPyIYmIeiLBQAC2RTyxaTuIPB8ihZ22eP2RQRsXp8guRiuqwxTzSuIFn0Q6CscFM9AAggoCO8APIAM1J9H%2BIIg6qMsxZkNxnIF3NUvO0-POqKF6N1YAAzBLzp9yCRoIgxIh1bAaIgAAqSMhzRA0a2KGhXI1sk2w83XSB8l2CnDCtCiiqAl3PN0er0%2Bv3k2AAdzD0BIsze%2BlgFYWsHoEaECijiBjQnZ8lNNvhR2T8bRIodAFYc1A857vb7-QBVciqGgVqv0Gt1qwNpt6g1tiqsjtxlG9qD9lGDjMOgBsY8gE4L08QAGEcJXpg%2BG9MW1hoAo-ZuwPqcENXdjQ5eMjyTK0U1tNN7UxAB2a9bynIt8WlDQwz-ACgL0PcIE7IRu2eBNLTMJtU3TG5MQADkQ91J0Lf033lTDt3bPCDy5cCTy5M9KKeABOWj8wVdUFDDN90DCP9Px3HCQK7MCeT7SCBztIdMSxB4HRvOi7yLKUZTlDcxyw2T5FwsB8JhQ8lOPFTTzU88NJxbTbxEsSaAM2UzGMh0ZLYyyOLNLj7J4xy%2BIqRlrzeD4FFVegABUaCUAB1Gw6RM1jgNjUCbItZTSKg3jMz0LFnVc3SFRoWBLHgAARRAcCsGUPOk1sAqssBCKgYijhOIrwpK%2BQsWzbTCSIF51QSmlKQIQDEE%2BGk-QUNL4FpP9AWZbL91yzjbMRBQyOgiihqELFRzGok3nVKwiFVBcSB-GhiHIf1pmmddGzHYctrknKFLyxN%2BtUmD1IZK9LqIAAlRA4BoeBVvWsdNo6oKe324GHNBpyGQQyGqpoEglFVGhSQ-RGModFHtvY3bgoxpEBuxiLSpoyGADU7TEPx4CWCmNt%2B8z5IIxT8qgTGwuZ06ICxQTIfYSxv0%2B7n3j5qw1spzFqb%2BnaAb2sWIMKkGTodJlr3xXAFia7UxFMaAAGsxEJh25mmeLPhDJisHQL6HVM1G6fRg3uLNYrTZczFIAAOUQEtrYLBQy0pBKigam6ok%2BhV3lQ9B0JoFZMvmgO9fp4PQtDwbTfFbSAGlEEQchJumyk3g99ByTJFii5pwLA6I8CJYrqXTfKyPxrmmVphpfnkcFoQLM67q4X2kObTDzE0lGyPvipPAqsWb3KRWxANHxBAdUxf2e8X0XE1Xoj17FC7I4VJrFnoBX6CVhtvnfx6sH9AlWAMUj6PU%2Bl3bCQt-oi0BiRHAR1H4VDSBDF%2BOAPL0DAfoYsVIc55zTn4Gwn0C5%2ByyjrWmJcg533LmvSuG88bbxbLKBQZ8kAQLMvPSEUxQQAmONMdgH1Vj%2BQhEAA)

#### Code

```fsharp
module Example

module Foo = 
    module Bar = 
        type t = bool
        val lol: unit -> bool
    
    type t = int
    val lmao: unit -> bool


module Foo2 =
    module Bar =
        type t = bool

        val lol: unit -> bool


    type t = int

    val lmao: unit -> bool

```
            

#### Result

```fsharp
module Example

module Foo =
    module Bar =
        type t = bool

        val lol: unit -> bool


    type t = int

    val lmao: unit -> bool


module Foo2 =
    module Bar =
        type t = bool

        val lol: unit -> bool



    type t = int

    val lmao: unit -> bool

```
            
#### Problem description

Foo2 is the formatted output of Foo1, and both add 1 new line, resulting in 'new line creep' over repeated formatter runs

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 09/04/2020 15:37:11 - dc08bfbe4348983ccef0b33be523669681dc0873

Default Fantomas configuration

**Comment by nojaf** [comment]
Thanks for reporting all these issues, the `new line creep` once are easy to solve but rather hard to anticipate.
One day we'll have them all...

**Comment by vsinha** [comment]
Thanks for being reponsive and fixing things! I'm more than happy to continue to report stuff :)
