### ISSUE TITLE
The 'member' keyword gets deleted in 'abstract member' declarations

### ISSUE THREAD

**Issue by vsinha** [fsprojects/fantomas#1106]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAogB4CG6ADngDoBOVAdrQwC4Ce5%2BAYrLGALxgm9CBBIAjAM7MaJaMzDpE6MYhpgxJNWgCW9ZpAA04KBMTNmugOYTUYANrGIoESMgASNh1uRd%2Boy4h3ADcSHCxkNAcAkQAGf2ioAEl6JD0AZW0AL2R46IAWRxEAXUKAX1ywZwD3TwioX0NCwLcQsLqohIBGCpdIAFkSIgAZXUQhxHpLZgALRoSwToAmGKawEpdywqrej3Y6yDEeHDnqltDw2w7oxZ7XNKVtOBxYegBBZgIUgHkAMxH6HKrCA-UKmVbrESbFzbVy7LxoA5HE47VoXSJAsAAZlugTS5FkiAAQogfrAaIgAAqaMhmVTIgLScLgsoVGHNWreQ6wY63YLndoYvI4qB4gnE0nkoawADuqmgJFMySCsHlFhe9JcjMQzI2rNWNT2nKRvLObUuGIArMLIKLoESSWTEABVcgcGjyxX0ZWq7Tq4UgnBg6IQiBQkRsqBw-Zcnn601o%2BwYgBs1tt9oliAAwjgFRJMy8pDQsHIyRqRAGgwEQ2Aw044xyETGy3yzej5gB2VP4u3ix19JQqGhl4Gg7XBllbeuGxvGuOogXzAAcXbFDvJ%2Bee9GHYArY6rE%2BhU-hUCbJvn5vmAE4V3bXj9mKp8%2Bh0CRt1qdZC9dEDcfEdzm-GC5dHEGI2t26aOvc6CPNyfoYruH6hl%2BpwNies7foBF5dN0oFpneD40FBMGbm%2BRZ7i41a1pUR7Ruhpznm2XQ3KBySpMwXz0AAKjQrAAOraDM24IeOuqThhqF-rGGEMYm8ydNiuHga8NCwFgKQACKIDg2jQQRpFMiJn5iSh071HoAEyVcASdEKoEDEQiQ-Jx0wTAQgaIGk0xksw-HwIJwp5CshlIcZOwSQ0Z78lh0SdFadmDMkPzaEQXxuiQzBksQ5DkhIEi%2BluwoWkF%2B6iYe4mmT45mRa2sldCm8VEAASogcA0PAvn%2BYKxUUQe4Y0d4EVzlFjExZ2DXKTIrBfDQIxSB1swBd1xS9XW5W-oN0nDbVMXLg1ABq-KEro8BWPN26BYhNbIWFFUbfRW1WS4nTXg1nBqXI%2BVHSkp3aH5C1dZdVERj%2BtH-tVCaPSIyzWn0uAWNpAKEs80AANaEjIqNmBIHFpDSG5YOgBXwaOgPXbCEmnkNNWQxAiw4fMkAAHKINKCP2swsoTJxeyaUl9ACflrwpP2yiqDY-ok8FV2heTFWU5t1MYoszEMwA0ogiDkI5zkTMkuOKP8gLzMJJVGWVJnrVVVMQ0rCkM-ZbnQRI0xnYtpMy%2Byct0SiD1K7ZDMZJMeDKZYBMTD5iBiH0CBGwkJs9aVfVraDUn3Yr8yLHFDOvNplj0G99AfS8GR5%2BlWDkpxsCseH6X5UJkumyF5s3b%2B8tpzbGf1dnOAEfQtdBGMLyWCLg687oAsFvX7nu83sut97sKWUrY0B9IjzMNHSBT5WCeQsYRTxD4EicHltgIaUQA)

#### Code

```fsharp
module Example

type Foo = 
    abstract member bar : int
```
            

#### Result

```fsharp
module Example

type Foo =
    abstract bar: int

```
            
#### Problem description

Member keyword is deleted. 

This may be intentional, is that the case?

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.0.0-beta-003

Default Fantomas configuration

**Comment by nojaf** [comment]
This is a bit historical I think. In short in case of implementation files, it will lead to the same compiled code.
From an AST point of view, these things are exactly the same construct.

Take for example:
```fsharp
module Example

type Foo = 
    abstract member bar : int

type Foo2 = 
    abstract member bar : int
```

```fsharp
ParsedInput.ImplFile
  (ParsedImplFileInput
     ("tmp.fsx", true, QualifiedNameOfFile Example$fsx, [], [],
      [SynModuleOrNamespace
         ([Example], false, NamedModule,
          [SynModuleDecl.Types
             ([TypeDefn
                 (ComponentInfo
                    ([], [], [], [Foo],
                     PreXmlDoc ((3,8), FSharp.Compiler.XmlDoc+XmlDocCollector),
                     false, None, tmp.fsx (3,5--3,8) IsSynthetic=false),
                  SynTypeDefnRepr.ObjectModel
                    (TyconUnspecified,
                     [SynMemberDefn.AbstractSlot
                        (ValSpfn
                           ([], bar, SynValTyparDecls ([], true, []),
                            SynType.LongIdent (LongIdentWithDots ([int], [])),
                            SynValInfo ([], SynArgInfo ([], false, None)), false,
                            false,
                            PreXmlDoc
                              ((4,19), FSharp.Compiler.XmlDoc+XmlDocCollector),
                            None, None, tmp.fsx (4,4--4,29) IsSynthetic=false),
                         { IsInstance = true
                           IsDispatchSlot = true
                           IsOverrideOrExplicitImpl = false
                           IsFinal = false
                           MemberKind = MemberKind.PropertyGet },
                         tmp.fsx (4,4--4,29) IsSynthetic=false)],
                     tmp.fsx (4,4--4,29) IsSynthetic=false), [],
                  tmp.fsx (3,5--4,29) IsSynthetic=false)],
              tmp.fsx (3,0--4,29) IsSynthetic=false);
           SynModuleDecl.Types
             ([TypeDefn
                 (ComponentInfo
                    ([], [], [], [Foo2],
                     PreXmlDoc ((6,9), FSharp.Compiler.XmlDoc+XmlDocCollector),
                     false, None, tmp.fsx (6,5--6,9) IsSynthetic=false),
                  SynTypeDefnRepr.ObjectModel
                    (TyconUnspecified,
                     [SynMemberDefn.AbstractSlot
                        (ValSpfn
                           ([], bar, SynValTyparDecls ([], true, []),
                            SynType.LongIdent (LongIdentWithDots ([int], [])),
                            SynValInfo ([], SynArgInfo ([], false, None)), false,
                            false,
                            PreXmlDoc
                              ((7,19), FSharp.Compiler.XmlDoc+XmlDocCollector),
                            None, None, tmp.fsx (7,4--7,29) IsSynthetic=false),
                         { IsInstance = true
                           IsDispatchSlot = true
                           IsOverrideOrExplicitImpl = false
                           IsFinal = false
                           MemberKind = MemberKind.PropertyGet },
                         tmp.fsx (7,4--7,29) IsSynthetic=false)],
                     tmp.fsx (7,4--7,29) IsSynthetic=false), [],
                  tmp.fsx (6,5--7,29) IsSynthetic=false)],
              tmp.fsx (6,0--7,29) IsSynthetic=false)],
          PreXmlDoc ((1,6), FSharp.Compiler.XmlDoc+XmlDocCollector), [], None,
          tmp.fsx (1,0--7,29) IsSynthetic=false)], (true, true)))
```

Notice that both `SynMemberDefn.AbstractSlot` are identical, so we don't have the information to make the correct call.

Now in case of signature files, this does matter (see https://github.com/fsprojects/fantomas/issues/944) and there we have a workaround [via the trivia information](https://github.com/fsprojects/fantomas/pull/967/files#diff-f8b6feeba094116ff19f14ce2465b71dR287).

I guess the same trick can be applied here for `SynMemberDefn_AbstractSlot`.

**Comment by knocte** [comment]
> it will lead to the same compiled code.

Then one could argue this is not a bug but a feature?
