### ISSUE TITLE
extra newline characters are unexpected

### ISSUE THREAD

**Issue by jmagaram** [fsprojects/fantomas#1119]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBtAPAMQIbQBcA%2BAXQB0AnMgOwBtECwADJgdwAtFqwl6DEwubgFUAcgGEAEgEFRAcQCiAETAVYrADSqGAVwrcAyrAC2AndWjshAc0TwwAN1y0diFmAAUASjABeSjQQEHyChDrOfgHcQTEARrCxYAA%2BRGBKuAS4AErqAHTmljZ2yanpmTmsubwMiFExIYgAHgAOiITFvmDxiSlpGdl51fz2vUamdUH4BOG0JWAAzuywOrT2iACOM2BNre3wUZAa4FDzDAQAltTW86hg6McQoDEQkAAkBACerbeQlwSHDyCbycLmQaHuzyCAAYjpCXgBJahIagEAznABeyFhcIALICICRAQBfbGPfFQd5fMFQP4AyHA5yuW4QuEARlJz0gAFlcI0ADKXRB8rjWAjsOlsgBMUPJhJiJMBT05lO%2BaEg8VgtAlMQZoOZ5Igko5OoMiGM5zgtFg1GkBAUSIA8gAzAXULEGsBO5ynWXEjlKnUq6nq2Ca7VA14gpngj0AZmNQIMzXwiAAQognbAKIgAAq4Ci4Uz8CjhmIECiuX3y-3kt6fVVQDVahO66N3D04hMvJMp9OZ7N89SICjQXCnREOWCji7W0tBcuVyFyoIKmIBiP14NNuet6ksyEAVi7UB70DTGaziGEzVaI7HiAnU4y51nx69tB9S79itrQZ%2B25bSNGT3D0ADZj0gU9z37RBxFoMd5nEa15gXQgsznCB30-Z5lwgVcgnXF4-zVADfyjEC4TAAB2CCoL7S8uTNWJhwwz1vUQKsVxreliMbUNmzI4D9UogAOWjkzPejsyQq1qFYrCOK-asfx4zd-34ncgL1GNKIATnElNpCdYskOMYxcFYhdFJw7811-NSSI0wDyOEtkYQ9SCJOgy9TXNS1Xw9BTOLw7jlQcviw2coSdLZdkPKgozi18i1NQCyirOCsB8LJVSqXUyLBO09tKNZI0PMRZECAdagABUKA%2BAB1c4xXk9jMuysBCIpcKQwKniXJiyFWXjeKvOkNRzHgJREFoc5zWLSyK2smJcKy0LAx62koqK-dnlZTsPJ5Rp4SdGrOGoBQP0QAwlgoAgmvgFrjxxGUlK4lSwrytUtsKttdpiVkj0O3lESdc5GgdW8MizBQWmzeZ5hfOTjwPV6bOUuzcobX4UU0gbirZcDgcaLI2izeAHqejs0ZW2yCPsr6aVx7a-o9VkaOJ8aCw%2BB0KAFFDKfFZ6aaCVaOq6utGZx-4WYotkxOJgA1YDU0ueBLmsQXWJe9r1o3KWfv66KCaG-TiewAoZ2oVWkQ1rXhd1j6Nql0ijZ2j1pQgrkVguWa3VTK1oAAa1TAtg4YeZqoMQtYM1HRjGRwK2rekKnf17HXeVfH-qCSU4soyBREQVg-fPAhWEQLgaqpaaweoZqkekJFGOMZiKBuN9k-R97Mc%2BjOnN%2BuXIUlMqC4AaUr5oTrOrhEWj0xXXdSigpTta06IzbmcH1zh5Ggujsu81Fnt6nHd753%2B76rPjZzw0DoLtErnocbrHjrh7sQWIuQQJe4RX7vU7n3TluAebtWaUUlEDAu0hZrWGoBbCwVs0RwIyHoRANVYAVXfs%2BNKf8u60wxvTLGICr6Bmzh7Im0DaDFmoM%2BBwQprTWBbm3WulwG7IValdM%2BRC%2B4kIEmAoezxJQcwfuWC0BBv5IEWouABWVjgkGxL8eY2BEa3CCkSIAA)

#### Code

```fsharp
[<Fact>]
let ``when delete an UNCHANGED row, return Some unchanged value`` () =
    let actual =
        bob |> DataRow.unchanged |> DataRow.delete
    let expected = bob |> DataRow.deleted |> Some
    actual |> should equal expected

```
            

#### Result

```fsharp
[<Fact>]
let ``when delete an UNCHANGED row, return Some unchanged value`` () =
    let actual =
        bob |> DataRow.unchanged |> DataRow.delete

    let expected = bob |> DataRow.deleted |> Some
    actual |> should equal expected

```
            
#### Problem description

in a bunch of cases Fantomas inserts extra newlines and I don't want them (or maybe you can explain why they are there). I don't see a configuration option to remove them.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 09/08/2020 18:11:08 - 75677b97fdabccfaddf3945cc8c9d9d94a43d4a5

```fsharp
    { config with
                StrictMode = true }
```

**Comment by nojaf** [comment]
Hey @jmagaram , Fantomas will add [blank lines around multi-line code constructs](https://github.com/fsprojects/fantomas/blob/master/docs/FormattingConventions.md#blank-lines).
As this is expected behavior I'm going to close this bug report, feel free to create [a feature suggestion](https://github.com/fsprojects/fantomas/issues/new?assignees=&labels=&template=feature_request.md&title=%5BFeature+request%5D) to further discuss this.
Lastly, please don't use[ strict mode in your settings](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_strict_mode).
