### ISSUE TITLE
Leave `function` keyword on same line as `let`

### ISSUE THREAD

**Issue by Elonon** [fsprojects/fantomas#1132]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBDMAvGAGYCuAdtFgJazkA6ATveRBAD5j2S7dgC0APjABGJizZhO3AEZ8hYAEzjWbTgH0BwgByQANOCgBnbDXIBzI6jABtQxFCSIkACRYAngAdkaSNXJY%2BvZsrgBuuOikPrbBkgAMBk4hAJLkSAEAytQAXsiJSWAALLFgALrBAL75DiWuHt7WfgFBSWERUdZ2BaLVTpAAsrgAHgAy-ogjiBZYABYtBSKKcSXlklXBjn1uXtGQMrCw6POSbZHRXQWKvScZiAC21HDodACCWACiaQDyxGPkeSUIMQIiYVpVepsTtsGr59odjiEXOEzp1AWAAMzXEIZTy4aCIABCiGIsEYiAACrhGLg7thEIwEZIsIwomC1hDatDdnCjljTh00BckoUsc4cXjCcTSRNYAB3enQXAmVKhWCKmh0RlsZmspKrNjrSSQxH1bkHXmc5ECmLdACsoqg4vxRJJZIAqp5vIxFcryKr1bRyFqgSDEGyDRzWlzGjytfzzmiAGwOyBOyWuxAAYXQSqMmboRh1VFJwZIofDEENbGNzmjsPNcaR7QT3QA7Cm0y7pf17jJ6aXgehQXrwRtOaaYw2%2BU2UYK0doO7jnVKyfnnkGHYPh059ZXI1sJ-X4dOrS2CgBORcSl7ELD0-N3O64Us6sMj9ljqOHqCxk-N1HdCICRoqmS7ptKtwPE8mqbuW74Rp%2BB47JOx6Wv%2Bc6ASIV74jed6MJBjyHDBaKvhWYBVjUX7IUeFpRqeAELFcIGpOkWBfOQAAqjDuAA6tQswDnBO6jka47UT%2BU5obONoLJiIFpi8jCwBQ8AACKIOg1APHhL4sm%2BwkfqJVEwlA-iBH%2B0lCk4IgiiBgxDMkxAcTMUzvEOiAZDMpJYHx8ACQ6hTLPBe6IVC35NOZUnWlZkgiPadnDKkxDUEMXxergWCku8QyeGSRhGIGpa2kFBkIUZSEmRFjb0RhCzJglQwAEqIHAjDwL5-looFZEUWANZQHWpnNBZ0VoiI7YNYp1LuF8jBjIWHVzAFJWSLu5H7mF4lVSNZ5JCIC4NQAas2BL%2BPA-jmItpbdcF62hSaW1mdV6EyXtl4NQAYhQVCBqdaQXVdy09RtD2Vb%2BUW7U4Swpv0pDoDQmn-ASzzQAA1gS1Jo9gRjsRkNJZocpB3BuaJbvpq0idWYlg5JdEvTFbCKFhIEAHKILKiOSlg8pTBxOzqcl5D8YGLxpD2dx9owViwe5wP3bW4Xg3TlloooTHdJAADSiCIJ4jnOVMqR47SfwAt0ZNy%2BVm2VU9O0MUkihyRr9luQ8RgzIDXUrWwa29f1dRbUrWw1a9UO2RrWQWJginmETUw%2BYgMj9AgZsFBbt1%2B9TZqocro3dIo8Uay8mnmOQX2UBq5BZKXGWkGSHGwCx8cZYVMvbhThlU8Z2e0cH9Oq-VRfw-S5At6EMoWOLksC-4wsFoJssZyDCuB7Tfcq-nE0R8yjxYMnSAL%2B3PuVIYpT5H4RgfQV1gWxUQA)

#### Code

```fsharp
let a = function
    | "a" -> 1
    | "b" -> 2
    | _ -> 8
```
            

#### Result

```fsharp
let a =
    function
    | "a" -> 1
    | "b" -> 2
    | _ -> 8

```
            
#### Problem description

I read the style guide and the above code doesn't appear to be breaking any rules. I guess this is a feature request.

Apologies if this is a duplicate issue, I searched them and didn't find anything similar.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 09/10/2020 21:17:15 - 56328470dbcf0d92e6f8110ede6d263751bff5b2

Default Fantomas configuration

**Comment by nojaf** [comment]
Hey @Elonon, at first glance this would be inconsistent with all the rest of Fantomas.
The expression of the let binding now is on the same line (if the length is below a threshold), or it is indented and on the next line.

On a side note, I prefer that feature suggestions are created via [our template in GitHub](https://github.com/fsprojects/fantomas/issues/new/choose). I've updated the online tool to make that more clear.
We keep can discussing here though ;)

**Comment by Elonon** [comment]
Oh, I'm sorry. 😬 I should have looked around more. I will use that in the future.

I agree that this is inconsistent with the rest of Fantomas, but I don't think it's inconsistent with any F# style guide and I do think it's idiomatic F#. It looks like it would have to be treated specially to make it work, but I don't think it violates the spirit of the project.

I am willing to help, though I am admittedly out of my league here.

**Comment by nojaf** [comment]
Hey, couple of remarks:

> I don't think it's inconsistent with any F# style guide 

Well, the thing is that there are two known F# style guides right now. Both are incomplete, to be honest, so if they don't mention anything that doesn't mean that they don't have an opinion on this.
In my experience, those guides only grow when people ask questions, so I would encourage you to open issues in both [Microsoft ](https://github.com/dotnet/docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%208c09996f-24ac-cf39-ef43-d7909cbc2b89%0A*%20Version%20Independent%20ID%3A%201efdd523-8552-6421-e149-74f76826ef8f%0A*%20Content%3A%20%5BF%23%20code%20formatting%20guidelines%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdotnet%2Ffsharp%2Fstyle-guide%2Fformatting)%0A*%20Content%20Source%3A%20%5Bdocs%2Ffsharp%2Fstyle-guide%2Fformatting.md%5D(https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs%2Fblob%2Fmaster%2Fdocs%2Ffsharp%2Fstyle-guide%2Fformatting.md)%0A*%20Product%3A%20**dotnet-fsharp**%0A*%20GitHub%20Login%3A%20%40cartermp%0A*%20Microsoft%20Alias%3A%20**phcart**) and [G-Reseach](https://github.com/G-Research/fsharp-formatting-conventions/issues/new) style guide.

I think a setting might be the most pragmatic thing here, as am I not sure how people would react to the sudden change. These things can be sensitive topics from time to time. Of course, a setting should be fleshed out before implementation. This determines the name, the scope and sets the expectations for the consumers.

> I am willing to help, though I am admittedly out of my league here.

That is very nice to hear. I made a couple of [YouTube videos](https://www.youtube.com/watch?v=UFUOYc22rkk&list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K&ab_channel=nojaf) that explain the codebase.
And I'm happy to assist you along the way.

**Comment by hvester** [comment]
Note that moving `function` to the same line as `let` would break the following valid code (if no parentheses are added around the function expression or match clauses are not indented to the same level as  `function`).

```fsharp
let inc x = x + 1

let f =
    function
    | Some x -> x
    | None -> 0
    >> inc 
```

**Comment by nojaf** [comment]
Thanks for pointing that out.

**Comment by Elonon** [comment]
Thanks for the information and feedback. I apologize, I didn't see these messages until last week.

My thinking is that this style is really only for quick "mapping" functions, and that normal formatting applies when used in function composition, etc.. Looking at the [AST ](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQ2wAuYAtgE9iAV2TMwAXkpjmPRK2QAdAE5LkECAB8wSyFT1gAtAD4wARlXrNYHXoBGh02ABMVjZp0B9Y2YAckCAAvkA) of the simple example vs. the [AST ](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQ2wAuYAtgE9iAV2TMwAXjAAdAE4zkECPDHMeiVsnmLlYAD6zIVGZDABaAHxgAjDqXLDpgEamL1gEz29hgPruwAA5vZUtrAApwgGoASlsYyBAAXyA) of the code noted by @hvester, it looks like I could apply this format to only the case where a `SynModuleDecl.Let` has a single binding of `SynExpr.MatchLambda`. 

I've watched the first video, have the project cloned, and plan to watch the rest. If I can make this work behind a feature switch, would you be interested in a draft PR?

**Comment by nojaf** [comment]
Hello @Elonon, I recently extended our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md) and the lack of evidence in any style guide makes this request fall under the category: [What are we not looking for?](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for).

I'm sorry to break it to you but I don't want to clutter the codebase with this. Please read the Contribution Guidelines to understand why I'm closing this. Thanks for understanding.

**Comment by Elonon** [comment]
I understand, thanks for considering.
