### ISSUE TITLE
Generics error when breaking line

### ISSUE THREAD

**Issue by fc1943s** [fsprojects/fantomas#1134]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAyogE4BuAltIgM5gC8AOsQwHYQQD0XYAQluTni0AhoQAuxRMPRgASjVg5S%2BAGZYW0MeVhthABz3FYh8sLH4xsMGIAW%2BapclgARonIsA5mCzVE8Jqzs1gCeevgEElLo8tSKysQAFA6wxMIeiGgRKWmIAHQAkiwOwhqIAJT0AWxB7OiI6K7EYAD6zbkxcYhVNT1gCd29g3BI0GgAYtQAwgiI0AUAososYtMjADwA5IhLYgA0LsHmYADaALr7zQB8uwODPSqK8GgJG8VHALSXYFs7YL4AjmBPt83uUbsxqncau5yFphDg0K8xGZEODAlCatQWPpqDZYGJni9tohlkCvs5YIoKgAqPpIlFk77E5ZlMq3O5siEYypcjHoMzQGx-Rw5MAAd1hNnZgwAPuJsulcgBZeopYJZJzJJyfaUY%2Bb-fgsWAAD2VquI6sceQ6ShISSt%2Bwmq1muR4Jtyzrmk0kKISZX2D0E%2BxhcJwZXaCltup6co1OVyixJYg1%2BASHhRYuEwX20GEgvKZOjdzwYjAeao1GoEVS5g8wR56O5PX1hvdieWKdyAEFoBWqxIUXX2oocO4PARsXpcfjaFicXixFUi4MS2Bc-nq4P64xeU2ai33G2dp3JnmbGPN7XgrkCKP4GOAOrueCwMUJdd2fYAFXIdQIehKXIxiMdAlXcLBzFoAAmAAGXJOVYZdegPI1TXbZMrQjWJbWITZmT2EFkXMC5LjTDMsxzGZoADR5gxYWFTBwHMz0QS9EDrfZyxofsa3Y4JwxtZQqkgXZwCgXwxC0TxqFQE4xIgUAekgAASMRQmQNBIHcMQRPk9gVNIeEsA0uTBhg0TBkgQokA7cgAC9kAs3oABY9IgU49IAXychS3KgVT1NkrTll0pTlMMnBjNk44-IgABGHyakgJVhGNAAZdxEDSkkPFsULeji2C-I8oJvL0xSkoCsIgopRR8qCAyjJMmLBigxKGqIdBKEUHQuzEeYWHgAB5FQMpYRzYrAFR4V8YqvMSiqGqqkzIFqnB6v08KmuiyaAGZ2v0-880QHhEAeSQAAVhFSOpzGIDaggkYy5tKha-JUtTqs0taHv8iKorQFqXIOiBICOqhTvOrLXxIXNfEKUhYFzLQdF%2BiAnsQF72DKoJFs2z6Vp%2Bg7Gsi5rJoAVhBqBwZOs6UkQABVAxYeEeGWER5HtBYNGppmzGehK7G3rCgmaspdbia20mdsGAA2KmwYAiG6ckSYcFZqYdAcYgsE0FIeemnBZoF%2Bbyve5axbqyX-rJwYAHYFZpyH6ZVBoSANvmsYgHH2Dx0GLe%2B8XfpJgHTN6AAOR2ldpqHphwVGqcN42akF73hcq0XA6t82bZl3oAE4o%2BOrsVDu6Z0H5HmMa9sAfd8kXAqziWc%2B2wHJri8zJsV47nckTruvj7nE89k3XrNhuvqgImW%2BltvBjihKu5pku7v7uBB6rnX%2BZT03cfNzOp6D63W7DnpCoV6ykyGlgvwtJ88uHo3t6CVPa-TpaD9Wo%2BZ9DoGz-2pe0cuxGHUPAAAIogUcXU7qb2eqPIW48M6NygNpYOUtf7t2cgrFKxp8gqC-HYFg8wn4EDxMQMQT54AP0ms5GCNc65gD9v5T%2BqDj6z1PjUOKlMu44MKCocgxohphBrCkeYxpDDcS5jzcmdD4Fp0QR-ZBwUdJsIwfPeWPDUryDgMQeAlDqGDFofQ9%2B%2BMlGsJ-rbAqDtNHGmAakYIQ1iAZQcPomwPMjFyLfgo0xk9lFoNznPAqkcbEADUmo8GfI%2BcgVC3FUw8TvMee8J4rXMWFAJHCghxULjYsY6hNBcwiYNKJMT3GyISQgpJSDfHTzSSfP%2BNRYLYNwFoUc40eDx2gAAax4KkLpiAxDUGvgQaQiA45YHQEPSaSdn7sFfgwphH0lE1Mquk%2BpQQoKL0sgAOUQGKVptMxBikQCSL86kIH8PoijFgXZBqu0aDJR%2BycX6719vvJZ39ansLWewKCbUu4AGljl6DwQQkkhRhl1DGhNQY0zjHeP9iwkKqjLE9CggAyyODiFdVxK40pcLKmKOqR8lZdTJpQSwUvMceBgEeHGUmB8iBnBKhmB7J%2B%2BLXnJMts3T5ajehQW4ZZLso4PAsFyRoK5BByAirMFgSQX5YCX2WGYKRjyZnuRefXKphNiVLVWWSjRgqcB3WxFoZQaUdAeDuSQc5IYuYPKmSPcp8iCU%2BO1dnHlKKGnWMstWSgYhmVIFZU82ZXkxLnDElpagExyCyVhZ5IAA)

#### Code

```fsharp
module Services =
    /// Builds a Stream Resolve function appropriate to the store being used
    type StreamResolver(storage: Storage.Instance) =
        member __.Resolve
            (
                codec: FsCodec.IEventCodec<'event, byte [], _>,
                fold: ('state -> 'event seq -> 'state),
                initial: 'state,
                snapshot: (('event -> bool) * ('state -> 'event))
            )
            =
            match storage with
            | Storage.MemoryStore store ->
                Equinox.MemoryStore.Resolver(store, FsCodec.Box.Codec.Create(), fold, initial).Resolve
            | Storage.EventStore (gateway, cache) ->
                let accessStrategy =
                    Equinox.EventStore.AccessStrategy.RollingSnapshots snapshot

                let cacheStrategy =
                    Equinox.EventStore.CachingStrategy.SlidingWindow(cache, TimeSpan.FromMinutes 20.)

                Equinox.EventStore.Resolver<'event, 'state, _>(gateway, codec, fold, initial, cacheStrategy, accessStrategy).Resolve

```
            

#### Result

```fsharp
module Services =
    /// Builds a Stream Resolve function appropriate to the store being used
    type StreamResolver(storage: Storage.Instance) =
        member __.Resolve(codec: FsCodec.IEventCodec<'event, byte [], _>,
                          fold: ('state -> 'event seq -> 'state),
                          initial: 'state,
                          snapshot: (('event -> bool) * ('state -> 'event))) =
            match storage with
            | Storage.MemoryStore store ->
                Equinox.MemoryStore.Resolver(store, FsCodec.Box.Codec.Create(), fold, initial).Resolve
            | Storage.EventStore (gateway, cache) ->
                let accessStrategy =
                    Equinox.EventStore.AccessStrategy.RollingSnapshots snapshot

                let cacheStrategy =
                    Equinox.EventStore.CachingStrategy.SlidingWindow(cache, TimeSpan.FromMinutes 20.)
                Equinox.EventStore.Resolver<'event, 'state, _>
                    (gateway, codec, fold, initial, cacheStrategy, accessStrategy)
                    .Resolve

```
            
#### Problem description

Please describe here fantomas problem you encountered.

Before:
![image](https://user-images.githubusercontent.com/688618/93007733-8bc7df80-f542-11ea-8344-169a440575d0.png)

After:
![image](https://user-images.githubusercontent.com/688618/93007738-9e421900-f542-11ea-9026-4ba497cacc2c.png)

![image](https://user-images.githubusercontent.com/688618/93007741-a9954480-f542-11ea-8c72-ed3542fd92bd.png)

Source code:
https://github.com/jet/dotnet-templates/blob/master/equinox-web/Web/Startup.fs
(dotnet new -i Equinox.Templates --> dotnet new eqxweb -t -e)

EDIT:
If I remove the generic type alias the formatting stops breaking the line, but still crossing the configured 120 limit
![image](https://user-images.githubusercontent.com/688618/93007881-6045f480-f544-11ea-81ff-e42639c58b3b.png)

Does the configuration options support something like this?
![image](https://user-images.githubusercontent.com/688618/93007879-57edb980-f544-11ea-8477-cb6999bc1cdd.png)

#### Extra information

- [X] The formatted result breaks by code.
- [X] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 09/10/2020 21:17:15 - 56328470dbcf0d92e6f8110ede6d263751bff5b2

Default Fantomas configuration

**Comment by nojaf** [comment]
Hey, thanks for reporting this issue. It rings a bell 😅.

> Does the configuration options support something like this?

No, please upvote https://github.com/fsprojects/fantomas/issues/501 for this.

Lastly, you might be interested in the [fsharp_alternative_long_member_definitions ](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_alternative_long_member_definitions) setting.
