### ISSUE TITLE
Unable to format the code

### ISSUE THREAD

**Issue by captain-yossarian** [fsprojects/fantomas#1144]
Hi, I'm unable to format the code.
![fantomas](https://user-images.githubusercontent.com/16646733/93662358-d627ef80-fa5f-11ea-9ca5-cb9360635433.png)

![error](https://user-images.githubusercontent.com/16646733/93662432-50587400-fa60-11ea-9fdf-c66d8fafdaa7.png)

After I click Format Document - nothing happens.

There is no option: **editor.formatOnSaveTimeout** in VS code editor.

**.NET info**

.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**VS code verion:**

Version: 1.49.1 (user setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by captain-yossarian** [comment]
Sorry, wron repo

**Comment by nojaf** [comment]
Hey, maybe not, Fantomas cannot format incomplete code. The code doesn't need to compile but the syntax must be correct in order that Fantomas can reformat it. The extra spaces on line 9 in the first screenshot seem to indicate just that.

**Comment by captain-yossarian** [comment]
@nojaf Hi, thanks for fast response, I thought fantomas should handle extra spaces.

**Comment by nojaf** [comment]
No, the F# compiler can't actually, so the way Fantomas works is that it uses the compiler to create an Abstract Syntax Tree and it transforms the tree again to text. But due to the extra spaces, the compiler cannot make the tree Fantomas needs.

[Example](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQC27ArjbDABZKijABeADoAnScggQBAFzBoAjryrTBADwlg9AKgMy5ChQAdpKJfHmTIyXlwBGsaWACkiB2AAsAEyQIAC%2BQA)

**Comment by captain-yossarian** [comment]
@nojaf thanks for explanation. I'm new to F# but want to learn it.
Have a nice weekend )
I'll close the issue
