### ISSUE TITLE
Don't break records update expressions if not needd

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1152]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBnbASorrAK4BO0iAMgJYB2A1gJLxgBuAhuqYmABSdyAc1xoAKp1yMAyoiHQAFgEERuAJRgAvAB1yO%2BhGBghosAHdaWRWCIkKVOk1bawM2AFs%2BXHnwC%2BkAA04FD4WFgMoqhgANohRvEQUAAkWACeAA7IaJAMWEGJEJDJPrzRcUmVYAAMwVVJkMz0SPRYMrQAXsh19WAATIVgALqJfj0J9cXpWdG5rQWTJdxlaBW9AIzjVZAAspwAHk40iPTC1gu9AJzVgyOVY4mgi9PZUABGsLDoF5XFpa9rep9La-OQeWhwdCwejKLAAUWaAHkAGZHH5VZHcfC3UZbJ7bVKZV6QD5fdFFJa%2BcqDCAAZhBDRkGU4VAAQohkbByIgAApCTheLCIcjkpJYci8HH3PGDKZE2ak74Mv7LAE0sAAFgZRSZLMQ7M53OosHMwugUkQTXYsHNEWhoog4sl9TuSQelXxv0JMxyitFKqpq3VAFZtVBdWyOVzEABVDJZSgWq02zh2%2BgOsCY9DYl24x6y73Ev3KykrWLqgBsYcgEf1Ue5AGF0FJcA3obgndAsFyM1mc1VXRB3UlPQ1CwrPkqC-9qb0wAB2au1g3RnaIDxvYW9rGIKVumXPeW%2Byf%2B0tqucADiXzMjhsQbah6bDfd3uel%2BcPPveJ5LM6Dc8ua89WUZEhXINsPA8TgMydV8BzzD0CxeCcyV-VVZw2Wp1RrG86zvMEIS%2Be1nx3PchwPAlkOPVDp3Q-8Nk2bDaxAsCCMhYj1VgsiwGHCZKKPb8aMWP9yzndZgWwpoWiwRF6HEcg0gAdSsRRt2zODKkHHiKK9KjBKnYS6NEjZ6SY3DVDIZoABFEHQWhwTAmCJQ0pItN4sBRwpPS5nyNDA2M%2Bp1i1bC9n2ZhkXERQTjhdSZEULksGU%2BBzjDDUbjffcP34r8fNPETASqdZQxCg4mmRWh9kRBNUy5OF9gyblcFwWgOLnYN0vg99EM-Yk8jyoyCsqdYqxK-YiDgch4CSlL1TS7j3M8lJvL6vyy0GpJ1kXUbVHITg0kRcg6A7abVNSjrNIQkckIE3LVvPDYr1GgA1VVWQYeBIhOjM5oy8ist0m6Vto-z1ogdZANGgAxUh6C7Fr6De5pPtoZLTtm87XMuviAZyoHDJB9U%2BiwuddgOKzYCwABxbA6oa4hmuhL6w3a%2BadLHbzi2BtbCcYkmdlIdAIjs%2Bh9ShaBGFZXbxewXBZJkAV7y%2BUgPCfdUX1Z-72Zuzn8e5uc%2BgkkmADlEHMYW6ywU0TnEIkbPK%2BgrHh5RmjXDdhVwNT%2Bwurqrp6lCDIJfLCdMkmAGlEEQDJwsik4mnlrw0RI9SNe67LevmO6MKBYK%2BYOGLwVwRQmfRlPfbT-3%2BoJ-XipJ9pTkwVRhGVk5EsQN4dgQbo1dI37tM1rztZ-Ln7qBEaSeUOzhHoaHYbTdop9TChEHEWApJb1N4c9lyIDctmB5ynXA4GwmtvHwXhXoDf2BoaFhFdzdyDthhHfbLfS%2BxrWD6H3WR6qPpHtruKCEWAO5IDfr3PwIQhg9FyLgSGzVojqz8EAA)

#### Original and expected

```fsharp
let setResourceLinkId value (args: TaskSearchArgs) =
  { args with ResourceLinkId = Some value }
```
            

#### Actual result

```fsharp
let setResourceLinkId value (args: TaskSearchArgs) =
  { args with
      ResourceLinkId = Some value }

```

I suggest not breaking record update expressions if only one field is updated, and the whole update expression fits on one line.

**Comment by nojaf** [comment]
Increase [fsharp_max_record_width](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBnbASorrAK4BO0iAMgJYB2A1gJLxgBuAhuqYmABSdyAc1xoAKp1yMAyoiHQAFgEERuAJRgAvAB1yO%2BhGBghosAHdaWRWCIkKVOk1bawM2AFs%2BXHnwC%2BkAA04FD4WFgMoqhgANohRvEQUAAkWACeAA7IaJAMWEGJEJDJPrzRcUmVYAAMwVVJkMz0SPRYMrQAXsh19WAATIVgALqJfj0J9cXpWdG5rQWTJdxlaBW9AIzjVZAAspwAHk40iPTC1gu9AJzVgyOVY4mgi9PZUABGsLDoF5XFpa9rep9La-OQeWhwdCwejKLAAUWaAHkAGZHH5VZHcfC3UZbJ7bVKZV6QD5fdFFJa%2BcqDCAAZhBDRkGU4VAAQohkbByIgAApCTheLCIcjkpJYci8HH3PGDKZE2ak74Mv7LAE0sAAFgZRSZLMQ7M53OosHMwugUkQTXYsHNEWhoog4sl9TuSQelXxv0JMxyitFKqpq3VAFZtVBdWyOVzEABVDJZSgWq02zh2%2BgOsCY9DYl24x6y73Ev3KykrWLqgBsYcgEf1Ue5AGF0FJcA3obgndAsFyM1mc1VXRB3UlPQ1CwrPkqC-9qb0wAB2au1g3RnaIDxvYW9rGIKVumXPeW%2Byf%2B0tqucADiXzMjhsQbah6bDfd3uel%2BcPPveJ5LM6Dc8ua89WUZEhXINsPA8TgMydV8BzzD0CxeCcyV-VVZw2Wp1RrG86zvMEIS%2Be1nx3PchwPAlkOPVDp3Q-8Nk2bDaxAsCCMhYj1VgsiwGHCZKKPb8aMWP9yzndZgWwpoWiwRF6HEcg0gAdSsRRt2zODKkHHiKK9KjBKnYS6NEjZ6SY3DVDIZoABFEHQWhwTAmCJQ0pItN4sBRwpPS5nyNDA2M%2Bp1i1bC9n2ZhkXERQTjhdSZEULksGU%2BBzjDDUbjffcP34r8fNPETASqdZQxCg4mmRWh9kRBNUy5OF9gyblcFwWgOLnYN0vg99EM-Yk8jyoyCsqdYqxK-YiDgch4CSlKQw6zSEJHJCBNyvyy0GpJ1kXUbVHITg0kRcg6A7abVNSubXIWvjdOWvrVvPDYr1GgA1VVWQYeBIhOjM0u49zPJSbzbto-z1ogdZANGgAxUh6C7Fr6De5pPtoZLTvVH6MvIrLrpyoHDJB9U%2BiwuddgOKzYCwABxbA6oa4hmuhL6w3a36dLHbzi2BtbCcYkmdlIdAIjs%2Bh9ShaBGFZXbxewXBZJkAV7y%2BUgPCfdUX1Z7H2eWzn8e5uc%2BgkkmADlEHMYW6ywU0TnEIkbPK%2BgrHh5RmjXDdhVwNT%2B3mrrFp6lCDIJfLCdMkmAGlEEQDJwsik4mnlrw0RI9SNe67LevmO6MKBYK%2BYOGLwVwRQmfR86IDctmvO1n8ufuoFipJ9pTkwVRhGVk5EsQN4dgQbo1dIzHtM1yucp1wOBsJkaSeUOzhHoaHYbTdpZ9TChEHEWApPb1N4c9lyy8ujylpH6vddrqo%2Bi2qfBeFeht-YGhoWEV3N3IO2GEd9td5T320-9-qCf1o9Bu4oIRYG7kgL%2BA8-AhCGD0XIuBIbNWiOrPwQA) or checkout #1143.

Please also don't use the online tool to create feature suggestions.

**Comment by cmeeren** [comment]
> Increase [fsharp_max_record_width](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBnbASorrAK4BO0iAMgJYB2A1gJLxgBuAhuqYmABSdyAc1xoAKp1yMAyoiHQAFgEERuAJRgAvAB1yO%2BhGBghosAHdaWRWCIkKVOk1bawM2AFs%2BXHnwC%2BkAA04FD4WFgMoqhgANohRvEQUAAkWACeAA7IaJAMWEGJEJDJPrzRcUmVYAAMwVVJkMz0SPRYMrQAXsh19WAATIVgALqJfj0J9cXpWdG5rQWTJdxlaBW9AIzjVZAAspwAHk40iPTC1gu9AJzVgyOVY4mgi9PZUABGsLDoF5XFpa9rep9La-OQeWhwdCwejKLAAUWaAHkAGZHH5VZHcfC3UZbJ7bVKZV6QD5fdFFJa%2BcqDCAAZhBDRkGU4VAAQohkbByIgAApCTheLCIcjkpJYci8HH3PGDKZE2ak74Mv7LAE0sAAFgZRSZLMQ7M53OosHMwugUkQTXYsHNEWhoog4sl9TuSQelXxv0JMxyitFKqpq3VAFZtVBdWyOVzEABVDJZSgWq02zh2%2BgOsCY9DYl24x6y73Ev3KykrWLqgBsYcgEf1Ue5AGF0FJcA3obgndAsFyM1mc1VXRB3UlPQ1CwrPkqC-9qb0wAB2au1g3RnaIDxvYW9rGIKVumXPeW%2Byf%2B0tqucADiXzMjhsQbah6bDfd3uel%2BcPPveJ5LM6Dc8ua89WUZEhXINsPA8TgMydV8BzzD0CxeCcyV-VVZw2Wp1RrG86zvMEIS%2Be1nx3PchwPAlkOPVDp3Q-8Nk2bDaxAsCCMhYj1VgsiwGHCZKKPb8aMWP9yzndZgWwpoWiwRF6HEcg0gAdSsRRt2zODKkHHiKK9KjBKnYS6NEjZ6SY3DVDIZoABFEHQWhwTAmCJQ0pItN4sBRwpPS5nyNDA2M%2Bp1i1bC9n2ZhkXERQTjhdSZEULksGU%2BBzjDDUbjffcP34r8fNPETASqdZQxCg4mmRWh9kRBNUy5OF9gyblcFwWgOLnYN0vg99EM-Yk8jyoyCsqdYqxK-YiDgch4CSlKQw6zSEJHJCBNyvyy0GpJ1kXUbVHITg0kRcg6A7abVNSubXIWvjdOWvrVvPDYr1GgA1VVWQYeBIhOjM0u49zPJSbzbto-z1ogdZANGgAxUh6C7Fr6De5pPtoZLTvVH6MvIrLrpyoHDJB9U%2BiwuddgOKzYCwABxbA6oa4hmuhL6w3a36dLHbzi2BtbCcYkmdlIdAIjs%2Bh9ShaBGFZXbxewXBZJkAV7y%2BUgPCfdUX1Z7H2eWzn8e5uc%2BgkkmADlEHMYW6ywU0TnEIkbPK%2BgrHh5RmjXDdhVwNT%2B3mrrFp6lCDIJfLCdMkmAGlEEQDJwsik4mnlrw0RI9SNe67LevmO6MKBYK%2BYOGLwVwRQmfR86IDctmvO1n8ufuoFipJ9pTkwVRhGVk5EsQN4dgQbo1dIzHtM1yucp1wOBsJkaSeUOzhHoaHYbTdpZ9TChEHEWApPb1N4c9lyy8ujylpH6vddrqo%2Bi2qfBeFeht-YGhoWEV3N3IO2GEd9td5T320-9-qCf1o9Bu4oIRYG7kgL%2BA8-AhCGD0XIuBIbNWiOrPwQA) or checkout #1143.

Thanks! I totally missed that setting.

> Please also don't use the online tool to create feature suggestions.

Got it! May I ask why? I figured it was nice to have a simple demo/repro, which is why I chose to do it that way.

**Comment by nojaf** [comment]
> Got it! May I ask why?

Well the feature template forces people to check with existing style guides, think about the effort necessary and whether this is a breaking feature.

A small issue report like this one is really perceived as "hey I want stuff", the feature template has more of a "I thought this through" vibe.
