### ISSUE TITLE
Allow trailing semicolon on last item in list/record

### ISSUE THREAD

**Issue by lydell** [fsprojects/fantomas#1161]
I propose we allow a trailing semicolon on the last item in lists and records.

The existing way of Fantomas deals with this problem is that it only allows semicolons for non-last items.

## Pros and Cons 

The advantages of making this adjustment to Fantomas are:

- Making code easier to edit. When adding a new item you don’t have to think about adding a semicolon or carefully lining up the indentation.
- Less git diff. It makes pull requests cleaner and reduces the risk of merge conflicts.

The disadvantages of making this adjustment to Fantomas are – none, I think!

It’s common to allow trailing commas in lists and records in JavaScript and Python.

## Examples

Options:

```
[*.fs]
fsharp_semicolon_at_end_of_line=true
fsharp_multiline_block_brackets_on_same_column=true
```

### List

Input:

```fsharp
let someList =
    [
        ("insurance", encodeInsurance insurance);
        ("reason", Encode.string reason);
        ("revoked", Encode.bool revoked);
    ]
```

Output (notice no `;` on the `revoked` line):

```fsharp
let someList =
    [
        ("insurance", encodeInsurance insurance);
        ("reason", Encode.string reason);
        ("revoked", Encode.bool revoked)
    ]
```

### Record

Input:

```fsharp
let someRecord =
    {
        event = event;
        questionId = questionId;
        payload = payload;
    }
```

Output (notice no `;` on the `payload` line):

```fsharp
let someRecord =
    {
        event = event;
        questionId = questionId;
        payload = payload
    }
```

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: n/a

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [?] This is not a breaking change to Fantomas
* [x] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Hello @lydell, I haven't been very responsive when it comes to your suggestions, for that I apologise.
 
For this issue, it is really hard to tell if anyone is actually using [fsharp_semicolon_at_end_of_line](https://github.com/search?p=1&q=fsharp_semicolon_at_end_of_line&type=Code). So that might be an argument to just change it until the next person opens an issue that they don't like this change.

As no style guide mentions this setting, it is one of those things I would rather remove altogether (don't worry, no immediate plans). There is just very little buy-in to have this from my maintainer point of view.

I hope you can understand my position a bit.

**Comment by lydell** [comment]
> As no style guide mentions this setting

I think this is because F# seems to favor “beautiful” code over code that is easy to edit.

When we found the `fsharp_semicolon_at_end_of_line` option at work it was a godsend. It makes lists and records so much easier to edit and copy-paste!

I assume you have code like this (pseudo-code):

```
if last then
	output nothing
else
	output ";"
```

I suggest changing it to:

```
if last and not fsharp_multiline_block_brackets_on_same_column then
	output nothing
else
	output ";"
```

In other words – if `fsharp_multiline_block_brackets_on_same_column=true` then output trailing `;`.

**Comment by nojaf** [comment]
While still having very mixed feelings about changing this, I guess the change in scope to the multiline expressions (where ` fsharp_multiline_block_brackets_on_same_column=true`) could be deemed acceptable.

I will allow a PR that covers all the following cases:
- arrays
- list
- record types
- record types in signature files
- ...

**Comment by nojaf** [comment]
I'm going to close this as it falls under [What are we not looking for?](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for).
There is no interest to pursue this.
