### ISSUE TITLE
Lambda argument splits in awkward way

### ISSUE THREAD

**Issue by reinux** [fsprojects/fantomas#1164]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBLAdrjgLwA6ATqfhAIbzwAiNWiAKrgLaIDCs%2BAbonItKlahDAAKAGYBXavBwBaAHxgmLSYoB0ATUQ1yAGjA6AsnywALEzqYBPAJSOKVCVLnVJGxFPsmOW2cwVVdxdwBlewBnFg5tH3YuSX8wQNNnMMgjcCho7CwCAHNo1DAAbVyIUHcISAASLHsAB2Q0SAIsbKqJBv4adFk2ip73AAYc2t6ASXwkfCwI3AAvZEmpsAAWUbAAXR6AX3XqnYam1rKOhe6pvoGhssqNsABGY9rIMxoADwAZAkQv0Q%2BCK1huGwAHABWHb7dxHHo1D6NFrDSAAI1gsHQ4Pcd0GwyeGwATO88RFEBxcHB0HwAIJYACicwA8tJ-vg1jsINIBvlYYd3ki8SiLu1Mdjcb16v0CY9uWAAMxk3oRZo0aCIABCiGksHIiAACoYaFwRFL3FhyEMBfChadRWiJTiVfiHmgiVNNiq6mqNdrdfrAbAAO5CaA0fKzfiwCOFPgWiRWm1TOESBHuYXS85OrEuh2y90jZ5Qn1QP2anV6g0AVWarXIEajAljzFwCbLvPQ-NTgsRDpzl2dibdhIVADYy5AKwHqzx0JHorx8LFrdAsPrEzy%2BYhben7bdHUO8yOZfcx88AOxTmdVoNmSnooRbsBdnu1NMQDMSLN1I-ik9XTPOUPQVCEb3VStAwNXhaXwF8313Xs7X7Q9BwAyUgMLC8NgATgg-06WkEReA4DgaBfZMkI-PtMwHVFj0wgtz3lZ4XgmBVp0g2cgwpKkaQ7BVEL3L8D2RdCoGHLCWNAti3k4mciJEPjqWxQTniokSwG-E40IYjD80PbDWI2F5SU42Z5iwFl8FYch7AAdSIKwEJ3LSdLAX8oH-STAOYkDi1M5UFO4ulyFgeRGEQdBOCIZ8y005D91Q8T9KgTpT2M2TTO9Tivm%2BaZpFYKxgUZbtEAiKx9SwJzFBcstNjGdyxJFCSri6aSAs9WoXlLPKflmaRcG%2BFkG2YfVGW%2BZoDWiaJ23gssoSapLRJS1q0vazKZMCqYXknfrvgAJUQOByHgWqwQa5aaJQui9LFdLrk6otuvcF5rwOsLyBoewWXIf5Ygu%2BqFUa5q1uzDaMuenDdvAg6ADVzy1Ah4GKIGX1BlbtJaiGHs26GTN2-CDoAMXkdd5uRuY0dwOqMeu9xP2x8G-zaqH-JehViQ455Ph%2BBhYCwABxbBJumxBZvm9HFoZiQmY8ryzg2qSOZh2piXk3mzFkdBChizktVpaAAGstW%2Bk3sGiGyIlNHhsVkDgFqEtysYV%2Bi8ZVoztteiRiXM3mADlEBDfWAywMNgVYVEGF1AgiHmuk5gfDgn3IUpOxdm7kru1KPb8r2uq54LeYAaUQRBmkK4rgVmG2uA5LlnmE12cdZyGntVwn1dyrWfjKqloisaWQdliB5db7y2s95Esp29W%2Bt5pYQUwMKigd4EasQdELCQVzyrBnP1rzpiC8555iX23m6Riop8DJ-AKb4JZb%2BYWQDVYWBLI3tt1I2Zus9WofXGuYT4z29lzD6V9dZCHwG2QQvw%2BBFGTqnGOQ1CDxhXHvd8jNaI-ndiAwyYDC7nzhovK01IsA70bn-TOOD4S5F2OsDo0QSZzTKMJA4QA)

#### Code

```fsharp
let init =
  addDateTimeConverter
    (fun dt -> Date(dt.Year, dt.Month, dt.Day))
    (fun (Date (y, m, d)) ->
      System.DateTime(y, m, d))

```
            

#### Result

```fsharp
let init =
    addDateTimeConverter (fun dt -> Date(dt.Year, dt.Month, dt.Day)) (fun (Date (y,
                                                                                 m,
                                                                                 d)) ->
        System.DateTime(y, m, d))

```
            
#### Problem description

I'm not too sure what the condition would be to make this work right. Maybe when there are multiple curried arguments and the lines can be split more cleanly between them than by having them all on one line?

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 09/25/2020 16:37:27 - 27af638582040e0328a4b079d263d62fc771bfca

```fsharp
    { config with
                MaxLineLength = 85 }
```

**Comment by reinux** [comment]
That was mega quick. Thanks!

**Comment by nojaf** [comment]
Well, it helps that [code changes](https://github.com/fsprojects/fantomas/pull/1168/files) required for this were minimal 😉.
