### ISSUE TITLE
Multiline SynPat.Record in pattern match is formatted as a mixture of single/multiline styles

### ISSUE THREAD

**Issue by Fizzixnerd** [fsprojects/fantomas#1173]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbAhgF2gCzADNZYwB3AS2zwB0A7AHzGDACFMAnMAXjACNO9CBAAyiAG6IANjzABGAExDhANQp9EAZ1kAHKYjrYAnstGwOidLJqQR5y2Ao7NAVyvxYU82E1UwmdERsABowODpNRGhsIJcuTHgnCk1oCjoAczBpKlDI%2BDAPLIoXTXQEMBj0HW801MT4F0MwF2wwKUw%2BeyzWjy8LMCx0ukx-KQoARxdMADowGzAAXzAAWgA%2BUznIAHYbeiYAfRXVzYAOXbpIYPAoSOxsNPTNVDAAbWuIUGFhSAASYx1kGhIGlsJd3t8fuJMFIXIDXuCvgAGK5fL6QACSdCQhgAyhQAF7IFGoiAAFgRYAAuuCFsSPhTfv84cDDGCSb8oTC4W8SRA5HTUZAALKYAAeIjSiDEGWobN5ikRFOpX1p4M%2Bgr%2BRgBz0gnU8crRkOhsOePN5CgFaJxlgocC8dAAgtgAKJYgDyhAldCJFIghGhkSVNIF6sNTJ1eqkBohnJNaDNJIAzJbvjidJhoIhWIhiBYAAqcAJBRAcaNfbAcWFBlUhhma7VAyNlqBGrmm31gUkpiCQNMZrM5%2Bx2Mgl6CYSKY8SwMf3WAXbsVSuIavCVVfUMQ8ONkhRlMc43cjsAVgXvfTmezucQAFUdACOGOJ3QpzOKHPm36A8uScrV7X2fWzJNnurZxvCvJgAAbKefYXoOFgAMLtJomgIXOmgVi40TmB%2BRBfiuEBrsIG49oBEY7s2%2B5tvGHZbDB54DleQqWBopYLv6UiBj%2BwZqnWW5QMBdaxoeEEnPR-aXvYaH2rhHFcaiv6Ef%2BGr8bqFEgcJ7YQQAnOJmYOoQMQcGh6BYLhmHfgpPHrnxWpAepQkHlp8rIh2Z4SfBiDWugtqeO%2B7H4dxNa8QBqmCQBmk0RBcj8m5sGIAZRneb5MkLhZBGLMpYZ2eR%2BoaU5UXyhabmYti2BunQAAqHBGAA6lQeCyYFVnBTZoU5dueWOdR4HysmcUMQ6HCwI08AACLZD5RnmUuGVEfS7UNlAIKUaBInyl2bkiqK6KEJVeAGM6nFeXg5jYPV8CygupKKkFf4hSpHXLay%2BU9QmqJyCeW1ipihAUKKbr3jg5jOqKOgWChb7zset0tfdbWPUtLKgq9YHvV8cjQd9ooAEpROY8AXVdHY3XNWWbk9yOrZFvUknIdHY0NHCYEYbocBKGFE4112w18imZQ92VIytqPrXTYmMxwzOs%2BzyTYAAcm4rEeuilRPAuchk4LFNI%2BgLhSPcYzegAYuYWB3CWlU5aLzl07pblMyzbMc9gQr64bkqmxw5vTae%2BCFtEJb7JQl2NVrCNC8yIvdWjHYKK5EHCmKKgHqwaSJBkXO4aTd1KdrpGqdHEUFbTqIKLFifbcbjTRFDadYg8Wc8%2BHxG2cLL0x2LZfFZXYpjbA2AAOJBKD4NaL4c5NzDLcLYj9ldcXb1x-1lfuxQRtZl40AANasMzO9BJoFU4kW0luNDEFyZZfPWa3i3z7une22Xm2J-LiBkBv2bYCOBhWwCE0-p0CoFDB0WJmLoFYurDsV8Z7MDbg-amJd0bCAUF9ROABpRAiAdC7X2gYTEJ9Aheh9JfZqN9Wp3znjqIuGoaYoIgAoLGvdRRHR8poPAU8II5zhnnCOOtEE20KiSBQDNE54gyPoIa6Q3AGHOogPgQoECkN5LA3OAt%2BEF0puFOhyC44S0Tg6MYQxq50FrnOPEQwcBxEQJVWApU5E4Chk1Y6cCSItjCg5RescIIKHtoYg2JZhj3EkHYDIEDWKALSCA9CLj5IUPhlQyOuVH7eK7l8RMCdeS9grLaV2yi4nX2EPzBY1xKTEmBJoY2vhniwIWEAA)

#### Code

```fsharp
match foo with
| { Bar = bar
    Level = 12
    Vibes = plenty
    Lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. " } ->
    "7"
| _ -> "8"

```
            

#### Result

```fsharp
match foo with
| { Bar = bar; Level = 12; Vibes = plenty;
    Lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. " } ->
    "7"
| _ -> "8"

```
            
#### Problem description

I believe it should be formatted as the input is, unless I've missed something important.  Also affects `MultilineBlockBracketsOnSameColumn = true`.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 09/26/2020 18:28:15 - 0771e9a8825b9e411aa16c7f2743427d21652615

Default Fantomas configuration

**Comment by nojaf** [comment]
The fact that `MultilineBlockBracketsOnSameColumn = true` has no effect here is deliberately.
It is rather complex to solve and it doesn't occur in the wild at GR, so it was not tackled on purpose.

For the default scenario, [PatRecord](https://github.com/fsprojects/fantomas/blob/0771e9a8825b9e411aa16c7f2743427d21652615/src/Fantomas/CodePrinter.fs#L4291) could use a change.
