### ISSUE TITLE
Comment inside empty Elmish children is lost

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1179]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBDMBtAutgOgE74B2EEA9BWEgGZGk6QA04UAzogC5cCWJAc3apsbCKHLlIAEi4BPAA7I0kflxZip0gG7oANgFdloyZIAMrU1ICSJJCS4BlXgC9klq2AAsmiDk0Avh7ivlCyisaqDhpWMrqGxlihEACMwaaQALLoAB4AMvyIeYiCXAAWMZ4pAExmof6SQZoSGeFKIpAARrCwepWScfpGIkmeYNXpA46IALa8cHqwJACCXACidgDytAUk7slgtPqc9YHpLQNtkd29-Vrxw2ijngDMk1KOCujQiABCiLRYIREAAFdCEdAzbiIQh3SRcQhGU6Nc6hGTydoqG59d6DBIjA5ed4QSCfb5-AFAoqwADuMOg6E4tm0sAZfCWcPICKRVga5CakguWgx1x6OLROiGiQOAFZiVAyT9-oDgQBVBRKQgMpkkFls3gc%2BVHPQnXlnZoSkUdbGcvGPEyeABs8tJXyVlOBAGE9Iz2J6luxudAuEDORBjabTHyIALyEKSVdrWLbZL8U8DgB2F2KikqxCZWadGFhw7HRDI-mo2KJrHJ3Gp%2B3PKwADmzbtzVP9ixIJYj5bNKIt1attdu9Ye0rGAE42%2BTlrQuDD-TMZugS9z%2B1HzYLLREk2OJROCWMUhYDq7ycqqdM5gtDQc%2BxWY1XWiOoDbx1Lj1U0uec-PF0IG95l6e8xg3J8wFjEJhz3UdxWrI90xPCZz1sewuE2EgABVCDkAB1Xhyl7MtIOgsB4zCN8ujrQ8v2Qqo3j-dtlkIWADDsAARRA9F4OZAPXRFN0kaMoJfS5qLUFMkIdKwUiJc9shyaxaGwsoSjWE1EEcMogS4Qj4GI%2BUvDqAdKyHV84KgKTPzTWTTBSOVFNyWxaF4HJNk1dAQ0INYcgUYF2HYA0e3lGVTK3Qcd1gzFrOiWzGwOFJnWcnIACVEDgQh4AMozCQikTtzjXdYqidQEsnKos1SjKsvgAA5AwZiLQhtmsRcZmEeUUjI8ThSsyAZgMPQ%2BF4vYADEgVXHgYWwvcKu-OTW3PWqgXgTJhtGwpJsIaaBJdaAynBb5AIAfRpXhDIqXqLIkgabLouymwcmdUtYiE5E2QgCkDXKKmMgryFE8jKPRe74sexKxlqF0lPe9BPu%2B3hA0a5qYTajquqSm7oss0qhpG3gxsQHa9tm%2BbIcqqxql-MZIHhxGfq4DbCeJ0nvP289DuO4MYXOy7iJx4qYsiB7EPo%2BzJGqVC6aUgA1KVfn4eB%2BAEP6SxMoWYLx0WIfFp6DmqJjZdycaOODEKlbsVX1YBrWKJK3XyspxbTGqBSTZyTjYC4ABxbg-ICxAgpC23ZUBvwiu1u7So-F2GOppzZc2onCl%2BRZoAAa1%2BCEs%2B4dgsMcSFEC7JrQofUizOfW7%2Btj2j9ahzxqhSun6sQGlif%2BLg6RKOalG4tySCIkLljsAs0cILGxkfKuxJrhNqLjhuqbd6q6YAaUQRAFBUtSSlsIuoV2fZp8ryLzNxmOnekiXnql5bPc0uZ2DKMOxk12eQcd-cENaGS7-INUV6dNnCCD0IgViAgmolH0ogTomQEAn08DPc%2B1dL611FAeZertJAvDPHTZYvEBAkDNiQC2SxnDEO8gYYE2FYDoRgd5EKJEtL21BjWd89c-63wOC8Wmnh6YjRhCQJh2hqSCHHi1Ae-Bh4BhYZGQqUVhY6x-jfA2YwXgywEY4BE8xmaIPkcJIGgQ2A4A8Kodg41goiEfAEIAA)

#### Code

```fsharp
a [] [
    // def
]
```
            

#### Result

```fsharp
a [] []

```
            
#### Problem description

Comment disappears.
Reported by @reinux in #932 

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 09/30/2020 06:55:15 - b0dedcd49f206c5ec6ab0e2cae09c2dffa725a53

Default Fantomas configuration.

---------

Hey @reinux, as I tried to explain in #932, please always create a new issue when it comes to bugs related to comments.
I will judge myself if they are related or not. There is no one fix that will solve all these sorts of issues so we need to tackle case by case.

That being said, this issue is actually not that hard to solve.
You can see in the [Trivia tab](https://fsprojects.github.io/fantomas-tools/#/trivia?data=N4KABGBEDGD2AmBTSAuKBDMBtAutgOgE74B2EEA9BWEgGZGk6QA04UdAliYgM6pQs2kDjwBiPDv1roANj0QgAvkA) that the comment was detected and assigned to a token node. 

![image](https://user-images.githubusercontent.com/2621499/94899746-1e99d100-0494-11eb-9bf3-59006916dc53.png)

The problem here is that we don't call print content before that token in [CodePrinter](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L1241). Notice we are doing it after.

More information on how Fantomas technically works can be found on [YouTube](https://www.youtube.com/playlist?list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K) and [in the contributing guide](https://github.com/fsprojects/fantomas#contributing-guide).
I hope I can encourage you or someone else to try and take a stab at this.

**Comment by reinux** [comment]
I'm going through the videos right now, and I'm wondering: aside from cases where trivia goes missing (as in this bug), is there a reason the entire output AST can't be checked against the input AST each time `formatSourceString` is run?

It would seem like a decent sanity check to do just to make sure there isn't a bug that's breaking code, and probably not that expensive.

**Comment by nojaf** [comment]
Fantomas doesn't strictly guarantee the exact same tree. As far as I know, it never claimed to do so.
For most unit tests that will probably the case, yet there are situations where extra parenthesis are added and that leads to different nodes in the tree. For example the fix for [1183](https://github.com/fsprojects/fantomas/pull/1183/files).

It is something that could be explored thought.

**Comment by reinux** [comment]
Ah, interesting. I guess superfluous AST elements could be ignored for the sake of comparison, but if any cases are missed, inputs that used to work would suddenly break.

**Comment by nojaf** [comment]
Yes, Fantomas doesn't require working code to be able to format it. If the syntax is valid and the compiler can construct the AST we can format it. So that is why the unit tests do [validate the result after formatting](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas.Tests/TestHelpers.fs#L70). Yet that doesn't necessarily mean that the code is still working, unfortunately.
