### ISSUE TITLE
Implicit unit else results in extra lines with each reformat

### ISSUE THREAD

**Issue by renngar** [fsprojects/fantomas#1187]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzAdmABQCUYAvADoBOlhEYAlrmFtQK6KsAWi%2BNdBkLAARWAGVYAW2zdG%2BAObESA%2BsNETps%2BQoCi6AM6JSqoYnTMwB7rHbp4AdS5Ze-WmuEPuAQyyIAbojUJu6qmDhg%2BIgAHli47PjQyhSmDAAO1PJxYJSQABKMuZAANOBQRlhYOgaoYADaZRCg6pAAJFgAnmnIaJBZJY0Mbf7e6Jy1DeoQAAylU1AAkvhI%2BFjijABeyHNTACyDEAC6gwC%2BO00HUO1dPVD950OtI2O3k1MAjA9CkACy3tEAGXkiABfAULgG83eACZppdjkIzoNmsI2p1urVIAAjWCwdCQ1FPUbjNBvdTQr5DcSIKSMODoWD4ACCWF0ywA8rggVECepcKMjPDTg8Ud9rhjeji8bzHs8SfVLhAAMyUiCQcRpbzQRAAIUQuFg1EQAAVvNRvDI-NQZUI2JwhYiRZc0TdMVL8ZThsTXoqwLtVVANVrdfrDSDYAB3ILQbxGJb%2BWAxqqMm0MO2IB0MJFCUWPdG3bG4j3OokvCa%2BgCsAfVmu1eoNRoAqmlutQY3H8Amk4wUwH%2BYYM%2BoEVmnS1xQX3amvWXSb6AGzVoN10NGgDC6FjBlXjIMdugWENqYg-cFQ%2BFyJL%2BbdRanpflZOEAHZF7WQw3ED8aVigke8ALB8Iw4QNmDC5mq47XtKnp3j68wABwvsG9ZhtuDL4L%2BJ4AUIQFgCBFxjleko3tBcqwVMACciHakyuBWtuUhSN4v7ppmwGjoShFQJOJHeuWUKzL6NZISuiDUrS9K9r6mGsbh7FipxhZQSWpF8R8nyCUuiA0VaYl0niknzCxZ6OheBGukRSljips5QhSglLCsWDsvgAAq1AdA4jAQn2-4yXhYBgVcCnccpvE2R8Koaa%2BTLULYywiOYjC0lazEcFhDA4f5gUuhKdyrLe1kKlC-qCX80QLLgLmuPoRjiDY1BYJ58Deb6uxwsZI6mRx5l5VgBVhUVHxVqV-xLLgjDROyra%2BIaujRBkiAGAYPboQGFbtYB545pePV9PlPEzoN6jvAuI3RAASogcDUI4jDNdwv5tX5cl5rt9yhYdD5CO8z5nZd13wAAcuwUjftQnILH4Ug1AG7zPV18m7VIdhVBYUQAGKGoxlRBC5roHfevrvAhgn-Ya8A-CjjBo4gmPUNjKXVtAPjmvuQQAPoRndELw9tZm5XtfUE2Rx2UWdMXmh07LUECu5NS18xPR1bEI69AvvVZA1fQwsLVmVEveFLMuMLuwOg0EENQzDRO86BO0C8j6Co8CdMM7j%2BMfYT8zQup8yQAbRuy1glNO9TLtY74jOCczZpalanPcw9tv4d16v7Z7IvCNCdl%2B2VABq3o6vI8A6PLD0Bkrm0mXzqcFhrhKFdrEDQpFuf-OjCT7itRfLKXiePRt2FbXb-N1%2Bnmufb60IlW30RiFgADi2BzQtS0rWXv7rcnAX2xOxEZ6p5LDbnVM0zqDLQAA1jqrOX9gBjOeIFqIKhIOrVJvnK7JqvgcF%2B8T17KY0JTp%2B0BogCMZ9sBRj4HjboCVxr4C8itJkyxPzm2oNbeY0kv5ZV3pBYsADM5CGhL9P2ABpRAiA0gVSqnwJYT8ZDcm2B-Ac29soQV6PXMUjcp4k1nvoWk1gN4V0HhlYeKdEYCxCoQw%2BWcxZ%2B3WIoTAMUFAgz4I1RAWIfgIGYVgz%2BVdOo10kXvSyDcta%2BiVAJP2TILAKHwB3RIyZ8DrDsb4dgRoXKwAcuo3wK0ML6KHtXEetd8H9UnvMJUvspj%2BydkEfAvjAgAkZAoNBYN4HyCQTufxrCcEvV-rtaRZjwlTCVDnaJ4g2B0mDjo7Jp4DHATKIcHYfQDDo2WrUaSJwgA)

#### Code

```fsharp
let fn () =
    if true then
        DoSomething ()
        DoSomethingElse()
    elif shouldWe then
        Whatever()

let  nextfunc () =
    printf "Hi"
```
            

#### Result

```fsharp
let fn () =
    if true then
        DoSomething()
        DoSomethingElse()
    elif shouldWe then
        Whatever()


let nextfunc () = printf "Hi"

```
            
#### Problem description

Nested ifs or if-else chains can result in additional blank lines being inserted with each reformat. This seems to happen only when they have an implicit unit-returning `else` tail.

I have many variants of this in my code. Some occur at the end of a function others in the middle of a function.  In the latter case, the rest of the function is pushed further down the page with each iteration. In the former, the same happens to the following function.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

I am not familiar with the Fantomas code, but would be will to try to fix this with some pointers or hints.

In places I've had to resort to things like:

```fsharp
let private setState (host: IViewHost) retryMsg program (state: Model) dispatch =
    // create new view and update the host only if new model is not equal to a prev one
    let stateDiffers = (Some state).Equals(!stateRef) |> not

    if stateDiffers then
        let updated = state.ThrottleUpdates() |> not
        // Only build a new view if the screen has been updated with the previous one
        if updated then
            stateRef := Some state
            let view = ((Program.view program) state dispatch)
            host.Update(Some(view :> IView))
        elif retryMsgInFlight |> not then
            // Otherwise, dispatch a message after a while so that we can retry updating with the latest.
            DispatcherTimer.RunOnce(Action(fun () -> retryMsg |> dispatch), TimeSpan.FromMilliseconds 50.0)
            |> ignore

            retryMsgInFlight <- true
        else
            () // Avoid Fantomas formatting problems
    else
        () // Avoid Fantomas formatting problems
```

Interestingly, if I only put the comment on one of the elses, Fantomas will insert it on both.

#### Options

Fantomas Master at 10/02/2020 17:06:53 - 31305c2b96e2e511b44459e879004e74ce1d6c06

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello @renngar, thanks for reporting this.
I believe we are adding a newline too much somewhere in [CodePrinter](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L2180-L2509).
Sorry that this doesn't really narrow this down a lot.

The learn about how Fantomas works internally, you can check out [some videos on YouTube](https://www.youtube.com/playlist?list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K).
And check out our little [Contributing guide](https://github.com/fsprojects/fantomas#contributing-guide) section.

As for tackling this, I propose you create a unit test in [IfThenElseTests.fs](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas.Tests/IfThenElseTests.fs) and do some debugging to see which code path is taken.

Don't hesitate to open a draft PR and ask some further questions down the road.
