### ISSUE TITLE
[Feature request] GR style tweaks

### ISSUE THREAD

**Issue by JackMatusiewiczGR** [fsprojects/fantomas#1189]
We ran the latest version of Fantomas on our code and have a list of minor issues we have with the formatting style. Some of these may well be due to our incorrect config and we are going to be double checking to see if that is the case of some of these.

To begin with, here are our config settings:
```
fsharp_space_before_uppercase_invocation=true
fsharp_space_before_class_constructor=true
fsharp_space_before_member=true
fsharp_space_before_colon=true
fsharp_space_before_semicolon=true
fsharp_indent_on_try_with=true
fsharp_multiline_block_brackets_on_same_column=true
fsharp_newline_between_type_definition_and_members=true
fsharp_align_function_signature_to_indentation=true
fsharp_alternative_long_member_definitions=true
```

**1.  Casting operator not being treated like other pipe operators**

What we had:
```
Reflection.invokeStaticGenericMethod
    <@ someFunctionHere @>
    [someParameterHere]
    [someMoreParemetersHere]
    :?>
```

What fantomas did:
```
Reflection.invokeStaticGenericMethod
    <@ someFunctionHere @>
    [ someParameterHere ]
    [ someMoreParemetersHere ] :?>
```

What we wanted:
```
Reflection.invokeStaticGenericMethod
    <@ someFunctionHere @>
    [ someParameterHere ]
    [ someMoreParemetersHere ]
:?>
```

**2. List function parameter formatting**

What we had:
```
someFunctionHere [parameters] [yetMoreParameters]
:?> _
```

What fantomas did:
```
someFunctionHere [ parameters ] [
    yetMoreParameters
] :?> _
```

What we wanted:
```
someFunctionHere
    [ parameters ]
    [ yetMoreParameters ]
:?> _
```

**3.  Formatting a list of tuples that didn't hit out line limit**

What we had:
```
[MyType.ofPartialThing path, leafObject]
```

What fantomas did:
```
[
    MyType.ofPartialThing path, leafObject
]
```

What we wanted:
```
[ MyType.ofPartialThing path, leafObject ]
```

**4. Ending parenthesis for lambda functions passed into HOFs**

What we had:
```
List.collect (fun (a, element) ->
    let path' = path |> someFunctionToCalculateThing

    innerFunc<'a, 'b> path' element (foo >> bar value >> List.item a) shape)
```

What fantomas did:
```
List.collect (fun (a, element) ->
    let path' =
        path
        |> someFunctionToCalculateThing

    innerFunc<'a, 'b>
        path'
        element
        (foo >> bar value >> List.item a)
        shape)
```

What we wanted:
```
List.collect (fun (a, element) ->
    let path' =
        path
        |> someFunctionToCalculateThing

    innerFunc<'a, 'b>
        path'
        element
        (foo >> bar value >> List.item a)
        shape
)
```

**5. Tuple formatting when not near line limit**

What we had:
```
| Leaf.Func getFunc -> iterator.Iterate (path, getFunc >> fun f -> f.Invoke)
```

What fantomas did:
```
| Leaf.Func getFunc ->
    iterator.Iterate
        (path,
         getFunc
         >> fun f -> f.Invoke)
```

What we wanted:
```
| Leaf.Func getFunc ->
    iterator.IterProv
        (path, getFunc >> fun f -> f.Invoke)
```
or
```
| Leaf.Func getFunc ->
    iterator.IterProv
        (path,
         getFunc >> fun f -> f.Invoke)
```

**6. More Tuple formatting**

What we had
```
|> Seq.map (Tuple.rmap (MyLongLeafPath.toInnerPath >> InnerPathType.toHumanReadableString))
|> Seq.map (fun (added, str) -> sprintf "%s - %s" (if added then addedString else removedString) str)
```

What fantomas did
```
|> Seq.map
    (Tuple.rmap
        (MyLongLeafPath.toInnerPath
        >> InnerPathType.toHumanReadableString))
|> Seq.map (fun (added, str) -> sprintf "%s - %s" (if added then addedString else removedString) str)
```

What we wanted:
```
|> Seq.map
    (Tuple.rmap
        (MyLongLeafPath.toInnerPath >> InnerPathType.toHumanReadableString)
    )
|> Seq.map (fun (added, str) -> sprintf "%s - %s" (if added then addedString else removedString) str)
```

**7. More parameter spacing**

What we had:
```
InstanceObject.make [a; b; c]
```

What fantomas did:
```
InstanceObject.make [ a
                                     b
                                     c ]
```

What we wanted:
```
InstanceObject.make
    [a ; b ; c]
```

**8. Constructor formatting**

What we had:
```
new ParquetWriter(
    file.FullName,
    Column.Thing
    WriteProperties.make columns,
    dict metadata |> Dictionary
)
```

What fantomas did:
```
new ParquetWriter( file.FullName,
                                Column.Thing
                                WriteProperties.make columns,
                                dict metadata |> Dictionary)
```

What we wanted:
```
new ParquetWriter(
    file.FullName,
    Column.Thing
    WriteProperties.make columns,
    dict metadata |> Dictionary
)
```

Will update this as I check to make sure these aren't already solved by config we aren't using.

Thanks,
Jack

**Comment by nojaf** [comment]
Hey @JackMatusiewiczGR, 

Some initial feedback:

1. could you complete all the samples so they at the very least produce something in our online tool.
[Example 1](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAlRAzANo6ALgJawB2AdEaQG6wDWiAygQIbHQDiipiATkdACyiAgAsEAHV4TSECAB4AAmADOsALaIAYgFdShEqQASfRGEUA%2BKTLlgA2ms0AFFrxaaCfE70QBda7JyDhqIgrA%2BLj4efCrefgG2KAD8FpAANOBQKiLEpADmKqj2mRCgthCQACQEAJ4ADshokFQE6SVyVdQsODqNxeVyAAwZAxUAkqRIpASMRABeyCOjACztEL7tAL5LpWtQ1fV9zdNtA53dvUV2exAAjDvlkIIsAB4AMlSIb9x5YqejtwATIM9htbNt2mVHgcGkVIAAjWCwHD-WznHp9a6jMCAh5oxiIdQCZFkACCBAAopMAPJYD48VHlLDdbKgrYPKFomFHRHIxkVSpdDFXG5gADMeI6jDqLGgiAAQthwohIu4RHx%2BXICLxemzwRy9lVarCmryUZL0Zc0FiVpKKtLZQqlT43rAAO58aAsbITWhe4hkTUQbW6gZguQQ2ycjrcuFmzWWzGigCsdqgDrliqwyoAqnUGrwvT6aLB-YYg2BmThWWH2ZDDbHTUjzQ2hVb%2BqMAGxpyAZp3ZnwAYRw3pUg7IKhDhHCFarNfK4Ygkbk0YFxp5zYTgouSexAHYe32s8rhOp4Rq03PEHqIwazo2oPGLdvhdbRQAOQ8yzPOxDjnCBpeLLXrW%2Br1ve65xpuz5truowAJxfo6pJYJ4vDjuo6gsBWIYgQudZRg2kFNnyME7iK2K3MMoq9t%2B-bKgSRJwABpCzsBN5Lne0LEY%2B0GtuRb6UfcNF9ihaGMcSLE4TqeG2IuYDLrsEGHFBpH8a%2BHYDECPYTFMBDUqQAAqvA1AA6kQfxAdWslyPJilgKu%2Bw8QifH3rBFEAhKIl0aSvCwHo8AACKIDgRBEmh0mhvhYGEcpJpQC0W7uYJALLD2zwvGMWCGaI3AUtZjDiLwBDmfAlmissIKgbe4HcSpTSJWRGk2lpqY0RlExYEQLzUgWbDhBSLx1D4KgqOWabJlV0U1bFdXxccrRNe2LXlLc3bta8mBwLw8CleV2KVRxClcVyzmNepy2ircB4bS8W3hPAAByOhnnwtJjJ46iFGmtxHfZjlGvVUDqDoODEKFPBaOEWEEGhhkqUtcFaZ%2BNH3Ttgig%2BDnxQ7wMMRT20CiK4spoQA%2Bm6RBlaIkB-SdMZnSciMeVpiG3b5bg1NSvAfJOe3U2mh3VZxtWnUDC1JQJmnlMC6WvOzLCc9zRCTs9r28O9n3fVdtMi-TYsg2DRAQ9o0NsHDCMXUj0vCdikDy4rPMEBjhvGzjeMXjRhPE4QfDk5Tfw67NovzedbmSyttiArit0AGo7vKVDwFQeR8xWgvTcLQd6yHjOW8z0tebbGW6PoAakAnkzJ6nAtTXJBErkRYuh9CyVS5HaW3YFsAEFwlJDSNY1kNXKa17Z9dKXNG5qWHzWioCbVF5jRufPKAHQHQ8puOvIgqAZjBqv%2BL2sVZ851zFDdxVPLYz5d2KAuttuPYgbrG4qBAetw8MNMFXWkBZhikkmKec8vAtbYivIHC%2Bk9VLXxbuHOeN1bYAGlECIDqFlHK3AJj700PSRYooIFC2OrrNcTdc43ytpHFGRdXj5SJCoUQw8Dqj3WOPByjd5pPjzilAYgJWa21mPkPAvk8gvW4CVRA8IwhIDYtZSBE9g5XwlrPbEYpqK21JKFPIpAS4GDILMbRbAdA%2BEMrAXS4i2DjQIexIh-0OFKKZjw8oYobajDtmDPgpBLHUC%2BGQPIwC%2BA-yoP-CcsjT5j3Pgo7ODjuFtzkGKaOAjtQCCdggfB4CbEZwUpkXwSxmgqC0GNIoEDNhAA) doesn't parse for example.

2. is related to the Elmish formatting. `someFunctionHere [parameters] [yetMoreParameters]` matches the formatting explained in [Elmish guide](https://github.com/fsprojects/fantomas/blob/master/docs/Formatting-Elmish-code.md).
I don't want to be "that guy", but I did raise this during a call in the Summer 😋. In short, I'll add something to disable this behaviour.

3. `[ MyType.ofPartialThing path, leafObject ]`, is crossing the 40 character limit of `fsharp_max_array_or_list_width`.
Having this [on 42 for example](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBtMBZAngFRwAdEA6WAMwAUBDAJwBcBLagGzwAtGA7AczEOr12AGjAtE1cgHkARgCtE0emAC6kYeCgBnRPSa8tqMOk0RQEC1AAk9IsjSRu9daYuQrAN1YBXe8deWAAwalpaQAJJcSFz0AMqMAF7IIaEQACwBqq4Avilmme62xEaOMS6p7l4svkYmqRAAjHmhkFjUAB4AMtyInYi8QuX1DQBMgZkqOc3mLTZ2JTKwsCxDYZ4%2BfnX1I81hsYgAtoxwLLBcAIL0AKJRUuTdXMmZEOSsOhNTrjNrRX6Qi8tVm51tVNs8wABmXZuWICaCIABCiHIsFoiBotGoB10iFoQMs9Fovg%2BllyXwKc2KDgBK2hlQ2tXBaWhEEgsOo8KRKLRnVgAHdcdBqDpIh5YEKmGd8RZCcTUpNSdMKb8FktaRSqjU0FtUgBWFlQdmc5GoxAAVUIxFoQpFXDFEsYUoNrxY73ln0s32BKupaul9NBjPqYAAbAa2XDESa0QBhFjCrQxs5aWVKVHSl5vRAkixkz3K%2Ba%2BwF0kFa-zBgDs4aNUe5iCwhxkuIzYBdbtCCtzSoqlL%2BNP9pbBwYAHNXI1zTUnTlwW23s%2B7FeSez6oP2S5qh-UAJxjjmIc7kei4pMHA7UFuy%2Bcdj0WL2s3uq4sahna8ENYLgiN7ido-ZHE5OuCc45hAea3gWVKrn664vuWwxNJ%2BNYHketB-scyyAcGl4gWAYH5MuhZQU%2BPYbkGww7J%2BkTRPQUhcHgtA4AA6owgzOlmOF4WAd7WCu-zQc%2BgavsGDRQohkbnLQsDeFEAAiiAsIwRwoReRJXpYnagd2sy8U4A6kUJwzMp%2BbTtOE5AcP0VyuogsTsKi9DMfArFMuMC5dku2mEaUzgwYJcGpA0%2BrGR0kTkIw7RSFagiolc7SEGiWhaI6M4GrqrnXou%2BYEZB3l6bBOqhA0YbBe0ABKiiovAjnOcGaTpepN74Z5OW6b5ZYFZYDRViV5VwLQ8AAHLeAcTa0Hc4RHgchgGg0HFaT8XkHN4LBMApjwAGKomeei4gQxRtZuAWjp%2BvWVVgy2rT0m20NtynhtA7B0ByKEAPp8owTnsJAc0eQtLVlAdZEBTuJUSZiOBSLQ3QptVX0GmkIw-VlzV-K1AnteCYzhiZYPUBDUOMCmQ0jbi42TdNb5I%2BB2V-EtK2MGtiDXbdu3zIDBmpCMCHBpAuP49D9DnfTjPM4Id2fg9T1KLib0fYMVNNX9qMA%2Bjh2hCMFE8yZABqGwItw8DcDwsMtnVCtcRBys%2BarQPq6JWsdOt0lKMl%2BtREbJvw-VFgabh83el5aMkflmNGQ77QybA9AAOK6LF8WIIlyWe%2BCaXm9xhReWuNsc%2BrQVaxdDM9AipzQAA1gimLl7oWi0bEWKIFOw0peC2FuZpv0Bzl2fB35HUWCMxU8wNiB8ozSL0AK-R7YgclhVwLHJecUQNiTtAU8GwHt37nf3rxPezPp-nq91PMANKIIghBmRZXCRPX2IPE8m-sdvnEZw%2BDhB4fIfBiMx3hyskcLQ7AU61W9hAX279LaPnVL3DGf8QY83iLwcQEkeDDX6A5RAMgsAIGfvULeGV3LIyVrAvKfdwQQg-Dzc4CkeBcCdlwF2Zx4gMMEN4NEeBYBUSwYIZKs5X7EI7qQrufZ%2BLwLVpYCE3N6i8xWriLg-CPC9DODwVeo057cEXsmQR1l04wKLHAn%2BlDgwQk1nI2IhJjiC3wXo9sDVSSaBUCkRwWh1pJSMMBbIQA) does what you want.

4. This is an interesting case, I do agree that it one of those things I don't like about Fantomas myself personally. I think the scope is bigger than the example you posted. I'll create a separate feature request to flesh this one out.

5. Can I get a more complete sample of this? I'm guessing that it is nested code and near the end of the max_line_length.
At the beginning of a line, [it seems ok](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbAhgF2gCzAA8wB3AS2zwB0AnKgOwB8wAZRTAMwDoAxAV3rQwAc0TZ%2BgsAFoAfGAqIaOWDS4BJbIpyIwACgAOOPABoRYiUJlyOAsB2nX19AG6wA1ogCUkY%2BCgBnMWwyemF-VDAAbT8IUAh4qAASbABPfWQ0SBDsHxj4yETnTAAbPgyovISABl8EhMg1eiR6bABlMgAvZFq6iAAWSrAAXTyAXx7YwYLU9IisltzegqLS8ujeiABGCbrIAFlMQhYQxDZQykWNzYAmKsGRhPG8uN3ktPLIACNYWGLL%2BsKJTKEXWG2uO3qrUQ6DIcGKsHoAEFsABRJoAeQ4x3o3UGEA4JUC9zGOxeAJmH2%2Bv3%2B%2BUBqxBeLAAGYIflWoZoIgAEKIDgqRAABUwSnQYkUNIS2BoZWJj1JUzes0yVL%2BrOWQLWjL6rIgkHZmE5PL5NFOsBIimgmECjVcluCCIl8SlMt6D3iTwSZNpFLmKsd6vpaFBvQArDqoPrDbz%2BQBVfTpGiW60uWB2sgO8ME4pE10k54Kn3Kn6qhUrYFBxkANnDeo53OjJoAwsUrf5Gwj-M7oNgVI78YTELL3fKlorKcX-XTyxUNmAAOw1yP142IPbQz7izMDocQD3xL26se%2Bidqqea2cADkXdaN-Pb8Pofbs29zcvzo8LUD9p7L542AE5rwNRBEQ4TQaHbdAsCfZ1B1fYd31eT8vhPUsNQZWdNhqRla2A28TShGE4QzRksxzOo3V3EckPeY9qR-dCK0w7YcKXUDwMI2FfhI2dYJ3MA90mD9aKLei0MDGcrnBHDGmabB0XoAAVGgUgAdQoPAnzIuCKLzT0CxEr9UNHX8MKuFlWLrREaFgAR4AAEUQYoyBhcCYOlHSEkogTqPJQz5hyBiJODOpNm1HCDkINQOEUvBEHoFFs0QVo8BUbB1PgC5wz6O54KoxC-KVKBsknUymKuMMIsORoODIQh0QTZQaBRQh9BNfx-HTR9wxDXLdLffThKKgLSsYyTek2asqsIAAlRA4BoeAMqyrU%2Bq8vT9wM4aSqC6cQoSTYF2muaFvgAA5Ph0A3GhMQ0aFwnDTZ%2BMEsADySZD0D4YpgmcnEeBULBsHAxTaN2v8JqvHCTpUeA9i%2Bn6Tn%2BmhAbcmt8GFA1wIAfXITLNOe3zvX8nbxL2xlNkA6brKUFJ0RoY5O2WzTsuuAmCqJ7aFjBszeluGtIupzBafpshOwuq7FFuzR0Ae8m2cGmjhs%2B76yF%2BxAkZRxQQdmbnyt5ljZ0gQXhYZ7A4ZVtWNZwVGcPRpRu0UHGyDxyB5c2oaPhJkyxv2%2BJrmkw3IoANQ1LkQngEJhCZp8crdoTFc9rnSfBuprgswPDgse16DDppI%2Bj7K1vibyXre6ZiaT73gsZa5wozwh7NgbAAHExBatrEA6rqC8ZXq49erbxzEquydna5KsD%2BHVZOLl4WgNwuXtjxsH8BTWkwUV70u7rGT4vKfPZw9kO-ZOedTqbDbOxASDVnlsHNeLtcQRzavoCgusRJo1wlmhZdnbT%2B5lyPKJEsI8U4JGuEdQ2ABpRAiB9DRVivFRo69RTYlxP-F8-UEIK0KonQKp89ap0hvXRKMJ-B4B7rOWO%2B9S6DzoqA14ZVxqp0pobdooRiggRoMIS68V0qIE%2BHsBAGCNgANoYTI%2B-kT5gLPgkJk2FDaImcsIegWcurtFUTgPgJpFKwFkvwnAXUtJYPWgNd2CcGGjWrrOJkBsNhG2%2BooegRjnCmlCN-a6L8Qjvw7CYpKgD6EgOsaPDYTIA4ONaFKWEZsRH%2BPImY90fghg9CyP4HgnUIgANGEAA).

6. Seems to contradict 4. a little. Why is it not 
```fsharp
[]
|> Seq.map (
    Tuple.rmap (
        MyLongLeafPath.toInnerPath
        >> InnerPathType.toHumanReadableString
    )
   )
|> Seq.map (fun (added, str) -> sprintf "%s - %s" (if added then addedString else removedString) str)
```
in this case? Is it tuple versus lambda?

7. Full example, please. It might be related to 2.

8. I should look into that one to see if there is any current reasoning behind this.

As we tackle some of these things, we should also update the [style guide accordingly](https://github.com/G-Research/fsharp-formatting-conventions).

Thanks for writing all of this down, much appreciated!

**Comment by Smaug123** [comment]
I think what we need to resolve 4/6 is some more detailed style guidelines. I've documented our style in https://github.com/G-Research/fsharp-formatting-conventions/pull/10 . I think your version is more consistent.

**Comment by Smaug123** [comment]
Number 7 was fixed by disabling the Elmish formatting.

**Comment by Smaug123** [comment]
Re 8: I've raised a discussion over at https://github.com/G-Research/fsharp-formatting-conventions/pull/11 about what the right thing to do here is.

**Comment by knocte** [comment]
Re 4: I'd be interested in this too.

**Comment by nojaf** [comment]
Hey @JackMatusiewiczGR  and @Smaug123, in regards to 4.

```fsharp
    innerFunc<'a, 'b>
        path'
        element
        (foo >> bar value >> List.item a)
        shape
```

a function call is only multiline now if it cannot respect the max length boundary.
Was the example intended that way? Or are we missing another setting to control the max length of function calls?
Such a thing would not be that difficult to set up I think.

**Comment by Smaug123** [comment]
That looks fine to me.

**Comment by nojaf** [comment]
I'm going to close this as most of the mentioned items have been resolved by now.
Feel free to open new issues, when there is still anything missing from the G-Research style guide.
