### ISSUE TITLE
Problems with very long lines and/or files

### ISSUE THREAD

**Issue by dungpa** [fsprojects/fantomas#119]
We use ranges from F# ASTs in order to look up constants (numbers, strings, etc.). It is handled by https://github.com/dungpa/fantomas/blob/master/src/Fantomas/SourceParser.fs#L24. However, constant lookups are unreliable. Range values produced by F# ASTs are really strange:
1. For multi-line ranges, F# ASTs have offsets that we have to compensate in order to get correct string values. However, this hack is not always successful (see #110).
2. F# ASTs give bizarre results on long lines (e.g. lines with more than 512 characters) (see #83, #85).

This code fragment

``` fsharp
(new CsvFile<string * decimal * decimal>(new Func<obj, string[], string * decimal * decimal>(fun (parent : obj) (row : string[]) -> CommonRuntime.GetNonOptionalValue("Name", CommonRuntime.ConvertString(TextConversions.AsOption(row.[0])), TextConversions.AsOption(row.[0])), CommonRuntime.GetNonOptionalValue("Distance", CommonRuntime.ConvertDecimal("", TextConversions.AsOption(row.[1])), TextConversions.AsOption(row.[1])), CommonRuntime.GetNonOptionalValue("Time", CommonRuntime.ConvertDecimal("", TextConversions.AsOption(row.[2])), TextConversions.AsOption(row.[2]))), new Func<string * decimal * decimal, string[]>(fun (row : string * decimal * decimal) -> [| CommonRuntime.ConvertStringBack(CommonRuntime.GetOptionalValue((let x, _, _ = row in x))); CommonRuntime.ConvertDecimalBack("", CommonRuntime.GetOptionalValue((let _, x, _ = row in x))); CommonRuntime.ConvertDecimalBack("", CommonRuntime.GetOptionalValue((let _, _, x = row in x))) |]), (ProviderFileSystem.readTextAtRunTimeWithDesignTimeOptions @"C:\Dev\FSharp.Data-master\src\..\tests\FSharp.Data.Tests\Data" "" "SmallTest.csv"), "", '"', true, false)).Cache()
```

always have columns smaller than 512 although it has more than 1000 characters. At some point, there are a range like "line 2 - column 500, line 2 - column 22" as if columns have been wrapped around at 512.

This is the root of bugs #83, #85 and #110.

My questions:
1. Where shall I report this? fsbugs? F# Compiler repo? F# Compiler Service repo?
2. Is there any better approach for getting constants? They are useful for getting semantically equivalent values but preserving original styles.
3. If we stick with this, how do we enhance reliability of look-ups?

cc @dsyme @ovatsus

**Comment by cartermp** [comment]
@nojaf @jindraivanek This may be able to be closed. F# 4.6 (and corresponding FCS) [now use larger ranges](https://github.com/Microsoft/visualfsharp/pull/4476). Range isn't notable in memory pressure in recent measurements of the F# tools (though boxing due to comparison was until that was recently fixed...)

**Comment by nojaf** [comment]
Ranges in newer versions of the FCS have indeed improved, I don't think this is a problem anymore.
