### ISSUE TITLE
A comment before an anonymous function gets swallowed up

### ISSUE THREAD

**Issue by naartjie** [fsprojects/fantomas#1190]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAKCYA6A7LY6AVGHALZmK4AuYARogGawBOiYA5otQM5g8B3AIYAbEbAGJ4YIgEo8BRgFd8ADzABaAHxh1JACwAmPPNx50CrMrWadesEcsRipWBSq0hjaohZgAlnwA8gDSMqam5lgu5JQ0YLD4jP4sPLQi-rjsgWChYNSwsOFOYNa6tuUGxriykAA04FA83NSZHDyoYADajRCgBBCQACTUAJ4ADshokJnU9b1YwwBuokpT3QsEAAwNA4sAkrhINADK-gBeyLt7DptgALoLAL7XfXfDY5OdMzTze8urdY9G5gACMrwGkAAskJVAAZTKIOFUDjUAAWfxuoMMWzujwILwW-UhIwm60gdEKIkxBABIjWnWBN0MENpJ0QZH8cHEuAAgtQAKJHIKMBFZGkDRiiZp454Q4m00lfaaU2DU1lQIYrelAu4QADMGsGJ3GQmgiAAQkxWIgAApCFhCSg%2BFgSgjUFhrWUE%2BXvJXk1Xqv3ahloJl7fRGqAms2W61sOESXzQITNQ5LWAp1qJN1YD1evb4rCEggKxb%2B76B3N00MbEEAVijkBj5qtzDYAFVxpMWCm07gM1n-Dmo1KRDLC3KiX7PgGqdWtYDGXqwAA2JstuPtxAAYREqZ4O8SaU90AKrtH0sQ3uLvv%2BFZV841Nd1IIA7BvTa344goRyGBeK5jhOAxFhAJZYGWgwPlAVbPouOrLiCAAcn6xm2NpHjyuYQMB16Tj6073rOlZPsGS5hiuACcaHmry3i%2BEeFBCDh%2BSevhoFTqWM5kqRaoLiGr5YjsK7Nl%2BW42uynLciOQFXje4F3iSJGPvx8GCUhWLgqJm70S6UlcmqskgvmHEEGBYAQW8xG8apQb3hplEgtiTaHMc1BBLgAAqLCjAA6v46KsXhCmWUpioqbBZEORRdZYoaOnibyLCwCo8AACKIBknIuqxpmhVZYBQZqkU-HM6mxeGAygpGokwqo%2ByMF5aJUAK46ICcaKsNQAXwEFUb6LiBG3kRym2VAswCZVK6go2dWwocySqEEPZCOeAqqOMbA8Dww64Kx9ZDZxhHcTZyoTb8FWIU5WLrvNqgAEqIHALDwL1-UroNBXheWpWTVdtZVQQoIfvdT0vfAAByShkABIr7D4ZAdFGoLfaNEXjZAZBKCIrQZFkABirBkGtLpebxANCXsoKoaJ4OsPAUI43jiJEywJPULlTbQGiDpmi6AD6Aj%2BH1GJo6dY3nWVU3XXF1M0fdyWOqMQQsAiaTvRiA1HeZXGQTxUv-eRstA1gOJNvVStCCrauBNQ0Ow748OI8jM3i-rZ3ktjuP%2BPjiBsxzZMU8bgMroY2kgpAVs2%2Br1BMz7fsB6TvisTAvOOmevhCyLQXu9ZkvkkbMUm2HLL3QAaoCFqZPAbSa6xX3DYp6O-ZjRcko5csDIYCWR-VBMqGee3V0cdc51rn061gFmFcVHxt5dIdU93tV97C6WwNQADi3AbVtiA7Xt9dRodedFQbc5qUvml7IYc198zvuIha4jQAA1haGdv9wPCeScTq7jVDDfal52pnznjBCk0UO7TRBIYO6kdIaIAEH7K01BJBUHJpMTKyRcCBT2ryI4f5HapGCvJJuYUW7QVKnBa%2BN1b6g0jiERAiBxiNWalQQ4-9KBiiuHJMBFDZ4X2%2BO3RUndTYQEMLTNeqg2qch4GiY%2Bk9wHCLsjLUOcCFaRzOLgDgIhEDJQ4DDDwflEB0ChAgPhIIQqCJ%2BtQzGtDi4aJuPqESkdeQZA4LgAeuAh6JDOF4taSg2BeVgG5Dwa09pkIEcdEaEsMZS0cTAkuIJ9QRxuFHXGvhcCRKWEiRIHBiEARwZkfBx5okgV1idD2Bc%2BL2WSc4vY%2Boy7aI9FyOOliKlmWns8Ro9xrgzB4ATXanQQpPCAA)

#### Code

```fsharp
(   
    (* comment before gets swallowed *)
    fun x -> x * 42
)

(
    fun x -> x * 42
    (* comment after is OK *)
)

(   (* comment on first line is OK too *)
    fun x -> x * 42
)
```
            

#### Result

```fsharp
(fun x -> x * 42)

(fun x ->
    x * 42 (* comment after is OK *)
    )

( (* comment on first line is OK too *) fun x -> x * 42)

```
            
#### Problem description

A comment above/before an anonymous function is getting dropped from the formatted output. This also happens if you use `//` for a line comment instead of the `(* *)` block comment syntax.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 10/02/2020 17:06:53 - 31305c2b96e2e511b44459e879004e74ce1d6c06

Default Fantomas configuration

#### Possibly related issues
#1179 #1172 #932

**Comment by nojaf** [comment]
Hello @naartjie, I'm in the process of writing some more 'getting started' content. See https://github.com/fsprojects/fantomas/pull/1195.

As for this problem, it is a trivia bug.
See [online tool](https://fsprojects.github.io/fantomas-tools/#/trivia?data=N4KABGBEDGD2AmBTSAuKAKCYA6AnbAdlmOgFRhwC2liBALmAEaIBmsuiYA5onQM5g%2BAdwCGAGzGwhieGFIBKPIWIsArkQAeYALQA%2BMFvIAWAExKC8yABpwUJCwCWBRH1RRrtyA74AxPg7cWcT5EEABfIA).

Fantomas assigns the block comment to a `SynExpr.Lambda` node. And in `CodePrinter.fs` we need to call `genTrivia` or variant in order that the comment gets restored.

![image](https://user-images.githubusercontent.com/2621499/96274454-cb199e00-0fd0-11eb-866e-25e6e47ef7c2.png)

In CodePrinter I believe it is not printed around [here](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L1639).
Call it a gut feeling.

**Comment by naartjie** [comment]
Thank you for fixing this 🚀 🚀
