### ISSUE TITLE
Elmish-like syntax using yields with interspersed let statements breaks the code

### ISSUE THREAD

**Issue by renngar** [fsprojects/fantomas#1191]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAHATgJYBuAhlomAGYB2YAFAB4DOahNOA2gLoCUYAXgA6%2BIXQjUaAJhFiJ8sEMhLZ4hWE5hMOfILABlRAEcAdAAtEpeGBarV6%2BQE9CidNdGia9hxG1hmerRS9LzePswmACKw%2BrAAtthm7ADmIWDckAA04FDM2FgpzKgaORCg6pAAJFiOuMhokOxYWaUSVWToAK71JT4ADNk%2BkACSNEgc%2BoQAXsiDDgAsrRDcrQC%2Bc2VLUNW1PY0cLRWVHd3FnFsQAIwbCpAAsqSMADLsiE%2BINMlYZocOl1J9LYreTrVrlW47OrFSAAI1gsHQv3k7VIXR65x8UhuyMMcUIcHQsBoAEEsABRMYAeSoLxoswu1FReSBaxu4ORkL2cIRSLax1RpzQGIcAGZsW19LhSNBEAAhRBUWD4RAABVI%2BFICQo%2BF58iw%2BG6LJBbK2VRqUIa3MR4pRaLODPm4ogkEl0rlCqVb1gAHdEPhoKQ8qNiLAAwUibqJPrDepgRJQfJ2XzzVz4dbTfy7UKGQBWJ1QV0y%2BWK5UAVVwdX9gcQwdD5EIEfzVCZiCN8ZNRxT0Ktkdtgt6DgAbPmXVKix7lQBhdCB5iTonMaPQLBKyMQZvoZmx1lgjNdy1p3uZ-vC9QAdhHhfdJcQd0QcRhfrXjM3re3xt3nd23cPNuP6IZAAOS8x2vT150JGhnw3LcFDjCAEwkJNnU5H8eT-E4AJ8ABOEC3WJKhtXnOI4lIZ9ozfOCd0TPdvwPdCM0w%2B0fEuAYGVHN1i09XF8QRRsGRgyj5HgsBEM2L8LSgHsMIFLC-mudirwI7UeIJfifAotsEI7CF9yk39GNk5i-ixdjRnGLBKRoAAVfBHAAdUIb5oJbLTRJ0jk9NhAyjiY7MWLFRTQOJfBYE6MZIlcQg8W1ciDSEiQRLEsBkO2LymiPPyB3US5HXYh5GGGKhrIsGgyVffQzCVLBHPgZz83mQF33bT9dLoqAMpkrNsoUS483yx5RioQhGEpStyCVMlGAIRBmGYBsoPzHMmqoj8aIkvZOsM7rT164cBsYAAlRA4HweBavqh0VuE6ikNoyT9maLqTwZS4LwO47TvgAA5ToHz9alhgoOIinzS43OS1KzXayA4k6dACnQV4ADElVIrBtWs79nrknLgPYz6lXgO54cRlG0fIWKR2gMx1WlbUAH1vUIOqfghjzkxhrbfKM-y-lwg6Qo1RxKXwF5Fwun4GuuxLbvEtqHu5iEst2%2BQARHAqhdIEWxcIRdfv%2B-BAeB0HXvZ1rPJhuGEcIJG6VR-B0cx7HtpezEFKGLWdfFrASZtu3EAdp2n2p2mNWXP0mZZ5zzfWhXNoOHHjPUKRTKGAqADVZNldh4BSSXn0a2O7o26ElY5FWGSkQL08eZHwuXBac7GfPo6lq7i-ly3FcT13cYUKQ8trxhoiwABxbAppmuaFoLpaZeWOWUvu1MGJ5naq-69PSdt15ZUJaAAGtZXDw-sGYKz9E1RAIL%2BxaBNc5rtItzmHukvvk4H-ahm%2BxBvQD%2BUWBfQfCxnUSKw0aBOQWsSMYd5Damx8IJTuy9S70XTOvN2DgpDvSGAAaUQIgXARUSofFGFfBItJ6SIMfqtFqcdu4Jyeh-PmKd8bD3KniZgZg54dyfu5F%2BKEvLvwwf3NWAshiTE%2BJgEKyQ-ofBqogGEdwEBUIcEgvhkMV5oXQcrXmPV5AijYp7JGyQaD1xoI3IkkxTHkE6MqaysBzLyPrOpNRNCbprRLvHbRmU9GqwkCKD2DhIDEgRn6Gg9ZiBek%2BHAx8%2BBwHsCgQuFyr5kFQ1Qmg3xG8fAijTsE-Q%2Bp8S%2BxUSk2CHj4w5G4HMRozBkbzWKEg1YQA)

#### Code

```fsharp
let private fn (xs: int []) =
    fn2
        ""
        [ let r = Seq.head xs

          yield r

          let s = fn2()
          s.DoSomething() ]
```
            

#### Error

```fsharp
Fantomas was able to format the code but the result appears to be invalid F# code.
Please open an issue.

Formatted result:

let private fn (xs: int []) =
    fn2
        ""
        [ let r = Seq.head xs

        yield r

        let s = fn2 ()
        s.DoSomething() ]

```
            
#### Problem description

If you have an Elmish like syntax that uses yields interspersed with lets everything after the first let is not indented correctly yielding broken code.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

As in the other issue, I am unfamiliar with the Fantomas code, but would be willing to try with some direction.

#### Options

Fantomas Master at 10/02/2020 17:06:53 - 31305c2b96e2e511b44459e879004e74ce1d6c06

Default Fantomas configuration

**Comment by nojaf** [comment]
Interesting, the `SynExpr.LetOrUse` expression inside the list should be printed with the `atCurrentColumn` helper function at first glance.

To have an idea how Fantomas works you can watch some videos on [YouTube](https://www.youtube.com/playlist?list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K).

As for this case, I would start with a failing unit test in `ListTests.fs` and try and find in the `CodePrinter.fs` where the `SynExpr.LetOrUse` inside the list is printed.
You can do this exploring as part of draft PR and I can guide you along the way from there if you want.
