### ISSUE TITLE
[Feature request] Optional: Indent with tabs, align with spaces

### ISSUE THREAD

**Issue by ShalokShalom** [fsprojects/fantomas#1194]
I propose we add the optional feature to use tabs for indentation and spaces for alignment. 

## Pros and Cons 

The advantage of making this adjustment to Fantomas is that both the benefits of spaces and tabs in the decade long epic question can be delivered.

## Examples

https://dmitryfrank.com/articles/indent_with_tabs_align_with_spaces

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [X] This is not a breaking change to Fantomas
* [ ] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Hello @ShalokShalom, tabs are not supported in F# so this request does not make a lot of sense.
Even if they were, this change would impact the entire `CodePrinter.fs` file so the cost would more be XL or XXL.
I'm not convinced this would benefit the project.
