### ISSUE TITLE
Downcast operator doesn't get a new line 

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1203]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbWA7A5gWUQBcALBAOQEMBbRAHSwgk1wEEAnHAVxq0PsbDMc7Lj0IAmeigD8APjAAZAJYBnQgB4ARrFjpZkADTgoKooSW4VqMAG1jEUAIiQAJIQCeAB2RpIFwob2jK4AbhTonD62QQIADEZOwQCSWEi8AMpKAF7ICYlgACwxYAC6QQC%2BeQ7Frh7e1n68gYmh4ZHWdvlgAIxVTpB4FAAeyliICoi4JM35AMyxxWUClUGO-W5eUZDaujMCrRFRnfniffvpiFRKcMwshACiqQDyAGajucUQL%2BGmixV9a32G3qvh26D2wRcYUOHU%2BYFmZ2C6U8FGgiAAQogXrA2IgAAoUNjUIiINgQgSENiRP7LAE1YFbMHkqBQtpHOEFRHOZGojFYnHjWAAd1J0AophSIVgYvM2GZEEp1MSS0YKwEgMhdUZOnBiIO7TQx0SAFYuVAeWjMdjcQBVTzeNhiiVYKUypRys2KxA01V0loMhpMvWsmGGuEANjNkAtfOtiAAwuhxSp49g1FToIQcfKwN90L9lf9VvStYGdcz9eyugB2KMxq0CghUTSknN5gtOFUQNWMDXOAOg8vB6EG6JdAAcdZRlv5uNTzBzXp93b961Lg92w7ZsK6AE4p7yWC9CKTU1QqBRF1TvYXacX-euoEH6SOq-luvE4dHp7GBRcrjcHpwkut6%2Bvea6bGWm4vtuYZdN0vRfjGR4nmw-7XLoQFdCBnZFuqJaQRuuowaGY7vqcX4pGkhBPFgAAqbDuAA6ko0xmu2N64Xe%2BEPoRT5DiRo5Gk43QIkhP7sLAnCpAAIog6BKFcqFXkqXFgTxEEglA-gViGQlwt0nJfoMQxJC8dHEJM9z5og6SkGwhAsfAbEcgsoEruBQKPo0ARbqRwkCN0prGcMKQvEoQxPA6FBZmw9xDJ4uIqCo7pYDmxpuWpHkaV5fE%2Bbpr47u%2BkYhUMZCIEKCljGFEVRaSMU4vFiWIMlqVkNwLZsK8SQnlQVhmt0y5gD21S8VpkBUJw6DmFViAAGI4hehCoXRkF%2Bfp8G1sZU0zRYiA1UMeA7Uos0LWwS3KVG0DEISqKoQA%2BkKSjOcQkBDSNYB9iy3k6etb6JN0k6lQASogcBsPATkuV0BSZQIXbDauuXjb9gn-SJ%2B4g2DOLwO1zakt1vX9QZ71I5qeWTdNJ17WdF2kqt9R-UViTiJ%2BXSQKD4PwEdVOnYtMWXV%2B123ZmpKPc90yk555Mo00TNwSciHsyZ7BEu4TxsMoahQ69Zqw1LOUy1sqP%2BoVCssxRyvDKrFDq5rqiEHjnWE5cxPwQbvYEeNlO7WMtMC-Ta1o8zTjiGJ7M23bWuEDzvvzfzy2tldN1EqLbDiy9b3uYj0v9j9cvB%2BbodGVbQwAGpsuiFjwBYOA6zm%2BvZx9X21HlJvrGbZEs8FpdzdJmapVXqS1-Xetw4wCPN17xsF6bsFd6HJWlzJsCEAA4kQTVJSl2Cj3CGUe6NmnatBc-%2BXC4hbcrx2zeimDQAA1uiqcP0QKi0ekxLztwaXsT8nHwzwp7MaJ9iJnw2icIG7NyqVT2piQgIpJgM0QHJcKWBWKpRYKkJsnU3b5A4ofT608oJgI7vPAKjBxCY3ZgAaUQIgTwZkLKTBSJ-Gg7w2z-0IS3Ac2lZ5kPPl0eYUYTLWSuCoYge8YbjwgJPMmec8rPnAejAQswlb5GjLXdAiARDcEmI5RAmg8AIA%2BF0AhTd5HfUUQJZRIdVGWw0SwBSOAsB9ywAPbAmQXExU4LiOisAqL6JiqlFSACJ5AKPsjUBBVyFwlmOHRx01SRYGCSEQUuAcGklQRYDBaZQncOIURGJgi5glw0TJVQFBNDaLEaoYg6R3C8GGPkixucrHjSUQIiBiRZg9w0ekSk1wY4mM4TZd6xgSh5D8CoOaKVrAEPKEAA)

#### Code

```fsharp
longMethodName
    longArgument
    longArgument2
:?> List<bool>
```
            

#### Result

```fsharp
longMethodName
    longArgument
    longArgument2 :?> List<bool>

```
            
#### Problem description

Note that here I've collapsed the line length to something ridiculously small, so that my code sample would hit the line length limit. In our own code, we have a sensible line length and just some rather long lines.

The formatting we would prefer (analogously to how `|>` works) is:

```fsharp
longMethodName
    longArgument
    longArgument2
:?> List<bool>

```

This is question 1 from issue #1189.

If you'd like us to enter this into the GR style guidelines, let me know and I'll do that. I think this `:?>` placement seems pretty uncontroversial.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 10/23/2020 14:47:21 - cda111ea873f3373706e2e11fa2a39e3e1451884

```fsharp
    { config with
                MaxLineLength = 30
                SpaceBeforeUppercaseInvocation = true
                SpaceBeforeColon = true
                SpaceBeforeSemicolon = true
                AlignFunctionSignatureToIndentation = true
                AlternativeLongMemberDefinitions = true
                DisableElmishSyntax = true }
```

**Comment by nojaf** [comment]
I think we can indeed identify this a stylistic bug, `SynExpr.Downcast` is now handled in a weird way.
