### ISSUE TITLE
Fantomas & Friends

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1206]
As part of the `road to adoption`, I will be hosting a talk show called "Fantomas & Friends".
Where a special guest and myself will be pair programming to solve a Fantomas bug.
Warning: experimental format but it could be fun ;)

Our first show will take place on **Thursday, October 29th 20:00 (UTC +1)** with guest @WalternativE.

Microsoft Teams will be used as a platform and we will paste the link in this issue an hour before we start.
Afterwards, the recording will be posted on YouTube.

I hope to see you all on Thursday! Looking forward!

**Comment by Smaug123** [comment]
October 28th (today) is a Wednesday - presumably you mean Thursday 29th?

**Comment by nojaf** [comment]
Yes!

**Comment by knocte** [comment]
@AlexTselikas you might be interested in this ^

**Comment by nojaf** [comment]
Link to meeting: https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Fmeetup-join%2F19%3Ameeting_ODYwNDkxYWUtZjU1Ny00ZWIzLWI0NjYtOTM1ZjY5MjM1NWYx%40thread.v2%2F0%3Fcontext%3D%257b%2522Tid%2522%253a%2522edd1c3b6-be87-43bb-92d4-7a911c5cee17%2522%252c%2522Oid%2522%253a%25224f969602-91a5-4bbf-96de-6a8a7115fb8e%2522%257d%26anon%3Dtrue&type=meetup-join&deeplinkId=a0a5717d-75d9-4445-8416-0ea4b25b0485&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true

See you in an hour ;)

**Comment by Smaug123** [comment]
I enjoyed this, by the way! Even aside from fixing the actual bug, it was a great opportunity to ask random questions about the code we found ourselves in.

**Comment by knocte** [comment]
By any chance was this recorded?

**Comment by nojaf** [comment]
Link can be found at https://youtu.be/tctK7v00zw0
Thanks again @WalternativE and @Smaug123

**Comment by nojaf** [comment]
Our next guest on the show is @baronfel!
Join us on **Wednessday, November 11th at 16:00 (UTC -1)**.

![Fantomas-Friends-Chet](https://user-images.githubusercontent.com/2621499/98439984-1fa6c980-20f6-11eb-915a-801eea63c7fa.png)

The meeting link will be posted an hour in advance. The recording will be on YouTube afterwards (hopefully better this time 😉)

**Comment by MecuSorin** [comment]
https://www.timeanddate.com/counters/fullscreen.html?mode=a&iso=20201111T17&year=2020&month=11&day=11&hour=17&min=0&sec=0&p0=49&msg=Fantomas%20%26%20Friends

**Comment by nojaf** [comment]
Link to join the meeting: https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Fmeetup-join%2F19%3Ameeting_OTNjYmYxY2QtNGE2Ny00MjIyLThjM2YtYzQ5ZTY3YjJlNzM1%40thread.v2%2F0%3Fcontext%3D%257b%2522Tid%2522%253a%2522edd1c3b6-be87-43bb-92d4-7a911c5cee17%2522%252c%2522Oid%2522%253a%25224f969602-91a5-4bbf-96de-6a8a7115fb8e%2522%257d%26anon%3Dtrue&type=meetup-join&deeplinkId=2bd4135e-2775-4297-8ae5-77a4c78a8122&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true

See you in an hour!

**Comment by siwatanejo** [comment]
was it recorded?

**Comment by nojaf** [comment]
Link can be found at https://youtu.be/fcY2iT-Iubg
Thanks again @baronfel and @Smaug123

**Comment by nojaf** [comment]
Our next guest on the show is @theimowski!
Join us on **Thursday, November 26th at 18:00 (UTC+1)**.

![Fantomas-Friends-Tomasz](https://user-images.githubusercontent.com/2621499/100009351-16447f00-2dcf-11eb-9a8f-fc6aa296cfab.png)

The meeting link will be posted an hour in advance. The recording will be on YouTube afterwards

**Comment by Smaug123** [comment]
I'm afraid due to a personal emergency we've had to cancel today's show. We'll let you know when we can run the next one.

**Comment by nojaf** [comment]
From time to time, we hang out on our Discord channel: https://discord.gg/sqCBuax3
Catch us there!
