### ISSUE TITLE
Format in pre-commit hook

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1207]
As mentioned in https://twitter.com/rastreus/status/1321296796124143617?s=20, how can Fantomas be used as a precommit hook?

On top of my head I think the [local dotnet tool](https://www.nuget.org/packages/fantomas-tool/4.3.0-alpha-002) can be used for this. However, as I find this a good question we should write something out in the documentation to explain this.

Also mention in the docs that `.fantomasignore` file exist in case Fantomas is not able to format the file for some reason.

**Comment by nojaf** [comment]
@rastreus this seems to work for me (on Windows):
```sh
#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.fs" "*.fsx" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Format all selected files
echo "$FILES" | xargs dotnet fantomas

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
```

I stole some code from other places so I can't really explain each line 😅, but the `dotnet fantomas` part is doing the formatting.

**Comment by agentlewis** [comment]
@nojaf i wrote something very similar this once take the hit diff and pass only those files to the shopify cli for deployment.

Basically:

Line 1 gets the changed files filtering the git diff
Line 2 passes the files as args to Fantomas executed with dotnet
Line 3 stage them with git

I thinK the way to to this in a more automated way will be to create a [git hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) that runs the lines 1 and 2 of your script as a ‘pre-commit hook’.

That should do it.

**Comment by nojaf** [comment]
Hey @agentlewis, this is the content of the `pre-commit` file, so it is already a hook ;)
