### ISSUE TITLE
Named string argument to type provider requires a space prior to '@', which Fantomas removes

### ISSUE THREAD

**Issue by reinux** [fsprojects/fantomas#1209]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WA4gE4CG2AFgLYA2YAvGABrUAKhsAbgJZKEA8AytDKIKxegAEAOpDLp02FAHpFAcxLlqAOjWky8EgHdOAOxWbYhFYoAe1YwGdFARk0AGVespUAtPfSEAV2h0AMJETWt7eGkAPkgAGnAoe0Q5ExV7VDAAbSSIUAhCqAASLFwsyBN0BLzCyGL2YioA5DRcoqLXRI66gEljJGN0fk4AL2RunrAAFlqIAF1agF9J-LmSstaoKpqe%2Bsbmrfapp1WOyABZYmsAGRNEG8RTdDJdk4AmV3XFopXagvOpRwW0gACNYLAqG8ivsmi0ssceu8zjD%2BCJOHAqLBjABBdAAUQGAHkAGZ3YwTdYQElNFLfZZnAEwoHlNBgiFQlElA7wtpUsAAZi5EEg-GwxGgiAAQogSRZEMxiCQKKlEIRoR1-C16b9Get6psKuDIRqRQ04Ud%2BdNhVAxRLpbL5TdYAY1dBiCl%2BuxYO70JxsabClrEDrCn8iky6iyQcbOfrzYcEfyAKw20XiyUyuVhACq2FwhHdnuM3t9-uMgeptJDPR%2BYb1e2jRo5gdhib5UzAADY03bM46wgBhKge%2ByD7F%2BQLBCyVsA0qh02sM-7xw1s2OthO8nL8gDsvYzDuziAuIlBatn88XHTrEHDhUjZrXUA3XLb28RHQAHAf7Vn5eOWIVjaV41jey4RquwLNiab5bpanYAJy-pKOIkugarjhQoizsGoZ3g2gLPuysHxjyCEnF0-Lpn%2BA6IGiFAYpCAYgdW%2BFgPeayNsRr5kRaSadk4pzUX2iBoRhhAMUxQG4YEYFFLeHGEcyPEtnB5ECR8ab9IM6BEsYAAqhCYAA6pwLyXmxS66iu3HQeual8e2O6CUKImHjibABAMAAiiBUJwjESbJ2rWfWtlEfZ2xDJuGkdic1rUVc1i9CSBnCMY%2BILvRZAWOgZnwBZNrTF8YUERFKlRZUMXqfx8U9E4qZJdc-Qkpw1hEgWxDoBY%2BLWNgYT2PY5azsmpXgTZkF2ay0XVLVzmfkUTg9s11gAHKIAYAUUq17WdWq3W9f1g3Ddia0BBQ56EKSvQYRQmQ2k47GcWAj4bFVFABFQfrbYgABiFiiHIaoGdB80fvyTj7klX0-fcu3WBcsOcL9AOEEDwVpkISoShJAD6RiFa8z3KVGxE7ODFENT%2Bq0AEqIHAhDwAVRVWuNCkQQ%2BUEzdVc1ORDgnIXTDMWPA52XWqN13Q9kMkxVZMfcjqOA91Emg%2BUlOaUiVGdpA9OM-ASPfSj9xoxjF5Y2QOPBGqBPcBZctTZFPMU-zVMdO8wm68lnkkJgRKEHcfgs68xXs4UikvW9BpVa7jZxS5UzvMiq2%2B8Q-uB5wfji1dUsiDLgmO1z00gp9xvK%2Bjqsg2Dbtax7bm62nGdB%2BgRtwxSZtV%2BqlvW-jhMO2VSny0%2Bsc1bX9Ue4l3vXAAahaUomPA6Qh7OJVF1xzsgnHgIJ4thTvE10-WH93nBOWC8DMv9uh2z6%2BvdzW9j-HdWJ0iK1Hz5sDoPgqR9QNiBDXLCvG0Y077RybA5Uiz8Fr8neNDb2St7hSixNAAA1lKEgaDUj2H0vwYgKpAIXWAvyUCYCH4wTjNAgWScaa6w2ltJBqRXRPHVogPybVjDmXLDiAYp4JaEALlMUhg8o7kMgZQneL894QHeELXWABpRAiBsCpXSk8foeCVTkkpJ2YRE1wpO0qi7J%2BkiYGdgFDrKYlxrhZUYvYMgwDb4iNJiPHmvEqHuyKAKL2ViRimCoGJSwF0nj5UQKCC4CAdFCKsvo8qhiFZuMch4uuXiU6NwCioYwJ9jBn2xCMTJ3VQiIAMrAHSITuojVYtlMhJcKGxSkfyAUDcrE4m%2BmqYwFT2APGxCoPhV12EmC4ROSy1TnHD3eokqBpjqE9AFFPKxPks7EFBAE2xWcyD8EwEMa4Izrwc0msXTedTNYTy8YfXx-gMSt0ibs%2BSEdlhJHmJMSo9g-rDSyKQpYQA)

#### Code

```fsharp
type Graphml = XmlProvider<Schema= @"http://graphml.graphdrawing.org/xmlns/1.0/graphml-structure.xsd">
```
            

#### Error

```fsharp
Fantomas was able to format the code but the result appears to be invalid F# code.
Please open an issue.

Formatted result:

type Graphml = XmlProvider<Schema=@"http://graphml.graphdrawing.org/xmlns/1.0/graphml-structure.xsd">

```
            
#### Problem description

F# requires the '@' to have a space before it in type provider arguments. This makes sense, as `<@` is used for code quotations.

Weirdly, the compiler also requires a space even if the preceding token isn't a '<', e.g. if it's a `=` or a `,`.

I think Fantomas is behaving correctly, but unless the fsc parser can be fixed by 5.0's release, it may be preferable to work around it.

If you agree that this should be addressed by Fantomas, I'd like to try tackling this bug (along with the other disappearing comments one), but I don't know if I'll have time to study Fantomas' workings for at least a couple more weeks :(

I've submitted an issue on [dotnet/fsharp](https://github.com/dotnet/fsharp/issues/10358) as well.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 10/26/2020 19:07:04 - be9212d13e2c7c12002f404725e59f440cae29a3

Default Fantomas configuration

**Comment by nojaf** [comment]
I think we can extract [firstItemHasAtSignBeforeString](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L3833) and re-use it to solve this issue.
