### ISSUE TITLE
Access modifier is lost in `extern` declaration

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas#1213]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBtAPAEQDa4EkBbAB1gCcAXACgB1IBrRcgO0VwGYAmAOnn3oBKAHwBdWuVpsAHpWYswAVQItKABUrkwJcgEsAbgEM5YAOKJ15WNEQBnWwAlEhktUGQANOCi2LlXSwA5raoYOjeEKAQ0VAAJJQAniTIaJABlJ4R0ZCxRrgArilhWTEADF4xMZAqSKoAyroAXsgVlRAALCVgolkAvq2RXTmJyaFpqpltOXmFoeFtEACMA5WQALKG0gAyAYhbiEGUABaTC4tcpV09Mf1ZUavxSUWQAEawsLinVbmGBUXzCy4KyqdUQRF0cFwsBYAEFKABRFjwADyADMdmwvpVUb9fFc%2Bit7t8Rs83h8sRBpr9ZmgAW0OMDsnUSIYbAAhRCoiiINSGciGIgWZgU6KaQr4m6EoaPUapMmfRlUv5zLodRmU5msxAcrnkPawADuzGghl8Kn01mMumhIogYsQEuitxiROyMtJ7wV0pm-1VYAArOqoJr2ZzuYoSMlyCazSwLSb-DagzjcHi2tcnVKpu6xvKRUqacUFmAAGxByAh7VhvUAYVwptsNehtjF0EoFFtYBTacqGYgzuirspOblnvzP2VtL9AHZy5Wddy1mCXsLk7iHemCXdpSTc2PFRPC3TKgAOOcs0O6xBNqEsTvdje9rcundPPfkg8%2BlXFgCc561MKonI5BNkQRCGJ29qOv2WYPLuo4ft61K%2BsWizlH6FYXlWV6guCkJJn6D7QWAA6DNm8FQHmn7Id%2BZzLBhlaAcBuEQh8BHFlBm6Stu5FvghXrZl%2BU6oUCGE1AclDIiwAAq5AJAA6roxz3uuxGkWAQ5xBRrz7khk5FmcDIMVhMJWPkSLYOwujgsBkHkOKXGZjxcF8VA6TjkJBltIs7Tlhs0gEKi0lHAc8KpogdRHBQlCKfAylBu0lyOTBznEq54wZNR%2BnHjEiyBhh-kqKiujSMiUbGBQ8LSDodi2Nad5Bv6SVPtxL68bKbkTFlR5%2BosZYFZsAByiAGrguxFSVZXMBV5BVTV9j1YN%2BRECu5BogQchECEQaLGpsFpR1kBEPkuD%2BGNbAAGIUOBlDAdJb7dShZyzgVJ1neNLDFdIaxvbo52IFd5A3bZ5bQEcfKssBAD6Bq6HFJx7albrae5j20d5Z4DdIABKiBwOQ8CxfFfqJYjbUuYdqN6T1qF-ljuP4-AS0rcw62bdtvVk4Or6Hcdp1-bsgPA8w92jGjwmAuhxaQAzFDwD9-P-ULxggxhYMQ22zAw3Dylc2RFPPFTgk0RLbRcPR0v%2BaZ-IJMi5A7C2RMnAlzUxH2JH7cj6VGw8nk5dEXCiZbmzW4Ytv27oLbM6tbNghzqF6xpPPPHz72XddKsiw91NPWbRnS6H4cO5QCtpwDGe3auavg-ymvkNr8OQInmnDN7XU5%2BjlRcL5WMAGrIWyATwAEgRO52pPJR7SPDij7fG9lfpcPlwfSBd5ltvVg9IiPY8u83ydjD73x%2B4v-Ur9gsCUOYCLVXqC3QrvfpNfv7Ueoh8804CL2W79-1slC0AGBslrkwSgtgpJ1AFNeD4y0GqEVUpPdSLcRyUV0h-XOXdMbS2GqNXYHJKBGgOKLRAlliosCUvVGESIlws3IPHBYRFEGexnulKiHdTZdzptLAA0ogRAJBArBQOCoSBgoMQtHgeFF%2BBtD5z19ibLylQOBSwWOsTYYVwS2COI-YsE8WpOXJgdN%2BAl5EL2LBwC2qiGhBFwIgUygRloSXkogF4awEASOLIw-RKVDFe0Omw9BncYjcHLDCMagQWBrxYBvaEDQInGHyHqaSsBxKqCtOxBhCDvFT18Sw-xaDTGf3pPnVRYTgIsCtPofUQQaGrVIQEChzYVJSKYdPLSrCCnHwUf7CAHAe7S2wJHQwLxbEaMjkcOoCQ0nSGaT2N2z5uav3fCYrpZiFgcGXlYzQEIS7uNmY%2BeZNxvCiFaGkWwF06qhCIr0IAA)

#### Code

```fsharp
[<DllImport("kernel32.dll")>]
extern UIntPtr private GetProcessHeap()
```
            

#### Result

```fsharp
[<DllImport("kernel32.dll")>]
extern UIntPtr GetProcessHeap()

```

The code is taken from [Lib.fs](https://github.com/dotnet/fsharp/blob/05b0569a7d6acefd21ad31bce49f780d961db651/src/fsharp/lib.fs#L505).

**Comment by nojaf** [comment]
The AST I get for this is:
```fsharp
ParsedInput.ImplFile
  (ParsedImplFileInput
     ("tmp.fsx", true, QualifiedNameOfFile Tmp$fsx, [], [],
      [SynModuleOrNamespace
         ([Tmp], false, AnonModule,
          [SynModuleDecl.Let
             (false,
              [Binding
                 (None, NormalBinding, false, false,
                  [{ Attributes =
                                 [{ TypeName =
                                              LongIdentWithDots
                                                ([DllImport], [])
                                    ArgExpr =
                                             SynExpr.Paren
                                               (SynExpr.Const
                                                  (SynConst.String
                                                     ("kernel32.dll",
                                                      tmp.fsx (1,12--1,26) IsSynthetic=false),
                                                   tmp.fsx (1,12--1,26) IsSynthetic=false),
                                                tmp.fsx (1,11--1,12) IsSynthetic=false,
                                                Some
                                                  tmp.fsx (1,26--1,27) IsSynthetic=false,
                                                tmp.fsx (1,11--1,27) IsSynthetic=false)
                                    Target = None
                                    AppliesToGetterAndSetter = false
                                    Range =
                                           tmp.fsx (1,2--1,11) IsSynthetic=false }]
                     Range = tmp.fsx (1,0--1,29) IsSynthetic=false }],
                  PreXmlDoc ((2,6), FSharp.Compiler.XmlDoc+XmlDocCollector),
                  SynValData
                    (None, SynValInfo ([[]], SynArgInfo ([], false, None)), None),
                  SynPat.LongIdent
                    (LongIdentWithDots ([GetProcessHeap], []), None,
                     Some (SynValTyparDecls ([], false, [])),
                     Pats
                       [SynPat.Tuple
                          (false, [], tmp.fsx (2,37--2,38) IsSynthetic=false)],
                     None, tmp.fsx (2,15--2,22) IsSynthetic=false),
                  Some
                    (SynBindingReturnInfo
                       (SynType.App
                          (SynType.LongIdent (LongIdentWithDots ([UIntPtr], [])),
                           None, [], [], None, false,
                           tmp.fsx (2,7--2,14) IsSynthetic=false),
                        tmp.fsx (2,7--2,14) IsSynthetic=false, [])),
                  SynExpr.Typed
                    (SynExpr.App
                       (NonAtomic, false, SynExpr.Ident failwith,
                        SynExpr.Const
                          (SynConst.String
                             ("extern was not given a DllImport attribute",
                              tmp.fsx (2,38--2,39) IsSynthetic=false),
                           tmp.fsx (2,38--2,39) IsSynthetic=false),
                        tmp.fsx (2,0--2,39) IsSynthetic=false),
                     SynType.App
                       (SynType.LongIdent (LongIdentWithDots ([UIntPtr], [])),
                        None, [], [], None, false,
                        tmp.fsx (2,7--2,14) IsSynthetic=false),
                     tmp.fsx (2,0--2,39) IsSynthetic=false),
                  tmp.fsx (2,0--2,39) IsSynthetic=false,
                  NoDebugPointAtInvisibleBinding)],
              tmp.fsx (2,0--2,39) IsSynthetic=false)], PreXmlDocEmpty, [], None,
          tmp.fsx (1,0--2,39) IsSynthetic=false)], (true, true)))
```

The access modifier should be the first item of SynBinding but it is not present.

```fsharp
Binding
                 (None, NormalBinding, false, false,
```

Am I missing something here or is this a bug in the compiler?

**Comment by auduchinok** [comment]
Yes, it seems access modifier is always ignored here: https://github.com/dotnet/fsharp/blob/05b0569a7d6acefd21ad31bce49f780d961db651/src/fsharp/pars.fsy#L2634

**Comment by dawedawe** [comment]
@auduchinok @nojaf I think, this can be closed. Current fantomas/fsharp keeps the access modifier.

**Comment by nojaf** [comment]
I tend to close issues that we can no longer reproduce with the latest version by adding a PR with a regression test.
Just so we ensure it stays fixed.
