### ISSUE TITLE
`extern` declaration inside type declaration is converted to `let` binding

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas#1214]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAKgBQCUYAvADoBOFAdhANoA8AIgDZsCSAttrFekIVIAa0RVaiNgGYATADp4HYcQB8AXWp0IiAB7px9AKqda6AAroqYbFQCWANwCGBsAHFEFqrGiIAzn4AEohO2CSQADTgUH6e6Ha0AOZ%2BqGAM0RCgENlQACRYuKmQCeiRGdmQuc5sAK7IaOk5OQAMUU0VpkhmAMp2AF7Ibe1gACzlEOrlAL5DmeN5BfVQJWXtldV1qY3DAIyzTZAAsk66ADIJiKeISegAFqu7ss3zkzkz5VkH%2BThLkABGsFgbAeOXWTlqS227Vk%2B1B3UQ3DscDYsFoAEF0ABRWjwADyADNzpIQU18eDYi9pvtPqDvoU0P9AcDYXkNpD5hBpCyIJButgnL4AEKIfH8RDmJxUJzcTziEk5Kx1SlvanzSqLIoAoHy1ngzYNDmjblQPkCxDC0VUS6wADu4mgTlipgcPhcdlROogisQyuy7xyNIqdN%2BWuZaqqevZwzAAFZjbz%2BUKRWKjNhcFQHU7aC6HfEPcayWwKe1Xn7VWtg5qmTqwRCtoaAGzx01Jy2IADCbEdfnbqL8iug6H4nrAheLTVLEH92UDPMrDNDNYjdYN0YA7M3E%2Bbk1bDgi-nKC%2BSfSWqR9wxqF9WWbX9WlDQAOTdmi1i3so2gjscnidngMXn4q21G9lzvKEmgATmfXw0XxAwqF7bhuCcEdvV9Kdyy%2BS8oEXEC2XraMdlaQ0ExfHdEHhRFkXzQ1v3QsBpzmCtsMZYDw3w1ddj2EiW0QWD4MopEgRo6M0NPFVz2YwCrzYisOPvQiYRIzprnQXFaHwKhMAAdTsO4v2PejGLAWcFmknDr3YyMCN2LkeK3NFvBqHEWCkOxEXg1CqCVcSy0krDzOKMwl3k8Cch2EZ42OXROHxfBbmuTEiwo25%2BHQXT4H040RmeXyMP82kWJWPDrM49odjjEjotMfE7F0XF0xcfhMV0Wx-D8d1P2NGNct-CT-yk%2BllmCkqVwU3Ymyqk4ADlEBtNgLhquqGvEJqqBatqAk66aam4A8qAJTgDG4FJjR2IzMMKwLuBqNh4gWyQADF%2BGQ9B4PwQDRrAw0dg3KrbvuxbaFq3RDgBuwHsQZ6qFezz42gW5JQFeCAH0bTsTL7gugqgyKkarLGsLsh2J8pt0AAlRA4CoeAMqyw0cuxgaAqGoLSi%2BqNdigsnKep%2BAdr28RDuO06fqZmcANZm67ohi5odh8QPsKDmbOhYjo0gXn%2BHgMGZch%2BWXDhkiEaRwdxDRjH9PFpiWd%2BYqCe%2B6NZG4jXoscqVMFxKhzn7On7my3qcknBjLtxwL7bk0rxuhJTXZOd2nE9727H7AX9uFhFRcI62TMl35pcBp6XsNxXPodznoTsjWE6Tn30F1wuoeLt7D2NxGpTNqgLcxyAc9M9Vw-xyPCcNWRIrJgA1SNBQSeAEkSP2R0ZvKQ5xuc8fZ8vVaaWRKrj3RHucwdOpnnF58XgO%2B7zooI6%2BULR8m-eWFgdAPCxVqrS21EL8NHqr8GkMllh6O2GLIP6rtwaQ0FCiaAIhBQdzEOgPw6lujSg7ECXaXVaKGRXsZfu84LKyTvlHImEBZCkw1rNeaFxhToDtNcJWiBXK1VoHpTqaIcR7kFlQLOww6K4NDuvQKuEt5lR3tzDWABpRAiBsCxXitcUwqCZREkGNg5K-9bY3yHsQke0ZpDq2GEcE4SVER%2BFuD-aMy8%2Bp%2BWZldVmIjgEVyaNIF2RjehJDYHxKgiRdqqW0ogP4hwEBqOjPwmx%2BU7FhwcUA3RID2hyHjGiBaiRaCH1oMfVEvRUkuBqFafAsAVJmDdCJPhOCImryiUImJRDaT330VXIxyT4K0DdA4a0SQuH7WYQkNhfYDIaIEWvMyNSwxOO3jkaQ48NYsBTk4P4XjTEp1uN0TAxTdADPHEHP8EsAFATGXE5xky97uKsEieuITNk-m2W8aI6ghjFD8I9DqqQ6JTCAA)

#### Code

```fsharp
type T() =
  [<DllImport("kernel32.dll")>]
  extern UIntPtr private GetProcessHeap()
```
            

#### Result

```fsharp
type T() =
    [<DllImport("kernel32.dll")>]
    let GetProcessHeap : UIntPtr =
        failwith "extern was not given a DllImport attribute"

```

**Comment by nojaf** [comment]
This is available in the 5.1 series.
