### ISSUE TITLE
`extern` with `void` return type is converted to `let` binding

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas#1215]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKiAeAXRAnAdmAG6wCW8YA4olgAq6zSIDOzAEogIYAOAFAJSQANOCjMaWUvgDmzVGADaoiKAhqoAEiwBPbsjSQpWYcrWQNRTgBsArvsWn1ABhHr1kAJL4k%2BLAGVSAC9kVzcIABZHMABdUwBfUJUo8x09eUNfEzDzS1t7JTCIAEZEt0gAWU4MABkpRGrEGSwACyzCooAmJyjY9QTTVTKtXXtIACNYWCs29wtrO3kCwo7S9z9EAFtSOCtYfABBLABRbwB5ADNa-BCoiHPrcR740sHZ1NGJqZmzObzF27AAGZVmY-NxOEwAEKIc6wXCIWicXCcDY0PDfdRYXB2J59F7JYZpAyfaYgnLzfIA8IgiCQMEQxDQ2Hw6qwADueGgnHEXhIXMkewxaixOLCvTU-XUrx%2B73SJKF5L%2BaCWYQArDSoPSoTC4YgAKrcPS4Lk8-B8zgC-BCu4PRC4iX47KEj6TUkE3ILZUAgBsGrp4O1zMQAGErNzmMG9swRdAsHDrWB7lZHmLngMCbLia6Fb9PQ5CmAAOx%2BrWMnXw8qbMbojVJlNucUQSVqaW051y7Nk3OUgsADhLAbLQcjuyttdt9qbjqGmag8q7Hp7hQAnAOGftzjhcJGNhtOAmRXbU3j007Z%2BNO%2B6Kf8C0UXAD-Qymbr1lsdoLx8mjw201KMyMOy%2BBdry9W8SgfUsNy3V9timD8AUPScwGbJIzwArMgKvJV83aFYHy8HwsFOfAABVcG0AB1UgWgTOtv3URtkOnN50LnS8nUXG92mBCDB32BgbG8AARRArFILYtwPbF6LURiULAVtNHPIwc040D2mpB9KgwDxzhI5pGiOL8-GaOEsCo%2BAaI1cJumPB1TxnViMmMYDsJVNwinVLSqi8c5SAwU4jQtOEjgwbh4VYUh4ILVVbJ-E8-zQokoBU1y83c9Qil9byMAAOUQNkxOuXz-MCvBgtwULwpYZgovwXKbA2atcAuDwcA2OQNSKJD5MUlInI2GwrEkIrEAAMThPcsC3EiALSpcwiKYstKGka6hKjBylW0hRom3Apskv1oGaJEIS3AB9NlyBonrmJlJzUqw9KASKfscoAJUQOBcHgCyrKpOKGN-Ft-2S5zVJAnDFtXD6vrheAGqavBWvazqXtuhyWLBwbhp2uo9oOvBZrSeauLCLo-U%2B774C23Hdsmi1DofY7TtjPBLuu1oMcSxywcejjIYytQOnAgsKiqfjkW0U5cFqaM-taazAdk4HUN50Z%2BaGNSobcDo8LF7TJc4aXZdIaNEealHNjR29uZBpLRhxtbrgJxmibmp6Ft1nixaNk25awWnnfGhnpprZmTuRNncA5yyubsqdMfuvnMlJ9Tyc0g2qgANQpSEpHgKRpAVhMbLttWsY11PPbJ3WvKzjAxsE2M6vz7wi5LpXy4U0Gq5cmv0917KG6E2AsGoY4woi2q9k7gFYu7vr2wwt0BbcgEOmWg3ttGyFdmgABrSEo4PmhmGIvwURDKZGrHAE6MX3vANXrXBY3t6xfywq6mhLAOUaYmiARJ%2BXwNROq%2BxvCViRrgG2hQH4JyYknNs555wDx1uoDoMMxYAGlECIG4LpfSjQvCX1RFcG4BZ4HxXsjzSu6RNazG1kLCAgJ7wNyMlsZgzQ54FjLgg3qT8V4Q3XgWQEotCh0iLlYRA-FpCNUaOZRAYxygIAoXAic-C7rIKcqgtez1RH6wkfsMS0h8BN3wC3PYARTEWhsPCEisACIKItHVWiGjqGJ1ocnF0mE9Fe3UICH2Rjhp4HwC4og9Q9jSCgc1YBUgwFRjcV%2BR%2BDtn7CP0YUQEmcJFCTNpwMY0iOFm2aH4bQvgqhJPrEDBK9t1ZpLTugtQgJ64SL8FibYgdVGVJkhAOSohoihEMMwMatV5APziEAA)

#### Code

```fsharp
extern void GetProcessHeap()
```
            

#### Result

```fsharp
let GetProcessHeap : unit =
    failwith "extern was not given a DllImport attribute"

```
            
This is a special case in the parser: https://github.com/dotnet/fsharp/blob/05b0569a7d6acefd21ad31bce49f780d961db651/src/fsharp/pars.fsy#L2709

Return type may also have custom attributes:
```fsharp
extern [<A>] void GetProcessHeap()
```

**Comment by nojaf** [comment]
This is available in the 5.1 series.
