### ISSUE TITLE
`extern` C-like parameters are not supported

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas#1216]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKiAeAXRAnAdmAJb5ZgCyAjABQlYCUAOro-s65jgcaRQEy1eRJizajOeQnQoBmagG0APAEEAfAF0eZYezEdskrRQAsgrPM07Ruid2nkArGYBUxEaxsG7vR2YBkbrqeXFI%2BTgBusETwrlYe4l6hZOQAbNSR0bGUADRgGTHEfPSQ2eBQAM6IWFgkAOblqGDyZRCgEO1QACRYAJ4ADshokHQlLe2QneEAhgA2AK6DTWMdAAylHR2QAJL4SKQAykQAXsjrGxDGy2DqYwC%2BZ61XE70DjcOko%2BcT0-OLzecQHJXCCQchTDAAGRIiAhiHwtSwAAtPgDKHwVlcbh17mM2htnv1FpAAEawWAzFGbSazBaNf4AvgPfH7RAAWyIcBmsHwyiwAFFdgB5ABmUPwp2BYGFs0qmLuTLxVJeRNJ5Mp42pvzpkpkTM2%2Bz6U2giAAQohhbBcIgAApTXBTVlVPDqjpYXALOXYhVPbqEt6qil6ro-WloennYxBkEGo2m82WmGwADueGgU0qO0iaZq3Jd7TdHvOWPaOI6io1yv9ZMDPpDf0lDijUBjxrNFqtAFU%2BgNcGmM-gs1Mc-g8xBpTNZUX5bifZWhgG898afWAWAUk3IC24%2B3EABhGbp8q77nlAvQLCW0dSmWIT0l71fX2vefVxea0NLVcAdg3W7bCfINliWdJtx0nDZiwgUt2nLEEnxVV8gyXLUw0lAAOX9DVbeMrWPLkR1Am87ygh98Xgqs1SQ98VwBABOTDY2UYUuGPVlWSmK8C1vKcvRnR85ygBcqLrbVV0oNZJU3LDtwTFl2U5XNCInbiIOnMtZz9F9KNrZdRNRIFVykxjmLwOSOXJRTJS44iwGgx5%2BM0wTEJ0lDP1RRlJJ2PYsEFfAABVcB6AB1IgkSvMCVI6SDbNIpVHJJZzHxE1CxN1SSt2UXBYDmXYABFEBmIh2S4Tj3Ui9porssBYK6AT3iwN9krc85KEjSSwQwLZhT8xE4T5ZT9kRS0sBC%2BAwqbYwMR4%2B8%2BLIuqRmE3SUtRRt2vBHZhSIDBBR7IdLT5DA%2BitcpyiISzVwcKbVN49SHOfKAFpcj9ww2Sh1zWjAADlECTQrxQ2radrwPbcAOo7EBOs78E%2BuZWWA3ARS2HBWQaJtKBsqqaoJe7IFZOYZhqP7EAAMUtdjqjwPy-UW1yXo6Sgf3a-HCehAGMHIZmiCJ0ncHJkqN2gRE7SNLgAH0k2iMKMdiit4sepKlua16MI%2BgAlRA4FweBRvGyVJul2a4px%2BWyKaun2koei1Y1y14BhuG8ER5HUcldHppIw3ZZxvGCa56Eeb5ynqaemjznRDd1c1%2BAOd97myaHfnJMF4XzzwcXJeRA3brmuWPhp57JT4AyAVBcFMvtHpBVwKFTx15EJquqK1JgjTjbzkO9LDjzDI68upkr6uiFPe34adtkXbErOW7uokfZZ8UA4ToPXnz0ONj4NLDL7gea6wGP55J%2BOKdwK8YCF%2B1U9wdOxsz92Ys9uD5vbhXacLtqe-BAA1ZcTRIeA6jrlefWd9MatyJCbKkZtC6rQ-hgYmOVzxQ1-rsABGcgGNwqs3eyOc24NVXp3de71YG5VgFgAA4lUMGx1TrckAU2S6U9sFGwQtpF%2BBdVx8EZj3TmRMTRcmgAAaxNBfARVRyi%2BX2A6Pc5JYYEUlBFRh1UwEURrGwteHQ%2BAq0Mt9X60IzRYBTHCKmAx8qbXwKFKGyhdiAQdrgCeAIFEgJlo-eKQkO7LTDlbQyABpRAiA%2BhdR6nCHYkjHRiglKuRx10ZrZ2YW8CBGooGrhkBJWB-V2TlERHQvWGCICVWcbVVxiVTaK3NhAGQxcviHHhDMRAmVaiwzhCNRAxJyAIAiQ4oiTiH6FJxm4tRBCOgyG7iXZQhVaj4HgfgRB3JDgTKHHMK0flYBeSaUOKG4UunRI9rEr2LDVElNfskzeoyCaSHWeERM8IbHw1MSQCxJ5NnKUUVjciWkDmQNKTqd%2BJdcpDymMSWp6Sh6In2D0Ug4InngSbjdaeOD9mNS%2BckmBJd9hug5HvdpULyp5LuGUdQZxhjlGJqdRoCjbhAA)

#### Code

```fsharp
extern int M1(int)

extern int M2(int i)

extern int M3([<A>] int i)

extern int M4(int[] i)

extern int M5(int* i)

extern int M5(int& i)

extern int M5(void* i)

extern int M6(void* i1, void* i2)
```
            

#### Error

```fsharp
Fantomas was able to format the code but the result appears to be invalid F# code.
Please open an issue.

Formatted result:

let M1 _: int: int =
    failwith "extern was not given a DllImport attribute"

let M2 i: int: int =
    failwith "extern was not given a DllImport attribute"

let M3 [<A>] i: int: int =
    failwith "extern was not given a DllImport attribute"

let M4 i: int ``[]``: int =
    failwith "extern was not given a DllImport attribute"

let M5 i: int nativeptr: int =
    failwith "extern was not given a DllImport attribute"

let M5 i: int byref: int =
    failwith "extern was not given a DllImport attribute"

let M5 i: nativeint: int =
    failwith "extern was not given a DllImport attribute"

let M6 i1: nativeint, i2: nativeint: int =
    failwith "extern was not given a DllImport attribute"

```

Related parser rules:
https://github.com/dotnet/fsharp/blob/05b0569a7d6acefd21ad31bce49f780d961db651/src/fsharp/pars.fsy#L2654

**Comment by nojaf** [comment]
This is available in the 5.1 series.
