### ISSUE TITLE
Clarify constructors

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1217]
I propose we align the way constructors ([SynExpr.New](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-syntaxtree-synexpr.html)) are formatted with both the Microsoft and G-Research style guides.

The existing way of Fantomas deals with this problem is not really aligned with either guide.

## Pros and Cons 

The advantages of making this adjustment to Fantomas are ensuring correctness of what the style guides dictate.

No disadvantages come to mind.

## Examples

```fsharp
let thing = new Foobar(a, b)

let otherThing =
    new Foobar(
        longname1,
        longname2
    )

let m = new Meh(a)

let otherThing =
    new Foobar(
        longname1,
        longname2,
        longname3,
        longname4,
        longname5,
        longname6,
        longname7
    )

new ParquetWriter(
    file.FullName,
    Column.Thing
    WriteProperties.make columns,
    dict metadata |> Dictionary
)
```

Things to consider:
- The constructor can be short in terms of characters but still have a lot of parameters.
- A single argument can still be quite long.
- The style guides might have a different opinion on the closing `)`.

## Extra information

Estimated cost: S or M.

Related suggestions: https://github.com/fsprojects/fantomas/issues/1189

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] I have read the [Contribution Guidelines](../../CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [ ] This is not a breaking change to Fantomas
* [x] I or my company would be willing to help implement and/or test this
* [x] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting): https://github.com/dotnet/docs/issues/21362
* [x] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions): https://github.com/G-Research/fsharp-formatting-conventions/pull/11

**Comment by knocte** [comment]
How about doing the same for invoking functions that receive tuples? essentially, the look the same except for the `new` keyword (which is even not required unless you're dealing with IDisposable).
