### ISSUE TITLE
Misplaces `=` in function signature so it's invalid F# code

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#1218]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAkgHYBmATgIYDOALmVtDVmfgLwA6RnEEeNYASyI1EZIhRxgASogAOsMjQCyiKlQoBzRNx66AFOlXqtaWmSEaAlJwDEAkmAAiAUQBCAVQDiO3RD0B9NGcyMgUAGUQAN0QcayIbGKptIl8ePVFQsgjonCCQ8KiYuISieHsfXw54%2Byc3LwrdEgoBHAB3ARoACzBDNU1khJwkhp4%2BMCThMgBPZ2jhMFYwAGVESZm5-j0VtZU%2BrR6jfoAaMGyYhbAMgpy41L9i1bKSTkgj8CgkmhoLKlQwAG13hBQKlIAASGhTWTINCQIQ0V5AnjgyISLAwgFI3QABjedygxCQwiWAgAXsg8XcACxYsAAXSRAF9KcDaeDIdC-nDhIjQWDUTh0X9AfiAIws3yQJQUAAeYSEiAiRA0XV5d1FACZsbSGbpmUiQZKIVCMZAAEawWA4NW6FFojEiu4aiW2lboARwHCwIgAQRozlKAHkSPKiBTaRAmkNEDqmRLDbbjZzYRarTbkfz7cKI2AAMwu5FLWQUaCIVyIEgKRAABQolEMIjI6d0dHRsb18bZSdNqetBbtgodOapBYgkCLJbLFarYVgrVE0GoiGIkVgi%2B%2B3ubPFbMdSup4%2Bt0CYzHJ7lr7XYFQrQjtSAFZR1AJ6Xy5WWO5ZNCyIukiu1xQNyILdIwkJJ2wPTs%2BVPLley3Adr0xfEADZH3HYsX2nFgAGEcGoKgsO9MwGBoBRgLAKMwL3OMDS7aCU3PODM0HbN8QAdlQ58pzfRAVHQM1RDIijd18fcIEPHhjzHbsYIY-smIQ29fAADg49CuKrAivSAx8hPAsTIKNOioFguSryHfEAE5VMnH0SEbAj0HQCgyJ3PSwHE1koJNGS01MrMbxzUVcRzNDJ1fKs3Q9K1Nx00DhN0UT3IMxMjPNWTL38xD1XFELONsxtIs9GKc1cqiOxorzk2M9K%2BTMlj1WdELCVWGhAyIAAVaYAHUOk6QS4rcjywEkqBpPo3yMuYgKxXzXK1J9UIsFKRwYgEd1Gxc%2Bh4p4RKhpG9lvNheFGLq6b1RHELpRlAgSHazpVmcaMlk6BQaB6%2BBVUfKltTKiCKsMw6oGOvypqy1JRQfS7ZWIEgBBlQMvwAhRnBlWQWDUARivxO8fpE6ij1owHuQREGFMClCoZlAA5RBWhwBUYbhhHRCRsgUbRoxMaIKmsD40RgwIER0F%2BR9RUG5KTyJ9BcG%2BemwwAMQUJyvlEdrvNJ8z1XYy6ZZaBnSDhpRdblxBFbIZWNtQ6BOjrEtG38doPr68X-pSongcmsmxRUymZDgMh4Hez7h1xhL8YkwmquJk7MsU3RRSs33EH9%2BAeb5sgBaFkXApdgnKtNaWcFlhUzYt1X1c9zXUi1VC-YUeAjaLvWFaVgDLZC63bcYUQHYEJ3IFziP865D3atjnMNRy-EpVlBbKCmQMsgEWgg76r7Q528PPIBqPR6NU6wd8DVGunq654oBel9oNP%2BIzkhBcQYWyLF379NdyWo8L4uW-Ntvy85DW9Vq6zWnufS%2B8paCN2-qbVuKsmxWxtpQbuZBe790HtvN2u8eSALOtXC6p9ZQADV7SuCEGUZUq8yLfXQcNSOpo96JgPnHHgGpIYEJlPLJajAuakNKBYSh68aH7TGkDbBlcgFHwpuwxwsAaCeEQP6VG6MqBcwETmHGQi6E%2BQvGPUGzCIAam1qfY2CpXBemgAAa1cEgixCiqBtSWBQQwmlebaRzLpV%2BSV35SVSiZcRuCj4%2B2njTOmpiFHzlWGraEK1YZEA6FzH0pReK32zviDxeNyp5x3meCauivZOkTtPAA0ogOQN07qrGII4wwoZwxpIGp4vaWijpiLyVXXwuZgrsMeu6KgnQ1H4moY0iWPiiZ%2BLaRI3QuYp53HHBYPAC0NC8xal1RAZolAIDqXcdJYdMlD2ydomOeicy5hPrMn09MNBEE4UQbh3oSRXIAswRA7VYDNWEABLm-VoyaOHuNHR%2B9x74lzCA85RdRDiG%2BNEWcypkmiBiUIeJhFvmUQyX9LJmCckAsYUCu4uZ8GzMcMvCgZo8A9OXp0JYUwPkyhRdtCAu0RmjV8TVQFxzgVsNmUsOgHplCbLpYNd4dJKRwioPLFRfxdKMiAA)

#### Code

```fsharp
module Infrastructure =

    let internal ReportMessage
        (message: string)
#if DEBUG
        (_: ErrorLevel)
#else
        (errorLevel: ErrorLevel)
#endif
        =
#if DEBUG
        failwith message
#else
        let sentryEvent = SentryEvent (SentryMessage message, Level = errorLevel)
        ()
#endif

```
            

#### Error

```fsharp
Fantomas was able to format the code but the result appears to be invalid F# code.
Please open an issue.

Formatted result:

module Infrastructure =

    let internal ReportMessage (message: string)
#if DEBUG
                               (_: ErrorLevel)
#else
                               (errorLevel: ErrorLevel)
#endif
    =
#if DEBUG
        failwith message
#else
        let sentryEvent =
            SentryEvent(SentryMessage message, Level = errorLevel)

        ()
#endif

```

#### Expected

```fsharp
Fantomas was able to format the code but the result appears to be invalid F# code.
Please open an issue.

Formatted result:

module Infrastructure =

    let internal ReportMessage (message: string)
#if DEBUG
                               (_: ErrorLevel)
#else
                               (errorLevel: ErrorLevel)
#endif
                               =
#if DEBUG
        failwith message
#else
        let sentryEvent =
            SentryEvent(SentryMessage message, Level = errorLevel)

        ()
#endif

```

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [?] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 11/02/2020 11:33:23 - f7b8f3a57ab91939683246fab651d12fe9930571

Default Fantomas configuration

**Comment by nojaf** [comment]
This might be a more complex problem, I can't really give any pointers on top of my head I'm afraid.

**Comment by knocte** [comment]
This is actually a regression, it was working fine with v4.0.0-alpha-012. I mention this because maybe it's easier to find the bug/fix by bisecting.
