### ISSUE TITLE
Swallows comment inside `with` block (of a try-with)

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#1219]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYrLGALwA6AdhBHgC5gBCAhgE5gAUAlGVTf2GYBnAJ6VoYYHwEy6rEdJlKw9AIRg4lOoi1kwckQBFYAd0o5YzeAQCWeMFlY5Fyga0R1H1AMqx0%2BTW0tF2UTGzoACxDXCAB6WLAhCNhceDATfCEAB0RoGwAzETAACTo6LIAlRABHLEQhOgBRAA9oRCy6G1hKAH5omMRmsABaAD5%2BmJoASUp81mE5LGhPdwA6KqzYVjoAdTZKG0oAczBBicmwdxXqADluxAmAX0gAGnAoIQ9O46FUMABtd4QUAySAAEjoIhyf0ghzoryBNHBADdmDg6n9AcoAAxvZSQGZILTeGwAL2QeKUABZERAALqIx6U4G0qAQqHINCwrQI0Fg1HozkA1kQACMzIEkAAssxmgAZQ6IOU6I6RXlKUUAJmxrIZ-CZiJBkvZ0K5ACNiDh1fwUWiMWgsUpNRKbd5EOgbHALJQAIJNSjwADy%2BQVlApIrA%2BTRn11jIlRptJqFkAtsCtLrZAvtwuUAGYMxBIN4ssw2oxEPktogAApsZj%2BbSsa0CRaIWP6%2BOs8GQ01QVPprv8u1Cx0yKkFqDF0uIcuV9xy0yIVjQYSIGbI2ArzrdZv8VvtmgG-gJpFJmH93eZ4eYiMAVgnRZLZYrVYAqlkcsvV%2BvN8xt5RLwgKMcBjGQ9UPTs%2BR7ZMLwzW1BRvZQADYHynZ850QABhHBhCETDugaVgljoLZAMjaM2zAuNDUHaDz0tS94OzUcBAAdlQp8ZxfdwpXdM0lzI4DQIEcCICPGgT0LM9zQYuChwQh0IwADg46dZyrfDvUEiiDzEyDjTomS00Y%2BTmIjABOVS2h9fJG3w9B0GYMj9yojsaKgjl6OMuSsxHCNRVxCNHzU7jEDdD0vR3CchMokTqOPWjPKMgc%2BV8xCNXFIK0MQGzG3Cz00yiiMXLityEo83sU1kwc0sU5QtQfQkdDoQNKAAFXkHZwgibSQNi-hRLAcSWQqmDqtS686o1fMss4n1WBSANDEQHAbA9RtnKI-qaEG4bJESyq4RM2qcw1ccgplZopnyNqIh0Ro%2Bu8ZJti6%2BA1QnKkdVciD3IMpKoCOnzJtOmRRXvC7ZRmfIbGaQNPz-LYWiydwhCELoAInW8vtKn7yr%2Bw6eSBhSQYEUUUIh5obkQExVrDKGYbhpcEdYJGUbR7obiwdB%2BNYYMpm0dBfgnUVdKG-TE0MjBcE6WnECIVhHLKJc2s8omzPq9iLuluxFXp5opW12X5cVjaH2gCI62WJcAH0wjenrRb2yS2Ul7l4TVvz6pUimqjgVh4Fe96I0%2Bx3xdPV3AZq4GWP4UVLJ93ItngTnuaXPmBaF-zQ9%2BiX-sgdBDcVY2-0bFXoQ99KZG1B9faTg2cBlouthNgSzYt%2BYrdYW2bHtyBs7x3OCfdqPiZjmhNUy-FLvm%2BYREDVgFQaQOeo%2B7GBviiSDuTSOJtHiNNWdCmZ%2BYOeF5sBoU559P3Uz%2Br%2B830aYQLhudbDYuldYMvw139WnRm-Fj6n0XnQeujc37NxLq3IK5tLaNm7r3e%2BI18bb0JiPX%2BVdzpT1lAANWHIwQ48BDhHGXmREO309I53DnnHexoTpjwgJqcGWDmgECwOIf8%2BCAxEJIavRB%2B1H5choYmOh%2B9ybMOMHQAA4h4Vm9R2aUB4XeNeO0N5IMHmNbyaDPZOk1lPQuYZGAWGgAAa0YB3YxHghCtW8PWLCaYuYYwjDFPhztux51gloyuAhNTe3xFTGmipyx0AyDoL%2By1oYHH-D6AMvFU6sFvkoZx5CxaUKkq7DxP9tFV3jviAA0ogdo11bo6BmDY-woZv6JJ0skp2W8YRCNPCIvMgVmEPQ9EkRRygyE4woQPKhlUMm0OjhGXMk8lBFiIXgeaRwubNR2IgM0UoECVJkEknpKS%2BlpPceNIZe88yHwAatI4lBWHsPRiSY5f5HCIDarAJqWg-zo16sJdeZUH7IK8ilXZ6CBC5n-uMn0DclyUEeciJU3QjixJ5uEw44R0YJNWdU9ZtSBF9h2cI4ZeZMHjMMOfZgZo8BtPPhEbwYg6Cymedtekqj%2BEfOSsdTFShcxMPGd4OQnoQHLMpY7d4dJKSwiEAQNGfxnGPCAA)

#### Code

```fsharp
module Foo =
    let Bar () =
        async {
            try
                let! content = tryDownloadFile url
                return Some content
            with
                // should we specify HttpRequestException?
                ex ->
                    Infrastructure.ReportWarning ex
                    return None
        }
```
            

#### Result

```fsharp
module Foo =
    let Bar () =
        async {
            try
                let! content = tryDownloadFile url
                return Some content
            with ex ->
                Infrastructure.ReportWarning ex
                return None
        }

```
            
#### Problem description

Comments should never be swallowed.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [maybe] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 11/02/2020 11:33:23 - f7b8f3a57ab91939683246fab651d12fe9930571

Default Fantomas configuration

**Comment by nojaf** [comment]
Hey @knocte,

The comment is linked to the correct matchclause:
![image](https://user-images.githubusercontent.com/2621499/98353976-64603100-2020-11eb-926c-9a730d9febb5.png)

See [online tool](https://fsprojects.github.io/fantomas-tools/#/trivia?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYrLGALwA6AdhBHgC5gBCAhgE5gAUAlGVTf2GYBnAJ6VoYYHwEy6rEdJlKw9AIRg4lOoi1kwckQBFYAd0o5YzeAQCWeMFlY5Fyga0R1H1AMqx0%2BTW0tF2UTGzoACxDXCAB6WLAhCNhceDATfCEAB0RoGwAzETAACTo6LIAlRABHLEQhOgBRAA9oRCy6G1hKAH5omMRmsABaAD5%2BmJoASUp81mE5LGhPdwA6KqzYVjoAdTZKG0oAczBBicmwdxXqADluxAmAX0gAGnAoJHzD%2BtQoV-fIDYhAQhDZfvlmDghIgQI8gA).

It looks like `genTrivia` call is missing somewhere in [CodePrinter](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L2107-L2122).
