### ISSUE TITLE
Swallows comment before #nowarn directive

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#1220]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6dYDuiwFcBnPAFwAsBLQsAO1mwEMAnGsAI0WgaLzYBsGZdgKH9BAHRoBiOoxZhxkACxLFkyTQYBbRIQAODaHgBisWOppaE%2BPngBCzMAF5JECLZJgHALzAAKAEpnVzdQwMgAGnAoYhISChoAc0JUMABtaIhQUIhIABISAE89ZDRIBJJIzLd8gDcGPnxS9OrQgAYonJqASRokGhIAZQpvZE6usCVWsABdaoBfcazp-KKS1PKBqq66hqbUjImwAEYlnMgAWQYADwAZBMRbxCTybYnjgCY26bnQxersucCsVmpA2GY%2BG9QrtGs1DhMPmdoYNEFoKHA%2BLAaABBEgAUT6AHkAGb3GhjaYQYkNYg-BZnQHQ4HrMrg2CQpFQPL1WEHSlgADMnNygwMRjsiGJsCYiAACsxtIgSIgmFCciQmE06X8GStmaC2Ry9Tz9mh4V0lMKoKLDIgJVKZbd6CquMRerVYFx4li1aENVqur83P9QoyavqNobfVyTXD%2BQBWK2QG3iyXSxAAVT0JSYrsQ7s9DG9NGjVJpiG1wd1OwjrIh0ZhppaRwAbEmU3a0zKAMICQiEbtYwj%2B6AkaWlsDUvi0wP0gF6tYG%2Bucxtxo4AdnbYs7DsQF1RHFVVqnM5yQYgIbcYdytagUZX3L2a4mAA4t7b7enB5iS8fy5WL2rIFF0jZdjSfPkjgATnfIxsWJZUmEHLQtAYCd-QrWcdXnGsQLrdkG0fXkzX5Y4On5ZNt0-GUUTRDEfT-adMLPOdQwXEFQIIh9Y0g95Tgojt4MQ2j0XZBj%2BQwgCwEvZZcI4-CjRrHiSKOT4k16foSEJGgABUmEKAB1ChXkY09QnPaSgKZPC7zApSIJU94hQE7dsSYWB8D6AARRA%2BAoNFEPQzVmPM1ir3YlkoAqQjlObd5LQoq5rm6YkdLIZ48SYwYyGlEgjPgEz%2BSUb4sKrHDgPkqKtm4hy4q6Y5E0Sm5emJChrkJHMi2lPFrj0GV%2BwocSjnjEqWOwti5MizZKhq4i6pyY42ya64ADlEGwPzyRatqOpVLqmB6vrdEIQaaBW-AtEPElumVLQUitY4pJksBry5GzIC0Gx4k2xBTCYVC4hVHSONmptzQWzdEq%2Bigfu264Lmhn6-oBwKk2gMgFVHFUAH1sAoAqyEgJ6rPDd7otB596rfZaACVOGleB8sKo5iuJ8rrMq6aYtq8HQmOGDafpph4HOy6VWu277tItmJoqqbPr4b6HmRotEOB9YKd4roviTOm4GFhHFZh5XpRRlUJxgDGmEMRDcfx14ZfCybQXJ8C5t5twPn4o5LhuNzrcKQkmHuYcmcJq1WdKwD2dJznXfs93%2BQ%2BRFlv9hhA%2BDqgSFFq7iRu1EpdUx3ZLl0EFaV8kVcBph1YpBOwaT5yfbTjOQ5IQ2K9%2B03VfNtGrZtnG8YJomo8smObzJ6q3Ybo4PgSn2koANSfOwEngBJEjDidI7GsrZY5qb46BWKPYgD5GoXm5jE80dTtXvoN63iPRtC8andLjYj6ZE%2Bk6Wy-ri8rAEgABxJUh1%2BonSxE-BML83AWWeq9VYnN7zT0pjkD4kMF6IweHYTE0AADWdhrYEKVIQbSgxFTfgur%2BfkJ4QpwLCiXA%2BS4uKoK1ug6mPs1obRwUqXAzxa4%2BVajQYyp1sR9H3GLJghcJh0OLi9CKLDFLHx5knAWPsADSiBEB6BSmlZ4vQKE6DJHXWR-5R4IMUZ-Ke9c0GhAFORf%2BmU0SEDINAlmsCIDwJJhPZBdkVGJyOAKb2Exkwb1sG5RIF1nh5UQGwC4CBTFdDkRYnxb0-GsNsew%2BxKdm5%2BUSDQa%2BNBb5YmGAUos%2BAZQ6VgBpGJRZToThSbvaO%2B9Y5TRQVkxyXQBRN1CdiRWKpNDxFqI8LEiRJGHiEQkURQ5GnmOaWPVpvj2n%2BO-qooJ89QleSoAwfgiBnFUDIIMQoAwbhzKYvIxBt4wSrPDD-IJF9QmDA1OiduiTzlmQYX8aIMxxjlEIMYE6qQ5HzCAA)

#### Code

```fsharp
// we use this nowarn because blah blah blah
#nowarn "44"

namespace Foo

module Bar =
    let Baz () =
        ()
```
            

#### Result

```fsharp
#nowarn "44"

namespace Foo

module Bar =
    let Baz () = ()

```
            
#### Problem description

It should never swallow comments.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [maybe] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 11/02/2020 11:33:23 - f7b8f3a57ab91939683246fab651d12fe9930571

Default Fantomas configuration

**Comment by nojaf** [comment]
Hey @knocte, I think this issue could be straight forward at first glance.

The comment is attached to:
![image](https://user-images.githubusercontent.com/2621499/98353822-295dfd80-2020-11eb-8977-1da998a62901.png)

See [online tool](https://fsprojects.github.io/fantomas-tools/#/trivia?data=N4KABGBEDGD2AmBTSAuKB6dYDuiwFcBnPAFwAsBLQsAO1mwEMAnGsAI0WgaLzYBsGZdgKH9BAHRoBiOoxZhxkACxLFkyTQYBbRIQAODaHgBisWOppaE%2BPngBCzMAF5JECLZJgHALzAAKAEpnVzdQwMgAGnAoJAAzChpdVChI6MgqY0IKZNiGPmIQAF8gA).

And I think a `genTrivia` call is missing in [CodePrinter](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L122).

**Comment by knocte** [comment]
Fixed in https://github.com/fsprojects/fantomas/commit/6c325838a6efc3af3601f8942cb3f821df1ce3eb
