### ISSUE TITLE
Lambda functions passed into HOFs

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1221]
I propose we add an alternative way of formatting lambda functions passed into HOFs as describe by the G-Research style guide.

The existing way of Fantomas deals with this problem is following the Microsoft style guide without any options.

## Pros and Cons 

The advantages of making this adjustment to Fantomas are following both style guides,

The disadvantages of making this adjustment to Fantomas are introducing a new setting and maintaining both choices.

## Examples

```fsharp
List.collect (fun (a, element) ->
    let path' =
        path
        |> someFunctionToCalculateThing

    innerFunc<'a, 'b>
        path'
        element
        (foo >> bar value >> List.item a)
        shape
)

let mySuperFunction a =
    someOtherFunction a (fun b ->
        // doing some stuff her
       b * b
    )
```

Things to keep in mind:
- This seems to only have an impact on multiline constructs
- There can be arguments before and after the lambda.
- What with multiple lambdas?
- Desugared lambdas?
- Setting name?

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): L

Related suggestions: https://github.com/fsprojects/fantomas/issues/1189

I think this feature cannot be implemented in one go. It will be a back and forward collaboration between trying things out in Fantomas and further polishing the style guide.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] I have read the [Contribution Guidelines](../../CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to Fantomas
* [x] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [x] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions): https://github.com/G-Research/fsharp-formatting-conventions/pull/10

**Comment by knocte** [comment]
Doesn't this github issue overlap a bit with https://github.com/fsprojects/fantomas/issues/815 ?

**Comment by knocte** [comment]
(If yes, maybe a better name for the setting is MultilineLambdaParensOnSameColumn, for consistency with the other Multiline* setting.)

**Comment by nojaf** [comment]
Closing parenthesis does not align [in GR guide](https://github.com/G-Research/fsharp-formatting-conventions/pull/10/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R796-R799).
#815 does something slightly different.

**Comment by samarsha** [comment]
@nojaf In Fantomas 4.3.0-beta-001, it looks like setting `fsharp_multi_line_lambda_closing_newline` to either true or false doesn't restore the style that was possible in Fantomas 4.2:

```fsharp
let printListWithOffset a list1 =
    list1
    |> List.iter (fun elem ->
        // print stuff
        printfn "%d" (a + elem))
```

Is there any way to keep using this style in the latest version?

**Comment by nojaf** [comment]
Hello @samarsha, in https://github.com/fsprojects/fantomas/issues/1201 the default style was updated to match the [MS F# style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-function-parameter-application).
It is no longer possible to have the style in 4.2.

**Comment by samarsha** [comment]
Hi, I see in the MS style guide that it shows the lambda on a new line when a function is being applied with multiple arguments:

```fsharp
let printListWithOffset a list1 =
    List.iter
        (fun elem ->
            printfn $"%d{a + elem}")
        list1
```

which is OK, but I was not able to find where it says the lambda cannot start on the same line as the function name when it's the only argument applied. I found examples in other sections that use the 4.2 style instead:

https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-records

```fsharp
let foo a =
    a
    |> Option.map (fun x ->
        {
            MyField = x
        })
```

https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#pattern-matching-constructs

```fsharp
lambdaList
|> List.map (function
    | Abs(x, body) -> 1 + sizeLambda 0 body
    | App(lam1, lam2) -> sizeLambda (sizeLambda 0 lam1) lam2
    | Var v -> 1)
```

**Comment by nojaf** [comment]
Please open an issue at the MS style guide to clear this out.
The guide itself is a living document, not everything is always clearly defined.

**Comment by knocte** [comment]
> @nojaf In Fantomas 4.3.0-beta-001

How did you install 4.3.0-beta-001? I don't find it in MyGet

**Comment by nojaf** [comment]
@knocte it was published to NuGet, https://www.nuget.org/packages/fantomas-tool/4.3.0-beta-001

**Comment by knocte** [comment]
oh I see, thanks; the README explains how to install stable versions from nuget, or preview versions from MyGet, but not preview versions from nuget :)

**Comment by knocte** [comment]
(also this new version seems to be not compatible with netcore3.x anymore, so the README also needs to be updated to show net5.0)

**Comment by nojaf** [comment]
Thanks for pointing that out, I'll update the readme somewhere this week.
