### ISSUE TITLE
Add Feliz-style formatting

### ISSUE THREAD

**Issue by l3m** [fsprojects/fantomas#1225]
In #453, @ForNeVeR  and @blumu asked for a style as follows (from aforementioned issue): 

```fsharp 

type MyRecord = {
    xxx: int
    yyy: string
    zzz: MyRecord option 
}

let nested = {
    xxx = 0
    yyy = ""
    zzz = Some {
        xxx = 0
        yyy = ""
        zzz = None
    }
}
```

This also corresponds to the default Feliz formatting (https://zaid-ajaj.github.io/Feliz/): 

```fsharp 
Html.div [
    Html.button [
        prop.style [ 
            style.marginRight 5 
        ]
        prop.text "Increment"
    ]
]

```

This is a style I see in a lot of open source projects and that's why we've adopted the style for all our projects too. While there have been follow-ups to other points from #453, I didn't see any on this. 

In comparison with other styles: 
- The Microsoft-style uses half-indents, which often conflict with tooling and also with learned behavior from other languages
- I feel G-Research style doesn't work well with Feliz and Fable.React as it seems to add lots of almost-empty lines that make it harder to parse Elmish/Feliz/Fable.React code (at least for me) - it makes code a lot longer vertically.

In my personal opinion, the style above is a nice compromise between the two, which might also be the reason why it's often seen even without any tooling support for it. As I believe I'm not the only one in favor of this style, a config option to enable this formatting similar to the multiline block one would allow us to adopt Fantomas into our CI pipeline and greatly improve our F# dev experience. 

I propose we extend Fantomas to support this style. 

## Pros and Cons 

The advantages of making this adjustment to Fantomas are 

- Support for Feliz 
- Support for a style that is widely used in open source projects

The disadvantages of making this adjustment to Fantomas are that it's probably a non-trivial change.

## Examples

See #453 

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): Unsure, maybe L - XL?

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] I have read the [Contribution Guidelines](../../CONTRIBUTING.md).
* [X] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [X] This is not a breaking change to Fantomas
* [X] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Hello, this feature suggestion violates our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md)  and falls under the section [What are we not looking for?](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for).

Fantomas has two styles of formatting records and this third one would imply massive changes over the entire codebase. I have no interest in maintaining this and wish to stick to what is listed in the styles guides. Please read the Contribution Guidelines carefully to understand why I'm closing this.

**Comment by l3m** [comment]
@nojaf Thanks for the explanation and a working link to the contributor guidelines. - the one in the issue template is broken and leads to a 404.

**Comment by nojaf** [comment]
>  the one in the issue template is broken and leads to a 404.

Thanks for pointing that out, created https://github.com/fsprojects/fantomas/pull/1246

**Comment by texastoland** [comment]
This is an issue for me for the same reason. Feliz is the [standard library](https://github.com/fable-compiler/fable-react#:~:text=please%20check%20feliz) for React rendering in Fable (Fabulous looks similar except round brackets instead of square ones). Both the extra vertical cadence of `MultilineBlockBracketsOnSameColumn` and extra horizontal cadence of `ElmishSyntax` hinder a HTML-like reading of the data structure. I understand your logic but wonder whether there's another solution? Here's an example pulled from an [AsyncRX demo](https://github.com/dbrattli/Fable.Reaction/blob/main/examples/Magic/src/Client/Client.fs):

```fsharp
let view (model : Model) (dispatch : Msg -> unit) =
    Html.div [
        Bulma.navbar [
            color.isPrimary
            prop.children [
                Bulma.navbarItem.div [
                    Bulma.title.h2 "Fable Reaction Playground"
                ]
            ]
        ]

        Bulma.container [ viewApp model dispatch ]

        Bulma.footer [
            Bulma.content [
                prop.style [ style.textAlign.center ]
                prop.children [
                    safeComponents
                ]
            ]
        ]
    ]
```

Brackets on same column width 80:

```fsharp
let view (model: Model) (dispatch: Msg -> unit) =
  Html.div
    [
      Bulma.navbar
        [
          color.isPrimary
          prop.children
            [
              Bulma.navbarItem.div
                [ Bulma.title.h2 "Fable Reaction Playground" ]
            ]
        ]

      Bulma.container [ viewApp model dispatch ]

      Bulma.footer
        [
          Bulma.content
            [
              prop.style [ style.textAlign.center ]
              prop.children [ safeComponents ]
            ]
        ]
    ]
```

Elmish style width 80:

```fsharp
let view (model: Model) (dispatch: Msg -> unit) =
  Html.div [ Bulma.navbar [ color.isPrimary
                            prop.children [ Bulma.navbarItem.div [ Bulma.title.h2
                                                                     "Fable Reaction Playground" ] ] ]

             Bulma.container [ viewApp model dispatch ]

             Bulma.footer [ Bulma.content [ prop.style [ style.textAlign.center ]
                                            prop.children [ safeComponents ] ] ] ]
```

**Comment by jkone27** [comment]
hello, i would need this working also for Feliz.ViewEngine, what settings do i need to specify? 
else fantomas keeps formatting everything a bit random inside a Feliz view. cheers!
https://github.com/dbrattli/Feliz.ViewEngine

**Comment by nojaf** [comment]
https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html#fsharp_experimental_elmish
