### ISSUE TITLE
Should prefer splitting right-side of `<|` expresion

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#1235]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAzAhgSwDYHdsAXACzAB4AfMAZwAcAnbAOyPTAB1J1ZY0BSGgBowAI0wMBNAJRcwPWGIkdmKrHkKkK1ek1bsuC8ZLCCRRieIBeU2ZHm9jD2MeuQh4KDUREiLAOY0qGAA2p4QoBBRUAAkRACedMhokCxE7uFRkDEAbpi4AK7JoZnRAAwe0dGQAJLMSKwAythWyJVVEAAspWAAupkAvu0RPdkJScGprBkd2XmFxWEdEACMw1WQALKYAB4AMiyIe4jM-qQzyysATGU9-dFDmZEbcYnFkKK8uBfVuflFwSWyyu62qjUQAFtsHBcLBmABBIgAUXqAHl0AdmG0ehAsLhvHdButnr9xu9PrBvqDYvMAWggR0AMzUiCQRp0TDQRAAIUQPAYiAAChJMBCfIgGD8qkQGEVCQ9iaNXhMUhSqUraYscWBOiyoOzOTy%2BbABXtYPgJdBMN46jlYFa-HCpdEZXKOvcoo9oiSssryV9nTT-lrlmAAKx6tkcrm8-mIACqdCSDCtNuYdod2CderxBPdRKeSrJkzVgbmwcB2oAbJGDTHjQKAMK4a00Rtwmiu6BEE2B3H5PNVD0QL1RH2sv0lgPU8sLSuhgDstejRrjm0hoglffkA8Q8s9itmk9V041Ffp2oAHMvDbGTYh27DmNvc3v8wrC0fiyfKWW-nOL1DABOG8uXhdAiAldsIQhTBt1dN8hwLb0izeKdfxnf86RKUMVgqbUo1vBtEHBKEYWzbVX33EdDxeb8oFLTDNXnS41gIutEHAyCGFI6FKQo0MEOosBRxGL80J-dUj2YwDLhBAi6gaIhUWYAAVBh4gAdWIEgX13YTRLAcdYnoj5T2k88cMuZl2JXeEGFgAp6gAEUQXBsChbj4NlRDomHETaNJCSoDSP8ZKsjoVl1Ajth2Gp0FUkgTiRfESJIE0iG0%2BBzj1TpbnfA9Pzo4KpnSJjLIZKoVgjGLdjqdBsB2VFk0wHsGCRHZGEQGgaCzZ89TDfKkI-FDxJVELpnKgCIqqmtap2AA5RB8HcrF6sa5qJVak0Oq6nq%2BoWgoIU3Bh0RqSCISCPUVgMwLfVMiEClwPxVsQAAxE1YN8CVVLQqbsMq6IViXGKnpew51p2TYwbwQ4PoYL6vMjaASBFbsJQAfUIbLdNuoqgvG0qwoq7UVmveaACVEDgBh4CynLtTyvHRuKwnQv%2BkNLhAynqZNeBDuOiUzouq7SeZsdUMJx7nthrF4cRn6-rPabAaiG5Iypmn4GhmXXvl1qkYIlG0e4rHsBxyBxbE1n3nZ5WAe1K42NDLZdnshhMHiVEGAOTt6d03Khr85CJbG23JvtzmOiueSXdi93Pe932iAFk7hchUXcKtozJfeaXwblz6DcViYOZY6ObJdhOvZ97BOx1gv3qL77JWR1GPfRhgzYt7PjLGEq7YslXHeiuPdgANWDbkWHgAJ-e3JmCpo-H7oHiOh4d0Mrhqsedjepzuz66f6jn82GdDRfhsKlmCfDsrI-Lqorjm3fnNgIgAHEfF2gV9rheeBpByiP5QyfdjwMXMi8cKqsIBXBBnHGGr1uSwmgAAa25B3VBPgaAqUaKKB8lIjr9UovpJeAUV4TlMoxB%2Bslo7kxdktFahxeREAtCcX6SRXINWYMQPq8J6jrkFgwTOywqJkNAbndCUkoEky3tzF2ABpRAiA6DxUSicOoeCxSYmxKGMRV9l431XmzdeMjh6hkZPhXeKUoQ0BIAAxmQCIAgLupQkq1CN5RyqIyZ2yw2QBFwJxBg-gjonEyogUQmwEC6NEaQgx5CjFuMJh4sxm9liMljn4%2BE7l-DMH3swQ%2BcJmi5NagUAUqlYCKTCa1PqelUq90kZJYm5j0mVyyc9CUzAak5COHCfwgiTpcJYLwjsdTBzBxGqHG2UjmlpKZKPPxzk66YFEIEmxdcSCNHiKwXYYzfLAJDtbW%2BMyy60O8TvPxjQZTQiIFEpAeyDKeF6O0VINA3q9WCFRAYQA)

#### Code

```fsharp
failwith <| sprintf "foo: %s - bar: %s" foo bar

failwith <| sprintf "foobar: %s - foobarbaz: %s" foobar foobarbaz
```
            

#### Result

```fsharp
failwith <| sprintf "foo: %s - bar: %s" foo bar

failwith
<| sprintf "foobar: %s - foobarbaz: %s" foobar foobarbaz

```
            
#### Expected result

```fsharp
failwith <| sprintf "foo: %s - bar: %s" foo bar

failwith <| sprintf "foobar: %s - foobarbaz: %s"
                    foobar
                    foobarbaz
```

(Because breaking the operator `<|` looks kinda ugly, plus this way of splitting the string achieves less horizontal scrolling.)

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [maybe] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 11/07/2020 09:02:01 - de55bd935d4b7cc63d2408b520ec8a7f962fa9e2

Default Fantomas configuration

**Comment by nojaf** [comment]
As this is not necessarily a bug I'm going to need some input from the style guides here.
Please open issues on the styles respectively before we can take any action here.

**Comment by knocte** [comment]
Filed: https://github.com/dotnet/docs/issues/21459
