### ISSUE TITLE
Splits in too many lines unnecessarily when surpassing MaxLineLength

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#1237]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzWsYAvGAEYCGATmeQF42UW0A6Adm5jvoSRdU2whDhIigA9BIqRAoBPSABpwUAM7YsAS1YBzFajABtZRFBTIAEiyyADsjSQtWRcaEWAbuXQBXO4ZfCABiVpKABJViRWLABlDVpkYOkAFn8wAF0XAF9Ek1SLK1t9ByjnM3MPb18jEIBGHJFIAFlyMQAZLURWxB0sAAtS6RqADlSM4WyXUwbLG19IUgJ0AeF3Tx99aukAJnqV6MQAWw04dFhWAEEsAFEIgHlcdtYE1IhcTzVRrPqplZnC%2BwWsCWuyg5TWVReYAAzCCIJBotZyNBEAAhRD4SiIAAKVHIB2wiEoyxEWEoPk%2B42%2BeT%2Bc0BwOpFXWaE2UiSsKgCKRqPRsExrVgAHdCdByGpwm5YCLNGdicJSeSpGMhBNhD9XDSinTZaDGRCQgBWdnwxHItEYxAAVWstkoIrFrAlUo0MvZb3QH0VX0m1IKtMW2tWlQ2kIAbEbOaaeZiAMLoUUqaNnFTy6BYXna17vRAU5VUsq%2BzX%2BkGBpl%2BEIAdnDJu55sah1IhIzeCzOYgKqEarhGoBRYZ4ODISGVa5Zt5iETp1YTbdHpESrbeemBZ7QIDYKDzMhAE5h8jzrgsITEwcDuQm-Ls57Kd787NC6vi%2BvSyyRDUgpDjSOo4h9kcTi7IRnS85y9VUfTvFd6TKXUB0GOoPwjRB90PShf2OIEAJCC9WzAdtclvf4oC1R8YM3Wodg-cJIiwW5WAAFUoWQAHUND6acWyvXMbyXCCiN7aD%2BzIwYYQQ6tzkoWAvAiAARRB0A0I4UPPMlgOEedcMXX5lygRw11IstBjZD9mjEUJcDo3puiud0f16XksBY%2BA2PZJIAhwvCwE7UFtOKJwSMEgypBqQ1jJacJcA0MRbhtcg00oK4xGsTEVBUZ0p3ZfU3M4hduK03jfL0gKX2EGow1CsQADlEAFeSnnCyLosJWLeQSpLEBStKKq8A4G0oe5QkPA49HZGp3M09UfIOLx0E0WrEAAMV5U8sBQui738jdAtfStjOm2aOnqsRGj2jQ5sWyhlqUo1oF6XFU0JAB9AUNCc-oxtyib8t0jbn0hYYjRMgAlRA4EoeBHOcyFXPesCCLmb6%2B024qhBqHdyuB0H4C6nrCX6wbhr%2BmGO3AwjICmmbTo6c7LsJNbCh%2BvVtnfEJIAx3l4GOimzqW2Kro-G67pQp6XrYon8J40mEYEpHIS2eCWZM8TKHIWRbkodpkwh-oXKykDr1hiX4ZKBnYKkLYKIVlolZVtWNawbHerxw4CdqMXPJJuZyf2p5qd52n1sR36Qi2ESWet1X1Y0ZNOe9haeZWxtrtu5X7soYXXsgN2vPyL7jcDxmzaMy2xAANXBFEtHgLRtC1ptoeyjSPq7HypemfTkYgLYQuL%2BapNTNKK4iava51rOPaKVvfnb2WyuL6TYCwABxbBWuS1KzhHyFMrHuH7ygtuitlnaFZOuaUVOaAAGsURTy-sBUWjojxccgW69LAI4vWuINvLSeI-PTYiC2EOD8VUaodDRFgIU3Q6aIFkhFVgrE0rnAiHWHGlAXbSCAjvQ2e9Coy2DmjFmABpRAiBrBmQst0cIT98SPGeCEbBDcPLZ27DpPO0sg7SChMzaQTQWjWSOCoXom8Qj1y-jlH%2Bn0-78QPgQ7h8s%2BGxB0JgcS2hurdAcogUgjQEAMKwZ-NSoFia70gvgrhUgoQWz4eceS2hWC91YP3M4sR7GxS8JiOisAqKaNimldiNkcG-z9A%2BABQlLGhxsTNQkrA-FuE6GcbQaDerwK0EgpMATZxGP1iY3BZiTbhJEFCIufDpJR3IKQTAgio69GiLIKILRMmqSEOpFh498lhK2sIKE3clGkmOFgXRSAmnuWUGkRIDgVDzVSvobBmQgA)

#### Code

```fsharp
let res = fn1 arg1 arg2

let res = fn2 arg1 arg2 arg3

let res = fn9998 arg1 arg2 arg3

let res = fn9999 arg123456 arg arg
```
            

#### Result

```fsharp
let res =
    fn1 arg1 arg2

let res =
    fn2
        arg1
        arg2
        arg3

let res =
    fn9998
        arg1
        arg2
        arg3

let res =
    fn9999
        arg123456
        arg
        arg
```
            
#### Expected results

```fsharp
let res =
    fn1 arg1 arg2

let res = fn2 arg1
              arg2
              arg3

let res =
    fn9998 arg1
           arg2
           arg3

let res =
    fn9999
        arg123456
        arg
        arg
```

(In the cases of fn2 and fn9998, there is no need to split so much, as the expected result above still respects the MaxLineLength without causing so many lines. The current results should only happen if this approach surpasses MaxLineLength.)

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [maybe] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 11/07/2020 09:02:01 - de55bd935d4b7cc63d2408b520ec8a7f962fa9e2

```fsharp
    { config with
                MaxLineLength = 18 }
```

**Comment by auduchinok** [comment]
>     { config with
>                MaxLineLength = 18 }

Could you share the scenario where such line length was needed please?

**Comment by knocte** [comment]
> Could you share the scenario where such line length was needed please?

I would never need such a shot MaxLineLength, I'm just simplifying the testcase.

**Comment by knocte** [comment]
Edited report to make it much more clear now.

**Comment by nojaf** [comment]
@knocte always please report with realistic scenarios. Fantomas, in general, isn't meant to work under 60 characters max_line_length. 

Fantomas will first try and have the entire [LetBinding ](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-syntaxtree-synbinding.html) in one line, the expression after the `=` is then checked if it supports `fsharp_max_value_binding_width`. In case it does not it will add a new line and indent the expression.
The function call (SynExpr.App) will also be written down in one line at first.
If the function call is longer than `max_line_length` it will be formatted as stated in the [MS style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-function-parameter-application).

Everything works as expected here.

**Comment by knocte** [comment]
> please report with realistic scenarios.

You seem to have missed what I already explained in my reply to @auduchinok in https://github.com/fsprojects/fantomas/issues/1237#issuecomment-724792585 . 

I can of course transform it into a less simple testcase by increasing the variable names, here we go:

```
let res = fnWithLooooooooooooooooooooooooooooooongName1 arg1 arg2

let res = fnWithLooooooooooooooooooooooooooooooongName2 arg1 arg2 arg3

let res = fnWithLooooooooooooooooooooooooooooooongName9998 arg1 arg2 arg3

let res = fnWithLooooooooooooooooooooooooooooooongName9999 arg123456 arg arg
```

Current Result:

```
let res =
    fnWithLooooooooooooooooooooooooooooooongName1 arg1 arg2

let res =
    fnWithLooooooooooooooooooooooooooooooongName2
        arg1
        arg2
        arg3

let res =
    fnWithLooooooooooooooooooooooooooooooongName9998
        arg1
        arg2
        arg3

let res =
    fnWithLooooooooooooooooooooooooooooooongName9999
        arg123456
        arg
        arg

```

Expected result:

```
let res =
    fnWithLooooooooooooooooooooooooooooooongName1 arg1 arg2

let res = fnWithLooooooooooooooooooooooooooooooongName2 arg1
                                                        arg2
                                                        arg3

let res = fnWithLooooooooooooooooooooooooooooooongName9998 arg1
                                                           arg2
                                                           arg3

let res =
    fnWithLooooooooooooooooooooooooooooooongName9999
        arg123456
        arg
        arg
```

The rationale is that fantomas is splitting into too many lines unnecessarily, because it can split in less lines without surpassing the MaxLineLength, which now is:

```
{ config with
           MaxLineLength = 60 }
```

for these testcases.
