### ISSUE TITLE
Shorter MaxLineLength with long variable name yields invalid F# code according to fantomas

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#1241]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwBlWXAOR3yJIB10nsEBXAG1ItwFl2uYALxMmECFwAu5SogBibdNDAAKAJTCx47VLB5ZAGVjRMHBUr2yAaogBOATyOxnL12-cfPXl%2BgDmABUxbHE10bXDxTDx7C2AtCISwAEsAM1V9XBsHJ29cvPzYP0Dg7GEwAEYNSQALRGYwxMaIW0RJNlswlMwkjgB3JJqwBkgADzHh%2BMaAX0ntdVF0SAAacCg8VskkvzxUMABtVYhQCMgAEkl7AmQ0SC3JZcPxM4A3UzZr-cftAAYVxMgAJLoJDoSRkJIAL2QfwSABYvmAALqPKYwo4Is4XK67W6gh4nU6vDjvXYHRLlNHhSC8TAjAxbRAGOq%2BGr4hIADm%2BCOR2lRj2OVPOlw%2BkAARs4OGztC83h8yQkAEyU6VkRDYJJwDiFACCkgAosCAPIpenoaEIiBdDjrbkoykC6VC7E3cWwSXKqCE2Wki1gADMHogkDI9EQACFEClYC1irRJHYpeFJLZ3rbefaMU6Ra73ZmiSS0PKIrDA1AQ8Rw5Ho4zYL07CZ1kDnsZMJtContMnUxEeeI%2BdoHU8szicx3Pfm5b6AKyl4OhiNRloAVQIV1sDcQTZbbcWpatNp7dv5max2YlY5lxMniQAbLPyyQF9WAMIcKJ4Z%2BFPBd6CSaNjy1TAPcJewgftxEHINhxdc8PUvAtPkSAB2e95yrFpeDVUUEz3IDEDTPsMwJU8R1gvNvULX12VQisnxaT8tV3X193ww902PYjhVIt0Ly9K8fUSABOGiSG1FJ41sT9sGwTAALALtWJAo8BxPLiYJ4uC%2BIQotwnKX5fTnWj0MQVV1U1dtcOtRTtFAsBwPRTjnSgUdNInASEnKCkDIfRAxIk0yNTdCzfQUgiwKIwUSPU3MCTcyjySVAygRBSRDXQAAVBwAHUBmqOSWLCuyIsdKLnLI2KKMQjyA280NtVsWBFHgAARRAOCSdUJLk0K2MIjjIrUqA7l4uKqoicoSwMmkRgBFJ0tqdA9SsshqmjSQcvgVlS1hLlevC-qSsG3F7lcyqdO0coZym2kgRSJIRkNNdW2jPURgIFo8DwJJgsSKddqU9iVMckVhtO-j4o8u9rpGKhEF6dqzVu%2B7HrsZ7bFe978C%2BwoqDYbBsNsY0AXjbAdlLcpCvssBIM9UrIGwThNgR%2BRoxkyQJPSriwe031yhQqbGZ6BkkZGXhBeZuRWdbLrZ2gaogmICSAH1%2Bk2vLKeKoc6dB8jwbG3TqOhgAlRA4FseANq230do1g6taOnWKr187xHKYTjdN6N4Fx-G7CJkmyd522gYGpz6fFhlJdsNmOa53WecSBV9P%2BE2zfgMWOCZyOpfZnCDLlhXfzsFWkjVyBg4g1Sw8dwVRpdiAFS8-5pvq4J7ENWx6W-S28u2-6bOUyvgZxGvHTr30FUS5vaVbzB287pJvx9gn-bVQPyQrhzQ5FBnM6Fs0o5juxOexbnr0VGr-ln%2Beu8kDOs4PnOZfz%2BXgiL2wS7LzfqarkG8TP9yEQFSTWniMKwsowxbHgFsXwPc5I2z2kVO2UFtb-3jufIBV1QHmF-N9dAkDgQwLgX3b%2BNNMQOzQU7BOiooagOarASQABxVoGMPrY3QMQ6c-dxC2SpmQ6CZUNLoMAeEBU-Nm4RzNGGLU0AADWYY36yNaHgNKZBaAMTxkxRIBVEF8N-txGKtczoT0Nv8WG8MGQRkkHWOoJ9ECtTuugAYeDtTAkwr7Ww68Eg6IBn1EOh0w4uWERDIB7t-gAGlECIAILNeadQgRqNwKac02i8KkP0TcUeQ5x6JD9MnBI1JaRLXVHgaonDEgIN8ftfx9tAnlSMc7X0fom4FPBH4Lg9VfB4zqOtRAop%2BBIHymk3RmsUFHSCVQjB4Q-RTwKdqdqvh0A4J3OCRZrZ2iIHSrAZKPTWx4KGVZdJw9oojWMbky%2BczM52CwJsZ4NY-DuIJg4rYzivwHOAgPQGQ9t4GNOY03JICCnNUXpgUUXBimL2qGQGIkhaTvOsjwweW8AlniEZMkR2g-RYNacmDUd8EApO8cMqpdlViIhhLcPAcgvq7AKlMIAA)

#### Code

```fsharp
namespace SomeNamespace

module SomeModule =

    let SomeFunc () =
        let someLocalFunc someVeryLooooooooooooooooooooooooooooooooooooooooooooooooongParam =
            async {
                if (someVeryLooooooooooooooooooooooooooooooooooooooooooooooooongParam = 1) then
                    return failwith "xxx"
            }
        ()


```
            

#### Error

```fsharp
Fantomas was able to format the code but the result appears to be invalid F# code.
Please open an issue.

Formatted result:

namespace SomeNamespace

module SomeModule =

    let SomeFunc () =
        let someLocalFunc someVeryLooooooooooooooooooooooooooooooooooooooooooooooooongParam =
            async {
                if (someVeryLooooooooooooooooooooooooooooooooooooooooooooooooongParam =
                    1) then
                    return failwith "xxx"
            }

        ()

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [maybe] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 11/07/2020 09:02:01 - de55bd935d4b7cc63d2408b520ec8a7f962fa9e2

```fsharp
    { config with
                MaxLineLength = 80 }
```

**Comment by knocte** [comment]
@nojaf we're working on this but are confused as to what should be the expected result. Would it be this?:

```
module SomeModule =

    let SomeFunc () =
        let someLocalFunc
            someVeryLooooooooooooooooooooooooooooooooooooooooooooooooongParam
            =
            async {
                if (someVeryLooooooooooooooooooooooooooooooooooooooooooooooooongParam =
                     1) then
                    return failwith "xxx"
            }

        ()
```

The above doesn't make the compiler fail for me, but strucks me as strange. Is this maybe an F#-compiler bug?

/cc @btzo

**Comment by nojaf** [comment]
Hey @knocte, I would expect the output to be:

```fsharp
module SomeModule =

    let SomeFunc () =
        let someLocalFunc
            someVeryLooooooooooooooooooooooooooooooooooooooooooooooooongParam
            =
            async {
                if (someVeryLooooooooooooooooooooooooooooooooooooooooooooooooongParam = 1) then
                    return failwith "xxx"
            }

        ()
```

I noticed the condition is being mistaken for a named argument from a constructor call in
https://github.com/fsprojects/fantomas/blob/d5f4d9f52d55a9ad54b964195fff1c0a028a06b9/src/Fantomas/CodePrinter.fs#L1644

Something like `A(B = b)`.

Constructor invocations may need their own active pattern to be captured and processed accordingly in CodePrinter.
I'll try to revisit this as it was introduced during an infix operation refactoring.

**Comment by knocte** [comment]
> I would expect the output to be:

I don't see the if's condition split in 2 lines, in your snippet; are you sure that respects the MaxLineLength?

**Comment by nojaf** [comment]
It should follow:
https://github.com/fsprojects/fantomas/blob/d5f4d9f52d55a9ad54b964195fff1c0a028a06b9/src/Fantomas/CodePrinter.fs#L1715
And then go here https://github.com/fsprojects/fantomas/blob/d5f4d9f52d55a9ad54b964195fff1c0a028a06b9/src/Fantomas/CodePrinter.fs#L2613 
as equals is part of https://github.com/fsprojects/fantomas/blob/d5f4d9f52d55a9ad54b964195fff1c0a028a06b9/src/Fantomas/Context.fs#L1076

**Comment by knocte** [comment]
@nojaf let's agree on the expected results first, before discussing implementation. The snippet that you have posted in https://github.com/fsprojects/fantomas/issues/1241#issuecomment-756736275 doesn't split the `if X then` line in two, but fantomas has to do it, otherwise the MaxLineLength is not respected (whole point about this bug is related to this).

**Comment by nojaf** [comment]
MaxLineLength cannot always be respected in combination with all other rules/settings across the entire tool.
`=` is part of `noBreakInfixOps` and that is not respected here as I explained, that is the problem for me.

Trying to split `noBreakInfixOps` operator to respect max line length will introduce a whole set of different issues in regards to operator precedence.

**Comment by btzo** [comment]
Hey @nojaf ,
 
> Constructor invocations may need their own active pattern to be captured and processed accordingly in CodePrinter.

You could elaborate this part please. 
Today at `SourceParser.fs`, the only reference for a constructor I see is the `MFConstructor`.

https://github.com/fsprojects/fantomas/blob/b36e5a54dd3a44922d12f7bea8a7fcca2035764d/src/Fantomas/SourceParser.fs#L545-L554

but it seems to me that it only serves to decide which keyword to use in each case in a Pattern.

Also, I can't find anything explicit for the treatment of a Constructor in the documentation of the [SynExpr](http://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-syntaxtree-synexpr.html). 

Maybe the `New` and `ObjExpr` expressions?

**Comment by nojaf** [comment]
Hey Mike, I'll get back to you on Friday.

**Comment by nojaf** [comment]
Hey @btzo, I added the fix myself, as well I'm the culprit who introduced it. 
I've explained a bit about what happened in the PR description if you are interested.
Thanks again for showing interest in solving this.
