### ISSUE TITLE
`function` matching with pipeline operator

### ISSUE THREAD

**Issue by 3Rafal** [fsprojects/fantomas#1257]
### Description

Currently, when piping into pattern-matching function, `|` pipes are aligned same as `|>` operators. I find it misleading, especially for long pipe chains.
Can we consider changing it to indented version?

### Repro code

```fsharp
// This is current formatting
[ 1 ]
|> function
| [] -> 1
| _ -> 2
|> string

// This is what I find more readable
[ 1 ]
|> function
   | [] -> 1
   | _ -> 2
|> string

// This is the only similiar case, that I've found in MSDN.
// This pipes into map, so it's not the same. However, we don't align `|>` with `|` which I find nice
// See: https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#pattern-matching-constructs
lambdaList
|> List.map (function
    | Abs (x, body) -> 1 + sizeLambda 0 body
    | App (lam1, lam2) -> sizeLambda (sizeLambda 0 lam1) lam2
    | Var v -> 1
)

**Comment by nojaf** [comment]
Hello, this violates our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for) I'm afraid. I'm ok with change the style only if it is based on a style guide. Please engage conversation over there first.
