### ISSUE TITLE
tuple with match formats to invalid code

### ISSUE THREAD

**Issue by ThisFunctionalTom** [fsprojects/fantomas#1269]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBDMAvGADqQASi66spxATsQHYC2uW0AFnmAO4CWWDvSYQIAHxKQAZnzoBnLKTABaAHxgAjMMaiwE0nMRxG8JWrAAmbboA0YANoBdSDfBRDWLH0YBzOagc3CFBdCEgAEiwATwAHZDRIbywXINEIgDdcdABXeMDQ0QAGVwKwgEkTREYsAGU%2BAC9kEtKAFlSIR1SAX2bg9qhI2LzE6pSCjKzcgPt%2BiA1e0MgAWVwADwAZb0R1qp9BMdKNC0L%2Bzt0e1JDFwbiAyAAjWFh0A90JnLyZ0ssFt5rEZh8ODURgAQSwAFETAB5KSbRhNWZgKRZQynboLK5vG7DR7PV5pcKZD7TJEAZl%2BaRqMVw0EQACFEFJYHREAAFXB0XDMbCIOgE3RYOi5dHnTH9CLRW4JPEvSnvKZoL6tSlham0hlMlnbWA8PnQXCGCrpWAGrywRgC0RCkUFM6iC66LGEqW4p5yiVEyafJEAVlVUHVdMZzNZAFUYnE6AajYwTWa%2BBarRAUeg0XaMZdPa67rKrQqfd8AGwByBBzWhxAAYXQhrkVYtCmF0CwLOTyNRiFFDvF4xxufd%2Ba9JKVSIA7KXyyHtUsAfc%2Be3U%2BnQvaII7RM6wv2ZYP5cPFflSgAOSc04Na1kNkGLzvdte9645nf4vfEg-KgoATlPGtBUiwfINswrDtjaXYZmKWZ9k%2BUB5q%2B3qkt8GjFEiZZnhW2r-ICwJJgGS7gSumZOtmQwDi%2BnpvoWhzzKh5Z-gBdBYUCzy4UiYF3mA659NBpHPh6faUYhhwWKWFRINU0KMAAKnQUQAOoCBwN5pgRuirpxD7YjBDy7hRCGjkhFK0ehoJ0LA2QmAAIpQfCAgxoHCqpojqVxYCbgM2lJEOgkGYcLSlisqxlFIUkcFUEIqTUHAslgCnwPsAYtCcEE9lBj68VAXnwSOh4FBo-qoYFFQyKs0JRmwLIQqsMSsnIciJpaAa%2BslhGQcRPHSplozZe%2BSIaCWhVrAASkYLLwHFCVIklHGue5koZSMyQ9VReUToNqwjXAdDwAActkzDznQsJlABzD%2BAGGgzZpLoLcw2ToF46BbAAYiyrCeHyUmkctQl5SeqGbWNSz3Y9L1vWw9mlpwnK0gxAD6-DxUpV1pVpC1ZXpOUfqEGjfutplclE0J0JsCgTUpiUtWpREbiRnWLd5%2Bm5aExwBWsBO4ETJN8Aoe0HXyx2nedfUo%2B16X03dD18E9CKvXQ70MV9tw-b5BQWDR3yQBzXOk1gwNSzLiBywrC5QxwMMtnyCN8EjkCi7THXDBjAlM9jugWCJ60AGrevS3jwN4Pjk%2B200pfeqM3fTzvXD5zPu0ZmuBc9Fktg1fsmIHweU-b3Hi073WY713wWP562WbAWAAOLYFVNWIHVDVZ36VPOTTudo-TcGFytLMFYnIPS1s9LUNAADW9JcmP2ByJJNTctWzz7Y1SL4Tnbl0265Eu1jSIWANms7YgPCG4yWB6lUSuINZMiMAIDWgiYs78-IynLtTbUO3nZH8THru72tmsADSiBEAxGCqFKoFQ548nhIib4q8w4aQjluTyBdt5F1KBYf6ic1gRUBHIDgTdvih1aqlMWHdN4-2xLHN2ogLB401nUXwmBTI%2BH2lUWKiB7hLAQHA0oCDSHh3IZHShjMd7fDJChTWoIno%2BEYMnRgqcLR1DkWwbIrIpKwDEhwtgDVX5OQ6G3dejtv5iIwQUMkGtShawenyRguj0g6l8E-Q619vB30bPotec1tywV0ugnuugySe37lLWB6xuT3HgLgGssB6q%2BEPsfLYXjEGzQ3qYlWcdRBkgTtYyyPNcD3EwHgnmHAahRGqGsFJgikHCJQQtKo8BYSwJqNETAZjAnZNLprKETS4TJKhnQdAUg7apOuvUzu-jf7iNKGSPu1jWl0CBHrXh1T34OjcI4ZoiQ5DPXqgEVeXQgA)

#### Code

```fsharp
let a = "Hello"
match a with
    | "first" -> 1
    | "second" -> 2
    , []
```
            

#### Result

```fsharp
let a = "Hello"

match a with
| "first" -> 1
| "second" -> 2,
[]

```
            
#### Problem description

When formatting a tuple with pattern match as first element fantomas puts comma in the wrong place and generates not compilable code.

Expected formatting:

```fsharp
let a = "Hello"

match a with
| "first" -> 1
| "second" -> 2
,[]

```

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas 4.2.0

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello Tom,

Thank you for reporting this issue. It appears that Fantomas joins every [synExpr ](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-syntaxtree-synexpr.html) of a tuple with a comma and a new line (if the whole expression is multiline).

So in pseudo code:
```fsharp
let myTuple = a, b
```

If `a, b` is multiline it will go like

```fsharp
let myTuple =
    a,
    b
```

See [genTuple](https://github.com/fsprojects/fantomas/blob/2c2b5264ff2c70033128e6eb7c64665b8c08e10e/src/Fantomas/CodePrinter.fs#L1072). In the case of SynExpr.Match, this leads to different code that what you originally had.

Would you be interested in submitting a pull request?

**Comment by ThisFunctionalTom** [comment]
I'll give it a try.

**Comment by ThisFunctionalTom** [comment]
Hi Florian,

thank you so much for explaining the issue and pointing to the right place. 

I wrote some unit tests and fixed this issue, or at least I hope I fixed it 😅 .

One thing I am not sure if it's important.

If I have a long tuple and the match is the last element in it should it also be formatted with commas at the beginning of the line?

Here two examples.

This
```fsharp
match "Hello" with 
| "first" -> 1 
| "second" -> 2 
| _ -> 3
, 1
, "Hello"  
```

must be formatted like it is, I think, because of the semantics.

But this

```fsharp
1
, "Hello"
, match "Hello" with 
  | "first" -> 1 
  | "second" -> 2 
  | _ -> 3
```
can be formatted like this

```fsharp
1, 
"Hello", 
match "Hello" with 
| "first" -> 1 
| "second" -> 2 
| _ -> 3
```

with my current implementation it will be formatted with commas at the beginning of the line. 
I am not sure if it is OK. What do you think?

Also, I think that maybe it is not important. One should not write code like this 😁 

![image](https://user-images.githubusercontent.com/3315570/100314027-063ac400-2fb6-11eb-9d02-97b904be9037.png)

**Comment by c-rindi** [comment]
@ThisFunctionalTom Thanks for submitting the PR (and humour)!
