### ISSUE TITLE
O(n^2) performance issues for large arrays

### ISSUE THREAD

**Issue by Janiczek** [fsprojects/fantomas#1272]
Hello,

(I tried to use the online tool to report this, but got
![req](https://user-images.githubusercontent.com/149425/100845966-3edb1180-347e-11eb-8824-6a40deb3b70c.png)
probably because of large URL size or something.)

----

First of all, version/OS info:

```bash
$ fantomas --version
Fantomas v4.2.0
```

![spec](https://user-images.githubusercontent.com/149425/100849130-67fda100-3482-11eb-931c-e8c7dadb3d89.png)

----

My issue is with the **performance when formatting a large array** (1000 elements). (The formatting itself is OK)
I encountered this when solving [Advent of Code 2020, day 2](https://adventofcode.com/2020/day/2). My code is [here](https://github.com/Janiczek/advent-of-code/blob/master/Year2020/Day02.fs).

Formatting this file takes around 8s:
```bash
$ time fantomas ~/Localhost/elm/advent-of-code/Year2020/Day02.fs
Processing /home/martin/Localhost/elm/advent-of-code/Year2020/Day02.fs
/home/martin/Localhost/elm/advent-of-code/Year2020/Day02.fs has been written.

real	0m8.164s
user	0m8.406s
sys	0m0.276s
```

Or with `fantomas --profile`:
```bash
$ fantomas --profile ~/Localhost/elm/advent-of-code/Year2020/Day02.fs
Processing /home/martin/Localhost/elm/advent-of-code/Year2020/Day02.fs
Line count: 2040
Time taken: 00:00:08.4035405 s
/home/martin/Localhost/elm/advent-of-code/Year2020/Day02.fs has been written.
```

Perhaps there is some O(n^2) processing somewhere in there?

I've experimented with various array lengths (and kept the rest of the code unchanged):

items | time (s)
-- | --
2000 | 29.46
1000 | 8.02
500 | 3.03
250 | 1.69
125 | 1.22

Which results in [this chart](https://www.desmos.com/calculator/0j4rp0abiq):

<img src="https://user-images.githubusercontent.com/149425/100848438-67183f80-3481-11eb-8b6c-96b24f25b554.png" width="400">

To be explicit, my expectation would be that the formatting time would be some form of O(n). The difference between a file with a small array and a large one is noticeable when writing code. (But again, it's not common to have such long arrays...)

**Comment by nojaf** [comment]
Hello @Janiczek, thanks for this extensive report.
I believe the main problem here is the number of string, int and char values inside the records in the array.
Fantomas cannot trust those values that are listed in the AST (binary strings are converted for example) and that is why all the original values are captured as trivia items.
These trivia items need to be assigned to the correct trivia nodes (which are in this case the original AST nodes) and I believe that is taking a lot of the time.

See:
- [StringContent](https://github.com/fsprojects/fantomas/blob/f93af000769060d097647b0e889e58592f4656cc/src/Fantomas/Trivia.fs#L431)
- [CharContent](https://github.com/fsprojects/fantomas/blob/f93af000769060d097647b0e889e58592f4656cc/src/Fantomas/Trivia.fs#L439)
- [Number](https://github.com/fsprojects/fantomas/blob/f93af000769060d097647b0e889e58592f4656cc/src/Fantomas/Trivia.fs#L435)
 
I don't see an immediate action to fix this right now.
Trivia assignment as a whole could be revisited but that is rather complex to nail down.

Are you interested in helping out on this?

**Comment by nojaf** [comment]
I was able to peel off a second by optimizing the trivia detection.

![image](https://user-images.githubusercontent.com/2621499/102613010-0b60de00-4132-11eb-935c-a88cb9525198.png)

The first time was formatted using 4.4.0-alpha-002 and the second result is my local machine.
I'll have a PR for this later today.

**Comment by Janiczek** [comment]
@nojaf That looks great!

> Are you interested in helping out on this?

I'm sorry but I can't promise more time to another OSS project. I wouldn't be very active and if trying to help would have to get up to speed with the project, how it's structured etc. Can't find the free time for that...

**Comment by nojaf** [comment]
> I'm sorry but I can't promise more time to another OSS project.

No worries, I fully understand.

I've published https://www.nuget.org/packages/fantomas-tool/4.4.0-alpha-003 that should have a performance gain.

**Comment by nojaf** [comment]
I'm going to close this issue as the situation seems to have improved over time.
The latest version of Fantomas gave me:
![image](https://user-images.githubusercontent.com/2621499/120887156-9145e800-c5f1-11eb-8946-a923837132b8.png)
Feel free to reopen this issue when new information presents itself.
