### ISSUE TITLE
[Feature request] Specific option for Expecto tests

### ISSUE THREAD

**Issue by Evangelink** [fsprojects/fantomas#1275]
I suggest we add a new option to prevent the reformatting of `Expecto` elements such as `testList` and `test`.

I am new to using `fantomas` so it might just be a matter of having the right set of parameters but I couldn't figure them out.

## Pros and Cons 

The advantages of making this adjustment to Fantomas are ease of use for tests.

The disadvantages of making this adjustment to Fantomas are inexistent if we consider that `Expecto` is important enough framework/tool like `Elmish` is.

## Examples

With the current `fantomas` configuration my test is reformatted as:
![image](https://user-images.githubusercontent.com/11340282/101640919-66f3e300-3a31-11eb-944e-f6128e0ce2dd.png)

But I would like it remains like this:
![image](https://user-images.githubusercontent.com/11340282/101640848-53487c80-3a31-11eb-8ad4-07cd690d47f8.png)

or like this:
![image](https://user-images.githubusercontent.com/11340282/101641021-83901b00-3a31-11eb-9339-1066976ec800.png)

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): No idea

Related suggestions: Elmish and web customizations

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to Fantomas
* [x] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Please try [.fantomasignore](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore).

**Comment by Evangelink** [comment]
But this will exclude the full test instead of excluding only the `test "" {}` and `testList "" []`.

**Comment by nojaf** [comment]
Well, I'm very hesitant to change Fantomas because of Expecto.
This is the first time that it is brought up and I have no idea if it is worth maintaining yet another exception to function applications.
Elmish was an necessary evil and can be nested far more so it made more sense to make an exception.
Here I don't necessarily see the need as the formatted result is what I would expect given the style guide.

Some alternatives:

Partial application in combination with fsharp_single_argument_web_mode=true 

```fsharp
let tests =
    let testUtils = testList "UIUtils"
    let testBooleans = testList "Boolean"

    testUtils [
        testBooleans [
            test "meh" {
                // foo
                ()
            }
            test "bar" {
                // meh
                ()
            }
        ]
    ]
```

or fsharp_multiline_block_brackets_on_same_column=true

```fsharp
let tests =
    testList
        "UIUtils"
        [
            testList
                "Boolean"
                [
                    test "meh" {
                        // foo
                        ()
                    }
                    test "bar" {
                        // meh
                        ()
                    }
                ]
        ]
```

**Comment by Evangelink** [comment]
I understand you are somehow reluctant :)

I don't know how many users of `Expecto` are also using `fantomas` so I can't really try to push forward on how important it is for user.

I am pretty new to F# but I am a big fan of enforcing styles so that's a bit of a problem to me (that doesn't mean it's a global problem).

I will leave it to you to see if you want to keep this open for some time to see if other people are having a similar concern or if you want to close it.

**Comment by rahicks26** [comment]
I am a bit new to fantomas too. Is there a way to have multiple configurations. Say one for tests and one for the rest of the project?

**Comment by nojaf** [comment]
Yes, you can change settings for specific files using an [editorconfig](https://editorconfig.org/) file.
Example:
```
[src/**/*.fs]
fsharp_max_if_then_else_short_width=50
fsharp_max_value_binding_width=50
fsharp_max_function_binding_width=50
fsharp_align_function_signature_to_indentation=true

[tests/**/*.fs]
fsharp_disable_elmish_syntax=true
```

**Comment by rahicks26** [comment]
@nojaf  That might be all I need thanks.

**Comment by cmeeren** [comment]
Given that this was mentioned in #2180, I just want to add my +1 here. (Haven't tried the suggested settings above since I'm holding out on using Fantomas until [Rider supports it properly](https://youtrack.jetbrains.com/issue/RIDER-60796)).

**Comment by nojaf** [comment]
"A version" of this now available: [sample](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAbRAXMXEGct8wBeAHQCcyA7CCPQgGQEtDKa7OwzIBVASV5Zm6fD3a0uEANoSpUhlhZsqk%2BfJ4AhWLEwBDauNXr1s4yYuLukALaIAFjzDA5FtxAD0HsADMdr9wsACgBKAMDOAF9wiPoCHB4AIz0qSGcY2M4vMDtHc0ypUIyI6PzAgF1isHLIABpwKHxsYWoAc3xUMGkGiFApSAASLABPAAdkNEhmaiw6nrpBgDc9dABXCa75zgAGevVIfmokGYBlZgAvZD35ABYt6vnI6977wZHxzqmZuf6B5bWNt11ABGZ5cSAAWT0AA8WNREIxEG0sPYfvJgQAmbb3cqPMF9cFDMYbSBI%2BAAeR8cMQJxGmDRnCWK3WnSB8gxYMZAFEjpTqQzwegfJAcXj5gTGUSPpNEjp0AKIEyAaz7hAAMychaHJoULAAMWmKwAcogAO7oaZXVW4CjrUVRfGvKUk2W6BVQP7MwHWm6axUnUZ6aCITSIPwURAABRSejseAo7votsQ9roT3FTveLrl7qVLLQbKkAFY-VAA0GQ2HYBHGLBTYgKNA9E1DotYE3hLBqImbXapLiHRnflnPq75Zq8971AA2UuQcvB0PhxC8UbjRvNxCt9t6Tvd0s%2BFZNVMQdOcCULZ2jnMTz3KgvWgDsc4XleXAGF0M38O%2Bu4RbdAWDVj2h6iCm-ZiuembEtebq3v8%2BabOoAAcL6BouVYRhCiA2IkDYgUe4FcAOaaOsOMEyjeToIVO8gAJxoRWS7Vogv7oF2BFgSeYBnnQF6KlelFwdRXoqiCuzWvO6GIAAgj48a-jYNh6D2WDJtxvEvOR0pQGOuZ3ohhZcMCoKSa%2BzERicOHMHA7H7taoHHhBg5Qdp2bCb8NFieiHJmdJcnxlZNg2boHGlmpfbEZBfHQTpkB6fBokPiCGp%2BRWMkULAqxHAAIogFrBfGqnqc5pFDoSI6TNMsyJfeSHor6klQtC-A%2BAAKvYSInPY1ZYAA6sw8Aoj22KlaeZEVRRUDVfpXnJeiJZNTCrUdUiXJgd1vUDUNqKltOo1RS5MVuZ8M21YZ1rArOS0tdQPjMNC5Lrru1ZctCowRvg%2BDMGF1rIQdnAkeN5WSpV03fOdtFSMCz43QASogcAUPA23DaWNwA3QQM8RNoNTV8NUiXVRmcMCqHw4j1bwEaqy4Q2lL8HgNgdKWwIabjl5g7YqzoMIFrwnq1bKVg8ZtTBkPedDDGSQjSPwBCPN85agsUMLRVztA9gxoBDYAPqmoNw3syDnP42dRMXeoWJzs1GUUHowzkhQyj9Ybu1-ZjEDY5pzixSS5ueUl9VSBipn7LbFD247zusFgNN0xQDNMyzl3G65k1xTYisiMrQu7qL4sW1DXAYr5%2Bx2w7TsuwrvM5wLeci-hGta-bOsUPrbsimNOMmwJXMB4Sc3ByXqXhzCABqXqaNM8DTK0qPuyhnsPEdWkZ-7ENF5LJeNWP0J6tlgE-dQ09HHPC89hjafHevp2b4HxPWhii17zlsBYAA4tgb0fQQ31dhfUs-1r5rzxnFBKW95oh2uuHbO-MQzsWgAAa00K3JB2B8DkmoCcWMrFdC03suoCKRFAbRVAabcBVEH6W3ZLDfYJpzSWlDFgesSIxbjDyvdagzA9wySONhBOKciElUOmVdOYD3LjkgcPTgGJyblwtK0agB9qBHy7GcJRu5VgRjarAQ4xwsC7mPpxJyojgbiIoZI2aQcSZ0AxNLBR8ZqBGMWAiLsrQBF4QoJw6YPDj5CPkI5EhWMyG%2BxOkJKR1Di6cDVBJWBtdqSMFjIkeAehPywG%2Bm0Bh8CTHBK9qE-iHouYQKidvGJYd5CQB-g2ZgdgZgrAANKIEQKMfRSIsCHFQQYTWuSQFhNvhE6xj91BqjLpUzQX5qBIOpPgDKWUjgmkIIgeWcDLQ-0%2Bv-agASFAiNIavfpEjYKRMHjY60apR7jJSBZRAOVWDQAoLUw0eB4C8G4V2PK0Avz2z3L07uPtClvHxiUk5wz5Bql3pU6pDy6mGPQLSTKqx-yrFGLSYY9Jwq7JCfsgFglwaE1KVArgaoX6VKaS05q8cvGUgmQYaZlptnGW2Mvb2HM%2B5AqoSCmhUg1QwMqfCmyWAIQICtOoIJGkGjlGuFMfAepvqdDFZEIAA).

```
[*.{fs,fsx}]
fsharp_multiline_block_brackets_on_same_column=true
fsharp_experimental_stroustrup_style=true
```

I'm going to close this as close enough. Further input should be driven by the style guide.
