### ISSUE TITLE
Comments are sometimes removed unexpectedly during formatting

### ISSUE THREAD

**Issue by kevcrooks** [fsprojects/fantomas#1276]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBlWBbRAxArgHbQAuAlrIQBQCGATgOYCMANADp1uEQT0MBM7Ttx58AzAEowAemlh4sRAGcwS7IhIALMoQYcumHAHktiOgWLlKtRqzB9%2BU2fMUqahWKbpgtOhpBZwKCUNcl0lVDAAbSCIUB4eSAASEgBPAAdkNEgdEgDYxKSANxoAG3ws6IKEgAZAhITIAElCJEISdDIAL2R6hogAFmqwAF0CgF8%2BuOHktMzInPb8-uSS8sqY-ohWYYhIAFkaAA8AGR1EE8RdLWWtpn4a4bGEyYL4htmMysgAI1hYUq3RrFMoVSKbLaCXYYRBYMhwUqUACCJAAoq0jAAzM6EXrQzFlEJPCZTMDvYFzb5-AFAwprMFoCH9MSkxrodI0aCIABCiExsDoiAACvQaDgSGZaQkSHQKsSXqTyYVKQtqYDWVAQetwdCBhq9uzOTy%2BQKLrAAO5maA0EItIqwa1WQhSngyuX9Z48V4JJV7FJfVX-dUzLUMqpbMAAVn1GA5XN5-MFAFV0pk6NbbYR7Y6KM6YwTSkSPSS3iGVdk1S7VqCNtCAGwxyCG%2BMmwUAYVKNqUbcoSjdpAFLogBaLDU9EG9PF9mvLUErGur2sZ0IA7I3m8bE4h9rCfpL84TEPKvYqywGK0Gq6HaxGABzruOb009xF5-GH48T08rf3zC80hdrx1CMAE4HyNJFMQlOgeywLAaCHHxZSPYsFVLH9Z1%2BS9APpG87jqaEm0fBNTXQWF4QBShEJHFCxxLH0zz-OdsJDXDgLuHYIyIiCoLMMi4QRKiYzdWiEnHMBJ2mDDz2YgDWJrdj%2BnuRsWjaEgjEIAAVOhUgAdTIG4D0LUSeHEySyUYqkWJ-NjlwjJgWUIjckToWAiHgAARRBSjIOFoMQkTPwk78Pl-b5civWzwzuPVCMOI4mkxTTNCuVFjPQTQBRIfT4EM3VHlQk90NCzCIpwhS7LuaM4uOFpMTII4jDTGgSAFVEjnSQUlCUXNEMjAq6LQhjpKYxY8nKpdoqUhsaqOAAlRA4DoeAcryiMBgGsT6KnSyFjK%2BTJqZBomDXWaFqW%2BAADl8CwPc6CxJoJSwCIYyYILzOnT5RqwfBSnIHzcVwAV4JIaDNIDCawyOhImHvQjzoFeB9l%2B-7ziBugQf8xtoE0UVSDMAB9c0yFyzRIHekKKRksbIoqqbjrA2aXLoGhUiMOgzj7VayZjDaKeKqnRv2my6ehngHkbeLmdZ9nOZIa7brMB6npe6E3sKr8BeVamfr%2BsgAbwYGWrBiGDqh6F%2BE4rZIGltmObIPtkb1g30cx-dCJxvHoKJkmbn54aSup4XQqisWIH4KEuPigA1GtuR0eA-G5xC%2BY14Ktb9UqlkhvD%2Bn4Ryo%2BOCxSFzePWiT32efy-2dpG8Ls7N3OGn4WLC6ODzPAAcQ0drOuUHrKGTmN%2BprqTA9G%2BdG8U5vqqjlH9fOblEWgABrbkWdXjQlA09AxUQF8brfCMaNHiy68DOSRcOi2Zq4y7EHNA3eRIS0rnBzIvPqwgDNzJFWh3RWdBVbHw-GnD6u1-zBivubCM-BTpcQANKIEQOkRKyUrgtF3jgHEeIQHGVPp9MKe0G7QKbgkfgcM25pThEoTQQ9q5gMptrCe1kQ6iwtozLinRdClEQC5BgN0rjZUQD8fYCBcFbBPowjOM5qaT1IdPBIYgCJcSRD5BghBi5Ok6Bolq%2BBBSaVgKpIRLVepGVHFtIatdx5WUvmw6%2BEYxBWxWGo6ChBTFFDNLoABd1P46B-r2aioDBpFQDoLWxUD7EwK2GISO1snbkBwScMUPx4A0A7LAHquh76P3OEE-B0iwnMIibTBxMSC7Ww8g7GgPxeHUIdpodAqR2jHHyRY0y20x7hIWFceAWIcHoDSLw0p0TmSt2tuiPp2I8nYzoKUTE5NCnWO6ZAkZZCeBiFntbQZdB4QkDEUgNpJkIBmSCCMPoOQlC4B6pEE%2B4wgA)

#### Code

```fsharp
SomeFunction(arg1,
    arg2,
    arg3) // does something
SomeOtherFunction(arg1, arg2) // does another thing
```
            

#### Result

```fsharp
SomeFunction(arg1, arg2, arg3)
SomeOtherFunction(arg1, arg2) // does another thing

```
            
#### Problem description

In this case, a comment is removed based on the original indentation of the code. I'd expect that both of the comments should be preserved in the formatted file?

If the arguments are fully indented (to line up with `arg1`), then I think the comment is kept, but otherwise it's lost.

#### Options

Fantomas Master at 12/09/2020 20:05:59 - f93af000769060d097647b0e889e58592f4656cc

Default Fantomas configuration

**Comment by badgh** [comment]
also in this situation:

```
type ABC = {
    A: string
    B: string
    C: string
    // TODO: later add D?
}
```

TODO comment is removed during formatting...

**Comment by nojaf** [comment]
@badgh please create a new issue for this.
