### ISSUE TITLE
Comments are removed before and after empty array literals

### ISSUE THREAD

**Issue by samarsha** [fsprojects/fantomas#1281]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYrLADoBOJAduVXgC5gAeYAvGANoA%2BnAumAPT8wAQQBmdRGTCJ0ABzoBPMAEMyZZQprUKlemCUstECILAAhRKNhl8M%2BUtXrNO4x248tkADTgoAZ0Q6OgBLSgBzP1QOXwhQVwhIABJFWWQ0SFC6bxjjJIA3ZRwsNOj44wAGHzKEgElKJEo6AGVggC9kKuqAFhyIHhyAX07Y3qhkhVSojMbssvzC4qj2UYgARmH4yABZZUYAGVDEPcRwugALWerVgCZy0f7XIZy4zfHJ9IAjYhxL13mikrLapga4bP5NGTBOA4WCUYR0ACi9QA8qIDpQOiswKJCgF7oMNi8-m8SpAvrAfmCxgUAUssQBmKkJJqyZTQRAWKw2AAKqmU6ECkl%2B8ToZGK%2BMehNGSRSpPJlOliRpizQQO6TKgLLZHMs1iOsAA7pJoMoAnU8rATSFYcLXKLxWUHsYnq4ibkSVN5bbqQtAViAKwayBa9mcvUAVVkqTIJrNlAtVuCNo1OJweMdBOeitlnu%2B3v%2BKtK1QAbEGQzquYgAMI4U1%2BKuwvz26B0azeiCp9PxJ0QF3GN0JD2fPNUgt%2B4EAdjLrNDupsWxkHyFKdxiAlzqlcyHUC9o6VvrpwIAHNPtWGbA2YZR29jV%2Bve5vXjnhxT8-vaaqsQBOU-ssQSMgG3QdBlBve01wzSUsy3Z8dxHRVlXHK5KixYMZwrPUIXQKEKWTLFOwg7tM1dbMJjleCt0Qw8rnWVDy3-SQsJwq8wLFQjXB7MA%2BxGGCyNzV89yoz9gRuIM6gaOhkUoAAVMgFAAdWCc4bwI%2B8uMfYlYLJCjXiEosylWRk6PQ4QyFgLB6gAEUQHBgmwgDWIdIioJI3j3igTI3z0tUDK6IMdkYGpRGks4TgRNNECaM5rDoRT4GUjUujuSCN2gp8%2BPSTzBIPYSrkDVCArqURgkYZFo2UVsyARRhZBsPw-CTa8NX9ZLnNS1z0vc6Ysmyj99PiVZSwK3YACVEDgMh4DihKsSStTuLAAcxi0rKEJy-rXFWKdhsYMaJvgAA5LB0CXMhURqCR0EiDVVnmjT3S09BcBCWyMSIMgQKCSRpL43rCx8gaT1QvbrHgLZnuCV7EHez6HKDaAzj5FtJAAfQNYJ4ouO60s0jKPJmP6kIMn8dtMpxkTIA4m2mi5EtajjiP7UiutWyj1oB1xbn83YyY0CmqboI6Tskc7LuurFbpSh8cYevHICenAXsOGGKoAn7JkJ6iymuWjgUgXmFH54Im3BxXIeV6xYeXVCEaRgC0Yx5TsY63GWYJta%2Bo54xrlBHaADVfTMUJ4FCMIaZvOapfUmXBxW922c9rFriMvWAoICyW0aoP6lD8O6edpm3NJVndPZpO-J2yzYDoABxQJqtqxB6savOA3p4xOIWpaZTl3cPf%2BpP8tTiGobMGFoAAazMdRJ8CPwpKaflqwpY6mvwu8o675nyIE-uifia4hr1g7EANUfAiNE51cQazisoJTGuEeoF2FshxeBVTN-u2Pe504lvKTttPWABpRAiBZBBRCicOoi8BTokxB-DebVpYu1lm7Hqe8tYHyBqnXY4VsJ%2BDOK3YEkdkHR1QT-LqfcE4D2BNcEmesWjhDwKZMIx0TixUQB8LYCAEHVE-mQreRd%2BIKhofvVw9IUJ62ELZMIlB06UEzrCFociKpYBsNJWA4kOEVUaipJBDMXKF06jvURpdE7AnpLrao%2BtFaSEoLovI%2Bpwgv1OrfUID9Gz6IigXHiJiRFeTLpY32w8zbwL2PyD48BlA1lgA1cIJ8z6HG8V2Qx7VjGu1MYEix1R6QpxsZZY2ygPh4HwcbM4TQFCNF2Ck9iHdGZ%2BMyVME48BUTwKaIoPA2TaG5IrnrJErS0TJPhmQHAohIC%2BMWtvAJmtcplHpEPGxHSyBQjoDwpAtT5q%2BB4J0DIfgCANSiKpAYQA)

#### Code

```fsharp
module Foo

let x = [||] // After empty array

let y =
    // Before empty array
    [||]

```
            

#### Result

```fsharp
module Foo

let x = [||]

let y = [||]

```
            
#### Problem description

Fantomas removes comments that occur before or after an empty array literal. The formatted code should keep both comments. Non-empty array literals work correctly, though.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 12/09/2020 20:05:59 - f93af000769060d097647b0e889e58592f4656cc

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello Sarah, 

Thanks for taking the time to report this issue!
At first glance, this seems like a Trivia bug. The code comments are detected from the F# tokens but not printed out in CodePrinter.

![image](https://user-images.githubusercontent.com/2621499/102008031-e59c9900-3d2d-11eb-9044-3c686e63483a.png)

Maybe `SynExpr_ArrayOrList` is missing in https://github.com/fsprojects/fantomas/blob/5a66ce5e54f8752cfa53ab5d2efab72b3ce12bb3/src/Fantomas/CodePrinter.fs#L2693.

Checkout [this video](https://www.youtube.com/watch?v=FCrkUqCCzgI&t=3s&ab_channel=nojaf) for some additional context.

Are you interested in submitting a PR?

**Comment by c-rindi** [comment]
Thank you for submitting the PR @samarsha!
