### ISSUE TITLE
Documentation comment for primary class constructor is removed

### ISSUE THREAD

**Issue by samarsha** [fsprojects/fantomas#1286]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6TYAqALAlgM5hFgAuui5AngA6IA6ATgwHZl1UDKsAtotk7M2EUWEzocBYqQpV8vWgBt80fGTBxWhMkwCu0MrBYtWYiAAoAhmnzsANGABGt9gEowAXmGsfYiVKkspRg-LxOiCYiomERTGAA%2BgB0XHq8Fh6eYFZgANTOPpD24FCEiGRkdgDmhKhgANolEKDmUAAkHPR1kHZkRU2ikG0AblZKeshoja0QAAzFM1AAkqxI7Fz4AF7ICzMALAMQALoDAL67zYftnZNQvf2tQ6Pjt9MzAIwX5pAAslYAHgAZOyIQGIVhVCgPD4AJlmVxOYnOAxa3w6nG6TlgsCU0LETzGEzqb1aMK%2B%2BK4iF4qhxsFYAEEyABRVYAeQAZsDWDsrhB2WMygizl9Ufj0V00JAsTi8YMRoTXrywABmcmDLi0KzQRAAIUQ7OMiAAClYmFZ%2BGRIrKxLoJkKkSKrkMbpjsbi1QSXsSlXs1RBIBqtbr9YbAbAAO6RaBWMorYawaOVOnW0S2xD20TIsSiuUuyXS91O%2BVeqZKgCsfqgge1eoNTEQAFVaPQmNHY6x44n8MnK-ylILWojM47HuLblK3SnPUTS4sAGyVgOamsh%2BsAYSUMcIa7pOn0hmMKb5AvTg%2BFKKLeagBanxZnDSVAHZF9Xg3XED8qXEj2A%2BwPzEOEBZqIOb%2BmOroyh6d6KosAAcL7Lm%2Bho7koPZKn%2Bp4Aee2aXhi%2BaTlBzz3iS5gAJwIUG9LspaTA7rwvBWD%2BaYZkBI5oleE6QUWREwR88xKkuQa1oalLUnAqGsD%2BGEsWAwGXKOHE3oRCreos7yfAJr5UTRok0hJTH6JhYiAbJbFiopBHcSps6wouKxrGQrKsNgTDUAA6uouBSSeMlyWAoHXHh16WaOPGqR8qqaYh9JMLAeirAAIogKjUjRBl2meDoXgpQU9Owt5hTZrTvL6Al-P8Szsng4JMv2iBcLgxhkB58BQpWezwplw7ZexuX3MpJYPmpFZlQCKzsvg-ysi2VhGEwTL-LQ9aEIQ3aSZWZadVhWU4TlEp3PlA3EUq7wLqN-wAEqIHATDwC1bU%2BltxnYSBuH7XlfRHbxxXPudV03fAAByaRxBySyWrwtSVu8vlmbmuW8HoSiVCo3IAGLGAxFSRIIXRfeFxXwQJ-3GPAPxIyjIIY0wWNpYu0C4KaWo0Qk4b4K1Xmwz15l9YdVmDSRYjvOR50xWa1CskwwI6PdXntU9ogmX5AXOrzn388dixwou5Vi1YEtS0QZDA%2BEkRgxDUMnVzu29e9iPI-gqOINTtM4xi%2BNFeYMIaYskB6wb0tkOTDtOy7s10wJDNM4YkSs%2BzULW69e3jv1GvfV7ZLnQAagqOp2PA1Syz%2BHWJ-Jtsp3zoXWUNMwwpFvvlWj8WGGteerIX8dy49pf%2BW9Ffq1XAtKjCpUNwCCWwGQADi5QLUtiArWtRcbQrxwvWXPPvUpacE17I0NxTjsgjqqHQAA1jqZrn%2BUhBOVw5qIChaTrehPldax3Pw1vIVooVNekmdX2gNEDhidnqMgkZwS40QElCarB1BrXpKsT8psmCW0WNJd%2BplP5gQslxQemta6-V9gAaUQIgWglVqqsBWPffgXIeQYLfttbqNtN79wKtXQWogYREzHv8Wq1JCC4GXt3LBys%2B4QULAQ9OYgYQi19hsCEShEAxSqGkcEzVEBOB%2BAgRhMxMEsI-mwr%2B45t4yN3mIZU-Ffb0hUFUVgTdWAtzpBsBxs09D1mwLAeymjZprW8nVHuKtwL4Xwb-LhSplQ%2BxmH7ZGkRWD%2BOGKCOkVQUFxFgXYBBu5An-mejtJO5cpGcKHosZUmcD4OwYYCc0Th4BWA3LAVaEJgGgJBLkoyit1692TsUj2-9zDKnrrEhKRArBOBUYIoguAuDUHYACDpwTJGSnBPADkDCuAcBUSUwhrRlSj1iSyNZnJ2n0yYEodkkAlm9LCdIiJpSZjKn3rEzZTBVBBz0Ys8RJQji7B6IQNGq06jSVOEAA)

#### Code

```fsharp
/// This is the type
type SomeType
      /// This is the implicit constructor
      (a: int, b: int) =

    /// This is the member
    member _.Sum() = a + b

```
            

#### Result

```fsharp
/// This is the type
type SomeType(a: int, b: int) =

    /// This is the member
    member _.Sum() = a + b

```
            
#### Problem description

This example is from the [F# guide in the XML Documentation section](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/xml-documentation#documenting-f-constructs). The documentation comment after the type name and before the constructor parameters is for the constructor itself rather than the entire class, but it's removed after formatting with Fantomas.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 12/14/2020 16:48:17 - 93b3b1e8539595ccf2cfde0867673ae99f13948a

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello Sarah, thanks again for reporting an issue.
This one is slightly more complicated I'm afraid.

In short, the trivia (comment in this case) is attached to the `SynSimplePats.SimplePats` node and is not printed in [CodePrinter](https://github.com/fsprojects/fantomas/blob/fee9f2d352f5af66bfda6979d525f8df3ac99c45/src/Fantomas/CodePrinter.fs#L4116).
![image](https://user-images.githubusercontent.com/2621499/102492994-caee5b00-4072-11eb-96ea-d9bb2e80698f.png)

Adding `genTriviaFor SynSimplePats_SimplePats ps.Range` would print this comment.

However, and here comes the challenging part, there are three versions to write out the constructor.
There is the short version (which your source code has), and two longer (multiline version).
The helper function `expressionFitsOnRestOfLine` will try the short version and fall back to the long version if the page width was exceeded.

Adding the `genTrivia` to the short version:

```fsharp
            let shortExpr =
                optPre sepSpace sepSpace ao genAccess
                +> sepOpenT
                +> col sepComma (simplePats ps) (genSimplePat astContext)
                +> sepCloseT
                |> genTriviaFor SynSimplePats_SimplePats ps.Range
```

will lead to an expression that crossed the current line and so it will fall back to the multiline approach.
And here, adding `genTriviaFor ` to `longExpr` will lead to other problems I'm afraid.

I don't have a good solution in mind yet I'm afraid.
What comes to mind is checking for the comment before printing it.
Something along the lines of:

```fsharp
            fun ctx ->
                let hasCommentBeforeSimplePats =
                    ctx.TriviaMainNodes
                    |> Map.tryFindOrEmptyList SynSimplePats_SimplePats
                    |> List.exists (fun tn ->
                        RangeHelpers.rangeEq tn.Range ps.Range
                        && List.exists (function | Comment(LineCommentOnSingleLine _) -> true | _ -> false) tn.ContentBefore)
                
                if hasCommentBeforeSimplePats then
                    sepNone ctx // TODO: do something clever here maybe?
                else
                    expressionFitsOnRestOfLine shortExpr longExpr ctx
```

Are you feeling adventurous to submit a PR?
