### ISSUE TITLE
Avoid name-sensitive alignment in function call

### ISSUE THREAD

**Issue by lydell** [fsprojects/fantomas#1302]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAzWsBGBDATmANpjBiwB2iYAvGAIwDcYALgO6y1gBMzLAFvkTU6AZmaYAroToAWCQEsAbiLABWMAF8wAXUgAacFADOiFiwUUA5sdTEjEUBGdQAJCwCeAB2RpIllgMHZ0hXJVwAG0lfexcXAAZDOJCASQokChYAZQUAL2Qk5LBZYIgdYM1Cx1K3Tx87f0yg5NDwqJiiGoh6KrjIAFlcAA8AGUtEEcRrAWai%2Bm54mvKXSuCnPvdvGMhsLAjZl1bI6LtOop5ew6zEAFsFOAjKAEEWAFF0gHl0MaoDuPRIqYlhVeutDpt6n5drB9pc3G0TmgzkVRHCIJAsl5cNBEAAhRCYIQABQIuBuZkQ%2BD%2BLhY%2BGiwJWoJqoTq22hsOZYWOHS6xTRUEx2LxBNgQhGsDYlOguFMaSUsGlFko1OctPpyWWzlWLjBIQhbL2KqO7VOvLU-IxWJx%2BMJiAAql4fPhpbKKPLFQplfyAREgRqQWtOayGuyjVyTUjeQA2C2C60ioQAYQiMuMicoxjV0BYopVEB9frimog2ucuvR%2BpDhrhxsRsSKAHZY1bhbb%2BrdsJS82AC4gGVqmS1K1Dq5yETzzgAOZtCm2ixDpx4Ubu9-slwcbYMjmFh8em84AThnOKe6BYlPTNxuuG7ar7-sZgaHW6goZr4bryOS9ESvMts4TRBrjuB4vV5VcHwHJ9Ny2Ksd3fPdI3Oegej-ONEFPc98GA%2B4YTA847zXLQN3BF8dlHIdEPrb9uAtNIMhYD4KAAFXwDwAHUFBmb1AXvIsAx1INYO3DlKO5fc5lRNCWyefBYEkdIABFEAiBQ7iw286T4lxi2I6DSOEqAAl3cSkLmWQLUGIYUnQZj%2BCmV5fSA-hRRYTj4G43lZEWSD130vUyOMhDTOouJ6HNP8rLSdAFCGD4nVwHN8FeIYvCEYxjE9Zd%2BTUHz%2BMfQTn0MxpAmCiNQpcegY0i4YACVEDgfB4Hczzzm8ojS2qIrISMpoys-Xl6CbGqhnqxr4AAOUkG5O3wL4UnPG5bH5egOpIgLipuSQIgsVSqAAMVFa9zEpZjYP6ic5mnP8xtFeB%2Bm23bxkO-Bjo0i1oH4Uls0pAB9NgFA8-hIDW-yK0CvqxxCr8wqPEbZPwXAPA%2BfAxkzFrgf5drfL0wqYJ6kqTPKmGXAWSzhgRpGUbRlgppmyl5sW5bBtBvGDIJradoUPbEBet7TvOqHid5bhUPOSBKeR1GFEzB6uZ5vnEvev9Pu%2BrD-sBmZWbLISCaCoWBvObhaJGgA1blcUseBLCsDHu2x-KoLZja9chsThaNqTxas-aFOzLLLfSG27axvKdIEnXuu2fX3cNopuAskbFNgFgAHEzBStLEAyrKQ7NMPnF0zrSF1g14INy7km4CLvce7nxlxR5oAAa1xRGW7MYwmKyMkFxhabsvA3jta6-Gy9EjYqJJ5xuGq8WJsQNgefxdhhBYrZlJiiguKyp50nben8GZ84IMdvznfB4q3wriSq%2BG8WAGlhC8Gy7KmNIe-JH4CiHpyR5LqODQY6T2hiLa63thiOTuMYfgec2oFzKBHUe7Nx5EzjlXOG4scjWAiBhfAVhppTDcogbA-QEA-xPsPHGxdyy1CvhREBHsUS-nFk8VSVgKC%2BwoP7SgOQOGJWkIgZisB6JEMSllFcVCz640jmPOCE9wRT15KIMWRQJY7UpBQcRKhxTWAPrNTelgd4ZkkX-ah61L4E2vrHSucRRAm1rlzb%2BIwyTYHgLgZMsBMrWAXkvcYpjCzhwKrIlB8i0G2JcKIL2ajFIy1wNgXBUCZb8CyB4TIwwAnaULkggBci-BTHgF8b%2BWRPC4PCbfOxidxbvEKd8fxH18ARHQCDcxYM6FWIYYo0B5xRA1zUSU-A9wWBkKQJkjqRgdCFH8MYfamU7Crk0EAA)

#### Code

```fsharp
foobar [ { one = 1; two = 2; three = 3; four = 4; five = 5 } ]
```
            

#### Result

```fsharp
foobar [ { one = 1
           two = 2
           three = 3
           four = 4
           five = 5 } ]

```
            
#### Problem description

Fantomas violates the [Avoid name-sensitive alignments](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/formatting.md#avoid-name-sensitive-alignments) guideline.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 12/18/2020 10:30:36 - f383752f76699a4354ddec1bb2ed9dd219cf97fc

Default Fantomas configuration

**Comment by nojaf** [comment]
This one can actually be avoided by
```
[*.fs]
fsharp_disable_elmish_syntax=true
```
I'm considering flipping this setting for the next major version, so Elmish syntax needs to enable instead of having it by default.

**Comment by lydell** [comment]
Oh, thanks, didn’t know about that option!
