### ISSUE TITLE
Revisit place parameters on a new line for long definitions

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1307]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAsmALwA6ATqQHYQR4AuYAMrFQOYBiWV09AlqwDqfegAsW9AM4B5AGYAFAIblF6RPUTlJFarT1gAFIoBqmgJ4t2SlejQBBU%2BQus2AFTMAHRK9GL6ATVgsADlERHhXWABVSUQASh0afQgjAGVEOCp4R2crZVV7HMs3T29fAKDQ8MiY%2BMTklMUfPnJs82LrArAHdpd3Lx8-QJCwiOjYhMok5LIphrAAegWwADo1sDF8ACMEMzBYWQ3RfDUxBDBZWBwcWAB3bTmGgzjIABpwKFj6fnZJVDAANofCCgZKQAAk9FK-0gfCo9DewNoEIAboocFhkGggfMAAzveaQACSWUQ8NSfAAXsgCQ0ACxIiAAXSRAF9aSDGVBIdC0LD4YiweC0RisYCuRAAIwc-SQAiKAAeTDhiCYZLYYkFDUlACZcVyWXp2UjQbKeV4YTsrlq9Kj0Zj-jiGjqZbb0ug%2BHAblQ7PQAKJZOTKqg0iUXdGxA1smWm23msWQK04G3I4X2sVO5IAZldyNSHkU0EQACFEJdyIhOqdNCm9PRyJio0aY1yIVCLXyk7XuSKHdiw3TcxBIPnCyWy7AKyxbppoIpYiSUbA5-xWN2IPXG8lDbRjXpY6n2wmu7m7aLHWGAKxDqCjoul8uIKIeLzkOcLqhLlcCKjr8M4SNt2jE1W3jS1YGtU803Pft5gANhvEcC3vCcKwAYRwedJDQ1hJE3XhJz-WQI0QJtdxbIUj3AyDQN7DMwwAdkQu9x0fAhEHQLYaxvYiANIoDmxAyjeSgE9aPTC95gADmY5DWMnRAcO9IiSLIiA91oA9hzAzsIOTKC6MkhoAE5ZLHOxZA0cgcPQdBFD-Td%2BP0Hd1Ios0qN0mihUM2DtXxMMkLHB8FPdT0rjXHjVIE8ihPckTEz07szz7cV5klaUApYiyrNCr0IrDRy1LADTOWEjtRMSgyJN85JdUQkkkHhaQqFcJxhE1SK%2BKKkqwC07kPIqryzR81LtRzTK5LscggiyAARRAcD4D0rIchsnL0FzircuMBv5BEqpg0basHAL5QVIlZB8Mk-T41JREnehhHgDqB31aLXNinb4rhfbxMOzN9Ela9TsVElZD4BVpFfPxJz9BUPArSRJB-P9Lze5zgP3UDdp%2BpLoJSgG9ElBCQYVAAlDJJ3gJ6XvmOl0Y2zHNOx76BQOgmw0lJjSYpuBWmCLBOM0OQiQ0dA-hvSVuu2w94vQXB%2BEWkMOEnOzvk0fpQ286qjsBmSAt5qmCAVvglcQFXyDVlbEOgXwVF4TQAH1bj4Z7REgaXPtl8q9rxkbCdoSVTNJqaVDMaRyGVPCafdm96c9rGyoTXH2fo%2BY9UQs7Q8UcPI74PCBaF8gRbFiXOYT5mk5heWcEVlULatjXoVTozkh1DLCWz3Oo-oY3a9N%2BvVb8a2Att-IHfIZ3Xc1CvSrin2U7%2Bjn05dUnjHTYs4XgOE2Bjv94-erave0nG2aXtPnXGwkzq4HhVyoTesh3ve44Z2hNp6vq21Z37tf%2BsMdQnWvoqWasB6AAHF1BwwRogJGP4X5XjfsyJmc8vo%2BzEn-ZezpgbXxNmbYsNxoAAGtiz2yIeoGQVBUiqEUlcQWv5OqAQxoJRO89jyVXPq3fQOoSaElCLcfB6gZxkk1vNcGVARA-jsFkdiRcy7zF4kwxmLDK5sOovpThNVuHc0JAAaTCB4C6V0qAkmoWoYMWsGiKPWu-FBvUWYLzPpgi%2Bbd9bAIVDdD0khRAILpkgsAH8ZYn3ihg4aOsA4QB1MHQkFJ2B4CmmwQWZJHqIC2AQBAljkjWNnvYqunkNHOK4XoLM-lO6LTYFQW%2BvAfwUgqX4LAFZIgNWSX4FGjCbHIJUag727Chpxn9mGLMHcGiQDsLXTQVBWkolVC4WRXFyBiLhJI3CKkuqH0-g43pBSwn-3mFmVeuD%2B4WKYKoLY8BFAYVgMjdg-CzarKUbYrpuS1H5L9uEwZV8RmzXzooLYeBPH51EKkMw8JFT3I6QEuxX8dJQDJPAIMKpUhQjwG83ZDQsxAJGQGeFsgLF-hgOQHAsgPbrKCf1EJHDClaOKTgkZSLyCel7hk8F3UPhMlpLCSQHBkb-GyayIAA)

#### Code

```fsharp
module M =
    let LongFunctionWithLotsOfParameters
        (aVeryLongParam: AVeryLongTypeThatYouNeedToUse)
        (aSecondVeryLongParam: AVeryLongTypeThatYouNeedToUse)
        (aThirdVeryLongParam: AVeryLongTypeThatYouNeedToUse)
        =
        // ... the body of the method follows
        ()
```
            

#### Result

```fsharp
module M =
    let LongFunctionWithLotsOfParameters (aVeryLongParam: AVeryLongTypeThatYouNeedToUse)
                                         (aSecondVeryLongParam: AVeryLongTypeThatYouNeedToUse)
                                         (aThirdVeryLongParam: AVeryLongTypeThatYouNeedToUse)
                                         =
        // ... the body of the method follows
        ()

```
            
#### Problem description

The Microsoft FSharp style guide had a recent change when it comes to long function definitions.
The original snippet is now what it should be.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 12/18/2020 15:13:04 - 5ecb8db3ac5074e98f318d8ec17e7f7aa08c9aad

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by knocte** [comment]
Should this PR include two more testcases? One where only 1 param is used and another one where a return type is used.

**Comment by nojaf** [comment]
I'm waiting for https://github.com/dotnet/docs/pull/22098
