### ISSUE TITLE
Formatting of multi-line list literals

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/fantomas#133]
This:

```
let xxxxxxxxxxxx = ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
```

is turned into this:

```
let xxxxxxxxxxxx = 
    [ "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"; "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"; "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" ]
```

I think the first is better when the items of the list are that long. Even if the full list fits into the 120 chars, if each element is bigger than a given threshold (say 30), we should put it on separate lines instead of adding the semi colons

Interestingly, I had this which fitted on the 120:

```
    for abcdefg in [[]; [abcdef]; [abcdefghijk]; [abcdefghijk;abcdef]] do
```

and it was turned into this:

```
    for abcdefg in [ []
                     [ abcdef ]
                     [ abcdefghijk ]
                     [ abcdefghijk; abcdef ] ] do
```

**Comment by nojaf** [comment]
If the list or array as a whole is a code construct that spans over multiple lines, Fantomas will now put each item on its own line.
In case it is small and fits on one line, it will format it that way.
