### ISSUE TITLE
SemicolonAtEndOfLine causes syntax error

### ISSUE THREAD

**Issue by lydell** [fsprojects/fantomas#1342]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzMAvADoB2EAhqRAD4B8YAzgBawCu68YiAjq%2BemABGwkaLHiJkqdJmy5gqmGhg6jFu048%2BA%2BJAA04KA2xYAliQDmDVGADahiKAjOoAEiwBPAA7I0kc1j6Ds6QrgBu-Ky%2BdsEuAAwGLi6QAJIkSCRYAMqmAF7IiUkQACyxYAC6wQC%2BhY5loZ4%2BNv6ZQUWhEehRNvZFEACMtUmQALLkAB4AMuaIk4iWWExtff0ATHFllS41wU7D7t7RkIKwsOjLyeGR0b19q0PJWYgAtqZw6LAkAIJYAKLpAHlcNMSAUyhAsAAnKKbapDPaXRpHE5nC4hK5dG7gsAAZgeISyXnI0EQACFELhYJDEAAFciQ8jPbCISFolxQmFFLbOHYuBHopHNFHnfEda49bHFfEQSCE4lkilU2awADuLOg5GMaTCsA1Zk%2BbOcHMQsO28PqByafmFhrFmIlfTAAFZpVA5STyZTqQBVLw%2BSEarUkHV60wG124fjGU0883tS3I04ii2dbpoW5FABsrtlRI9iupAGF0JqGIXPgwOdAsFTDRBI%2Bho1y4bsLYLrUnbRi0zFHQB2HPuhVexAjF6CFl1vBRk3Ns2t%2BPtqA20XdrGOgAcg7zw6V5Y%2BJCnDabSW5EF5zn5MoTQs7q9T676AE5t-KvrgsCzy89nuQp8aY3PON9iXY47xTcV02xfoEmxXN5U9JUnled5w2xY9Z1PFs%2BTbQ5b1Re9IN7FZBjgod30-SFkLeM40MdAC51jBcQLwjsCIg%2B0oMdNYczSDIsABEgABVIQ8AB1UxFiPGdALAC86kXVjl3A%2BMHwdFY8TIncvkhNh0gAEUQdBTFeSj-2hTCXDPOTgMRJSWkCQjOOIop%2BilOCxnGFJcCEph5l%2BRtECyFhISwCT4Ck11ig2RigOYuyrSgAIuzUriVhdDyJjSXBTHGAF-XIGtIV%2BcYvGpBgGDDQ9XSdGKsPnHDFMShyUqIjMkn6bNMvGAAlRA4EheBwsiyU6qs7DL1w5rkqcnt2pcfoB26vqBvgAA5VhngnSEgRST9nmsV1%2Blk%2BSwCvNxQOedgzGM0EADEqV-LBKKEvDZsfVytzglaqXgEZrtMW7EAeyEnrMnNoCYeliUogB9FVTAipYTtsgV7Jmji5ugl9up0hkPABSFpkrYaliisbnGs07zoadHWne9SinWHNPLx8gCaJ0xKw2raWV2-bDuglH4rR5qrvQG6ZhBsGWVepoGbSpnSMdSA2Y54msH%2BiXAalx7CvBuDIeh6sWXhxGpOFxqWOm%2BnMY%2BpJVnubqADVrlJcx4HMCxSanaLLcmpqjgx1S2uxVZNJVzy7tYEhqyq930i9n3yf9hTraD22Q%2Bc%2BbnFWdzI4mfTYCwABxbASrKxAKqq5PsVq1OzqmxN2KzrHHVWDLI4BoHSQ%2BaAAGtSQZAfsAYQSskZRB9026r0Jk2KbJF69QJXO3GYdrqVbWxAVR77A1XmOXEEMnKSEkqqvnSMdechQXHQwhuaZvNjk1b%2B2XFWJaVYAaUQRAvG8r5eYaQJ5MhBGCe%2B896pMStglDOjk16Kwdl9Au4wAqvGYLXR0fsF7UybvhV%2B%2BxUouQdjjFWORLCYB0hYTa8wwqIEECMBAEC%2BgP1wajZe9lV5v3Xi4HEsEVZfGMhYEg0dY76hIDkERhVWDUiErAPidDCpVWkoFR%2B%2BCX6tWztiHEys%2BiqwliyEgyiwjKksNfbaJ9zDnwrKok840GoB3TgQrRbc%2Bg4idl3bW4DJiMkEPAcgxZYCVUsNvXeMw7GWUphNNOcCXEKxIXwiO%2Bj9Jc3IIITA6CuZMCyB4TIExInqMDs0eY8AgTgKyJ4TArj37OBxPnfR-wynAgiRDSE6BcCQCKc4zRCSc4QBxJ3fRlTIRvE1swwpuDDDlEKP4Bgd1Ko2AflUIAA)

#### Code

```fsharp
let f =
  a
  |> should equal bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  c |> should equal d
```
            

#### Error

```fsharp
Fantomas was able to format the code but the result appears to be invalid F# code.
Please open an issue.

Formatted result:

let f =
    a
    |> should equal bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    ;
    c |> should equal d

```
            
#### Problem description

Workaround: Add a blank line between the two statements – then Fantomas won’t add any semicolons at all.

I found this when upgrading from Fantomas 4.0 to 4.3 at work.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

The reason we use `SemicolonAtEndOfLine = true` is because we love it in lists and records, but we don’t care about semicolons at the end of statements.

#### Options

Fantomas Master at 12/26/2020 15:00:23 - 76fa31efcc568685abafe6efe770557f66147917

```fsharp
    { config with
                SemicolonAtEndOfLine = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by lydell** [comment]
Here’s another case. This time, the “blank line” workaround does not help :(



Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAagJaIDuAQlkTkgE5gC8AOgHYQR4AuYti0YAB1pEAbgENO%2BAEZUaAOQT4AFEQDOACU7ocYNFNiwcASjBLVU3WADKnYSwDmlanRNKWiywA1tCpCbRYLETczGzs4VxgMs4AonjoiCzc0DiwqkQO5LRi0ADWiNxKiPFyYgkANGAStkQykqpe2gCCnDV1%2BGK02QCeJqHhA%2BzoEtAAFlWtwu0NpMGjrIODAD5gANpLSwC6YAC0AHxg8LBg5mAA1AxgTJAAPNfnl8WI6KUJ5wCEYClpGY7ZeQUFotwisAPq7PZA4GDI4nCwXK63e5nT5PF5lRCsKHQ8LVKZYerYnEQJYHJpdMTdAB0wUQtCJxPCSgAZoEJrYIQzGYNhpwxuz6LNOPMwtzoSsANKIboEMQ4LDKXKVEQmfaHY6nBH3ZGXXIPRHMJjXHVgEQfRFG42QLli9grcgGPBiNh6tWwzWXbWQc25IxY0Xc93wz7fdKZf75Tj%2B4GRDI4DLSWTwAAKnUSnF8mIDwKKJQxlTxtQJiAaaG8OBabWLVQpvRtTPcSFLYHLmbA8dUnD92cW-WJsOiNDiz3TiMh3tzz1eiALkyL9W79fYzNg9Eb%2BAyYHXDSOS8Gg-gbbUmm0cK3imj-Y18M9twA9Ca0dPzddx5eeSNxuuwEKRcCVgAKogAAe3CSKBELqmeKJgOBUY9iSYCprwSRtkUlTbqqBwDkmyHpm2%2BDbjaKwELARDwMOCRJGA%2BBuscB6UaOZjFMyADCqRhn8OSRmAx5aMYNGQOU4BQKoBScL8qioGsIkQKAgyQAAJJw3QCMgaCQBknBCbJ7BKeI8rqTJwIAAzCcCkAAJIsEgSRWEQABeyDmYsAAsukQJsukAL4uXJHlQMpqlGZpSQ6QpikGQq0mrAFEAAIx%2BQMkAALJiMBAAyCYZYk9jCuFizxQATCZAVeeEvm6fJyVBWp0mQPohgFeE%2BlytFaCxcCRVJS1VjPEQcCpCwLQxDZADyzJZSwzlxbBtAKmVPlJdVLW1SFjU4M1emRW1RmdYsADMPV6VYAg5Ig5CICuvDIRiki0Ft4S2AtgzlewlXhCt20qXVGkbY9gVRXts2ucdECQKd52XddiAZbApB0tAYhidZIiwEjEmwCwAMQM9iCLRVy0BUpP3rY6AOtYZMWzQArGDUCQ9AF1XauiAAKoCGptBIyjLBoxjRBYzjYDMnKYkE%2B9RMRaT9X-cdlPtcZiwAGz0xDZ1M9DrPscjqisVjnbzdAnCrsLos4OLr1LVVxNrbL5PyztVMdbNADsauM8zMMpc8Uh0mbYv41bhM29LwX201jtA9TwIABwexrXva4YQv0%2BblsDG9EAfewX3g3bf0O7b0cu8CACcCfnU0zL3fr6DDMLeMS9nUs1TLheR8Xu0x4VZmzerUMs7wfXoANKfY2ngfN2AOf%2BWHv1QHLXfO0rgzxYl-ee9X90j2PQ2N-NQeZ9bn22%2B3i9FxFJerwMxVq9ZtmcGNLAAbQ3QAOpzAHFtH%2BEWcz63Va58GqXxqtffaa8jqb0TuSWAgR4AABFihEFHvdA%2BL1j4h1PvPEKWkKZO0VhA2%2BoN%2B5pWApZZkAFRiJDiGJKwoxVycE-vAfK9NXKlWDpLUObdw4aTwVHbupdCp01IelayzIiDATGlzCQq4YjASECWdIqdaYcMwVw7BPCF6hW0gIleRDwjxVVqI4CAAlPgq54DMNYSDNRf8T65zPrwqA-Dl6ENmvFd2JjzFwFoIeLA6A-a0AmpZSQ6ApL03itPWeYA86BWAegXAEl4zTQAGKrl5PdAC4c9HuOBPFeO-cfGWJSkk6gCZ0m0Eyf7NWYxOg5HuqCWYLDRiQGiYA76zidH4PAR4iuJjyQ9DGrQLKnZrGtLYXY9g-8YlxJJl01xV9BE33CCVNWZDBmUmGaMjMASgkhLCREjx7TuFAK6YknAySKkZOqHSbJdVcnAy6hvCymzujbLUJwUplzylpJua0Gp-c6n-Eac0-KJzNFnO0YssByyDHsCKt1ExspDLkAyPAX44zhbsIhY4nB9UYWrV6V1KBFkyGpMCMbQWLA0U2UxeRGxwIcWcJbqczp0KwqPJ7oMIqJCyXpQQbATgABxAo8jFGqGUSwLF9MaZTM8g4ueWiyadyWfo2aRURFkrKSki6qQ8hZG4gUVQz8rAYn1vKdAE9Zrp1-tMxVsSnHaKXmqvJiwirGIsnIMgurLqcARoke5iAkESKCJjYaNkfaBLpEc4EtrcVKqhSqzaXKhE8q8RZKUiABAUKoYkayZqEhTRmnGqeLKAFsvzsAwl21iXusKfy4CcRR6qFGDK2xCbHX4o7imtxTz3X9IsvZBweByT2ACemd%2BiApApUUN-DO9isF4uVRHXtrr%2B2DAOn3V58Z7AsApSwKlWN7J7okFgXgAFYAP3TBIal867UKqXYm9lyaelwtmgdF5ixIBNEuXSFgt6RCwyxvYKNQSQ0ZGCNS2Nix43ltmU619qaVnsAOki7VPzi0ZTKFIeAYh2I-AcN60gur72drmQXC%2BqrYXquBAdUl36EFqDEFIPAza1CjCsN0JI6UyPwY6VWrpiR4ATWLTYboeA320cOny79o0ROTQTMLGAtAcDMjafxyt8Sukupo26zdWrv02GEMbWdSA%2BPqOziJTYLlNKqFSekaS8bvJAA)


#### Code

```fsharp
module ViewBuilder =
    let rec private buildNode (isHtml : bool) (sb : StringBuilder) (node : XmlNode) : unit =
        let buildElement closingBracket (elemName, attributes : XmlAttribute array) =
            match attributes with
            | [||] -> do sb += "<" += elemName +! closingBracket
            | _ ->
                do sb += "<" +! elemName

                attributes
                |> Array.iter
                    (fun attr ->
                        match attr with
                        | KeyValue (k, v) -> do sb += " " += k += "=\"" += v +! "\""
                        | Boolean k -> do sb += " " +! k)

                do sb +! closingBracket

        let inline buildParentNode
            (elemName, attributes : XmlAttribute array)
            (nodes : XmlNode list)
            =
            do buildElement ">" (elemName, attributes)

            for node in nodes do
                buildNode isHtml sb node

            do sb += "</" += elemName +! ">"

        match node with
        | Text text -> do sb +! text
        | ParentNode (e, nodes) -> do buildParentNode e nodes
        | VoidElement e -> do buildElement (selfClosingBracket isHtml) e
```
            

#### Error

```fsharp
Fantomas was able to format the code but the result appears to be invalid F# code.
Please open an issue.

Formatted result:

module ViewBuilder =
    let rec private buildNode (isHtml: bool) (sb: StringBuilder) (node: XmlNode): unit =
        let buildElement closingBracket (elemName, attributes: XmlAttribute array) =
            match attributes with
            | [||] -> do sb += "<" += elemName +! closingBracket
            | _ ->
                do sb += "<" +! elemName

                attributes
                |> Array.iter
                    (fun attr ->
                        match attr with
                        | KeyValue (k, v) -> do sb += " " += k += "=\"" += v +! "\""
                        | Boolean k -> do sb += " " +! k)
                ;
                do sb +! closingBracket

        let inline buildParentNode (elemName, attributes: XmlAttribute array) (nodes: XmlNode list) =
            do buildElement ">" (elemName, attributes)

            for node in nodes do
                buildNode isHtml sb node
            ;
            do sb += "</" += elemName +! ">"

        match node with
        | Text text -> do sb +! text
        | ParentNode (e, nodes) -> do buildParentNode e nodes
        | VoidElement e -> do buildElement (selfClosingBracket isHtml) e

```
            
#### Options

Fantomas Master at 12/26/2020 15:00:23 - 76fa31efcc568685abafe6efe770557f66147917

```fsharp
    { config with
                SemicolonAtEndOfLine = true }
```

**Comment by nojaf** [comment]
Hey @lydell, thank you for reporting this issue. I'm afraid I don't have a lot of incentive this look into this.
`SemicolonAtEndOfLine` has always been a strange setting as I have not encountered any F# codebase in the wild that does use this (regardless of using Fantomas).

Perhaps we should sunset this feature in the next major and replace it with something that better covers your need.

**Comment by lydell** [comment]
@nojaf There is an easier solution!

`SemicolonAtEndOfLine` is super helpful (our favorite option at work, actually!) in records and lists, but helps nothing when used between statements. And the bug only occurs between statements – in records and lists it’s perfect.

So I suggest making `SemicolonAtEndOfLine` only apply to records and lists – see also https://github.com/fsprojects/fantomas/issues/1161

I could try making a PR that solves both issues at the same time in the upcoming months.

**Comment by nojaf** [comment]
> So I suggest making SemicolonAtEndOfLine only apply to records and lists

That would change the overall behavior of the current setting, this is something we cannot do at any given point in time.
A breaking change requires a major version.
Personally, I'd prefer the remove the old setting completely first and then consider #1161.

**Comment by lydell** [comment]
This option was deprecated in https://github.com/fsprojects/fantomas/pull/2250.
