### ISSUE TITLE
comment deleted on reformat

### ISSUE THREAD

**Issue by jmagaram** [fsprojects/fantomas#1343]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBLAZmAzgFwEM9EBlAVwCMA6ANQIBszEwAfAPjBMOKoAsCcAYX4A7AOaIcYPL0QiAOgCd5IiBAD06sAAUyOXmGiiJOJSrVh6iPAEIwABz2z4YALwOnubojMLlqtU0wAEkAW3tYRTwwEUQAdzBrAjEpWGxHfUQXdGJQ038LeFhfCwsM5xLSiHYwAHl7PHRYESoKdBEXABE8WCojAnFJAEEcMIioyqqa%2BsbmqhzERTAACkwyVX7BqQBaDjJ7eCJmZbHI6M2TAEpWDnQxEUjES99IABpwKBxrRvEcVDAANofCCgKqQAAkeAAnvZkGhIO08G9gWoIQA3BhMf5AqoQAAM71xUGCHTkeBI6AAXshCbiACwoiAAXRRAF9aSDGVBITC4RgREiOajwRjGHycbiAIxCiyQACyBAAHgAZdqIZVyMQyZFEyUAJjxXJZFnZKNBpQh0Nh-0gFFgsHoOotIsx4q5ED1MtRJEQoXQcHozSGeAAoh1aphVbEnVVMAwvka2ULzbKedb4XaHTHhaKsWgJVUAMxeiCQEj2AjQRAAIUQmEe2gIigIoWsi2zFjwiiYiZNya5lt5Nszjq96Nd2PdYDpJag5crNbrj2VsDii2gAkQJLRsA3sxEHbUXZ7VWNalNFhTwqtfNt9tHA5dYsnRIArLOyxWq7X64pEABVexYUUDcvm3XciCaA9ZzjegE1PJMzUfG9h3vQ9x2ffMpwANg-edvyXP9BHoAQhGafBu2gHpFEPCBYPg0ozwgC81CvUs01vEd0KfPNASnAB2PCv0XX9EDlX0KHbGD40QXtz37MEONQrMxx4t0iQADiEhcf0eQQHWaWiwHo2SEL7JDFJQjM0NU3N1NxABObSqyGTBiEUfTQlCAgjOPUzGMQy9kKHayVMfOyXylAkp0-HTCNIX1-QM6CpxMuTmIU50rKgLjbInLDdWlGL8MQVz3J9P0A0M2c-PSsAWM5SyQpymzwvyvjdU9GKSSQAVahEAAVRQoQAdRyXgjLSsz5IsrLmrvMLFIigqpWLYrhKGRRYHWeBOkQeh0D9dzfO7fyLCY%2BrMtTbKEQFbjlo6qUZxihVFWCTABtkEQQzg0heDOMb4G1Wc6UNaaMtm675sRe72oLUpJXfF6lRJTB0EVepFiISIQ0Vew-xwHAoKM18wYC8ygqa9N%2BUFNrMMeqpJVw5HFQAJUQOBFHgQHganUG6oasA2O5G6Yby%2Bn4YsSVBJZ9nOfgAA5MhQkkxQI2CXI-lnSUBau695tCMh6EaA7YgAMUiby8Hcgah3F3jJbUSUtJiuXIngOUjZNtULcUK3jo-fpmyoxYAH04nQIGJt1yH9ep27aaWuGp0lJyWc25soVqRRVXwHmJpBsnzsC1jgvjsW6YdqcDQ-V6M4ILOc-QfAlZVxZ1c1oydfBy7Y-Ym7DeN9BTcQX3-cWW3rXt%2Byqj1IqiUgevG9zvBPaHkex6IAOYqDyt3PDyPtRjym5vLu7p8i2euoX166DFat2ngdoxHzoz%2BZ7wXhcHM-E%2BdB7HY9GtG%2BSozbrColBB%2BHRn6v0LsfUuVNbwVyThLauz1gGKk6LAPAABxawuN8aSCJs0GBU5SZwMaqfTirVkFVyJHqJGN8vbDzVNWQM0AADW1Zg7sOsDgfqJAWyIH0owUIKUiRTXJjNE%2BUN465UrjPUoepmYLwVvEEetY8BrjkJPRAe00YiByFBIYHRxJt0UFrVKMlyFCzLlQxaf9k50JlgvAA0ogRA9h3qfTkCSARrYow0ksb9axX8lLwiQQ4lBdCXboJ%2Bn6fQJCiTv0kRDaRcc7EPhoQoiweo04LwpOIKwm0xDKzJCNRAFA5QIECeIqxH89b93mnIrJl9SiFmigvIYB17igJEOA5oFJ7hEDIH%2BAasAepkkgtVIJDFi4U3gZQ5SmTIm0NxIWeeuJF7G0WCISCaJ1TNDEKY1Wej2iGPIpNOpKTe5pMabI6hKzslqELNfTZa9GgBOVC2CghxiKwCJuIVRcQR6XOCfUvuIsmkPNTP-KchYgGbM6M3AgFArBxObrwEgUIBRKlBbMtQF1P62JtHIeAEYAlcChFYWGUS1loM2WGMlkY1RGRgIoegmBIAhOJaFZZMLHFrIYZsrgih-Sr2qXis6BK2QfCZLSBEOAzZE3%2BGlVkQA)

#### Code

```fsharp
if stateSub.Value |> State.hasChanges then
    // Push changes
    let! pushed = push state

    // Import new etags of pushed items
    do
        pushed
        |> Option.bind Dto.changesAsImport
        |> Option.iter (fun changes -> update (Import changes) |> ignore)

```
            

#### Result

```fsharp
if stateSub.Value |> State.hasChanges then
    // Push changes
    let! pushed = push state

    do
        pushed
        |> Option.bind Dto.changesAsImport
        |> Option.iter (fun changes -> update (Import changes) |> ignore)

```
            
#### Problem description

Notice how the comment above the do statement is removed

#### Options

Fantomas Master at 12/26/2020 15:00:23 - 76fa31efcc568685abafe6efe770557f66147917

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by Evangelink** [comment]
Not sure whether I should create a separate issue but I am facing a similar issue:

```fsharp
        let automationManager =
            new AnnAutomationManager(
                // WPF or D2D rendering engine must be consistent with the ImageViewerAutomationControl used
                RenderingEngine = new AnnWPFRenderingEngine(),
                // Ensure that the objects are bound to the container
                RestrictDesigners = true,
                // Do not select/edit object after they are drawn
                EditObjectAfterDraw = false,
                EndDrawWhenLostFocus = true)
```

gets formatted into:

```fsharp
        let automationManager =
            new AnnAutomationManager(
                RenderingEngine = new AnnWPFRenderingEngine(),
                // Ensure that the objects are bound to the container
                RestrictDesigners = true,
                // Do not select/edit object after they are drawn
                EditObjectAfterDraw = false,
                EndDrawWhenLostFocus = true
            )
```

**Comment by nojaf** [comment]
Hey @jmagaram, thanks for reporting this issue.

> Not sure whether I should create a separate issue but I am facing a similar issue:

Yes, @Evangelink please always report a separate issue and do not chime in on another issue that looks related to you.
See [Contribution guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#related-issues).

**Comment by nojaf** [comment]
I took a look at this yesterday and it not easy to solve in Fantomas straightaway. Having more information in the AST would greatly benefit us in solving this problem. See linked PR to FSharp compiler.
