### ISSUE TITLE
Required backslash removed in string interpolation

### ISSUE THREAD

**Issue by suside** [fsprojects/fantomas#1344]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKASAOpAkgOQGUBRAJQBUx8yB5MTeyYAFwEMAjAG0TxYFtEAvvWxhgcDj34BnAWABqAQQAyAVSIFRANxYcArohnZIAGnBQpiJkwCWAOwDmU1GADaZiKAheMTAJ4AHZDRIOyYTdy9IdG09INcI7wAGU29vXFskWyYCawAvZBTUiAAWBLAAXQiBQo8yqL9A5xCs8KKomP1nNyKIAEYa1MgAWRYADyU7RCVEByYAC1ae3oAmRLLK72qIz0H0BrjINlhYDkW06J1OtG6e5YG0gkRea3FYWwUmIgzqADMJ2wKZQgPx0FnWVQGO3O%2ByaRxOZ0iF1iXSBYAAzPdIgR-CxoIgAEKIH6wABOiAACiwSXxLIgSQjvEwSfpwZtIXU9gEDnDTpj2pc4jcisVMRBINjcQSiaSprAAO506AsCw4WyaWBKmxvBleJksoobLxbbxQxEw4I8nX85HXVEAVlFUAleMJxLJKn8gRJSpVao1LC1th1wNBiFZRvZbU5jQtx15HI6gtRADZHeKcS7pWSAMIcZVSbNvKR66BMUnBsAgjhgg0Q7Yc81QS18pFXeI9MAAdjTzqlbsQQyebDpFarNdShogxq8prF0e5catraTHYAHD2M32ZYWONrHWOw7W2fWo43DouW4mUR2AJwbyUKH5MOmF3i8FgVvWHid1k0NrmwheCYCteSzJKi6aSq6MqPM8rxBvuobhlOka7GezbATa7ZLP0EG9o%2Bz4krBLwnHuqJfshYDTrUp4AbG8KXiBtodisaaqpkTDULYZAkr4ADq1jzKOSFHhGJ5oXRTZAVGV7MUsGJ4ZuCgkrAugZAAIogHDWM8hGfsy37eJOVGodCknNGEjFYUKqS9CKEEjKMOA-GQcwzEQ1aIAQcykkwAnwEJjrFGsokoeJZkxlAoRLrJ2FFL0DoOWMqo-NYozUF6AakkQoz%2BGSUhSNYZEdnaIU-sef60ZFFkxUxcW2amSWjCQiBwCS8D%2BYFqLBZR1GiP%2B1XRVZbY2d4vTdk1LVtfAeC6Lww4kr8ODPrwTiOr0vWmWa5m8LoHA2NpAIAGKku%2BVh0mQAHDSuSzrhBU2kvAQx7QdkwnSSZ16Wm0BzFSuKEQA%2BnK1gBQsm3hdtg0tNdoHxXeTXKdSvjUCSEzFp1CxBWVRm-jOA0HENmEjaiqxpo5iMsMjqPWMWs3zXSS0rWtqIbaFJkQ3OZ67ft1iHYg72fRdV1EzdRTLLhHaQBTVNo0wz083zAsBl9EE-X9pZ0kDINCeDlUSVDlki7DqTLHcTVyAK%2BJ2PAdj2BjFY9WzfWzj45mEzJdWjV4ywKZLjlHWppZFbYVsZLb9tY7reNVQT0NG3JYv2X7YzqbATAAOKWDleUGIVbwR-a2NeMZzv44BDHx-V3jLIlfsvbzkz4ru0AANb4tSreWFIXEEDSO5zQhqIHlHNH6wuFce9ZJONZLeCIHKfOEkwCozJdgSaaltiCcHCgZIO9MkszHbD07W2c%2BZGGT8THbLBNksANKIIg-jOa5Myqr3-D-ICx8ieVYl6wirHQ2V9RYmzusnUYHlnhSDmAXDsjt-5hUAZDce8ZQHG2rvDSWOQHBcGUvYOaMw-KIDYEMBAP8egnyQezFB59qqX12LFL2EA0TgUlgobS9hbAB1sEHN4ORuEBl0GSMgsB2LEIDMHYSnkR79RjuXdBTDPaojRBLHoUt9p0lsFIzQsoHD7wWhvOw28iwyPHDjCq0cx6KNqlPDsaIzZ1x5t-JQfA2DwBYLmWAhUHBzwXpMcxhli641HkA2xMME6pDRL7DR6kabsC4NAmmcwCC%2BCyGMIJciXb1HMjMeAvxv4ED8FwOx18ehoiThor4BS-iBO%2BiSDgPxIDZLLvRJR5xmGqNrho4pJIXhywoVkp2ZhyiFBCFII6hVnDDwEEAA)

#### Code

```fsharp
$"INSERT INTO \"{tableName}\" {colNames} VALUES {values}"
```
            

#### Result

```fsharp
$"INSERT INTO "{tableName}" {colNames} VALUES {values}"

```
            
#### Problem description
Interestingly, formating this does not remove `\`:
```fsharp
$"INSERT INTO \"{tableName}\" {colNames} VALUES"
```
so it's like the third variable is causing the error?
#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 12/26/2020 15:00:23 - 76fa31efcc568685abafe6efe770557f66147917

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello @suside, thank you for reporting this issue.
This looks like a Trivia issue somewhere around https://github.com/fsprojects/fantomas/blob/d5f4d9f52d55a9ad54b964195fff1c0a028a06b9/src/Fantomas/CodePrinter.fs#L2512
Would you be interested in submitting a PR?

**Comment by suside** [comment]
Hi @nojaf
I took a look but unfortunately I don't know what's wrong there 😕

Failing test case:
```fsharp
[<Test>]
let ``backslash in interpolation, issue 1344`` () =
    formatSourceString
        false """
$"\"{bar}\" {1} {2}"
"""
        config
    |> prepend newline
    |> should
        equal """
$"\"{bar}\" {1} {2}"
"""

**Comment by nojaf** [comment]
I believe the active pattern
https://github.com/fsprojects/fantomas/blob/d5f4d9f52d55a9ad54b964195fff1c0a028a06b9/src/Fantomas/TokenParser.fs#L514-L518

Needs to be changed to:
```fsharp
let private (|InterpStringEndOrPartToken|_|) token =
    if token.TokenInfo.TokenName = "INTERP_STRING_END"
       || token.TokenInfo.TokenName = "INTERP_STRING_PART" then
        Some token
    else
        None
```

In order to capture all interpolated strings as trivia.
