### ISSUE TITLE
Functions looses space before parameter if func is defined inside method

### ISSUE THREAD

**Issue by dbrattli** [fsprojects/fantomas#1345]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzArgHbRgAU6aAloVgJRgC8ZtAOoW1gJ4AOiYAKogDOOUvQZsIEALaJpAI0QAnMFgAWlIQDpBI6gHNmjSVNOYcBYmQphqdRsxOmIS7PiWEwABjaQANOBQQthYBkKoYADagRCgzlAAJFy8EZB2-jFSkAkAbgCG6PjIaNHxEF4BZVAAkoRINADKlABeyJVlACyZEAC6mQC%2B7bHdicnFUOlDWbkFRRGlZQCMU6aQALJ5AB4AMtSI24iE%2BuoZVYsATF4jfaaDmXHO2WOp8rCw6KePM4XjC-HnKyyDTklDg6FghAAglgAKJ1ADyuF2hDaIwguAKwWuAymD1WSR440gr3en3x%2BR%2B8zRYAAzICIJAGtw8tBEAAhRC4WCuAAKeSUeVkWGUZOcWCURWxt1xIyehJebw%2BgOyFLmJWpHXpUCZLPZnO5%2B1gAHdlNA8sFajlYGbQhDRaZxZL4jcpHdTHjps80MTFfbEqrftSAKxaxnM1kcrmuACq3F4SjNFsIVptlDtWox6Cxzpx91lBJS3pJSvzAapVQAbKGdRH9a4AMLoc1CesQkQS6BYbl%2B9GYxBS10y%2BJywtQYt%2BlWzQNVADs1fDeqjiDWckUSh7eD7A4gbqkHoZBaJ4%2BV3zVUWpAA557rIwbW%2BDCBvM9nnC6d0Ovl6x76T2X1VUAE5r1ZSFcGFJRW2kaQ8g3R1%2BxzaU82HQ8FVJX8p3LJYKmpMMbzrRBgWkUF3nTaln3g19c3dfMvx9NDSww-8lmWHCa0QUDwMI4iH1giUKNMN8wF3YZkNo48GMpJj4guUNanqLB4UIfglE4AB1SgTgzLcEMHJDP3lIsfwks8-mcRY6VYhdISUWAiHgAARRB0EoIjwN4p1KMQ6jRIMiYaAnU9pyWTUcI2TZqlwfg1EOGEswItRuSwdT4E0jUrh0989PxWjJmMoLpJDUKtlqXBKE2eF4zyLslBhTZuFcIQhDTR8tSDdLPN07z9NHNJ-PQyTzzOKsis2AAlRA4CUeBktSqoOnagSqL3GjfN6rAAr-QaljnEbxsm%2BAADl8AUZREWqYVpHCLVFm3ISP2y1bpHwdBQmclEADFuWgrBwP4eV%2BpM6lFivHC9u5eA1me169k%2BpRvrc0NoDUfkWXAgB9I1KBStRIFu4SwH3UZVty5DNtM0xFiAkbrIFTh4SUXYRBmnGtXmvH7s9Ym%2BryzD-mwqp1i2Gm8jphnNCwI6TqUM6LquoH2ayzmeqel7KDexBYfh5Q-pSAH8ucc4WIF4XRcZrBIdV9XNaqhGcKRlHO2UDGsZOBWuoenqSa%2BMnqXOAERoANSnNlqHgAxmY3NmMruxWDxy7nScYrb-gsgWwveohO2akO6nDl2WbSt3lp8z2E%2B9pPyakc4QrTrZ7NgLAAHFsFq%2BrhCaiEI9ahapEE-HCZHI8jMTgbK4gc5CrTqG1b2NlwWgABrNkBUX7AhEUhpBUQe9jpasjtI6zL3aVof6JHwGqnOYaBYOxAjXVjksBNQ4dcQRzSsIDTmshOoVyluWqjkSLiJbqp8Szn31qYc4O0BYAGlECIG4BFKKhxaib1kMiVEgCD6LS8sXUBqQvbkgrr7EGtdNixSIkINQXdC7R37itHq4kIG8wNlTAWTQjiYGsvoY6hwkqIHkGsBAWCyhAPoRzOOq1mHl1HtSGk-MyiQEhM5fQhAM7EFtIQJoaiqruEQPwWAcl%2BFVWak%2BHBvclogI9mAjaJCqg0iNkolR4FCCmJyIaI4f81zv2oF-Ns5i4rAIJow2xetWGmBpP7KeqtMHbEFPIeAeRGywCakcW%2B989iBJfLgzq%2BCbGoXAbIi%2BZQaSpyUfZTQeR5CYEoZoNQDROA0C2Nk-ili8HWJPqkQ48BESYIaFwTAdi5EOJrkouEvSkRZMRkodAuBcYSNjkTJhw9imQKkDSSeSiBlKFBObERrS8aBB6O0NIQh3pNQiEA-oQA)

#### Code

```fsharp
let func (l: int) = ()

type Test () =
    member this.Testing () =
        let func (l: int) = ()
        return 0

```
            

#### Result

```fsharp
let func (l: int) = ()

type Test() =
    member this.Testing() =
        let func(l: int) = ()
        return 0

```
            
#### Problem description

A function `func` inside a member method will loose it's space before the parameter if:
- fsharp_space_before_member=false
- fsharp_space_before_parameter=true

Preview version: Fantomas v4.4.0-alpha-007

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 12/26/2020 15:00:23 - 76fa31efcc568685abafe6efe770557f66147917

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello @dbrattli, could try setting `fsharp_space_before_class_constructor=true`? Maybe that helps.
