### ISSUE TITLE
Comments inside Elmish gets repeated

### ISSUE THREAD

**Issue by dbrattli** [fsprojects/fantomas#1347]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMALLAtumALwA6AdhBABKHoB08AlgG5gDal1PYADgCdYfBtHQBDAM6SAcuIKIwZSBXGsARuIEBaBRQCuy7rwiDho3M3TwBiKlyonedIkzadjTp2ZFips%2BUVlVQ0tbUksLSwjRy8THwsrGztOOLSlWPSTF0ZxD0ysrwS-aTkFJRU1TR1mLEQCZUL0zybqAF0W1rAACgAqTtachjyOfiFfCVLAipDq7Vr65QBuMfNcWwAzHs1JRABVAWIAagB6CoAxK0RJZQBKMDb8rqLxhjqADxxlS8wbyAGmm1ercAXEOgUnI9WqDwTw2pAADTgKC7LBYZgUADmklQnGREFAJkgABIsABPPjINCQDFYRH46gk1jidD6Kl4rwABiRXkgAEkKEgKFgAMrMABeyB5TgALAyIG0GQBfaUE%2BVQUkU9k04X0onE5ms9kcdUQACMqt4kAAsuJ3gAZDGIe12TFYXB6pxmgBMnPVip4KoZhKtmspuMg6lgsHQnp4TJZbNxJq83st8ZF9WYcHQsAoAEEsABRQUAeQ2jooUtNYA2LN2-uVlpD8bD2qjMbjjINieNNYAzOnGSK%2BOJoIgAEKIDawWwABS0gTqAi7PCwAjZjcDzfVJPJ4epHdjQ4TRuTNZlQ4gkBHY8n09nztgAHdEAJoFJEALWLAP%2Bi86u1DrpuJgBtQQY8C23b7u20bHruPZnmgKZOAArFeUC3uOU4zrYex8JS76ft%2Bv7iP%2BFCARAdboA2oFNsGCEwRGR6AaeSbITWABsGE3qO2EPrYADCkySIJeYRBu0BYLOlG1vWiBbuBO76kxh5waxiHsRyTgAOw8Vh964Yg1r1Oob6ydRtG8GBEAQdQUHXm2zHqSeml9l4AAc%2Bl8YZj5ibmFEYZZCl0duDEqVqzmdq5hpaShJgAJzeXe%2BYbMuYkEAQ4iycBIXWfRkGMZFanRQhsXuV63I1rxd44Y%2BmYENmMYAUF8mKbZymhqpUAsTFvbnl4ZoWtVBmpcuDVNQFOUbnlcIFfZRUHj1Lllf1HGDWm1UCkKWClhQAAqAhkgA6rUHqtTRs3tPNaoRUtkYrfq5UDV6g4jT5%2BZCPogoACKIOgzCNcu00gflYWFXd2q0hpz3rV6l7Vba7x8hs%2B24HYRaXSKuCzlgp3wO6skyn6oVKeFXXFVA0N9Uh2kmGa6GI3aAobMw7yloRZGzkW7yCNckjMC1NaoSTYNkxDFP3dTq20-FvBmtxTPvAASogcACPA%2BOExhxPtWAdm3ZLUO6jTcU1maelK6r6vwDI%2BgEGZAjlnydQEDiGFmnrBtgA5GrdZABD6Og6IA1W5yzllaJvvtkWmxV9NedV1uzvA1pByHTrhwIkfAzx0C4IuUlvgA%2Bs%2BzAEx6Xuda2-vS09a10-LSVK59AjiGSpYCI6ERa%2BdF6i3N4MLZDEZ16GsONzwvo8Ujrft533dYHbDtvs7rvu%2BbVfkzXlMB%2BnViZxHZHLjH4Zxy9JjesNvJzx3XfMBEafBwfYdH1HK55wXbdFwIpfl4TW8JY7ylibGWZtUybV5EjAAar2CcGIWBYl7kTAe10h6G2AcbOk584aXzelAu05xvpSUFhQeBgoMSYmQTrVBCobo%2B0WlgmGDc5ZTwRgQ94P1YBYAAOLYB5nzaQpDqHC1oQ8ehvs9y716mA%2BOvBvSMygfvUOk5czQAANYTm-uo7Akg9oikCP5e2gUazBUAcPI2UV4L11ljWb0iteQyEQM%2BFRU4sCvjsKfRAf1WYUFqKQ-MgoTIrwEBvLwuVzEYOgtIx648WF2MtryAA0ogRAfAUZozsAKAxChKzVi8GY0mHVt7RJAdg2RF95GJw4ZjRqkhcAiK8LrIp%2Btq6lNgqVGx4CnDembryMUWJMCfUxPbOweNEDqGtAgfJThCli2KUA9pVjmG2K8P2KqN8AaYgoEQigJC8xim2WRfQth9qwG2mMsipCLJtRad7SRTkSrWLiaspw-Zr5OEgPmYOb5VDolYE%2BLEwTHY%2BIxP48SNzLqRIYSPJ5KzukmH7JAz5T90R5PtPIdQ8BxDCVgALLETiXFOkhVZQe4sLGYOWTgye1B%2Bz4M%2BT9B%2B4h1CYFqQ-XAIoyTCjtCSq6dD0EwssdSOw8Byx5JFOSTA8K5E8H7Owz5JZRUVmJXnQ4GxIDQoef7GRXSZW0sUZ8iVAhsxYCmUgXlXtkRtGlDSSQ5wBa4jMUqIAA)

#### Code

```fsharp
let html =
    Html.div [
        prop.className "navbar-menu"
        prop.children [
            Html.div [
                prop.className "navbar-start"
                prop.children [                    
                    Html.a [
                        prop.className "navbar-item"                        
                    ]
                    (*
                    Html.a [ prop.className "navbar-item"; prop.href (baseUrl +/ "Files") ] [
                        prop.text "Files"
                    ]*)
                ]
            ]                
        ]
    ]
```
            

#### Result

```fsharp
let html =
    Html.div [ prop.className "navbar-menu"
               prop.children [ Html.div [ prop.className "navbar-start"
                                          prop.children [ Html.a [ prop.className "navbar-item" ] (*
                    Html.a [ prop.className "navbar-item"; prop.href (baseUrl +/ "Files") ] [
                        prop.text "Files"
                    ]*)
                                                           ] (*
                    Html.a [ prop.className "navbar-item"; prop.href (baseUrl +/ "Files") ] [
                        prop.text "Files"
                    ]*)
                                           ] (*
                    Html.a [ prop.className "navbar-item"; prop.href (baseUrl +/ "Files") ] [
                        prop.text "Files"
                    ]*)
                                ] (*
                    Html.a [ prop.className "navbar-item"; prop.href (baseUrl +/ "Files") ] [
                        prop.text "Files"
                    ]*)
                ]

```
            
#### Problem description

Commented code `(* ... *)` inside Elmish constructs gets repeated

Fantomas v4.4.0-alpha-007

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 12/26/2020 15:00:23 - 76fa31efcc568685abafe6efe770557f66147917

```fsharp
    { config with
                NewlineBetweenTypeDefinitionAndMembers = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hey @dbrattli, thanks for reporting this issue.
Did you know about the [fsharp_single_argument_web_mode](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_single_argument_web_mode) setting by the way?

**Comment by dbrattli** [comment]
Hey @nojaf, yes already using single argument web mode 🥰
