### ISSUE TITLE
“FS0058: Possible incorrect indentation” around if/then/else after running Fantomas

### ISSUE THREAD

**Issue by lydell** [fsprojects/fantomas#1349]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6dYDyAnAlgOb4B2AhgDZikAOArgC4oA6JFiDYAHmALysQI%2BAGZgSsTgApRZWXPkLFS5StVr1GzWQCUYBgAtEJAYNMBGExEQUAzokumwAJlatMYAGKxcAWzIMGRHgwWEZ6TlhRA0QwMgAjWAA3RAAaahIwYW9YsDs4EmCs338WNg5uPgcRMElxKQdHQRktFta29o6GwW1daOMMxrALAatbexHHJ0gU8Cg7ANJCG1QwAG1ZiFBGyAASBgBPGmQ0SFIGaY3BXcTKOmO1y9MABhnBqABJAqMGAGV8AC9kK9BgAWR5gAC6lwAvsDNuDdgcjitTiRznCrjsbhQ7it1m8zBjTJAALJkLgAGVIiApRkIBguBKcT3BUNMsMuW0ciMO90gCVgFEZ3Kxt3u%2BMGTiJVx%2BiB8%2BDgFFgJAAggwAKIFbDCKkkIHgiDCSh2VkwjFc4l7XkogVC6XXMV4g1gADM0ogkB%2BNDI0EQACFEEVEAAFMi4Mg%2BDiIXDCxoMXB3U3s80Iq3Ik622OY7G4tASxog91QL0%2B-2B7w02AAd2j0DIdk%2BiVgdYY%2BGVWdM8cTjTZgg5pgtmKRfMz9tFOPFzoArEXPd7fQGgwBVGhHXB1hskJsttskDtNY2IJN9lPbNMj2CC-cOidOt4ANlnJYX5dwiAAwhR6zZ38qbF3oAYbx90NQ9jwgftBEHD1zxtS87VTHNJzeAB2J95zLIMSTlOJoxAzIwJ7M1OVTYc4KvMckLvQYAA50NLRcK1-JU9yLI0xnAsBIPhM8yIzeDr3HXMHjeABOejfRVYRAlwX8fD8fCuyPIjkxI3jrX4ijEMdPNnTMF5nTnBjX0QWV5UVds2MIxxewg08RT4qBR2029dIJQlDOfRApJksyFUFSznSUzjuLAaCoFgzSELPKi3MGMwpUMz4kDRbASAAFVwfYAHV8AZKyOJUk81IcjSnIEyidJE%2BK3U8jCVVwUICgAEWsfB5RkxSE2UmziIHUiytRdEXOE-NHDMQtDLJLh3mEdLDBIdUxh%2BfRvAYXL4Hy50QRZIq7JKy1HKGwTYuqxozBnKbyU%2BYR8C4bA138bx1S4Gg3xsGxd3wqddt61T%2BvU9MoDOE6qrG8xHyurgACVEDgXB4A2ra3h2kL7MOwaQcq1yzvGtCodh%2BH4AAOToHxcNwbV3kCHxliLMw0YOodBp8OgKFbChqS8YoAmjdLrWx0a9LowzCe8eASTZjmue8PxeZjWdoH0MMfRkgB9Kt8E2-RIEZgHSqB47BeQ%2BLxKhhrw32PAqX-JGdaLVG9q49HmcNrGRpNxpmVnaaLbIK3cBthhSfJ6MqZpum9L1qCBsN1n2fwTm9W5uWZP55Fjeor2PLeSA-YDoPJYTpPEBT-xOsV5Xw0A6MNa1hlo54g2%2BXdmKwedJxEtz6aADUxT9Uh4EWO38Mdv7iv1jG3bRUGcfBwQnFq7vyQ8OgSEA3cB4KYf6-t7bftMWznaZmCjtbkVTvniAnEm5euGaiQAHEOBet7EA%2B3cR6LH7G7C2OLy0m3OeHdLrdylonakfolTQAANZ%2BmrjAjgNg0o-AjB%2BQUZNWLOnYiaJ2oVwo8kNs5IBQs3hOEhrnYmiAqwlwDAwGsRh06IFardEgeVdwqgKNhUOuBI5vBwT1Q%2BfUY6AwAdFC%2B7cyH41zgAaUQIgGgs15pGE%2BKgyMup9T8OskI-6Ijm4onPpaS%2BHcRZ3yWvKGw%2Bgv771-gQyK5VAESOAWQs2uc-gkEIOwBqhAybfGyogOIJIECaMGAI2x-9yLiKMZIwYLoDK5xVJzQgJBV7r1bMqP4yT-B0DfOlWAyVvj%2BC%2BgVXB499qT1dmI2epDYk50GHndm0ZyCtmSBSZUhBuEUxYaQdhf58JhLwS7U%2Bg1iFOJqY0F0Xd6lF1bBoikEY4jwDIJ%2BWAn0PFUJodSfp2jBBH3wREqK1TPaOBdEvepzV8A2HiOwcxlz9A-H2Gick2zCplOPhU4ZhsjDwG1Bon4Bx2BHKzic2%2B9TNQ-J1FsxWuAKDCF1oMk%2BEUjqjOic42JoD6n-IIIBIJSAXmlJ0X2WYEJgSnBsB4T6KwwnQiAA)

#### Code

```fsharp
// Original input:
let x =
    if not (f aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa) then
        1
    else
        2

// Formatted output of the above, in for a second format:
let x =
    if (not (
            f aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        )) then
        1
    else
        2
```
            

#### Result

```fsharp
// Original input:
let x =
    if (not (
            f aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        )) then
        1
    else
        2

// Formatted output of the above, in for a second format:
let x =
    if (not (
        f aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    )) then
        1
    else
        2

```
            
#### Problem description
Formatting the input results in:

```
FS0058: Possible incorrect indentation, this token is offside of context ...
```

The issue is not only the compiler warning, but also:

- Idempotency. Running Fantomas twice causes further changes.
- Redundant parens around the `if` condition?

Workaround: Extract the condition into a `let`.

Extracted from https://github.com/fsprojects/fantomas/issues/1342

#### Extra information

- [ ] The formatted result breaks by code.
- [x] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/05/2021 21:00:18 - d5f4d9f52d55a9ad54b964195fff1c0a028a06b9

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hey @lydell, I believe I can solve the idempotency problem.
As for why the parenthesises are introduced, see linked compiler issue.
