### ISSUE TITLE
Inconsistencies in if formatting

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/fantomas#135]
In most of the places where if have something like:

```
if a then
    b
else 
    c
```

fantomas changes to 

```
if a 
then b
else c
```

which is fine. But why did it then turned this:

```
            ||> Array.foldBack (fun line (currentLine, allLines) ->
                if line.StartsWith ("i," + DateTime.Today.ToString("MM/dd/yyyy"))
                then "", line + currentLine :: allLines
                else line + currentLine, allLines)
```

into this?

```
            ||> Array.foldBack (fun line (currentLine, allLines) -> 
                    if line.StartsWith("i," + DateTime.Today.ToString("MM/dd/yyyy")) then 
                        "", line + currentLine :: allLines
                    else line + currentLine, allLines)
```

I'd prefer to keep the then aligned with the else. What was the reason?

**Comment by nojaf** [comment]
The formatting of `SynExpr.IfThenElse` was revisited in https://github.com/fsprojects/fantomas/pull/557.
An attempt was made to align with the F# style guide.
Please create a new issue if necessary.
