### ISSUE TITLE
Comment on first constructor argument gets removed

### ISSUE THREAD

**Issue by Evangelink** [fsprojects/fantomas#1350]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBDArlrALa5YCWsAdgLK5W4DmiATmALwA6LnVEEVRAHcwAQSpVRhEmUq16TVgApuvfurAB6TWADqABQBiYWGwAiAJjNgWiKkhbkqjMHcZPEYYvgDOOAEaecFQ%2B5H52OELkWAAWYLGeAJKkzABq5MKsUkSkFNQAwtRYLLDoYL6I8Kp8GhAASnYOTowAos4eHGCCIuJUBoYN9qzNbe6CSgCUADTVtRDaYG0%2B%2BLbxMWRrnrD%2BAFaI0Fg%2BeKv%2BsPj28bCbYMFYuB48PDW1DX6OB2aIoYyCLEfs8RY%2BEQMyecy0OjMVyosBwPkQmAOmkq0RMu32OFwADMsKxNgBPY6eeAsXBCKizOYteDRADy6IOohxrDMpJEAKxuHQ8NBaip9lZZN0MTsABlYH5DLBoL5OsVgRNIFNwFB4VgKM4fKgwABtFUQUC1SAAEiw%2BIADsg0JAnFglfr%2BCaAG5c4HavXggAMyvBkESQyoWAAyuQAF7IH1zAAsDogAF0HQBfSMG2NQU0Wq1QW32o3Gl3oN1oD1zACMKY0kDoAA9RR5RW5YrmyxZPWmE%2Bpkw7DZWM5btZBTqVm%2Bpna6syXahYK6Og4hiOQ4OhqKIsG14LSsXXBCONJzuYh20mKz3R32s4PYMOZ%2BmC0XdWmIABmG8QSBB824aCIABCiCxpiIPouCksQ2CsLu6jyoetQdvwXbqKejrngOQ7oJBt7ju6j5gFGr5QB%2BX6-v%2BgHikIrDQLg8L%2Bk60qyNQGEQNBR6dieaYmma-bWmhGFjoWE44QArPh76ft%2Bf4AbYACq5qWiwlHUVQtGUXkVCMWA%2B7wix8FsXmnEXjxN58fek4aAAbCJhHiSRtj5OgVE%2BIUITygcpjqZpMEaHBEAIfwSFvih3FXuhRn5lhxY4QA7JZYnEZJiA0POgQsO5XJabBx7duxgVQIZ2V3gJ4IABwxUREmAYUy5qfhHnaT5um9vpqHBbxYX8dh4IAJyld%2BTK4iwhTEKQ6nMRlrFZXpmbNde%2BXhQ%2B4Klt6OGiWVNmIHOC5LgxNVpZ56jeWAvmppNXG5S1oUFR1ZblstVmIH1rAbYupTbTho1eZliHZU1QUzXml0RQt07Lf6SCBrSVAACosPiujRDEqUHnVh0NWeP1nX9vYA-NZYvrdsWiCU5zwJ86DkAu-UjUCe38AdR1gP56bozagatdjpnqKWeHLTWiRYpDIpUC0B5BjEphYHD8BNvhUZtmNOkTY1U3WjmF1zRz-ClsJPO4NW-pYuQ1a0nJZCmC01bmrYPihK94KCXLH3jV9J0Xqrs3tYDZYWTr1YNHALDwJL0s4bLyP04zHHK9mrNqx7OO1KW0U%2B37pjwAAcvgxDJZuiS4sQWr4aWYeo8hzPeOgFBk4IUosLk-WQ1NscmThpYlctKcBzQ%2BAV%2BQVeIDXdcQSJ0DrKSBysAA%2BlEUsI8Xito1HLN2k3hVlt1PuE6S%2BK0iwdZ%2BEHCMyw7%2B2fX532L27-3qzhrYiTWm%2B4Nvu9hFgGdZ6wOd5wXLdz87SunZAculcPADzIPXRu7tm7ggsDdX0D8n57ywF3HufdQHqiHstEeIEvz9SnuQGekBf5nxdgOS%2BWNr7QOBr6GsqRxw-icDSZwB91Kh3lvVeepcL4x0gavKceNqG60MOcA4ch6H2GaMwo%2BRDjr-1dtwq%2BccNYQAsNzAR1YoRYAAOLYHNpbL4Ns%2Bj4ODnbY%2BtNT4yIXgAvKCioFzAsNrah3dgGCB-MuaAABrH8Y93HYB8BDIMuAwKVUztVHCtU2Eow4QFZm1jyGKJvt7X0adhB9z-FgcidgG6Wk%2BAbKg0Q5DiHgIld%2BfxEbpUdgrP%2BliDLnR4VdKcSdfQAGlECIHNHzAWdh-QBLAtuCMYTdrSIZufABZCzzsxvm3NRwsFw%2BBiJIkOpj4zmOGSQ36IU6meynOvX0IZnCYEJowTOERdCIH8DQBA-TwThIqewqpnCrG1JsbwjQT4lpwLJj8IRVARHUBDD8MgKxECQ1gKDCI9FQnXMGRE8OIyamY3GRQuYT5YFzEgKICurAGAUCdIgcUzhinJRyU4fJ1Bv5QqRjCku0TF6xMRfE8ET4qFouQRQPpopAn%2BHgLgOyEpmjJKEH3MpNNllO2IbI6aGznn1NefwtFZgwi4H8JgGZYQYhBnxIGXWwqhkRxypARom4%2BlBjNJgNmSLahPlUWi9cRqPDqRgCwdAWJCFUqiUzWlTy4m2MtQ4tFJr3hIMuTqmFKo4yRhtD4QwoRtS1UTEAA)

#### Code

```fsharp
let automationManager =
    new AnnAutomationManager(
        // WPF or D2D rendering engine must be consistent with the ImageViewerAutomationControl used
        RenderingEngine = new AnnWPFRenderingEngine(),
        // Ensure that the objects are bound to the container
        RestrictDesigners = true,
        // Do not select/edit object after they are drawn
        EditObjectAfterDraw = false,
        EndDrawWhenLostFocus = true)
```
            

#### Result

```fsharp
let automationManager =
    new AnnAutomationManager(
        RenderingEngine = new AnnWPFRenderingEngine(),
        // Ensure that the objects are bound to the container
        RestrictDesigners = true,
        // Do not select/edit object after they are drawn
        EditObjectAfterDraw = false,
        EndDrawWhenLostFocus = true
    )

```
            
#### Problem description

Fantomas seems to remove comment placed on top of the first argument to a constructor call.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [X] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/05/2021 21:00:18 - d5f4d9f52d55a9ad54b964195fff1c0a028a06b9

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello @Evangelink, thanks for opening a new issue. Much appreciated.
To solve this, the comment (trivia) above `SynExpr.Tuple` should be printed.
I believe around https://github.com/fsprojects/fantomas/blob/d5f4d9f52d55a9ad54b964195fff1c0a028a06b9/src/Fantomas/CodePrinter.fs#L1924
and https://github.com/fsprojects/fantomas/blob/d5f4d9f52d55a9ad54b964195fff1c0a028a06b9/src/Fantomas/CodePrinter.fs#L1933
`genTriviaFor SynExpr_Tuple rangeOfTuple` could print the trivia.

The `rangeOfTuple` information is current lost, we should add it tohttps://github.com/fsprojects/fantomas/blob/d5f4d9f52d55a9ad54b964195fff1c0a028a06b9/src/Fantomas/SourceParser.fs#L734 and then add it to https://github.com/fsprojects/fantomas/blob/d5f4d9f52d55a9ad54b964195fff1c0a028a06b9/src/Fantomas/SourceParser.fs#L800

Would you be interested in submitting a PR?

**Comment by Evangelink** [comment]
Yes I am :) I will have a look at this during the week-end and might ping for some support if that's ok.

**Comment by nojaf** [comment]
Yeah sure, sounds good.

**Comment by Evangelink** [comment]
@nojaf Apologies for the delay, I had a look yesterday and there is something I don't get.

> The `rangeOfTuple` information is current lost, we should add it to
> 
> https://github.com/fsprojects/fantomas/blob/d5f4d9f52d55a9ad54b964195fff1c0a028a06b9/src/Fantomas/SourceParser.fs#L734

What I understand is to change:
```fsharp
| SynExpr.Tuple (false, exprs, _, _) -> Some exprs
```

into:
```fsharp
| SynExpr.Tuple (false, exprs, _, rangeOfTuple) -> Some(exprs, rangeOfTuple)
```

and to make it surface on the `AppTuple` active pattern.

But I don't get if I am supposed to add one more object to the return or if I am supposed to do some merge with some of the range.

Current code:
```fsharp
| App (e, [ (Paren (lpr, Tuple args, rpr)) ]) -> Some(e, lpr, args, rpr)
```

New code:
```fsharp
| App (e, [ (Paren (lpr, Tuple (args, rangeOfTuple), rpr)) ]) -> Some(e, lpr, args, rpr) // What to do with 'rangeOfTuple'
```

**Comment by Evangelink** [comment]
Sorry just forgot to post progress, as you can see on the PR I have the start of something but I get the comment set twice before and after the syntax element. Not gonna lie, I haven't understood enough of the code to actually manage to see what's wrong or even how to see what's wrong...
