### ISSUE TITLE
Violation of name-sensitive alignments

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1358]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBDMAvADoBORAdhBABJYC26AdAEYCuWWslA2mAA4lYfRgGcsAT0xheYyYkZ1cJAOYBLcgBlEAMxwBWMAF1SFKmfMWBQxlwDC6VdADWYABTbWlAPpgAtAD4wEWxbWE8cVzhwvzAARgBKeJNKC1SzK2EsRAAPHCJIABFEaBJEOkRyLHyjSAAacChgjnVlEVRpBohQC0gAEgk%2BZDRIdSw6zqo%2BgDdcdFYhjrSABnq0yABJciRKgGVVAC9kVdSAFgmIQwmAX2Ou86h%2B8UH2kcrxnt6ZuYXue4hY27mSAAWVw2Q06kQWnIyiwAAt3qlYgAmJb3S5mG4TbpAx7PYbMWCwdCIszTWbzdq-NLIwFknZlRzErgAQSwAFEtgB5bQQ8hHP5gbSzYLo66AnFkvELSCE4mkyafCk-QUAZjpkx2fFw0EQACEdLBSgAFJS4cpZEgKsxYEjzMWYiX3PoDGVykka8nfKmCk4aiCQLU6-WG0oaWAAd0QJGguGCmymsFjWFUXGtVFt9osGKoWLMksVrpe7vTXspaGpqT0-qgQd1Bu0RsQAFU%2BIMY3HEAmk7gU2ma8L0KLs%2BLsc7pcWiR7x19y4tUgA2GuB7X10OIexxkShchiO3QThWgcixAO3NOj5FglT0tK70VwUAdmXdZDjdKwLKzGj6Ygg%2BH5g5hAeZUAWAYTte8qenec6VhYAAcL6rm%2BTahOg-aCv%2Bp4jo6Y6Xk8bo3tBs4qmkACcSHBiyujRqEdCKL%2BYCZthgGjvm45XlAJbEcqPppLEKyCiuwYNk2DJ0Ey6HkIxWFnsBF64pxspETOvEPvxAJCa%2B1GWuJkkYWkzFyWAIF3Ph%2BJcSpHwkXxSK0kJmzbFgXLkAAKiQ4gAOqqPCMknsZplgGBDxKdxqn3vOFixOqWnISygiePARQOBJlqMUZOHnnhikES8oy3jZ6lIn6Qmgtk6zaK5cIVOyQ6IDscJGlg3nwL5NYnGimXydlUpKflPERXB5ixNWpVgps2iqNkXLtr2RrstkAiICIIiptJNZ6J1rG4ex5kyv14WwYKsRLmN2QAErFEa8AtW1vpbWYQEmQpvW5cMB3WWpkXDc%2BZ2XXAJDwAAcqwdDfiQPLrFkdBtDWsQBS9hZvVAdCsOgKYOPyABiRqKBw0aublA1HfxiFCf913AmjGOQjjJB42ly7QHCZoHtGXgRqorUIgjPVIxZrxjMTpFIhRZ3xSQuDiFyJAQmIt0Iu1D1UE9gXBS6yOCwVX1DWYqLLmVEtSzLctYCDYPRpD0Ow8dvO7TlAuo%2BjqiY4gdMMwTROHSLFjIppaxG9LsuqGIVPO677u9ozQnM6zloc1zvl26BHGax9uKFd9ev2WsZUAGrKnq6jwC0CuMR1ydmQ7%2B1vMLtm%2BzFudgljngHmtRdbKXieK-dldBanAvp1Kme61QyIlU32QFLAWAAOLYAtS0rWtZcbcrFxsSne2TlB3v1%2BYyKjbn1Mu5Ceroc4eqS842AiC5OzmhuxKg%2BtmH%2BV1z18%2BBoVWRnOuCsiU6awgaIAjK7A0WAowVEJoMIok1yA%2BTWiyLYn4LYkBtmkWSH81YD0IrvT6g0AG-TWAAaUQIgPgFUqoVE2A-cofIBSYPfttLK9tXqD1rnvIqvsyaT1qhJEQcJV692wYjb%2BmswoEJJqkZEYs1h7BhJgeKyhQYVGaogZgwIECMNSFglh3U2H8zwdOKRPtzCqkEgHBwyhyAt3IG3LgewbG9lYKUVysBHJqN7GtPydU%2B7qwgpZfBf9CFpFVP7VIkAWTo2jOQbxUwoRcGUKg8GcD1CIK4Bg3RzDHqbyruw4x2tQmpFVDnSJYcUwMI0OaZg8BcD2FgKtGEICwGQl8QBXJO0t7Vx3iYkJ0iLCqkbpEgoIdcDMEwPwkOcIdjiEqGCdpLFOmsO6QUl4FR4A8gYTsCQmAikDPMRPSJnJNm8jaUzEg6BtCQH8bg3p%2ByzFmFVEfSJOySCOCwFopAiyAoNEMMcEYIgsarXaLJK4QA)

#### Code and result

```fsharp
let a =
    Html.button [ prop.style [ style.marginLeft 5 ]
                  prop.onClick (fun _ -> setCount (count - 1))
                  prop.text "Decrement" ]

```
            
#### Problem description

Violation of the new "avoid name sensitive alignments" stuff in the F# formatting guidelines. Should be something like this:

```fsharp
let a =
    Html.button
        [ prop.style [ style.marginLeft 5 ]
          prop.onClick (fun _ -> setCount (count - 1))
          prop.text "Decrement" ]
```

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/09/2021 08:58:25 - ca42f0d7cf05144c5838bba725378e2a856211bb

Default Fantomas configuration

**Comment by nojaf** [comment]
Please use `fsharp_disable_elmish_syntax=true`.

**Comment by cmeeren** [comment]
Thanks! To be compliant with the style guide by default, will that be made `true` by default in an upcoming version? (This also goes for `fsharp_alternative_long_member_definitions=true`.)

Also, do you know when you plan on releasing this name-sensitive alignment stuff in a non-alpha version? (I'm using the F# [formatting](https://marketplace.visualstudio.com/items?itemName=asti.fantomas-vs) VS plugin, and I think it only uses non-alpha versions.)

**Comment by nojaf** [comment]
Yes, I'm considering changing the default value to true and have people enable Elmish instead of having it out of the box.
Sorta, inversing the setting.
However, this requires a major version. 

Could you please point why `fsharp_alternative_long_member_definitions` should be enabled? (separate isssue please) 
`fsharp_alternative_long_member_definitions` matches the GR style guide and the current default should match the update MS style guide.

> Also, do you know when you plan on releasing these name-sensitive alignment changes in a non-alpha version? 

There still are some issues with the changes of the style guide. See https://github.com/fsprojects/fantomas/issues/1341
