### ISSUE TITLE
Update constructor formatting to match MS Style guide

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1359]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAyrALaIBqiATpgDKwB2A5gCo6IByAhiQOoCW6ACwDC9AM7oKAV2jpYFADoK6ECAApF85Su0dyVWoxa40AQT016zVkwEd0ATViS2iRPCawAqqMQAaDVraEBz4iHB08OYGVsZgZpQWhta2Dk4ubh7efgFBKhw2vBSRCdFGiKZRlmU2do7Oru5ePjkqAJQtEAC8HWDQADYcoqI9iBGQvuBQPujovIyiqGAA2pMQoLmQACRYuIuQc%2BjjqypbAG4cfZLIaCu5EAAME3dQAJIRo%2Bj4vABeyE93ABZjhAALrHAC%2B-zWwKg21YewORw2m3Ol2uyxhEAAjFCgpAALIcAAe1DmiGoowYgiRdyxACZ7jCwdpIcd1ni4bs0JAAEawWB9GnaM4XK6LW53Om44WhIi8OB9egmdAAUQiAHkAGakuh-TFgTUXHxMiG49nCzno3n8wXS2GosU3fUAZjtEEg%2BGwHGgiAAQohNXJEAAFDgULiIdCUIVBCRXE0ss0wrY7K18gUx90o0XoiW5AFuqCe71%2BgNB2gAd0o0EGiDep1gNdm9EzKjjiATKlZ2nNJ0te3TtuT2bR4v1AFZCx6vT7-YGKIhPNhcBQaz56427LwW4XDX1jblmV2k8jUwOba2RaOnc8AGxT4uzssLoQDIYiOjiKQyOStiB7g8giPCBuxUXsszPblB0vEdHQxZ4AHYHxnUt50QfFECIHlo13I0O0PU02WHSCoGgu0rzgvMggADmQks5yDERFToP8DTwzsQJPDkSOtDNyNg3N9QATjon0TE1KMKBEIgiA4Vj2w4sBQOhU94Sgi9%2BIdQTnixR59Wnejn0QWV5QFHd9QA-CgMIntiLU0iNOHLSxx0nF9MfRBxMkkyFXM54FIIxMiNUrkHL4pycxc2kpX0t4kDodB1ToJgqD4alcP3KztGApSuItHiyIi694NpV13JQkwKCcCIABFED6Xg5Uk%2BSpCylQcuUsBwNhHjEU0yKb1pAt9MJIkXk1GxRhVTL8AEOR0D4eB0v1AFGUC49gu4%2Bz9gSmDnMG3IsUnEbiTeTVeCJdUVzsOQVSJbAFyGbcWMLcc1usoLbJCq0%2BqKyj9Sxe8TqJAAlMI5HgRblueVbFM67qU2237kX2krDqQ4GwbgIo2EkLDKC1F4oyIBZCyxOG8r7HiiEkPpZga3UADE5FkmZKDKPaBrRoIsVo-SsYh-FafpslmYoVnmqnaBbHDGRKAAfQrXgloESAKc2-Kkd2-riqo7QsRE4HKvDTB1QoUlxCh1XC1h9bOI1qmtcOHX-ueBkp1G42OFN83eHEXH8YoQnidJgH1a%2BrbQsgGm6d4BnEDFiX2fhF3tMlNznkgL2fYt9Ahdj%2BPE7sSX9OlsNvUkxXlepcOwLsqPkY5VG9ZUOkYsz0bSBzX05ngOYGCt1jbY%2BjaI81hvtb%2BtPcjpMqO%2BJRnJDoGRnp7iJ%2B8Hm33uymy6%2B%2BhFJ5RrmW4gOlhvnokatgdAAHFIzuh7ECe%2BhN4nbf2t3lTI7TRyj91-U6THQ7sLOOZJfSKmgAAa19LLSBkZRBJXwBGJieMXoWXYnbXKDsILbUKn-V2kogaZxcBWeO-p0BVlGGUOq506D8GeiYCIGFA6h2eJZWuX9x4-3Cvg6eQQ6QY0zgAaVcNgcak06BvCQSQHUeo2EYJHvbMejsJ7OynlFGefML7TTlKIAQr8Ybv1BJ-Lq9duFDl4Ro-hhtM5fEYH0TyFAGB4w%2BNwRAPJ8QIDkXcdhmD4ZmPPDwpux8XR6UziYBqDA6CL2Xs2OgXwol2EkAuDwcUPhbj8j4hRO9Pp72-oEixwT-7PGdBnO4Wc6aUDoFuU45JLDMOwhQGhcx6FiFYr4xRWDlE4KjngopBDcjOnbuU-OsxZHUC4DyeAHBXywFEP3Eh8d2nZI-rkzhKjzGc2KXcZ0c9yk1T9hwHkDidF%2BwEPgTACViTLMyhw0x%2B9uSjHgFqWR%2BAsAOK2QMoIzpz7lLVM87UZJWIwAoH0TUas-GUx6Zs1OVjtDOiAeUt5FB5R5y8TcwCOSuyTBBP8fYohGbzMWOw8EQA)

#### Code

This is how it's formatted with `AlternativeLongMemberDefinitions = true`:

```fsharp
type SomeVeryLongTypeNameWithConstructor
    (
        aVeryLongType: AVeryLongTypeThatYouNeedToUse,
        aSecondVeryLongType: AVeryLongTypeThatYouNeedToUse,
        aThirdVeryLongType: AVeryLongTypeThatYouNeedToUse
    )
    =
    class
    end
```
            

#### Result

This is how it's formatted with `AlternativeLongMemberDefinitions = false` (the current default):

```fsharp
type SomeVeryLongTypeNameWithConstructor(aVeryLongType: AVeryLongTypeThatYouNeedToUse,
                                         aSecondVeryLongType: AVeryLongTypeThatYouNeedToUse,
                                         aThirdVeryLongType: AVeryLongTypeThatYouNeedToUse) =
    class
    end

```

#### Problem description

This is a violation of the "avoid name-sensitive alignment" clause of the F# code formatting guidelines.

Se also the F# code formatting guidelines, section [Place parameters on a new line for long definitions](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#place-parameters-on-a-new-line-for-long-definitions). It demonstrates how this concrete case should be formatted:

```f#
type TC
    (
        aVeryLongCtorParam: AVeryLongTypeThatYouNeedToUse,
        aSecondVeryLongCtorParam: AVeryLongTypeThatYouNeedToUse,
        aThirdVeryLongCtorParam: AVeryLongTypeThatYouNeedToUse
    ) =
    // ... the body of the class follows
```

Based on this, I suggest that `AlternativeLongMemberDefinitions` should be `true` by default.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/09/2021 08:58:25 - ca42f0d7cf05144c5838bba725378e2a856211bb

Default Fantomas configuration

**Comment by nojaf** [comment]
The setting should not be changed or impacted in any way here.
The default style for constructors should be updated to match the MS style guide.
The rule of thumb is that is that the default Fantomas settings should adhere to the MS guide.

`AlternativeLongMemberDefinitions` tailors specifically to the GR guide. 
The only remaining difference between the guides (at the time of writing) is the location of the `=` sign.
MS puts it after the `)`, while GR places it on a new line.

The existing way Fantomas formats it does not adhere to either style and that is the bug to me.

**Comment by cmeeren** [comment]
> The setting should not be changed or impacted in any way here.
> The default style for constructors should be updated to match the MS style guide.

Makes sense 👍

> MS puts it after the `)`, while GR places it on a new line.

Actually, the official guide is inconsistent about this particular point: https://github.com/dotnet/docs/issues/22296

> The existing way Fantomas formats it does not adhere to either style and that is the bug to me.

I agree.

**Comment by nojaf** [comment]
Thanks for starting the conversation at dotnet/docs.
