### ISSUE TITLE
Aesthetics of long members in a type declaration

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1362]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAkgGKyxgC8AOgHYQQCGARgM7oBOd06YAQgDZ0ALMGgBmJYWBasAllQDmYALQA%2BMAzqsJU2QpVq6ALy1sdS1bPSQANOChNE6dDqaowAbVsRQtWpAAkWLiukBbWnr5%2BAG50vACuyGgePj4ADDbJvvhUSFToAMrSBsjpGWAALOEQALrhAL4lXpVQATgJUKENEdFxbUmlAIydPpAAsnQAHgAysoiTiPLoAmGlYABsKU01PvXh3sn%2BgW2QDCS8y-tRMfGufRkATEO%2BeYgAttJwvLBUAILoAKLZADyImmVGKTQgIhi9k2dU6e2GLSCaGOp3OiO610SELAAGZHhBIHlsBxENxEGJWIgAAoaOgvByIVjo5JseKw7bwpoHVrBE6wM6PfyY3o4soEqDE0nkymzWAAdyZ0Do9iykVgyqcXxZPjZiA5tB2PgREUOfLRQsuPRuOIArBKiSToGSKbAqQBVbC4VjK1VUdWa6TaiVQ3gwjJbQ1cjI85FQfmC7lWrHuHGrB1S50yt2IADC-CYTFzXyksU4bp1tFD4eSkYgRtoJsJSKOCcrwquopWAHYM06XbKRq8GEzK5DofqI3DdkmzSi25aRTaVgAOPvS11U4ufKhjsDVye16fG2e8%2BcWpNL7ErACc6%2Bd3xE6CZxZeLzoe71Bvr0Yuc-jF4xsmXYDGkOKOhusrPG8HzBjiB7fmADaNEB-6ogK7bAcuAyDOBmaII%2Bz6sNB7wCnBKxflOnIzqhZ4ARhi6dthGT9A84FZDk6CAlQAAqrCYAA6tIix7ghVFRjRf50ehiZAVeqYrP0%2BJ4f23ysLAsTZAAIogvDSG8RGfqw7LiT%2BkmImhHSXkx14DOK4FjOM%2BAiDxAjzH8YaIHkAhuugQnwCJEplBsplIb%2BFnSVZck2QpAz2g5ExZCI0jjIC3p0Ogbp-OM2BUoWQa7hKtohUe1EnrRcYhLkmHybcyT9OmCXjAASogcCsPA-mBWKJU%2BHWYXmaakXVYx1q2SxvZNa17XwAAcrELwjqwwL4M%2BLwuBK-SIchYBNs0aEvLEvBOHpYLEKw76OEyPG8qNKZ1T4-RruB01uvAIxHSdMznZdhkOtAAh0pwTIAPrytIAVLNt4VDZVUUXLVOL9HeTVqewmCAqw0wsF1SxBb1tD9Tte2xkc8MYjFD20HcYErKMExo3QGNY9ILDzYtTIrWtG1I9Dg3Ngdn3SKdiA-RlRE3UEd0gfcuF04zzPY%2BgH3HcL31ur9o7-YD7DA6wYMQyJfPlVJcMjdZY2xfcbF045ABqnbcLI8A6Lje7BcbjanmbljS8xyR3MptsTIQmmcAVTvZK7ht4z1nsoabZPm9FltUxAdz2cH4xabA6AAOIONluWIPlXxu0VBPVMeXsVa2gEI5TOJ3PFttCyLfAagA1twuudw4TDcXk9J5gKC2FfBE7x7t3t1wxFv3U3jV07NiDyu3DiKvMkuIDpyVUMJBXfNkQ4c6wPMrGJpUSSbEWVQu88ywHk10wA0ogiDYM5rnzFkQ8MqC4IL6T1CsTGewRyZdEbisO4z0s4eTeEwAQ5c44gJhgLaS98U4L2gSjOmBR5C8AIqwOQC15h%2BUQAwEYCBAGlEvn1auCdb6z1kg3VOOJcS01KJAb4ek5BUFDlQcOXwCh8IyrEKkPFYAcTIRlAqolgFXzMjfWGzCapQNKLiOWXCeFESoLIyIcp5AnyWrvWQB8SzyM8lPEmLZzRzywY-HwuIbZcJVk4ABkx6QMHgHQfMsAmA6BXmvGYliaz0LKjXROdiWEUzYSsXEQcuFaVZowQh8DWYCDyJgXIExQmHnCdfSJTDgjzHgMCABeQsCELUXEjRmcuEAjKSCEJ-1WC8BEJAaxYDzz2NYdgjRLcuGVJkJwKhSA8nbVsFUEoIQmCEACa4BCtQgA)

#### Code

```fsharp
type IFoo =
    abstract Blah : foo : string -> bar : string -> baz : string -> int
```
            

#### Result

```fsharp
type IFoo =
    abstract Blah: foo:string
     -> bar:string -> baz:string -> int

```
            
#### Problem description

I set the line length very short so as to trigger this.

This is purely stylistic, but I would prefer to follow a different rule: if a member declaration has to be split over multiple lines, then all the arguments should be split onto their own line.

```fsharp
type IFoo =
    abstract Blah :
        foo : string ->
        bar : string ->
        baz : string ->
        int
```

I recognise that this change should be accompanied by a change to the G-Research style guidelines, which are currently silent on the matter. If you think this is a reasonable choice, I'll raise an appropriate PR to https://github.com/G-Research/fsharp-formatting-conventions/ .

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/09/2021 08:58:25 - ca42f0d7cf05144c5838bba725378e2a856211bb

```fsharp
    { config with
                MaxLineLength = 60 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by Smaug123** [comment]
Relatedly, by the way, it would be nice to be clear what happens in the following case:

```fsharp
type IFoo =
    abstract Bar :
        [<Path "bar">] bar : string
        * [<Path "baz">] baz : string
        -> Task<Foo>
```

This arises from using RestEase, for example. I don't have a strong preference for how this is formatted, except that currently Fantomas indents a very long way. It puts the `*` symbols underneath the `[` of the preceding `[<Path>]`, which I'd say is correct (though my preference is not strong) - but it puts that `[` on the same line as `abstract Bar`, with the result that it's sadly very far over to the right:

```fsharp
type IFoo =
    abstract Bar : [<Path "bar">] bar : string
                   * [<Path "baz"] baz : string
                   -> Task<Foo>
```

**Comment by nojaf** [comment]
Hello Patrick, this seems doable I think.
In the second example, I would expect that the arrow is after the tuple.
```fsharp
type IFoo =
    abstract Blah : 
        foo : string -> 
        bar : string -> 
        baz : string -> 
        int

type IFoo =
    abstract Bar : 
        [<Path "bar">] bar : string 
        * [<Path "baz">] baz : string -> 
        Task<Foo>
```

I've also raised this in the MS style guide: https://github.com/dotnet/docs/issues/22368

**Comment by Smaug123** [comment]
That seems reasonable; I think we don't have strong preferences about where the arrows go, as long as they're not all forced to be indented a very long way. I'll raise a corresponding GResearch/fsharp-formatting-conventions PR.

**Comment by nojaf** [comment]
> Could you let us know what the easiest answer is from Fantomas's point of view
Yep, I'll let you know.
