### ISSUE TITLE
[Feature request] Configuration to disable blank lines around multiline code constructs

### ISSUE THREAD

**Issue by isral** [fsprojects/fantomas#1370]
I request the ability to disable blank lines around multiline code constructs
(https://github.com/fsprojects/fantomas/blob/master/docs/FormattingConventions.md#2020-revision)

I can not find it in https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#configuration

Related issue: https://github.com/fsprojects/fantomas/issues/1119

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to Fantomas
* [ ] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Hello @isral, thank you for your suggestion.
I feel like this topic is broader than the limited information you provided.
For example:
```fsharp
module MyMod

open System
open System.IO

type Person = 
    { Age: int
      Name: string }

let someFunction () =
    // some implementation
    ()
```

In this case, the `open` statements, the `type`, and the `let` binding are multiline constructs.
I believe you do want blank lines here.
So, I'm guessing you mostly have an issue with the newlines inside inner let bindings.

Next to that, I have also been playing around with the idea to have more control in Fantomas where blank lines occur.
If people can configure it through settings, the existing newlines (found via trivia) could be left out.

On top of my head, you want control over the top-level constructs, inner constructs, and perhaps the number of blank lines after a module.
I need to give this some more thoughts but it could be worth exploring for the next major version.

**Comment by isral** [comment]
> So, I'm guessing you mostly have an issue with the newlines inside inner let bindings.

Yes, that's why I put link to 2020-revision and issue #1119.
I love the compactness of F#, so don't I want blank lines.
```F#
let emit nodes =
    let an = AssemblyName("a")
// I don't want this blank line
    let ab =
        AppDomain.CurrentDomain.DefineDynamicAssembly(
            an,
            AssemblyBuilderAccess.RunAndCollect
        )
// I don't want this blank line
    let mb = ab.DefineDynamicModule("a")
    let tb = mb.DefineType("Program")
```

```F#
let emit (il: ILGenerator) method opcodes =
    let labels: Label array = Array.zeroCreate !method.labels
    let locals = Dictionary<string, LocalBuilder>()
// I don't want this blank line
    for i in 0 .. !method.labels - 1 do
        labels.[i] <- il.DefineLabel()
// I don't want this blank line
    for i in method.locals do
        locals.[i.Key] <- il.DeclareLocal(i.Value)
```

**Comment by nojaf** [comment]
Oh, I see the 2020 revision text doesn't really go into detail. The point being, that it applies to both top-level and inner constructs.
Out of curiosity, do you sometimes break this rule? Are there situations where you do put a blank line?

**Comment by isral** [comment]
> Out of curiosity, do you sometimes break this rule? Are there situations where you do put a blank line?

I still new in F# so I don't know.

But in C#:
* I maybe leave blank lines as is if the code is copied from other source
* For my own code, sometimes I put // in the blank line so it's not really blank.
```C#
	DefaultConstraint = 9064,

	PrimaryConstructorBaseType = 9065,

	FunctionPointerUnmanagedCallingConventionList = 9066,
	FunctionPointerUnmanagedCallingConvention = 9067,
	//
	Compilation, BinaryExpression, PrefixExpression
```
2 last lines are mine, notice empty comment.
Other lines are copied from Roslyn (I leave the blank lines as is).

**Comment by zyzhu** [comment]
I just started to try Fantomas. I find blank lines around multiline code is very disruptive to compact F# coding style. An option to disable it would be ideal.

Take the following snippet from DiffSharp to make a case.
https://github.com/DiffSharp/DiffSharp/blob/dev/src/DiffSharp.Core/Data.fs#L53

The default Fantomas settings will format it with too many empty lines, which breaks the flow of the logics.

Before formatting
```fsharp
type MNIST(path:string, ?urls:seq<string>, ?train:bool, ?transform:Tensor->Tensor, ?targetTransform:Tensor->Tensor) =
    inherit Dataset()
    let path = Path.Combine(path, "mnist") |> Path.GetFullPath
    let train = defaultArg train true
    let transform = defaultArg transform (fun t -> (t - 0.1307) / 0.3081)
    let targetTransform = defaultArg targetTransform id
    let urls = List.ofSeq <| defaultArg urls (Seq.ofList
                   ["http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz";
                    "http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz";
                    "http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz";
                    "http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz"])
    let files = [for url in urls do Path.Combine(path, Path.GetFileName(url))]
    let filesProcessed = [for file in files do Path.ChangeExtension(file, ".tensor")]
    let data, target = 
        Directory.CreateDirectory(path) |> ignore
        let mutable data = dsharp.zero()
        let mutable target = dsharp.zero()
        if train then
            if not (File.Exists(files.[0])) then download urls.[0] files.[0]
            if not (File.Exists(files.[1])) then download urls.[1] files.[1]
            if File.Exists(filesProcessed.[0]) then data <-    dsharp.load(filesProcessed.[0]) else data <-    MNIST.LoadMNISTImages(files.[0]); dsharp.save(data, filesProcessed.[0])
            if File.Exists(filesProcessed.[1]) then target <- dsharp.load(filesProcessed.[1]) else target <- MNIST.LoadMNISTLabels(files.[1]); dsharp.save(target, filesProcessed.[1])
        else
            if not (File.Exists(files.[2])) then download urls.[2] files.[2]
            if not (File.Exists(files.[3])) then download urls.[3] files.[3]
            if File.Exists(filesProcessed.[2]) then data <-    dsharp.load(filesProcessed.[2]) else data <-    MNIST.LoadMNISTImages(files.[2]); dsharp.save(data, filesProcessed.[2])
            if File.Exists(filesProcessed.[3]) then target <- dsharp.load(filesProcessed.[3]) else target <- MNIST.LoadMNISTLabels(files.[3]); dsharp.save(target, filesProcessed.[3])
        data, target
```

After formatting
```fsharp
type MNIST
  (
    path: string,
    ?urls: seq<string>,
    ?train: bool,
    ?transform: Tensor -> Tensor,
    ?targetTransform: Tensor -> Tensor
  ) =
  inherit Dataset()

  let path =
    Path.Combine(path, "mnist") |> Path.GetFullPath

  let train = defaultArg train true

  let transform =
    defaultArg transform (fun t -> (t - 0.1307) / 0.3081)

  let targetTransform = defaultArg targetTransform id

  let urls =
    List.ofSeq
    <| defaultArg
         urls
         (Seq.ofList [ "http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz"
                       "http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz"
                       "http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz"
                       "http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz" ])

  let files =
    [ for url in urls do
        Path.Combine(path, Path.GetFileName(url)) ]

  let filesProcessed =
    [ for file in files do
        Path.ChangeExtension(file, ".tensor") ]

  let data, target =
    Directory.CreateDirectory(path) |> ignore
    let mutable data = dsharp.zero ()
    let mutable target = dsharp.zero ()

    if train then
      if not (File.Exists(files.[0])) then
        download urls.[0] files.[0]

      if not (File.Exists(files.[1])) then
        download urls.[1] files.[1]

      if File.Exists(filesProcessed.[0]) then
        data <- dsharp.load (filesProcessed.[0])
      else
        data <- MNIST.LoadMNISTImages(files.[0])
        dsharp.save (data, filesProcessed.[0])

      if File.Exists(filesProcessed.[1]) then
        target <- dsharp.load (filesProcessed.[1])
      else
        target <- MNIST.LoadMNISTLabels(files.[1])
        dsharp.save (target, filesProcessed.[1])
    else
      if not (File.Exists(files.[2])) then
        download urls.[2] files.[2]

      if not (File.Exists(files.[3])) then
        download urls.[3] files.[3]

      if File.Exists(filesProcessed.[2]) then
        data <- dsharp.load (filesProcessed.[2])
      else
        data <- MNIST.LoadMNISTImages(files.[2])
        dsharp.save (data, filesProcessed.[2])

      if File.Exists(filesProcessed.[3]) then
        target <- dsharp.load (filesProcessed.[3])
      else
        target <- MNIST.LoadMNISTLabels(files.[3])
        dsharp.save (target, filesProcessed.[3])

    data, target
```

**Comment by zyzhu** [comment]
> Oh, I see the 2020 revision text doesn't really go into detail. The point being, that it applies to both top-level and inner constructs.
> Out of curiosity, do you sometimes break this rule? Are there situations where you do put a blank line?

I think the blank lines at the top level makes perfect sense. But it is disruptive for inner constructs, at least to me.

**Comment by nojaf** [comment]
Hello @zyzhu, @isral and @cxa.
I've created a new setting called [fsharp_blank_lines_around_nested_multiline_expressions](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_blank_lines_around_nested_multiline_expressions).
Please give try this out using [4.5.0-alpha-006](https://www.nuget.org/packages/fantomas-tool/4.5.0-alpha-006).

As stated in the docs, this only works for nested expressions and existing newlines are still being preserved.

**Comment by nojaf** [comment]
[Sample link](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBtAPAMQIbQBcA%2BAXQB0AnMgOwBtECwADJgFUQGdGAjWWWsADNYFMAGtEATwAOuAgAsWYABQBKMAF5KNCPUaMNYAhQCuibdV0MwAK3ixomixAgApDrGoARByYC2iNQEAHQACrgUHIjKHNIUAJZBgmBkkKmpwCmQuKlowKncuWAApNwAvmXpaZBGqs629tDBAEp8BACi9AFB9QA%2BRGCu4QrBvPxZuKPpVJZg-WAc8rAmtPBgiACOJrgCBJAANOBQUQQEiQDmHKhg6EcQoC4ukAAkBDLIaJCJe4ePEC8ANx2Zmutz%2BLgADL9wVAAJLUJBBADK8QAXshoeCACx3FwkXFlTFgB5-F5vaQfKDfA64-7PIG0EFoMEwgCMRMekAAsrgAB4AGUSiH5gXOChpMLArIATBDaWB8Y9CbiSZzXu9rpAxrQJaT6cDKSzwdKOU8kYg-PE4LRPABBDoIgDygkF1Ax8oggh2UXlipcyseqqe6opmu1urVDKZNw9YAAzKb-kjZNBEAAhRDCCiIcIUXABAiICgRv7GMy%2BglEoN08mUrV8HWmwEG0GxrGJqDJ-DpzMiYWwADuReguCi8IBDjk8U8JceZcQFaVVflZI1n3DTf1jMNsYArB3IF3Uxms4gAKrSCkUEdj6gTkdnGcdr20H3gv0QAMuatQEN1jcrlu0ZGn8ABsB5Hj2p4AMK0KOHDQZ4XCmIQIizi4L5vn8H5gF%2B9yAbWYYNuhzbbq2koAOwQSmUF9lyFrcEW6Get6C7vpWKoEWuUAAeCpHAbGAAc1HdiefaITa1DMUIrGLv6y58X%2BRH8CRQE7pKACcImpragiFhQiF%2BH4uDSfOcmfgpeqEeuxGblG6lslCsaHjRYnZualrWk%2BsaYWx2EcYGXGhjZKl2S2zKxqy7LOZBun6R5Vr8N5kpmexS6cYp1k8bZgH2eRbIms58KIgQjrUKwFCSAA6vE4rPrJaXyRlVncfWoW5eFMaSqyCYxTRtoUMsCJeIgtDxJa%2BmmaYfmPDheHEkFdbUmFZERd17bOTyvKwoIrDyIEnRREiSwUAQNXwHVbZyo1FnNWqWVfEEql5WtbL7ptfLwoI8S8o6V5yCI7S8nEnAcNOUkdru13%2BelgWZa1y0datXVsuBH28s0iBwBQ8DnZdkpYtDs0Bd%2Bi2aojikvSj4KslR6OY9j8AAHL%2BIxFDOrChZ%2BFcHasuZuGWfdrV%2BCsZxjW62AiMZpxFqwGorQJ3XCc5DMiPAXKi-E4uIJLFDS5NB7QPIET4PpAD6A7xBd8iQPz80-quwVUk9CsOTTWnowNeaSI6FCClweM2x2hN24LwYPRTepUyBjyygeW1e7gPt%2B-EXAs34bMc1zPORaHd3h8Lmva7r%2Buy-LSOKzC0rRZKkCJ8n-sEBrtBi0KJdyAbzlGybhBFhbVvinncMtU7j0-BXbt-NKhW11tABqBppok8AXIH0khzdAv5zWCMuxP%2BXGr1s98tgJjUIQ4NLwiq8D0HV1D6T8Oj5HkadTHLjShtx%2B8j4BAAOIMCBiDDgYNPBr0hkTPEJN8JP3-DlSmb9YzSnerPIuQo0w2mgGINMeYsEMA4GVJE%2BZEASX8BDHyDUYZNWHkLUevEo6IMlNKNGtcmaIAHNrDMBAhyBDlhSEa31qC1XBraBE9EM5FhzpKXyD8YEjzge1BByN34QGlHTWuABpRAiBpA7T2oEeERCAiundNIyhxNYaP3keTPeSjK7GmVt-TolpFjgPvpve2ZMQqNn3q9Y0Hta4omoOcegA1zj%2BECGdRA3AuQIFMTCGRHiw47zofAhhyjYxxicrXW0Y1zjUFPufR81AUT5LkCYbMrBYDFUiVOZKCTzFQMsXI2hCifF2Mno8OMNcYR1xbkWagU4AT9mCeItmAjEjCKQtJRJVDbo0ILqkxR6T7F-DjDPXpzczgmP5Pmbg8BcCwVgGDYJbCOFChmY0iAc1km-gevQ1%2BGTJRxiPr0rwqdcDcHoM41O8gkSSCCHyS5r4ZpNOoVY1pmpAjwGdCYpEbx6DPUYTCOMX9entCdC6C5hsKC0EELbJJ287mtQecGaOmSUG9K0TompQR4Q4NwOfO%2BZiQWyIWrA5S7SVmdJcHGFhvSMGMrECYjgA0hrM04IWdWaC3RAOzCA8GUiGmssJQslJbSkVPJReo3p8KEiEFiUgYFWELH%2BiOCQaEXwODYDBtcGRZQgA).

The setting is true by default so you want to put 
```
[*.fs]
fsharp_blank_lines_around_nested_multiline_expressions=false
```

in your `.editorconfig`.

**Comment by zyzhu** [comment]
It's perfect! Finally I applied consistent formatting using Fantomas. Thank you so much.

**Comment by cxa** [comment]
Nice! Works like a charm, much appreciated.
