### ISSUE TITLE
Object expression newline gets added/removed

### ISSUE THREAD

**Issue by bddckr** [fsprojects/fantomas#1388]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMXEGccAKASjAF4AdAJ0oDsIJMd9YBbbACwEs6BzCmEqRWHLD37Ca9aQ0bAwdRAHcwASQAi3fAAdY%2BAIYAjTGGXdxsxtbCwAbomrVuSXD3wA6Lbv2JSg%2BG09fEQwUS5ePgBRdBCwAF9ZSAAacCgQrCxI-FQwAG00iFAbKAASLABPHWQ0SF4sFMLGSFK7A3QAVxr8pusABlSSiEg1OiQ6LABlbgAvZEGhgBZesABdJviFopWWyurcuonGkpa2zu6CobAARi2bSABZAwAPABleRFfEfnFjoeuAEx9FbraybJrFe7lKrdSBGWCwdB-ayndpdXKXIYAu4oyaINjcODoWB0ACCWCiYwA8gAzd5KZE2GntEIgjZ3SEo6H7WrwxGM4atNEXFYQADMOOakx0BmgiAAQogabBqIgAAoGagGMSOAWMLDULpssEcnbc2F8pGS1HnDGisCLSXDaWyhVKlWfWDKRzQAwhUZ2WC%2BrIkvUQA1Gkqgxjg6yc5rmg6WvU29FoTElACsTqgLrliuVqoAqjpqtRff66IHg9xQznmbFEMaY6aToneQirWazmmelcAGw5yB5t2FxAAYXQfvw45JhEN0CwKrDYAbrKj7IhZr2Fs7KaFtvT9oA7EORwWPQ98UZdfWWU2Nyat22d0m99aD72MzYABxnmX5u6qqzsSdArmuD42NGECxvI24wm%2B-Ifj2IpXAAnP%2BrqkjSeDULObBsAYK4RpB1jQQkrZQq%2BHZId2wp2lc1wDPaw4AaOHp4gSRJ1vaEHNjBlFctRUDJsh9FHoxtwsSO2G4ZxhKIjxVwkfxFHPlRCE0V2bYoQx-zYixozjFgVJ0AAKtQFQAOoWJw4H3qpsHbC%2Bmkie%2BdGHn2-wStJbGktQsAdGMGiIOg3AErhxGGqRjDkU5YDxoKwmHA0Ymed%2B1jXI6LFPM8ag0mZnDfDEISTJwKpYDZ8C-DmizAo%2BLbqUJrkpfuukSf82Y5S8ow0twzxUmWBhLtQUTPDoqr4PgtZgTmmb1VBm5xvBPJQPUbXiV5JTXIO3XPAASogcDUPAVU1fadWOYJCbJetaVfva1ynnth3HfAAByHRsDe1C0moeBsDkObXFdTU3S1bAdOgWRhUoABiKqEZkjhmQh92of8f4sa9KrwA8UMwx8CPUEjkVDtAnCarKuEAPrmNVdmg8tLmra16N6dtGF7f5WoVFS1DvIQZ12bVC1kUtcEs7Cd0eQ9VxAkOuU8wYfMC9oWCfd9jh-QDQOPUzksaazkPQ9wsOIMTpMo2jssYyUAJSVckDK6rgtYPjpvm5bw1kyxFNU4ujh0y4vwG85RvS0c7MdfbBlO7lABqwryrwgT8MLK6XQ1Alg0lLUyzpm0ZYwAI%2BfHLxw0Fi4zSnYyRBnothwlK2R6ltsczYALZeXzwaLAWAAOLYGNE0ENNJIN-a81N4lZTJaJ7cx53XXxwTZsfPKxLQAA1vKWo79g%2BCmZM2oToiX2zbxDnZ2pzMR4h2lQu1W2d7tTvvSo5uKlg3rfKj1QhT6nQCwM1SRjCvFragesrh8RvvFWeuwWoL0Lule0AJnpOwANKIEQDofKhVvijBPhwek8wr6Nhni3A4Bcn5FzQVjHuMQCT4E4JPK4WdFpPjvs1VmyDaGoPllzJ20x%2BCYH8nwL63xKqICMA8BAZCYHX04Y1bh4NeHuRQXLIYYpmJO1JGFPgdBK50GriSaYhjhodFVGZWARkpHDRmvZChcDrp53UbRTRdsbBikdkMZ20NHB0AcQ4V4JI%2BAQJ%2BoA3gIC5xOPXMonOqi3G7g8fwrRJQxRxz8R7LIpDXjaiMPAAwk59CRA-soc2cSYoQDiq4ueSCNFpK8dYMUZc-HeGMJgJh2hOCTAqBMF4VTKFSwON8eAtJSGTEqJgDaAjtHdz8ZScZdIPgrhgNQdANJIDDPvlpWZ6TvErz8VM5wi45FICGXAtIqwFh1HwHDaauQ%2BLxCAA)

#### Code

```fsharp
let test () =
    let something = "something"

    { new IDisposable with
        override this.Dispose() = dispose somethingElse }

```
            

#### Result

```fsharp
let test () =
    let something = "something"
    { new IDisposable with
        override this.Dispose() = dispose somethingElse }

```
            
#### Problem description

As seen, the newline is removed right before the let-binding above it. While I believe that change is questionable (Fantomas normally seems to keep multi-line object expressions as a "group" and thus separate with newlines), there is actually an issue _after_ this is applied:
**If you run Fantomas on the result again you'll be back with the original code, effectively going back and forth.**

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
    I'm currently unable to put aside the time it will take me to make my first contribution to this project, but I'd be thankful if anyone who is also unable to resolve this could leave a few pointers on where to look in the codebase for this issue.
    Nonetheless I want to thank everyone involved in this project for the great work!

#### Options

Fantomas Master at 01/23/2021 12:17:04 - 5317acdc0f67cbde9a30f570a475bf7ff44bca02

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello @bddckr, thanks for reporting this issue.
I totally understand that you can't find the time to contribute.
The fix was quite easy, so I just went for it instead of explaining what's up.
Perhaps next time you can get your feet wet with some other bug.

**Comment by bddckr** [comment]
Thanks a lot @nojaf! Looks like the contribution docs actually pointed out exactly the right things for this one 😄

Have a great rest of the weekend!
