### ISSUE TITLE
Shortening big `if` clause still creates compiler warnings

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#1390]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosA6ogEYDMAyogE4Bu1li8AMgJYDOALmALwA6AdhAh4uAWQCGAT2KIASog4ALKrADuYABSIAHmgCi26IgAOHFrH4BKNFn4sufQUOciwVY9HltjFtogMA8qY8As5hQgBi5Iri7gCqZjgAdBEs-PAGRqbm-AA8sh5ePvx%2BmSZmFgB8oeG1EDoCNeHo4hzQim6FiN6%2B-tpBXKr2ik1hAD5g5LDo%2BO6e3cWl2mAAtNVOdRAsAGad8z0lfUkF0HpUKlRguZVg-Lg4YEqI-KObQjua-LBcGnNFvQZjh4zhckqJumxxABzRBJADCFg44jSbDAvEgxiotjSUO4sXaLDo6MsllebzqADIKZ9vpo-gsAdogadzrAqGCIdDYQj%2BEiUWjIIpEOIkJcvlxtrBbPBiaSNuTNlSaT96QclsyQWyOWxITD4YjkSUBeh2GwcY8qCx8F8kLLHkKXvKFXUqMi-GA4vwdMZENAOIwTv9DpqqGSIBMAPqrG4aSyQAA04Cgfg4Zn4ULYqDAAG0kxBQOFIAASDiSH1ZyBpDgJvNCYs0cQ4LDINC5uoABkTdUgAEl0s8OOQWAAvZBd2oAFlrEAAurWAL7j-PTqAlsstqBVmuFosNpsbtu1ACMS7CkAk2lYXqYzyhSm3tQAHO2V3PnIvawWz2vy2hIMRYFgHAH2cetG2bLND3CAAmU9QMoE04BwCwAEEOD0dIAm2K8xxXCBtkbPxXwXU8v1An8N3-QDgLg1c9wg1s8LAUhaIgSByGMcQjAAIUQSUqEQAAFWJxBmf0qBAsIOCxRBiPfUiV2LUtfygACgMktjd3Ag8mInVioA4rjEF4-jECYNRqGgcQ-D7GhYCsip%2BA0oRpObOShA-ZwyLrCiKzUmjFK0-dIKYgBWfT2M4ni%2BLZRA4mMH0qCsmz%2BDshycmc-DCNk8I3w8hSd2Uyj-OcsDgsYuoADYIsM6LTLhHBrLYHlOCxP02UysACJwIjcpIz9AqKvzqNKoKGJzJiAHYaqi4yYoE8F0BkCT9O63qwjyiBPKEbzNKGv8StosrxqgsJHxmoyTNihFkKc1bsvcraCu-fbVJGo6xp0uoAE4LqMFDtnEhF0BaTrXJyjb%2Bq8wb12G9SPvor7j07JjIsu%2BbEAQlgkIsTq1oh5xNrAbbl0K2GDvewLEZCuojxPVHasQAHxKxnG7qY8HHuJ57yNeqj4ap7SaePWDUb7JBeQCfgABUqEkAhhjxh6%2BvkgayZU-mAp3amKuPFiGdmlCVGlAARRAcBYE1xLBmSuZJsBdtXPmtwRoXdfCI89NRi8e22aWHT0HrMcUNkOAV%2BB730icXxV-K1Ze8nN15UadYm2nwu98RtD7bYWH6RLWjZAxMQhDL9NCmPIdV6H1col3BfKtPj2qzPtHkOAqHgcPI90yvCahnaYY1%2BvtbdpuPem1v27ZeAADksCW6gsJ7f10EzfSjztnmfL59BcESNJEAiNkWlTahpdh13G9O5wj3O1Hp870R95YC2vWPqhT%2BtiL2hEv1qAjEMCOihIBb3jrzROlZk5XxOkxI8v1W5G1dJIAIVBWCcG7iAqOfchBE3to7JSkCR7flTjfIQ0EUbdgvEgqQqD0EcHnovKgy9V7rzgWAmuCcNZ7xwAfd%2BJ9WjiQvuWGBSMYL027DQlBaD2AcGfrw1%2Bh8P5f2oJ1GAMRXT-yoIAlgwDQGxyeuAneRDoEN1gXUaCosqFZwAGraW4mkeAOJMGdWjhwwetcKzEPIqQpi0F9bWO0BEWwfocgOPSM43RPc6huIMdzIxe0THVlEcLGCXtAkm2%2BAAcQUMXASOocguPLjg2cA9SZcOKpTUe18-EZyoS-N%2BxlkLQAANbcU0S0hQbApbkFEogG6C92Z1Hxu48pECNaHTMWIsI0EW7dlnogVQjTeIcFUIgZ4wjEBm1znYRyKF0iLWWmw4Zysq5x04eMypAtqnmNqNBSe3YADS6zjC%2B39s8PsvSZg4SVkHUZDsh511MTc6ZzhoL30CYHE0bBFBFN7v8ghvkKbXJIWPMhEBoIIO7EOdMeAjZQgXgOIgxBRAIFwicv5cT8GArhlrVFNS6ikEobUSAKELZQn4ME-goSLBDg5a0LAAlpawHFgOVoZcmIjKpdvRJEyqn0tueEUgEiWVsvEvwcVdBzLpkOdQbZaR7A5GObUKVZzDEXOMXKlFPi0VMVIFYll8izA4SYKJYg8BxANVgGadMCylmH1%2Betfu1cPEVNpSnW1jKAkspNuwcQxA8BQvYIocgkheRZ0DQTXBZSAWeL-M8eAWEcLkFLHgCNDLaikHSSyjChbsIBp-lQHA2x9FmviRa2VVy6U2orUqupLKS2Wj9KSpAma7ZJhnOOSsbAIhmizCM%2BcQA)

#### Code

```fsharp
module Web3ServerSeedList =
    let MaybeRethrow (ex: Exception): unit =
        let rpcResponseExOpt =
            FSharpUtil.FindException<RpcResponseException>
                ex

        match rpcResponseExOpt with
        | Some rpcResponseEx ->
            if rpcResponseEx.RpcError <> null then
                if (not (rpcResponseEx.RpcError.Message.Contains "pruning=archive"))
                       && (not (rpcResponseEx.RpcError.Message.Contains "header not found"))
                       && (not (rpcResponseEx.RpcError.Message.Contains "missing trie node")) then
                        raise UnexpectedRpcResponseError
        | _ -> ()
```
            

#### Result

```fsharp
module Web3ServerSeedList =
    let MaybeRethrow (ex: Exception): unit =
        let rpcResponseExOpt =
            FSharpUtil.FindException<RpcResponseException> ex

        match rpcResponseExOpt with
        | Some rpcResponseEx ->
            if rpcResponseEx.RpcError <> null then
                if (not (
                    rpcResponseEx.RpcError.Message.Contains "pruning=archive"
                   ))
                   && (not (
                       rpcResponseEx.RpcError.Message.Contains
                           "header not found"
                   ))
                   && (not (
                       rpcResponseEx.RpcError.Message.Contains
                           "missing trie node"
                   )) then
                    raise UnexpectedRpcResponseError
        | _ -> ()

```
            
#### Problem description

F# compiler yields warnings after formatting with fantomas. However, I'm unsure about what the expected results should be (that would make no compiler warnings), please help.

#### Extra information

- [ ] The formatted result breaks by code.
- [x] The formatted result gives compiler warnings.
- [maybe] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/23/2021 17:11:48 - 6d75fff5d28bfcc273a74ada8294cb5741ef8603

```fsharp
    { config with
                MaxLineLength = 80 }
```

**Comment by nojaf** [comment]
Hmm, this is a tricky one.
I feel like it is time I solve https://github.com/fsprojects/fantomas-tools/issues/137 first.
And have a better insight on where warnings and errors occur in the online tool.

I think the first `rpcResponseEx.RpcError` should be further indented but that is speculation at this point.
