### ISSUE TITLE
Formatting error with MultilineBlockBracketsOnSameColumn

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#1396]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwBxRRAFVgHdEAnAOivwBc8mBRdeGn%2BAB10w7AgCuAG1IB1TG2gALRqzwcwAXmHCIEaWzABhTOgBKiAG6wA1ogCC6AJKTpAc0yTDsbNgCWbXHQ2KgAPMAAKAEpNHV04-TBJXjt4eAZ8PE0wWAAjACso7XQ4%2BMQDOHQAM19XLOAwWJKSimo6RiYAIWJbXiYvKprxBnlfWHQmCmD2X3RXfura8KT4FLSMllgAZTYGGdcoyMam3Vp-RQbi46uO-zgZ0wJoAFU8RizBSByFD6O4gF8ildCuhIAAacBQV5sNh7PCoMAAbQhEFATUgABI2ABPAjINCQGZsMHI3QYiwecR4xEkuIABnBV0gjl4iCCm18AC9kAzjgAWGlgAC6JL%2BPJRAox2Nx8IJQWJaPR5MklPhSKuAEYxSVIABZTAhAAyM0QBtZrjYinlxwAHLSBcL-lrUdrMTiqZ9YLBJFa4mSKVS1ccAExa32bRB%2BOCSMZ2NgCADylSN6G5AoglQ8r3tIqdEtd0vxOU93tDUEV-tVabAAGZSxBIJsiCQOohKrB0gAFTDDXBsRg%2Bko7SnZx0k52%2B-Puotegf18vKgNV3l1qCN4iIFtt9IGtoMaCYV7Mqz7mFjWe6IeIEe6UVjvNSqfF89%2BheVq4AVhXDabG9b7cQTwELie4HogR6wCeowgiuGaSFmTQOjeuYKg%2BMrTiWeZKiqaCBk0ABsX5rs2f7pIYkgHng-RqAw4jQGw7bnummZXghOZ3ihbpoU%2BpYvth1JXAA7IRP6bv%2BOoRjk-Ywcx14QLecTjqSk5cTOPHznxuElNawnrqJpFeme0lwSxJSIXJyEuqhhbcZhFY4VWACcOkkHYlR9gwXg%2BJgjFgJeslgPJuiKXOVlQOhz7qYuGr0lW366SRiDhpGBnQVWsHwaZbEKfenHWaptmvvZGqarFRH2G5jBJb4UaGVWfmsaO2UcQWYU2QqWFRcc6ohrFzJIEE8boFQDBYjIZw%2BelJlxGZAUWROoUevl7V2fxXW1qVP52AwsDiLwAAiiCSL4fjuT59WZY1QU5S1spEmpHVvl1y6xXqISOJUVDKOgXDGZsijtmwY3wBaPm8naDVIexlm5VAhIRQ9RVdZ%2BL36sy1QhPGwHyO2XAhAQ6R4HgUE%2Be%2B4MXZDTXQzdcP3StmlxOqBEoyE5hwAw8BAyDK5g-5gXis17o0wVGlVuqQnM6z7bwAAcuI2CSQwiaOH22Bwiu6q83NSkLdgUgwkdKYAGLttg8juVQnG04Vq1NOq2mxZL7M6nrvgG4gxsMKb0JSbFSjdsQ7kAPqnMDlqa1D80w7d8N06LTnM1twxYvGDBGmonOWtzZPTVlV0CzKQvLdb9O6EGMWMq9ieYMnqe%2BGosvy4wSsq2rovh5Tkc3brkj68aHte%2BblvC51TRBiVjJVzXadsM7Peu33Jtmz7jJ%2B8MdGMMHvih5A7d51TgtylbItXEGPUV-qABq-o3LwewZ6D2e6DNfNgMFZYLYXLoIzbJRBut58hENrtOiUEb7wDvlvLmS5H4QGflrEKUdP4Tm-iXCAQZnoAL2rANgkxcb4wyFBe%2BK5Sa735vvFSGEi7H2DMjCuLs3YdGjNAawHQ162A4INTYOBEBeGVNgVKVxzo50umQzuj4lpf1jifJmjJpaIFoAwso9BWQW1xAdao6B-BQQcPAcSjcGCtyuJNUhr9rriMoZI4uVYgzi0ZAAaUoAQd6n1WTMi4bgZMqYjEyQhuZCO2tEGH2Ho9Ue9sAE-T8HgRQRDoEmLfpKKO4Uj4j1-vHRk7JZjSC2q4OWrJAaIByDqBAXjjjGN8bNfxCCbpJOCYjJo1Zy7HEgHYI6rh0BAPQCAsY7I2nyCGK0PqeSRi1W8cZOJZiKExysVcas48mktPclgGEFgTRjFcHohW6iZhaLGIY0pPjyZ%2BI7gE6pbVLHUPqWfJps8YSeINDgHI8BMBkVgETWYciFHGjOjRKaT9c6iJOeYqZFySjVn-k0vaddMA5GkBEuuihNhYiCPqCaBzhEUz3mImUrJ4CJk8dsLE0hgUpLiNWDBTSExJi%2BV%2BaADBJCVB3uUl%2B8TlJ5QscgqRxxqy0KadsXYdEilIFRWMplEJBQ8gJHgQ2RN4TGL%2BEAA)

#### Code

```fsharp
namespace GeeTower.Tests.EndToEnd

module WatcherTests =

    let CanRevokeAnIllegalCommitmentTx () =
        let lndAddress = obj()

        let config = { 
            GeeTower.Backend.Configuration.GetTestingConfig (lndAddress.ToString())
            with 
                BitcoinRpcUser = "btc"
        }

        ()

```
            

#### Error

```fsharp
Fantomas was able to format the code but the result appears to be invalid F# code.
Please open an issue.

Formatted result:

namespace GeeTower.Tests.EndToEnd

module WatcherTests =

    let CanRevokeAnIllegalCommitmentTx () =
        let lndAddress = obj ()

        let config =
            { GeeTower.Backend.Configuration.GetTestingConfig(
                lndAddress.ToString()
            ) with
                BitcoinRpcUser = "btc"
            }

        ()

```

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [maybe] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/23/2021 17:11:48 - 6d75fff5d28bfcc273a74ada8294cb5741ef8603

```fsharp
    { config with
                MaxLineLength = 80
                MultilineBlockBracketsOnSameColumn = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
I believe this is also a bug when `MultiLineLambdaClosingNewline = false`.
I'm guessing 
https://github.com/fsprojects/fantomas/blob/6d75fff5d28bfcc273a74ada8294cb5741ef8603/src/Fantomas/CodePrinter.fs#L2764

Could use an `atCurrentColumnIndent` if the existing record expression is multiline (`GeeTower.Backend.Configu...`).

**Comment by knocte** [comment]
> I believe this is also a bug when MultiLineLambdaClosingNewline = false.

Oh you're right, sorry!

**Comment by knocte** [comment]
> I believe this is also a bug when MultiLineLambdaClosingNewline = false.

Oh you're right, sorry!

**Comment by knocte** [comment]
@nojaf what should be the expected results here?

**Comment by nojaf** [comment]
To make it valid I believe it would be:
```fsharp
let config =
    { GeeTower.Backend.Configuration.GetTestingConfig(
        lndAddress.ToString()
      ) with
        BitcoinRpcUser = "btc"
    }
```

**Comment by knocte** [comment]
> To make it valid I believe it would be:

Are you sure? Remember this bug only happens with `MultilineBlockBracketsOnSameColumn=true`. Therefore, I was thinking that to respect this setting, the snippet could be something like this:

```
let config =
    {
        GeeTower.Backend.Configuration.GetTestingConfig(
            lndAddress.ToString()
        ) with
            BitcoinRpcUser = "btc"
    }
```

Does that make sense?

**Comment by nojaf** [comment]
I don't think that would match the GR style anymore then. Could you raise it in the GR style repository as well?

**Comment by knocte** [comment]
https://github.com/G-Research/fsharp-formatting-conventions/pull/17
