### ISSUE TITLE
Nested matches format into something invalid

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1400]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBXMAvGADqSnEB2AtgIZbQAWlEEt9DeYA7gJZZMUWYAD5gKudOjABaAHwkyZQS1EBnGfNXMWvftoijykDWAAe%2BkWAD6JgGY0e6XRyOQANOCirsWHhQDmqqhgANqeEKBCEJAAJFgAngAOyGiQflju4SyxAG406LgpoVlCAAweUdkAkhRIFFgAyjwAXsgVlWAALCVgALpZAL7tET2xCcnBafWZlbn5hcFhHWAAjMNRkACyNKYAMn6Iu4gB-DMdKwBMpT39QkNZkRtxSUWQAEawsOhnQnMFRUsOhd1r8GogqDw4OhYBQAIJYACitQA8rZ9hQ2j0IPZ0N4boN1o9fs8JqkPl8ftkYnl-ossWAAMwg7INRI0aCIABCiFssAATogAAo0Pk0KjYRB8ylCLB8wr4u6E0Yk17k77Mv4LNCAyqdZnRVnsrk8-mHWBcSXQGjeGo5WBW3ww6UsWXyyq3Fj3IREqnjVWfdXKmla4rLACs%2Bqgho53N5AoAqolknyrTaKHaHTwnZGcXj3QSHsq-ZM1c7NQD6QA2SOQaPGuOIADC6GtqkbMNUrugWH5zux%2BTzUQ9EC9LB90RVJYDZep8wrywA7DW67HTZtwW9JX2wLnEArPUrZpOydONbPadr6QAOZdsmMmgXt6EUbe7-cjw9PYsniln4PzjoAE5byNWFbCwSV2yoWht1dPd80VQsj2-KBSz-Oc6WWFZynpWs73rU0wQhKFs3pN8EIPJCvxeKdfyDDDLywtZcLrMCIL5IjIS%2BUjljg98wFHEZkJon9AyPf9MPOYFcJqOosGRCgABU%2BXiAB1PgGFfAd4KHAtvSLETUNPeiL1Dc4mRY-DYT5WBcFqAARRB0B4CF2NguUdKEYcBM-YkUKmDJ0NMnUohWPVcO2UwqlsRSGGOBFcUQBoGH5LB1PgU5I06a4KI-Ki-MMgKZwkxjzgjCKdhqWweFMZFkzofkEVMRIBVUVQsxfSMwxy3TEP04TSSgdJioYszKhWasKtMAAlRA4D5eB0sy%2Blsv4wSwHHKBjyG6YgpDEKhBWJcptm%2Bb4AAOVwKhNz5VEqggqggkjFY1t831CqoCRfGcjEADF%2BTYdjFJovaAPGm9cNO-l4E2L7HAOf6%2BUBrca0YEV2XYqxeAyzTXvy97BqK0HJPG4Cpus0V4mRPl9k7JbNKynqvL0scDMJ4bidKyorhrSKKZoKmaZ4TtLuuyU7oep76Re3KfPxid-M%2B9BvoRgG6CBkGTP2%2BkLmY5ZIH5wXaawWHlfhv61awNzUYYdHu0lLGeBxyA8f66j2d2rWwaiC5pP1yKADU505Px4D8fx6e3VbZfWzaxkKjmvZJn2LP9nZfrs7sOpD2pw8jxnXdZgbXkT8TRoOlgLnCtPTHs2AsAAcWwJqWsQNqOvz%2BlusLoT3f9Oiy%2BCnXyv9uGfq5aFoAAa05UVp%2BwVQFIaMUmy%2BK7OrI7Se42tn%2B7Ep4SrGn3Jv187EC4cfuSwC1jmB5JHOqig%2BA62FanXMW%2BSl5ZyN6yi3YKwmaEk5cx9sdfWABpRAiBEjRViscGoy9xTokxN-LeMc3oKwTp7Qe2tlgXAhjXBKEJVAME7ssaOv88r-wJnvEaQ88Fk31k0AImBrL%2BCuscNKiA3ibAQCgjoP9mZ9SLn3Wi%2B9iSHwrhABkOF9awmcv4CgGcKBZxhE0RRdBcACkUrAWSnC6AdS0olbecdtrvGMjg72QgGR6w6AbZWkoKAGJyGaAI78boPz8M-DsRjBxCL-iIgBtDOZH2sX7OxptfDIN2GKN48AaDNlgO1AIZ8L4HF8Z5Fg3lY67zEXQ3BHQGSpzsfZYWNA3iYCIcLBgDR4j1B2BkkxuTUjHHgKiZBDQEiYHyVYlgDJq52KRG0tE6TUZ8nQLYF26D5ZbX8kAyxydrEjzsZ0vkkITZ8MaTHTwvR2hpFUL9dqwQ3wDCAA)

#### Code

```fsharp
let u = ""
match
    match u with
    | null -> ""
    | s -> s
    with
    | "" -> x
    | _ -> failwith ""
```
            

#### Result

```fsharp
let u = ""

match match u with
      | null -> ""
      | s -> s with
| "" -> x
| _ -> failwith ""

```
            
#### Problem description

This is absolutely hilarious, and I am going to change our code here because the pattern is absurd. But it *is* a bug in Fantomas, so I'll raise it; Fantomas shouldn't produce invalid F# even if the input F# was this mad.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/27/2021 07:36:19 - 138146e3e8fc7e8d9d8404ef9956ace3f529c127

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hey Patrick, it was right of you to raise this.
I do feel like the fix for this might be a good old wrap it with parenthesis 😅.
