### ISSUE TITLE
Invalid addition of a space after constructor invocation

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1401]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAdSmA0YAiAhgC6IAqAlgLaIDyAZnQM6JEAUATAAwCMA7NgDZs3YZ2wBmYQBZsFagGUADgQB2rEeLGcAlNoB0AGVjQCAG0Ik5ybOCjMiRcioDmjVGADatiKAh%2BoACREAJ6KyGiQTkSQNv4QkAEAbmYAruGe3nFimf6QAJIqSCpE8uQAXtY5flJVALqZAL6xfr5xCSFh7pHFMVUJyaZp7l5xfiJV8QCyBAAeBk6IBoguRAAWvaMQ3Fx1jc0%2BfUGh6ZAARrCwphttSanpI5vs%2B23yiJTkcKawKgCCRACihXo8xUlU2YDoZmYu38TUyrVyR06EXOl2uiIGQzQD1GkgmUCUBGgiAAQog6LAAE6IAAKBEpBGoJEp6LiREpaRhfjh-gRfnaxy6qKuz3it0G93xMnxkEJxLJFOpRgA7ohKSZmAVEsZiORvqz-OzOaN6rDnnyxR0TsKDYFMZLwQBWUX8uWk8lUxAAVUUYXVBE1Km1Jkc%2BpdECNiC5EB5LUOVqFFxFh3tw3xQhlboVnoAwqYA4wc99GEboEQqbaIJDTNCTXt4fHBSik7b%2Bnc0%2BD%2BJnlPKPdTJm9TmrKxCoVG62aG6MBcioDaXW2JR3NgAOcMEnvuxWIItfFQj6u1uKm7nmxuzs4thfirEZcEATnXss3PzozKLlEoBBHkejYFjBzTki1pXim7bYvi3DZOCz5ElunqvO8nxhvih7jse9a8ueIFoteqYQeC3DjDBbqvsyiEfJcKHgr%2BE6nlONwJs2uFgUuBGbNsT4FEURA0CopCUsEADq5BrAeY5-gBYAWoETFzqBQH4XeHF4iRL6UrAKSFHgiCmFQonDuutEYZOWFAXJ3TRHh4HKaM3DSjB0wzHkdCkKsyz-DWiDyKsVJECJ8BieuUicJJZ7mU2UBRK2N4Ohxzoyk5BR0OQMw0H6xBUv8MyKNSjCMHq%2B7ro6oV0TG4WMZFlkxUpOJxNwGaObMABKiBwJS8ABUFUqlSZ9FmZVF7RdZbG2fVXZNTMrXtfAAByKSUEOlL0HkJCUG467cGFDGIhZlApKYjh6aCABiVJfg4aqkIKI23nV-jcGuMrTVS8CTAdR0LGdlIXcyI4wKs9JEsyAD6yrkIF6zbQNu1VcNrF3ZBj6JbMPyUgywQ0JS8wll16zBb1-gnuVO38sBXTw4pNn3X4XBPk5aMY1jONEPNi1qita0bZB0NxhFF77Yd5DHYg32-VdN0I3FozsMRmyQIzBCY9j5Alu9Qsi2LxB-U%2B0CAwyZZqmDENibzgGDSclM3LV%2BLsE8KMzAAancJJOPATjOHjI4hWb0nYRTPS3dLcTsKp8tOSdWlloVruFB7XsE77MkzpbgdS8uMsOeHsx4LARAAOIsNluWIPlhUJ-iJVJ-7zHJlTo00xA7AJY5H3CwsJJfNAADWJIG93LCMHx8iMjulwLUVqESWV-4VbDF7zun7Ey418uzYgyoi2SRCqss11hDpKUqKJhU-IUA7s5S3Pgmh1f8zhdfW9TtsTfLADSiCIIoLlucsBQj9QEEYJNi3xnlJZO5MIhWwxM-cE7AnqTU8u8RgqwK7gh9mAueZMLKL3rojOByMSIe1MIgNGzgFrLH8ogU4kwEDANGKAvqJMYbYKqrgp%2BDd8SaCfD8PSzgVCRxUNHb4pR%2BHEBSNSUgsBuKUN1NREB08mGz1JpaNhCkOH4M2OIOW05eHMhULqRIixvjOAvktQ%2BTgT7FnEl5O%2BFtEwsTwcHfw4h7atyFkAgwjJTjwAIHmWABUXDr03gsGxR4iaYT5vY2uNVYFaLDtOPAqsCCnBIUg1Wqx5DBGKLMMJ6EImmSifPE4yx4DAgWPIEIJDYmcPBOILO05ARlLoEA-60BKSmDoJAOxxSHGPxgbUrRLd5aVMpB8IgtCkB5MkrYWozRIiMBOgVdwt8GhAA)

#### Code

```fsharp
"", DateTimeOffset(2017,6,1,10,3,14,TimeSpan(1,30,0)).LocalDateTime
```
            

#### Result

```fsharp
"",
DateTimeOffset (2017, 6, 1, 10, 3, 14, TimeSpan (1, 30, 0))
    .LocalDateTime

```
            
#### Problem description

It's not valid to remove the space after the constructor here, because we then dot into the result.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/27/2021 07:36:19 - 138146e3e8fc7e8d9d8404ef9956ace3f529c127

```fsharp
    { config with
                SpaceBeforeUppercaseInvocation = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
I don't think the problem is related to being part of the tuple.
![image](https://user-images.githubusercontent.com/2621499/106264486-02c9f000-6226-11eb-9def-46f18054bce4.png)

**Comment by Smaug123** [comment]
Sorry, I misphrased. The problem is the invalid *insertion* of a space, not the invalid *removal*. The right thing happens with a method call, if I recall correctly; it's the `DateTimeOffset` constructor that is getting the invalid space inserted.
