### ISSUE TITLE
Long line causes offside error

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1402]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXM0wF4AdAOwggEsAzMAIwEMAnMAHwD4wBlRARwDpEAHuQDOWYWAAUE5gGlEATwBqddAFdEzAJRhW7YcXg72E-NokdYAW0Rhym7VgAWiUpRXCbidB7BYG6yAAacCgPLCxyYgBzYVQwAG0QiFAyMkgAEix5AAdkNEhIrCCktPSANxUAtETU1IAGYNq0gEkDFywOcgAvZEamsAAWEogAXRKAXz7k4ahMnLyoQuKmjIq1BZr%2BgEYp2sgAWToBABlIxGOXKKdl-oG6mbHUyZKUvbncuMgaWFh0G9TVpUNjMIAAmXYAriWchwdCwYgAQSwAFEDAB5SinYi9EFgNzeRAPCa7V4A94LL4-P4Q2ZrKoJXEAZhpEEgHGydGgiAAQohKLAGIgAAqMOjWLCIBj-Wp%2BdREp4kmYZLIffLfX7S1nlIFxTZNAYsqDszk8vkC86wADukugdA8rTKsFtEXhmrIssJTUeZGeqVJpRVFPV1KV2vWutxAFZDWyOVzefzBQBVbK5Bi2%2B3ER3O8iuw0e%2BU%2BxUrcmfYNuwHh6q4gBsMeN8bNgoAwug7cJm-DRP5oFgBW6IPiPIWIL6yP6tYGy1SK2H6XragB2etx02JxD7RCWGiSgd49ye2re0fFt5TtUzmmV%2Be4gAcK5NCfNnbhxD3Q8PqWPYDH0xL56gcsrznYF%2BjAABOB8uQRSgJQYTtLEsOg9wLL1iReUMAMpDVgLpUDtgaXFY0fJtEChGFfjzXEPxHH9TzJLCgNDPCIzArYdiIhtEBguDyNhKiwNQo90L9TD5mnHDmJ1as2PBIjWiQYgsDRYgABUGHkAB1chrkNGi0IVDD-3Ei9JJLFiZO2ZlONXBEGFgVQDAAES8choTglD-E-Mhv1-MAJ1mLCllw6SGTYg0iMOARmkoVTnGIZECQ4RwBSwbT4F03E7lovyAuVEzFiU2cLLC7Zo0io5WkocgBDRNM6D7BhkQEbJBWEYRczfQ1I3uAyiyMs8CoKIqQqrUqmi2OsKoEAAlRA4AYeB0sysDsr6k8BoYobgqksaF1SLZl2muaFvgAA5VRt0lDFmglSxYkNLYcvogMhssVR0AidAzgAMQFJDwklVTxNGm82PvIiToFeB9g%2Br7fv%2BhqPJjaBHFFXtJQAfUtcgMscSBns217VUKopQfwibIOmuyGDoeQ0QYU5RGW-HDTW4TDNE4ySeGsndrB-pQUIsCDiOGm6YZpmsAuq6GBuu6HtxJ71roonJzeuHyG%2B7E-oYAG4OBj5ydYwWOJF8X6cZkQsFhz6tYRvWkd3FG0dpjGGGx3HrkJrnBp5nbzNC-ayFBOSRai5R1m5SJ4EiKIWb3dmvxE8cxP9kb%2BYp2pQWs8Ojh%2Bxze066ODDjhO2d6jn%2Bt9rb075wO9txUEIrzgQnNgLAAHFsGa1rEHazry6jSvk851PuaDS9M5NppQXK8PNe1nk4WgABrbk3dX7BhBUjgxUQF9Lq66iDx98e-cnsy3hK4OwSmkWzsQS0l95LBrRcQ3EBc6riB0zqEQMJuWWiswL6SrhtGuxNL4hgbgLWeR0RZyEQNkGKcUXCtD3tYLEOJQGnxVrlNOFIA7XyDk3CGrdErQmEI4Ieq0R4%2BRTn%2BC%2BEkYEkMbmBUEVMRadGiJgOyURLrtE0ogGg%2BwEA4P6GA0e1dz612gcVUhYFGTC36JABE30ojEALsQIu8JOiaIaqoQUqlYAKXaA1Tq748HgNVpA9WPMmKwKzqkRkZtVHqLgsQCxZQLTRCATuBg39Ih-y7FYgkZ8mFyJYQo9h-RGRh1UbbCI2DjhihoPAOgrZYAdWiI-Z%2BZwwnDnwS9ex8jjaWSaIyXOqinIiDoDQTAlCRCOA4PIJSRxCneVGIw-yhDPguHgBibBHAsiYBiXA2ojIW6qNRIMzEBSUYMHQJQAmxS1aBSGo4thEyXHz1USMhgMIbbiM6TlEIIw%2BgFGED9DqcQaLjCAA)

#### Code

```fsharp
let c =
    if bar |> Seq.exists ((|KeyValue|) >> snd >> (=) (Some i)) then false else true
```
            

#### Result

```fsharp
let c =
    if bar
       |> Seq.exists (
           (|KeyValue|)
           >> snd
           >> (=) (Some i)
       ) then
        false
    else
        true
```
            
#### Problem description

For unclear reasons, this is an offside error on the `(|KeyValue|)` line. The problem is that the whole thing is happening inside the `if` check, and the offside rules are somehow weird there. 

I think the *right* answer is to modify F# to allow this. However, if we have to stick around with the existing rules, then I think the following is the best of a bad bunch:

```fsharp
let c =
    if
        bar
        |> Seq.exists
            (
                (|KeyValue|)
                >> snd
                >> (=) (Some i)
            )
    then
        false
    else
        true
```

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/27/2021 07:36:19 - 138146e3e8fc7e8d9d8404ef9956ace3f529c127

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
This is another example of https://github.com/dotnet/fsharp/issues/10852 I  believe.
