### ISSUE TITLE
Long line breaks match

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1403]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzWsYAFAJRgC8AOgHYQQC2AhltABZgBGAdACoBOATwDi2AGqN0AV0TF0sagHM5i5UvlrFAGk5kA7gEssrGnTAAfMFj7Tt%2BsAFoAfGADKsejP0m6F3BIDOiNoA%2Bg7OfvroBkZglJBxkJrgUIFYWPqK-qhgANrJEKCmEJAAJFgCAA7IaJAZWIn5dKUAbhLS2XlFdAAMSV3FAJLUSNRYLvoAXsh9-QAsjRAAuo0AvjMFC1BlldVQdQ1dLW27nf0AjOtFkACyjAAeADIZiA%2BIikYHc92by6ZrjYUrtsqtlIBwCOhPqYjlITpsIAAmS7QlyIej6ODKACCWAAosMAPK4J7UabwvABRA-VaXQHQ4G7MEQqFNEqtWEdckAZmRTRcFUY0EQACFEPg%2BIgAAqMPiMDxYRB8FmmKzSal-WmbUrlEE1cGwSG8mHtNCnLqzXnFfmCkVi2ASh6wXSK6CMQJDZqwV3peTKuiqqldX50f6mOmsnWM-WGrVs46c-pgACslqg1qFovFiAAqhUqnxXe7qJ7vfpfamA%2BqQ5rDgzQdG-ca4YmAGypyDp21ZgDC6Dd-m78n8qugWHtfogfnQgSrEFDdHDxTreuZRrjHNN5IA7O3O5n7YhrmiOIqJxTp4GisG5zWgZH66vY%2ByTblyQAOXcCjN2iWD5RnqcZyDGkAVje8VwNRt1xfM0igATk-G0sVwBU%2BEHegmDPStgI1UDa3AqAGzXZ9m3OXpyQ7L8uwPVF0UxctyUAy9TGvMB5w2fCdgfSDiPjTdEzOC4KM7ZDUNojEDQYxNsKvECwzAriIJjWsSITc4kQooYRiwAlqH4AQAHVDFYADKVnNjb3pAimR4p8%2BNfASeWEqisT4WBJGGAARRB0H0dFUKw6xmLoVj2LARctms-ZeI3BzzgtCjbjuAZcB4Vg3lxC8XFYe0sCM%2BAPlTWZvhw6s8LvRS9lGKDVP484U0S%2B4hlwfQ7gJfNmHtXE7gqCV-H8MtqDPJMStk3D5M43UqvqGKYPJM420au4ACVEDgPh4HywryWK8ywoi7VKtqarZtIrozh3JbVvW%2BAADlJHoE8%2BCJAYFXoLJUzOPbLIjI76EkdB0l80kADF7SYNJFR4LjTrU86Pwo677Xga4AaB54wb4CGAvbNgZUFVDggMAqTO%2B8qrKO6K7Ni2DTDOBCltc2UBAJPgnmHLaTKK0aWLkhcFKm46ZupubEwRcjExue4mcYFm2f0Yd7sexUXrej75rJiaKsF-7AciDHweYVDoZBWG6q6BEhMlmW5fZrBUb14HEEx7HT1x1h8dHRUif0EnIE1-nJsZKmVPs2m6ARDTJaS8RYWFDJ4AyBRObPXbSpvcnfsFkOgVquKLac6P7hBjzR0G%2BPhiTlPuYDjjteDk6RbOooEQSou7k82AsBEPEer6gb5Gr8kRtr8KBajR9Q5p8kEQa6O0f10lhTkaAAGthVlNfsH8XSXDlRA-weobUyY0eDuXQjJ9zsOZ8WyXbsQXQndFLBnTeE3EG8lrqEMQasWGI8ys%2BDq0TKfdOFlM5LmskRJucMW6XUlgAaUQIgCoKU0pvCGHvDwJIySgLMuA-a49QQ53pHncOiIEbt0yuifwrAh6JjTmNMqWsKaCxgVPUW-QEQM0luMFQiBXIKAem8PKiAODXAQHg-oYDmEZ1YVnCetlOHN1MFyCW-RIBYl8goagJdqBl3kOMXRzBJASh4LALSojmCDVMheM%2BxClI1RvomLkVtNHaNQtQGxzQXjqEAU9L%2BGRf5DjsUBORECFFQKOhw6%2B09XFR00Q7dIuCHhyg4PARgvZYADUUA-J%2BzwwnBSWHzOubClHKTiVwroXJC6aM8grRgHBMA0IVqwFwAhRj3CKQ4oOoI3jwCJLglw5RMDOPif0LkbdNH4kGcSQpuM%2BDoFwP7QhP1onsKvmQlxky56aJGXwDE9spE9MIckRYMxaj%2BBBgNbIp8VhAA)

#### Code

```fsharp
let foo () =
    match b.TryGetValue (longlonglonglonglong, b) with
    | true, i -> Some i
    | false, _ -> failwith ""
```
            

#### Result

```fsharp
let foo () =
    match b.TryGetValue (
              longlonglonglonglong,
              b
          ) with
    | true, i -> Some i
    | false, _ -> failwith ""

```
            
#### Problem description

This is very likely related to https://github.com/fsprojects/fantomas/issues/1402.

The long line split has broken an offside rule in the match statement on the long variable name. I think if necessary, the answer if we can't fix F# might be:

```fsharp
let foo () =
    match
        b.TryGetValue
            (
                  longlonglonglonglong,
                  b
            )
        with
    | true, i -> Some i
    | false, _ -> failwith ""
```

i.e. one level of indentation on the bracket.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/27/2021 07:36:19 - 138146e3e8fc7e8d9d8404ef9956ace3f529c127

```fsharp
    { config with
                MaxLineLength = 40
                SpaceBeforeUppercaseInvocation = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Does this really break the code or just produce a warning?
The following code produces a warning for example.

```fsharp
open System
let b ="True"
let foo () =
    match Boolean.TryParse (
            b
          ) with
    | true, i -> Some i
    | false, _ -> failwith ""
foo()
```

**Comment by nojaf** [comment]
Related compiler issue: https://github.com/dotnet/fsharp/issues/10929

**Comment by Smaug123** [comment]
If you have warnings-as-errors for FS0058 turned on, then presumably it breaks the code ;)
