### ISSUE TITLE
`when` clause in try-with block gets split and causes compiler warnings about indentation

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#1406]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAontAC4BOW6AwjgJaIB2JYAvADoMcQR7MAOZWgDcAhiXwBJBrWYAKAGYBHeAzQBncrQYBzAJRhZfWGRJosWkgGYATLrQBBNQE8G0ADwBlcmMo16TAD5WLm5Q3jAABQAlAHkAFRiqGIAZAH0ANQIojwkYgDlUjwBVCIiYqLiCABFWMHTEMjVaWAYwNkgARgA6ABZ2jhDQiBFnVzBgQaGwxBIAQjAhBqaWjyw%2BIxNEeAAhJw8GxbJg1qnTiHInSbOzjTIfajpGEi79skP6xubOE%2Bvf7ipkhICHk4qk8vYALIEQrA0EJQpxKL2OJFCEwqKZKKpADqAAlgal8clkjErn8ztF4okUhksjl8oUSmUKtUyb8AO4yAAWYBQAH5CMRyJRXocojMsGRpDoCGQyMYCAAPaCIPgkL5gEZgRDK1XMdlcxhs8na3VqroQxBqNQibSILoEBjwNTY7kGSkJJJpTH0grFUrlSpVLpxWBeQQ6Ay6fQAWgCAx%2BJtC8hEtBwnJIPPaipz-W%2B5LIEqlYFu9z8T2NAF9IAAacBQNQzdU6NSoMAAbXrEFAU0gABISE4%2BMg0JALLWu9x%2B6IcFgRx3J6EAAx1s6QKRIJgeWgAL2Qq9OPUXYAAupPKwfu8f%2B4Ph22x0wJ72%2BzO523O2cOpehpAISJFckWiIMkjDaJmT6nAAHEux5nqEF6Tj2P4DkO86QAARrAsA4BBoTTiIs7zh%2BpzWN%2BeH7OgtBwDgLT2CQjrwDE8iAQw%2B7HhAKY4I2sHnt%2BSF4Shd6jph2G4VOL4EW%2BaDEVMlhkVOHh8CIKrbIg8jGIgEQiHc6AzA0YmhMKiA8fBfHXoJaEiTh8n4YR77sWAPTyRAkCKcpiCqephbJLA7INNAIyIFIQiwAF6otAZ3BGSZ3AIaE-HibellYdZ5mvkRDkAKzOVAbkqWpGlFOs-mBcFoViF8kUcQR3FTHBsVmc%2BSX3lZkW2VJC5nAAbDlrlKflXmIDQIxqFQLS3FgpDGFVYCcbVQz1RAcXcAlLkWS1KVtRJdnSQ5ADsvV5R5BWFpa6DofpOVzcZdW8Yh5nNcJm02dtHUyUMkGHf1x2DWNNEMDN10xUtjXIY9UCtS96X2WcACcX3ufY8jiGQY3oOgIgzdFt2mfdTWoRtolQ5JGWfiuDl9e5nkaRRVHYRFV01TdC13fFD0E09RNpSTMOnB0X4U0dSMo7T1EMw52Ms7jbP40JEPPdzO2dXzpEUxuTwxAwcRkE4rrgYzXHM6Ei1gMtV6y8lXPPtDu2fnJgvffY8pYE6VSIHQlEo1jFBG9wJtm%2BM7Nyw%2BJBbTbytTB0TkU3%2BioSPIcSGgwRCNh4XLGCQrrwPrDk9DBOMNXjYMc1A47E0r72hB02Ux-%2BUjyLQioxMOdwkAqioCFaywAzlmX51Lhcy8Xwdl4rb0OR0PW14q4pwGQ8BZznZx58DpugwJ4Mh2HPO23zB3T7PxjwHklAXWQTESOI6CtjlHSrwHq1QOto7oLg6p0KxABixgYyQKNxATcu49PyfQpofeeEI35piAt-Mgv8va9WgFybSykUapE5NnLkkB77r0SiXLeQDSZ83htPJ2dwnAxDIIBDQi8sE5RXgXEGRcN74NHtbHeEchjWHJmuWOZCRAUKobQDQJ9zoNAvlfG%2BE8cHMLwcHV%2BOB34wJ-mIf%2BgCx5EKmNYAWa5%2BGCOoSQSBijoFfxUX-S6FMkEoNIA0dBtBMHYMYWvWRa1N5sOQuHSu3BrCq14f%2BdIJNthaHgFobQtCZoMIHkwoeLCR6PkIbzLR9s-GKk-i7UgXwglOlCeE%2Bh-djasxWkHNC7iBKeIctYaOKSqiwBIAAcRmEqTu1ovi5Kyvkv2hTzbD0tqldhFcKk114VAj%2BHkaLQAANbbDuJMmYahNYeBELpP6lAe4OSBk4h%2BxTCZ9I8RwrxEBrBTzXHkRA7JRmqRIH5RgADhxuwbtIcKDB7BOjOmfKRZwNlROcTEuRvTt4DLONYfea4ADSiBVTx0TowKQizdIsTYp8pmMjfmuNYfEjRiSuGgJSUQSiaguRtOXh0iA-tcFouDpDTFu8tEkLXNuHQeAnbaEoE8bEiB0IQgQIi04XyCnSyKRbHZALgGnEsDw04kB7B0G0AwNJrgnnbllT4QsoZ1ZMAquLJFhsUWCp6cKhJNKhiWB0ZK6VKMGAVUWD5HQbyGj3K0DIL4HzeXIs2eSp%2Bm8qX9NFbJXxkqjHqgRckJZ6F4AiBoLAJoOhTnnKAoDN13ytlCs5rssp%2ByHKWGSZKqowiRDoTwHi4RXIPAuBIP%2BBNOr3UuM9fgxgjFmJAS8E4PAIrNHGqqZKhiTEEUzRgGQHA8hHFJo9TefB3q9mArFUMyV4YqKGO5ZW%2Ba-LYr1hPAeMcahP5NDbEDSsQA)

#### Code

```fsharp
module ElectrumClient =

    let private Init (fqdn: string) (port: uint32): Async<StratumClient> =
        let PROTOCOL_VERSION_SUPPORTED = Version "1.4"

        async {
            let! versionSupportedByServer =
                try
                    stratumClient.ServerVersion
                        CLIENT_NAME_SENT_TO_STRATUM_SERVER_WHEN_HELLO
                        PROTOCOL_VERSION_SUPPORTED
                with :? ElectrumServerReturningErrorException as except when
                    except.Message.EndsWith (PROTOCOL_VERSION_SUPPORTED.ToString ()) ->

                    failwith "xxx"

            return stratumClient
        }
```
            

#### Result

```fsharp
module ElectrumClient =

    let private Init (fqdn: string) (port: uint32): Async<StratumClient> =
        let PROTOCOL_VERSION_SUPPORTED = Version "1.4"

        async {
            let! versionSupportedByServer =
                try
                    stratumClient.ServerVersion
                        CLIENT_NAME_SENT_TO_STRATUM_SERVER_WHEN_HELLO
                        PROTOCOL_VERSION_SUPPORTED
                with :? ElectrumServerReturningErrorException as except when
                    except.Message.EndsWith(
                        PROTOCOL_VERSION_SUPPORTED.ToString()
                    ) ->

                    failwith "xxx"

            return stratumClient
        }

```
            
#### Problem description

The EndsWith invocation split causes a warning in the line of `PROTOCOL_VERSION_SUPPORTED.ToString()`.

#### Extra information

- [ ] The formatted result breaks by code.
- [x] The formatted result gives compiler warnings.
- [maybe] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/27/2021 07:36:19 - 138146e3e8fc7e8d9d8404ef9956ace3f529c127

```fsharp
    { config with
                MaxLineLength = 80 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello Andres, thank you for the report.
I would expect the when clause to move to the next line:

```fsharp
with :? ElectrumServerReturningEEEEEEEEErrorException as except when
    except.Message.EndsWith(PROTOCOL_VERSION_SUPPORTED.ToString()) ->
```

Similar to [pattern matches](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbAhgF2gCzAA8wB3AS2zwB0AnKgOxQH4wBRAG0WmxoFd0AyohoA3YQCVE2XjXpl6Ac1bKVKmjVg1WhaIgAO2MrHphMAZzCId%2B7KTyJ6tBhBeu37q7oMA6ALKIzM0wFRG9WengzAHUKPAAKJxN3ZJSIAAVxAHkAFUyAYUyAGQB9ADVWcQEASUyAOWKBAFU0tMzxbNYAEW9s2AEeeQU4gEpE1PGwYbAAWgA%2BRLGJlIAzTDJ2ckowKkhCPZ3IABpwKDMpQ0UzVDAAbROIUHdIABJsAE89ZDRIeWwj%2B5cLxEmHYvC%2BtwBrgADMcUpAqhEHNgBGQAF7IWHJAAskLAAF0AQBfTEPXEvd6fa4-eh-EmA57A0Hgu4pACMdNckF8mEIhXkiEKDgUlH%2BbIATFDcQTXMSAY83OSPuDIAAjWCwdiihUMkFg64s5JijmAoToMhwdjGACC2HC8Eyyz59AxuIgq3YZylRLp8s5ryVVLVGq1fsZerQBvcAGZjRBIAI9JhdAAhRDLTSINKYGiYdBSYQhtw8MFemU%2Bsn%2BynfIOa41A3XM11gLGxqAJpOIVPpmgC2AkYTQcyIBEiWCDwzGQuuYuIUsuWWuX30inKmtTqA6pn6psAVlb8cTKbTGcaek%2BNEHZxHY5wRno67dIM97ml8-LT0rq-VtYrYcbKQANn3dsj27RA8nYcwzDyYwzGLbhNAfMB3WfNxXwgBcXCXONP0Db913rLcIybAB2YDD07Y8e38dAVQLVsUNnF9vTlCsVzw4M603cMIRSAAOciOy7DMYMte8GKfJi0JYxc2IDat8K4v9txSABOQTdCtZZsGEGD0CwJCZznDD321diFM438GxU5JWRhJsDyEqjEFNc0NUnCSPSk1x0LATDSQ-cyoDXJTrOItl2QckDEC0nSaFci0PKbIzmLLVjAvk4LFKsojeNso0HIRJAaUyehshoN4YhFTzUJ8mSsLkqssssj9lPC2yYyiiirQ0XgIk6RB2DIM04sMvhvJcXz-LAbCNyC6laRynjIzcVkWwc7lCCqZZsnsegODOAQ8E0bAYngaqmyxSVUrfdKzMyhaCO4-9bL3DaeQRZYyEITJzxwTRtD0HtAjvJCd2u6S0tkjKmse0LcpW1xWSA97CEkOAaHgM6LpSK7jL80y-Xm34nravL3FZMjUfRzR4Fqfg6JoB0qh09ArlbVl8em2bFVh9BeHYQwhudAAxTQsGwOLsgDeHlqbVkBIcmnMd8AWhf5MWaAl0b93wbMkzi4pyHOvBIC5wnlweknZZein1NRnqczeTIaD5ODsdN1s8Zuky7qJq2aVJsLybcCV902x3MGd12yDg%2BnaOEZnWfZ%2BXzb9y2%2BbV9YNfFnApZlpbbdDyK4Uj6O3ewVXBez0Xc8l%2BiHL1nNuGEI2yBNs2fYJ9OcOJwObZs9wxQKuFNtKBtk3keBBg9pDvch27ofu2HrcLwfQ860eeRFvruDvSeIhn9ucexCG6qhhqYeVVfWuDxGXDFdat8ITpYGwABxKRAeBsw71n1twZpyXv7WGIU17tSHm9UeWdhadktNAAA1smZuCCpBmFKgIXM4ENT8HEk2RiQDL7Ly-C1bUZN74QDFCjOEtREAkFgambA-YHDS0%2BANL6cgJz0CtBEGijMU4rEkoQgKxCOI-lvgjJsYoqZwgANKIH0NtXaDgESYLzE6F0givLCJmo1a%2B-dwEh1cGKRWz8OBmjMHgf%2Bl0z6TXqiIkBJDxFkLvlI%2B2cIUSKE4D1BQ-AkRREQCqXwCBNHJAIV3bmeixFB0kSkKM9lS5DQUPQHe9A97GBRMknAMhEC9CKkiW8SUtG1TsRfBxGcnExLlnEkuyRIBWkFsIegt4xCFGMAoPhwh2HyAoHeARYShERItr3B6YCJHVOSFGEedSq6GA0YUXMKp4CYAgrAX%2BihaH0P5EhcJC9fbAIqdEgeEC3BRk3nUzosdMAqk4OY2OeABBvBpDyHZgy9ndwOSM2GDh7SOn5P0N4nAqlF1cFGJ%2BdS7QOg0UhGANB2DLE7u8yJV8jmGIoWAKMUC6n9BoOaSuITXnaIiScPEmIfhmBFr-a4BDCRAA).

**Comment by knocte** [comment]
> I would expect the when clause to move to the next line:

Hey @nojaf, but look at current results, it's already on the next line. Do you mean that it should not be split? But then it doesn't respect MaxLineLength.

**Comment by nojaf** [comment]
Hmm, you are right, I jumped the gun here. I was just thinking that what we solved for pattern matches did not yet apply to try/with.
Does the error go away when you do
```fsharp
                    except.Message.EndsWith(
                                             PROTOCOL_VERSION_SUPPORTED.ToString()
                    )
```
`PROTOCOL_VERSION_SUPPORTED` is further indented than `EndsWith(`.

**Comment by knocte** [comment]
> Does the error go away when you do

Hey @nojaf, sorry I didn't have time to test if your snippet gives warnings, but even if it didn't gave them, I don't think that would be a proper fix. I mean, because if that's the proper fix, what would have been the point of splitting the line anyway? If by splitting the line it doesn't avoid possibly hitting the MaxLineLength, then fantomas shouldn't split the line for the sake of splitting, right? Not to mention that this proposed snippet would violated the "avoid vanity indentation" principle, AFAIU.

Please let us know your thoughts, I think this is the last blocker bug for us to finally adopt fantomas

**Comment by nojaf** [comment]
Hey @knocte, I was actually more curious if this could be yet another case related to https://github.com/dotnet/fsharp/issues/10929.

>  I think this is the last blocker bug for us to finally adopt fantomas

[.fantomasignore](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore) to the rescue 😅.
