### ISSUE TITLE
Incorrectly combines tokens when formatting

### ISSUE THREAD

**Issue by josh-degraw** [fsprojects/fantomas#1407]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBLAdugYmABQC8A-JQJRgAeY5Z5AhHfQDoBOnh2YAIak65HnwgRMObogDOAV3Q5mAeQDWYYAB8wAJXlKscpmADaAXTDaAvuPySyBxcoB0sdQDVB6BSVkuWDSuzkZyrmYADFbaAHz6hm64chr2jlSUYFjcfvaQADTgUHLYWAQA5nKo5kUQoI4QkAAkWACeAA7IaJAEWAW1ks0Abj5%2B1WYDjpGFDYMAkvhI%2BFgAyrgAXsgzs2AALJNgFgM223UHzW2d1T3L-bPDo101O2AAjKcNkACygvQAMsQ-oh8OUsAALO47V4AJkiByOjhOA3qnxaHSekAARrBYOhIY4Hr4nhMXtCPgSVogALa4ODoWD4ACCWAAootVAAzAH4LYHCAcnwleHHD4ogloq7dbG4-GDJojInjPlgADM5MGK3agmgiAAQogObBZAAFQTcQRU7CIbiyxzZPzCxGi84SjHSvHqwljNAkna7dWNTXavUGo2IP6wADu1ugghKCyGsFjZQZtskAvQQtmCMkSMcYrllzdOI9LoV3ueOwArAGoEGdfrDbIAKrtTrcWPx-CJ5O4VO1jNZho5iB5yQFxqu67utNe4nKgBstcg9ZDTcQAGF0HG5BuGXJ7dAsEa0-zBYhHbnnfcp1KS7P5Y8lS8AOzL1eNsNfamY62nsCDhe2YisiLpFtO96eo%2Bio%2BsqAAc75ag2oayHu9L4P%2B9pAcOIH5mB6IQTKUHlvOLwAJyIcGjIclg1p7lSVKCJhOTYY4I5gGOZw3uBd5EWWT6wS8rzTMqK5IWuYaUjSdL9sqgGXqO16ojxUAzsRAmVrMrzvKJq7UbR3BSbSuKyS8WEKRxSniipWKQfxMGaQ0MLLgsSxYKo%2BAACrcK0ADquDgv%2B8nAU6oHcQRvGljeJHPlCaq6eJjLcLACiLAAIogRA0gZzEOiFV5hcpEVQL0D4xYJUL%2BqJPz0HMHKeWCwIspmiArGCRpYP58CBbW0JVhZnFaPhkolbc6kOb6Wk1tVvwLByuD0Ko7aCMe3AsvQ7QBHIfYYbWVZwvlimFdZxU3H040VpNTlLjN9AGHA3DwF1PXKrsB04aFeHhSNZ1lRpV2OK8b63fdRrwAAcgoVK-twnJzLRVJVLWrwDVZhanVSRi4EQPIAGJGoxWAGZ5BEXaRUIIaJoOPV8WM44g%2BPcITOXLtAYJmtqBkAPqRrg3UQqjx3oz9pVk7FWkUbdSXmq0qjcACB7PRCtZvYLX1FSLY32ZdyqwsuNXS4Isvy8kWCQ9D1pwwjSPKijh2WULk42ZjyjY8QjPM9aJNXGLFWzNCOkvJAhvGwrWC0679MeytLOiWzHNHtaPN84FavjsNGKi9r5P%2B2St3eESuoEPAFRK-%2Bqv24NE5QLeo3ndn4sNNC8VBzVuOpUeO1F4spcp8rr3vWxuHp99mda9F-261Vre-GlsBYAA4tg62bfI20MmXe2D5I7FVxnhFRai5WOY4fX63TxC6vS0DqLq5o39gKT4CsFqbriUO7cq5mV2jTunWpDc-ZNxukHcGiBIz031FgaMwJvaIAyvNfAAUdqMkWN%2BC23AbYvGCh9Aq6sTo-QARPCautgZBwANKIEQO0OqDVgQLBfpabkvIzIsTTlxDWY967EJ1qSSmM96DNRpHIMEm8B7sKGqPA%2Bf0SGkklkHNYIJMBJXKFDYEnVECYi%2BAgFhOwcFD0%2BiPTh0jfYn0kCqESQdGREHKPgdu%2BBO4MjWLYlaChZCeVgK5dRK0dq5VYjvYeHCCHFj4jwnODQVSBx2MHZQ1p8A%2BKGOGBk5R0EwwQQQZB%2B4-ESOrhcf%2BdkwmN0cCqPOrcsbML%2BBaTE8BBBblgNtEEYCIHEGyT-R2NcbJEKPpPF4KoW7RLSskQQmJMBCOSGCFYrRli-CCueHJ%2B9ujAngJyZhKw2iYBkbwnYKpp7RLZMsrkLTWbcHQBySA8ypGRU2eE4p00FHZFpOHHRsyWoDSKBYbYPQ5C422tUeSNggA)

#### Code

```fsharp
let inline (=??) x = (=!) x
let mySampleMethod() =
    let result = Ok {| Results = [] |}
    (Result.okValue result).Results.[0] |> Result.isOk =?? true

```
            

#### Result

```fsharp
let inline (=??) x = (=!) x

let mySampleMethod () =
    let result = Ok {| Results = [] |}

    (Result.okValueresult).Results.[0] |> Result.isOk
    =?? true

```
            
#### Problem description

Fantomas sometimes formats incorrectly resulting in invalid code when encountering custom operators, in a manner that I can't quite predict. It seems to merge some tokens when formatting. Notice the `(Result.okValueresult)` in the formatted output.

#### Extra information

- [x] The formatted result breaks by code.
- [x] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/27/2021 07:36:19 - 138146e3e8fc7e8d9d8404ef9956ace3f529c127

```fsharp
    { config with
                SpaceBeforeLowercaseInvocation = false
                SpaceBeforeColon = true
                MaxIfThenElseShortWidth = 25
                MultilineBlockBracketsOnSameColumn = true
                KeepIfThenInSameLine = true
                AlignFunctionSignatureToIndentation = true
                AlternativeLongMemberDefinitions = true
                MultiLineLambdaClosingNewline = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by josh-degraw** [comment]
Looks like it may not just be related to custom operators. It just seems to combine tokens sometimes for some reason. I get the same issue with the following:
Input: 
```fs
let choose chooser source =
    source
    |> Set.fold
        (fun set item ->
            chooser item
            |> Option.map (fun mappedItem -> Set.add mappedItem set)
            |> Option.defaultValue set)
        Set.empty
```

Formatted;
```fs
let choose chooser source =
    source
    |> Set.fold
        (fun setitem ->
            chooser item
            |> Option.map(fun mappedItem -> Set.add mappedItem set)
            |> Option.defaultValue set
        )
        Set.empty
```

Note `fun set item` turns into `fun setitem`

**Comment by nojaf** [comment]
Thank you for reporting this issue, my first guess is that this is a bug related to `ASTContext`.
Please be aware that using phrasing like `blown up` and `freak out` were not perceived as very welcoming language.
See [Code of Conduct](https://github.com/fsprojects/fantomas/blob/master/CODE_OF_CONDUCT.md#our-standards).

**Comment by josh-degraw** [comment]
> Please be aware that using phrasing like `blown up` and `freak out` were not perceived as very welcoming language.

Apologies for my poor choice of words earlier. I realize that not only was it not in the best tone, it was also not descriptive of the actual problem. I appreciate any help getting this bug fixed!

**Comment by nojaf** [comment]
Hello Josh, thanks for the apology, water under the bridge.

As for the original bug, I believe this is solved by my changes in https://github.com/fsprojects/fantomas/pull/1415
So all that remains there is to add a regression test in [DotIndexedGetTests](https://github.com/fsprojects/fantomas/blob/752f2e222c152fc64203b9b5ed308ebcf53f0d5b/src/Fantomas.Tests/DotIndexedGetTests.fs).  [See sample](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#pull-request-ground-rules).

The second sample you posted is an unrelated bug I think, I created https://github.com/fsprojects/fantomas/issues/1427 for that.
