### ISSUE TITLE
[Feature request] Option for formatting multi-line lambda without new line when it is the last argument 

### ISSUE THREAD

**Issue by hvester** [fsprojects/fantomas#1413]
I propose we add a format option to start formatting of multi-line lambda argument from the same line as the HOF taking it as an argument. The option would enable formatting code in the same way as was the default until Fantomas 4.2 for a well specified set of cases. I am not suggesting to revert the [PR #1202](https://github.com/fsprojects/fantomas/pull/1202) that changed this behavior, but to introduce an option to format certain subset of the cases affected by the PR in the old way.  

I suggest that (when the option is enabled) multi-line lambda argument is formatted without new line if it is the last applied argument of HOF (and max line length is not exceeded).

## Pros and Cons 

The advantages of making this adjustment to Fantomas are:
1. Support currently dominant way of formatting F# code
2. Support formatting conventions that appear in [G-Research F# code formatting guidelines](https://github.com/G-Research/fsharp-formatting-conventions#formatting-function-parameter-application), though it is not clearly said when this style is recommended nor if it is in some cases the only recommended way.

The disadvantages of making this adjustment to Fantomas are:
1. As far as I understand this would be a special case compared to how other long arguments are formatted,
2. Supporting more options incurs maintenance burden in the future and may interfere unfavorably with future features. 

## Examples

Example [from](https://github.com/dotnet/docs/pull/21978#issuecomment-749849436):
```fsharp
let names =
    people
    |> List.filter (fun person -> person.Age >= 18)
    |> List.map (fun person ->
        let petNames =
            pets
            |> List.choose (fun pet ->
                if pet.IsAlive then Some pet.Name else None)
        $"{person.Name} has pets: {pets}")
```
which is currently formatted as
```fsharp
let names =
    people
    |> List.filter (fun person -> person.Age >= 18)
    |> List.map
        (fun person ->
            let petNames =
                pets
                |> List.choose
                    (fun pet ->
                        if pet.IsAlive then
                            Some pet.Name
                        else
                            None)

            $"{person.Name} has pets: {pets}")
```
## Extra information

Estimated cost (XS, S, M, L, XL, XXL): I rather not guess anything about the cost.

Related suggestions and discussion:
- https://github.com/fsprojects/fantomas/issues/1221
- https://github.com/dotnet/docs/issues/21927
- https://github.com/dotnet/docs/pull/21978

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to Fantomas
* [x] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting)
* [x] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) ([link to section](https://github.com/G-Research/fsharp-formatting-conventions#formatting-function-parameter-application))

**Comment by hvester** [comment]
Regarding [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) I asked for clarification for this [here](https://github.com/dotnet/docs/issues/21927#issuecomment-770195255)

**Comment by nojaf** [comment]
Hello @hvester, thank you for this suggestion.
Are you looking for [fsharp_multi_line_lambda_closing_newline](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_multi_line_lambda_closing_newline) perhaps?

**Comment by hvester** [comment]
I didn't realize that fsharp_multi_line_lambda_closing_newline **also** removes the new line before the lambda. In my opinion it would be better if these two things, whether to have new line before the lambda and whether closing parenthesis is on new line, could be configured separately.

Another more minor thing that i had in mind is the formatting of following code:
```fsharp
let result =
    retry 5 (fun () ->
        failwith "Boom"
        42
    )
```
I would have suggested to format it like that instead of the following
```fsharp
let result =
    retry
        5
        (fun () ->
            failwith "Boom"
            42
        )
```

**Comment by nojaf** [comment]
What is **fsharp_multi_line_lambda_closing_newline** implements is according to the GR style guide.
Example from [guide](https://github.com/G-Research/fsharp-formatting-conventions#formatting-function-parameter-application):
```fsharp
// OK if lambda body is long enough to require splitting lines
let printListWithOffset a list1 =
    List.iter
        (fun elem ->
            printfn "%d" (a + elem)
        )
        list1
```

The thing you want here falls under the section ["What are we not looking for?"](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for)
I have no interest in having any deviations of a style guide.

As for the Microsoft guide, I'll see it pass by once it is in the guide itself.
