### ISSUE TITLE
editorconfig setting to disable fantomas as alternative to .fantomasignore

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1419]
I propose we add a setting to `.editorconfig` to disable fantomas, as an alternative to using `.fantomasignore`.

The existing way of Fantomas deals with this problem is to use a `.fantomasignore` file.

## Pros and Cons 

The advantage of making this adjustment to Fantomas is that `.editorconfig` is already used for configuration and already has the capabilities of targeting arbitrary files.

I cannot see any significant disadvantages.

Example:

```editorconfig
[MyFile.fs]
fsharp_disable_fantomas=true
```

Estimated cost (XS, S, M, L, XL, XXL): ?

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [ ] This is not a breaking change to Fantomas
* [ ] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by Tener** [comment]
How would the setting work for directories?

**Comment by cmeeren** [comment]
According to the sample on the [editorconfig website](https://editorconfig.org/), I would guess something like

```editorconfig
[folder/**.fs]
fsharp_disable_fantomas=true
```

**Comment by nojaf** [comment]
Hmm, I'm not sure about this one.
"Not formatting "is not really part of the FormatConfig and you create coupling between two concepts.
I'll leave this open for now until I had some more thoughts on this.

Please note that this would be a breaking change, if we were to do this I have no interest in maintaining two ways of ignoring files from formatting.

**Comment by cmeeren** [comment]
I understand. This is not a big issue for me. It just occurred to me and I figured I'd suggest it.

**Comment by nojaf** [comment]
I'm still on the fence with this one, it has some practical benefits but I'm very sceptical that outways implementing the change.
