### ISSUE TITLE
Surround return type annotations with white space [F# style guide] 

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1420]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMiAeADogHYDOAlgG6IAqsAwrALYECuWiYa5xOAvGAAMAHQBOw4phxMAngDFWxMAAoAhmiTRyTVegCUYAEZhoXMJu26wA1WADUR%2BycgAacFFLYsPAOalUYADa7hCgEOFQACRYMkQBkDxYriHhkJGUuqzIaMEREYJueakAksRIvADK5ABeyIVFYAAsKRAAuikAvvWhLVExcWgJvMlFaRnoWQG5DQCM3XmQALKqeAAyPIirJD5YABYjswBMgr3tEV0pYQvRsdlQhrCw6AcRY5l300WH868ViEzkODoWDEACCWAAomUAPIAM3WxDqvQgsN0nlOnXmV1eNwG90ezx%2BUXGkxyyLAAGYiRBIBUCKpoIgAEKIWGwUSIAAKqlEqiY2EQoheeSwoiyGPOWN6aX6d0gDyewpp6XeU3JjWpUDpDOZrPZm1gAHdBdBVJ5SpRYKbvCCleFReKimdwhcItjUri5QrCdKVRMPuSAKya2n0xkstkcgCqBCIolN5uIlut5FtmtR6HRTsxl19svi3rtb39aoaYAAbCHteG9Rz6OgzaRGGQHdAsOy7Si0YgJS6paNPQWCUW-aSguSAOxVsO6yOIRb-QyCztgDNZvLOiCu8Lu5X5waFonFsefPIADmnOoj%2BsYwOIK7XPezktzA-3%2BMVR9HAbLAE5L4yoKwhwoiMEwOgrg6T4bjmbp5rcQ6fr6JI-rMBTkqGV61ogfwAkCabko%2BvZbv21zvvKw5fihpazHMGHVogQEgbhgJPARZZQcRYDbj0b4IQelHIaqZJljM3wYaU5RYNCxA0KIMgAOrkHsD7dlxPFgLufT8R%2BPoDtRImzFS9EzqCoiwIo8AACKIOg2jKcumqcc%2BfavmROlDEkVHCeOokahhyx4MUsI0LsJAQpmOG7OyWBKfAKmao0JwuSRbk4uRiQjgZvmzMGAUrKUsLkHg0Jxqo7aiBChAcqQFDsQ0gbJTBL5wXxeKeVlPmnhEMyVvleAAEqIHAojwHFCXqk1ESbtxpHpR5mXeSWhlFDMU79UNI3wAAcqwTBLqIcLFBwTD%2BJqMzqXNHrkUwrDoN4dmInI7I6FgIE0AhS0nuSMwXhhm3svAix3Q9GzPaIr0gSuMC7DyDIgQA%2Boa5Dxfsl1pddC3DF9qGrf%2B-VmbyMjQqI6ykLFKMTWWSXo617ntYtQnLTlXzoWWSwrITqjE6T5Dk7t%2B2CkdJ1nT9tM7vB7W3fd5CPYg4OQ4KH1xDjNFfHR7NczzZNYMDMtywr5VQyG0Cw7ybaCkjlNoyls0Y3uWNeUz31loc4ns4FABq7xMjw8C%2BON%2ByJVN4QzRpWkyo7nXM914SHMZHsrAoxBtqmxC%2B2UAfWyuNO2%2BHktyoz%2BldeShz%2BYneBWbAWAAOLYFVBA1XVxCByujXi7x9NeoJxcx6XeUeyDssbEywLQAA1ky5vj9gpAyRUfKILee33umal51dDvtYezu43khx9ez22IIacsslgxokMriA2UVxDKWnoJlAuguiKLZZERv9vadvPfXNlscICHHWuzAA0ogRABBgqhRIKUBe-IERIg-uvZqrk6bzQZtjXeat95-QrhFAEpBdit2Dh3TSBdEJ6X-iXV2%2BN2ZVGID4TAZkfB7RILFRAhhFgICQQ0T%2BqDUroMxr-JCvcXYNApGzBokBQR2R8MQZOqcQRVHkeVVgHI6CSXYeVNOqlIpkIjoOASojqF9zLBSDW0jZEgWIDo6gqwQQ%2BBfgdW%2BPAH4gnfnwlB01YISzat3ExOIAHkgpO7aRetvCINWHyQw8BVD1lgBQRhx9T4bD0euHxLU-Fd0odHcRRQKQJ2kVZPmqhDCYAIXzXYFQZC8BWOk6CmS0HZIwXKEg8A4SIIqDETAeS94RApOXaRUIOnwjSSbUQ6BYSQAMRQ4xVCgk0IkQPaR3TRCAl1jwhp6l3CtHqAkUgcgKABCIh0IAA)

#### Code

```fsharp
let expensiveToCompute : int = 0
let myFun (a: decimal) b c : decimal = a + b + c
```
            

#### Result

```fsharp
let expensiveToCompute: int = 0
let myFun (a: decimal) b c: decimal = a + b + c

```
            
#### Problem description

[F# style guide:](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#surround-return-type-annotations-with-white-space)

> In a let-bound function or value type annotation (return type in the case of a function), use white space before and after the : symbol:
> 
> ```f#
> // OK
> let expensiveToCompute : int = 0 // Type annotation for let-bound value
> let myFun (a: decimal) b c : decimal = a + b + c // Type annotation for the return type of a function
> // Bad
> let expensiveToComputeBad1:int = 1
> let expensiveToComputeBad2 :int = 2
> let myFunBad (a: decimal) b c:decimal = a + b + c 
> ```

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/29/2021 10:31:35 - c1a4fe61fc4089eada7b38ef8f872ab28f8b914c

Default Fantomas configuration

**Comment by nojaf** [comment]
Please try and set `fsharp_space_before_colon` to true.

**Comment by cmeeren** [comment]
No dice, that produces this:

```f#
let expensiveToCompute : int = 0
let myFun (a : decimal) b c : decimal = a + b + c
```

Note `a : decimal`. This is also a violation of the F# style guide, which says `(a: decimal)`.

**Comment by nojaf** [comment]
I see, thanks for clarifying this.

**Comment by knocte** [comment]
@nojaf This will basically change all the type declarations of all code, will `fsharp_space_before_colon=false` override this new behaviour?

**Comment by nojaf** [comment]
No it won't. Both style guides dictate that the return type colon needs a space before it so it outside the control of a setting.

**Comment by knocte** [comment]
Mmm I see, then the setting should probably be renamed to `fsharp_always_space_before_colon` 🤔
