### ISSUE TITLE
Don't insert space before ( after DU case constructor

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1421]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBZAngFUwB0QDot1EAXACwQAoAdSAQ3oBowBGASloCdaA7APIBrMHUYt2XXnwDKsALaJR9JpFace-AKLdusbsvFrJmvlgAiAVwDCDAM5LDq9RzXgoDsmQCWfAOZ2qGAA2u4QoBCRUAAkZPjIaJC%2BZG5REJDRAG4MADaWCSFhaQAMzEVRkACSfEh8ZDLeAF7IZWmRACzlYAC6RQC%2BrZERaRlxBEFJdakjWbn5QaFtEGyDbZDoDAAeADK%2BiNuI-pTTbWwATMVdvVEDRcMVsfETAEawsDknkRnZeQWLS2dViMZIh5N44DlYHwAIJkLQ1AQAM12fBaXQgiNyDiu-SB9y%2Bj3GiVe70%2B6VmvwW6LAAGYgRUZHgGNBEAAhRCI-SIAAKDG4DEUZEQ3DJkTI3HyOJueK6oyexLeH3pMR%2B8zQ-za7WV6UZzLZHK521gAHdhdB7IhqplYOafFDRRBxZK2tdIrcovjyWMCpASUrZRS1YUlmAAKzaqC6lnszncRAAVTwBG45ocVptDDtfAdYExOWxLtxdwD3peitF3zmf2pADYI5Ao-rY4hrDl7HZrFC7E7oGR9Dm8wW0q6IO6hiX5VA-RXA9WQwB2euNmNc0jyZ7CgdYxBSt0ytaEn3T5WVynq6kADiXTOjBrjnch2Yjg53helxYPpYVpJPs6pIYATmvPVoURIVuE7eR5AYHMnVfYciw9CciSnctf1VOcljYUpqQbG8my5EEwQhe1n23XdR33GYv1Qn8Aww-8sJWXDG1A8CiPBd5SOpOCKLAMdwmQo80PoqtGNOQFcOqWoyAEPhsG4TAAHVvGOMj83gqIR34qiHho30RIPBjzxDNg6RY-DoT0SwanMRAcm8MFwNgiVNMibSBLAT0Yn05IZ2M4MsK1XCNk2SpEWwChDi0DSZCobgyBU%2BA1OpdpLjfPcP2oydJhSdCxJMrDwxCrZqkRbxNgEZNM30LRNjwOM7DsbxuJDUN0oQ98kM-HK-Pys9AtOOsSs2AAlRA4G4eAkpSkM0r4zzvLlFDcv8grBrSNhFxG8bJvgAA5Sx12FJFKiFeRAgjNgFt0gl9PkSwch8BzUQAMX0aCvGFXBxn6oMNU2q9cN2-R4HQR7nr2d7uE%2B5z62gCg%2BWZcCAH1jW8ZKKEgG6sr03qpj%2BzDTiAkarP5TABG4XZuxmrGI3mjLKNxu78by0SBoBqILnrUKyYYCmqe8btDuO7hTvOy7qWuxmdOZr0coep7vBexBodh76nkJ8S0jOZiQ0gPmBepshwaVlW1czOHcIRpHe2FNGMeOHHuuyla%2BvZ-7qTOST9dCgA1KtWV8eBfD8WmcwZzrMpdvG3YJj2iZ18zfa2V6bN7Fq%2BCDmpQ-D%2BmOq0xDxx6uO2aM9bOciM5gpTzZzFgMgAHFyDqhrECazO8%2BpdrneL13hLo8uOa94rfYh5W9lZSFoCEVl%2BRn8g7DkmQBRbd4jqfakX17wSS4H-0h89kMzmG-X9sQY0VfZMhTUOH7EDs8q%2BFUzPoRqNcN24SWQ23mXFqEssg8ZgBUrhAM4219YAGlECIDwOFSKhxqgr0UCiNEP9yJ-1uvLUua1h7HyBrXGKYI7AUC7nNAu7ki6737oAg%2BwCK5exJvrBo-gciICsn4I6hxEqIGeOgBAaCli-yjkzGOLMVrHgTtrKINIcL62hA5PwfA058AzlCBoSjMyWDjNgWA0luGZkzluDSO8vIAO-HQh4IDqQ0j1ksA2T1hR8EMZkfYUI-Af2FI-XwL8uzGKHIXLqfdY771wUfJYNIfb2NNj4VB2wBTPHgAwVssBmr%2BHPpfPY-i3IQA8lgnyOVJGH0TjI5O9jzBCwYM8NhRChYUBkJgOoWxsmmKWoeCYhx4BIlQTIOIbCwklMiDSGu9j4RdORFk%2BG3AciImxpguWBSJGGXoXgiJo97G9O4OCE2AiWl-3cN0QYSQ7CvWakEbefQgA)

#### Code

```fsharp
MyType.MyMethod("a", 1)
Ok ("a", 1)
Some ("a", 1)
Error ("a", 1)
MyDuCase  ("a", 1)
```
            

#### Result

```fsharp
MyType.MyMethod("a", 1)
Ok("a", 1)
Some("a", 1)
Error("a", 1)
MyDuCase("a", 1)
```
            
#### Problem description

The F# style guide does not mention anything about the spacing between DU case constructors (`Some` `Ok`, etc.) and a parenthesis (it may mention it implicitly in a sample; I haven't read through all samples to look for this). But based on F# code I have seen in the wild, it seems uncontroversial to say that the standard formatting for DU constructors is `Some ()`, not `Some()` (let me know if you disagree).

I expect the trouble comes from the `fsharp_space_before_uppercase_invocation` setting. I expect Fantomas does not know anything about whether the invocation is a DU case or a method. For methods, it is correct that it should by default be a space: `MyType.MyMethod("a", 1)`.

One possible way to differentiate these two cases a bit better, is to use the presence/absence of `.` before the invocation. Typically, member invocations will have `MyType.` before the invocation.

I know that `open type` on static types and `[<RequireQualifiedAccess>]` on DUs are both exceptions here, but I still think the result with the aforementioned heuristic would be better than without. It would cover many common cases.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/29/2021 10:31:35 - c1a4fe61fc4089eada7b38ef8f872ab28f8b914c

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello, Fantomas cannot make the distinction between DU case or any other function call.
Please consider the follow code:
```fsharp
type Foo() =
    class
    end

let Foo2 () = ()

type Foo3 =
    | Foo of unit

Foo()
Foo2()
Foo3()
```

The relevant matching AST:
```fsharp
          DoExpr
             (DebugPointAtBinding tmp.fsx (10,0--10,5) IsSynthetic=false,
              App
                (Atomic, false, Ident Foo,
                 Const (Unit, tmp.fsx (10,3--10,5) IsSynthetic=false),
                 tmp.fsx (10,0--10,5) IsSynthetic=false),
              tmp.fsx (10,0--10,5) IsSynthetic=false);
           DoExpr
             (DebugPointAtBinding tmp.fsx (11,0--11,6) IsSynthetic=false,
              App
                (Atomic, false, Ident Foo2,
                 Const (Unit, tmp.fsx (11,4--11,6) IsSynthetic=false),
                 tmp.fsx (11,0--11,6) IsSynthetic=false),
              tmp.fsx (11,0--11,6) IsSynthetic=false);
           DoExpr
             (DebugPointAtBinding tmp.fsx (12,0--12,6) IsSynthetic=false,
              App
                (Atomic, false, Ident Foo3,
                 Const (Unit, tmp.fsx (12,4--12,6) IsSynthetic=false),
                 tmp.fsx (12,0--12,6) IsSynthetic=false),
              tmp.fsx (12,0--12,6) IsSynthetic=false)
```

so in short, Fantomas has no idea.

**Comment by cmeeren** [comment]
Yes, I said as much:

> I expect Fantomas does not know anything about whether the invocation is a DU case or a method. For methods, it is correct that it should by default be a space: `MyType.MyMethod("a", 1)`.

I also suggested a kind of workaround, which would get many (but not all) cases right. You didn't comment on that; did you read it? Quoting it here:

> One possible way to differentiate these two cases a bit better, is to use the presence/absence of `.` before the invocation. Typically, member invocations will have `MyType.` before the invocation.
> 
> I know that `open type` on static types and `[<RequireQualifiedAccess>]` on DUs are both exceptions here, but I still think the result with the aforementioned heuristic would be better than without. It would cover many common cases.

Seeing your code, I could add constructors to the list of exceptions.

This is just for clarity. I totally understand if you do not want to use this "dot heuristic".

**Comment by nojaf** [comment]
You know my policy on these things, either it is listed in a style guide or it has no place here.
What is seems like clarity to you will feel inconsistent with the next person.

**Comment by cmeeren** [comment]
https://github.com/dotnet/docs/issues/22664

**Comment by cmeeren** [comment]
The issue was clarified as "do add a space", and a PR is now created: https://github.com/dotnet/docs/pull/23094

**Comment by cmeeren** [comment]
The PR is now merged. I know Fantomas still can't discern between the cases in a robust manner, but the issue should probably be re-opened. :)

**Comment by cmeeren** [comment]
Can this issue be re-opened, to track the discrepancy with the official style guide? Would you perhaps prefer a new issue?
