### ISSUE TITLE
Violation of "avoid name-sensitive alignments" clause

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1422]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAnbuAngMoCO6APAOQCGAfGALwA6uzAdhAAqzoCW0Qqw4QIAOgASNdvEwAVXNIDOfROyxl0AUVy5YuABQBKYZ1FiA6jT5YAgjIBKBQraWF20A6dGiAMnyUsMQBbGgAHMDk%2BYMRiMOkxADE9YOJEOBklMABtMABGMQBuMAAmIrAAZjEwAF0AGm8fMAAzAFdORAAPMCwsvjBoLG6AWjpGprBfWABzMQBJdmb9UKw%2BWHYvNjMJiC6GrZ3RZkgAEQAhPGcwMN4BQjQtTuhEMNX1noALPQB3djrrxC4Ja4YJ8djTS5YIhgYBOKGEABysAAvv9YGFATQ3pxgAB5DGKbEAaUQhGRx32IkOYD4lO2O0GnTE%2BMxxNJ4yaRhMB3Mrlc7mgPH4gmo9GMkDq4CgSmwq3BSlQOSlEFAE0gABIsIQMYrIGCsBLlaINQA3GjoVrINDZI0%2BAAMksOkAWSHUxD4AC9kI6dgAWW21I2oo2qpoarU6tB69SGtXqs0Wq1Kw55H1qgCyNE6-nYiF8ammWA%2BsZ2eRKdoDNSDaZhAfD2qTkAARrBeCWfKbzZbFTbDiUax20qC4Oh1rYsFoZLjmjnvQGIM1zTLK9WQ3XNQ3dS22wOoPGu0nezsKruIJA4jRnmdEMDEFwaIoYlhAe2mlDLSufMGfKGOxvI1A27oK%2BZ77omPbzmAvqnlAF5Xje%2Bh5rA3yAtANAygsJqwGh2IgaI76IJ%2BojfqIv7Gv%2BjZAXhnbgdakEAKwwee8TwbeACqYQEmhGHsFhOFrOweELkuhETFWX41mRoERpRrbAbuNHdnRhwAGxMXBiDXreADC6DoUo2nrIEuCtIM%2BhCS0IlERAJEquuMlbnJ1FgUpyY7AA7OpLGaQh%2BDpogwRNi%2BMGLugy5iauP72ZuUZUQpLmHpBAAcXmXj5Om8OsFmheFTTicRknRQBzZOfFCauUeEwAJypc8tjNM%2BuCGcEoQWQR1lgLZtZxg5sWleu5WJSmDqQcxaVaYhQ4CJlgkhVZEUSWuPUxYB-VxoNEEpqmo0afVjVTSOWUwe1C0FUtYYUY5O4DQem2lv2o0umoWC4uwCiEBYNjFnNYWiXlkWkUVsnXett3KaWJ47d5th6O08AnIg-Cgo1bUmX9Pj5TZhXLcV%2BrORt4MTHk0GjZmnRzM0cgfGoWi-cQHz6Fgn3wEWFm%2BhWp1Y%2Bdf69VAeNlWDblE4xpNZgszR8J0LKEvojxhPgSgqEdDEc-9i1RTjjb8zdtFC00eRqaLnROHAuDwMzrMwezHVdVJe689GBoC7rlX655Rsm-o8AIq0gWAtOczPsECowXkNvYxdDvBK06CrPwuaJMsWKNXIm7OxVkF5Clo2e2b6Yx3HYKIInILJ8Fo3QB8D6Xo1AD63x8Czxbh9z5EO9roMu5nNVGzDiiELiuD%2BIEFvfZB1uc51Ec8ytjv44Lrs%2BOWTFk33NAD0PARYD7fu4AHQch5nLca5Hs-R7HfDx8XSdYCnac6xnfbbU6a8b8PWD5xfV8lysKNMZX1dBiAnro3Vmx9Aaa11B3C6BM9ZLwek6MmAA1A8ZwwTwDBNMUebNVYYwBnZSBUZoF-lgYvUQJRIaIKzIkdogwBJoJkJg7BVtcGiExlPVu0lZ7EPIqQyCJQSZUM6CcWAWAADi2A5YKyVuwZhKtwEENPsVOKD8ho7BKCLRBBdL5FzOKOaAABrM4ihDHYCUK9YgNAYiGQtMEWakEcrozYfg7qSjgbyVUXdCYJRDZOgRIgb4V9rxYBQmoVOGIEYS3YDYAS9h4D%2BV3ofQ4jiFGuJnsotaMCF78Pdk6EkLwKZUzUAsSxMRZzZXmmrM6J90laxjOnNR3js5CNpqCJQHw5GHAnlUrmNS26zxUZ3R%2B6ie5OndOCTAMNpi%2B2ehYRATZ0wIDnMkypeD1YQLcVdDxQzGlNAqCNF%2B-BpjsBoR4bE7pjlYlaPgOQsAnrqCxAJCpv1Ul23rBkkGWSu6HAqM-HYkBbCx0BOwR5JokLggSUFXAkSwQxKMs83KazqkbNqVs%2Be3zjwIP%2BZ-VYs5fBWKbPAGgulYAqHBP4wJRcEVOIgOw22QM0UNK8Xsyh-yTgBBoE2TArSAgfGIO4LAWZqWvIZVGNQ8BpyzmIFqTA6LhkTAqII-5k4JUzipf-XA6BmiQBFYQ1anySHZJ%2BZo-50rcACA-ks4Vk9kRSnqFKPUShEgqEVCk5EQA)

#### Code

```fsharp
let retrySql<'a> =
  Policy
    .HandleTransientSqlError()
    .WaitAndRetryAsync(
      List.map TimeSpan.FromSeconds [ 1.; 2.; 3. ],
      fun ex ts i ctx ->
        Log.Information(
          ex,
          "DB retry policy: Exception thrown, performing retry {RetryNo}, operation {OperationKey}",
          i,
          ctx.OperationKey
        ))
    .AsAsyncPolicy<'a>()
```
            

#### Result

```fsharp
let retrySql<'a> =
    Policy
        .HandleTransientSqlError()
        .WaitAndRetryAsync(List.map TimeSpan.FromSeconds [ 1.; 2.; 3. ],
                           fun ex ts i ctx ->
                               Log.Information(
                                   ex,
                                   "DB retry policy: Exception thrown, performing retry {RetryNo}, operation {OperationKey}",
                                   i,
                                   ctx.OperationKey
                               ))
        .AsAsyncPolicy<'a>()
```
            
#### Problem description

This is a violation of the "avoid name-sensitive alignments" part of the F# style guide.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/29/2021 10:31:35 - c1a4fe61fc4089eada7b38ef8f872ab28f8b914c

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello, I believe this issue is fixed due to the changes in https://github.com/fsprojects/fantomas/pull/1415
Would you be willing to submit a PR with a regression test?

**Comment by cmeeren** [comment]
This does indeed look fixed on the web. Thank you so much!

Unfortunately I am working at 120% capacity now with no immediate end in sight, so I'll have to pass on the test PR.

**Comment by theothornhill** [comment]
Was this covered with that test, or should I add something more 😄?

**Comment by nojaf** [comment]
No, the PR was not [linked to this issue ](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) I think.
