### ISSUE TITLE
Probably incorrect indentation when passing composition as argument

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1423]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXM0AWi0A1gM4CuAtmALwA6ATrQHYTRYAeAdACr0CeAcWwAlRAEcyiElgASiAIZJ6YWpADCsJlkRaAtGoLFyFVQ2YQAPgD4wAeQAOWAJabOWevIBuieiUSjydBwACjMWCAjcegVtMMiIqxsAsiDOPywAUXp6WGUAbTAnJk95dCd4OUUfFXVNbT0DQlJKVTAAXQBKSAAacCh05yYAcxJUMDy%2BiFB4qAASLD57ZDRIIqweyYjIWZL0STGJmYgABl6jqABJJiQtAGUnAC9kM6OAJk2INs2AXxepj7mCyWY1WWg2M22u32aEORwAjH94pAALLydgAGSKiHROiGWDw4Phr2OAK%2BkV%2Bm2mSPmi2WUAARrBYOhCZFIaVoeMARBXoi2bdEBQnHB0JoAIKZa62ABmmKYz25YGlpT8pJ%2BiKpbJpwJWjOZrK2Ow5dNhMwAzHytrd7PJoIgAEKIaW5RAABXkHgo2B8Bsi7kkavJGoB2yBdMgepZlvZexNioALJaIJBrbaHU6XejYAB3HzQeR%2BK6eWD55yaX0Rf2IQMRCmRTWGsMgyMVmOc03xACsSagqbtjud0QAqvYlvR84XiiX5GWmBWIMr0KqZmTa8GIdrwy3o0bYwdFQA2Hspm39jPRNToAskDRMaT0MhsXLzpUq6sr9WUkOb5tMqPfqE43OAB2Y8%2B3TQdEGRQV6R9HtF2XeJVwgOsIgbZMf11P9W13dtFQADjA08IJdDRRTneC3xrFD12pJssP1HdAP3c4AE4iLTMVpW0egNAoCh5BfKtqLAVD-g3eiGWwpjjRY%2BFTkVE80wHF0BSFEVy0opd3yQz962-SSI2kgDZJhRU4QRRTwK4ni1OFZlNMVYSPyDL8JNpX9GJMvczPOOFeUUq4biwWwmF4PgAHUnHxF8EJ0yJkNE2itUM7dvLwvyLSs4ixRyMhrgAEUQMohR4oSH3iiJErEsB0MBDyVjWHDmN8%2BFE0U1F2AuaVuAIJgMm0248FyLAovgGKe3jEkXLXNy6IaqAmpknyuT87sOrRK5pScdgHB8Gdcgydh7GiEgSBcCjFU7abdNc-T3J1RawWWjL4SPDb2FEOB6HgMaJoTG6Er0tCDIW0F1heoD4VAj6vtyeAADlKFg%2BgZQubQKFGHs4REmq6tDMGKBSZwynlAAxXIBKwHjuA8yG5JmOFCMUuGfuRYmnFJxAKfoKmyuPfAPVtHiAH1s3KGLceSxswaW9KocZ9iPtyjw%2BFsehMWkP6CUmwGquB8T5se8HmtM1a3gU84UTRFX5DVjWnGkJGKBRtGMax8ypbmlLCY5rmeb5nxaeBenWpmV5LKt237c1rB2aCTmsQDmd%2BcUwWPDYHwxYlgkvfuo3wzljcWvN8OAqtzqADVjXtIp4CKIZtZfKa85Bh7C%2Be%2BWGfiV4sortEyfytgLtr64G6b3XW8Nn3jaL6kS47SJXna-v2AK2AsCETJjtO87NAnq69c%2BA3atB420uLs3F4iV51orv2sXtUViHtDOiGwEhQtueQvTIyhLvOHFKep926eX-JfFa18eTvStgjRA2YuaOiwLmHQwdEBFW2kwaKF0xTXGgi7HwHtAFURmjRb2Mtz7GQga9cOMMrYAGlECIHsN1XqOgrjfy9HKBUxDtLAPxphJ6EMu5hx7szVeA0hQkDwAfc4LdSFJXIRhVKVD55X0VK8JWVt7jDEwLlIYlAdCjUQPSZECAeFHCAQovGZ8tyqK1AvRUZpLZHEgGKMoQwmCDyYMPTQ9xPEzjINEbgsAgpGJnBdWKJDbqzXzjPOxXlqEK3iGaSOrj3E8SYBE7wWZhj4JRhgoo2DNBEMsdEoGd024FzAabSBTjy6uPjs4bh6If70ngPIS8sBzrDDgQgrEUS%2BHWOlsosGF81F1POGaPuriCqO3kPSTAkjHZ4FuHwLQaJBmIQqbEqp8SQQ6HgDKbhtwFiYFqTQlJK9XEZClLKAZAt6DoGlJAfhtiamh1Liku%2BrjTn0GFHHcxWzKrH3JH0NoLxVgkDJudMYQDvhAA)

#### Code and expected output

```fsharp
let checksum =
  ctx.TryGetRequestHeader "Content-Checksum"
  |> Option.traverseResult (
       create
       >> Result.setError [ invalidHeader "Content-Checksum" ])
```
            

#### Result

```fsharp
let checksum =
  ctx.TryGetRequestHeader "Content-Checksum"
  |> Option.traverseResult (
    create
    >> Result.setError [ invalidHeader "Content-Checksum" ]
  )

```
            
#### Problem description

Compared with the following slight refactor (which Fantomas formats correctly as shown below), the result above seems inconsistent:

```f#
let checksum =
  ctx.TryGetRequestHeader "Content-Checksum"
  |> Option.traverseResult
       (fun s ->
         create s
         |> Result.setError [ invalidHeader "Content-Checksum" ])
```

Specifically, I am talking about:

* The placement of the parentheses
* The indentation level (when using 2 spaces)

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/29/2021 10:31:35 - c1a4fe61fc4089eada7b38ef8f872ab28f8b914c

```fsharp
    { config with
                IndentSize = 2 }
```

**Comment by nojaf** [comment]
Hello, to me this is correct behaviour.
`Option.traverseResult` follows [Formatting constructors, static members, and member invocations](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-constructors-static-members-and-member-invocations)
While the lambda sample follows [function application](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-function-parameter-application).

**Comment by cmeeren** [comment]
> `Option.traverseResult` follows [Formatting constructors, static members, and member invocations](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-constructors-static-members-and-member-invocations)

This seems like an error. `Option.traverseResult` is neither a constructor, static member, or member invocation. It is a curried function. Therefore it should follow the function application guidelines you linked to.

**Comment by nojaf** [comment]
Again, Fantomas has no idea what it is. It is function application that takes a parenthesis argument.
Please raise this in the style guide repository.

**Comment by cmeeren** [comment]
> Again, Fantomas has no idea what it is. It is function application that takes a parenthesis argument.

The function is camelCase. Does that help? Fantomas already has `fsharp_space_before_lowercase_invocation` vs. `fsharp_space_before_uppercase_invocation`, so it already does some things differently for camelCase vs. PascalCase.

> Please raise this in the style guide repository.

AFAIK the style guide is correct. Could you clarify what exactly you think should be changed in the style guide that would help Fantomas? For example, I can understand if you'd want "composition" (as opposed to lambdas) demoed explicitly under "Function application", like this:

```f#
let printListWithOffsetPiped a list1 =
    list1
    |> List.iter
        (someLongFunction
         >> anotherLongFunction)
```

But given your explanation of Fantomas not knowing (in this case) whether `List.iter` is a function or a method (if I understand you correctly), I don't see how this would help.

Heck, this also goes for the current lambda formatting: How does Fantomas know that you're applying the lambda to a function, and not to a method? If it knows, then it can use the same way of knowing this for other argument types such as composition expressions.

Hoping for clarification on this. :)

**Comment by nojaf** [comment]
All of this is based on F# Untyped AST, in this case, the information is stored in [SynExpr](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-syntaxtree-synexpr.html).

[Sample](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQ2wAuYAHgEYwAXgA6AJzHIIEAPIAHHolbIAdDwlUAbrAn0ASugCuNPgApJ02TbDMJsKj1hWZtiAD4PYI2lM81eh4AUQkJVgkwAG0wFG1aRGgACUc4SLFIAGFVZ2QeAFpMgAtYZgBrPwBbDLAAXQBKV1duPn4AJlFXG0VlVQ0tXX1YX38u93N4Yxk0MHyPMfc7BydYMDQF9wAfbxGzQN5Q8MiYuITk1L0wDOy82DzCkvKqmobIEABfIA)

```fsharp
let x1 =
    Option.traverseResult (
        create
        >> Result.setError [ invalidHeader "Content-Checksum" ])
```

leads to
```fsharp
App
                    (NonAtomic, false,
                     LongIdent
                       (false,
                        LongIdentWithDots
                          ([Option; traverseResult],
                           [tmp.fsx (2,10--2,11) IsSynthetic=false]), None,
                        tmp.fsx (2,4--2,25) IsSynthetic=false),
                     Paren
                       (App
                          (NonAtomic, false,
                           App
                             (NonAtomic, true, Ident op_ComposeRight,
                              Ident create,
                              tmp.fsx (3,8--4,10) IsSynthetic=false),
                           App
                             (NonAtomic, false,
                              LongIdent
                                (false,
                                 LongIdentWithDots
                                   ([Result; setError],
                                    [tmp.fsx (4,17--4,18) IsSynthetic=false]),
                                 None, tmp.fsx (4,11--4,26) IsSynthetic=false),
                              ArrayOrListOfSeqExpr
                                (false,
                                 CompExpr
                                   (true, { contents = true },
                                    App
                                      (NonAtomic, false, Ident invalidHeader,
                                       Const
                                         (String
                                            ("Content-Checksum",
                                             tmp.fsx (4,43--4,61) IsSynthetic=false),
                                          tmp.fsx (4,43--4,61) IsSynthetic=false),
                                       tmp.fsx (4,29--4,61) IsSynthetic=false),
                                    tmp.fsx (4,29--4,61) IsSynthetic=false),
                                 tmp.fsx (4,27--4,63) IsSynthetic=false),
                              tmp.fsx (4,11--4,63) IsSynthetic=false),
                           tmp.fsx (3,8--4,63) IsSynthetic=false),
                        tmp.fsx (2,26--2,27) IsSynthetic=false,
                        Some tmp.fsx (4,63--4,64) IsSynthetic=false,
                        tmp.fsx (2,26--4,64) IsSynthetic=false),
                     tmp.fsx (2,4--4,64) IsSynthetic=false)
```

simplified:
`App (Paren(App()))`

The inner `App` in this case is the composed argument

with lambda

```fsharp
let x2 =
    Option.traverseResult
       (fun s ->
         create s
         |> Result.setError [ invalidHeader "Content-Checksum" ])
```

```fsharp
                  App
                    (NonAtomic, false,
                     LongIdent
                       (false,
                        LongIdentWithDots
                          ([Option; traverseResult],
                           [tmp.fsx (7,10--7,11) IsSynthetic=false]), None,
                        tmp.fsx (7,4--7,25) IsSynthetic=false),
                     Paren
                       (Lambda
                          (false, false,
                           SimplePats
                             ([Id
                                 (s, None, false, false, false,
                                  tmp.fsx (8,12--8,13) IsSynthetic=false)],
                              tmp.fsx (8,12--8,13) IsSynthetic=false),
                           App
                             (NonAtomic, false,
                              App
                                (NonAtomic, true, Ident op_PipeRight,
                                 App
                                   (NonAtomic, false, Ident create, Ident s,
                                    tmp.fsx (9,9--9,17) IsSynthetic=false),
                                 tmp.fsx (9,9--10,11) IsSynthetic=false),
                              App
                                (NonAtomic, false,
                                 LongIdent
                                   (false,
                                    LongIdentWithDots
                                      ([Result; setError],
                                       [tmp.fsx (10,18--10,19) IsSynthetic=false]),
                                    None,
                                    tmp.fsx (10,12--10,27) IsSynthetic=false),
                                 ArrayOrListOfSeqExpr
                                   (false,
                                    CompExpr
                                      (true, { contents = true },
                                       App
                                         (NonAtomic, false, Ident invalidHeader,
                                          Const
                                            (String
                                               ("Content-Checksum",
                                                tmp.fsx (10,44--10,62) IsSynthetic=false),
                                             tmp.fsx (10,44--10,62) IsSynthetic=false),
                                          tmp.fsx (10,30--10,62) IsSynthetic=false),
                                       tmp.fsx (10,30--10,62) IsSynthetic=false),
                                    tmp.fsx (10,28--10,64) IsSynthetic=false),
                                 tmp.fsx (10,12--10,64) IsSynthetic=false),
                              tmp.fsx (9,9--10,64) IsSynthetic=false),
                           Some
                             ([Named
                                 (Wild tmp.fsx (8,12--8,13) IsSynthetic=false, s,
                                  false, None,
                                  tmp.fsx (8,12--8,13) IsSynthetic=false)],
                              App
                                (NonAtomic, false,
                                 App
                                   (NonAtomic, true, Ident op_PipeRight,
                                    App
                                      (NonAtomic, false, Ident create, Ident s,
                                       tmp.fsx (9,9--9,17) IsSynthetic=false),
                                    tmp.fsx (9,9--10,11) IsSynthetic=false),
                                 App
                                   (NonAtomic, false,
                                    LongIdent
                                      (false,
                                       LongIdentWithDots
                                         ([Result; setError],
                                          [tmp.fsx (10,18--10,19) IsSynthetic=false]),
                                       None,
                                       tmp.fsx (10,12--10,27) IsSynthetic=false),
                                    ArrayOrListOfSeqExpr
                                      (false,
                                       CompExpr
                                         (true, { contents = true },
                                          App
                                            (NonAtomic, false,
                                             Ident invalidHeader,
                                             Const
                                               (String
                                                  ("Content-Checksum",
                                                   tmp.fsx (10,44--10,62) IsSynthetic=false),
                                                tmp.fsx (10,44--10,62) IsSynthetic=false),
                                             tmp.fsx (10,30--10,62) IsSynthetic=false),
                                          tmp.fsx (10,30--10,62) IsSynthetic=false),
                                       tmp.fsx (10,28--10,64) IsSynthetic=false),
                                    tmp.fsx (10,12--10,64) IsSynthetic=false),
                                 tmp.fsx (9,9--10,64) IsSynthetic=false)),
                           tmp.fsx (8,8--10,64) IsSynthetic=false),
                        tmp.fsx (8,7--8,8) IsSynthetic=false,
                        Some tmp.fsx (10,64--10,65) IsSynthetic=false,
                        tmp.fsx (8,7--10,65) IsSynthetic=false),
                     tmp.fsx (7,4--10,65) IsSynthetic=false)
```

Simplified `App (Paren(Lambda))`

In both cases `Option.traverseResult` is the same thing: a function application `SynExpr.App`.
We do not know any more detail than that. Could be a function inside a module, a static member, a constructor...

And based on the argument, `SynExpr.Paren(SynExpr.App)` or `SynExpr.Paren(SynExpr.Lambda)` a different code path is followed and so a different style is printed.

The combination `App ( Paren ( singleSynExpr))` currently leads to
```fsharp
myFunction (
    singleSynExpr
)
```
when multiline, and that is what I want to see clarified in the style guide if that assumption was wrong.
Should that only be the case for multiple arguments or does that always apply?
As that exact shape matches what is listed in [Formatting constructors, static members, and member invocations](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-constructors-static-members-and-member-invocations)

**Comment by cmeeren** [comment]
Sorry for taking so long to get back.

I have read the [Formatting function parameter application](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-function-parameter-application) part of the style guide now. This includes the "Formatting constructors, static members, and member invocations" you mentioned.

As I understand the guide, I think the assumption you mention is true: For constructors/members,

```f#
foo.MyMethod (
    singleLongParameter
)
```

is correct. But I think it's not relevant in this case, since it's a function, not a member/constructor.

For function parameter application, the spec is clear about placing long/multiline arguments on new lines and indenting by one scope:

![image](https://user-images.githubusercontent.com/7766733/107872624-cba54100-6eab-11eb-8355-7935becd3bf5.png)

Let's take it step by step.

Based on how Fantomas works today, we both agree (with the style guide) that this is correct:

```f#
myFun shortParam

myFun
    longParam________________________________________________

myFun
    param1
    (parenthesizedMultiLineParam
     >> parenthesizedMultiLineParam)
```

Of course, from the last example above, if we just remove `param1`, since it's still a function application, it should be formatted similarly:

```f#
myFun
    (parenthesizedMultiLineParam
     >> parenthesizedMultiLineParam)
```

However, Fantomas (for the reasons you described) formats this as:

```f#
myFun (
    parenthesizedMultiLineParam
    >> parenthesizedMultiLineParam
)
```

From your description, it is my understanding that Fantomas in this specific case (single parameter application) doesn't know the difference between functions and methods/constructors. However, you already have different rules for lower-case vs. upper-case invocations. Couldn't those be used to produce the correct output?

Please let me know if anything is still unclear. I may also have misunderstood your explanation.

**Comment by cmeeren** [comment]
Also, there are actually two separate issues here (my bad). The indentation is another issue. I'll create a separate issue for that.

**Comment by nojaf** [comment]
So, again, AST can't tell the difference.
Example:
```fsharp
foo.MyMethod (
    singleLongParameter
)

myFun 
    (singleLongParameter)
```

AST:
```fsharp
ImplFile
  (ParsedImplFileInput
     ("tmp.fsx", true, QualifiedNameOfFile Tmp$fsx, [], [],
      [SynModuleOrNamespace
         ([Tmp], false, AnonModule,
          [DoExpr
             (DebugPointAtBinding tmp.fsx (1,0--3,1) IsSynthetic=false,
              App
                (NonAtomic, false,
                 LongIdent
                   (false,
                    LongIdentWithDots
                      ([foo; MyMethod], [tmp.fsx (1,3--1,4) IsSynthetic=false]),
                    None, tmp.fsx (1,0--1,12) IsSynthetic=false),
                 Paren
                   (Ident singleLongParameter,
                    tmp.fsx (1,13--1,14) IsSynthetic=false,
                    Some tmp.fsx (3,0--3,1) IsSynthetic=false,
                    tmp.fsx (1,13--3,1) IsSynthetic=false),
                 tmp.fsx (1,0--3,1) IsSynthetic=false),
              tmp.fsx (1,0--3,1) IsSynthetic=false);
           DoExpr
             (DebugPointAtBinding tmp.fsx (5,0--6,25) IsSynthetic=false,
              App
                (NonAtomic, false, Ident myFun,
                 Paren
                   (Ident singleLongParameter,
                    tmp.fsx (6,4--6,5) IsSynthetic=false,
                    Some tmp.fsx (6,24--6,25) IsSynthetic=false,
                    tmp.fsx (6,4--6,25) IsSynthetic=false),
                 tmp.fsx (5,0--6,25) IsSynthetic=false),
              tmp.fsx (5,0--6,25) IsSynthetic=false)], PreXmlDocEmpty, [], None,
          tmp.fsx (1,0--6,25) IsSynthetic=false)], (true, true)))
```
`LongIdentWithDots([foo; MyMethod],...)` -> there is no way of knowing if `foo` is a namespace, module, instance of a class, ...
Nor should that matter, the question there is if a single multiline argument inside parenthesis should follow the member invocation rule.
And again, I'm going to need to see it **explicitly** in the style guide before anything changes here.
So please stop discussing this here because I'm not the one you need to convince.

**Comment by cmeeren** [comment]
I apologize if I have misunderstood your points. I'm still confused and I think we may be speaking about slightly different things, so please allow me one more chance to clear up potential misunderstandings and attempt to understand your position.

> there is no way of knowing if `foo` is a namespace, module, instance of a class

I don't think `foo` is relevant in this issue. (I had another issue, #1421, where I suggested some heuristics that would involve `foo` in this case, but that is not relevant for this issue.) My suggestion here is that `MyMethod` is upper-case, and you can use that as a heuristic, as Fantomas already does with e.g. `fsharp_space_before_lowercase_invocation` and `fsharp_space_before_uppercase_invocation`.

> the question there is if a single multiline argument inside parenthesis should follow the member invocation rule.

Allow me to rephrase my understanding:

As I tried to make clear in my previous post, the style guide contains examples that are unambiguously clear on this point. There is no ambiguity or inconsistency. Isn't that sufficiently clear, when all code samples in a style guide that relate to this very aspect of formatting (long parameters) are consistent?

Furthermore, the style guide stating that a _member_ invocation rule should be used regardless of whether the invocation is a member or function, would be very surprising. The style guide would have to be completely explicit about this if that were the case. It is not; as I explained in my previous comment, it in fact clearly shows the different styles for member invocations and function invocations. The samples are consistent about this.

As I understand it, the problem is that currently, Fantomas can't differentiate between e.g. members and functions in a robust way. If this is the core issue, then there is no question for the style guide. To overcome this limitation, I have proposed using existing Fantomas functionality (lower-case vs. upper-case).

So according to my understanding, there is nothing here to be modified in the style guide. Again, here's what you specifically suggest should be cleared up in the style guide:

> the question there is if a single multiline argument inside parenthesis should follow the member invocation rule.

If the case is that you want it spelled out in words, and not just in (consistent) samples, I don't really understand why you'd want this in this particular instance (since the samples are consistent and there is a lot of other formatting in the guide that is only shown fully in samples, not words), but sure, I can try to get it into the guide if you really want. In that case, could you briefly explain _why_ (given all I've said so far in this comment), so that I know what the style guide PR should contain? I support your position that things should be in the style guide before Fantomas adopts it; I just think this is already clear in the style guide, and am therefore confused about exactly what you require when you say that something "must be in the style guide".

If this is not the case, then I have still not understood your position, so it would be great if you could just tell me, based on my previous step-wise comment, where you start to disagree.

Thanks! :)

**Comment by cmeeren** [comment]
I see that https://github.com/dotnet/docs/pull/23130 is now merged. I assume that was the clarifications you wanted? However, I'm not sure it clarifies this issue.

Specifically, the additions in the PR says that (emphasis mine)

> When the function take a single multiline *tuple* argument, the same rules for [Formatting constructors, static members, and member invocations](#formatting-constructors-static-members-and-member-invocations) apply.

But in this issue, there is no _tuple_ argument. It's parenthesized, sure, but it's not a tuple (it doesn't contain multiple elements)

Have I misunderstood something? To be clear, according to my understanding of the updated guide, this issue is still relevant.

Please let me know if I can help clarify anything.

**Comment by cmeeren** [comment]
Please disregard the comment above, I think https://github.com/dotnet/docs/issues/23004#issuecomment-795905871 is a better place to ask this. (Feel free to comment there.)
