### ISSUE TITLE
fsharp_space_before_uppercase_invocation=true breaks method calls

### ISSUE THREAD

**Issue by lydell** [fsprojects/fantomas#1437]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAZWBzAdJrWiATmADwC0AOgHYQT6FEDCs1AZgJZYCuRAhgBcOrABQBKGnSlgcAEUQBnAUW7QBvRDgBiAZQAWfIgAcAKgE8ji8ZOkQcAdSIcBiE7BwtqC2ABtE12lsZJiJEQUQGYgDIABpwKAVEASFqLAVUMABteIhQW0gAEgELZDRIDmoBWJy6QoA3Ph9uUqyaqQAGOKCoAElqJEqdDgAvZC6ggBY2sABdGoBfcdzpwuLLDPLK6vyChqaW7O6ARiXpSABZPgAPdAqIxFSBPW2go4Amdum5qUWavLOiiUNgAjWC%2BF5SeqNZoZQ5BN6nSE6RAAWw4cB8rAAggIAKL9ADybFu1DG0wgbEaiS%2BC1O-0hgPWZVB4MRUF20IO5LAAGY2RBIDojHxoIgAEKINiwUIABUMfBRSWIEOkymaNJ%2BdJWjJakBZPhVAo5%2B1h3Im-KgQpF4sl0oisAA7sRoHxEn06rAXUJWIa6GrEBq6L8pPTajqQWCDWyoSa0HDbABWC2C4WiiVS0IAVSMliILrd1A9XuE1F9EH9gYgwbooaNa11%2Bt9MZhce5ADZk1a07bQkwfK6FJ4lCo1NKy2BKT5qbZvkGtTt6xHWdq9i3Wt0AOyd1M2jOIc6o4HKi2T6fSWdV%2BcAxfMyNN41r%2BPSAAc2%2Bt6btLExpZPVIDM9pP5tRvKBG2jB8uW6ABON9RSxNgXGYWAURRPhxwrADNSAhcgVvZcdlXSDXk6bkU3fHtEGRNEMR9X8p3-c9AJDYDcNAu9wMI01jhOUiu0QeDEKo9FfFo7kMMYrDmJwpk2PwgFONbY4EVIvoBgEAlqBMIgzHsZxnjos8pAvMBq2WaSG3YldOS414%2BV4ncsSIWBuH6eQfA4NFEPQlQGKMpiaxYmTNiqDjrMU15zVIy4rh6NgTD0B5cXo-RpQEXT4CeccJk%2BTC52w69WOC%2B8FPXV4kyi64%2Bk4K4CVzQRpVxK4jFCBQFBLccExyiS8qkgqgoqEKrNjUrbCODsKquAAlRA4CIeB0syi1ssrEyrwZECitC4anykI4twm6bZvgAA5bgUSPIgiR6FwUXSC0jhW0ywFrdkNpRbgfCEdzSS0aVUOSYhzHWLbH25I5X1Iw7pXgc4Pq%2Bu5fqIf6vOTaADH4NRiAAfQdDgMueR61rDDaBuKsKRukI4YImxz%2BDMAkiFuJQFv0s0ur8ySAvMjZSZBojbA%2BZNotpvh6cZjglFO87iCum67rBwn8vWwr3s%2BjhvsQRHkcBoE%2BZsgWeO6SARbFpmBFhtWNa1wQUdItH5UxogcbxzLFd65X%2Bq2PXwoF5SjeigA1TkxQqeAKiwFmsvZuhjKel7VkK3mhtB7o3js-3ri0Fy1BLEP%2BnDyOlujiBY6JutE695P%2BekN5Iozq5ZFgAQAHEkka5rFDa1hC%2B5Tq3a5vqLLkhkSp2ug3nK-24fVu4xUxaAAGsxQxhekgUDSdAVRAvzOn9uVPXyY-8szB6XKMq-1mvxqN47EAdDWJQEJ0HiBxB5E4ahnBLLF%2BgPaWiHlt0A%2B-cT4eyHufAi5Mx4QDePtI2ABpRAiAjCxXig8Pom9FQkjJEAv8IDnqBV1EnSB21uRvAhvXJKaIFB6B7t0ZauVLxK2JoVMCF8fY12pkbIYqQ-COR4IqSo9hEDAnOAgHBQRgGMNWsw8uQU2EkJTkEHkJEjZYnclgagWdqA51YEMTRggNBuFUg8AQgh2oGUPiXY%2BBDuZ4QgfJKB3IeSGyCMbT6xBqDmLqPaVIf8LrvwqF-VggDJF4OkXHQhZ8yakO6DyP2biLZCGwegBUwJ4B8D7LANqqRb73zuOOKR3UmHuxYfIyyijq5SB5OnNxsgJZ8GBH4KhEs9A6DMJUa4hTwnFJkaUuRuoHjwCJNgnQxQ-AxKUbYHkdc3H4mGcSApqMiA%2BDYJAfB8dwz2MmVUugPJJ5uLGU4NQYikDdPoo9eIMxxjlAUFoNqGRgHzCAA)

#### Code

```fsharp
Log.Logger <-
    LoggerConfiguration()
        .Destructure.FSharpTypes()
        .WriteTo.Console()
        .CreateLogger()

```
            

#### Result

```fsharp
Log.Logger <-
    LoggerConfiguration ()
        .Destructure.FSharpTypes ()
        .WriteTo.Console ()
        .CreateLogger ()

```
            
#### Problem description

The output code causes the compilation errors:

```
error FS0039: The type 'Unit' does not define the field, constructor or member 'Destructure'.
error FS0501: The object constructor 'LoggerConfiguration' takes 0 argument(s) but is here given 1. The required signature is 'LoggerConfiguration() : LoggerConfiguration'.
```

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

This seems to have been introduced in 4.4.0-beta-003.

#### Options

Fantomas Master at 02/05/2021 16:56:34 - 0cbe3df847dd1815455ee222b918644c2b6ce98d

```fsharp
    { config with
                SpaceBeforeUppercaseInvocation = true }
```

**Comment by knocte** [comment]
Wow, shouldn't this be an F#-compiler bug?

**Comment by auduchinok** [comment]
> Wow, shouldn't this be an F#-compiler bug?

@knocte Nope, it's per-spec. The application without space inside has a higher precedence than a normal one, otherwise it'd be very hard to come up with rules for applications and access-via-dot syntax, and cases like the following would be messed up:

```fsharp
f(x, y).g
f (x, y).g
```

**Comment by knocte** [comment]
> cases like the following ones would be messed up:

hey thanks for the info, but what do you mean exactly by that example? how is `f (x,y).P` different than `f(x,y).P`? genuinely curious

**Comment by auduchinok** [comment]
> how is f (x,y).P different than f(x,y).P? 

Here the first example passes `(x, y).P` to `f`, while the second one accesses `P` member on the result of `f(x, y)`.

**Comment by knocte** [comment]
Truly interesting, I guess I hadn't come up with this because the fluent style is less visible in functional languages (because returning the same element in each call attracts a programming style that involves mutability). And what would `f (x,y) .P` be?

**Comment by auduchinok** [comment]
Well, the tuple example is not very correct, and my point needed a syntax example where parens are required. 🙂
Imagine accessing member on a function application result like this:
```fsharp
f(g x).P
f (g x).P
```

**Comment by auduchinok** [comment]
> And what would f (x,y) .P

`f (x,y) .P` is the same as `f (x,y) .P`, since dot access has higher precedence than "normal" application.

**Comment by knocte** [comment]
Ok thanks!
