### ISSUE TITLE
Vanity alignment used when calling base constructor

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#1442]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WbArgEYA2AltGAKImLToBOBAtgMqIMBuHASougQYA7MkIDmASSHoOQgIYkqDBrAZUAHtETZ0ZWELAAKZogDOpuWMRpTjUWIA0AHQMQ37j56-efv93CQ0UXRnVz9wiMivVTIxUQU%2BAEcCM3QbO3FQqOycvxi4%2BRI%2BU2x9U2swWwZ7AEowAF4Xd1EACw4ydGpaeiY2Dm4GPgFheyUVNU1tXX1jMwsrBzAAxEX8%2BKLEZNTV6oKEs1KhcprIB3AocvRdcVNUMABtc4hQT0gAEixcO8hg06e3d6cBQpO6PbwABjO3kgUiQ0lYZAAXsgoV4ACz-CAAXX%2BAF9Uc9MVAPjhkGgftI-q83kCSCC0GCvABGAkeSAAWTk6gAMqJENzEOJ0C0qV4ABzgok49z4-4vNkkr7koiwWAkUXuQHAskPIkQABMrM17GYFDV%2BgAgugqEJ4AB5ABmvKEKL1YAdCnKUrxrPlmsVOsgKrVGoBNO1oLdAGYjQDWNg5FoAEKIB2qRAABTkDDkJhkDFD7kYKW9Mt9RPen0DwfVsa1dJ1jM8aNjEEg8cTiBTaYY-NgAHcONA5OUpJxYMPpkJC25i4hS25Ze4-WGq98azP6-Tdd4AKytqAd5Op9MAVWwuAYw9HQnHk7004PHpIXs80sX5epa%2BVqtrFfDDaRt4ABsB7tgmx49ogADCJAjqY0FlMW9CqDOEDPq%2BHjvhAS5uCubYBuuv6bgB25Nh4ADsYFHl2J69uyiDMEQHBoe6nrzm%2BPpyv%2B35QBudakY2bpitREG0VBiEkPorEYRxWFccuPGkkRIYCbSZFugAnKJnYWg6%2BaIcwzByKxc4Ljhn4KrxQbEWpEYMm6TKQm64Gdt26YmmaUmPm6snmWAuGEl%2Byk-qp-7qUJ3hMiyLk0Xp%2BaeXA3mmUwcnuNhAWWf61n8eF9k7syhoubCgroHaQgACoMJgADqHQik%2B7H%2BYFYD4cSOW2XlgEOVFMaxWJFoqAQtoACKIOQpr5ilJacWW3HBUqUC-HZ3UFZ4TIti5nLqBIDoVW0Qg0OUrAtKo6B1fAwqsWikqzR%2B81WSFS2UitGlRfuW1clIDpkOodqXnI6CqBo2C9uYD6sbut3yXNikLYGy1dW9zKgZ96h8HADDwBdV0HjdzVZauT0UugJERUBzJUWjGOqPAAByLDMQwjoSDIzC3AeTIEw92XE8wBAkLo5AugAYqoxlXBwFXKa9kXMiJLk01j7IC0LfJiwwEtTWB0AtNmib5gA%2Bv2ZCXSK3Nw49i0k2T%2BXke4TLaWjg05pgdoMLytg4w1br43dFk80T1uI9S5M9V4%2BrOdC20u3Ibse2QtgM0xHAs2zHOORbeFKdb-OC2QwuIBrWtSzLSNy54%2BoxdCsfx576Aq-nhfF4D2subr%2Bv0Bwxum1dWdBVbCMveXFOV0V0dcgAatqSaiPA9je9d0PpQp2fw98IcKmHa0ePqfUT%2BoIvDfQD6z7aC%2B9z73h%2BzD92W7zwfD6Hdtuvqm0HyNsDoAA4vwINg6YB8i8DxQ37q1HO1ZOrP1WvbNw%2BoPrR1VgXPkSYpLQAANZJhzBg-gphyqsFzDBNULAfLeD8v7TKgcCIdTCtA5GldUbQjpogfshcUzoEHIKaWuAxo-REFOC0toGIpwYBnMhTUKEtTapWYmuU6EV13lTaEABpRA2hdr7UFFIAhJhnSunES%2BNKbgMpSIgRvJ%2BW8X7eH1ArA%2BNBTSmBaMA32y9jGrwHg-SBtDLEwNfk7aECJxC0EGmIFgpUaqICIOyBA%2BivDkNvgHe%2BQcvF-nkaPDwUYo5eEgBacgYghBHyECffQCJ8mA0EIgCqsASrSEBhDRqhiwHSMIqFVJPj6EZOrtk3J%2BZ5C6G4NyfQYhhFM14aIDoD4xFxIkQkyhSTqGyKge0hR7gozj2yY3XQejuS5iIPAOQsFYCAPEMw1hfIZIzJXrDNeg8VJtP9NvWBEAoz72ySNROchSCIHsYnForBMC1PUBcxpkjCYLOtoKe0To%2BSsCwLQW2vjvBRnftkm0UK9GsRgAwEgDpIBNLMa0hFHTVkIOybC6o9BolIGBZhK5i5zhYlRD8UwItAF3D8riIAA)

#### Code

```fsharp
type public DerivedExceptionWithLongNaaaaaaaaameException (message: string,
                                                           code: int,
                                                           originalRequest: string,
                                                           originalResponse: string) =
    inherit BaseExceptionWithLongNaaaameException(message, code, originalRequest, originalResponse)
```
            

#### Result

```fsharp
type public DerivedExceptionWithLongNaaaaaaaaameException
    (
        message: string,
        code: int,
        originalRequest: string,
        originalResponse: string
    ) =
    inherit BaseExceptionWithLongNaaaameException(message,
                                                  code,
                                                  originalRequest,
                                                  originalResponse)

```
            
#### Expected results?

```fsharp
type public DerivedExceptionWithLongNaaaaaaaaameException
    (
        message: string,
        code: int,
        originalRequest: string,
        originalResponse: string
    ) =
    inherit BaseExceptionWithLongNaaaameException
        (
            message,
            code,
            originalRequest,
            originalResponse
        )
```

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 02/11/2021 13:26:01 - 7783b6f0ad7fbae744cbc4f742c778eafa946a9b

```fsharp
    { config with
                MaxLineLength = 80 }
```

**Comment by kevingentile** [comment]
I'm seeing a similar unexpected alignment with the following:

```
type ChildTestType() =
    inherit ParentTestType(System.IO.Path.Combine(Environment.CurrentDirectory, "myfile.yml"))
```

formats as:

```
type ChildTestType() =
    inherit ParentTestType(System.IO.Path.Combine(
        Environment.CurrentDirectory,
        "myfile.yml"
    ))
```

which yields an incorrect indentation error by the compiler.

**Comment by knocte** [comment]
@kevingentile if it yields a compilation error then your bug is not the same as this, because this one was classified as minor (stylistic), while yours could be classified as higher priority. So please file a new bug.
