### ISSUE TITLE
Oscillating newlines in custom computation expression

### ISSUE THREAD

**Issue by theothornhill** [fsprojects/fantomas#1463]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwAxTdAF1m0zwB0AnB9Z17BAVwBtSBZTAQKImYALzs2LdBAiYA5gqaIFmKogBK%2BXlTDApco2CEEeATzABLeNdl5aiMl3TQqV2NNbG5mHg7B4K0IeTHNMACM%2BAElbK1kAQSUVNQ1tPF0AOjoCMAAKADMXMAAPMABaAD4wPComeIVSzIAtAEowBUMfE39YMBEmB1l4jsQqABUACwawSwAfaqTlVXUtHR4qTNgC9N0unz8AzhU7MCWU1d2NzIj4%2BH3ux%2B68hTGAGU8FItd3TwA5HCIADqViokw%2BVDwAHkCgBlKhcAoFB5PVFySqLZIrNLrTbbK5UVootFPOjxKYNKbqAASpkQ6EYMmJEBUCKYXlkaOAYFiEms9xkJIgABFgmYwpEYrZxIExaFwlFELFmd1%2BLATjLjqQAL4PXUySAAGnAUDwY3c6AUeFQYAA2iaIKAfJAACRUcwiG2QeJUI0OuSugBufi4yDQ9seAAZjY9INF0EhqLCrAAvZAx7oAFn9EAAuv7tRnHTmoG6PWGoD6-c6XcGeKGbRHugBGIvGSCCEpveKIN70hRg6stgBMkZL%2BaMhf9TvbZc9aEgEVgsB4Q6MQZDFabPmHbfXsMQ2CscB4ngSVAAogmYd30OmSxACodEOOC22Z%2Bu5xXF8vV3vS3WDbhg%2BYAAMz-hAkCwkQJAAEKIAU6qIAACpgTCAhoTBrsYdShq%2Bk7viWrruvOUBLiu2GQbWm6NiBmYQVA0HEIg8GISoHwAO6iNA9BKuggawDxvzoJRci4S%2BPgTnIU5GB%2BAZfl65F-kR1H1luIEAKwMVBMEsQhSEAKrCNxvHxgJQkeCJDFPv4EnGFJEAyXIclUSR35KaJG5qbRjwAGzaUxcH6SoADCoR4HgIWeLUTBcG46qiY%2Bz74dJhE1m5im-p5qlAXaIEAOwBbprFIfwh4RKIiVgDZZopY5aWzhlC4ef%2BXm5duxgABxFcxJWhSunhVTVdlGA5YBOcW6XlplFGtTl6mPAAnD1JAJAUmFRdgdBVeJdXjQ1n5NWRWVzYBC0ttGIE6b1wWIAeR4noN1nJZJb7TipR0-rNKlnT5LatldgWIGtmH3ceA1WSBu2vQR71TaRX3KTWv3AY8za7ld8aJlQULoOMTDmCCg7PbZe0TfoH3Tc1J0-TRqMtuBgO6QkTCwC48DCogPBWEemE7bFI1yGN5MuaWn1VqddN5Wj9FXZ20QFFM9IXrZsKTOqVAgvAxN0WOMOpXDjVU5W1DZSj0stlpcuYCU8YFFYJRQgM6jqheJQECoEWWVVGl6-Zb2yZTCMS7T3n0z4zb%2BdbJTaHATDwFrOuPJmfujQHzlB9%2BIfI1LHVGM2hXR7H6rwH8XDYBVTAwtEGjYNaDHNmTB3yZ92C6FY3N3mQ6p0FQmHjNNkthxbEfdVdxfx-w7ed04PfqHz2nQJMaHEJhAD6HE2IOTeG4dxveqbQ-tSBzbLdHLPoeYUJMN2tSJ5MVUpzvgfw1nh%2Bh8fjyjtpnYX2E1%2B3yoGXCuohq613rifZ%2BGdX5ejbhsDuPZu5MF7v3QeH9zo7gBrGP%2BV8b7BCoFPeBM8kEoMqovZe6E3CiA3lvB%2BUDJpG2Du-HOw885yGHBjWMnYABqm5YJ3AaPfR%2BqchbpwYXvJhvoj4YOMMORmXCbbOB%2BJZfhCZBG0OEfQimMCFzZ1nObNhEBhyywUSUYUsAqAAHExhuw9vgPAlkhEMV9lo0WxF94tXQX9HcVsuHTx7LBU80AADWsFKHBLGNCdAsJARRXrNgSGjxhquMzjNJG%2Bjc4gWHFHWMfxEAcRnvBKgXF6QDxEJze26BQSWQSAmMqIDBhDRev7WGL9GHuRpiwz%2B3RhyF1jAAaUQIgAgCslboHjDE3At57xJOaWnVp0D2lej0Z%2BAxWSx6mJVkePAkwnG6xSTo4630ukyKMMOM%2BsZkyWj4CzBQ5d6Sa0QBENUSAmmk31vVXeLcPGdIyawkCoFLrYO5godASi3CWWTKC9QXAVDjFgFjB56hvYk1qh8-aXzXI-OOX87pPhQJYO6JABIGxRBYHcIGXsnx6mVwqfEap0U3lopaQbNpEiOk4tWZkx4oFOFEsIe4aZbwcARHgJgMKsAHGWjyQUnsTLBZ5jEdopZ1NOXyTWTy%2BRRLRR4ElIgLZwRJiwnMNQG28qDkqqgPSeAN4ezwnMHwM23LuigRMUSq8NqCjTKqjAJgPACiQAteytJTr-k8t8US%2BE9Q3AvJmd0ZJ6LtQmlzBmb0eAyAOJtMk7UQA)

#### Code

```fsharp
namespace Fantomas

module Mapper =

    aggregateResult {
        apply id in someFunction
        also displayableId in AggregateResult.map (fun x -> string x.Z) g
        also person in getThing y |> AggregateResult.ofResult
        also more in AggregateResult.bind
                         (getLongfunctionNameWithLotsOfStuff
                          >> AggregateResult.ofResult)
                         mainThingThatHappens

        return
            { Id = id
              DisplayableId = displayableId
              More = more }
    }

```
            

#### Result

```fsharp
namespace Fantomas

module Mapper =

    aggregateResult {
        apply id in someFunction
        also displayableId in AggregateResult.map (fun x -> string x.Z) g
        also person in getThing y |> AggregateResult.ofResult

        also more in AggregateResult.bind
                         (getLongfunctionNameWithLotsOfStuff
                          >> AggregateResult.ofResult)
                         mainThingThatHappens

        return
            { Id = id
              DisplayableId = displayableId
              More = more }
    }

```
            
#### Problem description

Fantomas adds a newline here, which by itself I don't mind. But when fantomas is run again on the newly outputted code, it reverts back to the first example. This goes back and forth every time fantomas runs, which makes for an unstable experience. Also it seems for format things correctly inside the `aggregateResult`, apart from the oscillating newlines. This issue does seem similar to #1227 though?

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 02/19/2021 13:56:09 - 33044705e3b0f40b56b278e3d46c58786f5b68d5

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello Theodor, thank you for taking the time to report this issue.
The problem is indeed from the same problem space as #1227.

To solve this you will need to add `| SynExpr.JoinIn _ -> genTriviaFor SynExpr_JoinIn synExpr.Range` to 
https://github.com/fsprojects/fantomas/blob/33044705e3b0f40b56b278e3d46c58786f5b68d5/src/Fantomas/CodePrinter.fs#L2642-L2676

Are you interested in submitting a PR? If so, please read our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#getting-started-with-fantomas) and add your test to `ComputationExpressionTests`.

**Comment by theothornhill** [comment]
Thanks for replying :)

I will look into creating a pr this evening!

**Comment by nojaf** [comment]
Wonderful! Thanks for taking the time. If you have any question along the way, feel free to ask!

**Comment by theothornhill** [comment]
Not sure what went wrong, but I checked [fantomas-tools](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBDA5pgToz6ALogEqIDOArgDaFjAA6ODAdhBOgA6fUCeYAS3iC25WAFtEAMUotohAbBZNW7MOmpiw8AeR7pe6AEbVEASWEC2AQWx4CxMlVoA6cVzAAKAGaywADzAAWgA%2BMHJCHCtMAJcALQBKMEwVNnYNLU5EHDE2K2TEQgAVAAtosH4AHzDbXHwiUgoaQhdYbydm1LUM2DBxWDwRMFr7Bo7XIyt4LrVZudnPTEKAGSVMXzkFJQA5dEkAdQFCEtXCcgB5bwBlQkpvbxn5p9mQmrt6xybXNvHCBMfns93FZStFSkQABJcLIscipAF4W44ZTMNJzYBgCxgAC8gmmqMBABFdPpDCZzMJcTo9NQDMZTBYAXMALIDRA4vpssAAX1SvNRqSwdQcjWcdEYBPS3D4eKGYkkMk2ihRqnSml61NJ9IpQxGH1FzTcHh8fkCoXCkXK-niSRSko46rAWRySiGS2KZRYMSqb2FYy%2BLR%2BAfh9vUjv6g3yepFvxckxY%2BNVgOeixWaw28mVuwORxOsDOlxudweoeT81ew3eMYDrXaAf%2BpbLamBLFBXvBhCh3EQsJDSbAiMoyKZ7AxWNxQhHamJNLp5PH2hJtLJDMTaPmrMGuIj7P5rD3LEgABpwFByIUFF7yKgwABtU8QUBzSAAEkIvCyN8gVkIx4f7FfAA3DRKGQNB7yeAAGE8nkgMwEx7QgrgEAAvZAYPmAAWf8IAAXX-bkMMfHCoDfD8wKgH8-2fF9gOoUCbwg%2BYAEYiNmSBmXQfxlisRBlh7TBjmoliACZIJI-C1EI-8n3YsjPzQSAjFgWBqGEtQgJAiimLmES2I0q5EHEAQ4GoJRrEIABRBNLh4lh0JIiBvAyRAJIItjZI0%2BSKKUlS1P00i6IY8DHLAABmAKIEgK5OHQaBEAAIUQbw2QABXQHA9kKbJ1NmSJQLcqSPJI193wUqBlNU3KotorTGNCzDIqgGK4sS5K2VWAB3bJoHQc94MA2Beq2Q8mvy1y5kk9hpLUTyAO8r9Kv8kravo7TQoAVia6LYvipKUrwABVbscF6-qWEG4blWq9hnM0CbZimiAZtHFayp8pabs0tb6qeAA2baWr29q8AAYVpchyFBpQIhwSh5AGG6nJcwrpuKmj3sWvyvtW4K71CgB2QHdrag7EGZIyjBypq7vPVHnvRuTMcUz6Au%2BvGdNmAAOYnWv2tlobM0bQtph61CenlGa85mKuxtncfWp4AE5efi6xvGIHBofEdwkbAcb6clmS3vIrGqvloLFZY6DQp2vmQcQQzjNMpQ9dFw2XuIjHTZZuWVst36WNY22gcQdXNadkzVNdsa4bF9gJc9%2BgTfK3zzf9uqQqeZi9Nt%2BCkBYQhzlbHBeEOISaZRyb3ON73U9ZjOfqzliIpDknrBwWBZHgQlEGoARjM1vWDerora6Zn3KMLnGA%2BbuZmMa23OP8MxvFKHtLPuq4SgGQhDngCuGvE0e0fH6XJ%2B-aeLcz-Hs62peuPg7wBH8c5nSIAZLP8Tg8Eh66mo2sfR6NdZopx8lRa%2BTdb4sQBg-fwZA4A4HgPvQ%2BTxMJAPFiA16ddwFX0bhzUKzEiZwIQQMeA2xKDiCpjgS4ZhiDiGvE1ZiHspbzRlpAcQzQBD93slIAY7hCCayKKbSBBDs481tqQpBzIuE8OkPwogQ9trQBKBlOKmsAD6nUhBCRYWfNhF8IH4KtvPFWcCO6ZV4OcHAPEIgoJKHrdBejQE4K-EYmis9oG6RtrBZeFiDDWNsYQChVDsi0PoYwwhzjsET1Tpw2g3DeJ8JwAIoRIjjGB10sHWC-irE2N0IQGRCS5HJNSdTW2Ki1HyGyFonRDjole1ibg38oiTGzBErnXxXEABqWkEpTGiPYxxGCE5YMaefVO7i5KeM5moESrcun%2BEVJmJQ-SEyDLqcMhpydXGKSmV5GZoURKL0WYSfMABxQoX8f4UHIMqIZACRl4TGTsppZtloeJvrM9gIl76%2BNkbxBKZloAAGsEqZVBYUC4LArhZUFpQ4WTx3YnwZvomq7CG6fKgd8iAIlYGwW2IgTqcikqEG6j2YRWRe7PxYEcZU1gEwU1CTkN2VdgFjxcW8326csViPmCJYhsEADSiBECcFXuvFg8FYWSDsg5JFbLMEcpiRM5pM8vlHIkYszexlyAlAeUfbZc10UX0xdMjVTwRJmNgshL0pgO6YEoYhfYiAjCsiQKy%2B6RqwHvPVdi0KYUfHzEgNYfumAWDLJGshcNRAhyICKLAfOiEiD-xFoq0ZyrxkGPrn7XlbS1BhWycG0NmsWApsAnxNYTLqHUqsHSmGnq6YoqNpy1VvrWmZNmGFTpwaikKDlcsPYRh4DoHBrAO5XpCXEt4o2%2BOzzM2vLbdyj55r-VPDCgs4NM5tQ6t0CUK4vBC5cVnd63ZUAezwFsrxG4vBTB%2Br5XMMKJzg3WUvd4OVesYA4GoN4SAp6uWyx5auh9Xa-nBpuFEeQ7r5XzGRey6ap5cIYW-OQKQdybzu25EAA) again, and it seemed to exhibit the same behavior as before the fix. It is using the latest commit from master. Do you know what went wrong here?

**Comment by nojaf** [comment]
Hmm, not sure what happened there.
The latest deploy seems to be present. I did tinker with the tool today, perhaps my changes are related to the current behaviour.
It works on my machine though, pretty sure this is unrelated to your fix.

**Comment by theothornhill** [comment]
Ok! Thanks for getting back to me. Let me know if there is something more for me to do :)

**Comment by nojaf** [comment]
I redeployed again via [an empty commit](https://github.com/fsprojects/fantomas-tools/commit/782c15eeb1cbb09546a18d6778cae832c8ebf38d), the problem seems resolved now. Can you confirm?

**Comment by theothornhill** [comment]
Yep, works on my end! Great :)
