### ISSUE TITLE
Inconsistency about when fantomas decides to split `()` (unit) to the next line

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#1469]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwBlWXAOTwB117sEBXAG1ItwFkX2wBeehAjsALmADiiUVVgAnbJlYBBaHGbpReAAqYAlnL3oA5gEl0AM1gAxeQHVMo6AAsHrMQAoAlGgDyBUT1YdAAeBydXJTFzKwA%2BASFhJLEwIz1ApWUAIzwBVPR0vSVrREQ7dOdlLjTsZmwJTB1DEnM7RD0AET1oUUdEeAAhAE9lADd9Vkws9m1mae7rNlZZJDwAOgBhJWg2Puy8WFZmUUQANSVmRG9EpIg0jJUcsAB6MABGAAYPyAAacCg8NJAiY8KgwABtf4QUC3KAAElEQwIyDQkCMol%2BUOEkDh4yOKIhWKSHz%2BsIgkHMSE0ZD0AC9kKSyQAWIlgAC6WIAvozoaycYjkWC0ZpMbCcXjLmDIWT3jzbpAuJgAB4AGSMiBViBMomcorJAA4PqyOUluViYfKEUiCZAsrBDnqkuKLgTpWSAExyp1kRDYbqHYLKUQAUXQ8F8FjV6AZrIgFiUgONXLlFqdVsFqLtDq98IlrtjYAAzDnyWQiCQBogrHJELo5DhpIg5I7bqI5Jck6aU3z0zas6wW%2BTcS6pQWmSWoGXiIhK9WNbAAO5N6CNRDmUawFeBYKD4Rtjuwk3CM1JVPY3tC-u75340cygCsE8gU4rVfkiAAqgRkXIV4D15ujhBOgu5xgmiCdse3Zihemb2gOOY3pKaBurCABsT4vjOb41hskx4HgGzBHg%2B49PIoFgPGrCJoeybmj2Ap9vB17DreKEFgA7Jh5bYXOXC%2BlkTYUVRNG3EeEAnsIZ5Doxl7MYhrHIYSMr6tx06zu%2BRGsDuE4iRBtFdvRMGyXB2Y9nmd5kgAnGpJDKBYJxyER2CKBR%2B76WJdGngx1pyWZMEWexMqfLZvHvj6fpwNpIG6eBkESdBlomVAV4KYFylkm8byhfZjkRf60Vue2HlJOJYCSbyxm%2BaZCHmSOQWZZ6BYUmGWqiL46AACpyEM5Q6sJcUGVBRlJdVKXyXVbEZbCbzFs1WHKHIsAaPAHSIKweh%2Bo5RUHp5hneVVGZQOiLHpahtxvOOzWKkqpgWJ1zhasG1GIGQzjyKI5TwP1E5MkaQ0JSNabJcKGJpfV00XY%2B13KjEehKv4TaOPIwZKgQNYEcBFH3v9e3DQdo1HaDp0Q%2BdSRvBhMNKgASogcByPAX0-WOuOlV5Uk%2BUTJ3g1NZPCG8XFU7T9PwFQdSCXIEamCc2CghObzxeViXA2NkC1KwgQbdGtgKI4jmdb5PNKXzEBvKpzXC-I8BcGwmvqjriiiNtT4uJg9Y9E2AD6C56N9uqKxVYDSfCIPc5NxsFm8NlU4t9ZDL4chqiRTO6r9rPCGVgfB-yqthwFpMFu6JIx3IccJ0nMji02Usy3LkcB8r54g%2Brdva-Ijv64b4f5jK7rZc1seYPHid6CRNsa3oWuIA7etCS7zhu8Qjne77-UN0DTe5yKRs9x6TUygqyrnPiAxGPARjGCnFF-evBMq1z2-d5ZsLunNB83Ys6A9MBp9hhfV9p1vhzQ6No86WjOoXK679lQdFgKIKQIY0YYzwMBABBYcZAMqoTJi-lwEF17tDd%2BttJ7qgGNpaAABrAY7sKHSDwB1MgDYtJ1BigWPSmCg6cxwbVfOvNC6UwPlQRAC4p6VlEEuLUBtkRrQsPcYCygwz8WwBLOuMp2EAyVhvGSqtUpPwai-QWB8ADSpQCB3QelqcwjDcBRhjGowaeNAZ303g-MGejIZJHdObaBSpnp%2BjwK4VeqcWYcOzrBcauC0wQN7tHA%2BNITDsEWsYOobU2hZB4EgAaL1QlcL8jwvBfCZSFmLgfZQG1jDoE-t-YINIKmOGYDWTqsBKRtSAjpNhDi2b7WAdgvJJNClkkLP3UpGsmxYECKMecJglESxkXI4iWTRJdPxj0%2B%2B3D%2BkRyKfvMkCpiG2JVDgLI8BMB4VgCgkwQiRHqkWSVDO7MsFrL6TvZ%2BtxCxvx2V0PAUx2B%2BNHs4MgQxNDKhuTkkBQotThkjOqMgiJ2AbN3rCQsUCdmhkhbYiiMA5CsAsJAUFvSarwpeUkQshCdkwuaKIDJdiyTqMceVf4bJGRojwNYFBYJ2GciAA)

#### Code

```fsharp
namespace SomeNs

module SomeModule =
    let GetNormalAccountsPairingInfoForWatchWallet(): Option<WatchWalletInfo> =
        let initialAbs = initialFeeWithAMinimumGasPriceInWeiDictatedByAvailablePublicFullNodes.CalculateAbsoluteValue()
        initialAbs / 100
```
            

#### Result

```fsharp
namespace SomeNs

module SomeModule =
    let GetNormalAccountsPairingInfoForWatchWallet
        ()
        : Option<WatchWalletInfo> =
        let initialAbs =
            initialFeeWithAMinimumGasPriceInWeiDictatedByAvailablePublicFullNodes.CalculateAbsoluteValue()

        initialAbs / 100

```

#### Problem description

As you can see, `GetNormalAccountsPairingInfoForWatchWallet` function has a long name, but not too long to have to split the line to respect MaxLineLength, but it still split by fantomas, why?

On the other hand the invocation that takes `()` at the end is not split, so this seems inconsistent.

#### Expected Results?

To be consistent, fantomas would need to do this:

```fsharp
namespace SomeNs

module SomeModule =
    let GetNormalAccountsPairingInfoForWatchWallet
        ()
        : Option<WatchWalletInfo> =
        let initialAbs =
            initialFeeWithAMinimumGasPriceInWeiDictatedByAvailablePublicFullNodes.CalculateAbsoluteValue
                ()

        initialAbs / 100

```

or this:

```
namespace SomeNs

module SomeModule =
    let GetNormalAccountsPairingInfoForWatchWallet()
        : Option<WatchWalletInfo> =
        let initialAbs =
            initialFeeWithAMinimumGasPriceInWeiDictatedByAvailablePublicFullNodes.CalculateAbsoluteValue()

        initialAbs / 100
```

or this:

```
namespace SomeNs

module SomeModule =
    let GetNormalAccountsPairingInfoForWatchWallet()
        : Option<WatchWalletInfo> =
        let initialAbs =
            initialFeeWithAMinimumGasPriceInWeiDictatedByAvailablePublicFullNodes.CalculateAbsoluteValue
                ()

        initialAbs / 100
```

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [maybe] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 02/21/2021 20:52:04 - 8e72be95ecc684ebfe2e822e42dc9c7e79169eac

```fsharp
    { config with
                MaxLineLength = 80 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
The unit should be on the next line indeed.
