### ISSUE TITLE
Vanity alignment used when splitting first line of a match pattern

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#1473]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAyrOogLLZ5gC8AOgHYQR4AuhxiAYlndGABQBKavUaiwASwBmYAM7sAwrDrxxzcUrDMAFojoixBlmABOiGcIYGrEdAENm0LbLMz1debceJ4AOUTMAd1hjAGsAEXtbADoAeSxmAHNYcToEgBVjWzoZTzUlGSiMgE8OFPgwaCxjUx4isADVLX1rAwAfMB8lfABaAD4wUlsAByjEdCHmIuaW0XaiEgqqmugigEF4eFMZGTMwPsXq3RX1zZczaet5-C2LxkQcHduDTrpkABpwKB3mNVSZVDAAG1PhBQAZIAASSZDZBoSApZiQD7giEAN1sOCwsKBILEAAZkVZIABJZS6ZgEcQAL3euNEABY6WAALq4gC%2BhNBTMh0Ox8LoiM5jEh6Mx2OB1gAjELRJBBgAPAAyKUQit0CW0SKZEAAHHimazRBzcWCxDyijCAZAAEawWA4LUo0VYgESqwAJhlwoIY3EcBwSlWzAAosoYpJla9HVZJBidgb2ULTbKoRa%2Bbb7dGU87xdqwABmL0QSAEIaeRAAIUQkmCiAACrZMiRmIhjFmxMxjFiE0ak9zU5a4RmHV6RRiXWg3QZ6UWoKXy1Wa6ZFbAAq3oLYdqTUbAN3k6O3RJ3uwZDYxjaJk8KB%2Bm7SP%2BznXXmAKyzktl6CV6u1gCqQxhxgbludA7nubiHowsYPIgPbnn2KK8law4QWOYpPtYABsb7zp%2Bi61vIOCbjIijZMe0DMMEEEQFB8anomJr9ohQ53ihaLjrm1gAOzYR%2BX5LmQYzWq2VFgDRMF0b2DEIWmSEsaObFoZOeY6jxC7fqYigBges5ibBEAXowV7FjesmZvJj5KdYACcqmfqskgtsYijoHYInHuJYhnvp8FmiZzFmQ%2B7HoVYkoEnm75qfxProH69pKCJukSXBUm%2BUxUDIeZQWWSF0rhThiD2Y50WxVpbldh5oheWABlctJg7pXJgWKTiUqeuFpJIAKMR0MUADqjQJXGFWMFVNVgEZUB%2BQ1AVOllLUhYWeW8asxiwNw8BhPc4gxY5ZUnp59GXoxMlwgirEWfNBiSjO4UKsSkhpDodDBtBBBaMEzD9fAmqzvS%2BpJd5KUpml-KCk1E6XWIkqvrdtjyqSkjiPKMQAfYwTBvKQxbK48Wzs%2B-0HZJR11XyZ2Zc1U5Q1hsPygASogcDGPAX0-Xmf16dVPnAydUBk%2BDHEhdxNP04zvhYOgQnGOGxItug-yzpKHNjRN5r1ZA6C4GoOAqhwwR2D8rZpDJ5MQ5ToiSip4Ui8E8CkJr4ja68uvGPru1vo4ja5K2AD6DTfVokBK1z14g3zs0U3mko2TTK2ZEUMTGMqMifeI-siezAOc0DIc86D51zWbjDumF1hynDse2PHifiMnPji5L0uy-LkdB9nxkgxrOBazrev2I5RuWibAsGO6uWlxXVdJ8wdtdw7Pcu33wnu1onvkT7fuaq3xOpbnYe%2BRdhcQO6bWlwqABq7EVmUKQJCzAe-QTlWHYZx1q3v2YF3m7qLafcNcDw%2B4r7KBvnfdOj8RrP1qjvN%2BAp84R2sO6G6v95RhFgMwAA4v4DGWMXBuFAXjcBEBRrB3brnDK-Ngojxhqfe2jtKwBmgCECsmRGH%2BBkN1AgtgSCaXFtpPMiVCbJW3tzNW5Dw6my-tTUufgAh0KrIERAugB6IE2ojOgqg3CrGUKQQSrZm7WAEU-ImL8SamXvOI4eYh3RC1LgAaUUUMe6j1dCkk4SQSMtIDFDS3iY6BpNYFD0oVYy2yCXoxRkFofBbNCEskgeNV%2Bt4Zr70-gg6OpdKSpDwCtBI4tyS9UQNacgSBBrQR8VAkRiTzHJPgVYfMJciSrG1gkOg-9yJuEpM0%2BwVREBpFgB1ck9hwI6W8ZnZWCSzFwIkdYfMY8Gld1bHQQZqJVRKASDoiWrZVEpA0fkEptFBGA2ETnURjULFBNEPmE%2BRIZ5qA8YqLh1p4C2AIrAVwqQZF0L2cNIhcSVZTRtKc6pUzak-yJGEGuthrR4DCTXLQBAigCjhl8sp8TTFwl0PAcMHiCCTDwJMyxFykFElDJiiMKoRIwGMDgSQgdRkkMmiDMRQKCWMHzNQokOLjB%2BmnggTxMYRkHOqp8ZkhJ4QyA4K4AEuk2RAA)

#### Code

```fsharp
module SomeModule =
    let SomeFunc () =
        if someCondition then
            let res =
                match sessionCachedNetworkData.OutgoingTransactions.TryFind currency with
                | None -> Map.empty
                | Some currencyAddresses -> currencyAddresses
            Some res
        else
            None
```
            

#### Result

```fsharp
module SomeModule =
    let SomeFunc () =
        if someCondition then
            let res =
                match sessionCachedNetworkData.OutgoingTransactions.TryFind
                          currency with
                | None -> Map.empty
                | Some currencyAddresses -> currencyAddresses

            Some res
        else
            None

```
            
#### Problem description

The line that has the "with" keyword uses an extra identation of 10 spaces, which doesn't sound right. Why 10 spaces? The indentation size is 4.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [maybe] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 02/23/2021 20:41:59 - 525c5ac303849923d72a65b88330e2bb5bee950f

```fsharp
    { config with
                MaxLineLength = 80 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
This would seem very inconsistent that the argument on the next line starts before the function name.
It is a vanity alignment from the point from the match keyword, not from the function name.
To me this is not problem and I would like to see a this first discussed in the style guides before we can act here.

**Comment by knocte** [comment]
Ah! So what happens is that fantomas is adding +4 chars from the vanity-aligned point of where the `match ` element ends, right?

I wonder if this would then be a better expected result?:

```
module SomeModule =
    let SomeFunc () =
        if someCondition then
            let res =
                match
                    sessionCachedNetworkData.OutgoingTransactions.TryFind
                        currency with
                | None -> Map.empty
                | Some currencyAddresses -> currencyAddresses

            Some res
        else
            None
```

or:

```
module SomeModule =
    let SomeFunc () =
        if someCondition then
            let res =
                match
                    sessionCachedNetworkData.OutgoingTransactions.TryFind currency
                with
                | None -> Map.empty
                | Some currencyAddresses -> currencyAddresses

            Some res
        else
            None
```

**Comment by nojaf** [comment]
Four spaces from the start of the function indeed.
The expected result mention should be based on whatever the style guide says, please open an issue there.

**Comment by knocte** [comment]
> please open an issue there.

I wanted to double check with you (and maybe @cmeeren) if the snippets look reasonable before opening an issue there.

**Comment by cmeeren** [comment]
I don't have strong opinions on this, as I find that breaking `match` statements are so ugly anyway that I always declare a local variable if it's necessary.

**Comment by cmeeren** [comment]
Though I guess the last sample with `match` and `with` on separate lines is what seems cleanest to me.

**Comment by nojaf** [comment]
I would like to remind everyone that I don't want these discussion to happen in this repository as mentioned in our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for).
For good or bad, Fantomas follows the style guides. If a style guide evolves to a point that Fantomas is not adhering to it anymore a bug can be raised. Not any sooner and nor without explicit example from the guide.
