### ISSUE TITLE
Doesn't add semi when formatting record to one line

### ISSUE THREAD

**Issue by theothornhill** [fsprojects/fantomas#1477]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAdATugdl3ANogC5gCeYAvGPjhBMGAIbTECuTBVYARrfQIrUAHmAC%2BtWpAA04KAGcSxAJY4A5vNRgA2nIZ76kACTEyAB2RpIq4jIMRjAN05tLO%2B-QAMsgQMgBJHCQcYgBlZQAvZB9fCAAWDwBdAzEY-VjjUwstaxC7DKNnAlctXViIAEY030gAWSZhABlVREbEdWIAC3zyioAmTySU6tACrLdIHlhYAh6-Qpc3MvK%2B6r9QxABbZTgCWBwAQWIAUSCAeQAzZpxojwgLzkUhgVSDUZqTcwmpmbnDBeKSzuYAAzGtDKEzCxEAAhRAXWCYRAABSYmCYmxIiEwfwExEwrme9FeAne83GOR%2Bs3BTkWpWBcXBDkh0LhCKRjVgAHdsdAmIpAo5YHyVPtcfR8YTYskXiMPJkvpTptT5QCSmhlrEAKxMqAs6Cw%2BGIxAAVTMFkwfIFOCFIuUYt1DwIT2lwzeqopVip4tpgPp5TAADZdZB9Yb2YgAMIEfnySP7eSS1iI8X3R6IIkQEn0Mn-T1Qb00tVAgMAdhDYbZxtqWx42NTYCdLt8MuJcrGiq9yp9xf95QAHBWoQaq0j43scA2mxnXbL3R3sl3fkWiur3AGAJxD6EHC7EbHxzabJgNyUzltu0kezsF7sruka4EVbzA0PD8PGjbbXYO4HTzPiO2Hz5pMd6qquJa9FUr5hru%2B6YF%2BOwzL%2BAZngB2bpMBN6gcu4EPuuvSrK%2BgTBMQZw4AAKpgZAAOrKF0U7puhQHkthhZ4X6j4BhUYIwe%2BByYLAbBBAAIogBDKNs8GngS54CK2WYsXm2E2D2EF9rEFSMq%2B9TCP4FwUZ07THM6iChJ0iLEHR8AMbqcSDLObbzlhi5QKp96cQRmk6jpDSBBcyjCGcFpMMQiLHMIZhIvI8j2pOupag5F5zleC4TO5HFrpqvgVMGvnCAASogcCYPA1m2QySXyZeObXq5uS2B5WVPuW%2BVFSV8AAHJsJsdaYJc-j7psmi6hUzHOax9WbGwBAqBJNwAGKIsexDwRRipNZBmmDq%2B7WIvAtQzXNLRLZgK3SSG0CdGiLDwQA%2Blyyg2d042pS56V5JtGk5Vu%2BUCeiZBnJgzSJuV3R2VV9AKYBE3KfVGUFOpXErC%2BAZ1A0-1MIDwPKIm3W9diA1DSNT6vbVaU5NNs3KPNiCned2LrdkX3I7EfTQWjmPYyDxCHdTtP06FF2vldN2sNiD1PQxZOYZNH2NZlW2%2BH0RFo7pABqiwwqo8CqGoYMNvZMtgLmDifPDn2K99Ah9LxasNAtwmsHF2tBHrBsQ8bptQOb8tqfh2U29p9vCCJsDEAA4iQEVRYgMVxR7wKJV7dXfGBiMB8CfQ%2BWrR00y0MJ7NAADWMLoiXJDyORoQYlGMw9fFf5MY5imw2bIHsRnnmB-QfR5WjnWIFytNwsQPLtEziBiQFOD0XFBxBDWBOYCTAb-i3MNvXLSq4V3zUBn0rVowA0ogiBmPphntIENeYtctxr83yVOVvcN%2ByzXnKztIcmds8idInAMRsN4YRNqnHeKo95Kxtr9NG4R1BEAEmoHq7QrKIB4LUBAD9yjr2fq3V%2B7c2Lpw%2BEjT%2BAgQSo3KJAA4Ek1A4EdjgZ2%2Bxwh0NCmwJEFFYAkVQaFOKjFTIpwpkuSBJDM4BhBBzKhND4I4F4Y4Vo%2Bw1BLz6tPVQc8Ez8ObNVFK5N3oQP9t3YEIJVZUL5ioe%2BjQMQ8HgEwaMsBYrqEHsPFomi5JQxqrLN%2B%2BiP49wgCCO2VCRK4yYDwIgv9cadFCGQEIDRXGCL0VYdo8BLj31CKYIgBj97lBBMHKhpxklXBcZdTABALiQHidvYRmToH0BBDnKhaTMA7F5lguJIC5CJBiNYeQC1YpaH-GIIAA)

#### Code

```fsharp


let y = 
    { actual = b
       y = x }


```
            

#### Result

```fsharp
let y = { actual = b y = x }

```
            
#### Problem description
When working on #1476, I found that fantomas doesn't handle these small offsets correctly. It should add a semi so that the code is syntactically valid.

#### Extra information

- [x] The formatted result breaks by code.
- [x] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 02/25/2021 08:33:56 - 9bc785c38d316c5e5b1bbdaeae04ed05b5ee8088

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
This actually looks like correct behavior to be honest.
`actual` and `y` need to align before the AST will see this as two record fields.
In this case `b` is a function and `y = x` is the argument.

**Comment by theothornhill** [comment]
Yeah, I see what you mean. I think we can close this.

**Comment by nojaf** [comment]
Great!
