### ISSUE TITLE
Unexpected identifier in lambda expression when using pre processor directives

### ISSUE THREAD

**Issue by theimowski** [fsprojects/fantomas#1484]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBDMAvGABQBmArgHZgD6YAtAHxgWXRYCWslAOgE49qEMAB8wAQQaN%2Bg4XJIBKGZQDEHUmAAiAUQBCAVQDiy%2BcNLElA1Ykrx1J4WN1SHpi8suDIAGnBQAzticlADm-qhgANp%2BEKCmkAAkWACeAA7IaJAclFg%2BMcKJAG646OQZUflyAAy%2BphCQAJK2NlgAyhwAXsi1dQBMlWAAuvkAvj2xA4kp6RFZOXnxCcWl5dF1YACM4-KQALK4AB4AMtmIRzYhWAAWC3UbvVUDw3Jj%2BXE7SWnlkABGsLDoW5yIolMoRNZ9bbA1qIAC2HDg6G44iw2lsAHlSCdKN0BhBSCVAk9Rtt3sDPjNMn8AUCCktQas8WAAMxQgqtVK4aCIXSIUiwPiIAAKuD4uFh2EQfFpciwfDKxJepMmFO%2B1MBbJBK3BTIALGz6hyuTy%2BQKzrAAO5S6C4QJNQqwG2cbgy4RyhWmZ7CV5yMl06Zq-4alXLMFoCGmACsBqgRu5vP5gv0qXSfBtdsoDqdXEorvxhMQiu9ysWAdm6tdWrDFXWADYY5A4ybE4gAMLoW3%2BVvcfzu9gCvMsAtFiA%2B4R%2B%2Bqq8tByv07XhpkAdgbTYTZt2cJ%2BUsHBPQRM9JLeKrLVJnmrn1Yj8gAHCvOfHTYLu0jczHd-v5F7RyWPieoBXz1DRl1gATjvY1xFILApW7WFYVwQd3ULA8lSPUsvmnGlAIZHV1g2GomUbe9mzNGF4URF032HFDizQ38MNPLCQxwhc8K2Qim0g6C%2BDIhEAUopkkJHMAxwmdDKX-M9mPnGs7l6BsmiQHJ0UoAAVPhkgAdQ4a4d2oz9D19Y8GMkpjFiA3C7lZDjiPEPhYCoeBNEQdAOHhbjEPlZCDNQozxO%2BbJcmwmSrzkDZ9UI-YDgaUhVKuGxtD3RBWiuAUsG0%2BBdJjXVHho786PJP85iC6TLyZDZo0iw4mlIDgDnRVNcCwAVtAOVJBX8fwc0HSNcp82i-PoiTitnCzWLuesqoOAAlRA4D4eAMqyvU%2BrkL8RJ-QqTJG4Kyrw5cptm%2Bb4AAOXIWEtz4TEGmg2FwhjDZhNEsAJygKdMlhch0E4VycQAMQFeCsG41SMN24C7lvQijoFeBdi%2Bn7TgBvggY8htoCuUUuW4mgLQ4TKbiezb-W2wLRpY2TTA2MCprssVknRPgTl7Jabmy1bhHW57XqmUn5nByzTAeBsorp3AGaZjhezOi6pWu277vKomCpJ4bPu%2BjhfsQZHUalUGZgF8ahfY9ZIDFiXmaweGNa1nWmrRwiMax9gpVx-HdOVwatuGsnDcp%2BRenkqaADUGV0bI7FCVnBxyz3x2Mn3%2BdKiGhes02or%2Bqh2BzcPbGyEJo-ZuOxKGgKk-MinQuEXoIvTw5NFgLBDGwVr2sQTqc0LpleuLl6E8DMyPjG-25F6Sr04RzXTl0JFoAAa10MV5%2BwfwVNacU2wBc7XyZd9vLWwz4-8zDgwrkKmV6SbTZOxALS13ksCtGx9cQZzasoHSc3EWwN1lvhFfWHvXuPN3qmVPkPSuF8DqmwANKIEQKkGKcUbBNHXhKbEuJAH6QPr5I%2BpdZi%2B2ToLAOUM64HESvCfwVwu7rFjnlDaKtJxFQAkQo2Acaam3aKETAdkQjnRaJpRAPxdgIEwXUIB9Dub9xPuTc%2B6xmQEVNuIVyIRKCZzYM6Sg7RVFNXIIKVSsBFItCat1KiSVgHSMYuA8kw8q4QGZCbOoZtvpSkoCYwo5pQi-0um-bIn8ex6XMZI4mTDtosLPntOozIg4Tw1hgo44ofjwFwO2WAXVQg3zvqcQJH4cEDTwd7Ae1i6S2KZMyNOTjNBS1wD8TAFCpZXFaMkHIhwcn705ofEuhTZg2HgJiDBrQUiYFkZE0wzJa5OLRH0rE2T0Z8HQKQSAFjj5WJGSneQzJx5OMGXwBEVtRFtKen4QYPQsj%2BD%2Bl1CIQCRhAA)

#### Code

```fsharp
let a = (fun _ -> function
    | A ->
        ()
#if DEBUG
        f()
#endif
    | B ->
        ()
)

```
            

#### Error

```fsharp
Fantomas.FormatConfig+FormatException: Parsing failed with errors: [|tmp.fsx (6,9)-(6,10) parse error Unexpected identifier in lambda expression. Expected incomplete structured construct at or before this point or other token.|]
And options: { SourceFiles = [|"tmp.fsx"|]
  ConditionalCompilationDefines = ["DEBUG"]
  ErrorSeverityOptions = { WarnLevel = 3
                           GlobalWarnAsError = false
                           WarnOff = []
                           WarnOn = []
                           WarnAsError = []
                           WarnAsWarn = [] }
  IsInteractive = false
  LightSyntax = None
  CompilingFsLib = false
  IsExe = false }
   at Fantomas.CodeFormatterImpl.parse@76-2.Invoke(FSharpParseFileResults _arg2) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 82
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 404
   at <StartupCode$FSharp-Compiler-Service>.$Service.ParseFile@457-3.Invoke(AsyncActivation`1 ctxt) in D:\workspace\_work\1\s\src\fsharp\service\service.fs:line 457
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 02/26/2021 10:32:56 - 64646841537d863ac5a27314f991228959a6532c

```fsharp
    { config with
                IndentSize = 2 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Thank you for reporting!
