### ISSUE TITLE
Splitting single-parameter unit () could be rather done at the last resort

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#1498]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwBlWXAOTwB117sEBXAG1ItwFkX2wBeehAjsALuQAWsAE6iAYs3TRRAS1joAFAEo0AeQKr1AHk6IASolHNp6ACoBPAogB8AocI-b3Iy%2BUrnMUQlEaQAZdQBzRGiY2JCqHEQ5GQBBBSVDTR0wfUyTfwsrGwcnV0F0D08tbzAxP1wzQODpAFEANRaqcPQouOjpBNxk6TTFZTUsvQMJ-IbLaztHFzcKyogvVZ9xW2Dw2H2Dw6Pjk9Ozo578UUHEXQAzFNZWbSm800KFkuXytfXqhnQkAANOAoHhLKoenhUGAANqgiCgNaQAAkoiWMMgKnQomBCOEqIAbphWMxkGh4b8wAAGEFUyAASXQSBxZBUAC9kHTfgAWfEQAC6%2BIAvtzEfyoGiMWgsTi8ciUcTSeS4RKIABGMWVSBcTAAD1C2MQoUQPSC8t%2BAA5qRKhR5RfikdqpU5MQAjfasC0eIkkskwym-ABMWp9ZEQ2BUcFY6hSohazPuhvQXLVYDuJPBtpFWqdPpdKsgHtgXtDkqV-opaYAzGWIJAyEQSAAhRB3GSIAAKmGkiVEIW9lVE0jJ2ftuYlqPRrplxdLk8VfpVgbWPLrUEbxEQrfb0mNsAA7iFoJhwUzCbAT5lBx5h6O1nbhA6PHmCQX3Z6b%2BWlwG0wBWdcGybbc2w7ABVAgnGkE8z3QC8rwmL8IAzVgswfHNHQXadCznL9fWVX8qQANkAzcW1AvcAGFWFPPBKPUPA72UGQkPTTNEDHJ8JwVbCPxLPDFwIqsqQAdlI4Cdw7LgIzdAd1xQtDKkfCBn2EV963fWdPzLfDK1VKlLXErdJKokt1FYhSOPQ8dMJ46UoFwnTBL0ldKgATiMkgUjuftpHo7BsEwVi7yspSMJfLD7KLbSFwrZc03VWk0yA4yKMQcNI2jcz5PYziVO451eK0-inLiwjfnVTVkrIxBvN8jKozMwF1xCvKwFU8U7JnByYoVMrhIqkNkqZFlRF0OxpHsAB1FRzRy1DQo8ZT2oK-Mip6krYp-Aa1nVWtquAlJpFgRR4AAEUQVgVEjXzgpHRbhGWjqwHUyV1tlXFSu2-SKrXZLdT1Bk7h2U0WgWsgpFkGb4DmtMeRtayuNswqouxT6tqEn7doA-79SZO4VD1fQQkCGQWj1Ag9zwPBEPXP8EbCmyIq6ws0YE-qscqdUSNxvULDgaR4Gh2GqXhtrnteqdUblL7Mdcjx1TE3n%2BZkeAqGYbBZOke4GX7bBoXXdVxdWt93uwNhVCulNhkC0RfK%2Bdnvvl4R1UM5KVcFrgLZUK2khkW3bsA6AJB7YhfIAfQPFQYYkSBjeRtbpfRvqnYSjzeaO3t7F0MIVEY4XY-XMXEfyhPTaTx25bTIMkvpAHM8wbPc8Y9XNZCHW9YNhL4%2BZlHusgc3WEto0bcCe2MVllzq6q%2BkG6bw1GK9oefZH-2x7k5Lg9D5QQkj6PzR7tTIv7tnJ-iqkgyGuv9TaJdm2xeBsQiAvWOLxmkd7xOT5ljGp4v-br56nSOMdQ99mRPxfuuBmS1wpHxZpiU%2Bv9z7Bj%2BoAs6sBRAAHFLDk0pvgGm6hIH-mgY9WBnU%2B44V6s6DmzsIBBhxnXb2vtmwxmgAAa2bL2dhlg8DjTIIkeipJsDNTTJZQ%2B5Cv6UM2inKuF8eb0ioIgA8zDLBHlNF8C6BN0CzQmCkZk0k27SC7lSMRJcVplw0u9RySDyprCDErekABpaIBAgYg3QEyfhuBkyphMblMxEtj6sx-jIv%2BwY3aALBpGPAEgiGixIYKMhL0gl8XnKE5Bdj070jZD0dgR0Iga1NKIKaiA3Q8CQBZfx79S6f3Lv3ax6TbGVGrLXX4kBHgqAiOgYBmQ2RdMCNYRAthYAjSKYEWmoiqkwKZnAihqTK5hLWNWGebTHi%2BSwKoQk%2B4egGK1po7EOiGKVIWuI5J8DippOoanKk1Yr5tKXqoHxoQcBungJgaisAaY9EUcoo0xzFLTI-rMyR8yz5NI8NWABbSzp50wG6dgUS84SDIPYHE%2Bp-kPUSTMiRdTCymngEmI0ZB0TsAWRk5pqC2kJgJXcHxrEYDSFYHcOOASTaWKig0q5sjfjVgYW04l0goyiHKb434pjqntVBAKbkWI8ByBpjCMRwogA)

#### Code

```fsharp
namespace SomeNs

module SomeModule =
    let ShortFunction(): Option<SomeReturnType> =
        ()
    let SomeRatherLongeeeeeeeeeeerNameForAFunction(): Option<SomeReturnType> =
        ()
    let SomeRatherEVENLongeeeeeeeerNameForAFunction(): Option<SomeReturnType> =
        ()
    let TheLooooooooooooooooooooooooooooooooooooooooooooooooooongestNameOfAll(): Option<SomeReturnType> =
        ()


```
            

#### Result

```fsharp
namespace SomeNs

module SomeModule =
    let ShortFunction () : Option<SomeReturnType> =
        ()

    let SomeRatherLongeeeeeeeeeeerNameForAFunction () : Option<SomeReturnType> =
        ()

    let SomeRatherEVENLongeeeeeeeerNameForAFunction
        ()
        : Option<SomeReturnType> =
        ()

    let TheLooooooooooooooooooooooooooooooooooooooooooooooooooongestNameOfAll
        ()
        : Option<SomeReturnType> =
        ()

```

#### Problem description

This is kinda cosmetic but I find the split done in the last 2 functions a bit funky. I understand that in the **last** case (when the char count of the line is extremely long), fantomas doesn't have any alternative, and it's fair that it separates it like this.

But the 3rd case (the function `SomeRatherEVENLongeeeeeeeerNameForAFunction`) could be split (to avoid hitting MaxLineLength) in a slightly-better-looking way:

```fsharp
namespace SomeNs

module SomeModule =
    let ShortFunction () : Option<SomeReturnType> =
        ()

    let SomeRatherLongeeeeeeeeeeerNameForAFunction () : Option<SomeReturnType> =
        ()

    let SomeRatherEVENLongeeeeeeeerNameForAFunction ()
        : Option<SomeReturnType> =
        ()

    let TheLooooooooooooooooooooooooooooooooooooooooooooooooooongestNameOfAll
        ()
        : Option<SomeReturnType> =
        ()

```

(Because splitting it like this would already not hit MaxLineLength.)

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [maybe] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 02/27/2021 10:13:49 - 20a09de8ffa27af11a0c19161991207923638736

```fsharp
    { config with
                MaxLineLength = 80
                MaxFunctionBindingWidth = 0 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
This needs a link to [a style guide](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#stylistic-features).
You are forcing your opinion via the means of a bug report and I won't have it.
Fantomas implements two style guides, nothing more, nothing less.

**Comment by knocte** [comment]
> You are forcing your opinion

Forcing my opinion? Dude read my bug report again, I said it's "kinda cosmetic".
