### ISSUE TITLE
Incorrect align close parethesis in functions

### ISSUE THREAD

**Issue by fearpa** [fsprojects/fantomas#1499]
I want align close parethesis to end line:

let createContext () =
    new Context(DbContextOptionsBuilder<Context>()
        .UseInMemoryDatabase(Guid.NewGuid().ToString())
        .Options)

but fantomas format it as

let createContext () =
    new Context(
        DbContextOptionsBuilder<Context>()
            .UseInMemoryDatabase(
            Guid.NewGuid().ToString()
        )
            .Options
    )

Thanks.

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXM0BOiAhlogMKwB2JAHjgBQCUYAvADoUQQWIDuY5VRLToARAEYCaWAPIAHLAEtKAZwBCAVwXokeADyShWAHyN2nc2AB0AVWWIAkhQCyiALaw8ATxHFCYwnZ0AOKa8JYAcrwhCvCMlgAqsADKWHgKFADmjAxmFhCWcooqDJAANOBQdliKmcqoYADaFRCgeZAAJFiesshokOlYZc2cHQBuhOjqvY3D5gAM5XkQkI5IVEkKAF7Ii0sALLNgALrDAL67LYcdXT31-VRDbe3jk9NNS2AAjBcWkE6E1AAMulEIDEJksAALR5LT4AJjmhxO5nOw1av063WmkDEsFg6Bh5jGEym9XeSzhPyJSTcCjg6EoAEEsABRCjwaQAM2B3EJFk5EzsSLOP3RRMxtz6uPxfOWzxJb0OEAAzFSRklZIRoIhVIhOR5EAAFQh4QiubCIPCyzipKbClGiq4S7HSglq4mvMlKsB7NXLDVanV6g2A2A8S3QAIOCijWCRooUa0QW2Ie2cVHmMUjZ13V3Wj2ktDkvIAVj9UAD2t1%2BoI1lkPTwkbsjlj8aUifLAvQQryyPTjqeNxdeLdTpehZmHwAbOXIJWgzWyOgAsoBMpbdAsB4k2Auz2LH2IBnOFm5UPcyP8-LPUXvQB2Wfz6sGlyuMSWnd71O9kVop3nqVL3da8J2LCwAA5H01KtgwIcgGQ7b0vzTI8BwxACoDzYDx0VD4AE4oMDRlORIPByFcVxCB3FMULAY9LkHLELxlbCFS9D5PgWb052ghcDRpVw6XxShP0Fb8D1-TN-yYwCWLHNjbw475uPnYjSIEoSEOovA7R-B0-0YyVMKA%2BSb0nWFKW41ZwRkCh4i8AB1BQoVE7txPMQ86LQ8UMJxEynhw9jYVVFTeMZPBYHUdkREQdAFEE0jtN0iT9KkwzsQGK9AsU2FfW4-5qHsTl4khcEWTcpJIQ8LAnPgFzyz2RE9P7Az0JkqBMtYsywPMT4y3ygFHE5BRqDkS1iA8FlqFkAhlGUdsdxLJqUpatK2qM%2B5Bi60DvU%2BGcBuoAAlRA4DweBavq71Gto%2BiwFPKAcz6TrTJ2jiHwO47TvgcJ1DfS0uXsEhXDqctPhu7zs181x1HQRQ4u4AAxDxKOqS14iY7bcNhSDuM%2Bjx4CcGG4ZBJG8BRxLZ2gSETS1UiAH0eBiFzwdanz2s2rKFPMvJPgIg7wtNTxpDwYF1wu6EGuWjzJJPaSNuegKuZ6zgEVnAqBcIIWRYUdcfr%2BvAAaBkHdpZta2Y26HYa0EnkeIUj0duTGgryOFlI%2BSANa10WsEJq34cQUnyY-SnqdNTdLQZpnoVN2X0ruBWMWy7mLDhSz3YKgA1BVVHSeB0gycWd2u5rUNZyH2YT8Uk%2BViA4RC9OAQRqLN3bHP2XzwvJZjhj1oyh4nZyl28ob6gRFgLAgmwKaZsQOb20770lu7u65eHOTFe6704X69Oiet7hVAZaAAGtVDD4-sGUaQKCSM0yHxX7EI%2BZCS68suz3ZrCXqxl39vdyIeD%2B11FgcM4IHaIBisNCgzl2yMnZK%2Bd8eBjbPzEsve61xP7%2BUTkrLe713YAGlECIFkEVEq4JHC33NDyHYSFUGv1uugx6HV%2B7f2dinHGI9yqCWUJCBeHxi4rVLmbcuG0v4b1ehSPm7sNiZEwOFDIv0bIOUQGIJwCAaEoLcmg1ezFRziJ-hYZUXF3aMjihkCgTcKAt0oBscxxB1AEESNZKgxAFqdjoYIt%2BwiP6iKwVXHBHxlRuyWB7WGloKCuNGKCSgGQEGWkgekGBKhXL7mlqlWOvddGc03oEtOITfaKGoYCM0Yh4CEFIAyeamQAH%2BxSe5TgnkGE6Nkno7BOSljKnriEkQOs-CYC4TrSESRPAuOoHU7Rcc%2Bjgg5NyEEKRPCYGyRIvIyph4hLZDM6hO4YB4HQJySAEzMktKWQY8wyod4hJSGkTcaikDjPoRUI4ux%2BjKARvNeoyFThAA)

#### Code

```fsharp
let createContext () =
    new Context(DbContextOptionsBuilder<Context>()
        .UseInMemoryDatabase(Guid.NewGuid().ToString())
        .Options)
```
            

#### Result

```fsharp
let createContext () =
    new Context(
        DbContextOptionsBuilder<Context>()
            .UseInMemoryDatabase(
            Guid.NewGuid().ToString()
        )
            .Options
    )

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 02/27/2021 10:24:36 - 8c8dc37bab4e8bd4a470573bf3172dc37e4a52d7

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for your interest in this project.
This request falls under the category ["What are we not looking for?"](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for).
We don't accept any stylistic features that are not based on a style guide. 
Thanks for understanding.
