### ISSUE TITLE
Exception - detect of multiple defines when define surrounds a DU member

### ISSUE THREAD

**Issue by theimowski** [fsprojects/fantomas#1503]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAgmALwA6ATiQHYQA%2BYAQmLAGZgCWl65VtYAwt0qCAxG1YARAKL0AqgHFBEAO5t0AC0UQwAW0TaARojJh1bAM4A6OYnSNSFalojaAhumhqTa82BXrNTnSMAB5gALQAfGDBAVp0APrhUcwubAA2fp4kkGZqsACuafCUAOToYGou2LhCkCKIlPBigpAANOBQZjboHADmZqhgANodEKBOEJAAJFi4g5Ac6G2jWtMAbi5p%2BchoIxNaAAzt%2B5MAko0N6ADKbABeyMcnAEwrEAC6KwC%2Bj2OvUDM4HZQRbLfbrTbbQZ7E4ARh%2BE0gAFkXMEADIcRCohq9dSg2FPA5-D5Ob4rcYIgFzNCQfSwWBpPFOcFbIHQ-ZPeFMq56NhwNKwSj4dCSRoAeWY6MoDz%2BEBSaS6RK%2B8PJTMpQJpdIZnP%2BGxZUJlYAAzNrJldsC5oIh6IhmLAyIgAAouMguXToIyMiboMjbRUk5V-aazdW0%2BmeyZTXWQ3YGgAsJqgZotVptdsxsCURmgLi65zWsGzPQF4a03t9%2B2JWlJThVqzV81DWsDkYhrINAFYE5Ak5brbb7TJqlmc4g8wW3Gxiwm5QqK0qyc3gw3NSXmdHhgaAGxdnsp-uIPhpHNmPgCsxl6DoO0l2WbWcTSsQataWsRpfUxurlt6mMnMAAdh3c1e1Te1ET0QwyBvMAZ0QP0qwDMF6w-FdtTXNs-wADiA5M%2BzTU9%2BUoaDYPgp9EIpd8oE-NDv3XNkJgAThwy18GYd0yFPbRXGgss4Lnf0FyQyiNTDGioww2EjgNbtgL3NNuW0Xl6SnA0SP4hDBIowFl1E5txP1P8YThaTd1Y9iFKUwieJ9PiH3nGtF20lDdKQ-Tf3xLtziQThRUoAAVMhMAAdVUNRiLvWynEfMBn1%2BISnKo1C9NbAzYWNEzZPwMgCkacREDSNhFPY6zyzsgSHPiqlgU4L83I3Qz42k5FglOZg-LUBpJHlRArjyMh0BC%2BBcQTWNCXUsjNNVYSQTElL3P2GFOyalFzmYNhglFXAXSvMhJGCbB7TMMxJyIhN2zGsqNIqrSqoWGrZp-erYW3ZbggAJUQOAyHgQbhrjC6ovsl9HNumbkse%2BinBhQDXo%2Br74AAOXyAwjHFU53W0AYExhUiYvIqaEsgbRCh6AqpQAMTtVx0HYvztIeuiDRhbDpLhu14EREn0gxSmyGp4quw8Z0LXY%2BIVCGsLcdisBX3%2Bab7vBxnDKY16spdTBRTIdFz1%2BsKRoBrRoul2Wg0JsHXLmp72Skv8kRRNWXA1rXzHQJGUbINGMaxpmpfxuthOJtJSZ5qm3Fp%2BnFYk9ljNth2ne19BOaD7mKdDmmPUFyoXUvIwxbYCXIF9yb-bNhWLYhg0ng5V6ADVW3oDgmkoXpdeg0ai%2BugnQbLik6shrQnnS23mvJ-JKEvE6G8aPpW-1jvgcq9Vzd7y3%2B4gJ5GuHlFxFgdBrGFfbDuOgVZ47A33iBuKbpDJLy6V54luHrmyatfloAAa3obP35sMxfKuV0B56TI1OqpCK88r5dxvi5FeFc-xPBerbBGiAlAv2tOgTMDQ6a4DymtSgqgTr4EaOBd23s-xqUuhNTuJdbrUUjqldkMNbYAGlECIGwK1dqDRzgAN0JKaU5DwHjTxsXN8pclgMyjhMJ4LMt7BC6opXIp8-zt2EcbEG0Cmx3ykU4J4KtbY3GbmkRAWVejI0uEFRA%2BhEQIAEScChgNyoL2vjpLRsD777ENDbE4kB8AFV6JQUe48iyUBuAEtw%2BR7R%2BVgF5S4E4VKCO6hAmWGjXG1VXgaQ0McfF%2BPYpQCcax0zNxIZBXBHACFnnCkktRfsxG0Nvu4nRWhDTVyfsnfhqJXT6HgC4Q8sBjrN2QagjEVT7yOKus4qBaTJEMImIaIePjxDmBcPoYxCjzBqCuJgTgKJRmRUNpfFJi95gNHgOKfhVwsDGPSXAk4hpN4%2BJFGciUIzBZkDSMwQuNTRFy0JnQ7RsynCGkfj4y5ZBeSJ1sXsqWHQ3iPAWGYcmx1BgkU%2BEAA)

#### Code

```fsharp
type A =
  | B of int
  | C

#if DEBUG
  with
    member this.GetB =
      match this with
      | B x -> x
      | _ -> failwith "shouldn't happen"
#endif

```
            

#### Error

```fsharp
System.Exception: Fantomas is trying to format the input multiple times due to the detect of multiple defines.
There is a problem with merging all the code back togheter. Please raise an issue at https://github.com/fsprojects/fantomas/issues.
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
   at Fantomas.String.merge(String a, String b) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Utils.fs:line 62
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 222
   at Microsoft.FSharp.Collections.ListModule.Reduce[T](FSharpFunc`2 reduction, FSharpList`1 list) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 234
   at Fantomas.CodeFormatterImpl.format@408-1.Invoke(Tuple`3[] _arg1) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 417
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 404
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
```
            
#### Problem description

Removing the preprocessor directive fixes the isse

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 03/03/2021 07:40:00 - e92fa7a9201c4ac7c208e8edaea87c124c2a1d40

```fsharp
    { config with
                IndentSize = 2 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Thanks for your recent reports Tomasz. I've looked at all of them and none are really trivial to solve I'm afraid.
Perhaps over time, I see more opportunities to fix the others as well.

**Comment by theimowski** [comment]
They are quite edge cases, multiple preprocessor directives probably don't help. 
On a side note, I've found these type of conditionals making code harder to maintain and strive to refactor towards getting rid of them wherever possible.
