### ISSUE TITLE
Quote character in a comment results in removing code inside preprocessor directive

### ISSUE THREAD

**Issue by theimowski** [fsprojects/fantomas#1504]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6dYA6lsCdsA7AFwE8AHRMAQTAAoBKMAXgOPaIGIBLAMzAARAKIAhAKoBxThAA2iEmACGTVg0acuiIvH6cZYeYoH0AHmh6lmbQkQgQAtkpLQAFmFNgA7jxKuDEAA%2BYAD6YAC0AHya-EJiUgH2TJqIsgDOiIkQybZaOnq2kAA04FAZJCSWAOZpqGAA2qUQoPb2kAAk5FR1kJYkxU1t7QBuSrIArshoja2tAAwls20AkjraJADKPABeyItLYABMgxAAuoMAvvvNJ1CdlFNQfQNLHaMTjzMHAIzXs5AAWSUpgAMpZECDtFU-C8foc5rdzq0roMWv97t00JAAEawWCyWGtN5jSZ1L5LQ5-IkbRAOHhwWSwIg0EjCHQAeT4YKIe1uED4YwyiMufzRRIxjxxeIJVLu71J0z5YAAzLKIJANhQlNBEKJEHxYPhEAAFJT4JQOBSIfCE2YkfCTYXI0W3DpdSW4-G29UjEmfJUAFjVUE12t1%2BsNENgXmt0CUGVWw1gccqTO99ntjqWSPsKNaYqG7p6nplrt9HzJSoArMGNVqdXqDUbxBQqPg4wmiEmUzw08GBelEE7cy7XhLi9L08SK4qDmAAGy10MNiNGgDCsnjaTXTLSmegJEN6f5gqH2ZFqLLRaxJan5YVDSVAHYl-Xw03EADadjrcewAOhXPZ1LzHa8oFvWVpwfclZgADlfMNG0jHdGSIP8ALPWYcwgPN7ALH0wKlL1IPvf05wATgQnUaD4EhrR3BwnD-TNMNabCwFwm5QIeCdiLLeUyJ%2BBYlTrRDV0QGk6QZPslQw4ccNHdFCIg-i-UrOdvl%2BETl0QGi6PwST6XxGS5xY%2BSOMU8VlMnEiBPUuFa1WJBSHZIgABV8DIAB1XxXHQ09zM4sB8Luay%2BLHOzZx%2BVVtLfGh8FgcYdEEVIeDpfTmIdVj7HYoKQrdHisWeWy1KipZviDESgVMZY%2BDc1xtGEQcNlcQ0SB8%2BAYWDAMESAkcQKUwqnlIO9IsfDSayq4FVj4HhTHZNtnENYRTAoI00jSXs0ODKteqwi98yvIbehGkqZ3Gn5Fym0wACVEDgfB4A6rrAz2tiDrwo7MWG-ozugpVvhfa67oe%2BAADlxgcH98E5ZY6IcWpg2%2BQLLMLY6HHGWRKlkcEADFDScCprTcni-sE8r4JEkHDXgAFMexvGCecDLazcM1tX0kIfE6vyUYGqzjuK1Tzpg1pvko674vNMh2XwME92evzurenKPq4wbvpO37hf%2Bud4VraqpaUGW5Z4PcIah61YfhxGAb5w7uM1jGsZ4HGeXx-BCf0knujJ%2ByKS0udICNk35ZIOmXbdxAPa939WdcdmD2tLmeB5yB7c%2Bx3JSFiLSouilKWugA1P1REsXQiCqRW-x6jP1YFzWc-RMbRfsQ4YqD6rcaSg8trL-JK%2Br5W6%2BCr7s9OnXydmQ5Ks74FBFgEhJAUFa1sQDatqH6sVbONXR6z3jS1zkWlUOSbO-p13wVERloAAa1Ec174UNJXI2C1EBQyHttkgK%2BoU-maNNYqWPrrA4hwrpBzBogLwUc9QkBjNoH2iAUqzSIL4LaNAdBfktvgW2c45L-wsoAgix0QHNzzq3CAhwgZBwANKIEQBQWq9VtCrHfpabkvICF-32sBB2Gtx7a1AVPVohxKZz1ME1OkaRXBbznLXIheUx6H1GpQ0%2BEsg5bErvIeKVRIbrC8ogbEAIEDcIOIQvh-UBENw9DZSe-tZjKmEkHGgOMqhEG7kQXuTItgeOcOMI0blYBOXWM4La-lBwj3yuOG89iRGONaMqQOBxg5Y2tEQcJwwoyVxwdDVBlgMG7kiYBKxACbFALseFChJ85zKkLhfF2XCQQWmxPAJQG5YCbUrtA2B4ISnZV3vwzOgjVF%2BzKk4juqTBBmyUNieQ0izauA2GQUgwIBnRJUVibQ8BORcI2OQeQajakHGVLPVJbJdlcn6azfAsg%2BDpyUajUhwD4k1LAUsZU59UkHPwPScOZiNlKNKKcfYvQ0i402nUOSFwgA)

#### Code

```fsharp
// "
type A () =

#if DEBUG
  let a() = ()
#endif

  let f (x: int) =
    match x with
    | _ ->
#if DEBUG
      ()
#else
      ()
#endif

```
            

#### Result

```fsharp
// "
type A() =

  #if DEBUG

  #endif

  let f (x: int) =
    match x with
    | _ ->
        #if DEBUG

        #else
        ()
#endif

```
            
#### Problem description

This one is actually quite interesting - took me a while to come up with a minimal repro. Looks like fantomas doesn't like `"` in a comment and removes code in following precompiler directives. Removing the quote fixes the issue

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 03/03/2021 07:40:00 - e92fa7a9201c4ac7c208e8edaea87c124c2a1d40

```fsharp
    { config with
                IndentSize = 2 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hey @theimowski, thank you for reporting this (and others) issue(s).
The problem here is indeed an interesting one.
For better or worse, we first scan the entire file to detect all the defines in the source code.
See
https://github.com/fsprojects/fantomas/blob/c86b187b4968421ee9ebc73ca5c07e763624d5c2/src/Fantomas/TokenParser.fs#L106-L308

In that function, we try to take hash define inside strings and comments into account.
So that we for example don't mistake
```fsharp
let s = """
#if FALSEPOSITVE
#endif
"""
```
as having defines.

The bug here will most likely but something in the sense that we assume the whole thing to be a string.
