### ISSUE TITLE
\xHH escapes in string literal are expanded

### ISSUE THREAD

**Issue by vain0x** [fsprojects/fantomas#1508]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAdS70A8AMem6AdpADThQDOiALrQJbEDmVqYA2pRKBH1ABJaATwAOyNJCa1y3PpAEA3AIYAbAK4TOc-ngr9%2BkAJLEkxWgGUGAL2T6DEACw6wAXTkBfezxcKR49ilzWQcFFQ0tLgcIAEZvA0gAWWUcABkmRFTEFloACxDomIAmPBd3fi85XgShMS1IACNYWFUCwyU1TXYo6KL4wwtEAFsGOFVYYgBBWgBRUwB5ADN04jsXCEW1GjLPeOr2-3qmlrb5Doju9bAAZn75C1FlaEQAIURF2AAnRAAFZU-lEM6IhPqd%2BLRPpodhU9r5agFJMdWncwp1IldHHcIJAHk9Xu8vplYAB3EHQZQ0EyKWDkxgTMF8CFQhzlPiVfj7M6HQJIhmoi5oHoOACsWKguOebw%2B3wAqqJxJ9yZTiNTaQx6WLNqptizdlU4dzEc1kXDwl1BVcAGxinGPSUE74AYVUFKojomVCZ0FoXwZGy2iGhbNhoXhR2NfPO5u00TAAHYbRL8dLEIlhg0QX6wFqdQZWRB2XxOdiwzyIyio%2BjYwAORN25OE93jUiagNBgshmqGqC8itmqvRACcdbxk0WtBB7qGQ2UWaZgd1MP1oe7jXLprRl1jMT0V1teKlhMGIzGGquOYXeb1HINdTLJz7m4t27ie6TY4nn2PoxaZ9j8-bMBCx8Fc7yNB8NwFGNCj6PcTDMWh5mIAAVT5hAAdQYPIswvQDgLAYtBFXXtIOjIUDBiW433rSZPlgdRTAAEUQVQGBGT850hS9%2BHzIDOwOMCoGkSN%2By3QpMT3ZIcCMRZkNybIZm1RALFyL5aEw%2BBsLFRxSkXYNly7QSghkR8oPI-gYlFSSUhMRYGBweYFWUH1PhmHBRG%2BKgqHVFsrmFXSryXG9QIRITglMsirhia1rJwAAlRA4E%2BeANK0jEAp468i1vULjJEp9oIcGIE1ihKkvgAA5dQhgzT4liMCchjYMUYjw-iuSMoZ1FURhWNWAAxL4Z3oEFkLvCKByK2s9zKr54ESbreoyQbPmGjibWgXJ-ieT8AH1iQYTT8jagyBNy4SJrEorh1i2iAWEeZPnST1UvybSMr4Xj8MIvwjIu0jJoMEobSku7lAep6GE9KqapBerGuaqKTuCwzcq6nqGD6xAVrW0bxoBq6gdfWNIDBiHntoBaMaxnHnPWvdNu270QX2w7sOR7KQvqf7Q1E59elgkmpIANTRF4mHgJhmFerMdI5kDUe58KCf5hwiiooWUn6hjvR88XTClmX3vlgicqVkyVcKoGJM1nBGNgWgAHE6DcjzEC8nyjb8j6IC%2B9qS2I9deYK8y%2BCKKyhcWzGMhecZoAAaxeAEE7oKgkIsQFECbarfNjXC9I7U6Otykjg7Mq4ihikmKsQYksbeWhSWyMbxGYuziCwnzJlMNNYc%2BRG87bAu%2BKLgOjNLmo%2Bat-gihKkmAGlEEQUQZLk7ITAzoEVjWQelJNn7S0kHnJ5DivpttxSRioXIvdjOXh%2B%2Bs37xNMvItjIobpJqwWFURBaOYaq2R1KIAaIkBAO9oj50CvpFGZ1wwQVfoDfg1xdwk0mKxZgxBtbEF1hMKwmDnLqG%2BMhWA8EgHOR8jhIe0DC6wOLvAl%2BJ9y6xmuMTaIpMeogmIBQxQRIWC91qm3JgncPRUL3g-f2RFx5ByYW-aI1xBbsKpowbeqRAQNHgMoZ0sBvIsBrnXDIYjcyZSCpzRWz98rMPkRrdhjEobKAaL-S%2BUNcgWGEOYFIRjuKfSygrOBgRsjwCWNvCwIhf6WLkQ4a4Nt2FzCCcsQxG1PiqEWJAfeT9wKMPaFPUOEBrgR3YaEz4oxKbgK8XhSgrh7BSCoP1by7BcIeCAA)

#### Code

```fsharp
"\x00"

```
            

#### Result

```fsharp
"�"

```
            
#### Problem description

Hex escapes that look like `\xHH` in string literals are expanded to the escaped characters.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 03/05/2021 14:51:06 - 69fd7ea5fc92994488b6f1fd6e6fb8dbf9313db8

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello @vain0x, thank you for reporting this issue.
I believe it can be solved by adding `x` to this regex:
https://github.com/fsprojects/fantomas/blob/ba5b44e3b2286f0a3241d3b55fbce2f31e23d55a/src/Fantomas/TokenParser.fs#L509-L510

Would you be interested in submitting a PR?

**Comment by vain0x** [comment]
Thank you. I have submitted a PR.
