### ISSUE TITLE
[Feature request] Keep function or name bound to computation expression on declaration line

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/fantomas#1526]
If you have such method
``` F#
let asyncDoSomething () = async {
    do! asyncSomething ()
    let! result = asyncGetSomething ()
    ()
}

let items = seq {
    "item1"
    "item2"
}
```

it will be reformatted into
``` F#
let asyncDoSomething () =
    async {
        do! asyncSomething ()
        let! result = asyncGetSomething ()
        ()
    }

let items =
    seq {
        "item1"
        "item2"
    }
```

Can we add an option to preserve the first formatting?

## Pros and Cons 

The advantage is the fewer spaces at the left which allows putting more visible content on the line

## Extra information

Estimated cost (XS, **S**, M, L, XL, XXL): 

## Affidavit

Please tick this by placing a cross in the box:
* [X] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md).
* [X] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [X] This is not a breaking change to Fantomas
* [ ] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Hello, thank you for your interest in this project.
This request falls under the category ["What are we not looking for?"](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for).
Thanks for understanding.
