### ISSUE TITLE
Idempotency problem when trailing comment is present

### ISSUE THREAD

**Issue by brianberns** [fsprojects/fantomas#1538]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAHATgSwHYBcAzXMAHUgFIBncsAAXOhVNKUJYHMALbFgKwDWAG3KlMpXFjxES5arUbMWrRO2XdeywSMhiJe3AAoAVAYAeATwBeB4wEpIAGnBQqifPjwcqqMAG0XCFAIEKgAEnwLdGQ0SGknQJDIMIA3AEMhAFcY-0TQgAZnUNDIAElcJAIAZWwrZCLiiAAWPLAAXUSAXwag1uTI6N84ggTG5PSsnIDGiABGHuLIAFk0swAZPEQ1xFwOfC5RmdmAJnzWjtDuxODFiKicyAAjWFghQ5LUjOzfaZnjhZKVUQAFtsHAhLBcABBfAAUQqAHlCBtcPVWhBCBk3Ocugsbh8Bg9nq93klPpMfuiwABmAFJKroNLQRAAIVUsEwiAACmlMGlge5EJhSaF8JhsjjLni%2BndBrFiW86eMvlMqU06RBIAymaz2Zy1rAAO5C6BpNzlFKwU2eSEikJiiWNC4hK6hfFkwlDBV25UUtC-RoAVg1UG1zLZhA5iAAquhophTebcJbrdhbSHMUJsU7cdcZZ75S9FTKJt9-VSAGwhrWM8N6xAAYSEZqoDchVAd0HwHLtGKxiElLulY1lRKLPvJZdyMzAAHZq2HdZHOUsQY8hb2wJns8VnRBXSF3ZrR17x0rJ6qZwAOBe1pdRtsQ3Cb7cDnNSvMjgtQb3n0uXmYAE5bx1KFCHwIU22BYE0k3B0313XM3Xze5TxJP8VUpGdZkKKkax1CMoyBUFwXTKlX0Hfdh1ub8njPEtMPLbD5jwxcwIgzBiLBV4yJneDKLAA9ei-VDC3Qhi-WnI5-jw8pKnwBFcAAFUwCwAHVsH2F9%2BwEoSwCPcJaN-CSpwDYpZlpVi7yhTBYEyCoABFECEbBQQ4uDxQQ0I90E6iCVEqB4gwySzNCWZ1TwlYzFKQglK4HZYSzRAqi4Dl8A0%2BAtJDJoznfIdPxogLhnwCd-ywo5g0i1ZykIbAzAReM0m7TBYTMLBECoKg02fENA1yxCP2QkS5UCkZgtMqlZirKqzAAJUQOBMHgDKsrVfrvKQw8UJG4rSsYqTGlmecZvmxb4AAOUyYF10wJFSgg4EfBDWZdL8j0iuBTIhE8FzUQAMQ5GCPCFJTUPGgDDpvPDTo5eAli%2Bn7NgBzAgfc6toC4XkmQ4gB9Q1sEyg5XoK-ydqCkyIfM4CZpsvkLARTANg7FaDmy9aQh8vSDP6IryZHMqmL%2BXCZ2WVZabSenGewDtLuuoU7oep7JuJobCp2z7vuwX7EGR1GQbBinysaY4WJF8XJaZ-B4c17XdaatG8IxrGuyFPGCa0lWtuGh4%2BduAWDuKY4ZJFqKADUVRZPB4C8FnNxyz3hLVn2xsNwXjcskPVj%2B%2Byu26yOKhj93WbWhP9O25OSvBo3A4izOzAc2B8AAcXcVr2s67rY969mIE5t7jyM%2Bj%2Bf20KQmOSqQ4RrXNhZCFoAEFk%2BXn9wqEUqp%2BUbV4rp68idLyqiSfenbjOHkKqWOaaRfOxBDW1tl8GNHZQeiJzatwTTuqhCpVzlzAlZnCi%2B9fKHwHkVE%2BfsR7n2OiLAA0ogRA6AYpxR2OUdeAoURogAXvAa%2BVVakwrntM%2BM5jhQzrolUEVAuBdxLkArm5c0LFlPhNYh1MRY1F2EIRANkOBXR2OlRAjwlgIEwTMQBOCD54KPmOcSTDKahGpMLGYkAoQuQ4LgbOuBc6QhqGopqmRORKVgHJPhTVuraSSqXbmJ4xKMIgUQmY1JTZKJURxXApiUhbEhBwH%2BN1X54A-u2cxO4NqDS9knBhhDmEOODko62ngMFrH5I8eAaQmywC6rsa%2Bt9NhBK8hzTaid8ERKrmnYo1IM5KIctLNIjxOHkOllwKoFgCCrFyZY%2BhsQdjwCRBgqokROGRLkSEaktclHwm6ciHJ6NMBCEIJAdp3timpwDvIieSi4EIOMQQcoi80iaOLlgixtD%2B6GTAUPOxUTGjUkvkovpOAuxCKQG02hLg2gNDiFQP6XVfAUU6EAA)

#### Formatted code

```fsharp
printfn "%s" @"c:\def\ghi\jkl"

printfn "%s" "c:\\def\\ghi\\jkl"
(*
xyz
*)


```
            

#### Reformatted code

```fsharp
printfn "%s" @"c:\def\ghi\jkl"

printfn "%s" "c:\\def\\ghi\\jkl"
(*
xyz
*)

```
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 03/25/2021 16:56:06 - 360c1f87a8835fb7a1befc66edb6495de603c4c9

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello Brian, thank you for reporting this issue.

The problem I see here is that both the new line and the comment were detected via the F# tokens yet assigned to a different AST node.

![image](https://user-images.githubusercontent.com/2621499/112600980-24a0b700-8e12-11eb-87c8-9077142abd20.png)

![image](https://user-images.githubusercontent.com/2621499/112600948-1ce11280-8e12-11eb-895b-e34f03203656.png)

Fantomas first prints the comment because it is linked after the Do expression and then prints the newline because it is linked to the anonymous module.

Are you interested in submitting a PR to solve this?

**Comment by brianberns** [comment]
Hi. That’s not something I can take on at the moment, but I do think Fantomas is very cool!
