### ISSUE TITLE
Comments are stripped at the end of a vertical list

### ISSUE THREAD

**Issue by pbiggar** [fsprojects/fantomas#1541]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzAdgM5gC8AOvhBANpjBgAepYZk6s%2BA5mIvrAK6cAFmCywwfHJ3FiwHRGHQBLfIlYUqmsAE9mAVjABfDQHoTWuhICGAWwUk8lVgGUsAJxWdWLSL3iEAdSUsIW8ABlNzCzAkAAc3RGgrLER4ZgA5WCwAEUR4xOTUo0iwAElRIRUAawqFQliraAVk2rBCLCs3HFhcVuVVYisAI1gANwUbZJS3DU0AXQpIABpwKEJsLE9CVDBqVYhQC0gAEixtWOQ0SBUsZf2qE9GrdH5L3fvNMJXoqFL8JHwWGcSgAXshvtEACwfMBze6GCEHGEnM4XHbXQF3I7HJ4vN57H4ARkRWkgAFkrAwADIqRBU3icEJY6KEgBMYRhcM0CPuh1Jp3Ob0gI1g6GZmkez1eOwJ0VZJIlzkQNiUcHY%2BAAglgAKL-ADyuBpqnFWlwz3WnPhJL5EoFaKuIrFCqgOKl%2BJhEAAzM6IJBnA0mgAhRC4WAJAAKnVs2EQbhNmncr0t3OtyLtQsd8ZduOlaFlFkhPqg-saiGDoYSVNgAHdY0l1n9RrAkpsOFmIInEMmqDzNDaHun0ZnnZK8TKPWA9EW-QGyyGw4gAKqxC5ueuIRvN5JKNtFs3oC0WLk91PY1EZ2CirOj3PvH4ANmnJaD84SAGF0FZCIQ3xx2m5%2BGgMQ4z3c0uyPK1eTTc8h0vJ00xzd0fgAdifWdywXMllSGWN2zwMDuwgXsqH7X1BwdODr1dMc8wnAAONDSww99RV3Cd90PLRjyI09%2BRgiirxHajb3zLQAE5GKaDVcGmX8bEmPDO0IoxeNtfioGHBC3XHIkvgnGcmNfRAlRVNU2J%2BDjwK4yC%2B2gwVYMErSaLvFliX059EGk6YTNVVj8EUgCrPmGySLs%2B0NMooTEJ0ll5X0v4ASwPV8AAFTcbQgiZUCDyCqhuJUqCz3sgT4OxaLaKJb13NnDU3AEf5cmUFVpgCpMIJTQq%2BOKqAbio8qXIsQlC30ikGFKXAUqEXhtRy5whDDLAgngLKJ0hDl2pPTq1O6jFbii7SKpZKcRspP5cCUBg9VXZIw21Bh8m-Hd-KLPR1usjrbKK8Ldr6g6Bq0QlHxOhgACVEjDeAlpWn41uU4ikS%2BoVev25zRM0QlUOBsG4DceB0n4GwcLcA1ShSGxtiLQk4dUgd1MgGx%2BHQTZ%2BkQAAxMNJiwaYUvslGRInQkGP07GIbJRnmdpdm3E5lrp2gIQoyA2MAH1qyUZahEgamttpnbkac-miQk4HarcKxtD1NwaXaKHNaLWGNp4nWyLp-Wyr%2BtGqHZadRtN83LetrB8cJ2MSbJimBe1z6uu%2BhmmaUFmpZl2MebRPmkLlNyfkgP2LatpR2jF%2BPE45qZcLlhWzaVtxVfVpko9CxH0Td-l%2Bs9iBWTi7PRoANTdQMVHgTxbbwh33s26Ptu%2BlvbTbidWSq7vKVZ-h8CAp6B-%2BYe67t1a3uCj7G5jpHMXTmKLFZYal4YbIsgAcWwO6HsIJ6R5e-e8pChHj4c0rW49%2Bex1u7iwTrSQM7BoBVEDFXKo2BCDJWcNGX8LwbDPXYgRR2BVJ662%2Bppd2qN55A2zukRA1YWbBiwLWXgqdEC5HOvgYIT0NT-CwiHNwEcLIYPHk7bBLsdp4P-gQn4rJMbZwANKIDyONSavA-iILsEacE6CcoN2-lPE%2Be0DYZwvkLa%2BM0VSECEG-Peqi6BhQvI5fBhs5TG2zsCLgmBaqcAJrwRaiAhhkgQEozhKjMHwzMU3Eqv0hHRE9HpbOGplCcHwCvNerZ8DAmickfgCQUqwASq47c5loiWVMaRF0dMBGzwAT8T0Wdog5yZrGfA25xhVi4KwomdCVCML-HhXJfiaZ8NwZFLR58tCei7hUoumxFFUlsEMeAVgPywBflwEhZDaTtK4QfCeR91G-2CdYiwnpF4VOyAXYYmB9EFyEM4bQgJKTLN8dwrB6ycFCj8AaRRrhtCYC2dogZV8Km6ngM8pZcs3DoFwFrTpzsCn8N6VYz5mhPRAIqRIqR-xXF-GgVYNeu8fGcVWTw%2B53SLF-2KSEnZRCKmuA8EBTxSBrnYs-tyVYcwITXEIKzF%2BOxcmGCAA)

#### Code

```fsharp
let fns =
    [ { x = "long enough to not go to one line"
        y = 5 }
 //      { name = fn "String" "endsWith" 0
 //        deprecated = NotDeprecated }
 // I think the space at the start of the lines above matter
     ]

```
            

#### Result

```fsharp
let fns =
    [ { x = "long enough to not go to one line"
        y = 5 } ]

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 03/26/2021 09:37:20 - 2cfd9aed77548318d18ba8eb2aa515851e80dfcb

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Thanks for the report, Paul!
The first one is on the house 😊.

**Comment by pbiggar** [comment]
Amazing!
