### ISSUE TITLE
Fantomas removes the format string from string interpolation

### ISSUE THREAD

**Issue by kaeedo** [fsprojects/fantomas#1549]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAHRATtIgHY4C8ADAHQCMArACwAcLAbADoEclc8DCsEgGdYmagHUCASyyIAMtJKIAFABIOkAGKwCAWwCGWOfDTB8RUlhS4ATAF9NASkgAacFGHYsSgObDUMABtDwhQCAioNSwAT3xAyCUsN1CIyDUANwN0AFdkNBDIyMp3IrSASRIkMgBlaQAvZFKysEZUiABdVPtmsPao2Pi0RLIUsvSs3Pzg-ohaXqLIAFkDAA9FZXlSXywACzGW2ltKfq7IntTwxei46cgAI1gxA8iJ7LzAwpbbBdeaxD00jg6CEAEEsABRKoAeQAZhsmrMwLDsl5Tt0FldXjchlBHs9flFJh8CkiAMyEiCQGq4AzEABCiFhukQAAUDAQDHpsIQXkUsAQ8ujzpj%2BulBnd8eg%2BVTMu9pl8yoxKVAaXTEIzmQQFLAAO6EaAGLyVDKwQ0%2BIQyiICoVlM4RC6RLFpHGSp7SwlvKafJH0FXU2kMpksgCquAshuNJFN5uklpVKPQaLtGMuYtdCSlVq9JJmLTAbH9aqDWsQ-HQRuEghENugWF0VogieTRXtEEdEWdsolmfd2bl3tJ%2BYA7EXAxrg9qlgD7ryE6jEMKHaLxhnhlnPQPc4qiswx%2BrNSzBCCSI3kQul%2B2V9ce%2Bu%2B5viQqkQBOffEUGwuQEQR6Qxnm2LimIppqut54ve6aPj6%2Ba0CUSIBgek6IP8gLAvGSLNoBrapk66ZgQ8EGrlBQ6HPM8HFogH5fihQJiOh%2BYAZeYAdn0oG3L2BKQfK0GHD88GVNUWDQiQAAqBAxBIsj7POSZYZEbbMde2L4RuXGDnmhwUuR46ggQsA5FUAAiiDoNIgJfv%2BgpyRECksWAXYDOxwxJP2xEaWUtDKvBKyrOUsIibspAQrJNS7LoWCSfAexnowJxAcuIE3k5UAuQ%2B3EkR5freWslSwtIqzQhYRi6BCqy4NqwjCHGp4qvQcXYcBuFsbiIzJGl6k7pEtCFtlqwAEqIHABDwJF0UqrFTF2Q54rJa1rnpe5RS0KOvUDUN8AAHI5Hos4EHC5RyHoAQqrQk1KS6%2BF6Dk6A%2BKZyg6PoRhfiJ7HtduSK0Hu8Frbo8BLNdt1KIgD2GMYc7wdAuwcnSX4APq6tIUX7GdiXKbNqVqe9MGvr1umcjE0IEIowgRYjY1IhN8VXqjF3o6Mb1Pvmxz%2Bj5eMGATRPSCTW07YQ%2B2HcdH0o01SUtVdN3SHdwO6KDz2vZjjPfGR%2BaQGzHPE1g-0S1LINPeDKuQ9DdaEPDZPI1Tik092dNtQrPFlLYfEqz5ABq8r0ko8B%2BKN0kU-V8k4Z2eE2-NHVIrYWnO2sWgGXW1Ue1U3tmzF-s2YHrGi3cGNEQtnURLYXlR6shmwFgADi2CleViCVdVPtnnVwtB81bqcTnYdM1lzsA5LQP0iC0AANb0pyQ-YMIwk1FyZZiNtNUYReFtTcHLWqe3WPfD1KsbYgupS4yWD6qQL34MZeUkLI1WglU068wQgv5phTcZ2jq%2BEdcbl5xAtgrSrADSiBEC4D8gFUglQp7cgRGeJ%2BS9zrWxatnD%2Budw5fSLsFQEwhdj13GqnTo6d7Ir1bh6O2GUii2BxirOoJBfCYF0r4baVgJCIHuEsBAiJH6LwaglEWr8iGhw3mUMkcEVaglMr4EgMcSBxyEHUcRRgcjahErAASVgjDVWgZwgOjVm6Zw4sQ9eitBHKxaKrG6hASBqIyDqaht9dpnyUJfIQD8WgwK4dTHhtM35tyQR3FoZInYmK1j4BE8guT3HgAYcssAqrUJ3nvIGGjZLPwIS3PR-DDFFDJJHExhkuYGHuJgdBXNdg1BiGQNYiSWxaO4To3hCRSDwDhAiGosRMDpPtpkwuJioSNPhAk-00ACDoFhJAZJ001zgW8diT%2B5Iu4mIAUAlRZBKgjwMFI32HCkmwKto5Lx%2BifECMyVvExLSZB1lYUgSp1k8HnA8B0ZoiRhBaCqoEJ%2B9ggA)

#### Code

```fsharp
let percent =0.1548486

Console.WriteLine($"Formatted: {percent:p2}")
```
            

#### Result

```fsharp
let percent = 0.1548486

Console.WriteLine($"Formatted: {percent}")

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 03/27/2021 09:09:43 - 9bb8c255f314ce012c8510d02dfe2e8ee9060051

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hey Kai, thanks for reporting this issue!
