### ISSUE TITLE
Vanity alignment in destructuring in function parameters

### ISSUE THREAD

**Issue by lydell** [fsprojects/fantomas#1558]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzWsYAvADoB2EEuArmeZQ2PAIZaIDyuAkmdAJZIyWeowjAwAZyzMATlgAirRMTABVMgDdm6AUvgBZPjukyAngGVEMjX2iJzJhUrC0tOlm3gPZTtgG4RUQhEMnhFNhV1N11PQ2NZCysbOwBRUPDlV20YxHg0sKUAiiCIAFsjPhNTdUqVcvizGpwAXzAAWgA%2BQMYARkgAGnAoCWwsPjIAcwlUMABtIbEFykgAEixTAAdkNEhxrAGliFW3am25w8oABkGSyB5BLHM%2BAC9kG6CAFguAXSXm98WolW6y2M12QgOQJWJzO8xKPQBjEg%2BmYAA8ADLjRDokITLAAC0hQR6ACZLj8-ojQFCQWdIAAjAjoIkMY7aU4zOFBEmI1mWcpwdCwMgAQSw%2BU4mLIbwuVG0IwpDH%2BS2pSLWmzpjNgzN5UGh7NhsrAAGZdUdzBtmHYAEKIfAyRAABVkzFK2CsLMYWBkp0VlGVDFVrPVoJ2Wp1FzZ6A5aC5og%2BZqgFqtiFt9uxsAA7lZoMwRjwNLBc2NhZ6GN7faJfkqqZGQ5qmWW9TDOUaAKyJyDJm122AO1QbLYyXP5zRF1h8UuJ3DyxB%2BiAByhB5b1sHhptRmPnEoANk73dTvYdAGF0HmJMfhVIfdAsH2m3L0Aqq5SVXXaWvG7rN4aSgB2fdLR7dN9EQUp6Q9adZ3nMBF0BNUPzDL86xbWMjQADkAlM0z7RBLyFMgHzwaCXxrN8aQ1T9tQ3fVo1-IIAE4sLsEVcDYGRL1KUpmCIis51I-1awo0MoHXb9aK3ONemuI0uyAw9035WxtSnI0ZyffjGGrQTyIQyikOo8TUO3YkEVkg9WPYpTBVUko%2BJguCwGXI5VwMiMoWMqSGFJTt7hCLB2DIAAVMwAHVKkJKCNIcoS9JEhlkI8g1W3hU1zPkkUZFgWgwkQHRynY3ifU0hhtIXWLg0QqA9hozyjR6BNZJRVEuFwIL8RCFINPMfE%2BywcL4AJIiPnJATyt0yr9OqiEjOStD4Q7Jq0R4XA%2BFRdgh1YPsUlRDYHQkCRJ0IxM21GrTX0Dd8pvBfZZrolLiT3JbUQAJUQOAZHgAahsTEaYomlcqpu2q5pM0QegA563o%2B%2BAADlqHAqxOC4NhSmmRMen%2By7hLpUpqHQMYdGlAAxPtuKwdigsou7JPqzDZOhvsDHxwmsVJmRycKztoHxF1bysAB9TMBCGrGlyu%2BKapp%2BjwaY57MpkZhTHYGRMSkb7IqNP6xtgirAeuqWUNBrzKDJTtmoVpWVbVrB4cRmRkdR9H6rF%2BDJvivGCYqEmydYSnqaN%2B75u5Mzbkt5XVb4KR9BZ73EHZznINknm%2BfYoWRcJV2nIlulDaSoOwcYEkeWegA1A1rXGeBxgmDXhrO0qLvFnGwTztU6pKEk0tuZridoW8jsr0Ia7r36G8oMrdYBlygbb4MO%2B5Rqe7ReRYCwABxbAdr2xADqO0f23HiBJ8c5y9SBsTA9pzvFp72OidTIVoAAa2tRWX%2BwCRAvMV08O1BHjpqRIudMi2M4oNkMlfGWRcnq3FhogTMD9bRYGzCEKmWx5B2nGJUI6IpQigXts7Eo6lnwgJ0mA92ED3Lt2NkaEkkNbgAGlECIA2K1dqIQeA-zdFKGUxDgGN1Ac3cBrcZpQIeqIEk9Nl6oi6uUCQ%2BID4lG1mQ8aFD9bxUvvna%2B3I5a3CeJMTAmUJgI38qFRA9J9AID4UEEhJUJ5NzdhoqhIMC4mwgMaGSYcdATDIH3XgJYyBPF8awagDogqwD8kICctlbECIcUIpxM9rpaJoW4o0xpQ5BEgCKAmVgyATg0BmSYBCIIyEwatMgOCrxETsVnM%2BwIUmJTSTo0QxoS53y9rw9Erp6QsFPLAQ6kx4GIKxLU%2BJx9HHZxbm5VxrTGDGm7tk%2BQUdmD0kwHIqO%2BJzCmGiaicZ0UdanxzmCEI8BJRYgcKYTAczoEMGNEvbJEpcC8KIjAGQ6BcCQHqSc2Z0sJELNvtk5hrColYB4G-ZgvBNb8MOaoqe6jkmaOafPWhJRjSwOyQ4GQtgsBWKQAc0hgj-RDG%2BO8XYEhiaHRmHU5oQA)

#### Code

```fsharp
let foo =
    fun
        dateOfIncident
        { startDate = UnvalidatedMilitaryServiceStartDate unvalidatedStartDate;
          endDate = UnvalidatedMilitaryServiceEndDate unvalidatedEndDate;
          militaryUnit = militaryUnit } ->
        1
```
            

#### Result

```fsharp
let foo =
    fun dateOfIncident { startDate = UnvalidatedMilitaryServiceStartDate unvalidatedStartDate
                         endDate = UnvalidatedMilitaryServiceEndDate unvalidatedEndDate
                         militaryUnit = militaryUnit } -> 1

```
            
#### Problem description

Result violates the "avoid name-sensitive alignments" rule.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 03/31/2021 17:11:59 - 44926de35f4004f81313d31f6f54cdca339d0a5b

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
This is available in the 5.1 series.
