### ISSUE TITLE
KeepIfThenInSameLine breaks function indentation

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1559]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzWsYAFAJRgC8AOgHYQQBG6AhgBY11gA%2BAfHgK7VoWAJaxq7DnU5gAHmAC0vUpAA04KAGdsI6gHMNqMAG11EUJKgASLAE8ADsjSRh1LKtN1IlgG5N0fR2MPDgAGNQsISABJaiRXAGVhAC9kcIiAFmCwAF0PAF80syyvWwdDZ1d3Cy9ff0CTCLAARkLJSABZJhkAGRdEbsQ9LBYqiKaAJhCs3I4Cj3M263tAyHoCdFGOGr8AwwaI8dat%2BMQAW2E4dDEAQSwAUViAeVxe6lSsiFw-LWn81oWtksyk41rANkcrLVdmh9hYAMwQyLxOxMaCIABCiHwACdEAAFJjYpinbCIbGbSRYbEBX6zf7FIErUHghlQ%2BofMDpRFQZGojFY2C47qwADuZOgTC0MW8sAlIjEFI4VJpFhmdDmHABnkZ5WZishO3ZjQArNzILy0ZicYgAKp2BzYiVS6gyuWiaj6z7fRC09X06o6kHrfXbOp7DkANjNFv51oAwswNBo42INMqhILPXhvb6IBq6FrIoGoHqIaHoUFGgB2aMoy0C3HtM70MlZr7oH6qv7zBmlJnBss%2BQ3hxoADlrfKtgsQKauHu57c7kjVef9iz7uoHrOHMI5AE4J2jrrgsGSU6dTkws8qfV26T2Axug2CQ0Ow7vGk0whzzXXY9OTnOS4FQXHM7z9B912WTcX0HNkRzGFofxjY9T2xQCLjBECORvXMwHzIpH2g58WQDeCPzGQ4fxiOIsEeagABVsRsAB1YRhjbMDl27TVe2IkstzIndKzGBFkL-a5sVgAR4AAEUQdBhHONDr2pW9uPvXiiOBKAXDcODhNhSQmi5H9OhkKJcAYlhBjuDtEHiFhBSwNj4A47l0imcDV0gwEn10yoDPfESLCaU0zK6GJcGEGRHgdJgsEFO4ZDsXEk3dLNjS8jSIK0qCdIqfTt2CoyOCaKMIpkAAlRA4GxeBXPcjlPLwgiwELKx-MK19yJC4ya0qmq6vgAA5PhThbbFniiU9TgMbkmlatc-P4yBTj4dAREUt4ADFBUvLA0IY6CgorUq6CaccfyGwV4HaDatr6PbsQOlSzWgFhCVRNCAH0RWENyRiW3ztS6vSesMjkmgPSrJKJGxHmxXo00akYPOyjgV3w5bQdW8HTqNA5v0aDoujhpgEaR4Q0zGiayWm2b5qh4G8pWgr1s24RtsQZ7XrJY6ygJhCLHGJCSfJynkawe7Oe53mEren8Pq%2BoQyT%2BgGOJZgs%2BIK-HirOjlxioknzIANUNdEXHgFxdFRrMWu87GQaLMHAv1wmRbEk2uh2gQhHdS3Yhtu30a1wj8pWPWhJKw3TO9mRZNgLAAHFsGS1LEHSsQQ45LKw-anX%2B1g93hckcZwpNh6ub6dErmgABrdEiQb7ANHo%2BJiRnMFxvnDlF3UzGeO17Si9IxZevOiBxgqkmRsQEVucxLAxUGAXEHk6LqHY91rliJs6exJnGn7-OOpKVbSxLiiRYGkmAGlEEQOxLOswYYg7klXneRpcMdtqz%2BLN1IW18y5XXjnZc4GgWA50aA7HKPlWa4wKpfaOBtGjjBhiTRIehMCSV0ONQYLlED0HaAgb%2BEQT5-xxi7C%2Bglx6Q0aHCYmERIDXEUroagvtBDymoIkDhCU%2BC4gYrAGihCEoZVAvZU%2BhcYJj0BBPDkcIxYsLYWhag4jvD9DELofek0N4uG3qmTiUiqHO06rQ4uqCPaSDhMbFhMsRBf26MSeg8AmAJlgBoG2c8F59GMUuQemlh4R1kRDGOjCvYsNktTJgjBEAQOpiweINhXBdH8QPOgWN-4yKcIMeAzwv7xFsJgMJaCIhwjjiwh4%2BSXh%2BPetidAuBIDSJHqE4BfUOBwgriwh%2BT9RGuBiE3Jggg0Z9y4oE3KwS2aj1KdYzpM8WFFOxBcaWZD0mtXUNkNIzgNA7S8YYE%2BeQgA)

#### Code

```fsharp
let foo () =
    blah
    |> function
        | x -> ()
```
            

#### Result

```fsharp
let foo () =
    blah
    |> function
    | x -> ()

```
            
#### Problem description

The match here needs to be indented one place to avoid an offside error.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 03/31/2021 17:11:59 - 44926de35f4004f81313d31f6f54cdca339d0a5b

```fsharp
    { config with
                KeepIfThenInSameLine = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
`KeepIfThenInSameLine` is actually unrelated here, the problem is more centered around the combo infix operation and SynExpr.MatchLambda.
