### ISSUE TITLE
Removal of bar in one-case DU

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1563]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwAhTALwB11aAXATwNIDFZYwBeWiCAekFgAEgEsAhLz4AfcpgBOYWADMwo9PUgAacFDyJ69dQHM8qMAG1dEUHz6QAJExbnI6zTrsRHAN0wAbAFdkNCsvPgAGT3CoAEl0JA0AZVFKZGjwgBZrPgBdHIBfDLBbL0dnEKh3bRzvBz8gyrCYgEZiu0gAWUwADwAZdUQ%2BxHRjegALGpiwFoAmCNqwfLsinNKOp2ZKyAAjDn8psvqA4PNm8Nn2%2ByTEbFE4f1h0AEF6AFEEgHllAfR0xYgygC%2BkWyz4qzs63smxcaF2%2B0OGwap1CALAAGYrt4kkQSGREMpYPJEAAFBQ4AyIeSIrz0eTBUGFYpQuoVVx7WAHK6%2BE5NNGZLFQHHERD4wnEvqwADuVOgmH08R8sDlRieNLsdIZ4TBEAhfBZUBh2w5XMWPMaZzRAFZBZBhXiCUTEABVAgseRyhXoJUq0RqwVA-wg7VMtZmo3shHc44W1HTABstvtosdxIAwv55Xg0088JroPQieq%2BIHg14dWA9TZw2y4Sbi%2BaUZY0QB2JO4lPixCdW47KnFwHAxCMlbMmtbSOchsxpvnLwADnbIrFTpzj3QA7ApeHIdHYfC5Qndaj4eRfOmAE4lyRnsp6FSc9hsJhN5qd%2BXQ5Dx7CoPXo2fLWmFoojRO0OxXYkbjuB5-TRbcR3BMcDwjY8p3-XlANaNpQOTW973kKD7k5WDpjfBDdSQo5a1-E9kIAuNWkuUD4kSehPnQAAVeRGAAdVECZN3g3dEP3KijxotDTwwhjwhaTEcI7Z55FgQIEgAEUQfxRDufDX3pd87ArKsSm-bZqnQ2NmyAgVQO6HpYmUDjxhGN4g0QJJxiJeg%2BPgATBUyBZhIo0SNmotwNGneirNaG1bN6eJlFEHpPndTBC3kN4egIYk8DwP0N0FK1Ao-Pcv2QsLzKkyy5zsFpEzinoACVEDgeR4B8vz%2BWKwzP31UzXEqujpOi2S2wa5rWvgAA5QJsD7eRvlie9sDMQUWnIytKNC8TIGwQJ-CMLS-nYeRn0MKkOInCzZzRFpF1AiaiXgTp9sOwYTrO3TbWgcZyQLKkAH0pVEXzJg24yDUPH9wo8KqbqAq8GqU%2BRMEYT55AGPMOsmfzuryXrq3KnbBqOKKar4eZbTs5HUfRzH6BmuaqUW5bVtu8GtuhMK9oO0QjsQD60vwy6XGu88YlmbDpkgGm0Yx0Q8xe3n%2BcF87qW%2B36Uf%2B%2BQgZBgSOZCrniYisXMIuJjpbsgA1XkyHUeATGxzcAoNsqxOhkmkWG8mIFmeTLd6VhVILfK7YSR29ZxrrXb6omPZNuHxYuGyA56NTYHoABxAxMuy-A8qeJ3CrxiAjM51kdr-ROza8WZYst16%2BcGMhHmgABrMgtbbgw8HYpIKTXWaCrgocY8J93jVo0nvbRWZ6ulqbEClfn8XoGURhFxANMS9B%2BPy54Eh7Jn5DZ6YhJKkS3e26Gq6G6rZ7G6WAGlEEQAgHKckZ4n73Bfn%2BUj9JjxMnHMyCc77wwlvdVOrk7h4HGEXaOQVNqGwrjfKeXt77TFmIjaWKRRj%2BEQEpYws0RjeUQDsToCB-4xHPj1UqscJ6TlNOApOXh0QgWls8LSxh0BB3QCHJ4KQeFpUCMSDisAWKkLSvlQSo8kEQ36qhZh09MExHRFLGIMsDpUiwEYHwQwnjGCPvNbe6g965lkW5IBkMUISWURgiB4R0QW00UrIwf8%2Bg4B2PATAGZYB5VGIvZegxLFljoZfBh19J6SRYTXOw6J-aaLUgrTAOwCEwIVuMJIjANC9FCQZfG9Dx5RNcCMeA3w-5JCYAQyKM9pjohTpoj45SfghO%2BvIfwyhIDWMUXY2pqinH100S-N%2BkiNDxE7pgfhUcz5yIvsFK%2BRs0ExJUY4th89NFVPkPceglCkD5PBroXI0Q3B4FYHlcwZEChAA)

#### Code

```fsharp
namespace Baz

type Foo =
    /// Hi!
    | Bar of int
```
            

#### Result

```fsharp
namespace Baz

type Foo =
    /// Hi!
    Bar of int

```
            
#### Problem description

The code Fantomas produces here is fine, and it compiles. However, it triggers what I assume is a compiler bug: the output documentation `.xml` file does *not* contain an entry for the DU case `Bar`. This breaks our internal tests asserting that our API surfaces are documented.

Would it be out of the question to give us the ability to always have the `| Bar of int` formatting?

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 03/31/2021 17:11:59 - 44926de35f4004f81313d31f6f54cdca339d0a5b

```fsharp
    { config with
                KeepIfThenInSameLine = true }
```

*Signature file*

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
I've actually already identified another case where the pipe is always necessary (See https://github.com/fsprojects/fantomas/issues/1483).
For these kinds of scenario's, I'm in favour of always having the pipe.
I'll clarify this with the MS style guide, if they agree then I'll update Fantomas.
Otherwise, we can add this to the GR style guide and put it behind a feature flag.

**Comment by Smaug123** [comment]
(Personally I always use the pipe whether or not it's required.)

**Comment by smoothdeveloper** [comment]
@Smaug123 
> However, it triggers what I assume is a compiler bug: the output documentation .xml file does not contain an entry for the DU case Bar.

Is this reported upstream? Disregarding formatting tooling, the issue is worth bringing to attention on the compiler repository.

**Comment by Smaug123** [comment]
auduchinok beat me to it and raised https://github.com/dotnet/fsharp/issues/11488.

**Comment by auduchinok** [comment]
@Smaug123 I've been playing with xml doc edge cases while working on our tree, yeah. 🙂 I actually thought I've seen this issue being reported somewhere but couldn't find where it was!
