### ISSUE TITLE
KeepIndentInBranch not being respected?

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1569]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBLAZmARgGwEMALMAFyMQDsAdSiCABwCd1LTM7rIBBHWJ0qwDmAOi616YAIy1EeAM6JatZq3adIAMVixxlPIlJgAtonnyCQxGAC8uAgC9aWew7IUadeqrYcwXXn5BSlE9SRlKOUVaAAZIABpwKEVSYKF5VDAAbSSIUEkISAASUgBPBmQ0SDUE3PpigDcCPABXSuy6yRjEgvqASUokNgBldAdkHt6wABZOsABdOoBfSby54rKKzOq2Wt7G5rbMnKnpVYLIAFkCAA8AGVZEO6ohcj2pqQAmGLnFyRW6vkLiVyu1IHxYHh3pIDq12icpp9zjDhohjOg4HhYJRuKQAKKDADymAekWhBUwzUUv2W5yBMJBWyqEKhyKgRSacOOcwgAGY2YVhgwCNBEAAhRCYfiIAAKBCYBFMpEQTHJklITDaNP%2BdPWjLBLLV7M5RzQCN60wFUCFIvFkuld1gAHcVdACIoBg1YG7BNijRANVren96ADJPT6vrtoa2bDTR1TgBWK2QG2iiVSpiIACqDAqTDdHsoXp96D9VspCkQ2tDuv2UeZOlZepN8J5YAAbCm03bM4gAMKEcz97HyQPQUj8f1gSvU4O0wF6zYGptGuNt04Adm7wvT9qzlzROBV09n1fnOsX9eX0dXsY5hw3UwAHDvbRnpSOsZRT1TzwUQwgMN6AjQoGygGMW0fblTgATjfUVuEwZUmBHYxjAIadA3-SRALAYC1mvUFb0hNcHy5M12ykbp21TXde2lVF0Uxct2zPGsgLrYEb0bUj71bGCPikBDECQlCmIxSFWNObCOPwriGR4iC7ygiiEw%2BJFaIGIZSEJSgABUmFKAB1dA3grP85IIsBQPZJTwRU%2BsBMo04pH5Wie24JhYBaQYABE5HQdEUKwzUcPoPDrNsjZiKqGp%2BOglyPktWjrhuPpMH0jw8SrYYiCCUz4HM9tph%2BC9ayvbjYowXYErU80CikZNUtuAZMHQG5CXzAhJyYPEbmYMx5DLH8rUTMqAIXcMl2qnZSDI5z1N6KQuxam4ACVEDgJh4EK4rTlKqyFMjez4tU%2BMGvCbc1s27b4AAORaYxjyYYk%2BmVYwMitKQjsqxTZuMFo8EEPBHm0JgMNSFV9OIuqLqo19aNu-h4EuIGQbB-hIZClNoCIeURRQgB9J10CKohIF%2B6aiKZGr5rhp9lvgtavIVUpCSYB4xz2imrUO8rOL%2Bk7ZrOpzEqWgpvhTNLWYIdnOfQMdHuelU3o%2Br6qKpkCZtpyBAeB9BQcicHseh2HzsZyXhNo2X5a50g0YNo3EBNnqcdovGCYnFUSbJt4tcIqrddF4FFsu%2BhPk004rluAA1R8xVYeBhB56d%2Bcmy9qaDsEQ4ZMP20%2Bdzo7SzRfInEbE8GFO-d5kqJtwqbtZpnPaotwTek%2BFLi9uPzYFIABxQx%2BsG8wRtTsb64ixvA-%2B3XILF%2BqC%2Ba4v0cNx4xSxaAAGsxQVbfDHkPThkVAdISe0a2MsgX5KFsD7Pn0PxfDiBPlW6P7sQJ1nYlUgXSoGGKgBXapQMyI1uCDEPCrJgGtTjsWvlFHWK4%2BJtySh3a60cADSiBEAMAyllKgAxj6mFJBMS%2BVYA42UQdsXOkZ86nE%2BIjbuNwcronkEQcedcKHRXAg5ZBC94b0OZtHUYIQDBeSEE9KgpBjKIBwJcBApDYFXwzhVLOs8kHNn4ZbSQvIaLR24KDIQlBS6UHLtiUYRieotCzPpWA2kpE9RGr%2Bch8Djp31mg-POT92y8mtvo4GKpKCOIaE8bEQhIEvSAawUBo5nFzhUYLNRws56OUfovU4vIo5TCuKvEhdxFQ4HgAQQcsBhohA-l-R4cTwoQEim4uyHjUlePSVMXkRdsl%2BUVgQfAiAWGKyIMMUobBbjVK4VQqoVB4DEhIcMMoBgFreIyV3bJBIpkkiqbjJgeBMCU1cbfBpKS%2BFpIEa05e2SsE4PsWwAYu8CCmNrjJMKYzm4kU0cc7R9BeRv2ybMlgE55FIFGfApI8xJjVHkJoYamR2JLCAA)

#### Code

```fsharp
if blah then
    printfn "Aborting."
    1
else

printfn "Foo"
let message = baz
if baz then
    printfn "Aborting."
    1
else
0
```
            

#### Result

```fsharp
if blah then
    printfn "Aborting."
    1
else

    printfn "Foo"
    let message = baz

    if baz then
        printfn "Aborting."
        1
    else
        0

```
            
#### Problem description

I'm not sure what I'm missing here - there certainly seem to be tests covering very similar situations. I expected the source to remain essentially unchanged (certainly no indentation changes).

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 03/31/2021 17:11:59 - 44926de35f4004f81313d31f6f54cdca339d0a5b

```fsharp
    { config with
                KeepIndentInBranch = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by Smaug123** [comment]
Another example:

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzWsYAvADoB2EEARgIYBO5lYAPgHxgAyAlgM5YB0uLuiyI6YABS4ArhS5gAtK0ZNKXXHhroeiMFgAWiMitWrcWnSdWJticlaaYcAW2JgAjtOkAPB5U8%2B-ADK0tDQiDw8YABk0WA8sM7Y%2BlxkAOYAorZWAJSQADTgUDpYWKlpPKhgANpFEKCmkAAkWACeAA7IaJCpWAV1lM0AblrSXTUDTAAMhaYQkACSZEhkWEFcAF7Is3MALJNgALoDAL479QfNbZ1VPav9jU0j6GNVtXNgAIznqpAAsjRvNwyIgOEY0gYHnNPgAmKYHY5MM4DBq-FodcaQKgEdBQpjDUbjd5zGE-fFBRDOLhwdCwMgAQSwGWWAHlcMDtgcIOZbAjTj9Ufj0TdutjYLiyVAnoS3lywABmSXzILtGjhABCiHwdEQAAV6DQkqI6HjVFg6GM%2BUiBZdhZixRLbc9XmhiaZdkqoCq1YhNdrQbAAO5iaA0HRLIawUNlOmmpjmy2mRGUZFMQWDO23B1xqXOolygCsnsg3o1WtgOoAqu1OnRQ%2BGyJHo1xY56eTorSmbY9rvacTmCS98x8AGzF0u%2B8s6gDC6DDPGndL4FugWArOe5FkQnYgqco6fmmdF-clg5dEw%2BAHZx6qy-6-pSqGIN5peUn%2BSjbb2syenTLXXKAAcN4%2Bn6FaIIutJkC%2B7bbu%2B1qfj2GI-uKA7SkOsofAAnCB4T0rgxqLs4zg0C%2BCZwaoya7t2aLfseqGnuh55uqonwzHKJa3pO-oUlSNKtnKsE7mAe4XEhIpQNmjF5ph0LfBxE74cavHUuKAkfORwmiWAB5SnRkm-o8MkAR8sLFksKxYCyZAACp0K0ADqXCQm2W5aTRQr6VihlosZF7QoqClcfSdCwLI8AACI2FwVLGmRFoUUwVEiR5GZeb0aF%2BSxTCfB6HEAt4Cy4DZhhkFkOhBPoFZYE58AuXKuzwvBXaIbRyHdBl0n-v5pifEW%2BWAksQjeCytY0GudAZN47Q6pELbQZ6BZNZRH5pl%2B7VQJ1f4YSZ0JjgN3gAEqIHAdDwLV9UfI17mtZ5G13H0XU7T1rHXgdx2nfAABy0jOE%2BdBsgsojOJUnqfDda3iZizjSCIwipIgABiFYkaUYg2chT3MXKnzARxH0VvAfyw2U6AI8jdCo3FxbQPoBqrmIAD6gZcHV%2BiQBD%2B7rRJD2Zd12WUJ8OEHSFdA0K0LJ0NwfAXeznrXc11G3Wl91bUZ-NynCxYFaL4uS9LWA-X9YiA8DoM45zYltTzMNw2TIIU1T6OY9t2MfDC8kfJAusS1LvBYMTdvkyj43UxxtP08azOs5Cls6dzmJq75Gvu6SB0AGqEuqqTwOUssvgrK0IZD1uJ-cWPDiSgVewViOyKu83Z8secx3LDXLUlq1c1DtxJ0KWWa3lNeAhFsBYAA4tgU0zREPDzfni0d5QyXabpVz3VJruV6YML9TXJPwyC6q0tAADW6pi2f2A8NZQSGhB4q-QtgluYrKXK4eXmb%2Brz0CxAML7S9l9RAgZ7aTiwMGIwGNOhRSEGQZy816TLAfMbOg5sPhCTfqvBOKFHQ-zdiSN6XsADSiBEDtCKiVIwSw75JA5DBV%2BRcWolzujzPuGYB7uzxsPbwWQqQ8H0Avducc15HgMgxLeskd7Cy9usdImAQppF%2BkYGqiAqB-AQJyDBjDO7F27qXXBfNf5ynlOxL29IyZpDIHXMgDc6TrCseNaQOobKwAsio8a80GFviYUrFhKsebf2TsYj48pPZzG9iIMQZBPFDADOkFB-1YGpAQUubxHYsGpU-hvHy-cU5zHlGnfecMOQcENFQeANBZywDnukYBoCEbpMSsvLuVtWF9gkfg7eqh5TVwiRFXgNAqCYD4bwfQQRWirEBE0kRODuhGHgGyDkQQ2iYCMQQ0w8oh4ROZIs9kjSaZ0HQLgDmmSP56RyZ04JGyel7wiaQ8h7jVhLAvjQWxbcNIJVmT3eieDrndKYPKQBESVl0GpAHTRMysFFEODsHoPBEZzyqEJE4QA)


#### Code

```fsharp
let foo =
    bar
    |> List.filter (fun i ->
        if false then
            false
        else

        let m = quux
        quux.Success && somethingElse
    )
```
            

#### Result

```fsharp
let foo =
    bar
    |> List.filter
        (fun i ->
            if false then
                false
            else

                let m = quux
                quux.Success && somethingElse)

```

**Comment by Smaug123** [comment]
And this one (a couple of examples in here):

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbW0DWZM4EsA7AcwHkAjAKzAAoAzAVyLoEowBaAPgB0WIwBemCKwALmDEALYiUlTERPgJVgADgCdiY%2Bix6R9ygUYgBbAIZjoUsIg0bYGsAHcC0k2AA%2BYAMqxTiLb2jpy8-KqCwvSwsPKKbB4q0rIJ4ar05ugAzoge3gBysESB3HweFlY26ARZYgCMADR4NWIATE3VtQDMLm5SeWAA2gC6TSNjw6GJArWM9MK0rNMQYhqMuWne40OjYAD6U2kqpo6IPmJzC0tHAqvrAwelNxAe8LAAsqcAKjKkWakqDLZDasSANcBQHJiMSyLKoIYQiCgCKQAAkYgAnmpkGhINowYiBGiAG6ZdbwwaElQABnBEQgkAAkkQkEQxD4CAAvZB0%2BkAFipYGGhIAvrykYK0ZjsfC8WyCSjUaT0OS0JT6WBGoKGe9zAAPAAyxEQBsUJGkCvpdVa1MFwpUYsJyNUUqxOKgFBi6EtKhJZPd6vp7W1UB8iFMBDgmCIAEExABRFlkehG4o%2B9KZHJ20XisDO33ot2yz2wb25hlK-0UkNdctEnxqczQRAAIUQ0Q0iAACuYNOYAmI7OmkmtENmHbn80TCzLcSWy5LKyqAyG%2BXWGQ2m6326cDbBnHZoOYcsziVhLAQisPbqPxwJHSopxXpe7IPPr37l9WNQBWdehxtmzbDtEAAVTUbENCPE8iDPI8YSvf8gSzCJ7XvSdFxfYsvQ-JdVQRDUADZ-0gTcgJ3TsAGF0GPLJKKKWo1mgMRHGvCBkLHVCcydTCiznHC60-fDAwiAB2EiyO3ED3nDCghyQzNONUNCIAfAQnygGdX3fQS8JXDUAA4JMAqTTno6M2LADi71UjDFSw-jS1w5VhJDABOYytxjehBw0ejTAsSy7iUlQVLANSJXsviPQExcXP0q1aRDUiTOA04wwjKNEJDayuInHiotnGKnN0%2BLvytLUNRSryfLsDLI1LbKNWCmzwrsl0tOwkq4qrNUQ2tEjmVZMQyCIL4NAxAB1PpLNy5TuMfXiirfWLFTKvqNTqWtkskmMHGYeAABFEGqCNfKC288vQgqOocqB8VK3qCKtNdkt1PVGXoH5FHjYEfCkRwxGm%2BALX-PlbSu2yboLO65TEZynpE1Q6j-N79WZegCD1MhIMsRx4z1TRECyLJLyISyfwh%2Bb8sWwrXwenqvw2q1iLRvUACVEDgDR4GB0HVyp0KFvUpb6flR6meeiI6nEtnOe5%2BB8kYUw5I0ZNGUHUw4X-OpWoivNRdlUxGHQGFqmKAAxRwKl8r4iwl1zNqM5L5cceB3hNs3jStjQbfk5LrF7JtfL2VwQakSA9famHorhhHJaRlQ6g8tm9r7DEyA0I1aj5iOwcFgQwv1jTXWWhm1sRkMbRI960-MDOs5aJWVbsdXNe1-qo%2Bh6dYeN02CHNxAfb9jQ7ZlB2EoiVpKvpSA64b7OxA9-vB%2BHyxzpIwO%2B2YuxQ4IcPI8htru%2BfWPy469apdUVpgyq96ADV-RbYh4FkXPLPBrvadus-xcZx2gzbTvvqC2zBmJk2fiyN%2B%2B9%2BYak-kfYuhtcTnwLJfROAhWivWAXqQ64gADiiAEyE07CTMm79-yUy-iLOmXUFwVwTlXVGd9PYD2NC2fA2AWzb2wIQrIo0fD9kQOZZW5MFLAioZFH%2By0dL-0ntfVmVV8iIGcIPNsYgDyKDHogY6mMiBuDJjGFkMkW4aA7hqOaQsabUKkdpVaF9K4alaLLKqABpRAiA1CfW%2BkQZkAiAiph5DlRSEiDY0OQX-ehACp7O2wb9CMWQpDkIFiEkunVHJ0PsQwxxKcqoclIOgRAe0SDK0UEDRAFBPhIFmsEhB0ce6xxkZEuRKguhJSqjGaoJAiCgKIOAooHIumWEYJ2L4sAhqlIvE1ekFjC7C0kTHaRdjUEOPpF0GeKIOm%2BSIBeYkJoigkGMarHRxB9EMWqeI2pJ9NKw0aZkqJqgui31nsvGEASDT9goPAcw1FYCk1IEolRxpzkoWptdb%2BCzbHdSaeVCIXQgGz0OjUcwFAClxJqFIHwGI2T6mBSFWZVj5n1OWooeAyYAnnAxAU%2BO9yWlYNnomUlKYgWbw0Ogegh9QVQ3BUSyFGTllZNWUw2ebiPHjLZMyLh5hel5xDC1S53LT6LKhXc5pAgugKNnucLQzFKmBPMTUzl4UISjAhHiLIFtSbwmsiKIAA)


#### Code

```fsharp
lock lockingObj (fun () ->
    if not thing then
        printfn ""
    
    match error with
    | Some error ->
        if foo then ()
        thing ()
        false
    | None ->

    match list1, list2, list3 with
    | [], [], [] ->
        stuff ()
        true
    | [], [], _ ->
        moreStuff ()
        true
    | _ ->
        
    doMoreThings ()
    false
)
```
            

#### Result

```fsharp
lock
    lockingObj
    (fun () ->
        if not thing then printfn ""

        match error with
        | Some error ->
            if foo then ()
            thing ()
            false
        | None ->

            match list1, list2, list3 with
            | [], [], [] ->
                stuff ()
                true
            | [], [], _ ->
                moreStuff ()
                true
            | _ ->

                doMoreThings ()
                false)

```

**Comment by Smaug123** [comment]
And:

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAYrLGABQCUYAvADoB2EEAlreogE4BmAhtHgJIARRgGdssYVwBGAGzwB3RugAWdBmrCwAbuzaMkYAPoGAdENHi85KqvW3GHMLVjowMrkrDLEtG7b%2BkyX38wRGlhRDog-3Q2TCjgiBi4%2BgTg6FkuWgBVbAD4hIVlfOCAHzAUAH4wPgB5AFEAD15sdEZYegBaAD5i1LAOIjyUgsUPRCawbt6-AaJickgAGnAocPRW2gBzYVQwAG0ViFBbSAASLFxdyGZ0JcOGM80uaQBXZDQD-wAGZf9IPloSBYAGVGAAvZC-PwAFnuEAAuvcAL5Qo5wqDnHDvKA3O4nU5PV7Yz5%2BACMqPUkAAslwGgAZZiIOneTbKPFkgBMX3RiLUKPux0pmMuaEgkiI0nZakezzeuxJtg5FOlwMQAFtGHBpO0AILoOqAmocBm0SHoiDcMKIHnIimC6XC7FiiVSh4E2XE81gADMyoewOwPEQACFEAM2IgAApcNhcNWIVhsV1qGJvG18u3os4XJ3i2CSv0yonyr3Qv0QSABoOh8NM2BydjQLjhAGaWBN1rtZMMVPW2y8hj8tT2t05q55gtZ93Fj5egCs5agVd4NdgEZyuDYTZbtDbHbatG7Fue4XTg8z%2BLHoon3aLctn-gAbIvK4GV2G14gAMLSZvCL-tMIqbQOga5Hv0J59uoA4QEODAjhWjrji6hbTve%2BxegA7C%2By4hh%2BEZUuqkjsOBlqnv2toClOV5QDeqGEuhCrqAAHDhb54bWAHaoei5kVBagwWAcFopeWLIfmt5oZ6-gAJxsUGOocImAFqmqXDgb2Z6wReQo0c6En0R6Jb%2BKSPxeq%2B1b4YgqoalqXa8ZBWlCTpDp6XRU4MdJZLkuZuGKYmNmavm9leppFEZlRokirRKEeUZD6ci%2BAJAugNS0AAKrEADqoykY54XnpFulidesX4p5xlkr6vnsTqbCwC8gICKEjAaomGlsGmBXaUVrklTiLCSRVCW2KSZbmTSDR8Bw6VKN4dRWsCShrugOXwGyi7Qty3XOb1o79dcg2GTOGEmQuE20gCHCMA0NSblwoFsI02ARsIwgHuBc7bdBlHDtRB24sdjFeqSz4XQ0ABKiBwGw8BrRtpbfQJv3wf90WHbcQNeaN2Hg1DMPwAAci8arEWwRp8Kwao7IupJOcJYAIRielqi80itNIjKEGwanrOw6ViVjlWjax5n42u8BUmzHNc2uvPtS%2B0BKDGPCJgYCjrUokD0y5%2B3o4DcUnUxaiknJ4N1bGmA1GwDJAfDWubUjDCCQzTPZgDR2G8D-hci%2Bk0W1wVs2yI6DE6T7AU1TNMgzre2ISz0uMJzprc-L-OC172PqByPl-AHQe2%2BgUvs0nss8w9CvmUrKsgew6t6Gysd-VFToG%2BV8WnX4HJKuDABqHrBsw8DMJs9vgVtTeoy3Vxt0Kw2d4q1V-JN%2BCNSBB6D4CI9j47k8icV%2Bue%2B3Rtehy43L7SAjOAA4gmz2ve97Q7-OTsIij%2B99ej7nH97Xfncvidk4hm1NAAA1sGWMYCEzCDSsCOM358wkx4l6Pie9GZo1zGVOeHdjYMA5GDP4hNEByCAaGdADZvAC1wM1a6tBFAHh1ICQi4c2DR38KgnarsMHiUnD-LOagOS4z%2BAAaUQIgbA01ZreABHA%2BMJozTsPyj9CKzcD6tyPtgk%2BPtRYXwaAtDUwglDP38BPThut44HW-po3%2BiozZ-FBFsWQdVNgk28KtRAkgqQIAUTMJRyMVFTzUTwoaOCvTejMnnTmmxaCr1oOvdooJokPReBGdKsBkpuIeh9ByVo0FuyQqVAymdhbqG9LnPwkAdTs3YLQLJ2g6TtE2MwsmNDmD0MAnlXJZi47M0sVgh089cEQG9D3ABJd5F0jjJIeAXAfziBHkQkhjJOnkWUYVVRn9MFFL4SUtQ3ol4VLMFIWQ%2BiRBKGBJgFgtIVn8Wdu-dB09RTeHgEaeRwIsCyBCVovw3pz4VINC840yzFZsGkBwbW3SNl6y2bw6x-CGDen-hU0R4iMksABBAzISsbl5O4YU2FAzQn%2BG9AQip7zdAgS8UgHFnCVjwihNcYQ%2BB3q7FQUiIAA)


#### Code

```fsharp
type Foo () =
    interface IDisposable with
        override __.Dispose () =
            if not blah then
                ()
            else

            try
                try
                    cleanUp ()
                with
                | :? IOException ->
                    foo ()
            with exc ->
                foooo ()
```
            

#### Result

```fsharp
type Foo() =
    interface IDisposable with
        override __.Dispose() =
            if not blah then
                ()
            else

                try
                    try
                        cleanUp ()
                    with :? IOException -> foo ()
                with exc -> foooo ()

```

**Comment by Smaug123** [comment]
Another example:

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYrLGALwA6AdlRBHgC5joCGAlpWABTMBOA5gGcwaAPoBKMjVrSGYegAt2fAIxkuYqdIgAHHu3oAzDuUgmqmrS3rR5YdgPo8s0eq1iUhAd1YKL0gD5gAKI8PLA8YPgAtAB8flo6epSGxqamHAlaAEzxEIEA8gDWXApKADR2Ho7Oru4CErHmGQk4sHwAdAAybQCSlAbhVm6UnGaQGs2WzNa2AMqw6IillB0DJLyCYN6%2BkwFgACI8AJ4ASliUALIIiO2HR2CNu5m6%2BkZgY7laAAyfgXdnl2u7QA6ksHnFqE8IAAVRQrdqIAAeiGgWHoiE%2B0gARrxMbQcQAvPEQTjLPgVezVFzDeqfL6QMrgKACJauFYCVBgADaTIgoASkAAJPQjtpkGhIPoGbzaEKAG7MHBYcXcmXSL6MzJQPpIZKzVgE5CazIAFjVYAAujKAL7GvnmoUisWcyXJaUCwUKpUqnla5R2rSQC7MRGddiITqIFYKd2ZZRZL7mq3SW0y-mB4WilWQLHEHCx6TyxXKzm%2BzJZAOF2aIdCsOCtSgAQXoQUo8HyBjDlCN5ogBkVLKTNoD6cLmedEtzsHzlagnuLPt7YAAzLOIJBZtpmNBEAAhRADHiIAAKvGYi3RPALWmqiCHKZHDvH2anM6fXpLaDLCRNa6gm%2B3PcD3CCNYE8RAeGgZgWT6OVYCg2pKGvaRb3vWhU2kUdZWfF1X2QucP0XLUAFY-w3Lcd33Q9EAAVW0MVIOgxBYPg6ZhnwvsBzvBJk3Qx8PSdF883wotvVLJcADYyIAyjgKPABhHBoIEeS6ipehwg4sB%2BxwQceOHNMn0E3DhNnUTP1VLUAHZpIooDqIuGssQgrSdL0rReIgDDaCw9ccMnUz3wXcStQADlswCqJA1SG1cri0K8-iM2MgLpxE%2BcxK-JcAE4Ip3RsDEvVT0BYLTUP0h9DIErMTLSsyMos78tGUDUl3IyK5MQata3rdw4t07iPIMzCjJq1K3w9QiQrjf02pkxACsvbq62nPq-3KobKpG6qJygPD6qmrK-QrNqdSjeh8koaFjmBHx5H69zpE8sBvPtHahLqoLMssuNVzmuzGzCc54H2RAcFYWtLzKpxBqe4afNG3bXXodLDp%2BhJlF-Nrg0RHoDFhKMggG2Z5HCehbvgGM-xNRMKr4qrkrGqApQO4KjrjUjsZDPoDFYRF8gY6ZwiCRFdEQAQBHYv9iNpzb6e2xmkZZr7GqXZQpK5xEThRcJ4ApqmlxphKXqSscUuZt1We%2BprpGUGzNe1uAeHgAA5LB0GcngOx6dF0A5P9lGN16wF8udzcgdBcFccHuyIHgrEvaEaqt1W-XCtrHd1i4o9YGPEDjhOXLImwzxcCCRG8Sn7qD03sPD5XJrZ9HmtyzXAZ4ZgjnyHgwwcfX7up2W4a2hH3pdBuMzRm3aATMicfbzvu97%2Bg3Y9iDvd9-21ZrhmzaZiOc7zgvpkT5OVaI8tZq1SAF67nvWAcbOcGj8Nj-oKHi-kUvLwr1gq8gHeCs95K0tufaaCQsgnWvjjAAaguXc7B4BKH7lpI2dNEq7zrvvCeY4p5LiyH9aBIYCDnGpO4BBbZkF-wNlqNBcsMFAKwSAlGKcL4QKxkQxE%2BxYD0AAOJLBFmLCWwwUHSyHrQZ6wdQ6On3vtMB7MIGc2gYfcMu5WjQEKLuDuGilgCEurMc8iAYruyQutGGgDR6Kw%2BhNSeTdp4QCyBra%2BLtECeDzvueg4EoxJzFKDXmlAfDDEbG2Rya8eBby1G5WGEj4ZvSsbVGxuC7H4PttfAA0ogRA2g8YE0oH0Axiwuw9kifFdBJtMF%2BXrqAxu1t8Hp04UTWsAh5CiMNuIiAkja6VNkYFGpqdyyt2vvqFYeBAZ8HdudUEWIrhIAetEjpsSQ6I2sajZJWplytWvo2cGfBKAkMoGQyg%2BpdnTCwEeaEsAzrJDYmtJcUSLFxOASs1h4CtDLivpkG%2Bz8IKUDYnKUCKxQmez8ewQJdQ5kPKWWPcaqzanrKgZ8p%2BrgimdHPFieAzBFKwElisFxbjwwQrKVI5ZCTYX9ISMuQhnz9gP2YFiPAjSH7yFmEca5iJCX0PKYw7pSMoztk7OGWYIo8BkrYW8jhnzWz8qKVpGAPAcAGAAUSrpYcemfT6WK6Qy4lGfIyVkq59A%2BhaOYAcgeS4NrD3lpYp5pKXkKLeU4z5Qq9AuBmcUzI9yiVMgtMaSUAgCCS05Pc60QA)


#### Code

```fsharp
module Foo =

    let main (args : _) =
        let thing1 = ()
        printfn ""

        match instructions with
        | Error e ->
            printfn ""
            2
        | Ok (thing, instructions) ->

        log.LogInformation("")
        match Something.foo args with
        | DryRunMode.Dry ->
            printfn ""
            0
        | DryRunMode.Wet ->

        Thing.execute
            bar
            baz
            (thing, instructions)
        0
```
            

#### Result

```fsharp
module Foo =

    let main (args: _) =
        let thing1 = ()
        printfn ""

        match instructions with
        | Error e ->
            printfn ""
            2
        | Ok (thing, instructions) ->

            log.LogInformation("")

            match Something.foo args with
            | DryRunMode.Dry ->
                printfn ""
                0
            | DryRunMode.Wet ->

                Thing.execute bar baz (thing, instructions)
                0

```

**Comment by nojaf** [comment]
@Smaug123 I've pushed [4.5.0-alpha-004](https://www.nuget.org/packages/fantomas-tool/4.5.0-alpha-004) for this.
