### ISSUE TITLE
Pipe character missing in single-case try/with

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1571]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXATgTwDoDsIIAKASgIHcBLdACwIB8xEAPaMAWgD4CiwzIAGnBQAzonToq%2BAOajUYANoiIoPhEgASdNgAOyNJGnohKoloBuAQwA2AVwNKzfAAzD15gJL4k%2BdAGUqAC9kdw8wABZnMABdMwBfMNVorR19BSM-Uw9LWwcFZXCwAEYk9UgAWSsWABlpRBrEWTps8OKAJhdouL5EszVy7T1HSAAjWFgbVr5c%2B0dC8Paymf9EAFsqOBtYfABBdABRHwB5ADM6-FDoiFPbcW6EsoGZofTDccnp801rOYLrsAAZmW5n8uis0EQACFEKdYJhEAAFKyYKxrCSITBfPhYBwPXpPFKvEYfKYg2b5NALDwREEaMEQ6Gw%2BENWAUTHQKzibwWWCcqQ7bFEXGIfFEPp8Z7fNIkiZkom-SlOIoAVjpUAZkJhcIRAFVdPpMJzufhefyqIL1bcbPcPD1xYScsSMqShRT5gCAGzqyCapk6xAAYRsXNEgZ2olx0HQ8KFNzuortj36RJlLrlbp%2BeQ9RQA7D6-dqWRV1qNMXGwNbbep7RAJUQpRpne8M%2BSs38qQCABwF8Fa5kI8PbfAVquJmvJyWp4bpz5txU58IATl7jN2p3QmPDazWVgrIrFdcdgzTLbnCuz-yKxTcAN9ff9LNWGy2loBY8PYHrySdp6grvnS9O2vUo7z9ddN0wZ9NkmN8igPJMCRTX8ZzPeUnQXK82iWO9vF8dBjnwAAVHAAHUaFoUcE0-b8wEbKBm3-VsLw7ZU2mBMCH12TBYDsHwABFEBsKgNkg-dMDxRCHWQk9UKgYxM0w4C2lpO8qhYTxTiI2gmgOG1EH8Wh4XQcj4BadUIi6KSjxkl4-0yExANY6l1GKNU1OqbxTioFhjkNKwY0wA4WF0BFRFEC0R3VFUrInJCpxQt55KyJylRcvhim9DyWAAJUQOBMHgUzzIBSyaOPOy5IcxSgLYjxinzbK8oK%2BAADk7DWMtMDOTxNzWeR1WKcrbOlKq1jsGwpGEy4ADF4V3SRMSImdUsXeqezvZr4XgCoJqm%2Bo5swBaxJ9aBaBRCFIIAfWoMzKOGhLZKS6rVqw%2BqV2y7jUWwY5MDqSNisoizYr4Wsvwq0bnoU17lI8TofXUr6rB%2Bv6qEjdrOsxHq%2BoGgEhus8GRqbezxsmqhpsQQ7jqWlaWLSgF2lAopICRlH-vQXayYpqmApOu8zou6NMRuqg7sgB6G2nKGUrptb1HaHDmfUgA1bMoWkeBpBkQGKzKgnaPo1Iquh2W3vljileqGa%2BOjSL1Z8LWdeBiWfyekYTYw2r0qIdpVMtlh%2BNgdAAHEJGC0LEHCyKnYBGKXboqXZXPT3nIZ9ylb28n6ihbZoAAayhVF84kURCP8NEg0mDqooBBC4ukx7KuegDTdh%2BWsuZ1rEAoCmYXQdkmmW-RBO8-AaEi3YfBLTHMFxooP31iHiaqluU-pop2ka5mAGlEEQXRNO0ppvHL9ELiuefqMXomGPsj3BiUur5Y2-29I2URaBjoo9frmzG8hpO6EH5ewZh9ZmgRZA2EQNxGQHUmgmUQKMCoCAL7hAXr-Qm-9l7N2YmvOWfBAS3mZrsYSMh8DW3wLbHYgQyEBTsAiIisA8LwICpFKi%2Bl46G0YmMXBwDU5FEBEzcILNJqYnwKwiwrJZDTy6iPaQ48IzsOrKDScktEqAJqvw8IgJFbCM5lIc%2BNQ0SjHgFYYMsAIqyC7j3eoSjxwqPimot2s4gEvEft7CAgILbCP4mjKwowoFvzRrQfw2A-DVDsZwxOGQmjwDOOffwOgoGaPXtov2wijhxPOLY06mAbCnHFtfLBt8V68LcSAgR6dhG733swvw3hC5WEoUDd8V8MEG2iWhFJ%2BCiCAg7sIxJmBNgcxQZE-WIgYhhCMKIGaEUFAfniEAA)

#### Code

```fsharp
try
    ()
with
| exc ->
    ()
```
            

#### Result

```fsharp
try
    ()
with exc -> ()

```
            
#### Problem description

This is extremely minor, but I prefer my original formatting here, and I consider it to be more consistent with https://github.com/fsprojects/fantomas/issues/1563 as well.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 04/01/2021 13:17:28 - 82615ce1a3e64176255215d19ca7af0ba79c7f5b

```fsharp
    { config with
                MultilineBlockBracketsOnSameColumn = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hey Patrick, sorry this has been dormant for a while.
I clarified this with the [F# style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-trywith-expressions).
Will take a stab at this now.
