### ISSUE TITLE
Const() stripped from string literals [bvreak

### ISSUE THREAD

**Issue by piaste** [fsprojects/fantomas#1574]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAKmALxgDKsAtovjogAoBOsAbgJZIMA8cAdgM7oAFAB1IYAQ1Y8A5mAA2rdIgYBDOWFFgA1GABKAUQCqpfQBEA%2BmAAyASXz7dAQSvnS%2BXTYByAcQCUAPigAGnAoPkR0dClpPlQwAG1QiFAIVKgAEixcOMgpdEgQtIhIdOY1AFdkNESi1IAGQtqoGx4kHnRSVgAvZEbagBYk1IBdIYBfPrAUopKsqqg8gqHi0or5mqaARkm0yABZFQAPKylEK0QZdAALJaawTYAmOuWwUbSJoendzNocgCNYLA5LcZqs5JU4htag8dqlIKREBRWHA5LAeI50PpWgB5ABmJx4vReEFxanCLzeqQ%2BaS%2BcJ%2B2TQkABQJB3zK4PWxLAAGZYcVSNgVNBEAAhRC42AMegqVRUJQMVlFdAMSoU8aTWkrOb-QHA2EldkQ6pc-p8qACoWi8WSs6wADuymgKnCLWYsCdUTRirSytVtUpEGpqU1GW1jOZepeBrWkK5AFYzfDBcKxRKpYZsLgGE6XTw3R7WF6zaS5OT-erPlH6fMmbrvRlDZy7gA2RMWlPWqUAYTkzr4XbREnK0HQkvrJLJiDV7w1VbDUAj9ejHNjdwA7G3k1a04g9oi-spx2AS2WigGwEHknPfuG6-qwUaElyAByby2pm0D1E8I8nqflmdK1qWYbwXO8q0bVcmgATjfYVHFxeUBwoCgVCPX1-zPCsaWvBkwJZe9IONO5NgaLkk3fTtEARJEUSLLk-2nKlZ2A6sdQIiCY2IrZtnI9tEAQ%2BUaORIF6LuDCmMDFjQXnWsONYoinxImFyJaNp0GxHh8AYTAAHVFBuYtJ0ki9pO%2BWTF0IrilK2Xk%2BK3RwmHKVpTEQBQkXldCVUwtJz0vKZcJrRYrJXbjak2U1yIOQ4bFxfArgufRS2oq5JXQfT4GuI9%2BmeADmKAmTQNydolwfJstgTKKjhaXFWEObEsxUUcGH0Q5sClPg%2BELH8zTjXKsMAnDWNk4LONCmzwtbKrDl0RA4AYeAMqys0cpM-yQxAvDivyELHyhIpNg3abZvm%2BBPHKCgDwYPEbCUChYjNTY1rMulZIoco5CiBRCQAMUlVDImUGhsl28rwtfciTsleA9g%2Br7Tj%2BhgAc8xNoCuGUhXlcw7XYLLnoK8yitGhTrP2tJNlg6bHNUTBsQYE4BCWwyTX63zsODQKcmJ0FFLJ1InkTaLqZUWn6dYARzsu5Qbruh6uSevKpIJ16ivez7WG%2BxBEeRoHflBqDoV4u5IGF0WGfQWH1c17WmpR8i0YxkdlGx3GbnxobCq27m2VJrkHhU43ooANTWEUpHgaImey1mRnZq9hqJkr9bCooHjswOjh%2B5yR26sPWkj13o-djmE69pOxr2v3Iozw5TFgdBvAiVr2sQTruqj3qY4gPyXq1IrLIrsHU8qwO4Y104RVRaAAGsRVUGeIj4TTSBUKgvwunqGOMxXTOVvutoHknxr5iAHim43PEQO1NbFdAHQuYHEFc2qeEUbrHFaPcpYYOW7kYnf1qc1vPJHmvs7gPCOsbAA0ogRA2BYrxQuC0FeVACREj-tvAa%2BUPaEzLjtQeBtU4QxrklJEfArgdxZsXeOnsayH1AcfP2lNjadBkHIASDBpAXQuOlRAfw9gIHQU0f%2BWClY4JVgfcCR9K53G5GRY2jgFDSB4FnHgOc0SdGUU1coUp8CwDUjwpq3VfyYLZoNEutD2KRmkUPNI3IjZNBNp9ZQPAjHMFtDIL%2BV1n5SDfoOExyVqEBVLnQqRDCZFNG5AHRxlsohoKsKvP48AVA9lgF1GQl9r6nACaeMx2CLG4NCSAn2jDZHp0caYcWKg-jsNIeLK4pBMDtCODknysdzE0MKTkC48A8RoNIFgdhpVeZcm5NXRxWJen4myajBgchcSQCCRtNiwDrHhNsakbkI9HEwLgQY9oLQ54qDUczDBgSAG91DP3MJJSIm1G5OfRxAzJAjgEUgVpa1QjDEaLkPgP0upxEYmMIAA)

#### Code

```fsharp
type T = SomeTypeProvider<const(" string literal " + REUSED_ LITERAL_STRING)> 
```
            

#### Result

```fsharp
type T = SomeTypeProvider<(" string literal " + REUSED_ LITERAL_STRING)>

```
            
#### Problem description

`const()` is a fairly obscure F# keyword that allows you to create an inline string literal by composing multiple string literals together (instead of declaring a separate `let [<Literal>] value = ...`).

It is most useful for type provider parameters, which specifically require string literals.

Fantomas deletes it, which breaks such code.

#### Extra information

- [X] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [X] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 04/01/2021 13:51:56 - a16da08ec0f6a93344cf35611bd9f93fcec3b98f

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello piaste, thanks for reporting this issue.
I had no idea this even existed.
My fix for this might be a bit naive as it is based only on this one example.
Please report any further issues you might discover.

**Comment by piaste** [comment]
Thanks, I tested it on our codebase and the issue is fixed.
