### ISSUE TITLE
Multiline type parameter arguments inside indentation

### ISSUE THREAD

**Issue by piaste** [fsprojects/fantomas#1611]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosACrLAE44CeAkgHZLUAui8YAvGADonvWfdh70wAMwCWtACoALMQHMwSAA6Jay6OTD1p1GZWZte1CFgDO%2BaOj0cuhiAEcsiEuoDKsdIgAiAQ3peARl6mAHQAwiSIPoghbuhetAA87JAGEKlp6RmmeNCC1F7uKRlFGUIkbhpaMsaFxbVgAO6SjvgiliitNUkAfPKISirUagaF5vBBAILG5IMAogAeiNBYjAAUrawVsroAlJAANOBQpvT0ssaoYADahxCgGZAAJPTkSheQYvT7N6mPAG5eOAcF2uxQADAdipAaHR6M4RAAvZAQooAFm%2BEAAut8AL7I27oqBPF7INDvBhfe4Pf6AklXAkQACMePSkAAsl45gAZMSITnKGSaClFBkAJlBBKxaVx3zuLKJr1JfmIOCFaT%2BAKBaBBRRFzLVzkQ6BEcBwsGo43oM1oAHkhNzqEj6cIAaYJTjmbK1fLaZAlbAVXrCdTNXTigBmQMQSDOBReaCIABCiCEpEQBC8JHyiEYJFV6XoJAcbqlHoJj2eCqgfoDZapGtp2oyKMjUBjccTydTnNg9Uc0ECiBov1g-dOZrzaQLRYyktS0rSnp%2B3re1YnQfrwKdAFYW9HY-GkynwgBVBRKEj90xDkc%2BETjltCF2IYtz0uUis%2B1eB9U0zfFABsu5tgenbhCEOCBMY0TUMYU45KQa4QI%2BOCujO7oyrWH4rsqa4-iGjbpAA7EB%2B4dkeiCsoafiOIhzooc%2BaElhh77Eth-q4XWv5ak6AAcJHtoeqbRKa1C0chqHpLOEDzqki5Rsuio4d%2BnH4U6ACc-HxuMQg5tE6CxLRU4MZJ6ELphrGKexynBg2ToMuCTp7gJoGIAaRomveTricZaRSWAMn4ixla%2BkptY2X%2BwpMo5wGINpOZuca-qecURkvtJb5ylhlk1pS4XccUoq7tCyj0Na1DiE4ADqIiCg%2BT5pf5GVellVahblG75cKEbRaR4xlFgtAeIgOAiEaOaGYWPmpH5AVgHJhItWSnzWR1obCs2jnsnMlBCFIygzPRziSKQ9DVfAtVOii4qMa%2BzGZRZUAfBxeVrRkDI7ptHI0KIczWuePikPMCjhMYxh3qJLZbtdJlMWZQU%2Bk9K1ca96QMoBn1zAASospDwGdF3FFdDWzfN5YPUtz2rQRaQMsRGPY3AJDwAAclg6DUSQtqUIw6DnC2DLE01S6LeguCnCNDoAGKkLEJyOOIrFI6pBV8Y5DO46yYsiBLiDSyQsvjbu0CSBmcY5gA%2BvUrSCoLd3NeTiNhVTdkaRjfWZuQ1okNysH45ItFEzd6V28LDvkkrtnFGKu5be7Xie97Iiwaz7OOFzPN83Zttw-dwWizg4s8nrBvy4rTvI9TqQilFkJxwnPv0JrBfa0XMs%2BIbjnG6bOSOJb1v%2B9nsnmcFjvtRXToirqGMAGr1gmYjwLIfsB9DvmmUP8NvKPcovZXEAit1kJbZLA05OD8%2B0Ev-cr4PgW5wj4fl8rOobUfHIeLA9AAOLZkDINg2aZekNV7TXXnfe2wUvxP0jjqD6R8tY6wTKaaAABrBMmZUHZmMGVZwWZhJswhl5eqQdGoh3kotKBY9n4ZBFOjSEzNED1EQdmXsygFZKCGqIagNVwbjFoJRVOJBM7FG8rfOaw9PxtR3s7KOdNIQAGlEB9B2ntagNBcHuHtI6ERxCYa3RzhAh%2By1oERRoarN%2BcwDpGmMJIIBl0QGYjAeIze2VKbjyjq7SEcJtB4D6jINmJVKqID8KyBA2iiiiJISTCRbEcrSPcUUMMDla4jRkNQE%2BgwxzUDhGknwWBwjiFgMVBgt5koRN0WvWGG976xLcdQ9IYYa5FEgOMAujg8inF%2BLyM0MgBEc04WIHhZphHlPomI0mClWpWRMZ1DIYYp7wOblozk%2BQ-DwC8OBWAYNtAMKYTyMSFTQFVPAaHSBUivS7ydGGQ%2BzSPBJ38HgKxSdJDOGmL4OYByxlRKFuQ8myh4C2i0c4Z4eA6kwLma-ZpVoAV2n2UbMgQhIDjJia4iOpiGlwOaYo5RAx6A0HQXEY2nyJKVP0dUwxtS0WzIaXQ5pSC4goK0cYPqsABos0QLBJgTdC4Oj-hygBMEJrTj0cHAxpzJHTKoeChpcjmnApIMaRuYTiVTUcVKQ4GJkTvGMJLMGFxRHYiAA)

#### Code

```fsharp
module PoorlyIndented = 

 let findThing dependency thingId = 
  use cmd = 
   query SomeDatabase.CreateCommand<"
                    select name
                    from things
                    where id = :id
   "> dependency

  cmd.AsyncExecute(id = thingId)
```
            

#### Result

```fsharp
module PoorlyIndented =

    let findThing dependency thingId =
        use cmd =
            query
                SomeDatabase.CreateCommand<"
                    select name
                    from things
                    where id = :id
   ">
                dependency

        cmd.AsyncExecute(id = thingId)

```
            
#### Problem description

This one is tricky and very, very niche. The sample code above is how we often write one-off queries in our functions. The `query` function is a helper that lets us pass type-safe database connection and/or transactions instead of raw strings, and the first argument is the type-provider-generated command.

Because the argument has a multi-line string literal as a type parameter, the angle brackets need to _end_ within the indentation rules for the containing declaration, or the F# compiler gets confused and doesn't compile anymore.

So now let's say the whole code tree is insufficiently indented (this actually happened). After Fantomas applies the wider indentation, the indentation requirement for the parameter increases, and the code breaks.

When we edit this code manually, we add the right amount of whitespace at the end of the query string, since placing the entire `">` in the right place looks better. Fantomas, of course, should never change the content of a string literal, so what it should do is add space between the `"` and the `>`, like this:

```fsharp
module PoorlyIndented =

    let findThing dependency thingId =
        use cmd =
            query
                SomeDatabase.CreateCommand<"
                    select name
                    from things
                    where id = :id
   "            >
                dependency

        cmd.AsyncExecute(id = thingId)

```

which is ugly but will satisfy the compiler and won't change the code semantics.

#### Extra information

- [X] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [X] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 04/05/2021 16:09:34 - 31922c00d7c6b5ef8241f5466f52f17fb55510aa

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello @piaste, thanks for reporting this issue!
This is quite the challenge at first glance.
I believe the function `indentIfNeeded` can be used to get around this problem.
https://github.com/fsprojects/fantomas/blob/31922c00d7c6b5ef8241f5466f52f17fb55510aa/src/Fantomas/Context.fs#L774

Add it to `genGenericTypeParameters`
https://github.com/fsprojects/fantomas/blob/31922c00d7c6b5ef8241f5466f52f17fb55510aa/src/Fantomas/CodePrinter.fs#L2878-L2891

so it becomes something like:
```fsharp
        !- "<"
        +> coli
            sepComma
            ts
            (fun idx ->
                genType
                    { astContext with
                          IsFirstTypeParam = idx = 0 }
                    false)
        +> indentIfNeeded sepNone
        -- ">"
```

the closing `>` won't really align with anything, but it will be indented far enough to make it compile.

Are you interested in submitting a PR for this?

**Comment by piaste** [comment]
> Are you interested in submitting a PR for this?

Yes, that should be enough guidance to get me started, thank you 🙂  I'll take a crack at it this weekend.
