### ISSUE TITLE
Some of newlines in string interpolation is deleted

### ISSUE THREAD

**Issue by vain0x** [fsprojects/fantomas#1613]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKASAOpbuB2wAjAL6YEBMpeuOO1eWt%2BAtGEVa%2BWWa8ACwcwAVm7UmdSABpwUAM6IALgoCWeAOazUYANoyIoCIYwKAngAdkaSKoVS9hyOgBuAQwA2AV0s77RgAzSRkaQAJJ4SHgKAMrKAF7IgUEQfL5gALr2xIn6qY6mFlrWkXZJjq6e3rpJEITZQZAAsi4AHgAyqoitiOoKABYl1YTkfqkZRln2BvXo%2Bd6QAEawsG4Dwc7uXlpV1eR1wVGIALbKcG6weACCCgCi4QDyAGbteAmpEA-u8qOZdVNrs4VFstVg51hUtm8wABmPYOKJmFzQRAAIUQD1gACdEAAFFwYlyHRSIDEgowKDFeb7jX65GbmOZAlawsobSqQviwiCQeGIlFozGdWAAd2J0Bc8jCTlgYpU51JhnJlKSY0MEyMf1BAKsjPlLPBaG2SSEnKgPKRqPRWIAqmYLBixRK8FKZco5SaPm4vsqfpNaVqoDrmWDNgbIQA2E3chHm-lYgDCbnFsjj51kiugCkx8ven0QVNVNNKdIK2qWTNp5RDPmqYAA7JGzXzLYgGkd5sTs2APV6giqIGrDBqucWGWXdcG2TWABwN6NNgUps54TvdvPe6m%2Bov%2BhZjoOVyfVACcs95FweCmJKcOhxcncVa97PvVfvpgN3FdZEJrhACkKjvItAUDmOU43UhVd837Qtpm3QMP31atBlqP9GzPC8MWAk5ljAmt70gsABxyLdX1LYE90-UNv12P8wgiBQ7jwAAVDETAAdWUPoV1zfDCLYF8SwDd8i33L9BhhFC5wuDFYA8cIABFEDcZRjnQu8KQfIw%2BwI6D-hIqAbHHETKMGDk-yaZoQgeRjem6a5PUQKJekxBR2PgTiTT4EZ1wLTcYL0opbHIhDDSCQhjTMlowgeZRmjuO0XEzDFrmaMwsVkWRXWXE0hC8x8N2fYiBICwyKMQpJCAjCLmgAJUQOAMXgVz3PZXLNKfQd%2BLmAygqrEKjEIesqtq%2Br4AAOQ8Q52wxR4QgvQ5NBNQgeJ0zV-MODw3BUJSXgAMUxG8lGJRjXx6g9ypnP9hsxeAGg2raOj2jEDtUyNoF6PFEXQgB9IVlDc-plt83Siu6%2BDeshQhjyqqT8RMO4MXaNMmv6DzWsMLTeKHYx-NB4TSr6wxhkjcyYZcOGEeUNNxsm4kZrmhaIcBgq-KK9bNuUbbEEe56jpOsGzqCchkJrSBSfJxGFFu9nOe5hKXr-N6PozYkfr%2BzimY6wquuKU7RKSchqJF8yADVWWRVR4FUNRkc7TyNaIlntcC-m9cF8SjZaHbZIzTLzfCK2bdR%2B2%2BK1wpcemIyysF0yPeaOTYAUABxRRktSxB0sywPIRy4Osbyfy4Lx4LIXIcKjbujmOmRM5oAAa2RfE68UWQGKiAlEEXCasvA7jvKgoHVqKwuI-xkvKpF0bECFTnUQUEVumOiwFOivAOMyi5wlbGmMQZmsIL77SB%2BHWChJH4ua3IQaRYAaUQRAzEs6zujCNvCWeV4997vKfOZ4GnZK8%2BOwLqxzsscWQvQs41jtgfTGnU3xkRdsZfWUMRYxHUG4RAUk1ATW6C5RA8wGgIA-tUfe39%2B6-0HqOBBRdwY1ihL%2BEWFwlJqDwF7PAPtzgxBYQlDwWJGKwForghKmUuL2VznA0i5YaECyMFCYW1RRabWJHgYRThBTqC3lNZeqg16plET2Nq%2BVNaO3gVIs%2BtDqhQkNgoqWKh36tAJPMeALgEywAyuoSe08Oj6I0ujdqDs-6mIARYpIUJ3YKLkpTFw8wMGgMpr0KIJhIgtB8eI0OVhujwEeO-KIpgMHBJkYYKEMcFG3CyU8bxr0MRuAeJANJJjJEFNdrIsuCjb730EZEMIDcXDsJRj3MRMCVrHwLqfNYkcCYQChOPBR1dem13frIKSMlwiTzTIgG6FdOapzShlPRJo8JDKPtjIeYzQQTMhFCK%2BCjckYhOJLIhqSYEyDSIkawsgdoZS0BBYgQA)

#### Code

```fsharp
$"""
{1}
{2}
"""

$"""
- {1}
- 2

- {4}
- 5

"""

```
            

#### Result

```fsharp
$"""
{1}{2}"""

$"""
- {1}
- 2
- {4}
- 5"""

```
            
#### Problem description

Formatting deletes some of newline characters from string interpolation literals.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 04/06/2021 19:55:49 - 376c409945b22eeaf659f7c6e5ded396966be745

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello @vain0x, thank you for reporting this problem.
Some more magic is needed in the TokenParser.
