### ISSUE TITLE
Mutually recursive functions break with function invocation above definition

### ISSUE THREAD

**Issue by arnarthor** [fsprojects/fantomas#1628]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzWsARgIYBOYAFAJRgC8AOgHYQQDCsjAzrJgHQDqpAJZZEAGSGNEFepAASidOliyqTJizCYcpRNDwFKNWmBLlZCpSsgaWxRvFNkwnLORMAHYYyy4wsgFJOWRc3MAAfAD4wIQBzRlhddWYWfFgjZO0DImdqOlsILN19NKM6J3N5RWVZArB7RzNQ9zAvSV9-SCCQ13IomPjExGTNUuomSAAacChObCxJWM5UMABtGYhQTQhIABIsAE8PZDRIdqmNlj2AN2J0AFcTtcvNAAZp7auASQdEHwBlIQAL2QH0%2BYAALC8wABdS4AXzBm2he0OxxWZx8F0%2BNzujxW63BYAAjEjtpAALLEAAeEikYj%2BsSwAAtseDiQAmV7QuGaRGXLbk-ZHJ6QQgEdBszS4h5PQngjlk6X-RAAWyEcGUjAAglgAKIOADyuDpoOhEFwdzmPIRZMF0uF6NO4p4Uquu1usoJ5rAAGYlVd-h5iNBEAAhRD4XQABTIxFV2EQpDdmjcjxtfLtKMdopdkoDMvxaHlnwhAZ2QZD4cjQzEsAA7knoMQ5j9rrBmwsOCmWGnEBmWPzNPb3WjcxKe4W5T6AKzlqCV0MRqOIACqHmOpGbrcY7c7Qm788t6Gtn15g6zOJzGLzk49eOnRIAbPPIIvqyvWOgW5x2Fw09AWCJD2FpWv2Z62gK2ZjjeE4FveXrFj6ADsr7vsuQwUmqhBJiBeBgQOEBDiwI47NezpwdmnpFs8RIABxocGS41ro7Banhx6nts55EZeQowRRrrwdRj7ggAnIxVbargoikOwqqqsQeF9oRYDEciV4CVAt7CQ%2B3pEsS7w%2Bm%2BTEfkMKrqpqh4%2Bpx4HcZBw7QSKsFCVRelIQZpLGe%2B0myRZGo8NZRIqRBmZQZpzmCfmbmIbR7KKsZPxID4hqMAAKqQBz8CIrJHgRoUXuF-GRdplFXiJ%2Bnsv63mmdqpCwPcDgACKKEI6qycppDpgVvFFQ6WmYlgd4VR57JlsZVLUl8uBpcyfx6ieiD-MyiRYNl8AsnhELcj1al8f1JWDcN7lxZ8xJzhNNI-LgQjUoam7EEBpB6tSXiIJwnAHoweEzjt9lhY5EVOlA5y6bFJbbMSL6XdSABKeiJPA62bfO22qepYCkVA5Eg1iYM0RDmjEqhMPw3ApDwAAcvcqo4aQxpfKIqrLPOxLo-to6Haq9zoAs6CSIgABiiSKVgslpc5%2BOiWdDHGWTiMUjzfMC8LpCix1r7QMycaAUmAD69ZCBtrLs31nPA0dUuVWdEkw3VpDEAchqkBIrjI7lPpo7tGNY6ih2gzFBM%2Blyr6TfbjvO67WDU7TSYM0zLM%2Bmz3sc2RA3c7zQj81Iqvq0mEvolbo2fByXlEpA4dOy7QiuIrmfZ0LIuPRrxlazrskG0bm2m4DxUWwH5UnYTLAcgl5eTQAag%2BYaSPAizu1tf2aDxe1m2n-t44H0vbBy1XjzSguNYBX0zw489dx7RJe-9hW9wd-eb4P4PB%2BN%2B-Uk1sBYAA4tgL1vR9X0F7zl%2Bj3EiTkLY6S3tbHeF1x5KyzgLMMyhoAAGswwO1QdgTgqV-jxkQGxGm308qLVARpPu45XJPyDkSDk0Ny6U0QPWBuEYsCNj%2BAXRALUbqMBEF9bUDgsKx1IInIktlSGY3ARQ6KVDt6aA5CTcuABpRAiAPDTVmn8H4uCEymg4vlG%2BvU77m1FAPIUI1To71lm-Ba6pODMiAZ7JeLAV4%2B0kS5aRZih7B1tuXQEjBYiYDqrEGmfw1qIEIBSBAZpRH6OXg5MBQMpHHWfkSX0Rly7an5vEQ%2BjBj4cEBPER69xdBpVgElUJj0vp6JISnNe2MBqQJkdAzQvoy7ggrrzJMjBKnXHEBwWIgi6ZcMkLwjgIjwRiNqUY9eECyqeJSeCX0Y92l1wWKaMQ8ZCDwGIF%2BWAn1-EMKYQLapXE4kAwSeQ9xyTqGLL3u0pqNdiCEEwDYmuzJ-gHB8DSE5dkzm3wuffUUfx4DGlNP8Q4mBrmyJYL6V%2B7SDQgpNMczWpB0C4EgOI32OMxRzIdOY4eEBfSwPaco1R5SfA-HQfYLWPzMVuKilC5pMK6HtKQfYFBppOB1Qag4BhrhEDwFWQgqQf9dAALGZ1bqBjV7TPqYdRp8ybmfF9Ao9p4LhCAUiUgWl3sZgwjBGcTggtPorDEfCIAA)

#### Code

```fsharp
let foobar () =
    Console.WriteLine("Hello")

    let rec foo () = bar "Hello"
    and bar str = printf "%s" str |> ignore

    foo ()

let foobar () =
    let rec foo () = bar "Hello"
    and bar str = printf "%s" str |> ignore

    foo ()

```
            

#### Result

```fsharp
let foobar () =
    Console.WriteLine("Hello")

    let rec foo () = bar "Hello"
    let rec bar str = printf "%s" str |> ignore

    foo ()

let foobar () =
    let rec foo () = bar "Hello"
    and bar str = printf "%s" str |> ignore

    foo ()

```
            
#### Problem description

Creating mutually recursive functions within another function that has Console.WriteLine above the recursion breaks the `let ... and ...` syntax. Some goes for other functions, ex.

#### Code
```fsharp
let foobar () =
    SomeModule.SomeFunction("Hello")

    let rec foo () = bar "Hello"
    and bar str = printf "%s" str |> ignore

    foo ()
```
#### Result
```fsharp
let foobar () =
    SomeModule.SomeFunction("Hello")

    let rec foo () = bar "Hello"
    let rec bar str = printf "%s" str |> ignore

    foo ()
```

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 04/09/2021 08:14:41 - 8b0920d16a3cc8c75962f236fd87c4bae4476da4

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello Arnar, thank you for reporting this issue.
This was a regression that slipped in the 4.x release 😅, so I'm glad you brought this up.
