### ISSUE TITLE
Style guide discrepancy: Use a space before parenthesized/tupled parameters to discriminated union cases

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1634]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB5A1mAFAHUgEMCAaMARgEo8AnPAOwGVYBbRXA4yMq2hgURo1YNDkVIVqdegFkAngBEArgGFCAZ3ZiuPKQz6y5AFTkAHRADp5MxABcAFgnzjuk7uCibbtgJb0A5uqoYADaHhCgEFFQACS2ZshokH627tEQkDEAboQANkqJoeHpAAwkxdGQAJL0SPS2jD4AXsjl6VEALBVgALrFAL5tUZHpmfHmwcn1aaPZeQXBYe0Q5EPtkDKEAB4AMn6IO4gBDjPt5ABMJd190YPFI5VxCZMARrCwuadRmTn5hUvLc5rUaMRAsHxwXKwegAQVs-Fq6AAZnt6K1uhAkXlNNcBsCHt8nhMkm8Pl8MnM-osMWAAMzAyqMUyEaCIABCiCRIkQAAVCDRCGxbIgaOSorYaAVcbd8d0xs8Se9PgzYr8FmgAe0OiqMkyWezOdydrAAO4i6AaRA1LKwC2%2BaFiiASqXtG5RO7RAkU8aFSCk5VyynqorLMAAVh1UD1rI5XJoiAAqqZzDQLZprbbCPb6I6wFjcjjXXj7oGfa8lWKfvN-jSAGyRyDRg1xxAqXIadQqaHqZ3QWwiXP5wvpN0QD3DUsKqD%2BytBmuhgDsDabse5NhYLxFg%2BxiGl7tl6yJvpnKqrVI1NIAHMvmTHDfGu1Cc5Gh7uizKS4ey4qyae59TQwAThvfUYSRYUaC7FgWEIXNnTfEdi09SdiWnCs-zVedlnIMoaUbW9m25UFwUhB0Xx3PcxwPWZvzQ39A0wgDsNWPCmzAiDiIhD4yJpeDKLAccIhQ490IY6smLOIE8JqOpbHQegjBoOQAHUfBOciCwQ6JRwE6jHlov1RMPRiL1Dch6VYgiYWEJRagURBch8cEILgyUtKiHTBLAL1YgMlJZxMkNsO1PDNi2KokSMewjn4TTGEcGhbFU%2BB1JpDornffdPxoqcplSDDxNM7CI1C7YaiRHwtnQFMsxEfgtlMeN1HUHweNDMMMsQj9kK-XL-IK88grOetSq2AAlRA4BoeBktS0N0v4ryfPlVC8oCwqhvScgl1GiapvgAA5JQNxFZEqmFFggkjchFr0wkDJYJRcl8Ry0QAMREGDvBFEwJgG4NNS2688L2kR4BkJ6Xv2D6aC%2BlyG2gex%2BRZCCAH0TR8FL7EgW7sv0vrpn%2BrCzmA0brIFOR0BoPYe1m7HIwWzKqLx%2B6CfysTBsB6JLgbMLycISnqZ8HsjpOmgzouq6aRupndJZ71cse56fFexAYbhn7niJiT0nOFjQ0gfnBZp2wIeV1X1azeG8MR5G%2BxFdHMZOXGepy1b%2Bo5gGaXOKSDbCgA1as2T8eA-H8Onc0Zrqstd-H3cJz3id1iy-e2N7bL7Vr6GD2ow4jhnOu0pCJ16%2BP2eMjauaic4QtTrYFFgWwAHE7HqxrEGarP85pDqXZLt2RPoivOe9kq-chlX9jZKFoEwNkBVnux1HkxhBVbD5jufGlXz7oTS8HgNh690NzhGg2DsQE1VY5WwzSOX7EHsir6DUrOYVqddNxoKXQx32WluEuWIesxApVwgOcHaBsADSiBECmAilFI4NRV5sFROiX%2BFF-53QVmXdaI8T7AzrrFcE6h7Dd3moXDyxc94DyAYfEBldvakwNo0AIuREDWX8MdI4SVEAvBkAgdByw-7R2ZrHVmq0TyJx1tEWkuEDYwkcv4eg6d6CZ2hI0ZRWYlDxiMLAGSPCsxZ23JpXe3lAE-noY8UBNJaT62WIbZ6Ip6BGKyAcaE-hP4iifn4V%2B3YTHDiLt1fuccD54OPssWkvsHFm18GgnYgoXjwEIG2WALUAgXyvvsAJ7kICeWwb5XKUij5J1kSnBxChhaEBeOw4hwt7CMDkPUbYOSzHLSPJMI48BkRoMYPEdh4TSlRFpLXBxCJukomyQjGguQkQ4ywfLQpkijIMPwZEseDiYFwIMfUGo89CBqPptvTBoi5biJwWE7WRV2i0jPg46eBzMBoPUNZWAtlDod2FODCeqs25NRav4yMfEFnnKWZc6R1z0i0kgQ4vpNAISm0Ea0-%2BHgehDGSOoN6LVgg736EAA)

#### Code (and expected result)

```fsharp
Ok ("a", 1)
Some ("a", 1)
Error ("a", 1)
MyDuCase  ("a", 1)

MyType.MyMethod("a", 1)
```
            

#### Result

```fsharp
Ok("a", 1)
Some("a", 1)
Error("a", 1)
MyDuCase("a", 1)

MyType.MyMethod("a", 1)
```
            
#### Problem description

The [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-discriminated-unions) says to use a space before `(` in DU constructors:

> Use a space before parenthesized/tupled parameters to discriminated union cases:
> 
> ```f#
> // OK
> let opt = Some ("A", 1)
> 
> // Not OK
> let opt = Some("A", 1)
> ```

This was previously reported in #1421, but that issue was created before the F# style guide was updated, and didn't receive any response regarding re-opening after the style guide was updated.

Based on the discussion in #1421, it is my understanding that Fantomas currently has no robust way to discern between DU constructors and e.g. member invocations or constructors.

I'm opening this issue to track the discrepancy between Fantomas and the F# style guide. If you know this will never be supported, feel free to close this issue. I'd just like this decision to be deliberate, hence this issue as a replacement for #1421.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 04/11/2021 08:57:52 - a926fe813c309cc9025dd0ed0e460bff615c2840

Default Fantomas configuration

**Comment by smoothdeveloper** [comment]
@cmeeren AFAIK fantomas works with the untyped AST, there is no way to distinguish between a DU constructor from a method call (fantomas has the assumption that methods have first letter upper cased IIRC).

**Comment by nojaf** [comment]
For all Fantomas knows, you could be having
```fsharp
[RequireQualifiedAccessAttribute]
type MyType =
    | MyMethod of string * int
```
in another file.

Use `fsharp_space_before_uppercase_invocation=true` to add the space.

**Comment by cmeeren** [comment]
Got it. Thanks!
