### ISSUE TITLE
Regression in fantomas 4.4.0 – doesn't honour fsharp_space_before_colon = false

### ISSUE THREAD

**Issue by sebastian** [fsprojects/fantomas#1641]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAKogM4AuAstngDoB2depYtAhuommQE4CWtA5mAC8YapAASiHDlhjIAGnBRiiUqT79iqMAG0lEUBCNQAJKQCeAB2RpIfUgv1HIJgG4scWG7qfGADIrGxpAAkrRItKQAyjwAXsiBQRAALL5gALpOAL6JBmkuFtbadpGOSS7unt56SRAAjLlBkOQsAB4AMnyI7YgCpAAWZbV1AEx%2BaZnGOU6GTWZW3pAARrCwOEPBbh5e2jW1I43BUYjoPHAytACCpACi4QDyAGadtAlpEI8eKhPZjbObhUWKzWG2cWyqu3eYAAzIdnFFLCxoIgAEKIR6wLiIAAKLC4bFUiC4oOMpC4Xh%2BUz%2B%2BXmRVswPWcIq22qUOScIgkARSNR6Mx3VgAHcidAWCowq5YKL1LBaCSjGSKUlJkZpsZ-mDAcUGfLmRC0HskgBWDlQbnItEYrEAVUs1i4ovFtEl0p4svlHy%2BiEpqup5VpQNWjJplR2BqhADZTVzERa%2BViAMI4MXEBOy7hYaCkTEesCfHDfZW-GY0rX0oO68Fhny1MAAdmj5t5VsQ5BOSyJufzhaCKogaqMGs5Ae1FaZVdZtYAHI3Y83%2BWmLl2vT7%2B365mWoDrx6HJ7UAJyznmXR6kIlp9DoFi5xXeotUkv%2BzfLMchlmQ2t1AJQmM8y3845TnOd1TW7O9e2LdVSwWUcQR3d9w0-BofybE8zy4QCzjWECoVvVcwAHPInxg8s4LffUa2GA4fzCCJSHuWgCC4cwAHUeAGZcC3A4w%2BwI9cARIrdX39XcP2GWEULnS4uFgLBwgAESkHhTnQm9yW4oxeMIsAh1MZ97ErUTEOGdkfxaVoQkeAh%2Bl6G4uKifpMVINj4A401knGe9fUfDdBJKBx4Iow0gjqE0zLaMJHh4Vp7ntFhsy4G5WksLFiGIN05VNI1PIgh8oOIukoAMwLq2C4w6ijcLWgAJUQOAuHgFy3LZHKeMgwdoMK-zDIQyikjqBsqtq%2Br4AAOSwdAOy4J4QjPdAtFNOp8O03SCj89BcHUHAugAMUxK81CJAgYJKvd%2BpnH9hsxeByE2nhttePauAO1To2gfo8SRdCAH1BR4VzBmW-jNT84ryNKqE6kPKrpPxcx7i4ToyCawZ3NazT2qI3yurBkTerKowxmjczYZYeHEZ4MhxsmokZrmhbIaBnyBK6jacC23b9vi9DjqKU6xKSEZkNrSBSfJpGKDuh7ECel7Ozej78SzIlfv%2Bjimfy7HFlxuYjL6oIRmokXzIANRZFE%2BHgDQUdzDyNY6grtdKfnjMFiTjbaHa5KzDKLfCa21dRlr7axlmnYC8GzoN0yPdaeTYFIABxVQkpSkh0tlG2svRiAtOB4dn23SOBYNsLjalroURkaAAGsUSVmvVGIBiogJRcJsyqEwJDnTOsDMi8aCqERkqkXRsQQVpbRUhhV6XnEEUqLaHYjLLnCNsaa4Bna27ry12ZkGuqLweIdrEZBpFgBpRBEEsSzrN6MJW-YF43h3lc974g%2BC9B53i9dg2F1Y52VOMQfoWdg6fxWn3WCwYT5R2MCMaGIsYgCDwNJfgE1ejOUQEsSgSBOI9janlB2WtYE9SHrWaE34RaXG2vwWgXtaA%2B1lDEBh8UsBYgILAWi2D4oZUIRpXOmNe6O3IS7fWxhoTC1qKLdmRJWDqFcAKAQG8pqLz4CvdMgie6rRHKROBut8ZQmhEbWRt12Y8Ffu0NgSx4AsCTLAdKAhx6Ty6DoqB%2Bc9J%2BWPkYyhtRoTu1kfJSmLAlh4BAZTfoURzCRDaB43K3lNZh2KL0eATxX5RAsHgChp8Akx1kXcdJzx3FvS4DgR4kBdEwIMbkhBRhoRl1kdfW%2BvDIhhHriwZhQd35cWqWI2pEiCYQGhKPWRVcuk11fsQaSslwjjzIIgG6FdXip1ShnWg29ah4U8d-bxR9hJ%2BLyUkaEF9ZFZN4FmfBb9ai70Sf2JQ6REh2GIDtdK2hu5ZCAA)

#### Code

```fsharp
module TestModule

let name: string = "Hello"
```
            

#### Result

```fsharp
module TestModule

let name : string = "Hello"

```
            
#### Problem description

The `SpaceBeforeColon` (or `fsharp_space_before_colon` if you like) doesn't seem to be honored. As you can see from the formatted code above, a space is inserted before the colon in the let binding.

This problem does not exist in 4.3.0 as far as I can tell.

#### Options

Fantomas Master at 04/13/2021 06:51:51 - 6d1c30f865c326aa5bf9f5214cbb152115920d46

Default Fantomas configuration

Thank you for building this wonderful tool!

**Comment by nojaf** [comment]
Hello, this was done deliberately actually.
Fantomas follows two style guides: [MS ](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#surround-return-type-annotations-with-white-space) & [GR](https://github.com/G-Research/fsharp-formatting-conventions#surround-return-type-annotations-with-white-space).
Both mention that the colon before a return type should always have space, so Fantomas was updated to always respect that.
