### ISSUE TITLE
Idempotency problem with ifdef in a function

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1646]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYrLGALwA6AdhBANoA8RsAfALpU1h4AuYARjgCGAC3oByQczBxKAMwCWAczBoAKgE8ADvgqUAxPNlgAIgFEAQgFUA4h041Zg%2BTgDu87sLDlI3qnsSU8IZ29iawqsLylIoAdPCwAJK8ABQAlCH2PGAATogAzri8pGAASliUlIjZMWWU4pLSsHJKGZytNIZgBdDQ%2BXmyuGAAPlIAMvJ53DETpuia3OpgHgHtobkFONyrYIg4eYjbnFlV2bDZeWSHoWDl3b15-bhXoSNg45MxCptVz9cQyQNqLlNGdeABaKSUWC8YGgmLmLDOeAlfKFGIJPIIpEAZSwPT6wyGYChMMQIOyUyxOGRqM26Ly1gCVUE3EQuPxD3S1D%2B11e7ym6EEml%2BfwB5RyZNBYAhEvJlMR1JRGympmyp2yAFk%2BoJFIguTyaL9HM43B4vD5IJAADTgKD7bjcKKKPKoMC0W0QUChSAAEgW2ldkCi3GtHpovoAboIcFhkGh3X8AAw2v6QBKBALcbHyABeyBT1wALGGIKwwwBfAuektQP1aONQYOh70%2BqMxhsJ64ARir9kgGsEAA9xpVRgFFB5m92AEyJmtlziVsNevt1gNoSB8Yg4KecSPR2Ouzuhae9vfYxDoeRwHBNACC3FMgQA8rIR-maxBHHtEPOK72Vz3NcG03bdd3DVsDw7T8wAAZjPcNsU0QRenMRBZDORAAAVBGyQR0EQVlsnAzhuGyWM-0XACa19f0QK3WAdwQ-d2yPGDCwQiBICQlDEDQjDclGWAXCqaBBH2dMI1gMTHSaEiaDIijQgXGgl04QCILowMGKYmjINY%2BMYIAVk4qAeNQ9DMMsTRtGyMSJMoKSZPkOTTMU39lP-Zc9K0jcdPkljD0Mv4ADZTO45CLIExAAGEhAeGKmkmcjoG4M55IgdzKNU6iW18qB-OY-SgrdGCAHZwvMvjLNyLV0D4KoMqWciPPsFSIDUmgNK44DtLAoq2xK497AADkqyLquixLb0oJqss8qjvLy%2Bs%2BsYgLiugv4AE5xt4u9ZCIxL0EFOaWuyjrctXfLQLWgaoLYv4u2TGCIt4-jMIvK8b1cmD5rarz1J8la-P6vTBs27sexeqr9qIz7r0Yn6-j%2Bzh2rATrq2W9cCtBltwYemdwvTJBKG4Z9KFUbJ1AAdXcYQmu-fZzvRy6gOuwqwfu4Lu3g6GJrvU5yngYxdnkK8iNOpT-sWwGsZAps7oM0rHo4l6B0HBJZAiAJTB-bFhFBWn4EnUzCznBacqWq7gcbUn1vx7nQi7Ey1aHdMFEHZ9bJZM5TEHTR1jyFzZtMozzely3Zet7GgztxWhpgrswtdwcUTgbJ4CNk32PD1GAa6oGY4VzmleGzguwqlO07OeAADksHqqpXySS8XVMrtmYxsButra70EKZwokQIhskFB0qg0AN44hp2xpe6uM41AecCHkex4l8LoGEXCUKIgB9NxjfpzvWc0m3Y5DaeCadnaU4FvD1GfbJ%2BSz%2BnTdzmg0a7nvaPP4u8a5sra4s5wrq3voIR%2Bz8JjcHro3bIzdWToDbonE%2BVs2bn37psQelQ14siIpPD8ADS4wWnFDVM4DIH8iXlgleOCzjr0apvbeeFUpVAPvII%2BkBUFR3QUXOOJcE5-GnKeFOAA1KC5gohBGiK-JqZtuEFzloGf%2Bq4HZAJPLzVM6sCDlFSsHSRgQnSyPfgozG0d5b8KIYI4BqstFDmMNCRkj5-aB2DsY4yH9Sz5zMbw%2BiuNVGALLjQacLstHLyHuYW80AADW5gWHRMInkcm2J8KxUYg3EOv0zoWwumgs%2BMcOZWJnvYacydUy10QC4Wh1VuAiQCAQkWChKDuGDneQIdUGrnElq1POMtFHmNWrpIp18SmV1TAAaUQGSTW2tKDphSQRd83TTHd0LhYy%2BAjimcGnHPOxg5dZXjyMIdxfx5E5JZnknq7N-FATUUEiA05b6pmzNEPAAtFAN0zNTRAfANQIEIdcRmPTP7eNWUokGt1NkjM4LBZ65CV6KEoDoygeimjZkRSyLAuRVCJAzKTFkwdlnnO-mswZ9tAkwVgmQ64kA7zfGyJQAlEZEBCWiB0qojSogtKSkSiOuSeH5L8ZC4Zjt7CwREWErB75Rj4T4PAQQcVYBB2iBUqpQ9eW9Mjv03xZKr6iphZomlxgJiCAEIgA5ExhDYnUPiwcDNoxM2JafK558AjwFfO%2BbECw8DkuIX8WCtiaVPndW%2BdVm9sg4FkFwp1lze7n0KQEv11xYKhJpZM6ZeLuDpjiYIFFb8slS01fy7VgrdVQv1TQWCZSaWRNzdE98eQBawCFhUyYiB4DUMdNUv2Ac%2BjB2QcjbJfKLkCpdQUm5EE7mUrGTSr12RrzcD%2BUge1P5O62lYAWIMeQCBB1dECkA5YgA)

#### Formatted code

```fsharp
module Foo =
    [<Foo>]
    let blah<'a> config : Type =
#if DEBUG
        failwith ""
#endif
        DoThing.doIt ()
        let result = Runner.Run<'a> config

        if successful |> List.isEmpty then
            result
        else

        let errors =
            unsuccessful
            |> List.filter (fun report ->
                not report.BuildResult.IsBuildSuccess
                || not report.BuildResult.IsGenerateSuccess
            )
            |> List.map (fun report -> report.BuildResult.ErrorMessage)

        failwith ""

```
            

#### Reformatted code

```fsharp
module Foo =
    [<Foo>]
    let blah<'a> config : Type =
#if DEBUG
        failwith ""
#endif
        DoThing.doIt ()

        let result = Runner.Run<'a> config

        if successful |> List.isEmpty then
            result
        else

            let errors =
                unsuccessful
                |> List.filter (fun report ->
                    not report.BuildResult.IsBuildSuccess
                    || not report.BuildResult.IsGenerateSuccess
                )
                |> List.map (fun report -> report.BuildResult.ErrorMessage)

            failwith ""

```
            
#### Problem description

This idempotency failure goes away when I remove the `#if DEBUG` and its contents.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 04/14/2021 13:41:07 - e164e231f5456b9e128bc567462fcb39cbb0f491

```fsharp
    { config with
                SpaceBeforeUppercaseInvocation = true
                SpaceBeforeClassConstructor = true
                SpaceBeforeMember = true
                SpaceBeforeColon = true
                SpaceBeforeSemicolon = true
                MultilineBlockBracketsOnSameColumn = true
                NewlineBetweenTypeDefinitionAndMembers = true
                KeepIfThenInSameLine = true
                AlignFunctionSignatureToIndentation = true
                AlternativeLongMemberDefinitions = true
                MultiLineLambdaClosingNewline = true
                KeepIndentInBranch = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by Smaug123** [comment]
Looks like two different problems here. There's the insertion of a newline below `doIt`, and there's the re-indentation of the `KeepIndentInBranch` code (which was correctly indented after the first format).

**Comment by nojaf** [comment]
Hey @Smaug123, I believe this is solved now. Could you confirm, please?

**Comment by nojaf** [comment]
Closing as original internal report cannot be verified.
