### ISSUE TITLE
[Feature request]Disable empty line between mutually recursive type

### ISSUE THREAD

**Issue by cxa** [fsprojects/fantomas#1658]
```fsharp
type Cmd<'msg> = Cmd'<'msg> list
and private Cmd'<'msg> = Send<'msg> -> unit
```

formatted to 

```fsharp
type Cmd<'msg> = Cmd'<'msg> list

and private Cmd'<'msg> = Send<'msg> -> unit
```

[Preview](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAwgLbwA8A5IQM4DmAfGALwHFnlV1gA2AlpegDoA7AIaD4YbACduAN2Ho8ReKwo16TAMqIxbNWAC09AK6Du6SABpwUSonTpug6pVRgA2tYigIPqABIsXFdIR3MrXwhIPzlOI2Q0DwifAAZwpKgASTFtdA1uAC9kNKSAFk8fAF1ygF9isG8IqMD4qFDLcsjo4ViWxPSARjrfSABZYQAPABlHREntanQAC3b0sH6AJmSOsCrfWvKG4YCcFsgAI1hYThXGrp7XPqT1oZ9ILUJuOE5YQQBBdAAomIAPIAM2mgiK2wgoO6tm2ux8%2B18h1exyCaHOl2uLyiMTiD2hYAAzC9IhpsMJoIgAEKIUGwSSIAAKwkkwkIdkQkhuSXQkjiCJqdVRnWawQuV15aPxvSJJTJUApVNp9MZs1gAHdudBhLYsjJYLqHD9pb5%2BYKkoiIMifKL-OLMZKcds8d0CQkiQBWRVvSnUukMpkAVWwuEkuv1gkNxu4psVsM48KtwoOrvRp2dZv8ssJqwAbL7lQG1Uz8Jw9ZR8D8%2BALoOhGdmYXDEEK9iL046oFncXcPe4iQB2Iv%2B1VBxAjRCEM7cptgRPJiLWsC2rydk4S7HZt33T2rAAcI5VgfV1e%2BgjnC9bKfbaaSTQ3Tq3vdze-SAE4j9TfqCFJJq4QhDCHOFrXkuqYouuGLds%2B6avgOqz9KkRJ%2BsepaIO8nxXPGRJXm2SIdveGablKL7unKiGDChxaID%2Bf6YV8OGrKB%2BE2oRtxdlipFweReYDM8KFZEggjoMCggACqSJgADqZjLAmLasSu7FHJxPY8buCEDKS1Gjr8kiwCY8AACKIDwHx-iBApgb4y6rvUUGnG0ZGaY8ET9AqKFjOMGSguJizaACSYYYsjLoLJ8BLHOJRbDeBF3hxj6tCJ259hRAw%2Bl5ExZKC3DjMC4byIyALjFIiCUJQcYXoqXqxeBt6QURnHORp-Zub4-SFll4wAEqIHAkjwBFUWKjFSn2faD7QSEKUuW1RL9MO3V9QN8AAHJGNO3JghkChUHO-TjSpaKcYQRicA4PCQgAYoyQH2Ny4kbnN6VJP0h4oStjLwCM52XTMt2SPdlm%2BtAixslSf4APqatwkXLEdCWqUlM1hK1r3uZ%2B3X6eymDApI0x8MN8nynVtkQXajnBC1RHwe1PibL63k48IeME7w6AbVtkg7XtLiKodcVsUjJ0o2dF3cFdiCA8Dj3PejfFPFRqyQCzbOE%2Bgv0S1LMvyCDKFgxD9bcjDcNRYjjWJdNNO3HTRLrAJKveQAauRNKOPAjjUMT0Vk5UFNrk1KM20cdurOsOlOxM10mPWVXu2IXs%2B6NfsQHZx1isHs0K2%2BTyeVH4zGbA6AAOJ2CVZUVVVyfeqnOwBw5QfTeptO8bnETrJlTt-ZLMw0t80AANY0uyQ92JQYkaByiBnpt1W4YpQvKSLmfN7BreufbXUq2tiCalLdLoNq2hPbgpm5aYJp-GIk7c-zC-BRblNN5m6%2B223WlPEtKsANKIIg2BfL%2BW0FkKenIIRQlWHhJeE0qaYhDjKD%2B9MIDrA%2BgXIKHxKCLBrqsMaMCM4OhRi3d%2Bm9w5YxVnkJwnBaKSGoJtHI0lEBnBGAgSB6RoH1XipbZGa9uIb3mqsYkyEVa-B4NQQQMdBBxx%2BHkcR8gjBMnErAISOR5BVUvIvThwtuGi14S6fhGNfDEmVukVWF1uQiAcDIDUThb4zkkOfRwZgqr3ygZo8mDVn5W1fnwkhAj0jEkdqYrWDgIGTA5GceAwhyywEqk4Xe%2B8ZgaMfvglehC9GpTDgEyOpjjK8GEGcahGDeCLA0JgESExkmLg8VwrxPDTjaHgGCCBGgsDUMyUgokxJ86mKBE08ESTQaSE4KCSAT9A7eJIvovxhifDEi7qYv%2BACVEiSyCPUQYMqk2X9p4iZ9SpkdNIQE7epj%2B6iEHhAyg%2BlDJiF3nwRAP0e5SwrkyKuNYrKWi0cvHRq8fHTNDp0wR39TGtOkPWFhSAtnjWsBUNIIRKDXUqq4PC1QgA)

Can we have an option to remove the empty line above `and`? Thanks.

**Comment by nojaf** [comment]
Hello,

Thank you for your interest in this project.
I'm not in favour of introducing a new configuration option for this.

We should have a better default for this.
I see two options:
1. Go with the [default multiline rule](https://github.com/fsprojects/fantomas/blob/master/docs/FormattingConventions.md#2020-revision).
So if both types are short, it just goes underneath each other without any introduced blank lines.

Helper function: `colWithNlnWhenItemIsMultiline`

2. We respect `fsharp_blank_lines_around_nested_multiline_expressions` for this.

Helper function: `colWithNlnWhenItemIsMultilineUsingConfig`.

At first glance, I'm more in favour of option 1.

**Comment by cxa** [comment]
Hi,

Thanks for your reply.

Yes, I agree that less options is better. 

Both options are acceptable, but I think option 2 is more explicit.

**Comment by nojaf** [comment]
@cxa I went for optional two.
