### ISSUE TITLE
Long .Setup line in Moq code results in broken indentation

### ISSUE THREAD

**Issue by asik** [fsprojects/fantomas#1662]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAdATugdgFwE8AHRMAYQBsBDAZxoAoBKMAXi1wggFtEuAjRJjB4AFgEsaAOgAG0gNZzZTVuxyd1YWgRzQwwVRsNgusaHINHLkgMqI8AVyL0AZvbVcwAWgB8Fy4a5JMkxEKjxEACFqET9-S3oASTxJBJoAQRwCAB4aPEwxHABzbyYAGjAklPTMnLyC4rKK5NSM7IT4EsZyypaa%2BwK8AGYAJk7GRli4iEkAJTt7TBwGa1geY1M5Cew1KfVJAFEceEnOAF8TiAAfbzA0mm1oGzwqTDwErh54MTDEVUhS8BQGh2PD1GioMAAbUBEFAhkgABJCCQIZABv8YZxEQA3KgUezINDQywABgBlkgCSOiHw1jEAC9kOSjAAWTEQAC6mNOzNh7KgSOIhKg6N5WIRuPxwuJRgAjGL1JAALJUAAeABkCoh1TTCqIMZZZcMSfyueoeZi4RpEcjhZA%2BLBYBQDdaJXiCRCZYZhgqsbYuGI4BRYDg0nhDvAAPLOTU4Jn8iDOPHA03csVWxWClFoe2O52%2BnHu6UJsCDX0QSDWIhUaCRRDOWAhAAKLyoPHCmBdhjyBNT5vT-JtQtRDqdXfFko9RJLLPLUCrNbrDZC6tgAHdBNBaIgqdjTGExCHx%2Boe4g%2B2cB-Cs3bR-nB26pZ6SwBWOeV6u1iL1xuIACqRBITAt2BXd91BI85yTCgU0MM0L0te9bRHPNjwFSdi0sAA2N8F0-b8QkoWgaDIENckwexoDwRtUMTZMz1gtMEKvJCc1vVDC0fadLAAdhwj8lx-JVeAETtILo88IAtdQM3FFioDYgsHynKESwADj4xcv2XRASODHAaLAKCYI0ODJMvV05NzMdFPQp9LAATg02s0mcDsSI%2BKgDNPCSwCkzgZIra9kOs%2B9bK4uUyRLd9NPwxB-UDJ0IJLIz6JMxjpMQ4dWJQmyizsuV5Si3DEBcjt4qDJLLG8hj%2ByYiysvknLQry8LDCNN8qSQfBIxwAAVTACAAdTEfUxOg1L1FM3zzMzSyFOaziVMNMsiv4tJMFgNx4AAEUQCgxADDsvPIibOCmvy%2BWYhq0XwdilIwuVZyilVVQSZxepEGl9nG6wREbPBhvgUaZxNGr4Iyq7sxFW7csWr0NFlV9nrVKlnDEVVI0AsJG32VUiBCOhD30udn1BtLaoh%2BqoZuvA7rCpa5Ww5HVTmOBMHgQHgcsFkycm9L-My6nRQW5T4fUWVeOZ1nG3gAA5ex%2BEEaMkl4cE51lHyLr0QW7S4ewKFBfa4wAMUbLgwg7Xrh1h0WS1ldSoul9mlX1w2tVNzBzbwI632gERW0owQAH01zEIGREgTWZtk67havemxc4WVHOZ9bMCoAhI0wTVck5iO5x5qO6tm2OYZFh7vUiikXrTjOs5zvB5cVzBlfCLg1btovKZL6m9YNsQjcQD2vct63y-y71CopWvM%2BziQ8Bd-vB%2BHi3BAMmB-fTwPMBDsP9S7gXIbtOPXQTkthh9ZmADUiwiAoviKPODMLsGzOLmOhbL%2BOWoZ70VurtUxs3CUSJnfI49Qn4F15mdfml0qbHy-qfH%2BicIDDCegA1U21YB4AAOJ2FxvjRAhMQyQJfNAzksDtZH2Cneb%2BcNz5I2rq7AeWoogbAiFvOQdgaA9WsG2HSToFbE2SuJV%2B0136BTmk1OhttLDDCZhSWWiA1yDy-HgDcNIrYkF2mjHAI0iYZHgEJZuHdLApQPnAnuN5pFIPoXIyWFIADSiBEBEDeh9GkVI%2BE8FjPGMxojybg0PvA1EJ9MxnzkQ7DB30Aw0BEKQ7m5CwDnWjpI6680ZEVw0MMFOFI6RFAoCVTAhQFY0gBogPgSoEB%2BKMOYsRWsAoCikSFTJE8NCDCrkYSAaR9qFBwEAnQ4EcB0j6WEBYiBeqwE6mUg8lVakBL5hTYJViaF02QSWQYU8uk9I7DgA82JtQhkKMYkSOiCj6NIgZOpgS37dw-tYlptjZFGBGG%2BReoJfHqjbHweAVBKCwBoPUJRKitRXIWTApZlj7mrJtlk9Qgx-5dO2hIKgfBCkxIkCIaw2hniqjBeNCxVCQk5hpFGGMWprCEEKWsuxLz0FdIjNGXx69oCYAoM4SO9TUlNPSTY8J6zLCDEYV05xrjpn4CpBwqgOh84iIJVyiRPLqYZKeXCzggwFFdKiNKuQvj0gbS2ko3IiAjHMMHgQgmgLLlzmqjc8Rdy0nKr5ROAVLyHFdMpfkSiVSkD4uMoss4gIOTMjRDQY2gKITmNOEAA)

#### Code

```fsharp

type Class() =
    member this.``kk``() =
        async {
            mock
                .Setup(fun m ->
                m.CreateBlah
                    (It.IsAny<string>(), It.IsAny<string>(), It.IsAny<Id>(), It.IsAny<uint32>()))
                .Returns(Some mock)
                .End
        }
        |> Async.StartImmediate

```
            

#### Result

```fsharp
type Class() =
    member this.kk() =
        async {
            mock.Setup
                (fun m -> m.CreateBlah(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<Id>(), It.IsAny<uint32>()))
                .Returns(
                Some mock
            )
                .End
        }
        |> Async.StartImmediate

```
            
#### Problem description

The resulting code is not valid F#.

Note this code uses Moq. The `.End` property is an in-house extension property that does the same as `|> ignore`. Indeed, replacing it with `|> ignore` is a workaround here as fantomas generates valid code then.

This started happening with fantomas 4.4. Fixing this would really help us as it happens in about a million files.

#### Extra information

- [x ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 04/17/2021 11:23:36 - 26674f958aaa77992dcc5fdfc1bd43ce0d71e919

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello Andre, thank you for reporting this problem.
