### ISSUE TITLE
Attributes in a recursive type get misplaced

### ISSUE THREAD

**Issue by purkhusid** [fsprojects/fantomas#1668]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAlgHbqIBOhAhgDZgDqspA1kQOYDKAFhafGALwAdQhAgAfMG3TcSvWADMwAJUQVo6WAGkiiAM74AHp27wACqVjRdOhkJFhxk2NlyyFj54njKK1wkKEUhLzeapraevoAgs62Itik%2BABuFCSxEAAUaXZgzIS6%2BDpoAJKRALYUAF6whFp5ejoANFl28JiUpbAAIgBCxWWV1Z1tFB09TcLZEBTOAHIjiGg66AmELOOTEEukKqVzpQtgW6zrGwDuDIxkRfCLy8fNceaWOtakAGKq6qSYxcpwPGYLFYGB9Qt8TpM4IQ5PgWGgQupavl9ABhaowlhZACUYB8YHQHAK-H8fgmECIJFIclUeCKCLCdQM0WwYFO%2BAJDwgAG0ADwogAyRQAoolEMQAHwAXTA%2B1KACMyPjCToAHQAeUIRUI7Pw1HwFU8-AI2vQuqo%2Bs8IrF6BVJgArnLzToOJywLyBcLRRLpbKFaQlQV1YRuiloBxAc8dIa%2BGA5aHw08rJavTb7Y6ChxIA1wFAo%2BhTasdKg3TmIKBJpAACRYXDFyAUrOlkRV5JUO3INBcpt2AAM2Y2UC1SGIbAtjYHABZu2BJU2AL79kTl7JVmsdqANxd2FvUdvFrsDgCMW5XAFkKPp%2Bdp%2BWKWATxxtDwAmHvT2d2BdN5fb6s4deQOVYFgKgHx-Vs907acICfE9tzYRBSnwOAqGqSJ0CFII1TkK88lA7JqSoKM33nE9v2bX9azQACgJA2CoErcD1wPDYAGY6IgSA2GwGlukQOQGEQExuHmSk8LsZZ22Ij9SOnVc-zrQDgLE%2BjGP3KCwAndioC4ni%2BIE-lYFOMhoB8RAtUSCwUnwaplIgCTECkkRPzsMiOIo-9FNo2SGN3Jj1IAVi0zjuMsXj%2BO2ABVDxSBMqNzMs00bK0giiMmd8nJkit3IUmjlJ3Ns-IHAA2IKdNCvTthRKgfB0NFCC2O0wVssAUoctKSK-by1xypS6PyiCSwHAB2UqQsQMKBNPBC-Wa1rHIgZyly6%2BSqM8vKfIKtSBwADlG3TwsQNEUMIWbqFS7J0oWzKV2y1bcr6jaBuYyYAE49ssSI5EpNFSnKZr7PmsBFrLZbKKgNaHtUyCjz7dTgv2gT4MQ5CkvUub2ukzqsu6u7eu8qHBsfY84bKxBPspJGkOA1GBwBjGMqxm6cfB%2B78d8rbHxguGh2tDUABVvlodlM2Ss62oujqXNBjzWaygnnuyQ82JJsbInMO0gk6RBzUQ0StLpiXMal7GVo3Yh1vl9TD00uHz30Io5D5jgxSFQjEE4Bh0CF%2BB7y0idX3pq7GZ-Zn63NyH2ehx9Atti8tRhfQ1VwUgUgYIV9HiKxrJOrT-IDw2GeNpnTbD9ALcjwnJkPErY-0P4GHgb3ffU-3AeBsBXPo0PNzZzao6rkba-rngZjteUyCwooSFKIstMPNvrpDkvSjtKhTXNPI3gYcp8zIPn5IjvvK8V3a4eH%2BBT1X9ftC30gd71uGw2EtQyAAfTZH3MwX4PyO78Pe6elbN6tc1Yp0wGqUgV4lhNxFi3fOdhLpA0Xr-EuPc5YVwVnYF8QU7agIoOAyBBR0Cj3HqQSe09Z5W2-kXJeYNIArzXvgDeiBb73z3gfABhUNhPmJgOSAeCCFQPQJfRhzDWEpAfnwp%2BKcX6kHfvgT%2BkBqFLRNnQtBN1LYDifFzPhdsABqvluhEHgKwGBzVW6ByQT-Nyf8y6H0AVo5WuiLxvA1mobORigimIUc3Sc8CRCIPbp3OSaj-7oKPpgkQT4bbOP0J0WA6AADiiB0IZ22C8bOZjc7%2BIgIE5BNiS4Q04RzSYT4Y66Kvkw7Q3QULQEYN0GRlx0A6A1GweYR0x45zRmLZRINVEyzxuEhx3Ca58JmIgU4zDeLoCMmKfeuAtYwhNNnSIQQpqkMoQOdGBcg40JQXQopQyuGlMHnwjQiBEDYAdk7MUWo2n7BwsgUWbtekd2lnWdRYEMHqSfKfWJrtELOiyXA15wTbos0GRo75WjgF8NHKsKgZNSAsDHtaWgiA5SngQE87pLzLFBPebjLyRySnZBYrDPhkRzQsEIK4wg7jqijhpSkO02w%2BawB5sQKyNMNjbIQZLFRxcDmyyhRE9SLFeEbH4WvMglBTSigMqsdZfpFlEB1NUTZvKen4vyV3QpIqvlioHCxHRUqRGmkefyEYcp4AUCqrAPQqxxmTO0KdPFOyrF7IKcKyFhrhmTBYk4qVnQCgUEdIgAFGY2BtCkPoN151%2BVG0FbQ-8Yp4BYUeZITAiLy5GtYjEqVGF03YVdUFaApAqByCUTq6xeqfXEtFf6sl5SpXnMuZy9AWoGmBDDPG8WibC7Jv2QMhtfrjlktGVKmpgRGCPJ0GrWAGt4DjKWJ4c1VS8jp0zhkjV-1SCSRrV6utI7c1NrsCxU5UrJAJDUFipAfa245klIuesOg3h6GLHNOcQA)

#### Code

```fsharp
type internal WorkingShard =
    | Started of ReactoKinesixShardProcessor
    | Stopped of StoppedReason

and ReactoKinesixApp
    private
    (
        kinesis: IAmazonKinesis,
        dynamoDB: IAmazonDynamoDB,
        appName: string,
        streamName: string,
        workerId: string,
        processorFactory: IRecordProcessorFactory,
        config: ReactoKinesixConfig
    ) as this =

    interface IReactoKinesixApp with
        [<CLIEvent>] member this.OnInitialized = initializedEvent.Publish
        [<CLIEvent>] member this.OnBatchProcessed = batchProcessedEvent.Publish
```
            

#### Result

```fsharp
type internal WorkingShard =
    | Started of ReactoKinesixShardProcessor
    | Stopped of StoppedReason

and ReactoKinesixApp
    private
    (
        kinesis: IAmazonKinesis,
        dynamoDB: IAmazonDynamoDB,
        appName: string,
        streamName: string,
        workerId: string,
        processorFactory: IRecordProcessorFactory,
        config: ReactoKinesixConfig
    ) as this =


    interface IReactoKinesixApp with
        member [<CLIEvent>] this.OnInitialized = initializedEvent.Publish
        member [<CLIEvent>] this.OnBatchProcessed = batchProcessedEvent.Publish

```
            
#### Problem description

The `[<CLIEvent>]` attributes get misplaced when the formatter is used on the example.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 04/17/2021 11:23:36 - 26674f958aaa77992dcc5fdfc1bd43ce0d71e919

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Thank you for reporting this issue.
