### ISSUE TITLE
Line comments after `null` value used as argument in function call are removed

### ISSUE THREAD

**Issue by rehael** [fsprojects/fantomas#1676]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMA3MAvGAGZgB2AruumAPS1hwC2TiZWAOgE4dne%2BYc6WAGcsAYVgs2OAvzIQIpeoymt28xVvJUaK5us48F2iPn1qZm0zup0GBq8ZtgALACZ7q6Ruc3KdhY%2BRrxaQYbykAA04FAi2FgAlmQA5iKoYADasRCgppAAJFgAngAOyGiQyVjROYqFuACG6BQVWXVaAAwxLpAAkmRI7ADKiQBeyD02rh1gALp1AL5TubOFJeUZVey1%2BQVNLW3ZLgCMK9qQALKNAB4AMsmId2wpWAAWuzYn7p2zC1rLOp5C5FMptSAAI1gsHQny0DWarQyxxs7nO8OGiCYiTgwjIAEEsABRQYAeWIDzIk1mSma8T%2BS3OwPhoM2lShMLh9X2iKONLAAGZ0fVhqVGtBEAAhRDEWBcRAABUaXEarCwiC4XK0WC4rQZAKZa1Z4I5sOFCMOyP5rmFEEgovFUplcqesAA7hroI14gNcLAvUlYGQtYodXrTP9FICtMzuRsTdCzUaDki0CjTABWW1QB0S6Wy%2BUAVVK5S4Xp9ZD9AcSQZDtPQ9IjjKBRvjW1NIYtqfaLgAbNn7WK8875eJ0N6RJIyGJddAsHK6yQ6Yh9VHDXs2%2BzE52eZa0-yAOwD3NOguIS5YiEaxfEZeriDRxSxu3G9vb8277vp7QADmPQ9PF1JDxG87ybA0Ww3ME305D8Uz5FwAE5-0dfFiHVLhJBYRpFzDFdwLXSCQU3KAOzg3krVObp%2BUHR18xdTFsVxWts1vBt8O0SMH3XYjoK3WDkwo-dTjOGiTzQjDGJxGEWP5PD7zAR9VigtlSPfQS9x7L40RogYhiwUkyAAFS4YoAHVEneUD2IUpSwGfKBX34pM9ngyiviFMSAPxLhYAoQYABFEHQRJsQw3DdQ4rQuMUniWRI7YanIzTvy0E4bRo64bj6YgjLeNgiXY4Y3jlLALPgKzs1cX4CO4oj4r4qBqh3NzhK%2BLNMtuAZiESG5SVLRp5y4IkblKeURBEGtg2zDMas45sY1bRrEpaoStNME5%2B06m4ACVEDgLh4HKyrrTm6KFqfJbVJW5Kv35E4j22vaDvgAA5CgmCvLhyT6dUmHSbMTlsuK42WpgqCSEKqQAMTlJhBowozoNuhCvj-GjnrleBLghxIocQWGuHhrBwoHaA3mVcUMIAfTdRIKo%2BYH6tB67mpR9yNuQ7afJVYpSS4B4xGOj4qrOxQYrshz1mWtmNLulwfgHLKecaPmBcSMR3s%2BjUfr%2BgH7qZxaVPBcH0Ehx5CeJxHkbl1HTHcUTehVtXBawHGzbxi24YR68yYplU5w1Wn6asw3LuNrZZdctbUsUdwdN6LKADVeUlZJ4GSFJhcXaqw%2BU3jWZ2dm2vtzzE9uaH-LnKa08GTPs9FvP7Ku8Eo5BVr1u0dwMvLm4AtgLAAHFsBGsbEAmqaG-5Wam6lpy1IE6OUv5dwOsT3H8clYRoAAa0lAOd%2BwERDOGVVEGAj7pv5NjG3miCjYLhNF-bmOV623pXsQN1N%2BwD02CR8oQUepkEslNfEgwLzay4PrFwN8oriwuvnBq10yK2w5l3R6vQADSiBEClBynlNgAxT6sEpNSWBYE76EQfsg1uRc0Ely7ujXuhVsQiDeFPFwudaqxWZi%2BBKqCl7y1RFzXooxUiYB8ikD6MgzKIAhJcBA5CbBwNni3GCLkX7LxcAKaiTsQopDIJXMg1cgyjEMYNCg8ojKwD0jIQaU1rK33OvfcOj8NGrW0TYAUjsbCQHxGbDUZAHG4FdKkSBX0gHJFAUGGBKjKEuOoW42hHji6dy0AKBOfj3ZJDIXcVUEJ4CNDHKITOn9v6PCcfAiAEsQb8OWoIrRwjTACjLn4gKGtGgQkwKwjWbxhjFHYLcKpaiI6VDYPAckZDhglEwJ45p2gBQ9z8SSSZFJKlky4OgYgkBRnuOcvMu2iy15%2BJwXgux7ABj70aCYkW18EkINcUglmT9NEsg7rHCAAp35%2BK3jcneZCRA%2BT8oMT%2BYhEDYw3o8Ue41JqxIiuGKhdUaEvNSQw9JigBSYL8TMrgOI3ZKJGTwxYsQ5hTCqCIaGk0MiqMWEAA)

#### Code

```fsharp
let v = f null // comment

let lostComment =
    f // comment
        null // comment
        v // comment
        null // comment
        42 // comment
        null // comment
    // comment
```
            

#### Result

```fsharp
let v = f null

let lostComment =
    f // comment
        null
        v // comment
        null
        42 // comment
        null
// comment
```
            
#### Problem description

Comments after `null` are removed – should be left as is, as it is for other argument types. Looks like `null` is handled specially.

I was trying to find how it is handled in Fantomas' code, but clearly my fsharp-fu is not enough to grasp it, so probably can't help directly with making a PR/fix. :(

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 04/17/2021 11:23:36 - 26674f958aaa77992dcc5fdfc1bd43ce0d71e919

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.
Comments are not part of the F# Abstract Syntax tree.
To overcome this limitation, Fantomas uses a concept called "trivia".
In short, trivia is the detection of missing information in the F# tokens.
After finding those trivia, we try to assign them to existing nodes of the tree.
See https://www.youtube.com/watch?v=FCrkUqCCzgI&ab_channel=nojaf for more information.

In this specific scenario, the comments are found and assigned to a SynExpr_Null node.
You can see this in the "trivia" tab of the online tool.

![image](https://user-images.githubusercontent.com/2621499/115879179-ab64a600-a449-11eb-9b25-215aa092308d.png)

![image](https://user-images.githubusercontent.com/2621499/115879243-ba4b5880-a449-11eb-8b05-9c5a9659323f.png)

The problem you are facing is that the trivia is not printed in the `CodePrinter`.

https://github.com/fsprojects/fantomas/blob/728e31e5d0ba158f8abeb6cc15803a6aa34ea2e4/src/Fantomas/CodePrinter.fs#L2657-L2694

`SynExpr_Null ` should be added there.

Are you interested in submitting a PR for this?
If so, please read our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#getting-started-with-fantomas) carefully.

**Comment by rehael** [comment]
I will try understanding this and working on PR – in case of any problems I will ask here.

BTW: Similar issue with comment removal in pattern match:

Before:
```fsharp
match v with
| x
| y // comment
| z -> 42
| _ -> 0
```
After:
```fsharp
match v with
| x
| y
| z -> 42
| _ -> 0
```

**Comment by nojaf** [comment]
That would be the same [category of problems](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#trivia-bug-example) yet there would not be one fix that would solve both problems.
So, I encourage you to open a new issue for each case you encounter (as mentioned [here](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#related-issues)).
