### ISSUE TITLE
Idempotency problem related to comments in `with`

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1686]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwAxWWAHXRuwQFcAbUi2MAXhoghYBcwmTtx6i%2BAJwCeI0bLAAzTAEsmAdyV8AFmCqRdM2eq0HRAelNhNSgIQmeAHzAoA-GACiADxIE%2BS2OkE8MFIAWgA%2BOzlFFSNtfUhIABpwKDxEPl90AHM8VDAAbRSIUDlIABI%2BSQJkNEgldD4kop5ygDdMJgYagubRAAZkuQhIAEl0JAaAZSUAL2RBoYAWXrAAXWaAXwXilfLK6ry6hqbSsvbO7sKhsABGbdlIAFlMDwAZesRXxGytE6GbgBMfRW61EW2aJQeFSq3UgACNKEw-qI2h0unkrkMAfcUZNENglHAmP4AIJ8NzjADy8ne6HmKwgiiYaRBm3ukJR0IOtQRsCROKgZzRlwZYAAzALhpMiCQAEKIeSwcSIAAKmHEOHSiHEyNkEi6rLB7N2XNhvP5JvO6LQmLki0lUGlxEQ8sVytesFU2ugmDSY1asB9vn8urE4gNclBPHBog5LVNh3NocFVpF1wArA7IE65QqlYgAKoEariH1%2B9ABoN%2BdDJxkdFmRtkQk37M2I5Ooi4Y0UANizOZdeeVAGEmL68MP-Hh9dA%2BErawp64hDdHjadW4n2wLO9aetcAOz9mWDt2IR74uHahdMhuyKMQGM8OPDBM8reW4Xd64ADiPztd%2BaTsSNYOvqy6NkazbrjCm58h2QpdjaooAJx-iQJLyHw2qTtg2CYAuYErg%2Ba5Qhub5wduCG7rasg3AMorZseAHKniBJEiGoHhuBd5NrGLYweRFqnKmX7-HcDEDhhWHiKxhJ8hxoqERBq5QaRAlQEmlEiUh1yAlmYwTHwlLoAAKlIADqGiaARXFEWAj47NB3Iae%2Bwmfjp-wShJx4kuIsAMOMAAiiBMEoBLSTZEY8ZBfFObC9SNFp7l7v89oMc8HgjPIJmaN8bjMogkyaEqfCWfAvwOoswLKcRqmcmRUAJfB2kpXINyZulLxjPISgeJSJaYHO4ieAQyp4Hg1YLum1XRSpsVqc5RyJR%2BiGtbRfadR4ABKiBwOI8BlRVopVXZDlgM%2BgoNUtzXJTRog3Iem07Xt8AAHIMNgl7iNSIxYdguQOjcp0kfV6mQNgzC%2BKFdIUOIeEZNqJkwUlq13TwNy-gxz1KvAjyQyoHyw-DEVZtAmjqsQ0kAPrqOV1nA3V8ZXU1KPUaKNyoZtvkapIlLiO806HdZlUzaI972SDTNgyzK1s9cQJZhl3OYLz-NKNO72fdqP1-QD7MM-NoOLRDTBQ4TSrE4jyOy2mWLidckDK6rAt8HjpsEzDFuDSTDFkxTs7ajTSh05ABtPvxi0y25qOigC2KbQAasKsr1PA9RZELC4nTVEuMy%2BzPHKzttyACXkOxlZABbO1Yp%2BM6eZyLYeOQt8WFzbokl2l5cvIFsB8AA4ukI1jRN-gN6K01N%2BdEdthR7ceSXHXl-j0MusS0AANayhqm-pHgxmTJqQEfSBoo3txYu8eHcWwUJUItWjEAAhtDuvYgqir-KfBet8SPVMFPV0AaGrCScY54tbiD1tcc%2BU8Lp7DBppeea1RAAkeg7AA0ogRABAso5W%2BGMQ%2BuBaT0mgUuWBM9DhR3vrdWOmNu4eHygSPAmhx7XGzrNWqhspaLUQdHOWWJOYO2mNkFgvksgfW%2BKVRAcJHgIBIUMGBOczpwNfC5OefDi6yDFPRB2JJQpZHQJXdA1d-DTAMYNBgyoTKwAMpIwak0HSKI4bnLh%2BcEGuWoTHa4Yp7ZDEdqbbUWBfCtE%2BP4LI4CvoAPqMAqc14yFKMlm4nhHjOQP1FGKeOy93bENeDgOE8BMCjlgBNbIb8P4fDiQVchN9BI3S8UMMUZc-GBXVpgOELBGHq00JMSQDQXiVNvJfGK18W6HG%2BPAakxDJiVBYHU-hcgxRdz8RSCZNIKmk3EEweQocEl50uu49Rnj5laKXn4zB2DbENDGNvTAxjhZn3ic45RFDalFw7lol%2BfjZRjnQBvYheBfL%2BXGG-aciBcYrw%2BMPfAo90BQKGEpJ5iT9nJMOakmh3i0F%2BOmeIQkrs5EDIvjwcWGwUirAWHUPAZAJp5BgRsIAA)

#### Formatted code

```fsharp
namespace Foo

module Foo =
    let a =
        try
            failwith ""
        with
        // hi!
        :? Exception as e -> failwith ""

```
            

#### Reformatted code

```fsharp
namespace Foo

module Foo =
    let a =
        try
            failwith ""
        with
            // hi!
            :? Exception as e -> failwith ""

```
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result.

This looks like being #1647 again, maybe?
I still think the right answer here is to retain the `|` character, though.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.4.0

```fsharp
    { config with
                SpaceBeforeColon = true
                SpaceBeforeSemicolon = true
                IndentOnTryWith = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
This looks indeed like https://github.com/fsprojects/fantomas/issues/1647 but with `as e` as a slight deviation.

> I still think the right answer here is to retain the | character, though.

Yeah, working on that part from a style guide point of view first.

* https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-trywith-expressions
* https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-discriminated-union-declarations
* https://github.com/G-Research/fsharp-formatting-conventions/pull/26

I'll create a follow-up issue to tackle the style change.
