### ISSUE TITLE
[Feature request] Support multiple files/dirs as command-line arguments

### ISSUE THREAD

**Issue by pbiggar** [fsprojects/fantomas#1696]
I propose we allow multiple files and directories to be listed on the command line, and for all those files/dirs to be formatted, checked, recursed, etc.

The existing way of Fantomas deals with this problem is probably the `--recurse` flag.

## Pros and Cons 

The struggle that I have here is that when I want to check that my project is formatted, the `--recurse` flag doesn't work for me. This is because I have many .fsx files in my .paket directory, and also I have OCaml files with the .ml/.mli suffix in the same project.

I have a script that looks through my repo and finds potential files to be formatted. Those files are put as command line arguments to the formatting tool, which works well with prettier, rustfmt, and ocamlformat.

The other way to handle this now is to call fantomas individually for each file. This works but is very very slow compared the other approach.

One alternative way to handle this would be to add a `--ignore` flag. This seems to be objectively worse as then we're going down the path of creating a directory traversal language, while there exist better tools for that such as `find`.

## Examples

`dotnet fantomas --check dir1 dir2 file1.fs file2.fs`

This would operate the same as `--recurse` except it would not choose the files via recursion, just take the ones listed in the 

Please provide multiple examples (before and after scenarios) and explain what rules did apply to achieve the outcome.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to Fantomas
* [x] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Hey Paul, would a [.fantomasignore](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore) file help in your scenario?

**Comment by pbiggar** [comment]
It would help, yes.

I do think that supporting multiple files/dirs on the command line is the standard way of supporting this, and certainly it's extremely confusing that when I enter multiple files on the command line and run `fantomas --check`, I get told that things are fine when they are not.

**Comment by nojaf** [comment]
I'm slowly getting on board with this but what would happen when you combine this with `--recurse`, would all folders then be processed recursively?

**Comment by pbiggar** [comment]
Yes, exactly.

**Comment by nojaf** [comment]
I'm less familiar with what `find` and `xargs`. Out of curiosity, could you post an example of how that looks.
Perhaps the `--recursive` flag could be deprecate in favor of solving this via the current shell.
I'm wonder how that would look like in PowerShell.

Another setting that will conflict with multiple files is the `--out` flag. Perhaps there should be a limitation that `--out` cannot be combined with multiple paths.

**Comment by pbiggar** [comment]
Sure, this example in inlined from https://github.com/darklang/dark/blob/main/scripts/format.

```
  find "$1" -type f \
    -name "*.rs" \
    -print0 \
    -o -path ".git" -prune \
    -o -path "_build" -prune \
    -o -path "./_build" -prune \
    -o -path "node_modules" -prune \
    -o -path "./node_modules" -prune \
    -o -path "containers/stroller/target" -prune \
    -o -path "./containers/stroller/target" -prune \
    -o -path "containers/queue-scheduler/target" -prune \
    -o -path "./containers/queue-scheduler/target" -prune \
    -o -path "_esy" -prune \
    -o -path "./_esy" -prune \
    -o -path "/home/dark/.esy" -prune \
    -o -path "esy.lock" -prune \
    -o -path "./esy.lock" -prune \
    -o -path "fsharp-backend/.paket" -prune \
    -o -path "./fsharp-backend/.paket" -prune \
    -o -path "fsharp-backend/Build" -prune \
    -o -path "./fsharp-backend/Build" -prune
| xargs -0 rustfmt --files-with-diff --check
```

**Comment by nojaf** [comment]
Thank you for that example. I feel like the boundaries of this feature are getting clearer.

* Extend the [MainCommand](http://fsprojects.github.io/Argu/tutorial.html#Main-commands) to accept a list or paths. (Both files and folder).
* The combination of `--recurse` would recurse all folders.
* The combination of `--out` is not allowed when there are multiple paths.
* The combination of `--check` should work as expected
* The [documentation ](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md) would need to be updated.
* [Integration tests](https://github.com/fsprojects/fantomas/tree/master/src/Fantomas.CoreGlobalTool.Tests) would need to be added.

For the next major, I would remove the `--recurse` setting if this feature is implemented. But that is something to follow up elsewhere.

Would you be interested in submitting a PR for this?

**Comment by nojaf** [comment]
Hey @pbiggar, I've published the first alpha with this feature:
https://www.nuget.org/packages/fantomas-tool/4.5.0-alpha-017
Please give it a spin to see if it works as expected.
Worked on Windows, that's all I can tell at this point.

**Comment by pbiggar** [comment]
I switched over to this method, thanks a million!
