### ISSUE TITLE
Currying a pair gets spread over multiple lines

### ISSUE THREAD

**Issue by pbiggar** [fsprojects/fantomas#1700]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBLAZmAMugzgC4B0AhgHYCeYAFDQLwCUtsA7uYgE4BypAtogA0YAK74u5fokbN8AB0TR0pADYBhUuPxhCAC0TkwANgA65M3SYt2XXgOFiJUmZEHgo4woXTkA5vlQwAG13CFAICKgAEkJKBUDIH0JXUIjIKIA3VRFkNBDIyIAGNwK0gElyJHJCAGV0AC9kEtKwABZUiABdVIBfZrCO6Nj4tETqlNL0rJUcwPyWgEZ%2BgsgAWVIADzwOHANfPQnFgCZCwe7IvtTwlZi43KgAI1hYFUPIqez7%2BdKj5feaxB8dBwFSwcgAQUIAFFKgB5TDbJqDCCYVTiM69ZbXd63EaPZ6vP7RaazPLIsAAZiJEEgNTkpGgiAAQohMLBOIgAAqkThSQhcN4FQicHIYi5YwbpYb3SBPF6CmmZT5zcmtalQOkM5ms9mIHBsLjQTSICoZWBG7xghURYWi0rnCKXSLYtK4mVywmSpUzL7kgCs6tp9MZLLZHIAqnIFJwjeJTebSJbyNaUWjEGLHRLJm6Eh7rR8fSqWsZA5qQzqOWoVJp8GowUQRdBCOyU2BUSp0fbMVcvdLcwT897ScFyQB2UvB7VhxCrQEPAXq9udgoOiBOiIuxV90Z5okF4ffAoADgnWtDurroOTi7TGbXWZu2-x8r3Q99xYAnKfGeDMPzOHWfB8KQra2umXbij22ZPrKA6viS76LMU5JBmeFaIACQIglaN4duBK7ds6vZ3P2L5eghRaLEsKFlogv7-phwIvDh5JgXeYDrgM0EkTucHkcqZLFgsvwoRUVSELC5AACqcJQADq6AHLhy6RKuHEPjiMG7vxhaCYsVI0ZO4KcLAIiVAAIogKjoEC-6gSK%2BGqYRG7EXiYzJPBAkjkJaooesGxlJgUn6OQUJ4TUujsoQCnwEpqqnBBmZQY%2BPEYOMnm6d5iwBn5mwVJg6AbLC0aJuyUIbHIHL4Pg6AscWfoJQRkFEdxblJIOFF6aUCxGIG-kAEqKOy8AxXFxatI1TnNS5rUyu1GUHuSCzjrlGyDXAnDwNwIh8POnDwmU-J8AE6oLOxnFgJuQypZAfAiCo3jWRwABi7LAV4XBSSRC2Id1J4oetw2rPdj0%2BIgr2cO9dmBtAug8gy-4APqsOgsW6JA50aa6MHzTpi1CV%2Bq3GbylCwpweBEKN6PqhNmPJZpN249mnVZT8yHFmsmzE6QpPkwQhDbbtXAHUdJ1LXTLUpW5d0PegT3g29ib-l98Q-ZRPzURz3O8xThDA7L8sQ1DC4obD8NNlwyOowcEszVLc3pXjv0FEcIkc-5ABqnxMj48A%2BL4VOtrTiX3vT2OM47zNeYekRHAZ7ubM9ZlNrV5A%2B5U-uBzTk0RGpF1XVKEceU76su75CcbOZsCEAA4og0IVVVNVgln-o510zlcfbpGelHmUxxERw5e7INy2DTKgtAADWTK8tP9f4JJNRSJeO3XuSS6ObnneXa57p8X3%2BMtEcvUodwiCsPLLKEKwiAGCriCWQV5CKan4KVLOQucGLxab7bXcMzctpQ%2BztY4rQ5gAaTvnIQKwUDAVGXgIRErY-4h3UmHLcRcOrR3JEcf6FcwpAnwLoVu4125gDzljTBQCD43BZgPCARxCYczqH4FQdFOC%2BB2gYaKiAHirAQEiX%2Bt40H5z3j3bB-dyQUnZi0SA4JrK%2BHIEncgKcwR1CUYmEQHIpKwDEjwxMqcUEiKaklSWgD95kRAaXSIFJNZyIUf%2BSQ3gMh6jBL4T%2Be0n4%2BFfvWYxeF-671mhItWXUCgUjdnI-W3hEQ4H4A8eApAqywBqn4c%2Bl8wb%2BJUtvaaADw40KsXQnBxYKTxzkeZAgpAHjsMIQQXQNRKDVE2FkreHdclBO7qMAw8B4SIhqLEdhkij6lApOXORMIekIkyTDTgKhMAY1EVQ66BTe5FKkSU4ecioGIBgZUHhFRZ4UFhi0wJBccy8UKTieh0jT4cwnhQKeiJ8DGVMpUc%2BRBEDwGiWPDg5VKqIGqqnH%2BLQ2KLIwcsyxqyrnFJaBScBcj%2BmcGBHrQRJzRHuE6M0RI%2BBno1UCH-HoQA)

#### Code

```fsharp
// Actual code
if List.any ((=) (ownerName, username)) specialCases then 6

// Reduced version
((=) (ownerName, username))
```
            

#### Result

```fsharp
// Actual code
if List.any
    ((=)
        (
            ownerName,
            username
        ))
    specialCases then
    6

// Reduced version
((=)
    (
        ownerName,
        username
    ))

```
            
#### Problem description

I would expect this code to be kept in one line:

`if List.any ((=) (ownerName, username)) specialCases then 6`

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 05/01/2021 14:37:19 - d8e76d456b7eda5419e5eb836a793fa5c6ab491a

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
This problem was introduced while fixing https://github.com/fsprojects/fantomas/issues/1341.
I believe we miss a check whether the code is short in 
https://github.com/fsprojects/fantomas/blob/0237e8fc240d6713e82cb615f5cc9a0c50937d1f/src/Fantomas/CodePrinter.fs#L1958

we want something like

```fsharp
        | AppParenArg (Choice2Of2 (Paren _, _, _, _, _) as app) ->
            let short =
                match app with
                | Choice1Of2 (a, lpr, ts, tr, rpr, pr) -> sepNone // TODO
                | Choice2Of2 (a, lpr, p, rpr, pr) -> sepNone // TODO

            let long = genAlternativeAppWithParenthesis app astContext
            expressionFitsOnRestOfLine short long
```

I don't time right now to provide a complete solution but you might get the idea.
Would you be interested in submitting a PR?

**Comment by pbiggar** [comment]
> Would you be interested in submitting a PR? Gonna try for an hour or two

**Comment by nojaf** [comment]
Great! You can start out with going through the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#your-first-contribution).
The first set of [YouTube videos](https://www.youtube.com/playlist?list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K) might also be useful to get started.
Let me know if you have any questions.
