### ISSUE TITLE
Breaking method chain in the middle of an `if` statement causes offside error

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1712]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYrLGALwA6AdhBHgC5gBGAhgE5lU1dgCWAZmABKiAOaIAHgApykHLEoiwchUvmLl6tapUbtmhTICUAOgCyzOtAAWkgM4mAylmjREt22DpXElTt38AcvKIfv6IOLb4DrDo%2BDJWPDKQADTgUJF0dDwKtqhgANppEKD%2BkAAkdACeAA7IaJDZdClFNOUAbsw4WHUFLVwADKn%2BEJAAkpRIlHQOPABeyEPDACx9YAC6LQC%2Bi8Wr5VW1eQ1TzaVlHV09hcNgAIw73JDm4gAy2YgvPiJep8O3AEz9VYbLjbFolR4VGo9SCMYg4X5cdqdbp5a7Df4PJEORDoHhwZQAQToAFEJgB5PhvSgLVYQPidSLArYPCFIqGHepw2AIrFQc4oq50sAAZj5Iwc1WYrgAQog%2BLBWIgAApsZixOiIViI7h0VjdZmg1l7Dkw7m8k0XVFodH%2BJbiqCS6WIOUKpUvWAAdy10GYkXGbVgvqy8h1XD1Bv8IJoYK4bNapqO5rD-KtQpuAFYHZAnbL5YrEABVaq1Vi%2B-2UQPBnihh0MiKIQ0x41nA5m%2BEp5GXNHCgBs2dzLvzSoAwjg-bYR-JbBHoHRFSn6YzG1GWeCTW2kx2%2BV3rb0bgB2AdSvNuxCmXGMLWLsD1pmro3r1vQrc8zsC7s24UADmPztdBZTsoN53iu3DRhAsY0PGIyJly26WoKPY3AAnH%2BriEnwmqsFO6DoMwN4RmBXAQWAUG7M%2BnJQMmO4fnutrcLcgzCjmJ5DmeOJ4gStbCqBTaQS2kKbvBb60WmyF-PcLGDph2GcfiPI8TcRH8WRgnssJ1EIWc4lfjcALZuMkx0OSlAACqsJUADqPA-HWy6qeRYAwfymmwtpkK6fufxitJbGEqwsBYBMAAi4Q8Hi2GEfqxE0KRTkufsL71I075eQxXC3PaLHPKMfBmd4lAkg2DhWIqdA2fAdnCksQIPs2T5CclUCpWJSF6X8WY5cw4jjHwPDiOSpYWIqJLiNUSruDWlA3hmdXgWucYbs1xxNG1n7ef4tz9t14jCHArDwJV1U3LVjnqQmbmtYhG0ZTQtxHrt%2B2KvAARYOgV6sJSoyauguQOrc52NRpK3oLgWQ4O8RCsPhmRamZL7rfRwq3L%2BLHPYdpjgzwkM0tDsNRdm1hqnOWoAPqejwVVWJAQNLZRMLXTp7WbYxaG7QFrDMJU5KsG8M7HTTDpnfVAnA5dK1M55LN3RAgLZs8nPc7z-N0G9H1at9v3-SjdPQctVGQGDOAQ1DioE-DiM3cjNz-FJNyQErPN8zwM5YybONmzDFiEyxxNc6TrAU1TPx6xRTWG1L7LpcK-yYrtABqgoytk8DZCIgs3iLC2PvTEeMycSPphivkO88BDBXO00pxM6eZ8L80kYt%2BsM0cUcJjHtvZWXPUhbAdAAOKIKS42TbY0318Kc1h85BvtqJ1vF-4-xdWX2O4y6cjQAA1jKAfb8PtimQ46qIEB70zfZDYz4lcFaQvzO3bHO0OwEiCehvcp0N6PgI7UYX9UoLZaahIJgXg1qwHWNw%2BKizUuLWCbkaKLwksvR6DsADSiBEDVDygVHw4wT6xGpLSaBDlYEJTnm3QuyCOrLzRj3cQxU8S2CsJPU6jc4rN3DiDQ2SDH42wxOzB2MwFB4ACiId6PgKqIEYKYBAJDhgwJzg1POPD54Wn4UvbgIpmIO0JJDEQlAK6UCrvIGYhiLBYCVGZWARkpEWGmiBMhyixaqIlrwjy0cZbChFPbYYjsTZakoA4toHw1DgM%2BgA7IwDpxOOvuQi6CCVp8Olk-G4Ip45rw9sQl46pGDwGYGOWA48FBvw-u8OJ94XFwLcUkjxD9UkCP8CKUu-iQqu2YIwPATDXZWAcJUKYPVKmxQgPFRJrkVo%2BHgJSYhDgqh4DSt49J3d-FkmmVSCpRNWA4D4LTBJ8CJn1I0Y0rRXARSr38Zg7BdipjjD3swExQteLOKbrnFu%2BdXzHK8Wk4YIoX7%2BJlOOSg29iG2ACkFCYb8ZyIHgO7U2NIxoTTcOPWJDoVL7NqYc9RiyfnNLQf4uZrB8R0DkUgYZjk0hrEWA0WwBBx55D4psIAA)

#### Code

```fsharp
module Foo =
    let bar =
        if Regex("long long long long long long long long long").Match(s).Success then
            None
        else Some "hi"
```
            

#### Result

```fsharp
module Foo =
    let bar =
        if Regex(
            "long long long long long long long long long"
        )
            .Match(
            s
        )
            .Success then
            None
        else
            Some "hi"

```
            
#### Problem description

Not really sure what the best format here would be. Maybe:

```fsharp
if Regex("long long long…")
    .Match(s)
    .Success then
    None
else
    Some "hi"
```

assuming that actually compiles.

#### Extra information

- [x] The formatted result breaks by code.
- [x] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 05/09/2021 13:45:10 - f10b822434c5223dbf01c1d94ab734cb8a467c1f

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Maybe be can go with
```fsharp
module Foo =
    let bar =
        if
            Regex(
                "long long long long long long long long long"
            )
                .Match(
                s
            )
                .Success
        then
            None
        else
            Some "hi"
```
as suggested in the [MS style guide here](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-if-expressions).

What do you think? It would be easy to get around those offset errors that way.

**Comment by Smaug123** [comment]
Oof, I find that extremely ugly, I'm afraid! @TobyShaw I don't suppose you have any cunning ideas here?

**Comment by nojaf** [comment]
Well I feel like there are two parts to this:
1. How Fantomas deals with the expression
2. What Fantomas should do in case the if expression is long or funky.

As for 1:
```fsharp
Regex(
    "long long long long long long long long long"
)
    .Match(s)
    .Success
```
might be an option.

When it comes to 2, I do like the 
```fsharp
if
    longExpression
then
    // ...
```
style, it nicely highlights that you may wanted to go with a intermediate let binding instead.
And it also has a bit of rhyme with `try/with` or `match/with`, though indeed quite far fetched.
Any chance that helps? I'm open for feedback here, life is easier with my proposal for 2 as it plays better with the offset rules.

**Comment by Smaug123** [comment]
I guess in real life an expression that is long and complex enough to format this way is going to get changed at review time.

I think I agree with both your suggestions 1 and 2; it's just the implied combination that makes me sad :P perhaps it's fine, though, and we'll just have an informal rule saying "you should never write code that falls into this case".
