### ISSUE TITLE
Appending two lists with `@` fails

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/fantomas#1719]
This only appears to occur if the second list has multiple items separated by `;`

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBtMAmAdAbjABYcwBdMAATE1wOLMgBpwoBnRAFw4EsA7Ac1apqLCKAgSoAEg4BPAA7I0kPhyaiJkKQDcAhgBsArkpGTJABmZnNASV5JeHAMrcAXsivWiGiKQ0BfTzEfaTlFYRVHdWstPSMTdBCIAEYgs0gAWV0ADwAZPkRcxAEOAAtor2SscxC-SUCNcXSZBRNIACNYWH0KyViDY2FEr2w0vqdEAFtuOH1YXgBBDgBRewB5ADN83g8ksA2DdlqAtKa%2BlvDlTu7ezR0BhL2AZjHNJ3ldaEQAIUQN2AATogAAq6AG6SacRAA26SDgA4zHeqnEJaMJta49V79eJDPaEV4QSDvT4-P6AwqwADu0OgunYdm0sDpPHmsIk8MR1jqEgakjOd3REUx7JxgzQwy8AFZCVASV9fv8gQBVeSKAF0hm8Jks7hs2UHfRHbknRqoi4YrpY81xcWmLwANllxI%2BCvJQIAwvp6awPfNWJzoBxAeyIIbjWYeRA%2BRIBUSLcKraL7riJXsAOzO%2BVkpWIDJTdrQ0P7Q6IJG8lExBNXJPYlN2yXWAAcWddOYpfrmvGL4bLJuRZqrQprNzrtseIwAnK3SQsNhxoX7JpNdMXOX3I6b%2Bebh1ARWOHniRslLHsXaTFRSJtNZvq9r3y9HK81dx1azbD2nj6kz9m5wuAWvGZujvEZ10fMAY2CIdWkTUcP1Te1rCqZ07AcDg1l4AAVAFZAAdW4Moe1LCCoLAONQlgkdrSrccj0qF5fzbBYAVgQx7AAEUQfRuGmAC1wRDdJCjSDn3OV9VGTOiv0qAkzyybIbA2LDSmKZYjUQJxSkBDgCPgIjZUIGp%2BwrQcXyoqBJIPRDGzMZIZXknI7A2bhsjWdVdGDAFlmyeQgVYVg9W7WUpWMzcB23GDLksqJrIbPZkidRzsgAJUQOAAXgPSDPxMLhK3WMdwsyI1DiidKkzZK0oy%2BAADlDEmQsAU2GwF0mIRZWSUixMFYrJkMfQeB4nYADFARXLhoSw2Cyvo5CWzParAXgDIBqGgoxoBCb%2BOdaBSjBT4AIAfSpbh9PKbqzPE4qrIQ%2BLj2nZKWPBWQ1gBfIA2y8pDLyiQRLIii0Ru2K7vK6xqmdBTnt0V73u4AN6sa6EWrajqEsuyLzOiyB%2BsG7hhsQTbtqmmbQbmswsB-EZIGh2GPo4Va8YJonPJ2s89oOoNoROs6iIxwqoraW7aM-JCKawSGcgANQeb4%2BHgPh%2BC%2B4sjP56CsaFkGRZsvYsEY6mFJG9igyCuX7EV5WfrV8iiux4XmmksXJCwOSDZyDjYA4ABxTgfL8xAAqCy29lC63AerPd321%2B6vCwByDbW-GCm%2BOZoAAa2%2BcF084VhMKcCFEE7BrgvvEiTKfK7eux-cyZk8Gkup2rECpAnfg4GlimmxQuJc3hCKChZ7HzJGATRkYH3L0TK-jV8a%2BjsGKcq6mAGlEEQeQlJU4o7HzyFtl2cey-C0zMeuu2tYd0XbOdha3eydTplYUpg5GVXJ4B23LXg%2Bfyedx7qZcAIfQiAWL8AasUXSiB2gZAQAfLwE9j4V1PlXL%2BNFL46xGE8U81MFg8X4LwI2vATbzBcPgzyhggRYVgGhCBnkgrEQ0mHT%2BcE0HnEdtfCQTwqZeBpoNaEvA6HaEpAIYeTUe58H7v6BhEZ8oRQFhrFhUkr7PAlvJRO%2B9cgQnaPAXQXpYCBQEE3FuBRpFCT%2BgVdWZ9UFKIwV4J4%2BseEcXhrodowCH7w1KE4WQjgcimKYYLCIxR4CbH3k4OQwCbEx2sE8V2PDVjBK2CY3aAJ9AbEgP4hR1FIkL0kE8eOPDV7rxoY4OwmddBEO%2BqXRh78eoz2KnPdBUSzBPAbjwlO5S0771YCxNi9gm4BkQCtROBM-b%2BUClI2U4EanT0otXKOjScmcKXjwsJAIZgM1gX49%2BLBSCeBUKwEagVhAPn8EAA)

#### Code

```fsharp
[ 2.; 4. ] @ [ 2.; 4. ]
```
            

#### Result

```fsharp
@ [ 2.; 4. ] [ 2.; 4. ]

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 05/09/2021 13:45:10 - f10b822434c5223dbf01c1d94ab734cb8a467c1f

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello Isaac, thank you for reporting this issue.
This might be related to https://github.com/fsprojects/fantomas/issues/1188.
I would need to debug to see what is up here, might take a stab at this over the weekend.
