### ISSUE TITLE
KeepIndentInBranch not respected for values

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1728]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPMAvADoBORAdhFdVQJYBmY5sOAFKRTVzSYgM4BXdFgB0ACQCGfAEr8hWPgDFYJdmUrdN1ANpgikdBIBGidPo4atVvZFoAHAG4AWc%2BuvX9AWwnQAgvHhePj5XTnctL0R4WgFPUMtwri8JcgF6HywBXjJIMABdC0SIAEpC62KwLAALRHIyxIA5WHJEeq1TPlb1Ns1MHEMTdEIwPiwSWnIAczAg%2BRFtfQHTfQK3az6we2dh0fGpmblhef0tl0hVsKsmlsgAGnAoTqwsCcm%2BVDBtB4hQLkgAEiwAE87Mg0LZyFg7t8qACHBJ0AIwZ8YdQAAz3TSQACS5CQkIAyrQAF7ITHcJyo-IwgC%2B5J%2BVIBwNBHwhUPpsP%2B8MRyK%2BmgAjBzqJAALISXAAGQmiAltUm1WhAoATGiqXlaRzfjQmSDkZAjLBYOhFdquQikR8%2BdwlULYQTEJ5aHB0M1fFgAKJ4gDy9ClN1tEHS6E6ao1MK1wsButZBqNJsj3ItaCtXAAzAGoAS7D5EAAhRD0FSIAAKEhIEk82EQJHjNDGSND1Dp4cZUZZ4NjxttcPNvKpECcGcgWZz%2BcLvAlsAA7tXoFJELiHLA5y9mrXqPXEI2qM3qBHOcy9Z311AzTzLf2wABWIcj6B5gtFgCqdlBJDnnUXy4kq-IJ8DCIhlw6pNpqraHjGhpdq2iZ9poABst7ZveY5FgAwoYwRoc0uwCNAWAqP%2BYBBkBNAgTuYF-G2R5QSePbnsml4AOxIaOj68CKDomDWGYkVuwFhnu4HRh2tHdmeSYopoAAcrEoexiDYS6f68YB-FkYJVD7hAOrtlAx7ibBF6aAAnHJiC%2BPQWDVthnjeERm7bhAu5acJen6mJMG9sZ3D8hil7DshD7jog9qOs6a6qcG6nUORzmUaaEGiXGhneYxAqCgFd4WVZ1ZhU6RqRZejkCaBLZUUl%2BmeVRRnpb5NoBbi%2BJYF65AACokECADqtAKlFpGxZpDIVSJVUpV5DFSb56ZZUFvgkLAAh4gAIqYtCOtZPHFSQDalRR5WJaNbJ0RJcG%2BYOAVirg2L0G1NTkO60UElUKhYD18B9ZeTiqnt8UHZGlXHalk0pjQ-I3pd4q4vQtC4F6b4-io7q4HYQR8LQRWaFeP0aWVQkje5EzshNkmg9Q-KIZDuCyHAJDwO9n2aN9TlgC5w2HYTkInbVU1cPyLFUzTKjwA0sTcT62LWZ47wZvyLNs2A2mnoDnjyLQ6DSsoJDeM81ZtdGwOk5e-KyQFQt0yKasay0Ws65tREwFUZYZNWAD6U60B9VSQPLCUA0dRPc2lvNg2ZVPzeWQJeiQUqjAz3sZszv2s37B4B1zhtnVwKpDldEcSFHMe0KMoueOL9CSw6MvG77-1p%2B5qvCOrmsqHbesGyTWc0EqmVYvnhex1gltN9biC2z%2B9tDtATvlvhbse17PvJwrSu6XqgeZz52cNViV0AGq9rmEzRFM8dEUnuP7fjHPrxnndb93M27%2BKihLfhGPkEfeKvGfic44NeNXIE1vsTGqwcyZUCVBdZ%2BuBlosAAOLYGRqjfg6Nmi-0vNjWu19-buQMvfOq2cIa7yttKXMLpoAAGtcyz0odgPgrUCQVkUkaWIKlLx8WwUAm%2BkFxpgJBpeJUlMsQNEQFOUe%2BYsAzlqPrUEq0YbkF6h-XweJOJl2rNXTQnDl6px0tRXh0F%2BFG00EqAWWIADSiBEB2BundWouImGVj9GSDhakuHs1wSAoOAiTGmxgY9R0fAqgYKZv-KgcUU51z0YDfBRiu7UCVGHLERIpiYHmpMWItQ3qICMCKBALitFuJ0VE5WR1Ymmh5hAiAqZ-J9w1pMcgr9yDv2aESBpP4siIDarAJqWSfwfyItoy%2Bf0cH1xonwip4DLypl7twSAvhhDVnIP0hwMpmiTDUdxeREwlE4UGUU4ZkTRnRLKdVSZPjuCph3nM4eLxnESgrEYeAEgMKwHRlMUR4jpT7Oiu4xWblxmGPOcYy5T85nLWLsYTAATi5VAJECSE4ofkDXCUNf5wDWS1HgD6ZxBJgSYG8SCtM0C5memxb6b5U8SDoHoEvQ5K8AUGMJfEqgqZiFzMsdY3pkJcQ0JSNPByO0YqosAR4sZTLN6EJoKmYRczyEpEoc4vg81Fp4lEaMKItzm4tGQWjD%2BmjuAlXpbo0peCzkJimZoVMZi5l4vGPhPJSBkXCogBEmkDw8jklsEodGHxOE0iAA)

#### Code

```fsharp
let x =
            if not (
                result.HasResultsFor(
                    [ "label"
                      "ipv4"
                      "macAddress"
                      "medium"
                      "manufacturer" ]
                )
            ) then
                None
            else

            let label = string result.["label"]
            let ipv4 = string result.["ipv4"]
            None
```
            

#### Result

```fsharp
let x =
    if
        not
            (
                result.HasResultsFor(
                    [ "label"
                      "ipv4"
                      "macAddress"
                      "medium"
                      "manufacturer" ]
                )
            )
    then
        None
    else

        let label = string result.["label"]
        let ipv4 = string result.["ipv4"]
        None

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 05/16/2021 17:45:16 - 76ffe36ad44388dcd3b0c4ddc66c1838a98f7e80

```fsharp
    { config with
                KeepIndentInBranch = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
@Smaug123 for a single value (not a function), it is expected to keep the indent here as well right?

**Comment by Smaug123** [comment]
I'd say the last case should be unindented, for consistency. Thanks for finding this!
