### ISSUE TITLE
Fantomas in the wild

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1748]
Hey all,

I'd like to get a lay of the land in terms of projects that are using Fantomas.
More specifically, projects that enforce formatting during CI via [`--check`](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#using-the-command-line-tool).
Having a list of these projects would be very valuable when declaring new versions as stable.
Next, it might also serve as an inspiration for newcomers to set up Fantomas.
And overall it can increase general confidence in the tool.

I'd like to bundle the list of projects, so feel free to respond to this issue with your projects.
If possible add a link to the project. When it is not publicly available perhaps you can share some numbers about the size.
I would like to repeat that the enforcement of formatting is a must though 😊.

I'll start:

* [https://github.com/fsprojects/fantomas](https://github.com/fsprojects/fantomas/blob/master/build.fsx#L480)
* [https://github.com/fsprojects/fantomas-tools](https://github.com/fsprojects/fantomas-tools/blob/master/build.fsx#L186)
* [https://github.com/nojaf/ronnies.be](https://github.com/nojaf/ronnies.be/blob/master/build.fsx#L77)
* [https://github.com/G-Research/TypeEquality](https://github.com/G-Research/TypeEquality/pull/25/files) *almost 😅*

**Comment by pbiggar** [comment]
We use Fantomas in our CI build via CircleCI at Darklang:

- repo: https://github.com/darklang/dark
- installation: https://github.com/darklang/dark/blob/main/Dockerfile#L350
- running formatting scripts in CI: https://github.com/darklang/dark/blob/main/.circleci/config.yml#L290
- specific invocation of fantomas: https://github.com/darklang/dark/blob/main/scripts/format#L192

**Comment by adz** [comment]
At mitimes (mitimes.com) we use fantomas in check mode on CI. Looks like this in script:

```
#!/bin/bash
set -e

echo "Checking formatting in src..."
dotnet fantomas --recurse --check src

echo "Checking formatting in test..." dotnet fantomas --recurse --check test
```

I don't think it allowed passing in multiple roots, so we just call it twice.

**Comment by nojaf** [comment]
Thank you for these initial responses!

@adz in the next version of Fantomas, we will allow multiple paths to be passed down to the cli tool (see [docs](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#multiple-paths)).
This will speed things up.

Thanks @pbiggar, this will be a good repo to check before I can mark future versions as stable.

**Comment by nojaf** [comment]
@baronfel recently added Fantomas to [https://github.com/baronfel/Giraffe.EndpointRouting.OpenAPI](https://github.com/baronfel/Giraffe.EndpointRouting.OpenAPI/blob/main/build.fsx#L671-L700) 🎉

**Comment by dbrattli** [comment]
[Cognite](https://www.cognite.com/en/) uses Fantomas for [github-workflow](https://github.com/cognitedata/oryx/blob/master/.github/workflows/build-and-test.yml) in [Oryx](https://github.com/cognitedata/oryx).

**Comment by JonCanning** [comment]
I've just implemented this check in all our repos, building on BitBucket pipelines. One of our devs is using Rider and he was getting formatting clashes with VS Code devs, so by installing into the repo he can format before committing. We also auto update fantomas (and paket) in our build script
`dotnet tool list | cut -f1 -d " " | tail -n 2 | xargs -I {} dotnet tool update {}`

**Comment by nojaf** [comment]
Yes, we currently have a bit of a messy story when it comes to the different versions inside editors.
In short, each editor does its own thing (Rider uses a custom fork, Ionide the version on NuGet, Visual Studio a git submodule).

To solve this issue, we'd like to make a change to the command-line tool that editors can integrate with a pinned version of Fantomas, listed in the tools manifest. I haven't created any public notes on this idea but it is in scope for the next major version.

**Comment by nojaf** [comment]
Hi all, we are getting close to calling 4.5 stable.
Could you please try out [the latest beta](https://www.nuget.org/packages/fantomas-tool/4.5.0-beta-003) to see if anything broke on your end? Many thanks!

**Comment by nojaf** [comment]
@JonCanning following up on this in https://github.com/fsprojects/fantomas/issues/1844

**Comment by nojaf** [comment]
Hey @knocte are you able to share any info from your side on this? I have a strong hunch you are using Fantomas in a professional setting.

**Comment by knocte** [comment]
Oh hi @nojaf. At my company we have tried to use fantomas since about a year ago. We found many problems along the way, filed bugs, and contributed PRs for the bugs that were blockers for us. But as you might imagine, we give low priority to the work around this, so we advance very slowly; that's why we don't use fantomas yet on our **main** repo (size: about 20k LOC), but we use it in 2 other side repos (we fail the CI build if any commit doesn't align with what fantomas dictates):
- In one of the repos we currently use 4.4.0-alpha-008, but we plan to upgrade the version soon (size: ~1500LOC).
- In the second repo (size: ~4300LOC) we're using a forked fantomas which is basically a 4.5.3 version with 2 features added:
* One related to generics normalization which would be unacceptable to contribute upstream because it's not compatible with units of measure (but as we don't use units of measure, we're happy to use it until we find a better solution).
* One related to parenthesis elimination whose PR has been rejected. We have thought about converting this one to an FSharpLint rule (so that the bigger F# community can benefit), however we prefer a tool that can fix it automatically for us instead of a rule complaining whose fix needs to be manually committed.
Let me know if you need more info from our side.

**Comment by nojaf** [comment]
Hi, thanks for sharing. This is interesting to hear. I understand where you are at. You can really only start using Fantomas if everything works out and for a larger codebase, this is tricky to nail down and for each new release, you need to check again and again.

As for the refactoring items, I understand that a tool is better than some linting warnings.
Have you ever consider writing something using the Fantomas core API? I've made a small sample to illustrate what I mean: https://github.com/nojaf/fantomas-refactor. If you are able to update the AST, you can print it out again with Fantomas.
This way you can perhaps implement what makes sense for your team without maintaining a fork.
If you ran those refactorings once, I would expect that Fantomas will honour the changes from then on.

**Comment by nojaf** [comment]
Adding [https://github.com/demystifyfp/FsToolkit.ErrorHandling](https://github.com/demystifyfp/FsToolkit.ErrorHandling/commit/732ab1f7b98acffd25469848473a0cbe7da1dcc3), thanks again @theangrybyrd!

**Comment by TheAngryByrd** [comment]
@nojaf also added support for `--check` on [MiniScaffold](https://github.com/TheAngryByrd/MiniScaffold/blob/master/Content/Library/build/build.fs#L596-L622) so anyone that makes a library using this as a template will get it starting out.

**Comment by dsyme** [comment]
Using it in 

* https://github.com/fsprojects/FSharp.Formatting/
* https://github.com/fsprojects/FSharp.Control.AsyncSeq

and very slowly beginning to use it in 

* https://github.com/dotnet/fsharp

**Comment by nojaf** [comment]
We are bundling these now on our [homepage](https://fsprojects.github.io/fantomas/#who-uses-fantomas).
Don't be shy to submit a PR to add any new ones.
