### ISSUE TITLE
Creating anonymous record based on a function call with a list arg fails

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/fantomas#1749]
Using Fantomas v4.5.0-alpha-019. Unfortunately I can't reproduce this in the tool - I suspect because I've changed some options (.editorconfig below), but I've narrowed it down to the following:

```fsharp
module MyModule

type Foo = static member Create a = {| Name = "Isaac" |}
type Bar() = member _.Create (a,b) = ()
let bar = Bar()
type Thing = static member Stuff = 123
let x = {| Foo.Create ([ bar.Create(Thing.Stuff, Thing.Stuff) ]) with Age = 41 |}
```

I've tried removing various elements from this, some of which make the code valid e.g. removing the parens around the list in the last line.

```ini
root = true

[*]
indent_style = space
indent_size = 4
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = false

[*.fs]
fsharp_space_before_lowercase_invocation = true
fsharp_space_before_uppercase_invocation = true
fsharp_space_before_colon = true
fsharp_multiline_block_brackets_on_same_column = true

[src/Tests/*.fs]
fsharp_single_argument_web_mode = true
```

**Comment by nojaf** [comment]
Hey Isaac, could you please use our online tool anyway?
If you click the menu button (when in the Fantomas tab)
![image](https://user-images.githubusercontent.com/2621499/119265476-34a4ff00-bbe7-11eb-8c49-63ea894d6658.png)

You can tweak the settings of the online tool:
![image](https://user-images.githubusercontent.com/2621499/119265490-4686a200-bbe7-11eb-8c42-3c4f6177688a.png)

Thanks

**Comment by isaacabraham** [comment]
@nojaf ah, thanks - i didn't notice that.

```
https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAsgJ4HZ4A6ATuQHZW0AuRADvgGKyxgC8YAzgwCGDAJbQw6ROgBGiSmADClRMPyCeYYAB8wAOUGSN5SAEk%2BgwdGNgtAX3o0mrMACFBlABQBKDZJlywAH0AOiUVBnwPQQAaaR9ebwc8BjBpdw03Ty8HJ3wAFQALERoAcw0BYTEJKVl5AGUGLAAzJo0ARgAmAGYkxBSADw1tMA5YUOVVMA8AbVT3cfDED0LikuCG5qbosBXS9caWnwBdHwB3EQYCsABBEvxeABY2m1tIaPAoPj7RUr5UMGmHwgoAgoKgABJcv9IMUGG8gaDIOCAG6CHBYZBoQFgsEABneOMRJhoSEcdREAC9kATCWAHgiIEcEbYacCGRCoWgYY54YSkaj0ZiAeyIG1WTjIARBP0ADLFRAyxClS682mdXHsplglkIkESyEsIWQaScHCqsH8tEY-7Y2kdcUWupSMSwHCwGjXBgAURJAHkmnKaNSRWAmmivprmeK9RaDaxoSbXebESirULbYSug7EXVmJZEC5EE1YMoAAruAx9OTJsEMSgYyPa6PspGcqCJs3Zy2Cm0hh7ZiCQXP5wvF5Qy2CnOTQQRfYnI2Az0TumugusNwla0E6sExlNt42m1fd61YkMAVgHUGH0ALRZLiAAqsxWJQZ3OaAulyIV1f14hG23Zs%2BTjI0O2PVMezPWkwAANivIc81vUcHwUHBZz4BR3QEetoAYEtVwgMMcAjTco11FtQITI8u0g09hRggB2BCbzvMdEAIGpqyvYjSJxLcIB3UE90HKiuXA2iBXojMcQADhYpC2NQ11fxDf9AME4D9QPCTKKk9MQwATgU-NriaCJKCw9B0EEQiwHUsimwokCdJovS017GC2nxENEJHe9lCddAXTdGg7N4gDHKA5ztMNaik0kjzoLVMVfNYsyLKCkLVJghz%2BPI3dKNchL3Kghi1XtXziVJBhfRoPJKCIAB1C4CnC8NIvypzCpcuLxLckD9M8tUszSxTrkoWAsBJAARRAcBEYKLLsvKwQEsAhLZXr4y5WEIKG5LCTaftfKlfoTCaQolS9EjEDqAoSwYFr4BVK8Hg1KLNJi2MDz2xKypksE2kvU7pWJJoRH6X1X2EEsvX6ZhlD4PgfzCq9zw%2Brrop62KdqgP7SukkM2ng0H%2BgAJUQOBKHgZ7Xr7TG1oK4Sir6-GeX%2BomvOYsnKep%2BBdCwfxKH9EwInQP4rzaDSNq0n62cgdBcFEBagw4SgbIYCy8jizmDK8%2BTfL5kt4AIZWRFVxB1c15aEOgAoKzwuRAnOF62plzbNFZvHuThPXhqO4yyYmyhBCIX1KDlAQ6bat7GdBdbPZEjkFYJwakvKwkOh8mDJWlEOw4jqOGEF4XRfFyXiY9uX9wVpWcBV%2BVreEbXdcJ-W7VS3OC-DyORAEM2G4tpuSxt7jfPtx2LJdkQ3cgavvtrn20-1A7M5xDpKtzs6ADU0xcYp4FWGO7Pehecfl5eOfbgON9G7fpTYaa8NRg%2BSWP2f6Zgs-PtlxfRN%2BtfdOAMQwdBOg-foM1YAMAAOJ9HhojRAyNUYn3RvHRkzMtq4zAgNVeGdAagg6CDbe5tLYuDdNAAA1i4UOVC%2Bh8DqnUSsWF0ToDRmpesnUmbdRZttHBJVgFcztKTXOuhECnDIX0KcSodasDmhDGgFxUbXBJJxYWlcYIRXPrw7B8VOw30OhvHmucADSiBEDMAuldGgxImGSEDMGTRHVtFYMvkaFesY14EIgB0Q2ECbrBT4AUVBDMXFez4Xo-a%2BDQFB1zuSUoeAJolCFkqJ6iBpCkCQO1W6YTk6tgVrpQRHdMw51pJAa4C0Sg0CfjQF%2B7pyRVOEFgZQeRYDVVSZUHKtItG-yTt7fh%2Biim3zBF0LuZSKkWRoJUZECp3QlDUbUeRxQlHYWyXxbh2MdFuMif7QxIyt5lMHqIBxMoDDSHgIINCsAUalDERI%2BUayuEJ0weE3R-UBF4JATBLo98ykzX7oIaQeAAn9wKHUIgjhpSPNyf06ESp4D%2BgcQ0IgeAolfNpF0cBZSfQIoDA8u2lAcBNHnr0muACCm4M8dE75xCylmIse0xwxIaGCFqbHEMPSsZfQvkvAZaKhGZhEWU8hrLKEOL4BNKaJIxECEQKbUh8oEFIxRqsv8nCYURPeYMz5AqcRdGMWUholAxAMEyY47pzjekfCODSGEfA2Ao3%2BFo2wQA
```

**Comment by nojaf** [comment]
Thank you, I see what the problem now is.
When printing the long version of an Anonymous record in
https://github.com/fsprojects/fantomas/blob/8611499ad2e5fb4e32eb3bce9c9a0c82191438bd/src/Fantomas/CodePrinter.fs#L1298-L1301

Both styles print the copy expression following the normal indentation flow.
In your example, the expression needs to be indented by the current column it starts.
To resolve this, I believe you would need to wrap the expression inside the `atCurrentColumnIndent` helper function.

https://github.com/fsprojects/fantomas/blob/8611499ad2e5fb4e32eb3bce9c9a0c82191438bd/src/Fantomas/CodePrinter.fs#L2910

Something like:
```fsharp
    let copyExpr fieldsExpr e =
        atCurrentColumnIndent (genExpr astContext e)
        +> (!- " with"
            +> indent
            +> whenShortIndent indent
            +> sepNln
            +> fieldsExpr
            +> whenShortIndent unindent
            +> unindent)
```

Are you interested in submitting a PR for this?

**Comment by isaacabraham** [comment]
I'll ask someone on the team if they'd be interested - for me, it's not something that I have the time to commit to doing, I have enough projects I'm working on currently.

Please don't take that to mean that I expect you to do it - let's see if someone has the time and interest in doing it - but I'm glad I've at least reported this to you so someone can pick it up.

For me, we're not depending on Fantomas at the moment and this has been a useful experiment to see how and where it works (definitely way better than when I last tried it a couple of years back).

**Comment by nojaf** [comment]
Hey Isaac, this is a good response thank you. I'm well aware of all your adventures in the F# community so this response is quite sensible.

I also like the fact that you don't have any expectations on me personally solving this. From my side I don't have the aspiration to solve everybody's reported bug. Sometimes I just don't have a stake in the issue, so when that happens I usually leave some clues on what is going on and I ask the reporter if they are interested in taking a stab at this. Sometimes this works, sometimes it doesn't 😊.

If somebody of your team is willing to pick this one up, I recommend checking out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#your-first-contribution) and optionally a couple of videos from the [YouTube channel](https://www.youtube.com/playlist?list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K).

In case, you were using Fantomas, you can always ignore formatting the file using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore).
