### ISSUE TITLE
Fantomas adds space before colon when SpaceBeforeColon is false

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas#1773]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAKgBQCUYAvADoB2EEAtonQEaIBOYAHgHQAKaAllXTlqtMWAA2iYfwFDyYAIyjxERZAA04KAGdp6QQHMdqMAG1tEUKsgASLLlORB6TZdp2AbgEMJAV2Q0C1UIAAYtEKgASSokIQBlfgAvZAiQgBZ3CABddwBfNKssqHscQKgXNxtbH39y4JDFQvFIAFlvDgAZQUROxCpDdAALKsaAJlDi3LEC92sW0sc0SCZYWAlRsS9fANMG1THmrfjGfjgJWCoAQXQAUViAeQAzbqpU4ogn3z0p-Ob5raLcorNYbI4lWq7IIfMAAZnBEEg8Ww3mgiAAQognrBWIgeN5WN4GOg2JtxOhWAFfjN-sU7A5gat1mTETUdvUYekEVBkaiMVicb1YAB3NjQbx6GKeWDigyXFm0ClU1TTWizMQAjxApxMsF0tl1PYwgCs3KRKLRmOxuIAqthcKxxZKqNLZfx5dyvhIfiq-nN9QydaCFdtDdDIgA2M28y0C3EAYQkEp08cuOiV0HQOIVn2%2BiGpatp1UDy11IYNUPMMIA7NGLfzrYhWowWKwc2AvT7xKqIOraJrWSWoGXwaHK-txAAOOt8q2C1MXKjtzv5300-3FspB5mjiscyIAThnaKuTxJrFTdDo3nbStX3b9GoDW9Lwd3kP3jXCMPNs7jiBOOgznWD0YRXAteyLBYhxBHd9Q-I1IkUJofxjRBT3PQDgMXW9KXvMQezAPsik3JZhzfeD2UQ8YzRiOJ0AeKh8FYTAAHV%2BGGZc8wgoioMBGCR0osMqyQ%2BFUPrK5WFgPxYgAEUQCR%2BCA89cOVB91yfUjgUqd8qPDRouR-doOCiJ58CGfpbm9AChhxdB2PgTjuXSSY10LDdoJfCohHLBD9NURRTSMjoYiefgOAeB1vCzVhbg4bBcR0HR3SXbljVc9T3M0zyyOcHzdOEicxEUKNgo4AAlRA4FYeAHKczkMoIx9%2B2fXKdKE8cYUUWsysq6r4AAOT8Zg2GeKISToExuUUHjiLAAcShgug-AkAxFLeAAxHFr3Qc98C3ArOqQ6cfz6nF4FaFa1p6LbWB2lSzWgIYCVRc8AH1hX4RyRlmvitRg9rqj8kTGiPMrJMJTAHlYbp0zqkZnMa2hCLmhb6S8vLXEOz8Dm-SI2g6CHvChmH%2BHTIaRtYMaJqmrrfo8-iMeW1b%2BHWxBbvuth9scbHqIOFD8aJknYfQS6WbZjnooen8npezM2A%2Br7OPp7LGba-KOpx8QxkOMqADV2XRQR4CMeH2xclWWq0pxAYWYGitoMYxPx4yNpkzMUqN2JTaVhGGstkicu0jWgb0kGDkMl2Olk2B0AAcWkOKEsQJKUrNtKkZyZrA7VxkKNDwqYTGIKXau1menRC5oAAa3RQka%2BkHRGPiIlEAXYbUrA7i3Mghn-oxwSC6OkIxlK-GBsQYU2cxdBRX6bnEHksKqA4lKrliZtKdpyJwJ73i%2B8HAf87tsOHYgMYevxgBpRBEGwUzzP6GIW4YV53h37vMt71X%2B-VrHNb5trE6UcOBWSAjoIY6d-Z71Rq1POcEh5azEGMMG%2BNEgDCkJJQww1%2Bj2UQEwVoCB34hF3l-feP9D65UHifQukRYR4xCJAK4ilDBUDdlQD2lxEisOin4XE%2BBYB0VwdFFKXFrIB3mnA7cepEGALELCAWjDmHnioCIzwQoBib1bEvQQq80xiK7E1DSVsg7SN8qfGEsJdalxZm-ToRImDwG8ImWAyUBgTynj0Ax%2BFkbZ0kdbV8CCaHD1ULCZ2jDZJk28EwKQYCyZDHiJgIQHRvESLRtqZY-R4DPDfvELAUhzG0JCLCSOjD7jZJeF4x6rAJBPEgGkqRgSZHBKQbQWEJdGE3zvkIoQMQ67eA4X7D%2B4iYF-UofA5pgJ7aWLHowyuAzq5vx0JJaSsQJ7pkQBdMubMk6JWSvo7kd4GkBPIkEqZFi6GXzmQSOcuJIk6GgKwJSghoqbJtCvS48loBJkJHKTuwzDG%2BOMTnX%2BEzCkhPELCYBjC8lPMzIQpAqSYHaGyGkZwOgNrJVMOBPIQA)

#### Code

```fsharp
type T() =
    member x.P: int =
        let i: int = 1
        1
```
            

#### Result

```fsharp
type T() =
    member x.P : int =
        let i : int = 1
        1

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 06/09/2021 15:42:35 - a79ebea8baecaa59a8741e6228519d29c1033833

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by realvictorprm** [comment]
Just ran into this one too, good to see I'm not mistaken 😅

**Comment by nojaf** [comment]
Hello, this is actually by design and was introduced in https://github.com/fsprojects/fantomas/issues/1420.
I would accept a PR to update [the docs](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_space_before_colon) on this.
Otherwise, this can be closed.

**Comment by auduchinok** [comment]
It wasn't like this in the code style previously, I believe we should discuss/fix it there first.

**Comment by auduchinok** [comment]
@nojaf The code style has been fixed, see https://github.com/dotnet/docs/pull/24643.
