### ISSUE TITLE
KeepIndentInBranch  not respected when returning short function application

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1779]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAHATgJYBuAhlonqfgM6ICyCi6YAFALZPoDK%2B0aNLEQB2AcwCUYNACVENAK7osAHnoBPWVnn5hAFTW5EAGjCCRosOkKCAfGAC8AHXyPhEQgDMww2DlYAxQkwAOgBRAA9rLBoOLl5ocUksAAtEYWdXCAhQ-HxYfDAAbVMCQmEsL0dIAAU84kIkeDBOJB4%2BMEdOyABSGk6qsHhYOW9fMERIwQGW5niwAF0Mt3H0OiWsy2wwUXxSXGSHb0QAdzAARXlEfDVSACNMAHFd-dZxdaydveTggBlYUng-jy7ECmFirXiJl02iwmGq1Do%2BFebxc6VRG0wOHCNHg8JSDneGzx3wAwrB2LcyohWAARQj4RDQLD5NTBB7YEnaBnlOkMpks14mKrccmIYLY%2BBVFGuQmbHCwcqwdCwURqYkE9EbMDE4JkilU2n0xnM65sjlctJYXnGgXiIWQEXsMVYWFSpayzFgBXMp5fQ7CE5gADyiuVqt9L2lywgoMQfwBV1%2B-3grG9sAjyRMabDavIySjHq2ZCs8HIhAVOTytA1mS1GYAaqQS2WFcFiw1yJQJeq0xmOpBki7cCgAPQjuDsXCkYSsicjp3JAaffbuzXuLw-KLBayhSdYNRgdulrDl4SV-I0MApNKyiBBgDW22ei7XKzWr%2ByuXyh6bHZPFa-WglkgIxwCgOgXTKUQaFQIowIgUAtSgAASfdDFgyAyiwED4KySBkOLS5YMKXCNgABlApCIEgABJYQkHKbhCAAL2QSiqIAFlIhZcIAX3YhDuPwtDkDQTDyhwpD8MI0S4KosAAEYBK1SB6FIcJNwDH40lEFJJKohSACYyO4%2BY%2BOUxCVNQgxZMgW5YCVfSNmkpsiLQEj5MM5TnO4RB2EIOBlWEABBLBQnooMPE0tjuIgDwmzoUzzNwyznOs9CxPsxzvJQmTiNisAAGYcuo7gp2gRAACFEA8fJEHhXYnQofAnK1IRLiSjZ%2BJSoT0tsrL0Fa6iCNc2SPM4kqoDK0gKuq2qGT%2BY4rmgUg6Do4hYBW-9hCGrJ2sQTqsm6jZUrwvqMIG3aXPQNy5KogBWSaHXKqqarqgBVXBDD4VbEHWzaWx2yb4tWA6kLMrqLN6kSLocwacuu27xqQgA2J7ptmt6GRJdBVpoMlhDMeR%2BRa4GErBrUIaOqGpPOzK4aukabrGgqAHZ0Zeua6voPzbiuXa4vJw6IGOrJTuGmH6ey3q8vcgqAA4OZm175sQMkgoFsAQcS8HkpO6GbNh6Xadlu6kIATiVirgo8Zq9XYUhNf24WwFFwTaclqBLoRpmkYKhSKIK57la5hlfP8wKFU17WKY2KmRZpqzPbshmfdN5GtQUpSg4xxAbea8OAqVKPJud3XIZ6j3Dal%2BGZdG-L5KMp66IYrAQ10a4AHVCD0snQZdt2wHFlDk%2B9uvmYbgzipzl7gryeR6JpZhCH85qnfwDry%2Bpyuk%2BrqAsMZ9P-Y4p61PCGiPF0VIz1B7hknyLBu-gXuCo4kyt4Tne0uTg%2B0-ruXG6PSDmfOiHhCDhCDN9cg%2BQIgEDkDQU8mt7rv0pnrMWBsMr7wkn-CeACDJo2AepWQcB8DwCfi-eSb8B6J2-nvcS2EcF%2B0buzQh4RiH5HgAAOXkBSK4kUaIUHYDBSaClqFfzOsndgigTxWADP4fIDsXRXH0OhRhLNG6KyDuw0h9BpFBCpPI-Aii15PWgMkagM1moAH1jgND0mI-WVdMH0MPv-M2mdLasLnrsNQQZ8CbkEOQ5ImsqEf1djQiRdDf7jyYVRYyp91LeNIL4-xURuG8PwPwwRwj-YOPQU42yUilD6LkQo8gzUVExRNm4jOGxDLZ3kpAJJKSAlYF0cU2RiBDHGP5qY8xuwmRXBsXY4JeT3a72cdE6puD3F1K8qwxszNKplHgFBIJISUFxzQeM2hkzsExPUXE6ejSz7%2BAXkyU8yz6JrJGRssZQ8MG2SmVZI%2BnkT6sJpL4dkYVwhwJoAghU6zJrIPucPYSdCx7TNiUhQyQCTl6M6ZVZU0B7yVQGfebANAQzcFIE6dWPCgYFRjqCx5Rta5QsOTCghjTOEnERdgJaaRKlLzAcIHup5gr0R5hknJ8liVhMHmCumXtU4HMnjClhjSADSiBEC4AvlfNIdEcVOmitHIWAqIkSyifsil4qtSGU0Sc9SoR0D%2BRoMkIFr9NlZHjuE8R2rnGQpeTUgqhlPGNKYmITAc9RA8MtJ3RAtxGBIHVf3TVDqR4QtFXqvBSFCqB0acFKwohhBnOEBchUTFU3kG0IgXQsAW6WkBmGnWqCK6OImf1GNLqZm1KyIVBpVEmlKCuMIMsxA4wKlENyvm%2BAWVlHZQqXlVF%2BXlu3pW3Z1bja1uhVqQq8z4XFOij8XFtxSw41gAgsQtLjidNLbHW12yHkFLJa4utBVCrHObXSGgdxMCmvNckbgahyjqQPSS09Yk0jwEitFbg%2B5MDnrnRsQq7zGnhV-VFKkmsYD4HQB4SAn6q1nrUfq0DcLm0yrlUW8odE0XTjMevTe47P6TsiU6mtaVXlUUKtS5tSLpz3mijQOesAF5cLkBQeA7SZFUlgQyf5p4R1ITLqR%2B15HHXTvJbOyl87JUMeoKHRAt7oBEH8u27j702UKiXtAXGuxtofojZJqNlGZ3UddfJQqRrm0AaIEyENVTR0avE7xMC8x2KYRoP4BBsFiW8SAA)

#### Code

```fsharp
let private parseModel (modelSrc: string) : Result<MyReturnType, string list> =
  if not (File.Exists(modelSrc)) then
    Error [ sprintf "Provided modelSrc \"%s\" does not exist" modelSrc ]
  else
    let graph = new QueryableGraph()
    graph.LoadFromFile(modelSrc, TurtleParser())

    let xsdPath =
      Path.Combine(Directory.GetCurrentDirectory(), "Some.xsd")

    let ontologyPath =
      Path.Combine(Directory.GetCurrentDirectory(), "Some.ttl")

    let ontoGraph = new OntologyGraph()
    FileLoader.Load(ontoGraph, ontologyPath)

    let validationErrors =
      GraphValidation.validate xsdPath ontoGraph "http://company.com/meh" graph

    if List.isEmpty validationErrors then
      Ok graph
    else
      Error validationErrors
```
            

#### Result

```fsharp
let private parseModel (modelSrc: string) : Result<MyReturnType, string list> =
    if not (File.Exists(modelSrc)) then
        Error [ sprintf "Provided modelSrc \"%s\" does not exist" modelSrc ]
    else
        let graph = new QueryableGraph()
        graph.LoadFromFile(modelSrc, TurtleParser())

        let xsdPath =
            Path.Combine(Directory.GetCurrentDirectory(), "Some.xsd")

        let ontologyPath =
            Path.Combine(Directory.GetCurrentDirectory(), "Some.ttl")

        let ontoGraph = new OntologyGraph()
        FileLoader.Load(ontoGraph, ontologyPath)

        let validationErrors =
            GraphValidation.validate xsdPath ontoGraph "http://company.com/meh" graph

        if List.isEmpty validationErrors then
            Ok graph
        else
            Error validationErrors

```
            
#### Problem description

This is a good example where AST alone is probably not sufficient enough to make the right call whether this should keep the indent.
@Smaug123 I'm correct that is should not indent the else branch right?

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 06/12/2021 10:31:17 - 8f71594df9f6f30871e26ccf0aa5da1ac7be325c

```fsharp
    { config with
                KeepIndentInBranch = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by Smaug123** [comment]
I agree, this should probably unindent. What's the problem that means the AST doesn't determine what to do here?

**Comment by nojaf** [comment]
Oh I mean when you have something like this:
```fsharp
Error [ sprintf "Provided modelSrc \"%s\" does not exist" modelSrc ]
```
the matching AST looks like
```fsharp
App
                (NonAtomic, false, Ident Error,
                 ArrayOrListOfSeqExpr
                   (false,
                    CompExpr
                      (true, { contents = true },
                       App
                         (NonAtomic, false,
                          App
                            (NonAtomic, false, Ident sprintf,
                             Const
                               (String
                                  ("Provided modelSrc "%s" does not exist",
                                   tmp.fsx (2,20--2,61) IsSynthetic=false),
                                tmp.fsx (2,20--2,61) IsSynthetic=false),
                             tmp.fsx (2,12--2,61) IsSynthetic=false),
                          Ident modelSrc, tmp.fsx (2,12--2,70) IsSynthetic=false),
                       tmp.fsx (2,12--2,70) IsSynthetic=false),
                    tmp.fsx (2,10--2,72) IsSynthetic=false),
                 tmp.fsx (2,4--2,72) IsSynthetic=false)
```
so a nested `SynExpr.App` shape and this is difficult to recognize as a short statement.
In this case, it is a oneliner, but it could also be longer like
```fsharp
Error 
    [ 
        sprintf "Provided modelSrc \"%s\" does not exist" modelSrc
        // some comment, same AST though
    ]
```

I'm guessing you would indent if the application was multiline.
Or not?

**Comment by nojaf** [comment]
I'm going to solve this purely based on AST.
I do think it makes sense as you are immediately returning a functional call as an expression.
So that does kinda counts as an early return to me.
We can discuss this further when new evidence pops up.
