### ISSUE TITLE
Remove trailing whitespace.

### ISSUE THREAD

**Issue by shivinsky** [fsprojects/fantomas#178]
It seems unnecessary. Or do I miss something?

**Actual**

``` fsharp
[<EntryPoint>]
let·main·argv·=·
····printfn·"%A"·argv
····0
```

**Expected**

``` fsharp
[<EntryPoint>]
let·main·argv·=
····printfn·"%A"·argv
····0
```

**Comment by dmich2** [comment]
CodeMaid http://www.codemaid.net/documentation/#cleaning can do this for F# files already.

**Comment by lijunle** [comment]
+1 on here. I am using the Nuget version.

**Comment by xperiandri** [comment]
Actually there are lots of places with unnecessary whitespaces
https://github.com/fsprojects/VisualFSharpPowerTools/issues/1382

**Comment by nojaf** [comment]
Solved by https://github.com/fsprojects/fantomas/pull/336
