### ISSUE TITLE
Soundness regression in 4.5.0-beta-001. Nested lambdas are stripped

### ISSUE THREAD

**Issue by seanamos** [fsprojects/fantomas#1782]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPMAvADoB2EEAZgK5kD6YAtAHynltjV2NNhGQAWidOlh9IAGnBQAztiwBLEgHNpqMAG0pEUOygASLAE8ADsjSRFWCVvKQ9ANwCG6KmY022ABkm6IkAJIkSCRYAMryAF7IPr4ALB5gALo2AL4x2gl2RqZqFiHWunZOLm6avmAAjOnskACyjrgAMoqIjYjKWPwFvhUATJ4JyWxpNjo1BiZukABGsLDo3WxFzq5qZb691UuhiAC28nAiJACCWACiQQDyFM0k0QmUzrKDqdVjSxM55rPzi7YOK1KDzAAGYtrZQsZHNBEAAhRAUWAAJ0QAAVHEjHLtsIgkX82Fgka4XsM3plPlMfgtwcsSmtgbFwX5IdC4Qjka1YAB3XHQRyyQL2WB8hSwEj48iE4m6IbkEZsd7-bKUubU8nFVZoda6ACsTKgLJh8MRKIAqsZTEi%2BQKSEKRfIxRLHuhnjLXqNycrclSJbTNe5ygA2fWQQ1sk2IADC6H50kjYukUugWGRTo4T0QJLlZMKFO9qt9ALpWuBAHYQ2HjRzantpri0xQM1mIPLyIq-HnvgWaUX-dr2AAOCtQo3slHxo4Nptu0ke3Neru-HsaoHlACcw9ZxwoWFx8d2u0caalmZn2bn4wXUB9y8B9PKFW8wNDI-DHJ2%2B0Ojv1jZdp-Ysotjml6TPmS7qneJYPlUz5htuu5Ih%2BBzzN%2BwIns2YCthk86gYuaq5iu949Jsz6BMEWCXCQAAqSKGAA6vInRTn%2BGFYWA7b6FeMzdhBxYBj0YKwa%2BxxIrANDwAAIkI8j7Ahx5Ev%2BbCAZhwEfFxliFoRUE9Iyz71Lg-gUFRggkGcf6hPwyJYAx8BMfqsQDGeQEXmpuFQBpt58f2bAVHqekNIEFDyLglyWo4KZImcuDGCi0jSA64r6jqjkAe6Cqem5eRWJ5fbAhUwb%2BbgABKiBwEi8A2XZDIpUpaVthlXzufkOWrj05aFSVZXwAAclQux1ki1z%2BLuuyqPqFSsapSqZbsVDoAo6AtAAYsih5YAhVGgS1RG6BUQ7Pp1yLwLUc0Lctq3hXJIbQPwGLQghtBcvItldJNLnTY1WWaZB-G7RuhUiZihiXEizSJpVXT2TV5DKWxHFZJlHm8bl5T9CG%2BmA44wOg-Iia9f1uJDSNY15W96U4Z9s3zfIi13CtSJrRtW3I61ui9DB5SQJj2Ng1gJ3U7TiD04z9bXbdmLJrij3PUxZP1RTUxIwRP3eeQvQkZz%2BkAGqArCijwIoSgQ2mDly9hIGfUr4xab97C9IJmsNEtNDJgletBIbxtQ2b7ENYrzUsztdu6Y7uASbAWAAOLYFFMWIHFCVe8CyU%2B-DnbXjxytecCvR%2BZrp00y0sIiNAADWsIS6X2DSJRoRYlG8x9YlwK-q6qWzuTFsquBWcoxsBWc91iBcoL8JYDy7SbaYUlBSQjEJccQQ1gTSIk%2BUreKTDdXm65n03oH2ls%2B1nMANKIIgxiGcZ7SBHX2K3Pc6-Tu356d7v-vZQfttsL0%2B2h2Z%2BxpD8CTuUU2TkVLvQ7FxfevdWZ23%2BpzcIyhMAiSUH1do1lEDTFqAgR%2BvgN6pz9mBfC1sVbAhBE%2BTmxxFpKBIM7EgrsxThFoeFKgKIqKwDIhg8KCVmJt1qh3eWXdiHfWzuUEEHNfBc3mriEgPD7CcmUMvAaM9FDzwTHwzeEBYZTSgZlGBpCxG%2BBBBrKR-MFAP0aFiaY8BHDRlgPFZQQ8R4tE0YQhWIjtqH3YCCB2UiJK40cNMTAADcb8FCIYEIDQ3HgLhkQ8w7R4DXAfqEIwmBRF910CCEOUiLhJJuK466SJ0AUEgO44ReEMlwLYCCPOUiz4Xy4SEQIFdHAMMhi3Z%2BAjX5CPfp4r%2BqsIAggHlI4ubTS4P2kCJMSQQh6JkQMdAugtY6xXiho-U6FYm6M4vozOhjMk%2BOPqMjEVYUQBOkNAJEMlFDhQWaaOeYopLQBjJiUUzcn4sS2ZAnZe89kfBtoM0Ef8pGpKucmHBSAYkvxbFIRIMQLDSCWvFNQBCUhAA)

#### Code

```fsharp
let x =
    fun _ ->
        fun _ -> "hello"
```
            

#### Result

```fsharp
let x = fun _ -> "hello"

```
            
#### Problem description

I noticed this with the latest shipped version of Ionide which includes 4.5.0-beta-001.
When a lambda is nested as in the above example, one of the lambdas will be removed by fantomas.
This obviously breaks the source code.

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 06/12/2021 10:31:17 - 8f71594df9f6f30871e26ccf0aa5da1ac7be325c

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello Sean, thank you for reporting this issue.
I believe the problem lies in the change in the `|Lambda|_|` active pattern:
See
https://github.com/fsprojects/fantomas/blob/8f71594df9f6f30871e26ccf0aa5da1ac7be325c/src/Fantomas/SourceParser.fs#L1252

It appears the processing of the `parsedData` is wrong somehow.
