### ISSUE TITLE
Empty line before and after multiline value binding expression

### ISSUE THREAD

**Issue by domenichelfenstein** [fsprojects/fantomas#1785]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYrLAEICGATgDrUB2NV9dA2gDwFnQAuAfALoNaeLmAAGojrS6x0ZAM5hEADzLoADnnFgAFAEowAXkEQI8gJ61oYYCdthjdiMMUA3RFICMhsAHN3AUTcpQmJA9y4AETIuMgA6cgp7SABBKkgHR2dEIK4AJm8-WjDgolhiyOi4hKSSNIy7LJyAZgKAnJCynKiY%2BMoE-soaurpHJ0QRbPCAFlai9tLy7qrBtIBhYcZRsEbwgFZZ8o7Fyt6KAbO%2Blch19JHRnakANgP50K6T8-Oh283R%2Bts9PUAL6CSAAGnAUDk4y4AEtaD45KgwMxIRBQI5IAASLhmNTINCQeFccFokzYlxkHBYAkosm2AAMEK2kAAkrQkFIAMqwgBeyGZoym9LAfDJQMF6JF2Nx%2BORRKkpMxWMp1NpqK2HkldkgAFkyEoADLwxCG9w%2BLgACyVow8uQZIrFtglZIxOpxeNpkAARsQcDbbBSqTTkRrRrltYGuYh0LC4DhYLRklx-ByAPIAM2NtAFIogGap0Md4u1bsDHrlhN9sH9kagKuD6rzYCadYgkC5ak4iBIiAzsAoiAACpRVONEBQA3YuBQacXnaXpRWvdXa0vVSG0GHHFM21BO93e-3B4bYAB3CfQeSIdkuWBXuGJqe2GdzxxOkwu2xl8nL%2BWr596w3Jstl2PcOy7aAez7AdEAAVTUfEKCvaFb3vaJYSfPcCxwIt3xLV0l1lFc-UAoM1VDZtHnAg8oKPWDVhweQ5FWRM5FfbgB0A-NC0QedP0XZViP-Ui63Izc6S2AB2GjIOg49EF1GNvQnbiwBwvC7A-CAvxMH92z-KtRPXRtKK2AAOWTDxgwdWITWg1I0vj8IXQihM9ESazIhsKK3ZsAE4rKg5IMy4CdWPQWQ1NfZytII78iI8oyvLEnyJO3OwPCZZsIOshTo1jeMsObJz%2BJ0wT3WE5K12VYCzNtLUctoxAQrCigCrjGtiq2GKyrAXSpXcysoAA1K6r8zUIxy9lOS4NNaAAFQoMwAHVYStRzeL6gbrES4afWM2rTIm21WyauTkgoWAsA5CJEBwWFYza6LZ1i2xtP6iryyqqBiW88bJNtXccv1JRWQzBbLQCXDEC5S0By4Nb4A2vcpgdFyBLcyqkt%2BxUxuOwHHA8MCQYNdkM1hJQ0yQ6IB38JQ1EHOQ5Ewhy912dG4tchKhq9P78d8wnMuo0mlAAJUQOAKHgJGUebNHtq%2B38foVEkBfS5sPBk0WJal%2BAADksHQFSKEzVkwvQJE9w8RWse%2BnHIHQXA4QenMiAoWQuDahaPPVkDbUsnLdYHeBdWd2FXcQd3Pee8DoEtUduAnAB9M9YWR61bZ57H9v5kzBYy2wPEC0XLooMgzDTChjXY2XrVRzn3vivS9r5vH841rZ7XA0Gy4rqua64Q3jYnM2LatzWs5b3n5SdnAXZNaPom932O-9xxckalk%2B8r6vYXYsP54jxeBxj1S44T8uk4oVP042qfBpztu1bX%2BqN6mllQYANUbEh4XgeEPg65qQVhjcqdtlYOzzkdAuzZchnU-gaAgN1uCsz-hyQBwCG4P12jPQk0D3QA0LiYXIwNEFKAiLALgABxcY9NGaIGZqzLBzYOY4P0vWFWo1X4nQ3iTT%2B4dI4kATNAAA1iQK%2BojxhyHmlyMcdkjZsxKltMBn0IEGS4YdQhBNiEQFyCLFk%2BtEBniEeMC87gfb4juhTWg61WbJA5EpEeFAJ5bFKqonaHCZQO24TAzu4ZtYsgANKIEQGocGkN3DsjkegU0JpNow3Ya3eUBDyxELgYHch-gcCxjkJaFhWxQFc0xtne2%2B1fHaNgV3EuLIeQIjwJdHwRtwgrUQN6XUCBcxuJUcU8BpTIHlK0WknRzYmjZW3g9HwtBkGWEfLQHkUzohYEHAtWAM1wgYW6qMdxvS1H9I0T4oZv50lbCaFvUYKR54TloBhNwp4EROJNtY%2BEdi2IJM0k3bm08n6eRqpU-xjgmgfwuYfOE2ZTSqG9PAMgjFYAswREYkx8TsI9M%2BSU75ZSSIpR4ULWwTQEEXIiPvMg3o8DZNyZaLkFgYhKHeW9EwH1PHJMJO4eAmZwVclxHgf6IzTlkIuamNlWZkU5WgBQHAGZIBJLwSNI5BkTmjCaPwi5ISwnrKkOyCRZBLD12UYkjxSsDmDOxX49edgmgGIucI7VojwVyEutdDkRj2KIFDoIk09CmYszeXuXqBr1GcMOSa-5Zq8WBKtX0GyiAiVyDFY9eE0RXVwVsYmO60AmLlzmXS6VPzqo8qqYqzJFzOUUDjFwDpSBs0eMhHwQURI5AEBZsiUqQIgA)

#### Code

```fsharp
module FooBar


[<Fact>]
let ``Fantomas example`` () =
    async {        
        let event1 = genEvent FooEventData.Bar "A"
        let event2 = genEvent FooEventData.Bar "B"
        let event3 = genEvent FooEventData.BarBarBarBar "B"
        let event4 = genEvent FooEventData.Bar "C"
        let event5 = genEvent FooEventData.BarBarBarBarBar "C"
        let event6 = genEvent FooEventData.BarBarBarBar "B"
        
        ()
    }

```
            

#### Result

```fsharp
module FooBar


[<Fact>]
let ``Fantomas example`` () =
    async {
        let event1 = genEvent FooEventData.Bar "A"
        let event2 = genEvent FooEventData.Bar "B"
        let event3 = genEvent FooEventData.BarBarBarBar "B"
        let event4 = genEvent FooEventData.Bar "C"

        let event5 =
            genEvent FooEventData.BarBarBarBarBar "C"

        let event6 = genEvent FooEventData.BarBarBarBar "B"

        ()
    }

```
            
#### Problem description

When the maximum width of a value binding expression is detected and fantomas breaks the expression into a multiline expression, it also adds an empty line before and after that expression.

I don't see why fantomas does this, and I think my code would benefit if I could decide if an empty line between blocks of code is necessary or not.

Anyways, thanks a lot for putting fantomas out there!

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 06/23/2021 09:31:26 - 2d2b0ca9775a686191961c8248b2baa8aa72174b

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello, Fantomas does this consistently for every multiline expression as described [here](https://github.com/fsprojects/fantomas/blob/master/docs/FormattingConventions.md#2020-revision).
This is to somewhere draw a consistent line in the placement of blank lines.
Blank lines are not present in the AST so that is why some heuristic is in place.

You can disable this behaviour to some degree by putting [fsharp_blank_lines_around_nested_multiline_expressions](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_blank_lines_around_nested_multiline_expressions) to false. Please note that this is a recent addition that has not been released in a stable version of Fantomas.
So depending on your editor or setup, this feature may or may not be present yet.
