### ISSUE TITLE
Style bug: using </ catch /> from FSharpPlus indents on next line

### ISSUE THREAD

**Issue by adz** [fsprojects/fantomas#1786]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbWA7AhvMwAOlhBADaIAuAhGOgJ4BqOZAromALxgDOs6iAII96WaACVEPVmUoB1AE44ADssTwAklknTZAFWKkwCqqwUkGzNomIBfYgB4A9NByVoACycA%2BMAAoAM1YSRAUFWAUrdjAAWl9KD3CAd38GAFEwiIBZFTUFMFDwyJZ2AEpSyAAacCgeKkoASywAcx5UMABtGohQIwhIABJKejV2yCbKKu7SQYA3EuQ0Lr7SAAZqlf6tJCxKAGUGgC9kDc2AFmmIAF1p21Oey6ghkcWoCamVuYX25c2ARnufUgOQAHgAZJqIMGIFoJD7-ABMq0eNyMd2mvSBz1GaEgACNYLAyPCjF9rD9HhAEYDSXtEOgGnAyNhBJQ0lh4AB5AIQrAnSlgAIsOoo26AzGk7GvfGE4k0p7zclLAUAZnl-T2yhw0EQACFEAEIogAAo4JQCSihEl9SgKdiitHix6DYY4qAEonW-oDRXsCmbMBndVQTXavUGo1g2BJUKuOpaWawVyNbBe0i2%2B0rVGkdFGCUzKVjD1y50%2B77KgMAVmDkFDOv1hpMAFVVLGcPGsInkw1U8GhWQRVmxRjS67pcW02S-RXNgA2Gt18ONxAAYTI7Z4K%2BwPAz0EoETTEH7g762YgudI%2Be9Y6LssnZaVnQFAHYF1r6xGTFl6XirX3hYgDo5k6nyFriE7ylOry-CsAAcb5hg2RpbsyWCHoKAFAeeIFYje4F3pBD7Tk%2BAYAJwITqggBJaChbug6A4OhGaAUOjojqBeHugRpa%2BtBAp-OsAq1u%2BS5GnSDJMr2ArHixp7Dnmo4vLenqEbx-r-ACQmLlRNHiYyRJSQGzFYWAF4PBxSn4SpPHliRiI1tsMKUJyWB6Ao9ByA0cL-gOslGGepk4ZKnEytZoFqTOKx-GqWkiYI4TBPAAAiiBkA0DI0Uxdp%2BaQAVmQQiluuMuz3hFdlRUGQmghoAR6B4MJpL5eweBE8gNPA3kCmcyKscB7G4ZZbwlaptkwX0fzVlVOAgloAQNCCnJ5G4ERpCCygmDwPA9mhwaVj1clsQpFlFe8I2PmNRh-POU0gpIcAKPAnkdR46HdSZ%2BVXk8IWnTZ538a%2BN13RE8AAHKsOgv4KNyGiWugbTBn871BQWIXoDIjRpXyABiEQMZQNF6EpZ3ERdpB-PBQlAw9WTow0mOIDjCh45lNaeGa2o0QA%2Bkk7Vwkj-XBYNxWTMTfEBn85E3fFSj0JyCgQjuT2dQGb29dhAso0LP3haNApIjWoLSzgsvyw0O5gxDoTQ7D8P8fzR0DUVaOyHTkKM8zoSE6MovqSsCKaQGkBGybCuUDTLv0%2B7bgs0JbNKHuoTc7zL325ehXStrWJlaTVLUjdUR6k08BNM0SsvcGqsHX1DuCydw2-STesxYHoJY8Ee7bbqRcl2Xr37f58lp8dGf1zrf0BgilUt9NSWwJQADiVCretUhbdgve7f3uWD%2BZjvjtxY%2BNxPk0t7T9O6sy0AANa6vHV9UDwLl7DgAgoeDO3SZhauBRr15CxBDcxabARNdQOINEBJHPlQGMMIvaIBSnNLAXltqCA5N%2BS2ChbYBhkqnXetd95hSzrrCeANA4AGlECIGUDVOqMItDPwELyfk2Cv5V3VjXTWdcRaAN9n0BEFNp4gkagyHgHgN5dS3tcHeBVh7KRLIfIBftJaBwOC0Cg8VmjgycnIRAeIsgIGYZsHB38PrpzkaVYhmwVSCUDoINKzQsBtzECmLABwHFuDMIgPQsBHK7DcNtdCxi2E-w4X-IqACFG8KMCqAOmwg6yFCLgRoswoTYGaOgyGCCmjIO3IE1hA9DpDz3uYn2kU%2BgqjzqfF2TCwQvzxPAHAa5YBbRaOAyBkI8m%2BVwTI4pVl5FEPHlY5ucSkpmxwHiCgwizYeD2KISg01OkngKdXIp%2BCxgwi5DySEexhgUAsYMlYKop5xPZJsph6EYAKDIAESA3TPoun-gfAZR8rEnziRQqhvjKBaFvjgMQ5dP5dJMcjMJBD%2BmSmzqqUBcSL5-Kvkwng8VYCJXATudQ4cMaQmXhtNeWAsGbGMsC3%2BX1HmEIhZYw5pCYVmiQiYUZPBoAKHSk0Nw6gmxIOwClaA64lAuMWTlKRhS8GcLBfsl5hyBFxJ2Uyvc%2BikD8vejUK4pxxg8CxltdoODbBAA)

#### Code

```fsharp
monad {
    let! myValue = someAsyncResultWrappedInResultT
    return myValue
}
</catch/> (fun errorValue -> throw (myErrorMapper errorValue))
```
            

#### Result

```fsharp
monad {
    let! myValue = someAsyncResultWrappedInResultT
    return myValue
}
</ catch
   /> (fun errorValue -> throw (myErrorMapper errorValue))

```
            
#### Problem description

The `</` and `/>` operators in FSharpPlus are designed to turn a normal function into an operator. The most commonly used one is `</ catch />` which is commonly followed by a lambda. Ideally fantomas would not break `</ catch />` over lines.

https://fsprojects.github.io/FSharpPlus/operators-common.html#Functions-as-operators

#### Extra information

- [ X ] The formatted result is styled poorly
- [ X ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 06/23/2021 09:31:26 - 2d2b0ca9775a686191961c8248b2baa8aa72174b

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello, thank you for your interest in this project.
Fantomas, does not know what your code does or what frameworks are involved so this really falls outside [the scope](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for) of what the project is intended for. 
However poetic this style might seem, it is not worth touching the very delicate nature of formatting infix expression in Fantomas. Thanks for understanding.
