### ISSUE TITLE
Strange formatting when "piping" with custom infix operators

### ISSUE THREAD

**Issue by seanamos** [fsprojects/fantomas#1787]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBZAngFwBYEsA7AcwDoBbTAMwFdCwAKASgB1CAfAPjCzyLMq1CAJjAtIADynSJAQnFtOAXm68CJCtToBmSABpwUAM6Js2fkdRgA2oYigIjqABJsmAA7I0kItn13HSGcANwBDABsaLxsApwAGAycnSABJQiRCbABlfAAvZESkiAAWWLAAXQCAX0L7MqC3TysfTP8ioLDI6NsiiABGWqTIdFCJABkiRDHEEjw23r7hOLLKpxqAhyHXD2jIACNYWHD55JCIqKse3uFB5KzEcnw4cNhCAEFsAFF0gHkqCcIBTKECoERMK2qg02p0auwORxOgTOXUuwLA2lugSy7lC0EQACFEFRYAAnRAABVCJNC5FMiBJiKc2BJUQhayh9W2TW88OOmI6526aOKmIgkGxuIJRNJU1gAHd6dBQiY0sFYErzK9GY5mayiqtHOsnNCkbDmrztQKUWgrkUAKyiqASvGE4lkgCq7k8JKVKsIao1%2BC1jtB4XB%2BshG05Zp5hz5nM6FxtaIAbI7xTiXdKyQBhcLKow515GXXQbCk7UgsGINmGjntLlwuOW5FJmK9MAAdnTzqlbsQ6Aee3plbAofDSQNECNjhNYsb5ub-NbQo7AA4e5m%2BzKiy9CKPxzWI%2Byow2Y1ALcvE6vegBOTeSt5UbD0ovkcihUe6o%2BTyPG6M7IuCJXoKqIdn0CRohmkqujK9yPM8wZooetbTvWWznvsS4JqBybgQMUG9k%2BL4kvBTxHEhHbfqhYAznUZ6AbGwE4da7YLDcUFpBk2A-IQAAqJKYAA6vgcwhtWNF0WAc4uJhl4sW2tpJH0GKEVubwkrAdDwAAIog4T4I8JFfiyP5OFOtHoTCjFQL4LbXmBCwilBIwSCkVB8bgMyfGGiBZLgpLYCJ8BicKyzHnWp4YTZLR%2BCBrFKU4fQOi5oxpFQ%2BASD83qhOWJKfBI7hkkYRhBvujp2uFv4nv%2BDHcrZrTxYpaJ9GmqUSAASogcAkvAwWhR2xRVeZf6zgB9WxfZuFsUUfTdu1XU9fAAByNDkMOJJ-CkL7kJYjp9JJVmmjF5A0OE5gGYCABipIfmY9J8YBTU3rNG5QYtpLwOgZ0XZMN0kndxnptAuBUriJEAPpyvgIW4JAh1RdZE12c9jmzfe7UadSmA-CSEwlv1cOOkNCO1dFyONQpL1JEs6auVjoQ43j%2BAlqt630ltO17S1pNjXVuyned%2BCXYg-2Aw9T1U2jNMER2kAM0z%2BPYN9Qsi2LuVA1BINg2W9JQzDcy8-R5O7CjUt4dcHFy65ABqgr4kQ8D8ITo4kxFaGI8dFNxebM006p1ujFddBlmVDvpM7BtE2FRvSeNpuUw2DkW0UwjOYHEg6bA2AAOKmAVRWICVZUuxVw2OBZUkyQ0MXyUn02JY4wgpdbP3C5M%2BIvNAADW%2BLUj3phGLxWQ0ogu5reVyESe7lme-OcnYfXCVosIbVy8tiByiLhLYAqMyPZ4ekZYQollW86SDuzJLcx2KEz1X8dAfGS-NR2wjzXLADSiCIO47meTMNII9aQAiBLfae1VIpkyRgnH2L9qZOGEG9DOPlHhGFwKXGO98jrz1rovLYyc-aIIxnLHIJBwiIA0sQNaMwgqID2OgBAYDeh30gR7aBXsmzMXgdLJw2hIJyzeAZYghBg6EFDq8HIIjco0DJHxWAXFaG5TKgeCBI0ap8xNk-Kay8OzaFlr0eW516SEGUcEWUJBL4bSPkQU%2BxZVG%2BVjtXBcTFn4EIbmibQVtDEq3MKAsYNI9jwFCHmWApUSAby3pMBxE51FQM0TA7RqMU5JG0AHQxOkWahD2BQ1BLNcBZEwJkUYMSzIV1GsbRJ3gZjwD%2BKArIbgKE6Nfr0bQ6dDHfFqf8aJwMSThCoPDbBc9ZJ4O4e43RrSW6GO-r-RRmQ0h91COI6O4DHFDI4bgiaddxktKKNoNehjO5LO7qAowGktLpA3iWRAX024iwLsVUq9jHTUXWQkzhSTfaNwgNoD%2BhyqSwTJJkow0ASSGSILlG57oT6vD0tAfM1JNST1WbE8pGjKkfNcc0hBjhtDIMMQ0sFZZGFIFKZJQw5RCg%2BCMFdUqVgUJVCAA)

#### Code

```fsharp
Mything.myfun ()
|> Mything.myfun2 "xxxxxxx!"
>=> Mything.myfun3
```
            

#### Result

```fsharp
Mything.myfun () |> Mything.myfun2 "xxxxxxx!"
>=> Mything.myfun3

```
            
#### Problem description

The original input in this case would be the expected output.
Reducing `fsharp_max_infix_operator_expression` can somewhat mitigate this by forcing all these infix calls onto a newline, that is obviously not always desirable.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 06/23/2021 09:31:26 - 2d2b0ca9775a686191961c8248b2baa8aa72174b

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for your interest in this project. You can change the value of `fsharp_max_infix_operator_expression` for a specific file using `.editorconfig`, choose to ignore the file using [.fantomasignore](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore) or place [a comment](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBZAngFwBYEsA7AcwDoBbTAMwFdCwAKASjAHpWAdQgHwD4wseImUq1CAJjAdIADznyZAQmldeAXn6CCJCtToBmSABpwUAM6Js2YWdRgA2qYigIrqABJsmAA7I0kImxjJ1dIdwA3AEMAGxo-BxC3AAYTNzdIAElCJEJsAGV8AC9kVLSIABZEsABdEIBfUucqsK9fOwDc4LKwqNj4xzKIAEZGtMh0SJkAGSJEKcQSPC7BofEkqtq3BpCXMc8feMgAI1hYaOX0iJi4uwHB8VH0vMRyfDho2EIAQWwAUWyAPJUGaEEpVCBUGIWDb1Ua7S6tQ4nM4XUJXPq3cFgfSPUJ5byRaCIABCiCosAATogAAqRCmRciWRAU1FubAUuIwrZw5r7Nr%2BZHnXE9a79LHlXEQSD4wkksmUuawADuzOgkQsWXCsDV1k%2BrNc7M5ZU2rm2bnhaMR7UF%2BpFGLQdzKAFZJVAZUTSeSqQBVby%2BClqjWELU6-B612Q6LQ42wna8q0C05C3m9G4OrEANld0oJHvlVIAwtF1WYC58zIboNhKfqIVDEFzTTzunykUnbei0wlBmAAOzZ91yr2IdAvI7M2tgSPRtImiBm1wWqWt63t4WdsU9gAcA9zQ4VZY%2BhEn04bMe5cZbCagNvXqc3gwAnLvZV8qNhmWXyORIpPDWfZ1jc14wOVcUTvUVMR7IYUixHNZU9BVnled5wyxU9G3nZs9mvY41xTSD02gkY4MHN8PwpZC3jONCe3-TCwAXJor1AxNwII%2B1uxWB44KyHJsABQgABUKUwAB1fAlgjesGKYsAlw8XDbw4rtHTSIYcVIvcvgpWA6HgAARRBonwV4KL-DkALcOdGOwhFWKgQIO3vKCVglOCJhkDIqCE3AFl%2BKNEDyXBKWwCT4Ck8V1nPJtLxwhyOiCCDOLUtwhhdDzJiyKh8BkAF-UiasKV%2BGRvCpMwzDDY9XSdaLAIvYCWP5RzOmS1SsSGLNMpkAAlRA4ApeBwsintyjq6ygMXEDmsS5zCK4sohn7bq%2BoG%2BAADkaHIccKSBDIP3IWxXSGWS7MtBLyBoaJrBM0EADFKR-KxmSE0C2ofRadzg1bKXgdArpu2YHopJ7zOzaBcDpQkKIAfSVfAItwSBTri%2ByZqc97XMW59up0%2BlMABCkZgrYakddMaUca%2BL0dalSPrSNZs08vHIgJon8ArTbtuZPaDqOjrKamprDku678FuxBgdBl63rprGGZIntIBZtniewf6xYlqXCrBuCIahqtmThhGlkF5jqcODG5aI%2B4eKVzyADVRWJIh4GEUnJwpmKsNR86aaS62FoZzT7cmO66CrKqXeyd2TbJqKzfk6bLdplsXJtspxHc0OZAM2BsAAcUsEqysQCqqo9mrxtcGy5IUloEuUtP5tS1xxAy%2B2AfF2ZiQ%2BaAAGtiXpAfLDMQS8gZRBDy26r0Jk73bN95clPw5uUqxcQuqV9bECVCXSWwFUFle3wjJywhJKqr5slHbmKX5nsMIXuvk7A5M1-antxGWpWAGlEEQN4byvkFhZAnoyEEYJH7z3qrFKmaMU4Bw-vTNw4gvo5wCq8MwuBK4J2fmdZejdV57HTkHVBOMlYFBINERAOliBbQWGFRARx0AICgYMJ%2BsCfbwL9m2diyD5ZuH0LBJWXwTLEEIOHQgkdPgFAkYVGgVIhKwD4owwqVUTwwImg1IWFs35zXXj2fQitBjK2usyQg6jwiKhILfHaZ8iCX3LJowKid64rjYu-EhLcsT6DtqYjW1hIFTAZEceAkQiywEqiQHee9ZguJnNouBuiEH6MxhnNI%2BgQ6mIMhzSIRwaGYI5rgPImBciTASVZGuk1zapP8AseAQJIF5C8DQgxn9Bj6GzqY-4jTgTxPBhSaIVBkb4KXopIh-DvGGM6R3Ux-9AGqNyFkIekRpHx2ga4sZPDCEzSbtMjpZR9Bb1Mb3NZ-dIFmB0npbIO8KyID%2Bl3CWJdyqVWca6ei2yUm8LSYHVuEB9A-1OXSRCVJclmGgBSUyRBCoPO9BfT4RloDFnpLqWemzEnVJ0bUn5nj2koNcPodBpiWlQqrKwpAlTZKmGqKUAIZg7qVTsBhOoQA) after the unit to force a newline.
