### ISSUE TITLE
Fantomas adds "of" to a union case when it is seemingly _too long_

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fsprojects/fantomas#1796]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAKgE4CGAdgM7HToCWsp%2BOeAvGADqFukQQA%2BYAbQA8AYVgBbbDQA2ieADli4vG0gBRAB7pEhUsWlgRhOTXRgAQvrLQ8AJUQAzAK6l4qgHwBdMJu279RiboltLWiPbOrhxcPGD8wmKSMnKKyuyQgfCmFlakNmAAgvAAVk7k6MqkZgAUBdjY0jRyYA6EEobGWWYhYQCUHt6Zpj15iEWl5ZXodQ1N8ABibeJDwbk2kAA04FDkiOi0pADm5KiC2xCgsRCQACRYuKeQNFWb5zy3AG76TshoAm%2BxAAMWyu7wAkq5EFUAMo0ABeyBBoLAABYAWBPG8AL5Ii7o273X5QZ7oV6gz7fIn-ZFgACMuKukAAssQNAAZZ6INlQw7oAAWZORtIATID0ZjYji3pdGXcmI8AEawWDSQWxCnSH6nanI4UM9XQxDiGhwaT0AroNSuADyDg5pER6IgDn0u3F2IZMvVcoeaEgSpVaveNy%2BmqpTrAAGZ9e9odgqIhzI5YMYAArEEjKPxB2LoQg-d2Sz34n1E-3K1UxjVav4RlEx65xhNJhwprmwADuOmgxF2EI%2BsB7tHoOZ4eYLoIlPClsS9wcJioro%2Br4ZpAFYG1AmzYW22AKr1bu9xD9wfEYekUfO12IQvT4vk0uLwNVkOU7URgBsm8g28TyeMERQnIcgxAocdqBTK8WhvO8IBnHg52uJ8-QDSsS1DGszhpAB2H8-13YwmSNBUdGgl1pDdScPWlEsF1QpdX0w1dkQADnw%2BMdwAxAxDNS9NwoqirineCH1leioDQ5c3zDD8aQATg4hMCgcPxEnEYhoPHW9qKLWjHwk8sXww99axpWlgQjX9OP-VtjENY1TRHATYN0%2B99PE%2BUGOMx9mLkoV6Ssv8VL8ByTRVZyI20uCwAQvEDK8yTGJM2SzKFPUrIhJAqmtBhCEwAB1UwBRcyidOEmjZzoxKjPQ3zTOwoVoyCmyCjaFx4AAEUQRpjWzTdorc0SPO9QySWkvy0tBWl6yslkNDBBx8D5KE1DK6E%2BRTdAivgfloJRMUhtisTRpq8amIanVpo3ObWQhBwaA0a1cBIdAU00bBjBAuh%2BIjNdDoqvSqoS31iReC7Usa6bv1ujR7DgQh4B2vbNwOmK4rAJCoBQsHSQhrCrquWk8Nh%2BGUwUJxxFIwhbTBbRxBOTdaXRk75xq8QnGkWhGgdeYUw0-YdEYB58ZY6b2KssnEaZTnuc5PnCAF-qrOgPkMyoPwAH0OxoXaBRZka2dBp5wZSgmI1pRTYbakhMGtQgOXKZGSrrAHYhE47DeQsbTfqyHCdiUUf3mm3iDth2aHKeRKep2n6cZi2DeBzzjY5rmZHl-nzz8YXHT982aWFQKaUgUPw8d9AZfTnnEAVpWyJ-VX1eoHRtd1vak8Q6rjfOs2xauYUMpL%2BaADVKXMZ4siOZ39rdngPYxrGCTO33ZUmqGB%2Ba4fWXmFxqB%2BifXGeQ4Z9RueIAX1nvZXvG%2B-80FhVm7eNE62B0AAcT2D6vvIH7T7%2B8%2BGJKpdxBmWKSot74DxusPWWGcHTmDNNAAA1uYEgyC9jkFytCJQPEVSU1%2BjSQS5V3bAPiinMByV8790DjDEu8hEAdhrkmdAXYoS526g9UgpgfoFFcMRKmOgE6ENcoDdyydTrG3AXfKaA8SYlwANKIEQNgRay0oQQmwcoe0edkREM7mQiRZZe5UMgYHCWz81rGnIHyf%2BNI0ZHUXt3ChPk16XQjMKK2JdYRHFkG1Q4lMoTbUQAqJkCAdGgj0Q4q%2B2NDJSJMTI2IkZLIlwKI0Q4pBd55AvLCdJ54nDGHwLALKgTzw-XIiIkhQMQHkOfHVVx-sIyRmLsiUuXMdB6FoB8dsRx%2BHUw4c8bh9AhG6IqfPUhmMnG1Imm4mkkYh4tKrrQbRbIlAKngMQICsBf5HHoYwzk5Syr6ImaAqZECEk8EjFvFpnVI7EAVLISxkc%2BTQkwFUVkByhKVLEdUwxjwoTwFtNo6EWBZDTIabMp%2BLSrQArtPsxuhBpAOEgEcpeONapgoLsiSM0CWmKOUcUqoEJUHWBdsIw5USvYxJqnE%2BpmLQSRloS0hBZAkHaPIG1WAHV6HlDkIsuBiBv6IG%2BkMrS%2BZiFjKqQYo2zi6nenXgHC5cimUZkIogG55BoCEBoMaDpcg9xcPoN1aAoRXplNKp8iV3ypXX0kZQ2l1CLnmJacCrV1BQlIA%2BeKi%2B2JtieCRE8cg8xf6nD0ViIAA)

#### Code

```fsharp
type TransactionType = 
    | [<CompiledName "External Credit Balance Refund">] ExternalCreditBalanceRefund
    | [<CompiledName "Credit Balance Adjustment (Applied from Credit Balance)">] CreditBalanceAdjustmentAppliedFromCreditBalance
```
            

#### Result

```fsharp
type TransactionType =
    | [<CompiledName "External Credit Balance Refund">] ExternalCreditBalanceRefund
    | [<CompiledName "Credit Balance Adjustment (Applied from Credit Balance)">] CreditBalanceAdjustmentAppliedFromCreditBalance of


```
            
#### Problem description

Fantomas adds "of" to a union case when it is seemingly _too long_

The second union now has `of` at the end of the second union without types which breaks the generated code 

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 06/28/2021 08:27:00 - 31fc9494d1ff3248ab08555efcdb26496687ef5d

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Thank you for reporting this issue.
