### ISSUE TITLE
Nested Fluent API produces wrong code: misses indentation

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsprojects/fantomas#1804]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEOa9%2BAjAdAMrQAWiAtgIb4CqAzogE534CKArkwJ4A6jPAO2zCRGfAHUyjRAAoAZuyEAPMAFoAfGCX4ASrAA2iAJR9Bo81nwBZSgBdSiOvMXRbAS1hC9h2g0Zg4cgAHSgEuAEl4NU1AkLDIsAAfAH0NZOSTfiELHPxwgRlTbJySsDwiByp8AGFYYNC3RzZORl4s0o6xSSZZBWVorXwAGTdoRAExyKN8AFEAR3ZKfSd9UfHJ%2BEyzTo6iRENXZ36NQamineEtgUgAGnAoBlt3AQBzOlQwAG17iFBsSAAJLYuEFkGhIG4BLZbj8MICAG5LTgfb4iAAMdxEkHySChhDcAC9kJjhAAWWEQAC6sIAviTfhSoECQWCoJDofS4QDEfpkWhUcIAIyczCQGxKEYCRBDcYvWwkGEiQUAJjRjOpmDpsL%2BWEBwNBH0guFgBkVuu5SNZAuwypFcMIFFGBk8AEFbDMBPAAPJySXExkQORLBjq2mcnWi5kG8HG012hGWlEBsAAZjtEEghBCYwAQog5LBpAAFSiMSjkRC2Jhm7C2RicUOa8OMvUsw2x-Q1rk8vlfZOk9NQLOUXP5wvS2AAdyY0EoDHy8Ngs-cni7mDrDewGowWswEa5%2BtZRpNnfjFt5VuTAFZB5ns4g8wXpDQgqDGLP5wJF8uPNdB0HlkQRsd2bf4oyPDs1yZHtLxEAA2W9h1HJ9EGqfQ5zoWoBDoDdXELKDA2DICtzDbUW3A9sTyghMLyTEQAHZEPvR9xysChcGrf8iOAiBdwwfcMwomMqLPGC6OEAAOJiRwfMdpFqfRVy4wCeLAPiGTAw9KLjcixP5ZMAE5pLGF05CrRhanIKgCLADdiKwbdeNA80tOEnSwL0vslQxZM7xkljpAdcgnUUv9kwAkMSKbMjNLbNzT10xN9KVYVfKQxBTPMoKQqU5M7NU9SwAEplXKgSDRKSryhVtXycXGWwvQEAAVVpxDceUbIi%2BzMEctTnMjUrj3c81POtLBBTTNL7xdRhYEUeAABF9jcYLzJs-KopAmKXLitkoWo89ezGzBBQHXzxXCOQmrIAQZkAwgSELWw2vgDrB1JNVNqc7aBt2iF9oq2jkqFG9zsoJR8jkNwlC9N87ELGYlCCaQ6DoX8bKvT6HNIvdyMG9kDtG5NBQQsGlB0RA4EYeAXre-ssZ6nH%2BLxv6CcBo7icYsmKap%2BAADl2HIDjGB9cIq3Id5B0FAr%2BoPP7yHYfR3FWKUADFCyoJ4mCatt2dgoUpN8nnC3gKxFeVyFEHVxhNbW29SFLEdzOSSc3FehUZZ%2BuXoz2jlEqBqrsEFIyyZmssuC9RgRhw2mFXehmMF6writbH3-r9jzKuOjBVVvcUw8oCOo7cHCBaFphRfFyXic93HYrThWlbcFWrY1uxzJ1g09fEm1UqxAui%2Bj2wzablvrdtzjfIdstXCYF23Y62vmfro82f9jmRGVGqsXFAA1S0c0heBIReWObI%2BpeNJ2tO18zgPs4gZVJp38HVZcFcBEPz0T7P%2BPL6KlmN8Abr31jaM6L8lALVgLYAA4pWRGyNHBo08L-a8CcqRMyvr9NO5UQE9ywMqUGO9zbN0tjmRS0AADWOYZ6UMrHQRqhByyoQMILMKIgur-xTkJMqIk8HAxtKTLEfNECThbnmWw05xid0QEtKGAh2q-hdJ6Ni5dmCdW4l9PqXtBKDVwXfDewhlRcyxAAaUQIgIIl1rrjHyEwisfoNEqS0cnQBq9gEGNAQQw2EC7rBToCQVBIgL4uNlrov6%2BiRpZ2TMqEOWJ8SvEMDNF4gt6riEQLgKwCB-QcM0djaKddr4QT4Z4-BmAUw%2BX7qsF4Ag34TA-viGpdh2DSCarAOqUI7Do2UpFfJW1CnYOKcNSMRMRApj7sISALolZMAEF0%2BEE5XiqOFnIyEijPDV1yc4vp30BneyGQlUpAisApm3pMke7g-RDHLLgeAlA0KwDRq8ERYjLZON6YzApy8inaUOVE%2B%2ByYUzP0mQtEulBcCGD8SXEghAuCdKUO87qidMEAJXoacY3pfSW0IMCQwhNoljPAZMj0mLHH20YPoOQkAuFuN%2BfigFYyiGTPMZYjpth8g0NCKQRFNK0XxXpYY7AKYhGTPIaEShfo6AzTmp6EROFECmxIS3BBKNkHYXWvWJFGCvlYP2XS7uxzykmNFaWAKsiS7QEYCtSEdgFU0AUZ4Ja0B0Jlg-jy0JOiSoRJKf8wVJyfGTJxVa1wWSkDup2Wpe4lISQQjoKrNGHxOE0iAA)

#### Code

```fsharp
db.Schema.Users.Query
    .Where(fun x -> x.Role)
    .Matches(function Role.User companyId -> companyId |_->__)
    .In(
        db.Schema.Companies.Query
            .Where(fun x -> x.LicenceId).Equals(licenceId)
            .Select(fun x -> x.Id)
    )

```
            

#### Result

```fsharp
db
    .Schema
    .Users
    .Query
    .Where(fun x -> x.Role)
    .Matches(function
    | Role.User companyId -> companyId
    | _ -> __)
    .In(db
        .Schema
        .Companies
        .Query
        .Where(fun x -> x.LicenceId)
        .Equals(licenceId)
        .Select(fun x -> x.Id))

```
            
#### Problem description

Nested fluent APIs (a fluent API passed as argument to another fluent API) seem to produce wrong code. In the sample above the second `.Schema` (and the lines below) need to be indented further than `db`. The error repeats after manual fixing and it also breaks the cli tool.

#### Extra information

- [X] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 07/01/2021 18:56:12 - 3a128721c96086f25f2e6bde91e224ebbd3d4dd1

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Thanks for reporting this.

**Comment by alfonsogarciacaro** [comment]
Thanks to you @nojaf, fantomas is getting better and better! I'm starting to use it regularly in my projects :+1:

**Comment by nojaf** [comment]
That is wonderful news!
