### ISSUE TITLE
Lazy causes indentation to produce invalid F#

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1805]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYrLGALwA6AdhBHgC5gBmxZVN7YOAhgF4CeYABRsOogJaMwlWAwA8AHzAAjLgCcwdABaJKI0frCquYgM74FYAKIAPaIgAOdMbGrlIANUSqBANy%2B--MD9vIMDggJDw0Miw2Jj4gRwXAHM3PQNORAZVLLImLhwzdIMJQ1ytHWKMiDdmWDTqarBEQsQq6rcVVQamsHkAPk5YZIA6AElKZnaOHLppgEpIABpwKDM6J0pkk1QwAG1ViFBRSAASOj57ZDRIMUo6ZcOaM58CrGv9p-YABhWDSAmSHuAGUxDxkH99AAWL5gAC6TwAvpCjrCzhcrrtbvdHidTq8cO9dgcDABGFEcSAAWS41gAMndEHSdMktLj9KSAEzfWEI9jIp7HSnnS4fSBKYg4dnsF5vD4k-Sciky4GIdBiOBJSgAQTolko8AA8owGZQIbCIIwCmZeUiKUKZSLMTcJbApcqoPi5cSLWAAMweiCQYH2Lh2ABCiGYOQACmouOgsl5pRw6Kp3rb%2Bfa0U6xa73TmCUS0ArRFDA1AQ2HEJHo0zYAB3LzQLhmCY%2BWAtpwuFPsNMZ0R8mgC9gO565rH53ueovy30AVgrwdDEajsByAFV7FdVC225QO13nJRp5brYhM8Ps3iMXnJdPZYS5wYAGxLqurusAYW4JhMX5cEx%2B2gOh11PfJWkvCARxoMcgwnF17w9R9i0%2BAwAHZ3xXGs1xyKk1SUZMKytSDBztQUc1vSckMLb0S19AAOLDq1rddEAArVwJIm0yKzCib1Fai3QfL0nx9AwAE5mLsbVGDoLwAPQdAuHA-sL14q9%2BOFKjEOE5DRNQ0sOFJX5fWXFjcMQVV1U1HtiPPKCwBg1EBOdKAp302dxI5ckzI-RBZPk1RrI1N07N9NTHOcsA4M9HT3JovEvPosklTMwEdDoQ1KAAFW8AB1MQ2Xs0iOCHaDr20wTdILJK6LQjkAz87DtVUWAsANAARFoxHVILVPTdSyvI0dKOqqA7geTz6qM9hSXLMyaWsMZGBy7RKEsVpgU0dc6EK%2BBit9KEeQ0iqtMdeLsSm2ixJSjlF0W2kJkYMRrENHcuFA1QbHsHI-2PcD5xO4a%2BNG1yxUmkTkoa0RSTfR7rAAJUQOBVHgfbDoMY6osqi7xquqGZt9UlMIR5HUfgAA5LB0EI1RjTGeT0B2CtSRx87x0u9BcCcHBGSIVRlI2LwcsE6bbph4ymLM8n13gKkebEPmzQFoX%2BqXaBNHjECvAAfQbMQDs0SB2bBqq3IJ8XDOJqSEdaow%2BENVQGSAjHjYrbHTqc3HOfxyGrefRVTP%2BJb7a4R3ndMOhqdprwGaZlnidN2Cxot7mcF5-n1zVkWxZu62DE5Xz-jDiOXboBWM6VrPBc%2B9WzM17Wgv1w22WTlzzYhnEA%2B80ROTSkPaXcOVwzueA7mSN3wM9kHNLNvGLf9-PA77prB%2BsAgOpA49R4NCep494H2HK72Ofgy6l7qiXZpoTkFvXzqZAAcSyH6-pMY8D4XI%2BaBP6LYvRPjDyy9e4cE5A9EOitlY1iSNAAA1uGIw8CsgmGysCBM7E3Q0xPCVHis8zrz19hbYBV8C6Knhv8SmiAGzQMjHQJsOhRZXG6i9SgRVjzagNPhWOqhE4GG4kNY%2BI0U7gyErVYU0Mb4QE5KTf4ABpRADgVprR0BMdBiZTTmn4Q5L2-9U5d2uqQleYDpbr02uqEwmgv5Yx-hAP%2BPtz5AMShIomhdbb-FBFsPArVkg00yvlRASgqQIC0foAR7cYr6LEYTa%2Bvo-TB30JAbUfNkiUE3pQbeLhQSpM%2BlgHIOVYAZXuJ9AGuDBG-2ER3Bed49IgLuqIP0xdEnJKCpQEpfg6QpG4XTFhdx2GAS4jo-Bp9CGOOIc4x0ki4kD0SZXJwmi6QJiUPALgP5YAfy2FQmhjJBmlSEaDERndok93qRwP0a9EmdVMFwJQeBzGmE0MCPgxTrC7LwfsuehzqlYh0EaE0jJgQXDwDEshDT76JP1H8zR4EYCqBwIwE2uiHFxScbUoxoD2B%2BggYkhRSiDSZQmIgrgGT3a%2BnCUis%2BKLxlopcbEgwfoKGJPDNwSgcDNEmFau1A0VCgKIHllAxkb9ED-QGRWSKFLRlUpqeIyZrj9B%2BlkUytQrEchXJMNAVQvU7ifT5RuNhLhurQG4EYbsOCyVDI%2BQQr5RDpUguMZi0xiTAWapAsEpAbzyl2KRKsOEkJbgmAIB-XY4TERAA)

#### Code

```fsharp
module Foo =
    let foo =
        lazy (
            if not <| bar then
                raise <| Exception "Very very very very very very very very very very very very very very long"
            let ret = false
            if ret then
                "foo"
            else
                "bar"
            |> log.Info
            ret
        )
```
            

#### Result

```fsharp
module Foo =
    let foo =
        lazy
            (if not <| bar then
                 raise
                 <| Exception "Very very very very very very very very very very very very very very long"

            let ret = false

            if ret then "foo" else "bar"
            |> log.Info

            ret)

```
            
#### Problem description

The `let ret = false` line can't go where it currently is, for indentation reasons. I think the solution in the original code snippet, of putting the bracket on the preceding line and then indenting everything one place, looks best - but possibly worth discussing with other people.

#### Extra information

- [/] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 07/01/2021 18:56:12 - 3a128721c96086f25f2e6bde91e224ebbd3d4dd1

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by Smaug123** [comment]
We have an easy workaround for this internally: in scope, we've already essentially got `Lazy.fromFunc : (unit -> 'a) -> Lazy<'a>` which we can use instead.

**Comment by nojaf** [comment]
I'm going to solve the problem of the invalid result in this issue, but I also raised https://github.com/dotnet/docs/issues/24977. So perhaps later, I can circle back if this is also a stylistic bug.
