### ISSUE TITLE
Fantomas introduces meaningless `match` block

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1806]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYrLGALwA6AdhBHgC5gBGAhgE5gAUAlGVTf2GB8BIoiQrURUiIxzMAFsOkiAPgD4wAZTqss0OgDp0zAA6cAZlmoB9TswA0Ya4%2Bs8AtBvMBLHHUSsAIWZoAGsvSgBzAGcwZi4lAQBfSHtwKCjEOjpw6NQwAG00iFARSAASOgBPE2Q0SHC6FKKacoA3ZhwsWoLm-gAGVOlIAElKJEo6TS8AL2RBqQAWXrAAXWbE%2BeLl8qqavPqJptKy9s7uwukARk2BSABZZgAPABlwxGfESLp5I6lLgCY%2Bss1vwNs0SrcKtVupBGMQcL9%2BG0Ol08hcpP8bkjNIh0F44DhYJQAIJ0ACiYwA8uZXpQ5ssIOYOhlgesbhCkVC9nU4bAEVioCcUecGWAAMwCiCQTQmYKIAKIcywViIAAKbGY6Ey-kRAh0XVZoPZ2y5MN5-JNp1RaHRIgWkqgMrlCqVKuesAA7v5oMwMqNWrAfdkibr%2BPrEIaaGD%2BByWqb9ubQ4KrSLpABWB3S2XQeWK5WIACqJhqrB9fsoAaDXhDDqZOBZIhBUeNx12ZvhSeRZzRooAbJmnTmXfmAMJyKJREdEqL6-TKpOM5kRxts8EmtsJjsCrvWnrSADsA%2BzuddiDuuMYOtrS8jEGjNFjUvjPK3luFPekAA4j868yqp4SlALmAdYNgITZ3i2kIbi%2BfKdkK3Y2qKACcP45sS5h%2BKwU7oMYwHhreYD3lsrbQpucHbghu62gIlwDKKWa-qeOJ4gSNaiqBy7gauMbrmRsEWscKYfn81wMYOiAYVhLH4ny7HSARK5GmupHclAiaUcJSFXJiDGjOMdCUpQAAqrCVAA6l43zAZxhHEYIfFqbCr5Ce%2B2l-BK4nHsSrCwFY8AACKIDgXh4lh%2BG6Fx-AQURUGcjBUANPBWl7n89oMQ8jzDOYxnyJ8ZL1ogmjyMqdCWfA1kOgsQJKc2KnQfxiWHJpbmpSIlwZhlTyjN4jyUiWzB0MqZKPCYKoTtWQEOmmNXccpvGqTCSUtYhbW0f2XWPAASogcCsPA5WVaK1V2XFcYJQcjQrdRoqXIem07Xt8AAHJYOgl6sNSwx%2BOgUTAZcp31fFjWQOguDZCFdJEKwxhZP4xlkddqZ-N%2BDGPcq8B3ODPhvNDsPhZm0DyBq%2Bj%2BNYHpeBVPyAwtDVOctb6rTR-CXKhm0%2BawzCVJSrCvDOh0-FVs3RTxD6OUtzWMzd0iApmmUc1zPN83Qr3vf4X0-X9DoA7VkFA%2BdINg74ONQ8q%2BPw4jUvIyI-xiUMCvc7zXgzljxuQ4geODQTDFEyTWHk5T1k02Li37AzrlM6K-y6UMmUAGrCgE4TwDkAvASduuxfrT4XeHkIpczND-J5sdPAQVj6JNSdjKngeC8dws0DF9mPoKueSxH0sYulpePAFsB0AA4pkI1jYgE1Emn02NxAzdnTnIMaVbIk251sfY%2B7ASEqEASc6EmRREZmiaogAFvVNHE3pnLfi%2BRgn561hcQP8G1DM9iAepvmRep8CM1EF3hKBWUmsSMY541asC1pfQqwcSJ03bBRZe7kbb3SGAAaUQIgEw2VcqfFGMfLUtJ6TSFstfeebcQZ505AXKOqNe4FTxFEeQU8G6wIcqHASyVH5RzZkMKYkQ8A%2BQiG9T4ZVECMDuAgYhUhSFzTqrTYGTkl6d2tgIMU9F7YhQiJQculBK5EimNowaWAVTGVgPpURg1Jo2SvnIvWCiDZKJcg-SO0gxR2ykJAYkvh-CUCsa0d4RIIjgI%2BgA8IwDpw2JgWQ7OFCnGIJUSvNRMdPGu2yEQ54mpGDwGYGOWAUQcjv0-m8KJYERbzRDvAu%2BXDXFSDFCXTxAVnbMFkIgBhzt5CaEqBMJ4pSopN1FnAxRMJPjwGpEQ7QlQ8A1K7iIMUPdPEUjGTSEphNWA4HMJANhrcdiL2cdQ7hbi16eIwVgixExRi72YHo%2BuJDbHlPkZU4Z1SkZJP4GKV%2Bnit7XJCEQqIPk-JjHfjORAmMN5vFHuNApkSHSKTsVnBxC94n3wObUuZqCvlsGHCqJpURoCsFCuEQaoKCxAKJEFaAchObBgvnc6J8Kb4cPUvsuMNC3F0M8doAl%2BhJFID6XZNIKx5j1CiAQApeRbKJCAA)

#### Code

```fsharp
module Foo =
    let bar () =
        {
            Foo =
                blah
                |> Struct.map (fun _ (a, _, _) -> filterBackings a)
        }
```
            

#### Result

```fsharp
module Foo =
    let bar () =
        { Foo =
              blah
              |> Struct.map
                  (fun _ (a, _, _) ->
                      match _arg2 with
                      | _ ->
                          match _arg2 with
                          | _ -> filterBackings a) }

```
            
#### Problem description

I honestly have not the faintest idea how this could have happened, but anyway, the additional `match` block is not meant to be there.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 07/01/2021 18:56:12 - 3a128721c96086f25f2e6bde91e224ebbd3d4dd1

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by auduchinok** [comment]
Parser does some desugaring for lambdas, and these nested matches are what type checker is dealing with later. @nojaf I've added the originally parsed lambdas to the tree in https://github.com/dotnet/fsharp/pull/10166 to workaround the same problem in our plugin.

**Comment by nojaf** [comment]
Yep, that is exactly what I'm using and has been really helpful.
The challenge here seems to be finding the correct body expression.
https://github.com/fsprojects/fantomas/blob/3a128721c96086f25f2e6bde91e224ebbd3d4dd1/src/Fantomas/SourceParser.fs#L1250-L1269

**Comment by auduchinok** [comment]
I might've added some incorrect range in the PR, since I found I've also added a workaround for getting the body, see `skipGeneratedMatch` [here](https://github.com/JetBrains/resharper-fsharp/blob/6b2a67d5df63a5697e31efbd5cf02b0dc30f7b21/ReSharper.FSharp/src/FSharp.Psi.Features/src/Parsing/FcsSyntaxTreeUtil.fs#L128). I think we should fix that range in FCS. :)

**Comment by nojaf** [comment]
Many thanks for the pointer there. I'll check if I can fix this in FCS sometime.
