### ISSUE TITLE
Comment is lost at the end of a match

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1822]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYrLGALwA6AdlRBHgC5gBGOAhgBZk208CW93HhAA%2BAPjAAZXgGd6AOn6IATmAAUAMyyU1AfQA0YWFnoAHYwEowAWlGChPeu16UA5nfsjxAWVYmF9ZTVNbQBrRABPMAA3VhwsfBt3Dx50VnpoThi4-AB3fnYk5JEwAHkQtQAVRFkAJWrceQJWXjilfHVLGzB1Zpw8xzBySCHCouEwAFElJVgVBPEelv7OEeHtIvtxnWtxVUsAen2wJwBCUZ5zUfNIPXAoaUR6emcXaVQwAG07iFB7SAASejhEzINCQZz0G7fWgArLxd5fZIABluyUgAElKEhKPQAMq8ABeyFRHgALNCIABdaEAXxJPwpUEBwNBUAhUL%2B-zhrMRHgAjPShJAfAAPKSURASRCuRwc-kAJiRjOpPDp0N%2BQuZIPekCYxBwcp4sNi8LQvPs8sFRtxiHQvDgOFglAAgvQJliSupxcTGRAejgHsraYKNUatazdfrDTCuSaeb6wABmK0w3EmVjQRAAIUQ6lmiAACqwlKx0I9lNGHEp4kHVSHGQCgdqwXrYAaU8bsgiE6SUxBIGmM9nc-mJLAcspoKwHpiorAp88nZXaPRq4ha7Q1TxQzGmxHW%2B2G7Gu2aEwBWPtQQeZnN5toAVRMIKUU5nlDnC94S8v-sD9hVm71pye46gey6dqanwJgAbJeA7pjeI5tAAwmw0jSMhTqyNW0D0LMy5%2BrEf5CABEBbrQO79uGoFRh2x6QeaQgAOxwdew53ogXi2kwFY-kR67-sG6pHiBLa0Ue3LdskAAcrEIex%2BaYY6lAEd0-EbmRQGaqJUBgXRkmnskACcclDs66gBEomHoKkqmrjWgl1sJwEsjRbbgfR8bJHyKIJvBQ63vmNp2g634Jr%2BAkkUJ24ia5YnufpcZSfyAp%2BWx5mWcF9ptmFyT2ZFPCkWA5EMi5za6eJnIGVB3mWn5mLYvQJSUBUSjhAA6vkqkRRpxVaWGOmRglElJYZ-LJml8nOjMWjwAAIogOC8Hall2WuvUlWAlFMoN7KJSeNX8r2fmiui6gVOw0oTAGiC4uwsz0J18CypepJKo5gHOdpcVsjiHnVYxPB8heJ2sCKmLqLwIolM%2BaSzBMIomG06Ffipl5nu9UVOTFZURntI0HYDtB8rBoMinUcBKPAT0vT2mOFdFFGxeV4J-ftDEJnyLFkxTszwAAclg6A8UonrogE6BvJefIbf1u4-ZA6ANC0ziIEQSipE8ygVK57Nefysl%2BbzVNeMrS0SurmurXBGTFhmlk6Hkz3sJAstfQNCv41Vo2HfYfImWT00luEJRKFIsg0y7r307QRWbdtjae2zBMc8kipwaKQesCHYcyPQgvC8oYsS1LnNuzj30s0rODPObauzFb2u6yn%2BsWqlaJZzn4f0KbNcqxbDdpNbfm2yWuHKI7vDO67H2ae78ss17moAwm8p1WiooAGpxlmzjwC8keqW95dM7jOpL2GK9pxNG9gwQWi4aju9YgfU%2B08kx%2Bz3189Ubtyfe4TVex1b4ijmrAegABxR4CMkbVGkKjQ%2B6MY5UkZqVSu%2B5KrLx9kTCA8oQYbzNqrLMjpoAhCzGPMI9BpDNVxKWRASkhZo3CupL%2B8dmYYOGgA1OHh5SkzRPzRAOQ645noBOaUOsQQLUhpQfgqNnRYi4oXJQpdkg9VYXLX%2BCs9It2ShabmaIADSiBEAmDOhdaUmJaFlm9N1FhWNPoVw9ovf%2BWDAFp0NiA66dppDsEQXTE%2BaCnEcMPFw1uQh5QBzRPiVweBpouCFtKR6iAmBeAQD6VRdiGbY1PugtyITXHcPsImXyHclouEoPfSgj8nT4nKWkLAbQKiwAaoktIqNbE3QCVtdheT-rYITImduHhIDOhrsoSgbSoiSidC4RRIspHOFkVhDpxEskOJyUE3petdFCETOvYZvdnjegkKWJg8BWCoVgPA1wAihGqxWQVWOqDuln3ivky%2B-TkiJhvsMuaMhWAsEQF4mQ7BcThBxGDB5XSE7UTBNKeAnpvS4iBHgPpbiPCJmAcM90CKvT3JtkoHA6gZ72Lno4hewS0WFN2fg4ZRiTEtJxJichrAqlR2YZ09RP8dpaMwR89FRS%2BHDOIaykI3ppDTSMFiARshEDwEOf3IFiNkbwOWZefK0KelvKpWEngiZ9HCuLIFNofzpDQCUMtZwaQ5X3hkU6Ba0A2AlkXEwjJnLSXf3JZolm2jQk7L1R44ZyKLW4VSUgKFrC7iUhJOCaQBB4HvB6jSIAA)

#### Code

```fsharp
module Foo =

    let blah =
        it
        |> List.iter (fun (_, output) ->
            thing
            |> Map.iter (fun key value ->
                match value with
                | Ok (TestResult.Failure f) -> failwith ""
                | Error e -> failwith ""
                | _ -> () // hi!
            )
        )
```
            

#### Result

```fsharp
module Foo =

    let blah =
        it
        |> List.iter
            (fun (_, output) ->
                thing
                |> Map.iter
                    (fun key value ->
                        match value with
                        | Ok (TestResult.Failure f) -> failwith ""
                        | Error e -> failwith ""
                        | _ -> ()))

```
            
#### Problem description

Notice that the `// hi!` has vanished.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 07/07/2021 07:46:28 - 6f0df78847a1dbb3c87fa2e00c6390703905b7c1

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
This happens as well with `fsharp_multi_line_lambda_closing_newline=true`.
