### ISSUE TITLE
Overly indented members on a record type with accessibility modifier

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1824]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwAVACwEt0BzAHXUYBcBPA0gMVljAF5GECAQBOVAG6ZmiQULnBZcpWABCmEWDQ1mi5UICKAVwAemsHmZi6uuQF9dFqVWhhc2AEaINagF5ntkAA04FB4iMzMNLR4qGAA2iEQoMqQACRsHLGQAcEpqZIANobIaAl6YAAMuXqQAJLoSOjMAMpUPsjVygAsiUIAur22nWDJSmkZJVA5vRBphcWxZXoAjMNykACymMYAMjSIO4h0zBRBM0LLAEwV5wN2w6Pr6eyTkO48BWd585NLypdrISQZqIbDOWAFWDoACCzAAog0APIAMz26A65wgyMwBTCt0GD3O4xeWXeEK%2BY3yOIWpUxYAAzIDZs0iCQVIhkbARIgAArqHDhLwU5SWYr4%2B69R5A56ZNBvD7C6U-RZ0rpMqAs4iIdmc7k7WAAdy80EwYXq4lgJsiUMVclFiHFQiGkqJMteZM%2BgLm1N%2BdIArOrgaztRyuYgAKoEDgiE1m9AWq1UG3q7G4h3KO5Owl5CakhVeqlFX3lABsgc1bND3IAwgVTXhq1CLCJDNBmFzbUJU3iMwSXTmSXKPZ3vUWVeUAOzl4M6sMbUGeESdrE4ntKTMQZ3yV25of513K2nlAAc061s5rEOTdO76fXfe3A9lUGHBcP8TpAE4zyRocjpCIjbYNgmDLmA9qOpu2aUruL77t8PrjisVR0kG55VogIJgnAkLoGBt6QWAW5CFKsxunm5JvohR4rKsqEVogf4AVh4K4WBEG9hKj4wYOcGUQe1EfuUVyBvUjTMIi6BkCIrAAOpUCc%2BGrnecgbkR0FPLB8r8QhY40coyyMvRwbQiIsCGA0AAiiAFFQYIAexLYqf0D4kTuvHZE0I6FjSQkrGqqFbMYtTIpQRxwmmzQUFyzDyfAinql0NycVm-Y8c%2BnnMN575-EoywBoF2z1MiVDGIi0ZSFycLGKI%2BB4EmeHqn6yX3lxblPq80y6b5uVyMsZaFcYABKiBwCI8BxQlqotaprlJO5GVdZSOV0ssU6DSNY3wAAcoYHheCitTSNgMTqsshHEfNHVZNghgFJEtnotwIggREXhkCSVF6X5Bmnqhm1cvAGx3Q9%2BzPa9DmBtAFD8m2XgAPoGlQ8WnBdGnSlpS1PCtwnfoNpkiJgrCIiIewWJNpyJTNLltVd6WdV5X09XS1yBkFBNEyTZPMLt%2B0iIdx2nataNpZpHm3fdVCPYg4NSABH2ZEzxZ6JcdHlJAHPE6TVAWMDkvS7Lb1LlDMOE3DIiI8jiki9xYuLYzAnfb1QiXACg0AGo%2BioNDwFEFNgUlNvtfTWRY0qgnOxAlxGerQWcBZbYNd7DR%2B1blPTUHdN2wzWVK0h-wBbH2yWbAzAAOLhNVtV4PVUL%2B011MQGpl0jAt7rwctEcswVscg1L%2BwqJC0AANYqGbw-hHgknNAKjZFNgjV0hxrWpbbGMea%2BjvM%2BUlwDer22IAa0vsswRpHAriDWSV6AKQ10INPOfNC%2BUBEpVBovrxlm-dcr-zrerABpRAiACAhTCugeoM9cBogxC-ZSmdW7XTlGHMiOMVZ-SLsYCKYI8AUHrhnN%2B6kP5kS0t-TuTsWZ43Vq0OgBRGIiFoHtI4sVEDuA2AgWBehX4r3fmvEhG8O7Yy7uUekKF1bQlsrQdA8d0CJyhK0KRUhDDcjILAMSzCnDXjgWmBBpEoDkT3Dpch289D0jVjUCRAEsCRHEAcKEtBH6LivjQW%2BTYlI6MIS3PRxIv6CPDhQkRbte6SxgTsHA7h4CYFrLAeqdAD5H32O4tcs1aaIJDoYz0W9f5KHpDHGolkdaYHcHQ7BOsKDNFYE0bYSTnJNzmmk7OWQjjwBRDA5obA6HZWEaYwuNQEQtNRIkqGIgCjIkgLotuFFMk-3zjknuNQgEgPUU0eoY9MCyPTto5JNNV7B0aRkrpATTF7xqIPdZw8YF4FMuZBoB8LCICBn3aWVduQ1was-PQy8Um7Kzp-duRihFHOUPSf%2Bpz1AXkvjraAYgwTWIeeGG%2BUJrLQDrITa0i8tm1LAM3dG-DfEAv8SY4FGCajtLEG2dhSAakXRCH0ao2Q8CcHqrECCtggA)

#### Code

```fsharp
namespace Thing

type Foo =
    private
        {
            Bar : int
            Qux : string
        }
    static member Baz : int
```
            

#### Result

```fsharp
namespace Thing

type Foo =
    private
        {
            Bar: int
            Qux: string
        }
        static member Baz : int

```
            
#### Problem description

This is an incredibly minor, low-priority, stylistic point, and it might not even be wrong, but I did have to check whether it was valid (it violated my intuitions). I had to check whether `Baz` came under the `private` modifier after formatting (it does not; the formatted version is sematically identical to the first). If we didn't indent the `static member`, then there would be no possible confusion here.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 07/07/2021 07:46:28 - 6f0df78847a1dbb3c87fa2e00c6390703905b7c1

```fsharp
    { config with
                MultilineBlockBracketsOnSameColumn = true }
```

*Signature file*

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
We seem to have it do it differently for [implementation files](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwAVACwEt0BzAHXUYBcBPA0gMVljAF5GECAQBOVAG6ZmiQULnBZcpWABCmEWDQ1mi5UICKAVwAemsHmZi6uuQF9dFqVWhhc2AEaINagF5nt-GAADJAANOBQeIjMzDS0eKhgANoREKDKkAAkbByJkNphqUJZkgA2hshoKXrB4TWQAJLoSOjMAMpUPsh1egAsRRAAukW2PWkDUNnslVAFY8WZZRWJ1XoAjPNykACymMYAMjSI%2B4h0zBSFNWsATEETw3bz6UpZOTOQ7jylly%2BLmOUzVbKa6bYptRDYZywUqwdAAQWYAFFmgB5ABmh3Q3QmEDR-yi9xGTwmr2meU%2B0J%2BWz%2BAJWOLAAGZQRBIG0iCQVIg0bARIgAArqHDRLxUpSWCqEx5FZ7Ut7kr6ilk05ZVem9ZlQNnERCc7m8-awADuXmgmCiTXEsFNsVhiqE4sQkqEo2lJKmuTQHwVoJK-xVyXpAFYNaz2TquTzEABVAgcESm83oS3Wqi2jV40oE5QPZ3EjLu94U74%2B5WA%2BkANhDWo5Ed5AGFSma8HXYRYRIZoMweXbcfjHdmia783LPUW7b7aaqagB2Kth3WR7YQzwiHtgDNZpQ5iAu%2BRukdQMclpZlmoADjn2oX9ehafpG-7W8He%2BHZNH3rdJ7pNQAnJeSHCaLSCILbYNgmBrg6To7nmvwHl6lLHn6p7rEE-7hnqiDgpCcAwuga4PtBYC7kIMoLPBR6fsh37rBs9KhtqgHAdhUJ4ZB7aPnI27EbBspvoeH75l%2BU7rCC9FNC0zAougZAiKwADqVDnARfZESR4yvh6AmIVRk4BlcTL0dWiBwiIsCGM0AAiiClFQkLAexEoDlKL5wfx%2BStOOpY0coazqvRuzGA0aKUKciKZlhFA8swinwMpGq9Hczm5kOblaR5zBecJ%2BnrMGAV7E0aJUMYKJxlIPKIsYoj4Hgqb4RqgZJU%2BLmkfu7lzLp-pAkoayVvlxgAEqIHAIjwLF8Vqk1XHPq1mnvB1QnUSJvmzv1Q0jfAAByhgeF46INNI2AJBqaxqbx5HudghilLEtlYtwIjgTEXhkGSSF6d1chrBe9HrTy8DbNdt1HA9T0OSG0AUIKnZeAA%2BoaVBxRcZ2pXx6ULb82WfUIax-v1pkiJgrAoiIhwWONFwJVNQjcepYBkUq8EY9SWP0rcIaBQTRMk2TzDbbtIj7Ydx30qdyUwajF3pVdN1UHdiCg1IwGvbk71dWzdH1FzxOk1QFiA7L8uK89q4Q1DhMwyI8OI8pKOuWj82eWrKHAmJ9SBQAashKg0PAcQU2uiV27NaWO5lzs%2BUo1yGe7eycBZnZ1T7zT%2BzblOTcHGmh3kzMLKzNTXP5sfGJZsDMAA4tElXVXgtWwgHDXU0MM1Zw78o6YtH1s3l7tA3LRwqDC0AANYqBbw-RHg0ltEKLblNg9X0lB4s8ZLjPuZRnfqwXfX1JtiCGvLnLMMapwq4g1lFegSl1XCzRLgLIs1IRK90wzkwUYJmNLTlwKrfUABpRAiACDBVCugJoM9cCYmxM-VSr9zrr3Rk7TqLso4-WLuFSEeAKANwzggteH8N5fxZj-bGEBrh43qB0OgpQTIiFoDtU4MVEDuG2AgWBegX7NRSvbKWhYSF5zIfSBkaF6JwlsrQdA8d0CJ1hB0KRUhDC8jILACSzCnB3jgRFTO9M2rpU3t-LuNQGSaz0JACRwEsCxHEMcWEtAH4rkvjQG%2BrYVI6IIXwpBAiO5GO3noBkbtzEG1iDA-YOB3DwEwA2WAtU6D70Pkcdxm5potVbvw9uxZUGRzkAyGO5jLJ60wO4OhWC9YUDaKwVoexkmcRpi3PRc08inHgOiGBbQ2B0KysIkxRdzHIlaRiJJEMRClDRJAXR79SQGMEUqfOASe7mKASA9RrQmhj0wLI9O2iUn1LSY07O75fGkOMQE3e5jB6bOHjAvAplzLNH3hYRAAM%2B7y2rryWudUn56GXjwiWXiiEzOOUI05ygGT-wueoa8F89bQDEJCaxzyozX1hNZaAjZCY2kXjsupzd9lTILJk7poKlAMgweYjpYhOzsKQLUtSERBg9HyHgTgtVEiEVsEAA) so I believe this is a valid report.
