### ISSUE TITLE
KeepIndentInBranch not respected inside a `let` and `match`

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#1825]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYrLGALwA6AdlRBHgC5gBGOAhgBZk20-c92JGrLpX5iw6VvWid6AJyz4A7gEt67PuIgAfMADNWOAM74AtAD5NWnpOmc5iI7kar1V6zrABROXNhywAH0wC31WFRxXTnJIGPcPXQB5AGsgkMtRD34ABzkVSno9URj2FTjMrNoDCKiwGJYOZjZOBpbm8srdeUV0sJq1aNjY6gr%2BasiBuqHIABpwKBN6enyAcyNUMABteYhQMUgAEnoAT2zkNEh8%2Blmd2kOAN0NFDe2tAAY5rUgASUokAoAyioAF7IT7iAAstwgAF1bgBfcG7aFQI6nc5QK43fYHR44Z5oV7iACMSP4kAAsqwAB4AGXyiFpiEoK3U2JJACY3ii4TxEbc9uS0WcNpAmMQcOyeA8nhiiWIOWTpQDEOgVHAcLBKABBeheP6JPT0yhglEQAzGRA8hFkwXS4UYsUSqV3XGyl5msAAZiVdwB2VY0EQACFEHp-IgAAqsOSsdCCRByF08bpWsS82j8nh210nEUXcWwSW%2BmX4uWeiG%2BiCQf2BkNhiO02BKRPQVgmX73WBt5Za5O0VPWvm2lGHPOOwvF0dusserQAVirUFrQdD4YcAFVsmc5G2O5Quz2VH2lxaTEPMyOcePRZP%2B6WCVtPQA2Jc1gOrhsOADCbCMRm-LUjG6aB6H8ftzUMc90xtAVpxvAtnRLGdH3lfgAHY3xXet10QClVSYRMILCS0LwgLNaBzasHVvJDpzxVDPQADiwj8cIjQDNUoYizzTfgM3Iq8hQQqA72Qhjyy0ABOVi621PR6ETQD0EkYjBxg4c4OvdFaKLe8UMkkkPk9d86zXCMVTVDUT09XiyLACjkW0-NRLonEJLnElSRM7D5MUuRLPVIsbK0dT%2BNg7N4J0xC9PE91CU9YlFRM35-noRJKAAFTkY4AHUBh4qC%2BJ4ASHKE%2B0RKdWL6Pip8tGJH0fLY7U-CwP4ABFEBwFQ1X8tSFGK2hSscsAqNRSqsTi2cEvqysTKpalvj0TL2GZLxLQBdh-HofL4DZJcIW5DTLy04TosxAp9I8maSUXeaaV%2BPQVGpRIdykfwvGpXJHCMY9uKXecjvCzTIucx1Jpq6a6pJV97upAAlRA4DkeBdv2isgZKiLKKilzLkuqbGPqzC4cR5H4AAOSwdBCLkQ1vkU9B1iXYl7JGsax3OyB0GcCIGSIORbH8zKdMJwyxGJFiTLJ-x4ApXnupNAWhaIt8ZBjQN-MCVQ9vYSA2fK3MuYh9zarQnhiRkuGWtjY5EjkelgLRvWDsxobsacs68ZNoVruhhVjK%2BBabdYO2HZUYCqZpxN6cZ5nEoN06Kq5nmcGWRXEGVqRhdFyGifEDlvK%2BEOw8d%2Bh5bTvmlf8FWkzV9gNdAxNtZUXX9eOwSk6N72Cbz8X%2BA5ZKg5pAA1WVg3yeBVmd4jDsT0GvfB3vTah83aA5Rrh%2BpAg2tAv6J7%2BafW-RrQ547squ%2Boibl99s3PQ5Oat-a2B6AAcUET7vv-P6Z4Bt3YQ9qNXGE43K31XvfO6QcFYMmDJqaAyRgyxngYIIwGUARxkQJxam-1PRhSxiDHGYNdJThXvnBUsMvgU0QEoDOoZ6AtmZCLM4nUnqUDUH9bUfx8LRzkPHLQdlz7s2AcQq6d8tAchJl8AA0ogRA2QlorWZL8dB8ZjSmn4UVeehDF6ih9vaP2a8IAcillvdaaojDsF-hjLRntk54zEn3TyCorZfCBCyPALUVjU2ZDtRATAKQIHUeIARwMToLzsSA6qpD%2B48C9IHcQkBtTdRWJQHelA95aiBCkqQWAHCZVgKlHxUg-qFVIoIw2V8uYOOiU4-gXoi4JKSf5SgxT7iMi1CsbhtMWH5HYUBUp0FQmd3Cd3SJJCwFkLqUPBJFdlhqNpHGJg8BWC-lgL9FkVCaEMgGYNABBDbGjJEWLWpsTN4JPahHVgLBEBmIjuwAExwCg0h2TYoBRCLjMngIaNRAITh4FEeArQXpH4JP1F8o02y1ZyBwHoduQyL4jMqfY0B%2BixHiC9JAhJMi5GFIKL8RBrB0ku1wQNV5HMaIxXGaiwF6KKEJNgYS5IaijAtVgG1SmjhFJy2gSaT%2BDhv79KXHg92%2By3k6MpQCyZsTJH0pjOZBwFyjDQDyGqFpXKNxsK1J1aAbBYy9hwRosp8KhHvNclEiZMTaBehMQk35eRQIBKQC8wR8wYTgkuEYAgv0Nh2XhEAA)

#### Code

```fsharp
module Foo =

    let blah =
        
        let a =
            match true with
            | false ->
                match result with
                | Error _ -> failwith ""
                | Ok _ ->
                printfn "hi"
                failwith "blah blah blah blah"
            | true -> failwith ""

        failwith ""
```
            

#### Result

```fsharp
module Foo =

    let blah =

        let a =
            match true with
            | false ->
                match result with
                | Error _ -> failwith ""
                | Ok _ ->
                    printfn "hi"
                    failwith "blah blah blah blah"
            | true -> failwith ""

        failwith ""

```
            
#### Problem description

I've seen an analogue of this case appear or disappear depending on whether `let a =` is `let a, b =` or just `let a =`. However, for this particular reproduction, it turns out not to matter. I expected the `printfn` to be unindented one scope from where Fantomas put it.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 07/07/2021 07:46:28 - 6f0df78847a1dbb3c87fa2e00c6390703905b7c1

```fsharp
    { config with
                MultilineBlockBracketsOnSameColumn = true
                KeepIndentInBranch = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
It does work if you flip the `| true -> failwith ""` on top, [see example](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYrLGALwA6AdlRBHgC5gBGOAhgBZlU228NisulXiNrpW9aJ3oAnLPgDuAS3rseo3gB8ws%2BWAC0APjAAzVkpzLVYcpFvqNEbWZwBnfEYePe4yZxmIrriMVmrC3qLaAKIyMrAyYAD6BsZmFqE2dnbhEVpgAPIA1kkpXrm8AA4ySpT0JsK27Er2OeUiaZYqnLYsHMxsnL2DAy3l3K28HRn2kJAANOBQ7vT0NQDmrqhgANqLEKCikAAk9ACeFchokDX083u0xwBurDjyW7uOAAwLjpAAkpQkLUAMpKABeyB%2BGgALPcIABde4AXyh%2BzhUBO50uUBud0OR2er2xHw0AEZUSJIABZVgADwAMjVEPTEJQ1qo8WSAEyfdGI3go%2B4HSmYi5bSBMYg4Tm8J4vN5oEmiLkU2XAxDoJRwHCwSgAQXoUUB%2BRMjMokPREBc7j5yIpwtlouxEqlMoeBPlxMtYAAzKqHsCKqxoIgAEKIEzxRAABVYMlY6EQ9EQMjdvF0iFtAvt6OOZzFV0lsGl-rlRPe3uh-ogkEDwbDEaj9NgChT0FY7gBj1g7dWurTtAzWdogt4Dvd%2BedRZLuY95cV3oArNWoHWQ%2BHIwEAKoVC4ydudyjd3tKfsr62Z0T8kc5-GT8XTgdlhU7b0ANhXtaD68bAQAwmwriuH%2BuquLo0D0PEA5Wi8NpXnaQqzvehauqWc4vkqIgAOyfmuDabogVIakwKbQaYsGXiI14QKOtDjjWToPqhs6Ehh3oABy4d%2B%2BFRiBOqUGRF7DjRt4ishUCPmhrFeo4ACcXH1nqJjJjIIHoOIZFDvB2aIXeWJMcWT7oTJZLfN6X71huUbqpq2pnt6QnaTeulifpKGGVJnoVo4pLkuZeFKSpNlasW9mOFpVEIWOSFuRJzH4tJ3ncp%2BAJAvQ%2BSUAAKjIpwAOpdIJFHCWAtFonpBZxR5LFeQuPl%2Bv53F6nEWCAgAIogOBKJqKmaXIlG8NRJWiY64nXLURmJbVZJVuZNK0n8JiZewrJRG4iDAuw8T0Pl8Aciu0K8k5IkuSNsVjbcnnzq%2BPnLrNdIAiYSi0vke4SPEUS0lUgSuKeAkrouh2RTp0Xlc6uKXWxPkfndtIAEqIHAMjwDte2VoDA1RXRMUVedE01ddZI4TD8OI-AAByWDoCRMgmn8yboJsK6ksVpVgPRGKjegwQWEyRAyL4KmZfpEMmaIpKceZJPxPAVLc515p8wLpGflIcbBipiTKLt7CQCzw0Tmd4PVVdmG8KS8kw018anPkMiMmBKM6-t6O0INrPs3mhvjSLSXKmZvxzVbrA23bShgRTVMprT9OM96zNHUNJ0GzjXM4Ks8uIIrEiC8LxuQxoXJ%2Bb8Qch-b9Cy2nPMK-ESupir7BqxBKaa0o2u6wn7vY2D3t56LIhciqMMAGqeqGNTwOsjtkQdetJwxo1Gwl%2BOm7QXL1QHdIEC1EG-WPgKT63qOODPHf6-PXsXb3vv9zNG%2B0q1sD0AA4kmH1fUBv1T-9LsIpjZWuTjSSV8prKlugHOWTJQw6mgIUUM8YYFJlcBlYECZEB8Upn9b0EUMbAyxqDAyM4l4m29FyaGvwyaIAUBncM9BWysiFhcdqj1KAqF%2BnqQERFI4yFjo4RyQNnIgwAVOeKIpJoE2VETX4ABpRAiAKgLSWqyAEKDExmgtLwoqp854cwvnjYhjguQSzvqtTUrh2BfzRrPQRp1AEiMdGIleEAuQW1%2BKCNkeAmprEpqybaiAmBUgQOojQfCcECLwUIghej86iB9P7DQkA9SdTWJQLelAd66lBMkiQWAAiZVgKlHxEhfqFTWlY8JNjhFVSIdEkQPoi7xMSSpSgRTHjMl1GsTh1MmE1FYaBEpcF%2BHHWscnSphDRHL29D6Qe4DK5qPpAmJg8BWAAVgD9NkFCqFMn6f1V2f82Zd0iT7EBtT17xNamHVgLBEAmLDuwYEpxah0m2WU-%2BFTxSsngCaNRwIzh4CiX3XgPpb7xKNJ800WyVYyBwCYdugzE7DPPrYqp4z9EaB9GA%2BJMi5EFNqACOBrA0lOywX1F5%2Bz8HuTGfYiZjgfRkPiVAglhQ1GuCarAFq5NAjJhlhA80b8Agfz6SubBuzcGvJGYc4B4jamSPpXGKyARzmuGgNUTUzSuVbhYbqdq0A2Dxj7JgjRpStEIp0Uiyl7oHGTKMfEn51QIIBKQM8juix4RQmuK4AgP0thCSREAA).
As I understood it so far, only the last branch or clause will do keep indent stuff.
Any reason the short clause is not the last one here?

**Comment by Smaug123** [comment]
Ah, I see. I've forgotten the context I actually had in mind when I raised this, but it is very possible you're right and I was just being over-eager. I'll see if I can find why I raised this.
