### ISSUE TITLE
Long list argument violates the "avoid name-sensitive alignments" rule (vanity alignment)

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1826]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBLAdlogE74CG6YWsAgtNIgM6MBKArpgCLWNgAOxWACtE0HAF4AOsUn4IAbTABPXInTwAhNNkRd-QSLEA6AJLxtcvWAA%2BAPjBl6TVhyYWrN%2B3QbN2mIwBmuOhExACq%2BMRMJABuiPAAwmR8ZABGwbhYqozuHnqKMaoA7gAKBqJYuXl6hYil5WIm%2BAAyuIxZ%2BADmVdUQtUUAEoyIAEKwZMTwnEzQxLh8WbD4Pb39Q4gJS1iOWDkylr19xeucsNBsALaIhLwAuiueYN7OfohG1NywvBoCwhWm8DA932kAANOAoMMsB1OoxUGB5BCIKAPJAACRYJR8ZBoSAELBgpG6dExChsHEIol6AAM4OqkCaSEIAGVcAAvZB0vIAJipQKJAF8uci%2BejMdj4XjCITUWjSehyfDEdUAIzCqyQACyZAAHq18IhmtdOlgABYyvIq7nUvm3QXqlEajFYimQVKwWDoC16ElkinKnnqn3MxAXXBwdBLGhYACi%2BHgAHkAvrOXyIAEKMNbfaiY6fc6Jbj3Z7vcS5X6lWmwABmIPE5kpBgjRABWBREoTMhXUKlvRYYjk7N6IW50UF13Fr1130K-1VgAsdYgkAbjlGLbbhtgRRI0DIwyaMTOZEW%2BF7un7g48duHDrH4onHqnY-lirQAY8AFYl1BV02N1EYR8NixB7ge%2BBHnup7nummaIEOugjnoeZlg%2BkqTueM5vpS1QAGw-iujbrq2UQJOg%2B6MJs%2BDtAOYhtjBYAZugWbXjmyH3i66FPph5azpW1QAOwEX%2BxGbpqoapCQDFMSxVg3ohd6ymhRbcdOvHYR%2BVgABzCURzYkRsnpLNJcEIRASG6Chy7jlxJZqa%2Bc7VAAnLpa40AEoSbBcFxkAxl7waxt6jkpnEqXZL4Vu%2BVYqrSVaEWu%2BmbiGYYRsZP4yQFclsZZHGFlAGH2ZFOGWmqcUie5oTJeGRlnj%2B-lmWAFkiiFeVuqpEV8VFqrcgRjLXFgCb4AAKsQSgAOqZOa6WmYFCnBU6yn5e1soOfxlq1mVRE0IIbDxtM6C4GGPZ1QOmV6PJ5mKQtoVQPiPGrV1lqLnF2o6iYARDaa1wxsxiDMqabZYBN8Bmgx842rNl3zfmi1SgShWdcVHgqt%2BL26k0QQ6gmIEnm2MY6gIzi4GlVafhDWVBexLWundCMadF%2BFozqLCiG28DA6DP7gw1TVgFZUA2bitMdfTqpCUzLNwJMABylyScQSYmEQFxwj%2BKo81dMM3ZAFwcFkB0GgAYm2PnQiQQ2cXTjmWjpcWS2zmp6xkRsmyex1xdApqdmIJAAPpFLgIPmhr0OodrwsrUVml6CqLlM9txBkEoCbEK07Qc1NC7k%2Bd2XNddrUR06D1I1Y1oEa9CdJynadYLLFzy4ryuq9FIdU-nrq6yEzuIMbxCm6EFsSlba0eNypX0pXyep20WCO13Bs967ZvEAxMBe4nPvEP7geg63OXU5Khf5sX0e6NyPVMwAan6IwEPABCdBnYPZ7oF2NZrYcF9Kw%2BPaPG30q9Q2u0xDE3wLfeMD8n5cxfhAN%2BvN%2BZinDt-EW1tR7PQAbqU4WAADi2B8aE2YKAqBpMYH8kpvvdutlnyR0RqfCA3JUYAKdgvEYkZoAAGsRgb3YdgRgg1mRdkMgqC4tUqwZT3nnLWrUCooJHqXRm9JpZ1BYdgHc1xB6IGmEEfAmRQE0HjOJeuJBm7VHEZDd%2BodrKwxkTQ0WPJxb0gANKIEQHwd6n1rhNAEVcFMJlfoSL5rlGmyDbGoNLrbDBOofphkYKaYh1RubmPgUEqh90o5Vm5HHekrIuiYG2p0S4-UxqIFSJqBAqZTEzQpnNNuUjHzhVCXIvQ1ZYoTwOp0fAQD8AgKWKyDpJ42BRCGrAPqhATygL8bJHO5DJGf3qdQou6TqjVnHnkSANAQgkHIFkOIzQlidEMfLLRBBdFLBMXkMx1Soa1Lmakn%2BJdmkXyYV3FMzQuypHgGQMiXwH5KKKAvSZZ1X650CQfMKCzj5LLyNWf%2BazOBtDSJgaJbRTTMiUGMnUgKAkIMFlAa4iZkwED%2BpiTAaTaFVmrOgtZcYCW%2BIIrMdAARIDYpSeCsldiPDVkYWs5xrjRlYCaFwsg3TM6VP8Ukj%2BVjtY2MWeS5ZCi1msOFewlMjBtqwF2vAJR7R4hz31kS-BURCFnL8qdFlYKloNNlRyqw1YHGKomIlKI8LGCzEOgQE88QIigOmNAciidoLTXFVcixNypXSOWtasJzSIlrOZP2cMs9ylYqSRCW4XI8SMENowXA8JxECiAA)

#### Code and expected output

```fsharp
let internal toAccessRuleDtos project =
  [ yield!
      project.Id
      |> accessRules
      |> AccessRule.filterUnreservedCapabilities
           [ viewProject
             viewProjectInListing
             viewHseBoardDescription
             viewHseContacts
             viewHseDocuments ]
      |> AccessRule.toDtos !project.Id ]

```
            

#### Result

```fsharp
let internal toAccessRuleDtos project =
  [ yield!
      project.Id
      |> accessRules
      |> AccessRule.filterUnreservedCapabilities [ viewProject
                                                   viewProjectInListing
                                                   viewHseBoardDescription
                                                   viewHseContacts
                                                   viewHseDocuments ]
      |> AccessRule.toDtos !project.Id ]

```
            
#### Problem description

Result violates the "avoid name-sensitive alignments" rule.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 07/07/2021 07:46:28 - 6f0df78847a1dbb3c87fa2e00c6390703905b7c1

```fsharp
    { config with
                IndentSize = 2 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
[fsharp_disable_elmish_syntax=true](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBLAdlogE74CG6YWsAgtNIgM6MBKArpgCLWNgAOxWACtE0HAF4AOsUn4IAbTABPXInTwAhNNkRd-QSLEA6AJLxtcvWAA%2BAPjBl6TVhyYWrN%2B3QbN2mIwBmuOhExACq%2BMRMJABuiPAAwmR8ZABGwbhYqozuHnqKMaoA7gAKBqJYuXl6hYil5WIm%2BAAyuIxZ%2BADmVdUQtUUAEoyIAEKwZMTwnEzQxLh8WbD4Pb39Q4gJS1iOWDkylr19xeucsNBsALaIhLwAuiueYN7OfohG1NywvBoCwhWm8DA932kAANOAoMMsB1OoxUGB5BCIKAPJAACRYJR8ZBoSAELBgpG6dExChsHEIol6AAM4OqkCaSEIAGVcAAvZB0vIAFipQKJAF8uci%2BejMdj4XjCITUWjSehyfDEdUAIzCqyQACyZAAHq18IhmtdOlgABYyvIqgBM1L5t0F6pRGoxWIpkFSsFg6AtehJZIpyryVvVvuZiAuuDg6CWNCwAFF8PAAPIBfWcvkQAIUYZ2h1Ep2%2Bl0S3Eer0%2B4ly-1KjNgADMIeJzJSDBGiACsCiJQmZCuoXLeiwxHJub0QvzoqLbtL3obfoVAZr3IbEEgTccozbHcNsCKJGgZGGTRiZzIi3w-d0g%2BHHnto8dE-FU89M4n8sVaEDHgArMuoGuW5uURhHw2LEPuh74Me%2B5nhembZogI66GOegFhWj6StOF5zu%2BlLVAAbL%2Bq7Nhu7ZRAk6AHowmz4O0Q5iB2sFgFm6A5jeeYoQ%2BroYc%2BWGVvO1bVAA7IR-4kVumrhqkJCMcxrFWLeSH3rK6Eljxs58Thn5WAAHCJxGtqRGxeksMnwYhEDIboqErpO3Flupb4LtUACcenrjQAShJsFwXGQjFXghbF3uOylcap9mvlWH41iqtI1kR64GVuYYRlGJm-rJgXyexVmccWUCYQ5UW4ZaarxaJHmhClkbGeev4BeZYCWSKoX5e6amRfx0WqsG8WMtcWBJvgAAqxBKAA6pk5oZWZQWKSFzoqQVHWyo5AmWvW5XETQghsIm0zoLgEZ9vVQ5ZXoCkWUpi1hVA%2BK8Wt3WWku8XajqJgBMNprXHGLGIMypodlgk3wGajHcrac1XQthZLVKBJFV1JUeCqP6vbqTRBDqSagaeHZxjqAjOLg6U1l%2BkPZcFHGtW692I5pMUEejOosKIHbwCDYO-hDjXNWA1lQLZuJ051DOqsJzOs3AkwAHKXFJxApiYRAXHCv4qrz12w7dkAXBwWSHQaABiHa%2BdCJDDVx9NOZaunxVL7OavrGTG6bp4nfF0Cmt2YgkAA%2BkUuCg%2Bamsw2hOsi6txVaXoKquczO3EGQShJsQrTtJz02LhTF05S1N1tZHzqPcjVg2oRb2J8nqfp1gcsXArSsq2rMWh9TBdunrIQu4gJvEGboSWxK1vrR4VplfSVcp2nbRYE73eG73bvm8QjEwN7Se%2B8QAdB2Dbe5TTkpF4WJcx7oVq9fSb0AGr%2BiMBDwAQnSZ%2BDOe6JdTVa%2BHhfSiPT1j5tK%2BuojZ7TECTfA99ExPxftzN%2BEAP58wFmKCOv9RY2zHi9IBOpThYAAOLYAJkTZg4CYFkzgfyKmB8O52RfFHJGZ8IBWjRlfZ2i8RjRmgAAaxGJvTh2BGBDWZD2IyCoLh1RrJlfe%2BdtZtUKmg0eZcmb0hlnUNh2BdzXCHogaYQR8CZHATQRMEkG4kBbtUSRUNP5hxsnDORdCxZBglvSAA0ogRAfAPpfWuE0IRVw0ymT%2BlI-meVaaoPsegsudssG-QjIwU0pDqg80sYgkJNCHrRxrFaeO9JWRdEwDtTolwBrjUQKkTUCB0zmNmpTea7cZFPgiuEhRehaxxUnodTo%2BAQH4DAUsVknTTxsCiMNWA-VCCnnAQEuSudKHSO-g02hxcMnVFrBPPIkAaAhBIOQLIcRmhLE6MYhWOiCD6KWGYvIFianQzqfMtJf9S4tMvus%2BeWQ0zNB7KkeAZByJfCfioooi8pnnXfnnYJh9wqLJPssvItZAHrM4G0NImAYltFNMyJQ4ydT%2BTOkEpBQsoDXGTKmAg-1MSYHSfQmstZMHrITMS-xhFZjoACJAPFqTIWUocR4WszD1muPcWMrATQeFkB6VnKpgTklfxsTrOxSyqUrKUes9hYrOFpkYDtWAe14AqPaPEV5PdCFRGIecnF15rlWNubK2RK0FXcqsLWJxKqJhJSiIixgswjoEFPPECI4DpjQAoknGCM0pWWpSRC5ajT7URJaVE9ZzJByRjnhU4FvMIS3C5HiRgRtGC4HhJIgUQA)
