### ISSUE TITLE
Parens stripped from custom definitions of op_Range and op_RangeStep operators

### ISSUE THREAD

**Issue by stephen-swensen** [fsprojects/fantomas#1842]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBtAPAQQK4BdYB5AB0QDsA%2BAXTAHo6BbAQwGsBLcgczGYNjCwy5XgBtRsAO4BnMLlnlY%2BMITAALZgDdEKgQDNc4gJ5gAjrmaj2ek4wSGdJAE5DET-O0TSAOuTvwHMAARRDhGEnZRZg9YcgAVL3wfRWEwAA1ccnZ8X1cRAGVJCmkKADoAVXJzJURfX39AuKEAGURtUVIASWlYKJjyAGYwAF5fCAhRRGUAClLSgEowAA8wEwAvEbB8xFNS6U4uScIRaZWAalWwC7X5sfGsADFmaHwaO4mpsAADL-ZpaVwOgAnABGNBCAD6ACVmNwdHp2E5pMpoFF-mBpEZyPhmCs9LAnBidmAnFNcE4RPgjGQwAAjAi8Jw8Rh-Fj4aBqH5gaaLUYicYCzAAAW5c0WILAACYwEMhZQwAAfeVIMIRSYjACEYG8kCaJFa7S6PT67FiA1KswWYAl0oGOrq-I%2BMzmYDFy0uGzUm22u323COsW550u1yu6lujrAj2er2o7zAR2%2Bv3%2BgLAoPBJGhsK4iHy%2BEQJDACKRKLRskx2NxRYJRNMJLJFJU1J09OUzCZYBZ0jZHK5PJG8cFIstrqtNplYAALGA5YrlaFYOFIjphlqdXqDYgOiRur1oqbBhaXW7x0NJzrIAAacBQEr4DzcaSoKM3iCgAUQSAAEipZGfkE4fAr1fcZv00SxAWfdAQIFAAGa8P1AzpyCQbF8nYNZkAQxCpxgsBqBAgBfbC3zw79f2QNAAOxYDELAiDKJfHDrRIj9IAAWVxZpOEQVpuHwNRaJwkFJVgvCCIFYiQPfNif2bf9aVgXohIFejREgtBoOYyVWNU7YWTgCRyGwfAAFEUKIPRuPILC8IgPRLBKcSiNYmTVLkv8qMU5TdKgL9wPUxitJwgZfM-fISGeRAACFEHxUkAAV22YRgpjcFSP3wJxAWcyTXLIjzGMgbzRAyz9-IYqC7KnMKoAiqLYvi3ipDcaBmBKZDNFgNr%2BjK8YspyxCJPGKSBTc0DCoUpTSt8tSNKYnCAFZasgeroBiuKCUQcoSDIJw2o68gup6g8%2BvsxzEFykb8royavOmvq5qC6qADYVrWjamoAYTLL7YmRbKXgJM6iwuq6IFG8ZxvKiipp8gqAvm4LEIAdneyL1sarb2MQRhaXS2qHNEJyhpc6SCth%2B74duxHnuYgAOdGGs20k-qMkGiZJj9hohm7ZMpqASseirAqq5igSZ9bsD0fMnD%2BxgWBBgbLtJvLydugXioe2aRaR6qQXg6rVoxz6tv09hDNiDmwdV671f5%2BSqZmhHKs0-WQUlxBpdl83LfIJXspV7mybGinHcF7WXdFt3mJElbkNQ-AiHiJwjAAdWyQTCZt4O1dDjXw616nZNpsXhNCo2PuwFxMngEIrBZWWA8G3O7fzh3PKgQDhdLmPhMnFbOKWTo9DiNQKFM4nczUAl8Az%2BABJBycxNt3n7fczXu513uFsQkFlqNofkIRJZSDcaICVMpZnC8fYrdqxaV9btf243wut6jvXY7ew-cShBcnDwHnovWqy9wZgEhqRAundqJAW3q7XeH4QRo1-ksf%2BcBAEADlcB4zcJZTo%2BZGBPlqiCcBkCwDQz8prRghgPBWBsg8AkbJZZxHkvA6OiCBQgkZkbdBBJ4DsVoZEHijCnDMIJkbDkyUXhuAhJIdgC9BJkL5m-GBH8aYIORkgiWqDq5OGYEYIgThuLImAVnaqYDV4QJURNTeNF2FfxwqJQeuI9EGKMSY-A2DcFOHwYQ4h%2BtlHr1sYXGhog6EiKYdEFhbDP50ycR7I2bjDHGL%2BPgQR4ThEMKifeCRzEYAaH0TIpwciFGLyCa-EJaj7FxLLohSUOlUEADUGLRU4PAA4Zil5PwFDzaxwSYbvxqRojhWiBSSgrvkoeDxMgvAPG0lCnSynmOYpY5%2B-TKmDOqXA2pfd6kD1QUEJQABxKYV8b7-APF0h%2BPTxh9PIZQ8ihchYOPifUg%2BUyhH0JihIaArBopFNYFMaQyd8gpUQGzHB-ts5TwqVDMOMCXm7M4eMSUP98mYMQJIb5sV8BFAoKwsgIQERZH6NgFCOMfEBOYpzIOvSQ7wugUVJFIzHH1JQfkgA0ogAsI8x4UGQmC1K1lbI0pzvSvOjKO5FXUSXTR1VJQ8KmbiSeXY1DXIsbciA9ybFbOZZHVlbyPySh0fk9C-ovZMhwRQOeiBaTsQQKKnCtK4VQOlXDZ2hq6kfgGIbfJ2ArBcHIDM8gczYjoSDdEckiAmgJxtfue%2B1UXVWIeQi-Vxd3I7zGeMAYiT-XhLcOQfc2hmixC4JS-GThiWcGyAealzrxV3IZW61R6bPVytGdVAYjTPmZJFc0FKtJ4DMB%2BrAP0XBMXYp4tbWFKbdVUOeQajtbKfWTJwpAIIfxmC0kmKqv4ah8hYhxEsGdXMJVtyla2-8FB4CWRFXmIwkwe7yuYgMA5%2BTzK3qstOla0AnCiD0JAV1FC00eufZ219Hz13ct5ShG1yEAWwg5KeulTbJUtqqW28DK6BQDHReu6KURyCsBFdIausBa6YuRIgARXyeLnNJJc-6zdUPaubSBplYHXnetwxygj7Ysakk3dIP97AWRFvzPASoB4QiomSr1GFZ60MXow3qrjyLs0QAGEq9deYnAW3SY6lDZCbzUGwgBaQDx9jPhdYRIAA)

#### Code

```fsharp
[<AutoOpen>] //making auto open allows us not to have to fully qualify module properties
module DecompilationTests
open Xunit
open Swensen.Unquote

module TopLevelOpIsolation3 =
    let (..) x y z = Seq.singleton (x + y + z)
    [<Fact>]
    let ``issue 91: op_Range first class syntax for seq return type but arg mismatch`` () =
        <@ (..) 1 2 3 @> |> decompile =! "TopLevelOpIsolation3.(..) 1 2 3"

    let (.. ..) x y z h = Seq.singleton (x + y + z + h)
    [<Fact>]
    let ``issue 91: op_RangeStep first class syntax for seq return type but arg mismatch`` () =
        <@ (.. ..) 1 2 3 4 @> |> decompile =! "TopLevelOpIsolation3.(.. ..) 1 2 3 4"
```
            

#### Result

```fsharp
[<AutoOpen>] //making auto open allows us not to have to fully qualify module properties
module DecompilationTests

open Xunit
open Swensen.Unquote

module TopLevelOpIsolation3 =
    let .. x y z = Seq.singleton (x + y + z)

    [<Fact>]
    let ``issue 91: op_Range first class syntax for seq return type but arg mismatch`` () =
        <@ (..) 1 2 3 @> |> decompile
        =! "TopLevelOpIsolation3.(..) 1 2 3"

    let .. .. x y z h = Seq.singleton (x + y + z + h)

    [<Fact>]
    let ``issue 91: op_RangeStep first class syntax for seq return type but arg mismatch`` () =
        <@ (.. ..) 1 2 3 4 @> |> decompile
        =! "TopLevelOpIsolation3.(.. ..) 1 2 3 4"

```
            
#### Problem description

I encountered this while testing out Fantomas on Unquote. The offending file is https://github.com/SwensenSoftware/unquote/blob/65a387801325d70ec03c16e6da8b58a468cbd2f3/test/UnquoteTests/DecompilationTests.fs which caused the CLI tool to crash with a "Formatted content is not valid F# code" error. I think there may be other issues with this file, but I narrowed down to issues with `(..)` and `(.. ..)` for starts with the online tool. 

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 07/18/2021 11:37:23 - 23cefe5b872a95112c9f6a2df37dec826190049b

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.
I noticed that [the AST](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQ2wAuYAFADpBASjAAPMAE8wALzABeMAGVYAR0FlkAc249WyAZIDU0sKdkjIIAL5A) does not contain the parenthesis in `let (..) x y z =`, so that is why Fantomas did what it did.
This is an issue that might be easier to solve in F# parser than introduce a hack in Fantomas.
I'll take a look some time to see what our options are in this case.
