### ISSUE TITLE
Fantomas is having problem parsing an specific case and wipes the whole file

### ISSUE THREAD

**Issue by chiniara** [fsprojects/fantomas#1853]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAyugIbp4C8AOgE4UB2EEwYAcgK4C2ARolWGgJa101OgzFgACswBMAoSPriIUgIxzhNRUoC%2BkADTgoAZ0Tp0ggOZHUYANqHGDhpAAkWXDciD0%2BpxFcAbkQANqzIaPZKEAAMBlFQAJK0SEL4-ABeyHFRACx%2BYAC6TtrZjkqu7uFQ3r7lLkGhVZFRKqXikACyRAAeADKCiL2ItBboABa1LdLR%2BUViJU6gdZWenLCwwZNigSFhNs1K0m3b%2BIjs-HDBsLQAgugAoskA8gBm-bRZ%2BRAvISazxW0lu03DgqpA1hsts56rsml8wABmY7OfDYIjQRAAIUQL1gVEQEiIVCI7FMPChYnQVDC-3mgPyFVBq3Wm2RO0a%2B3hOWR-lR6KxOLxg1gAHceNAiCYkgFYBLzNcKQwqTSlHMGAsxEDtiCPGhwSzFey9hF4QBWHlQPkY7G4-EAVWwuCoEqltBlcv4CotP2Cf1VAMWDJ1YIhrKDDWNdnhADYLZArQLbYgAMLBSVGZPXIzK6DoPGK76-RC09X05ZMvWhw0wjkm%2BIAdjjCZtQo6Z24VALYB9fvEaogGoYWuhK0rBrZNcjB3EAA4m2jrYL8ZmrrQuz3i-66YHy7qoFWJxG4fEAJzz-k3F6kKiZ9jsIhd5WbvsBzVB0f78fh2Gc%2BIqWLwvGC6JkKpznJcXrwhuJYDmWwIfvqkKHj%2BdYtK0gEJpe15gRcGyQfET4wWAg5lPBFafkh361lGf5HIBSQpOgTy0AAKlQmAAOr8OM65FkRJFgMO-jBsylF1Eev4tEiGHATcVCwKwyQACKIME-DnNej7Us%2BYj9sRcHaghNTIdR05iCo3KAV03QJC8LFjMM9y%2Bog%2BBjHi6BcfAPEWjkMxbqWO5kXuXhCNWEmoUoKjmlZPRJC8-DdE8TokHi9zdNg%2BJGEYnprhapp%2BS%2B25vruYLGVRU7wiosYxd0ABKiBwFQ8Ced5XIFbpr5Du%2B5EhT4JkVX%2BjY1fVjXwGwXA8K8CSkOw1gWio-EGSOPXsKwwTmGpHwAGJ4veZg8CxTL9ceLRzoBI14vAHRrRtAw7VQe2aXG0BjES6LXgA%2BiK-BeRMi2BYZPVleJKE0S0Z41XJxKYE8VD9NmLUTD57UMHpAlCVAIl6sDwLhWDhwAfEnQ9FDRAw3D-DZuNHZTTNc2Vf9xVBWCq3rfwm2IPdj0HUd5UnYc6FE6T5Pw%2Bg11sxzXMkE9gEvW9uY8F9P08YzXUlZ4OPanjZkMNIdFE9ZABqsKYoI8CWIjXa%2BarpGA8FmvQtr8LSNJBs9Ftim5jlpvJBbytI21NuCd19uhcdkmHJZbvdEpsDoAA4qYaUZYgWU5ZbeUoxAaNLcJCEHnzEfiNI0UGzd7MDJiVzQAA1pixK16YRjMfgJIphsHC5VBfH%2BbBAPLcFBcg6ZzvVUTzCICKHPYugYrDIduAqfFtDcTlNzJG2E1UPT8TQb3%2Bn93nPVD7joM6xA0hDUTADSiCINgtn2cMSSt6S7yfLvPeFQFTN26VYeFwisXM60cnLnCMGMDOgd97oxDiGL8w8BpRGkBDImaQRjBEQHJCwHBhgeUQJwDoCAP5RD3t-Puv8B7wLEqfEe8QESEyiJAG4akLC0A9rQL21w0hsJIKwfELFYAMTwSQHKvFnJBwxoyQeCDaFIKUAiQWTCWHXloKIgIwoRibw7EvQQq8sziN7B1IqatmaiTDIg-m4gET6yYeLcw79egkk4PAIgqZYDZRGBPKeAxDE6VRp1W2VDzFhTPvCBErsmFKUpkQTgmCwGUzGPgTAQgeh%2BMkXAzwwx4CvHfoQTAmDQl0KiAiKOTDHg5LeL456VBggvEgBk9WY4aFazCfQ0uTDb732EUIJI9ciCcIDp-CRMDc6Y3zrI1pxSFFjyYVXAZNd35GDkgpZIE9syICuuXDmydMrZQMRaQiozD7jOPpMx2bSSlXzmUSFs%2BJolGGgFQdSggSCbLtCva4KloBpmJPKLuwyjEBJMUEo%2BMiWkXOmdYkBTDCDPNzEQpA6SYGGAKNkLwRgtrZRsNBbQQA)

#### Code

```fsharp
type State =
    { Number : int
        PN2: int
        PN1: int
        }
```
            

#### Error

```fsharp
Fantomas.FormatConfig+FormatException: Parsing failed with errors: [|tmp.fsx (3,12)-(3,13) parse error Unexpected symbol ':' in type definition. Expected '}' or other token.;
  tmp.fsx (2,5)-(2,6) parse error Unmatched '{'|]
And options: { SourceFiles = [|"tmp.fsx"|]
  ConditionalCompilationDefines = []
  ErrorSeverityOptions = { WarnLevel = 3
                           GlobalWarnAsError = false
                           WarnOff = []
                           WarnOn = []
                           WarnAsError = []
                           WarnAsWarn = [] }
  IsInteractive = false
  LightSyntax = None
  CompilingFsLib = false
  IsExe = false }
   at Fantomas.CodeFormatterImpl.parse@75-2.Invoke(FSharpParseFileResults _arg2) in /app/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 81
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 404
   at <StartupCode$FSharp-Compiler-Service>.$Service.ParseFile@457-3.Invoke(AsyncActivation`1 ctxt) in D:\workspace\_work\1\s\src\fsharp\service\service.fs:line 457
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
--- End of stack trace from previous location ---
   at FantomasOnline.Server.Shared.Http.formatResponse@95-6.Invoke(Unit unitVar0) in /app/src/server/FantomasOnline.Shared/Http.fs:line 95
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
```
            
#### Problem description

I was in my process of learning F# and i ended with this small piece of code thats above on the text, i run it with format on save on and in this specific case it wipes the whole file.

Gif demonstrating the issue:
![YtgTy5dJw1](https://user-images.githubusercontent.com/6012227/128188733-17d825e9-c655-4921-abc2-8f6a1d33089c.gif)

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 08/04/2021 06:29:48 - 4bfd2581e8ef3a1f52e333e9d3a6a77ef33ab07f

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello there, 
Fantomas requires the F# syntax to be valid in order to be able to format the file.
<sub>This is mentioned in the README</sub>
> We assume that the source files are parsable by the F# compiler before feeding into the tool.

If you check out the [AST](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQAuAngA6wwAZS5UuggLwAdAE5TkECMDAA5AK4BbAEawZYbCi6z5i02AAKKgEwHkRuQrMRLARlv2TTsAF9IIb0A) tab, you'll notice that there are errors in the current code. Fantomas can't process the file in this case.

So, I believe this is more of a tooling problem, to be honest. What editor (and version) are you using?

**Comment by chiniara** [comment]
Hey @nojaf thanks for the answer

Im using the latest vscode stable + ionide.

**Comment by nojaf** [comment]
Interesting, this might be related to the combination of "format on save" in Ionide.
Does it happen as well when you turn that off?

**Comment by chiniara** [comment]
It does not.
But if i tell vscode to format the file it still happens so i don't think its related to format on save.

**Comment by baronfel** [comment]
That's exactly the issue here. In FSAC we unconditionally call fantomas whenever the `textDocument/formatting` LSP call is made. See [the implementation](https://github.com/fsharp/FsAutoComplete/blob/94ad926ce13bc3165fd30665ccfe5215e63f9033/src/FsAutoComplete.Core/Commands.fs#L1140-L1155) for the exact details.  If we need to check for parsing errors before calling fantomas, that would result in double-parsing of the text for each format call, which I think is a bit too much work.

**Comment by nojaf** [comment]
And euhm, what if we add a good old try-catch there?

**Comment by baronfel** [comment]
Seems to work great, we'll put this in the next version of FSAC/Ionide

**Comment by nojaf** [comment]
Many thanks @baronfel!
