### ISSUE TITLE
Unnecessary indentation in nested fable createObj expressions

### ISSUE THREAD

**Issue by not-rusty** [fsprojects/fantomas#1857]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAdAdgG0QFzACsBnAeQCNDFoCBeLCCaAJ0QEM9ELCwBtBxoPSRMbALaJhYWrQB8YYQHEArgEtsuMcIGCIwtgHNJkaXLAAmACw7dw4nlb4pM%2BS3adufG7sbDRE5zNhbFhsbUwfH2E4ZUwHAE9A11YOLkovCMis4U57JLA3VM9%2BTKyyhUhcvHzCj3SS8sbfSsR7c3yc1urIbybIzryTFwKUup4GvsmB7tN5afDJ8oBdXsmV0r71xYqq9qGglsHV3S3I04h1yAAacChifDxVTANiVD5biFAfSAASPHiAA7INCQJ54a4fRi-ABubGwymB7yyAAYbllIABJTBIOIAZVUAC9kGjIpZIRdIQBfEmfclQP6AxGguIQ74-WHwxG8OkQACMNN0kAAsmwAB4AGSeiHFiGeeAAFqzIrzzMi6UsqQKvoKGUC3pByLBQkrBDC4Qi3tysuYBabcYgxKo4CFMABBPAAUWxpAAZpLMMSeWAfXD7urNZDtabdUzDcbbfSORa0FbIgBmBMQSC4gFsaCIABCiB9sFYAAU2MxxPhEMwTboHAjw4JqZG6b9-nqQXHsPWs%2BzzVyg5ZM1Ac3nC8XS9LYAB3WvQNj3LHQ2CLx6wTB9xiNxDNxitwRRqEx-U97dmzmWoMAVlH2dz%2BaLJdYAFUAUDmIvl5hV%2BvVJu24QCG2Bhj4Gotlq7ant2Rq9gml7JkikQAGz3uOT5TqwADC2BLsQ2GbvYzDKDQpZAcGoZ7uBEZHtBnaxnBF4DleKZBgA7Ohj6Ti%2BiBCg65C1hRIFgSctGMMe-YMWeTEISxSGpj4AAcXETs%2B06ES6wlUfuECHhJ9GMjJ8bQUmQ5ZAAnKp%2Bauj6nDMIRYhiGwFG7rpYD6bSbLSbBJlsmZ15ZLyqJBg%2BalYYg9qOs6gGjiJ1FiZBbbeUZvnwaZg6Bcq-KhRhiC2fZUVOqEsVBm5NFJXRKVdlA55yQFbFBTaoVYjieCkJgAAqzDxAA6qoCraaBCWCBBB5QdVjF%2BTqDXIT4vIZrl3GuswsCxPAAAiiDYKojr2a5JEjYwY16RNOo%2BVAYLMbNim6LyI6hSKooYj6nXyrKHrDbi8qlng-XwINo6WGqFXjcl52pZdLL1ZljXKnej1iliPqqKKpCfhwpYeqKAKsMQxAAVuo43iDiVg1VEM1cy4Iw6xc13WhiOigAStQpbwP9gPDqTo3iV5lNMldtMKUGvKcUzrNwMw8AAHLKGIgnML6GKcGIryjry7meWAkn0hdkBiMo2CPDtAYAGKls5eD2Z1RnC%2BZyoqaFkvs0KRsm1KFvMFb%2B33tA8qVnm9kAPqzqoAOKlrZ3RvrQsZXTt2CLyVlMytVbxKQzCSvYnOKkDPPHXzOuGVTcf%2BbD9OCKq95PWnbAZ1nqj2HLCu1srqvq6LUfgzHkMG%2B76ie5bHA23b8ci9aOXonXDfZ3gbvG4P5vD9bQl%2BwHVY0LWofh4N3cU73pfQ%2BPDs%2BOYzXok9ABqg4Fk88BPAYucUcD%2B8GZN%2BplzNFeJ4w5iLZfMUZtYg0EJnfbEj9n75zfvzQ%2Bgtj7lwTkGKwNcxQbVgHgRQ%2BBsa41aATTcUDbwFwpJVd%2BAtjLpUQRPSI5gEaXwHqbQsIRoAAGsCybxYfgMgmBcTVk0vLImQZ4owOLh-NK10f7IMZuiGWiBZyMKLHgecspbZAi2ijTAA1CaumxPxVuzBO5ZGEaDU6PcTz6zqifLKZ9xbogANKIEQACF6b1ZRYl4RIf0gYjE6RMR5aO5i%2B5f2jDdZBTtAGik%2Bo6Yg8pCFZFfn47WusOx90sVQ0%2BuhzAp3RPiZ4uAVoGHlrKP6iByBCgQN4yI5UyamIPoEqmaTv5IKyGmEK08doGEwMAzAoDNz4k6RwZQrBOqwFasUjghMhqiV5qQ2B9SpqUKadQnwaYp6REgK6Y2tZRCPGhDOZ4ejFbqKeFooiUyjokPJmQuBFCJHNPTBfdZC9HhePFOIcg8A2C4VgATZ4sj5FSnOSI5JMFaqySsXDFZAD1kbSbmwcguAolN3lLieIcQxRAsSQEqSfdZTwF9F43E-xcB3OWboNMD10RenxX6QFftmDYB9JAYFJcFmkoyYINMdD1kOKcWMuIWJ2FsB6XnIRvian%2BLMTihp4L0nWPJdI9ZBY8KYBYV44gK01rYlkfYRA8BnlL0QDgvG%2BDMCGKqYdFlYiwXTRCZIlptilWVnUqwWFxAWC7SeKkeAr5NGbi2tAPCVYNyCJ8cNK15DxH23lZy8J6yiXMCdPPCpmKJWUluEsEkoJiBmwJm8YRlIgA)

#### Code

```fsharp

let jsObject =
    createObj [
        "name" ==> "Guillem"
        "age" ==> 24
        "street" ==> createObj [
            "name" ==> "lol"
            "country" ==> createObj [
                "test" ==> createObj [
                    "test" ==> createObj [
                        "test2" ==> "test"
                        "test" ==> createObj [
                            "test" ==> "test"
                        ]
                    ]
                ]
                "test2" ==> "test"
            ]
        ]
    ]

```
            

#### Result

```fsharp
let jsObject =
    createObj [
        "name" ==> "Guillem"
        "age" ==> 24
        "street"
        ==> createObj [
                "name" ==> "lol"
                "country"
                ==> createObj [
                        "test"
                        ==> createObj [
                                "test"
                                ==> createObj [
                                        "test2" ==> "test"
                                        "test" ==> createObj [ "test" ==> "test" ]
                                    ]
                            ]
                        "test2" ==> "test"
                    ]
            ]
    ]

```
            
#### Problem description

Whenever doing interop with javascript code sometimes I have to create big nested plain javascript objects. Unfortunately fantomas adds some unnecessary indentation, which makes the output a bit less maintainable. Maybe there's a combination of settings that makes this output equal to the original expression, but as far as I've tried I haven't found any.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 08/04/2021 06:29:48 - 4bfd2581e8ef3a1f52e333e9d3a6a77ef33ab07f

```fsharp
    { config with
                SingleArgumentWebMode = true }
```

**Comment by nojaf** [comment]
Hello, this is behaving as I would expect it to be.
When you have something like
```fsharp
                        "test" ==> createObj [
                            "test" ==> "test"
                        ]
```

The `"test" ==> createObj` is not considered as an identifier because this is an infix application.
And going from there the normal infix operation rules are applied.
