### ISSUE TITLE
Comment dropped in constructor parameter list

### ISSUE THREAD

**Issue by pbiggar** [fsprojects/fantomas#1872]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEAuBPADosAslgCq6IA6AdhBABRU020BUYAzrALb5yfeUYwzAJQMawsAF4wYiABtEggB5SwAVkgAacFDaKMAS0oBzNqjABtHRFCMIkACTY85yEYxbrNRwDcAhnIArshoVnY0AAza4fYAkpRIAgDKBgBeyNExACxeEAC6XgC%2BmTa5UE5kru6e4b4BweZhMQCMJXaQBH5KADJGiN2IJhgAFjUtAEwRZQWMxV627RUuaJAARrCwcmOMdUEhlmUQ4207SYicBnBysJQAghgAogkA8gBmvZQZh2CvAXrTRTaCx2S32aw2WxO5X8e0a3wAzFD7EkcH5oIgAEKIV6wABOiAACn5cX5uBhELjtnYMLjggDZkCyo5nGD1psqfYHDCGqFvlkkVAUWjMdi8f1YAB3CnQPx6eI%2BWAyww3Dk0Gl08IzGhzRjA7yg1xsyFMrn1fZNcJqAWQIXorE4-EAVRweFxMrllAVSoMKoFvzk-01gPmJpZhohqt2PIOMTAADZrbaRQ7EABhOSytipm5sdXQDB41UQf2BuxaiA6mh6zlhlZGyOm2G82MAdkTqLtovxBHOqwpRZ%2Bf0Q9O1jNqBrrEahUfN3wAHO3hfaxdnrpQByXh0GGSHx7WoPXp43oxa7ABORfo26vcm47N8PwD9VbsvB3WhyqT9lH7mz2PNKJvhtDtkzFM4LiuX1vk3EcKzHRZ93Bb8TV-OF-1aICk2vW9wMuTYoNjZ9YLAStSj3T8DynFCzTQiZrXiRIMGeShiFxLAAHUDBGDch2I0iwGrcpEMPaimxjFpEUwkDblxWBAgSAARRA5AMC5byfWkX0YcsSPgkFEOqH8aObFp%2BSAzolFiV5iGGQYHgDRAkmGPEME4%2BBuIFLIpm3UddwQii3AEBtUJM8JmitcyuniV4DCUZ5XT8AtcQeJQcHxNg2B9dcBTUbzXx3d9yOWKBDNEk9vmaBNIqUAAlRA4FxeA3I8vk8u0t8qw-YrAo8IyxNPRhmjbaq6oa%2BAADlAk4PtcTeWJyU4MwBWaPi9P1RDOECORDBUz4ADE8U4RLb1IFw%2BvK-8FyA0a8XgAgtp2voDtxI6MHU61oGGYk0VvAB9CUDHc0ZVr8-SAtK8cQvEsKL2qmSSSwZ5cV6XNmtGTy2poHT%2BME5lwaC86-xiSZrQs%2BG-ER5GDFzSbpopOaFqWiqQcK-zus27aDF2xBntek7KkJ2jwnGDDY0gcnKZRjB7s57neeO-sPq%2Bkl8wpf7Ae4lnOqKsEIcWKGBpocZjmqgA1M0MSMeAjGMNGBy8rWyLZ3WCbKonhcksWLL2%2BT8yyy2Ehtu2McdgSupd3q3aFuxxjMr2ugU2AMAAcUUFK0sQDKsuD75ctD3GJ0o5DIeM6GY4ir2Hq5voMWuaAAGsMRV%2BvFDYZiklJNNNim7LoN4ny4NB9aApEkv%2Bu%2BcYqrF8bEAlbmsQwKVBlOxAlJiyguKy24Eh7OncSZ2MYIH3Sh5rEeqLHi7ieGsWAGlEEQHArJswZ4g77gPi%2BQ-%2B-y3zWbB7qesQQGwnldeOSh7IXDYMMHOsYHbHxxuHcMxd9al0NkcWGYsUgmAUDJYwU1BiuUQKsAgCAv4xCPr-Qe-9h7dVHqg8esZ4SATFrcFSxhKA%2B0oH7G4KQOGJUCPiYgsAGKEMSllHiDl85IK-MaS%2B7s7DwlFjEcW20KSUHET4cUJhd4zTXkYTeOZJGlnagVbWztkFyIYVfcI8ITaV05p-bopJVjwD8OmWAmUTAzznn0YxWksYdSdgA1kF9rEKMYPCT2KiFLUz8KsBQkDqbDCSFgAQXR-HSJ1q4QY8A3ifySNgBQwU0EIjjiop4eT3h%2BI%2BriOQrxIBZIsbIkpjCYjwgrio%2B%2Bj9RECHiE3Pw3D0Z9ykQgtaZ86FhOAaUphU8VG10GfXT%2BbAZJyQSDPXMiA7pV25undKmUjECiImM0%2BQlz4oOmW02xN95nEmXPiWJbBoC4lUkYRKWzHQbxuEpaAGYSTKl7t-UZVCT40ImaEi5%2BoQFMLASowpLz8ykKQJkhBOg8iZDcGwPamVzAwUKEAA)

#### Code

```fsharp
  type MyType
    (
      (* some comment *)
    ) = 
    let x = 5
```
            

#### Result

```fsharp
type MyType() =
    let x = 5

```
            
#### Problem description

The comment should not be dropped. This also happens if there are parameters present, but I reduced the test case to remove the parameters as it seems they're dropped regardless. Also happens with ```//```-style comments.

#### Options

Fantomas Master at 08/19/2021 16:27:53 - a80f888cbb71e8d0bd65d05c6ceccf9502d30f69

Default Fantomas configuration

**Comment by nojaf** [comment]
Fix available in [v5.2.0-beta-001](https://www.nuget.org/packages/fantomas/5.2.0-beta-001)
