### ISSUE TITLE
Wrong indentation level with backward pipeline -> compilation error

### ISSUE THREAD

**Issue by OkayX6** [fsprojects/fantomas#1873]
Hi :)

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPMAvGANoA6ATqQHYQQDOADuQJZVYBmYpkApHd2AA8AHzAARAIZZEAFWYBbRADoAcrADuSmbADKWFlQDmACm4BPC2YC0AWRtX48bgEoK1ALqQANOCh1sWKyGdKgkvhCgtLSQACRYZgzIaJCsWN7h0TEAbhLoAK5JYVFRAAw%2BxdEAklRIbDrMAF7I5RVgACwZEO4ZAL4tEZ1QcQmFKWzpFbE5%2BYXEgxAAjP3FkDYSuAAyrIgbiEZYABYTrQsATCWD3VF9GZErw4mhkABGsLDox1FTuQWhc61gU7LL46RDyZhwdCwKgAQSwAFEagB5dhbKjNeZgdi5fyXXrLO5fB6jV7vT6Zaa-ND-VoAZmB0R0DAk0EQACFEOxYOREAAFCTkCSKaTkclRfQFPHXAmDWLxR7JUkfBnfGZ-TFtBkQSBMlnszncnYaRDkaASfzVLKwM2BaFi2gSxBS2g3KKEzLyklvZWy7I-WaYgCsWqgutZHK5PIAqgxEqbzYhLdapMw7SHsehcRUri6ZZNiU8lfbVVSiq0AGwhnXM8MGnkAYXQ5ro9ehdAl0Cw3PtEAzWeKOYgrto7u1BcV3uLfrV1MxAHYq2H9ZHEDYwc8TT2sTindn8bdfZ7C5OVdPSzSKgAORc15eG1tQqhbvu7gf7t2HkbHsmnykBgEAJw3nqMLsCKrbyPIEhbo6zpDnm9xHhOP6%2Bn%2B6oAgsZSYtWeoRoaoLgpCaaYi%2BcFgMOAz5khUBFr%2B-roScSzYUuoEigRELvMRAKwXu0oHlRX7IT6%2BZobOGFAth1S1FgSJUDI5BmAA6swhzPjuZEUWAo5DNRLwnqh9FiSc9LMbeMLkLAeQ1GIiDoAoKmbiGPFvnxH4CQqUCpFOollhUCyathay4JU7AyAcezwpmiA6Ac3JYMp8CqSGbQXLxub8YhgmeeMdEzr5xQLMGgXrNU7DMLgSJxlI3LwrgTCIHQdCpk%2BIaBqlLnpW5mUeWMaS5eemILJWxW4AASogcDkPACVJRq7VRIO5EIUSulef1-4nAuI3jZN8AqHk8gbuQKKVNI8ghCGCwactHpZZA8h5OggR2eiABi3JQVgIoyF%2B60MX517YTt3LwDYj3Pds73kJ9IpbjABwCiyIoAPrqMwiVHNdGUrXda0GXlF4FUBI3mYKZhIuQWztjNRzJfNtCLZp2lyrjOX4wNALnFWQWkxI5OU8w7b7YdJonWdF2DVjXU4z1D1PcwL2IFDMMmj9jx-UZFSnExAKQLz-NU1gYPy4rytSLDVbQAjgqdiaqPo6pUsjp%2BPV4yJhn5VEpwSbrQUAGr%2BmyrDwEENNbilTuUd1oxu-cPmE17Jm%2B%2Bsr1WZ2zVBzUocO7Tc2R1pLsx2z7sE5ipwBcnuBiLAWAAOLYLV9WNc1YetfTXTvs77leihJcc60pxFb74MK9sbJQtAADWbI25P2B0LJOhCogD4HS1JHqWl8HY7dPW0ezG1a8NusqIg6iKxyWDqIgexq4gNllVQKnNTCNRriL5ASwCpFb0tO9jrpfefdD7FFOFtXWABpG%2BDAQphT2NUJeig0QYm-pvDq29pa7yLn1A%2B-1QGA0rpFcEdADitzzr-JmhdvzCTjh7BOtBTjE11vUIwmBzKGAOnseKiBng2AQCg1oP90F-0wQAu6QDaGlwBLSLCusYR2UMFQVOVB07QnqIoqQeQeTaCklwlMXFBFoIWp3KOMse40KJPHTEtIdatD1k9E0VAUxZCNEYd%2BR0H6sGfm2NSUV87M3HDRfSwC8FRFpD7OxxtAjII2EKZ48AJCNlgE1Iwp9z7bF8f2Yxrku7R2od5Oh1ik52LEILCQzxMBEMFgcHQZg2DrEya%2BbJnVclmKeHseAKJkF6DMJgApUi6QVzsYiTpqIMmW3IOgdgkB-FUKEv0-uFRaRDzsVAxAMCahcOqDPCQKjc6oL8RQm6Yi97BMkYs4otJj52PHrsyeyC6DmUsjUU%2B7ZECgxHorRuPJm4%2BKcuQSURz-46XEWcyxhTpHgJuQKPCPJSl0GgCwcETjpDwCjE-aENloBNkFLadeByskMxMQXbu%2BSNae1oLSAhdi9AsE7HwpAjSNK%2BHcC0FIdBXpNVCKRHoQA)

#### Code

```fsharp
let x = [
    sprintf "%s" <| DateTime.Now.ToString("yyyy-MM-dd")
]
```
            

#### Result

```fsharp
let x =
    [ sprintf "%s"
      <| DateTime.Now.ToString("yyyy-MM-dd") ]

```
            
#### Problem description
Then, it should have an extra indentation level.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 08/19/2021 16:27:53 - a80f888cbb71e8d0bd65d05c6ceccf9502d30f69

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
How exactly does this break your code?
Seems to work fine in [this example](https://fable.io/repl/#?code=PTAEHUCcEsBcFNQGMD2ATRLKgDYoIZqj6gDO+AtgA46IBmkKFZ0GARvpALABQKV8AHagAygE9SCCr161YoAB6gAvL1DrQAbTJUYg2HVAAiAKSkjajeoA8AH1AARfAgAq0CvAB0AORQB3TxcUEVg9AHMACiMxGLEAWgBZBLi0NCMASlAAXRkeXWh9OmFTAEEjRSA&html=Q&css=Q).

**Comment by OkayX6** [comment]
Oh my bad it's a bad interpretation on my side.

The code I was writing with the backward pipe was actually not working before the indentation, and it is simply due to overload resolution.

For example: this doesn't work because `Html.td` is overloaded and cannot guess which signature to use.
![image](https://user-images.githubusercontent.com/1169339/132486574-f77502f7-8b62-460e-98f5-d54b57e83636.png)

**Comment by nojaf** [comment]
Thanks for confirming!
