### ISSUE TITLE
Attribute on type function incorrectly placed for 'and' types.

### ISSUE THREAD

**Issue by OkkeHendriks** [fsprojects/fantomas#1874]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosALogM4FgA6ATuQHawAOiNYAygJ6mLoB0AIgJYBDAOZ1S-aMQrUaVWgTaMwAYViVKiaGQC802hAgAfMAEEwsAGZgsNfgTmyZBsAG0APL0QAjLMOGJKFiJ6ABUAC0pYXzCAPgBdB2dYADcAyn4kQjD%2BYm4Q2CD0mmEwAAoASjBdckgah0SDd08fPwCgxFCIqOFYhKcDdC4vAKyc7itdCvr%2BiCbvX39A4PDI6PiGiFJBAgkwQfRhylHcibLy6dpBGngwAHVI4qqIDbBjACFzKxs7C%2BZGj3mrSWHRW3V6LxSaQy%2BAI2Vy%2BUK-EeFSedVqMhecxai3anVWPXWMz2QxGsLGpymGKJWIWbWWXTWfX0Bi2O2gxIOpLh4yelNokAANOAoMREAQdsViKhXMKIKBnBBIAASBSMaWQJEEQWygzK5KCHBYZBoFw65wABiFCt1AElrkwCCx%2BAAvZBW61gAAsZrAcR1AF93XKfcrVcaoJrtda9QajdLTR6wABGIMKyAAWUEAA8ADJIxA5pjCWFRj1JgBM5p9fucgZ18rTKsU4cgXlgsBwpecMcN4YTHvLqe7LC4Eg7sBoJgIAFFrgB5Cx5mhun0QCwG0XVgOphvdptqtCt9udodQJX63vx1dgADMp8VLHogmgiDeiAsakQAAVBJRBIMiEoLsFQISgjS3WsdxDfcWzbDtgMVc9Yz7a9PXvKBH2fV930-HNYAAdwCaBBFFO1klgYidgnBCDFA8DrRrAw62cXddRg9U4JPaCLzjE1rwAVnQyBMJfN8Pw0ABVehGEoYjSJocjKP4aj0PXHBNwY7d62gsMOOPGie14mVEwANiEkTsPExBlBwEjiFUGhSDArQ1BotcN0QCCmKg6N2MPTiDKQy8%2BMTAB2cyn1EnCNHTEkgNUjyvIgZiDFYxDdP8-TT0MlDEwADgirCxM-VQcBU681I0hVGOSnzGwyqAAuyoKjP7a0AE5CpfEwLEA1R0HQQQ3MIMDPM0yDtN8hqj3g5qeNystLWvYTIssz8R3QMcypoYbKrG6qtJYnTmz02buOQq9EyTFNlosnrAI2rbysTOj9ucGqwBS4MppOzKzt8%2BbLrLQdlrtJAaAIOcaBCSg2FuOwwl2xLxu8yb6t%2BxqsvO4LjLLO9btWkxVmuTwcH4TbAOG16ks%2Buq92myM5oukKyzQ5bMyzG0LHCJhp3UxAWDCNQCHh%2BAS3Qz0qxR2q0fpjGNQhwLAZZ60k0E9nsztCx%2BCzOcZO2NRpyzegNGIYhlJ29D%2BKlg6JqOn6DwjRWmZxtqFSTMyNazAAlTQ1HgUXxdQm33sO1LjsdhWtRd1rryTcKvd9uBKHgAA5LBOUoBcbSIdApXQpMaa%2BsA0rPab0FwHYyeXAAxNRBvFAIQhOmOFtVgrlqT-300r-hq8QOvKAbymhOgMJf2fQCAH18IyEsi7ptiGed7HY6uzqvaJv82DnSg81IQPEYlkODA%2B4vS9DeXGdXtuFUrISOa3wQd73nICHTzPs9z-O44X2Wl-lhXHAVd8yD2Hk3FuN8gbWnLDdRMkAn4v33gQHuwC%2B6gPrtsEey0x4Ty0AEGec9EZ-3tujSO18AbM1xjAkG8COYADVkJvCRPAJEwhD7DUliQ8ODsWwUMbMrahd98Z0OzDXGwWgLbMOuGwjhx9uHfTIXwlelDXbXnLGzURWZeCwAIAAcTFEbE2JBzYTjkQJE%2BEAz6L3SvLJqUCVZ33VnQ3u-c3hlWgAAazeH%2BLxYpiBQxYP%2BayHYM6WwqsjW2qNSFy0jvY1Ra8Bye3ganRA%2BE3FikIkwZujBPDa1sFRSc1xYqZx-omPaCiS4R1gljBJt9nDlgTvAgA0ogDoXMeY0DtEEwYS4VzlMiaHO2PClHqn4XuQRbsGkdy0XzTaxAwjmMTFw6WtN-62LibUgRVCpkGHLBveBTpih4CJsIDODpbjeHTAgfpHoKmrPPtU06XE6nQIVDeJa8CTBk1EOImgkiJxOlENsLAGh8hgwdNsC2SN%2BaVIvn5TG-1tlqMTDeOBHoEHAICDQKFqQ8LFBKYcPJSI7AWzKXcwZp8w6KNiTUpFEydnXhvLQjFqCdh9JzP%2BLw8BBA2VgObYoqT0n5hhVVIZ0SRm0ueUrRlqKREYoEMQQQXg8BzJyGEdgENsyirelS4ZNKAGRyYPABcfSghsDwDKlFHobyaIxbOE1i4RWj0oDgCwkA4VPL%2Bi85FiTrQ3mcRi1p7T7QQztD4q4Y8dWet4dK1ubznA3mSRi9xVxPF9OIETKI1xUmcHgGy9By4jGm1MY5Kmo0Y2jO9Vav17ymkpt-MVDQiroDpE2jiog8AJK2AnJ4aAtk-yFOjQ8mxZc7FbIZda-1MyMWIi0NcpAw6onJWFHEd0GpiA13NtKCp-ogA)

#### Code

```fsharp
module test 
open System.Diagnostics 

type Correct = 
    | A of unit

    [<DebuggerStepThrough>]
    override this.ToString () = ""

    [<DebuggerStepThrough>]
    member this.f = ()

    [<DebuggerStepThrough>]
    static member this.f = ()

and Wrong =  
    | B of unit

    [<DebuggerStepThrough>]
    override this.ToString () = ""

    [<DebuggerStepThrough>]
    member this.f = ()

    [<DebuggerStepThrough>]
    static member this.f = ()

```
            

#### Result

```fsharp
module test

open System.Diagnostics

type Correct =
    | A of unit

    [<DebuggerStepThrough>]
    override this.ToString() = ""

    [<DebuggerStepThrough>]
    member this.f = ()

    [<DebuggerStepThrough>]
    static member this.f = ()

and Wrong =
    | B of unit

    override [<DebuggerStepThrough>] this.ToString() = ""

    member [<DebuggerStepThrough>] this.f = ()

    static member [<DebuggerStepThrough>] this.f = ()

```
            
#### Problem description

Attribute on type function incorrectly placed after formatting for 'and' types only.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 08/19/2021 16:27:53 - a80f888cbb71e8d0bd65d05c6ceccf9502d30f69

Default Fantomas configuration

**Comment by nojaf** [comment]
Hey there, thanks for the report.
I would guess that this is an ASTContext bug.
Are you interested in submitting a PR?

**Comment by OkkeHendriks** [comment]
I would be interested but I am very busy with work at the moment so not sure at all when I would have the time to look into this. Also because I have zero experience with the Fantomas code base. I worked around it by not using **and** for the moment.

If/when I can have a look i'll let you know, but I wouldn't hold my breath😒, sorry!

**Comment by nojaf** [comment]
No worries, I totally understand. If you ever find the time and courage, some good starting points are the [YouTube videos](https://www.youtube.com/playlist?list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K) and our [contribution guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md).
Or feel free to poke me here if you have additional questions.
