### ISSUE TITLE
Comment removed in do binding

### ISSUE THREAD

**Issue by panmau** [fsprojects/fantomas#1875]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuK9ZgPRbAYVgFtDEA7AFzABEB5AHVIggBtFKAPMAXjAEYGmYAGZgAFOwCUUADTgoAZzbkAlqQDm81GADaciKEERIAEnIBPAA7I0kVeUizDUYwDcAhswCu1nXsMAGRycoAElSJAoAZWUAL2QgpwAWPwgAXT8AXwSwA0MTcystWwoHFOd3Lx9dYL5swUgAWTd2ABlVRBayNXIAC1Ka3gAmfzL0wSy-XPrTSx9IACNYWGZ%2BvNcPby1q4MG6pkhIxEJlOGZYUgBBcgBRcJohNtJ4soghD0VRzOyp-ZnCm0Wy1W0wqmzQ2ycAGY9kZIhY3NBEAAhRBCWAAJ0QAAU3Oi3CRyIh0cDDOR0d5PuNvmV8rMioCVnsTKCqi8wIkYVA4QjkaiMR1YAB3InQNyKMIuWCilTnEmCMkUpxjJgTQQ-Ix-OYMuXlDasmoAVk5B3hiJRaMxAFULFZ0aLxaRJdLlLLOW9mB8lV9JjTNfSlozfSytmyAGzG7lmvmYvDMMXyAikeQK6DkDE617vRCUlXUpy0-5QbVM9aVEM1ADsEdNvItiAaR3mRIzwizOYgqqY6ucBS1AZ1zL15eCAA5qzzzfyCGdSC33Z7DMqO3m1r3-UCS8HwWyAJzjxEXISE9EEYhuFsK7Neqk%2B-N%2BgH9zdD7cDQJsk0T6OIQ7HU6utnzlei7emqvprg%2BG5Bs%2BvgDLw%2B6IIex4-icyz-jUl7tmAnb6GBdIQYGd5bjBwRDMaYQROQNCkAAKuiZgAOrKL0c5tteua3queFFo%2BUFli%2BJHQu%2BkYIeisCeOEVCIMwyjHMeF7kkBghLlhK7TOBUB2AOpZgsRTi8By75NOwIRCNRPRkNcHrfj0GLkIx8DMZyiQjGxy4cWpXHFPYT58bphi8EahnNGEQjKOwNC2m4abotc7AWJi8jyC6s6cgaLnATeoF3upXlaUREL%2BeGQXsAASogcDovA9mOWyzmYdhOS4YWuU%2BTpBWCLwVbFWVFXwAAcp4hBNui9whIShCaJyvD1apvw5YQnjMCo0lPAAYhihBRce1F0q1%2BokWO749Ri8ANIty3tOt6KbeQcnGtAPS4gix4APqCsoDl9DN7lzZ5ml7cOel7sVFzoniZg0OibTJtVfROelSkgV2TVzP9vFtWywzGkZoPg5D0PkANQ1EqN42TWy02uSpP0avN53KCtiBXTd227ej%2B1OIMcHvrjbgQ1DyjJmdS0M5dG1bc292PXiqZEm9H3Md9WWcc1aOEdB7VMIMuzFQAanqSKqPAqhqLDLZ1VTDXdgWqMlAD-Gc4JNSNM0q3iamyWG%2BEJtm-DSvI9lf12%2BzgOGIMBnO0ZVCwOQADibCxfFiCJclvtsml-s4YHzXFiHDth4Fkf04zSJnNAADWSIy%2BXbDyFRkT4og06DSlAGsRl7HKx5Oc8ervmaxAgxFc7fWIIKJdsMKZA7VYkmhaQTHJRc4QNsT6LkzUgGZ412d9pBfcYzUgxdc7ADSiCIBYJlmWQYQNyQjzPJv7eI5lAcq7b3l535giDIdkfNEssceQPQ041Ath3NyXdfo933msfKmNgbO2iOoVgoM1CDTIHZRA8wGgICfsELeltZq008rnA%2BHNDCQjfM7C40k1CkDdqQD25xogMKip4TE1FYDkSwVFZKLErLb2tvebicCQQazZJCbmtClpElIPwlwAp1Cr2GnPVQi9zgb0IS-JgykrYo3XAReBkiaiQh1kXEWj8Wj4nmPANwsZYBJXUKPce7RBELlfp3d%2B3c97GIkf3KRTtgiQCoILNw8xWBAMFj0SIZgKDNA8YpPRSMs4fyKGQeA9xH6RHMKwPKpjgiQgjiE24WSHjuPuuiZgQhIDCMMfhApgSzGFxCefS%2BvCKBhCrm4ZhcM25COITTHsZDe4mOaUU4eITS69PLo-eQoMxLhFHsmRAp1i7tETglJKWj5KKkgdTaBpDYH%2BN%2BAgsxJ9pm4knJiMJ8hoDohkqoKKazLQL3OJJaAcY8Qylbs-QZByDG7yMU0w%2BRT-4hNyY81MeCkBJPqnIVIQRbDyFWklLQW8MhAA)

#### Code

```fsharp
do // Comment DO
    let x = 1
    f (x) 
```
            

#### Result

```fsharp
do
    let x = 1
    f (x)

```
            
#### Problem description

Comment is removed on line with the do binding. Trivia case: Seems related to #1677.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 08/19/2021 16:27:53 - a80f888cbb71e8d0bd65d05c6ceccf9502d30f69

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thanks for the report. This is kinda related to #1677, although in this case, it might be interesting to create some sort of artificial trivia node for the `do` keyword.
I believe the range of the SynExpr.Do always starts at the keyword, so we could introduce a node in ASTTransformer and pick it up later in CodePrinter.
The trivia would be correctly assigned and the normal flow would pick up the comment.
Are you interested in submitting a PR for this?

**Comment by panmau** [comment]
I would be interested but I have zero experience with the Fantomas code base and don't think I'll find time to look into this soon. If this changes I'll let you know.

**Comment by nojaf** [comment]
As for the zero experience, there are [some videos on YouTube](https://www.youtube.com/playlist?list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K) that explain a bit how the code works.
And of course, feel free to ask questions anytime.

**Comment by panmau** [comment]
Thanks a lot for the fix! 
The next regular release will be enough.
