### ISSUE TITLE
Update record should indent from the curly brace instead of the identifier

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1876]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAnAhgJYB2ARrAO4BMYAvADq73EQTB5FmVgWFYAWjZqxFgAQrADOkumHqQAUogBmy3IgCe8oS1EQAMvmgBrTTNpgA2nMgAtQgAcHWyAG4bAcUSxcAc0Ty7vJiAK7EvpjyYAC6YAC%2BOpAANOBQkthYJL6SqFapbPmskAAkWBoOyGiQJFjJhRAlAG746CGVeXoQAAwpnVAAksRIxFgAyoQAXsi9nQAs9TGFcTMFeiVlFbnVI3Vrxc2t7ZYLEACMK6KQALL4AB76JIj6iOECu52nVF0L0UsXoHsNu1IORYOh3iImi02rljn0qBdIaNEABbQhwdCwYgAQSwAFEhgB5ZQPYjTE5gZQtdI-P6FAGXUrlYGg8GIqD7aFHCkAZnZDVGDiMiDEKh8iAACvgCCjsIhcBDRFhcG1aSJlvSFutmVtWYqGpzDrCKbN%2BVBBcLRcpxfpKPLoPh0oNGrAHZksfrWMrVXpfur-lqmZsqnr2VCjWg4Z0AKxmyAW6AisXqACqTntjsQztd%2BHdxE9ECp6BpvrpIgZkKDLNgYM94ZhkYpADY4wmk9b1ABhdCOySdrGSb3QLA%2BAuU6mINWsDXlwNA3U1tmBg4NjqdADsraFiat4quqNI8rHRZLoj904DgJ1IcXdcNq6jegAHFvLcnEP3MfmzSfJ6X-ZqV7BlAobLlyxp9AAnK%2BibYsoWDyv2KIovgY7en%2BZ5lqwFZFFWC61mG97cn0pw9BS8bbu24rImiGIej%2BE5ThAM7YXO14gbehErsRHznORbZwQhuA0eiYL0RS6FMfEl6MvON4EWBEZrnonxxoMwxYISxAACq4BoADqfD8MejH-hegGyexIKcYpD4UqcfL8ZR2K4LAYTwAAIog6CEGiQloSqGEiOezEyZWclQDUd7cRBHymuRNy3P0yjafwLx4sWiCjPwPhYIZ8BvGaszfGZoUWeFVlRVx4GNiRsYJXcgzKIQtyEhUBAjrgeK3A46jSIQ4l9NGJWYQBs5AcCVW2TxKktg1twAEqIHAuDwPlhUmiNwVYaslnAdstTVUpj6iKcm7zUtK3wAAciEKKHrgxL9AhKI5GapxSSxu0VftKIhOgmQ%2BWSABiPgoVgQnaTqR12SRL7kZdPjwFc-2A48oO4OD-lxtA-DSkYQkAPq8AVxmfWFuERQd0U1cpp3QfNLkEBohK4A8g7rcZRVbawIXSeVlOVTsMMzaIXxxolTP4CzbOEIOt33fKT0vW99nkwLBpU39AOEEDiAY1j8pQ5sIuxXoVB8X0kBSzL7NYCjOt6wbubY%2BRuP48O8rE4QpOQOr417ZNwvTWbYsIvNABqXJiCQ8BZJzY7Ff7rETVsU17DFtWdFQjlW4lwNhMOA3EDHQzxz7G19EnpX8wHP1B4dIdZ%2Bb8V53cHmwFgXj4j1fWSMXCdmsNyffYL%2B2gRntMnSIVD1XnqO648YiYiYYgECY2CSFpoz4LKn53d%2BFK-iPYA4ZrVkT4ymd0zPc1W9diAUHropYBQiAvMbiBec1xB8MX2JDH3IrXAqs%2BjHxrl9U%2BbFx42UnsdCkVBzpWwANLvwcMlVKLxBg71lKSckYDTKjXMnXMeDcabwPhPDNutwMpokkPwQem0T5nw5FTS%2BlZr7T1YFQBmVtxjhEwC5Xwd0Xh5UQKQK4CB8GdHAUQsqJDz4wIUnA2GnQeRkSttiHyvhiAF2IEXLE4wdG5hCOobSsB1KiNzMXEymVmHQOrMoq%2BU9eSW06NbAG8piDWMaE8LEvggEPW-iQP%2BA5bGnm2mNFOgd8JLhUaLEQPJw7zx1ngww914D4G7FILID8n6PHCUFXmO0oGp3knE5xFC1G53cR5OW%2BBSCYFoXLfgowNAjDuIU%2BxZSoAvHgMSPBowyiYHIaovQPJW7uIJP0kkBSca4HQMoP2ECKaKMcRUjhLi%2Bg8jnu41BiB0FDFEYMNe%2BB9FcyPoQyJxDon11iaMhJrAeR33ccvM5xg8GSBcm5IYD9ByIGRgvPW3VeqIH6mEs0kkVka1YRfWBlSxmiB5Eg150pdzqDqZIaAuBfIkFzAClMv8sReWgD2DqNiGJ2OhQo2FSiNm4U4byKh7ihk4uHJIpAXSIGpGiDMaokhgb91yMfOIQA)

#### Code

```fsharp
let rainbow2 =
    { rainbow with
        Boss = "Jeffrey"
        Lackeys = [ "Zippy"; "George"; "Bungle" ] }

```
            

#### Result

```fsharp
let rainbow2 =
    { rainbow with
          Boss = "Jeffrey"
          Lackeys = [ "Zippy"; "George"; "Bungle" ] }

```
            
#### Problem description

The style guide says that the indent should be one from the start of the `{` instead of the identifier `rainbow`.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 08/19/2021 16:27:53 - a80f888cbb71e8d0bd65d05c6ceccf9502d30f69

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
@dsyme I found out why we are not following the guide on this one.
There is a problem when the indent size is 2. [Sample](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQ2wAuYsADwAOsZj1jQwAXgA6AJxnIIwMABUAFkQCSaAIIaUAcwB0AUQC2QngE8wAd0Q918xRAgbYAOVh2AarQBXWGkwAEYXJTcNKh5-GiCQgCYwAF9IEBSgA)
How do you want to tackle this one?

**Comment by dsyme** [comment]
> How do you want to tackle this one?

I guess "indent = max(innercol+1, outercol+indentsize)"?  So the sample would indent to 3.  A bit strange, I guess. But indent-size 1 or 2 should be strange (do people use it?)

**Comment by nojaf** [comment]
> do people use it?

Yeah, it is not uncommon that people use 2 as indent size. We do this at my current customer for example.

The issue I would have with a `+ 1` rule is that the indentation flow is being disrupted.
Meaning you some lines would suddenly have an indentation that is no longer a multitude of the configured setting.
This will then slip into any expression that follows:

```fsharp
let a = 
  // indent is 2
  { foo with
     // indent is 5
     Bar =
       // indent is 7
       someLongExpression
         //indent is 9
         arg1
         arg2
         arg3 }
```
We need to a bit a special trick in Fantomas to cover this and I prefer not to have this.
Please note, that we already are doing this in the current implementation.

```fsharp
let rainbow2 =
    // indent 4
    { rainbow with
          // indent 10
          Boss = "Jeffrey"
          Lackeys = [ "Zippy"; "George"; "Bungle" ] }
```

I see two options here:
- We relax the warnings at the compiler side?
- We add a product of indentations until a certain threshold is passed.

**Comment by nojaf** [comment]
@dsyme would relaxation be an option? If not, we could go with a double indent if indent_size is lower than 3.
Call it a necessary evil 😅.

**Comment by dsyme** [comment]
> We add a product of indentations until a certain threshold is passed.

This seems right

> We relax the warnings at the compiler side?

I think not for this one, it just doesn't feel right

**Comment by nojaf** [comment]
@dsyme if you consider the [following](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWTBjGutgBeADoAnIcggB6SWABGVMWIlg0rALawAarQCusMAF9R448m7w%2BYAO6IALgAtTUmfMXiIvfgJXqtu-QaQIAZAA):
```fsharp
{ Foo =
  // bar
  someValue }

{ foo with
  // bar
  Foo = someValue }
```
the first case doesn't produce a warning.
Would you only double indent for the `with` case and keep the first sample as is?

**Comment by dsyme** [comment]
> Would you only double indent for the with case and keep the first sample as is?

Since I don't use 2-space, I wouldn't personally do either.  So I'm kind of cool with you deciding any resolution you like here.  If asked my personal opinion I guess I would say double-indent both.
