### ISSUE TITLE
Named argument should not have a space

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1877]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBbAhgNaIDKWATovrgEpVLlgAeYAvGAHaIDuYJAngGcsiXADoAkgHkxZStTr4GACgAO%2BLAAtWTAJQAdcvo6QANOCiDsWAJYcA5oNRgA2hYigIXqABIs-VWQ0SDssM3cvSB8AN3x0AFcg1wjvAAZzb29ICQ4kDiwSGwAvZAzMiAAWFLAAXQiAXzKPaqj-QOcQ-PDyqNiEpLdyiABGJszIAFl8JgAZO0QZxActbqHhgCZU6rrvRojPcb8ApMgAI1hYdFWsmLjE50Gh9bGsklEbOHRYDgBBLABRXJSABmcy410ywLiVm2DTGBxubRO50uEIgvTuA2qEAAzC9IiR1NBEAAhRDA2CUAAK%2BHI1GwiHIaK8FESsN28JaR3awRRV3xGP6D2xYAq%2BPRhPwxLJFMoM1g3EZ0HwVhy0Vgyts32ZEFZiHZXj23gRkW5yIu-K5fXuaEe5QArOKoJLpeTKYgAKqqQLkZWqjjqzU2bVOqHoGHlHaGzk9M0dPnMwU25JDMAANidkBdpLdlAAwugVYI899hOR4tAsJSdWAwxHMlGIEavCb0XHeRbE7chbaRQB2TPZmXuiaiU6Mmt1-WRuH7LlI%2BOdgXd5N2zIADkHRJzssQJa%2BJlD0OnDdnxvnx0XqOX1qxqYAnFupYgfsCROQS7gCDW9QamzHDgXDtrytTFhVTYZ0hFLNt2HSg3lwD5LhDEUpz-MBm2aWMgKgBMbzA3sINGaDs1fd8EKQg8f3LE9vEbDCAMRS9gMtWNb3AtZnmgnI8iwKQOAAFXIfgAHUbBWI9w1orx6MwsBW18HCziXUCexTNY8RI7cfnIWB4lyAARRB0BsRD32otkZw5OdsOYqBQi7djCLWMVoKmJgJGBATNCWf4pJITRKSwMT4AkkUKi2KzoxswC7M6MJ8LUtdvGGR03OmHJgRsJgpB9DRKX%2BJhVEoQRBGDQ8RXtSLT2s89bJ5eyukS1cRWGDN0qYOg4HIeAQrC1MIvQuSFNaOKHOau81gHDquspeAADl4lwcdyBBCQRFwJwnWGIbGNNJTcHidBbBMrgADFKQILB3wEy8Jo48phk3aDZp6iYjpO%2BYLvIK7zMzaBNFpKV3wAfW4GxQs0SBdpipiGvixyCPUx7Hw6nS6X4KRyDmYQ%2Bqhp1Bqi-9Yf2samtUlrU02TN3PR-BMexmxhEW5bGTWjattamG6ti%2BHDuOmxTsQb7fsZW72nu5zynWYjU0gOmGZxrB3oFoWRY0P7oIBoHK0ZMGIZWbmWwveHxopybpa4uX3IANUxEk7HgOx7DxmtCZq6Kebhk4zbYpHkq8dZNOt6Yzv0ytyod3Jnddgnqros9jfqn3yb9pKRXWVyQ6YAzYCwABxbBCuKxBSvK2PKvjmTE6w3nzRAtPKaeNLrY%2BwX5hJL5oEIEk6W77BBH4kh6X3JaKtTNCiYYkm2yUvDzYezJ1nauX5p4IWySwRUlnFxAjKyjhxPKn5clHVnyE5ifjyN2vvavVjDic5Gl%2BmuWAGlEEQVRPO8pYcmH3ACx5iTmvlPYaJsU4JQXlLJez1s5%2BUQoITQFcBpVwgLJPas84rz0bhbJeqM5aFAcJgHS9glpLGCogU4EwEClFQqAj2xMvak3hjgx%2B-sRQ4ignLH4Jl7AcDDhwCO3xCj8I0PESgAlYA8QoRocqICpI33khA%2B%2BiN06phxLLIY8tjqMg4HI6ICxvj2DPitfedgj6lgUfWBOtUk511UZLZ%2B3gcRW20SrWwYIFjUFOPAfABZYBlQcGvbgQtrHSXQTXZRydHHQOcV4HEwdtEGSZvgU4mAEFM00AIfI0xwlKJGu2KASx4Agi8WQfgmA1FN3KDiLO2jASlNBMA-65B0DAmhmAzBilsEqVwYvFxLdtEfy-jI-IORe74CEfjehiiukzx6awvp7D1FDBxCvbRncpmEC8YIHSelchr2EIgeAHj25cGLiVMqVinS-nmcwrBSyG4rJqZkHEr9Nm0jgnvJm0ByCmTsBoE5HpD7fCMtAQsdItTjyGJPRh08HmLPrg-G4T8A64jgdouQHxla0PyWAiwNQyghEEGdMqzg0L1CAA)

#### Code

```fsharp
let makeStreamReader x = new System.IO.StreamReader(path=x)

```
            

#### Result

```fsharp
let makeStreamReader x = new System.IO.StreamReader(path = x)

```
            
#### Problem description

The style guide advises to not have spaces here.
> Named arguments should also not have space surrounding the =:

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 08/19/2021 16:27:53 - a80f888cbb71e8d0bd65d05c6ceccf9502d30f69

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by dsyme** [comment]
Thanks!
