### ISSUE TITLE
Print XML Document comments from AST

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1878]
Currently, Fantomas is not printing PreXmlDoc (unless in strict mode is active).
Comments are detected as trivia as well so, in order not to print them twice, we don't print PreXmlDoc but print the trivia instead.
This is actually perhaps a bit inefficient as currently, we need to match the trivia with a trivia node.
The PreXmlDoc will always be assigned to the correct node in the tree, so it should be ignored as trivia instead.

Practically, I see an opportunity to capture the ranges of `PreXmlDoc` in `ASTTransformer` and eliminate trivia content in `Trivia.fs`.
`CodePrinter` would then need an additional change to always print PreXmlDoc.

**Comment by nojaf** [comment]
Keep in mind that this idea needs to play well with newline trivia.
Something like
```fsharp
type PostalAddress =
    {
      /// The address
      Address: string

      /// The city
      City: string

      /// The zip code
      Zip: string
    }
```
Would still need to work. Perhaps the PreXmlDoc should also be considered as trivia node candidate in that scenario.

**Comment by auduchinok** [comment]
XML docs could be integrated into declaration ranges after https://github.com/dotnet/fsharp/pull/11973, would it help Fantomas? Would it make sense to wait until that PR is merged?

**Comment by nojaf** [comment]
Interesting stuff there, yes is worth the wait for that.

**Comment by nojaf** [comment]
Be aware that this is valid code:
```fsharp
/// DOC COMMENT
// simple comment
// yet anothet simple or (* multiline *) comment
type A = ...
```

**Comment by nojaf** [comment]
I've been playing around with this on a local branch using an FCS that has the recent improvements by @DedSec256.
It works out nicely.

The only catch was when you have a regular code comment underneath an XMLDoc.
```fsharp
/// doc
// no doc
let a () = 0
```

To resolve that scenario, it was useful to have the `let` keyword as part of the `SynBindingTrivia`.
