### ISSUE TITLE
A DU with one case but no value attached is formatted with a bar

### ISSUE THREAD

**Issue by panmau** [fsprojects/fantomas#1883]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAspgCICqYAvGADoB2APmAMoAWsATumLAGZgCWNdLVpZcYABoBNCtXpgAggGEAhgGdkAGnBR16dAIDmq1GADa2iKAjWoAElHI0kAekhabESLYBuygDYAro5mFh4ADO4engCSNEiCjHwAXpqhNgAsaWAAuqEAvpGWWV4OJs6CbsU%2B-kEm5lEQAIyFHpD4ygAeADICiF2INAbozJUNYI0ATGFZuTYFoVat9jjBkABGsLB%2Bo0u%2BgcH1DRMtNpCMiAC2fHB%2BsDTy6ACicQDy3D00qWPc-uoz%2BS1FqdlrgyhstjtgXtamhDlEAMwnaxnbDKaCIABCiG47EQAAVlGxlBdEOhEGxIR50Gwgv85oCqqUnODtkivNCDlkIOkkZ5GKj0VicWw%2BrAAO7k6BqRCxbywKX6O6UmzU2lRWbWeY2IHIkGrFnKuwcupcsAAVl5UH5aMx2NxJGwuDYUvUsvlykVNENEB%2Bfj%2B6oBC0ZKzBm1ZVWNsNNADZLSibULcYo-GpVIo7qpVdB0OxvWBff6PBqIFrrDrPHrQxC2dV9iaxgB2OPWwV2kX4S5rcl5guIOmahlREoh5lhw3smqcsYADmbAttwsQ6duXstvf7JcHSyZUANNcjITGAE45zb5NwyWx0xcLso86q%2BwH6UGh5XR9WI5P6w1GhFTfHW0Xc4rhuJU11%2BR8i0DbVg1Bd9w1fA84Q8Rpmn-FtEHPS9gOuLYwNNB8NzAUsilfHd1jHfcvyjMZJjjWJ4nQF4aAAFTYTAAHU%2BGGHsIKIkiwHLOxyL3T86xon9EXQ%2Bd5DYWAAjiIhED8Pgrkve8aUgmxi2IrdgXIlxx1rGFDx-Hl-3aDpom4FjmAGR4-UQFh2HQLj4B4y10mmJ8BxfbcRygQyqPE0yokaC0LM6WJuD4DoXidD12EeDpsBFVRVD4fCxjNbyoOfGCyIC8pXGCkzkJsRpY0ijoACVEDgNh4DcjzTS8-i9N1AyKlKqcfybaq6oa%2BAADkAguLs2DeaIyQuYxLUadq-P0oqLgCPx9BUz4ADF2FvPRyRYkMeu-MLZ3-Qb2HgfA1o23odrYPb1LjaBmEJNFLwAfTFPh3JGRaCv8uDAu6sSytNRoT2q2SiUwF42B6TNmpGTzcu06Cy1g1YgtB3qoimONLOh5RYfhvhM1G8bySmma5vB-6McKoHIFW9a%2BE2xB7seg6jpxk6PAmNCxkgImSYR9BrtZ9nOY9J7-xet7s3JL6fp4%2BnSMBrGQcQ6jQv545qoANUnDEBHgQwkbzNqfM3JbOqK7HtZC8rrAmKShcsraFOzTKaBNuJzZV5HWtR6wdIEoThyZh3dh152IAmcz3c6IhYHQABxUlktSxB0p9i3LRytXBMxqsEJjp3TQmCL3ZutnegxW5oAAawxIlm9JVRmMYYkly2MbV1Nddrd022KxEyjeYkvGqqF4bEDFdmsXQCUBkO3AlJimhuJ9%2BQ4g7Sm2Fp74%2BOH8OS-goykMr-qhYAaUQRBsGs2yBlibuSQ%2BL4GiHvLfIB5ao5a3LmDMYEwzpJw6A5K4qhmD52DkXCOb5dwT0diAo4kMhaJEGH4TCbADBjQGK5RAax8AIC-lEH%2BaN8oMw1qXS%2BsdTTwj-ELeQKkDA0E9jQb2dxEjsI9AEEULFYAMUIR6H2vFHIIPPsgj8qDcYeHhILBowt1rkhoGI7wopBj7wmhvAQ28MwSMLFQv%2BNCAH6hQcA%2BRNh4T6xrqzT%2BXRiRrHgMoZMsAMqDDngvXoRitKh3RurcxdDjpTwUW7ZRRAybKDWDgqBZNmCMEwIITofipGM1WAMeAbxP6MCwDg%2BhFcxjwkTso542T3i%2BOemwPw3BIDpNoRfUJusbHV2UffR%2BIjBCxFbsoLhQdj6SNPh1MeRVRJyL5jYmeyiG59Kbp-VQsl5JxDnpmRAV1a7syzmlDKhjLSEWGaPYSYzLFQgYcUm%2BMzCSJhFFE1Q0A2CqQEB6dZJAt53CUtAFMRJPRpMOf-O2TNxlWMmdYeE4DlF5MedmUhSA-m-xLNobIkRnCqC2hlEw648hAA)

#### Code

```fsharp
type MyDU = 
| Short of int

type XY = 
| ACase
```
            

#### Result

```fsharp
type MyDU = Short of int

type XY = | ACase
```
            
#### Problem description

I would expect that with the option `BarBeforeDiscriminatedUnionDeclaration` set to `false` the code should format to this:
```fsharp
type MyDU = Short of int

type XY = ACase
```

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 09/07/2021 15:59:52 - 7d861f4834c9bec59a1f3929265ecc3fc600c196

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
The bar is necessary in this case to not confuse with a type alias.
```fsharp
type XY = | string // DU
type YX = string // Alias
```

**Comment by panmau** [comment]
@nojaf Ah, that makes sense. Sorry for the hassle :smiley:
