### ISSUE TITLE
Documentation contains reference to infix multiline formatter even though it's removed

### ISSUE THREAD

**Issue by panmau** [fsprojects/fantomas#1884]
In the [documentation](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_max_infix_operator_expression) under the description to `fsharp_max_infix_operator_expression` the property `fsharp_infix_operator_expression_multiline_formatter` is mentioned. This property no longer exists though.

That option sounds really interesting to us, so I would be interested into the reasons behind the change. I couldn't find any info in the respective PR (https://github.com/fsprojects/fantomas/pull/1232).

But as I'm sure that there were valid reasons for this change, I suggest removing the note:
```
Requires fsharp_infix_operator_expression_multiline_formatter to be character_width to take effect.
```

**Comment by nojaf** [comment]
Hello, you can read up on the thread at https://github.com/fsprojects/fantomas/issues/1143.
In summary, this was something that I didn't want to pursue as it does not move the project forward.
The docs should be updated indeed. Feel free to submit a PR for this.
