### ISSUE TITLE
Regression of #502: Pattern match bodies no longer indented sufficiently for shorter indentation sizes

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1886]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbAhgF2gCzAA8wB3AS2zwB0AnKgOwB8wrIBGVsAWgD5aGIEADax6AcwAyZeogmjJ02fKky54lUvWK1C1cu369WmfyYtIAJk69Tgu2BHHNu5xp1vDrg0-feXpyAAacCgAZ0RsbGkxUNQwAG0QiFB7KAASbABPAAdkNEhpbCCkwUg0gDdMIQBXPISSuwAGYNSISABJeiR6bABlMgAvZBbWiwawAF0SgF8R5PGyrNy4gp7i1LLKmrrE1rA2OftIAFlMQjdEcUp11oAORvGpu1mSlKOMnLrIACNYWCEbnZNlVanFdqNDkDeoh0GQ4I4AILYACiXQA8gAzDSA%2BwYqrhR4zQ5vIEfZb5X7-HFtCognbjCAAZkhpV62Uw0EQACFEBjYDREAAFTA0TDoCKIGjUwTYGi1QnPYkLMlfSkAlnA7ZghlgAAsLLabI53N5-KUJEl0Ew4U65VgVqiomlEFl8tST0ELzsJNKKpWaulmtBaHBqQArAaoEbOTy%2BQKAKrZXI0K02%2Bh2h1kJ2RvFCAnuomvZVLVV-dXKrbB%2Bp7ABskcg0ZNccQAGEhNbQi3RKFXdBsPznWBc-n7B6IF7BD6aSX-WXA7StSGdQB2euN2Nm44w76SwfDxAKz1KjZ%2BilzjULquh%2By3NfsmOmgVdxx7-EHguKosnmdnqkXyv0nsACcd7GgiGLYJKXboFgg6uu%2Bo6Ft6xafLOf4VnS2p7GwzQ6g295Nma0KwvC2Y6vuh7jse7w-lAAb-phS7YQceGNuBkE0MRcL-GRezwZRYATvM36ob%2B5YngBWGtGwFj1p03TYGi9AACo0JkADqFB4K%2BeYIXYY6CdRpK0T854YYu1bScyrEEQiNCwNUXQACKIEIZCwhxcFynpggGUJYBTukJmFPOklMdJ%2Bp4achDtBiyl4JcyK6b0eD8tgmnwNcka6g8H5Hl%2BNGiVAIUMRZ152GwEZRWcnQYmQhBosmOD8sihDZAKoShFm9CDmGuWIZ%2ByEieSxVrKVV46mwdbVYQABKiBwDQ8AZVlOo5QJ-mBYsRWrEU42AdJq4zfNi3wAActU6A7jQmLtJB6CxJGbAbUZvomeg1RCFEbkyAAYvyWCRJKymoftUmpGwt54Sd-LwMcn3fYo-00IDnn1vgIochxAD65CZdpL0FcZO0leZE3YSBM12aKmRojQUg9it2nZf1%2BlIZOKEjbtoWMZZqQWLhewnGc1OYLT9NkD2F1XZKt33Y9k2E0NhVcx9X1kD9iDI6jwOg2TB38yxQui%2BLDPYPD6ua9rOBo3hGOin2kq42Q%2BOQErHPDV8pMSbz5WCBYskzQAanSXLSPA0RM4O615VRRNvSTY36%2BD9gWNZQvRb9jl9t1YddJHLurXsMcDflyvE1z3vvGFfOp5FGdnE5sDYAA4hErXtYgnXdVHkZ9e7wkq6W6E%2B2VOoWFVGcIxrihciI0AANZcg7C8RKESm9GKrb-JdPU5m%2BA8BZzw-idXvvj9NQtnYgJCazy2AWpcIO5C5dX0BQ3UIl0W4yzQCt7BRWOhl47Th2vRZO4V%2BZHSFgAaUQIgbIsV4qXE6JvcU2J966UPltU8o09oQNrnYCwUMG6ECSrCUIeBe5rVZr5dmg8K4nx5mPPYFhKZC36OIIQiA7JiEupcdKiBvjHAQMMciB8gGbWPmhU%2BpIa5%2ByZILVokAERuTEPQLO9Ac6iH6OonA1QBTKVgPJAROBuo6RHGzQaHsh4yOYeTVojIjbKNURxegZjyjOB-tdV%2B0gP7dgsT5CAflXqgK5uA0eDjUiMkDlPdWbgxTfHgJgNssAuriGvrfRQgTsHSLEvYg29hGTp2UU5SWmBvjcPIZLPAvRMg9DODkyRoSgo7UuPATEGhehZG4QUlOdhGT12UaiDpWJsnoxoEIDEbtmkgNaeEsykTCkDMnsouBCCTE9E6MvTAWjmbiKwbM8uCcFkjzPiwxxl9lFz12QvDQoQ7IOS6NfHsiA4bT01h3DqXUAmRn4kcmxjC7Fg0gUU6B1yRQbgFGU0I0AaDuWkDgN58Z36iBctAdsopHR7wOZYuh1iGEnKYSCwhghGQkOUd0%2BFfYRFICaaXccIQJgjAKKEX6XU4gUWmEAA)

#### Expected result

```fsharp
match x with
| "1" ->
    longLineLongLineLongLineLongLineLongLineLongLineLongLineLongLineLongLine
| "2" ->
    longLineLongLineLongLineLongLineLongLineLongLineLongLineLongLineLongLine

```
            

#### Actual result

```fsharp
match x with
| "1" ->
  longLineLongLineLongLineLongLineLongLineLongLineLongLineLongLineLongLine
| "2" ->
  longLineLongLineLongLineLongLineLongLineLongLineLongLineLongLineLongLine

```
            
#### Problem description

There has been a regression where pattern matching bodies are no longer indented sufficiently for shorter indentation sizes (e.g. 2 spaces). This was originally implemented/fixed in #502. I don't know when the regression happened.

The extra indentation is useful for better separation of patterns vs. the "body" of each pattern. The problem does not exist for 4-space indentation.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 09/08/2021 16:41:29 - 9bf6601bcb534f7afd200213aa28d81f8a39a139

```fsharp
    { config with
                IndentSize = 2
                MaxLineLength = 80 }
```

**Comment by nojaf** [comment]
This was updated in https://github.com/fsprojects/fantomas/issues/1501 to align with the style guide.
The codebase also benefitted from this correction.

**Comment by cmeeren** [comment]
Ah, I wasn't aware that the style guide didn't cover this. I have created https://github.com/dotnet/docs/pull/26071 to try and rectify this, so we 2-space-indenters can get sufficient visual separation between the clauses and the bodies. 🙂
