### ISSUE TITLE
Incorrect indentation of ending list bracket with SingleArgumentWebMode=true if list ends with empty line

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1888]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuK0AWsCW1FgG0AdAJyIDsIIAHAI1lgBswAfAPjbABlsAXREgENGpClTAAvAbADyJGeUQBBAM4AhBs3ace-ISLLlR5ALrHIAGnBQViXr2zkA5itSFrEUOIiQAJLwBPamQ0SEdeSw8qPwA3YQBXEPdvKgAGKxSfAElyJHJeAGVsKUjMsAAWKIgTKIBfDKovbz9A4Lcw-NLm3zjGRLcCKqoARgaUyABZQQAPHkUuRGdeDC6U4YAmVKGa8XqopvEWoKTIeiZV6J6EpMGy9bHmgsQAW1wmWHIlXgBRXJkAMzmyAe4n%2Bwls2zqDwOl1aJzOjAuPiufRuQwgAGYQdECtRBHg1Ih-rASIgAAqCITPOwCJFUXgkRKQ3bQoZHNqhBF02LXAboirYny4-GIQnE0lcWAAdwE0EEthyMVgcocHzpEAZTJSOyoe3EMORcPaXOxPNRfLKAFZBVBhQSiSTEABVajBEhyhXkJUq7Bqm1gxgQ7VQ-Zs-zHY2abko-poW6ZABsNsgdtFDtJAGFGPKVBmPipNdBeCT1WAA0HvDqIHrGmGjZyo6aY2iygB2ZOpsWOiYvWi0-3gxDM3Ws8bhjlQE1h3qx5KZAAcHbx9vFiDzjD9-PLQ%2BDLNDY-rk8b095cf5AE4lyKlP89Hnns9BKXNTvKyH9XWIw3zk2Zy3MsM6T8imy5pquTyvHAG7kKW27DtWo7dIepzHmOf4WgBozAamN56BBbzQc%2BjKvuIVZgDWnifhOKE-ie5pnmUGzJjkeS8AoAAqJABAA6nwKwDoGJFUGRFFgAaUDjvCqHdOhDEAVi2GgUoJCwPEuQACKIIw2CvHoRFam%2Be4fgeX5QOE0ayXOazlMmUzTFk-zsRgizfIJBRYCQvC8fAyyluUWy7iO%2B5IaZHQRL%2Bp5Wd4wzWsBdk5P82DTDIbqCMWJDfNM1CkioKi%2BjBNqWgFhlBcZIXUeZEX0VF4jDEmcUzAASogcAkPA3m%2BTa-nweRiGHJJ7SVXRs7xms7YNdMzWtfAABy8TPH28j-Fk-DPK4NrDD1onieyJzPPEjAONpigAGIko%2B9gCOxEZVSN-LDIuwFTSS8ATAdR2OIgZ0kBdenJpglL4noAD6UrYD5KxbX1sKhUNaGRaN0WXhNylCAEcg8AWHX8fy3WBQhwX9chcMyQj-KbLZMyo4I6MkJjvBzQtAgAitLzrfdUOEzD1H7Yd2DHV951pXo11tLd-4pOsWFlJA1O0-Tb18wL32-f2wEA0IRYCKD4O%2BZzZVE7DnTixhkv3BNABq1xqI48COE42N%2BcVpHvrWJkVcbw0S946wKTLdknWpRb5TbuT247XXO8JruUe7Jwk-1lmI%2BI6w2RN6mwLwADidiZdliC5flEf8kV%2Btu%2BVUm0fD1XJ1Q6yxf773859agbtAADWaia%2B3dgqAoBSCNS67zQVW6DmXscV5GVekzX5P1TLM2IFKAuErwMqLKLiCaYl5B8PlSi5D2TMkOzZRwfjvVc4aoVTtXd13ONMsANKIIg1AOU5iw5AP1JArB49L7bSovHT299vYp0ev7GYrlXgqAwMXMoeMSoEwNtzSuiITZyUlsjGWRRnCMGUCQJw81FheUQLQCYCBgT8hfBPMSIDp6YK9qbbwGIgIyyUNpJw5BA7kGDh8IoPC0rxFJOxWALEyFpXygAwS9CdoDW-Mw8BrDxAYmlpkWWh0BDkGkTERAkpnDH0WjvRw%2B98yyIrC7Iy5dDbUTvrPB%2BmQMTm0bnzIEXBB60HgIILMsA8rOCXivT6lihLVBjgwuOTCLJkzKBiP2mj1LYBUIIWghDYHJIwAUAI%2BQZihPkYw0Iix4AAiBAUQIhCYlzziWnGWvwSmAhCf9EgjB-iQAKVEpRVSnEpAxA3TRr936SPyDkLugh%2BE43PoAlBV80E33sdJROsTnEL00a3cZ7cgQqGUqpXIS8CyIFek3AWeccp5QsTaOhQDobzIwd0iBVAMRPzWZSLspIkkqGgCQHSjg0qHKdHvD4mloDZiEKqUeUy5HXOvhJZCDilnVOcVAzR5TvlFioUgfJQDrAmAaGEFQJ08puDgrUIAA)

#### Code

```fsharp
choice [
    pbool |>> Literal
    zeroOrOneAsBool |>> Literal

]

```
            

#### Result

```fsharp
choice [
    pbool |>> Literal
    zeroOrOneAsBool |>> Literal

    ]

```
            
#### Problem description

If the list has an empty line before the ending bracket, the ending bracket is indented incorrectly. If there is no empty line, it is [indented correctly](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuK0AWsCW1FgG0AdAJyIDsIIAHAI1lgBswAfAPjbABlsAXREgENGpClTAAvAbADyJGeUQBBAM4AhBs3ace-ISLLkAuqPKQANOCgrEvXtnIBzFakJWIocREgASXgE9qZDRIB14LdypfADdhAFdgty8qAAZLZO8ASXIkcl4AZWwpCIywABZIiCNIgF90qk8vXwCg11C8kqafWMYE1wJKqgBGeuTIAFlBAA8eRS5EJ14MTuShgCYUwerxOsjG8WbAxMh6JhWo7vjEgdK10ab8xABbXCZYciVeAFEcmQAzWbIe7iP7CGxbWr3fYXFrHU6Mc7eS69a6DCAAZmBUXy1EEeDUiD%2BsBIiAACoIhE9bAJEVReCQEhCdlDBodWiF4bSYld%2BmjyljvDi8YgCUSSVxYAB3ATQQQ2bLRWCy%2BzvWkQemM5LbKi7cTQpGwtqcrHclG80oAVgFUCF%2BMJxMQAFVqEESLL5eRFcrsKrraDGOCtZC9qy-EcjZouci%2BmgbhkAGzWyC2kX2kkAYUYcpU6feKg10F4xLVYH9ga82oguoaocNHMjJujqNKAHYkynRQ7xs9aDS-WDEEydSyxmH2VBjaGejGkhkABzt3F2sWIXOMX18suDoPMkOjusThtTnmxvkATkXwqUfz0uaeT0EJY124rwb1tfD9bOjenzYyQzSPlkyXVMV0eF44HXMx%2BwDF9xErMBqw8D9xxOI9R1-c1-xGICU2vPRwNeKCnwZOCqAQpCwH1KAxzhdCukw09SnWJNslyXgFAAFRIfwAHU%2BGWGDy3gt8a33T9D2-Y8zSY-9MVwkClBIWA4hyAARRBGGwF49BIzVX13d9xNQsIo0Y2dVjKJNJimTI-k4jAFi%2BWD8iwEheH4%2BAlhLMpNh3Yc9y6A92nCH8TwsrwhitICbOyP5sCmGRXUEIsSC%2BKZqBJFQVB9aC%2BQtPyDICoygokkKzPCuNVkTGLpgAJUQOASHgTzvOtXyhyrEdSpMjowpkiLxCGNtaqmBqmvgAA5OInl7eQ-kyfgnhca0hk6xDuoOWi2ieOJGHsLTFAAMWJB87AETjw36mcqsihcgPG4l4HGPaDocRATpIM7dKTTAKTxPQAH1JWwLzlnWyjqLZY5TOuv9VgvUalKEfw5B4fNWsEvkOv8rrAq24LYekm6%2BQ2azpmRwRUZIdHeGm2aBH%2BRbnhWvk1txjb8ZhMrdv27BDo%2B06Ur0S7WjhrDkjWHDSkgSnqdpl6%2BYFz7vr7IC-qEQsBGB0HvIhzbud60Lifhrw1juUaADUrjUBx4AcRxMZ8wqRMMsSephvqTYls35JlmyjtUwtcttnIHad9qXfI0TkOMz3jYwyrSas0a1NgXgAHFbHSzLEGy3KI-yqOqhjqiULoqTE4G27xDWaL-de-n3rUddoAAazUTW29sFQFHyQQqTXGa8tKLd9a5g0ysnKuSduGqZcmxBJQFgleGlBZRcQDT4vIPhcqUHJuwZkhWdHgdx5Kgmp-orbzJrqg1hGmWAGlEEQag7IchZsn7qlARLMeHNIblzaETGepta73X9tMZyLwVAYELqUHGRU8aX0NhXBE4tZKS0RjLQoThGDKBII4GaCwPKIFoOMBAQI%2BTPgvu7K%2BqFp4MSTqUdEgEZZKC0o4cggdyDB3eIUHhKU4gkk4rANiZCUq5QAefIBBtJ5MJvhcO%2BfJ0TSwyLLfaAhyDSOiIgCUTgj5zW3g4PeeZZGwXobHD2EZK4sOrmoi2Dc%2BaAi4APWg8BBCZlgDlJwi9l7vUscJaObsbGMIwRVRxbC-aaLUtgFQghaCENgQkjA%2BR-B5GmMEsiJcwllzjm0BY8B-iAnyAEQhUTZ4ZHRCnGWPwSkAiCb9EgjA-iQGsQU2xX5MHe2wV4dE9dNGv3fpIvI2RO6CH4VjM%2BVj5ETxosFZht9WE1PnpoluUy26AhUEpFSORF75kQM9RuAsc5ZRyhY60dD5loMUZErBg0qDoifhsiknYSTxJUNAEg2kHApWOY6Xe7wNLQCzEIFUI8MiAJQZzO5izr72JWdEmpUDNHlN%2BYWKhSAckQysEYeooQVBHRyq4MeNQgA):

```fsharp
choice [
    pbool |>> Literal
    zeroOrOneAsBool |>> Literal
]
```

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 09/10/2021 14:22:42 - 95fbd8276b0d64d91a0221dbfcd465e25b088987

```fsharp
    { config with
                SingleArgumentWebMode = true }
```

**Comment by nojaf** [comment]
This setting no longer exists.
