### ISSUE TITLE
Multi-line comments break Fantomas parser

### ISSUE THREAD

**Issue by Dolfik1** [fsprojects/fantomas#1899]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBtAPAJUQRwFcBLAJ0QEUCBDAGyIDMjF4BBaaRAZ04D4BdADoA7ALYICNRGACiADyoiADpLABeYcIiSALmHhFo2gIxqwAYVhDoBEmSHaAIge1FLVEgE9MYABQAqME5YESk4ERD7MBM-AEowInsAZgAmABowAiEibR4fGM0wHT1nZNMLKxs7R2dXIXcvXwCgkLAwiN1S2Pj7ADYAFnTy61tEeydDWvrMf0Dg0OD2sESwLoTtFPTM7J5c-KEoVPAoTkRtFyEAc05UMHQjiFAIJ6gAEm0PRWQ0SDXIQ%2BeIJAXgA3WgEL63e4AgAM-wBgIAkkIkPYAMpEABeyDh8L6UIgfChAF8cWBHgCge9PjcfvY-vjXqCaOCbnd4RAjKTnpAALJUWQAGQSiAFowu2gAFvT2VFktCGYTniSoeTuW8PhDIAAjWCwGjSikgsEQtnstIMwGoxAiAx6ywsbTSZEAeXoQqE2ItYHotBOCuJpNVT0pGppOr1BrVTJZaFN8MSXODqMUVA4ACFEPRYGQAAruBSnRAkSMA7QkcH%2BpWBhkh6nfcP6xNA6Mmr0DL2QZOpxAZrNkAWwADuRegVBOSOBsFHLksJeeZYr8MVT2VzyDgPVdagDbnjONrK9AFZE5aU%2BnM9nEABVRSfEij8dCSfT2q7iA%2Bmh%2BpcBlU1zeancmyNZlWxlHoTygLtzz7RAzBoMdOHKTgF0MbM329X1EErFdq3hWsAN1Rs-xbA8ZQAdggzszx7C8yB5a0tSLdCPy-AFlwgVcnnXV4qQIiMgJI2MvQADkoqCaJgiwaFnCCWKw78q1-PD-zDQjd2bfchJlABOMTqJYehtCLCxwiodCF3ktifzXP9eNU-jiM0yEZSMWEO3E3tLytG04GkoRmMw7CONww07PrNSBKcuMASMTl3P0wyi2820-PM8tLOediwE4h5bNDcKHOUwTnPZIxzRlSAkRRbRnSEAAVTwAHVsilWTAoUnClNC-LtwixyQNI0qE3i7sWBIWBMngBxEDoG0jOLCCLKC7KQrVMKoF%2BSKBq00r2wqvlZAReg6olUZpE-RBUQlbNtGa%2BBJXQvp5Q64KurWnraW0dTgJjEr4SMY8OwOpFGFkZ07yobRszkRQyG4V8IMPZ6rMUmzlPWz7vuK6LniMcCgf5XA4BIeA7oeiCnuWnKyTyrdMa236caeIwKIJ2QiezeAADkCBERiSFdBEjJEa4IKMKnVuDFTvhECQXDoD0ADFsxESH5rq0MGdA0rRI7DmSZ5OWiAVxBlZIVWziYyjoAlfNDCLAB9QciHuqUJbeqWMc2-rGa9IxdLZsaSCoDxnRIIVkLJ1q22RzLrK42nNW9oqoq9OVKIOoOQ7DiPtB5vmi0F4XRb9920e6unZZoeXhTNi31c1n3tfhZI4oqrPQ-DohkMN6vjdrlW1atjsbbt%2BanZdh6y4T9GPuTw1sbT8r2V5fkADVjTTBJ9EuKPHtjp4sup7j8Jpeeo1TmVkmG-b%2BUVzIJksLfkQSC494pg%2BCXj3LZ7p8%2BpcXlfPaK8DoOFgNoAA4qcGGcNOC1HfkeT%2BYAj6Sw3BjQCTdBot0BvtI2Js0zSWgAAazTMHYhpxOC1VRAWKSvN-JtQutPH%2BFc%2BJERTttP6AJkj4wqlzRAg58GnGHKMDWnxpqMCyDOIQLBkT0QLiQEuMo5JMJpr-VhWNL5mlZhVAA0ogRAigjonVGEiahIR3SeiUe1FGnVy7vT-nSLWWCuG61vrIc6NpOASgQTKSmL0VoezQR9DB7DfZXwDhVdElxJBjQuLzUYt1EBah5AgSx7JlH%2BOPoneybCF6aPjG5dudALhCHvlYKR6ISmQxsIgOqsAqoJMhgjL0GSbGvTsZ7YJfVQnNwBIkNuK8WDVyLHUFwwIRSWAuHI-m4iEjZFqIo9J1i46oxniwnJGiOFMwgBsIGRsLECgUFqeAVA4KwDgZcPhAjhQBUYZk1BPEumFTyVsr0iQb4rycJwKgWpJAeO7hKVEHh7D8luaxFZti1n2M1KMeAroLGoneJITZYT2SJGAXhJ0cK3Q3OtiQGg9BIAqJPtLXqzyL6vJlIkHBK89EGIafYJEpCqBWGjlYu5bSAkdKCXTEJLzUXxh4SvAhLKiEWM4GNCayI%2BHIWYL3GuHoYFcDgZYRZ8Ilr3MCY83l3T%2BW9OeIkbRwr3CeTIF86AJAiA2lGcwK8WRLDTWgPBYOUiwUZUPt-VR6yCq5IpQKvpriV6IstYYFJSA3VUyOHwOEPxOCKzgTcZRRIgA)

#### Code

```fsharp
[<RequireQualifiedAccess>]
module Example =

  let dict1 = ConcurrentDictionary< (* some comment 1 *) int32, unit>()
  let dict2 = ConcurrentDictionary< (* some comment 2 *) int64, ConcurrentDictionary<(* some comment 3 *) int32, unit>>()
 
```
            

#### Result

```fsharp
[<RequireQualifiedAccess>]
module Example =

    let dict1 =
        ConcurrentDictionary (* some comment 1 *) <int32, unit>()

    let dict2 =
        ConcurrentDictionary (* some comment 2 *) (* some comment 3 *) <int64, ConcurrentDictionary<int32, unit>>()

```
            
#### Problem description

I am getting `Unexpected symbol '(' in expression` error for valid code.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 09/17/2021 07:14:29 - 735d58ea7238156336c5e1ee7198e1865593bbf6

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hey there, this is trivia related issue.
The comment is being assigned to the closest Ident, while the `<` token is [the better candidate](https://fsprojects.github.io/fantomas-tools/#/trivia?data=N4KABGBEDGD2AmBTSAuKBtAPAJUQRwFcBLAJ0QEUCBDAGyIDMjF4BBaaRAZ04D4BdADoA7ALYICNRGACiADyoiADpLABeYcIiSALmHhFo2gIxqwAYVhDoBEmSHaAIge1FLVEgE9MYABQAqME5YESk4ERD7MBM-AEowInsAZgAmABowAiEibR4fGM1IVPAoJEYhLlQoQuLIIk4AMU4iSvpaTkQQAF8gA).
Are you interested in submitting a PR for this one?
