### ISSUE TITLE
Unexpected newline added before let bang

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1932]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEOaxADgJ1gFsBLAZ0TGAB08qA7bRx8gFwEkXFDSwBtAH34BdGvSbiMrAMqIANomid4HLmABysOolEMJ41gDFELaAAtidAOYruYFngCu22rr2N5LAIRhinWwF4wAEEcYgA6ADNjMxseHABDPBY1B0IAI0RaFzcmVlifP1IdHMZfLh5%2BAD5gvDx4gE8w%2B3qACUR4%2BDAqsGk5BSUbYpKsQ2jzK3yI%2BNlyHSHhjBkARya8VvbOsu55ha7qgHkcFmJNMLK8MAAKKSIKSure%2BUVEZT8ASh23AF9PvW6ABQIJHIYVILESLEgABpwFBWMcrKRUHxYRBQNhIAASFj1HDINCQCyQmEYzEAN2mTmRvFRWAADCTGJA2HQkHQWFJiAAvZCM7AAFlpECEtK%2BfMoQqg2Nx%2BKgROhkqxFNkVLQNKYAEZxZhIABZeIADwAMhZEEbEFYWKYFZqAEx0yUizBi2norBYnF45GQNKwWCyG3u8mU2Xqxi27UYSAyEhwWSaIIsACirP2ERNWkD2CmM0QjtF4rdOulXoJvv9WajwZVoclEAAzJGINGEtBEAAhRARWB4RD-RLxQjGTKVzD2Jz552FxUl2U%2Bv0ByNKkPUutgflNqBSVsdrs9s2wADumWg8XILLJsFPx00o4w47z2CdGBdmCLVc9c-Li5nytVKKYABWTcW3iNtO27XsAFUcDxPBT3POhL2vE46DvCAc3IScX2nUlP29b872XGtVyYAA2EDtzA3dIMQABhWQz1IOjNDBRxFB7dCwEwx8sGfCBXwwd9m1nAiFyI6t-zDbAAHZKJ3CD911LgMjwLieOwgTcKDfCy3EpdJNrJgAA55OoxTexY%2BM0M3DSnwLV0Z10qBCIMv8jMYABOMy2yCCJODwFjCEIeIuIfTSwEEtEnJlMSKzclc1TXDUGTXUDwL3XsY2IONb1s6YsPsqdHLw2K9Pi39EoAxgNS1NKqN8-zMmy3KbLXcKipwkqdLKlz9MqkikrtECWTZFh9joAAVNYAHVfGtfLcwiqKJVK0s%2Boq0l3NImrG3qncggIBxWQAETkYgSACsLHF4zB%2BMi7Ti2cwl2Qk7ahpqjc0v1A02AiSbTAtJNcykUwexYOb4CtLj%2BQdTqtO6p7epe4kBqk5LgO%2Bw0WQiYgDUOTJ4hYHskwNfBEFIUhUK4wC4b4hy3xi9aUbeqrpKwDUKKxg0ACUFB7eBIehzdYeWx6P2R%2BUEsG6rsA1OTub5uA8HgFJ0kyNNYi4jUxcRiXmcIBxZGOWRTQMHsQpYALJti6X0c1Uy0qVgXdSNk2zYtomrpAswB2ePAAH1D2IKHrV1xm1rnKW0Y8uXvO5w66nqfY8BNMEhYWtdRfhh69ZE57o62tm13tECfsThoU7T5JUlUzXCm18OhKZudDeN4hTa0c28Et63bZjnbsFtOqmEgCvk9TsgWFd9vO8Qbve5HH3TD9gKg5D6Gm%2BiyPvULoN3tlrBbQjbmADUQ3bCx4AsSwM5hum7oZ5ud4JPfiwP9nMFtPbR5%2BgxjsUKhS%2BrIb53xFg-DA90VrCSlAXV6dtY5Hy%2Br-Q0J1YAsAAOLGFJuTSmqEwFrlplvVaPVmauQHh9IemNf5uw7qads8ZoAAGt2x1GYcYUgE0pCDnov6VIbUmB2XpsVCOpCvz9SLjLT%2BGBbRc1HmoRAh456dhYMeC0Ns8RnVxnQXwqEgismUurPASJFqFWEV1URSMyESP3sXJgtoFajwANKIEQDgP6AMLQsm4UODMvI1xCMfiI5%2BYjd7wIoYfL%2BjsUEGmBsCUwBCmDZ3MQjSx%2BtxGbVsVIku8dR6cisPIQ6lhUgWghogNIuoED%2BMEQVW6kCn7b1CeVH8kj7aMHrKlUeQRTaWDoP-OggDNCcl6UTBwvZJqwFGqUom1NTF1OFA0khViMktKyW07A9YR5Mm6QFOgMyyQHisIY1SWiLC6NYupWpxCYEemRuQ1piDMD1hPjQ9ufijSDjSPAeIDFYBUysAopRppLlLRztAlucVVnvzse0n%2BTITpkHiGkeQcSyCmCkPUdkhoQVmKCRYkJyzvQWngGmPxUgcTyFZtkpg9ZkFMhTCS9MwKfZ4FkBESA1yIXNKpesrA9ZqFMhcW4qZ7IWSsPiAMzONTQUpNzmk-OdybHQupe0uRTIGESqYX40gh1YDHVVhTJQM93ZaBwb2PBFzNwdVleCl%2BG0oVVg-muesjj1WJAsogBFpBoB4AuhYImLwoI6M0GdaAjE6g3gEYwQJ9TgmNMJdyhBg8%2BXRKZOS31ihKlIBxfMsAUDYRCEZISUgBgqbIg0l8IAA)

#### Code

```fsharp
                promise {
                    setItems [||]
                    setSelectedItem None
                    setFetchingItems true
                    let! items = Api.fetchItems partNumber
                    setItems items
                    items |> Array.tryHead |> setSelectedItem
                    setFetchingItems false

                    Seq.tryHead items
                    |> Option.iter (Some >> setSelectedItem)
                }
                |> Promise.start
```
            

#### Result

```fsharp
promise {
    setItems [||]
    setSelectedItem None
    setFetchingItems true

    let! items = Api.fetchItems partNumber
    setItems items
    items |> Array.tryHead |> setSelectedItem
    setFetchingItems false

    Seq.tryHead items
    |> Option.iter (Some >> setSelectedItem)
}
|> Promise.start

```
            
#### Problem description

There should not be a newline added by `let! items = `.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 10/27/2021 20:15:01 - 95833f5b00020e03571e8e58060c52a7436435c3

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by knocte** [comment]
AFAIU this should be marked as bug(stylistic) instead of bug(soundness)?

**Comment by ribeirotomas1904** [comment]
I will try to solve this one

**Comment by nojaf** [comment]
Hello @ribeirotomas1904, thank you for your interest.

This one is a bit trickier to solve, I believe a first step might be to revisit:

https://github.com/fsprojects/fantomas/blob/b742103d512a22e7ab003784d0f40ea9361fb5fa/src/Fantomas/SourceParser.fs#L977-L984

I believe this active pattern is a bit too strict and should be more something like:
```fsharp
let rec (|CompExprBody|_|) expr =
    match expr with
    | SynExpr.LetOrUse (_, _, _, CompExprBody _, _)
    | SynExpr.LetOrUseBang _
    | SynExpr.Sequential _ -> Some(collectComputationExpressionStatements expr id)
    | _ -> None
```

Because of this change, you might need to update 

https://github.com/fsprojects/fantomas/blob/b742103d512a22e7ab003784d0f40ea9361fb5fa/src/Fantomas/CodePrinter.fs#L1633-L1643

accordingly to:
```fsharp
        | Paren (lpr, e, rpr, _pr) ->
            match e with
            | LetOrUses _
            | Sequential _ ->
                sepOpenTFor lpr
                +> atCurrentColumn (genExpr astContext e)
                +> sepCloseTFor rpr
            | _ ->
                sepOpenTFor lpr
                +> genExpr astContext e
                +> sepCloseTFor rpr
```

I hope this helps.
