### ISSUE TITLE
Question on line split settings

### ISSUE THREAD

**Issue by dsyme** [fsprojects/fantomas#1933]
I was a bit surprised at how low these default settings are, particularly `fsharp_max_value_binding_width`, though all of them really
```
fsharp_max_if_then_else_short_width=40
fsharp_max_infix_operator_expression=50
fsharp_max_record_width=40
fsharp_max_array_or_list_width=40
fsharp_max_value_binding_width=40
fsharp_max_function_binding_width=40
fsharp_max_dot_get_expression_width=50
fsharp_max_elmish_width=40
```

If I have a line width of 120 or 200, it seems odd not to allow use of the full width by default.

We can always set things explicitly, but I'm wondering what the thinking is for these defaults, e.g. 
* why not specify them via a multiple of `max_line_length`
* why not make this multiple 1 by default
* I assume `max_line_length` dominates these?

**Comment by nojaf** [comment]
Hey, the original implementation to determine if a construct is multiline or not was based purely on AST.
When we refactored this, we started looking at actual character width and introduced some defaults. These weren't based on anything really.

I'm happy to revisit this in the next major.

**Comment by dsyme** [comment]
I see!

Could we have some input on this from the G-Research folk? cc @nhirschey

**Comment by nojaf** [comment]
Tagging @Smaug123 and @jgiannuzzi

**Comment by dsyme** [comment]
I'd actually be keen to adjust these upwards to 4.6.  It feels to me like the settings really are too low but perhaps I need to look at more code.  

Anyway I'll trial a PR to raise these to something like:

```
fsharp_max_value_binding_width=100
```

and we can discuss about when to integrate.  I think that's the one that just really surprises me.

Thanks

**Comment by nojaf** [comment]
Hmm, I guess we could update the existing default values for 4.6.
This will have a lot of impact on the output that 4.6 produces versus what 4.5 does, so we'll need to move with caution though.

**Comment by Smaug123** [comment]
I agree with Don's suggestion, it sounds sensible to me. I think we already adjust the let-binding one up to something like 100 anyway (can't remember offhand), and I would be fine with simplifying them.
-------- Original Message --------

**Comment by dsyme** [comment]
I'll close this for now, though we may return to the question as things progress
