### ISSUE TITLE
Explicit call of active pattern fails

### ISSUE THREAD

**Issue by dsyme** [fsprojects/fantomas#1937]
Explicit uses of active patterns as first class values fail, e.g. 

    StringPosition.(|TrimStart|)

produces

    StringPosition.|TrimStart|

https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBlALgJwJYDsBzABVgGddNdZ8A6ACgB8AVPAWywENtNGBKADrYB%2BSABpwUMokxUiZVGADakiKAgaoAEkwBPAA7I0kApnGqNkLQDdOAGwCuR5Rc0AGCZs2QAkviT4mOi4AF7Inl4QACyuYAC6FgC%2BEWqxVnqGiiaB5pFWto7OKpEQAIwpXpAAspwAHgAyBIj1iESYABa5JaUATG6xCZrJFuqVOgbOkABGsLB2Xd429k6KxSU9Fd7oiGy4cHY0AIKYAKL%2BAPIAZo344bEQl-bSA0kVo4sZkzNzC5ZLhat7mAAMybSzofScaCIABCiEusGwiGI3E4bBkiGwv00OCcLyGbzS40yxm%2B8zB%2BWWRSBUTBEEgEKhsPhiOasAA7pjoJxpH5rLBuVQaNiNLjEPiNMNNO8-p8smSRZSAWg1pEAKx0jCQ6FwhFIgCq%2BkM2G5vPw-MF1FEmsedmekUGksJeWJX1m5KJBRWKqBADZNQztcy9YgAMJ2HlkUM0Mi46CYREih5PcUO14jIly0nuxX-b0uEpgADsAcZOpZSKqOymmKTYFt9q8jogUo0MvprvlOYpeephYAHKWg7rWdGDtagQ3U0309LMxMuz8e16%2ByUAJxDpmHS6YTHRthsTh1sUSlvOsZZqAK5dUwGF0oeIGBpkjpHbXb7YU2lOnsCt1Iupe0zdp6t4%2Bve5RPmWiDbru2DvnscxfkCJ5pgSGaAQu2ZLqByoFt0GxPn4ASYOc%2BCsLoADqlCdN%2BdrTpozZ-ueHxYVeIEuiud7dKCUFBoc2CwA4-gACKIHYuC7HBx7YHiaFOhhF5sdkZg3nhqpeKUtJPjUtQ%2BJczDtK0Jz0eg7SIpg1HwB0dZRP08lnoprEklApi5lx4HdBqOl1H4ly4LU5zGpwCbYCctT6EiZAUMhhZqvZM7oXOmEuSp7lgfhkSlP6Pm1AASogcDYPAVk2Zqdm-v%2BYDttoQFuWp%2BYaZopQlrlBVFfAAByDhsDW2BXD4u5sAomqlJVLGyspbAOHYVASbcABiiKHrImLMAuDWrllg5Pu1iLwFUM1zU0S3YCt0kBtA7SovGmIAPrsrg1mdONTmTal9W4Y1QKlBuuUCdgnC6Oc2CNLGpW0TSCWMbObbzh9OSbdxkR9AGukA0DINg5g3W9ZiA1DSNP2vclSmpdNs24PNiCneda0bV9W1eD0kGFpAGPA6DuCxodlPU7TIUXU%2BV03XBD1PTZJNwylkyfZxGVNRoPSEWzukAGpUjCBDwAQhAQ7Z0MaExVU1ekyly2MHmZczvGq3UC3CfGVpa-4uv6%2BVhsQMbE0dnViOM8jzPaXbtQibAmAAOIyOFkWINFVru0C8VSwBZNujh8vqUCPTearR1U00MIHNAADWMKA6XMhkGR6BomGcw9ROhZTin1Xw%2BnHqZ99hY9DlbOdYg7LU3CmCcq062GGJ-n4JQVqHP4VZ49gRPNz%2BDnMW9vvKdeAeeSjrVswA0ogiD6PphmtH4tfojcdyr-Rrem52xgW4sVuKxAPQ7SHJm7GQ7SJ0LBVdeJt26Lk7pbBW2c-ps2CEQOwMFsCEB6q0SyiAphVAQHfEoLcQE%2B1qtvDikCs6FmBI%2BNmhwJKEHwA7fATsaDBGoSFBwSJmCwGIqgkKVo6y4MSgpUmzkO7pRISUYErMSjs1mpifAXDrBsiIIvPqU8CCzxjDwtefDHICPekIpGe8vDAhVhI3mVBb71DRFMeAnBwzkF1gPIeTR1EPzwZvAhqUd5dyZpoYEtsJEiW5pwKYCDf7c3aOgXQgQ6hOMbDDJK0s05ZFaPAK4t8sC6AQcI7uojg4SLOMk64jjLrYDsJcSAj8wHYQgW-KBpDc4SOPqfDhgQ-Dl04HQyG98YlG1hqnQR4DMleI0MCPuEii5tJLrfMgAkhL%2BAHrGRAB187UxjlFGK%2BAV4lFQpoje2it7uKIdUkRkRgQH1GdwV8iB-FkGgOwAgIUFn6hnjQMS0AIyAyFE3HBGjYn8PiX0ypAzA7eO-hIrAeB4yYKQNEhi3ShiSDiBEEwZAFoUEUC3RIQA

#### Code

```fsharp
  let (|TrimParagraphLines|) lines =
    lines
    // first remove all whitespace on the beginning of the line
    |> List.map StringPosition.(|TrimStart|)

```
            

#### Result

```fsharp
let (|TrimParagraphLines|) lines =
    lines
    // first remove all whitespace on the beginning of the line
    |> List.map StringPosition.|TrimStart|

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 10/31/2021 14:52:39 - 420ef5c20d32aa6c8eacd6dd63d67bb3655f257e

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
I was actually hoping to address this in the parser and have the parenthesis inside the syntax tree.
See https://github.com/dotnet/fsharp/issues/11893
