### ISSUE TITLE
Comment in middle of pattern fail formatting

### ISSUE THREAD

**Issue by dsyme** [fsprojects/fantomas#1939]
Problems formatting this:
```fsharp
let f () =
  match lines with
  | head ::
      // Comment
      tail -> 1
  | _ -> None
```
Result is 
```fsharp
let f () =
    match lines with
    | head ::
    // Comment
    tail -> 1
    | _ -> None
```

https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzMAFAJRgC8AOgE7kB2EAtgIZbQAWY6AljYgM5gB3TllZVaEAD5hWiRvDAoUYuhFUB6NWADCsevUQ0sy1aqyNO6MAFoAfGACMxsFID61uwDlYPZZAA04FC82FjcAOa8qGAA2oEQoCYQkAAkWACeAA7IaJDcWP5xqikAbozoAK7ZMYUmAAwBiUUAkjRIhgDKnABeyA2NYAAsNWAAuoUAvn3xwynpWVG5hgWNJWWVUbH9DlOJkACyjAAeADLciMcGYSLL-fYATLXDYyaThQm7qZlVkABGsLDoG4mVYVKqbfp3HbA9qIeicODobwAQSwAFFWgB5XCnHhAxK4MrBJ4THbvYGfeY5P4AvFJZKlUEbYYQADMUKK7QyjGgiAAQohcLBKIgAAqMSiMfRYRCUWmmSiVYkvUkzCnfamA9kg9ZocGNAbspKc7l8gVC86wAQy6CMYItYqwG2hbxyiBYBWIJWqV4mMlFNULDVy7Vg5lgACshqgxp5-MFwoAqhkspQbXaaA6nZwXVGCegiY1nt6VSsA1T-prVQyddUtgA2KOQGOm%2BOILToW28HQ0Xju8rQLBC114Qmewskt6qubqivB%2BlrUNbADsjebcfNe1hPxlw7zBcSRYgPtUfrp08Ds6188ZurDAA5V1zY2bhTpETRd6OvUeSx9z%2BWaSvatF36ABOR8TSRXBpUoHQ9EYYc%2BzHA8J19KcvgvQCqwXJktnseowybJ8W3NGE4QRHMwz3ZCTEPMBj2mUt-ygIMgJw288PsCCeSgmCyPhAFKK2JDv3o39yWY35L2wm9a1uSFCJaNosAxGgABVKDSAB1YRWE-fMaNUOiGLAU8oDLFjpNLYDcNuNlCObJFKFgcpWgAEUQLg4RgxCPVEkyzNmDCcjyOcbI424DUIg5DiaXA1JkGhUQM9pWCFLAdPga4owGR5x2VScmOCqBQrY2S9USexI2io4WlwThDgxFNmCFVFDgyYVeF4bMPyjcM8pQgq0KKykSqWMqawqkx7AbGrDgAJUQOBKHgTLsrDXL-PE-1JNKmTJrDewVzmxblvgDxynobdKCxJppXoSIo3sLbCr-YrIHocp0FCLgeAAMSFJgsBgtSMImkDGnsB9CNOoV4D2L6frOAHKCBnzGzYcVuRglwhCyvSXuGt7RsWfJwdsyHwLmpyJTSDFKFOXs1r0nKBto1CT3Qkm9us9i5MaB5GximnGDphnOF7C6rplW77sew7Cc5kbvk%2B76LGRwHmBBsH9ohxI7i4wiRbFxmsARtXfsQFG0Z3DHWCxgcZVxzh8cgRXGOJ74eY%2BcL%2Bf1hStn2I4ADUF15bh4HCZnh02-Li1eiT3u98lfam1Q7nswOYr%2B1yBx68PWijl31q2WPBvjonE%2B58bdYp-Woqzo43NgLAAHFsDajq%2BG67xo76tmjI5j2q5nLDefKsM7mqrPEfVnheURaAAGteQlZfsF4VT2klNsAUu3qqK-OOfwTnb3tY2uIoF2bA48RABEt-ksCtAxQayDz6poYQeqRVpN2lyg8stjUXdqZLmo9KzjwOlsO4x1A4AGlECIAyHFBKBgWjb30DiXoh8DKgMChZUmYU%2BZpwgHcaGjdDjJThLwVgfcNoDwgMZbaZ5z5WR9iQyeVNA6dBoGETATkwiXQMBlRAPw9gIBwcAo%2B5cT6VzPiTC%2BUC9YmBZARQOSIuBhBoDnGgedvCdG0cwcowo1KwCUiI5gPV9L7nZkNJWntMKQI4RPLYLJDYaO%2BjKGgVjigWj4f-a6H9uDf28EA-oIDj5iVPqwxR7CU6cLcQHfo%2BxZ7YOOJKH48BGDtlgN1Phd8H5nBsYZJhQ8wHKyccQ1x-QWSZxSW5CWjAfiYGoRLVg7Q0iGCOCU-B4CFgGHgFibB7R0iYGqdA2pDcUnoiGdiYpGNKDoFwG7KJAV%2BkAWcQkmpjQWTTxSYg5BFjDAtFXowPRLNcG2MHvY4eCiIETJUaoFkN8UkL3OUvbBvAnIuVaHfXsiB4az0tp3TqPcey%2BUVGslh5lJJKJcZM3ZcC3ninXMKRpvBoCUE4HCHx0p4AJi-t4Dy0AOwSmdAfaReDoUxNhWwseCKnmsgoSk0Z2KBwSKQL0tZgQRh9FyLwP63UoggPGEAA

**Comment by nojaf** [comment]
Fix available in [v5.2.0-beta-001](https://www.nuget.org/packages/fantomas/5.2.0-beta-001)
