### ISSUE TITLE
Strings containing spaces at end of line change meaning

### ISSUE THREAD

**Issue by dsyme** [fsprojects/fantomas#1941]
If a multi-literal string contains a space at the end of a line then it changes semantic meaning when formatted.

This seems wrong, since Fantomas should never change meaning of source code, but it may be considered acceptable in the balance of things, especially if C# and other languages would trim spaces even in strings (as a general editor setting)

In the example below there are spaces at the end of the line within the string

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBnMAvGADqSmkCGVFEJATsQHYBGr5ZkkANOFLtlgCWjAOa5UYANq8IoWrUgASLAE8ADsjSRhWbjIWKAbhXQBXTVP3yADD3nzIASUZJGWAMqCAXsjv2IACxWYAC6%2BgC%2BfrLBSqoaEtpuev5KxmYW0v4QAIxR9pAAshQAHgAywoiliKJYABbJWdkATNbBYfKR%2BnL5yuoWkMywsOgNDkYm5hKZWU15Du6IALaCcOiwjACCWACiLgDyAGbljL7BEAcm-G0Red1jcf2Dw6MGaZNo0-4AzHMK7moUaCIABCiAOsDoiAAChQ6BRFthEHQXvIsHRzNcOrcYr14loniNfqkJhkzmAAr8IJB-oCQWCIZVYAB3JHQCj8ZyGWBsoTrFG0NEY-ztWideR3AwPBIE-nE9JTMkAVkpUBpQNB4MhAFU1Bo6GyOYwuTzBHyVRd0FdhTcujipfihoScW9SVkwAA2FXUgHq%2BmQgDC6HZuH961wgugWAh-POl0QmNF2JSuMejtl43lHzJAHYvWq6ZrEAUlswkTGwBarfYRRAxbQJVSU9K00SM%2B9LG6ABx5n0FhmhtaMcuV%2BPWrG25P2qAy1suhVugCcPdpGwOWCRocWiwo5cFo%2BrNvFdr6zees5J88atjJ3tpGoZC2WqzNZJHCdrSZ6U4GLedF6zbrZLkN75qu650I%2BKzDC%2Bbp7u%2BYB1tEk4ng6Z5-pmHaNLMN7OK4WB7IwAAqdAqAA6oIdTDnG8GIWADZQE2qFOsmc4AY0Pwgb2Gx0LApguAAIog6CCMs4G7ui%2B7yDWCGfvcKFQDo6asZh-jZBSN5FMUjgHIRtTVNslqIO4tQQlg5HwJRKoBK0Y6JhOX7yYkujnhhnz2NkyoaSUzgHIIxR7HqFBRnQ2zFGokK4LgppDiqio2Qe45HsheIKUkLntm58jZJ6XnFAASogcB0PA5mWWS1k0bJkqOYp6Wuo0ua5QVRXwAAcqYiylnQhyOOuiziCq2SVfZckpZAiymOgQjCScABiELblg4GESedWXqp3Y3s1ELwAUk3TRU810ItYletAtSwoC4EAPpMoIFn1MNSUOWNtXoRlZLZEuuXcXCKh7HQ5ThqV9RWfFUmHvWx6vWl731f4LReppv0UP9gOCOG7WdUiPV9QNn1PVDyX9BNU2CDNiBHSdSIrfEa1sQjwFupAKNo0DWB7WTFNU0Fp03udl2Rkit33ZRhNIS9-RvSx-4qfYTTYczmkAGoksCwjwMIIgg%2BWFW2R%2BI3VTDzlw%2Bt8scUrJSzXxkbRerLhazrYPi3R0NS7DMuuWSTTqZbxT8bAWAAOLYKF4WIJF0VO0q4O0NJtH0bEjkzqbDPy55Sv7eTFTAms0AANbAnCBfYLgBHuPCiADh1MWvtR%2BsyYbjbfinnsfW6TQ5czrWIEyFOglgLLVLTiCCb5jAUdFGwuMW2N0Pjbpvg3Cdu6ezE9MpmW0E0jXMwA0ogiBqNpunVM4FcIscpyL-XCV2c9o3uybbfw-Lm1%2BwZyy4LU0dunrd8GwfkbVMaEX5m3kE0b6zNPCiEwNxEQHVqhmUQMwAoCBr5ZCXgAxuQDm7J1-GAtO8gvjXmZhsYSIhGDW0YLbdYnhKFBVMJCQisBcJIKCtFKihkXaJ0YtOAhG9ZZbwgF8JmWQWZTSRIwDhhhGSiFnl1MewhJ5hi4VWCGiUiaSzXkpIRZIviK3EZzIQV9SjwmYPACggZYBRVED3PuFQ1GSTjpDCWj8dH0zlsQi24j%2BIYwoMwTAn8Ma1HcCoNwJQnE8NXloao8BDhX3cKoTAuivZui%2BL7cRux4lHEcWdOg6ADiQGicTDxqcvG0C%2BBncRB8j5sLcM4IuFAaGgzrtw5eVU8FjVboItJWQvhd3EbnZp%2Bcr64G4rxFwPdwyIF2lnCmYcIpRVUSqOCHSm4MRbgIsYm99G7yGbCe8kI-G4GgHQESwggqzK1BPdYgloBBjhLyWuN92nYJXqUpiqT279PfuIpJ5zIxoKQFE5evAQh%2BG0LgWaUUJBvnCEAA)

#### Code

```fsharp
let s =
    """spaces-at-end-of-this-line   
bbb"""
```
            

#### Result

```fsharp
let s =
    """spaces-at-end-of-this-line
bbb"""

```

The value of `s` has changed
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 10/31/2021 14:52:39 - 420ef5c20d32aa6c8eacd6dd63d67bb3655f257e

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by dsyme** [comment]
Note that as a workaround, normal (non-triple-quote) strings in F# can use "\032" as a space character

Triple quote strings cause more problems

This came up in this change in a test for FSharp.Formatting

https://github.com/fsprojects/FSharp.Formatting/pull/716/files#diff-3d4e1b6d62530b5574130d89d1068004861cb3525c7145eb9f4120426a5a3abbR168

**Comment by dsyme** [comment]
I found another case where fantomas formatting causes an FSharp.Formatting test to fail for the same reason

https://github.com/fsprojects/FSharp.Formatting/blob/b667a4bfb682760d8b9023ef261f3217a01fb6ce/tests/FSharp.Literate.Tests/LiterateTests.fs#L882

Here a test is testing the exact output of formatting, and the test result expects to see a space at end of line on one line.  Triple-quote strings are used because they're very convenient for such cases

**Comment by dsyme** [comment]
(None of these recent bug reports are blocking, since I can adjust FSharp.Formatting either tests or behaviour, but they are interesting cases for fantomas)

**Comment by nojaf** [comment]
Interesting, I believe there might be an issue when processing the F# string tokens.
![image](https://user-images.githubusercontent.com/2621499/139644809-89304cf9-cfa1-40f3-8f5d-71e074ac25d4.png)

The last token does not contain any content (only three spaces) so perhaps it is not picked up in TokenParser for this reason.

https://github.com/fsprojects/fantomas/blob/8f00ea8708adb1f665edeb42e0efcddfa5a11adc/src/Fantomas/TokenParser.fs#L589-L606

**Comment by nojaf** [comment]
I found the culprit: https://github.com/fsprojects/fantomas/blob/31fc9494d1ff3248ab08555efcdb26496687ef5d/src/Fantomas/Context.fs#L319-L326
We trim each line here.
This will be a bit tricky to fix as we lost all meaning of each line by that point.

Doing the trimming earlier in 

https://github.com/fsprojects/fantomas/blob/31fc9494d1ff3248ab08555efcdb26496687ef5d/src/Fantomas/Context.fs#L94-L106

is also not that simple as you don't know which `Write` event will be the last one before a newline. Nor do we know that the Write is a part of writing string text.

@jindraivanek any thoughts?
