### ISSUE TITLE
Offside code created when base constructor wraps across lines

### ISSUE THREAD

**Issue by simon-reynolds** [fsprojects/fantomas#1942]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6dYDqsBOA1gM5gCGJiAHgA6LQAui8AOnswHb0CetYAygEcANn0R4AbmIDiiWAFtE9PFwAqPRAFlS1agEt2AcwA8AcgOyFSrmADuAC0TswZi4uVgUAPjAz5brt4AFOZ%2BVqISutCIRCgAcvREvpbK4eKR0QA0YET0%2BIhqtGg5ePoGAJRgALysHBAQ%2Bg4l9Px2%2BPSxpAqmIclcWYJCAEJcjESegYEAEohCtHhEAHTQeIikjADCsOySeIx4YD3%2BqekkOXkFiGVZZysXZTXsD3VgQopguomyBnjadtbVbCczzqfCUpQWAFEBABXUhCIiBG75dRZZiQELfX5cNH9MGGTZyaikEpELYLADyeHg%2BjhAEkDOw8utyJcHk86rAdiUkGAAPq8hbrIRbRCBIk-SxiGJgABKMzWui2cIuWh04LlQgVSqEKu0ekMAAViZ1FFKKgDasCIAAzUi6IQ2XT0OxgNEaRSteBgABGCGsujwK1e4lInDAuR90IMaLZgMwYAAYnb4WAALRgRmMcMOF5bcz7b0ssDQTVEEjsE3F0jQoilbOIYtbYrQhj4cOwWw-agPbi8AapaSuKy6tWGbpD9z2RzOQ5WDzeJL%2BIKzlJiNJRGLxT6hVcRDfXXK3dRFPHlKrs%2BrsRpO2Xy%2BiKitCRfD9Sq-XGFw7vr8YTDUbjKYZjmRZllWDYth2PYDgnLhjg3bJD2RWgrgQ851HuQELxeN4Pl8TFqD%2Bc9AStCBQRKQxIRhOEESRC5UXRL4uz%2BHF%2BFPAlxQ%2BMlKWpR96UZFZmSIVlMOIjkuV0Hl%2BUFYV2FFcUTT2aUNS1R8R3fBZlPvbU1NKI0JVNeZzSw55bXtR1nVdSB3WdBAfT9d5AxmRAQzDCNvSjGMRI4SAMnAKAhPoe9DCIVAwAAbT8iBQCtSAABJe2QNBIH0egfMiuo4pDIRoUS8L0ueAAGXySKgWl2CQTg%2BF0AAvZBipIgAWfKwAAXXSgBfeqouauKEtC5LODSmLYqynLQoikqAEYuuBKzSEoAAZfREAWxwDGdIaSMmgAmArmra55OvS6LZvi9R%2Bt9WAhE255MrhMa0Amkjtpm27RDkSIrq2ABBegIXK8lrSW2SbuBW14UQfaOpmk7brO2gLtgK7QYgO7styp6rQAZlejK%2BCJKJBkQa08j0hSxBRuolByqHDphnr4dyyBLuu3G0YevKSoa3HUfx0hCeJvIFtgGwxGgFkyvEWBxa09hKYganIatA66iO55YYyxnEeRtmRvujHmogABWHmoD5gWSZWABVHQxYl7ZpZU%2BWwHBoTadV%2Bnhr6pKWcp9mDZKgA2U3IHNxAictxAhXIIhNnYZtWzwZ3XaV4EVYgNW6g11GtZ9pHWYZ0aA5IgB2EOw4jvJ3Tkb0KdNlP3Yzz3Tu9qBfd1ovxsNsAAA5y4J8PBYEr65fr6jU%2BedOwEz7qvfOvOdcL-Wu5KgBOfv%2BcQb7rT2Ak5FIZ3Fcb6fm7h1vmfzv29fRletqK7vQ4HyuVnez6ZOT8fj5nsBs6gXO28vh3Zej1u6TWmg-MO289ivzgO-U2R9lbQ2Ogzc%2B7cl43xAVNF6D8yoVXoOSdgKhlDYCdHYD%2BEMv6n01qgwB6COaY2BJNHGECB7fTwLAaE5UAAiMxdAfT2IfPANNEF02QXPBGSUUpX07pgra3MH5aEoLSa0KgHDsAhBDPgrRdgkPgBtU2DU9oiI9mIlu88oBSKARgzmW0TYKPmmVa0uhKDkjmGsfAEIaArDLA%2BZ2RsjFpyQerFB5iBqpSsfQ0Bwd7GUDlHAKkuj9Hd0MZQ0xZ9QmWLocXK0k0y4xLifgeAsRoQ1zEIDWkjA5AhVNpNVJwTxFMzkNCIQ94hDLQTPgfegUxAXGkcAmxOS%2B4PwKVSDQzTWntM6WsARIdoB2GNAwMQvJHR6LIXUrOISJEWMGhE7JjD14xLYT8LglIlo5ESWQgxATJ5BI2Q0-qmThoyIGcCXaIdFFHNICcvAZz2glNrngcplTqmgPWbPMxWzIBNJafaSZeAul7F6bs2%2BVptrgJKpAT53zfljJhW02SHT4XTLrg-OZCy9jLIkhtMFP9NlM0eadZ5DDnjbWwRixRAA1fWgx9A8QMBc52KTjFNzSdQjJOyskotecw9l80EycIYA%2BHl5VSgCquTS3%2BvVxXhMlbI1F8jZWUC4bAegMg-peOiLWLYaru7%2BI1XS7WBcnn9OZXUbadj2XjNhbJQYwpoAEEGD8f1igiAEL4CaTY2U5Cj27g3YVJ9RU5xoYvZ11jXUQG2tEjFsREA2HxYPegotHAXB4U49gToHzfXKtXAFIKSpxsCaI%2BpEKmZoNTZEkq208kYoANKIEQNQZRqjHBlXDQoYGdVY2f3jd-TV-8wl9LTd3baQzDUaI%2BkQOwNqubXLqFPWdDqF5OsZS65dByMVVUMK8NhBgSmOHoNgRA3oNAIEnfW6djaTHNvSZCttJ6l0lSxvfDF302kMnlewRVWwqoMjWNCW4sBcH3qdmPChM6qFJtCX%2BuGTLu5Y3RSRTFLSxAVnvJIYWhga1iFLfoCtTZyFu3Q4mv%2Bybj04dPYBtlhHcX3gnQtTo3p4CkCFLAWshgc15uWgxiee7bngp-a22h7a9nPCxjKwjXCPikG9K8ddHw7B8C4Jwea0n7X3KSo4eAgMJ2gi4K8RdHaSJYwNYR-6VmgZSdmXgIQ1pIBmZbY6hzKm6hYw9YRvtA6kOcDKoG0MczTNMe-WK39Sn-2OexlmwjvrQwEAnUQNhHDyo5pyEwHj3rECeOoN4q18dBHCM-SKpLmGUsprS8FiAWNu1ZeJM-RAmmiDLD4TSRg8Arblq2DwksxpZYJYawmprLGsOpfYwBpzq7CNkUiPQF9SBZs3MOn5Fq9VkpEATLWUKDd2pAA)

#### Code

```fsharp
// Works as expected
type SqlServerGeometryTypeMapping<'geometry when 'geometry :> Geometry> (geometryServices:NtsGeometryServices, storeType: string) =
    inherit ShortName<'geometry, SqlBytes>((Helpers.createConverter geometryServices storeType), storeType)

    let isGeography =
        String.Equals(storeType, "geography", StringComparison.OrdinalIgnoreCase)

    override __.Clone(parameters: RelationalTypeMapping.RelationalTypeMappingParameters) =
        failwith "Method body irrelevant to bug"

// Fails - note the longer base class name causing the constructor to wrap
type SqlServerGeometryTypeMapping<'geometry when 'geometry :> Geometry> (geometryServices:NtsGeometryServices, storeType: string) =
    inherit RelationalGeometryTypeMapping<'geometry, SqlBytes>((Helpers.createConverter geometryServices storeType), storeType)

    let isGeography =
        String.Equals(storeType, "geography", StringComparison.OrdinalIgnoreCase)

    override __.Clone(parameters: RelationalTypeMapping.RelationalTypeMappingParameters) =
        failwith "Method body irrelevant to bug"


```
            

#### Result

```fsharp
type SqlServerGeometryTypeMapping<'geometry when 'geometry :> Geometry>
    (
        geometryServices: NtsGeometryServices,
        storeType: string
    ) =
    inherit ShortName<'geometry, SqlBytes>((Helpers.createConverter geometryServices storeType), storeType)

    let isGeography =
        String.Equals(storeType, "geography", StringComparison.OrdinalIgnoreCase)

    override __.Clone(parameters: RelationalTypeMapping.RelationalTypeMappingParameters) =
        failwith "Method body irrelavant to bug"


type SqlServerGeometryTypeMapping<'geometry when 'geometry :> Geometry>
    (
        geometryServices: NtsGeometryServices,
        storeType: string
    ) =
    inherit RelationalGeometryTypeMapping<'geometry, SqlBytes>
        (
            (Helpers.createConverter geometryServices storeType),
            storeType
        )
// Works as expected
type SqlServerGeometryTypeMapping<'geometry when 'geometry :> Geometry>
    (
        geometryServices: NtsGeometryServices,
        storeType: string
    ) =
    inherit ShortName<'geometry, SqlBytes>((Helpers.createConverter geometryServices storeType), storeType)

    let isGeography =
        String.Equals(storeType, "geography", StringComparison.OrdinalIgnoreCase)

    override __.Clone(parameters: RelationalTypeMapping.RelationalTypeMappingParameters) =
        failwith "Method body irrelevant to bug"

// Fails - note the longer base class name causing the constructor to wrap
type SqlServerGeometryTypeMapping<'geometry when 'geometry :> Geometry>
    (
        geometryServices: NtsGeometryServices,
        storeType: string
    ) =
    inherit RelationalGeometryTypeMapping<'geometry, SqlBytes>
        (
            (Helpers.createConverter geometryServices storeType),
            storeType
        )

let isGeography =
    String.Equals(storeType, "geography", StringComparison.OrdinalIgnoreCase)

override __.Clone(parameters: RelationalTypeMapping.RelationalTypeMappingParameters) =
    failwith "Method body irrelevant to bug"

```
            
#### Problem description

Fantomas creates offside code when the base class has a long name. Once the constructor parameters have to wrap on to next line it results in an indentation error after the base constructor has been called

When inheriting from `ShortName` name the code is indented correctly but not when inheriting from `RelationalGeometryTypeMapping`

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 10/31/2021 14:52:39 - 420ef5c20d32aa6c8eacd6dd63d67bb3655f257e

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hi Simon, thanks for reporting this issue.

I believe the problem is related to

https://github.com/fsprojects/fantomas/blob/8f00ea8708adb1f665edeb42e0efcddfa5a11adc/src/Fantomas/CodePrinter.fs#L4768-L4781

Here you can see that there are two `indent` calls and three `unindent`, which I believe explains why the members after the constructor are not indented correctly.

Are you interested in submitting a PR for this?

**Comment by simon-reynolds** [comment]
Hi Florian,
Yeah, for sure! I'll take a look and have one asap

**Comment by nojaf** [comment]
Nice to hear, thanks! A good place to start is by reading our contribution guidelines (https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md).
There is a link on there as well to some YouTube videos that might help.
And if you have questions along the way, feel free to poke me. Good luck!
