### ISSUE TITLE
fsprojects policy updates

### ISSUE THREAD

**Issue by dsyme** [fsprojects/fantomas#1944]
Hi @nojaf,

@sergey-tihon and I have updated the policies we use for "fsprojects" to clarify things like when we would consider archiving a project, see https://github.com/fsprojects/fsprojects-admin/blob/master/README.md

We'd be grateful if you check you're ok with the policies and/or discuss here: fsprojects/fsprojects-admin#29

thanks

**Comment by nojaf** [comment]
Hello Don, are you asking anything Fantomas specific here? Or is this more a general question?
