### ISSUE TITLE
Formatting power operator in code quotation pattern match fails

### ISSUE THREAD

**Issue by cgravill** [fsprojects/fantomas#1945]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKsAOiB2YDKAngM4AuiAtgDoBOl2mOYAYngBYCG1GAdAIoCusEuxIBLWNiI06DXCw5c%2Bg4WIlFuAEUTVRAN0TwACiLLVJ07BYA2iEmEQAPDNTBoAok%2BoAeAGZXYIgB8YAC8YF4AAmAAjNwALGAA9GBx8WARgRYW5CLQrPaeYADuoiSsFgA%2B%2BFjQoj6i0ADC7FZW4RFRABRJYACU6RlgnQD6ADRgY2AA2kTRANxgRABMALr9ALTBEGAW22DOotgkPriUkBp6Z5XViLX1TS1tkV1gAFSvfQPBI%2BOTM-OLVYbTK0XDbA5HE47SCGWBFK6gqrDMCbXbgnSQ06QABysDAORIeQRdAsUy8biO1AIsMOJECK2stnx7EOYE4AHNdKE0RAIccsQAJRCtPFFWDUKzwYlgiAABiSyWotn4ZjZuFpiHZ2gKpTAcCQkFG4CgRFsYmw7KIqGmxogoD2EEgABISAQsNbILTDbbts7dC1%2BMg0FMfXtZUaHb6AJLYJBHPCiABeyAjkZSobAKx9AF9U3aM87Xe60J6jt7I36A0GbWmYnmHZAALLsBwAGUOiFbOHZZXLaeiS1lGaze1zPvtDZdburkAARrBYFY%2B3tK1ZA9aQ7WlvWV3gKA1FxIAIIkCnwADyPnb2BTGYgPhapuHOfrE5XU%2BLUHni%2BXvqd-rXatNzTABmHdfTwDB2GgRAACFEB8cVEGMah2HIWxtF-PYSGoQNn1HV8Cw-GdvyXcDV3XYM7xScDHUg6C4IQpDWzhbRoHYU0Y10WB2NUbAsO2HC8MjEdtjHPY3z-IsSIXMiiIAyiazTABWWioHomD4MQpUAFUMCwah2M47BuN48R%2BLUh8rCfESX3HIjpI9UiBIooDqIANjUyANMY7TEEaKwOKIRo1CE6ASHFAT70fRB8LEwiK2IpzZJc-8qw3aiAHYvJ8rSkMbChZ0wyyYriiBxO2STHSSktnPItLAIy2sAA4cqgzSmKVEL-As6irJsh1RPKhLJ0c2qUvqhS3NrABONqGKPHxTBC8gciisAhNi2yCPsxKxq-Cb5PSqja2icNqO89rfKQvdyAPHr1v6rbBrsiSHOnZKf0m46lMjaJonmmDFtMW77okdbNrKsAKvzPaPvGr6jsak7%2B23C6YzjEhz2wAAVKkAHVSlYR7Su2%2BLdtG%2BGDsRxKpqa-swIunyj2oWB%2BFjLQrFEO7TAh3Dnr2IboZG999tLEhUrplG-riLzmwcKMfBx1gcDcazEDYcUSEJ%2BBezUuIhzJ4aKdFqnxcln7gL%2B1SLvlmN6gcc8DJEcUPGcRAiCIcz1uUw2Xp2t64c-c3vuR36HWiTzbZbAAlW5xXgHW9eog2oZhsAqqgGqoC9UPFKtiPsujhw47gah4GxfhyCK6hLyjMhyCtNTojTkWpLN8h%2BCsMQuZvJhxQJUwcY%2BvPpv7VqLtLhPGy7nuO376hB%2BKi68k4aDTGGEpdeJ1uTfb4Pc6R-PqOiObi5Z1CCHPah21IJPif1v3Bdeyr3oPstR-pyNBzllsL-YK%2BN9RCkErtXbQdcG5NxPrvQOlNg6d27qIXuiAF5L2oMPd0n9pYOiWADC6-9AG3xIDPRByDUEmGXrWGACh17aE3qIbekAYGvyDjOQ%2BtNLbUSWGjKh8sABqVZYKHHgIcdk991qpyNsLPe1UxbsMnFLcOewliM14S2Jg7NwrmSEbGUR4jH7MNhnAthH8j5j2-rLYuGghAAHFbBuyVJ7cy%2BjqK%2B0MRnN%2BMkaYKM4VuG2vDZ5II7LBfw0AADWsFULhNsEQbGeA0L%2BUXFXXqtYnruMzoWM2dUzFfxwVHKh2JEBFGQfBEgRREA4AwYgLQ9RsClHMkeWMBUwHUCgak0m-tyawNNsHbJHCw4F2UUXKhABpCpGBFbKxwDGeJ6Fry3naerdJniPTyPfIowZ2wlgTzUQ4NWd0iCsBcbWSRnTjbdP3l4uS-Tj5bjPlQhMFobAs3ZFXHA2tECzkbAgBZaY0lSPThk7Oc5Do3PMQ6EC50qFHi5uybAGjsBaIkAmOFIgVSIBxrADG7yRDexKksgFbdZFZNBT4gZ1EQJ4Ohd3bQ2BcX6BYhaZpNcamHHqWoEmBKznSIucS3ppL1m%2BNAjwtMTZAnzNbGhWc8B2ABVgF7C0hTikdk5QNZ%2BAcWHGM%2BtcsltzQKqNFRcIg7BZw2H2cA1ghAjgtlVQLbYQtAUrJLDgC8V4Ox4FdDYC25LawgUsVQs8l55nrRgBKHwTDCUyKzmLPpurwV7BAv40VYzEATNjO8mMkT2CIofn1Dp6qumap6Vc71erIwgXyaKkJ2awnzKICzNmsZCmkAMCQueN4HEey9hytSkNI28ujSS7xgqfWgWGVWzgeUlRGugDoO6dKyDwB0nUiQWhoCBVQnxW1yzWHatLfG7YIEdmio9TocK3yDT4rVfanMxoVipk9EQJgXtrRpOzEAA)

#### Code

```fsharp
open System
open FSharp.Quotations
open FSharp.Quotations.DerivedPatterns

let expr : Expr<float> = <@ 1.4 / 4.4 @>

match expr with
| SpecificCall <@@ ( / ) @@> (_, _, [s1; s2]) ->    
    printfn "Div"
| SpecificCall <@@ ( ** ) @@> (_, _, [s1; s2]) ->
    printfn "Pow"
| _ ->
    printfn "No match"

[<EntryPoint>]
let main argv =
    printfn "Hello world"
    0 // return an integer exit code
```
            

#### Result

```fsharp
open System
open FSharp.Quotations
open FSharp.Quotations.DerivedPatterns

let expr: Expr<float> = <@ 1.4 / 4.4 @>

match expr with
| SpecificCall <@@ (/) @@> (_, _, [ s1; s2 ]) -> printfn "Div"
| SpecificCall <@@ (**) @@> (_, _, [ s1; s2 ]) -> printfn "Pow"
| _ -> printfn "No match"

[<EntryPoint>]
let main argv =
    printfn "Hello world"
    0 // return an integer exit code

```
            
#### Problem description

Taken from a larger codebase where we're doing code transformations. The power operator `**` is getting formatted such that it breaks the code - it looks like it's become a code comment which may explain the error.

#### Extra information

- [X] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [X] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 11/01/2021 19:30:14 - c02b8d1dd32eddd947466d90022cf7a3d410c26f

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by cgravill** [comment]
I'd be happy to have a go. It looks like adding a special case then leaving extra space would work.

**Comment by nojaf** [comment]
Yup, I was thinking along those lines as well.
