### ISSUE TITLE
`val mutable` in signature loses 'mutable'

### ISSUE THREAD

**Issue by dsyme** [fsprojects/fantomas#1954]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAdATugdgegLADFZMxEAPAF0wEMx4BLWgcx1gGcrHoOwtcAN1oAbMAFsArlVoAjEYjAcAFrADuABVqYOiTAGUZ0ANYB5HFp2IAopkyk0s2LBGQANOCi6q3HCw6oYADanhCgEBFQACRUAJ4ADshokIw4VO6hEZBRwiKSScGZkQAMHpGRkACSOEhp%2BowAXshl5RAALEVgALqZAL4tYZ3ZcYmBKWkZrdm5%2BYEhrRAAjAPlkACytBQAMqmIW4h%2BVMqTC4sATMWdPZH9meGrMQkFkE4uJxU5orNo8wtnKxV9IhxDwXLAcABBKjWGqmABmOxwzU6EDhol0Vz6K3uHxGz1ergB0RmBV%2BrQAzESIJB9PFaNBEAAhRBw0iISy0cSIKh6d7lGj5TE3bFDR6jZIEvnUz55UkosBtKlQWn0pkstlbdR6aC0XTVQSwHXccFSiICxBCiK3SI4rJi-HOQmiklzeUAViVNLpDOZrMwiAAqvFEpgdXqcAajYwTUq0SIMa1rlaRVN7WNJUTpl85QswAA2T0qn3q-0AYREuo4pfBXEwkmgVFIptR6Itiaxd1FePTjtNWdlrtzAHZC961X7EGtgbJebHW5aINaIrbpd2Jb3MzLvoVcwAOUeq31s6siGPyuMJ8pJxcph5rqAZ53ZwcLACcB4ZELhPMw1fE4loZswHNBcwCXQZU3vF4NyfAcfnlRZSnlL1DxLRAgRBOBTxwICLzbK8OxtLsnh7N5NxdeDc0WZZkKLRAvx-DDQWwoCQPbYVO0gkj1zI2DtzJcpzk9apaiocwABVMFiAB1Rgjlw%2Bd2OTTi724h8YNTCid1OSlaLHCF7EkGoABFEBERgQR-Vi63wyJrzA29cTU8Z0nI59KNORVkI2ChKjhcTlAOax43Q1RMCoWT4HkpU2kuJSbxUpzxSgVJXL4nNTg9bzNmqOFGAoUwQ1oRtMGsCh4n9DgOGjHClTdOKCI4oiuOSly%2By3DLWkWAtsooAAlRA4EweBIui%2BVYtA8CwBXaIoNS9qtIEyJFhHXqBqG%2BAADlJHEGdMHhSoeXEAIlUWSbHLtKCpBEbhzKREhMAAnw9HEki3Lg7Suv3ZD1tIeA1kkG7GDuxAHqeqzPWgZRtHpH8AH01EYKLjnOxLLuc%2Bb3v4hD316gy6FiUxMB2LhRuOGKGrswjl2I1rMfSl9WguT0fPx2hCeJxguG23a9AOo6ToQ1HmtU1rrtu3YweKn9XtGLHOvKM4aNzSA2Y5kmqABoGQal57MCAmBoboBs9ARpH5OFmmWueenNPcz7Ff%2BXqADVs0ZVImD8MmgN3SmInsqaZuGDGJnlxnFd0lWfKIIyGxq92alSFhvYpy2INFm3Q4Zjyma8qPNmM2AqAAcW5MqKsQKqapT90-YgAOLtXZzHztj6loiM4sqjwGJaRRlTxMRljeMbkOHMfROUQE8dtq89FMa5SRaSh1eNb7HczOHqVc2xA1BB5kqDURADllxBTLynA5JqiEainXmdAUkK0%2Bm2mV6dNeFciM5VpVgBpY-4h%2BQCgcaoE8uSImRLmPCz8g5pmSLbB4i15RnG%2BvnCgwUQQqBrrmCa8UHJoybq1FuiD7btwgGcXGKt6h%2BAUAZFgO0DgRUQLINYCBIELGgXgwOr9SLvxIW3eU5IkIqwhOZNgMccBx3BPUNgxVJD%2BnErAESjDio1UfpeKmTUrYZ14QtUhgjlYLFVjdPQOBVGCD2OCFgd89rn1SFfGs6jbL%2B2punZeuiw453KOSJ23cgYQK2JyWQ8BaDlk4EnHee9dhOJgTwnifCPhINzOSSORjjJczkAoDBXNlD6FiGkTYMSuGN1ms5A48B4QQMMLEBQeiBHJLzkYmEFSETRMhpgEQcJICxOth47ODtIjki7kY-%2BiBAE1EYdUIetBJHkznk-YpBDSlEI0vw9eCxyRbyMf3GZxgIEcAMrAIyW1K48n%2Bj3YGuxy6VWqo4pUbEF4JSXujFZq81mfwiOSH%2B2ztBHn9Okjg0BMAWVSMVRA8AAyX3BKZaAFY6DGlnlA%2BemjF7aPcfEup6yKSoKMYYYFDZWFICKY8sCngugtBSBwIg1VAggV6EAA)

#### Code

```fsharp

/// For extra diagnostics 
val mutable showParserStackOnParseError: bool
```
            

#### Result

```fsharp
/// For extra diagnostics
val showParserStackOnParseError: bool

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 11/03/2021 17:27:28 - 10f599c2d2cdeddcfb2c00b915aaf45b3a5f9be1

Default Fantomas configuration

*Signature file*

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.
The mutable information is not captured in:

https://github.com/fsprojects/fantomas/blob/3e077f5debfed7670edff01847dbb2b4268ef627/src/Fantomas/SourceParser.fs#L1555-L1568

and then not printed in https://github.com/fsprojects/fantomas/blob/abd23589c668fd0fb71455b8ccf197d3cc6bead9/src/Fantomas/CodePrinter.fs#L923-L941

Something like `onlyIf isMutable (!- "mutable ")` is missing.

This is a good first issue for newcomers to get their feet wet.
