### ISSUE TITLE
Local fantomas missing

### ISSUE THREAD

**Issue by dlidstrom** [fsprojects/fantomas#1965]
I tried to format a source file from Visual Studio Code and noticed this issue in the log:

```txt
[2021-11-09 14:13:39.563] [renderer1] [error] [Extension Host] [fantomas-fmt] Command failed with exit code 127: ./fantomas "/Users/daniel/.vscode/extensions/paolodellepiane.fantomas-fmt-0.3.0/fantomas.tmp.fs"
/bin/sh: ./fantomas: No such file or directory
```

I have fantomas installed globally, so I created an executable file `fantomas` in my source folder like so:

```sh
dotnet fantomas $1
```

Now the formatting works (with Alt-Shift-F). But I don't think this is what I should've done. What has gone wrong or what have I missed? I don't see any settings regarding this.
I'm using macOS, with Ionide v5.9.0, fantomas-fmt v0.3.0, and finally, dotnet 6.0.100.

Thanks!

**Comment by nojaf** [comment]
Hello, https://github.com/pd29/vscode-fantomas-fmt has no affiliation with this repository.
I would recommend uninstalling it and try formatting via our new integration in Ionide.
The experience should be similar as seen [here](https://www.youtube.com/watch?v=1jb6K_HZaEY&list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K&index=14).

**Comment by dlidstrom** [comment]
Hi @nojaf, thanks, I kind of figured it out right now. I've uninstalled the other extension and backed down to Ionide 5.8.1 and now my experience is on par with your fine video.

**Comment by nojaf** [comment]
Thanks Daniel.
