### ISSUE TITLE
Idempotency problem when exception definition used in signature file

### ISSUE THREAD

**Issue by dsyme** [fsprojects/fantomas#1974]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAlgHYAuiATkQIY5gBiAygBZXkAOAdAMKzpsF5yHAAqsAzogASiHGwpiAOuQVElK2HKL1mrTjz4CKHAIIAjMSXJVoJAJIAZDg7WrlRAPSewAFSb4K5LDkYFYEEvBgpgCeYCR%2BYGziiAD6AUHJ5ATQTGAAZlhENgSwRAA0YADuTFk5YWDQNHgR0bHxieQSwYhEAObEiC4A2gA8AHKwAKIAjlg0BCRRANxg4-rtYSUAfAC6LogAHtCIbCTFWgxRpFT7E%2BSBwbC5YLCmAFZgAFQhVL2IaFa-FyQUrgKASEinXpiVBgQagiCgCBIqAAEgWchhkGIJGB8KRkBRADcaFhkGg4cjkQAGEGU-G2IhIUgMAgAL2QtLpYAALHiINs8QBfTkIvmo9FkqDY3F0gnEnCkmEUrkARhFlMgAFlrvZ%2BvZuj04jLVQAmKligXI4V4xEatFRDFoSCmWCwHDG5FykmS5V0k3qz0MRDoLJukrGEgTRkAeVyuqIHLFEFyNAkFqF6ttnvtjqgLrdHvxRO9SqTYAAzAH8QxEkcAEKIXJBRCiKzoRBkciF5GWUnpq2ZsUEiWY-PuqtehU%2BsvcqsQSA16yIBtN8iIeywCoUBoSBmE2ANU4lbtI3uIftI63IrNFkdOscnyeK8llgCsc6gi-rjebAFU2HI5A7oge4HlQR5ECeyapuedKWpeg6yjmkrOq645DsWU6llyYAAGwfgutbLj%2Ba5cDgVBiGIPBEBY5BYDYQRQXkMEXhAV5Ije87IaOaGPphz6wmWADsBFfsRq6IJqwamBQTEpjgaZwRmNoYXeea8RO-HTjhAAcolESuzY8Dgx4fvJimUvBbGIXaamoQWmnygJvqUgAnPpS7GLknb6OgVBMWerFgOxopIXZD6OSWL44SqNJloRS6GWuQYhnAJmQWZLFKQOKlhQ6KERRhTnaaqarxWJXmdilobpQFdGwZZynXqp%2BU8Q5RVRYJMX%2BvFDJMiQ0ZEN45BRAA6vMTByVljU5c1eW5vZ6FIcV2GqpW5VEcYgQFPAAAiMgECGnZ1X22UIbltmtU60qRVh0WqrO8Xavsti5L43QTApiDMEEJDjfARofty5pndZF3ZnZN0dXdXWqu%2BT3XAyuQEPs0aAeBQQTPsbBrpRZxMa%2BIMzedc2XQtUPLZ1LnIiq%2BEI-sABKiBwOQ8D-YDM5E8iVnBTZENXVKpB8St910iqIn00zLPwKMWDoDJ5CxrYZDoNCH4qkFIVgJx4oC5A6C4KcOD9HQQR%2BRCFDeK1t3OWWKp6fFUtBPAmqGwIJtm%2BBx0EdkrDWJ2yQVAQAOTZrfO3nrFN2iLsNi%2B59NbVYUTRuQuoWOzk1A1zSI81rOvDpHQs2yVfpxThWrXInVDJ6nYQkLL8sUErKtq3bYfgxHC0GzgRse%2BQ5udlbGLF6tfpleXVc12nJCuz37sJqb-de7JPssFYNgUIHwdGu3pP8%2BTRfQ7bOEmj15fPQAat6dbEPAxA9BnTE6dn-JNRxLUHziI%2Bi5SJrref1w6AFCKCUG%2BjJ76Pyzrvd%2B80UJR2zDHamSITSPQAfsXasASAAHEOxYxxogPGJRIFvhfmAXO4cuLhQ0kfEuv94bnzdsbBMdYTLQAANZ1nXmwjsYhBoMCoO2YycsMplnMg1bmb9QpkwKtQymMMkEQBNHTcuoxEAVCYcREgW5uhD0QPtZGRB5hnGMIyKSjcOhTS%2BtAqR%2B8ZHtTkcfLkJoJblwANKIGOK9d6RAGT8PbPGRMOExHWO1h-OBh8HG0ORCaB2aDPohjEEwYhOFgYhPztxe8sjo5UzLCaeO5cWS9DwFtHoctuh-UQKYTUCBAlcmCaDXmHdKF60KpE0elJyxly5JAYwxsehECAYUCCLJ%2BngSwGubwsA%2BrlPAvjTKViGl5zCW1Ja2T5FlnLOPbpvTOzUFOISdcJQehmIVvo4gRiSityCdNCRs0YHSJWcLHJOFyxn26bPU4AT7ACNMPAKgZFYBiHvqo9R-RLEWVuSTe5tjHnf1jh0-%2B3TdphCoKYPA8SwhMAuFcfY4LxE50kaE2BmJujwFjAEhgCw8BPPWS81B3SoxkrjGCn25AcC5EgGk5ZmT7FrMcXScs9DunuM8YycpDJOE-GyHirlxKeWrIQc8rk5ZlHdJYT8NhASxBbVgDtVRFhEAu0Yf0PBuMgWXJOvi1%2BdybGdzsQqosiCNkuLVawJKeiwjQEyCGPZhrfyGJKPtaA5ErAQRlYsihusFqtL5VEpE5ZYndMpZkGw1SkDhuJmxUE2xORYjEHQIFMJAqCiAA)

#### Formatted code

```fsharp
module internal FSharp.Compiler.ParseHelpers

open FSharp.Compiler.AbstractIL.IL


/// The error raised by the parse_error_rich function, which is called by the parser engine
[<NoEquality; NoComparison>]
exception SyntaxError of obj * range: range

```
            

#### Reformatted code

```fsharp
module internal FSharp.Compiler.ParseHelpers

open FSharp.Compiler.AbstractIL.IL



/// The error raised by the parse_error_rich function, which is called by the parser engine
[<NoEquality; NoComparison>]
exception SyntaxError of obj * range: range

```
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 11/19/2021 20:14:05 - 720227d614165739008fac1c19a36525151324f5

Default Fantomas configuration

*Signature file*

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by dsyme** [comment]
An extra line has been added

**Comment by nojaf** [comment]
Good catch, this looks like a [Repeating newline bug](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#repeating-newline-bug).
