### ISSUE TITLE
Idempotency problem when comments are in odd places in type definition

### ISSUE THREAD

**Issue by dsyme** [fsprojects/fantomas#1975]
Low priority isue

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAsgDoBORAdqRZvLvgIJgC8V5EEALgJ4AO%2BACiVgA3AJZISAcUTlEJAIYdE8ACq98TMIJHi502QqWr1YWADMwACgBUonAHkSogOZqASojPWAlAEkAMmp8HhbWVrY4HuTy6Mrunj4BQYghYGHaYhL6copxJjiiAM4crJAANOBQhYgcHKLkzoWoYADalRCg7OyQACTcfM2Q9Rzl7d09wvI4WMhobV1dAAwVC92%2B5EjkHADKogBeyCurYAAsYxAAumMAvkcd51B96oPDo6u9k9OzrQ8QAIx3BaQAjyAAe-nqiH8MmcHAAFm9jn8AEyLB5XLq3MadIFPAZoSAAI1gsBwiK6HymM2a82OyMBFO2iHQojgOFg5HoHAAoht7GYIbJyQszFNquiboCcRS8d8iSSyQzHp9qXNfmAAMxKiCQbY8eTQRAAIU8sBIiH48gUsSUJGFXQ4JBmEsxUoevX6cuJpPtyqp31pqxO2qgeoNxtN5v8sAA7nJoPJquthLAE3UOb7OE7EC72FiutLxp7Bt7Fe6Jv6aeqAKwh3X6w0msxmxAAVR4fBICaT5BTadEGZDopw4tWGLzbvespLCt9lK%2BVeOYAAbHWw43I4gAMI4ROFLcc4pO6AcM2ZsDD0cLccQfPsQs66cE0tzisLtVLgDsa4bEeb5oIZlCTkc9LxzMdJWxcti2fWclXnVUfiXAAOH9wybFsD3ZchQLFcDr0ggtoOeWCfXgt9EMDBYAE40MNegzFtA90HQeRz0dZ0INdKCpxgqAX3IlUA3VP5lnVet0M3JkWTZQd1TA3Nb0nXE%2BPlMjyyExckQBcT10QBjbWk1lSTkpcOPwrobzAO97l4kj%2BLgjTKw-JF6XE9ZNg4exyBUEguAAdVEeFcJHCz2CsmywAfR5VIEpz3yQpEtV0396CELANgAEUQAoWVtdjs0U6zlJlVTXkE5zEtWP5g3EkFQV8MwVDhGRuVC7Y4TNDhAvgYKQxONEuInHiVPsoYtlfTSXOq2s6rBdYzFEUF7E7RQzW5UEeHNQpCgHHCQ2rQaCO4oi7PxKByviyiRNXObQQ8OASHgHq%2BvVAaisi6KPTGy6pymqqFj%2Bb87oes14AAOSwdBgJIflfCUdAmhDP4PpKosxvQXA6gKWQADEzVY2o5GSSbKqoro-lQ8TQaeggsbsSF8ZIQn8rraA4StA1bQAfRjcRgtRkbSp%2BiaKoS8n2D%2BWi7rShQuEcCFihehF%2BqOyzCPvYjzvGkYxeupdUTrerZfkeWSEVjhIehuQ4YRpGRMF07Ru1zGcGxxmCcUW0Sb14SDZ0pdIBNs2Lbpt2Gbxz2ibtNmOYUE85F5-mEUdzWzrlX7cX%2BiWIGRNzA-qgA1f0jXqeB6mcZXz2QtXwo12znYz0Wrr9ulkoLsFcYyk89tLjYK6r1XU4b4XtczmVs-VZFao70FMtgDhpB5Tbtt2jlB5rWvLnrqKta9Ry-rJqfZoL%2BmceNdloAAayNeOr5qQpvO2GJt1JKH9vkvDh939OZ3Uw-xZT1uoHcGiAYznxNBwOMMhkjZUWuQIKe16AbEAtbEg9slwKSGkpIW6NtZxQAfrOkwNA4AGlECIB4I1ZqMh1jP1iIKQ4n9Qrfy%2Bk%2BC6zdCGt1WMiKms82oskKHCDeS53rYOKrgx8sUD5ZyPgbaWgddgNDwGlZwUMZDdUQISAgCAmGYK-uIz6e8-5li4VpVYGoxKB3oAUZw5Au7kB7hyXYdjFBYHNCoWAHkNGKD2iFK86sTpp0biY0mgClwagDscIObs5DRDqMIKEHJnCoJhnA%2BoiDDz%2BLCtvIJI88H73-rI8JxwNT52iWHOojD-AxEJPAeQO5YC7QaKA8BkJsmsOMaRUxxSiEWPbtEzKRR5CEjwAIoocJthcC2GCDphi0ZSLGjIeA-JGHbG4HgMJfSFgahntE3kKyBTtLZiQHAZhICdN-t0rZ3Cdkn2ieQyh3itjrFvvIRxKtmEBLrnkn%2BITrm%2B3MTs4B0SjS7nIFfRhhQ0qwAyhDRAxRlCVIjogDaW0EVr3IBg445lLn-IckUiecjSkkNBVaDC5ohmFGgE4Fk8TlCtgQRybK0BdyGD8UOAxx1hpO1HoUnpRKSkWL4dE9ZTgTw6KQHM7lt5KgXCOEMQouNdrNFxdcIAA)

#### Formatted code

```fsharp
module M

module A =
    type ProviderGeneratedType =
        | ProviderGeneratedType of ILTypeRef (*ilRenamedTyRef*)  * ILTypeRef * ProviderGeneratedType list (*ilOrigTyRef*)

```
            

#### Reformatted code

```fsharp
module M

module A =
    type ProviderGeneratedType =
        | ProviderGeneratedType of
            ILTypeRef (*ilRenamedTyRef*)  *
            ILTypeRef *
            ProviderGeneratedType list (*ilOrigTyRef*)

```
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 11/19/2021 20:14:05 - 720227d614165739008fac1c19a36525151324f5

Default Fantomas configuration

*Signature file*

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by dsyme** [comment]
Original code was this:
```
module M

module A =
    type ProviderGeneratedType = ProviderGeneratedType of (*ilOrigTyRef*)ILTypeRef * (*ilRenamedTyRef*)ILTypeRef * ProviderGeneratedType list
```

**Comment by dawedawe** [comment]
The idempotency problem is fixed, but there are superfluous spaces after the block comments:
```fsharp
module M

module A =
    type ProviderGeneratedType =
        | ProviderGeneratedType (*ilOrigTyRef*)  of
            ILTypeRef (*ilRenamedTyRef*)  *
            ILTypeRef *
            ProviderGeneratedType list
```

I'm looking into it.

**Comment by nojaf** [comment]
The trick will probably be to use `sepSpace` somewhere where a space in a string is used.
