### ISSUE TITLE
Option to keep single backward pipelines on the same line

### ISSUE THREAD

**Issue by peterhirn** [fsprojects/fantomas#1976]
I sometimes use backward pipelines to reduce the amount of parenthesis. The style guides only mention forward pipelines so I'm not sure what is considered best practice.

Would it be possible and make sense to keep `foo <| fun _ ->` (see below) on one line?

[fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzWseYAvEQBQCUAOgE5UB2tD%2BhAPAD54Cu9YA%2BmAC0APjAAHGgEt6WXLyqQARgEM6kJozr0WYMrh78hoidNnylqhdS0adHbrwEiNECCZlywClWpev3Zl4WAF4KGrYEuvqORn5uUh7mPmFaruIJgd7KoZDWDJAANOBQAM7YWNIA5iWoYADaxRCgaRCQACRYAJ5iyGiQpoWNru0AbsroXL31Q2kADEUtwwCS9EgyAMqSwcgLi2AALDNgALpDAL67TUftXT21-TKDi6Pjk7UNe2AAjJctkACyygAHgAZaSIEGIeiVLAACyeey%2BACZZkdTmkLkNmn8Ot0pkoCOgEWkXhMph89kjfiT1ogALaSODoWD0ACCWAAoqsAPK4MH0HZHCC4cZlNHnX7Ykm4u59RSE4nDNpjMnvIVgADM1OG6zEymgiAAQoh8DREAAFVTKOnYRA0RVpLA0SbijGS64y-Hy2BE7Wkt5oCmLfba1q6-VGk2wM0g2AAdzt0GUZRWI1gSYqLIdridLsW6NcmLSUqVty9Cr9yte5PVAFZQ1BwwbjabEABVMQ9GhJlP0NMZyRZhsi9Bi-MSrEesv3b2%2Bj0qgPTT4ANgbkCbkdbAGF0MmSluWSVc9AsNHs8LRYhXYX3c9PTOK-Pq2rPgB2NcblvRxD-emKO3nngl7XhARauCWrT3nKj53guNafAAHB%2BerNlGZoHsy9CASOY4tAWoG3ji07QT62b%2BvBewAJzIRGrK4FgdoHnSdLKIBuZXuObqTnexFQLOZFVqqgbql88zquuKGbt%2BtIMkyQ7qjhHF4ROxZTniD6kZWcEvoiPziRudEMTQMmMj68mfOxIFgGBVw8epJFzrBz7CZ8yJrisaxYNy9AACo0J0ADqkhwthwGcTe3FEfZfEwTi2kuYiWr6ZJrI0LAPDwAAIog6CSAyRlsc6SlpPh1mEdKvEPFgAnxUuiIhuJgJAksuA%2BbCUIcqOiDrLC0ZYEF8AhQ2%2ByouFBGRRV0VVTVzl1YsXz1o1wIrLgkhAtyXbKKeNAckCEiICUJSDlhDa1qNylcapdmylAAxabNQYtF8q5LUCABKiBwDQ8ADUN6ojVZNlgBBUBQbdjz3UJc1Pe%2Br0fV98AAHJcHS-40LySwMXSNQNl8gPlaWU10lw6AVLlAoAGLRixWBGT56mQ4uj1pF8SHifD0bwP8JNk%2BCVM0DTBVrtAsJWiedp8HGkiDfC%2BMTYTN3TYzFHzdRr2pTQyidNyNBgkev3wsN50lSp4FqYrd1PlDzOuCia5NRrWs63rWDI6jdoY1jOMiXLV1RYrxOk5I5OIPzgt2vTdzKzpixInpnyQI72u65IR7c0HIdh1tQviSLYtGZL0shb7ZvXfiltOdb6pIlSr0AGrVoa0jwFUBuAQhxuuKVQMgzcU0V3FD3V0lCdNRTPAnsdTerK3ReG-9ncQN3BOQZVA-SrVNsQEiDWj8CmWwFgADi2C7fth3HW3p2Lycpu2f75aaVbTPV4to888H4KGsy0AANaGprP%2B2ASjeXWNaRAGEUYnQUmFC6EU-aTUVvxaOCVY4vQTojRAcYQ7GiwAmKEkdEDZVWvQYKx1WSrF-O7Gg3tPiKRLvfRBj9HKDyrp8JEsME4AGlECIDEC1NqUIVhgJtPyQUdDYEm0uqXB%2B9x15Kk3tXNme8gSdQZCUWEV8F4MOBubZhM02GUjVgnTY0JMCpUqCjKE-VECKH%2BAgcRex6FjTKvLVeU1kHPxVi0DUYkE6slypUeg496CTxZJsIJW0uBmh8rADy1itrHVCl1HRvcwYEifpXF%2BnwNTxz2InUmdp6CJJGBCFklQqFo2IdIMhh5km4SkfAmRTCNIsI3kPHJtd35BzESCa0ih4DKB3LAI60JMHYPBPU4qXc766LLq0gx2S9gahHvkzKqdlCKEwGo1OsJ1idBkMCKZqS9H3ChPAXkYj1hdEwIs7xaQNS73yVyC5fJJnCxoOgXAkATnzIcncmOPi375J4Xw%2BJMgVgAOUKE%2BeEiUkuJ7qc-5KDoYPPQfk7%2B0Lf5iJKKldKqxMFHkQFzD%2BIcz5mgvnUhslkEUr1BpVTxWT7muA1JwjFqgvxmnWSUaAUgGTFIYvANspCWTZWgLuTWmZoFwoaTM6RjCFb6JRVvTUyj8nXKkCeexSBjkIuKMcXY-QSgUyOrUehZwgA)

#### Code

```fsharp
let foo f = f ()

foo <| fun _ -> printfn "bar"

foo (fun _ -> printfn "bar")

foo <| fun _ ->
    printfn "bar"
    printfn "baz"

foo (fun _ ->
    printfn "bar"
    printfn "baz")

```
            

#### Result

```fsharp
let foo f = f ()

foo <| fun _ -> printfn "bar"

foo (fun _ -> printfn "bar")

foo
<| fun _ ->
    printfn "bar"
    printfn "baz"

foo (fun _ ->
    printfn "bar"
    printfn "baz")

```

Please tick this by placing a cross in the box:
* [ ] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [ ] This is not a breaking change to Fantomas
* [ ] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Hello, thank you for your interest in this project.
I'm afraid this falls under the section [What are we not looking for?](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for).
Please pick this up with the style guides first.
