### ISSUE TITLE
Fantomas writes even when not necessary

### ISSUE THREAD

**Issue by pbiggar** [fsprojects/fantomas#1984]
When calling fantomas with a list of files, it will write each of those files, even if no change is required.

This causes my build watcher to start a new build. I suspect it is also much slower than it could be.

I would recommend that if fantomas formats a file, and the input matches the output, that it skip writing the file.

Seen with many different versions, including v4.6.0-alpha-008+5343e280a18d679b36226f1374c3f2e2d079a029.

**Comment by nojaf** [comment]
Hi Paul, good remark.
I believe we do already know if the file was changed or not:
https://github.com/fsprojects/fantomas/blob/f8b5c07254ebb69fe8c7ba7d3d554038cbcdc553/src/Fantomas.CoreGlobalTool/Program.fs#L129-L140

Perhaps, we can indeed not write to disk if that is the case.

**Comment by nojaf** [comment]
@pbiggar I've released this fix from @dawedawe as part of https://www.nuget.org/packages/fantomas-tool/4.6.0-alpha-010.

**Comment by pbiggar** [comment]
Wonderful - I'll upgrade in the next few days, thanks!
