### ISSUE TITLE
Do not insert newline for multiple line strings binding

### ISSUE THREAD

**Issue by albertwoo** [fsprojects/fantomas#1993]
I propose we add an option to do not insert newline for multiple line strings binding

Currently:
```fsharp
Template.html
    $"""
    <sl-input class="custom-input" required pattern="shoelace" value="{name}"
        sl-change="{fun (e: ChangeEventArgs) -> e.Value |> string |> setName}">
        <small slot="help-text">{errrors |> String.concat ", "}</small>
    </sl-input>
"""
```

Expected:
```fsharp
Template.html $"""
    <sl-input class="custom-input" required pattern="shoelace" value="{name}"
        sl-change="{fun (e: ChangeEventArgs) -> e.Value |> string |> setName}">
        <small slot="help-text">{errrors |> String.concat ", "}</small>
    </sl-input>
"""
```

## Pros and Cons 

Make it nicer to read

Estimated cost (XS, S, M, L, XL, XXL): S

**Comment by nojaf** [comment]
Hello, thank you for your interest in this project.
I'm afraid this is something that doesn't fit in our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#stylistic-features).
