### ISSUE TITLE
Comment after equals in record type is lost

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2001]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAamALxgD0pYcAtlYgHboA6ATo3RBMGABpoDKsWgDEAlogA28ACo5ELNhw4BNNAHkAFgNrp1IugHMAouIDOc1u0VgAWmgCCAGVgGZuAHIBDWmAC%2BkADTgUGbo6Hr6JqhgANpBnHEckAAkWLhRkHroAQkQyQBuHuIArshosVYcAAyBFbkAknRIDHwiAF7INbUALDlgALoJPp3xFcmppVCZ2aNJBcUT5bUAjMNWkACyHgAeDnqIDvT6OtPLAEyVvQOKQwmgM%2BPpAEawsOInivmFJVGLFaerHz4iCoIjg4mcdnQhkaqgAZrs6B1ehBYYUzJdBqs7msUrIni83gCoLMvgtkWAAMxE3J8bAeaCIABCiFhsGYiAACh5mF5EOhEMx3lZ0MwShjrljemM8WhIM9XkLciT5j9yV1qVBafSmSy2ftYAB3AXQDxmBp5WAmsLORUcEViipXDg3RTYj64tKy%2BWEqXK75lckAVg1kC1DOZrPZAFVsLhmCazXQLVaRDaNajTIhxc7JfcZVBvbbPiqA7UwAA2ENhnWRxAAYXEppMdecJnt0HQbNtKLRWcdmNuvoeXoJRb9ZLLAHYq3Tw7r2etgY8Bd2wBn0f2JYO856C6OicX-TFyQAOGfaiN6lvguir9d9qxOiAujhuxIeiZy-e%2BuZH35WABOc8GTsWF%2BWYFsaA8Vd7QfRQn18XMcWHPcFQPcdVTLJZqnJUNZxrPUgRBME03Je9s2fJD3RQr80J-UlMOWFZcOrUDwKI0FXlIstYIoxDt2Q-NaJ9GZfwnM4QwaJp0FUOgpGYTAAHURGOdNez4l8RkE3dhLHMTGIqJYqRY-C7GYWAikaAARCQRBBcCYNFOCOAQzSwDfJUaKmdD9NLZZ1VwzYtjqWEpHUehjDMPh1DZdBlPgVS1QuTccwE6ihO8%2BiS2PLDg0C7YGlhEQtlUOMPE7ZhDC2bB2RMExU1vDVA2Sx8B1dIcMoYPSGL8wzK3yrYACVEDgZh4HixKyy6Fr4La18Op0zLRJ6nLlmnAbhtG%2BA3CKKhl2YOE6n5KhIg1JYNKo98aKoIpxDCcQ9iENkqHK8DXCRZbsv-RQljPXDNrZeB1lu%2B7Hue16VxDaB1G5elwIAfQNEQEvUSALrSq7OqyHyVu%2BjgliAgazJ5TBVGYXY2wm1GNWm9H2p3T8lpxXzVr%2BHCyw2bZiY8UnyZENsdr2gVDuO07yXOlLKIxzyhJuu6RAexEnuYF7QgFd7uq%2B8lTmYjnud5in0GB%2BXFcQZXVYcqGYZ5DsBUR5Hjjp%2BaGfSJn3RZvGIFOf4BvwUlGT0eBwip1cTxmly5q09LFq6nGtbLU5jI5oKhEsjsGoDxpg4d6mkqdqPMZj7Gsr-bWAuT7YrNgdAAHE%2BSqmrEDqhqQ6a8OIFcy6ZZ0ws49LhO8uTkGFb2RlwWgABrRkbYnvkTFkvheWvXbGrI9TJf4%2BntM-XuS-Ev5%2Bo5txEANU3mXQI16HemyiroFSGrsRpFyF5gxbLciN7cjziRo3fPv72opx1ocwANKIEQNgEKYV6ANEXrQBEH1agf1aluLe0dGaxz3gZKwpw-oVy2MYEEJh1Ctzzp-LuP8hJ-2ZrjbWhMOYtAMOIRAZl9C7XoHFRAjx1gIEQRUZBs1UHO23viOi-995WApOzWokA7APX0HQVOdB07OBaAo8qRR2RSFgFJDh5UGp3nXig1KaDC472-OI7BigKS6xkXI8CdB9F5H1AYZ%2B%2B0b56Hvq2QxmZ87uQWuYsRND461ApD7Ie8sEEOC8I8eAHgGywHqgYY%2Bp89g%2BI3MYqWpju6BJEsEgBFQKRJxkVZfmHhHjMMIfzTQmAGDbHSc5Dukd-Eu1lPQeAcIEF8CwMwzWBTJHlxkdCDp8I0khnELCNG5DpaUJ7hY-JEjrGDxkWAiBuiGANGnh4ZRuceJOT8d-aUcygnu1oWWCkh8ZFj22RPBBJgzIWUaMfNsiAgbD1Ng3Wq9VvEal4tM7Jszcl9MWRwCkwCrnckvOyUpJhoDMDsnocqryox32cDZaAjYeTWlXu-IxgiTHCPQaIvJpyQmFLwTI7p8KOw8KQA0jSQQ%2BidAyCYIQ9UojkR8EAA)

#### Code

```fsharp
type V = // comment
    { X: SomeFieldType
      Y: OhSomethingElse
      Z: ALongTypeName }
```
            

#### Result

```fsharp
type V =
    { X: SomeFieldType
      Y: OhSomethingElse
      Z: ALongTypeName }

```
            
#### Problem description

Comment should still be there.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 1/1/1990

default config

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Most likely happens as well with signature files.

**Comment by evenbrenden** [comment]
Looks like this generally happens with comments on the first line of multiline type declarations:
```
type Type = // COMMENT
    Type
```
↓
```
type Type = Type
```

**Comment by nojaf** [comment]
I'm actually trying to address this in the F# Compiler, by having a notion of the range of the equals token.
See https://github.com/nojaf/fantomas/commit/d21ec81845caa761e27871f26d0e169c2fd52700
