### ISSUE TITLE
Editor.config: insert_final_newline is ignored by Fantomas

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas#2002]
Original issue: [RIDER-72601](https://youtrack.jetbrains.com/issue/RIDER-72601).

> What steps will reproduce the issue?

> create a fsharp file in rider without a final newline;
create an .editorconfig file with insert_final_newline=false (either as a global setting or specific for *.{fs, fsi, fsx});
format the file

> What is the expected result?
Rider does not insert a final newline.

> What happens instead?
Rider inserts a final newline.

**Comment by nojaf** [comment]
Hi, I'm ok with supporting this.

Perhaps it is as simple as tweaking:
https://github.com/fsprojects/fantomas/blob/9e35634e25acd50cb0353abd4b7cd5cf0fc07792/src/Fantomas/CodePrinter.fs#L65-L69

**Comment by nojaf** [comment]
Oh, and the default of this setting should be `true` to be non-breaking.

**Comment by nojaf** [comment]
Available in 4.6
