### ISSUE TITLE
Consecutive `#load` statements are merged into one line if `namespace` is declared below

### ISSUE THREAD

**Issue by peterhirn** [fsprojects/fantomas#2014]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBiANrAhvMAOpACoCeADogM4B0AZlQB5EEBOBAdlrvkQAqtYAK0TQALvSYt2XbHkKQAqmICWmWg2aQ2nbvKIBxFRM3TOOjhxwBbauRzREYALKkAcjbsPEFyABpwKCpEMVUOAHMqVDAAbUCIUAgkqAASMQpkNEgVDjF-eKTIFIA3HEwAV0zYguSABgDk5MgASQ4kXIBlFQAvZAbGiAAWGrAAXQKAX36EkaL0ymjs3PyBotKKqriBiABGacbIZxxGABkcxBPECLEACxXtnYAmWpHx5KmCxIO0jMWr%2BAA8nQzhxEB10pg%2BrMSmVKtEtttHvsmgBRNpAkFQ7ZQaCsTB0SCvSb7L5NH4LLIAI1gsEw9zJ6zhaARAwAzMjCq1gqwxAAxHJlNyIADumHO9MaYlYlSJ7xJ0PmVUg1NpEoga1hmxGQw56o6iGsKjg2A4AEExGjAcDxbqwHQysFZUkPslSYVyUqVXSORqNvDtWAAKy2yAdeyOABCiDosFYiD4OFYnjEiFYaqSUplAzezvlqw9iy96d9TOq2IAbCGw94ozG4ydYMLU9AcMFWsVYC3VLAOOmIJnEE6IC6km71QWqTTvdDGVrsQB2KvhxC12OIRTkSisFttjgdrsqHt9u0OwfZ4mfBW-Seqn0wv3MgMADiXNeja4AwphW1QPz2qJm4ixse9rqGejQ5sOebfIqhZTsW96liyjQAJyvpG75xs4BqUqmIGnkOYAjjM%2BawTe075rO-rYjs9QBqGy6rnGf4mvhYGEcRYBjqkZFQEWd5UY%2BNF7PR1aOKadApqwf7WNYODHgOHHQWSvHKvBAmatRDxIqJjGYWCBpGrSR62qBjrnnKl6kdefHqTOmlCQ87K6d4ElSfqhrGiZAaKRZuZWTBNlqbe9kPmWDyDCGrTtGIAIcMQrCkAA6sYdymQRflQQFKlBfxoVIQGOzBi54mCOUbQACKIGKhpSQp0rgckkFEcp7qqTkeQaWFyHJDslb0UcjDNHQxA3FcKJgR0NyxmIKXwLcx6DC8mUtdlbVBR1CGCeFAw7IuA3HK0dAqIwAJbjgYixiijDkHGVBUIeva2oGy0QRerpXhSUCbV1BU0S%2BB2MAASqIsbwHNC22ktSlreO7XLL9c4PGhgMg3ArDwG45TWLhrBAs0KbWFEto7DDH3WV9kDWOUmCqGKoK8rGcmhKmZALIjWkDM8IZo2Dzg03T5yM6wzN1SG0A3ImDhSQA%2BsKKjzXcZOjp9So-flSNcyJ2KHMcpqsEmpAAqwZwARDaUBtDK2cdxcwbQjGuc40jw6Trg364bxum2IWM46m%2BOE8ThXKyRgWU9TtNqELTMXVJbNYt8209UkjzOTrHs4EbJsqAB-OR-TiDC6LeHi5LSbiKmcsKwtIdcarizq5RDk7c7kWAwAapqEY5PAOThObi2vU170qxTasO033UBo8xVu8cvLleIj3d20fcD1DQ9JM1Nv11kjeJ83ycQI8-Vz4wFWwGIBghNdt3UA9PbrwGL217bE62SFk9-Yi%2B1uwLUeggjNgaAABrCM5cQEhCoHFDongWLYyegGMyjUt4j1DjlSmeUv6a2dgDHWQpRTnCjGIJsVx45VWOhwYwj1TRtGwn7VgQdsTINfrvD%2BFED5T2xI8FGOsADSiBEDkGGqNK4rRYG2ExGxcyb1LLkzDuPTqjtHJsjomfCahoqA3CftiK2sj-LyIwZ6Oy2CnbJFZNrbYoY%2B6Qn1uEbGVxZqIEpM4BACcBgsOtq1OGuUTGcO-myV2VjTRinCBwBeHAl49i6GEi65Q4zEFgNFRxF1HrSJQRAbe3ieK%2BM-v4nB5i07BNpqmKwqhigXB7OEehuMKE5Gof%2BdJrCx5wTyQyQ%2BAZWRtz-pHTEJwbCUngDgL8sAHoRAIQXJpXjYY5MwX49pXDtislnlYiqOccCUkhBonONwOikFyMcKZ%2BisqGPWnMtp7ok6dNPlYgRQjkm5FaOAnAkSLbMIysc1apyfHnI4QsgJjRWS-ysUAl5IDMRUH1rAcqmNqApngHnQWoJb53QfhwJh2xfKfJ3i08iW0OnYlZHgkFiYmKIDWVQXEKhDRlMQPARQVCexVWgN%2BJM3ZEHvPYtM75szjEXPHFcwlvCrHglYEaMQrikBHOHu8QIox%2BjZCoLyB60QWETCAA)

#### Code

```fsharp
#load "Types.fsx"
#load "Project.fsx"
#load "Utils.fsx"
#load "Git.fsx"

namespace MyNamespace

```
            

#### Result

```fsharp
#load "Types.fsx"#load "Project.fsx"#load "Utils.fsx"#load "Git.fsx"

namespace MyNamespace

```
            
#### Problem description

Consecutive `#load` statements are merged into one line if `namespace` is declared below, but not if namespace is declared above, eg.

```fsharp
namespace MyNamespace

#load "Types.fsx"
#load "Project.fsx"
#load "Utils.fsx"
#load "Git.fsx"
```

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 1/1/1990

```fsharp
    { config with
                EndOfLine = crlf
                MaxValueBindingWidth = 40 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this bug.

It appears that `ParsedHashDirective` as children of the `ParsedImplFileInput` are not being separate by a newline.

See:
https://github.com/fsprojects/fantomas/blob/24705b93140e2e4bc3983cf15c9018a2711b8daf/src/Fantomas/CodePrinter.fs#L77

This problem probably goes away when you replace `sepNone` with `sepSpace`.

Are you interested in submitting a PR for this?
