### ISSUE TITLE
Comment inside LongIdentWithDots not preserved

### ISSUE THREAD

**Issue by dbrattli** [fsprojects/fantomas#2027]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAHAhlgBZgC8AOgHYQQC2h0JlsATvegJYBei8ACoRIB3DsSo0wAHzyCwAWgB84iTQLEIAeg1gsLfJQDO6QohnqssMHwCexWNRaJjWDgDdTB65Sz4AHspUVADoAJURcY2hEAApySCCgjQSkxLiAGjA4hIS4gEoAwJpINPAoA2wXSgBzA1QwAG1SiFBAyAASLGtcZDRIDm9ipqK213x0AFcehqGJAAYSwqgASUokbwBlbmQFwoAWGbAAXSGAXx3mg-bO7rq%2BgfPh0YmpxsWARgeJSABZPwAZfqIP6IarEQbvABMswOxwkZyGLRUVy6U0gIPgAHkAGYAyiIdadTDgpEjMaTOqvQoQz5FACiq2xuO2BwgkHQWMgMNOD0RXw6KNuACNYLB0MS%2BU9yWhKYEAMw01krcosLAAMX6YwAcoghJw8eKVLpJly4TzLvybr1haKDazSc8KSywLsFVB1ohaBw4Oh7ABBLD0zE4wG2mhYsblE00eESXnDa6o61imntSUvJ0AVldkHWBCiACFEFjWIgBHpaNhECxQxAjYgoxAYzQ43aE0KRcnzWnHYsAGzZ3P4AtFkt-WBCKvQfDlFauWBTlz2Gs6FjGwKw6Nm1oWxMd0OpsnpxYAdgHecQheLjgAqrhuiwpzPKHOFxwl67w%2BhI%2BvuQjzW2rT3FN7SlaZFgADjPIcLxHRwAGFjAMAw4PsAwjWgCxqw-CN6x-U0-23ACoCTfcQKPQoAE4oOHK9EG%2BD1BSrZdP2-FQN0bLcSSIyASOA7tpSdN55idHNz0vEsUJ9ShmJwhswCbC5CIFQCbT4w8e0KN4PhEwcol9LEsCrFDaHoZc6zkhSwBbKAd3bVSu3UgTIWomDaPdT1vXfJ0WNwtjf1jf9lOIoCHIdJzNPlHTz30wyWHcr1RS8xZzLwzcCK4oKeJC7d%2BLAzSXRElY1iwDFKAAFRYawAHVRCIGSv18iR2Pkzi%2BW43jQtAmUVDeLMoug30WFgcZVgAEScDhPViszV0amhmss6zkUtKB%2BiwUjcu6iQ3n7ETfl8JYsTKogQVpBr1iIVgsBq%2BAwVdXZoVSjj0razK1o2xy8sCN5Tz2vwVixDhfAxe9CFYWlfFwRwkLfaTXQzR6-PwgKlJWu51rUsKvp6yC-t8MI4BYeAbrup0Hos1r4ze%2B5OvI76qLxgnWHgTVxloRiWGxJZDNoWpXTeCmXqptHaHGdAXD1RBVVYegsFisqBUxrqnShbMmaJ74xYlwFpbYQhpuzRh8D0DCqwAfREW66sFlGMrR96lbplQIW0xYfj8Qa9GsDEWABNCSbq%2B7Eaa-zm0C%2B2aZyz6tpoCFqTxz38G932ODQ1n2arLmeb5wSbbD1HUVF8WOEl3XZflxXaY0wIIUit3E%2BTv2sE14vS5l-WmMNohjaHWKLY4K3OSelqhdbamMar8Ka4Kt39oANUPfN%2BngfoqgD5dwOD%2BbQ8Uu3UQdyfsYkCE%2BtnvxVRGjDYaX1ZV-XoO89316I4nqOsZjiAIV2s-fFG2AsAAOLYAhlDRAMN7D30zFvCAC1KZjzRh1N%2BytFgQl%2BrPLWJdAT5h9NAAA1vmE2uDsAGFKusfAFZJJszht5WSw9Frh13PZJBTtj64zdtqXUWDsAThBArbo41AaUFELDX0qx6IZxYDnRYPlH5WQYXZTszDq7OwZm7AA0ogcIh1joghWGQisTJ6qsRDsjfOe9bgHyUVPFQsphI-zOp6AwRBIGLHJnQuBNl2rZRJJtJ0spXaFBzKvTAg0qhsxBNdRAgpvgIGZNI2hSM0q22fowxRPjo5%2BPjvXTgVRKAX0oFfewmxcmEHGI4MqsAioRMILDIxc0YE7zkQXBRH135%2BLroE304sqyUBqe4Mc1RxEcwEf0YRqE6myKWrZFSaSJQZMWLKGegSW4uCZH8chgp4D4AQrAAwq8OGSwme40enjMqIPSW0hZp9AmjVTvgQUmAHGpyIOsLwPhfBHMSc9ZJwtUmtOQYUWU39AkaK0asCJKwCH6EYJ8kxSSzEpJaY7ZREhZRoMCdg-QuCmQGEGsNVY2o0K8BWZgvEIDoZ7PGa6FKXyR4-PgX85F1jUVsIxcbcSjhbkGGgCwSaGpDLwGvEI%2Bw41oDGD0Iuah8SGqTPkTM-5LCaCylUYEgkvKMIxKQLC7ecJSiHB2H0Awqo9l1BkScIAA)

#### Code

```fsharp
let path =
    match normalizedPath with
    | path ->
        path  // translate path to Python relative syntax
            .Replace("../../../", "....")
            
```
            
#### Result

```fsharp
let path =
    match normalizedPath with
    | path -> path.Replace("../../../", "....")

```
            
#### Problem description

Fantomas removes comment in method dot chain. It looks tricky since the white-space where the
comment was has been removed. Perhaps the comment should be moved after the `.Replace` instead?  Related to https://github.com/fable-compiler/Fable/pull/2738

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello Dag, thank you for reporting this issue.
Fantomas is not considering trivia right now inside a LongIdentWithDots right now.

```fsharp
LongIdentWithDots([path; Replace], [tmp.fsx (5,12--5,13)])
```

Comments between dots are not printed, an easy [workaround ](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAHAhlgBZgC8AOgHYQQC2h0JlsATvegJYBei8ACoRIB3DsSo0wAHzyCwAWgB84iTQLEIAeg1gsLfJQDO6QohnqssMHwCexWNRaJjWDgDdTB65Sz4AHspUVADoAJURcY2hEAApySCCgjQSkxLiAGjA4hIS4gEoAwJoC%2BixGMGY2fE4eflkRMWoaaTUSRQKJLR09Q2dTFp1LGzsHJ0I3Dy8ff0bA-syZwohQ8MiYrMTk5PTM%2BOy8qmKGJlZ2bl4BdXqiAubZNoWJOfbC5Yj8KNjdlO-t9ZzIXJgTq6fRGExmEgWKy2Ij2MCOZzjMCebx%2BSBpcBQAzYFyUADmBlQYAA2piIKBApAACRYay4ZBoSAcbzosk0amuKoAVwZJLZEgADBjFpAAJKUJDeADKZ1ZiwALPywABdNkAX2FNApKmptPpRKZLM1Eg53N5pMWAEZjTqALJ%2BAAyzMQDsQ%2BOIcsKloATAKlaqJBq2dqTTS6bzIG74AB5ABmTsoiCltMwntDnPQPKJFsK3ptJoAohK4wnkPn2ehY5B-eqbSH2WH9YyAEawWDoNMNjNZtA5wIAZnLEDFhkQLCwADFmVUAHKIIScROdiS6Hk1wN1pW68MG1vt5dQKnd81KiDyodQKWIWgcODoewAQSwRZj8edB4gsaq2PXNCDEnrYdGwjPcO3LU1MxPRYAFYL0gKUCCiAAhRBY1YRABD0WhsDHD8ujXQIAz-TdKWA3c2zArcjzNbNTzAAA2OCEPeRAULQxwHVgIQx2gfBsXFVxYF4lx7Dw1dEF-CB-y1Ki9RAiiDwgns%2BUWAB2JjENY1D0IAVVwekWF4-jKEE4SOFEi8v3QH9CNrYNZJ3FsFPA6jINoxYAA4NJYtj0IAYWMAwDD8%2BwDFXaALBYPCrJslQiKkkidTIpz9xc493MKABObzkO0xxbWvZtcMs78JNsjd7NIuTyNSqj0t7OjLSFOj4M03zHBC%2B9KGi0rJLAaTyQcpsoFAxTXOUvsVEta0WuYqIH1jLAxxC2h6DElgCLiuyAKG%2BTatI%2BqVK9PNZravKk2vW92wsuiYrKraKp2qrHJG5y6pohqrUHU6WIWpaWCvG87xuxZxL6gawEAw9qpSyiDo%2Bo7Aktc8WvFSUsGjSgABUWGsAB1UQiB66z7okeL%2BsS0MYde-aksOyaJEtWCfvmlhYC5CUABEnA4G9-vWzaye2mTnuGw0sDG%2BnGsYlr7V8UVYyxog3QLEmpVhccCfgD0L3lP1yuIyqkup8XJYRhmaEtdTZb8cVYw4XxowMwhWALXxcEcILzO6i9oP1h7Dae42XtNtLzcarybd8MI4BYeAtZ1ui9fBymGxN5kJbDtzPq9bKo5j1h4BnLlaCKlg41FJbaEJC9LRTo2qZD2guXQFxF0QCcTkIf6sZ3LOJro304ILuPbRbtvnU7yosH5uDGHwPQIrHAB9ERtaJ%2Bug8bsWM7N7PEZUb0ZpFOWHxYPRrGjFgnTChOid1-2hcekXg53o13v3i2IG9E6T78M%2BL5XxvlgYupcxwVyrjXRqm8X7bwjM3VuHB25TxKD3PuH8B6LG9N9EUAD8CX2vhwMKY9EHIK7jPYqLV56L3%2BqvDg69qwGwSg3NOIdd79ygrmFGf9fAADUzRIWZPAZkeI754Q8o-Gg5MIZQ23G-TOGDOGBG9MzHhE4OYRW9oIiUIixEPxgYNUWEZ2GKIysomWPDOawCwAAcWwG7D2iAvb2D0XRP2BjIa7RqnDOm4csHWxPuPJBzokL3mgAAayQovcJ2ADCYylPgbCnUS4%2B1ur1JhFMWFARNqNDhZjD6RxFHOBcITsDcTdL3ek3N7aUFEN7B8EoCpgJYFAxYd0PGyOSjTHx6Y-G5jziKAA0ogcICslZunFAk7CpZiaxSfoHWBrD5F70wYUfszUeGqxvAYIgriFSSIgNI1O2SQ65NMTnAcx9CjwREZgM%2BeIS5uiwHjRAzZbQIDLGkkmHSvGwxWUolQ-Zf7XIfJwPElB1GUE0fYGU4LCBckcFjWAaMnljBBoUdpGSZG-O6f8-JEh%2Bw4JBa3MclAxjuE4viJpZdqnMjqaFWZpMpHC0Ma-PaPSux9IHNw65JCXClgdIk5s8B8ABVgAYERxT26Mp%2BUY7xeKLmAtUdczmRD8DNkwFsohRApSTDRCVb5WLjnQ1OW9eGn86L9gsdc4ZoyJRPPFFE-QjAZVGqySasWZzzWrIHAE65oT9DhNLAYM%2B7MJRzjCrwPlwTEwOM9hKhlF4wZuq3ks9lCqD4EsKf6he7VECqoMNAFgvNpxLXgDpWp9hubQGMHoESqS2npIDsw1NJzPVmt8RaxY-YBnXOTMWiK7ykCuubf1TEypNRMgMBOCVRJ2lqiAA) might be to move the comment above or below it.

Are you interested in submitting a PR for this one?

**Comment by dbrattli** [comment]
Hi Florian, thanks for the info. Yes I can try. It would be interesting to learn more about the untyped AST.  I'll have a look at it (next weekend)

**Comment by nojaf** [comment]
Cool to hear! To get started, you can check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#getting-started-with-fantomas) and take a peek at the [YouTube channel](https://www.youtube.com/playlist?list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K).
If you have any questions, feel free to reach out.

**Comment by dbrattli** [comment]
@nojaf Sorry that I didn't have the bandwidth for looking into this

**Comment by nojaf** [comment]
No worries, this would have been quite the challenge anyway for someone new to the codebase to pick up.
That being said, I'm working on other aspects of this project. So to see your own issues moving, I highly recommend scratching your own itch 😊.
I'm going to release this shortly as part of `4.6.2`.
