### ISSUE TITLE
checking format on CI takes very long when many files need formatting

### ISSUE THREAD

**Issue by kMutagene** [fsprojects/fantomas#2029]
Running fantomas formatting check on github actions takes very long (>40mins, see [here](https://github.com/plotly/Plotly.NET/actions/runs/1693635573)) when many files need formatting. this is not the case when there is no or not much formatting needed (<60s, see for example [here](https://github.com/plotly/Plotly.NET/actions/runs/1681984592) or [here](https://github.com/plotly/Plotly.NET/actions/runs/1653659318))

Is this a bug or am i missing a specific option to prevent this? 

Here is the fake target that is running ([build.fsx](https://github.com/plotly/Plotly.NET/blob/5f0c565175713ca1f334e2df783e8a233b751bb6/build.fsx#L185)):
```fsharp
BuildTask.create "CheckFormat" [] {
    let result =
        sourceFiles
        |> Seq.map (sprintf "\"%s\"")
        |> String.concat " "
        |> sprintf "%s --check"
        |> DotNet.exec id "fantomas"

    if result.ExitCode = 0 then
        Trace.log "No files need formatting"
    elif result.ExitCode = 99 then
        failwith "Some files need formatting, check output for more info"
    else
        Trace.logf "Errors while formatting: %A" result.Errors
 }
```
It is using fantomas 5.257.0 on .NET 5.0.302

**Comment by nojaf** [comment]
Hello, thank you for bringing this up. I was unaware of this actually.
At first glance, I don't see anything out of the ordinary with your FAKE target.

Your Fantomas version (4.5.8) is quite recent, so I don't think updating to the latest version would change anything.

I was not able to reproduce this locally, unfortunately.
I've compared the time it took when I just checkout out the repository and when all files were changed:
```fsharp
    BuildTask.create "Touch" [] {
        sourceFiles
        |> Seq.iter (fun path ->
            let content = System.IO.File.ReadAllText path
            System.IO.File.WriteAllText(path, content + " ")
        )
    }
```

And it took the same amount of time in both cases (around 32 seconds on my machine).

@lpedrosa do you have any thoughts on this?

**Comment by knocte** [comment]
Maybe the bottleneck is somewhere in the implementation of the `--check` flag? To check if this is the case, you could try another way of checking the format: do not use the --check modifier, just call fantomas to change the files, and later check call `git diff --exit-code` to check if there are differences.

**Comment by nojaf** [comment]
Hello @kMutagene, I believe this issue is no longer actionable from our end.
Feel free to re-open if there is any new evidence.
