### ISSUE TITLE
Comment after [] is lost, more common in records

### ISSUE THREAD

**Issue by cgravill** [fsprojects/fantomas#2043]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMcCuAdlmgJZFgDaAumAPS26wC2Ti5AFogE6JgkDOYdLH5YAOlzEEIEALyUATFQlSVRAJ4AHXgFkEidGFlqZYYGACS-AEJ5%2B6tACNYsQ-TAAVdgMYs2OfjwuADcSYMR%2BE1NPWCwAQ3R0dQA5WC4mBIBlLDwAM1y0AAprRDiuMAAqMBKyiwJc2ABKIQEcdwAxMl5OHjAsFyjTAAU2eDIAcxqufiKpyurSrjqG5uo6BgBrRERNQSxOXCCecinBOIJ4ME0eAFpoTmgNvnrYMEdEBt70OMJ7icGZOEuOoLExNGl4kQvAJUlghnF%2BNAEgBhBGINBzNbuXL8dhlTToMjEMb8OKOTA3QkERAAiDuOJgXLfcZ9V5IzQ5XrQLgkLAkJGGbhcNL8AA0YAS-FeuS6tLAABEBAisNxYHYAEoGUr8RAAeVy2TyBTeLkMAF9IKLwFAdVg%2BQRxvxUJRrRBQNEoAASLBaZBoSBEy2umSQT3BBJ4P0uj0QAAMVpjUDqSCImRIAC9kAmYwAWYMQKjBs3Zt35r0%2B7TOgNEIMe0Ph9CR50UMsQACMJeikB0cQAHgAZLr9tjjfa1mNthSxsuF0zF4Purve31V0b6wfU7LqTDj0z1iNRluJhSdvcAUQu666u676FykBnRc7i73y8r-ucrhvEH3jcPrbAABmU8QzqHUuCwToCASZJEAAdypLMAKwLhI0fOdnzLUMKyjSBP3Qb8vQbJs0CPXMQJ-TJECYflXFgAgAEEsAveAr2pQiIFySVEHQmR51MF8QzfXD8MI38SOjGMAFYKKgTJNDiaBEBKT5EHhLg4lYFUuA4vpUJ4j1Zz4zC62EqtRJA8T-0TAA2WTIHkxTlI%2BNJEH7WA4O4JEdTqYJYCRPl6N0lC0MMp8FywsyP1NMSwwPZsAIAdnsxylJU1yAFVNG0LhvMQXz-LiQKCF0rj0B1XiIH4mRBJ-KKoAsyLiOsmMAA4UoUtKXJ4ZFvn4fhkXo0RUOgfodNksqKrCjCItMnDzJiyy4r-BLEwATg6pz0p4HRqPecaAMmgzoiMqqTKXeboq-JbmtWid4wAhzOuc1TBuEEqJu4yqwGq0s5pXK6CJu%2BLSIAtsO0e1LEAY3JtMGlg4mC-Tvt%2BsxIsuhrFqakHJI9SdNq61SqJouB3tKr7puM2aLoBzHruxlbQcTNtgMh56Ye04naLJ2SQuO0xTp%2B87XwxvCsdM26mYnHN7OTfxdQIDxgQAdV5dhyfK-mZEF1HavLWmxfpiWcbIvGZLZpyGOFQh4HlAwSBo7SkdCk7woE9GDcDYHGdx6I2zsx6e17Cxci8Ngz01zJ2AhVX4DHWSc2nSmzupkXPZrb2JNNv3ksDvtlhIXtdRyoq0jPXtrgifgSCC2SpKT12Zvd-73ygL2GazsH2rz3tNTgLh4Fj%2BOAMTlHhaE0X2%2BNn3s9MNsNp7vu0ngZI8CYfb9QsFUmCdWS2zH1OJ4Npg8HQPlEPaNIMjtbgPBXTOWo9Kd7KXgedFP8%2Bukv9Iiqd%2Bz7jKIpbSAB9OCJA47qwPs3GmrdqxYFipLX2pgFAQ0TN2PsVsNLqF1FwQcogh7qwTg3AWbsaoe1gVPJciDZ4yAUCeHumC4jYNwa0Ve69uCb23rvMGUCyEt1wifM%2BJAL5X1-rfe%2BHdH7RAUKzNBjDmF4KwO-IRIif43wOmggBGlRrcFAeAscvC-owNwpQ181CAIKBlj3AAageawZAxgOgIbpVqxDtakKMWnChGdJF3SfubNBQd2i-GKvYi4ExnFEMMWjfhVZTFCXMceAOgS%2BzyliAAcWwOXSu-Ua4EEiQBeu0S9bYQNo1aendjy50CR-YRXRrDCEeNYbRWwsD8AVpkTSiA3prw%2BodCmjcqbQK8SJcWVCTYWO7mg2CCF6nYE8mwO%2B2g7YygILyPJDELi7XYdMDWU1Bkp2GUfWB5TxkzwsQvNBABpbYmgQ5hwIHUTprANxIUTEdYp5CTE%2BIqVI0wgEHopN7BHGiuICmJlHsnIWh86qi1OWYiZiZAKoJjA5CYmArbjDXv4ZWiBHB6CQHsrWBYPExOMQtI2ZzKkxkAvQuRhJxgEGCQQUaeS0yMqKkERAHhYByyIEVPJRLPmxMBggxFNLZGooYmfbg0E%2BThHcg6bZ%2B0VlkHWUNIVULdZfIpUDXxUsPSASsTUoRrz%2ByaUcPAOIvURATBmYhTVBzoVHNhWUsZCLzlIoCaixUpJySIBBQIdgmR1D8t7I6khTc%2BHktFQ-Px0RALJNRTcnYfKsB1Gaece4Eb3FRs8cc0ZlKPXUsNdU1FDTzgbFefwK2aoLiwVEIgeAyjP7UmyTwXJGrebIy1ePV1Jz3UJPFYaqZ5ayjbUQL67kDsyBFSbRlNZ9E7bQG%2BBpYqOaSV5rJSM3VYrPU0suai7IPJRoEreTGD5WrrRUGzAGfg7Rq7Og%2BWaIAA)

#### Code

```fsharp
let count: int [] // comment here is lost
    = [2]

type Model =
    { IsBusy: bool // This comment survives
      TotallyNormalStuff: (Bear * BearInfo) list // Fine here too
      PendingBears: (Bear * BearInfo) [] // keeps the current Bears and pre-check info before launching
      veryImportantThisNotPascalCase: Bear [] // fsharplint:disable-line
      // a flag to capture critical errors, also fine
      DisasterousReleaseOfStuff: bool }
```
            

#### Result

```fsharp
let count: int [] = [ 2 ]

type Model =
    { IsBusy: bool // This comment survives
      TotallyNormalStuff: (Bear * BearInfo) list // Fine here too
      PendingBears: (Bear * BearInfo) []
      veryImportantThisNotPascalCase: Bear []
      // a flag to capture critical errors, also fine
      DisasterousReleaseOfStuff: bool }

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [x] The formatted result breaks (linting) my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by cgravill** [comment]
#2001 looked a bit related

**Comment by nojaf** [comment]
Hey Colin, thanks for reporting this issue!
It is indeed a trivia issue, somewhat similar to #2001 but they would need a specific change to be fixed.

This one is a bit tricky, but here goes:
The code comment is assigned to `SynBindingReturnInfo_`.

![image](https://user-images.githubusercontent.com/2621499/151405471-3c7552cf-bbaa-472f-9bca-68fcef728ccf.png)

That node looks correct to me, but we lose this information in:

https://github.com/fsprojects/fantomas/blob/0609000be1dc508840cc78877f16d418a6584639/src/Fantomas/SourceParser.fs#L524-L534

The underscore after `pat` will contain the range (if present), it should be added to the active pattern.

Once that is in place, you will need it in `genSynBindingFunctionWithReturnType` in CodePrinter.

You'd need to update:
```fsharp
    let genReturnType isFixed =
        let genMetadataAttributes =
            match valInfo with
            | SynValInfo (_, SynArgInfo (attributes, _, _)) -> genOnelinerAttributes astContext attributes

        enterNodeFor SynBindingReturnInfo_ returnType.Range
        +> ifElse isFixed (sepColonFixed +> sepSpace) sepColonWithSpacesFixed
        +> genMetadataAttributes
        +> genType astContext false returnType
```

to something along the lines of
```fsharp
        ifElse isFixed (sepColonFixed +> sepSpace) sepColonWithSpacesFixed
        +> genMetadataAttributes
        +> genType astContext false returnType
        |> genTriviaFor SynBindingReturnInfo_ newlyPassedReturnTypeRange
```
 This is pseudo-code, but you get the idea.

Are you interested in submitting a PR for this one?

**Comment by cgravill** [comment]
Thanks, that's super useful pointers.

I'm up for giving it a go but will probably be a while until I get around to it. So anyone else is more than welcome if I'm too slow.
