### ISSUE TITLE
Match statements should not be split into separate lines between parentheses

### ISSUE THREAD

**Issue by ghost** [fsprojects/fantomas#2044]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAYrLGALwA6ATmQHYQA%2BYAQgIYViwBmYAltepTXpNmALwHVxAG0TowHIqXEQOAV2rR03WBKq0wDQsQAUARn1gATAEowAWgB8YdBRWIl5gPp3HHZpIDOyAA04FCB6JrUAOb%2BqGAA2qEQoBCpUAAkWLhxkLzokCFpEJDpAG5%2BrnGJRakADIU1UACS1Eh8AMrcIsFJRQAsvRAAur0Avg3JgxlZyGi5fAVTJeWSlWjVjSYTRZAAsswAHgAyvIhHiNHoABaLjWAmFrVTI2njvSk7mTizUBfwAPIcE7URDtLDSW6fFZrBJTCAWbZpSAAUVagOBPTukEkHEgzzG2w%2BSK%2B2TmACMiJJIcToT8NjUAMyI1KQFqBCjofC8PwAOUQAHdJKdqUVnK58a9CUsST9IBTYFTmcsKnS4WA%2Bsziu1EABbbhwSTaACC6FRAKBws1cj8gQlqTeaSJLJlOXliultKqaoArFbIO1sMxoIhGIh5BREAAFVjMHUyRAUEVpMWIO0QB2pJ3FF3kylJjKe9ZqgBsfoDQZDYdgEaOsH5CegzECLVKsEbmm0%2BYgKbTYAzkxqJRmrrzSrKKq9dwA7GXA8HQ%2BHEABVbC4CiN5vUVvtrTULvWgKpmove1Swc5qBu-PK1aqu4ADlnFYX1cQAGFJE3-G-tP4xRpq33XxD17fswCzaZvhHBVr3HW9J0aABOJ95yrCNdl1MkEyAm0jyKE90zPT5h1zGCx0LWE7hMeo1X9OdK0XH9DT3K1gNtY8CXeaUSMvUcPQnIsqK2Wjy2DI0OHQBMfx1HVmH3HsOMlLjzx4uU%2BPPCj6SKB4UIY19tT1A1O1Y3DQKI4lVKvciBMozYmRE%2BjxMkigDP1BVjLVBT8M4x1uKg0j3Q0mytLSEwNVolo2nQf5qAAFQoTAAHVuGuHCQMU09lOI-zeLI-j4MEzZfQcisjQoWA1HgAARRAhT1Zz5JcPC0gIvtzOdVS8lgzS1RMUtaP2A4mg4WKrguZFD3aK5q3QZL4FSq0%2BieDLCKyiycvmfJrIK2yahMGcBsOFoOG4A5-jXZh0GrZEDmwCN-H8Xd929ZbvKU3yVI2rrtphELUhMR9DoOAAlRA4AoeA5oWtUlrMtaOq%2BhYfrvTZkKB0HwfgHkVB1LCKEBJpJJ1WIrRMOGPuy0koB1FRJE0IUQUIChZIiBNYqg5GEJqR4-Qx6t4F2Wn6dOJmWYav1oCuGMNATDx%2BW4eabnJzM-KpzbuuCtULGErFBrKihmEwf4KBOP8oZuRbXpanyVc%2BtXvvy36tYRIH9cN43TfQbHcYTAmiZJ3rlYHSnZRpunuAZxBRcu5z2eyTnCu5%2BysTdo2Te4P9BfDyPo9ZxMJalg2ZYoOWFdSoPwNV2UHaCna-vhcLdcOAA1FVGF4eBeCic393vK3UlasCIKHRGtsdlHueKpuDnwNQNF3dvWi7nvLYr4eL3VhPdqKCx%2BunqrYHQABxGQbruxAHt3FefX74YbeD9a1as8euZ3g7daFiPTkYQ1oAAa0YEXP%2BMh-AxXaLGd8CocYsTVGxZqA976VztrKZ%2BtcnZ3AsIDLEfJBTfxkPWC4cdEA1ROtQFKu4jStAwj7CgAc7hwLXlXaCgUoSawwWjLEABpRAiBsDDVGhcFo4C4wYjSuxN6mUKaP2rkjF%2BicigMhotPCaep-BXGvncWGK02rw2zJZdSrC65qgZDrRo-ou7SDKlEHGFxZqIDJLsBAmJGgMO0UPJhAUNZGLuAyF2KchRRGoLPdQHZqCdECZdFQEZYqwEirYy6T0TLpQkatKRCMn4GJpGwxoDJk5mKNHTBM1AEmlDONoKI1C8YkN4OQ38Yj4F33erbEOzCvHoJyY3MxWdNAYiOLGMk8BmAflgI9aIODI71MYcg1pW965gAZFPMxVUM7MDJNIFRGcrjtEwHwQ4ky3HtT0RtVBhj2mMj3mY7hvC4l8BaIA5g6gLawNMgc3RkEMl5TQRPBR78zE-weX-DE-gyoVVaHyP8iABaf0jmfe6j06lWi8tbJpD90koMyc6HqPisF-NYC%2BCMyz-DQAoNwPUxTJLwCXGQ7QNVoCfgNqE-ZKSdFpKOR8lhWTvE5I4WYsEJKNCOKQEy5F9pQhDAaLkfw%2BBHpxAYaMIAA)

#### Code

```fsharp
type Foo =
  | Bar of int
  | Baz

let foo =
  function
  | Foo (1 | 2) -> true
  | _ -> false
```
            

#### Result

```fsharp
type Foo =
    | Bar of int
    | Baz

let foo =
    function
    | Foo (1
    | 2) -> true
    | _ -> false

```
            
#### Problem description

When I format `match` expressions using multiple sub-cases in parentheses, Fantomas formats each sub-case as though it were a main case, whereas it should not split short parenthesized expressions across lines.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.

The main problem here is that Fantomas has one way of formatting patterns regardless of where in the syntax tree they occur.
I believe some separation of printing patterns in `CodePrinter.fs` might be interesting to introduce to tackle these kinds of problems.

Are you interested in submitting a PR for this?

**Comment by themadpsychologist** [comment]
> Are you interested in submitting a PR for this?

Unfortunately, I am not.

**Comment by nojaf** [comment]
This was fixed by https://github.com/fsprojects/fantomas/pull/2407.
A regression test could solve this issue.
