### ISSUE TITLE
Unicode string containing "\000" is replaced by null character when being formatted.

### ISSUE THREAD

**Issue by ds185357** [fsprojects/fantomas#2050]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAcrOvgK4A2Zh6AWogE6xgC8AOnSwHYQQDO6AhugCW0MAFtEYgEb0wAZXR0hHAOYAKAJTM2nbnrABBOlIB0AEUQAzfuXQmFS1Zp1d9EAD4A%2BQ8ZNj%2B2ABiQmTosmqWJFz8YAC03kKWYEI8pBRgMegAFohcLJD5YIhkPHj8WhFRYOhx3hxEYGp2AMKwHALKPGr5LCwADAP5GsOQADTgUKXowqo8qGAA2hMQoG6QACRYuPOQyuhjy9wbAG78ZCTIaEtuEH3jN1AAkhxI7XJCAF7I9zcALIcQAC6hwAvj8VgCoJscJcoHsDmt1qdzrDrjcAIzg-SQACy-AAHgAZZSIQm5FTZBEYgBMfUhwL0YMOq2x0O2aEguXgAHlLMSOIgFJgyN9ISczhd5mi3NSsXpIABRF68-mih6QMiWSD00FYlnytmwyBSWCwMhUg3IyVXSEQADMcqOz1KdHQwQ4Z3wiAA7mQSRb9IoLjrGXqxYadiazQGIOKUVLbWBfo7Y3JJCIzW0DOglTy%2Bf6U2BrCVECHuEy9PqjhGOVHzY649bFomAKyFyBybD8aCIABCVlgdEQAAV%2BHR%2BBIwnQY9wg6W3Azy2HEVsjXWZ43UYmAGztzvdvsDoeE2De%2BjQfilZ7HWAX4RtGcQOdliAV7hV2M1qDrhtIiVbh4AHY9y7Ht%2B0sQdEAAVWwXA6AvK8OBvO8hAfQti1KF8wDfCEVxhSNTXrcMrQAm4AA4QIPcDIOaMhLx4VoOD4OgSGgdBB0fIszkwhddWZcNVwI6NfxIhMHgATkosCj0QHFJBkad0O4%2Bd9EXV9l1ZQTa0Ijc-3jG0HnRO5Ew7UDDwgodWjINDEwwlS9DU7CNINLTvx0kT-zEjFMRM-cewMSwp1aMR-E459eNDfi8PZNzhOIzyDJpKTzMgtMxAzayOE4uysJwsAPyhVzjXc%2BL9ObQyHV8syAqnNKMpsh5wtUvjKwE-DtLixFRMStx0WTEznledBuQ4AAVOhMAAdSESklJLXLnOrIqf1KptpX0dE2yqg8jFgKJ4AsP10qnMKWPs7hHLygqNiK%2BEPLK9a9HRXcTLxfFHksUacg4BUSzkLJB3Qab4FmxNfjpCKlyizT2rhdpdO68qMWA16CWeSwhHxbk4MEQcFXxbAhx4HhUKywsWwh5rIta6KjTu1bSN6ijUfxAAlRA4DoeBgdBh5wYW6GXNh3Z4futbE3RSSWfZzn4FIaR6F5R4wjEOZC3RAWaZhmLIDEWwQhJQJB38aZ6FG-CxcZ-RaXbGXB3gHF9b9AUjboE2TvbaAsjHbspwAfW9IQQaybVIfUwWluF%2BmuoSpGZR89U3qMcdMG5OhiT4HmQ8Lfmw6ciPP1u0WGa8mVZRZ5P%2BFT9OUmIEgFboJWVbViXNffNqdb10IDZd43BCnc3tkt0vrcq9VK%2BrjP0Ed7vncQV33foTiYG98c2PoAOg8pNvcO1uni5jh7E2pfrE4JAA1f9e2UeBlBULPOLIymHJa9vaZ2aPWURx7uGpLaz-xIEKIbFSbXxeHfB%2BOdn4XVfrvIWOtP6Wljj-CA1IXoALMEQAA4ogHMBMiYkzaJA1s0CgSwPyh3NcJVD7iweNSFGicnYkl7NZaAABrXsa82G4J4CNOQE5EBWXrmTWyykd4UPfh1IiNCrZ6GpMzdUXpfTMNwWeXIg9EAWAxhwGapMDAvDkg3FuDwcp5yupQoS0iv7IOPlLdUABpRAiBsAfS%2BrkZ4-CJCqmymIsxi1C5RwPtYo%2BDw7TGQAb9dKPAsjEL5qQsAl1-GFWFitGRI89B2gTjcDsd8RRGBUPXXIQNEBSBxAgNUNxTFUyhlreBVDOrBNoTcO05dx5%2BhUBwIBHAQFtHeB0wQJAhyjVgINIpghSY%2BPmn4guySdapMabI7gdox7ZIMKEegHphDHFJG0FQhiFJaOULotoxjKm%2BOqeHWpkc5nUIWekpZp9skz2EKqQkE4pDwH4LRWAJNVBKLnpMniFz85XICTchpSCQnNP-tkswKR%2BBSBFJElIWQ5CYHaASQF50yHUzfnvSxCMbGhPQdkxxzjRntGeJw-g3Ts6iKmcC8xkjYpWMhU0twdoGHZJYTSthqoeC7X2l6PgiAHZMIFPjQmiBiak1OW4JqL9cVwOufU1l1Zv6JjtAo7lY5qJDjhTwaASh0qbNFVBHRbQLDQDouOe8IiTHnMVTUvFdSCXDx6voO0djskOBENPcpWLcoTEBD8XYPBAgk3mDlEEQA)

#### Code

```fsharp
type NotNullNotZero =
    static member String() =
        Arb.Default.String()
        |> Arb.mapFilter (fun a -> if isNull a then "" else a) (fun t -> not (t.Contains("\000")))
```
            

#### Result

```fsharp
type NotNullNotZero =
    static member String() =
        Arb.Default.String()
        |> Arb.mapFilter (fun a -> if isNull a then "" else a) (fun t -> not (t.Contains("�")))

```
            
#### Problem description

A string containing explicit unicode character "\000" is converted into null character during formatting. The null character itself breaks some text editors when the file is opened.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas version 4.6.0

Default Fantomas configuration with these extra setting:

[*.fs]
max_line_length=120
fsharp_space_before_colon=false
fsharp_strict_mode=false

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello,

Thank you for reporting this issue.
I noticed the settings that you've mentioned are actually part of the default ones, so adding those to an `.editorconfig` is unnecessary. For simplicity sake, you might want to keep those out.

As for the issue, the string content is not being recognized as a trivia item.
In short, we cannot always trust the string content that we find in the AST created by the compiler.
So, we try and detect this using a regex:

https://github.com/fsprojects/fantomas/blob/4a65cb4c1f39475b397632376847df75864b083d/src/Fantomas/TokenParser.fs#L524-L525

Adding `|0` there might solve your problem.

Would you be interested in submitting a PR for this?

**Comment by ds185357** [comment]
I have created the PR, but I could use some guidance how to create a better unit test for this fix. Thanks
