### ISSUE TITLE
Type parameter comment lost in formatting

### ISSUE THREAD

**Issue by bent-rasmussen** [fsprojects/fantomas#2052]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAxWsAPAOQAqYAFAFRikDyAInWFQJQB8lrYAvFwDoAnfgDtIAGnBQAztiwBLEQHNpqMAG0pEUBF1QAJFgCeAB2RpIirBK27I%2BgG4BDdAFdzG23oAMkvXsgASREkESwAZXkAL2Q-fwgAFi8wAF1bAF847WT7YzM1SzCbePtnNw9NeIgARiz-SABZJwAPABlFRFbEZSwAC2Kq6oAmb2S0vUzbHXrDUw9Ibvg6ADN2kURw40wBgMcXdzVKqqG6gIBREJW12OSISHRlyDGMuundvPmAIwJ0Hbs98qHW5gADMpzswVkgiwuEULgAcogAO7oDp-PRYQTuZ4TV45Wb5CzfWC-cGlfYVYEJcF3cKIAC28jg6FgIgAglgLktVmiaWBli5ZDjdJM9G9-h8CsTSfiygc0Ed4gBWPmQcImJzQRAAIUQy1ggkQAAUnIInPTsIhBOjdJjsfFxiK8SUCV8fjbyYCFcCAGyq9WanV6g2dWBIq3QJyyYIOWCRhSsm0QO2IYUQUW6cV3V1S91kgHyzxVMAAdn9Gq1uv1hoAqiYzIJI9GRLH4-JE3yBeghQ6XlN8ZKiXnZRSgcWABzlwNVkMAYXQUeks9Z0jt0CwBqT-MFqd7uP7LsHUGlHoLlOLAE4p5Xg4aGgzPlat12e-5HennTMj5AT-m5efBl8YE1QrINq0QZcWTETsdzTMAM2yQ85lzElT3-MdBlqYCAy1NlliwK1l3peknC3FM4IQsAswMb9fxHL0i0GE5sNAmdDTpRlmQ7YEX13N8%2BzFAdkKHVC-1Hb1i2qMEWMDPCCMEDimRJbji3IvcnQPL9hOPYcXXQiTBmpYDglCLA6BEUhBCMAB1eQ%2BmfWD1I-TT3m0n9dJmfTGPiaoVRk3DBFgVwQgYRBUUZeSyKxPi9HfeDP1cwkoCsNDxO8-xqj9YCmmaQJllIXpujObsNl6A0sFs%2BB7L5BJRic%2BKXIlNyUrEhjFQystspaYJlnkZo6AbJwN0EM5mhMQ1pGkdtoOBJU6v4-dBKQpLCmsVrC3avRqknLrmgAJUQOBBHgSrqqpebYoEzMhJWlr6I24FqivXaDqO%2BB4VcelH0EFZAgI%2BlVD5aoKISpqVvpVx0AUVF1nwQQSKweTSGQ9aAPiEZVVeg14AaSHoY6OGEci1VoF6U1NXkgB9JF5Cq-oQca7NvzuvS0s23Qhiw4tGhaNlBDNIw6EEdpV1O-oaou3Q4so6jcmaopUYw9HmO5nK%2BYFoWRawD6vqtX7-sBx6GaWrTwbx%2BQYcQQmhqRlH7rR-whmk7n1acQXhfkVdcahi2CYNImnxJsmzXXK1qdp%2Bzjeu5b5hZzy2eBIYjNVloADUKW1RR4EUJQxa3cdJYgaXQaZ%2BW1vtpXHb8lPmlwYL12mzOQhzvOJajxDTdjhWK4M9GsprhhYCwABxbBRvGxBJum1vZsL1Iro7xK3VEnv0r0IZOtV83Le1FloAAa21EP9%2BwaRzPCc0IJJT6ZuLXj26om7l5lVm2sTnbucRFEOl1LBw26ZGZhQq9REHZaabIQj3l1oIQ2d9HILQ0ibJeKEX7xzfsWIYz1uYAGlECIBMHlAq3RggXwtNcByJUH6yxzBYOOuwvLswgCCICNdiqMmkL0GexZapUKfig1K6Cqggi5lUNUOdMB8yUJ9boFVECfAaAgG4cDKH1RlnwkSqD6EJ2LCCFWoi2SoiUCIOuIgG6skiEYoarhDSkFgCZGRQ1poUNfJdRa0dO78MVr3fwIJnb6KhlaEQjiHChmUFA76wDFBgJXM4mKUsF6Pxjp41ejDQTJ1Ed7BQ1xWjmk%2BPAJw85YBTWUF-S2sTeFJI0QIh6Ojq6iIYJ7JwnxMBsM9r0cIRgwgtHKaokuNE3J0VfjUoR-dRG4PwfYsIwQj5OFMeLHi8DXGIPccgqpXi166BBJvURu9Zn72uNIPmQUQiIlXIgHG28OjjwmlNGJfI1IIOckgsGz9qkOz0CCD%2BOzTRsUQA06Q0BBDyEZEEgi8AaygNZKFaAC4zQJlvlUe%2BvTGb9JWoMtBwz4ggiwaIzYQL1wKKQD0x58EpApDiJYaQuAppqHvukIAA)

#### Code

```fsharp
let Foo<'T (* TODO *)> () = ()

```
            

#### Result

```fsharp
let Foo<'T> () = ()

```

#### Problem description

Fantomas lost a comment inside a type parameter list/constraint section. Granted this is probably a rare place to put a comment. Perhaps there should be a general test case to check for loss of comment strings in the transformation.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.
I was able to find a fix for this.

**Comment by bent-rasmussen** [comment]
Amazing response time! 👍 It is not critical to me, just noticed the issue. Thanks for fixing it!

**Comment by nojaf** [comment]
Thank you for the incentive.

**Comment by nojaf** [comment]
Fix available in [4.6.1](https://github.com/fsprojects/fantomas/releases/tag/v4.6.1)
