### ISSUE TITLE
Comments in anonymous record values are deleted

### ISSUE THREAD

**Issue by ArthurHNL** [fsprojects/fantomas#2067]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBbAngIIB2sx%2BusArgM4BKicATvGALwA6THxEEmOAGaxYANQCG6KonZgOkYbHlcefMALAAjcUwlSZbOZG3dIK4ufNrgAHytq%2BAekdgAKgAsZisADdJ0gDp7BzAAMRE9aVlFSMRgh2cXDxkTX39EIO5eELAAIR1Y2RNY%2BJsAX3NIABpwKBpsLABLYgBzGlQwAG1aiFAQyAASLHwAB2Q0SGasap6%2BQb99Du6csAAGGpXIAEliJGIsAGVGgC9kDZyAFlmIAF1ZsvPe66gh0fGoKZn%2BgYXpJeeIABGR4OSAAWXEAA8ADLNRDQxCtLDuL45QEAJlWzzuagesz6oNeYw6kER8AA8oJYcREAdhphUWp5ul-it0SCmQBRXaU6lnAEYQSQbH3EEEplE97GEToRlzH4stDLHIAZg5cx29SYWFCzUkADlEAB3dBwuVqLBMaQi3Fi56DYbEiaaGXml6-d7KkIXdUQSAHRC4RpwdBkQhYbkUqlm31gQSSeo2vh46z2yUkl2wWXq5mLJUCgCssf9I3E0EQuUQwiYiAACjpxLhsIgmG6IJbrSEccm7d9HVLM9m0x7WTkAGzFg6l8uV6vw2BGlvQcT1HY%2BWDLppkNtgDuIJMQFN8cXy-sZ105hV5roCgDsk%2BnFarsBrAFURmMmMvV8R15vGtusbxugiZdqK%2BJpmezoXsOio3isAAcD5lk%2Bc4AMLoCuNBoWQNAdtAWAvjuwGgQ43aHr2hJQVAg5urmfz5isACcyEzs%2BNZgoGmgtsRCb7mBtoQX2bznlmdFXgx8FousAolihs4vogOGhsQvEgfxZHgamwlOjRMHfCOjFosCslTihhCCFgLY4bguDiDue4HmAR5PDpA76YShlSSEGKsahikBkGIaAQKJEaWo5HOZRErUdKYmXl5XoOICaqmY%2BFlWUwgXBlmIUrI5Ak9kJVEidB8WwdeSVqICPqyTsexYOSxCuEw%2BAAOqNMiamkRFWnHpBpV6eVBlwVVfCAkWaXmUw1C7AAIogppBplDlWuFfCRS5YAnn66YTJ8CWjQKgITrJEKQlsgjJMQnLqQc7gvlgHXwF1sYXFihUUcVMWDZM%2BziYlx33mdUI7IIjSQuSn7iIRTCcpCIw1jQNAAapsYFh9mmCdpJW6X90yHZVx1ISDkIMMw8DPa9ArvU5W07S8sUHRVkljUCLGk%2BTL7wPqVC4NxTCUlsVm4O0saAnT0Wnr9uBUOgTSmjS4RMHZWCZa4ImE6zAqYsWXMsGCcsK3CyuqytxbQO4DYES2AD6RqNC9KKS990t48zI1E2yJmbOdhBMEw4j4OSTCwnhVMom9mO9dj-VuSSHueUdbLsqT-uB8HoeNHhvP8y2Qsi2Lx0uzjP147L8uNIriCmzD6uayzno66lmzp0HIdh1ghuV9XtdqzxFtW4HNtMPbjtdSXce41KicSoDbK1b7UKxLkzTwM0LQRzuCHRxtfWudPCf-VrTdspNS%2BQqEVDEARqOr7sG9b1Hk8H2XM-H43o4hOip0X3NsBYAAOLYHhojRAyNUZP0LLvW4%2B9toDTxrRE%2BX8HDomBr7I2Vc4S5FDNAAA1rkYeeDsA0CagcRsSksx8zRqFPiL94HxzKkOT22s2Qk02IaE02DsCLkRBrMYC1wbEE6qjEg8BOJ5yYEXFYYV6EMwdL9JBn8jLfw5psAA0ogRAIxLrXR2OQpsfJurrVgbHV%2Bbt34E2Ud5BwKoZIX1ukGGg7goErFpp9KKrtdqxSUSw0%2BqofY5H9BvTA-sWh80RE9RAmgwQIH5DIuhHj6YIPcsNJOXtVSp1bqaFoxAr43y3MQI4uSYZUBrK4WA9VIkw1RsYuRKTRLMPSaw1ULcgmEHli2YgNSfDzlaBIgWgjmgiNwnUpJUtvGKI8nPZOqpF5BO7k0Pk0JGyaHgOIDCsAUatE4dXMZWMiqlwsY0gGsyQgqnPkEua2dxCaEwI47O7gDj4H2FCfZMdDlTzfic5BKjbG-yCZo7RVT9g7EIeIG%2BkdaHqXqYwoaTSZkZPOegoJOCIV4L5DQf2s0ebgKsuIzB1dQFIxRqM2MBUDlfSOZMxB0z5Tz1VOw1FOgFI1muTQaATBGhBm6fi18wiyALWgJhQOhT3l7zMQww%2BTDTlItsWooJdIuUEViUgcVpjky1BuOcSYNBQgow6LIsoQA)

#### Code

```fsharp
let myAnonymousRecord =
    let fooValue = "foo"
    let barValue = "bar"


    {|
        // The foo value.
        FooValue = fooValue
        /// The bar value.
        BarValue = barValue
    |}

```
            

#### Result

```fsharp
let myAnonymousRecord =
    let fooValue = "foo"
    let barValue = "bar"


    {| FooValue = fooValue
       BarValue = barValue |}

```
            
#### Problem description

Comments of anonymous records are deleted by Fantomas. I think I've experienced this elsewhere before, but I'm not sure where exactly. If I run into this again on another syntax element, I'll create a new issue.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 1/1/1990

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello Arthur, thank you for reporting this issue.
Restoring code comments is a tricky thing in Fantomas, so there are indeed numerous locations where this is failing. 
(For some more context, you can watch [this video](https://www.youtube.com/watch?v=FCrkUqCCzgI&list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K))

In this case, we are missing a good anchor for the comment (trivia) to be attached to.

![image](https://user-images.githubusercontent.com/2621499/152782455-aa724e1b-6f37-4cdc-8f76-36bfb481aee9.png)

Currently, the comment is attached to the `equals` token but the `Ident` would be a better candidate.

https://github.com/fsprojects/fantomas/blob/896bc778905c270af14bbfd1d65b31fc9324cc94/src/Fantomas/AstTransformer.fs#L637

would need to be extended to also capture the `Ident`.

Next,

https://github.com/fsprojects/fantomas/blob/896bc778905c270af14bbfd1d65b31fc9324cc94/src/Fantomas/SourceParser.fs#L1566

would also need to capture the `range` of the Ident.

Last in CodePrinter.fs, all locations where `AnonRecordFieldName` is used, the `!- s` should be changed to `genTriviaFor Ident_ identRange !- s`.
That would print restore the captured comment.

Are you interested in submitting a PR for this?

**Comment by ribeirotomas1904** [comment]
I would be interested in trying to submit a PR for this.

**Comment by nojaf** [comment]
Hello @ribeirotomas1904, wonderful to hear!
A good starting point would be to review the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#getting-started-with-fantomas).
And if you have any questions you can ask them here or at [our Discord server](https://discord.com/invite/D5QXvQrBVa).
