### ISSUE TITLE
Problem Merging multiple compiler directives code

### ISSUE THREAD

**Issue by Rajivhost** [fsprojects/fantomas#2068]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview)

#### Code

```fsharp
let Ok (content: string) =
#if API_GATEWAY || MADAPI
    APIGatewayHttpApiV2ProxyResponse(
        StatusCode = int HttpStatusCode.OK,
        Body = content,
    #if API_GATEWAY
        Headers = Map.empty.Add("Content-Type", "text/plain")
    #else
        Headers = Map.empty.Add("Content-Type", "application/json")
#endif
    )
#else
    ApplicationLoadBalancerResponse(
        StatusCode = int HttpStatusCode.OK,
        Body = content,
        Headers = Map.empty.Add("Content-Type", "text/plain")
    )
#endif
```

#### 

```fsharp

```
            
#### Problem description

We got this error:

System.Exception: Fantomas is trying to format the input multiple times due to the detect of multiple defines.
There is a problem with merging all the code back together.
[API_GATEWAY, MADAPI] has 21 fragments
[] has 22 fragments
[API_GATEWAY] has 21 fragments
[MADAPI] has 20 fragments
Please raise an issue at https://fsprojects.github.io/fantomas-tools/#/fantomas/preview.
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message) in D:\a\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1439
   at Fantomas.CodeFormatterImpl.format@410-3.Invoke(FSharpList`1 _arg2) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 436
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 465
   at Fantomas.Async.map@167-2.Invoke(AsyncActivation`1 ctxt) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Utils.fs:line 167
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 105

**Comment by nojaf** [comment]
Hello @Rajivhost, thank you for reporting this issue.

I was able to reproduce [the problem](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMB5A1mABRwB2Wi5aAzlgE4CWpA5gJRgC8AOnV6QPT8wAYgYAzMAEEACgEkA%2BgHFJAFQCiAdUkBNMAB89YALKSAIjNk8%2BECBcUBDCgHd7ATwASWLAAdJ3hgBqAEzSdLAAHq4ASojU3rCk1IhEVqQ26WAAyliOAK7UAMIIiJxgTDiePtl5hcUAdLgA0gA0qRk2AEIIrqVkFOStvGlgghCiEhZKqpo6be0j-O6I9kh01KVG9t51iAC23liudZLw8CmQReSUWAC0Kq7eiFyQzWDPFOFY-N7o9kzPrDmoxEiHQSTm7SWK0Qaw2Wx2%2B0Ox1O50u-Vu90ez1ezy2PwY0EcDAS-AAVtQEgDUqNhJR4OIIWBAUMaaDwUN0n58YSsMTSAAZWArDr2X6kaAwmJxBJJFIc%2BbVLD5IpIUrlMCVbyK5X1JqDazzLrwHocMB9a764aQ5ardamzbbPYHI4nM7PNHXO4PJ4vN6QD5fH5-UhU%2BUQZl8VmkeliF7gKBJLxMZjUVBgADa8YgoHakAAJIdHmnIOU47m8wA3UW5ZBoTPzMAABmaWYykFk0eumQYAC9kC2GwAWVsQAC6rYAvgObDm2wXvcXS9P0vmq%2Bga2n6-MAIzLtubcL8piIfmUZhYAAWZZ3QUbI7A4-SU9bs5X86LaEgdNwYiPpEQ2SuJg15vmuG51veEBBHuK5qNGP5-v2kEYLG96PjYz7pK%2BNj5oWtZQAARrAsDoCBOGVtW%2BFbu0ADMME4R2SR0FgABiTCigAcogTjoMeZHpPQNZoZOe7YRAuELp%2BREkfxUAUeuVHIYO9HiZkewEiRCSSFgcHwAhfEqWAYiikkwlPqJ94SR%2BhHEaR9GrpRm7IQArIZkCZN49gSh0iBiLAdCINI9h0PYuzYDCskQIJiBmRhFnlnhxbSXZlnyeBGbIQAbG5HleYgPl%2BQFgpODChJJB2FawDyfKRWA0WxRAmEzqliVSbZskOQpTkNgA7Dlnneb5-mIAAqt4jx0GViAVVVRIJLVxlgjF7ToY18Vzq1NkyfZaWKQ2AAc-V5QVw0FL81C1IkgnQFg-kLSZy0ZKtYBNdmLWSVtKXlmBe3zAAnEdg2FYgRh7AREWGYtpkrSJL7vdZkDJR1u3dTuzbIe5A35UNAVFOg82Qw9DUvetb6bYj7U7T9qPtNuu4Y7lEqSGIFB0EUuy7PYtX1TD5lwwlH0U9tqXUxBDbbtBDNYydAVqbsGn46Q91LcTr1gGJcnk0jVOOWLO50VLeXM6zcsKwTyE809sNYfD%2BFC19c6ixl4vKRjHZIOQuCkCodCuBoDCXsr0NW3zNsCwj2si7rzs7q5htM2EuTRqYoIMPLrPc3QQm83F-MbYLS5R11eu09lGMHrIYgqBelBqEtmQXv5WD%2B-AgeGYOd452tedkwX5DI071EZNufXl-Y4QdmIDDhLgE2OP5ajhN4AUXTVhnOZ3Ie52H%2BcI4X33R0P6TbodY-hDEcB0PALdt0pm-pM9asa1Zdv747h-IduANnxf-nwBxuRdjgzoD%2BWQFBdipkMtuVWpNyLk12LkdAvJeL-hYv5TmXgYSYiQgfYuMd2i3jcr-K%2BRhEHIOPGgugGCM5uWgBeYKXlWbyCcAwVuV4YE9zgX3LAA8P4NiCPTBskADySDoCFVwuA6BHloDfK87d742EfrA8S75X79x1ngo%2BNggiSyESIsRbhJHSKwAAoBMJQHgMgZ-DhO9e4IwQUghgKDECUOoVghcGj0paKggbIRojxFGIYLQUhjjnGuMcDQjGdCGE3RhMw1hgcbHNXDmonhnjfoENdno8eARKIdCYPSFgsjar7QUWOa2yTd6pN4Zo5CQQ47ZPCCxJON0%2BT5OjMmYp8iklvRSYudRRcvF1LLo00wsAsCKGwIvZesRqB8i6S5MpD4Km9KqUlSmgyMkZCCKPPRZCnHHg6PjaA%2BAOghROdgagXtMihUQHjQBStCYqy7iTThKitYbNwUM-hp8hFcR4oc7AJVKDYJTlPUgAc%2BSSGjKDMxawg6PQfis9Wtt1nCy%2BVs9IQRv5CMaIgRA3hK7V0oB2G5YVEIIp6Sivpn436gT4fMGi6NGl13ltQC8CyhxLKUW8zWgtI4YpphkGigj5juWTJgURzBAHXA0IgAiRhiiUpeU-VFbV0Xv1qQ2GiuixWSF4swUgzTxS8gSN2Q1eQAoqFgO7a4c1HnIShoixRyLn6qLRQ7elWrGW%2BL1UgmEpAiQVhPAkZgsLgFgqYJCmUyqt7d1sVwiOnzNXfMZVksVITeSIX5KFAi8B7BnVgHMlg-znGxqRaHSpdi7YCpTZimwNEGlitMEE%2BwBFMCsqCReTIrhyDj3LS6ytqzq0epqam2iIyxV4oJba8gHYzn2HFHIx1RMVXKL5UmjVXrx3Ct2WKo5i78CIWoKI2ASd-6xAoPATNBz-zTJXnMmNhlLYVu3lWxNNbk3bvrRAGivz93BRlogFt1BoCMHloGq9I0IUJBTtAX4IVTUOobE6qlbqPlbvIoPZCNEcViuyIwG6iqkADvKU%2BeMo5pwlmoCxOZaZUMTiAA) using code comments.

This is a trivia issue, we don't print the comment (or in your case the `#if`) in

https://github.com/fsprojects/fantomas/blob/896bc778905c270af14bbfd1d65b31fc9324cc94/src/Fantomas/CodePrinter.fs#L2876-L2880

To do this, we would need to extend the `InfixApp` active pattern with the range of the outer `SynExpr.App` in

https://github.com/fsprojects/fantomas/blob/896bc778905c270af14bbfd1d65b31fc9324cc94/src/Fantomas/SourceParser.fs#L805-L809

Once this has been added, in CodePrinter you can to do something like:

```
     | InfixApp (equal, operatorExpr, e1, e2, range) when (equal = "=") -> 
         genNamedArgumentExpr astContext operatorExpr e1 e2 
         |> genTriviaFor SynExpr_App range
```

Are you interested in submitting a PR for this?
