### ISSUE TITLE
type declaration loses 'when' qualifier

### ISSUE THREAD

**Issue by russellw** [fsprojects/fantomas#2075]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WA4gE4CG2AFgDwDkxAfGAO5mIB2YNKcAttsYQJYBnWGwC8YAMqJ01YmABU7OgB1CylpAA04KIOnp%2BLAOaDUYANo6IoCLagASLLjORD6LVduR7AN2IAbAFdkNEs7OwAGbXCvAEkWJBZ0CX4AL2RomLAAFk8IAF1PAF9M6zyHJxCoNw8Y7z8gqrCsgEZS8MgAWWIADwAZQ0Q%2B1iN0MlrWgCYI8sK7Es8bDsccKshWeAB5ADMBlkQJLH8M8vqA4LNmmMn2u0gAUQSdvZOsqH9tyFni9qW7lecaEgACNYLB-BN-g0LqFyhAAMy3OIsPSEdAAMUMAQAcogGP5BpDwuhCMFvvNfqcAWtQeCiRAzo1LnCckiGVIuPw4P4RABBdCPLa7QlssDbAJ6cm2BZ2P5eakuWkQpGMmEWFkAVlFkAkvGgiAAQohtrBCIgAAp8YhcaSIQj02wkskxObSyl1BVApUO1VNFkANm1uuI%2BqNJrNfVgDDt0GIeniPlgsYMIgdECdiClEBltjlDM9UG9Kt85z9bwA7EG9YbjabEABVbC4Qix%2BMsRPJ-ip0Xi-ySl0-RZUyqKsHKqnQstZAAcVZDNfDiAAwv444IlyJBE7oOhTWmxRLMwOKUOPSOvWOfSWmbC3gBOOeh2tmzqILjAu373v98Ku7Pu5Zz0LS9i0nZk3haKIWR1aswzrDceQ0HtDyzMAczKM9VlHOlQNLcDWjaaDg31XltnQO0Ny4LhiH3DNUPQsA8wqLCLxwic8NvKZHwXOsOS5cFuxZb8j1-QdZWHFjgLYj0wM4mIWkRIjq1I8jCD47lBLeOjjzdU9AMkkEQPYm91Qg7JtXiRJ0E2FgABVCEwAB1fgxi-FCdP-PT-iAwzpOWWTTNaLUlPnXlCFgQIEgAEUQAlOVU2jSREuw-zQgDvIMmpcJMq5whaQNoO6HpYm2WzmBYe4%2BwOMhTXQZz4Fc0VshmDy0q8%2BUfKy4y1VyuwWkrQrenibZ%2BB6TZm2IXdCHuHpsDNQRBC7JDNRa0ST3EzDAWqJIrwC3rbBaWdBp6AAlRA4EIeB6sallmvo9KOsynbsp6lkWgfY6zou%2BBsUCd87R2WJyK4UxRRae72vzHyuECfwDAJfZ0VNaj0FU2ysJeqdrigt5IC%2B014E6WH4cGJHCBRhLtWgMgrR3O0AH0GH4Brxghjb9K21xnu6rHwkmQjcaKsKSEwTZCAGLdrvGJrVpSsTcwkzmupkjjAuuG5juF4hRfFoR0F%2B-7CEB4HQbetmFc2tYYbh-gEcQMmKbtdHnEx-DrkU3GtZ1iX0CJm27YdybKeg6nadUxnmdc82MI5tZlf81X9ogSZzOOgA1UsDUMeBDCMKX92nWXbFShimO8TruZVnKWUmYLBd6dFIp3Jas4SXP85l6PGMVuPK4T6u3kmAr656KLYHQfBpBmubEAWpaO5Wruy4LXzxyr17B4GwXidtwYDR5aAAGsDRII-pEEGyJGtZdwT%2B5a3mEpee%2Bwtf%2B43rJJiO3HcXxPfpGjVgztEAxRGiwFyS1eQJFfIbU2D93JrV0uzDKnMiw8zdnzD6uMADSiBEDYBKmVVg8Qr42heG5KqT9LYuHjlCROLJ4Q4yyF0XolVOSCDIAvN4d1Wql2fqxV%2BtCB5ZHhALJhKRjDHDCkYP6rA6qIGBJ0BArwsiPx4Q9KGBlUHr15nYeEGtPYEiMCwRuLBm4iBSEYyagQzS2VgJZWRk0lrkJ-HLdaFtY4v12nQt48IPZMN5HDO0LBHE%2BCGCIIw0CPyEBAYYcBm5nHJWLvLGOyCaRGW0eg3Rqdt42xeH0a0wJ4DEBXLARaxgf52wSZQjx-CvFCJiPCOuTCopCGIMCY4rChBkAkJgJIvQqlqMhsxFB6S346NsPCYeTCcF4PsUkeIJ9iCmOlkJeBrjEHuNSZ412clwjwi3kw-eSzD4vEEGFCKCRcRbkQITHedtp7zUWvE0U2kEGeSQY9EZflBHvwaV-Q5fA4JmhaYIaAAhOTBPIvAesYCRAxWgKuEgKZ74qLWUktxKTPlpO%2BfKPa9DMFiJJFyX2SiBlvLQjofImRXCCHRItMwj8ihAA)

#### Code

```fsharp
type Graph<'a> when 'a:comparison = Set<'a * 'a>

```
            

#### Result

```fsharp
type Graph<'a> = Set<'a * 'a>

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello @russellw, thank you for reporting this issue.

I believe the fix might be quite easy,

https://github.com/fsprojects/fantomas/blob/3b8a687695c3dde97e14f2e96f8c37541bc09880/src/Fantomas/CodePrinter.fs#L532-L547

`+> colPre (!- " when ") wordAnd tcs (genTypeConstraint astContext)` should be added in all clauses of the pattern match.

so unindenting it should do the trick

```fsharp
    match tds with
    | None -> !-typeName
    | Some (SynTyparDecls.PostfixList (tds, tcs, _range)) -> !-typeName +> types "<" tds tcs ">"
    | Some (SynTyparDecls.PrefixList (tds, _range)) -> types "(" tds [] ")" -- " " -- typeName
    | Some (SynTyparDecls.SinglePrefix (td, _range)) ->
        genTyparDecl { astContext with IsFirstTypeParam = true } td
        +> sepSpace
        -- typeName
    +> colPre (!- " when ") wordAnd tcs (genTypeConstraint astContext)
```

are you interested in submitting a PR for this?

**Comment by ribeirotomas1904** [comment]
I would be interested in submitting a PR for this one

**Comment by ribeirotomas1904** [comment]
Is there any semantic difference between those two? and should I also add the second case as a test case?
```fsharp
type Graph<'a> when 'a: comparison = Set<'a * 'a>
```

```fsharp
type Graph<'a when 'a: comparison> = Set<'a * 'a>
```

**Comment by nojaf** [comment]
There is a difference in AST ([sample](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQAuAngA6wwAcQBOVPgAsAPAHIqAPjAB3CbGRg52NgFs%2BVEUVbqAvGADKsLrKpgAVBoUAdEY%2BTPXvAcLGTZAI2VVdRk-LVZdfUNkRVMLKxC7DT95SBAAXyA)).

The problem does not occur when the constraint is scoped to the generic parameter.
[Sample](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WA4gE4CG2AFgDwDkxAfGAO5mIB2YNacAttsYQJYBnWGwC8YAMqJ01YmABU7OgB1CylqvVZcBEuWoAjRszZUDnWDz5CR9cVJlmF7A7UgAacFEHT0-FgDmgqhgANpeEKAQ0VAAJNrIaJD%2B6B4R0ZCxAG7EADYArolh6TEADJ4xMZAAkixILOgS-ABeyBWVEAAsJWAAuukAvu2RPZkJIckNaR2ZOQVF4R0QAIzDlZAAssQAHgAy-oi7rAHoZNNLywBMpT39MUPpUevxOEWQrPAA8gBm%2ByyIEiwuTao2yeUKIUWS0uayqAFE6j8-iCllBct9ILdBmsnlUXrgJgZYLBcuc8XMIWgoR0AMywjK1HyEdAAMX8eQAcogGLkDmTKuhCIUsfccaDxkkiST%2BRBZuCFj0uvTZVIuPw4LkRABBdAIr6-PnKsDfPI%2BEXRB4xXEZfFvKWk%2Bly%2BaQxVgACsRsgEl40EQACFEN9YIREAAFPjELjSRCEGXRQXCjp3C1ima2wnEh2gikK1EANk93uIvoDQZDu1gDBj0GIPlqWVgNb8IjjEATiHNEEt0WtsvTkszcadlOKqIA7IWff7A8HEABVbC4Qg1ussBtN-gto0m3JmpPYx7i14Z6WOsHOqmugAck%2BL07LiAAwrla4JHyJBAnoOhg63jaaO33UVDzTCUoHtIdzxHalKgATlvEsZxDDZEC4AwYz-Hc90qZMu1TZ4wMgCCzxzF1UWWcpXS9KdS1nd9NRYTCAM7MBuxGUDjwHU9s3lMiLlWKii19LVvnQGN3y4LhiD-dsWLYsBeziQjiJ4i9RwuGFBJopCAVQ9USS3V0sMAnCDytI8CS4rM01Iy9yLpLS7xEsTCFVfSGJkoUTJiXDWPwvFlMHEjeLsi5Ok9Wp6nQT4WAAFUITAAHV%2BFOJjd286JfPkxSxk48CgtU6DXWWD1HOEwhYHyOoABFEF5NUXM8xNTOA8yOMsqAUkg2z1I6ZYCyorZtmqb5YpMOF0okMhg3QZL4FSo1OhuICUxAgi8smVJgrUmCYmWCdBp2Wpvn4bZPiXYgf0IOFtmwENBEETdGKNN1lpa1a2vWjrNu6kLesqZYb0O7YACVEDgQh4DmhbXSWuT-JtQiuu2oryPg4GwYh%2BAOXyNCYx%2BaoxK4YIjWWeG1oCjauHyXI-F5f4WWDKT0Bc2LjxR3NoUo1FIEx4N4A2Gm6YORnCGZxrPWgMgI2-GMAH0GH4eaznJz7Ke%2B5HCs5jpLgEnmhq1QgSEwT5CH2T9obORa3p8syewst5NZsv7duiS5NP1nZDeN03zfQHG8cIAmiZJ4rVft9q3mp2n%2BHpxBRfFmM2YJDm%2BJ1hyee94gTbNoR0EFmO44Ty6JaoqWZZchWldS8P2K%2Bx2plT0KdfC4GADV5T9fx4H8AJLb-K8bcyu26-Vhutq1tPKkuUrPe2Fkqu-J6u7qXv%2B%2Bt2uFIdiYneeHrXYgS4Brn6rYHQfBpBuu7EAep719dV7N5y-t8u452dtdS4Dv1oXY4OP1NTQAANZ%2BhIMA6QggYoSEjE%2BEkuNnpGWYitPCFNEYbRUu-VG0IgY8y5Dyf%2B0gqysGTogWqJ0WApSelqOoKFA6h1RMZJ%2B28rK-Q-qiS46MeYAGlECIGwCNMarBajQKjMiNK2FbatQjvXHejdJ7N0qDSbmSxNg7AmmqQQZB76ojhsgvyqC%2ByBTfnvF2roaR6xUU0QIwJDYBFxqwWaiADAbAQCiJYjC9HZWYa-ayJi2FLBpB7FRWpeQBBYAvFgS8RBNDCZdfIIZYqwEig4y6T1xEZQgFlBGhj0EFUwdrRRGdgm0xjCwVJWRDgiACLQ9ChAyH%2BEoR%2BdJTDI4nl8eSUxqIaStx-jHZEuxIwGHgMQZ8sBHqBDwXHZpnjslKVycYjp-jaSzxUdVIQxADDAnUUIMgEhMANB2NM96KC1ZoO%2BhgvxWDaTHxUTwvhySGi1FAcQSJVtEHpRaTIlhTd-oxBpN-FRACXlAORIIQ2lU6hck-IgAWv845X3uo9JpRpZIzIMXM85eTLkFL%2BTgwFfBaIhjWYIaAAg1RlLEvAOcFCRC1WgC%2BEgzYEEMKQcc-RpycmYoWTafeZjOGWMFOqfOrijmSItF4Xo7RkiCBZI9EIjCBhAA).

You could also add a regression test for the second sample although I would accept a PR without it if the original problem is solved.

**Comment by russellw** [comment]
Great, thanks! And yes please, that would be very helpful.

**Comment by nojaf** [comment]
Released as part of https://www.nuget.org/packages/fantomas-tool/4.6.4
Thanks again @ribeirotomas1904 for the fix!
