### ISSUE TITLE
Error formatting defines #if (!DEBUG) ... #endif (no #else)

### ISSUE THREAD

**Issue by kojo12228** [fsprojects/fantomas#2098]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwAFbTAIVgBtEAnWAOgGFaBLRdAFwB0GfdAKGwC3MAFkO0JnlgAzHswCChAHKIerWA0RtY2ArHTceeZgHVEAIzV5E2G7QCezABKw8PDugDmIuhiEtKyXorKAKIAHjzceBwmFgAiiOLoSOjQLgCS6ABWiNA%2BJswxcegJSYHB6GA09EzMAEqOsD7%2BbJxmgYHYCACu9ORMfgw4YAC8vYJ1EGAA2gA8kbwMLmSwvjwAfAC6gfNg9DxSmL5gmAx%2BeFOHR-MnYDYDHLRIDFNg1nZ4Dk6uTzeKivd6MNh6TBxVIKTBDHgACiuNwAlPcHs9QR8WrB2jojCYzBYVPB4EsyJg-PhmJJzugaS4VAQCDsEXxIABiSi%2Bdlo2YYiAvN7YgDKjAAbjJ8OiBRBVKTWv0On4EUKwQwPF4eKtJUx0LheHyhLKjswxQxJSQ8IEORwFGAEQBCZKRKgAVQA4ka5iawC02uLECpaLQlqE5BEyrF4olKh4eDwCMwcu4EwRJPg8JTEO5MBlGiDhYwAGJvOIMVnejnceB2mWygA%2BOzAHD8QT09fmauxhfeCJRLQG6DULiy-bATZbbd0iE7EAADJAADTgKAOBO%2BG6oRariCgDGQAAkPBc4m3kG2y938yP4swtAGyDQC2vR3nK9lkDymR4Io4AC9kA-AUABZXzAPZrwAX2AvdwKPE8zzQC9eCvA9DzvB8nx3WUAEZYIeSBaWiAAZXxEBI7g-B4AALNCBVwgAmedwMgo4YOvfdCOPU9sMgGsAHkFDI0wRRPeh6KOW970fbcX1lRiCKk1Z4CEkSgPAiBIFoBRIFY6CCK4qSeKQqAbFxWhJJvDCZOw%2BSBQAZiUm88gcBgeFLLBaE0AB3ThTCso4eAYR99PYwz4JMvjzLoQKoBsrC5M0sAQOcrSxWwGQ6BMFRtQyNTyLiiBYVoBwwvmDijiM6zEOiiy4ukxLn2SgBWNKoBFIgSCoRAFBnClxlwcsirAYLQoxNiKoi9DavPGLLOcxrZOa2UADZ2sgTriEQHq%2Br0EjYB8xhoEwBw8nFWATpKdARrGxByogSr5mqrSorm%2BrFoS5acIFAB2Datu63qZzdZljtOxBzsuqFYxGkqyomgzOMi2bkPmhqvrs5KAA4Aa6nbgb0dhTrwHRKjG4pdDh%2B8EYeSbHum7jUbMj7Isw777IxABOPHtt2mcMycRhqdK%2B7EfC5GZt497Ys%2B9msbw99ks2-H%2BaJ7Kbva%2BGxbppGqpR6W0dZ9D5aSvD8OVwGgyURh8UoW6Qp1o56bAJ64Kl0zIHRuXbLNhjFMt1XCcQDKstoEwRdp529eeg3Pe9tnfZWhinMD7aVBthhQ7gcPNeSu6HtdxnjOZr3je403k4xXDUuV78zAE9AABV1ksDhaMjp35hdt2wBe%2BLS4Tk2k5%2B6u2rTkgVCYId4FSThMuG9qC-FqbJaZw2oEvH2mtHh5cPW5XiJyBQm5o7hIlFkUaN0Hg2-gDv2pAliV4ZteS43lCeAxyvd6OXD-sPpgaIeQFAcGiAJcQ4weC6BiAQPQfxYbtRas-XWEt9Yez4lvROO9OZ71xoA6IrQ4AMHgHfB%2ByUn6F17v3BCH8sHDxwclXCPMCFEN0PAdQAwhYMCEjkOI2A8AjVwlQ4uNUP7YHhG8cixZdCUATIwJu0tt4c2SsxDabCSGSEkf5RAMiGByMXsraANErjEHLAAfR8hwe%2BdERFvzEZ7ehFcR64KOIxC2n5iJT3GC4ASDAyLeDIXRR%2BKDo5oNjhg88TjjI-1cfMRiAdPFAO8ZgXx-iODeE4dw3h-DBHtWES-Iu9jXqlwkbQHwOi9EGIUUo7BKiFKp0-CktJASeBaPKVI0wVSoSGM-MY0xxRGCWOsR3Ox6D16ONQsohWApGK1ySdEAAarZKgvhaz%2BCCSNbGoTu4x3dhMzBUy6kzIxIxceCzixDmKLGVZGRNybJCWMiJByolHIYfU2ZB8FnJHaB6LQsD4FVHQA81qOyIA91ESUj%2BQ9nGMIUgAzx2jyJUHDtAAA1lQcY6KtB4EbiKHAiAdAPmwHnWU2snn7PfvHcuMSXGqPwZ%2BXyOieo8COtwRR4gYS%2BHbrGFQGRBY2EYHk5K5LCnULjnVWWxy-anJYZ%2BAA0ogNIx9T7cDyPi3A6lO4Ur7hK15X9pkyoeA5JWCyL6ZTwDREFspKFishQPaFNLrKxOSg5DxApNqbnoFPPwXCzA-EkAgDSZKaZd3BXs3VkSjZSveSc41iSPXBlbOgS5WRrp-jbFCAYegm6wHrrwGGEctahp1TQt60aFrSqrsaxpibymMCwD4QMB1-ACsYFy9APKkjartcUh11KY2wo%2BRiBy8yPXtJ8OpEiOAbDwEwOwLwm4mWFWLaLUteqK3fzpbKBy5yPXJAyZgZwiBzUZJoiKUcPAgE9tQavcZVLJWVtjUao4DkvkesVcqjIZg8iYrzMYm9YS73PIfTLJ9Q642voRR6lFeY0XqTwFPWAM9NDeEQPACdnST3RDgZmWMwrZTL1va-e9DjH1brhY5BlMGrhq0QAevAsgOCZUbeht0naTCpGgLQUx11AO7PCZSsjYGKPDuNXKj1YkGAyDaUG-j4b2Krj2MBC8eBiwJG3OSqCQA)

#### Code

```fsharp
namespace PmaBolero.Client

open Microsoft.AspNetCore.Components.WebAssembly.Hosting
open Microsoft.Extensions.DependencyInjection.Extensions
open Bolero.Remoting.Client

module Program =

    [<EntryPoint>]
    let Main args =
        let builder = WebAssemblyHostBuilder.CreateDefault(args)
        builder.RootComponents.Add<Pages.Main.MyApp>("#main")
        builder.Services
            .AddRemoting(builder.HostEnvironment)
            .Services
#if (!DEBUG)
            .RemoveAll<Microsoft.Extensions.Http.IHttpMessageHandlerBuilderFilter>()
#endif
            |> ignore
        builder.Build().RunAsync() |> ignore
        0
```
            

#### Error

```fsharp
System.Exception: Fantomas is trying to format the input multiple times due to the detect of multiple defines.
There is a problem with merging all the code back together.
[] has 2 fragments
[DEBUG] has 3 fragments
Please raise an issue at https://fsprojects.github.io/fantomas-tools/#/fantomas/preview.
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message) in D:\a\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1439
   at Fantomas.CodeFormatterImpl.format@410-3.Invoke(FSharpList`1 _arg2) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 436
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 465
   at Fantomas.Async.map@167-2.Invoke(AsyncActivation`1 ctxt) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Utils.fs:line 167
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 105
```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

Trying to format ASP.NET-style code which uses `#if (!DEBUG)` to remove certain logging. Originally I was using #if RELEASE and found out [this isn't the way to go about it](https://stackoverflow.com/a/507723/10325203).

Happy to try and fix this if you can point me in the right direction.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this problem!
I noticed it is a trivia problem, slightly easier to detect when changing the `#if` to a comment.
([Sample](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwAFbTAIVgBtEAnWAOgGFaBLRdAFwB0GfdAKGwC3MAFkO0JnlgAzHswCChAHKIerWA0RtY2ArHTceeZgHVEAIzV5E2G7QCezABKw8PDugDmIuhiEtKyXorKAKIAHjzceBwmFgAiiOLoSOjQLgCS6ABWiNA%2BJswxcegJSYHB6GA09EzMAEqOsD7%2BbJxmgYHYCACu9ORMfgw4YAC8vYJ1EGAA2gA8kbwMLmSwvjwAfAC6gfNg9DxSmL5gmAx%2BeFOHR-MnYDYDHLRIDFNg1nZ4Dk6uTzeKivd6MNh6TBxVIKTBDHgACiuNwAlPcHs9QR8WrB2jojCYzBYVPB4EsyJg-PhmJJzugaS4VAQCDsEXxIABiSi%2Bdlo2YYiAvN7YgDKjAAbjJ8OiBRBVKTWv0On4EUKwQwPF4eKtJUx0LheHyhLKjswxQxJSQ8IEAPQ2jkcBRgBEAQmSkSoAFUAOJGuYmsAtNrixAqWi0JahOQRMqxeKJSoeHg8AjMHLuZMEST4PCUxDuTAZRog4WMABibziDFZfrtHO48EdMtlAB8dmAOH4gnpm-M1diS%2B8ESiWgN0GoXFlh2A2x2u7pEL2IAAGSAAGnAUAcyd8N1Qi03EFAGMgABIeC5xPvINt14f5mfxZhaANkGgFvejsuN7LIHlMjwIocAAXsgP4CgALJ%2BYB7PeAC%2B4FHtBZ4XleaA3rwd4nqeT4vm%2BB6ygAjIhDyQLS0QADK%2BIgFHcH4PAABZYQKhEAEzLtBsFHAh97HqR56XvhkANgA8goVGmCKF70MxRyPs%2Br77h%2BsqsSRcmrPAYkSWB0EQJAtAKJAnHwSRfFyQJaFQDYuK0LJD44Qp%2BHKQKADMakPnkDgMDwFZYLQmgAO6cKYdlHDwDCvsZ3GmchFlCdZdChVADl4UpulgBB7l6WK2AyHQJgqNqGRadRSUQLCtAOFF8w8UcZn2ah8U2Ul8mpe%2B6UAKxZVAIpECQVCIAoC4UuMuBVmVYDhZFGJcTVMXYY114JbZ7mtYp7WygAbN1kC9cQiADUNegUbAAWMNAmAOHk4qwBdJToBNU2INVEC1fM9V6XFS3NatKXrQRAoAOw7Xt-WDQunrMudl2INdt1QgmE0VVVM0mbxsWLehy0tX9TnpQAHCDfUHeDejsJdeA6JUU3FLoSPPijDyza9838ZjVk-bFuH-c5GIAJxE-th0LtmTiMPTlXPaj0XowtgnfYlv3c3jRHfulu3E8LZP5Q93XI1LTNo3VGPy1jnPYcraVEcR6ug6GSiMPilCPRFBtHMzYBvUhcuWZA2NK45Vssaptua6TiA5XltAmBLjPu0b70m77-tc4HG0sW5of7SoDsMJHcDR7r6VPS9nus%2BZ7N%2B%2Bb-GW%2BnGKEZl6v-mYInoAAKuslgcIxsdu-MHte2AH3JZXKcW2nAP111WckCoTBjvAqScLl43dSX0tzbLbOm1At4B21k8PIR23q%2BROQKG3DHcJEksigxug8F38A991EEcRvLNbxXO8YTwOO14fI4hFgan0wNEPICgODRBEuIcYPBdAxAIHoP4iNuodXfobGWxsfZCT3qnA%2BvMj6E1AdEVocAGDwCfi-dKb9S6D2HihH%2BeDx4EPSoRAWJCyG6HgOoAYYsGBiRyHEbAeAJqEToeXBqP9sDwjeNRMsuhKDJkYG3eW%2B8ebpXYjtLhFDJCyOCogBRDAlGr3VtABiVxiBVgAPoBQ4M-JiEiv5SN9swmuE9CFHFYjbX85E57jBcCJBgVFvBUKYq-DB8csGJxwdeNx5kAGePmKxEOviwH%2BMwIE4JHBvC8P4YI4RojuriI-mXZxn1K4yNoD4AxRiTEqLUfgjRKlM6-gyVkkJPA9HVLkaYOpUJTG-nMZY4ojBbH2J7k47B29XGYXUSrAUrFG5pOiAANUclQXwjZ-BhImvjSJ-cE7exmbguZTSFkYlYtPFZZYxzFATJsjIu5dkRKmTEk5cSzksOaYsk%2BKzkjtG9FoRByCqjoBeZ1A5EAB6SIqT-Me7jWEqRAb4-R1EqDR2gAAayoOMbFWg8CtxFDgRAOgXzYCLrKfWbzjnf2TtXBJHjNHEN-IFAxA0eBnW4Ko8QMJfDdwTCoDIosbCMCKelalpT6FJyaorc5QdLkcN-AAaUQGkc%2Bl9uB5GJbgbSvcaVDxlZ8v%2B8yFUPBcmrFZN9cp4AYhC2UtCpWwpHvChl9lEnpRcj4gUu1dz0Dnn4PhZgfiSAQDpKlDM%2B7QqOYa2JZs5XfIuea1JPqwydnQLcrI90gJdihAMPQbdYDN14AjGOetI0GoYV9eNK15V13Na01N1TGBYB8CGE6-gRWMD5egAVSR9VOvKS6%2BlCbEU-IxC5ZZPruk%2BG0hRHANh4CYHYF4XcbLSrlslpWo1Nb-5MtlC5a5Prkg5MwM4RA1qckMRFJOHgYCB2YM3tMulsra2JrNUcFyfyfWqvVRkMweRcWFnMQ%2BqJT73kvoVm%2BsdSbP0op9RiwsWLtJ4DnrABemhvCIHgDO3pF7ohIJzAmcVsp16Ps-s%2Blxr691ItciyhDVwtaIBPXgWQHBcqtuw56XtJhUjQFoJY%2B6oHDnRNpVRqDNHx3mqVT6qSDAZBdLDcJ6N3FNx7HAjePAZYEj7mpXBIAA)).

The solution will probably be something similar to the fix of https://github.com/fsprojects/fantomas/pull/2063.
I'll take a closer look later this week.

**Comment by nojaf** [comment]
The problem was indeed very similar.
Would you like to have a release with this fix?

**Comment by kojo12228** [comment]
Fantastic, no rush as it is by means a critical project but yes a release would be appreciated, I'll continue testing my Bolero project the fix is in.

**Comment by nojaf** [comment]
Great, I'll probably pick this up on Friday.

**Comment by kojo12228** [comment]
Thanks, using `4.6.5` I was able to format my project!

**Comment by nojaf** [comment]
Thanks for confirming!
