### ISSUE TITLE
Trivia not restored after long identifier in SynField

### ISSUE THREAD

**Issue by pbiggar** [fsprojects/fantomas#2103]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAGmALxgA6AdhAD5gCCYsAZmAJbnpgD0nYAKgBYsAzmDgBbMYnZghAVwBOANxaLEQitTAAhBswDCAOgAiXHgOGjYEqR3jCAhtlz35QgISQANOChDE6dDYAcyFUMABtHwhQCFioABIsXDDINnQvKNjIeMV7ABtZZDRIuLiABm9SrIBJciR2AGUWAC9kSqqwABZMiABdTIBfduiehKSiqDSMquzcgomSjoBGYdLIAFl7AA8AGTZEHakg9H5p5YAmMtH%2BuKHMmLXEnAnIKXgAeUY98kQGrDy2qNZvlCmFFlVzqs4pAAKJ1T7fQEdKB5RiQa6DVYPaFPZJoSAAI1gsDyZxxc1BxVGEAAzFCauQ-PJ0AAxNj5AByiAA7nl9mTSuh5IUMbcsUDcS8iSSBRBgfMwdSuvS5Q1EGIWHA8rByLR0HCPl9%2BSqwIx8n5RbE7nFsVlJSlpaT6fLKRElQBWE2QBrYezQRBaRCMWDyRAABRc9kk6EQ8llsSFIqqNyt4pm9vxjvjLoWSoAbF6fX6A0GQwdYNzY9B7H5aopYNXAjr4xBE4hLRBrbFbXKM1As86ciDc8iAOyF33%2BwPB0MAVScVZriDrDfsTfILdN5vbycx9wl4wdxKdEopI46AA4J8Xp2W9Hka0I9DqhInoOgQ5uzXkLbuxfv00PTNj2zIcFSpZEAE5rynUtQ3WdUCVjL9tw7MAuxGQDniPGVBzPRVkSWColW9ScSxnRBn21DcTW-X9ShTTs00eID%2BxAvDhwI5YVhIot-VoRgY3kZ8JHsTc2zQjCwB7MZsOA3DT04iCLhg8iyzVDUtWbWjUL-VMAJYuS2IU9N8OUqoljpXiyIEoSNM1EltKVCS9KYgycVYwl2MU8C3UIzovVqep0HecheHkTAAHUWBOFCfx3Bi9xtA8jK8kzHjMvzlk9azi1oeRYFkOojEQPkNSE8ThQSuJGPQ5iPNSqYON88FSiWAsSM2LZqkYAQpBheKGn4EN0Gi%2BBYpNTorlcur3LtTymp811WriJZx067ZakYFgtneXB5DXEMYS2bBQyEIQWCc5F3WmxL-2SrC8UmdhQMylbYiWK8Nq2AAlRA4HkeAxompUpsk%2Br5sal7muWpUlmg76-oB%2BAOVkMQkPkT5qhjMRQhNJZwbm3tPLEWQ8kCPkfhZEMxDXITeGwmHzwhYjkUgJGQ3gdYyYp-ZqfkWmAmQr1oH4SN31jAB9bkWHG05CYewyntSaGluZ0pzh4tmuvyg7MHeeQ9lfYHTkm26aqS7sUuVxbTKUrKIUhb7dfsfXDeEdBUfR2MsZxvG4YVq3HpeUnyZYSnEH5wX6cZtWuIhKy2Zdt2jfQbmw4jqO6eFkjRfFoTpdl2LA8wpWXltjL7feiBzgC76ADVhy0Ng7HIIITc3C9zdiWqpJk7IFtVu2WqVc4cu17YWSK99LvIZu6mCDuzZL6TrfLofK5H5Fzg6ietiMWB0AAcX8Y7TrUC6dSXj1u76S3S4a5WBzj8yNfW7WefD-YtG1aAAGstAHX-v4IQoUGhRkoiSNGNElR0Wqj3e%2Bq9g44RPMPWG28vpsy5Lyb%2B-hKxSAZrgEq21yAxVnrQOoCFvauDivRC290g5lxQa9Kuo8EZswANKIEQNgHqfVyC1HAZIREtD4F3wYQ-SGNsN7klYciGkrMOgbG2ANDUQh%2BDX2RGDGafc17MKZvHUoNItZKKaG3AE%2BUghoxsJFRABJ1gICRB0OBK9%2B59jSqgze6COg0idknPkQRyBT3IDPHUTRAlrgUIgXgsAgo2DXLPURri9HyU8bIrePjE5KNoOTWM5AEmqB2DqIIVCMbELYGQl8SSdEQ2JqlZ%2BaD1ZxBpHXD%2BYdEQ7CjASeA9h7ywAum3bBEdql3X0orR%2BUpvKNMMc08eSijAOAJACVRwh%2BANEwOwbYIz6FjMYRM-RL8HZGN3korhPC4nsFqIA%2BwITTawN0qMty4ypGTPSuk7xVQaTvyUT-G5f9ERCHyoVOoXJXyIC5p-COZ8zqX0ZJVJMjzZrPLqU-KZXimmxBpJgn5LhbyhgWUIaA8gWAanyTGeAs5SE6hKtAB8B11zbIQRIpBTDUksIyZ89hpihSajTo4xl4irQ%2BF6O0VIQgWQXTCC4gYQA)

#### Code

```fsharp
type X = 
  | A of int // This comment survives
  | B of C.D // This comment disappears!
```
            

#### Result

```fsharp
type X =
    | A of int // This comment survives
    | B of C.D

```
            
#### Problem description

The comment labelled "This comment disappears" disappears! I played around a bit and it seems that the key thing is the variant type to be in the form `A.B`.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 1/1/1990

Default Fantomas configuration

**Comment by nojaf** [comment]
Hey Paul, thanks for raising this issue.
This is again another subtle trivia bug I'm afraid.

The comment that disappears is linked to the `D` Ident:

![image](https://user-images.githubusercontent.com/2621499/154634539-74af3c7d-9018-4cad-809f-b60dd090c5a8.png)

and it is not being handled in CodePrinter:

https://github.com/fsprojects/fantomas/blob/10d0dcbcb54858c00649a1de77113ad7e1c51505/src/Fantomas/CodePrinter.fs#L4348-L4355

Because the `TLongIdent` active pattern does not keep track of the range an individual `Ident`, it just returns the combined string.

https://github.com/fsprojects/fantomas/blob/10d0dcbcb54858c00649a1de77113ad7e1c51505/src/Fantomas/SourceParser.fs#L1503-L1506

Are you interested in submitting a PR for this one?
