### ISSUE TITLE
Fantomas inserts a space between array variable and indexer

### ISSUE THREAD

**Issue by chausner** [fsprojects/fantomas#2106]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBDATvrgJ4CMaAFAK4B2AljgLQB8YdNWAlGANoC6YALy8APiL4AdfBJpSZmHAA8heQiVI8ADHwqc5NSABpwUAM7Ys7AOanUvExFARnUACRZiAB2RpI7LEYOzpCuAG646FQ%2B9i4umsaxwQCSNEgcAMp0AF7ICYlgACxBEHxBAL55jsVuHt52fhyBiSHhkdE81RCklbGQALK4igAy7IhDiDRWWAAWTfmkAEya1aUuFUFOve5e0ZAT8ADyAGYjNIjpHphzLi0RUXYd%2BWALPTcAoqnHp7mdGEeQK3KPU2N22dV8ACNYLB0NdgmE7u1fgBmV7JGjmfBYABi7AiADlEAB3dCjOEuLD4KKAtbA6ohWq7KEw8luVr3NCPfIFNEQSDpRAAWzocHQsBoAEEsB9DicybywEcIuYac51i4QfDGfVmbC0bc2g9fgBWBX8zy4aCIABCiCOsHwiAACgRcILsIh8KyIJTqYlVmq6c0wUzoXr6QjDZzfgA2M3pC1W232x1DWBEz3QXDmFKhWBZyzi71gX2IVUQdXOTV8kM6sOsg0cmL5ADs8cTNrtDsQAFVPN58FmczQ8wW6EWFUr0Cr-UCNhHtZD6-rI02uYkABzty2dlOIADC6Gzpn34tMvugWAdxanM9iAYrQa2i6guobq6RTwAnNuk13HX0QoQp6N7KmWs60vOwYvpAb4ruyn7zPEvzmjuybdqeYoGJOYHlmAlZVNBOx1iy8GIkaTykN0KEJjuEpHFgnqnoKgq4MWpZ4QRYDVjUxFLqREYIRR8wvDRHboY6ArCqKE6-Le4H3nOGoLnxr7LoJ5HRpRqJiXRDGelJIowrJTwcRBgZQc%2BqmwepwZCVp8w8ihKRpFgBw0AAKvgxAAOoMLMOHTgpLgPvhT6gjBcEaVGzaJKQpq6VaEr4LAtDwAAIogpLCoxXoKmZimQcpRHglA-jvvZsWxKQcYoQMihJEcHnTBMbxBek0wOlgfnwDMxYFMs5mPpZEXWeVZExeu1VtnVgwpEcdCKAcA64Fe%2BBvIoniOqYpjjthJqDYVFnFVZpUNAEE1rr8pBbrNigAEqIHA%2BDwD1fUKgNnHhVqY2NJdiFxT%2Bd2Pc98D4lQgrAfgxxJIxgq2AqpBfSNP1nYKVDoJYpJnNiDqsVguUecR-3CYkSxmiDDrwH0GNY6MuP4PjuXFjA0yupenoAPpEnQvWzMjJ2jWd43RVdTwLNRTz9IMyVEMQBz4CM55vQFvyfUNYUozWMEi3ZmlVS4CyiVL9WyyQCtK1g4OQ56MNwwj10C1WKlo7TdDY4gDNM56RN1CTDlkzpUtm-Lit0OeNOY%2B79N46tzNmtAbNEBz%2BDc7zfVO4Rp27LrWyVVNhtOSbgwAGqIta7DwNYKvFhuh0hUpzslTnf2iwDsQLAlxeKNitCXntFepNX6eq086tHcNguoy3F1t6THe1d36WwFgADi2AbVtiA7XtNcKsa9fOKFXE8Qy1lRXrk2-AsM0m27HvWmK0AANbWsnz-YKY7npG6B4whD%2B0njyUztxF2oYBKXzFvkBYt0paEhJKMW0WAMwTF9ogTKC16CFklKkQCNt8AOyAbhDWJ8wEkXDJA9uhsgZSwANKIEQJ4RqzUJgpB-u6b4oEgogNPrWXwudQT5xRMhbubVhSmGmHvNWh8SiNyzkLcBFC876wLs4ZEkt8j8msJgZKVgIYTG6ogCEfQEA-CIdwkh31tbn1ssoq%2BTxkTG00RKUkVgaC9xoP3cUmQ3GrSoI6DysAXIGNWntLhd4G5FSbtnchFUVEoiDs4zGnoaChNCGMcUVg8FQwwewBge1CH5GAZYrWvEzoXzsVAxIyIi6aMjpYb4Qw3QQngLgQ8sBdqTHgR7cJwUj5yNAc3WJ-sDZqK7po9K4dcAQkwGI8O0x0jEA4IMXpPCyH8SUYI%2BJDjF6aPoYw4JHAUhv1wJ40eRTiET01lPax5TbFbPsfkZEt9NGP1Oc-b4phkqpVSISc8iBqb31GJvbau0zzsSpH02RUT5HT2GXPAOsRkSwNeQQCS6Dw7QHwHQYUqTGLwB7PQcUmVoBHiINg1ZJSbllMUXEx51SaGaIuNiy8JikCUquWUEwfA8h%2BFMNiXadhgFlCAA)

#### Code

```fsharp
let array1: (unit -> int) [] = [||]

let x = array1[0]()

```
            

#### Result

```fsharp
let array1: (unit -> int) [] = [||]

let x = array1 [ 0 ] ()

```
            
#### Problem description

Fantomas inserts a space between `array1` and the open square bracket, leading to the code no longer being valid.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 1/1/1990

Default Fantomas configuration

**Comment by chausner** [comment]
Another example where this happens is
```fsharp
let array1: int [] [] = [||]

let x = array1[0][0]
```

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.
As the new index syntax is still fairly new, not all cases are fully covered yet.

https://github.com/fsprojects/fantomas/blob/fb0b9cdb30648a28a6ca8fa303868cb4b99e3f5b/src/Fantomas/SourceParser.fs#L905-L915

Would probably need to be extended to cover this as well.

Are you interested in submitting a PR for this?

**Comment by curicm** [comment]
Just to confirm. Reproduced it on latest version: Fantomas v4.7.6+e784cd68954e7c6fac13ed723d108920d04c1ecc

**Comment by nojaf** [comment]
Released in https://github.com/fsprojects/fantomas/releases/tag/v4.7.8
