### ISSUE TITLE
`use` expression transformed to `let`

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/fantomas#2113]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBXAzosAPMAvGAHaIDuYAggBQCUkANOFNgC6sCWxA5pqmAG1mEUBDFQAJKwCeAB2RpIXVo2FjIEgG4BDADboFgteIAMTceMgBJYkmKsAyhwBeycxYgAWY2AC6agF93ER8NGXl%2BJXtVDw0dfUMhDwgARmCLSABZbVwAGS5EXMQeVgALGOSUgCYTH39xILVRDKk5Q0hi%2BAB5ADN80gcZXTdQrT0DfiTkqvTLAFFbXv6R5KhdHsg6wPTmy1aIxQAjWFhdCr34ibQpjwBmWfUbbAAnVgAxLj0AOXJdAvOLKxngYtg0dqNwu1jqcARA4uNEj4vA84Q5EABbDhwXSwYiUVgLbp9f4osA9PTYUFiRriXbqfZQk5nB7whKTJFgACspMgDlk2mgiAAQogerBnogAAraZ7adGIViIZ6wsRAkEeerU8GxBmRaHM0aXRGrABsPL5AuFovFhVgZCV0G02Bsmlgjs4uJVEDViCpEBpYjpcN1RyZKtZVyMqwA7Ob%2BYKRWKJQBVWTyZ6O53EV3ujie0nk3SUjXbJoQtp6sMssZs64cgAccctiZtAGFdE7MK3cZg1dBWOKvWSKb6S2CyzrIZWYdWjezVgBOJsJ60SzIYw5KoeF4sWTX%2B7UtKehmeGhHzypmDm8%2BNWpOIbs44jbkd%2BsABkKTisng06ud11YUjSa8LUFSgekVZ5u3RdFtCHH03w-MAg0kY8oH1cMa0jG4LGqZc7xtNFMWxfMOR3Uc91LWlywOdCqzPWso0qe4QNvcDIKIrFTlI1YELHLUJyPb86NPP9zwAypPB5Gw7FYLpiAAFWeaQAHUODKF8iwo8R93fQ89jQyAMNncSmI8FJuVYy1KGeWB0FsAARRA-kxSD4OBbSxF0pCULCYSohUEzGJw8QUjNa9slwKwegU0pijmLSHFKcVWDU%2BANNJTxan4g9BIM-zlEw-8zNw2MIpyGweg4XAunTbQB2eOZcFkCVMEwPNn1JTlsso8dqK-WiAqK0yQrEFJG3K3AACVEDgZ54DSjKOSyxD9PpQzCqC7CORSJdJpmub4C%2BdB0U3Z5eisRV0T4UkUlWvL1v89F0F0Tg-lIN5xVg9glQUistuNaYr1WSADvFeBMhet6Ck%2B55vrcnloFKGUBUggB9MgOHS8p7v6oTBs2hjttWKpgJByKbNlaQumefJe0W8pMp6nSqMDGj2kJsTgo5KoZkmyntGp2mOF7Y7TqVC6rpunbcbZgb2me16OHexBYfh37-qJwGPCqFiQYFoW6dYSGlZVtX6oR68kZR-slQxrGNNlz98Y56IAYvHWpMmgA1BEhS4eAuG4Bmh3rZmvNZ538oJt2tY9iwqks8mcjeez%2Bw6-3bCDkOmad5D2ciTmWmK0aICqcLk9wBzYFYABxBUmpaxA2o6nOOW6vPfJDETf2LkaebK8moeVgohRxaAAGshVlSeFUweSHDlB9ThOzqyNfHK9Ie4NDOMuOJJ1iaQZ%2BMgVZFVh7WKP75CcqriHUjrKFsddxeeaXVnIzuC5-YbuZJvaQYAGlECIFkNFWKxQbCL3lMsTSu4WZ9Tli7QuscubE2SLcYGyQsg5ASpiTApQ26rBWpvHy38e6-3QXcMm2CnA8GGDZbgJ1iipUQIcTICAVjJE-qQtaO9-J7zQdrCwtw%2Bb6z%2BNwYgqdiDp1xE4SR9V0ASgUrAGSLD6odTgZ5CA3k%2BGoQEfRIR8dxC3D1tgygr0lTEA0ZoW0PAX5nVvlwB%2BPYtFf3ltOXuFx%2B6rFuF7IeStli5DlIceA2h2ywHajwE%2BKs3G8O3vowagi%2B5-wwUnbBDkRbaEOMMPBItSgOGkPYHIcTeoCTxtHRkokUlUJERXbBwDQFqPsDYae2gZGM3XlpdxyCf7uwPiIwe2Cx7tInssTANk7K2B%2BL2RAENh4q0bq1dqrjSR8TKblCpj0kmGJqcIkxR9hkyhbBKTJmBoDPA4Jiaxip4DJnvriJy0AOyyg9GvD%2BG8Nlby2fwnZ1TvGpLuAA2hQIsTG04aUhB1JmC%2BHcEoTAbx2r8E-gEIAA)

#### Code

```fsharp
use x = new A()
```
            

#### Result

```fsharp
let x = new A()

```
            
#### Problem description

Fantomas should not change code semantic and transfer `use` into `let`

#### Extra information

- [x] The formatted result breaks by code.
- [x] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
In what context are you using this?

I noticed the [parsing ](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQCu9YAHmAC8YVAHcwAQQAUASkggAvkA)of the source yields to follow warning:
> 'use' bindings are not permitted in modules and are treated as 'let' bindings

We at this point don't know anymore that it ever was a `use` binding.

**Comment by sergey-tihon** [comment]
I've used it as minimal source sample for test
https://github.com/fsprojects/fantomas/pull/2114/files#diff-1300c45844b303b93e949149e2bc66214deaea62d3b2f86ea9095c1812aa79b6R279

so it is my mistake for making sample too "minimal"
