### ISSUE TITLE
Fantomas removes backticks around ``constraint``

### ISSUE THREAD

**Issue by Tarmil** [fsprojects/fantomas#2116]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMADXcAdgM5YBOAhgJaFb5gC8YAjJADThTHZY0DmxVGADanCKAiSoAEiwBPAA7I0kGlnZjJkaQDcK6AK7KRmqQAYOUqZACShJLQDKVAF7JLViABZTYALqaAL4e4r7a8kpCqrQantp6hsainhDMIVaQALIUAB4AMjSIeYiEfFgAFrEpzABMZr4BUsGaEhmyisaQJfAA8gBmBYSIjvKYVda6%2BkZCySk16dYAovb9g%2B6%2BEJDofZANQemtExGdAEawsOjjWpOJMxtgAMwLWnbcZFgAYjT6AHKIAO7oQpXKTkIx7JoHMLtSIqM4XEEyBLTNCzTxeZ6bRyIAC2VDg6FghAAglhlr0BsDMWA%2BvpuBDJM0pIdrscovDLs94lMkvcAKzUyCOBQUaCIABCiD6sDIiAAChRKDjsIgyIiIGDEAyIEzJCzNjDTudOdDkbyUmAAGyC4WiiVSmVFWD-VXQCjcOw6WBu3hE9VgTXasC60JxQ3s42I7m3VH3ADsNpFYsl0tlAFUFEoyG6PYQvT6qH7qbT0PTPI1GVCw2y4ZGuTcUSYLQAORN2lOOgDC6HdxE7RNIZAM0CwMv9JbLVgrOqrbRrUA5UYb5pSAE428mHbLMriTqrx3SteX9i1ofPIIv62a7hbmBZ7kKk-bU4h%2B4TCAfS0epyfmWeOhGCJXjyN7VGkD62mKxJ9Fgqr9jiOIUP6gbHpCp7VgBtZAaaIGxre8wQU%2BHaytieIEkW9wTt%2BUjTsGs5HJhC51jhMZNtUTyEXa0GwWQpH4hcFEWihP5oX%2BGGwkx2FhteeHVBiD52A4WA9IQAAqZByAA6lQFSfpONG-nq-4SRezHSbhbGeMwAqcVBZCwAY9gACKIECeI8chQ7UZItEhmA%2BoyOeahLjJllWMw1oPtkOQ2H0qnlCUixfo45Qylg2nwLp1JePUqGVuhc6MdE6jAaxaLhQmUW5HYfRUDkPRZhQo5kIsOQKLKxDEIWH7UnyuUiflYmFSZwWlY25VSMwrZVTkABKiBwGQ8AZVl9w5UGfkBeERWjSx433Mw64zfNi3wD8Bg4nuZD9DYsE4oI1LMBt9GskVOIGOgvBAkMHwyohWA8apAFjSunh1IKJ0yvAmQfV9hS-WQ-0eYK0DlIqoo8QA%2Bv8VCZZUz0FQxI0xCDoFg%2BBFpZLkxJkJQcg9GQBSkCtlTZf1BmiUZ4mdLt5llfcNQEZT0U03TDNM1g52XaqN13Q9B0E0NROdO9n1UN9iAI0jqpA5EpOyWDHGU6LFD04zVCkDDasa1rTXIw%2BqPoyOqrY7jumK1zw08yTe2g1YNTycLuQAGo8uKNDwPwLP%2Bs27M%2BYZoZe1EvNtKFE2SDUNlBzkHyOSO3Xh-YUdu6za1xxAvkvQaQU%2B3z%2B0WjUkXZ05sBYAA4tgrXtYgnXddHvXl-4Cf%2BcZRpSanFnpxANSVcLsPq4U4qEtAADW4qUKv2DECpjgUMqb4XT1lGHh7ifK4BJp137Ug1NNlN-ICi-YC6JS64gLm1YQOndcS9g7tLZB5YWioqfEe3ML4hUngLI6lMADSiBEAKFivFEodhd7KjWHpbyFdh5bXDCoFOEw073AePebOSU8TEHKP3MuoC8HnkvL7MmVgHgUxSEKfgmAaZ8AuiUdKiATiZAQOsYBJ88ozkJq9EyjCr7MKkA8IW7DiRAj4IQXOhB85EmcKopqBhZSqVgIpPhTVupYLoaPCB%2BswryKNkoz6qpCAmJ0E6Uo-8rofxoN-AcZjxF0UkdXIqMiJ78wtA8QO7Cra8DWHkPeJx4AUG7LALqpQH4ax8QNCRSspFj0vsE%2BuKQHhZ3YU5C2FATiYAoRbcojg5C0FyOkjmg1PbnywrkohUDQlN3YfAxBRjaB2HXhQDRpdRFfnMeA1pkCQkFNnuwpeQyV5rGIDTBy9g-ikEQNDeeGsu4dS6t46kwlGmZOadkyxTCDYsLvnMxUxF34W2gGQKgeJHGwXgGmL%2BRIXLQB7JQX0R9Rn6XjpzM%2BZzJlWKno8GB7CRhPJHEIpADTgWMk4H4DwqhiAfC6kIEBgQgA)

#### Code

```fsharp
let ``constraint`` = 1
```
            

#### Result

```fsharp
let constraint = 1

```
            
#### Problem description

The identifier `constraint` is marked as a possible future keyword and raises a warning. It should remain escaped by double-backticks.

#### Extra information

- [ ] The formatted result breaks by code.
- [x] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello @Tarmil, thank you for reporting this problem.
This looks similar to https://github.com/fsprojects/fantomas/issues/2034, which should be fixed at https://github.com/dotnet/fsharp/issues/12303 if you are interested.
