### ISSUE TITLE
Member with indexer that has a getter and setter doesn't use `and` correctly

### ISSUE THREAD

**Issue by baronfel** [fsprojects/fantomas#2129]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAKgIYDOA1gCKIBmAlgHY3o2x1gC8AOgE4esRiEARsXRdC0dGACS6RAFs0dQnMRoRXegHMwAWgB8YWIIBWh7ExZgA7owAWYTYnQAaMMSfdenusDB1EVgQkFNT0jMysNui23vxgKnKCiFxg0TTEAHQy8rFx-FH2jpIAFEoqaqJaAJRoRqaw5hHsYAByLIjeuRAJSSlpmdlyXXkFbk5gpcqqbpV0mlUTAG61JmYWdDVgAK4Mkpw8fHl5xQsAvpDO4FDu6ExzxKhgANpXEKBHkAAkWLiPkPToC6vfhfRaEAA2W2QaBeRwgAAZLnCoFI6Eg6OgAMo0ABeyCRcIALMCIABdYGnAlvElQb44aFQAFAj6fMGQhmwuEARipeUgAFlCAAPAAy9EQIsQc2izO5ACZ4TTyXFKcD3ny6b80JApfAAPJUMX%2BTFYcH4mmgiFQx6co5y3lxSAAUTRBqN5uRkHBVEgSopvPVjs1DMgglgsHBsqDbOtMJpEAAzA6Qaj3Fx0AAxegQloBcHiqN5URQv0qgMW4N-MMRwsQS3sm3xsCE5N1zHyGhwcEsACC6Bd%2BsNBdbYCoEPcpf4qrigZBle11cjyfrseeTYArCPIJjsOJEAAhaiwLiIAAKhDEKlkXFr-GLiEnEGn-FndfnUEXt5XHKbADYtzue6HlQx4SrAVjJNAJCIKiiywFB6y3hA96PmAz7UiyPwhp%2By6slaP7IgA7ABu7QAeR4ngAqtguBcFB7iwfBhCISOY7ghORzKlO5aYfSVbhkuFYxgRcIABwkUBFGIAAwuCJDENJLDqFsEjHkho7jg%2BnH%2BmqFZYfxNa4cJjbIgAnBJZHAaB-LyL06lsRxeRcU%2BPEavpC4CV%2BeENnGyJcoiTbbqR5EgSeindnQ9maah6FgK%2BtLuR%2BnlGfhJncjygWAWRPZUNeilyHIhDqSh2llrpvFaklhlCalvnyhZIWge2cidhGLBRexWlOTpM56XxHnVSyxl1UcXJJplwU5dezWtRFxVcCWpXceVbn9VVglDbVa5%2BS2gWoui6B6nQ%2BBcJgADqdgdY5cTOWhrlBolobJTVPnbdym4TXuPZcLAOzwJQ%2BYtde82Ld1ZW9RVIZMilr22nkXL-oFgpClIVD4LYUpOp1mK2Me6AXfAMojoSipLS5K0PWt-wYl5w1vaNxFI8KqK0EKeq0cxx5OkK2AnsQxAROp66k2Dy0Q6tlXU4CMOrnDcRcuJTNCgASogcBcPABNE02JMxfdc6PdDL2y02XLmUrqvq-ALRbIkyQGoMDwjlyesUwbVNyFs4JMPm-gZsehW3Mk%2BB8TLIl2gFnqW8e8D8l7Pviv7XCB8DW7QLYF7iNeAD6NiE7Yvpk3dbtvobNNh2ldoZZ6yPfWImB6lwYoiFrBfEyLN09S%2BfWS0bm2w02cr2krdeEA3TfpOgNt21wDuyHITum674uU5LnvezQvuIEnKfB6Hxvh3kcrjZ6o-j836BxxvW878xqeBenmcSMkuc0Pnhei%2BTK-u735cH5XR9do12FAANXwvueg8AtCt3UqJDu-BbqxXil8Mu0t-4jSPh9YBQoMw7AkBECBaJoFv21siXWRckE9yhn-fuJtkRykRtg8gsB0AAHEnDc15ogfmEQYEjmFsvbukMDIbQ1HTOW-A5SMxrvHTe4p9zdmgKQfcYglFOGIEdTEUxwq20iqxaKFD9alypjhdB9Mj6K09LmKwW9DzoAglKEOuBKC0F2BEHsaIbIz0XsiByXVO7gyERLbCz1aGHziHKc2noADSiBEDYFRujKUqItEqHdFdfxCCu4YWCX8PuYitoSMTJHOEAphRYxasQWwfCdbwLJNkuKVCRG00KU2BM1dSnYjmGab6mhbZSnxogQQ-IEAejhH4wROTV4hMGgUgeyIEzD1PvmTQdBcF0HwSwbEqzmJbBPPgWA%2B0BnMUFvozqkzGnCIGqI6MrSFkn1KT2b2yQlBMEWGBOYXjeguLCOsHx4yDGf2Lt-YxktTFhIAXEBMQDSlXyYO6EUyhBDwEILJWAAs5jWK3hki5yD3xPVmbc%2BZcIExYNKeQdIQgzQVPSLYTEmAMTChxYYkuCUTGhLmXQkljDSmxPiUcjEqIVGEA2W3JsEyWUgrZWCjlRKuVHATNI0pCiRWkHdMQb6v00S5hEIgWOsit6cL5gLJSINMn1MCVMn%2BMyblznEW0yxyqLxWRPBS4g0ANAtVeXqyiDAWCUGgHJMQLFxWAoCWLIJ0zmkVwwVCqJnTKgSBGUgZlQLThXFJASf4xAMwC0eBM04QA)

#### Code

```fsharp
type TaskDefinition =
    abstract Item: name: string -> obj option with get, set

{ new TaskDefinition with
    member this.Item
        with get (name: string): obj option = None

    member this.Item
        with set (name: string) (v: obj option): unit =
            () }
```
            

#### Result

```fsharp
type TaskDefinition =
    abstract Item: name: string -> obj option with get, set

{ new TaskDefinition with
    member this.Item
        with set (name: string) (v: obj option): unit = ()
        with get (name: string): obj option = None }

```
            
#### Problem description

The problem here is that the `with` on the second property member (either getter or setter) needs to be an `and` if both getter and setter are provided.

```fsharp
type TaskDefinition =
    abstract Item: name: string -> obj option with get, set

{ new TaskDefinition with
    member this.Item
        with set (name: string) (v: obj option): unit = ()
        and get (name: string): obj option = None }
```

Note that if the source code isn't written in the separate-property-member syntax (see below) the format works.

```fsharp
{ new TaskDefinition with
    member this.Item
        with get (name: string): obj option = data.TryGet name

        and set (name: string) (v: obj option): unit =
            match v with
            | None -> data.Remove(name) |> ignore
            | Some v -> data.[name] <- v

    override this.``type``: string = "fakerun" }

```

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-03-05T20:07:44Z - d7fb5cb8604ea5e845f80c76e94f16a6bfd2f448

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hi, this rings a bell. `SynPat.LongIdent` can have an [propertyKeyword](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-synpat.html#LongIdent) which tells you if `get` or `set` was used.

We combine both members into:

https://github.com/fsprojects/fantomas/blob/d7fb5cb8604ea5e845f80c76e94f16a6bfd2f448/src/Fantomas/SourceTransformer.fs#L119-L125

and then we probably don't do the right thing in

https://github.com/fsprojects/fantomas/blob/d7fb5cb8604ea5e845f80c76e94f16a6bfd2f448/src/Fantomas/CodePrinter.fs#L700-L733

anymore.

Are you interested in submitting a PR for this one?
