### ISSUE TITLE
IDE should be set in Release mode

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2135]
There are a number of unit tests that require the code to run in Release mode due to some tail-recursive optimizations that only happen in Release. We should document this in the contribution guidelines.

**Comment by nojaf** [comment]
//cc @josh-degraw

**Comment by baronfel** [comment]
You could also add `<Configuration>Release</Configuration>` to a Directory.Build.props file at the repo root in order to have that applied to every project in the repository automatically.

**Comment by nojaf** [comment]
Brilliant, thanks for the pointer!

**Comment by baronfel** [comment]
It should be enough just to add it to the existing one.

These files also can be scoped 'closer' to the files/projects they modify, MSBuild will walk the file heirarchy to find the closest on to the project being built, but they don't inherit like .editorconfig does and so you have to manually encode that inheritance if you go this way.

**Comment by nojaf** [comment]
Thanks @auduchinok, I like the suggestion.
