### ISSUE TITLE
Reordering comments on modules

### ISSUE THREAD

**Issue by cgravill** [fsprojects/fantomas#2141]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6dYBCsBOAlgHYDmYcADgJ6EkAWALmEbAwdIgDp6dHe8AKAFRgAyrAC2iMKzqI8YCnkQBDCQCMANtKEBKfnx5FMWACp0CAZzASEAV21grYNSoBexMgQYByawDMHTRl-MDlNCkDgzVhYAGs7CjAARzt5AkRLA1t4B2kARTTCTINIABpwKEtEBjZSS1QwAG1KiFAIDqgAEgYqCmQ0SGIGctaOyC6ANxVNNMaWzs6ABgrF8YBJIiQiBlECN2RVtbAAFjGIAF0xgF8jtvPu3v7GoZ3RtYnp2YHmh4gARjui0gAFkVAAPAAyxEQkMQpAYdHex3%2BACYlg8rp1bmN2sCen0fpB4fAAPL%2BaFERCiXraZGdT4zOZoBbHVFAhkAUS25Mphz%2BUE0-kgmJuQLxDIJz0G6limnp4ymTJ%2BrLWAGYORsiNU8AwAGLEGYAOUQAHdNDCFZ0GHg0qLseKHhMnkTZbB5ZrGd95gKTpqIJBRIgJOx3bAiABBBjcskUy3%2BsD%2BGbVe0dHGdCWKl0vN0ep1K70sgUAVgTgYoKg42EQ-nwiAACio8GoavIrR0bXa1li046PlLXXL217mb9jmAAGxl0QVqs1uuQ2Cm%2BTQFTVTaTWCrtjh9sQTuIVMQdMdTMBgc5oeeguj1WLADs09niGrteUAFUKP08Kv10RN9uBC7gmSaaCm3Ziri%2BbZjKV75l8t4CgAHE%2BlYvvOygAMKaGuliYeGlidtADD4HuibJoeEEOlB-YwVAubDjeKoCgAnKhc5vogILBuobYgRRR5gCe9y0YSl7uoxCHMeO-wrAK5Zoa%2Bdb4TERBkaB4GLD2x59vidGQAx15ST6MmAvJM5oRG-gMPI%2BESBIKhkQegnCWAZ6PGJsESUZyomSi7Lmc%2BSnKEGIZwKp6kCVRvY0Xpnn0XB-bGUWMkaoFlnWfIoWhhFCbOdFOmxZK%2BmGfBvkpSifryZs2wMKSRCmHgVAAOreEi-FgZRWmQRm0HxQZiX4slY4oqW6UcBGeCwHYWwACKIBaIY2XgTm2l1nTaUJunFf1wySeVI1rP8U7yWC4LrP45jwpynWiHQ%2BAMK18CImRJwYgVW1FVmu1vD5haHYs-yPqdEKbP4BDgqS34qCReCcuCSiZJYQFqQmxbvd11G9aJ0pQHtf2ITJKEg%2BCABKiBwHg8BPS9CZvS523fbjrwjAT0komxJPk5T8BGnYGjyOS6w2RIDQJv8DNfee%2BkSA4bAWlSer4A5tTyKYYls35azomW3P4PAIJywQCuIEreAq8tZEwHQTaVstAD6poEM9SKS9jcXM-jZX-XenSomZ46ghCk3NlQpJ4NChE0%2B1voYxtPWnn1nu-d7hNsgFgdnSHKhhxHVgMHzAt4ELItiwKEsfa57nOv1suaPLMJmxbasa6n7Pa2lgfZ7nkcMIb9fG43ysw5bZbQDbzbEfIjvOy9buJzjRJe0lB2%2Bx0qJVZnEIAGrKtgxDwJ40dkUhccdJtVdJ0vKcrz7AqomNW-gnqM3ESj%2B9bEfs8x%2BO9OV4z0sfqszblrRYqITpP1mqwAA4jUeGiNLDI3DMfNGZ9LgJxEh7Qc3kQEVW1sDTORsTbYBiNAOI2BJ5xBqJYeqogWwqX5qjAUGl1rnwwW5K%2B4k8y3zTtrYmgcTTmhhNWBgy54Tq36PNcGRBvAowjFsbiRcy7jhYfPTBO1malR4e3MBnNA4AGlECIAoBdK6RBNh0KkHySKnU1EcMXi8ZeQ1V4CjVHJJ%2BN0QyWDoCg2Odjq4Xi8tw5xd9xxqgDscQMnhtCTRIPzeEj1EDqBBAgfkKioqYxiu7DR2DgmSmGmvCAaoM6RIjBaEgRAX5EDfuGPYFSYZ2GUKYWANUEkwxRjYzS8csYLywVw-aoTjhqk7qU%2Bu8giDtMmLCcMJBFG8TwFI4gsiCKdNYegnp6ima5IGbwxYapN6RP7mwPkkI1DqHgCobCsBkakEESbVZ-jOFBJ2TozoapH6RNmlYFQWhECeKsHQUQVAdgQgef-KWHlNGDXyS4sJEDImGOMa0nYmwKEqGqT-Y4qjwXZK2f0zWeC9kEMiSQ9FcQ%2BSWEmtNLYJpCKIANkQmE8DlCIJRso44%2BVMmFVxYAqFODtGgLefwklTZgqIC%2BZYaAhAQwTJsvAd8MjwzzWgDhZsO4mHpNsTi3pOT8W4IBm8vRkSaSEGIikpAYKuVCUqBcI4QxLB6mRo0VR1wgA)

#### Code

```fsharp
// Boring copyright notice

(* Some other preamble *)

/// This module is amazing it's full of helpful lookup queries
module Queries

```
            

#### Result

```fsharp
/// This module is amazing it's full of helpful lookup queries
// Boring copyright notice

(* Some other preamble *)

module Queries

```
            
#### Problem description

It's not exactly an issue but it's a change between Fantomas 4.6.0 and 4.7.1 - I can narrow down the version where it occurred if that helps.

We have a somewhat common requirement to stick a copyright at the top of files to make lawyers happy. That copyright (with `//`) is now swapped with module level code comments (with `///`). It all works but it's fairly ugly.

No problem if this is intended behaviour, I'll find a way around it if needed.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [X] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-03-10T17:18:56Z - c455e63269f9fa0c137a7b4462328811c461bedd

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by cgravill** [comment]
In case it helps my case:

https://github.com/dotnet/fsharp/blob/d7bb97023b749298a4c0efc317c0797c7696201c/src/fsharp/AccessibilityLogic.fs#L1-L4

**Comment by nojaf** [comment]
Hey Colin, please try out https://www.nuget.org/packages/fantomas-tool/4.7.2

**Comment by cgravill** [comment]
Amazing response time, thanks!

As a "reward" I've got more reports incoming. :-)

**Comment by nojaf** [comment]
🙈😅 I already regret publishing 4.7 🙃
Also, somewhat related: https://blog.nojaf.com/2022/03/05/a-word-on-triple-slash-comments
Maybe some other problems you have are related to this as well.

**Comment by cgravill** [comment]
Ah ha, you've already caught at least one: https://github.com/fsprojects/fantomas/issues/2143

**Comment by nojaf** [comment]
Yep, this going to be a bigger evil than I anticipated.

**Comment by cgravill** [comment]
btw generally 4.7 is a nice improvement for us, fixes a bunch we were marked as ignore or manually reverting.

**Comment by nojaf** [comment]
That is nice to hear, thank you for this feedback.
