### ISSUE TITLE
xmldoc comment lost on Fake target

### ISSUE THREAD

**Issue by cgravill** [fsprojects/fantomas#2145]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6TYCyBDA1omALZEDOspYAIrNIQE4A6zAdgCq4MDmiALgDpoDRLj5EmkAEIBXAJYAbeLXqIGASWK5eZSWAAUAMxmswAfTABaAHwsmpiGAX8wAIwa5W0ABZgAvGAA4nKC6qyGsAxafHKwrAK8fFIeXt4AcrhUkgKSdqx5jmCYAiVkfDKGhiU5bAWO%2BgCUDZAANOBQZPwxrNxkqGAA2u0QoIUQkAAkfACeAA7IaJByrHytw46TAG64CjILg%2BuFAAxtYxthSCsAynIAXsinZ2AALIdgALrrAL6PI2%2BTM3m-SWKzWZy2Oz2-SGTzAAEZfmNIHgAB4AGWWiDRiB6fG8YKecIATEc3p9Cj91qMkVM5vtIDj4AB5QwY1iIK4zZwEwoQ3b7GFPImI3kAUVYzNZmJ5SIUhkgZO%2BiOpvNpQMWrlgsAUMvGE22-OhbwgAGYRedWJ0GHwAGLLHZpRAAdwU0vNED4DD2iopyv%2Bavpmu1uqg%2BshAuNL3dUCuiGIcjgCjiAEE%2BOLJWyHpHDDtOj7HJTCiqNgHgUGdea%2BVC0IKzgBWaOQK6zXDQRBSRAREQABS4mX4ahDHq9iHzEELjmLesBga1Ff9BurB1hADZG83W%2B3O5EsbAnWpoLhOmFNnQxLFWEOwJ7vWdyQW-eDSxq5yGqxHYQB2dcttsdruIAAqrM8wMIex6sKeh4xHEV45goeZ3kqVL%2BjOZavpWYaGjWkYABw-pu-47gAwgoR5kMRcRlF60B8JEcG5qOSG%2BihT5oS%2BwaYYuH5PAAnARf7biI2Bxq4g7RvBiFjPe46PjS7FQOWb5YUutZjHCJyRk2v5bgBlFJpeEmMWOYATn8bF0uhnELuGRqwnCCJaRubbJoY4gMJRxBaFeN5MdJyFFqhlkcfOT7cXZhLCk5OlESIsbxomsFGQhfmFDJplyaqCmQEpXG2Th9lmtFm6ue58UJtqSWRr5JlmWAU6htluU2dhy6Es8jYXDifBMhwDDTAA6iE%2BLJVJaUBZOQXqopGEtapkZwg2xUuQwsAmMoiCuvG7k%2BSOtWZSW2XLKseWtWphRwmuWmouohjsN4OKiilVzeJEfBDfAeJXs8pLMQ%2BrHycFUDHcp4UFYS37XbgKJhIYcgokyoFiJEooorMIhkGQF5XnWv3%2BSxgUWdNIInXNPFnHC%2BFQyiABKiBwAw8AfV90Y-ftANZUDJOg-lbUU-x1N0wz8BpDIxBiQwLLqOIxB9NGcLs4TgPE8QMgKDErrsjakTRO57CWad82wiSjZC5E8DYGrGuYtrURiDtjY%2BH2tFqGYTpyJ9%2BKK5NRP0iDhvk2MRKObCyLQ8mDAeNMTIMBiZTMyNkZs39skc4dXP%2B2TEVnESUWh6iEdRzHcd8KL4tqFLMtywt3vmcr9Kq%2Brig2zr9tqPrQIB9nQdFaHhe4NHsdyGUltN5riC27r4laU7Hguwwbse19tf1VNfugl34M5x11MAGrhlIyzwMs3AJ1euF4%2BNBM%2B-XwKZ2FvPnY4RJLfn0M2iYtEXofEon2frOX0cOlOqDUAQZw3lnLeQcrpvxRLQPggR%2BCo3RogTGF5-6RlxivUBz4ZrWQfmdSMRJIb5yts3dkUgkz0GSK2QgfAyC9SuP2fSYtDLZmMinDKadpxc2agQo2Qoqah0dC6TEHY%2BD7hxB3RA1BOzLBCBeZMEoRLlwYNXWEklUpAImnXTmxM%2BE0jBnzIOAtQ4AGlECIFmLde6OIwhMNIJmBiKVsFrzvhA-hgdCgmk0rAp68YyDeAwbCZO%2BN-pKz0bOfBhjH6RhNCHJ4TYT7OAjtwMW3UBqIFcNgBAWYNEcLCanCJ6d9GzU8d3bxedEnJldNwVgH8vAwVYDcOpYgZAiHYLALqKxzxVXyS4zhIC3EhR5oQ2EJpe7VPVmoVg55Ni7h6CoiWsi4asAUVRZxY1tHX10SUqJoUYljKeCaHepCm6ZjRJkVw8BcCkVgFjHoIjx6bK0RAYBB0eGlOiaqIxT9TSv0SdQYeuBXDOH8cPbwVxpg9JRC81xvsrIHJ%2BbE8ZMDEkWKsd0vgYQaGpDhYMj5jVeFlMOQIs4JoSGJMoZ4fAmYyARzWhKR0ZREAWzIePZBGMsYbOjDVAl3CiVfKRSWX5cShFUq4LFGRw9hByHjLM8Q8BAJrLiLI6AZEPBNPxYUrhxTPn7NGWSsYJpTGJM5AwBMfAclIG1VfAs7R3iPCWGQG0WN%2BiaJAF8IAA)

#### Code

```fsharp
/// Make me some Docker
Target.create "BuildDockerImages" (fun _ ->
    let branch = Git.Information.getBranchName "."

    //...stuff...

    ())
```
            

#### Result

```fsharp
Target.create "BuildDockerImages" (fun _ ->
    let branch = Git.Information.getBranchName "."

    //...stuff...

    ())

```
            
#### Problem description

Some xml doc comments are getting lost, may be related to #2143

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-03-11T12:09:54Z - b2d96b2d32870e98dd1671e23bf845e7fda95ada

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Aha, that is an easy one.
You can't put a triple-slash comment there.
The compiler doesn't collect XMLDoc comments on function applications.
Please use a double slash instead.
See: https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6dYCyBDA1omALZEDOspYAIrNIQE4A6zAdgCq4MDmiALgDpoDRLj5EmkAEIBXAJYAbeLXqIGASWK5eZSWAAUAMxmswAfTABaAHwsmpiGAX8wAIwa5W0ABZgAvGAA4nKC6qyGsAxafHKwrAK8fFIeXt4AcrhUkgKSdqx5jmCYAiVkfDKGhiU5bAWO%2BgCUDZAANOBQZPwxrNxkqGAA2u0QoIUQkAAkfACeAA7IaJByrHytw46TAG64CjILg%2BuFAAxtYxthSCsAynIAXsinZ2AALIdgALrrAL6PI2%2BTM3m-SWKzWZy2Oz2-SGTzAAEZfmNIHgAB4AGWWiDRiB6fG8YKecIATEc3p9Cj91qMkVM5vtIDj4AB5QwY1iIK4zZwEwoQ3b7GFPImI3kAUVYzNZmJ5SIUhkgZO%2BiOpvNpQMWrlgsAUMvGE22-OhbwgAGYRedWJ0GHwAGLLHZpRAAdwU0vNED4DD2iopyv%2Bavpmu1uqg%2BshAuNL3dUCuiGIcjgCjiAEE%2BOLJWyHpHDDtOj7HJTCiqNgHgUGdea%2BVC0IKzgBWaOQK6zXDQRBSRAREQABS4mX4ahDHq9iHzEELjmLesBga1Ff9BurB1hADZG83W%2B3O5EsbAnWpoLhOmFNnQxLFWEOwJ7vWdyQW-eDSxq5yGqxHYQB2dcttsdruIAAqrM8wMIex6sKeh4xHEV45goeZ3kqVL%2BjOZavpWYaGjWkYABw-pu-47gAwgoR5kMRcRlF60B8JEcG5qOSG%2BihT5oS%2BwaYYuH5PAAnARf7biI2Bxq4g7RvBiFjPe46PjS7FQOWb5YUutZjHCJyRk2v5bgBlFJpeEmMWOYATn8bF0uhnELuGRqwnCCJaRubbJoY4gMJRxBaFeN5MdJyFFqhlkcfOT7cXZhLCk5OlESIsbxomsFGQhfmFDJplyaqCmQEpXG2Th9lmtFm6ue58UJtqSWRr5JlmWAU6htluU2dhy6Es8jYXDifBMhwDDTAA6iE%2BLJVJaUBZOQXqopGEtapkZwg2xUuQwsAmMoiCuvG7k%2BSOtWZSW2XLKseWtWphRwmuWmouohjsN4OKiilVzeJEfBDfAeJXs8pLMQ%2BrHycFUDHcp4UFYS37XbgKJhIYcgokyoFiJEooorMIhkGQF5XnWv3%2BSxgUWdNIInXNPFnHC%2BFQyiABKiBwAw8AfV90Y-ftANZUDJOg-lbUU-x1N0wz8BpDIxBiQwLLqOIxB9NGcLs4TgPE8QMgKDErrsjakTRO57CWad82wiSjZC5E8DYGrGuYtrURiDtjY%2BH2tFqGYTpyJ9%2BKK5NRP0iDhvk2MRKObCyLQ8mDAeNMTIMBiZTMyNkZs39skc4dXP%2B2TEVnESUWh6iEdRzHcd8KL4tqFLMtywt3vmcr9Kq%2Brig2zr9tqPrQIB9nQdFaHhe4NHsdyGUltN5riC27r4laU7Hguwwbse19tf1VNfugl34M5x11MAGrhlIyzwMs3AJ1euF4%2BNBM%2B-XwKZ2FvPnY4RJLfn0M2iYtEXofEon2frOX0cOlOqDUAQZw3lnLeQcrpvxRLQPggR%2BCo3RogTGF5-6RlxivUBz4ZrWQfmdSMRJIb5yts3dkUgkz0GSK2QgfAyC9SuP2fSYtDLZmMinDKadpxc2agQo2Qoqah0dC6TEHY%2BD7hxB3RA1BOzLBCBeZMEoRLlwYNXWEklUpAImnXTmxM%2BE0jBnzIOAtQ4AGlECIFmLde6OIwhMNIJmBiKVsFrzvhA-hgdCgmk0rAp68YyDeAwbCZO%2BN-pKz0bOfBhjH6RhNCHJ4TYT7OAjtwMW3UBqIFcNgBAWYNEcLCanCJ6d9GzU8d3bxedEnJldNwVgH8vAwVYDcOpYgZAiHYLALqKxzxVXyS4zhIC3EhR5oQ2EJpe7VPVmoVg55Ni7h6CoiWsi4asAUVRZxY1tHX10SUqJoUYljKeCaHepCm6ZjRJkVw8BcCkVgFjHoIjx6bK0RAYBB0eGlOiaqIxT9TSv0SdQYeuBXDOH8cPbwVxpg9JRC81xvsrIHJ%2BbE8ZMDEkWKsd0vgYQaGpDhYMj5jVeFlMOQIs4JoSGJMoZ4fAmYyARzWhKR0ZREAWzIePZBGMsYbOjDVAl3CiVfKRSWX5cShFUq4LFGRw9hByHjLM8Q8BAJrLiLI6AZEPBNPxYUrhxTPn7NGWSsYJpTGJM5AwBMfAclIG1VfAs7R3iPCWGQG0WN%2BiaJAF8IAA

**Comment by cgravill** [comment]
Agreed it's a mistake to `///` there but it does lead to silent information loss. The code works as in despite what the author did.

(it's not urgent for us, I plan to make the change as you say. It's a change in Fantomas since 4.6)

**Comment by nojaf** [comment]
> silent information loss

Yeah, I agree from a UX perspective this is pretty horrible. My only regret is not preparing end-users better for this change in behaviour. That aside, I don't have any aspirations to fix something on Fantomas' side.

There is even [a warning ](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQD0PYAslQDWsMAFsRaVuLAARVs2EAnADorkAFSqKA5rAAuAOmaLYVPSOWQAQgFdENaHIWxFASVFVdaS2AAU8G2QwAH0wAFoAPlVlIIgwGn0wACNFKmRmAAswAF4wAHFEQ1dkeFZFDz1EVmQDXT0rVPSMgDkqaUsDS2jkbriwHgNBtD0beHhBzrVeuN8ASlnIEABfIA) from the compiler that at some point will show up in your IDE, so we are really just walking ahead of a problem you will inevitably will be confronted with.

Thanks for understanding.
