### ISSUE TITLE
Comments between tuple type are lost

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2149]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwAxWWAHQCcr1b6AXATwNIA0wBeR9CCHiaYmAS2hhc2AEaIaYAIJ4AQogDmo9AFF08MGjjYCAV2FjY6FAAoA5AppqwAWgB8ivC3TQAPDYAqLgCUzm58AuERkVHRAgD0sWB%2BABakNqoa6DaSiDJyYTEFhRG29o4AVGAAyixCOQB0Sp7QAMKYADZt0sQA1mAVsNIAViFVNUz1AJKNXgBK%2BMZtTMEV%2BUVrMfGJKWA2OvBZUrJ0dPzrZ5FW1bXYdVMes-OLI-7LYKvnH5vJqa1eiG0HHJHd4fM6XMaTabQOZ4BZMEbGdCiJaQAA04CgeEQTDE6DUeFQYAA2hiIKBIpAACSsdiEyCaJho0kCKkAN3axmQaBJ0QADOjopAJrpEOgmJVRAAvZACqIAFmZEAAusyAL6ysmKqDUthcqAMpkUynstqcwk8qIARg1EUgAFlMAAPAAymkQztFaiYSUNVoATLytSrwurmeTbTraWhIKL4AB5ABmrvQiEqrDaMq1bI5eotkT9NvCkD2ieTmcFbQTkCDapt4aLkb1kGklDavobJrN3K1EAAzIWWcKsTQmGRNO0AHKIADubTd7YiTBonJrIbrWcbdJbsDbA%2BzptzPbAcoHEEglRy4h3FgUTBLSfnp7ACfaWNXAlD4XrLM30e3u43TtD2iABWJ9zyIEhVATWAaEQAAFTAaBwbE5AXcIlxXSJgw-dcjRpJt-3Q7UgPNI8ADZwMqSDEGg2D3Vgac5GgTAsWFVlYBY8x0GIiBMMQd8IE-ARvzPX8oCIvdjRzMjogAdiomi6LggBVAh2BoFi2PQDiuNECxeOfV8BOw2sww3Ait1bYj9y7YkjwADkU4haMQGC4OaNpWLwZoLCEZdoCYWDDJfNo31MtdzPw3UrJ3GzpIPWSogATmcqC3Pou0gTQp9QvCiIcKEvCI0sv9rKk0ju2iS1%2BSPCCXOUxBfLaAzcuMwSwGEzVoqjCTysAmSqqta06uolyFATcYaF87BsEwQz%2BI6rqwFE7VSr6uKKsG%2BzqoLUalIyuCL2wK8Wp4tqwpMgqzK-CyYrKzaBsSobIktft9vGya5GO07WqPRaItwqKSvujaAKNSqdqtE86uFJAxTjdA-BoFgAHVkR9C78vCQrOuKht1ubfqIe2vMIktMCPpIexYEReAABF-lEE6poW5crpxm6RLu3r6TFeLIbJ8JLUouqHUdCYE2%2BbRLsqJJYKYdH4G9Qy5UDQGiuBgnQb5xktueqHXoUsWnWFBNREdOMNJEWCtEdAg4LwPB9POo8QPV67ItunqmwNfW7KFgRLSck3HTmOAaHgJWVafNWlvxn9Cb9p6A6PS1UtD8PYPgCdjFyGhEwmcZsAJJ9LXjrXE517A4VEOcUwoGg5pxOQ-Bi-3gKiANwKzyO7Vr%2BvEEb5vWfA6AkiQ4gpoAfWnURlZ9CvvZB3nk5Jg3A4gP0RsFcX7GQlg4xoV0hGjzGjzjjW8crsSk-5jukvzPbd6dffMEP4-RCEXP88L4vS7TkvbmPs6Q10WHXN0w8RBTTbrSB%2BL0Ih%2BneoKN%2BH8T5MH7uAweUCW40EMjACeyFApyFnvPFWQDuor19vfFOnd8wwxfo6AAajmZQmh4CaDUGfQyDkPacy9sAqhdI14RkFkeP0lNGFkERIFF2bDdCcO4bHPhAhcbLVWlSO%2BetaGP0QaLRh9NYBMAAOLYjtg7fAzsLBKLdio5UXNKHa15pJHRCDwh%2BmNrvAebplAtWgN0ZQRDujYjwIjSoKFmp51dtEPKHNVEOJWjzQixNRGk3ESHQUU5Zw%2BOxExUUsDECM3NkibiChdBZXzgAmJ7Ur7qKSbFcGqSN7iIzoKAA0ogRABBJbS2FOE3AZYQo1M9kDZeTjqHaPXqnaIvZaqMK0G0E6eAkg2OiJfEZmsxlV2cSkjsaSZk7yiOeThGZSh51FIrRA0g7QIHLFEWJFDEkgIeo0vZzSZnPyOQoOcah0DSK8NxCUvyRDGDgn4WAcMLkiBdkMy6jyNHiSJo9KZdCIi9mQV8xYcgsBiFZAxPEFSjhFM0MiF2VT7nDP4aMwR4yGkC32VEXsDCjmYLEGWZ0OBpDwEwJ5WAzs8RZMHrC7G8SBGOO2ck5FTTpmMskUc%2BmX9MDSAzAspZSRqhiidMKuJ9ixVPKES8%2Bl7zGX6KOR0rpkKxTCkCZgLw59qlwtqQnW%2BOsXEot0eEXsnijm%2BNtd0MseAaZ0ynLUeArKIEpnMY7Kx6ByWRABhs6%2BWyXU7KlW8mVkRewZJ9UhRqCq8DQBoMzcc4x4AqSRBYRm0AvLIW4tq%2BF9TDXwMNmi1pRy0xFsCjcpA9bakYiVLKekeAyDO0JItVUQA)

#### Code

```fsharp
namespace Foo

type X =
    static member AsBeginEnd : computation:('Arg -> Async<'T>) -> 
                                    // The 'Begin' member
                                    ('Arg * System.AsyncCallback * obj -> System.IAsyncResult) * 
                                    // The 'End' member
                                    (System.IAsyncResult -> 'T) * 
                                    // The 'Cancel' member
                                    (System.IAsyncResult -> unit)
```
            

#### Result

```fsharp
namespace Foo

type X =
    static member AsBeginEnd:
        computation: ('Arg -> Async<'T>) ->
            ('Arg * System.AsyncCallback * obj -> System.IAsyncResult) *
            (System.IAsyncResult -> 'T) *
            (System.IAsyncResult -> unit)

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-03-11T14:10:39Z - c9407209c3ed3a12aa9d099173598fa92027f88d

Default Fantomas configuration

*Signature file*

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
The problem here is that a comment is assigned to `SynType_Typle` and is not being printed somewhere in the `CodePrinter`.

@edgarfgp this can be a good issue to get your feet wet if you are interested.
Somewhere in `CodePrinter` you need to add `genTriviaFor SynType_Tuple tupleRange` in order for the comment to be restored.

The code that is printing the tuple information needs to be wrapped with this.

I won't tell you where exactly just yet. Try and find the right location based on the [AST](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmAC4BOArrPhJAMYD2cFkyAhgLboAHbs1hhirVgB1qk5NNmUAngNEANMAF55yCBDSVulRMzD9eAI1jUwAQTQAhWAHMUAUWTQw2NrwG0DRqzImAAUAOQ21E5gALQAfLZoisjMADxhACpxAJSxCdq6hUXFJaW6APTlYBkAFqJhji7IYaawFlYFZV3dReGR0QBUYADKivptAHR2ycwAwtwANgvmwgDWYEOs5gBWeSNjlJMAktMpAErotAuUuUOdPQ9lldV1YGHu0C1mljIyOo8A4ohUbjXgTE5Jc6Xa57TK3MD3QFI561erzFKwBZfNo-RFIgHAg7HU7MC5oK6UPa0ZCIG6QEAAXyAA). 

Be aware that this issue inside a signature file.

You can use
```fsharp
[<Test>]
let ``trivia above tuple parameter in function type, 2149`` () =
    formatSourceString
        true
        """
namespace Foo

type X =
    static member AsBeginEnd : computation:('Arg -> Async<'T>) -> 
                                    // The 'Begin' member
                                    ('Arg * System.AsyncCallback * obj -> System.IAsyncResult) * 
                                    // The 'End' member
                                    (System.IAsyncResult -> 'T) * 
                                    // The 'Cancel' member
                                    (System.IAsyncResult -> unit)
"""
        config
    |> prepend newline
    |> should
        equal
        """
namespace Foo

type X =
    static member AsBeginEnd:
        computation: ('Arg -> Async<'T>) ->
            // The 'Begin' member
            ('Arg * System.AsyncCallback * obj -> System.IAsyncResult) *
            // The 'End' member
            (System.IAsyncResult -> 'T) *
            // The 'Cancel' member
            (System.IAsyncResult -> unit)
"""
```

**Comment by edgarfgp** [comment]
Nice 👍🏻. Will take a look
