### ISSUE TITLE
Reformatting multiple array index operators (v6 style) adds spaces that are invalid

### ISSUE THREAD

**Issue by richardcox13** [fsprojects/fantomas#2151]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBDMAvGAIIBOpuAngHTSmK5aJgCMADGALQsA6pPAO0w4ARoRLkqteo2bs8fQYoEAHUgEsBWAGYCwPSAFJ4XAHxhjBvAG02AXTAAKEbbuuAlMsgAacFADO2FiaAOb%2BqGDWfhCgEHFQACRYlCrIaJCaWD7RcZAJAG646ACuaZE58Wy%2B8fGQAJICSFoAyuoAXsjVNRAALBVgdjkAvl0x-XnJqREZWtndeYUlZVHdECyjNZAAsrgAHgAymoj7iAIhWAAWc6ssAExs-YPxIzmxm0kpZZCn8ADy2ocBIhmslMNdagUiqUIitVrcNrUAKKNf6Azr9CCQdDaSCPYYbN4QyZfESwWDocG5SFLGEYsAAZgRuQagVIWAAYpoigA5RAAd3QR0p8SwpFKeOeBPGHym6VJ5OFiUW0LQsO6PSZmOaiAAtuo4OhYAJiFhkX8AULNWBtEVAhK4i94oSqcTpvKKUyFlDlnSAKxWyDNFS4aCIABCiG0sHoAAVcBQddhEKRFRBReLuk8HVL5jKSWSPdLlT7VmAAGwBoMh8OR6PHWB85PQXCBBr5WDN4JG1NgdOIe0QR1xZ2YvNuguKr001V0gDsleDoYjUfoAFUVKlSM3WwJ2531N2rTb0HbM-jXtLXXKJ57qSryqWABwL6vLusAYXQLf876N-nT0BYNGPbHqeNRZoOObvFeUDupOd4lqsACcL5LrW9BbLqIjJiBtr9mekoXrmMGQHBt7FrSpbsKhNYrogv6GgIuEnvh4Hnk6l6fOOCrkd6lE3OsdKBouiDENoTCkL%2BOo6rgPZ9gOYBDmMxFcdePFFnxM5UfCQlVmhdHanqBqHnSoGsfEEGKVBRKqbBN4adOD43IyukiWJEmGfq5ImaW8kEdmRHQbZpH2bmFFaTcGpCQ0TRYL8AgACqkJQADq6iXMxYEWexw6cbKdnqWFmlOd0LD%2Bq51ZkLAxSNAAIoggp6hJcliuZcSWUpYAjokJGZPB4UlTULAVkJOy7HU2gJRcpyIixzQXNGWBpfAGVWj0Dz%2BZBgU2flMxZLxjlqkN86jXsDTaOouy-JujDRoiuxqIg-j%2BAeTFWr6G1sYRHEqbtfUHfeR3xCwz6nbsABKiBwKQ8DLatdLrQpnXdRMwX-Q5gN0iwKFg5D0PwNyxQ6thpD-HUTA6uEVosEj1kusFOrFOgwSCkC7LRjJWASQlXEA4h3T3AGePRvAWxMyzRzs6QnPNQG0AXPGIYSQA%2Bny6grVctPbfTf2zHz-EC4JpbbHsZAUJQvykIc-5w1ca2fdl325b9Xzo0Vh10rcOnG2NZtUJb1tYITxPJmTFNU1jWs-UFu2M8z6is4gUsy8mPNTPrEUCy5xt%2BxbVvqP%2BYvx4nyeMLLQny4rgHJqr6sZVHzsx67esY-zNS3FFPt7AAat6YaaPAoS2z2j4O%2B1OXKU30xu%2B8A1A3EtzlV3uzsjVgGvf3jRD3XdsI2PEAdXTo69S37uY6WtwjcvtWwFgADi2D3Y9z2vcP737wME9dXl%2BaFbPxXzwgLcE6PtxYJyOGGQ00AADWYYKAwOwP4eKzRcCJgYkTN6pk8IN0njtX%2BhYz5t3iLcUGxteQCggdgRspw06IHqhdAQ6VXrEEaJhEOpAI6ljMjg7%2BLtuIEP-h7C%2BONjYAGlECIBUBNKapwGgoMTGiTKbUD5fxRmOdIM8IRzzpPSKoYNZp6n8BcN%2Be8eFqJImRVuBsaj0iNqsQMoRMBkBCETU4S1EAiC2AgdEXDsGbSstrY%2BwVLGEOsfEek3t7HEEFCEAQq8BDryNK0WJjBij0ASrAGKbjGCvSUWYn%2B-D%2BoAJ0dnKJzNkwCByfkesZw2Ek3oZoJhf48n%2BORgUtSAitHFNLPSTu9ii7BDRPsVBIh4C4E-LAF6ZxyGJxaV9AK0c8GFIzoNcJS97G1QLrgEQmADEFwuM0SgWg9hzMdgsxuSyOlFKEasekV97HiMkVkrQDQ4G4ASbvXxLF8l8KuSswBDIQH2Mge86BaJ-BVRqgTJ6TBRZgMTk-egL9mlWj8vMraiydb4OuefW5pDgXxjfPQTZ-g6DqD1JU2Fq5GFGnqtAL8FAuyYK%2BVlceTtcFYuWVYzONiRH2JBBoQCXikCnLZQ6PwdgugZH8OyF6ERuFDCAA)

#### Code

```fsharp
let a = Array.create 10 -1
let b = Array.create 10 a

printfn "%d -> %d" a[0] (b[0][0])

```
            

#### Result

```fsharp
let a = Array.create 10 -1
let b = Array.create 10 a

printfn "%d -> %d" a[0] (b [ 0 ] [ 0 ])

```
            
#### Problem description

See above for the simplest repro I could come up with (real case had expressions for the indexes. Note using pre-v6 indexing (`.[…]`) works.

#### Extra information

- [x] The formatted result breaks by code.
- [x] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-03-11T15:23:45Z - 1531c687bafcc817233abb70190ba7f3d0592bd9

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello Richard, thank you for creating this issue.
The new index syntax in F# 6 is not fully supported yet in Fantomas.

To fix this, I believe we need to extend:
https://github.com/fsprojects/fantomas/blob/9059695a4a7d6d15dfcde3e22da62e20a8d1f08b/src/Fantomas/SourceParser.fs#L906-L918

and capture the AST shape of [b[0][0]](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQBGA2gAwBdfgMggAvkA)

Are you interested in submitting a PR for this?

**Comment by richardcox13** [comment]
Having had a brief look at that, it it somewhat beyond my current level of F# and parsing expertise. Sorry.

**Comment by richardcox13** [comment]
Thanks for the fix.

**Comment by nojaf** [comment]
I'll publish a new version tomorrow.

**Comment by richardcox13** [comment]
Fix confirmed.
