### ISSUE TITLE
Duplicate ///-comments when immediately preceded by a //-comment

### ISSUE THREAD

**Issue by baronfel** [fsprojects/fantomas#2152]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6dYCyBDAngEaJhwC2ADgK4AuuNAlrAHZiIAeFATogM69NWhKgwA2SLgBpSsCg0TwwAMy6wyYAKLsaAYVg8wohoS64u%2BADpcLzTFgAWNGhV4pMAcwY17VQgDpydAArXGgAawBaClwKaN50LV19RHRCUVhCdDJcXhpELgTtPR50PWYaVVE-JV4rGwBtAB4AZURcUQUAPgBdOvL8ChI8IkQAIRFxfIAKAEowAF5SURzeNmZ4Pr7ISXAoXkQnBmZ3XlQwet2IUAgbqAASGgHkNEgjmm3Lm8g7gDd2qme50%2BtwADDtbrdIABJdaIcrNBgAL2Q4IhEAALMCwN1PgBfVFXLHfR6DM6vcofNHfP6iAFnC5oiAARgJEMgeHYABkjohOXD3N5KYymQAmEFYnG3fGfa5sh5PMlw%2BAAeSU3OYiGajw6Qshv3%2BgIZjJFrMhGnWqvVKKxEEgoiUkAleNZsr1JMBkEIsFgol1X31tMNNrAAGZTV8YfsuDQAGJHdoAOUQAHcjBq-bcKgCnVKXUT5aSXl6fRn7jS6WgjWj0eHba0yAw4OlmABBGjmlVqnmliBKdr7HM3aW3V3%2B91k4u%2B8PUg304MAVlrUGa0WgY0QSmSAAUzLgyAd8j2wFnEIOIMObqPbQWPZPSzPA3PGWAAGxLyAr0Lrzc8TmwZP5NAOSIDCPywEBjAsEeJ5nmAF6ElSN4Tt6U75uWQbPgA7O%2Bn5rqMG7JAAqrEgHAaB4H0IIR59qIA5opKQ55oh45Fih94BhWQLPgAHDhq7fskOjLPwZS5FwVDQDQ%2BjUf2p70c6Mr5ixUB3tOHEYYyACcfFfvhP6INgiBkMQXAybRckQgx55MXKymemxanoU%2BwpgsGH78Xpgk%2BlBS40XRlkKSOSkKqxJaObOlbBkyLJubhiAtkoeRcHoZDZNB4kWbcVlwTZbohSpDloRFXHCiasUeQRPD1o23nMGZ-lZYFl7BYWBVhUVj6Rc%2BTJhuVX4JUl1VNj5wYwfJuaKcx%2BX2e1iFOV1wo1m5MJIOUyrMAAKuYADqXj2PVmU3Nl8FgFe9x2apHWcVWEJMoufVri2qhUOsAAiiBGA2SXpdm42MZNtnTW87HzSVaJMm%2BbkclCSgbfYcIaOZzT2PoNC7fAgpLui4p-dZAN5a15LvOFnVg7d2FQ7g7AwkoDDsMqgymFJXBaNwfACCNz7zjjAUTUFU2E8DJPXVFvGU%2BwABKiBwFw8Do5jwbY7BJ1ncSQMUsLGng9p4tSzL8AJlQxn5KqUJ5GQpxLkyyu5WO01kFQoiMGmiAxvo2ROPkG0KprzlomK756-o8DYI7zs8m7XAe9977QPYu6SfkAD6yYMBj%2B02-jduCxrV1axCIoxc%2B7JU09pj4MqXDcrk8v7VjPONXzzUCx6Qt537BdlcXHJlwQlfVzQhvG1wpvm5bUWZ-zgOEw7TtiBH7v0El3ukr7C3%2B71xe9xXVcMLkodzy7kfR4esfx6YidcCnaeCpPzfT63udzcVN23CKS3d1TABqBqjEc8BHHcLXI83EG5HSaghB%2BZI27P1Jq-G4Ip7qf3YDGF6klBB-3WIA4B9c76QIJo-Ym7d14F0hsg16sAaAAHEDisx4PwQQOCFxgIgMdW214LqFVgSLZ8IoKbdzDvPDUox0jhFGBfMIBxeDrWaHuRAehaRkDqr5WSeDTotVvFwuUoN4EQBFGLYuSZUw8nwjQACcIV6IHerTZgXhBAtnWIZYe49nx%2BUOqwiB6iW7IVmtol%2BwYRQ62LgAaUQIgCgMM4ZwhhLI-cVoDpqNVkhF4MC-FwODCGVyyDEYNl4PYJhz4la4xylnDh01LrcPzrcEMRdGQfkAR0J67gjZwjRogQg2AEDWlcao4pKsNE%2BNQpUju1Su51JbEYdwzBUHMHQSwBEUz6BUB4BtWAK1WmUU5oyNxiSBmhSGWknhjIQyb3GU7fIzBKI-F5CwdwTiTLWKOHYlgLjtm9N5v9KeBDBkg38c%2BEMH86kH0YFaTke5CDwFwEJWAAhjhGJdgkvp7DzrlK0XqHRGSkF1NenvXAaREA5L3vYZo%2BByhU0RR8vGXzs6aN8eiv5xyyF1NCeE9Z5QYTiNwLMuuwYdlItKSiwmFTDlVJuCGfhdSRFcrCFaXgT1YAvQNnwPIIdBEuzoezQQry0RjUpSU6lZShVov9Bi-5BjJVmE8jwHFvBoBcAYA2S5KrCK2JYO9aAywmZURUeZXZ3j9m-PSf8oJdStT2skp0pAFLG5Dl2N0VErxeAxgEGcHZuIgA)

#### Code

```fsharp
// Maybe computation expression builder, copied from ExtCore library
/// https://github.com/jack-pappas/ExtCore/blob/master/ExtCore/Control.fs
[<Sealed>]
type MaybeBuilder() = class end


```
            

#### Result

```fsharp
// Maybe computation expression builder, copied from ExtCore library
/// https://github.com/jack-pappas/ExtCore/blob/master/ExtCore/Control.fs
/// https://github.com/jack-pappas/ExtCore/blob/master/ExtCore/Control.fs
/// https://github.com/jack-pappas/ExtCore/blob/master/ExtCore/Control.fs
/// https://github.com/jack-pappas/ExtCore/blob/master/ExtCore/Control.fs
[<Sealed>]
type MaybeBuilder() =
    class
    end

```
            
#### Problem description

Something's causing the ///-comment for the type here to be replicated. In the actual source (FSAC), this comment line was duplicated ~150 times.

It can be worked around by making the //-comment line a ///-comment line instead, which preserves the correct behavior.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-03-11T15:23:45Z - 1531c687bafcc817233abb70190ba7f3d0592bd9

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hey Chet, thanks for raising this issue.
I want to follow up shortly on all the XML document problems so I released https://www.nuget.org/packages/fantomas-tool/4.7.3.
