### ISSUE TITLE
List of functions misaligned and breaks (Elmish)

### ISSUE THREAD

**Issue by cgravill** [fsprojects/fantomas#2158]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAwrOgA4DOAOgE4UB21dsJitYAYgIYBGeAdAEqIO0AC68AClSaUatJi3a50HBvVl4RYMohEiAlrQDmZALIssWnfqNkwWEvA4jEAZSsHjYALyrVECAD0AWAuIgCeeGAAjH7%2BGmAkUuTesf7%2B-BzwerC8AJK0JFhiktIA2gQAFojQANaI8GAAZhw42qlpHZ1dYADytJUcRogAFI1YrAD6YAC0AHyWuh62AD7z9o7Obos2AJQAur6yaUEh4ZEATO3xidIpR10ZWTn5hcVJZKXt3ZXVdQ3NrUQXy6fQGQ1G4zAUzmC2snlWdgcTlc7l2B1k7Ru5EgABpwFBtNtjKgwKV8RBQJ1IAAScLMEmQAwiXHk-w0gBuLSwyDQZO6AAY8d1IPkkLQRC49AAvZBCroAFlZED2rIAvnKKUqoLSwvS0IzxSyqdTOThuSS%2BV0ohqOpATBwAB4AGQMiCdLEMIgqRqt535WpVaXVrMptp1eqgLHgPUaLtorjOsq1HK5PNJWog5xtaUgAFFaNHY66fVScI1IAG1TbQznw2nIFxYLAcCW2SbUxaM2AAMzZtn5bRUERsAwtAByiAA7jhi32ICIqNzK0Hq8m6wzG83WxAU2a05bOvK51A3Og9HAcLBaABBET5wtxpPdAHaZf%2BYNpGttun1zctvu7uavJdgArMekAuCQwiIAAQogjSwFQiDiBwVAcOgOiIFQ27%2BAuS6dIG76rsaP4bk2-5rqaQHpt0ABs4GQdBcEIUhTqwJOWHQBw2j5OysBcfoV44fOi6IG%2BEAfv4X47uu%2Bp-jhgH7l2ADsDFQdAsHwYhiAAKokMwVBcTxtB8QJ2S0MJTQtK%2BBFViGa6kXJ5EKe2e6dt0AAcalMVpSEEDg3FkEQtBkHhoiIZZL5ibZK72SRuq-s5AGudRB4dAAnN5GnMdpZjoFwWGRdZ0UdIREnEWGjlQPJyVUUp3RRIKXYQepmksYgRCXhZx5ReJYCSZq8URg2SWUR2wENdazWMRp16NM4VBEOgyiWXhJVpGV-UVbWVUjVutXjTRvpZW12mnuezZCT1xV9QNYDSdqu01WNbkTVavbTa1c0LedF5XV2a23dt34JWR%2B0valXZREezWiiwIh9AAKlQYQAOp6F6RWAkDcWVaDTng8adXuVaYGfdB15SOM8AACKIDOZ4Latok45%2BDn41ATIucTb2dFE9HNfaDq5I0iNVLQuaAi4FSISI6PwJjx7yv6MVEbjO0cwazIHa9R186pguOvkjR6A6PQGU4iG5g6iSIGQZDmZZIEq6Vdls0N9ZczrkMNV5hsOoIcBUPA8uK12yus1J7PDV7EP1VamX%2B4HiHwGOWD5VhMa5M46BkJZUSR4NePDeguD6DO8ZsIhyi6FhiOg978edH64HJ8HJhl3oFeIFXVA10z4HQBUqHCAtEyTnoCveoX93R57hqNyTzdTcKQuU2hYQ9FQLqhaH3pKy7G1u1HHsMrHROHWlaTnFm-vrxwm-b3ooVpxnVBZznefHgXqvlerIMl07t3Xu-c64NzjkvDo5wPrCnvo-HeIgO44HLq6EBTgB7NSHiPUQWFx6T0xjPB6NJdrnzDDzPWUCYar0dAANVTDBAwWQjB70sh5Q%2B-hNp3SIbJTmC8IG8ygWTahDo2DjFEOZBhBYPAsIPoQueZ8%2BEX11lffw5wBbCJprAEQABxHQ1tbb23MjI0C7DlTHyLhrYaz0lE%2By6OcA2q8gGuhgpeWoME0K1B0GQPoLh0IdWbOnbqXZeq-y2v-GST1Ro2KblAv2woJzTmcToDiLB67MDpibWgGNzLXgLHlAqVAv7BJuqErh8iCYUWiZA6%2BidhQAGlECIBICLMWLB8i%2BIwo%2BLGNlXaxXdsXee2t%2BEULSN2JqwjJZnjIBUYx3QI6lOBhEzW1iyGXy7N2FeXQIIeDwJTQw6d4ao0QFwEwCAnxdBCb0tW-TLGJUJqs5R6zb6wJnIYWgojaDiKvJKN5TgsBIURrAOG4onCO2utjBZ4THrLKiQ82xnRuwwK2deZBWFaCgvZG6K8hh8lYQyQYbJV4inPhKVcv%2BNyAF3MqXCmJoyqFbKQfoR8Tp0JcEcP5WADsjAJO7t09aHDzGz1PhU7mazujdiEVsmmz9uB4Emc-CoLgwggodHyuRwrqqwtrOQlREBuzqK2Q0ppwKRD5HcYMIearIUUqWVYrVbYdXrIcVslxgwaiPjIJTWA1MJyhXqIyrurp9FIUMUS5m%2BEyVhJtdCu19ztViq6N2OJLrUI5SQtKsg0AqB6DPOi5w8AdJZKvHTaAAU0KCSCSSiFkaykar2tS%2BNjzxW1K2aEbNohTlICtTW-Eew5SMjIGwB2JJeqqiAA)

#### Code

```fsharp
module Comps

open Fable.React.Props
open Fulma

let settingsMenu settings updateSettings =

    // Style 1
    let props =
        Radio.Input.Props[Checked false
                          OnChange(fun _ -> settings |> updateSettings)]

    // Style 2
    let props =
        Radio.Input.Props[
            Checked false
            OnChange(fun _ -> settings |> updateSettings)]

    props
```
            

#### Result

```fsharp
module Comps

open Fable.React.Props
open Fulma

let settingsMenu settings updateSettings =

    // Style 1
    let props =
        Radio.Input.Props[Checked false
        OnChange(fun _ -> settings |> updateSettings)]

    // Style 2
    let props =
        Radio.Input.Props[Checked false
        OnChange(fun _ -> settings |> updateSettings)]

    props

```
            
#### Problem description

This is an extraction of some involved Elmish code. 

`Fantomas.FormatConfig+FormatException: Formatted content is not valid F# code`

The online tool clarifies the issue:

```
(11,8) (11, 53)Error597parse
Successive arguments should be separated by spaces or tupled, and arguments involving function or method applications should be parenthesized

(16,8) (16, 53)Error597parse
Successive arguments should be separated by spaces or tupled, and arguments involving function or method applications should be parenthesized
```

It seems as if the top level bind is being prioritised over the list constructions.

The issue seems to have started somewhere between 4.6.0 and 4.7.x

#### Extra information

- [x] The formatted result breaks my code.
- [x] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-03-15T07:45:16Z - f10e2392ff7207059345cf75223ef9431c36821d

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hey, after taking another look I have some more insights. This is a bug in terms that the `Sequential` inside the `IndexWithoutDotExpr` should be at the same column to remain valid.

https://github.com/fsprojects/fantomas/blob/3e8086fcf3e0e64e7ac7a323280a8b3170dccb36/src/Fantomas/CodePrinter.fs#L1762-L1766

The helper function `atCurrentColumnIndent` should be used when the `expr` is a `Sequential`.

That being said, the expression is correctly identified as an index (without dot) expression. This is not what you want when you are using Elmish inspired code. So use spaces to get there.

Are you interested in submitting a PR for this one?
