### ISSUE TITLE
Wrong comma placement results in "Possible incorrect indentation"

### ISSUE THREAD

**Issue by panmau** [fsprojects/fantomas#2159]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzMAHmALwA6AdhBAEqICG0WAdAK4DOiAorroo2AApcLSgICUYALQA%2BMBSoKwAS3yZyAcywALQmFkBWMADIjYNZp1EAPGACMABjDbE5eYvfxYADUJv3idA45SndFTwBNXxCIABowAG0AH11EgF0xCj9BMUgY8CgOLCwlDTZUBPyIUHdIABIsAE8AB2Q0SBKsXMqqOoA3OnQWVorQsHs80cgASXIkciwAZSUAL2QJ0IAWbohU7oBfdartqHrm4fb5rpra-sHh%2BOOIW0PFSABZOgIAGRLEL5cLFdQrYAEz2Y67BQHbrVV6nFrlSAueAAeVwP3IiAWjUwQIUfQGQ3KD1GIJe%2BM4szRGLWjwwuEgEP2L1h%2BPh5wARrBYOg8T0boT7nSAMzknozDgAJywADESgMAHKIADu6F%2BfIUWElQyZUJZxzqjQRbS5PI1J1uRLQJM2YogkAWiAAtko4OhYOQAIJYSmo9Hqu14AYcXVUaEKVn8o2c7m8sUEu7Eun6QMOpoMRAAIUQuFgksQAAU6JK6E7sIhJeaIFqde5IWH9ddo4jTXGDQLE9a6QA2VMLdPQLM5vN-WDKivQOgcGa9WCT4oeqtObWIUMQcNUSP29kt2PmhNWkahADsfYHQ9z%2BYAqk0WpLJ9PyLP50pF4HcMHV3XmTD282TXu8YdoeNruAAHGeGbZpeiAAMLoFObCwR6bA1oweZLh%2BgRfoo9bro2cL-lArb7sBQqjAAnJBg7QSObzOhyFaYZ%2Ba5gBuRxNmcu5mkBlrkcC4x0mmUHDvmyHuuQzHYax7FgFuJxEZAJG8YKSajLYzxCf2GaergWAVshTpOnQS41jhCh4WxBFsopyntnxanAmSWnnrR%2BaOi6bpvnSWEht%2Beq-pxxrEYB9mqV26mii5Ol6RWHmujy3mjGZMnWVGXEATxYWdke7i2BsqYzHMWAouQAAqkoNAA6ko2hSX5uE-hGf4ZSFWXXA5EXAim0WDp6kqwCI8AACIBEoLr6ZWgYpf5DaBYRrUXJ0Kk5aBii2L2QkfAQUy4GVWguJw2ELFoeZYDV8B1YGGzgrN%2BHzTZi0dKRnW5etp5bZ8My4EoBAonedBYHmnAEE0%2BZsGwr6SYG%2Bi3Y1AXNUF5zPStIF0rYEGfQQtBwJK8AXVddI3alD3pcFS0veFb0KLYVFYzjebwAqLBOoxkpolM%2BlOmUga2CTiMLeTTosOgxRqpiMp5sZRQVmVXGo-x7hgqmDN428Iti78kuStLk1LjAWjFgwk0APrKkol1aIyd1WaT26KSj2Vo6SmmTNt-Ulg0KKSj8qEE1b11wxZTWbi15OOx1VNrQoILOW7nwe3QXs%2B0oqHM6zFYc1zPPo-zodI4iwui0o4uINruuy-LTuK4oIJRZMifJ77WDq8Xpfl4DeuptAhslowFZmxbdV5xxgvI5cCuOUrBVYwAaoKmYlPAJTqP7S5gUHVCWbJ8mGk9E-V1Ptc9fHBAyiIjBQ4vswr2vgcj3JYfj8th9dUrm2n8NsBYAA4tgINg0QBDKGd9kybx2CHUej1yZ2UjqtOkIIPpuw1iXX4mZ3TQAANaZj7pg7AbBSoLFLHBHkLNoY%2BRYjbHeT9uJtjgc7UIIJMaTCVKqNB2BxwuDli0UaP1yC1Shp6WY9EM6ShzqMXy5kt6QMfgXTKdC4SvWjlQEEdNJgAGlECICaLtfaLgZhELLDSeqUiIEI3zmPREEdFFRxFIJU%2BR0XRsC0KA0YxMqFpXtotWBNj4GjGFK7UIDoV6YH6uoFmLhzqIA5G8BAtIJGUPhnNAW0CYztV8Qw9wwo45BM9GqdQ5Bz7kEvh6JYBTAYsHzGVWARVImAyhiYh%2Bu8dzyMpn40Iwp665NFhWcg9Teijg0CItmvCSgCJQo0jxdsFLeNCvQmuChhQz2QcXGkXxSwcngHQeCsBIYaFYaXSZST7opLJmkhRbIlEihPkE4aqc6AckwI41OWgFgNHmJ8I5wdzFQLObQtpmTFDCg-kEzR2janzBmDgugxSA4UOklM05XiYFzIyQsqgwokFBPQTCzBNI2D9UGrMJUqFEDwFbprTEADwaQwmdNFcTSaGtMnm-IFzDsXFjcogO5bBoCSnGvKfS8Arz8I9KNaACESwLnIQkhFxzbZIpmSi9JlzbH%2BLUUE7E-LGCxKQF86RUJ8ipHWO0NgMpIblEkSAPYQA)

#### Code

```fsharp
let f x =
    React.useEffect (fun () -> 
        if length x > 5 && length x < 10 then
            doX x
        else 
            doY x
    , [| x |])
```
            

#### Result

```fsharp
let f x =
    React.useEffect (
        fun () ->
            if length x > 5 && length x < 10 then
                doX x
            else
                doY x,
        [| x |]
    )

```
            
#### Problem description

This is an extraction of Fable code. The function useEffect takes a tuple of a function and an array.
With the formatting by fantomas we receive the following compiler warnings: 
```
(8,8) (8, 10)Warning58parse
Possible incorrect indentation: this token is offside of context started at position (7:17). Try indenting this token further or using standard formatting conventions.

(8,8) (8, 10)Warning58parse
Possible incorrect indentation: this token is offside of context started at position (7:17). Try indenting this token further or using standard formatting conventions.

(8,11) (8, 12)Warning58parse
Possible incorrect indentation: this token is offside of context started at position (4:13). Try indenting this token further or using standard formatting conventions.

(8,11) (8, 12)Warning58parse
Possible incorrect indentation: this token is offside of context started at position (4:13). Try indenting this token further or using standard formatting conventions.
``` 

If parentheses are manually wrapped around the lambda function this construct will format without compiler warnings.

#### Extra information

- [ ] The formatted result breaks by code.
- [x] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-03-15T07:45:16Z - f10e2392ff7207059345cf75223ef9431c36821d

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.
I think this can be solved by extending the check inside 
https://github.com/fsprojects/fantomas/blob/f10e2392ff7207059345cf75223ef9431c36821d/src/Fantomas/CodePrinter.fs#L989-L996

Are you interested in submitting a PR for this?

**Comment by nojaf** [comment]
I believe this issue was addressed with https://github.com/fsprojects/fantomas/pull/2390, adding a regression test for this issue could close it.

**Comment by panmau** [comment]
Thanks a lot! :heart:
