### ISSUE TITLE
Fantomas `v4.6.4` and onwards removes backticks 

### ISSUE THREAD

**Issue by jamil7** [fsprojects/fantomas#2164]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzWsYAvGMAD5gAGlWAngA6LXFgA6kAFgJbthkC%2BkADTgoAZ2xYuAOwDmY1GADaoiKAgaoAEjqNFkGVmGqNkLQDcAhugCuyNCs2aADCKemAktKTSsAZS4AL2Q3dzAAFhMIAF0TflC1KO1deyhDY3czK1tUxzCARgSnSABZSwAPABkZRErEOSwODIKAJmck2M14k3VinQZUyHr4AHlcaulEPzpMZs0s6ztFPPcWovmAUW8xiZCkiEh0XEgOuKLe%2Bf69NEgAIwJ0OdMLRdz9sABmdc9pCQAnLAAMRk1gAcogAO7oGpPTRYP52U5dc5JMwpfT3WCPb4LHLLd7hb4HPyIAC2XDg6Fg0gAglgtqNxjCiXhrBIkRpupoLs90TdMdjUS88Q53gBWFmQPz0SzQRAAIUQ%2BD%2BiAACpY-pZSdhEH9YRp4Yj3J1OSjMldBgL9bilqKwmAAGyS6WyhVK2AqyqwCG66CWCRecywP1San6iCGxAciBcjQ8g4WjEPa3C23Kd4AdmdMrliuViAAqvRGH8-QHpEGQ1wwyzcGyo8azj0hXyoFacam3vaABzZ115j2IADC6H9YiH1LEhugWA94dZ6HZjeRzfNrbuyY72TTKycAE4%2B7n3SqSmTbrr53XFw2nCaY2a%2Buv20Lt12Cq53lKc278xOqdJL3raMwFjRI1wGJMsRTV98XtfJCk-F05RpXAsF1CdSVJSx50jYDQNIFsIP5TcX1eWDWkPH9BxJclKRrd4ryXW8m25QjrjbEjzRgu0Ci%2BRDvxQtC-hoiksXo%2B1cOXU1V0fIiOKgrcyJ49x8kJT8vB8LARmkAAVP5aAAdS4RpAOvPCH0uJ9OL6bj0zgiV%2BNdGk-lgGxvAAEUQaFySEnCERvTQ7xAizeTkgxfGgpS7IKJ1PzKcoPFwHSOHqDZrz8DgPSwIz4BMllwnaKT7xkyywvSRSRWilSsziiovFwLhyhGEtLFnP4NnKegVTEMRqwAlkxUK5iV1Y8D2PCowKp3d58l7WrygAJUQOA-ngHK8oJIbApYuM2MGcrSMq3dNHyA95qWlb4FBGxSXPP4xg8NDSQUFl8nMkrQvG0kbHQKRoUmQEPSwrAhJ0iCprfVYP3tSALo9eASh%2Bv6akBv5gd8yVoA4DVZSEgB9CEuFypp3tG2TxoOriouOjQWgQmH4uczVaBGP5qindamnyraNCC-D42SMqIoh8jVjWeamcsFm2a4Kdrtu3UHqel6ZtJ3axsGb7fq4f7EFR9HdTBvQReUpwWj4mHJel9msER7Xdf11qMc-LGcZnXUCaJky1bA8n9uFw7pvtFo1IZioADVXnlGR4BkWROfnbseZiHbfdKimA6po73haByw-KQE3JnPro%2B8OOE%2B5n2CI1-RKZs6mc9i-P3NgLAAHFsA6rrEB6vqK-FZOwD5kKEyshTA8hs2aoZpGdZqeUqWgABreVNWX7AxG0vwtWHLEbv6higKK4KPtHsLnyzoOwhaOaYfBKF5%2BwH16iNxBPIa6RjL6mlvFPBW-hVvaRiAVeap2rn7SCgpL6T00C0M6MMADSiBED0ESsleoXht7al2KZJi20RrqwgTcOulxbI0wgB8aGYRSgVDSuSMQHB%2B72gKlXAWaJz7WVIQ3e0Hx6bUICHITAzlZA3XqNlRAtwSgID2EAo%2Bw1pJk3TpaThzwyHvA%2BOLS20JZDSELtIYu1IAg6NajYFUOlYAaTEa1PquCQEpwIWnT6yjx7QNFk4D4FtqE0l%2BrqaQ1jzC1GpLIP%2Bd134yC-pOWxrC9qQMitnHhodqF2ykLsSoWpbjwEsCOWAvU5D311lE4%2B-MYnERcfXeJYQPh52oe5WWlhbiYDobLDgfhaC%2BAqIU%2BRxVFFONiSbKq7im7UKQSgyxvgvCr0sPormh8zJFJHoLcaF9ylX3cB8ae1CF5TKXrsMQzlXLeHBFORACNZ66y7t1XqkSWSSS6SfHpZ8lkqITGonht9NkagHCqWpYhoB-C4OSPxaF4AFk-tSTy0BRyalDAfWRcy7nFJrqUqBKyYEaA%2BPA6hC1LDGJckvTp%2BCFGEKUX0iebjNAFWdPCCkttpEEtAV0UQ0RQgGDEICXqihgEgH4EAA)

#### Code

```fsharp
let foo = {| ``type`` = "hi" |}
```
            

#### Result

```fsharp
let foo = {| type = "hi" |}

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [x] The formatted result breaks by code.
- [x] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-03-15T07:45:16Z - f10e2392ff7207059345cf75223ef9431c36821d

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by jamil7** [comment]
Looks similar to https://github.com/fsprojects/fantomas/issues/2116

**Comment by nojaf** [comment]
Hello, thank you for raising this issue.
Please consider fixing this upstream at https://github.com/dotnet/fsharp/issues/12303.
