### ISSUE TITLE
Multiline AbstractSlot without constraints introduces newline

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/fantomas#2175]
When trying to format some code using Fantomas I got an Idempotency warning.

I was able to narrow it to these code:

*The code can looks strange but that's because it is a Fable binding*

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6dYAuBnATAGYCGARgDaJgAMAdABy3UA6ATswHYC2CArpWFaJoYAOLle2AJYdeXWgDFeuRG05qOAYg6wA7sVYcwzSAGZTAThaQwmMPCm4yA-YZkBzXGEKxWYGQBuxORS8GAAGgCyADJgcFxciBx4GhqwAA5JYADKAJ642IhcaZlGCs6ItADCvqrsOqVg5RSVNUK0AFLZqfU88PxUSipgALw9nBAQANoAPACC5OR6AHL85NFShazBAHwAuhqTOLmZTcqI2b7YShzQ0rAcAJKFXKOHR5OzAKJcm48cSAAHohWPt3h8wGQCts7mBnkU0ABrRC5NDQjxgAC0OzAAFV8DNgAAfMAAA1JABJyWjsKwMUSAL4AGjAACVELgpAAvRBzVjbXKEknkqmkml0jjuADc-nggLQhCWxGwYEZOxxuk2AAswO5ENgWSpsOMjJ95osVmsNltdgd6kdZuJYKRbeDjqchogAPLpe4cADSKK9pAAVsIVbMAAoGYhcYNhu4yn6bAAUJgp1gAlPswCmOLHEGh8TN0ZKWezOTy%2BQKS7SPOqWbpEFJ3FrsAqldhM297RCwIkuKQQWAguQwPnEkWCaX3OWOdzefziIKZ%2BrRmAQ7hlsqpAEqJrsDq9QawEa3UcB0O-KOwE2W22O7BlevN9vpHvb9rdfrDfqNJAmXAKAjWkSVcFQMApiAiBQAhSAKWwE5kDQSAZGwADoMmeDR14ZDIMwo5qEAvsoH%2BJBkmyBcMJIgAWAiwD2TDmUw2CPngxDMgg1DkmotiKRwvCoJIgBGYi%2B0gSJiEBDYOEQaIkncQ9eIhYT8GoejGKOZijlYo52KQrikngL1CBki5EMoZSsP44JcIgoS%2B3wMS4K%2BAETLMqy9PIQhIA0pjnLAXTrI4vDIFIWBYHITyoBsiRBPoiBTACvT-hUVhrhkYJlkQXQQlk6KIFpXC-K0gKgogfTOJQ8LIui7DbPi2jkqw7IiikOAlg4OZsFc4zTJkZBmogEhyBUErJm0yZypikKuJqqLmvquL7ISsAAFYhqgbJ0mIaBEAAIUQHwhGjbZEi2AqcFYYqIU0iayvoyrQvmurYrstAHIhAA2TbIG23aDqO2poj0EFoGIFR-gCWBwb9S6isQcaIEmmDHoQgzqoiha0YElaSIAdl%2B-69sO47EFxdJMlYcHIY4aHYakB5LpGsbbv8li0dmzHasWt7Gr7egiZ2kmgaEKpyAh3Aag4aFeDuXxmeCVmPju5GHrg9GqqgF7edxj7VosIWAdJ2pIiKK9FdGxG2dKjmNa57WsdevX8JEojVr%2B4XAbJmpOst5WjlVsAUcCzmMcdnmcYavG%2B2E0SPeJ3lCC2GoEmIeHrutlX2Z0sOtbCp3dej-WRKchOvZNoRWt%2BDqmc2lms8DnOprz57C6j5aS9jpLy4BuZk5Bav2siuvVoRpHg-VviHYLyONZdz6PmEmjfrIpJsC9DgABVWFyAB1bV-cbyYg5D6anrm9v5%2BL13Y423u9r5WBeABAARRAQl%2BC7NvHm37rt6e4duLoSLp3W%2BKkfoe0koCR4hAt5aiSF8K22QtRXAPvAJSm0aLqT-mrABelNahTQs7G%2Bi8jjCUJlAqS-xCBSEBD6EEypfBfEBOkIQuBOSjxImtHB2dba53tkA4hoD3rgKXoLKhgJ2RwFYPAdBmDVrYInmfVuXFhEd1EWQyYwlDaSOkb4eAqxBwghMvCLg4FNrCWUVPAhM8uD8GkHlRAChfBcGVFsLeBkRH8whGpX6%2BjZGRAcVIJxLjWBuOwN-D20AtQxjuCCAA%2BpqDBWpfK4Mnvg4KQieLeJjr4%2BOJEJJSWrMuL0rANgFHkakzaa1rGZIqoQtROSNE%2BI%2BPgMuhToElNyGUip2AjFXlMS8Cxq0rHpJUYI-O9jyCOIGmEiJHivEtLyW0nuhTum9McNgIJMyQlzNce4kEl0YCxJhFsJJoQlJ1IEYA-O6jr5gK0RAfAK9JEADUGr7RkA4SUVTLr0F4U3fhLdJlEOaQ8zRq18D306VJG4dxGYcC%2BQCDwfysGApPs3VGoKmkgOWV3XxkDYWAlfrAbAoh9QsLYRyThHA0WrR4dckFty25zz4gvKFlDOnBKcftJY0BET7RhMiPAm9sgFl9nIDgGcbp8P-jc2xQCdb4rEUcfAEjCnZVygNQ62AmxJE8Zkd%2BtCOCbERXMAEZtjGsBGSRBuTLsUssvmyghHKSL4F0YUwMiB0iwPgUkf44rEgeXrkrY%2BEBT42KyXc8F7LSGrVMO7YlSDfi4C1PS2iGKI1YtDji7m2MIWtKOKYAp4lKKSkoHydwch1570QKQSICBBqrXteMqNDSZ7KsLSs4tHTxILBbBweFfpKLuHzNgXgQgt6wDXskHcXC%2BytrlXghV0bWUFrjY8hNaz%2B0zJBOO3cckHjuCtVeY1MgzUPFtYusNDrc1OvzSQrdJFTCvO5bssy0RYykHgMQcWsBOSSi1U4o%2Bd7z6NMfbkglHxTAwvEq-RwFQU2OC1HkOdgJQNtvqTNJVV9N2QpfUS8S3rfUAnXv8IVxBbjVJbberDq6O24ZddZN1fZTBcvEnyqjiIzK4Cfi-QxHJCjwB2bM2SVL2G0uvRCX%2By6MkMZw-nLt%2BGi2TFMBqzjBhK6IAQ7gaAdJfjjsQPAXEpqHjv2gBLbYcNQ1WzA6oyDKqnlgEsP44gY6DCwERJhuTEyH0Rw3a6%2BNmaiZ1juI2pAPmgUTSAnsMSqFcAKE5BBe1DIgA)

#### Formatted code

```fsharp
// ts2fable 0.8.0
module rec Glutinum.Fuse

#nowarn "3390" // disable warnings for invalid XML comments

open System
open Fable.Core
open Fable.Core.JS

module Fuse =

    [<AllowNullLiteral>]
    type FuseSortFunctionItem =
        [<EmitIndexer>]
        abstract Item: key: string -> U2<{| ``$``: string |}, ResizeArray<{| ``$``: string; idx: float |}>> with get, set


    [<AllowNullLiteral>]
    [<Global>]
    type FuseOptionKeyObject [<ParamObject; Emit("$0")>] (name: U2<string, ResizeArray<string>>, weight: float) =
        member val name: U2<string, ResizeArray<string>> = jsNative with get, set
        member val weight: float = jsNative with get, set

```
            

#### Reformatted code

```fsharp
// ts2fable 0.8.0
module rec Glutinum.Fuse

#nowarn "3390" // disable warnings for invalid XML comments

open System
open Fable.Core
open Fable.Core.JS

module Fuse =

    [<AllowNullLiteral>]
    type FuseSortFunctionItem =
        [<EmitIndexer>]
        abstract Item: key: string -> U2<{| ``$``: string |}, ResizeArray<{| ``$``: string; idx: float |}>> with get, set



    [<AllowNullLiteral>]
    [<Global>]
    type FuseOptionKeyObject [<ParamObject; Emit("$0")>] (name: U2<string, ResizeArray<string>>, weight: float) =
        member val name: U2<string, ResizeArray<string>> = jsNative with get, set
        member val weight: float = jsNative with get, set

```
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-03-29T09:12:14Z - 8f2ab14ee071fcb726451c759ed0aac12025acaf

```fsharp
    { config with
                MaxArrayOrListWidth = 5
                MultilineBlockBracketsOnSameColumn = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by baronfel** [comment]
This took me a minute to spot, but the warning is coming from the addition of another newline in between the definitions of `FuseSortFunctionItem` and `FuseOptionKeyObject`.

**Comment by nojaf** [comment]
Hello Maxime, thank you for reporting this issue.
I was able to reduce the problem to
```fsharp
[<Test>]
let ``multiline abstract member without constraints, 2175`` () =
    formatSourceString
        false
        """
    type FuseSortFunctionItem =
        abstract Item: key: string -> U2<{| ``$``: string |}, ResizeArray<{| ``$``: string; idx: float |}>> with get, set
        abstract X : int
"""
        { config with MaxLineLength = 60 }
    |> prepend newline
    |> should
        equal
        """
type FuseSortFunctionItem =
    abstract Item:
        key: string ->
            U2<{| ``$``: string |}, ResizeArray<{| ``$``: string
                                                   idx: float |}>> with get, set

    abstract X: int
"""
```

The `AbstractSlot` does not have any constraints but is already crossing the max line length.
This will trigger:
https://github.com/fsprojects/fantomas/blob/7373a06e838e4356a0ef469d490e06f105ebae3c/src/Fantomas/CodePrinter.fs#L4829-L4838
to add a new line.

It can be resolved by adding an additional check like:
```fsharp
        +> onlyIf
            (match t with
             | TWithGlobalConstraints _ -> true
             | _ -> false)
            autoIndentAndNlnIfExpressionExceedsPageWidth
            (genConstraints astContext t vi)
```

Are you interested in submitting a PR for this?

**Comment by MangelMaxime** [comment]
Hello @nojaf,

thank you for the clear explanations.

> Are you interested in submitting a PR for this?

I don't think I will have the time to look into the issue as I have a lot of stuff on my side to handle already. And learning about Fantomas internal, will probably takes me some times ^^ sorry.
