### ISSUE TITLE
Idempotency problem when using lower MaxLineLength than default and fantomas needs to split lines

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#2176]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwAxAZQA0A6ASXQDMAnTPAF2YFdp2vnEAHXTDsCLgBtSAVXQBLAB5gAvMOEQIU9mADirAEYAVABaIyc5hwqc56AOYAhRI1gCTZixwDCsCbHQAFBK2%2BGh4iACOADwczLZ2AHwAlCrqGunhEWDAael5YC7MYMHopLbFIXhg8LC5%2BfUAnnKIEvB19R1gQSE0FATB7AHtnSMA2gA%2BYIKo02DjALoANMMjHdZx9n0DAPIE7HL%2BeDQASohiAG6IAKLYew1X6Db4K6sQSUk0owAM8y8AvsJIItwFBwux9vY8KgwKMQRBQPlIAASdgNAjINCQWzsIFwjTI86YCRcDEwvHpL7AjqQBhIR4UOQAL2QVPqABZyWB5ni-qz4Zzkaj0dCsY9cYikYTiaTYR0AIx8vKQACymAUABkQurEPZ2MZxfUABxfTnc9K8vEIpUotGkyA6%2BDbRia0rWBpSA3pAlEknQ2X1ABMiq9D0dzpCnqVEkYkFNPMVVq9NuFmP0sF8kYg3ulfs5EAAzMH8Qxwsx2OYsBIAHKIADuJRZebAnBJcfNCYFybtaYzRezvrQ-vybKLWYoZzkcD86AAguxQ06XY2OowieE2xoLelE-iuyKexJM1BJT6ZU2AKyjqB9YiIJyFRAABUwrFw7EQzCPEBbiA3EC3Gg7lme6pumh59ieOaDk2ABsV6QDeJD3q4iDqrAtYftAbCIAw5ywFh%2Bz%2BF%2BzbcL%2B%2BRmpuHYSkK3ZgUe-Znh0ADs8GIXezgodIBDoswWHhLh%2BGYIR6DEauEjruR8aWp2NH7nREFSgOZIdIarFEEhHECF4EhsHgPjoLEPDsK4olrmReQUf%2BVHWrJoG9p2imMfUACcam3shAjKmc%2BgfqZ4nmekllgAB-LUbacn2RKjm5vKlJNgh6nsQ%2BPjTn5EkWVJ24yeFdngQ5p4xfUcoKvFbEzow77MD42DYJgxE-n%2BwXWUmtlQAe9GQUpQ55HKQalYlHmIOO2CTr4RFXmJ6WBZlgHZSmbXyflUHKUVhb9be5WVcNo2pVeDWSe20lhfNkDtQpBXQfKI7xbSOrsNs6CGMwDQAOpyHqaUBRoQUhdkc20ZF1rRZdRWXutJAzswsBcOg8AACItHII2VfVpGNb9QHHq1oo4udy3dekcpwfFqoKHQjDuOgVz%2BRQxiuOwb3wB9V5siaB2UUdNk5VA2IdcDK35HKLEk2qDCMIouwfkJrhXAoBACHgeAHCJV7nmzGWHVlx12rzeNdU2cqqSLCinHAzDwIzzNNqz6PNbu2O60t%2Bvyq5xum648BVlw2A%2BcwTp0O%2B2BQlecq25zLXc5A2CSPsDZkK4tXgh%2BhjhXrTn5AGcXUu75vKjHchxwnQko-B0DGC%2BxCVQA%2BrWchM-qYda1zJ2O1FF0C3kAYldSpOQ6wDTbMwmocJb%2Bos%2Br02a7N2siq3QPtwTGgBn1Pdqn3mAD0PcgcF7Psfv7gfBwbjfT83drRxIschPHzCJ5VKfCmnhUZ2t1Lr5vw-sHnl8F9fRdJ5%2BUu5dWC8A-DXOuH0T6hTPrPMUT8QYZ2uqvBQAA1U8DhbDwHiKPYixooF-RnpiOeSZ%2BaLwgAGMGyCyAw14MrDBsNsEQLHtbCe30ZrQIji3OBTt06d2JsguGsB2A6EQPOOWCslb%2BBwarVhEAfp22AtjM6PDn6d2Fj3fODYHB%2BGgAAawcCA3Roi8APQoDgRAKVvYqybJNL6cj2EEJgblPmC8mwBiNtSGs9YQhOHYBhHUD9EAI3FvIYSM5YZeT3pYT6%2BDMaCkjsotu%2BM3Gu2pAAaUQIgAg5NKYMDMbgJcMT2ZWXDvbSOxDdykKbPmLO9QVRqmpiNPAxhpEsNif9CKeUknO3qPmbudSGT2CkJDOw3s7ovUQPoZUCBlz1Fse0whC1AYkNcR0fMK86kzmCHYdA1D0C0P8AyHZQl%2BCIEMLAW6jwhLKyKRrDmTdOEAy6fPZJazX6bMvh%2BLA%2BxLhoXsJE32wTbDvWVkfFcZkFlOKWc8lZrzelILqd-fYS51Q4H0PATA2lYBK3sF4hstzJ73NPo8zpLi4X5HzJQupcNt6YH0FIRp29jAUAaFchQBK2FTw4WUk6iSXk9IpfwupGSsmXPYAwAxmB9nMPBf5SFJLnHwI7ukfM6i6naKlbopceBIbQ1hjWDgiB4BIt-qUWW8t8CSIMqjVsxSmqlMUQkxa3TeEqo8eql8g0aV4GgHEEa3yjWyGVgjaAOlWDCQ5fYrljiFXQrJQKvI%2BZUl1OOJgY5UNdGRq5A4uJIE41KrIWAVmrEbC8GmUgLNP0QRLBBFiPAZAlbQnmX8IAA)

#### Formatted code

```fsharp
namespace FSX.Infrastructure

module Unix =

    let GrabTheFirstStringBeforeTheFirstColon (lines: seq<string>) =
        seq {
            for line in lines do
                yield (line.Split([| ":" |], StringSplitOptions.RemoveEmptyEntries)).[0]
        }

```
            

#### Reformatted code

```fsharp
namespace FSX.Infrastructure

module Unix =

    let GrabTheFirstStringBeforeTheFirstColon (lines: seq<string>) =
        seq {
            for line in lines do
                yield
                    ((line.Split(
                        [| ":" |],
                        StringSplitOptions.RemoveEmptyEntries
                    ))).[0]
        }

```

#### Expected result

```fsharp
namespace FSX.Infrastructure

module Unix =

    let GrabTheFirstStringBeforeTheFirstColon (lines: seq<string>) =
        seq {
            for line in lines do
                yield
                    (line.Split(
                        [| ":" |],
                        StringSplitOptions.RemoveEmptyEntries
                    )).[0]
        }

```
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result (note, the bug doesn't happen if MaxLineLength=120), adding unnecessary parentheses.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-03-29T09:12:14Z - 8f2ab14ee071fcb726451c759ed0aac12025acaf

```fsharp
    { config with
                MaxLineLength = 80 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
The additional introduced parentheses are probably part of a last resort measure to produce valid code.
I agree this is a bug, I'm going to mark it stylistic but it can be fixed against the master branch.

**Comment by knocte** [comment]
> I'm going to mark it stylistic

AFAIU, idempotency problems are never marked as stylistic. Please note that this is not just superflous addition of parentheses, if you run fantomas 3 times, 3 pairs of parentheses are added.
