### ISSUE TITLE
Stroustrup: Type alias for anonymous record type

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2179]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WACgE6zYDOYAvADqFUB2EwAPmAMqKmkCWsdAkvDSl0hLnQDmNehBkARLqWwBDdNAAWaALKlxYALQA%2BMAFc6XdFIYywAeToAVRAA90SwoiUAxWNGOk0pub6RoHoYEwAvpaWWLgExGSUloxsHNy8AkIiYpK0VhDyiirqWjrBJmYWedZ2ji5uHt6%2B-hVBhq1hUXmQADTgUKSI6Og5pKhgANr9jNMykAAkschokGLovbMQCwBuSgA2xsuTmzIADH3W1pB8dEh06KxcAF7IF5cQACwnALqzEW8zd4LJbjVb3DZA%2Ba7A5HKbvCAARgBl0gmiUTgAMmJEBjEBJ0GoIfCEQAmU4-P7I0CQkErPHwGwAMyxdEQrCwe1eJx2%2B0O4zh8JJyKuAFFbkyWVz4VA9ozIBTrP9ZtSUYscEdIAAjWCwPZEq5Q3mwk4QADMwrmN0GhHQnjE%2BwAcogAO57bH6y4iQ4KmRK6wqg20qDa3UeraGmH8k1gD4WrbsAC2XDge14AEF0GKGcz3XGwIz9oMfRA-TIA3M1bhQSG9RaeZG0AL3gBWPOQVjKaCIABCiEZsHc%2BDcSgTQ0QhDDMi9iGLYFLgNVQa1Otr3IjfMb0YAbG2O0ou73%2B%2B4MbBnePoEpBjdtj4VDw6JOINPZ-OwOXw0ua5P6xvjtKAOy7p2PZ9gOiAAKrYLghAXledA3heIy8I%2B%2BaFjO7y-IqVJrp%2BK7fuuxrSgAHEB%2B4gUeiAAMJ7JepCUbwwiEMY0DoAOKEFnsRYYZSyo4eq1Z4XWBFRtKACcpEHqB7iaIgCaauO7FoS%2B2E0vxKxfkJ0K-k2lwIuc0btsBh5gfRqYPnmHFcZcmG%2Bipi5qcGglrlphHEkiBl7l2aaMug470QmCZKChz7cVhvGqVW6lOZCLkicSQoeUZUlsrJya6shFlKaFtnhfZkWOaGmlGnF7wIuaiVkd5vmEImaVmcFTHodZPH%2Bnx%2BXLoVznFZu0oIrGBk3Hc6C1IQmAAOrmISmWcU11g2SWdmBg5HWrjF3V-sSrYVV5xCmPAsiIG6SbVQ13rZQtuVLe1az4bFPXEjuBlok4fCMvYah4iKM2sGoA7oBN8AEihHzkudc6LRWS43UVDYbaVgFPeiNyMlwTg2NBKgDiKTjYO4nD3ihzag81YWtRFGrQ11sM6dYCIkYjTgAEqIHAhDwADQN5iDymXZDy2U2t1PRgi4kM8zrPwA6xhyeOTJ8L5CZjHmCI82TeUagmxh7CMbqst4hCBcM472PxMPadGZJtuLA7wJoWs69i%2BuGydbbqMOLHjgA%2Bs6XCA4Sqtlm1FPgmbrnvCS7nSqi6JpoQhBKJgNiEFiwgc1N0bc2Dr7vlAlbB%2BsoclZcJIJVHz2x-HifJwo6BSzLhBywrSvCwHC5XRr9tcLriBOyo1Um1Whf3eH5VRxXCdJyn6B29rXeOwOzsKa7aju9V3u%2B0DrdvkHoIC6qd1w8X-Vl%2BiABqRrdmI8A5GnKFEcTc0tYH5O7yHVPm9KJJbSfTieKYLH3kvrcG%2BG907SkziTHKat26vwLu-MOxdHo-1kLAdAABxIY2NcZpHvLfPMRMt452BMtDS8Ci7WBJAjMundu7dlTNAAA1t2eOjChikDsKwEcVFdTS3MtGEKkCLrQL5u1UhgsP6CnplHJ0rpsS9nQGePEA9EAHRRpUe8aZbgyXrs3aUllZoyHmuDXmH4SHRX3utGmMgSSiyjgAaUQIgbAr13p4huJw0ckpFIzUITvFYe8DQHysWafSP8vpJlIGoPBGcH6GKfm3ERGoxEWKFtKU0kd4TthyJyWO4hpZ4n%2BogTUmgEBSnhPo3xL8oqdXEQg6wppS6ZLTG6cQdA-50AAbwR4rSVDGHcPYWAg0Cl3gytGCpWcIamNEeYwJljoymlHk07W446B3m2DiXg4htHyUIKosQ5h7y6PKVlQRxjhFTKSTMisQT5nH0yTPEYkoMQjk1PAJQ1FYDcAkDI7u3irKP1Js-dWAkakpIke8U039MmFCUJqTk4SFBqFYJge46I-kGIgEY7OfiCqrTBXUmQpokGZIcU4oZ9wbjMKUB0sBxyfETJMbnXCoLZmpPhKaKhmS6HUoYZKUgsdYB7SdMIRAtsaHYiwXjdIdAjnvAEQCqBQKYHVLxay8FlxTRSK5W4Yy7hCjQFEEmVZvl4DgTMLwA60AaLxyQnwvRJyFVCKVYkkFqrrlzLSbYzJjMlA9OIAw06GKwBYsmUysxLL3VsveCDXc2QWIlKQOil8-RvhvFWKQTw3BxgVIiEAA)

#### Code

```fsharp
type Props =
  {| SessionId: string
     Dispatch: Msg -> unit
     OnTextareaFocus: unit -> unit |}

type Props =
  { SessionId: string
    Dispatch: Msg -> unit
    OnTextareaFocus: unit -> unit }

```
            

#### Result

```fsharp
type Props =
    {| SessionId: string
       Dispatch: Msg -> unit
       OnTextareaFocus: unit -> unit |}

type Props = {
    SessionId: string
    Dispatch: Msg -> unit
    OnTextareaFocus: unit -> unit
}

```
            
#### Problem description

I propose to include this case as part of the scope of https://github.com/fsprojects/fantomas/issues/1408
Expected result:
```fsharp
type Props = {| 
    SessionId: string
    Dispatch: Msg -> unit
    OnTextareaFocus: unit -> unit 
|}
```

To solve this, [fsharp_multiline_block_brackets_on_same_column](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WACgE6zYDOYAvGMAD5gA6h9AdhBAMqKmkCWszASXhpS6Qj2YBzRizZgAIj1LYAhumgALNAFlSksAFoAfGACuzHuhms2AeWYAVRAA90KwohUAxWNFOk0c0tDEyD0BiZmGgBfSAAacChSRHR0CUlSVDAAbUSIUDkISAASLFwsyAl0eLy2EoA3FQAbU2Q0XMK2AAYEzqKBZiRmdHYeAC9kXr6AFlqIAF1a6Kn8uahSnDaoKprOhubWrI6%2BgEYVwshtFWcAGQlEG8QpdA1d04AmLrXFuWXagouG3KaEgT3gtgAZndmIh2FgmpM1vsWltjp13uc5JAAKKDSHQxF9KBNCGQb5Lc4ArFAraQABGsFgTTe1MaKKOawgAGZMXUBslCOgvBJmgA5RAAdya9xZhTErXJv0pSJpFQZTNlRWKbMO7U5YGmvKKnAAtjw4E1%2BABBdC48FQmVGsAQ5rJRVsP5yKl1VUg9XM3nI3U5fUAVidkHYqmgiAAQogIbAPPh3CoTSlEIRNWx5Yh3RBPWxvVqyrT-dmg6j9QA2CNRlQx%2BOJjw3WASzPQFTJAb1XxqPjMbMQXP5sCF1Z7X1QcuB7UHKtEgDsdejcYTScQAFVsLhCJ3u8xe520vwh87XXnOj8PcrJ6W1YyAyqdQu%2BgAOFcNtfNxAAYSaXakL%2B-CiIQpjQOgSZni6TRuleFL-Cq95%2Bo%2BFZzuyepEgAnJ%2Bjbrh42iICadKZtBF6juO1BIZsD4arOL4ckSJw9Pqkark2G7AZag5OjBcGFNeBa3oCyHTqh9HzoxpxnKx9YxlaELoJmwEmiaKhniO8FKohd40ShdHPpJmEfLh34bqa5pMqevHkVpN46SJeliQZk4McZnQnDysmrgpSmEBZFrWfqmkCQhXrUcCzlPq5RkhkxhqsQMQzoPYDiEJgADqlivDZsGXqF2nhbpkX0uJhkYXFpzht5X5WsQ5jwPIiDSmafkaWB%2BVyIJY7CdSomVMMaFuZVHm1qxVzOAIEIOBoTzYnl7AaEm6BZfALxntMXx2UJDl9U5A3VBJFVooUJzLuN1wDBCPDOLYu5qEm2LONgHjcAOZ6hltBX2UVjklTsR3BidcgnB%2BF3OAASogcCEPAq3rU6m0Ub1Pr9QD5VA-qJw4eDUMw-AoqmMRmaQgISkmpkTonMju2o-tJqmE0aTSjCPiEGpqSZg4NGA6%2B6IsUSkB40m8DaIzzP3GzHNtRGmiphBmYAPoSjwa2vDTv17f9g281J6IyYLE11YQKiYLYhB3KI8M5fqSPbT1tMlvt6Mxcd%2BrvBi4PG6b5uW%2BghPE4QpPk5TWMa0WEW0gzTM8CziBS2ofnc%2BUuvuYU7xeYL3tmxbSjoGLMdxwnnNZrLGjy35yuq%2Bt4cTn9tIu4Cw3A2w7wJYb1wAGrzrGEjwOk1tnm%2BX1dWFEfFQ3OsY3z6fVR3zheOYEEDr3gwD9XNtEnb307ZrdPa4d096%2BnY3z-IsDoAA4ikT0vVwvD8IPTqfbXVET7R0VN7FLcQO852G%2BLWO9xYyWmgAAa1jCbcBKRSD2HYGmP8TIiY8WCh1V%2BxZ1j9RnEfNOch3hg0FuKKUwCUjtieMnRATVroWBPMwK0gxCKB1DkSPinU2DdUohgkoWCyqu0xkSd4ONBYAGlECIGwFNGaTwBjwPTASMieV0GRwqI3Vk399RcgFn0S41x5pmlIBoJ%2BtsR7sLHnXLWZZeFfzdkSLkBttGjCkAiOqkgiZPBWogOk2gECEj6KwpR799KfzUTYvoXJPZZ2lJIZgi9mDL34KMaJahTAeAcLAJK7j%2BxBRYbZHeDs95OxKtgvhM85Bckztoq0TNMzMH7PUB4-BJCMJIoQKhEhLADmYX43Jo9Crj3rh-Ia6jbHt20QXNIBIbhpjpPAFQ-5YC8CkEQuOCj%2BK9J%2Bv0ixgzU4jUKFyOe2jFCkBUHSBEeilAaHYJgYY1xVlsIWGYt%2BAyglDNCZ0Lkp9tGiPERk4YAxIEqDiZvbpij7acOUS8nZP8wBcn-tokBgKwEElIHVWADVxSiEQKLQBcdb6vQfswLpnQQrrN3ps-eliXLWP4WEgh8L3AcQ8Ec6A4gzS1KUvATcFh%2BBNWgABE2tC7kBOeVFV5NL3lCO0RDFQSTiBgKFWClGhTKXBJ9M3YxdYxDmnzj4hVeToiJHmFMSopAvC8CyP46IQA) would need to respected first.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-04-01T14:31:49Z - b6828ffefe7618b7441f0a85925b281c2b337aa8

```fsharp
    { config with
                MultilineBlockBracketsOnSameColumn = true
                Ragnarok = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hi @josh-degraw, could I inspire you to take a peek at this as well?

```fsharp
type Props =
  {| SessionId: string
     Dispatch: Msg -> unit
     OnTextareaFocus: unit -> unit |}
```

Is actually a [TypeDefnAbbrevNode](https://fsprojects.github.io/fantomas/reference/fantomas-core-syntaxoak-typedefnabbrevnode.html) where the type would be [TypeAnonRecordNode](https://fsprojects.github.io/fantomas/reference/fantomas-core-syntaxoak-typeanonrecordnode.html).

As the aligned version is working these days, it would be a matter of adding more logic before the new line between the header and body of the type definition. 

https://github.com/fsprojects/fantomas/blob/7c3b2e9d5971512be3bdbc6be4253f11068d5342/src/Fantomas.Core/CodePrinter.fs#L3351-L3366

Most likely quite specific logic is only relevant to this case.
Things like:
- config is stroustrup
- type is anon record type
- no members
- the body is multiline

**Comment by josh-degraw** [comment]
Yep this was next on my list to look into! I'll give it a try today if I get a chance.
