### ISSUE TITLE
Revisit Elmish code

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2180]
## Introduction

We currently have multiple settings to control a subset of function applications with array/lists as arguments.
The rationale behind this is described in [Formatting Elmish style guide](https://github.com/fsprojects/fantomas/blob/master/docs/Formatting-Elmish-code.md) and has a certain overlap with https://github.com/fsprojects/fantomas/issues/1408. https://github.com/fsprojects/fantomas/issues/1275 is always related in a way and it would be nice if we can consolidate everything in a general fashion.

## Proposal

As part of #1408, I propose to move and expand the current Elmish settings. To generalize and apply an alternative style for function applications that end with a list/array.

### Scope

Every (nested) [SynExp.App](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-synexpr.html#App) that ends with one or two [SynExpr.ArrayOrListComputed](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-synexpr.html#ArrayOrListComputed) (or [SynExpr.ArrayOrList](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-synexpr.html#ArrayOrList)).

Examples:
```fsharp
f1 a1 [ b1 ; b2 ; b3 ]

f2 [ a1; a2; a3 ] [ b1; b2; b3 ]

f3 a b c [ d1; d2 ]
```

Arguments before the final list arguments can be of any [SynExpr](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-synexpr.html).

### Rules

First of, try and fit the expression on one line:

```fsharp
fn a [ b1; b1 ]
```

If the expression is longer than a threshold (be it [max_line_length](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#max_line_length) or [fsharp_max_elmish_width](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_max_elmish_width))

It should put the elements of the list on the next line indented:

```fsharp
fn a [
    b1
    b2
]
```

Assuming the function name and additional arguments (`fn a`) fit on the same line, otherwise the default formatting rules should apply.

```fsharp
fn
   a
   [
        b1
        b2
   ]
```

When there are two lists at the end, there would be slight variation where the same rules are applied.

```fsharp
// try on single line first
fn [ a1; a2 ] [ b1; b2 ]

// only put last argument on next line, assuming `fn [ a1; a2 ]` fits on one line
fn [ a1; a2 ] [
    b1
    b2
]

// put both list on new lines
fn [
    a1
    a2
] [
    b1
    b2
]
```

Notice that the `] [` is on a separate line to visually indicate the difference of the elements of both list.
In Elmish code, the first list typically has properties, where the second list will contains children.

## Real world samples

These formatted according to the rules above.

```fsharp
fragment [] [
    View.navigation dispatch

    Row.row [
        Row.Custom [ ClassName "no-gutters" Id "main" ] 
    ] [
        View.editor model dispatch
        React.router [ 
            router.onUrlChanged onUrlChanged
            router.children [ routes ] 
        ]
    ]
]
```

```fsharp
Html.div [
    Html.button [
        prop.style [ style.marginRight 5 ]
        prop.onClick (fun _ -> setCount(count + 1))
        prop.text "Increment"
    ]

    Html.button [
        prop.style [ style.marginLeft 5 ]
        prop.onClick (fun _ -> setCount(count - 1))
        prop.text "Decrement"
    ]

    Html.h1 count
]
```

```fsharp
testList "A test group" [ 
    test "one test" { Expect.equal (2 + 2) 4 "2+2" }

    test "another test that fails" { Expect.equal (3 + 3) 5 "3+3" }

    testAsync "this is an async test" {
        let! x = async { return 4 }
        Expect.equal x (2 + 2) "2+2"
    }

    testTask "this is a task test" {
        let! n = Task.FromResult 2
        Expect.equal n 2 "n=2"
    } 
]
```

## Open questions

- Should this all be under the same setting of `Stroustrup bracket style`? I personally believe so, but I'm open to ideas.
- How much flexibility should there be for the threshold?
- Perhaps this should be considered a default in the MS style guide? The proposed rules share some elements with how lambdas and computation expressions are formatted.

**Comment by nojaf** [comment]
Hello, you need to enable `fsharp_multiline_block_brackets_on_same_column` as well when using `fsharp_experimental_stroustrup_style`. [Fantomas Tools](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAggA5EA6AdhbEYuWAGKI4CWAXhRQNoA8ASogENoAFwDCsdEVjlawgHwBdCnmFhxWcsMQAnABQBKMAF4KECCrC64G4QBowAZ0RjYNw0bD8hwgHRYnAMrCAlq6AAz6pmYAEsLoOD7wzABuYJxRZjFxCQBGWMLC0mkZmaVE2tQ%2BDsIAnnhpjrV4PugC2gDmzOS8zO0AFqoArGBKdKXj5ZXSoizQANaWAGYaYAD6YAC0co7O6ppWrppgANRgAIz6kWPjmZNEPloAHqqkkACS5NDaiOiyryWZUYArLxHx5ApFdLXG4QO5VJr4TiNOqIFptTrkAAyiEWQxGwImFXu01mC10yzo6y2OxcNgONk250uBLKRIeiGeYFeABFEF8fn9ICygdDMrFQX0zmBrJoSiLqLQwAAhCoAdyc2h83IkHG6ghE3IA8gBZHzfchIPR7LR6fT2eCwaBYX6aHztZwAUTwLuESpqb3gXMgFVgwle%2BkgtnAUCcBS67QcqDS0YgoHGkAAJLUaEnIF1hJGU2ZM8kBDgsMg0Jwi5kwlGYe8LbIAmxkPWbgAWGsjIsAX3bqe7mezlag%2BcL6YzpfLo%2BrMLOA9KkGNAkemK6iGx5Hawj6E5uZwATGFuwo%2B4u00uszUc2hILR4IbFuuZEEUfvMiWyxWk3ObofF0-D0LSfF8227CBIBwRZIFPc8i0vT9r1vKAclgWAcA-Ysp2-WcILAABmQDiw%2BDVhHoLoywAOUQVUWBkLDMmEbQKzgzJ%2BwQodkNHSA0IwxioBwmdf3wjtiMggIiCERAlRxWBvgABTaARfhtASIGY1jxjPdiLy4kdcz4zDiK-YSq3wwZxKgSTpNkxZ5M3WBVR0aABCcD5kkdEJmGkdSwE0xA2LMDjMkQ7CDLvIyBNMn9zJhAA2KzIBs6AZLk74AFUSBctzEA8rzhB88g-MWMsnCCiAQrMMLIO4wz0OMrjp1i5MYQAdiSlK0vs74ZjchxxHIaoWJEeSSrKwLtPg0L9JvHiopMoSWr-cYAA5Oqk1K7Ic40fhyHRxpwcqpt0zjJwi1CGuipa8JhABODbbPSxBxBwXyrNKo7JtKHTgr0865vq-jFua26DzrfDks2xACFxHRxHQVo-ICiqwCqwcAZQ3irpB3CRPnBdIa67bvgCH5mDgN7io%2BibUfRsAasEi7seBpq8big8AKJ6HYZtMn0ApjD3vwlGTr%2Bs6r2Zha2bM1qDyI7npIICoNHgXkWAFtSrNFn7puq2asfHXHZZW0ozjEyGV0eN5FgAFT6WgAj6eThAAdWYeBdz8k8xcq-7JcBu8jZl5b8LOSzLdXG37doL1Amd7Q3Y9r2rPin3ddOmbMZ44PJ1B-GD0SyPrfIRZmEeQ0aG0EJ5I9R5ykQBwHCKvzVvTwE9YxgPDc0a78458Yzg64v%2BDgbR4Hdz29ysjt27MX6-YlpDmdzq9%2B7lwf1pHvl5PgKjnX27QnzeLR0ETKyzjp-3l8DjBcEK%2BjEHoeTWgKHRbcB43Q-nB7IdH3fjT32YI-Z%2B2hX5a0htAPoykRA6FWKqZOe4r5L3CrfPMvcv5g3GMeJKVtlbVxqIabQ65qiTxTvhNuyCs7dxzhgkOWDSiHkJg2PB2gCFEJIcIfe6BD7H1PufMOVD9bZ1zOgIBICX4hBtB-HMmCC7YK5g2fBAhCHEOYNUQBOAH4blAeAg6SUoEwJtPAxBsFfZo2vqgnuBY5ED0YQrFhq4ABquElRdCSNuMh08KFzwgAvCxKDaorzoXndmG9GEW0cY8egGgRBFTcRaeMXi-KzyEV3G%2B1i%2B5hNNpkQ8EconamEAAcU9PXb4TcirJKspQ8x9NGbDjQdLUJJt8KHiLiw8RG4lRvXmCqIQcxnAOENOQAIKkXoYWdNTEWLFvod0zsImhQNGrNO-v%2BYeDYaJ0S6c4ZytAZGIF5GXcgzBCrSAIBaXaPCdACJhDrOZ4tqEZPmjjeh8jGFbyUSwdo5AYmfFOSM3o5AQhYG%2BLbWAHwkCaG8sLGEn1joZweQsp5SysktJhIeX%2BnybRAsKskRy25LmH0OV0E5RUbk3DhbM%2BencGYG2eazFZDDMgEQhh0rRzAwKYhUjkeAAgZiwGbtuTZj9DrwvuYvR5Vj6XLLXtk-CBFmE3EgHXKuzAfRlgANKIEQEQCFsgPh9M%2BN42FtNamWKCY0l5jK3nMsUUq7pAhyBzDAg4ZWhw96Ny0PATR2iZAqvKc3aQ5Lxh3OpfM9JUqUW2PCcyhx9q2gkwOeor4arKJeoysc6QvJoA4GUv80VVK-E0vqXVSKVrZVopuARSJSqVU6DVbIMsQQVbDSwEQN8eBkYzLSbSkRQcQkVtWeMAi%2BSlVap1VbbhvDFgOqdS6vyZwwi%2BJ7OG3tiyy0MsHUyswBF2lKubRTYQxoEDgRNV9Om0YFDtjzA4egzckyUpAL2IAA)

**Comment by panmau** [comment]
Ah, thanks! Good to see that it still works, was worried for a second there :)

**Comment by MangelMaxime** [comment]
Hello @nojaf,

I am trying to use fantomas in one of my project as fantomas is becoming more and more popular (good job on that).

But there is a bug in fantomas `5.0.0-alpha-001` and `5.0.0-alpha-002` when trying to use a configuration to format Feliz code style.

```yaml
[*.{fs,fsx}]
fsharp_max_record_width=0
fsharp_multiline_block_brackets_on_same_column=true
fsharp_bar_before_discriminated_union_declaration=true
fsharp_experimental_stroustrup_style=true
```

Original code:

```fs

let mainPage (ctx: SiteContents) (pageContent: ReactElement) =
    let titleText =
        ctx.TryGetValue<GlobalLoader.SiteInfo>()
        |> Option.map (fun siteInfo -> siteInfo.title)
        |> Option.defaultValue ""

    html [
        head [
            meta [
                prop.charset "utf-8"
            ]
            meta [
                prop.name "viewport"
                prop.content "width=device-width, initial-scale=1"
            ]
            link [
                prop.rel "stylesheet"
                prop.href "/style.css"
            ]
            title titleText
            script [ prop.src "https://code.iconify.design/2/2.2.1/iconify.min.js" ]
        ]

        body [
            pageContent

            span [
                prop.className "iconify-inline"
                prop.custom("icon", "simple-icons:github")
            ]

            footer [
                prop.className "site-footer"
                prop.children [
                    p [
                        prop.className "site-footer--copyright"
                        prop.text "© 2022 Maxime"
                    ]
                    ul [
                        prop.className "site-footer--social"
                        prop.children [

                            span [
                                prop.className "iconify-inline"
                                prop.custom("icon", "simple-icons:github")
                            ]

                        ]
                    ]
                ]
            ]

        ]
    ]
    |> Render.htmlDocument
```

Local: `fantomas `5.0.0-alpha-002`

```fs
let mainPage (ctx: SiteContents) (pageContent: ReactElement) =
    let titleText =
        ctx.TryGetValue<GlobalLoader.SiteInfo>()
        |> Option.map (fun siteInfo -> siteInfo.title)
        |> Option.defaultValue ""

    html [ head [ meta [ prop.charset "utf-8" ]
                  meta [ prop.name "viewport"
                         prop.content "width=device-width, initial-scale=1" ]
                  link [ prop.rel "stylesheet"
                         prop.href "/style.css" ]
                  title titleText
                  script [ prop.src "https://code.iconify.design/2/2.2.1/iconify.min.js" ] ]

           body [ pageContent

                  span [ prop.className "iconify-inline"
                         prop.custom ("icon", "simple-icons:github") ]

                  footer [ prop.className "site-footer"
                           prop.children [ p [ prop.className "site-footer--copyright"
                                               prop.text "© 2022 Maxime" ]
                                           ul [ prop.className "site-footer--social"
                                                prop.children [

                                                                span [ prop.className "iconify-inline"
                                                                       prop.custom ("icon", "simple-icons:github") ]

                                                                 ] ] ] ]

                   ] ]
    |> Render.htmlDocument
```

Fantomas online / master branch:

```fs
let mainPage (ctx: SiteContents) (pageContent: ReactElement) =
    let titleText =
        ctx.TryGetValue<GlobalLoader.SiteInfo>()
        |> Option.map (fun siteInfo -> siteInfo.title)
        |> Option.defaultValue ""

    html [
        head [
            meta [ prop.charset "utf-8" ]
            meta [ prop.name "viewport"; prop.content "width=device-width, initial-scale=1" ]
            link [ prop.rel "stylesheet"; prop.href "/style.css" ]
            title titleText
            script [ prop.src "https://code.iconify.design/2/2.2.1/iconify.min.js" ]
        ]

        body [
            pageContent

            span [ prop.className "iconify-inline"; prop.custom ("icon", "simple-icons:github") ]

            footer [
                prop.className "site-footer"
                prop.children [
                    p [ prop.className "site-footer--copyright"; prop.text "© 2022 Maxime" ]
                    ul [
                        prop.className "site-footer--social"
                        prop.children [

                            span [ prop.className "iconify-inline"; prop.custom ("icon", "simple-icons:github") ]

                        ]
                    ]
                ]
            ]

        ]
    ]
    |> Render.htmlDocument
```

I tested the current master version and it works locally so this is indeed a bug in the released beta version. Would be nice to have a new release to have the bug fixes because when writing view code it hurts ^^.
