### ISSUE TITLE
Consistency: Remove space between unary/prefix operators and literal arguments

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#2181]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBSAngHQE7YDs9D0AmYo-A9LCim8qigMhyauccJdbo876EAhG25UhXSsJGCCQibKEB%2BUVLlLJFeSsXLJkADTgoAZ0QAXcwEsCAcxOowAbWMRQED1AAk5zAAdkNEgbc0NXD0gvADcAQwAbAFdA53DPAAYjT09IAEkCJAJzAGUrAC9kTKyIABZUsABdcIBfSrc6yN8Ax2DCsKrI2MTklyqIAEZWrMgAWRiADwAZG0QFxDtzAAs%2B0bHSNLrGzxbw9ymff2TINfgAeQAzJYJEIt84ivbo%2BKTHEdHSSeyAFF8vdHu9RlA4ndIAdmpNTtlzl0ggAjWCwOLbRGDb5oX5VADMAIieTMuHMADEbPEAHKIADucWWWKy5lwSVhR3hH06lzRGJZEAGX2GdRqxKFRUQAFsrHA4rACABBczA24PZkSsB3eJmTkeY6eBERJF89GY4nCoY-MVgACsWsgRT8MWgiAAQog7rBcIgAAoxXAxaUWRC4QUeNkcqqHA3c-qm7r8i0fHGiiEANkdztdHq9PpWsHpYegMTMeSisFL1kVEYgUcQ%2Bogho8xqFidR5ojVtxKQhAHZsy63Z7vb6AKp%2BAK4UvlgiV6tWWtanVxPUxuEnHkXJNdy2fa1420ADiHudHBYAwnEyyZL4qTFHoOYfXXtbrGxuuVuE7zdwL9zTG0IQATjPEd819aYZRRMM31XdcsljZt4zOP9OwA1MRWAnYMltJ1hzzMdEHvBUCHgj8mzAFs2l-HcMJTBMgKPCExgmfCczdJU7nMMN72laUYjfBsqJosA228dCoGTbsD17fEsl2cCiILKVZXlZdbQQz8kM3I1t2RaS9yww8%2Bx2IkOMI7jeNwNS5QxTSIREr84x-ND6KMzCmOwlidmqR08gKcwbgIAAVXBMAAdSsTYKLXHTPGQ6jUMRKTIBkwCfLMqoxgdSzcyVXBYASfIABFECZWUbOE9kEo8JKxIkjoPJ6UJMtMhTPDGLN8NmOYcjuUKNjWQF4qKDYfXMaL4FirVqn2FyULc1KWpCWTmOyxTB16%2BY8juKw5huacYhfXBATmPxfRMEwl3IrU7QW3Tv30ujDNa9ass6jwxlPHa5gAJUQOBcHgabZttebRJSk00rW9r5NtMYwL%2BwHgfgGkEmlWDcHuHJeOlBwtTGKHlphlrpQSOJrCZJ4KR9QTLDDUKd3h9M-jwiFIFRn14GmSnqeWOncAZ6rHWgDZA1dGyAH16SsGathJl73LeuGTIRiFSHYzm%2BsKoNMBuXAlkfMGtjmx7Er01sDMuNXvI621SH%2BP69ZiA2jasR8MaxsNcfxwnEaV63XsuCmqasGnECFkWmZZ9W2aqUgLM5133eN8w%2BfDyPo5O0X8PFyXnzDWX5dioPaJV23elZnDE-8v6ADURXdGx4BsWxTbfY8Lfqq2K5W1Xq-j2uslIPKdfmCkSufW6W-ydvO-N8vxJt7o7bODavogUgeonuZStgcwAHELHOy7EGu27F9tB7l6ajtPMYjfPsd7adf5iPlndBVoAAa3dIMf8LAmBCkUYMJEMSYzulpSii1kqk3bGlDKw9fKJ1%2BpzOkjIv4WGLGsZmARyr7QIDFW6Sp8jQR9rgAOEJtJ31XgxD6DtNbI05gAaUQIgPwA0hprDyGAkMYI4qIUts9YOlc15D3thrUYBIOajBmPMUasoTAbGvhCSGcDGr0Mfow6RhJtbyJKHYN4hVbCYzWFNRAKJpgIHBKMWhmjoaIJasgqRCcsgEmdinJktgCBTwIDPRUJRfEnQSL6UKsBAoWJOrdIRdUIANScZJFxxk3Ej08ASZO8ilRUzDAQGJURCx2AodjQhNgSEPjiXQkO-4n7YhfhCAk9d37hzBAsYMKJ4AxGvLAG6dhMGRyqY4hByS3quOfkwmR495GlU9jEFEbwlGew2EUTAhR5hDKeq5ZWA8zReQmXojxu95HsM4VEwoeQAExACWbGB8VqniIYTXVBHi37yO-tc3%2BYITCFWKvkOkj5EC8w-pHM%2BV0bqVK1M5LZS0dlkzGakg57iMnoPeYGC8vpZkmGgLgKwsp8m8XgOOYhipyrQBvEGGs0CaGwJhfAuFziEX7PqZMwkLD5H-RiCEoqv9NkiO2WI3ZtTdHIo8PNbMbI5QZ1sXy3uRxjD1EqMEEwFIbqOFoU0IAA)

#### Code

```fsharp
%y

%2

%%y

%%2

&y

&2

&&y

&&2

!y

!2

!!y

!!2

!?y

!?2

!!?y

!!?2

```
            

#### Result

```fsharp
%y

% 2

%%y

%% 2

&y

&2

&&y

&&2

!y

! 2

!!y

!! 2

!?y

!? 2

!!?y

!!? 2

```
            
#### Problem description

Fantomas sometimes (i.e., for some operators) places a space between unary operators and literal arguments. The examples above demonstrate this for some standard unary/prefix operators as well as some I use frequently in my own code (some of which shadow standard ones I never use).

Fantomas should treat all unary/prefix operators consistently, i.e. no space between the operator and its argument.

(In case it's relevant, keep in mind that Fantomas can't know the semantics of the operator; it can be shadowed by a user-defined operator.)

As a motivating real-world example, imagine I have defined a `!` operator to call `op_Implicit`, and I have a `UserId` single-case DU that is implicitly convertible from an `int`. Then I call a function `getUser` that accepts a `UserId`:

```f#
getUser !1
```

The above is formatted as

```f#
getUser ! 1
```

which looks weird and is inconsistent with

```f#
getUser !intUserId
```

which is formatted correctly.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-04-01T14:31:49Z - b6828ffefe7618b7441f0a85925b281c2b337aa8

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
This should be discussed in the [style guide](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for) at [fsharp/fslang-design](https://github.com/fsharp/fslang-design#style-guide).
