### ISSUE TITLE
XML docs for commented code automatically removed

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/fantomas#2186]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6TYA8BnArgLaECGATgJ4B8AOgHabpgDKshiYcxidALvYxzoCxctQFNeFAA4cAKoly8AqnQCWsOmAC8YAGJqySsAB8WiOHXhhYAMzBq%2BpsHIAWh63bBKyjgOb0kAA04FC4iLy8-rioYADaoRCgEClQACRSsrGQjrzBiSmQaQBuJAA2%2BMhoCampAAwhtYUAklY8vMxqAF7IjU1gACwFEAC6BQC%2BfUnD6ZlVULn5TUWlFfM1-QCMU7WQALIkAB4AMo6Ixzx%2BvK5LWwBMdTNjqZMFybsZMvOQPPAA8rZTnREMwpGVejMVuVKrENk07jtUpAAKJWAFAiH9KBlWyQJ4THbvJGfLJoSAAI1gsDKt2Jqxh1RmEAAzIiWnRwmReAY6OUAHKIADuZTOtNqvDIlXxL0JkJJ30p1LFECha1hTMGbJVzEQhDUcDKmgAgrxUf9AaKtWBbOVwtKUq9UkTCvLsoqaWzVQz4hqAKxWyDMaQkaCIABCiFssDIiAACuQSOxeIgyMqUhKpU1ng7ZctXWT3WmvesNQA2ANBkPhyPR86wQUp6AkcKtYqwJtRTRpiA2sp2rMEt5yuZuqkeuX0ktYgDsFeDoYjUZjymksjITZbdDbHY0dG71ttiHtEEdKWdKvzUELnpK0Kn-QAHHOq4vawBhMrN3BvzQ%2BfDQXho33Xt%2B1qbMT1zD4RwLMci1vNVGSxABOZ8FxrGM9l1ckU2Aw9jzAU9pjzaCr1gm9J3VLFNgaDVA3nasl0QH9DT3K0QKPAcZSHYivlHJVyLvSitm2WjK1DI1bGTMgf1EfcMw4sDBydYdeJg-iJ0ExD7lQhjax1PUDS7Ni8M4nNuKg1TSPUvMKK0ppNlZUT6IkqT9P1akjI1eT8MIsBz1mSyKTIjSEJ9KiBgDVokD4P46DkSgAHU1GuXC%2BwU1JwIIyDiRIoLrI%2BWywq2f0nKrI0yFgfArAAEUQEU9SkuTJXSlJMt8-yilyxYBNCuFak2ctaIOQ5mlsNweGRNLmFcaNeCS%2BAUqtAZHlMiDzJywLupC70%2BtSTZZyGo5WlsNRDj%2BNcSEAshkUOaQY1wXBd33X0VsUrjlJ40kFj4ODCt2lJNifQ7DgAJQsaN4HmxaNWWnzspdLqfp6naNU2FDgbBuAyHgPkiGwsgAWaZNCBiK1Njh9aEcCwh8DKKIRWBPRo1ISIUzkXjkfveEaKxSBMYhvZafps4mbIFnGoDaBXATACUwAfUFNQFpuCmPosr6ciR7audqO4RN54byrIEgKD%2BMhTiUKGbiW16MqUs8VI1rabM0or4QRYGjZNs2Ld4XHCHxwnidJ1HVYdz7vhpum1AZxBRfFtmOe1oT4Uc3mvdN821CUQXo9j%2BPLol2ipZlqSFaVlKw6I9XvmdgrXf%2BiA7gi4GADU7zDRx4H8K39wfW3Wvt6uNqdrWXd6jU7hKg2jj0KqAN3TurB7ivrZhgfRiHvzHdrsf64nrE7kGmfDmq2BeAAcQiG67sUR7NF7q0Xqr7eI748dx5Rw%2BDoNoWY7OMMhpoAAGswzGxAREXAsVmCJiYtSIgrENTsRfh1S8eUP77y-v0O4QNeYCmFAAiIDYeDs1kLVE66hOx0CNFYTCAcUwhyxMg1aWVKYXlyteZOdldbo15gAaUQIgaQo1xp0FaDA9gGJUqgTtu9cONdsh1zpA3DUzIeb9H2EcSaepcCuEfuvFBO936-RUViZk%2BsNGdDoH4cE5U-BEHaAlRA5I9gIExP0Zhb0zJqxHgqYKn8dapGZB7dOIo-B0DnnQBemhOjhMuvgGMchYBRXaJdJ6xk0qGLfmpDByiD79GZGnDRRo6Ypl5FEYodZrF0PxuQxwyVdyMI8SZLxa0fFUw1pwgJKdajMhbr-aOGJjiJnJPAEgH5YCPWsfg2O0iWqbzkcPDpfj8p5KwU0Zk08NHVWziQck4JtHZ1cMwCgfAjhzKyQonJJj8kbOPhogRQiUl8FaGAkgUS15MJabI7x8jfHGM5j0oJP8NGAPecAjEuByqVSsAKJQiB4C52FsCG%2B9174ciapmVprD2nsMCl0zBgSUjMlwaC8gr4Yw7NwNAXwepykItULuWq0BPzGyoRclh7UjHXMBdwoJvCNEgxIHEiqwCOXYq5dkqyuSXR-XXhWCU%2BpeCuKQOKn5J5QgjD6DkXAehHqxGQeMIAA)

#### Code

```fsharp
/// <summary>
/// Some comment
/// </summary>
// type TestUnion = First | Second of int | Third of string

```
            

#### Result

```fsharp
// type TestUnion = First | Second of int | Third of string

```
            
#### Problem description

Ideally Fantomas should not remove comments during formatting

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-04-01T14:31:49Z - b6828ffefe7618b7441f0a85925b281c2b337aa8

```fsharp
    { config with
                SpaceBeforeLowercaseInvocation = false }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hey Sergey, this is a tricky one.
The XML doc is not attached to any (or any correct) node, so the behaviour is what I expected it to be.
Perhaps Fantomas should not touch this file in the first place as the syntax tree is empty.
Or course, adding another let binding to the file will trigger the same problem.
The AST is already giving out [a warning](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQD0PYAPGgCuAW2FUATgE8AfAB1kPLmADKrYbDBtRsZABd5i-lyGiJMg0t2SADhoAq6XQFVkiVsjABeMMUTi0umAAPiqwbMjQYKzwYCiBIXYAFn6R0WAB4igA5vKQIAC%2BQA) as well.
Changing your XML doc to double slashes seems like the right thing to do here.
But I understand that answer isn't very satisfying.

**Comment by sergey-tihon** [comment]
It was in the middle of the large file - https://github.com/fsprojects/FsUnit/commit/e60510c01cd30ee6e7566678fa069080d2c39de4#diff-badc17ff44c87f5563ad36766e8d42f4dfdb140433e680a9d82c439136af9066L28-L33

I think that it would ok to produce warning in console and skip file from formatting (if it is possible)
But I am not sure if it possible to detect it

**Comment by auduchinok** [comment]
> Changing your XML doc to double slashes seems like the right thing to do here.

it doesn't sound like a thing that a formatter should do to me, to be honest. Could Fantomas just print them as is, maybe?

**Comment by nojaf** [comment]
We don't plan to detect them anymore like we used to do. They are part of the untyped tree unless placed in the wrong location, and then we just don't know about them. There is no "print them as is", we don't know about them in the first place.

If you commented out the type, you should have taken [the triple slashes into account as well](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6TmwB4DOArgLZECGATgJ4B8AOgHZbYDKsRiYcJi9ALg03S50hEhRoChvSgAcOAFUR5eAVXoBLWPTABeMADF15ZWAA%2BYZojj14YWADMw6vmbDyAFkdsOwy8s4BzBkgAGnAoPEReXkC8VDAAbXCIUAg0qAASaTl4yGdeUOS0yAyAN1IAGwJkNCT09IAGMPrigEkbHl5mdQAvZGaWsAAWIogAXSKAXwGU0czsmqh8wpaS8qrFusGARhn6yABZUgAPABlnRFOeAN53FZ2AJga5ifTpotT9rNlFyB54ADy9nO9EQzGkFX6czWlWq8S2LQee3SkAAojYgSCoYMoBV7JAXlM9p8Ud8cmhIAAjWCwCr3UnrOG1OYQADMyLa9Ei5F4hnolQAcogAO4VC70%2Bq8cjVQlvYnQsm-am0iUQGEbeEs4YctWWIjqOAVLQAQV46MBwPFOrA9kqkVlaXe6RJxUVuWVdI56qZiS1AFZrZBmDJSNBEAAhRD2WDkRAABQopHYvEQ5FVaSlMpar0d8tWbopHvT3s2WoAbIHg6GI1GY5dYMLU9BSJF2qVYM2Ylp0xBbRV7dmiR8FQt3TTPQrGaWcQB2SshsOR6OxlQyOTkZut%2Bjtzuaeg9m12xAOiBOtIutUFqBFr1lWHTwYADnn1aXdYAwhUW3h31o-ARoF4GMDz7Ad6hzU88y%2BUdC3HYs7w1ZkcQAThfRda1jA5ECISlUxAo8TzAM9ZnzGDrzg28p01HFtiaLUgwXGtl0QX8jX3a1QOPQc5WHUifjHFVKPvaidl2eiqzDY17BTchfzEA9My48Ch2dEd%2BNgwTJ2EpDHjQpi6z1A1aW7DiCO43NeOg9TyM0-MqJ0lptnZcTGKkmTDMNEytUUwjiLAC95msqkKK0xDfRooZA3aJA%2BABeh5CoAB1dRbnw-slPSCCiKg0kyOC2yvns8KdgDFzq2NchYAIGwABFEDFfUZIU6UMrSLK-ICko8uWISwoReptgreijmOVp7A8HhUXS5h3BjXhkvgVLrSGZ5zMgyzcqCnrQp9fr0m2OdhpOdp7HUY4AXXUggPIVFjhkWM8DwPcDz9VblJ41S%2BPJJY%2BHgoq9rSbZnyO44ACUrBjeAFqWrUVt8nLXW637et2rVtlQkHwbgch4AFYhcPIIFWhTIg4mtbZ4Y2xGgqIAgKhiMVQX0GMyGiVN5H4lGH0ROicUgLHIYOOmGYuZnyFZprA2gdxE0A1MAH1hXURa7kpz6rO%2BvJkZ27n6geMS%2BZGiryFISgAXIc5lGhu5lrezKVPPNTNe2uztOKxEkRB43TfNy3eDxnDUyJkmybRtXHa%2B35afp9RGcQMWJfZzmdZExFnL572zYt9RlCFmO44Tq7Jfo6XZZkxXldS8OSI134XcKt2AYgB5IpBgA1e9w2ceBAmtg9HzttqHZrzbne112%2Bq1B5SsNk59GqwC9y7mxe8rm3YcH8Zh-8p26-HhvJ5xB4htn44atgXgAHEolu%2B6lCerQ%2B%2BtV7q53yOBInCfUaPw7DeF2OLjhiNNAAA1uGE2oCoh4DiswJMLFaTEHYlqTir9OpXnyp-A%2B39BgPGBnzIUopAFREbDwDmcg6qnQ0F2egxobBYUDsYNKYF7YfQjrXD%2Bf1G5TwxnzAA0ogRAMgxoTXoO0WB7AsRMNalvVhI9qZjwKFzVO9RWS80GIcE4U19R4HcE-DeqDd4cKUQ5FRBt1HdHoAESEFUAjEE6IlRAlIDgIGxIMFBa1spU0vHlG8KcTHpFZJ7DOYoAj0HnvQReWhuihKugQWM8hYDRU6FdZ6pl0oGPfhpTBDIuE4lZOndRxp6apn5DEUo9ZLH0IJhQ5wKU9yhxxO496Fl1ajyVCFL%2BusAmtz-jHLEpwkyUngKQT8sAnqWIIXHKRGT2FZM4YfQYrIZ7qJqjnUglJIRaJzu4ZglA%2BAnGmR4jqhi5nGPdiok%2B6j%2BGCKSXwdo4DSARPXo0syzT1qtPke0gqOSFktFZL-dRQDHkgKxHgCqVUbBCmUIgeAecRaglvg9B%2BXJmpZjeZ4j53igq%2BM6cogJeDAUUDfLGVZeBoD%2BH1KUmFag9x1WgF%2BE21DDnouOZkmy2TXT-S1KyHh6jQakBiZVEBzKWEtLYW0oxfjznpBWpWKUBpeDOKQCKoebxwhjAGHkPA%2BgnrxBQZMIAA) while doing it.

**Comment by auduchinok** [comment]
> They are part of the untyped tree unless placed in the wrong location, and then we just don't know about them.

We could add the wrongly placed comments to that collection too, perhaps? :)

**Comment by nojaf** [comment]
Maybe, if we can push the information of https://github.com/dotnet/fsharp/blob/6f1a77804b390c2a6e81f7ec56628075c1b95af1/src/fsharp/ParseHelpers.fs#L143-L145

to the `LexbufCommentStore` that could work.

@DedSec256 any ideas?

**Comment by DedSec256** [comment]
>Maybe, if we can push the information of
https://github.com/dotnet/fsharp/blob/6f1a77804b390c2a6e81f7ec56628075c1b95af1/src/fsharp/ParseHelpers.fs#L143-L145
to the LexbufCommentStore that could work.

Yes, this seems like a good solution to the problem.
