### ISSUE TITLE
XML Doc comments on DU cases seem to get shuffled

### ISSUE THREAD

**Issue by baronfel** [fsprojects/fantomas#2188]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6TYBKiAOATogM6IB2ALsWEQIbGxnUDuAFgJ5i1gWIAeFMPFjQArgFtyggJbVitAG6J4AOgA6BNZXZ5EYACr8KAERESpAZUWJc9RmAC8GrZnRgAsrTKjaAG1%2BcFATSAOYhiETwADRgiCohKmAARoGseqKkBGCEJMTSZCFg8koxKUUUtAQU%2BYVISaJhNVHOZK5gsFllXmAAggAKAJJg0H6%2B6ppkAD4eXj6%2BjmAAjC0tbT2iFLDitNXQXABmvFncSL607ONa0z2HEcaIZ5wOYABMKxNtAOppZDxpsfBpJssr5YMRBPszMRLlMwAAxKEAeQ2CwAzJAouAoKQKNUCsRUGAANpYiCgCAUqAAEgoOmQaEg%2BQoGNJFMgVIUflE9OJrMpAAZMZTKZABmQkJQLNIAF7IIXCiAAFj5YAAuqyAL7yskq9m03SExmUFkK9mc3zcwkkhUQRba4WQTx8AAy%2BUQzvIIQorBNNsWL35KvVlK1rPJDppdMN5HgiP2rrIiAstN8ct1HK5POtNpe9pFAFFxXGE2mbVBfPtIEHNfbwyLIwaGUlYLBfL76%2BbLWhswrUXm2WLMhQ4fk-AA5RDMXxu9vCoLc6sh2vp-U8yDN1uziBmzNWlVK-vbiyIcTSOCgsg9CiF2PxmeHsD7PykRcU0OUutshtrjdt-s7i0s33MAAFYH0gCw8FoaBEAAIUQSEiD6SpaEkI4twpedEFfCB3wpT9t2-Q1fwwgCu15MsADZwMg6C4IQjp3VgZgIhGUgxQUEQdmkRgMIgLCcLAPCdVNIimxbP9007ICywAdhoqCYPgxDEAAVTwXQCDYxAOK46peIfJ9fBfBVgzfZdRNXYiJNIjNAL3MsAA4FLo5TGIAYTOYhiHcxhwQIURoGBPjH2fbDTJrMMVyjcTN3-OzyJ7YUAE4XKUhiiHcE8kgiEKjJM4UzNwiyIys2LJNE6SHL9QVgIgxT6JU3yLzysLBOEsACOpMqoBI%2BKqu7YDFjtOraJgm4jl88RthCgSIqXKLLJi3qbP63dBrLf00saxjj1Pc8DOA-LwsKyKP2ixsVriqT1oov0%2B1GhqJoiPaz1bQ6yzm06FvOpbLvXVabvsja-UVcCxQlChETIfQCHYT4gR9Qy2vm8zFtK5aAeuyrbqSylFjAx66J6AhYFEcV7mnU90IfL7KSKoSSvrHqjWZNbgbuhVFmouqnQGfZ9B%2BfNjKTVgOgoBH4G9ELFUDVHivR5nMaZWyBs54VFnk3naD4MV9mkPhEU0nYOnzPgcm8niyBCkC5e%2BtHfox-6VfZxKhuc7W%2BFwOACHgSXpYfWX2qZr8WZdoG3c21LPe9jp4DHCQcoIOMBl4cQCQfRZg8V0PMfEURfGqadEwRAhtlxCJ9CjV2ZJzWqy0gWPffcAui7dUvy5puroFYFCgoiAB9ZhpCln1s8dpXneNGvqoVF4Robp0SYIc5EQIV1wX9pHgKD%2BXGZzwiw%2BniPa7n3NPeX1f19kCgE-EJOU7TjOhvH-CLrXfPC%2BkYvEA7nYjirgaGeIM54PQbpfdga8N4UBbl-H%2Bf8K4EBCjAXuK9%2B4ECHiPaWr8RJOzXOHHGHM8YUheGDT2AA1TMsF8iAgKFvEKjk7b0zOm-P6%2BDj6EMjjmQmi8dZwnJkFK21DxQ1HoYHJhFIGYdS6nqZWHCIxq2IRAF4PNeF8FMBQAA4oga85siCW0YGI4CtscGdXftZbGCjcbAReFrRerdv5ulgqCaAABrWCaDXE6OINDKwkhmoSGtsjEWpiZFiSuhVKxRCbEewbhOKcTidEsXIIAxA9x9ZkCBFbHo4osr3wiM-Msx1QnmPKqraxZYXjRwbgAaUQPgfmgtyBij8e6e8R0Ub2wVhPXOU82Yn1nsKVE9cbSOh1sLU8xBWBGLLLvLp%2B8emH0xn1AZIChkL1GVKAoqYSYhHMJQT4iAkjuAQKWG0xS97SNKRE8p0SyyonPuA6cIQyD8LIIIxgUoXk7FEEQfQsAIZSG4h9c5nTmE-VYXgixkSOwVJtKiMBoyeiFwiGQbiShnSMBCHkpO6T8hZL8q1EJlyQ5LP%2Biszhp8hlkPsV-EszpUJJHgLQTyYIajxJ-kSgq4KHaQsnj%2BQGlLBmUlRDw0ZxhZC0CSKmCZshWAWHYJQHWXKTo8u6Xy3pArLGwrufC1Roy6kNPFFIMUHivA9xVSUth0LblcN7HY0ZzivCuJLMQEmZNxQTnBMoWBbdExmwtnkQltMAqqskSw3B-KbXAPViK2JjrKhuSIBK4g0BginjRbweAqlMmMHuNAM4K99JBI6cS%2BZVzrVlJjUosAqJqmjOwLQb5pNXGWpJQfbqyzBVRLtcKWWNEghnhgactt5asSqnlIyYgcI8iEmKRqIAA)

#### Code

```fsharp
/// Represents reasons why a text document is saved.
type TextDocumentSaveReason =
/// Manually triggered, e.g. by the user pressing save, by starting debugging,
/// or by an API call.
| Manual = 1

/// Automatic after a delay.
| AfterDelay = 2

/// When the editor lost focus.
| FocusOut = 3
```
            

#### Result

```fsharp
/// Represents reasons why a text document is saved.
type TextDocumentSaveReason =
    /// Manually triggered, e.g. by the user pressing save, by starting debugging,
    /// or by an API call.
    | Manual = 1
    /// Automatic after a delay.
    |

    AfterDelay = 2
    /// When the editor lost focus.
    |

    FocusOut = 3

```
            
#### Problem description

Found this while converting `Ionide.LanguageServerProtocol` to use Fantomas. The formatting errors cause compilation problems because there's no indent after the second and third pipes and their respective DU cases. The Newlines after the pipe are also not-ideal, but that's minor compared to the compilation issue.

#### Extra information

- [x] The formatted result breaks by code.
- [x] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-04-04T14:08:13Z - e784cd68954e7c6fac13ed723d108920d04c1ecc

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, this rings a bell and looks similar to  https://github.com/fsprojects/fantomas/issues/2155.
I have a script ready for another YouTube video to solve this one.
In short, you want to correct the range of `SynEnumCase` in case there is a bar and/or XML comment.
How annoying is this bug for you? If it is a blocker I can just solve it easily, otherwise, I'd like to wait a bit until I can make that recording. Speak your mind please, I'm ok with either outcome.

**Comment by baronfel** [comment]
No rush, it's not critical. A video is a great idea 😊
