### ISSUE TITLE
Idempotency problem when Elmish Html

### ISSUE THREAD

**Issue by dab-lmis** [fsprojects/fantomas#2195]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/v4?data=N4KABGBEDGD2AmBTSAuKAJALgWwDYDp4BLANzAG0AdAJ0oDsIIs9DSraHGAHa2L-aAAsiueNUR129RjLDi6SagFFimWNTABmAKxgAjNoAMYABQqia6gDUAhrgCuifABEbme9gDyigMqY39gDOYAAe%2BACysHT%2BAOaIfjbUmAnugQBMAJRg9lzwbog00owAuoWcEDx8%2BIGYAJ64iBRlsowARog1RNjYiADqiXT2dDGBAGaJ7aZhAIKtAO6IREJDcQwAPgB8YJ5cmERR%2BNg2XKajQ6FgALRbYZHRNnEJSRkZzSVvEKUcMuaWgfgAJQkigACrgbNBEOhYKJEBpoODAoEOvguODIYIYYotLoDIYysVIAAacBQZGYPbDQKoCikiCgFqQAAkdS4yDQkCI0WJdMYzJIdkcNPIvJkhhJLQgkAAkgoJMkiAAvZASyVpUVgYq8gC%2BqvpGuZrPZUC5mB5jKZAocxpFkv0etkkHCNhCABkuYhXRIYphBObJXpDIYNVqZLreQzHSzamyaZBgZ5Ru66PE6g1-TJ%2BYKbRqIGkHZmlApE8mVbmoLhRpAQzqHZHM9HYxzWrAYRm%2BZbs8Ly5oC3zZcikgAxLl2AByiDmuA97ZkmGojhrYbrBsbxsgLbbfaz1u7doALH2pT5ENgljCotNMEX4CWZ0ewONcMil4xwzJ6x2jXHN7hZ1BO13NBbUlbQH0gHwuAhRAACFEFGdREBBRIbB6TA4X-CB50XFpQzfFcLW-ZtWz-bdAKFYDywANnAyDoLghDxFdWAFmoaAbGRWUSFgdi9iiTCwGwxBXwgd9GE-KU1x-Ej-x3CjaTtAB2WioMhBjEIAVS4Nk2I4xAuJ4tx9joASnxfXDawjVciKgX9ZPInM7QADhU%2Bj4MQgBhRFAg8qIagXaBLFMuxzNkPDRIIqMbI3GSyKteSQJaABOVy1Pc8RwlPdpqGC59hIs5crMImN1zsuKu0ou1A1S2D0sQXzcH4h8zPysLLI-aySukrdV3ixyAz0GrplGdDqF87obAEoSRLAMT9WKptbNi3qKoUgN83LCDVNqxj4lPc9GpM5qQtamRwtmyKG2isqVqAtaWj0XtNroyFhtGk8zzgQ6poXU6Sna8TOsWmKeotPq9wDQ9NtlJBok8OgABVqFqXoLD9Y68pmuawAkgDruWsHVsS2QDCG3ghngZxEGnM9Rp%2BnC2sKjqFvXU17PByqAxozbnRCaVRgRwQJCUPKfExJJUfgX0BP3YMCvwoqoq6jk2fKu7iZkPRlJ5l1ZVGIgQh2OE3HUJQQh4DpAmMgSjCxy6v2Vk1uTVhLyz0FydZCIE4GoeBJelh9ZbtxWrsdzlndu12qpSz3vfUeAxw8bLE2ldDsGpB91XliKQ4d4HsHsXA9mnFMh3UI4KThBGupd-qWjScVNrj33wkL4uPTL6gK7p8DBmwbKAH1YFGAeLFPalg%2BZpXgdVyO69kNJBs96ZqGoGxak8ah3Rqf30fLBvJ8Blm41nwn1f3ja7SdF0V7Xjet6IGpE-7uEU7TjP98P%2Bbp-XAui5EDu5c3CjWrrGWuEN65PSvrfdem9t6YFbv-EuiBO7dwwuBIQKFApwgHnMIgUs-RfxxkDVmEcz5RzVFDK%2BvNbDWhglyYgwxd4CSonLRmCsp6hxnmQqMHN7oLzAp7IcQxArGXoQoLkMRmEPlYUQ3Ghow6n14UTfe3NqEumcLATAABxRA15zbiCRMZaR5ZbbZwurnSS%2BNQbKPPnaNI2tqFtwASmGCjVoAAGsYJr08XowI8MfCoXqjCDwR1ywtTkSQ7qpE54QIXh7K%2BE4pwejgpgBYEhQGICpvrOgFhjLTAUJlF%2B1AP52gieY7G8ipLERsQ2PhGtGBpBjlfAA0ogRAXB%2BaCwkLKQJPRSy5VCmdAG38uGkLNOAzmLRNCN3USEEWZ5AiCBMQeNhwymZHx-tE9mKi7SaCXlfHwkiGgrxiB4eUvRECtEiEgQZf1PgjOIcfGpMTyHzxkJoS%2BkpIDTGnDEOgwi6CiKiEc-5ARxAI1gDDeURkmrhJOpE55S1akdnqT2KB3zfmjToEZEgnoogxCKdlbJXI8l%2BTuYirZLydl2MlJoKh3zEF7FLK6VCrQ8heVgFbYYSTkEUoqfbKxYcbpvLiR8wRV9nCPxsK0BoCzH6CB8LUe4IR6b3M1I8qp1jXm2IodMtR3y2kdOhdEWU3ibBAr3mUhFArLF42FQTXV7zGCaEcd8txFqPGlkCCvWAFMJw1EQPAJlLjEBmwtkY8lD5pq2s4XnUqjq6m7LpQk91iR1LiClYEaA1AuijnQvADSuSohUwRChPiYTrWY1jZssZ2zJn8I%2Bc075fhc2BRuWWKtQz-phlJMUVUnJAhDitjSCJ2ogA)

#### Formatted code

```fsharp
Html.div
  [ Html.div[prop.children[renderEditor
                             35
                             150
                             (EditorValue.DatumOderStatus x.MontageStartStatus2)
                             update]

    prop.style
      [ bestimmeWarnungsfarbe (
          x.Abweichungen
          |> Option.map (fun x -> x.MontageStart)
        ) ]]
    Editors.RenderPlaceHolder classes.placeholder 35 150 ]

```
            

#### Reformatted code

```fsharp
Html.div
  [ Html.div[prop.children
               [ renderEditor 35 150 (EditorValue.DatumOderStatus x.MontageStartStatus2) update ]

               prop.style
               [ bestimmeWarnungsfarbe (
                   x.Abweichungen
                   |> Option.map (fun x -> x.MontageStart)
                 ) ]]
    Editors.RenderPlaceHolder classes.placeholder 35 150 ]

```
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result.

#### Extra information

- [x ] The formatted result breaks by code.
- [x] I or my company would be willing to help fix this.
- [ ] The formatted result gives compiler warnings.

#### Options

Fantomas 4.7.3

```fsharp
    { config with
                IndentSize = 2
                MaxLineLength = 100
                MaxRecordNumberOfItems = 2
                RecordMultilineFormatter = number_of_items
                MaxArrayOrListWidth = 20
                MaxArrayOrListNumberOfItems = 2
                MaxValueBindingWidth = 60
                MaxFunctionBindingWidth = 60
                DisableElmishSyntax = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.
This problem looks related to https://github.com/fsprojects/fantomas/issues/2158.
The idempotency problem doesn't appear when there is a space before `[`.
[Sample](https://fsprojects.github.io/fantomas-tools/#/fantomas/v4?data=N4KABGBEDGD2AmBTSAuKAJALgWwDYDp4BLANzAG0AdAJ0oDsIIs9DSKb7GwAHa2b-NAAWRXPGqIGVWgy6MJdJNQCixTLGpgAzAFYwARh0AGMAApVRddQBqAQ1wBXRPgAitzA%2BwB5JQGVM7g4AzmAAHvgAsrB0AQDmiP621JiJHkEATACUYA7c8O6IHLIQALpFXLz8%2BEGYAJ64iOwycowARog1RNjYiADqSXQOdLFBAGZJ7WbhAIKtAO6IRMJD8QwAPgB8YF7cmETR%2BNi23GajQ2FgALRb4VExtvGJyZmZ5Yxlze9vEBZWQfgAJUkSgACrhbNBEOhYGJEJpoOCgkEOvhuODIUIYUptHpDEYiiVIAAacBQZGYPbDIKoCikiCgFqQAAkdW4yDQkCIMWJdMYzJI9icNPIvK4RhJLQgkAAkopJCkiAAvZASyXpUVgEq8gC%2BqvpGuZrPZUC5mB5jKZAscxpFkoMerkkAitlCABkuYhXZJYpghObJfojEYNVquLreQzHSzamyaZBgV5Ru66Ak6g1-Vx%2BYKbRqIOkHZnlIpE8mVbmoLhRpAQzqHZHM9HYxzWrAYRm%2BZbs8Ly1oC3zZcjkgAxLn2AByiDmuA97a4mGoThrYbrBsbxsgLbbfaz1u7doALH2pb5ENgljDotNMEX4CWZ0ewONcMil4xw1x6x2jXHN7hZ1BO13NBbUlHQH0gXxuAhRAACFEFGDREBBJJbB6TA4X-CB50XFpQzfFcLW-ZtWz-bdAKFYDywANnAyDoLghCJFdWAFmoaBbGRWUSFgdi9miTCwGwxBXwgd9GE-KU1x-Ej-x3CjaTtAB2WioMhBjEIAVW4Nk2I4xAuJ49x9joASnxfXDawjVciKgX9ZPInM7QADhU%2Bj4MQgBhREgg86IagXaArFM%2BxzLkPDRIIqMbI3GSyKteSQJaABOVy1PciQIlPdpqGC59hIs5crMImN1zsuKu0ou1A1S2D0sQXzcH4h8zPysLLI-aySukrdV3ixyA30GrplGdDqF87pbAEoSRLAMT9WKptbNi3qKoUgN83LCDVNqxiElPc9GpM5qQtarhwtmyKG2isqVqAtaWn0XtNroyFhtGk8zzgQ6poXU73na8TOsWmKeotPq9wDQ9NtlJAYi8OgABVqFqXpLD9Y68pmuawAkgDruWsHVsSuRDCGvghngFxEGnM9Rp%2BnC2sKjqFvXU17PByqAxozbnVCaVRgRoRJGUPLfExZJUfgX0BP3YMCvwoqoq6jk2fKu7ia4fRlJ5l1ZVGIhQh2OF3A0ZRQl4DogmMgTjCxy6v2Vk1uTVhLy30FyddCIE4GoeBJelh9ZbtxWrsdzlndu12qpSz3vY0eAx08bLE2ldDsGpB91XliKQ4d4HsAcXA9mnFMhw0I4KThBGupd-qWnScVNrj32IkL4uPTL6gK7p8DBmwbKAH1YFGAfLFPalg%2BZpXgdVyO67kdJBs96ZqGoWxai8ah3Rqf30fLBvJ8Blm41nwn1f3ja7SdF0V7Xjet6IGpE-7uEU7TjP98P%2Bbp-XAui9EDu5d3CjWrrGWuEN65PSvrfdem9t6YFbv-EuiBO7dwwuBYQKFApwgHnMIgUs-RfxxkDVmEcz5RzVFDK%2BvM7DWhglyYgwxd4CSonLRmCsp6hxnmQqMHN7oLzAp7IcQxArGXoYoLksRmEPlYUQ3Ghow6n14UTfe3NqEuhcLATAABxRA15zYSCRMZaR5ZbbZwurnSS%2BNQbKPPnadI2tqFtwASmGCjVoAAGsYJr08XooI8NfCoXqjCTwR1ywtTkSQ7qpE54QIXh7K%2BE4pwejgpgBYkhQGICpvrOglhjLTEUJlF%2B1AP52gieY7G8ipLERsQ2PhGtGDpBjlfAA0ogRA3B%2BaC0kLKQJPRSy5VCmdAG38uGkLNOAzmLQtCN3UaEEWZ4ghCBMQeNhwymZHx-tE9mKi7RaCXlfXwkiGgr1iJ4eUvRECtCiEgQZf1SgjOIcfGpMTyHzy4FoS%2BkpIDTGnLEOgwi6CiOiEc-5gQJAI1gDDeURkmrhJOpE55S1akdnqT2KB3zfmjToEZEgnpoixCKdlbJXI8l%2BTuYirZLydl2MlFoKh3zEF7FLK6VCrR8heVgFbYYSTkEUoqfbKxYcbpvLiR8wRV8XCP1sK0BoCzH5CF8LUe4oR6b3M1I8qp1jXm2IodMtR3y2kdOhTEWU3jbBAr3mUhFArLF42FQTXV7zGBaEcd8txFqPGliCCvWAFMJw1EQPAJlLjEBmwtkY8lD5pq2s4XnUqjq6m7LpQk91SR1ISClUEaA1AuijnQvADSuTohUwRChPiYTrWY1jZssZ2zJn8I%2Bc075-hc2BRuWWKtQz-phlJCUVUnIghDitjSCJ2ogA)

Please note that `Html.div[prop.children...` is considered indexer syntax now.
So, fixing the issue above might not lead to what you are after.
Is there any reason you went with `DisableElmishSyntax  = true` and not [SingleArgumentWebMode = true](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_single_argument_web_mode)

**Comment by dab-lmis** [comment]
Hi Florian,

thank you for the answer. SingleArgumentWebMode = true<https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_single_argument_web_mode> is in deed what I want. I just didn’t know it exists.

Thanks
Daniel

Von: Florian Verdonck ***@***.***>
Gesendet: Donnerstag, 7. April 2022 15:01
An: fsprojects/fantomas ***@***.***>
Cc: Daniel Berkenheide ***@***.***>; Author ***@***.***>
Betreff: Re: [fsprojects/fantomas] Idempotency problem when Elmish Html (Issue #2195)


Hello, thank you for reporting this issue.
This problem looks related to #2158<https://github.com/fsprojects/fantomas/issues/2158>.
The idempotency problem doesn't appear when there is a space before [.
Sample<https://fsprojects.github.io/fantomas-tools/#/fantomas/v4?data=N4KABGBEDGD2AmBTSAuKAJALgWwDYDp4BLANzAG0AdAJ0oDsIIs9DSKb7GwAHa2b-NAAWRXPGqIGVWgy6MJdJNQCixTLGpgAzAFYwARh0AGMAApVRddQBqAQ1wBXRPgAitzA%2BwB5JQGVM7g4AzmAAHvgAsrB0AQDmiP621JiJHkEATACUYA7c8O6IHLIQALpFXLz8%2BEGYAJ64iOwycowARog1RNjYiADqSXQOdLFBAGZJ7WbhAIKtAO6IRMJD8QwAPgB8YF7cmETR%2BNi23GajQ2FgALRb4VExtvGJyZmZ5Yxlze9vEBZWQfgAJUkSgACrhbNBEOhYGJEJpoOCgkEOvhuODIUIYUptHpDEYiiVIAAacBQZGYPbDIKoCikiCgFqQAAkdW4yDQkCIMWJdMYzJI9icNPIvK4RhJLQgkAAkopJCkiAAvZASyXpUVgEq8gC%2BqvpGuZrPZUC5mB5jKZAscxpFkoMerkkAitlCABkuYhXZJYpghObJfojEYNVquLreQzHSzamyaZBgV5Ru66Ak6g1-Vx%2BYKbRqIOkHZnlIpE8mVbmoLhRpAQzqHZHM9HYxzWrAYRm%2BZbs8Ly1oC3zZcjkgAxLn2AByiDmuA97a4mGoThrYbrBsbxsgLbbfaz1u7doALH2pb5ENgljDotNMEX4CWZ0ewONcMil4xw1x6x2jXHN7hZ1BO13NBbUlHQH0gXxuAhRAACFEFGDREBBJJbB6TA4X-CB50XFpQzfFcLW-ZtWz-bdAKFYDywANnAyDoLghCJFdWAFmoaBbGRWUSFgdi9miTCwGwxBXwgd9GE-KU1x-Ej-x3CjaTtAB2WioMhBjEIAVW4Nk2I4xAuJ49x9joASnxfXDawjVciKgX9ZPInM7QADhU%2Bj4MQgBhREgg86IagXaArFM%2BxzLkPDRIIqMbI3GSyKteSQJaABOVy1PciQIlPdpqGC59hIs5crMImN1zsuKu0ou1A1S2D0sQXzcH4h8zPysLLI-aySukrdV3ixyA30GrplGdDqF87pbAEoSRLAMT9WKptbNi3qKoUgN83LCDVNqxiElPc9GpM5qQtarhwtmyKG2isqVqAtaWn0XtNroyFhtGk8zzgQ6poXU73na8TOsWmKeotPq9wDQ9NtlJAYi8OgABVqFqXpLD9Y68pmuawAkgDruWsHVsSuRDCGvghngFxEGnM9Rp%2BnC2sKjqFvXU17PByqAxozbnVCaVRgRoRJGUPLfExZJUfgX0BP3YMCvwoqoq6jk2fKu7ia4fRlJ5l1ZVGIhQh2OF3A0ZRQl4DogmMgTjCxy6v2Vk1uTVhLy30FyddCIE4GoeBJelh9ZbtxWrsdzlndu12qpSz3vY0eAx08bLE2ldDsGpB91XliKQ4d4HsAcXA9mnFMhw0I4KThBGupd-qWnScVNrj32IkL4uPTL6gK7p8DBmwbKAH1YFGAfLFPalg%2BZpXgdVyO67kdJBs96ZqGoWxai8ah3Rqf30fLBvJ8Blm41nwn1f3ja7SdF0V7Xjet6IGpE-7uEU7TjP98P%2Bbp-XAui9EDu5d3CjWrrGWuEN65PSvrfdem9t6YFbv-EuiBO7dwwuBYQKFApwgHnMIgUs-RfxxkDVmEcz5RzVFDK%2BvM7DWhglyYgwxd4CSonLRmCsp6hxnmQqMHN7oLzAp7IcQxArGXoYoLksRmEPlYUQ3Ghow6n14UTfe3NqEuhcLATAABxRA15zYSCRMZaR5ZbbZwurnSS%2BNQbKPPnadI2tqFtwASmGCjVoAAGsYJr08XooI8NfCoXqjCTwR1ywtTkSQ7qpE54QIXh7K%2BE4pwejgpgBYkhQGICpvrOglhjLTEUJlF%2B1AP52gieY7G8ipLERsQ2PhGtGDpBjlfAA0ogRA3B%2BaC0kLKQJPRSy5VCmdAG38uGkLNOAzmLQtCN3UaEEWZ4ghCBMQeNhwymZHx-tE9mKi7RaCXlfXwkiGgr1iJ4eUvRECtCiEgQZf1SgjOIcfGpMTyHzy4FoS%2BkpIDTGnLEOgwi6CiOiEc-5gQJAI1gDD>

Please note that Html.div[prop.children... is considered indexer syntax now.
So, fixing the issue above might not lead to what you are after.
Is there any reason you went with DisableElmishSyntax = true and not SingleArgumentWebMode = true<https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_single_argument_web_mode>

**Comment by nojaf** [comment]
Hi Daniel, 

Happy to help. If you have any more questions you can always find some help on our [Discord server](https://discord.gg/D5QXvQrBVa).
I'll leave this issue open as it is indeed a problem.

**Comment by nojaf** [comment]
Fixed by https://github.com/fsprojects/fantomas/pull/2446
