### ISSUE TITLE
Formatting introduces error when using type provider and verbatim string

### ISSUE THREAD

**Issue by greenbutton** [fsprojects/fantomas#22]
Consider the following code fragment (using FSharpx.TypeProviders):

```
open FSharpx.TypeProviders.Regex
type IntegerRegex = FSharpx.Regex< @"(?<value>\d+)" >
```

Formatting removes the spaces from the second line, resulting in:

```
type IntegerRegex = FSharpx.Regex<@"(?<value>\d+)">
```

which gives the error "Unexpected quotation operator '<@' in type definition".  The space before the @ should be preserved.

**Comment by grishace** [comment]
Could you please check it works with TPs from FSharp.Configuration?

``` fsharp
open FSharp.Configuration
type Config = YamlConfig< @".\config.yaml">
```

in my case fantomas removes the space between < and @, leaving the code in broken state (I think F# compiler is looking for closing code quotation tag).
