### ISSUE TITLE
Idempotency problem when formatting quotations

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/fantomas#2203]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBDaWAlrAHZgC8AOmRGADwAC1tLYmOAtgM4DmFYAUgAWWLAAcASogCOAV0RcsAWQVdcPRAHVCWIQAVcAT3Sxc8ZqwgTZJIh0QAJROjGIATlwB0AM0Lp0TmbuXGDcfMKIZlwWlrhchiTQYMAxlrTsAIRgbgpipFyI-AAUArqEXACUng6iYgDC6ISItp4Ays3wAILxiUVhFWAAPgB8YN0J0J6dAO64OgAqcQDWqWnZ2LJuZDlceSQFngCi%2B5uIrbLQ0KqtWLhYslx1CIhFVU%2B2zVirtAC%2BqQzDSAAGnAUAKokIJB4XFQYAA2qCIKBLJAACRYQyuWGQSFYYGI2hogBuuHQ8lhCLWAAYQWtIABJEhIWytQgAL2QtLSABYCRAALoEn5cpF8qDozHINA42z4lGoklkqXwsUQACMItYkCUuAAHgAZSGIfXNHi6OVpNUAJipYsFLGFBORWolWOlHQA8t5DSQzhjMBaWMTSeS0JS0lbNUHjvAvT7OaqMN5IHahZrnUHXcrIAAjWCwdCBwkKkPK8OWADMUcJjIKbiwADFIaSAHKIaaNX1FlhYNzyVMO9NitEYt1QPMF7vixWhlVrbnViCQdocQhwEwkTpYGNxo1TiDeUkFAe-Ify0fZieF6vBpUUxMAVkXUFaYnwiAAQohvLAcgY3Lg9hYO4%2B5gL2-aWPap5OsOWbYleU63rO5asAAbM%2By5vlcX4-jk%2BqwNM7jQHEiCMkSsDEUQpCgeBiAnhAjosBmxYXvB%2BbXrBM5lomADsGGvu%2BOG-ogACqYiuG4xEFGRFF3MQJCgYe6DHpBaYweekpsZON4lneYaJgAHPxWGft%2BwkNHEjz5OBBC-opR50apg7qS6rHSghOlcfeawAJzGYJZk5CoHA5iBz5KSprBQQxZ6uZp7nsYhunIYmao0ommEBbhiBPBu9nKY5UVqUxsFueOiWeaW3mWhqGUCVcnTeMBbhPBwHC4DRfaFSw0VgIxtDMUucEJdpnFVfpazWv52GBWciCruu1HhQ59F9bFmZlbmFVjXpc6WlWdUmY1zUrmuBZLYmtGrf1ooaWOW2jfKXkTZaC4ZYyzJYB6JDzG4hjaOay0Fdd60sfF5WPS6z17ZYapPod76dG4sA2PAAAiziEKuzWdRBRXOSVd3ZriSXQyhLBquhGU6rq9LePMQjNIcBWtEIv5YNo8CA4m3K2k50GE3F90k5Vu3k7Qap8dTeqMr4uoehJdy-ocupiDsXDyaBD58-jAsDaV4MyniospZNRnS7qUhwG48Cc9z846z1xX60T2IiztpuWn5FtW7%2B8AtrIIXuF69LAdwoFqiDLkbYbHCyOgRCdogDa-u1ojuPMmkm9xaw2hhvs20o8eJ0aKduGnOMYdAQi4ABBDuAA%2BtMhBc0IKb8zF0dg8LsrZ9VlhWrVdI00jAGGB6biGoodtt8%2BvNR4LMc98bHs5xGkYW6PRgT1PWAB0Hbgh2HMLPpHHdrV3Q2bXHCd%2BKXqd3M1mdYn3L0DwddJb%2BPk-lMoxd376MuFcwoZWrrXfAzUm4t3NAvF2Qtia91Xv3VgVo3rDz1AANVLB%2BSE8BIQ8BnqBAyjtaC9RuskA2y9SbjRhig%2BG6DdQNhsAQeSOCmT4MIXPEhApna3XgW7RBT0aHiwgFaKmDC0awCwAAcWwCrNWqh5KcMfNwsAZDQZX0Nh5JBb8UFS2Hv-JOH4TDQCWB%2BOuSxsBcG%2Bq0QCOUCyBwUkDSKTsCZwKXpebaQixaJitObOkbYOxGi-FgQizRn6IAxr4EgOh5KdCZMFUKHh8ouNIbwihrsRocW8Z7Ae3s6QAGlECIDEHTBmzRGS2PsPGFJ3U0luL4R4gRK8clr0rOlBhzNVxcCEMoh2sDGnd08ZDTMZNEwViHmkZc%2BDMBIx4IHT4mhEA5iUM8WpAyMn8KydQnxawKwb0-o0HgJAmGJCoiQVkxy7inHmLAD6nw5IXTWBFOpPCGmbKads1%2BtCWAVg-lMzoCd3AkDkkSY0pAeCJPcFEyEsT8jrPPuQwa4pNraNacg35aCplF1vvGfUgEczwFwA0WAGsoSBKTgi3WndF5DK0tkqGwjxn0KmWjcouAcyYC6eUIQrQEi3F1FS1xetBmaPumixluy0gVnEVMopJT7m2EZOY3AiRZ6JheRs5FI4tFeMlbk1gFZ9FTOMaqpY8YuBIxRkyNsihEDwBxSXX08j1byRPpdLqWrKHDIZaMplez-EmtrkJHIbKuDQDcFjZswF4AiRiaQDG0B0DgPOUK%2BpIqPl0q%2BTon5tAKz5KmRIdQILkZLDTW8jN2rhoQ19cWMZDt%2BK9jXMoNZzjXlqKFKCfkXIcRcAbBrWEmqfhAA)

#### Original code

```fsharp
let action =
    <@
        let msg = %httpRequestMessageWithPayload
        RuntimeHelpers.fillHeaders msg %heads
        async {
            let! response = (%this).HttpClient.SendAsync(msg) |> Async.AwaitTask
            return response.EnsureSuccessStatusCode().Content
        }
    @>
```

#### Formatted code

```fsharp
let action =
    <@ let msg = %httpRequestMessageWithPayload
    RuntimeHelpers.fillHeaders msg %heads

    async {
        let! response =
            (%this).HttpClient.SendAsync(msg)
            |> Async.AwaitTask

        return response.EnsureSuccessStatusCode().Content
    } @>

```
            

#### Reformatted code

```fsharp
let action =
    <@ let msg = %httpRequestMessageWithPayload

       RuntimeHelpers.fillHeaders
           msg
           %heads

           async {
           let! response =
               (%this).HttpClient.SendAsync(msg)
               |> Async.AwaitTask

           return response.EnsureSuccessStatusCode().Content
       } @>

```
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result.

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-04-12T06:26:27Z - 7b35c8912c8a039bc443705019c7f15f5e6614c1

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this!

I believe we currently, don't have a good way of dealing with multiline quotation expressions.
We should extend

https://github.com/fsprojects/fantomas/blob/04d176a519106751750e29e5754075eb475e827c/src/Fantomas/CodePrinter.fs#L1356-L1361

to something like:

```fsharp
    let e = expressionFitsOnRestOfLine (genExpr astContext e2) (indent +> sepNln +> genExpr astContext e2 +> unindent +> sepNln)
    ifElse isRaw (!- "<@@" +> sepSpace +> e => sepSpace +> !- " @@>") (!- "<@" +> sepSpace +> e +> sepSpace +>  !- "@>")
```

(Didn't test this code)

This will slightly change the outcome of https://github.com/fsprojects/fantomas/issues/2154
But as I reported this one myself, it should be fine to change it.

Are you interested in submitting a PR for this one?

**Comment by sergey-tihon** [comment]
> Are you interested in submitting a PR for this one?

Sorry, no, at least not now.

This bug is not critical at all, I just tried Fantomas on TypeProvider project and discovered this issues.
It may leave for a while in Open state if it is not critical for others
