### ISSUE TITLE
[Feature request] Preserve file EOL (Unix or Windows)

### ISSUE THREAD

**Issue by rdeneau** [fsprojects/fantomas#2204]
I propose we add a way to tell Fantomas to preserve the character used for EOL (end-of-line) for each file to format, at least when it's not specified in the `.editorconfig` file, instead of taking the machine setting (CRLF on Windows, LF on Linux...). This can have a smoother integration with `auto.crlf` git config.

So, the rules to determine the EOL character would be:
1. Lookup `.editorconfig` file for [`end_of_line` setting](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#end_of_line) for the given file type
2. Lookup "elsewhere" for the "preserve file EOL" setting
3. Take the machine (`Environment.NewLine`)

Example of issues with different `auto.crlf` git config on Windows machines:
- `auto.crlf=true` → EOL for Fantomas need to be either `end_of_line = crlf` or left undefined. Otherwise, `dotnet fantomas --recurse .` will change all files (to fix EOL from CrLf to Lf).
- `auto.crlf=input` → EOL for Fantomas need to be `end_of_line = lf`

---

Please tick this by placing a cross in the box:
* [x] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [ ] This is not a breaking change to Fantomas
* [x] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Hello, I believe you are looking for https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#end_of_line.

**Comment by nojaf** [comment]
So, Fantomas today does what you describe except for `Lookup "elsewhere" for the "preserve file EOL" setting`.
I don't think Fantomas should be bothered with respecting any version control system.
Especially when there is a way to control the line ending via `.editorconfig`.
You could always check out `*.fs` files as `lf` using a `.gitattributes` file and repeat that setting in your `.editorconfig`.

```
*.fs text eol=lf
```

**Comment by rdeneau** [comment]
In its core, this feature request is not about git or other version control system. It's more about Fantomas "philosophy". IDEs / code editors respects the EOL of the file being edited. Fantomas can do the same or be more stricter.

But when there's no settings telling Fantomas how to be more stricter, here regarding the expected EOL, I don't think that it's a good idea to always force to have the machine EOL. The feature I request is about opting out this behavior.

**Comment by nojaf** [comment]
Could you give some more examples of "elsewhere"? I still can't see beyond the question to support git's `auto.crlf` setting.

**Comment by rdeneau** [comment]
It could be in `.editorconfig` file. I don't think we can use `end_of_line = preserve`, so something like `fsharp_preserve_file_eol = true`, with a priority lower than `end_of_line` if both are defined for `[*.{fs,fsx}]`.

**Comment by nojaf** [comment]
There is no interest to pursue this.
