### ISSUE TITLE
Parentheses are lost in SynMeasure

### ISSUE THREAD

**Issue by sonicbhoc** [fsprojects/fantomas#2207]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBtAPAWUQQwGcBXAJ0QD4BdMAFwE8AHRMAmvAM3YB0SuA7LLkKkK1ekzAB3RIgDWBHv0H5iZKrUbMAFr159FfccwAqiVmAC8BiBGAB1WCVkAJWKQIAFRCTszZaIgBLQ0wdMAB6MAAKVg52KT8CAEpyAF9rG1iaQOgwAFtEPIAjbzBoMjwaZis9GzB7Rxc3Ek9vXzlLMAAWAAYiUJJwmLZOBLlktMgAGnAoAkQabL4AcwJUMHRZ2y2bSAASI3XIYJppnYh9gDc8ABsiZDRNurqemefdgEk%2BJEMAZUCAF7IN7vbrnMCUHapEHbd77Q5oY6GM5wvbXO4PDbgiAARhhz0g2DwAA8ADLBRCkxArGhaFGgnEAJh64MhdWhO1AqIRUGp8AA8uxyXxEL96DdgeCrrd7usnqDGfi6pAAKLfQXCyWgqA3diQVlQ-FcgkHTRHIqwWA3enKtEyzHy94AZiVnz48xINAAYsFbgA5RCSG4Um3PGgke4G9lGqWmpjmy3W13SjFy7HdV0XX6FHJW2B8ACCNDVAqFIczYHYt3mUZsHLqxttPMgFqtoYudtTj3TAFYK5Bfgw8NBEAAhRDsRyIDx4Eh4ApVEjtmzhyPvNl1mPcs2I1tJ2Po2Xd7UANn7g%2BHY4nU9JsGkJGghEQX0usEf2Xzy4gq8QtYg9ZsRtdjjTEW0TZcUyPLFtQAdnPIcR3HScyAAVQYJgHyfF830qQJPwrKsbhrddDU5WNmz3CDOygx1ngADngy8kKnABhG5CAIFj81YCNoBoRwv0ratfxI6MyO3eNd3A5NqIddMAE5GMQ68yFwYpvEEwjiOeDd-y3E0KOkg97TTbUcVedMBwQq9kMQLibnw9MtJEnTSIbcidygSiZMPOSzLxSyLxHAt2EXLi8jyPBBJ-P8wAA2EDM8sC2x8kzjwZRVAus5iyGzPJcwcvhNOE2L4vqDzJK8ozUV80yGRdLLLxCxc8oKxztRi0TN3ExLKuS-carS6CGS6fsvh%2BGh%2BT4YwSDoOxAlpYqiJcupdLi-SmyS7zjK7Yb3hxPtGuCkg3G%2BAARRBg3yxdoojFabDWsqgI7ZsTio2r0v2s9LKJYkPnYYwtGpFVlt%2BLRHBoeb4EWitelKjbgNe5FUt22i6hxOCfpJL52ECYl%2BQwypHBVYkGDIAgCDwoqKx7Fkur0nrNr6t6UZo9McQYrHiQAJUQOASHgKGYfTOH6fWxnEaSlmdrZszFK53n%2BfgP0iHUkhBQ%2BKo8jWCscXhiWXqSvIiBubJgxFL1HEixZvGMM1Wb8hULO1SBFcceBsBNs2KUtkhrZu-toC0Wdh0XAB9SRAmhul9fciTQOlwbUfTRkApd36CxIOc6H5EhyVYIW6VhunXLEuPeoT5GZcd95GUy9OSUz7Pc-zmgVbVjWtZ19nY8AirQON03AnNxBff9237erura4al2m7wHO88CVhPaHkex8qAPLKDkO%2BO8COo8W3uEqZyvTgd6fnkZUauYANXtUdgngYJlkLwS6JL1a3L7%2BOjkTk0Pp7SvodBuxIvRED4HxKmj9vgvzfsXY%2B5Vf6In-raQBaMbCMm%2BqAs6sAaAAHEFgkzJmYSm%2BZ4G9k-g9b%2BJ9JZ9W2knWWCpMbpy9sPCko4HLQFkKOOc3CFgECmr8ecdkrSq2pk5EqYsnr9wTClKen0r6cxdgGIMHCFjSGpHbJgF1cZ8AWlTAs3w1IlBaEtbSX8y4-wrnIgaAChoYIgIyeWLsADSMgGD-UBtSL4wiCianMfdCAj0EaG2ZlXRhNdnhOmdqCQkJIQb5QIFoCh2pRal26uXU%2Btj3oOPTE6NOcT-grAlJnZYqtqSQ0QEUbACAtSgmcog56UAQI5IvoouoTp65xILMGZYfBwGQI-Hwf4-TKgiGMLAcalTcLtQaVIjJDMsl0NAgw%2BxydtROlnj0023g%2BC4UuJSfMywTHeF0cEAx3FAlNNkVJeRkTL6dJvqwoempSTziKPAPAbFYCUxWKoke1zpGhJaYZe56ymHOhAXEs6y88BFAlIk5eWhfh0EMCSIFizxbLLCas6qEKomdOwXE9xiBPHfEqV8XheBIFF0kctG5yCqrgrQXkzZLC4mcJpbITUBBM6nWVmYKoHs2Ej2IeTMh7pbprixTIpl-VckbNBE6ZRnLZw5UQLCgg5RAj5X2cKlC%2Bj8wXWgOxOcwzMWWMydY7Jdy7GsqVc6FxcTuZ4DGSdWQlrqFWNobitpCigF1F6OecMOQaC1KQF64JUJZiUBBMcAgXpKbrEaakIAA)

#### Code

```fsharp
[<Measure>] type staff
[<Measure>] type weeks
[<Measure>] type hr

type Test =
    {WorkHoursPerWeek: uint<hr / (staff weeks)>}
    static member create =
    {WorkHoursPerWeek = 40u<hr / (staff weeks)>}
```
            

#### Result

```fsharp
[<Measure>]
type staff

[<Measure>]
type weeks

[<Measure>]
type hr

type Test =
    { WorkHoursPerWeek: uint<hr / (staff weeks)> }
    static member create = { WorkHoursPerWeek = 40u<hr/staff weeks> }

```
            
#### Problem description

The definition of and value using my units of measure are formatted differently.  In the definition, there is a space between the `/`; in the value there is not. That is odd; however, the real issue appears when the parentheses are also removed. Removing the parentheses gives the following compiler warning:

`FS0632: Implicit product of measures following /`

Since I compile with warnings as errors, this breaks my build.

I see no formatting options dealing with units of measure at all. I would be delighted if they were added, as I plan on using this feature extensively.

#### Extra information

- [x] The formatted result breaks my code.
- [x] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-04-20T07:11:49Z - 21e17ab534e806edc157adf705676a54f9f79534

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by sonicbhoc** [comment]
I didn't check the box for "I or my company would be willing to help fix this" as I would need permission from my supervisor to do so (and the project I'm working on is already pretty late); if nobody else can do it, maybe sometime down the line I might be able to tackle it.

**Comment by nojaf** [comment]
Hello, thank you for raising this issue.
At first glance, we seem to be missing the information of the parentheses in [SynMeasure](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-synmeasure.html).
Meaning that this problem is best to be fixed at the parser level in `dotnet/fsharp`.

https://github.com/dotnet/fsharp/blob/68acaea8dccd80d9239dfb778fc2e0c9bb0a4fe4/src/fsharp/pars.fsy#L5505-L5513

**Comment by sonicbhoc** [comment]
How should I word the issue in `dotnet/fsharp`? Also, ideally it would reference this issue in the bug report as well, right?

**Comment by nojaf** [comment]
I can create it for you, might be a tad easier.

**Comment by sonicbhoc** [comment]
Thank you. I have no idea what the AST section of that report even means or what the syntax is, so asking you to write it up was definitely a better choice.

**Comment by sonicbhoc** [comment]
Also, what of the difference in spreading in the formatted version? The definition has spaces between the / and the value does not.

**Comment by nojaf** [comment]
That would be a question for the style guide over at [fsharp/fslang-design](https://github.com/fsharp/fslang-design#style-guide).
Whether there should be a space or not should be mentioned in the https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting and then Fantomas can respect the outcome.
As there is no clear mention of this, it should be there first before anything can change here.

**Comment by sonicbhoc** [comment]
@nojaf What should be done with this task now?
