### ISSUE TITLE
Long line with || operator being split when formatted leads to warnings

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#2210]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosACgE4CW6JALiQG6IDOYAvADoB2EEFAngA74DKACywV4sAO6t%2B0UjwoEsAIwDSiLkzA9S1AIYV8wNh2NghIsZOmyKaKyTlGOAXzDjKgxybB0KektDB0RHRFRCIwABUiLgAxIlh0OzkwAAo6GXt5JVUuWwy5AEpPLxLSspK0ACV6XAoAHjNRCSl8rJU1ABpvClJWAHMAPiZi0rwKMBI6ADUdHBJ4GJJWWaS2nOH2cpMUgh0uCNgFRQBrNQAJHTpBCOCeHD1EADoASVYfHVZoJ4BhQURoY6rI45NKtYFqApFTZbDgAH1hqV2%2B1gAHVKOCuBcrjd0HcHi83r5Pj8-gCgdk1KDrBjISMtvDEXsDmiKKssddbvd9AT3sTHr9-oCwRSuFTMjSoTCUgVIB1wFA6IgKFR%2BnRUGAANryiCgLyQAAk3D46sgSwosu1HANuhwWGQaC1pQADHLSpBXkhWKySAAvZCukoAFktEAAupanAGdSGoIbePaoGaLXr9Ta7erHSUAIxRkyQACyOgAHgAZJaIEuIfoUQTJkoADidMfDxkjlt1ebjxrQkCr8AA8gAzMusRD8bh4OvGa2zdMOmMQABMuenAFFWAPh%2BWp3mcIPIM2I7mO9OuwnIIpYLAcDuIDPbQnM14AMwrq2vRVECiLZY4AByiDiHMo63hwPR2oerbHjGBpGuel7XqB95zpqC5gIGb53vwwT%2BNesCsAAghQ66biO-poYOsyKpBzjQSmcEmghN5vshj5oQArJhUD8DwOhfAAQogg6wEQiC7EQOhBPoRCgZwRAQV4La0e2MFnoxV7MapaZsaUABsXGQDxfGIIJwmiSWEhhNAlyIK81CwNZVD4bJYDgYgNEQG2xgnlaak9kxSGprOOklAA7AZRkCUJImIAAqjwfBENZip2Q5fjOVxlE4NRilHip9HxupiEsUFD4Zmh9YRbxUVmYg3z3HQdDfPhPjydAFAiS5WU5SYSmeXRnYMf5GmBdp5WlAAnFVxmmTF%2BbBKEMmZVR7m5VB%2BWDYVw3FVpwXjdmLpoYZ1UmdFonNTgGUUStHlgF5HA%2BXeflQAFJVjfOpRZjmR2RYgBGDtJzXoOgOguW5t33dGBXdi9I1vXtH3ZsuP0nbNonYeQcCXawXU3WtyneapQ2wztKbvahn2vijxn-dJGO4djYPyatvV5YT0PwXDu1lYjXhZhhR0elWFD9qwURcCytbLdlLPGH1d0DaexMXlzZMIxT2acdTXwEfEWAbgAIogczkNJTMKaz63s5tMOml6o3q0%2BJhZvpR2FkWzyDhEfysKuMtCCJFBovANYuYGTb4-1G1K1tib2-DPMa3z4Vu8WryDiQRb9olegiauRZaPQdAkFdpTsRHlsEw9ROx3b5oJyhTvGFmlWp0W1RwEQ8DB6HXHhxDiu%2BcrSYNyFfNTW3HcifAf5YCEYRDs8%2BjoGqXFZgP0dD7X6C1CQwGIDEIkg8qYQRIVo-7V4i6HW6U9d-mu-74fRDH2bBnQIIOgSe1YQAPpuCHWsG9rYx1tiPbmjc0KLm%2Bm6d2usJJcH7EQMsPge5SzQv3SOCtN5PWHvHCBY8TCLmRrA4s8C9hIJQRQWe88iCL2XqvNC68sGQzAI9WMysd44CoE-I%2BehpJn2NBfXmRCqZunIYg5BkwKAP24Xvcsz9X5hBcjAT%2B39pL-3mKHYB1cOYmnAWrROTcOCLgFqQosMwHz8SWPAJYfQ0EuUbDoqGNtzwGM7OTYxS4tbmJiPrdqJdWDWI3HYhxfcK5yzZro1x%2Bj8GGMgaURcrtzEG1gBQAA4kqfOhdGqBLCRxCJHB5asPYbBWur0CGXyISnWBj9yz8UugCfi39TgUDoKLfgkk6rXjnjjaWPVIlW2iaAzmpMPGOyga3N0AEgL1KVOIRAVZBGICNhnVglBAkEQ3PNWhjDSjdVlkUqJLiRlFU0vEwhxhFwTzdKoRAPBPbeyrK8TpQQyK4xls4thNcwFxPGUYtCz4b4lALMWP25Arj5NKJgyuUcQFb1thUi5VTjDPhgSC-gdi8C6z6HPYWKJECKHzAgci%2By8awuwfC3B5TVb-ISSUZ8JCQUETmH0VgfjPhOSkCQNlegsCiQOELL06U%2BnXU%2BSwwe1LEW0tPJ4wFYjmXcLCMsKgtALL9B2YtVZSwNktQ%2BQMo5QyTkItGecullyODPjMSC2RVAyIlkkooeAOh6qwGLv0GZ%2B99WHLDMc75ejtpmtlRM0oz4fEgoNpMHQig8DgsmIIfgXBhVFm9V80pz0VZjODQC0NySQV3IeRuYWrxmkfA-qmiVOCOE0qzb5OVoaakgoaR8Y4ZE6C61gPrGe9B9DwFtfI0c2TRK5L1VxcGlaqXVulbWp69aGVTKbV-NGKzJgZHICqxA8BYrrPwkbaA9wJJcorRSkpPzTUOxzQym5ILKg6F5fEY4x7BlV2NVK89wik4mHDhFHo-gZEkqfYa5w8pQwBlNHQGIxd1QHJAE4IAA)

#### Code

```fsharp
module Primitives =
    type ShutdownScriptPubKey = private {
        ShutdownScript: Script
    } with
        static member TryFromScript (scriptPubKey: Script)
                                        : Result<ShutdownScriptPubKey, string> =
            let isValidFinalScriptPubKey =
                (PayToPubkeyHashTemplate.Instance.CheckScriptPubKey(scriptPubKey))
                || (PayToWitPubKeyHashTemplate.Instance.CheckScriptPubKey(scriptPubKey))
                || (PayToWitScriptHashTemplate.Instance.CheckScriptPubKey(scriptPubKey))
            ()
```
            

#### Result

```fsharp
module Primitives =
    type ShutdownScriptPubKey =
        private
            { ShutdownScript: Script }
        static member TryFromScript
            (scriptPubKey: Script)
            : Result<ShutdownScriptPubKey, string> =
            let isValidFinalScriptPubKey =
                (PayToPubkeyHashTemplate.Instance.CheckScriptPubKey(
                    scriptPubKey
                ))
                || (PayToWitPubKeyHashTemplate.Instance.CheckScriptPubKey(
                    scriptPubKey
                ))
                || (PayToWitScriptHashTemplate.Instance.CheckScriptPubKey(
                    scriptPubKey
                ))

            ()

```
            
#### Problem description

After formatting, indentation warnings appear.

#### Extra information

- [ ] The formatted result breaks my code.
- [x] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-04-25T16:08:33Z - 2d32fac87ac73ff0c9b76386f5ac5ed695748986

```fsharp
    { config with
                MaxLineLength = 80 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, I don't see any warnings in [the online tool](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQC27ArjbDAAFAE6IuiAC6IAbujABeADrIIESQE8ADoIDKAC16TorAO7JdzMVslDeAIwDSsDYpVqPYLWJlVJsd08g4DADIxNzS2tJbCjEGzAAX0CgtEk-RGYwLlgue1gRMAAVEQ1iEVYuOJsUoLUACjQreNsHZw1Y5psASlq6sGwAJXR%2BSQAeMOMzCy7WpxdcMDSxZABzAD43VX61AUkwIgA1WkRoYhRaarn2rZ26%2BqEqDSLWO3sAaxcACSo0fSLcloaH5YAA6ACSyDSVGQzDBAGF9LBmO8rm92vU%2BndPE1ouiXFi7t1ettsWoAD7ksAPJ4vADqUnxGh%2BfwBXCBIIhUPSsIRSJRaLaLkxpLJONmTMJO2JUv6lOpj2erAZkiuLP%2BgOB-i50N5oMRyNREqFGhFYrquJaktFZJlyFlDRJkBAiSAA) for the result.
Are you using F# 6? I believe this is no longer a problem due [to the relaxation](https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1108-undentation-frenzy.md).

**Comment by knocte** [comment]
That's true, I just tested with F# 6.0 and there were no warnings.

Can we contribute a fix that would, for example, only happen when a flag is passed, like `--legacy-lang`? (Being only a flag means it would not pollute the settings/docs.)

**Comment by nojaf** [comment]
I have no interest in maintaining any legacy constructs, regardless of setting or flag.
