### ISSUE TITLE
Use F# compiler from the source files

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2217]
As mentioned in https://github.com/fsprojects/fantomas/issues/2160, we would no longer use the FCS version on Nuget of the compiler. Instead, we would grab the files we require from source and build our own little FCS layer that only exposes the F# parser.

## Pros
- We can fix parser bugs at [dotnet/fsharp](https://github.com/dotnet/fsharp) and do not need to wait for an official FCS release.
- The dependency footprint would be a lot less as we don't bring in all the dependencies that FCS has.
- Performance would increase
- More problems will be solved at the root instead of introducing hacks in Fantomas.

## Cons
- We are no longer using the standard FCS like the rest of the ecosystem.

**Comment by baronfel** [comment]
One open question that we would need to solve would be the integration story with editors. For editors that host fantomas out-of-process, like FSAC, there's no problems.

For VS/Rider, though, there are hurdles:
* VS - currently supported via out-of-proc VS extension, so also fine. If the F# team/community move towards pushing fantomas down into the FCS layer over time, that would also solve the issue.
* Rider - currently does their own periodic integration, but they _also_ do their own build of FCS and so might be amenable to such a move.

**Comment by nojaf** [comment]
For VS/Ionide nothing really would change there.
I believe the impact for Rider will also be minimal. They are also formatting out of process and would only need to address the dependencies for loading the `Fantomas.dll`.
@DedSec256 any thoughts?

**Comment by auduchinok** [comment]
In Rider we already ship separate FCS builds for Fantomas and the rest of F# tooling
