### ISSUE TITLE
Keyword 'override' gets changed to 'member'

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#2221]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAyugE6ICGAtgBKIA2uRAFAJRgC8AOgHYQQCWnAC0RFe6AsTLlmXLjzCwAbsJFIwADwB0AJTLwAggGdMnaGAbwD6ADTyAZrYOJrYOAFdOz9LADWLVmFk5HmluHkVlXlVNAHURdERDY1NzSxtYe0dnNw8bL182ANCgsyZAiHCiFTxNADEaVwMBEoKQuQqq9Q18RERvBnSHJxR%2BdAA2ABY0kQBzfhRu3oB5Gf4-MqDWsKVKyOqupwAZRE5p9AEGBVJ6xGGPCbWijdLH9t3OnVJ4FOcBzJts9B%2BQrFCDMEFydavKIaWKiRAMAxEaBpDJOf6wdyAgrrOSbcrbDqaD7wABCmHiYI4j1xzzaBLeMTiiDJ8TAcPIbBxwVpWwi0IAwqROMTgSCAO6iJrTJyUrnFYiuRCQ%2BkCoULbxysASs5gaXoWXUkG2K6OZV8vaCziw%2BKa7VSmUPcFyBVKl4qvZHE5nW2S3UOzmG4oARjNO2hAAVYAZRLxYJwfTq9QanTwQ4GwEL4GBMmBLtcAymIGm6ebOgARXgGbBRvDwSvV6MnAsg5iQKzgKCZdD8aYGVBgADaHYgoGKkAAJFhcP3ICM28OeBO84r%2B0PwQAGdvgyAASU4SA8%2BF4AC9kFuQeMFxAALoLgC%2B55HV6gk5wyDQs4887H4%2BX78Hz5Fo%2BQSQAAsqQagHPwiCeqcAjfiCQYAEzrs%2Bt5yA%2BC6jiBr7Th%2BxzwIsthQZwiCEJgNBns%2BS5XCuaBriCSHAXIkAAKL7kRJFUduNC2JAaH3sB2Esbh-6QAARrAsA0AhIl-qugFgAAzMxi57o4RDoDU-BXAAcogYo0NBslBC6AkYUJ1GiTOknSSZEA0dcCngpMimQN05C8HANBxno6DsYRxHGapEDGjQjjmTwmFyMJi7WR%2Btkyapjl0QB4IAKwhVA%2BDYKQ0DMogtiwCQ4akEQFBOMI9k8GZxToVFlk-lOYmJdVKX-gxxSjFl7m5flJKFcVMGwGKwjQKQjh7gosDjd2cbVRAtVBPVEDRTwsUOfFUCtclv60R1ikAOw9TleUFUVJAAKrYPQ42TZw02zbGnALWAYURXVglYVZzU2VJSVWfJ9GKQAHCdfXnUN-I0BNBj8nGlhEK40BeEQr3vYgkWrY1OG-Ql-1tXtTnA%2BCACc4NnQNF2IKBiDkOJVVZRjWNgGtT5NW%2Bf12btQNpYhm5uad-WDSQ8M%2BS9TMmpjn0Wd9HN4dtBM8-tzmIUGFP5XotjxEQ8PkOQpCvUtcgrazOMiXjivc4DKsk4hTGCxDVNDR5XnSfNkvhdLy1fTFP2c-j1s-rznVBEGKmO2dWs6673ke4pxs8KbbNgBtL6WxJSs28TfPBq5257ge6CLJwAAqRCYNEkro1LLMp2nE4Zzt2epaHchBplkea0QGL7mWtC8J5OtG0j3sm7763%2Bwrn7oITIeKUG3VueBag7rYpdCJwrFe-gAjFegVfwGcr3jKhMsNXLuMB1Ac7Kznbepsdy8QXuti8Goiz0KQqOsWo2AkAYaM8cMpnx9rLP28sxK3xbgdcEQYwbPzUDoOARB4CH2PllU%2BddzZxQztA4Ottc5h3Jog5BxV4C6VcPTYQREdzxHIH2LKQZsGXwttfSA5BXA0G7EZUiNRioG3QDrUunM76t0UihHqZDUGgS4Tw6C-CiCCOHj1aAAgyp5R1gAfQlEfeCLCIFX2nvgnC89wRIXVogvQlRSCYGWFBSw6D4KYNAePcBk9IEzhMXJQhD8IBIQdtuFe1jyp2KIA49AlDqFEFofQxhC8DEeKMWJTh3DeC8MQIo5RwgRHTjEbAxiEdtwhNsfYys6BZFpIyVk7%2BKi3JqI0SjYQOjIjH0SezZJXivz5NVsUJC%2BcQRgQggANX2iSfgdYThONeiDVxScJ4dLYcY7pMDelBCQp3IJEEajuBRs9cZ%2B4ezTJce01OU8oErIIffCRS8tlqDLLAdAABxJwv9-6IEAc9Y5il0pzJvAss5njA4AyueI8xT8glyPSdBEkPloDeBJOVeFTgDAl3wBVMWVCJaKWZufbGrDcHsObqCgpfSEHbn0oZGFThRrHFyYgfub9OAxl8vuWm0T4nglxWAi%2BhilktSziStZcgkIkO3AAaR6NgNeG9jh7nReQGCwUcW1zxWbAlm08GXNMb4xSSkBZ3O3p5Ro3yXJ-LAMnHBmqiWCp1dc8ESlLHbiPCcSi1jphUOOAfRA4lQIIG4kaVVPL8V8sJdPYldqwUgiUoEwZegjLTE4Dskwc1OBHkTd-VwJBS6wELl67%2Bz0a5e1OQ3Lamcg6RtJUEJSRS43cOEJwAtSgDhxmmOyhmRBGX8BZZwTlgbi1qvrucrmILK3Cp4EpAZY5Kndi4gcCg4l4CkGhlGHslKMlFo%2BsG9VobrXhttT4%2B10bNmDIrAYUg4lKJGsrAIfAxh0AQU3WPeZ7jFlhoFRWw9UbihKVuYMyViBpX7i9XuRFQo1FPpLcO4Fc9dUOohYM2FQpvBcQMNY3uFCPnxHgDO6FpE3kAKAb2keiooNAqtqOr9Va5BKXJYhsqzsSBnugCITyjbsOXWZXGfu0AYblVTZBwdVr042s-XFMx0axWDK0KQDNPdvCCe3UO8j5bKPibgxeA1gzCAiBRn6pAim3FRQ7Nec8s4DA1GjP2Zmd4gA)

#### Code

```fsharp
type StreamHelper() =
    inherit Stream()

    override x.ReadAsync (dst, offset, count, tok) = 
        ()
    override x.WriteAsync (dst, offset, count, tok) = 
        ()
    override x.Flush () = ()
    override x.Seek(offset:int64, origin:SeekOrigin) =
        ()
    override x.SetLength(value:int64) =
        ()
    override x.Read(dst, offset, count) = 
        ()           
    override x.Write(src, offset, count) = 
        ()
    override x.ReadByte() =
        ()
    override x.WriteByte item =
        ()
    override x.CanRead 
        with get() =
            true
    override x.CanSeek
        with get() =
            false
    override x.CanWrite
        with get() =
            true
    override x.Length
        with get() =
            1
    override x.Position
        with get() =
            1
        and set value =
            1
    override x.Dispose disposing =
        ()
```
            

#### Result

```fsharp
type StreamHelper() =
    inherit Stream()

    override x.ReadAsync(dst, offset, count, tok) = ()
    override x.WriteAsync(dst, offset, count, tok) = ()
    override x.Flush() = ()
    override x.Seek(offset: int64, origin: SeekOrigin) = ()
    override x.SetLength(value: int64) = ()
    override x.Read(dst, offset, count) = ()
    override x.Write(src, offset, count) = ()
    override x.ReadByte() = ()
    override x.WriteByte item = ()
    member x.CanRead = true
    member x.CanSeek = false
    member x.CanWrite = true
    member x.Length = 1

    override x.Position
        with get () = 1
        and set value = 1

    override x.Dispose disposing = ()

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-05-04T06:20:06Z - 0e036ac3c54301fb8208205c1af0613e7bb06636

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for bringing this up.
This will be tackled by https://github.com/dotnet/fsharp/pull/12691.
In that PR we have the original keyword information.

**Comment by knocte** [comment]
> In that PR we have the original keyword information.

That PR is already merged. Will fantomas 4.7.x have a fix for this at some point? Or we gotta wait for 5.0?

**Comment by nojaf** [comment]
This will be a 5.0 change.
There are no plans to upgrade the FCS anymore in the 4.7 series.
