### ISSUE TITLE
SpaceBeforeClassConstructor inserts two spaces before explicit Interface definition

### ISSUE THREAD

**Issue by panmau** [fsprojects/fantomas#2226]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAkvgHbqIBOAZgIbR4C8AOkRBAJYnnW1MtiJHwmTLLgLFSlGogBMYRsxbsJXRD14sqAIwDO6MjXRgAtoiObyYABpoArkVaGAtAD4wdh2oj9BRYTjyEHJK0AMxynlq6%2BtCGJmYW1m72Tq7u6EyQADTgUNqI6OjsAObaqGAA2jkQoOpQACQiyGiQSllVLJB1AG5UADY2TRXtvAAM2bUQkMRIJADKrABeyOMTACzDYAC67QC%2BK9UbnY1lLSRttZ09-YOVE2AAjPvqkACyVAAeADLsiJ-8RegABbnCb3aQjDbbXh7do1Z4NfwnbwAeQo3yIiFmWF6y0O3T6AzKtwm0ievEgAFEBKj0bi7pBehRIJDdk84eSEbgTppYLBeiCOVdCWhibUQmSOsQ8mR0AAxdh9AByiAA7r0fgL1HoBizoWy8cdmjy%2BZrJvjrkSNhBVhLJrNTKw4L1YEQAILoKnwGka21gai9PK6lgw3jsjqcwaQY38iWXAk3K1gACsvsgs2wUgAQogKLAyIgAApUfQmCSmljaxBBiAhlhhs2GqDR8txi0ixMANlT6azObzv1gKvI0CoeWIXVgI8KLvLEEr1bAtYOFwj3N5MbxQoTdwA7N2M7Rs7n8wBVbC4MgjsdECdT1gz33%2BwO1KHB-UrxtR9ct83CoZ3AAOfde2PRAAGFelHbQwJdKIbBiPNZzAecX1ZWEDURI1v1jX9twmABOYDDz7fMXlMcwyCQp8q1QvV0I-TCm2wzd40tO57jGRM0wPRAj37GDnSIKi%2BmfdRXxrd94U-ZscK3NjQUeLie1oV0KAkGCjCMKgkJQsS0NDDCuSwk1ZNY9t2NJJSeL4-N7SMR0%2BQfRNqIXJcwHreppOYlc5PM0FxSsqRVIkOyHMEnSyB1Wi33oqTGK-EyWLbf9QRtLjpn4dBkSIAAVMhMAAdQcYFHxEmi9LogyGKMpjEp8syUtqe4U0ClSyFgOx4AAEUQdV7LLX1dN4cTF0kjlP1aUzktFdR7i7Li3nefAKBywF%2BApANMUBPN0CK%2BAgSQ1YIWiiTYvG%2BLJqSv8Zt4e49wWj5iAoVh3mRC8qHQPMKXebB820bR7yE30k2OiqYqquKatOdAf18xrZqAh73gAJUQOAyHgPaDt9I7XLG8MJrOKbrsTe5CKR1H0fgRUbHiMhUXwUgjFKX17jxs6CfiowbF6Qp1QxWU8y0gpyByxFibw2pwVTSm83gF4eb5n5BbIYWBq46BAWLAxyAAfRVVh9uBdmIfOqHLvq6bE2kRT6UW10yH0TBkTIb5dCxkrE1xk7Ro5hsLqJq7JfUaRLLtj4Hadl23fQGm6YZpmWdJk260MyNud51h%2BcQFW1dF8Wg-kqWAvpSOqGd13WF0BXM%2Bz3OPvV%2BlNe1mI9YNo3mR9tyPKOAOYYlouQ7S8P3gANXjTN2HgYoPaQgDQeG-TU%2BqyMLfhOGbpYaQWpH2U7BiQHJ4EGfDexr2F5YEbu7Tk418FBrN4gaR5pHrrYHQABxfJvt%2BxB-sB2ewML4QCvvjf2UMZKFz8lLe6dtFZZx%2BJmZ00AADWmZogoPyNobKswqAmAErTIGzkyop2XJDSMkDLYkzuNIRG9JlRqkQfkIc-Axa4B6s9ZIgNXQCDInTJOdwXJdzAZ5eKlD14P2tuTekABpRAiBsDLVWvwYguCTC0mEptUh7kb7NDvuGDeiYQicRHhtey2hASAPPtonuq5jIbiocHXgIRbYTDTMUHEDsii00ygVRAmgXgIDpBMIRYNTqm05hA7yEirZ3BCGHNxrp1RFCIHvIgB8XTzBSR9Gw%2BYcqwAyiQD6gNNGiUXpVZe5C1x1RidQiYIQS6JN5uQIgxSugDiIEUPhFEOHsAcIDARISSHCL9qIqJNT76xPqcPNxNdCi0k%2BHgzQ8AqAQVgADTpDDs6lPKuU8GlSzYUOiZMupYod5uK6lXLQOIzFV0BLMTART3g7Jsbo2qDjalOJYCEF%2Bbi5EKMKegYg6CqDpM9oI4ZYTfYRPAUciZBjJFxNgW4pBoKUG0m0A7DqAhlS6EQPLeB2cf5-QBrBCKUUoXXxXtUj5JyvkQBCHQlFxYbKIEudoaAZBWD2VaaQeAJ57Auh6tASC%2BhpxEIhVokZMKxlwtpQiqZYppFuORlQbJ7UUEvOlQcyJcrYaIrWCYtxWIuUxECUgLVlKcibBWC0bQsoAZlBcjsIAA)

#### Code

```fsharp
type IInterface =
    interface
    end

type IInterface2 =
    interface
        abstract member X: unit -> unit
    end

type IInterface3 =
   abstract member X: unit -> unit
```

#### Result

```fsharp
type IInterface  =
    interface
    end

type IInterface2  =
    interface
        abstract member X: unit -> unit
    end

type IInterface3 =
    abstract member X: unit -> unit
```

#### Problem description

With the setting `space_before_class_constructor` activated, Fantomas inserts two spaces between the end of interface name and the equal sign. This only happens when using the explicit interface keywords (`interface` and `end`) to define the interface.
When the lightweight syntax is used, this doesn't occur as can be seen in the IInterface3.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-05-04T06:20:06Z - 0e036ac3c54301fb8208205c1af0613e7bb06636

```fsharp
    { config with
                SpaceBeforeClassConstructor = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.
I'm not really sure why this is happening.
If you want to take a stab at this, I would accept a PR to fix this.
