### ISSUE TITLE
Formatting of multi-constrained SRTP functions needs improvement

### ISSUE THREAD

**Issue by dsyme** [fsprojects/fantomas#2230]
The formatting of the F# library source for signature files for functions like `Array.averageBy` needs improvement before we can adopt Fantomas on those files.

The multiple SRTP constraints need to be lined up vertically I think, anything else is problematic.

For example see below

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEIHptgCoAsAnWAdwGcwAeaAPgEFCBzAVwFtEA7AFwFEAPaIgAOXAJawOlTLQA6hGRwxhsmKpkR8AhqyEAbRDTkKlAbUoBhWDtH74AOW2IAFDMh0AbokKbGiVwEoaAF0jRQx3TV0wUQ5dGMQwTU9vXww0TUJvAE8UAD1cEyCwAFoaMHyMUKVqmtraknxOctwwNCcyLk0xaDB2VgAjLzAnMABqMH9W5rAAKmnS5smqupXVxI54CAq2jq7RHr7BwjAAEVF3USQAISyASW4p-JmYrhKy-KX5MLWfpU0NrYtHadbq9RADIYALS8sEeuH8kAANOAoGREFwxBxGGRUGATCiIKAapAACRcLJCZBoSAvJEEjCkiK6ZhUvH0pQABmRdUg9yQ3AAyqIAF7Ibm1AAs7LAQXpAF9xYTpaTyZTcTTuHTiSSmSzcfi6gBGRXVSAAWU0fAAMvErZxGFx8FraoaAEwc6WypQK%2BlE01kimsyCceAAeQAZjaOIgBeT9M6lIzInq0Abaq6TYmeBsI1GxdKIJBdOHIJ75Sa-YmA2rqf1YLBdAmGTrk6y0zUAMyZhn3NGELgAMRikTsiBIcWjTaUXEILLL3oryurQbrDanUBbzLbBbAEu7hYF4P2DYkdF4Ocj8XXEHDkTR84wPqUlebqpX9cb3aTW-1O4ArPuUACkImiCFciDhrAhCIAAChkjhcF415gDOc41F6j6Ltqb7qqun5Lrq251AAbIBkDAaBiDgZB0FWqQXjQJoaL3O4sCMWIEjIahiAPhAT4YC%2BhbLrhH7rt%2BKZsnUADsZEUWBEFQYgACqQiUoQjHMRwrHseIHDIbeuj3uh5a%2BkuOG1qJX6bhJ7bVAAHLJIHyTRiDmLoTFkJYHAdLO0BcFB%2Bl3jxxkLqZ2GBiJa5WYRv51AAnI5lHUYpZrgkcgWGcF1QYXxWH%2BuZUB4WJ1lES6XI7uRTlUQp0GWLonGAQZRnZSZz5mRFFlRQRraxS6xoVXJiB0OGiGEJYrCsJoXGzllSg5WA-FKuFNaFZZ3U-qmO5uolzmKYerDHvVemNUFvELXlVYFZARXRT1m1Gl2A1VcNo37YdDU7txZ2LWAgkbldN3rTZW17hVfKcFwoYcLghBZAA6qIjoZc1c2tQJ7Urdda3ajF90ugBT2UQwsDMBsJyIHEB2jdNaEtaFbXLUGtK3RtkkuqRFUWnwtzhgQnA8JlAr4FBXAI-ASOARKHohZhYX5R1UDM0DpU1IaMmc5a9zhqIfChmpXRQfwQjQWQZC6chf7S3TssM-LmNKzjd1s6rDka3wABKiBwIQ8BixLO5S99F2vgrGpcMVuPO9UhoJW7nve-YbBHBGtyIawOKAYaQdy5doesMwuhiBOiADlBk0Yl4uARSzwN1O6ZHx1B8BmgXRfxKXhDl9TZHQPg8F%2BV4AD6JCXEj2e27n9uajXKvVK6-U8lzDDZKGhA2h0ftOpLVuo-T6OM%2BqDv%2BpHtlKK6GZu8vmhZKv69cHYSdeCnacZ1t4-73bQb54XNjt2XXSjSrmqGevUaiukejyK%2BN816iA6C3H%2BxcO5dyQj3Pu3gB6EGHqPJ078lqf0PtPZWoC56g0XpaAAaq2K4MR4AxEYJvZCdkd4YHmj9P6KpQ5HyrCfHcroCZkL4AOUmfldLUI2HQhh29cG-QxkzQhjtWanwwK6DmAiTiwC4AAcXREbE2ZsJCSP-MwiArDg5CQBtjY%2BTslEQFdOrRerdf7RiuPVaAABrK46C3HojIFDAUjg6psGOjuJqs0WFozwZPd8XUFG13TK7Hko5xzxHAlwEgiBOBAMQOTbWHBEa6ToBsVKEJCCvzqKE6R7DhKdXwrE2eZ9Y48gANIZKEDzPmHB7j%2BPYHmZGYSTERJkQfakXDmw8LqB2cqAiBYHTIPgQxdRA4y1yjnEOmNAZ1OIUoDsC9ajkTofoBgLB2DcDhogfoZoED5nKadZZ51VnmNDhsqxiidwdgvpAuIjAOBCI4CIiQQpvldGYNBXAsBwbcD2B9G5mVKmyMirUl5cTOwQL2XQQuXgOB7E8HRLExSjg5JiPkiQZTagVLuWw%2BFNSI7WLeaQvZ8CxB5itNofo8BNBuVgGbLESTi59LhcM1aMSkX1IwB2fheyzhkE0P0fQMzYH4AFFkSFfB%2BUUrMf9J5ljuG0omaovZLThAQq4PcTx-xe5qutisieazomIp1a8iZ9i9kuP%2BG4vMZBiak3sIgDoiBm6OOLro31%2BjvI036TKQZVSLHCodci6oHYEkuoyMlaCUroCEFEAdLFiF4BKTyRIcm0B3LeA4sEmFKNwl70ibahFNLHW1A7I0vZ7sfBYuIG4y1u8bYfyiXWkBeMahS1kjOfYXBLlIC7VWx8KIgjihpGQAcZtcRfTlEAA)

#### Code

```fsharp
    /// Throws <c>ArgumentException</c>
    /// </example>
    [<CompiledName("Average")>]
    val inline average   : array:^T[] -> ^T   
                             when ^T : (static member ( + ) : ^T * ^T -> ^T) 
                             and  ^T : (static member DivideByInt : ^T*int -> ^T) 
                             and  ^T : (static member Zero : ^T)
```
            

#### Result

```fsharp
/// Throws <c>ArgumentException</c>
/// </example>
[<CompiledName("Average")>]
val inline average: array: ^T[] -> ^T
    when ^T: (static member (+): ^T * ^T -> ^T) and ^T: (static member DivideByInt: ^T * int -> ^T) and ^T: (static member Zero:
        ^T)

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-05-04T06:20:06Z - 0e036ac3c54301fb8208205c1af0613e7bb06636

Default Fantomas configuration

*Signature file*

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Looking at the [style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-explicit-generic-type-arguments-and-constraints) the example isn't explicitly mentioned, so that might be interesting to have there.

Would the expected outcome be something like:
```fsharp
/// Throws <c>ArgumentException</c>
/// </example>
[<CompiledName("Average")>]
val inline average : array:^T[] -> ^T   
   when ^T : (static member ( + ) : ^T * ^T -> ^T) 
   and  ^T : (static member DivideByInt : ^T*int -> ^T) 
   and  ^T : (static member Zero : ^T)
```
?
