### ISSUE TITLE
Format on Save Not Working - As of April 2022, VS Code no longer has the "editor.formatOnSaveTimeout" json setting

### ISSUE THREAD

**Issue by ed3899** [fsprojects/fantomas#2268]
1- Install the VS Code Ionide Plugins
![image](https://user-images.githubusercontent.com/53999059/169172674-f86ec55a-368b-402b-9ece-5b7ee646c6a7.png)

2 - Install the VS Code Fantomas extension globally
3 -  Create an Fsharp file
4 - Try saving

![image](https://user-images.githubusercontent.com/53999059/169172242-2c9148e5-0204-419c-beb0-287ad67b9ba7.png)

Settings.json

![image](https://user-images.githubusercontent.com/53999059/169172731-c476534b-b75d-48ba-9a60-4c999312cb45.png)

VS CODE VERSION April 2022 (version 1.67)

**Comment by nojaf** [comment]
Hello,

Please don't report issues about Ionide in this repository. If there is a problem with the integration you can always open an issue over at https://github.com/ionide/ionide-vscode-fsharp.

Fantomas needs a valid F# file to be able to format.
This looks very suspicious
![image](https://user-images.githubusercontent.com/2621499/169228685-bb3df1d6-19c0-4c65-9bf7-64981613124a.png)
Your ` match` appears to have an extra space.

Please use our [online tool](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview) to report actual Fantomas problems.

**Comment by ed3899** [comment]
> Hello,
> 
> Please don't report issues about Ionide in this repository. If there is a problem with the integration you can always open an issue over at https://github.com/ionide/ionide-vscode-fsharp.
> 
> Fantomas needs a valid F# file to be able to format. This looks very suspicious ![image](https://user-images.githubusercontent.com/2621499/169228685-bb3df1d6-19c0-4c65-9bf7-64981613124a.png) Your ` match` appears to have an extra space.
> 
> Please use our [online tool](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview) to report actual Fantomas problems.

You're right,I did that on purpose hoping for fantomas to adequately format it but it didn't

**Comment by nojaf** [comment]
This is an established limitation of Fantomas: you need a valid syntax tree before it can be formatted.

**Comment by ed3899** [comment]
> This is an established limitation of Fantomas: you need a valid syntax tree before it can be formatted.

I tried running it again , no success yet.

![image](https://user-images.githubusercontent.com/53999059/169291379-c2b6a32b-15ff-4186-b521-6ac25938ca06.png)


And if I try that on the Fantomas online tool: https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMXYAUBLAcwBkBDLQgOwAoB3WAJ3hQGcsmbiBKMAXjAAdJkOoQImHITYA1WPUTpa0FNAAW5Jn34ixEg2AC2lDWGhh6hLOr3jDEAD5gA5ORdhnLxB6%2BFfLrABAK4udg5OrgCCvq4AorEuAJKJAPKJAKoeALQAfLhMwYjhEY4A%2BmB5YABm5OhsxaL2EITVYDLyiuiWzPAAdADaAAwAurjqiNQlDowsYADUwpAAnuTLQpDTYEoNWwaz-QMAjH19Y4scXNTEDL2Do3yLG2sbkAA04FANWFTXbKhgAafCCgByQAAkWGWAAdkGhIDQsO9gRIIQA3OpFAFAiJgIYfXGQJLUJDULAAZUIAC9kASIgAWFEQEYogC%2BdJBTKgkJhcKgiORYPBGPQWLQOIiRw5hkgAFlyAAPUg0RCkSbEGyCyUAJiGXJZBnZKNBMp5sIBkEm8FS1WV1EQ5KhmC1BnRmL5Eoc2ulrriJJtdtpXIgkHQ1Ug%2BrZ0pNrrNfMgACNYLB0C7UcL3djg2AAMw%2B1HEhpMLAAMRodQAcoh6OgVWmDJwipHDdGuRCoeb4UmU-XuSKxYDs-T8yHydDyNBEAAhRDVZiIfBachGbCIJi9iCNxDNiRGgwx9Md%2BPd1P5t2ij3ZgCsI6gY4n09n89ICjX0HIDWJaNg76osGoG4FE2DgGrurZCkeFonr254Dp6hgAGy3pA96TjOc5MIgGTQrCTDvp%2B1Dfr%2BhD-oBtT1NuIFRsabZxlByanrR-aXriADsyGoY%2BGGIAAwugH5sDx-6XME0B4Out7kQ0O4QHuEgHiGdFdgxMEZheWa4gAHBx45oU%2BmGyogRgJmuZF1NJVEtjREG8vRPZnmpcHZgAnDpD7ofOQnoKRknmZRhigbJ4GmpByn2UxmbitmRz4tmKG6YgUTVFga5CUYJiAVuMlgHJnI2Z2UDQQ5zEaZKUpxZxHmYeSRmEHA3kAb5FHZblYAKdyoWFSpxWRYOuJHN6FUJUlKVMDVRh1SmPnZllllgdZIW2WFjFCiVUX9XmQ0PlETCwMEJIACJKIQE2jZlhT%2BQYgU5cFsadQiZKqWtfWSsOcXygqSTVAAKhM1BxBR5LqMwWAAOqEPAmq3vSepzUFC13Ut-KPT16nrZKN7vYqxLVIQCqpLhlDMHECrQphbBsCRjXXrDAXUfutH3QKqNOf1SFYwqABKiBwCw4OQ%2BogEwy1t2HkjD1IizLGSuxHPc7z8AVsExlrjaSQpUY-y3kcIsI2LBWQEYwToFQtb2iWzAmD8a7fbZUulQ4RzaXF8u9LKxumyqFtMFbZ3IRoS5iWuZRWALEZwzdeuKUzKMRWjL2O65HM7UwaypEwyocPzUNDrTV30-JjPi8zcesxEurIR9KdpxnMhYErKtMGrGta9FusM-l8ZGybhBm4g3u%2Bzbdul9LXrlYS1fLOnmdYO7Pd9wPlB%2B3FAep0HTAhxDmrt4XncWiXq29fBBjaoNhIfbI7pTjQ8DcNngu3ppecSNdrXte2xex4f8fHxI2qbefRUJZ9piSptfEkd8t4P1zjvPKi0DYH1NM9X%2BEBtRvUAQqA6sAsAAHFsAkzJogCmVN76ASvM-ZkBc4GIwNkVEeDtDDakxufD2vcVRTm8tAAA1lONeXDsBsFSNQcky5eIpmVtTXEUlLovyoW1IutDur0PRl6dmhIqw1nYdgRQkxbawiOrjag1gqZRBJIZRurcpF%2BVgfIvey0npH2zNqWWE9azEGoMA6goD-yUncZQYImFvqwGJKSLAlAqZmWahHN%2BCjjxKO-mXL0ztXGjWoOEtEqp-zEHMSZJgBiaDGOEpEiydMrId3gXE8KCTR6MKTiwnugYKDGXgOQPisBKbXA0X3YpMjKFlN3hUuyK0kGONxDmWKhICFrhOpMMJ6AADSiBEDQhCbM4kvDyBeOgVYqJpT5rlJoZU4ZsZkHZhzOPCIkAOGbK4YGNgO09okirBwRA8A56e3tAQ8mlMim3lmns%2BGBz9ZHIcT-M5Z9LlTi0FVRAB0ZDQC4BNNJKV4AZCMf%2BI60B%2BKpz-JIiI0ibHvyUl1KpIywVjIAZcqZiLZl1EdLtYIIloSOmWM6JqJT879OocC-eX8yWJMMDmdBlzFnLI%2Bg3XJNprnUFuSqSxkohgULAK-UW0dxZ0OqQwgwOZmGXPpXVWeCAgw7I5bIw0nwRh0gRGwEslMAQEtZEAA

It worked:

![image](https://user-images.githubusercontent.com/53999059/169291463-7c73efd0-b60b-4739-94a6-d9b256b54353.png)
 Any idea of what's going on with the Vs code extension?

**Comment by nojaf** [comment]
No, I don't and please open an issue at https://github.com/ionide/ionide-vscode-fsharp for this.
