### ISSUE TITLE
`global` keywordis escaped with single-backticks when used as part of a namespace/module open

### ISSUE THREAD

**Issue by baronfel** [fsprojects/fantomas#2274]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBtAPAYVgWwAcBLAGwEMAXI2AOwCVECAnRAZ0RosupoApdCpbrQbM2HLlVoAxcgHNWAOgCyCAK4lEAZTUAzXUQAeASgB8AXQA6TSzTzrNYAJK0iSRQDUtud9K0ALMiYCa1tQmlgCDjA5ElgAIzISRQA5BERFbH9SeAAFJlhoNlZIABpwKHYKKhoFVDB0CohQCFaoABIKAE8o%2BsgiTjKm1sh2gDcktWQ0Rra2gAZyuZGnGiROLSIAL2Ql5bAAFmGIc2GAXz3m447u3rR%2BwcuR8cnphuuIAEYntshlMkMABkBohARw5BR-EN9mBPgAmebXU5tC7DFpzUa3N6QDjwADyumBNG03U00IxLxIU3qs32cJ%2BIwAomsCUTdh8oCRdJAkecnujfp0etj4rBYCRyYKJlS3rTlgBmBkQSCrdhMCjSAZJFKIADuJBBkrmFCYU15KP510xwr6ovFRuVlOpMw5ByVUC0BDIRQAQohdLAWLkgmQ8IgKIgmA7Wiazctka1UW0Bc8sbaxRKGaNpc73jCAKzuyCe72IP0BliA2C6yPQMjsVZjQrCGjRiCxxDmxOW5bWu5QO2Zq1O2UcgBsRZLvv9gcQAFUCFEmHWGzQm3WpK33bokuwuxAk60U460-dB9Hs68aRyAOyTr3TiuIbDkVisXA0Vix6AUQNtsA7iQe7xnyaLDqeA4ZheI7XjCAAc96luWs7KIgeDxJG-6AcBcwJgePYUhBkDnlmMEujCACciGPrOuBxFuHLYZ2IEWmBvZCv2xFQaROajjCnyLByxYPogACCugRkwAh4GQ-4dvuYCHlc7FESRw68bB%2ByfN8QlTmWM4sFoaFEHA9FYbuzG4aBybgTaZ7cepV7kVp9K6SJ4mSUZeAmeKtByaalltHhikEYKqkOexGnOcsnyKm5paiQUahrAAIogBreZJ-lxlZrE2SpdlQAMFDQVFeZaW6Qn-IYTi6AAKv4HCMkB2j%2BIGFAAOpuJC-4HIiLHdmxhGFQ8JU8U55UxYWVUAqsBiGHiS6UIGjKGGIb48P%2B%2Bb9blg35cNnHFaVE1ynMnwTjNhgMHATDwF18A9e6fUKUpYDHjcI1HeNMqaTFd6XddgbwCkajoZGBJOBGeAlO6nwvaFqYjXgGhUAaxLSIGMnVJGdU2t9uanW0nwIUJgO3coKOkCCGNMFjWVFtAgRMN6kkAPq6t1ULw0NYWfY8jk-dFZ1UZdiXM10eJMMCX73Y9ro7UF1lHrZh385FJ0cgiRbVWLZAS1LRBfiDYNMBDUMwxycMDfhPOI5xyMkKj1OY5Qkm470%2BN8XSOkwpAuv69LFAU47VPoy72NRgzTMs5G7Oczy1shbbJ582NAsE5rrm%2B9VHivD6AzwAMciy1C7pwQrrTBa9719tiX3p17yxwnF2cAtIyU-jw%2BdrEXJe9RXJxK8pB112rFJlYTrRwpVreGClsAUAA4uGq3rawPB9%2B623c-tvOcWp6uC5NcxwtN2eU2jZZxNAADWPrM7f4asHiNBaKGz7iqDDEwkxO-KwV%2B8Irjw1jCOEF1fY6n1CCP0FAawcHdogNKBgaBEE3KJNYqETYWx-hZP%2Bw894iiAVKEBdJ-q%2B1EgaOQNB240E7rQTYVDKBqBYHVWAqx1iSE2tuXBidq4q0IfaT2v0T4k3IY7SMNBuBjFBLQOQmCMJMCQQMVBPBsH7F-rwhGKdAGCIbsItocIRbnxDmyQEoZ4jwDIC%2BWA69aiQMvuZFqeC3r8PTLow%2BGcYTykEr7VekYiBhk4EkAA0ogRg7CJCrHvmQWhpdGI8N2jbXedsBFDg8Y3OY8ofb7EgD6cgNAb5slYIlWAyVgZsAjPAYOTtiSrxYBtWgajljyU0cnD6Oi0nAKPpPCA8os45J9EEZCLAUqG2gEwAJWpKlzhQbQNK0ByDM03I4nCis8r-xHm4zpxDukcnlC3HJfiJmBK4CQLQJpSlflNAQc5XQyTcKca05J2jR5p3Sfo1o8oZ45NCYwaqxsFEEjyTEwpIImlnXmAPMAVctHtNScdXZXiz45PORMn8qgkArMCpXc4FRzB7H6KwaQ696i-zOEAA)

#### Code

```fsharp
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module Ionide.VSCode.FSharp

open global.Node.ChildProcess
```
            

#### Result

```fsharp
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module Ionide.VSCode.FSharp

open `global`.Node.ChildProcess

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-05-20T08:43:30Z - 5fdc87df2b09629ccfe7386858ad54b971148cfa

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Looks like [SynOpenDeclTarget.ModuleOrNamespace](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-synopendecltarget.html#ModuleOrNamespace) should a have `SynLongIdent` instead of `LongIdent` for the `longId`.

We took that `global` straight from the AST, which should have a [IdentTrivia](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntaxtrivia-identtrivia.html).
Cleanest way of fixing this would be at the compiler side.
