### ISSUE TITLE
cannot format F# files with reserved keywords

### ISSUE THREAD

**Issue by baronfel** [fsprojects/fantomas#2275]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAYrLGALxjBgCWAdtADYCuSaARkXWAL6QA04UAZ0Tp0NAOYDUYANr8IoCIqgASLLimQa6XnMWRlANwCGjZGllKlABj6W9ASWpJq6AMqUAXslt2wAFl0IAF1dTh95QJU1MygtHTt9Y1MpC18ARnDLSABZIwAPABkaRALEajF0AAt49IAmK0iQpTDdBSzVHBjIMvgAeQAzIupEVyw6b0jEkwYY1LtazKVIAFEnAaGJ3yg6fshG0My2pY71NEg2WDoa46SZlMiIAGZFh2ohACd0fBoTADlEADudGK10s6HeM32zUOkxOXQuVxeU2S5ge-heEEgrmwRmgiAAQoh%2BrB3ogAApGd5GAC2wkQ71BSnBkLsTUULSURz0cI0CMZKluszRAFYMVBsbiCUSSSVYAD6dAjEJHAZYIrRLBqPyIMzEFD2TCEjyznykYZpkKtgA2MVYnF4wnE0kAVWwuHeiuV1FV6somu1YH6JiE%2BogHMUXMxxqgpthgvuWwA7LaJQ7paSAMJ0JUCDOagTM6DoEkBoN0EOsg6tWHRXnsfnIu6orYADhT9qlTsQ2UQ1JY9NLwb1leh1aNtZN9bN8ebvgAnO3JY6ZXm6P6xWWK5Y2WHDe0JzGp3GLQn0jY0XbJQBBfroel56nUowB3Whrh744H85Ho0zmRotIMgvVNOxlVxe0oOA1y1DchzfcMInHTo60uBtzRRf8tjSBZgI7G873ecDqUgy51zRV8RwNMd92QydUOnE9ZzsNJnlw693lgBgnAAEUQYFiIIl8IWHbcq05GtaNiFw0L-OZLDSPxbVyPJ7H6AAVSoymWcsRkqEl0AAdUoeAqgDPwGko3dqM-STNGkhiMLkpQ0lFC9lMcfpKDyXp3SMYt3mWPJsFJAQBD9GCRQs0TR3EpDTik7QHKbTD0htNz8gAJUQOB3ngIyTOqMVzPgj9uS-OIkstdJk3SvIspy%2BBfgYPt6QGew72pSQxTSErrLK2zqQYOhRGBYZCHeJ8RHpNTkMq09mLbC96pJeBsiGkbinGybBNtaBKkpXECIAfQBYzTN62KaPiuzEuPRyAIXWqr3eKlMF6d4igLfLTKKqKlB3d8%2Bqjcr7Lu5KnMUeolPyZ7Xvez70Calr3jajquoAi6Iwk67BuGyhRsQLa-IImb1DmpjLFqICtkgWGjDej7KALNa8YJompoZXb9qpIt6ROs7qkxxCrq6Cqwaq%2BYcJp5SADULXxGh4HEb7CrRFs-sUAGEPIbHRdB39GJS%2BZWOl-J8C4otwoVpxlYFsyNeCMSsbivXboN%2B6tlqRTau42B0AAcWEQLgsQULwpVgNhQdsAtdK4HbNjd3wbRWpXOl9b8eKfE12gABrfEedz4QBF6ahXBpRBV2aiKtk3ET-qd4WbOuxP2lklO0pp-4gSz4R5TKUnEF4zzqEoDVqCvJwe2R9Ha7gyzAcu5v4R-NvDYhiBahqmmr2BMRqHN2hx-cfe-IYUk1NgRxnHQPzwsHHShZ1l2UMRcX5spxad%2BG%2BlqDvgxZTlGnv2d4w8aBj3CrPXwdcn6RiiAnVeNx14p0eunPGGwCg0hYPAIwWZYBhXKN3AmD8twNxis7EWr8ZLIK2I8c8NNg70koLSFwJgADSiBEDYGvmUdAjgC5GFoKrOej8F7azgfoL8rckEe18I8amvhIDZ0EbnDYAhnqcScP8AsiBVoZwJsHEKYV8xCRZNFKiS9%2Bot0QdydutCpaKPxJSZcpJuJM2gO8ZhPw7zwGdKPTUvF6AHXHiQ%2BumtG7P0oXRN%2BScJaWEeCbRRjDPEsNvnQUYHEGAFghNgUYmBxihNgbrDQYtYkfyUI8b2NMOFcOUkjEBAxlHUFUcUKBzErDR1jkDeB1j6LvwphUtOiiMmQXQNkBAmxoHz3MWGfgQQfCaAEPgMKUgYGcCAA)

The code below throws the following exception when formatted in the online tools (and I can only assume this is why the file doesn't parse on the command line tool):

```
Exception of type 'FSharp.Compiler.Lexhelp+ReservedKeyword' was thrown.
```

Luckily, this can be worked around by surrounding the keyword with double-backticks.

#### Code

```fsharp
type Foo = { include: bool }
```
            

#### Result

```fsharp
type Foo = { include: bool }

```
            
#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-05-20T08:43:30Z - 5fdc87df2b09629ccfe7386858ad54b971148cfa

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hmm, this is an interesting one. The original source code has a warning ([tool](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQAuAngA6wwxVqzABeMMDApmNAK5xsAIxE0wAX0gh1QA)). Fantomas will no longer fix theses kinds of issues for you.
There should have been ticks in the first place. The tool will validate this in 

https://github.com/fsprojects/fantomas/blob/5fdc87df2b09629ccfe7386858ad54b971148cfa/src/Fantomas.Core/Validation.fs#L8-L25

Perhaps we need to add that error to the warnings to ignore.

**Comment by nojaf** [comment]
@baronfel can you still reproduce this problem?

**Comment by baronfel** [comment]
Yep! I think what you're saying above is 'if we add this warning to the list to skip, fantomas should property-escape the keyword when formatting'. Is that correct? If so I'd be happy to make that change and add tests.

**Comment by nojaf** [comment]
What I mean is that the `cli` tool should be able to format the file, but leave the warning as is.
The input was invalid, so we don't produce valid output either.
The warning in both the input and output should not be considered a problem in Fantomas.

We no longer have any aspirations to fix these problems in Fantomas.
In v5 we gained a significant amount of performance by not doing types of checks.
These occurred in `Ident/SynIdent` and are all over the place.

**Comment by baronfel** [comment]
Fair enough then! In that case we can close it.
