### ISSUE TITLE
Don't break namespaces unnecessarily

### ISSUE THREAD

**Issue by Thorium** [fsprojects/fantomas#2279]
Looking at the (silly example) code here:

```fsharp
let generateSillyPwd() =
    System.Web.Security.Membership.GeneratePassword(9, 0)
        .Replace("a","b")
        .Replace("c","d")
        .Replace("e","f")
        .Replace("g","h")
```

The max-length would allow this code.
Default setting Fantomas still breaks the namespaces, hiding the method call "GeneratePassword" with the intention of post-processing:

```fsharp
let generateSillyPwd() =
    System
        .Web
        .Security
        .Membership
        .GeneratePassword(9, 0)
        .Replace("a", "b")
        .Replace("c", "d")
        .Replace("e", "f")
        .Replace("g", "h")
```

When I read the code above, my focus is that "oh, this is System: That is important".

**Comment by nojaf** [comment]
Hello, please raise this over at the style guide.
We have something in place today but tries to respect the `max_line_length` but it doesn't always hit the mark. This conversation should be happening over at https://github.com/fsharp/fslang-design#style-guide

**Comment by dsyme** [comment]
I commented on the "Don't break namespaces unnecessarily" here https://github.com/fsharp/fslang-design/issues/664#issuecomment-1138877804
