### ISSUE TITLE
Idempotency problem when format computation expression with generic parameter

### ISSUE THREAD

**Issue by albertwoo** [fsprojects/fantomas#2285]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKCCGAXDAeACogE4DOsAdgHxjAA6Rt5EEcAruVvY82DgNaIwARgAMXJsxJ8AlgAdhYhuQC%2BkADTgoJRFizTyAcxKowAbU0RQPCJAAkWAJ6zkaSPqzqLzOwDcMAG1YXMy8eEQ1rbwBJciQOAGVpAC9kCMiwABZQsABdL2U0y2y7R2cTNw5PSN8AoJNzdOFC60gAWQwADwAZfUQuxEMsAAsq9KEAJhFsvJ4CrysW%2BydgyAH4AHkAMx7yRHjHf1Ti2z9A4Ib08eaeSABRWK2do8bIf03IafzmhZulstcAEawWD%2BUa-U51NAXSIAZmu0XI2iIWAAYvoAgA5RAAd38vTB1iwRCCn1m32OpRWQJBBJsJ1q52yEAy8Js8VkGGgiAAQohNrAiIh8BgiBgALY6Yi05hEkmRGbMOY8H7eP5U4Gg%2BE1M71JlgACsrKg7M5PL5Ar6sGxxGgGG0MR8sFtego0ogssQpMV5OqavK1M1xwhjMaADYjZATVzefzBQBVWTOIi2%2B3kR3O6Suo2bALaL0QJXMFV0yn%2BjXS7WQkKNADsEajZtjiAAwv47SRmxQSLLoFgBW6wDn-Hn5V95hTlmWaVr6TqoXqABz1jnR82C1qIMUAqXZ3Oe0dk8e%2B0uA8sz4O6xoATmXppjFs7-izeqHI%2BsCoLPsWJ6gAYrs6raFrFEW8uQAQU2LBiE7MUxQwAcPXzMBCyKY9J1PacgwZS8xiEUDGwteJN2kOAn3IAdX33d8x2VCd-l-M8sLnasxiuPVIxXRAIKgogiLFEiQWfRpEIPb0j2-dCGMw30L3nRohDhdiGzAohYHYeAABFEDxfieIQ4kqJ4D9kK-X4fwqDxz2wuSxhZdj2g6KJNgAFSGAZbmHPYhgFLAAHVpHgYYBwyKZRM-cSzMkiz-1kljIiEQ17M6GJNmkDp1iTbABVuDpZEFEgSEzcijX1ULqMPWi0Po6KrOYoCeCEcMko6AAlRA4CIeB-MCkYjRCpCUJoOiVncGLrLi4C62atqOvgDFWC3YgtiiKCxWMI0hAG0zVXMsVWH8PQ8V2FEBTg3RiGcydasAvUhCXdiZoFeBWn2w7ehOogzr0iNoCGEVOR4gB9bEAqCraIp2qLRuukMxhvZqVNFBx1iIHpu26oK%2BrKoyaKLYbymhpibsaSYIwcxGMGR1HpG7ebFqIZbVvW27wcqiTqr2g7pCOxAPq%2Bi6rqJ2HInGPD2Ipqm0awF6uZ5vnsG%2B9jfv%2B3tiGB0GRlZvGqpGyoYZwkW2JeByADUGW5fR4H0AwMd6xdseYYzBuLKA-VcQmZPG%2BrmHGRTjc6FF2F7IqLdia3beCh2ICd7aSyhvWhYN6xxjs-2Og02AsAAcR0HK8sQAqiojkqo9yXHUPZ9VpMWWLvYgcZEuN17ud6bkn2gPhuVFDudBIdZyHicUWxBBbipfPctYryLqr-fWbJFpqXixXFW50a0Bku5wtNS8hpBdcgwNiDd6eZxpKMnoadanQNPbqvVximl4wLxAxyED8hg4oRJX%2BwVhBWc2AMQ4g4H3hRCeYUTIQzjjPRit9iaXHuk-A6xByDYGkD4S0hhj7biINvfQe8iqn3SOfCBzt8YYRvjXL2994ZNy5k8Lo4oATwAwK2WAhVDDLx5mAzyF8XYlCirPRO89rAwnCOxPOxBpASg4AEAA0ogRAsggEDCwDELuGAP52zPuA8qYk2bTyrpQ8E1DGgwjFi8Numi%2BBPBICpNSsQsTdkQM9ZuPM875UKl2fSco9HhQMZDGB1cTF3zMUbdIkBuQinvIKDSNNoBEGkeiKC8A4y7woFpaAbZRSgN3Lw0hsdXbmSEXA4Woi-YRMkYkmROB-D7FUqwbsxJZD7AcIcHhb4cYVW1pXAmCdSlJx4DCVOESFFKIcnTHBWwrHkBsb0Ih8URClxjlAopgjYFUNCekGEjcIn1JItLBAzxiG6K6YqTQOQ0huBICiQqJhz7KCAA)

#### Formatted code

```fsharp
odata<Person> { count
take 10
skip 10
}

```
            

#### Reformatted code

```fsharp
odata<Person> { count take 10 skip 10 }

```
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-05-28T16:36:31Z - 929b3f09486d71f79cbb9671bc021dae5745b531

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for opening this issue.
I believe the problem here is that the generic parameter isn't captured in 
https://github.com/fsprojects/fantomas/blob/e5a8830693233f330dfa27852d3f7aa2db99f138/src/Fantomas.Core/SourceParser.fs#L580-L588

This active pattern should be extended to deal with `nameExpr` being `SynExpr.TypeApp`.
Are you interested in submitting a PR for this?

**Comment by albertwoo** [comment]
Sorry, I do not have the knowledge to do this.
