### ISSUE TITLE
Inconsistent multiline bracket block formatting in object expression

### ISSUE THREAD

**Issue by tymokvo** [fsprojects/fantomas#2292]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAkgIJgC8AOgE5kB2EEAhgEYDO6F906YAtot44gph6YNAEtq6SjWmScefACFSwlmw5de-QWEaiwEqVWqysuAgGFSsugeoALQWK5EbdCY4rOCi2aflgAEqIcBTwACoBJGDAYABqgpgAMrDUAOYAChSwuBRYAHL0vOKSANxghNQAogBuiNQp6YJZOYIFRYhorF7pAL5%2BxgA2iFzo9hJpKm4QwNO2YNSIAO6WYEvO9nPzdFoCQgD6AHQi0QCMW9s8fHtgR3rRAExzvZAANOBQzCPoE8yoYABtD4zYF0SAAEjMyDQkEMb1BEAhNXogwArtDAQi6AAGd6XKD4ahISQAZTEAC9kHjLgAWLEAXVBvWpIO2EKh-1hknhbPByLRGKB%2BNOLPmkAAsvQAB5JCSIJL1NJjHmXU4PbEMpmi0C8jkw%2BrwADyADNZYsSVhhirbEiUej-kLLg9RTaqkSTWaqVjEYNjZBNbZmaCdWLIfJOYxYLBBtawXy7YLvWAAMwusGEr55ABiEhR%2BWWgzlsdsbHRAboQdsIZtYdwEajMbTtoFDqTNLTiJJ2A4iEUiGNsAoiAy9HYvHQgmLdFLiHLEErdGrcb1UEj0anzftaEd2wArB2oF2e32B0OUktBNB6F9CTVYFefqkpxAZ3OwAvWaGV5A142sZvE3xAA2A9ICPaBe37QdEAAVWwXIrxvag7wfMQnwPY0US%2BN8Pxif9awxH8Gw3eMW23JMAHZQPAyDT0QCxBmvZgLFSbpUU4QdnzATDBmw7ZGUDbV8O-X8SP5LdMXxAAOajuwgk9oPFa5JwwrDZ34rVg2E8MYVEptSIknd5gATlk48oKHFjBnQpMeL4%2BYBIrITdR01diP08TANVXEkzAuTEEIY0JwoFjuG4eguNfDTBK0ly6109z8M81thRFXyaIUocST4MQ4Gs6guLs9SHM0qttPitz1w8hMUtVZ10v8wLguy7hcujGz8SikqYrKuLCL0pKavI4VUwantCGyVEiQAEUQQtWuCyKKDLaKnNir9XK5dAxKGyTVXbXzJSlfBjXCRxql4xASXsQd0AAdTEeBlQPGkNVW%2BdnI2iqtp2si9u2U590O6VCWNMQpUNXJ6HQQcqilbAh2YZg0IKg9dze7q1t6r7CLhaq-qM2xThA4GpWCUJ4Aep77C416cM%2BmtvzxwaCaTU4qNJ8nB3gfJUW0CgTXwCduD%2BA9Tnp9bGc27hUUGH5C0WLNB3C9BgsiOt8cMtmZN8rmwnFWX5blJWKBVxbQOgexRw0QR9nWan-Xe98GeXTbmd5ZLhtVUzSYm9hMENChZVYKnnrbDHbEcj7Jdd773dDT3-vmdVQKOv36ADoOxFYXn%2BcF4XRbZiXsal76ZblsQFcQE2zcEdWvQ93bCboB40vxSB08z4P0ANiuq5r6Hzd8y3rc4W37eVYvF3K3HuU1rztgeer26OuIE0UCR4AmUOaYPKSI7oKPnZjxECM5eOa0T5uIAeUaV%2BlLMps4FGN6JbfHrD-E6ad3Cl1Ppm54sy1viB4B175SmmrAdAABxEYcMEaICRijHeXF0ZT0-KXfqiVG6sxAUDFehtK5ykUNZaAABrRQ7ByEjGYIaagJIOhWT5qjJMXVI6lWnn1esVUgEL2TiTdu%2BYlhVz7OgC89R66zTBtQZwKNKjwCUvzQu%2BIiroLwlwhKPCcHAKdBzduhBCxpGoI-agz9UhkiMdDVEQ5wiwEJMSdA0MUaFTUmov%2BUAz6aL-NovhtgHg630XLQQ1AnF1EaGkRRewpESFkaxFxl03Ez24d4hOTckwPB9gQiunokhFEYPAegDFYDI3SEIqu8T7LsJ6pwnGyTfo6O2MmHy7d4FOF4JIFEABpRAiBsD2PqOgQklD6CmN3rZVxP8Xb-02gNHxtVGlt0uJAEhIyyGemYBNWAU0eaIInAowhVd4GI2RnEg8bDD4cIwbHLBWjUm4MuMmZeSzFCjkyogaa2doBeFaiEvZMEZGpFmtARi7BHwsJURMzG0cS7XLqfPeZ8xkx3yWa075AyUQWkmmxbAFpMBWlUgkyZJ8PEAO2vCr2jSwFLO6b0o6uc9gmhWdQNZcplHeQPhAI%2Bv8klePqb4ugyZ8FLMxblHuCAG6XFUT-D49JqSwmYFmZG-xVG9CAA)

#### Code

```fsharp
type IA =
    abstract member a : int

type IB = abstract member b : int

type IC =
    inherit IA
    inherit IB

type RecordType = { VeryLongPropertyName: int; AnEvenLongerPropertyName: string}

let thing = 
    {
        new IC with
            member _.a = 1
            member _.b = 2
    }
```
            

#### Result

```fsharp
type IA =
    abstract member a: int

type IB =
    abstract member b: int

type IC =
    inherit IA
    inherit IB

type RecordType =
    {
        VeryLongPropertyName: int
        AnEvenLongerPropertyName: string
    }

let thing =
    { new IC with
        member _.a = 1
        member _.b = 2
    }

```
            
#### Problem description

Super minor, but the formatting output of `RecordType` and the `thing` object expression are not consistent with one another.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

(I could potentially help with a fix if given a pointer of where to start in the code, but it wouldn't be fast 😺 )

#### Options

Fantomas master branch at 2022-05-30T18:11:41Z - 5e927521516445116087af12c76d83e0dec01332

```fsharp
    { config with
                MultilineBlockBracketsOnSameColumn = true }
```

**Comment by nojaf** [comment]
Hello, thank you for raising this question.
The setting `MultilineBlockBracketsOnSameColumn` is meant to cover the G-Research style guide.
See https://github.com/G-Research/fsharp-formatting-conventions#formatting-object-expressions-and-interfaces.
