### ISSUE TITLE
Function lambda with type annotation breaks code

### ISSUE THREAD

**Issue by abelbraaksma** [fsprojects/fantomas#2295]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzMAHmAJ5hoCWAdjgLQB8YVOAvGADoBOblEEuArjwD6YeoTABqEp268yjaqIZNIAGnBQAztixUA5ptRgA2hoig5ESABIsxAA7I0kFestRrANwCG6fk5MzSwAGN3coAElKJGoAZXIAL2Qw9wAWIIgAXSCAXxSwC0sbO0cjF2o1DI8fPwDTcLAARny5SABZbwIAGSpELsRKPSwAC0qGxoAmYKrsuTygwtbbBwDIAfgAeVweykRYu0wxoq9ffyN68ImW3kgAUWitneSqq3RcSBnc-MWb5dLnABGsFg6COSxqZzQF3cAGZrlYotoOFgAGJUXwAOUQAHd0L0wZYsBx-J85t8qsUVmUgSCCVYTrVzi8wKl4VBYvZvNBEAAhRC4WAcRAABW8HG8AFtsIgOHTeESSe5Zrx5nIfvSSqsaaDrjYIXVmQBWNmQDlc3n8wV9WDYmXQbzaKKeWD23SwShyiAKxCklXk9yU-5QbVyvWnA0NABsJrN3L5AqFAFV7I4OPbHZRna7yO7PXhfNpfRBVbx1R5NdTgTqKQzIYEGgB2GOcuOWoUAYXQDs07fdmgV0CwgrzuALPqVXwWNYrgKrodrEfCAA5m%2Bb41a2ogJQCZSOx0WwCXzNOqbPabqF0yGgBOVethOIXvoXNs0foQsTslTgN-LVzi-6le4SNKEzKmi2iAAIK4FgMq9hKEreHm3oHkeBQnkGkAhgB4ZAe4jTNGBsYWg%2BsRbuQcDPh6r77p%2BfrfscM7Bv%2BNaAVCzKTHeUEwTKZEShRIIvsyKF0cW-qMaezHnqxuHseMcJERBkEcLAgjwAAIogeL8bBspsiJljKmJDFLEx5RYPObH1sBrJgR0BARLgAAqwwDLc757MMgpYAA6uQ8AjHmqTTKJh7iaZknmZZsnWfhxp2Z0US4OQBAbKm3hDhwtwEPYQqaJoObUUaIWGZOaoYasrgyYycnAdGCUEAASogcAcPAfkBaMbLBah4W-GZVU-lZ0KWI0TYNc1rXwBi-DbjKWwRLBEqGGyjS9SZ-WRRK-DoLoeK7CigqIVgulOVSOE1bFo0rmBk2CvAbQ7XtvSHRwx26XmMDDGKXK6UI2L%2BYF63lT%2BA0VBddYjXIjS3g1ynisQGwcD0-YdYF3UlXIRlhRtGqRYNxzDcyUwmvZ8PeIjyPkP2M1zRwC1LStHHA6WFVlNtu3kPtiCve9MpnaUEOLu4EyEQ0kDk5TKNYI9nPc7zGUfSa0DfeKg4yv9gOjCzx6g-j4PVZDxNXA1ABq4Y8lQ8D6GjXXMkumO8NjaFloGlUG0NMVQ7wEwKeL9kooIg6FZb0Q21rQWO1kZWs3rmEE%2BCXvE7Z-udOpsBYAA4tg2W5Yg%2BWFbbeaGlHYDO31eOYdhhvC5YEzxf7T1c70PLPtAADWPJq%2B32CaBslCxJKj4grNRUNG%2BH6lV%2BIMSVXLGe5d3sQBM9Xi1iuIt9gtoDALiCacllDkG6lCQdEm500z4%2B0VP9EzxFc-SQvRsNBM43i5BeJ6JQgeUMH7rxF-DK-AhROVgFEGIWAMqFT3B5HW6E45-kfoTJOL8brv12jKSgUDPDWkGOfHcHB95UCPoVS%2B4QJ7jhvsZO%2Bm0H7VifrXOQExYaN05k8LokoATwG8J2WABVBjr25jAyeWMY661nog%2BhyDF7MhhKBcWucZTkClNQXwABpRAiB7DgIGFgKIXdvC-ztlfWBoUXZszPFIxOMiGgwjFuESArdDHtyeJoZSqlohYn7IgB6Tdua5zygVPsyFiSUNEdPWOEjKxIOsc-cIMITbix5GKdcQp1LU2gBwZR6JYLwETIfd0mloBdnFMfYRYSnZiPgVEyx0UbHxL9g4xRWSVGQPQPsFS-B%2BzEnsPsYghwaKmKoTjGhld3YWSFnhSwMIU4OI0Vo%2BytMCFbCcZQFxvQyH4WCKXcuuNyyRWrgwqZcgYQNwcR0iiMsEDPBMSIypcwNCZDCC4TQKICpGAoSAHIQA)

#### Code

```fsharp
let f x y : int -> int = 
    fun _ -> x + y
    : int -> int
```
            

#### Result

```fsharp
let f x y : int -> int = fun _ -> x + y: int -> int

```
            
#### Problem description

I encountered this in a slightly more complex scenario, but this was the minimal repro I could come up with. If there's *no* type annotation on the function definition `f`, Fantomas will reformat and put the type annotation on the function, i.e.:

```fsharp
let f x y = 
    fun _ -> x + y
    : int -> int
```

correctly becomes:

```fsharp
let f x y : int -> int = fun _ -> x + y
```

However, if there's already a type annotation on the definition, *and* the lambda has a type annotation, the result of putting the whole thing on the same line breaks, as can be seen on top of this post.

Probably a niche scenario as clearly the type annotation is redundant, but still, running Fantomas shouldn't break code. Solution could be to put the lambda in parentheses, or to drop the type annotation (after all it is redundant, it's already there), or to not format it to one line.

#### Extra information

- [x] The formatted result breaks my code.
- [x] The formatted result gives compiler ~warnings~ errors.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-06-09T08:42:49Z - 25634b293fddce9794956bd80189f91d0406c8c3

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

Btw: I do know this, but for some reason, in VS 2022 at least, using `.fantomasignore` does not have any effect.

**Comment by nojaf** [comment]
Hello, thanks for reporting this. It is an edge case for sure, yet an interesting one on an AST level.

The additional `: int -> int` at the end, leads to the expression to be wrapped in a `SynExpr.Typed`.
You also get this node when you have a regular type annotation in a signature.

For example:
```fsharp
let x : int = 1
```

leads to:

```fsharp
SynBinding
 (None, Normal, false, false, [],
  PreXmlDoc ((5,0), FSharp.Compiler.Xml.XmlDocCollector),
  SynValData
    (None, SynValInfo ([], SynArgInfo ([], false, None)), None),
  Named (SynIdent (x, None), false, None, tmp.fsx (5,4--5,5)),
  Some
    (SynBindingReturnInfo
       (LongIdent (SynLongIdent ([int], [], [None])),
        tmp.fsx (5,8--5,11), [])),
  Typed
    (Const (Int32 1, tmp.fsx (5,14--5,15)),
     LongIdent (SynLongIdent ([int], [], [None])),
     tmp.fsx (5,14--5,15)), tmp.fsx (5,4--5,5),
  Yes tmp.fsx (5,0--5,15),
  { LetKeyword = Some tmp.fsx (5,0--5,3)
    EqualsRange = Some tmp.fsx (5,12--5,13) })
```

I always assumed this was duplicate information from the SynBinding that made things easier in other places from the compiler.

So, a bit to my surprise:
```fsharp
let x : int = 1 : int
```

gives

```fsharp
SynBinding
 (None, Normal, false, false, [],
  PreXmlDoc ((5,0), FSharp.Compiler.Xml.XmlDocCollector),
  SynValData
    (None, SynValInfo ([], SynArgInfo ([], false, None)), None),
  Named (SynIdent (x, None), false, None, tmp.fsx (5,4--5,5)),
  Some
    (SynBindingReturnInfo
       (LongIdent (SynLongIdent ([int], [], [None])),
        tmp.fsx (5,8--5,11), [])),
  Typed
    (Typed
       (Const (Int32 1, tmp.fsx (5,14--5,15)),
        LongIdent (SynLongIdent ([int], [], [None])),
        tmp.fsx (5,14--5,21)),
     LongIdent (SynLongIdent ([int], [], [None])),
     tmp.fsx (5,14--5,21)), tmp.fsx (5,4--5,5),
  Yes tmp.fsx (5,0--5,21),
  { LetKeyword = Some tmp.fsx (5,0--5,3)
    EqualsRange = Some tmp.fsx (5,12--5,13) })
```

Anyway, I would suggest detecting that you have a `SynExpr.Typed` with an inner expression `SynExpr.MatchLambda, SynExpr.Match, SynExpr.MatchBang, SynExpr.IfThenElse` and always add a newline to solve this.

https://github.com/fsprojects/fantomas/blob/25634b293fddce9794956bd80189f91d0406c8c3/src/Fantomas.Core/CodePrinter.fs#L1210-L1213

I wouldn't change it everywhere you find usage of the `TypedExpr `active pattern, for the reason above. Sometimes the `SynExpr.Typed` wasn't really there.

I hope this helps, are you interested in submitting a PR?


> Btw: I do know this, but for some reason, in VS 2022 at least, using .fantomasignore does not have any effect.

Please open an issue for that here if your `.fantomasignore` isn't working from the command line as well or over at https://github.com/fsprojects/fantomas-for-vs/ if it is only in the editor.

**Comment by auduchinok** [comment]
@nojaf This should ideally be fixed in FCS tree (so it contains the actual tree structure without changing it), but until that is done you can try using this trick: https://github.com/JetBrains/resharper-fsharp/blob/b6faed78754be2001edf81878e2ca53bbbd19191/ReSharper.FSharp/src/FSharp.Psi.Features/src/Parsing/FSharpTreeBuilderBase.fs#L874-L881

**Comment by nojaf** [comment]
@auduchinok I'd be in favour of that as well but changing

https://github.com/dotnet/fsharp/blob/db4bf11c5b28a7fb416e8e8a0d503742985da017/src/Compiler/SyntaxTree/SyntaxTreeOps.fs#L670-L680

feels like a landmine 😸. 
Who knows how much code in the compiler/tooling will depend on this.

**Comment by auduchinok** [comment]
Yes, it does 😅

I think that wrapping it like this could/should be done just before processing an expression in the type checker. That way it doesn't look _that_ scary and would allow the tree to have the correct structure. 🙂

**Comment by nojaf** [comment]
Right, that does seem more doable. A bit similar to the fix of https://github.com/dotnet/fsharp/pull/13131, where the logic was essentially moved from the untyped tree to the typed tree. I might open an issue for this later on in the F# repo.
