### ISSUE TITLE
Trivia before comma in tuple

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/fantomas#2309]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBDMAvGABQCMAOgHYDEAlgGZgAqAogMpNUA0YATFdUSV4DKgEpIXcFADO2LLUoBzGajABtaRFARdUACRYAngAdkaSIqyStuyPoBuudAFdzG23oAMUvXsgAksJCWGy0AF7Ivn4QACyeYAC6tgC%2B0doJ9sZmapaU1ul2js5uapoxEKSF-gCyuAAeADKKiI1CSlgAFjYVYKS8XgnJemm2On5Zpu6QQvAA8vTNlIhsxpg9E8Wu7uUVvNV2LMILS1EJEJDo9JBDqYXj-oZTuQBGsLDoG49O22XnYABmA4XIJyABOWAAYopnAA5RAAd3QLS%2BfiwYLctxG90yTxyFjeH1RFy2pTQuxisWBUDYJlw0EQACFEPRYGDEAAFXBg3AAW2wiDBxN06MxMWGulGegeRWy00JnwO9h%2BZI8vQArNTILT6UyWWzWrAEYLoLg5EEHLBTQpYJRhRBRYgsZKcTFJvioArhcqSjt-gA2LU6hnM1nsgCqJjMYNN5soluttFt9rA9GccmdECluhlJLlr3eitxKr9vQA7EG6SH9eyAMLoM0yWu2mSi6BYNkptPoDPiu5jXH5gmF72k0sVAAcld1oYNNUQvJegq76adfexA7dePlI6VY7%2BvQAnNPq2HEM30Mnqd3e34JVnXZsh57d8XfQeKqQfP9tVXEABBegsEFZteV5XAU0dTMwGzDIt2fSAvT3EsPxiUgqh-YM9TPNgF1oOBLzta9V2g2CwFzAwEKQt9fnJf5%2BhPACgMFXDeXwj4r3%2BKD1xdTcn2eYciWQ986N6UggUwv9-zBWAXGEAARRBkTY4ChWpbi737aVBwEqArFHFDRM-KkfzqeoAnoJhOiEFgexWTo2SwAB1Wh4C6FNYkGHiHz4x4EP04TaLVT9NVMhognoWh6jmaNcA7MEWHqEx2RkGQkyI-51S8zSN20%2BDdLyAoaNVCk-FIQMwvqAAlRA4DBeAXLc7pqU80jHz8gqAuK8c0IrSqarq%2BBYRcRdBQWAJgN5VRqVINrfNlAreRcdAFGRZZITZcCsFUphnkCkr6KnH8BrZeAamW1aWg2sEttUlMYE6bl6VUgB9BFXPcua8v4j1CoMkTgrQ49KuknkjDmMFmlbRr3Ja7K9HvGD2oW36uq3QzAb8AYtTM0HcHByHaFbYbRrBcbJum%2BivpzHTfqWlbaDWxBrtuwVdpyfaeqxjDekgPGCahrBzoZpmWbiu6tWgR6eXbQU3o%2B7pqbgn7pjRzYMdKvReH2SqADVfUZRQRGUGHmv%2BCd4d0RGyIo91Vfyf6gs13ReAk3mzMhOT23Sw3hEUJRTY8y2IGt5G806h3OdQrGTPdhp5NgLAAHFsES5LEFS9LA%2BpLKlfI2mdyE7ro610L3YuxmWkZS9oAAa0ZGXa%2BwGQ5koNg%2BXPD4Roy3obzXHLeO%2Bjrfuo9GAediBeAq3n4SRKvsGNIR2cQRTIsoWgbUof9hHnUnKd7kjvKR%2Bbw5H18x6d-5eD63n-2RJRKE9yhvdtMIH7ilx2SYWAgiQfI4vSiuOyedbbbgLEXC%2BB1ei8COrfFagpKAAIcIaZQu8lxglXooDe6V94VD7iAgu4CiyQK5lrYG5cGanEaHyF48BcD1lgGlZQs8mZANvAjLSNN8pnwgerce-wATfl5mnQUtB%2BT-3QAAaUQIgEwv8QhBAbrgZ%2BZsD7AKPjbQhgliF8Mvr0AEPMKiQGrso2upwZDSVksIeErZEBnQrkzNOKU0otkghifuHDcpcJVkQx2UCKgAh1rzRk3JZzsnkkTaAYIxEwmAvAcM69bSKWgA2Hkm82EeKtpw5Ww9C46O%2BPw-RbsjEiOieIrAzhVgyRcK2DEJhVhGHWMRdRA8fJDxRvbIqJCS66ABLHIx0jZFmRJughYJjKBmJaLgtCXhg5JGyfnbheS-GkN6WXIxVT8JCwQGcNR7CskjGkIkaIlgZCQjSmofBKQgA)

#### Code

```fsharp
let a = (1
#if TEST
, 2
#endif
)
```
            

#### Result

```fsharp
let a =
    (1,
#if TEST
     2
#endif
    )

```
            
#### Problem description

Notice how the comma which was in the compiler preconditional gets lifted out of it.

Maybe such case should be formatted:

```fsharp
let a =
    (1
#if TEST
     , 2
#endif
    )

```

Maybe a warning showing the location of the invalid construct, and formatting the remaining constructs would be good solution rather than failing to format the whole file?

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-06-28T06:06:04Z - f175d437748ce81cf3b135d70e91d015e6d6be77

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.

You are using conditional directives in a very exotic location there.
Perhaps if the commas inside a tuple are used as trivia anchors you might be able to solve this.

Are you interested in submitting a PR for this?

**Comment by smoothdeveloper** [comment]
@nojaf, sorry I glitched the title due to adjusting my post the wrong way.

I may take a look at the issue eventually, the issue is not urgent for me, so you may leave it as up for grabs.
