### ISSUE TITLE
End-user documentation

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2316]
We need a section in the documentation on how they can start using Fantomas.

This should cover:
- The installation from the `dotnet` tool.
- Initial usage from the command line.
- Usage in the editor (VsCode, VisualStudio, Rider), the important bit here is that the user should be aware what version of Fantomas is being used in the editor.
- Formatting check during CI. How to do it and why it matters
- `.editorconfig` support and an overview of all the settings. It would be nice if we can have some sort of generated code samples that are always up to date.
- dotFantomas ignore file
- Git hooks

A lot of topics are somewhat covered in https://github.com/fsprojects/fantomas/blob/master/docs-old/Documentation.md but we need to revisit and chop everything into logical units.

**Comment by yisusalanpng** [comment]
looks good! 
thanks nojaf :)

**Comment by nojaf** [comment]
@yisusalanpng I've been thinking about this some more. Here are some suggestions:

- Start with an introductory paragraph on how `.editorconfig` works. How both the command-line and editors respect this.
- Split up the list of settings into some categories: "Auxilary settings", "Maximum width constraints", "G-Research style" & "Other"
- Remove the listing of all the default values, people seem to copy those anyway even though we mention that shouldn't do this.
- `fsharp_strict_mode` should still be the last setting.
- Make sure all settings are searchable. Entering `indent_size` in the search bar should lead people to the right section.
- Try to make the page a script file as mentioned above. The examples should be rendered from the actual formatting.

**Comment by nojaf** [comment]
@alanlomeli I think the remaining todo's here are:

- Connect each page with the next and previous links
- Visual Studio page:
    - Update the VS for Mac section
    - Verify if the guidance for both VS and VS for Mac is sufficient.
- Rider page:
    - Repeat the Fantomas info found at https://www.jetbrains.com/rider/whatsnew/#f-support
    - The existing problem of overridden settings in Rider hasn't been reported anywhere, so we don't need to mention it in our docs.
-  VSCode:
    - Mention if works out of the box, similar to VS.
    - Maybe explain how it will detect the Fantomas version. You can find the algorithm in https://github.com/fsprojects/fantomas/blob/30f73bc1c805d0c09e3cb7a268b5f71cb0e7ef38/src/Fantomas.Client/FantomasToolLocator.fs#L173-L195

And the general gist will be: is it clear for people how to get started after all these pages?

**Comment by nojaf** [comment]
Well done @alanlomeli!
