### ISSUE TITLE
Long C#-like arguments list 

### ISSUE THREAD

**Issue by wklm** [fsprojects/fantomas#232]
Hey, many thanks for this awesome fromater. 

The default formatting for function calls with a lot o argumets is something like:

```
let subscribe (client : ClientWebSocket) = 
    client.SendAsync
      (new ArraySegment<byte>(Encoding.UTF8.GetBytes(initMessage)), WebSocketMessageType.Text, true, 
       CancellationToken.None)
````

Wouldn't it be nicer to have something like this?  

```
let subscribe (client : ClientWebSocket) = 
    client.SendAsync
      ( new ArraySegment<byte>(Encoding.UTF8.GetBytes(initMessage))
      , WebSocketMessageType.Text
      , true
      , CancellationToken.None )
```

Cheers,
Wojtek

**Comment by nojaf** [comment]
Hello @wklm, the behaviour of this has been changed.
[Example](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBnArgEa7QBOAloYmABTTrmIB2OaAwg81gOqKEDKsaAGtsASjABeMAB1SMphAj1GLAHT9m8AIK4Ank2hyFSpTSaIA7mG2lSAQz2aA5gFsuAHkJ6siAHw0AKKGCORMzmoAqgAqAGIAHGoA4tgAQj6IuDRh5FgAspm49s6IYmIANGC8AkKi%2BYXFiNF6AA6IatGIAB5YlVik%2BIiVxoqmEGz2hojo6PZY5LBM0bCiTGoAcoulkOXgULjY8%2BG4qGAA2nsQoGNQACRYrchokGFYO5dKkLcAbvbog6cLjcIAAGXbAqAASSYSBY-Ba9mgiHW%2BFc7whABYPhAALofAC%2B4KU1zGXwebVOLxY6NJPz%2BALQQOBAEYiTdIAAFRrccjwLAACxpN2ZACYQdiwHjTISPiTTGTHpTCLBYOghZ86f8nucJRARWzSZpXOQ4OhFtosMF4AB5ABmABkwsgDaZbX8DhKpUoZaY5RrydrIMrVeqIF9flrAbqwABmF2feGIxCpRC22CkRBchzuXykUNKfqDT0Eg1%2BsP3RXPYNq%2BPh%2Bnapk3DHxsOJpEptMZ%2B2wSyIUjQewHaHfIRzBZMfMQQuIYvS0sShUUqsqmsLzUMnUQgCsLagbeTqfTiEiLTa-cHiGHo-mi0nYDd6A9Ny9EB9xLXAaVK-zdcjjOjABsu6QPuHZHhwg64Gwiy4IW0BYOmd4Pk%2BYwvmAb5XB%2BlZQNWP7rg20YAOzAaBh4ZgUrhUHmu7ITOz4lrKWFLjh361vhUYQvEJEIu2ZGINBZoTjR7p0ahDG%2Bkxga4WxEYbo2YwAJzcUm2i2rm0GuK49h3tOs7evO7IVsxQasWuskERCzJgtGIE8QenaIEaJqqrewmPqJphoRhYBlncn7LiGMn1hxLKsjZ%2B6qbmTmmq50a6fRc6MYZ-ksYFZnBf%2Bln6jZ0Kwlg1pLKQeg8gKSEiXpr4GbSKUmWlhnmSFwpxuFdm2LA%2BAwgAItM5DGrmOkDB5SheVV8pGYGrx4Q1mUss2Nl5PYXSQra0T8swgTufw-LpjwvKlbuGLigl%2BlJdV2FUm8QV-puLI7vNi3Qra5BdNaZ5zOmgRdC0Ga4Lg453luR1iYlEnJedk1XXJ0bMkB91dAASogcCkPAPJ8oKB1A554nvmDxkQ%2Bl13yaYzLEXDtgOHo1qkI6sFo-t0aHRV6Gjf64PUpDFkslxcP2mkYTwGEzj0xjjNY8NOOYXjUmmfVGU3cKSnzfg6DzAwFipGaIipA4IjYLgBX8PY7gCaiQnRrRzPeb5i4y3VtLTQrYxisB6xWOrB5YL2zDNG03VPUwuTjtoMIUVRJxuSh2Mg7jZ3GdJhNQxCIphRCIH9Ca%2BQIM6Fvlcdr57DiRIvLgsR-aclv4kAA):

```fsharp
let subscribe (client: ClientWebSocket) =
    client.SendAsync
        (new ArraySegment<byte>(Encoding.UTF8.GetBytes(initMessage)),
         WebSocketMessageType.Text,
         true,
         CancellationToken.None)
```

The commas are not before the arguments if that isn't a problem we can close this issue.

**Comment by nojaf** [comment]
Feel free to re-open if you'd like to further discuss this.
