### ISSUE TITLE
Automate building of selected open source repositories

### ISSUE THREAD

**Issue by danyx23** [fsprojects/fantomas#233]
I think it would be valuable to automate a setup that takes a list of open source F# projects (ideally more complex projects, maybe even the F# compiler itself), downloads each from github, tries to build them and if that worked format everything with fantomas and see if it still builds. This would be a nice guard against regressions.

Has anything like this been done yet?

**Comment by nojaf** [comment]
Infrastructure is now in place to build open source projects.
Thanks to @danyx23 , we have a fake target [TestExternalProjects](https://github.com/fsprojects/fantomas/blob/master/build.fsx#L185) that build projects, formats them and tries to build them again.

This is runnig on the [test-external-projects branch](https://github.com/fsprojects/fantomas/blob/test-external-projects/.travis.yml#L13) on Travis.

The only thing left here is adding some other projects. I open to suggestions. Something with Fable might be a good one.

**Comment by jindraivanek** [comment]
I made my suggestions in form of PR: #338 :)

**Comment by jindraivanek** [comment]
Closing as it is already done.
