### ISSUE TITLE
global namespace should not be escaped

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/fantomas#2366]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwBJWdASyQDoA1AZQGEFFaAxRgC0wCcCAHXTDYBROjABzADawARphm0Acm2GQANOCh5EAF31V0UvKjABtHRFAQ7UACT6AnuPORj%2BrdbuQHANyUAV2Q0K3t7AAZtCN8ydCR0fUYqAC9kGNiwABYfCABdHwBfTJs8xxc3NA8k71i-QJkQ83CsgEZSiMgAWUwADwAZY0QBiSl9bjr2gCZI8sL7Ep9bLqdXUKgJeAB5ADMh9ERGFxkM8obgjdbY6c77SABRBL2Ds6yoGV3IeeLOlfu1lUoPJYLAZFMAY1mmFyhAAMx3OLoPR8fQcYxKFSIADuMmGEIi%2Bj4IR%2Biz%2B50BG0gILBBIgFyaV1hOUR9MYRBIACFELtYHxEAAFfg4AyIPh0uxEkmxBZ2Jb2f6%2BSnuGngxEM6GWZkAVlZUHZxEQ3N5-IGsGxYugmD08X8sCtRkoEogUsQpLl5PqyuqqolGqZ7wAbHrIAauTy%2BYgAKoEcR8K029B2h1UJ163ZKPTuiDyuyK%2Bne4GgtUUqEBrIAdhDYaNEf5zBk1rwrGRUug%2Bj5zrAGZkWZlv2WFMqVN96oClxazIAHNWObWTYhuohsPIxV2e32IrKc57VsOVcW-ePGZP3gBOWeG42R1hydDrzNu-tkwde-c%2Bw9jsun9rRZmhucAEFdn0MVWGwbBMC7V1szAXMyjfdYD1pL8Jxhd42g6f8a2vflGGXKg4DvB9eyfLcBwVIckI-FDSzQrUMNubCgJAsV8OwQiwTTZkYOfD1Xz3aii1or1v3Q9oEWYw1AL4WAggSAARRA8Q40DxT1XjyJfSjEKBGovFQk9xNiNpshDXo%2BjIXYABVuAkHg%2BX0AB1GgJi7OY%2BJ3ASAXfKBPCPMSGPaXV-wsqzbIkB5SIc1EXPgNy9WyDytP4nTBL0-zDM1a4IjaYNQv6eJdioPptjjTAOz4B4%2BgIfk8DwVN7z1bVkvsbc4N3HyhP0gL6Jy%2Bw2irAq%2BgAJUQOA%2BHgOKEuZJLYPgsB8wqbrMrooygpMmdhrGib4BUIIVzFPYyFA7AzD1Np5s6pVfMgbAghkIw8UODg%2BUgwwxWspCsvLEyL3-Ha%2BXgboHqe4ZXr4d61K7GBeD4Yg1IAfWxVzJiu7ybpW2ofp-G4-3eHp%2Bhk%2BHnG2PghjwZzUa7ObPI6jGC1u1bRL65lpiwgmLOJzBSfJqhKf2w6%2BGO07zuZS66YWpa-Fu%2B7HqoZ7EAhqHPu%2BtbsrZpiCe53mKf0EH5cV5WKuhkNoDhhGxWR6n0bSrqMux9XfoiaZJM5-p6EuTljHgYwpGmyY9SnVq7HaqWqIdgyndxl2zOGjh5PbRrvYSP2A5pkOCgovMI6pZnVkC-q7GmEL3b6BTYH0ABxAxqtq-AGsodPmszsAw%2BuxnutHaPjJd-LOdBhXhk5ORoAAa05eHx4MPBtnQRgRVvA6muZDcyLa7OEPSkdPx7jaXaGgmsVxYeDAtCQvvEJTiuoR10EAhIlyFsX3jX22c90neRIL1n3mmLbtZ4ikOgBO6Ak6UBSMAiqQR%2BTWVgPERI%2BgKqNRIpuDe2kP7b2QiWFm60i4QGmP9QBaksBGH8CMSgUgn6rj4NfYwVA74vyyG-SWHdlp6W7rgjW7w4T4yyD0QerwBg4HkPATADZYANRMMfRWqD16h03otXO2Dep4OZHCDm-C65iioLgJISgADSiBEAEAQRIfQ8RJ6YDAYHVej535b3tl-HBP81E8K1vwke1ix6vDwDJOSCQsSU0QMDQeis651UbsiaCxJ5FZwwY4zGHDd5cOdvYOEbtPH8FwogBS-NoB8F0RiUC8AozUEoEpaAjZ4Z3zkQ4pRn8VE417ukuOBNtGFL0UgmQxxZJBEpsSAgxxnCnDqawhm7C86O1STHdJpd%2BFGJMRZQWNC9hePQD44YTCTKRFbu3CZMsu4pNcdwrIcJ%2B78N6YRfWbAxkpRzDofImQPB4A4A1cwb8ihAA)

#### Code

```fsharp
namespace Ionide.VSCode.FSharp

open global.Node

```
            

#### Result

```fsharp
namespace Ionide.VSCode.FSharp

open `global`.Node

```
            
#### Problem description

Fantomas should not change `global`

#### Extra information

- [X] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-07-15T14:30:45Z - 87cd2120c82ce2c83838ee0eaa81f53d03ed33af

```fsharp
    { config with
                MaxIfThenElseShortWidth = 40
                MaxInfixOperatorExpression = 50
                MaxArrayOrListWidth = 40
                MaxDotGetExpressionWidth = 50
                NewlineBetweenTypeDefinitionAndMembers = false }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thanks for reporting this.
It is exactly the kind of feedback I want to address before we can call v5 stable.
This fix will require a change on the compiler side, one I have been postponing for a bit.
Time to finally bite the bullet.

**Comment by nojaf** [comment]
Hello @MangelMaxime, I released this fix in [v5-beta-003](https://www.nuget.org/packages/fantomas/5.0.0-beta-003).

**Comment by MangelMaxime** [comment]
Hello @nojaf,

I confirm that I cannot reproduce it using Ionide repo. Thank you
