### ISSUE TITLE
`begin`/`end` are replaced with parens

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas#2368]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuK9YB0B2EICNEBzAS1wEYxFt5IAacKAZ0QBdWyinUwBtRiKDx5IAElYBPAA7I0kMq3oCRogG4BDADYBXWX2XCADA2HDIASRrVWAZRIAvZCdMQALAbABdZQF9ngjzFJGR55bEV-FQ0dPX4XCHJIswBZdQAPABkyRAzqIlYACyV4sHIAJkMPb2E-ZSFTIOk9SGp4AHkAMyzsRBtJTSdAtS1dHjj4sqSRAFEaTu7BkshNDsgq30j6s3Em0PxYWE1ihuGYsY8IAGYpiAtsFgAnVgAxMi0AOUQAd01s45dWA9dOsapshsFmvtDv8oiNYhcwK4blAbFJ1NBEAAhRAdWAPRAABXUD3UAFs2IgHjDhIDgS5qnhasItioIXsDkcpmJoqM0OMXABWZGQVHorE4vE5WBfSnQdQsSyqWByjiwbDUvC0xAgxlglyNEJyKGcoY8%2BElABswtFGOxuPxAFUpDIHnKFdglSqSGqNRAOloWDqIEy8CzbjtDVBjRruXDziUAOzWtG2iX4gDCmnlTHTaqYtOgrDxvrA-s0gfpGzq4N2Ro5MdOvP0JQAHMmxXbJclEKTCFTkWWK6YGcG9Sc2XXoVzG%2Bb4gBOdup%2B2IXOaH0DgPayug6v6iOQ%2BvTs3x%2BLkYwIkUpxAAQQ6rEpudJpPUJa1QbAIYCe4nUcPprjfIIuQiQXja4rLjYPYkHAa7qhu5ZbsOVbMjWkaQNGR4Ac2p6TKBV63veDyQaS0GHOuCJvtuuq7uOta-lO-5nIBJTkNceFiteDywNoNAACKIL8JGEa%2BQKIcII4fmO2w-mEESMU2-KmOQSIXqkaTmB0AAqBTUDYBR4qwADqJDwIUJaVFRo40dJdGyQ2x7MaeQqqekGnadQ0wIXpBnGaZRTIhaFlITuKHfrZCj2VhinCOQVouep2AdCQaRtC66hFg80xpFI%2BJMEw3pwQiLZBeJyGhqhzQRZhTHYS45BJvFABKiBwA88C%2BWZyKuCVeASZ%2BYBhlA%2B6hFV8mznVbZNS1eLwO82i9pSnTmPepLcMi5Dvv1g0Gs0pLaJoHC-D0zx4s%2B7CUppuzVQpQELhezWtfAyT7Yd2QnQ8Z3CcK0AFMS6KEQA%2Bl8JlmZtUmsuF4SRTV0V4BUwpqZxJISG0DxZPmHX%2BUVPUQH14PhjJo17g5tWmGUIFLIjDzI6j6OsHNC0PEtK1rUBYPWRDaF7QdJBHYg72fRdV1jSeLhlLhSxI%2BoKNoyQ%2BbPTzfMC%2BlX0Xj9f2FpSQMg0U7OhbRaFEycJOwxAZRsZT6QAGpwpiZDwJwmMlsVevlWFhtQ9d41kypltpM8PGFgVds0I7Oslt1rtfgblWeyLjli85fu8bArAAOJsFlOWIHlBVO8iLuWZJHME7ZGHx6TwhlHFlMvbz2SYmu0AANaYiSLdsEwbTYDYZIroc82FSUg5ib1ZXRzZaHl8TUUImUDVLJ8PwN2wMrUJdMj8Ul2AkKq2DXjQ3aM6zJSUcF1H65PB4MTPMNz5Nku-EQ2AB9gQdqnYz-pdo%2BKabAlhIHCOlAqJYR5RwGhVdkN9jazxKGUO6j9CLYGAaoKU2AiBHz7FvMgu8Con3iGAouW1IGThNLfG6JRLjnlrjzBYGQyT4HgOoTMsB8roKXnzUBm5wHbWGqQ6GFD4iXApvESAWdKQkHJEAzQABpRAiApAAOsJYNu6g35Y2Htwoh%2BMhoyWnjAu%2BlCJaiMbmo5uCwmCcW4jQT4%2BZEBPTrnzLOuV8p5hEnSc%2BVlL6c2vmQgxgiXCXAtiY4knZ8S8TltAB4ki3j3ngA6Heap%2BLQCzCSPeXCEI8JIfRPx2wTYIkuL7UR4jolSNYFoPoXFtD5iBFIPoEgBgZKHKVEKbsY4jTjuQ72whLhJ1EXIhRakGZ9k6KY7A5jsj4LqoYHGXhx4QPdr4gR3S8CXBrqIyp0FWDJAQIsAhWjPEfkYJ4Zw8gmDPHyjwMBPggA)

#### Code

```fsharp
do
    begin 1 end
```
            

#### Result

```fsharp
do (1)

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-07-15T14:30:45Z - 87cd2120c82ce2c83838ee0eaa81f53d03ed33af

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
The AST is identical to `do (1)`, so without any additional trivia in the syntax tree, we cannot reconstruct the original result.

**Comment by auduchinok** [comment]
> The AST is identical to do (1)

It looks like that indeed, but there's still a small difference. The only case where `SynExpr.Paren` is produced for something not starting with `(` is [`beginEndExpr`](https://github.com/dotnet/fsharp/blob/a571e6e6e5344cd6524134ea60f4cfa26dad5a49/src/Compiler/pars.fsy#L4446), and as a workaround we could check [`leftParenRange`](https://github.com/dotnet/fsharp/blob/5a5a5f6cd07aa4a8326baa07d4f7af1305ced6f4/src/Compiler/SyntaxTree/SyntaxTree.fs#L446) length to see if it's longer than a paren. I agree, though, that it'd be better to have it properly shown in the tree in the long-term. 🙂

**Comment by auduchinok** [comment]
I've seen `begin`/`end` expressions used for scoping (and using disposables), so here's a bit less minimal case to show the change:

```fsharp
do
    let a = 1
    begin
        use b = f ()
        ()
    end
    let c = 2
    ()
```

Which gets [formatted](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuK9YB0B2EIBtEAXMAQzAF4wBGHPMAI0QHMBLbO%2BvAVwGdFGlMADMwACgCUnLuKm48ibPGlhCJaEIBMKyZAA04KPyJF2zXqjABtQxFAzIAEiIBPAA7I0kdkX228TgBupPjcntb%2B9AAMBjIQkACSSopEAMqsAF7IsXEALJFgALr%2BAL45dgVOrh6W3ti%2B5QGOwaHhNnE0jfSQALKkAB4AMuyIg4rMRAAWfh3UmlEFxfRl-vZcVe7hkIrwAPLCw9iIqa6EM%2BvNIWGW7XGaXQEAokr7h9kF8fjCkIuljWvdZybWoMWCwfDnQEta5oW4yADMD3iSX4ACciAAxdghAByiAA7vgRpCuERUWFfst-pUgTUvKDwST4pdWjcPmBckioKk3KRoIgAEKIYSwVGIAAKpFRpAAtsREKimXgyRSZEs8Ct6ACmtUtgyIQ8glc2uyAKxcyA8vmC4Wi0awfEK6CkfhJQKwZ2mWDYJUQFWISka6kOWl6sEGmnQk0dABsFqt-KFIrFAFU3B5Uc7Xdh3Z7WN7fSIQvxAxBNXhtczdSDw0qjazYeyAOzx3mJ21igDC%2BBdvE73t4KugRFFheExYDar%2Bqxp1fptcNLJhEQ6AA5W9ak3aeogZUxFVzx-gS1OqTOQ3OoPq60vo3EAJwb9vJxD9-AFw8T0tgcsVC-A%2BdGUXKM2VmGJ2UtNtEAAQWEIgFX7GUZVIQt-W-X8wErKBQxrIDI2NUC4moagnxtF9Ul3Vg4HfH1P2PScuHVMtgwuS9IGvYCCMbWZ7gghMYLghUKJlKjwQ-dk0NPINz1YgCrwXfCGxXIjET4qDoNRWBuCUAARRAiRE%2BCDwk8kGPoJifxYwE2J8G8QO4ojOQgvp%2BgSYQABVJkUVJJlFIgAHVWHgKZCwWKTmJk6y5LqBpFOXOEuGoc1nIGNzPMUR56J8vzAuC6YuRjMLGOnLVZ2i2zOKUhL6GoOMUtc7BhFYfpdgzUgR1RR5%2BjcMVeF4fNaPZVcivMkqKzKukoAquK7xkagW3qgAlRA4FReBcpCrlchGvALIwrCNkmmK7K45S5vXJaVtFeAcW4PcFX2BJ4JlCwuWodCrJ1aKZW4fBTCJI4MVFZCTAVdzgUq%2BL2WoR8IOW1b4B6X7-pGIHURBozCxgSYpT5IyAH18SCkKPsir6jumkN7LOrh5gtFyNOlFxdlRYZBw2-Khp2iA9s%2BqtyvqE6qvZTQSPqxnSGZ1nWEHW77tRR7nte6HSdK-8jp%2Bv7WABxA0YxsGIZmwiZE0XiOkgCWpbZogka1nW9fazGLWgHHpWHBVCeJ6ZVfG9Wtkpi5qeqvBNFU82XIANWNAV2HgMwOcLYafb-WSKcFyHZtppzw4GDFtOHAaY6UeOvcLbbk8wib-fTo2HJN5Kc-6HTYCIABxYgup6xA%2BoGhOuST8LLLJ-mjo42uafoTQ6vD5HtZGAV32gABrAU3aX4heF2bBUllV9wTuwaOiPE9irPNXU7DPCqdO4OIE0BbzbxQl5%2BIR1FHBjw9Ka7BWC9bBoKUDueWysOiSVPtJc%2BUVR4KWvsLDomgLrm2gkSZg2A87YALt6dIqD2rcDFO5WASQkD1HagNMcX5B77SrrhCMsCobwNhkgv6CpsCkMCPabAzAgH7i-uwX%2BA0QFxGPmZXaY0U5QMvrQwON92TwnAjPLWbxBiygYPAUg3ZYD9U4U-HW5D6IVwOjhQCUioQyI6PCMW5tO4KlYHKEh%2BAADSiBEBuCISkJIq9SAYM5kfCh4CIqQPJpIoW9C4jwjNnESAC8vFLzeLwDSWklB4kHIgRGs8dad16v1AcqFTIGOocYkJmd6DwjDpEgUUotxih0jLaAqJbHYngvAFMP9vR6WgD2aUf89En1GmfX2F8aFFONlweE2dInWPqXYogIQTiaT4CqNwJwXBnDor00R-TxFBNqAHUxcCwkN0iU4lxLk5b7n2NE7AsSRiCLmlEbmRQxGVz9kMjOIySnT0iXMqiNsEDvF8foyhhhCg5G8LwDE-VLDCJACUIAA) to:

```fsharp
do
    let a = 1

    (use b = f ()
     ())

    let c = 2
    ()
```
