### ISSUE TITLE
Idempotency problem when using object expression and having a space between get / set lines

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/fantomas#2372]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKwwDtEHcwBUBDAZwGsARRAMwEtMaAXG2TMHRgCwB1WIwBbRPwBGiAE5gGHGsQB0ASQZCefVW05gA5ogZgAFJkKC0xBmLqaAlGljCAVmFgAHJizABeMPEINCs-GIAngDiOlhGiCpqEFHRhJjwYMRhBhEmZhaW%2BgBuNvaOLsyY1mAArvS67rHRfPw%2B0Bxg2epS1TVgAD5gAHIsiGAAtAB8Xj5%2BAEpCsNmIqYJZHSM0mpiwYpG87RBdAMqwgk2DI96%2BsgDahoIAumAAPANNPNXT4uZIktJyAAZfDIFOiB%2B6XMmE0HjAXEgVEIpHE5UhYAAvjxIAAacBQZIMJig4ioMBnDEQUDRSAAEj%2BAPxkDoDDRRL45OyhAANqVkGhCe0AAzo9qQeQJRCYBg7GgAL2QfJqABYGRArgzEdLifKoBT-hyoLT6aSycy2VquTUAIwqtSQACyhAAHgAZOiIO3CzRSXWmgBM3LVitUyoZJItGqpaEgwvgAHkqA7sDs-iypWqmaz2fjjdEPebVJAAKIJKMxxP8llUSA%2BpXmwPZ4NayDCWCwFnu6sG1OctUQADMWcZguSYgYADE6KzurgWY7m2ozOzy37K0ma9T642pxBk4a0x2wDKe%2Budk5CNBEAAhahrRAABUIYgiSjEa74M8Qc74-tUVcZS9DK6bPY3bYEtuACse5QAeR6nue6x2rAODiNAJCIIK2SwIhriYI%2BEDPq%2BEDvnwn7rt%2BUC-o%2BAFGtuABsYGQBBx5nlQF4AKpOACYiIckKFoT4RRYWA0IsskuFIgueqUrWpH-vqKYUe0ADsNF0VBjHrAAwiyJDEKpLCmGIpTQAwax8QJQnRL6b6iUG4nLg2f6Lq2sk1AAHIph70dBiCWkIogPmBJkvmZFYBou1k-rZZHSZu7btAAnK5kEMRe2ksiwxmsqZajmXhlnVqFJHhVJDlbu0Jq8tutFuYgACCVD3tp-B1HxOGBfOwViZqNmroVMnFaaZrlUpiXrDsQg0HAKWYX56UBZlQUfiFHVhV19k9dFnrxceNX3iN-BjY2qVgc1s2tfN7Uhvly16kVa3RCa3YDZVVViLA5TwJQE67feTV6TNqhZSJbVWYt2oihF11ASVu7ldaNryFQ%2BAcMKOwcGsDAAOo0PAbpgd6LUWYDuXAzSoPdVFEOmqB0O2nDCPCjmgmIMjqMY1jHB8ZRuPHfjp1A%2BdxN0qTgHpmoJrUVTsOYLQNoRmxPhrDmNpOOsxDELxYFOZzf1zQRC18zqguObdCni5McBiPALPY9uMqa3w-34aqZ21vrK1k8Lqgmi5JuIGb8DdKUIjiFGihCHiYEmsJDtgIR6p5ZA-ClCyTATtgg5rHU2LiPgHUG71t1xeVptrPAlqJ8njpp2IGdfTRDQ3ke94APrsKzZZ49lBNfnHLtXat5MZmV-Iw09t6BBGYgOqYlts%2BrtsKtrju887JOu0L24ev1Q%2B2iPhBjxPMgMP7gdiMHSj8GH24R%2B3AM84TfMJ0nNAp4glfV1nOer4bagepm5U73vk8GCl0fs-V%2BPga7lTrreAy4hm6YzdJHHKXciY9yDODd2fAPT3S3jaAAajJE8dB4AWGnnxDWiDO5EW7ivXubt15QxwYOcoBkiiEISCQ%2BBM9rZzzAPbJBVCUE0LQX3DBEAPSUxweQWADBQgMAVkrRAKsiikNnhQ2%2ByC%2BaSU-nnb%2BYsh5lyfo6E8KVoCkBPNA2EDBiARkwDsCIyUA6TW3P5NROsnadTsrQte7QPTG35GOHAz8zwMHgsKbOAJKC0AqEUKqCQvLHwvu0I6WsTpuKXh4sGIj15e35FVCcKwmGYBYSwMUKwfClHWPgWAgokAih4gdZx01XGLzvhJAq2ibrfwLrkpO4hDBMBmLBUE8SfKRLoIwIoiSaguOvlHGO5I45aK8V-VQnZB41CtAYwsdojDCG8OpWAqtQQBOfmlBmzTo66zaZdYRdD2idk3hs%2BR4gaCCDqSyAA0ogRATganCgYIKcx8QGhnIyik7maTWkZNzp01Zv9%2BTGPiKQQsxAnovQSGOUwiAS4GOfvI5WqsdLfVnLM-hsciZLNud4monZsEbJPDeIaiByAyGgOYXa-TsVMXoCwSg0ANK3gwqC36dsF6XPcUtTxVKVl8E7Awp5isXlvN8CyOMz1Si6VKE4OMgQEzCoufM4i-NMl3JpRIjZXyfkwyPj5KMiLMDIsdFM263IeF8MoeSzR7Tlk6NWXojZaqxpAIQEWaZTTZkYiuNKGkxBByq3xC4xEQA)

#### Formatted code

```fsharp
{ new TaskDefinition with
    member this.Item
        with get (name: string): obj option = data.TryGet name


        and set (name: string) (v: obj option): unit =
            match v with
            | None -> data.Remove(name) |> ignore
            | Some v -> data.[name] <- v

    override this.``type``: string = "fakerun" }

```
            

#### Reformatted code

```fsharp
{ new TaskDefinition with
    member this.Item
        with get (name: string): obj option = data.TryGet name



        and set (name: string) (v: obj option): unit =
            match v with
            | None -> data.Remove(name) |> ignore
            | Some v -> data.[name] <- v

    override this.``type``: string = "fakerun" }

```
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result.

#### Note

If there is no spaces between these two lines:

```fs
        with get (name: string): obj option = data.TryGet name
        and set (name: string) (v: obj option): unit =
```

then the format is not generating a new line on each pass.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-07-18T06:16:36Z - 452064c6e05acd2eaa71520ea006c45cc0455783

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Thanks for the report Maxime, I'll release another beta once I can deal with the `global` issue.
