### ISSUE TITLE
MultiLineLambdaClosingNewline + ExperimentalStroustrupStyle is not displaying very well for some use cases

### ISSUE THREAD

**Issue by albertwoo** [fsprojects/fantomas#2378]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBZArvAQpgLvrAHYDkAFAJRjAA6ATrcRBAM74CeANojWPAEtWABy4BDDgEliXAcUQ4usaAGswAXwZMWYACJCxAIx7wwQgDKwxg4gHMtzFgHliAYVmryAM0zMA%2BmAAtAB8YPhirGp0jI46bIj4kqyW1nK2YfSYiA5xLPCwAIRgABawsCoAdLqwAO4yVvAAKvRixKxi0PgCJABKiMKw9PisVDm5YKwJSSk26V5iXJNjEOqUy2YAjAAcxBX4Lcy0kK6wALanJBU4%2BMTVdUrWRw6aMZAANOBQk4RprKhgAG1PhBQLlIAASTjCZBoSByfDvYEsCEANwWWX%2BQPGYAADB9sZBpEhiPgAMoCABeyHx4wALEiIABdJHqGkghlQSEcaH-OEkxFg8ForgYtBY8YbNlxSDoMQAD3MckQ5kQdnwxQFEoATDiOcydKykaDpVyebDVfAnF5FfJSZweJqdKj0TDARyIFqpU6AKLES3WpWO6VcLyQPUsqXGp2m12QQxlLhBiDOkWu8W5ADMXuR0kmQwAYnIFgA5RA1WTyJMsfZZcMGyMciFQ2Px2CJ7Mp0Vu7G07PJ0nCDoKRBeQaIAAKYhapwSiHoVYgNcQdZYhp0UeRMd5rfbjaFLsx7rAAFY%2B1AB0OcCOx5YanPoBFENIUcoxF0SAuMrXcvrVw3Bc224JlWnZpkeABsZ6QBe0DDqO9CIAAqsI0L0A%2BkzPq%2B77EJ%2B8yLMuP4Rkae6AbCO4gfuqaHtiADsUEwXBY7uBErAnG0NadIMuELJMK4rP%2BJqkVA5EdpRXbpnEWz0YOsFXvBiDoIgpyGHO3H4XxGgCdGQlxsBonCuJR4AJzSZe14IScSg4WeeG8YR9bEQB3Itnpe4GWB2IbHiR7QTJiAAIJePgc4nOcYifkuGlriwG7JluZGuYK7nURKko%2BQxcljqSSkCHAVlqXZcS-vxjmCc5QFthRyVikeGyeulfmBcF9DZacuVth%2BZ6RfZf6ldp5UJZV%2BkHjVnlZg1Q7%2BfQsC%2BPAuiILIbXNRFmQEUVRHriRA1QPCVUjd2Eq9j5spypIXiNMUqqkqUQwAOoCPA6qfrqPUlZtTlmjt-LDVRo0Sqex3ymdF2qt6%2BHXYM%2BD3Y9GpnuBL3rQ571lZ9fIIj9hmeZBgOncQXgCHKTioW%2BgzenKwgIawrDdNZR5bAjOjFZpfWbjpu0Yx5Ep0TjfRwPQ8DQ09Z60gzLBM9F7IfbG7NuftEk6NsUEnbzgzwMWmDKXOVqSMFpx-GeGxRVprPbZApyYFwXQVog%2BaDKcb7NY05UcyluQbCZPkq-zWCWwI1u2-Q9uEKpUHQMUU4dM1fg1A9T1GyzcVs99su-QduQ6kr8pTS0HBOPQirsILsN06LTIbTFW2ozLSVy0eWppQSJ3ZxIecF-g6ua-Q2u6-rtXx8j-Wo%2Bbvv%2B3bDtzk7PIu396f1QSze5-nQj4D7VtKgHQfLaH4ctJ0c7R7HGr9xXUu8tXJrVWncRauNjfygAai6OByLMRefvTx%2BSyj0vJzXqfyywLUR075ynzL4ToNNn5%2BjSG-YWpcwDi2NonU259oyXwAR6AGIDqj4AAOIJDJhTRAVMaawJLp-GglcXJDRTpjcYWpsaNwtmveQihlAqBwLvFQCRWAuFJGIGclkNa02xLZNajNy5f0HtQ3cf86Hp25gSUs5YlRXnwHeVUk9EDzXxsQAQ2F-J%2BkUp3Xu2JuqI16gPE2qMRK0M5unKSPl-KyFsMQMBxAIEkHJK4t8mAEKNFgESVU4RsIFXEWLSRlDT6DVkRfWu2ItQe3npbOcxA3wCBRMqEgthjEqXoDouQ%2BiaamPGGIihsVOQ6VsXI%2BxcQMzeSYb7G0yoBGGHgGIdwsBqZ2GUdbFa34LFvRPt-CqsS0HxPGBmBu4xICELnAIGcJIFgAGlED9CCSSaQnDWhhzCeUqhoy9r-yPBmOeMzFCtBUM01gU0Zp%2BlLOwRA8BV5%2ByVIQym1MSAlNyGU16zMrHIJsYlOJxzsQZlvucqcmUEL6FYNAegCyizBXgIhPRJB5rQHEC0UJNkeLhLLkjYZ0jDnTyvjoDMwCZlzIRYs8IXA7TTUwOwTIwg7TcGpEecxEjCVSOsT-dGdjXZ1KwTM1Z-QTodzyVaC5xArlKm%2BXELy8DEEJ0qabapIL5F1MYTMhluUV4IA5aIvFUVPiMhpHCVg%2BZqb-DKeoIAA)

#### Code

```fsharp
MudButton'() {
    style { displayInlineBlock }
    Disabled isLoading
    OnClick(fun _ -> task {
        setIsLoading true
        do! hook.DownloadTransactionReports()
        setIsLoading false
    })
    i18n.tran "Common.BtnDownload"
}

```
            

#### Result

```fsharp
MudButton'() {
    style { displayInlineBlock }
    Disabled isLoading
    OnClick(fun _ -> task {
        setIsLoading true
        do! hook.DownloadTransactionReports()
        setIsLoading false
    }
    )
    i18n.tran "Common.BtnDownload"
}

```
       

#### Expected

Can we put 
```
}
)
```
into one line ?
     
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-07-19T14:35:52Z - 0fe6785076e045f28e4c88e6a57dd09b649ce671

```fsharp
    { config with
                MultiLineLambdaClosingNewline = true
                BlankLinesAroundNestedMultilineExpressions = false
                ExperimentalStroustrupStyle = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, on paper this sounds reasonable.

However, a lot will depend on the implementation. I would accept a PR if it can be solved in an elegant way. If there is too much church to get this right, this would be an acceptable limitation.

Are you interested in submitting a proposal PR?

**Comment by albertwoo** [comment]
Sorry, it maybe too complex to me.
