### ISSUE TITLE
Paket fails to add dotnet cli tool.

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/fantomas#238]
Paket dependencies contains: `clitool dotnet-fantomas 2.7.1`
Paket references contains: `dotnet-fantomas`

I get the following error:

`You can't use paket.references as a content file in the root of a project. Please take a look at C:\Users\Isaac\.nuget\packages\fantomas\2.7.1\content\paket.references`

cc: @forki

**Comment by nojaf** [comment]
Hmm, I actually tried that myself and had the same error.
Although running the command did work for me.
Did you try `dotnet fantomas`? What version of dotnet cli are you using?

**Comment by isaacabraham** [comment]
Yes, it does work, although Paket seemed to hang during the install process.

**Comment by nojaf** [comment]
So I guess [this](https://github.com/dungpa/fantomas/blob/master/src/Fantomas/Fantomas.fsproj#L8) is the problem but why exactly?

**Comment by nojaf** [comment]
@isaacabraham should be fixed in 2.8. Please close if no longer an issue.

**Comment by jpierson** [comment]
@nojaf, where's 2.8? I don't see it here: https://www.nuget.org/packages/FantomasCLI/

**Comment by nojaf** [comment]
Try https://www.nuget.org/packages/dotnet-fantomas/ of the global tool https://www.nuget.org/packages/fantomas-tool/
