### ISSUE TITLE
Fantomas moves comma and breaks code

### ISSUE THREAD

**Issue by dbrattli** [fsprojects/fantomas#2381]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXM0sGcwBeMAO0QHcwBhAQ1OkXXVqwEtZSAVWAa0VIBlWAFcATowAUASgA6Y2aXmLMOALYAjYstIQIAWVpt0G2AA8ACmNiN8%2BWGIB0grLTFZJOvd7AAzEbpspKZmYAC0AHxePjGqYGKI0GBqiHa0AOaIADKwsAAOYAD6xGC0%2BACeDGDA8djipACEyan4Gdm5BTJgAL460THeKWmZOflgMv0%2BADS4BI48-EoKunrSkFPgUPjY7KTp%2BKhgANqbEKAxkAAkWOV5yGiQQVjrp3pXAG606CL3x6-eAAYNgMoABJUhIUhYQRsABeyGBAwALP8wABdV7dRFnVFXG53Q6PKEvC6XT7fX4nEEARmxPkghjMWSC2QE6SwAAsSQNqQAmAGojHeLGvc70663X6QATwADyvmZ5Bc5Uw3O8Hy%2BP0OVIGvLp6oAohD5YqEaiIJB0L5IILMXSxeqJQSHqZYOg1W8yZrKeawABmfVvcHbdwAMSCXwAcpR0CyPd4sGIfrbhfbcU6pa73YGNRTtb6kYGLYI8rRGAAhRC%2BByICxuWgpLCIMTxvSJ5MxIV6EXeB2e-GZ3LZ9PkrVoHUxACsRagJbLiEr1YSOQozegZUQ4PeNlYHFIrYg7cQKe7adJA8JWdbubHfxBADYZ5A5xWqzWAKp5O4SDdbnfsTgDz8L5thPCAez0PsLQzS8h2vL083HX0AHYnxfBc3wSagWDsahOHwds8AcIDfBA49OztUV0wvF04JzBDbwnHwAA40NLV8l0QfREE0ZsSLIsCejPcUaKgK96NHH0QQATjY%2BdFxrPD0EAmdSPQUCKNTKjz0lWC3XgyT8xpIFfWfdjEAAQV8JsxDwtQ1FoICj0EiCcR050xLokdvSMnlaVM9CFISQQeLYOBlP3VSBM009tJE3TaP0iSfKQmk9QC8yrJskK1DCt0VN9ZyYvA4THVEyBxO8xC7x5AMMvnCzrACeAABEmDYXKbKcpNyJ8LsSrisqEqgJ4DJSmqYmpQtTMZUFfC4DkBEEDkHCwAB1Nh4E5ICBWKoTBv7YaiWeZLqqY7xqWnGbaDMOaFoEA11MQZbVo2rauRne9dr6yje2oo7RtOxjfWpR9rtu0hfDYMxZW-VgHANMw8gSOw9yA5jvu8fr9r%2B9ypUBqrgZpVDwYAJUSBx4De7aZyRTG9Gx1zqn%2BjzjrGs6QdYsmKbEeBIxEXixHlUEmzUA4Z2pFzSsO1m1BEdB2FjchQwcBysBsrhdKBqSeVk0zybgXn9HlxWWRVsQ1a6p9oA5es8GbQoKE27apYO6DyoJ0lDNS3UTJBBkbsasRaHKWUxGZAjqY%2B30Mdd3H4tZz3xW9iafF5fz-cZIOQ7DiOsH5wXhdF8WQbjyCWalOWFeMM3VdYDWtcJnWYl5dL-ez0Pw7YAjjerpXEHNy2%2BOt23g-tsRHedrky7chP8eJbXfJburM5ugA1b1yyCeAgnSKP0fpiBGel92AYXpul7T6bV7MUMAjwPct4hXf99pw-0V%2B8u8cJJPHRT869C8iujfFqsAsAAHFsCI2Ri0Pcr8Y7v2Pm7KAMFErDi9uNABEBeRg0zibGu5ByzKWgLwcsY9%2BAEFlEIBsiAlIC0ir6NSGkfpaXjkNVmlUMEcxBLyEm-towUH7pWLAq4BCazuG1KGpA2AAVIBZCE3FBYlxBEVFhsU2Ey0HElC%2BPsW5c3brGdIpA74MFkTCIxrBxCIB4OCSErhZH8SejPZm380HsyJrqPWBibKkF3O8doexFEaGbJIoIMi9zKIGEw3qWNP6z3YVo9BydMG%2Bj9H7AYDJ8GmiyA2DQ8BaDYVgPgXeAj%2B6OOYbE1hX8556SSX-FJII-QZwydA5sHUBCuHQAAaUQIgPItiOngjIfQG25SYkMziS4mpbjF66J8H6NuGSiH0F4KafAjVRAQmjARRA8Be6m3INAlGxT8LdQ7GogaGjT4cK8lwjxMQ-QryWW4IKiAWrd2gGIDqEYmzwHfNIzgbVoAsGDg4qKTi9pMygig8qnDkncIGH6a%2BLSkZtJSFCL4LgmoESTHkZUqpwUVImVU%2BJmif7nzuc3eZwCMk9L6YyAuwSha%2BGWaQVZLJImTQBIgyZ0K8RHThfUhFDzcEZKxWFLA%2BgEBmhBNElymw0SIkePgUMxTDhyu6EAA)

#### Code

```fsharp
let cts = new CancellationTokenSource()

let mb =
    MailboxProcessor.Start(
        fun inbox ->
            let rec messageLoop _ = async { return! messageLoop () }

            messageLoop ()
        , cts.Token
    )
```
            

#### Result

```fsharp
let cts = new CancellationTokenSource()

let mb =
    MailboxProcessor.Start(
        fun inbox ->
            let rec messageLoop _ = async { return! messageLoop () }

            messageLoop (),
        cts.Token
    )

```
            
#### Problem description

Fantomas moves comma up to previous line and breaks the code. It would have worked if the lambda was inside parenthesis, but in this example we cannot move it. The error I get is:

```txt
 This expression was expected to have type  'Async<unit>'  but here has type 'Async<'a> * CancellationToken'
```
#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-07-25T10:40:05Z - 59293a12e0bc40fd257f4823cfdcfcfee8528c20

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.
The same fix for https://github.com/fsprojects/fantomas/issues/1319 could probably be applied here.

You would need to extract the `longExpression` function from
https://github.com/fsprojects/fantomas/blob/724087e0ffe09c6e1db040fe81b9986d90be8cc6/src/Fantomas.Core/CodePrinter.fs#L873-L905

Into something like `and genTupleMultiline astContext ts = ...`

And then call it

https://github.com/fsprojects/fantomas/blob/724087e0ffe09c6e1db040fe81b9986d90be8cc6/src/Fantomas.Core/CodePrinter.fs#L2379-L2382

instead of `(col (sepCommaFixed +> sepNln) args (genExpr astContext))`.

Are you interested in submitting a PR for this?

**Comment by dbrattli** [comment]
@nojaf Sorry do not have time for this right now
