### ISSUE TITLE
Question regarding FSharp.Compiler.Text.ISourceText type conflict

### ISSUE THREAD

**Issue by greg-420** [fsprojects/fantomas#2388]
I am trying to use the parseFile function from Fantomas.FCS:

```
open FSharp.Compiler.Text
open Fantomas.FCS.Parse
// ... 
let ast, errors = parseFile false (FSharp.Compiler.Text.SourceText.ofString "let mutable x = 3") []
```

and opened both FSharp.Compiler.Text (from FSharp.Compiler.Service 41.0.5) and Fantomas.FCS.Parse (Fantomas.FCS 5.0.0-beta-003). However, using the parseFile function then results in an error: 
```
error FS0001: The type 'FSharp.Compiler.Text.ISourceText (FSharp.Compiler.Service, Version=41.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d5
0a3a)' is not compatible with the type 'FSharp.Compiler.Text.ISourceText (Fantomas.FCS, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null)
```

I atttempted to resolve it by using FSharp.Compiler files directly from fantomas [https://github.com/fsprojects/fantomas/blob/master/paket.dependencies](url) but this seemed messy and did not work either. Any suggestions?

**Comment by nojaf** [comment]
Hello, `Fantomas.FCS` is not compatible with `FSharp.Compiler.Service` and mixing them is a bad idea.
`Fantomas.FCS` does expose a couple of the same API's from the regular FCS (with the exact same namespaces).

What you are probably after is something like this:

```fsharp
#r "nuget: Fantomas.FCS, 5.0.0-beta-003"

open Fantomas.FCS.Parse

let ast, _ = parseFile false (FSharp.Compiler.Text.SourceText.ofString "a") []
```

Note that the AST you get is not compatible `FSharp.Compiler.Service`, though it is mostly identical in every way. `Fantomas.FCS` is closer to the main branch on `dotnet/fsharp` than what is on NuGet.

**Comment by greg-420** [comment]
Removing `FSharp.Compiler.Service` did fix that issue. However, I am not sure which parts of it are exposed: for example, the types `FSharp.Compiler.Syntax.SynAttributeList` and `FSharp.Compiler.Syntax.SynAttribute` both result in 
``` error FS0039: The constructor, module or namespace 'Compiler' is not defined.``` despite opening `FSharp.Compiler.Syntax`.

I need those types in order to traverse the AST produced by parseFile to count the occurrence of certain keywords. Is it possible to do this? By the way, what are the 'defines' (third argument of parseFile)?

**Comment by nojaf** [comment]
Are you sure about that?

```fsharp
#r "nuget: Fantomas.FCS, 5.0.0-beta-003"

open FSharp.Compiler.Text
open FSharp.Compiler.Syntax

let x : SynAttributeList= { Attributes = []; Range = Range.Zero }
```

This works for me in `dotnet fsi`.

Our documentation is a work in progress, but https://fsprojects.github.io/fantomas/reference/ can give you a glimpse of what is exposed.

> I need those types in order to traverse the AST produced by parseFile to count the occurrence of certain keywords. Is it possible to do this?

Probably yes, what exactly do you mean by keywords.
```fsharp
type MyRecord =
   { X : int
     Y : string }
```

are you looking for `type` or for `X`?

Both are possible, of course, this begs the question of whether you really want to use `Fantomas.FCS` or should stick with the official FCS on NuGet ([example](https://fsharp.github.io/fsharp-compiler-docs/fcs/untypedtree.html)). Both options will work, however, `Fantomas.FCS` doesn't appear to have an edge over using the official in this scenario.

> By the way, what are the 'defines' (third argument of parseFile)?

If you have code like:
```fsharp
let a =
    #if DEBUG
    0
    #else
    1
    #endif
```

Depending on `defines` you will get a different AST tree. ([`[]`](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQ2wAuYVYALwAdAE7DkECAGJE8MABEAogCEAqgHExEqWAAM2yVOmw6sQ7oCMF47GTQ5kEAF8gA) versus [`[ "DEBUG" ]`](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFAIgUQCEBVAcUgBpwpE0AxNRLMeAQwBs1ZKJIBjAezhNIbWABcwLMAF4AOgCdZyCBADEieGHzESCpSrAAGPcpWrYHWCYMBGa2djJoGyCAC%2BQA), notice the difference in `Const (Int32`)

**Comment by greg-420** [comment]
It works indeed. I believe I confused unions and records and attempted to pattern match on `FSharp.Compiler.Syntax.SynAttributeList`. To clarify the keywords, I am investigating when 'mutable' and 'do' occur in F# code. Of course, your reply contains plenty of resources.
