### ISSUE TITLE
Incorrect indentation after interface member with anonymous record as generic type

### ISSUE THREAD

**Issue by theimowski** [fsprojects/fantomas#2396]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6dYAuBnATAGYCGARgDaJgAMAdABy3UA6AdgLYICulYATomhgAGtkR92bNtgCeAByoBtADwBBcuVgB3AHI9yAGQCWYvsXIA%2BALpgAKuPZHW5sAF42ECGVzYz0bGCwrADSiDJoAJIAogBuiKzYysAAPmAA1mFoPnxOAOYA3GDwsOyx8dhooTKksMR88GUJYMkAvhZgWiYAFmC5iNgANGC4-R6e3r7E-oGsxqyIAGKIiPCRjYlcrCbtndg9fYPDo6yQA%2BBQI9jYebioYIrnEKCenpAAJLIKd5BO2KePrzeMXMXGQaAeLxe1DOkNeEVYSASAGUjAAvZAw2FgAAsAIgVgBLUxTzxUA%2B8jBUF%2B-1h72B5FBdwhWIAjMTIZAALLEAAec0QBniuT2NNZ%2BGopIJLyJAOeHPJXzQkHi8AA8oR%2BUjZJRRS86SDKczYfh2Xqogj1fzdRzyIRIJLCey5XqFZTIDVYORrRB9QzDaSIABmU1w1gjPjYBZOcw6RBachODEBnB8UEO6VO0nvT5uj1ekO%2Bxng5PYkM%2BpFyKaIABCiEIsAEAAU6sR2P1xN7PL407CpZ4ZS9nYCc98853C-6sWAAKxlqAVqu1%2BsCAzacTQYgjeExWAb65BTsQbuIdP9zO012j2Ce8dAg1M5MANjnkAX0BrdYbiAAqnIFHwNy3Vgdz3IwDznEhyBGU8IAHTwhx9S8lTHAs7z9B8pwAdhfN8P2XRAAGFyE3XACKCbIuH8BtDzASDoN7R1ZSzJCoBQ5j6SLe5k3oHDK3fJcv05RB2FIDsIPMejIT7WDz3lEdkOvfN2PvYspwATl4xdPwEMjNBOcSoJPBiMyYi95NYxTbw4ydWWhZNXz4xBVEIUwyPYdhiBo48YLAOCSTMikrxvVDrIw1k2Xs3CBIEJFhKMOA9JouijKkxjB2Y8z3UskKVK4qcWRNSLHOc0xYscBLwOTbzjLPUy5MChTguU9DVNZYMiqrVQ%2BFgTZ4AAEUQBNHFMLzUxSl5pN82SXUy6kcpavLWVLezuR5CJCFsLp4iRLoG2wAB1Ix4BFOcJRqmS6pmhqqQSKzcqNSEWVnFbeXWzb4iiQydr2w7jq6GjHzO1KTPSgLFRuv55s4h6XhZZ8XrW1hCCMHlVX-YhsAbKIeTkARcFwMD9O4oGJrS%2BCMuun5bqhmzYRZbCEYAJUEBt4F%2Bk6SxJzxJr8sAELJWbqea6HkxZHimZZ%2Bo9BE8R1QiMR2FuOcWR83n%2BezSn2B4a4E3mBYGw8q5xFsQKabCumNPs5m4HqTltaMXXFgNjGRpfaAuhbfxxAAfU6P77XOqbLuHSm5uF2nIXFF9Vq6swZFVPhjB8dn-rnegufxMn-Pq8Gqch8PzcjiKpy5XlY%2BIePE6MHxpdEvg5YVpXRdV6aQ9zrXyB1xN9YkF3jdNgvWuNQqS-Lyuk%2BwO3O4d7vnaNvgaJgD2-FMX2jpFFvg8QwX84vUKh8j9qS9WgA1A1qyceA8hTmj0830Gc7dMO9-u5N8GW4-eQWTZ-EJi%2BEWvuvVOnN77kzBk-IWL8Fow08PgZ6n8eR9VgNgAA4v0bGuNED40JjfNOGcwA81btvSmbEoEiynPgeGx97aO2rJoaAaRqx%2BAyHgVUrAkStkIp6Lg7AiZTmSqA7OV1c6kPlPvRaxoGYl1jPGRMtZsBaGWKwE2CgBrIy2PuVgqgERCRlnwJuU5qrA1qg-YRuZsqDwkZHcWo8Ey5FYN-Vgv8ggonsRjLgAhbCwHhIibAGNCZJQkuNbmWc%2BYUxERYshEcXj4EtrY0wzhrhxFXKwXIui65qKcCYQmBisQCMDmrcJ5impRMLi8QMdlqHT35AYVspB4DECIrAAmqSZGO0CYZQRYTwFBSUqUg%2B5Ti5YkgBg8QRg2wJHMKERAcgfHlHhEw4gTjgH8KCV09WLEsolLEa-KcgYR7DLoUstI-JcBdR6giWMPgVhTy7vMDBeMCbkVGj2YxF1TFt2KX0nZ0DkyBiPocuo0VEB9WrtAHIjhEkrG-FsIIA1oDETMJojpklSYgzAY-Xpd1fl7I-sM0ZELyjmC1N1LgFE5BahkDqAyqKQnoqEZ874z8fnkKxIGeBwzplyFWrXWWhAjmsBOYmXJdNqD4MIVvAWJDIksuiZ4QMVDhkkvipPBASZVmdIKecKwmIfi4AWATO4AiWhAA)

#### Code

```fsharp
// ts2fable 0.8.0
module rec Xterm

type [<AllowNullLiteral>] Terminal =
    abstract onKey: IEvent<{| key: string; domEvent: KeyboardEvent |}> with get, set
    abstract onLineFeed: IEvent<unit> with get, set

```
            

#### Result

```fsharp
// ts2fable 0.8.0
module rec Xterm

[<AllowNullLiteral>]
type Terminal =
    abstract onKey:
        IEvent<{| key: string
                  domEvent: KeyboardEvent |}> with get, set

abstract onLineFeed: IEvent<unit> with get, set

```

+ following error:

```
(10,0) (10, 8)Error
Unexpected keyword 'abstract' in definition. Expected incomplete structured construct at or before this point or other token.
```
            
#### Problem description

Generated Fable bindings for https://xtermjs.org/ using https://fable.io/ts2fable/ and Fantomas generates invalid F# code when formatting the bindings

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-08-01T12:33:32Z - e2eda798e15b9bf36fc2bbfc809c87fe23681fcc

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Siema!

I believe this issue can be resolved by changing `0` to `1` in:
https://github.com/fsprojects/fantomas/blob/3706d26e3ee70223d53b898e5eef3af13a96dfc1/src/Fantomas.Core/CodePrinter.fs#L4031

This will avoid the additional unindent.

Are you interested in submitting a PR for this?

**Comment by theimowski** [comment]
Siema :)

Sounds like a serious change - challenge accepted! (will take the credits)

I'll see if I can submit a PR with a test tomorrow 🤞

**Comment by nojaf** [comment]
Thanks, you can add the test to `ClassTests`.
Please checkout [the guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#guidelines) as well.
Good luck!
