### ISSUE TITLE
Unexpected concatenation of docstring lines after `private` modifier on DU

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#2401]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAYrLGALwA6AdhBNgE4CWAbgIbqKXVgD0PBRH1HlzAAhZrQEQAPmAAqAC3oUA5pAA04KAGdE6dEuVbUYANqaIoThEgASLLmOQl6deeq2WAGwCuyNGatqAAYNQOsASQokCnQAZXoAL2RQsIAWNwgAXTcAXxSLDKg7HD8oZ1dAj2YfUoCwgEZ8q0gAWWYADwAZJUROxBV0eQqGgCYgwuzOPLdLZuKHNEh%2B%2BAB5ADNuikRYrE9kwqqa4zrAkabOSABRKPXN-bCoTzXICdym2Yv50sgAIyJPYafLy%2BY6FCAAZnO7kiOlo6HwSmqADlEAB3Tw9QFWdC0XyvKbvA5fRx-WAAqGHEH%2BMFgVJQ6yxbDMaCIESINawWiIAAK4mYAFtdIhaFjODi8YFJtRppwPu5iYtSeSicDajSAKz0qCM5ms9mc3qwVHC6DMHSRRiwU36WAUUXUcWIfHSwmVBVQJX2ylqh4ANi1kB1LLZHK5AFVsLhaKbzRRLdb6Lb7RA1tUdM6IDLqHLrO7fv8vTZVaCHgB2ANBvWhxAAYU8Zq0NdtWnF0HQnOTYFTnnTkreMyJ9m%2BnopReqVNMNIAHBWmcH9VyWoh%2BT9hZ3u72rFLM665kOSQXR8XqQ8AJyz3Uhg1NzxJrUbp19gkDt37xWHlXjn0NEI0wNzxAAEE1jYWgm35flmE7R0MzALMClfEoDzJQtj0nB56kaP9KyvLlYmXeg4FvO17zTR8t37WVByQ98UKPL8S1GC8WWA0D8P5QiyTvGkYKfF0Xz3GiPQ-N00JOKx6khbCAMA2hYG8KIABFEAxDjQOg3FyM4bc4N3T43zKGJUIYk8GjpP82nacI1gUfpYnkTl0AAdXoeBBk7cY%2BJ3AT9KEpwjPoo5TMCepNQsjprNsihLh7bYHLhFy3KGLVfU8ijnyoxCFkMlxAoncTOHqf1wqsig1nodoVijVhOUudo6EQLQtETEjpzS7TKOzajsv83LPyC9CGnLEqACVEDgWh4ES9ytVSdrqB0%2BCwBzIoDN64yBoK6h6hnUbxs5eAkW8FdhXWcI2H5IwtXqWClpW2w1v5bxPH0DEtkIWhIL0YVZCQvLvxC88-zGib4BaZ7Xp6D6vvUgNoHkPk22FAB9VFXPc269PlNbyn%2BxjTl-B5Wg6WTaGYTAVloboW2m5K2sxnzsb83H%2BvymkRiwonLNJ8nKep9AjpO2gzouq6aRurzdMZ3NHoh%2Bg3sQaHWFA36HDx4KrBGM4-x5imqfoFtwZe%2BWoc5GG1zhhGyaR2hUfRoYGcywSepZ0STMG04pK5joADUvxEJR4AMWnOyneask6hDne%2BV25jE9nzO99p8AUtsWoDqJg-tzs5sdrqspjgLWYBzWwqTxTYHQABxXQ6oapqWpDrUw7zqPfJ6kdi-xzXiq5uWFZEW9oAAaxEa3h90LQVgoWIBVrMljtah4H1b5buuHES4-draIBGYaiZRdEejZdBjX6VXEGU8qKHoG0KEAqIlyFsWHl49L%2BKd9uN7oruNc4EZdpE0AhiZQFAU4UDTraeIoDWDeC5LIWAkRojoFYC1dcZFV73TzJ3N2m12ZAyAS9YUFBUGMENCoJ%2Bq5aBXyULfFqL8wgr0lnddeyFlS4LZg8cEhMwitDlncToAofjwGYHWWAzUVCHwVug2KmDWG0XYVvPBXDOa8LrsKeggoYjVAANKIEQNgJB-R0CRDHswCBdNl4YOYVjGWfkcFKM4WEcE2siaD3McPO4WhZLySiCiFsiAwb9x6HXLkDdmwaQlO-byn8mYd03kCbeNJwRe14WIWguFL4G2gAwDiJC2DwDDDfW0yloD1jJnfGRm4OoZXztHNhG0nGBHBInNR9UNFaJQZ4HYclvAtlxNgHYmA9hVK0gtSOa8C6OFjok5Rziy68L0QYyygsqHrHcRQTxPQGEhSCOHMAi1bGrXsQk%2BU8cuG914T0wi6AWgIHuIw6x0S4KaEyCkJwWh8DNWMCvHIQA)

#### Code

```fsharp
type Foo =
    private
    /// Foo
    /// Bar
    | Thing
```
            

#### Result

```fsharp
type Foo =
    private /// Foo
    /// Bar
    | Thing

```
            
#### Problem description

There's nothing *wrong* as such with what Fantomas did here, but I think it's aesthetically pretty displeasing. I expected Fantomas not to change the formatting of this example. (This seems to have arisen some time after v4.5.2 and before-or-at 4.7.9.)

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-08-02T09:15:05Z - 1fdb14dada5abb2e9ac9c35b5699bf2e185c5739

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hey Patrick, thanks for reporting this. I've addressed the issue and released https://www.nuget.org/packages/fantomas/5.0.0-beta-005 if you like.
