### ISSUE TITLE
Underscores in subsections of configuration docs disappear, plus suggestion for table of contents

### ISSUE THREAD

**Issue by abelbraaksma** [fsprojects/fantomas#2411]
First of all, great work on Fantomas 5!!! I'm going over the changelog of each alpha and beta (didn't find an all-encompassing list somewhere) and I really like what I find!

I found the docs (it seems like they aren't directly linked from the `readme.md`, I wouldn't mind adding them there), I think these are the ones: https://fsprojects.github.io/fantomas/docs/Configuration.html

If you look at the "Configuration" page, it renders the captions wrongly, because of the `_` in the names of the items. I was trying to search for info on certain settings, but that doesn't work because of the rendering:

![image](https://user-images.githubusercontent.com/16015770/183227399-79bed1bb-3807-4f53-8fdb-c99c65ad8559.png)

Or this:

![image](https://user-images.githubusercontent.com/16015770/183227552-4a6127c7-c386-4ae2-871a-991a504c7c0c.png)

PS: just an idea, but perhaps we can make an TOC of the editor options on top, that way searching through the page won't be so necessary anymore.

PPS: the same file on Github renders just fine: https://github.com/fsprojects/fantomas/blob/master/docs/docs/Configuration.md

**Comment by nojaf** [comment]
Hello,

> First of all, great work on Fantomas 5

Thank you 😊.

> I found the docs
The documentation is still very much [WIP](https://github.com/fsprojects/fantomas/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation), once we made more progress, the idea is to replace the current `README.md` with a link to the docs website.

> it renders the captions wrongly

Yes, this is a bug in fsdocs (see https://github.com/fsprojects/FSharp.Formatting/issues/389).
Feel free to take a stab at that one 😅.

> TOC of the editor

That is a good idea, I would accept a PR for that.

**Comment by abelbraaksma** [comment]
> That is a good idea, I would accept a PR for that.

Done 😃. See #2414.

> Yes, this is a bug in fsdocs (see https://github.com/fsprojects/FSharp.Formatting/issues/389).

I tried to circumvent the bug. Not 100% it works as I don't know how your CI renders that page.

**Comment by nojaf** [comment]
> I don't know how your CI renders that page

https://github.com/fsprojects/fantomas/blob/8b608f590115d11c0cad599c1df8fdaee4db1ffc/docs/.README.md

**Comment by nojaf** [comment]
Due to the upstream fix of FSharp.Formatting, this is no longer a problem.
