### ISSUE TITLE
Formatting (*) returns ( * )

### ISSUE THREAD

**Issue by LyndonGingerich** [fsprojects/fantomas#2452]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAKAVAJRgAeYAnmALylgDUFkANOFAM7ZYCWAdgOZtUYANqsIoCJKgASLOQAOyNJF5ZmYyZGkA3AIboArkpEapABhZSpkAJI8kPLAGUuAL2SWrEACymwAXQ0AX09xPy05RSEVR3UvLT1DY1EvCABGUKtIAFldEgAZXkR8xH4sAAs41LSAJjM-QKkQjQks2QVjSFL4AHkAM0KeRCc5TCrrHX0jIRTUmszrAFF7fsGPPwhIdD7IBuDM1onIzoAjWFh0cc1JpJmNsABmBc07DgAnLAAxXn0AOUQAO7oIpXKRYN5GPZNA7hdpRZRnC6gmSJaZoWZebzPTZOeS6aCIABCiD6sDeiAACro3roALbYRBvZEQcGQryNSTNKSHa7HaKIy7PBJTZL3ACs2KguPxRJJZOKsABjOgug4dm0sBV3FgPGZYFZiChnJh8Thp3OgthqNFqTAADZJZBpQTiaTyQBVeSKN4qtU8DVarg6vV9fQcI0QLmSHmbM38i3I4W3dH3ADsjudsrdiAAwuhVWwczq2KzoFgySGw4b2fsWrC%2BQiE0KbmiTLaABwZvEuuXk7KIWknRmV9DhmvQuumhtQAWJls21IATi7Mtd8qL6GDktDo%2BrVg5kZNbWnkFnzetd1taQs9yd3cQAEE%2BlhGUXabTdHqDRGwFGwlOOnjJFzxFS9qgyW9MzXcknAHLg4E3XVtyrH8-zAGMZBPM8rVAlMr3mSD7yfF83lg2l4IuLd7m-cdjUnY9AMbYCcOTNtqieQiZQfN5YAMewABFEGBciSK-CE9ykA9fyPI5GKgVQ5wvPDqixW9chIGw%2BgAFXKUonHKMksAAdS4eAKj1epaMPejZPheTYhA1iMSsNIJTUvJNJ00pFl3fTDJMszKklO1LP3WtuXrOSYjURzW2cqQ0gddyNJ4PouBIHpvV0cs3kWEh5HJNg2CDJD7nbULJPC6NIrs6LFNwtivDSdNkoAJUQOA3ngALzMlbwKskKS0IwiIooU2KFyazs2o6sl4F%2BAxB0ZfobBfWlBElNJUJk3kotpAx0G4YEhk%2BMkPywEitMAiawKa5db3azr4GyA6jqKU63nO0THWgcpqXxEiAH0AVM8ztps3bavGli4vuOpHXU7iaXIHo3kKEseqCsqBogIadtjE9odNJTGqsGoINtHI8iR3QUbRrgSwWpa3hWtaNvuLarOkiGCb216uGOxAPq%2BxkrqiG7lK8GoCMpmm6fRrAXsOgX3rO7LvtvX7-rLRlgdBypwYigCoYcmHJrJjjKfUgA1EVCV4eBeD4TG9XKw3quNzoibaEn4skGpVKtvJPj4ssSvt%2BwnZdvqcYCKr-wYk2YrN26ybcoOSH42AsAAcWwPKCsQIqSuj7H3YT2zzWY4mGr9iAaiSq3%2BcFwlN2gABrQkaQ77A2B6HgnDpXMLkW0rbR3McwonI3E6ry0a6cuGWsp-4gSKYksCVUoxcQQS0p4LhtR4B97H7Zn2dtGip7omfK6A%2BefdruHptl4E%2BB4EOeDDnUXHf7KDHJFpWAdgHBYGyiVEck9KrTw9rPe%2B9VF62hqPdV%2BJEeDgO0AqfgZ8hxvD3rwQ%2BJUL6pAnhJQa8d0I1Tngg2GtoHg3ibsrNY%2BQ6QnHgLoPMsBir8FXoLSBZDcYUJGnGJiD8Ji%2B3uA8CmqRIAF0ZFwekjh9AAGlECIHkCA0oWA7Bd10F-LG48UJc2GlQ%2BBEtSZSAeDLGRrc9HtzWGwbivF7D-BLIgZ6zcigF0KsVYsYk2TX2srfSG1DzF10eJbGx1JoK7wZtAN4CifgvngO6A%2BOpBLQHzDSI%2B-Dy6UM9mYlOksrAPEDjIuRCTFFgPQCMHiBgSwQnkCMcgYxkK7jycIwmpsF60NSA8dOMjVHqPUkzXB-RbE8HsUUYhTUzCxzxjzTCUVsI9PNpYxuMjanwUVggdYhj2nGNYP4TwKg2CfGKkIUhIAghAA)

#### Code

```fsharp
let (*) x y = x + y
```
            

#### Result

```fsharp
let ( * ) x y = x + y

```
            
#### Problem description

This seems wrong. Fantomas doesn't seem to insert spaces around any other identifier names.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-08-29T08:36:14Z - 30f73bc1c805d0c09e3cb7a268b5f71cb0e7ef38

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Thanks for the report, there are cases where you need a space because the operator starts with `*`.
This isn't one of them indeed.
