### ISSUE TITLE
Bad split of chained method call expression

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#246]
Before
```
                             root.SetAttribute("driverVersion", "AltCover.Recorder " +
                                     System.Diagnostics.FileVersionInfo.GetVersionInfo(System.Reflection.Assembly.GetExecutingAssembly().Location).FileVersion)
```
After
```
            root.SetAttribute
                ("driverVersion", 
                 "AltCover.Recorder " 
                 + System.Diagnostics.FileVersionInfo.GetVersionInfo
                       (System.Reflection.Assembly.GetExecutingAssembly().Location).FileVersion) //  line 127
```
The first builds, the second goes
Base.fs(127,85):error FS0039: The field, constructor or member 'FileVersion' is not defined. 
Base.fs(126,20): error FS0001: The type 'Diagnostics.FileVersionInfo' does not match the type 'string'

**Comment by danyx23** [comment]
Another case of what might be the same problem:

Before:
```fsharp
type Exception with
        member inline __.FirstLine = 
            __.Message.Split([|Environment.NewLine|], StringSplitOptions.RemoveEmptyEntries).[0]
```
After:
```fsharp
type Exception with
        member inline __.FirstLine =
            __.Message.Split
                ([| Environment.NewLine |],
                 StringSplitOptions.RemoveEmptyEntries).[0]
```
Results in compile error:
The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints

**Comment by SteveGilham** [comment]
This issue is back in version 4.0.0, in the self-same piece of code

https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEMYE61gFwDoBlRPAQTzywEsAjAVz0QB0tmA7TLsACmcng0AboiwA1UQGdqsdvwA0rDty78yAGzwBhWCKwEASojhYkWMPyWcVGANRgiAT0lMAtgQAi1AIYBzdrAu1NCSBABi1OqIEljSsgCS7ABmsAQA4qQxceyJKXxs1jZcTi6I7kZJUdB4MuwEZJKSZbTqjumkAKIAHsaM1Oy%2BDU2uLY48AJQEADKw0N41spMRUVm141aQ8uBQTZT9vpKoYADa2xCg3JAAJHiOAA7IaJD9eJtnGNdC3ur0jyfvmAADFsbJBEkh2HgiNQAF7IEEqAAsALAAF13gBfBHnFHXW4PI7PSFvS5XL4-P6nGwARmxXEgAFlvF0pv1EFNEAM8AALEkqACcgJR6MwWPeF3pN3uf0gtFw6j5mE%2B31%2BRypKgATHSlSRXMFYOpZBQOux4AB5JKs9jwlEQJLfJrCzF0iVKqUEp5yg2Kj5klWU21gADM2o%2BRDu3mgiAAQogUlhEAAFbxYbyuUiiH2YKi-J2il2490yr0K0PKilqwOI0MQSDhyMxuOwBMzADuojmTUSQlm81qWYwOcQeYwYswrt9%2BOL8oH5dVaHV3AArDWoPWo7H44gAKp3B5YTuIbu9hbsAd2h3D7gi0cF0lTwkl2d%2BisLwMANlXdYjG6bCa06jeI0OjsC4WD0NUzbnmA9rqI617OuKhYPp6M5li%2B87-DYADsX7ro2W4Ms0marrB8FcDeEBjhgE61kWj5oYW5KYYuXAABx4T%2BBHNogOiGmepGXiOVF3pKKFQE%2B6HMQGNj8pxDZkEkTBYDoriuN40FDsJYDUTi97Sgx3pSf6lY0sCgbfg2m48bq%2Br8dBZFXhRiHjshBmoUZTEmW%2BNK0hZ%2BGKcptlwPZq5aQh%2BZIfpHoSYxpLSaZKjUlqFngpyeBmuwAAqWCOAA6tQPIOUJEW3lFYnubFnnxd5WFJSG-lcWQOD0KaHiIOo1B6spmngU5mCUTpoluuJRKvMZr51dw1LVhZTJdPESRZdynIdHBiBENyzZ4AV8BFauiJCqVInlSNlVjc%2BCU%2BUlK5zcyuTUF0Zr7vMzbdHcCaNP2q5LkdzmRa50Uyi8l21axmDUp%2Bd1dEYJjwLt%2B1Vn9A0uTRbkxRdE0sYG1K4dDzWpo4ZpYKyLgI7yB3Ixgg26WAtFQPRTwg1jMlJRx0NiP60b9PA%2Bzk9Bh3abT9N4udzNeZN4MYNScnQ2ErXVLU3Omnz1B7RTSNC8Nk7nZJEvYzYGrmaCDL0JokRstGhrQAA1tGqa26QkiZUQaa8Qa9CuAJgaOVrp06xjes1ZLgYan5oIAHKIK2nXWrGeDtpyWXSu1ST9IVtRkKaREjFIxXrX7gMVYHcWSldU1cBqKWggA0ogiB3Ity2cokrvplaNo2L7x1Df7dGjeLwcG5qDUm8ya16pI3L85Thdo0DhmlvrrPcBqs2gtCAxRM1vie%2BleWILQDIIJ3Kjd-9ZVF2dJfVWXYOh7doIaNQ-jy%2BwiuyNC-jzPQCZZbAaVIR9lkPnciKMAbz2LtOW%2Bbpy5SwgBqKGT9NCiHYH2EQMwBg51oKIVO6dTyHEEgXHuwt0bQKXkPFelc8YbyoMEPAx8kCgP6tTTE2xUQImeJIMI0gji%2BwxEAA
