### ISSUE TITLE
Only open the menu of the current page on page load

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2462]
When opening any page in the documentation, all three menus will be open by default.
It would be an improvement if they are closed by default and only the menu to which the current page belongs should be opened.

**Comment by alanlomeli** [comment]
We may kill two birds with one stone if we migrate the current menu items to use https://getbootstrap.com/docs/5.2/components/accordion/ as it will give us the animations we planned from the start, and the auto collapse element. 
For closing and opening depending on the page you are on, we might need a bit of js tho.

**Comment by nojaf** [comment]
Good thinking! Yes, the current page would require some JS I fear.
I don't think it would be easy to contribute to FsDocs to have this information.
