### ISSUE TITLE
Mishandling of comment

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#247]
Applying fantomas 2.7.1 to https://github.com/SteveGilham/altcover/blob/f1aa1e0a4a80a62abd5c07adf8f337fd0da025c6/AltCover/Runner.fs, the comment on line 638 ends up in a completely different part of the code (what was line 484), causing a build break, like this
```
                       match x.// And tidy up after everything's done
                               Name with
```

**Comment by jindraivanek** [comment]
This is comments integrate bug.

There is also wrongly placed comment before that one:
```
                interleave
                |> Seq.fold (fun (bev, // mocking points
                                       sq : XmlElement) x -> 
                       match x.// And tidy up after everything's done
                               Name with
```

Something in formatted code at this point or before it put comment integrate alg out of sync.

**Comment by nojaf** [comment]
Could not reproduce anymore [online](http://ratatosk.dynu.net/fantomas/#?code=DYUwLgBGIM6QdhAvBA2heA6TBaAjNnhALoCwAUKJAJ7IQAUAlBQPQsQDKA9gLYgQBjXn3hgYQA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA).

Please re-open if still a problem.
