### ISSUE TITLE
braces within string interpolation

### ISSUE THREAD

**Issue by OnurGumus** [fsprojects/fantomas#2470]
[Fantomas online tool](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEIAsAuBbANgDoB2GZYAJIZNbaeRADyYCMAfAMqIBOAbj2ADyxAK7dGAelZsSDCMFlyyAZ0QBHMAvpKMAM1jcwASzABeMCzDZYFgAxh4sRToYBPI4nzxK1RgAc2YCMAX0kAuhcIYOcdAB82MA5sbiNiAHMAOjhiaABDbDBaGm1yaJKyf0DcBE8MgBVEAA9sUIlwmg7IABpwKFVsbFS05VQwAG1e%2BUmMSApsVz9kNEhU7G7piFneXPwRJfGNjFsepUgASWIkYmwOIwAvZBO5ABZDgF1p4Kephln5xdGK2u61%2BFG2u32EyULG%2B5EgAFlco0ADKpRDIxDpbCYEFyFgAJls70%2BsNAoP%2B%2B0gmPggl0qOIiCSrnwj0OWx2e1GULk%2BNhZEgAFFLrT6azTvhdJBiWQvtMyXC5gtKQAjWCwfC4-lgjmQw4QADMfJmF1U3GwADFUjsAHKIADu%2BDRmvIyT20owsrI8q1FMBqvVzs22ohXL1YGeRs2HD8uWgiAAQoh9NxEAAFXLcXK4RDYHiBjCuxDuqKktmKgHLf0ao3skNobkMACskag0djCaTBnRsDtPDyqguvFgeUGsGI%2BYgheLYE9GG9M3LKrV1bL4M59bDADYW5A23HE8nEABVPyLbj9xCD4f5IxjidgXQ7VTT2c-BW%2ByvL-O19cHJQAdh3PcO0PABhfBcmUZRQLHZRXWgaxuHvR98GfBgPhlUtySVP0vxrYNfwbcgAA4gJjfdOxTeFEFwZU8xbFC0PIDCPSw98cM-AN8LXXUlAATjI9sDy7GD8DvBinyLdCSTlMsPygKtvwI3i8WOMNd3IxAAEFdFzbgYNwXBcnvKdpMw2TsIrBS8NXHVQ2hGF1OA4SUy4XAjDgMTxwk1CpOYmSvTkjjrK42y6z-PFeSczSdL0tyPPVcSw1M-zzMCyyl1C0EePsvFDWi9stO4WAREuAARTwjHcvSTO4N0zNYiz2KsoE1m4uyN2hCN1MRRozl0OpMExDhMAMbAAHUjHgbF7yJBqSyan1gtapScs6vFmx6pF%2BsGzEBV8kaxsm6acRbTc5tSxr0uaylVlWjqIoYFhty2vriF0IxGkEM98gMAVGj8FMoNvbyw2Ii6yBYhbrqWlq7va8KiLIFhANegAlRA4G4eBjpmltnghjAoZnNjYdu4EEcIsMWFI9HMYMeBrREWieFpM5c1wEYWxYF9SYXeTIFwER8EGR0GXNAwjIGHg6hwymVKegT1IxrH4HhYXRbRCXuClmqd2gTAM1jPSAH07SmmbecW-nlvhsKqaUQkd16orM1cQRuFRODcdOsHCYgYnX00IK4Yp%2B2FfIfFHNOF3uDdj2vewJmWe4NmOa56mrZhm2WqFkWjDFxBtd1mW5fD3KGHxKLTld3J3c9ow4PV-PC%2BL-I9fUg2jYQngzYtnEs7nEPyba8v1sr-KY6RAA1HV41SeAhh9%2B9wcHt8ycBO3soepGMHxbqp8ac1SoQkH58uJf%2B-vAm1%2BDjLN7D7fEbDfFNsPsrYGwABxHN-sBxBgZjmXi2Ve80SbWyDALRS8sK6RxejHDWBc0TxjEtAAA1vGTM6CczKGEBwLMiBRLM1BkoRiflIYBSHvfTiK4n4Ox5KjU4toHTIJzL2TEstFgVQ%2BsQIwo5iBaUuNRFOGclApQoWlKhN1cJZQVGtR6kdaY10dGkYgx8cj8NuKo-IYhEB1FgBcK42AbxJVIZJW%2B85IHLWgWPBRZB8RK2UXpYgN5%2BDIjHGkYRdFuDcNSHwkGoi5BkIscPGRtC5E7zDPqNSCD86imRFmZU8BcjgVgMoIYzDC7IXMWAoOlioCLjCfdZ%2BSh9TRzkIKAGPAqqYmMfgAA0ogRAfhDG1IuJg3IORfZmN8iE6hIVwlankbvA01cKkoM6Wg0UygiolUuLaOCiA1aIMLn-IG6TYK1XqpdaGUiN40OKfQhg%2BpJ7jIzC5RAZVG7QBSO5FxuZ4BHl4WOCq0AIKZn4dk3puS%2BZWJajYuhEcyD6gPhUv%2B1TszXB2EkYqIg4J1T8EyFkWzyFE0oevHOI9DlAowPqN%2BFTGnNN6snbxtIJnECmWiQJT1bD%2BzAIHX5BSoE2UBbA4F8CKkwo8tgeENQvlMQkR6XobwngrGUOadJoxgnBCAA)

I would like to keep the code as below
```fsharp
    html
        $"""
        <h1>Server Onur</h1>
        {
            seq {
             for i = 1 to 10 do
                 yield $"<p>{i}</p>"
            }
            |> String.concat ""
        }
        <p>{model.Text}</p>"""
 ```

but it turns into this

```fsharp
html
    $"""
        <h1>Server Onur</h1>
        {seq {
             for i = 1 to 10 do
                 yield $"<p>{i}</p>"
         }
         |> String.concat ""}
        <p>{model.Text}</p>"""
```

**Comment by nojaf** [comment]
Hello, we don't take [stylistic requests](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for).
The style guide is pretty clear on [this matter](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-string-expressions).
Thanks for understanding.

**Comment by OnurGumus** [comment]
Ah ok sorry. I understand. I actually felt this is almost buggy. Thanks
