### ISSUE TITLE
Private record definition error with stroustrup style

### ISSUE THREAD

**Issue by sheridanchris** [fsprojects/fantomas#2481]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WACogE4DOsAdmALxjZECWAbgIbp7AA6RHlEYAYvVLoAcswC2iNCXQNyAcy48%2BYADLMZYydNn0FS8gF9IAGnBQSidOj3ySqMAG1zEUCoiQAJFlwPIe9FMXPi8WABsAV2Q0Z3c%2BAAYzOI8ASXIkcnQAZXoAL2Qk5IAWYIgAXWDDQtdSqG8caKgAoLjQ5kjG2OSARmr3SABZZgAPVT1EVUQFdAALFp6AJnjaipUq4Ld%2B%2Bt80SCn4AHkAMzHyRCysMILato6HLriFvpVIAFF049Pr5Kgwo8gVpU%2BpsXttGpAAEawWBheag8JRe61CAAZmeITSliI6EE5HaIkQAHcwuM4e5ZFFAWtgTcwX4oTCyR5PAjOsiwEV0R4sthmNBEAAhRBHWBERD4ZhECRWYhMvgUxBUvjrFQgkJ03YM2Ho26ImLsgCsXKgPL5guFoomsEJxGgGkQaUYsDtNgocogCqVEBVfDVzJ84K1ct1bJ%2BADZjZBTfyhSKxQBVbC4Ih2yyO52sehu41HdqWL1gH01VoaqBBnUs9p6pzsgDskej5rjiAAwmENCQWxQZEQItB0KL3WBc2F83FVsqaSWA-TodraaykT8ABwN3kxi1igaIcQQ2U5vOK8dAja0meaufByt3fU-ACca7NsctXbC2fZI7H7gn3qnW3PZaXhWi63j0iTslG66IAAgkcbBEF24jiMwQ6ese1KntODSzoywFVqGPS9BBjbPmKWQ7vQcBvuQQ6fke34nqqZ7YReuELvhS6LI%2B-KwfB5HiJRMLvj8aEMRhTFYTsgFsSWIE1j83RosRUHQUQsAROkAAiiAkgJ8Gob29EqD%2BhZ-qCAH%2BJkV5yQ87jdJyEFDMMKRHAAKjMUxZDMoroAA6vQ8CzEOyzoZOmH-ixTRWXhN7yT0RqOSMLnuVMryjuc3nYv5gVzMaYYhWJYUSRFUmWYEMXVrZKjdBGiXOeQRz0MMBzJqwoqvMMdCICQJBZjRxrLgVxmMb6zGlc0FUEXE3T1nVABKiBwEQ8DZUFxpFENfAmUWYB%2BnUFkTexsVVXw3SrvNi2ivAIgRLuxDHCkbDiPYxrdAWO17V4FniBEYQ2CSZz8KKyHWMQrnYZNnHTQ%2BEELUt8ADL9-3jEDRAg-pkbQDMkp8vBAD6hIBUF71meqB3RUdlXskskZOapUqYAcRBjDIq25eyg0k%2BF5mRWV1kcaBjxET8gwjPTzCM8z9CaLde5EA9T0veyb2hb%2B3Nk7zP1-fQAOIKj6NgxDlNTe4CxPBB4uSyz6CI9ruv66wGMQVjOP9sQBNE3MXPFTz40U7JAtxY8Ski05ABq%2BECno8C2GzQ6c6rpnq-6vOHQHx3Uw5ocjPwGn9n1UfpLHntDht3ujZJ4Jp1sNnUwl2fDJpsDoAA4lYHVdT1fVxwNm3lCNxYlYGQHG1Dpu1aHSM6%2BMApvtAADWApSgvVgkAc5BZNKr63f17KicN4kV0POHzunVM-Ass0iwSxIz1YNpTODuDaY15D0K65DQek253aQBmUonD6Y1h4yRroHE6EAFjnRFtBEk8hyC53IPnCgOR4GsAiGKVysA0gZHQJmYSyQ6Ll0Hr7EBp8wEZwvjDGBf1iB4hsIwK0Cgf5yxfnod%2BfUlY-CIYA0mKdSrllHoLdwKJwKT21l8dQu54DMDbLAXqCgb661ooeYhu1gEn35pQ5IKJhbJDeJ1Yg9BJCZHaAAaUQIgbAOCpjoDSEvZgSD2bcNUbw5O%2B1eaCLPibFQKJzYi1no4%2BeXwSCqXUukAkMhEAIynrrDuYou7dn-kZLaA91GV00ZDYRviQ76IFJKUiiBNLS2gAwAS9DonxjfhQbS0B2xSg-io9KajPqlkhCPbxY9fFZ30R3IxJi8FhAuGpCIPYIjYAuJgK4ySWkaN2NXeE4D2QonrvoixVinI3V-scQJ5BgnjC4WBPuYBtp8I8QIjpFDz46Invo4ZlEbYIG%2BIQ1xhVvTmDKIUfwJB%2BC9QcEQwwQA)

#### Code

```fsharp
type Person = private {
    FirstName: string
    LastName: string
}
```
            

#### Result

```fsharp
type Person = private
    {
        FirstName: string
        LastName: string
    }

```
            
#### Problem description

Formatting the above code with the below options results in a compiler error.
I expected the code to remain the same after format, which was not the case. Although, I may be mistaken on the _expected output_

#### Extra information

- [x] The formatted result breaks my code.
- [x] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-09-07T06:05:21Z - b0916a411b7e5314d84475c5cd4be45c85ea5359

```fsharp
    { config with
                MultilineBlockBracketsOnSameColumn = true
                ExperimentalStroustrupStyle = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello,

Thank you for reporting this issue.
This one is tricky, if you can fix this in an elegant way I guess we can store the original formatting.

What I mean by elegant is that the fix is a tweak in existing code, without having to rewrite everything we currently have. If that is not possible then we will have to fallback `MultilineBlockBracketsOnSameColumn` when the type has an access modifier.

Are you interested in submitting a PR for this?

**Comment by sheridanchris** [comment]
> Hello,
> 
> Thank you for reporting this issue. This one is tricky, if you can fix this in an elegant way I guess we can store the original formatting.
> 
> What I mean by elegant is that the fix is a tweak in existing code, without having to rewrite everything we currently have. If that is not possible then we will have to fallback `MultilineBlockBracketsOnSameColumn` when the type has an access modifier.
> 
> Are you interested in submitting a PR for this?

I'm not familiar with the codebase, but I am interested in submitting a PR. I'll take a look and see if I can fix the issue.

**Comment by nojaf** [comment]
Great 😊, you can find some notes on the codebase over at https://fsprojects.github.io/fantomas/docs/contributors/Index.html.
Going through those pages should give you a general idea of how it works.

In practice you will most likely need to make a change around:

https://github.com/fsprojects/fantomas/blob/0981dfeff69a59b76f39e2b8a7e6ed76dc8b9b79/src/Fantomas.Core/CodePrinter.fs#L3413-L3429

`opt (indent +> sepNln) ao' genAccess` will add the additional indent if the access modifier is present.
If `ExperimentalStroustrupStyle` is active you want to avoid this.

When submitting your PR you want to check https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#pull-request-ground-rules first.

Don't hesitate to reach out if you have any questions.

**Comment by sheridanchris** [comment]
Is ``MultilineBlockBracketsOnSameColumnRecordTests.fs`` an appropriate place for tests? Does this warrant a new file?

**Comment by nojaf** [comment]
I would add the test in `SynTypeDefnSimpleReprRecordTests.fs`.
