### ISSUE TITLE
Spaces added inside new index syntax

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas#2494]
Context: https://github.com/dotnet/fsharp/pull/13867#pullrequestreview-1102199713. Please note it behaves as expected when there's no qualifier expression on the left, i.e. `a[c] <- d`

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBDAdAIwNrQF0wAeAWjHkgBpwoBnRAF0YEsA7AcztTF1olAQhUACSMAngAdkaSO0bV%2BQyCIBu6ADYBXGbyXCADDWHDIASTZI2jAMosAXsmMmIAFn1gCSgL7OBHlQlpHjlrRRcVdW1dPhcIAEY-E0gAWXQADwAZdkRMxE5GAAtwuPiAJgMPL2FfJUFksSldSHz4AHkAM2y2RBsJDScAtU0dHli4sqTTAFFLTu7BuKgNDsgqnyT600bg2WxYWA0S7ajRtHGXAGYp5QsGACdGADF2TQA5RAB3DRzjk0Z7jp1jVNkMgs19oc-hBIiMYh43DcYTZJOhoIgAEKIDqwe6IAAK6Hu6AAtkxEPdoUIAUCXNUhLVhFtlDsIQcjjdYdExgiwABWJFQFFozHY3G5WCfCnQdAMCyqWAy1iwNhUiA0xDAhmgiKskKQjlDU7wpYANkFkGF6KxOLxAFVJNJ7jK5WwFUqWCq1WAOpoGFqIIyhMyYXq9uyqVyznolgB2C1W0W2xAAYQ0sroKZVdBp0EYuO9vo0-rpGzqYKa%2BojnOG3POvIAHAnUdaxXiUogSdgKYW-ZrSyDy7rwVWoTXjTylgBOZsim3irMaL2Coslkz0wM6hoj8Njo1wyelIy8y0txAAQQ6jApWZJJPQ3o1AbAQf8w8ru8Nuon9aW8USJ6JvOeI2J2LBwEuqorn2z6vmAIaiDuUAGpGtbRhcJjlLO6KXte9ygSS4GHMuvJPgO2pDtuH7IdW%2B51jGpTXIBZ7nvcsBaJYAAiiA-IReGPoC-brmWTIVrsUDyKhP4MS48SuBaaTpGYHQACqFPkNiFLijAAOosPARTepU5GbpR2xIaECjjgev6lAKJ6Kcpan5NMxa9Fpjx6QZxSCqaxnCYOonvuJllSTZMmYeaDkZBYHQsOkbROug%2Bb3NM6SSHidB0J6UGNv5wgbi%2BW7mdRoXWfRGHCPE8bRekABKiBwPc8BeYZgquPlQiFXBCGBKVknlehvLxE2tUNU18BvFoXYUp0ZjXiS3CCvEsHFSyFkkloGisD8PRPLi97MBSKmVoNJqlDOJ7jbi8ApFtO05Pt9yHfxFrQIURJonhAD6nz6YZq1met-VhGdh4uBUCkZKxxLiG09zZDmrU%2BXlgNBVRIUDXRQ1LGUAFLKk0P3LD8OI4wU0zfcc0LUtw1o8GYnNJt20sLtiBPS9x2ndj50Q5MJ4w%2BgcMIywOZ3SzbMc8lr0nu9n15hSv3-cU9NvhjzRY9%2B4WVUIZRMQTikAGpwhi7DwOwHDI96DadRA3VraGFmaw00k6xAZTybVTwcXmOWm5YFtW%2B1tueCJDPBRroM8%2BDJhlPZBsZJxsCMAA4kwaUZYgWU5UHqMmUVQOO6VKFg7ZENRQb92szkGJLtAADWGLEg3TB0G0bA2KSqaHNNuVLKuQkFWHaslSFJfR2Xsc1QTHzfDXTBSvkJ3SNxcVsCwypsOelgdpTtNLGRAUUejo9snuWsVbyZSjQT54-BwbDe2wvsqnYD-JVoeIqbAFhWIwyU5V7G5VW8FGaji-C7bWV9Lq322hSNgADVASk4Lvbs9xV7sA3jlfecQB4gN6mGGi59IGXyWJcY8lcWYLEyKSbA8B0BplgNlTgs82ZALXEPQK4d1bgLCqQuIlx8ZxEgBnCkLAyTWE0AAaUQIgSQv98iMAsE3dAz8Ub9xgvnHqYDPx8JxgI-mBNa6qPrgsOgrF2KWA%2BDmRAt0q5swzplbK2YBK0iPqZE%2BwMx60Qvvoq4%2BthEYiJMBRAnFRbQHuOI14154B2nXiqbi0B0zEk3uwweXVh6gIjrw0uEVhCXE9gTURkSJH-w0H0NiWgcyAkkH0cQAw0n4J0RJKOvjeYmEuPHYRMi5GKQpmgzoxi2CmJyDg2SBgQ720LohYuPiSF%2BI6RXYRFTwKMBSAgRYuDNHuJfLQAgzg5B0CeNlHgeDvBAA)

#### Code

```fsharp
a.b[c] <- d
```
            

#### Result

```fsharp
a.b[ c ] <- d

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-09-09T07:46:11Z - c1a16e6d28cd281d27cb9161f4b77d5bde8f8f64

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Thanks for reporting this!
The AST for `a.b[c]` leads to `NamedIndexedPropertySet` so that is probably the reason why this differs from `b[c]`.

We can fix this post v5 release.
