### ISSUE TITLE
Items.Item <index> <- value gives wrong code

### ISSUE THREAD

**Issue by dbrattli** [fsprojects/fantomas#2498]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPAzmALxgDaAPmACwBMY5AugDoB2rBAdAJJaIC2%2Bbrz5gADGAA8AWjA1RkADTgo%2BbFgCWLAOb5UZZRFARjUACRYAngAdkaSJqyKDxyKYBuAQ3QBXW-pMmokoBLlwsSCxYAMrqAF7IwSHUzhAMzgC%2BiYYpZpY2evaRTiGunj5%2BpDkQAIxZAZAAsh64ADKaiC2I2lgAFsVJ1XI5aSaZzkb15tZ%2BkF3wAPIAZm0siFGWmP0mpV6%2BepVJsnXbAKLhSysJVRiLkMMZdRPbU-l2AEawsOhbLu67FdcAMzHUIsVQAJywADFNF4AHKIADu6HaPxMWHBvnuo0eOVceRmHy%2BaLMZT2aAOSSoIIgkCiVg80EQACFEItYODEAAFDzgjx8bCIcEkiAYrEhEbGMYmJ6-AkFInfEE7cr7a4AVhpUHpjJZbI5HVgiKF0A8qjCblgpo0sBYIrAYsQ2KluJKL0JnyVeL%2Bqop1wAbFq6Qymaz2ZyAKpWGzg03mliW63qW32xZeVTOiDS4yy2nuhWekkq8n%2BJIAdiDOtD%2Bs5AGF0Gb8LXbfgxdAsBzU%2BmnRKHuNvfL3oXlT6S5SQgAOSshvXhxANfhvIVd9AZ3s4-tuwdQRVF0cAw4ATmnurDBub6BTWrTq57AUlWddk23kF3I7JB4GQWuwd1AEFFl4cFmz4PgPHtR1MzAbNsi3aYC2Jd9-jVQ5qlqH8q1nA0on4dQ4EvO1r27KCYLAXNcngodEO9D8UIGGgTyZACgJwvg8K%2BK9rkg9cXU3Z9KJ3YcaOQv1UOBDCZz-cFYG8cIABFEBRNigIgzE7xMB9oKfZ4XwcPdaNEgZqR-JpcC4RYABUei6KIeg5LAAHV1HgXp7VEEjtLlATCkcJDfVLEJqk1EzmnMqyuhOW9bPspyXL6LV-XcnjHz4nTvL0vyx2uapAxCsyWEWdRcHmGMPA7cETlwKxOXwfBk0I64JyS%2B8%2BxlAd0qKTLP0Cis8oAJUQOBwXgWLXK1Khmo01qc3a14oAy4T-PHAJqinfrBo5eA4W8Pgl3BJYeH4XQtWqDzUq8ubID4bx0A0FFVihDkwKwICLPgrq6MC48fwGob4AaG67vaR7wWelSg2gHpeUZICAH1EWc1yzrauDLoWt0DICgI5CDUypL5Cx5nBNpW1G%2BLGsm4xNNI8j8Q63zFqyw4aHQw5GmafGPEJ4n1FbbbdqFA7hGO7LkZm1GZmu271HuxAQbBoU3vyD7DJCGgGJ-TnuZJrAAel2X5bK8Gf0h6H2yFeHEb6MXYP4tHOsZ7rsfEtnTIANX%2BZlNHgTQtDJ%2B0mptsjZpmdHJkx5aTBoYzXeaKFZPbeqvfCX3-fGynUmm220vthmMZErGo%2BC2PcDk2AsAAcWwSrqsQWr6rTimg9p-MqK9fOluuGhctdwGZfaZlL2gABrZk%2BRH7B8HmFgon5RALx2hrDhvNcWo3FG7Y9aiO6ZpIaF6tmEWRAfsGNLolcQBTCpYdQbRYP9wgXAXwRFw5uLX3iN5zrf2-DgvI%2BMDQNabM-woi0CweOLBE62hiOAsq3hOQWVgGECIWAyr1RXKvKa69xabwQr-Z4Ecu7fRAbdIULB0FuENNoJ%2Be0r6aFvvVV%2BSQV7qSplnYOEt8H6X-kCb8vdpaXBaPyN48APD1lgHVbQR9ZaYLYZnHB2cLo-x4Z3Q4gJWZJEgDXIU6gBSRC8AAaUQIgKwKCuhYDCGPDwUDybL2IslLS508wvjfI7T6ARAQazZoPGxw9Lj4CkjJcICJWyIH%2Bn3WWNcap1RbKpcUH8Upf2UdwlWhdjCAhdlo5kvIzycjkrzaA4I9Gwl4PACMN9bQKWgA2Pkd85HNxDqk9xqtPExy0To4p%2Bi0HoHWNJbwrZMRWHWBYTYRFbyNK4XYMOhDeHqOLlo4xpjTL8z2ksXxLB-HtGYYFUQGcwDU08i47ybid5OxMICHuWi%2Bl4V1ggK49iJmOPSMoBgiR7D4ChHVPQrCQDpCAA)

#### Code

```fsharp
let xs = [| 42 |]

xs.Items.Item 0 <- 20
```
            

#### Result

```fsharp
let xs = [| 42 |]

xs.Items.Item0 <- 20

```
            
#### Problem description

Fantomas removes space that should not be removed.

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-09-10T06:40:11Z - e1bd9638e60461020f803e443bab95c82c591211

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, this problem seems to occur around the `NamedIndexedPropertySet` node.
Are you interested in submitting a PR for this?
