### ISSUE TITLE
Incorrect Stroustrup indentation with let binding for anonymous record `with` expression

### ISSUE THREAD

**Issue by josh-degraw** [fsprojects/fantomas#2508]
Sorry to be one of the new voices of issues post v5 🙃

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzWsAIlrGALwA6AThQHYQTAA%2BYsWAFolcaQO4CWHanQaiwAFUQAPLADF%2B6LFwDO5YfTGboVQV34BDAHQBZbEckz5irus2amAPjAB5AA5Z%2BsWoYC2%2B12AAFLgArvS4YAC0TriGVkpUygCUtnaiji7unt5%2BAYEAMvzKWL7%2BQcquOrRYERSQAH4ApMr1dUkpNBppEBluHl6GJM4ARgBWqT0AvpAANOBQytgetADmyqhgANrzjDsMkAAkWACershokPzVs3sQhwBu%2Bugh51u3DAAMc2mQAJK0SGqAGV%2BAAvZDfOwAFneAF09pNIbtNIcTmcNpdrkj9gdHs9Xts0gBGbGiSDGfRSQq0RD5RCrDg3YkAJg%2BcIR2NAKKOp1ekHp8GcuGpiCBJ0wTLEDyeLw2hLszNJ%2BwAogChSLJSj0LhIOzRIi9lypTz0RdhgR0JqcXjZWh5ZoAMxKu7-RZUORXJ4AOUQvHQVwh7wgWCoLz1DANoiNZJNfPNsEtSul%2BLlQbAUOdUCBrn00EQACFEPgqIgAAr6Kj6HzYLhW0QhsOaeH6znvVG8jHxxNt3EyglpgCsmcg2dzBaLsBL%2BVgvC40H0i3%2B91g8-6tDrDAbiHDEEjDGjOLRcYtG%2BTtreaQAbMPR3nC8XEABVVxnKjzxe0Zer7IbiC4J6LDuYB7sixpHp2J5Jr2KZ2mmADsN45neE4lgAwugC7KKhXjFKG0AkFQv54AB25Nhyho9uBZqQT2Nr9mkAAciFjvek6IKYPjDLWmb-uggFkS2FHclRUBdqe0HnvaYgAJzMchD7YegXhEbx-FiM2EatsJHbUQm4l0amxJfGmI5IYgACCuAJNhPh%2BERW5ASBYAHncsYQXpUEGbBxIkiZt7jg%2BQKID4-BwEp648SRjlaWBOmiTR3JeRedhEoqflmZZCRBSFYXKZmDkCZpQmxaa8UebRfaGSlTrpWO5lULAYTwIQiD%2BiFCT2aGpHqeRUaUXFmJYPplXeSlGYmRSUi-Lg4icLQQLsJOWAAOr8PAjKZmyhW7jFMYiYNw0wclmhEkOE2UtNs30sqfGiot7qret7BEZeW09YJfXaaVB2eSNx1iES17nVNtC4PwUhuFw%2BgEcqUiVIgyjKD%2BmYMW9ogaTtxV7QNVxDb9R1SaIRIIcDABKiBwFQ8CPRtaZQmjDAY8Bu2HjjWIVQTaZEkxZMU5O8BeiEnFcEKvxKD46yZkS0VY6z30%2BCEigKAGsiTn4WAJOIHb45JXOySZ5OU-AxiKx4-o0qrVDqx1w7QOwFa5gkAD6AhPbq23M7Lrn7bjh262krLDpN9WVsczhUIUxQ089KMMxATNOS5UBuRcvs6-RCq%2BT8wdUKH4eR1ggvC1Qovi5LXMy59JV8grSvm4glvW1wWvounVWaMyaU-CH%2BhhxHRRYCbdcq2r0M2yZdsO-hXAu2tjKV-u-XfWnHP%2BwqNXZ5SABqfb5lc8BXCs0dEajC%2Bgdjy-s4lf2EwwzLjZvUiyGE%2BHZHvAKH8fmb02fzlL3yK9r6cwDmdR%2BhA2AAHFsCw3hojbIX80ynw9onf%2B7luxALXh3IG2dTbKxpPmJS0AADW%2BZKzEOwMoZw80qyIEUkLCKaYCrvSKlXC%2Bx5yoYIzh3EmPwfR%2BgDIWLAs56Qt0QC1MGtBBDZHMgCDiXFEidUbMwzGrC5bsPQcaJKt8IDMh5t3f0KxaDP1oK-LwIJDHQxCCWcQsB-iAiwNDZGaZVLdXRr1ReX11F%2By4WIZk%2Bt9EJFoI4%2B4tIvArDkVwcRVwpE4RUlFZBLNvYDTEm3UajpjI4KViKfIVZhjwH0OhWASNVh8PrnE26v8k7tm%2Bik1ePjRAOiznYSAMC9DVmqE8AA0ogRArg7H0iwP8Uh%2BgTEx2cfE5RntVFJJqQlTRN80wOi7s0ghIyiEimUPVRqAIfTFEQMbXB9cYEljgbE-KXVKmoN0homMWjFkbxWRWViJZCBFG0PwEKQSlDwEfJIrwLVoAYUrGucpak3EfQ8dXNB3j25iAdA-ZprSdDtIcegMUDUQi4RCK4MUxwJTnKUeClhkK2EYkAfM4BdgHSgOad03pk0i7yKFKs2g6yAzlyMnHMACdEnJ32rUzhsKGnYOaei0Kg8ECBjSC4xy8xYSQkuMoWQSMNgysmEAA)

#### Code

```fsharp
let fooDto =
    {| otherDto with
        TextFilters =
            criteria.Meta.TextFilter
            |> Option.map (fun f -> f.Filters)
            |> Option.map (List.map (sprintf "~%s~"))
            |> Option.toObj
    |}
```
            

#### Result

```fsharp
let fooDto = {| otherDto with
    TextFilters =
        criteria.Meta.TextFilter
        |> Option.map (fun f -> f.Filters)
        |> Option.map (List.map (sprintf "~%s~"))
        |> Option.toObj
|}

```
            
#### Problem description

See above examples for the issue. 

Also, if I add a comment or newline to try and preserve formatting, it results in this:

```fsharp
let fooDto =
// Comment
{| otherDto with
    TextFilters =
        criteria.Meta.TextFilter
        |> Option.map (fun f -> f.Filters)
        |> Option.map (List.map (sprintf "~%s~"))
        |> Option.toObj
|}

```

I think the root cause of this might be related to that of #2501.

#### Extra information

- [x] The formatted result breaks my code.
- [x] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-09-16T18:11:37Z - 5182588ea61183f658c572eb55f3f9cc926c263a

```fsharp
    { config with
                MultilineBlockBracketsOnSameColumn = true
                ExperimentalStroustrupStyle = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
> Sorry to be one of the new voices of issues post v5 🙃

No worries, someone had to do it 😅.

This one is rather easy to fix I think.
If you look at 
https://github.com/fsprojects/fantomas/blob/e1bd9638e60461020f803e443bab95c82c591211/src/Fantomas.Core/SourceParser.fs#L1773-L1785

We ignore normal update records as a stroustrup expression: `| SynExpr.Record(copyInfo = Some _) -> None`.
We should be able to ignore these as well for `SynExpr.AnonRecd(copyInfo = Some _)`. ([ref](https://fsprojects.github.io/fantomas/reference/fsharp-compiler-syntax-synexpr.html#AnonRecd))

Are you up for it?

**Comment by josh-degraw** [comment]
> Are you up for it?
Yeah I'll try and tackle it this weekend if I can!
