### ISSUE TITLE
dotnet fantomas does not work with > 1 .fsproj file in a directory

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#251]
I add the `DotNetCliToolReference` to one project and `dotnet restore my.fsproj` it.
```
>dotnet fantomas --help
Specify which project file to use because this 'path/to/folder' contains more than one project file.
```
The same error message is given no matter where in the line I place the project 
```
dotnet my.fsproj fantomas --help
dotnet fantomas my.fsproj --help
dotnet fantomas --help my.fsproj
```

**Comment by nojaf** [comment]
We don't support the older dotnet tool model anymore.
The problem can't occur with the global tool.
