### ISSUE TITLE
Sharpx.Collections/SkewBinomialHeapTest.fs lead to invalid F# code

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/fantomas#2512]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAdAdliEAuAngA6JgASiAhkQCKV6UA8A5ACoA0YzAMmAO4ALRJi6s0cALZFKAJwCWAZ1iYAfGAC8YYDly6K1NGzABlANaI%2BAITmZYEuZQA2%2Bojt0QAknkQSFh3o6KeG7uNIgK0GgARrCwjiEAvliQ7OBQCoh4eDYA5gqoYADaaRCg7lAAJIQkBZA2eCkluJAVAG5OAK7IaMXlEAAMqX1QHphImHjGcgBeyEN9ACxNEAC6TQnzpcuV1d1Q9Y3lLe2OXQW9fQCMm%2B6QALKUAB7cNojcwjl4AodXAKz92zWug2TTKtyqxD2kGE8AA8gAzF6YRDGQiOObbY6dPYXcoAJhuukgAFExgikRjhpBHPDIID1jcwUSITU0JAYnEfsyTmcetsIABmQnNUYZGR4ABiNicADkLIFkVz3HgZF16cDGZiWVCOY4lRAsaccfywAthQbjNJoIhLIh4bAZIgAAqySgSTKIGT63DwpwZdW4EG6JnNbW1XXew28oom37mqCWyjW232x3cWB8T3QSgZUatWDZ7LKb0QX2Of3lIGBzVHMNsiPCqPG4YANnjkETybtDsQAFUiCQZNnc5h84W5MX42WK%2B4qxAg7gQwa61AG1qec2%2BgB2dudm3dx0AYUcOYUh%2BUChVHWgeAdJbA08QAfnNfBu3DsT1jba2POJoAHLuVr7qmiB3D4USevej7PmAC5bLW771p%2BkY-kaf7DAAnEBSYgT256OJOJowZWDKglqSGrih34bhhVyDCaHbAQAgvC3gyOeEgSJQ95Xk%2BpEauRiGQh%2BnI0b%2BfLDJc1yMXuKY9sYPhyHAhGYNBfr8bOZHBhRInIWJ64STGUkErJLFsZ6in2CpRHDHxsHwVoumslRBm1rRklXEKZm4cxMiwB0YxhIE9jsbxqqaboc5wa%2BzKUXUEyoR5xlXGajEPI8HjwqwQiYMYAgOngADqcjwF894AgJ1ZCW%2Ben7Il4noZ55SXHG6VPFlOXCMS5YogV4olWV3zxi2lVaYJOnCS5CUNI10a4u4lxtu1mWYPCciPLCg70A6xKPEQjoKAoE5qfGW5jVF2mLs5UIHHNm4tTuK0AEqIHAMjwIN5XxgsF24NFjlLjsdUzUlRkLbolyAS9b0OvAModBIkEyAiXg%2BPk8aXA5sWhvFEgdI42QKogEoOtxWSeqwIn3XRLXYYxr3vfAdwE0TrykzI5Nhe20ACK6N6egA%2BnwpXldjNVxSDd2GU1KX4gxVIZX5MiUAQsIyC8l5fcNAF-asV0IbV03S%2B54MmniMmK08yuq%2Brmt4AjSOeqj3i%2BPeWNVS%2BEu4yD%2BOE3IxMc1zlPUzL83m6ZVI22rGtBCz-uB2T9Dc4xvP8%2Bxwui984uTUbt0NWHD3uHi3lW48ABq2LWGMuTa-e-562AAM48u8Um%2BCyUQ7geJpWXEqBTeJ3V-AtdZ%2B7jfN97rdSwXpuy13EB4m1Zc0LAeAAOKZHtB3hMdyh1-GDc59dU06tRhe08Xy2K6zAevJYhHQKYlgq0-mQKLCeVuogBGI6dxEaWPobSW001xz3DsMPET0qRyj4MTW0eBMzCCpiQMI61MByCLJgZiYxwJOxkBjE09lPYxSnsDUB59wFF10HiaGUdAg5EwP3TAg9lBTEYfQDojpWCwFGOMBgWD1K9SAU5U%2BokvwX2asXem9D2KYHoHIVobxlA5DwcjNBNhMEnUIcMEi41qq5xAWfNyHczbDAFArPo9xb4Um4G6KI8BKDHlgMdTAORYHEyETOS6E0T553EWDeeJoBSWysdvT0ch3QTCcAAaUQIgIgfDhB4FGC-SgLCda6MASQwGN0Ak0ykboAUkcrEP3SaYCkCg-IBTGHKS8iBma32JtvQ6e9MA6L6MQ-RXtDE%2BwoSY7kZi%2BgClLqU2Q8lHQ0EUNAeQ9h5HeHgL2DBygwjQBPCrQR8Yuk%2BIMX4ox%2BTJFy3cAKXuYT9oRKiQwRwqJ-IdEvKqIgqICDonCmqHJLdyH51mocheYABTLysXEhJGVHbIwRGUzAFTXgdPKAKERQMWjxTAaYoJ5jr5WJucpPAdwECUj6HonZ840grHmHUBQEpjoFBggkIAA)

#### Code

```fsharp


    type HeapData<'T, 'L when 'T: comparison> = {
        Heap: 'T SkewBinomialHeap
        Items: 'L list
        Desc: bool
    }

```
            

#### Result

```fsharp
type HeapData<'T, 'L when 'T: comparison> =
{ Heap: 'T SkewBinomialHeap
  Items: 'L list
  Desc: bool }

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-09-17T05:39:07Z - c1a99d498361c19f4e66b8877dd237275168d63d

```fsharp
    { config with
                MaxLineLength = 150
                SpaceBeforeParameter = false
                SpaceBeforeLowercaseInvocation = false
                MaxInfixOperatorExpression = 70
                MaxFunctionBindingWidth = 10
                BarBeforeDiscriminatedUnionDeclaration = true
                ExperimentalStroustrupStyle = true
                KeepMaxNumberOfBlankLines = 3 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
I think you forgot to enable `fsharp_multiline_block_brackets_on_same_column` as well.
See [docs](https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html#fantomas-setting-icon-type-orange-fantomas-setting-icon-fsharp_experimental_stroustrup_style).

**Comment by sergey-tihon** [comment]
Indeed, my bad. Thank you for help.
Who read docs.... 🙈
