### ISSUE TITLE
Indexed property setter

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/fantomas#2518]
Sorry, cannot reproduce it with online tools.

When I format FSharpx.Collections here - https://github.com/fsprojects/FSharpx.Collections/pull/194
Fantomas [removes space after property name and before the key/index and break the code](https://github.com/fsprojects/FSharpx.Collections/pull/194/files#diff-3c011bff4f10c1659142953f800c04c4fe66e2482149892d52a364df72bfc201L163)

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1197905/190890651-79ab5d28-fec6-4a82-8f7f-7ca9ca5b6c85.png">

Appreciate ideas how this can be reproduced inside online tool...

# Config

Latest Fantomas
```
    "fantomas": {
      "version": "5.0.0",
      "commands": [
        "fantomas"
      ]
    }
```

with following `.editorconfig`
```
; EditorConfig helps developers define and maintain consistent
; coding styles between different editors and IDEs.

; For more visit http://editorconfig.org.
root = true

; Choose between lf or rf on "end_of_line" property
[*]
indent_style = space
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[{*.fs,*.fsx}]
indent_size = 4
indent_style = space
max_line_length=150
fsharp_max_function_binding_width=10
fsharp_max_infix_operator_expression=70
fsharp_space_before_parameter=false
fsharp_space_before_lowercase_invocation=false
fsharp_multiline_block_brackets_on_same_column=true
fsharp_experimental_stroustrup_style=true
fsharp_bar_before_discriminated_union_declaration=true
fsharp_keep_max_number_of_blank_lines=3

```

**Comment by dawedawe** [comment]
I think we fixed this just [yesterday](https://github.com/fsprojects/fantomas/pull/2509). The online tool already has the fix, that's why you can't reproduce it.

**Comment by sergey-tihon** [comment]
Cool, than let close this issue for now, at least till next release

**Comment by nojaf** [comment]
Hello, yes this appears to be a duplicate of https://github.com/fsprojects/fantomas/issues/2498, I'll try and release a new version shortly.

Something to maybe add to our docs is how the online tool gets updated.
Ever commit on master triggered a CI build on fsprojects/fantomas-tools which will update the tool to the latest version.

You can see the exact version in the setting pane:
![image](https://user-images.githubusercontent.com/2621499/190896544-37c11e9a-8a9a-41d7-bdcc-17777343dbc0.png)
