### ISSUE TITLE
dotnet global tool support

### ISSUE THREAD

**Issue by JonCanning** [fsprojects/fantomas#252]
See https://www.natemcmaster.com/blog/2018/02/02/dotnet-global-tool/

**Comment by nojaf** [comment]
You can try an early build by downloading [the appveyor artifact](https://ci.appveyor.com/api/buildjobs/bqqsl9xtk3ew7gnj/artifacts/bin%2Ffantomas-tool.2.7.1.nupkg).

And install with 
`PS ~> dotnet tool install fantomas-tool -g --add-source ./YourDownloadsFolder`
