### ISSUE TITLE
Question about multiple function application

### ISSUE THREAD

**Issue by AlexeyRaga** [fsprojects/fantomas#2532]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6dYAqALAlgM5hFgBmsATgLYCGALvYvGLcYgB4AOi0T8AHQB2AG0T0wAN1oiArojABeMMIgRgYAGL5EI%2BAEYl5HXv0A1GfNVqI23fABMRsiccW5CgL7DhmHAWJaeHhAoTBOekpaMBF8IQUAI0pEWgBrMATECmSwaBFYQjiAczAuWmShYTEJaQ8jawgAZVhqRAARBloAYVghQkjZPioACgabLVdDZRd7c0tEMZs7PSdlZbd5sABKSAAacChCcXpiwlQwAG0D9Wu1SAASegBPHnPIOPo924gH2vlzq7jNQABn2QJ%2BAEkhEghPRGvgAF7IMHggAs3zAAF1bp4UTcgQ9nq80O9YV8Cfc-sg0IDwfo8eNIABZWgcAAycUQbMQQiK9Fw5LpDmBGOxNlxt1AFKJ1KgPPgAHkyBz4o1nmJBTZfvMARiIA4GVqAKLQpUq5F6qAiMiQUU4hlSxmPF6yyAJWCwESau6UnU0y0AZkNdyhR0o9G0QhkADlEAB3WLxb02AaIO3ih0Ywkut7uz3JqC%2Bjy68FgVHBn6NMrQRAAISyVEQAAVyrRWkxKAWIKn02oJTZHVrncSoHmvcHtcX-aWAKwVqBV2g1%2BvZLmwOOISjQNiIKGSWDbk69LtgHtAsV9zPSnMkscFyf-afggBs88gi%2BXDeSAFUuDwtzue4Hgw%2BDHvOZAyEcvYQP2aiDj6Mq5h645ZkWj6XJaADsb4fnWX6IF0IhsIQPR9AMQyduBkFpue9qSqhiG3sh95obKtJAgAHDh1Z4auTKINQmSUZaEEiFBtEZvR14jm6zETqxJbggAnNxS68Y2PT5EIJ6ieJ4wXjBV5Ooxo5yahVKKUC%2Bigpa748QAgmQHY9NQdAnme%2Bl0QODE3qZ%2BbyRZT5WfStm4SujaNAJ%2BBwFpOnUdBYCwfixm%2BbJ-nmX6GGlvoBqhQ5TmbpF1DRZ6YGWh5NgGYlRlDiZaUoRSgVZXSQZ5Wp9mULAsjQm0uj4MVHbuZQ8gJUlYDwT8w6uh8LFNex4z6OWtkshwEJkHgPKNLgVD0AA6vg8D8ieIoSZeUkpTJM0BZl802Poc7Laya0bUIRpiYgW07fth0CvOz4nZ5knedJ01ktdU7NVZr6PatQguBwCr-gwVBGtwySEIUZWlhxAOVV5cE%2BZdYMZRDt1qPo2EwwASrwVDwN9R3zqiuNqFVY0TYWdVXST6FkxA%2BhcdTtOUPA0ayIJm5KhCTDUGc876KNNUIal1CyCIJyJogmhUHQjCbtgObg7zlr6Cptk03AItMmrGuctrNAMINb7QLgrZ8JuAD6cYHUdivnbVqXc41N2WsKb4rR1URPAqlAcv0DO-ZaON%2B8DF2g58RtsaHIWlsyrKR7Q0ex0Q9BixLlBSzLcsmynBMg28qvq-gmv27rHYG68meWeMDi5bnBdF3H9DW03Lc647m4njArtRO7lBez7Aq18lAdExnPNZ6WDitbnK3uPItZxPAxQJyeyenYZ-vK2vs0h1vS276ymjdXwoFCIf0In4vJ7M8v42E%2BnW%2BpNQ4PUfhwNosB6AAHFxCoy4OjTGQhT7znPoDM6qdV6ujvF3IKPdoa7xts3TktZ8jQFSLWWeqRxCEAVEIRobYCKenFtpKi70-4c2zDJbBG9u42AcJTXOsYEzEPEBuHkHd2hZDiPgI8Qh7LQn4uXaupYKqs3xiva%2BWCzLB2AVvQW-dYhFCEM-IQr9ejwiMQwWQyRsCwChDCegIEsbgl0jRNBl8MGaKQulHRxst5mwMR2KMJxJBrl5IooSvUXBCBkW-ZRLj4oX2qlfSadVuG%2BM3uCAMNkCFN3NGyNsCR4DdHyIUXkQjNZxTYUk9mADvENSdHNQMOdwSQDgZufqPJHEiAANKIEQFwexXSoQUNoKYxOpZXHsLqUxHxjS75ZL7q0khYzUjmkIB1Lq0JYz9GYCPW28Q4EILiUNEaNSlapNSuk%2BZuisk72WeUcKyQ2hEGgJQfqcQGDMG-DE3ovU8itlkVUvSeMgZ1zTvUoBfiskP1ae095rRYQyDVJ1WQ-RhpcDVE8DUrCQVqLBRoy5N8cGQ3GAGUBrS%2BkDJWmXISSoVlCDWZyeJVlgQswgGzC5nMrnaJudCoEAZ8GtJRdFYeCALSTMSe4xKBxMQoneIQTQhRzhTM8EAA)

#### Code

```fsharp
// This is formatted as expected
let value = 
    { Field1 = field1Value
      Field2 = field2Value }

// This adds an extra line break before closing paren
let value = 
    SomeDataConstructor (
        Field1 = field1Value
        Field2 = Field2Value )
```
            

#### Result

```fsharp
// This is formatted as expected
let value =
    { Field1 = field1Value
      Field2 = field2Value }

// This adds an extra line break before closing paren
let value =
    SomeDataConstructor(
        Field1 = field1Value
        Field2 = Field2Value
    )

```
            
#### Problem description

Formatting for closing brackets and parens seems to be inconsistent, and I can't find any settings to control the line break before closing paren in a data constructor invocation

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-09-20T21:08:34Z - 11c2a862e2b3828627c19ea339f2db48d556e268

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello, Fantomas formats code according to the F# style guide. (see [docs](https://fsprojects.github.io/fantomas/docs/end-users/StyleGuide.html)).

There is no setting, nor is there any support base to have a setting that controls this.
