### ISSUE TITLE
Incorrect scope chosen for trivia, hence comments lost

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#2535]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXRBndAdATrgHYQQA8AAgcaaftgK4A2ehJtpAdAEqIAOTAIbREACgDkuAuIA0YSbgYAGJQDFV4gJTV2HMD35CREqUVnypytRu1s9EAwOFjckSyvXvrrua6%2BfIWxp7RyMXSAAOTgBGACYfMFco6IBmV00wAHpMsABhbgBBAAUwLDh6MHxYBiJ4AEsiAHMde31eJ2NXABYY%2BMhfSB7U9Kyc-OLS8sRK6tqG5rsQgBV8OoBbUQBtAB8LRQ8NMG2AXQyAXjBEAA8%2BRGhMeBaQ9rCTaTkFK3UtJ71Q5zeZg%2B-hsvw4-06bn23mhAQGIPSYNonBW6y2u0%2BB3ER1OYIoAD5%2BuAoFhEOh0PMsKgwJtiRBQHpIAASdAAT1u1MgDXQRMZTIAboImAxkGhaa0lDI6RxIABJWqIIjoADKdQAXsgpa0utKIMdpQBfLWkBkylns0VQbm8s2C4WW8X2aLGxkAWUEVwAMg1EJ7FY10AALG16OJKXVgfW0I3S020ZlsjloSCK%2BAAeQAZt6iIhlWymJqI8y7SLqY69LEXTKAKK1TPZwutSBMDOQCNR0gx2hx0gJi2cgBGsFgTBDvYFQtLYojEBSVfj8tJ%2BHQqgaQoAcogAO5MH1j2jofAi9uGqs9iB9pNQIcj-dQCf2sszsBdee95V8ZwAIUQGdg9CKQR8EENYyUQfA7wgQ9jz0DsIC7E0i3NK9IBvUc32LScHWfABWN8Lw-b9f3-X1YC3cDoEEUl5X5WBKIpWAiEgsBoMQE9ozPJDE0tVDh3QpCS2w1oADZ8KgQiRB-P96AAVT4W58Eo6iiFo%2Bi6kY5iMyFUl2M7Ti%2BW4wc%2BLvTDH2nVoAHYxMgCTECkkjciELAsFyRicCPe5-007S2Ng09Yy4-tkzQkyHynGlnwiazbPs%2BhXUQNYB3A7ymB0vyOICgyguvYyMLCoT7AATmiz9JOI%2BhXKYDSxK01LfI4OCwAQ%2BlApQkK8sEp9WmiSVnxs0rEAKDNMHwVy1jWQRmNY3T4P0s1DOC3KBKwrqnWdPqYvK3MErqOAqqYmqfJmpq5vjZCePa5azIi7rKw2gahpG5Udr26rn2m9K9My%2Bbst428OpW8ynTne7nAKKoangAARRBdzWOoRqmo96toRrmrAc97wWq0lVCzqgdDV8%2BvdK5ZQzJZA0VZVA3-dAAHU6ngINmPDT7Zu%2Bs7sa5XGAeu8sOGiPDiY9MmKcVas6up2mGaZ4MxOE1mGv87tWp461efC-naGiUThdJogMzqK40wUwR0H-asbnoZz1IOyLFdR5XEKylD1auzXn2iKy9d4cp4Bl5mxK6B3SDR07xy5t2%2BXxm6nSin27n-eB1wYRLwMzWVMDWKkxOiY70cxy8eLWZgKV3HNVH-CbyXApZ%2Bw1grQ2KvrfaT11S7qcvEEr-Bq8R6zoEDIDhBGgB9LdGeZ-Pw4vc7OSj21AdjiteqbEnweA1k03wb0cADuX7enjmI9%2BhezpjrXSFida149DfBC3ne6hwFO0-wDOs5zz2j5Vl3i47ruPc%2B613ru7RuHBYh3SbPfR%2Bu90DtxYJ3H0QCzb9z6oPYe9xwLj0nsGH%2Bzsfqux5mA1aFYQa3yuAANSwl%2BBo9Qmj72YhEEOeonYtT-vPYh0cl6XwgLEImFDVA1HuLbWhcwGG4OYsHfB7DCFqy4YvPmz5YhCwoVDWA6AADiZJLZ8GtlgW2jCxLMJkRjVWRl-okIJhA3Wa8AE%2Bi-FVaAABrL8wEXFkiwGmIgyoQKIEqqnO2rRappSVhlX%2BciLH8W4Uo1osRvZNk3DuBxZJyKKjrrcGGhsiAI1tgUWo8U35f1aB9MJX0Imc1%2BpdGJHs4nx2gbuRoRAhFEBEYxVUTSzYMHoEsWA8okBKjNrbFKoTHbhIIZUtqS0angNoLEZuDSRpECGfyUiTRClJXwFkhouS3IjJRqHNhZiOGLUsTM0hHAUir3sJABBFIGyehAgOeAghHKwAMU0JJXd9mmMLnPU50TFG1PsCkG%2BNzdHgXWIqdAQoADSiB%2BD9OhfKNxghWkH2CUdNmJ1j6zy5tUoFszSApCgTcxxaLnENiwODWYydsAPDuUgnMuj9G22KfYUpYzykTJPlMs5hKLm0BSOQslQFYqIChs-aAqx4bLIeDJHJjEYbQCEMBBiQT7AhIOaw8ZsjJkXWmQK6xQqBHgpuJC0CgymB5ghu5BgfA8ysgLD87FBdzHJjPuOC%2Bz4UiqJufC-gJNX6bMzOSoglKfTstDCoX57qcr8vPjwn1tibk2t2vAhAjZNVYrKfBYkxxjRciwKoAx1ItUgANEAA)

#### Code

```fsharp
test
    <@
      result
        .Replace('\r', '\u00FF')
        .Replace('\n', '\u00FF')
        .Replace("\u00FF\u00FF", "\u00FF")
        .Replace("8.12", "8.13") // CRAP score rounding
        .Replace("4.12", "4.13") // CRAP score rounding
        .Trim([| '\u00FF' |]) = expected
        .Replace('\r', '\u00FF')
        .Replace('\n', '\u00FF')
        .Replace("\u00FF\u00FF", "\u00FF")
        .Trim([| '\u00FF' |])
    @>
```
            

#### Result

```fsharp
test
    <@
        result
            .Replace('\r', '\u00FF')
            .Replace('\n', '\u00FF')
            .Replace("\u00FF\u00FF", "\u00FF")
            .Replace("8.12", "8.13")
            .Replace("4.12", "4.13")
            .Trim([| '\u00FF' |]) = expected
            .Replace('\r', '\u00FF')
            .Replace('\n', '\u00FF')
            .Replace("\u00FF\u00FF", "\u00FF")
            .Trim([| '\u00FF' |])
    @>

```
            
#### Problem description

The comment is lost; this is because the element representing the quotation brackets `<@ @>` is chosen over the element representing the quoted source simply by being first in the list, rather than being the most specific element, despite [the comment in `findNodeWhereRangeFitsIn`](https://github.com/fsprojects/fantomas/blob/5208057f3bb101d482cca9df64b371451a85a54e/src/Fantomas.Core/Trivia.fs#L28).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-09-20T21:08:34Z - 11c2a862e2b3828627c19ea339f2db48d556e268

Default Fantomas configuration

**Comment by nojaf** [comment]
The operator node in [SynExpr.Quote](https://fsprojects.github.io/fantomas/reference/fsharp-compiler-syntax-synexpr.html#Quote) should be ignored and not visited in

https://github.com/fsprojects/fantomas/blob/60fc9026e897ec67118a5f12410de070996173ad/src/Fantomas.Core/AstTransformer.fs#L221-L223

It is an artificial node constructed by the parser. Removing `visit operator` resolved the problem.
