### ISSUE TITLE
Setting fsharp_experimental_stroustrup_style to true results in invalid F# code

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/fantomas#2536]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAKogM4AuAOgHZWkCeADvgILzwBOJxAIqbGALxUIEYGACS8NAEtKFSsOEAhLFJzwZAcwByWdACNEbNGTaahCsABkZiAIzHSpyhrABfSABpwUYolKlNYlQwAG1vEXDhSAASOkZgyBlST0iIGIA3AEMcLGQ0MIthAAYvQrSxSiRZAGUpAC9kUrKAFlSwAF1I1yaIwpi4vKgklL7orJzBgrLbHotIAFlMgA9rSkRLRGdSAAsR6YAmIrbOhW7I0FGBhM34AHkAM1XEaro8PYUM7NzgqcL92Y%2BAFFKg8nu85jh7pBjl1Zhc5rEGINIHpYLAcOC0mMvpM2hAAMwAqIVXxsUgAMRk2S0iAA7jgbJjhI5cjDTnC2v0kQlUeimZ8Jj88WBmkS0tV6JloIhFIh7rAOAAFTJsTLoPyGJkQFmINnCM4KeEfRHxNAotEYokC775YUAVjFUAlUplcoV61gtMM0Eyvgq6VgPoCsEoWrAOr1EANwiNURNyN5ls52MFtrKYAAbI7IM7pbL5RwAKr0RhsH1%2BygBoNSENh%2B7ZXyRtwcy7cs2J-kpm2hYUAdmzuddBcQAGEcL7iCOQyYsNBeGw6w3dYUTvqWwiru2LZ3xt3fhYABwDyV5t0ceaIfSax31nCNlew87JzdQDtWru49MATmPLvz7qnHBaxvJcm2jXoNzbV9t3fXdP2mEphRzE9ECYe5SEMKd0HQTIwwjB92SfVtTWgvlYJxIV01sGYkMHf8OGqS8pDgIDQxAu9lwsVco3XY0X3NMjkzgyiDl-aU0IwthGPQZj0WA4V8K4x9DWfKCBKTUZhLTaZCVolCmDYWAsEqLhEAZGTJLwthWQItciMgkjElkHcKO0wpbFFJDFiWMR7gIbZNmqbYFVIAB1KR4B2MMjlsnj7L4tThnI1Meyoh0vOWXz-M2QEOKCkLwsi3ZHQzGKlMIlTiORJKhNc1LpizDKfMoe4pCWW5S0yedASWegOGIYgazY4UDzKhRuObeK434mrNLq-cFFsfsmoAJUQOA2HgQqosdZoxuECbwLAWMsRm5zkr3YVbCPVb1oVeAdCvNgHjEDD0CCR1bDA3jprU9BcACBk1nJBUcP8QwCG5C74Pcn8kLWjb4HmAHVBsEG2DByzs2gbYVSlSSAH1aQiqLvqm07EvO2qUoW4RDmzbyDNVWhbjYawyG24qRv2iBDp%2BinHNmhEtPqv4aPTBZliZzIWbZqQyEegxnvuV7Lw%2Bq6ycqhzkX%2BnBAbR0GuskyH4mhkS-n%2BJDpdl9nSGRvXUeBw3wYXbHcdVOdDCJkndk1mNVMFqm5pp4V9l0iXvIANRxRQZHUZxObDUa-YghLA%2BSM23IsfZPIj5ZyWMuchtjypNET3aeY6ZT-aqhIheNEXaYgfZ0rzpYuFgUgAHE-B6vrOCG8vuZT46A4TGDqcu9N9kaiOUaBmUgOgABrRQPeXvxiFuShqjVUd0V0Yb01ve9yrsrW0-HwTg6nsp9mWiWaXpGxZVIL1NhNxBTNaygpGDSgmCVAvE9dW6ZFLjWrqnX6jk3yTxhtnG6EsmAMg0JQAulAi4hlqKgrqWAOAEFgBUKopAupDUXBxEeJ0oDxh5BPG%2B8CFD7DhkgvWhhKCkPSB6ZwwClbfxkH-IaoCygn04hAiqNdta0OvsLeawp8SITng7J4lg1R6HgJkMcsBBrOCfgvchp8xHnwkZfKRGkZEh3TPicWZRIB90MFIdUshsgAGlECIHoEQzYpAKhr0yBgrmx9QKxUmhfaBV8zEN1kZYy2EtFDjkoMvJ4xADJGUqDSMgiAkbzxsH3fqg1pxWRsmfOKoSBbhJchYso%2BJw42MUCqeiX95bQFMDJdhGF4CFl-iGUy0Bxyqn-vo0RB1IGj1rluaRkTKmFHxLnGxdiWleOyC8QyWAZz0BeLQN4jpwHDPEVAspdcg7mNvtM1uNjXHuO8orQwDw4l%2BMSTYIR7kiiVz5uTah-FYH0PNhYfEs8bHLOYnbBAjRhQiLAt4doTREjEHJINYI4LXBAA)

#### Code

```fsharp
module Test

type AddressDto =
    { Id: int
      BuildingNumber: string
      Line1: string }
```
            

#### Result

```fsharp
module Test

type AddressDto =
{ Id: int
  BuildingNumber: string
  Line1: string }

```
            
#### Problem description

We just updated to Fantomas 5 with no problem. We wanted to use the experimental feature for formatting using Stroustrup style but Fantomas was failing every time saying it was producing invalid F# code.

The example above is a minimal reproduction of the issue.

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-09-20T21:08:34Z - 11c2a862e2b3828627c19ea339f2db48d556e268

```fsharp
    { config with
                ExperimentalStroustrupStyle = true }
```

**Comment by nojaf** [comment]
You need `fsharp_multiline_block_brackets_on_same_column  = true` as well.
See https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html#fsharp_experimental_stroustrup_style

**Comment by nojaf** [comment]
Hmm, well, maybe.
Can you create a separate issue for that?
There are other scenarios where you need two settings in order for something to trigger.
We might want to give it some thought on how we want to report it.
