### ISSUE TITLE
Comments in anonymous record deleted after formatting 

### ISSUE THREAD

**Issue by edgarfgp** [fsprojects/fantomas#2538]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAKogM4AuAOgHZV6lgCClslAnplsWALxUQTAAfMADFmpYQEN0ASxwtuYAOwAGZWAD06sADMxAWgDuiaQHMAFhUp9royqQDK0gF74uYACwAOAHRgBAX0gAGnAoYkRSUmlKE2JUMABtUP5kvkgAElIWAAdkNEho0mDUiAyANwkcLDzEkr5lEOtrSABJSiQ7Rxdipr53OoBdVP9GvlBejKzc%2BIK7Hqbyyur4pN6IAEZRiYBZCQAPABloxAPEGNIzed71gCZlQeGtsHGFzJyayDP4AHltI8pEPYsngrml0hUqjVVmsbk9mgBRdq-f7IOFpHDaSAPawjVIvZpvab5ABGsFgOFBpXBSyhdQgAGY0aU2uEAE7iaKVAByiAMOGOlL4pFZ1WxfFx1nxYKmH1J5MFi0hKzpHiZUHs2Qk0EQACFELpWYgAAoSVlSCKIVmCiDC0W9IY4p5SqkymZyiloxXLNDQ3oAVjVkA1Wt1%2BtghoOsCMrOgEnCbTKsFjUWY1rAtsQYogErGdUm7zdZI9eepSp9KoAbIHg9q9QbEABVbK5GNxxAJpMSFOUNPaSrhLNgHMpCaE2VFhWl721NZKaua2thw0AYRwceIy%2BYZBF0FI4d7-cz9seeJLrpJE89U9ps8885DdfDiG2iHQxMtB5wA%2BPjtPo-PUDupOELTr6TQAJz3ou9abjgqZqn2X5Hk0Drik6Z4Fhe8pXiBN5rOsDQqkGC6IPQ2ikJam7oOgEhphmg7Ds8GFEoBl4lrhyqzusmxETWob1vYr7SHAcE9ghh4Meh-6Yax2HsTSnH4bCvEkWRFGsoJMgifBKr0T%2BaF-q8AGQEBOEKeWXGMipIb0KysBYO0AAiiD8jI6l0SKyHWKh2ZSUZMmzEUZlljO%2BHuIGux7C02gEGYZz2GY4akAA6tI8AXGm9z6b5hkEsZhTAeZoXXAGRGRdFsVnPCSEJUlqXpZcaoVllKEnpKzEfAVwWgSq6xVmV%2BxtNo0h7N8LZduG8J7NkhrEMQ0g6beLXeW1ubSSxgWFSFYHWOsigRfsABKiBwKy8D1RlaruMtfA%2BUOfl5QFXXydtvV3gNezHad8Bclgb6Wr8LQUegcRquskm5dKAXoLgUT8gCoisjRkSWgQBbdXh1yQURX3hvA2yw7IxyI8j7mBtAZimlq6kAPoGGlGUQ%2B162dXMGOKb0dwHXstlmiw3yskcZAXY1KqeDdEB3YxzpQGOMzPaOHEWTCPGzpAkW8xI-OC9IZC-f9rKA8DoO9Uza3%2BRtMM4HDxPhqTqPoy9PWzjcylq5r2tC6QBPW0TCN212ZNERTVO7padMM5cZsjhbrNBU7mNNDcVlq5FABqNI6tE8DRCYItpuL0dMSz8tswnHNJ%2BFH3CA5u4LZQWftLn%2BdXRLYBSw9UMbQrrxK8VSelan%2ByObApAAOIRFNM0kPNzAt2Lbcd5DLoBaZ5fK5z-Wp4T8O6nB0AANY6mah8RMQ3yUPY5qwX9Ykqoh36tb%2BzOx4WcmK0VO18Dc%2B1ETyfLHD1KQIwZw0a5GcsNSg0huyMHxq%2Bd8rITazj0k-AyL9HobTXh-V6Lt3ru35CYSgNdKB12YI4QhXYsCGgILANoHRSBdnrp%2BR%2BK1n7mwweOd%2BvdP4qhuNjfB6lKCMLKCcZgJgXwGwgdEaB9ckFrAfl5W6q0Y4cLfsWbBzs1j0kItvX2KIDhSGJPACQq5YDzRiP-XezDFGS2UcXV%2BWF1HcJwVo1WaxIBT0tNIdAZwGE4AANKIEQNkOhvi2jHwkCQ0Ws4FFFxlvmTBbENGJ2sPSN27idRrkoAfFExBbL2XaDyMgiB8Y72OFPWas9KByN6Cg1haD2Fd04U4gkfcv4MhThk00j5DSOV1tAVk3jOQUXgA2KBzBnLQDXGabs1i4kdTUVtTRvR6RVzVp4wZPi7CVCBHZDgtpshAhYCCcSSF5kl3yD3VpPDZz0kHu4wJwTIr6wQb8TJkScnHBqU0Aii87HxLlo4pZKS%2BD0i3u43ZwlvYIFRPfCS2UhyhAGKMAoxBhDzXiLE-wQA)

#### Code

```fsharp
module Test

let Anonymous =
    {| FontFamily = 700 // font-weight
       FontSize = 48. |}
```
            

#### Result

```fsharp
module Test

let Anonymous = {| FontFamily = 700; FontSize = 48. |}

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [X] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-09-20T21:08:34Z - 11c2a862e2b3828627c19ea339f2db48d556e268

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello,

In https://github.com/fsprojects/fantomas/blob/dc8b277571f20c3935188549a65fc6a3539585ef/src/Fantomas.Core/CodePrinter.fs#L2565-L2568

There is an `enterNodeFor SynExpr_AnonRecd_Field range`, to solve your problem you probably want to add a matching `+> leaveNodeFor SynExpr_AnonRecd_Field range` after `expr`.

Are you up for it?

**Comment by edgarfgp** [comment]
Sure 😀
