### ISSUE TITLE
<Insert meaningful title>

### ISSUE THREAD

**Issue by ursenzler** [fsprojects/fantomas#2550]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAIgK5gC8YAOgE7kB2EEAPmAIJW31hMBCYsAZmADO6SgEsaAczZ16TAMLTpAG0Tow0SogCG6RAGUR4iUNJDF1GirXxiZHgAoN23QbGSKkABaIlS2OUgASkgAGnAoQVV0I0FUMABtcIhQDghIABIsXDjIcXRQpPoMgDctJUJkNETU%2BgAGMJq0gEkaJBp0PVEAL2QGxoAWQogAXUKAXz7koahMnEqoPIKakrKKuOrGgEZJ1MgAWS0ADwAZcURjxEl0TyWtgCZa6dGOCcKU3dnstEhL%2BAB5PinGj6LAqW4cFbleYbGp3HYQgCirQBQN60zSSj4kCe4x27whn3mkAARrBYEpwUV0qUoet0WAAMzwootSKUdAAMXEZQAcogAO5KM6UjgiCo4l546YZLJE0nkkUzGlrKr0-rMtJ6bBaaCILiIPiwTQABS0lC0AFtVIhKIqIGLEBL6K8OPiqbKcvKKczISqEvSAKwaqBanV6g1G86wfk26BaSItYqwOPRWA0O1gB1OiAu%2BhutKEz1k73S6mraH0gBswcgod1%2BsNmgAqthcJQ4wmaEmU6I0xm%2BGVItmwLmpstC98vYrfRXGmAAOw1uvhxuIORKeOCORp4SUQjQdBG-uDx01Z7OqXjj2T4vTsu01VzgAcS%2B19Yjmj2iAtxJtx6UQ5nribylteUBTj695%2BjCqQAJyvmGDaRtufjpsGA4AaeqTnjml4fGBJK3pByqzls9T0rWb6IMwfC6JQ24WhaWgZlmQGSiBV5zEWCrEeWdJzps2wUcuSGaHo36iHAqH-oB2HAa6oFcTePGliR-H3Ahuo0XR4kWpJ5J9sGrFyexCmcV84FEapfGPlsTLCVRzCULAhCtPgPiiHpdEsXuWEcDhI54QSBGLLxD7%2BgJ6oUQchxNHwAAq3g0HonhGugADqojwNcGaPGxF4cfhSkLO0d5qbZNSbEG0VHHFiWXAimEpWlmXZTcwaVnlJkFWZRUWbkpVhdB9KbNWNWxTQfCiIcfxtjoRoIoc2CaIIgi9mh9JPl1-nyXmin9aF1nhTBHCbIu40AEqIHAlDwK1OXBv0230AFo5gPmMwhYNR3DQJL6XddRrwDyhA-jaAJNLoFqxMGmzDm9H0ysVkAWoQSjREKwIckaTHoHR8VcUNpGVfBFFXTd8B7GjGNnNjlC495NbQJ4Zo6nRAD6-JZTl8NBe6yOHeO5URY0Dw1jFTnmpgfyUKcwj3e1m3PSMu1jn1RKCx8wsnfQdxCXO%2BxHJLWjS7LojCCDYOUBDUMwyNvOFcFyOo%2BjoiY4gdMMzaBPZET6mwnCFHG6bcvoFTrvu57OiMxRzOsweNqc9zNwO71TsHd9Qs2SLsL2QbMUAGrllw4jwEYCsZltqd7eZGuZ1r2c6xAdxRfnRwcq5B7rSXrTl8nGZPdXavp3X%2BR%2BxVqR3NVbeHPgsDoAA4qoi3LYgq3rRXwZV-luGO-z-UQT9xOT2N%2BfU27ZxcH40AANZcOat%2BqIIfzJZaa7kqDG1zhhsk7aZNfq24iWLOx16R3HOgbPkgpL6qBjJcH2iB3JTRoKIVMNBmCtC-FbO2c5jJ-x6gAkeQCyqNzAf9A2zAhQSBoB3GgXc0ydGoToQgmh4qwBaG0dAOh1oyT8i9VW719pyisiA36otSYUPRjaGg3DihRkkFg38lAkHiFQetHBjQf58JVv-Ye%2B9hEqVEcfDgDJyJn1dqiY4lpiTwC0OuWAa1JBQPdrwoegja7EPHjnVIDJ9aNEgCvG0nlLhcKUAAaUQIgbAHCQktHvloOhitv4njcYjCcllDEN1AXOBkgcDZXwSTfVEggnIuVaHyYQiBKbn3divFaa0dw%2BXFDvQKe8CwEUPkY-2Pi87%2BK4GaUSiDzYaE8tyXQ8AmwoLTO5aAG5zRoNcS0hGQjPFH26SY1u-jAliCtO0MorgXK7kINgAwmAwToRSUsvm7SBb1wJNrekDJp7%2BIiVEmKlslEAgKTQIpZwNGVVqMrMAr1rmfWRp0rJYiagMlPv41wkkw4IDRMkzC8NwjDD6LkQQHI1pxC0SAMYQA)

#### Code

```fsharp
type Du = 
    | A
    | B of string
    | C

let createString s = s

let du = B (createString "hello")
```
            

#### Result

```fsharp
type Du =
    | A
    | B of string
    | C

let createString s = s

let du = B(createString "hello")

```
            
#### Problem description

I think that there should be a space between `B` and `(createString "hello")`.
There is a space when `fsharp_space_before_uppercase_invocation` is set to true, but as far as I understand, this should not count as an uppercase invocation.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2022-10-02T10:47:50Z - d40a5bba96b2261a876ba5fcb5717db84f56b475

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello,

The style guide is quite clear on this: https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-union-case-expressions.

In short, when Fantomas encounters `B(createString "hello")` it does distinguish it from a union case constructor or a regular function application.
