### ISSUE TITLE
Stroustrup style not respected for a list comprehension assignment on a record field.

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/fantomas#2556]
See [here](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMiAeAhgLYAOmYAvGMADoBONAdhBAGKyyVgDa9TLA6n2aDRrAJaJ08LgCECdMAEZhoiAF9Va2gxFqWEqTKrzFAJi2jNu-Tv76Dk6XIVgAzJcHX7ou3oeGziauACyeAt7%2BAn4OjkYuigCs4SyRAgC6wuqQADTgUADO2FjijADmBag8%2BRCgopAAJFgAniTIaJClWLk1LI0AbgToAK7t1foADHn6kACSjEiMWADK4gBeyNNqIb0Q6b3qW7W7UE2tY51LPfUNgyNj3CcQSkeCkACyBHgAMqWI34hylgABbXNRKMwTE77CKvOpvM5tKqQQHwADyADNfoxEMsWpgwQIBkNRlVHvozK8iQBRBaY7GbJ4YDGQaEHOEnRotJEdABGHHQhL6txJDyZbipfXmRToWAkjCGADlEAB3dB-IUCLB0UZs2G9eFExEXfmwQWS4n3MlMkKSiCQZYkAjQRCyRAY2B0RAABQUxGwiDompY2t1ohhqQ5N25JoFwctpLQ5LUiTtUEdztd7s9-1gKsD0AIRXm-VghZKsEYwYgocQesjBs5xuRpvNTbuifGagAbGmHU6XW6PV6AKokNp0QvFxil8viSvVsAYoZFesaKMImMtuMWkVWpNMgDsfYzg%2BzXoAwugiwUL5WCqHoFhPYvl%2BhV%2BH2Y3o%2Bdt2b43unbJqIAAcJ4Dlmw6IO8iBELygaviudafvq0RNlufI7u2orWvoACc4GZkOOZ3ugC5pm%2BH6CBG67fpuv6Yf%2Bu4dmK%2BhKFMTL9pmACCGJYIGd5EEQBCLrWa5gIcdFGhhUCtgBLG4eCLycaekE5sssHiHAZFVhRSHiZJaE-jyslYTcCkHmxlIqRBvH8XQGlEFpZrkUyYkoQ2Rn0SZkBycxOGWeCEo2TxdCwMMCwACJSOITn2aJOrIdRX5edJDFQF08kBV2ohKLanGfHgswYgAKsCgLLMCnpYAA6uI8AgouUIebRqXCjJlzdP5%2B45YISipgVXzFWVgLUu%2BuJVbKdUNaCabds1yWoSwhrtelnVZT1wF9b2g1FYwGLiHgaITgQz50NSeAkF6BQFPOulMiBC0ZCly3oWtmXdUBTJKMeu0AEqIHAdDwNNjVpiET0sDREkbmlPkfdhm3fWB-2A568CKsMcGBpisz8UQlRpkoBmw6tPlEMM6AlOqOLsHQwlYPZJW-p9rHggRnEA0D8DvJT1N-HTDPxX20DAn6T6BgA%2Biq9WNSTUlkxcCPmdlW0CJCfaFdxdB0AQzRonQvwPqDs0PZDewvccxlK1crOKaIZjKTMWs63rBtG1gmPY3QuP44T33y219rNh0FNU%2BINOIILp1MyziNfRS1kzNruv64b4gPrz4eR9HjMISLYu6xLdDS7LoKB691vIsrCIWb16vBc7XwAGqirIpTwKUZQm4uj0V1b3k2118dsw7%2BVN3grARU%2Bd3twsXc9%2BD5tgNDhmV4P1e2yP9uCGYA0T5FsBYAA4tgF1XYgN13YvZv99Qb0%2BX52%2BBQ7O3O3zEd-LIZHQAA1rIRdf7YAKGiRgyx-SkSxvdfQ7lFqeXXnDWMTFn71xYGYX6MxlRqi-tgfMgJmZtGigdRg4gKyMG4gsGC3t-YwMSnfFawcOpPxVkjCkKNk7qjKIwKejAZ6VlWFw06wwvQlVgPMRYWBTp3UQuNehD8kFthYQnNQZgOYcPsgqEo-RczlCofBOgRDSikLujQtQlEkrPSWgPRBf5FG11VuKDi79w4Mm%2BMQXk8ACBXlgLdcoWDI4yKopY%2BB1jFa2I2so0QbgnZqEgOfQMsVASSPQAAaUQIgEg4iknzAAQQXhpt9DmLkVXRidijR1zViwNwSdYnfzyb-BkBRtbhQWMqB8iAeYf0jufa6t17wJTDHA1qCCwmlIiaPQQbhG61IUMRL0kUM7QDoLFUop0OkjhIZWaK0Bry6zIYEixUNLb3xKaZZBSiJkCDcOPWJ8TllECSUMPEYVhgPh1CQPEzQCRplgcE4ZoTGHvS3hcneVz96xLSRkwqXt9GYjqYwBpfxTG5QmMvVepNAWPzMvY1hag3Bv1ic8rSWB3gIEZIU-SLUJL5HSFsToBRWC3SqEU9QQA) for an example. I would expect the code to look something like on the LHS but it is reformatted to the RHS.

If you [remove](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMiAeAhgLYAOmYAvGANoA6ATrQHYSuvAPNvesBiAlonTxKYAEIF6YAIycWPMAF85CsB0bzVEAUJFUJUgEwqFyjavVct2wcNEGwAZhM8zVnpc1add-ZLAALC7cbl5sntY2uvb%2BAKzBbKFsALqQADTgUADO2Fj8TADmWag0mRCgPJAAJFgAniTIaJD5WOllrNUAbgToAK6NpaoADBmqkACSTEhMWADK-ABeyKMKAe0Qye2KK%2BXrUDX1A80zbZVV3X0D1HsQ0jvckACyBHgAMvmIr4iFWAAWpwppIYhntNol7hUHgcGiVIN94AB5ABm7yYiFmdUwALYXR6-RK11UhnuOIAolNkajljcMEjIKCthC9tU6jCmgAjWCwdDYjrnPFXGmOEkdSY5ehYARMHoAOUQAHd0B9eWwsPR%2Bgzwe1ITjoUdOdyVfsLvi0ITViKIJBZiQCNBEGJEEjYPREAAFSTEbCIehGiBqjU8MGsbba5l62EGnki3GXAk02KWqA2u0Op0uz6weU%2B6AEHKTTqwXN5WBMP1gAOITUhplnVn6rnR8MmwWqABsSettvtjudroAqiQGvRc-mmIXi-xS%2BWkT0ctWIKHwuH65HG0bY6bBgoAOydlM99OugDC6DzWWPpayAegWBdM7nVaDjLDdcOa8NMf5cbNNIAHPu3Zpn2iCPIgRDsj6D7oPOz5asub5slAUYbt%2BW7mjwACcgGpr2GaXug05JrOMFPtwwaLrWUKrhy65fi28aqNIIw0l2qYAIJIlgPqXkQRAEOWlYLkoVG6jRyF0c2AqMYCdysQewEZrM4H8HAhFlsRj7CUu7Aru%2BtGflJP7bjwQI4fanHcfQylEKp3JETSQlwTWr7UfpEmGWcDG-kxwryUB7H0LAvRTAAIkI-C2VZgnqmRKQvghblIccrT0dJPmAgEnbPHg4xIgAKr83yzL8LpYAA6vw8B-OWILOZRrlie5KWod5JncNIiasTleWFd8pKkSVZWVdV-xJm2dXkQlumIUcLStel7VsNIHbdS8kxIvweAIsOBB3vQpJ4CQrpZFkU4af%2Bk3xfBM1JXNJxpcZGEdXua14AASogcD0PAI01UmARXawFEiY1fLiS1j3oTS0gAW9n3ffAMq9BBPrIuM3FEMUSbSNpong81RC9OgeRKmivAuvxWBWfl75Q62gLYaxCMuvAjzE6THwU-QVPRZ20C-J6t4%2BgA%2BvKVU1XjYNWhGTTzfTMk8MC2UvIF9AELUCL0O815-WNl1S4lTXJfLRnQ0ScljDlasa1rOtYMjqP0OjmPYzDhu3cbRxEyT-Bk4g3O8z6tMwgrGVK8SrE25r2v8Ne7O%2B-7gd7XzrEC0LVlixL-we7ss2wqbXmLc9bCGH5VsvAAagKYj5PA%2BQFHr5Z-kDGzTXnd0Fw9ZsM0rWVvbwIW3udtdTA3TcA63YAgzpHde13qU94r3CGF1Fd4KFsBYAA4tgh3HYgp3nRPBv1aDRsE8lKFh0trCGKtVsc37HxiIR0AANZiOrH-YFkCJMLML0BEUYXVUE5KaN056XwbJ5KEbUS531emMOUioX7YGzN8EOiBwqbSYPwEsTB2JTDAk7N2YDYq5zUHpK%2Bkki5PRpIYOGYx2JKgKEwQeTBh6lnmGwvavRXT5VgJMaYWA9rnWgrBCBLkL4ywhtfJe4cV5M2YSTH00o8idEzIUEhkF6A4PyPg86ZCFAkUkddaRntoEfibHQ82ChHAsUfr7KkrxiDsngAQU8sAzqFBQf7CRcVgbtyofnAyNi4HFyFJbBQkB94%2Bkit8UR6AADSiBEAkGEYkyYX8CCcP1qoUxgS26QJCZ3MJC16GqEcJHMYr9cnvypFkQKwUphymvIgNmT9-b7xOmdK8MVAxSIajI-YcjaERMqfY8uMSDB4VdKFOO0B6CRXyHtDp-Y8GlnCtAM86sCEBMoTqKx5Sb4IIgI4fuYw4nLKIIknoGIgq9GvOqEgGJahYiTOA8xwzLGyOaoXCZdieCODXjE1J6ScqO10ciOpTAGkfGMaZIYU8Z74z%2BTQ2Bup4FCgfjEh5qksCPAQNSApWkz6KEyMkFYzQsi8DOiUQpIBFBAA) the record then the issue goes away.

**Comment by nojaf** [comment]
Hello, can you please open an issue using the online tool?

![image](https://user-images.githubusercontent.com/2621499/194234839-9a2d6ec5-e497-423e-be85-699fcd52d0df.png)

Thanks!
