### ISSUE TITLE
Idempotency problem when having a comment in an anonymous record and Stroustrup formatting

### ISSUE THREAD

**Issue by abelbraaksma** [fsprojects/fantomas#2566]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPMAvGMAD4A6ATmQHYRgCahYALAEyU10D0XYWiAZywdqJAL6QANOCgDsWAJbUA5gNRgA2jIig6dSABIsATwAOyNJCVYp2-QYBuAQ3QBXC5rt6ADNL17IAElqJGosAGUFAC9kP38IZi8wAF07MTidJMMTc3UrMNt4w2c3Dy14iABGDP9IAFknXAAZJUQmxBUsAAtCisrWbyTUvXS7XVqjMw9IDvgAeQAzFupEcJNMXoDHF3d1corWGoCAURDF5dikiEh0BcghtJrxrZzpgCNYWHRN%2BxLdtH28QAzEd9ME5BQsAAxJQuAByiAA7uhWj89FgKO4HiMnllJrlLB8vmioNtSnsrixQddwqYnNBEAAhRALWAURAABScFCcAFtsIgKCSIBisfFhnRRnpnvZXnkid9QcUdmVKQBWalQWn0pkstltWCIwXQJxyYIOWAmxSwajCviYxDYyW4or496fRV4v6qipgABsmsg2oZzNZ7IAqqZzBQTWbqBarQobXaFi45E6IFK6DLrm75R6ScryQDKQB2QPB3VhxAAYXQpoENZtQkx0CwbJTacd4seYzxcsJBaVZP%2Bnl9AA4K3SQ3r2XVELy3oLO%2Bh0z2cX3XQOoArCyOfRUAJxTnWh-VN9DJzWp1fd-wSzMuibbyC74feim%2Byq%2BSlB6eIABBBZ%2BAoJteV5Jw7VFO89AfMAs0yLcpnzYl3xVT8%2BmqX9KzPdlwgXBQ4EvW1ry7DN4KfF5kMHVCvXQksv0ObD-yAkD8N5QivivSloPIhDiH7aidyHOjizHPoQWYnUAIoWBXBCAARRAUQ4kCoIdPjKNlIT8hsNCxMBfxKmYQMGlwQIFgAFS6Dpwi6NksAAdQUeBujtQZ12dTdnx06w9w-Bi%2Bg1X8zIs6yOmOW87Ic5zXJ6TU-Q8%2B9e2lQSCSgPz9NHQy9EqAMQsaYIFgUXA5mjJx2woY5cFMdkBAEJMSMpccktglLszS6ZMtE7LKUqcsCtwAAlRA4AoeBYrczVmFaug4P4nNSRfbrXQC8T4kqSdBpGsb4DhVxF0FRZAn4Xk1E1SpNO8qj0sgXlXHQRQURWKE2QgrAQMs5CsoPDbj1-Ha2XgOoHqe1pXood61MDaAum5ekQIAfURFy3Ku1KkNulaJjWnK6AGUzGhknljDmCgWiESb4ua2aIHmrTc2Wgofow%2BJWCw316iJigSbJimsH2w6KGO07zr69GOsx6Z7sehRnsQCGocFL7chZwK2aYzniacUnyYUIQQdl%2BXFYq6Hf1h%2BG20FZHUZ6CXEJ8rHmZ637-FYSTObMgA1FVGSUeAlGUKm7Ra%2B2BKlvJsa2XHKVYEzBqheS20av2QkD4PptplJ2odm6uud1b6PWt3gs9xoFNgLAAHFsGq2rBAam0M5psPFuyHS3xd1m3fyz3Qbl1pGUvaAAGtGR5UfsAEOZqHCPlay%2BA6mt9XjPMfa7tNuzvC4M2OBs5hFkUH7AjQ6FXECU4rqAUa1qAAkJ5yFsWV40teKI3xmO5Enfet9Vgtq1iiZQ1BE7UGTjaSIwCKquHZJZWAwRQhYAqo1Fca5kobgxo7d0tEf6uz0Kwf6gCQLUGQQ4A0KhH5LgoJfJQN9GrPwqDeNBbUMGSywShT0uDu56CBD%2BPussLhND5G8eATg6ywAaioQ%2B8tUEwTmjncO7CaKcJxkXPGEAgQcwqJAOugoFD8jCC4AA0ogRApgEEdCwMEceTgwHU19EwuRdMFFtzzMo-yajKRAk1tooetiR4XAEDJOSIQERCEQMDfu8s651UbtQBh8RV7oK8pgvOHCPG719ECD2vjuS4QvvraAFB9Gwn4PAcM18bRKWgPWHkt9ZGt06uktWxceHx05ro4pBikHoDWLJVwLZXCmDWMYDYmokksJSWwtJlgo6-E8Vk0u2iTFmLMoLKhiw-HUACa0BJRlvBZ3ph-JaX8cGqMyRUIEvdtF9MIlgOoCBLgOLIm-MQMhkhxCsAIKEDV1COJAGIIAA)

### Original code

```fsharp
let x = {|
    Y = 42
    // test
|}

```
            
### Formatted code

```fsharp
let x = {|
    Y = 42
    // test

|}

```
            

### Reformatted code

```fsharp
let x = {|
    Y = 42
    // test


|}

```
            
### Problem description

Fantomas was not able to produce the same code after reformatting the result:

* Having a comment on the last line of an anonymous record leads to an extra empty line being added each time you format
* This is a relatively common scenario, i.e. using a comment temporarily to disable a certain field

### Workaround

Just don't do this in code.

### Extra information

- [ ] ~The formatted result breaks my code.~
- [ ] ~The formatted result gives compiler warnings.~
- [x] I or my company would be willing to help fix this.
- [x] Breaks Husky integration with precommit hook, the last line "walks down" on each format

### Options

Fantomas main branch at 2022-10-08T06:02:14Z - b0eea044f22051d63093de52b73fdd0d7f1a32eb

```fsharp
    { config with
                MultilineBlockBracketsOnSameColumn = true
                ExperimentalStroustrupStyle = true }
```

### Related example

A minor bug happens when `Stroustrup` is off. Note the comment being outdented and the closing `|}` bracket one space too far. Not sure it's related, see [example without Stroustrup](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPMAvGMAD4A6ATmQHYRgCahYALAEyU10BaTZkAzlgoBLagHM%2BHWhABisWL0gAhAIZVIUugHotYLIkFSSAX0gAacFH7Ysosf1RgA2pYig6dSABIsATwAOyGiQoljmrp5eAG4q6ACuQc4RHgAMFh4ekACS1EjUWADKwgBeyOkZEMzJYAC6EcblbtXefoGOIfnhFd4x8YkuFRAAjI0ZkACyKrgAMqKI04jiWAAWXYNDrCnVdR4NEe5jPgGJkIvwAPIAZrPUiAV%2BmGuZ0bEJjgODrKOZAKK5VzcytUIJB0JdINt6qMDs9WicAEbydBPSK9N5oD4VADM308OWsFCwMlEsQAcogAO7oOYojxCBKQ3bQ5pHNrBRGwZG4nqvfrAli4kEFfwqaCIJSIS6wCiIAAKahUAFtsIgKLS6PTEIy6HsPDDInD2hyuSy0XzBmAAKyCqDC0XiyXS%2BawCmq6Aqaw5KKwd22WDUdUQTXaiC6uj6kGshFI9U8vrvfkANhtkDtYolUplAFV-IEKO7PdRvb7hP7A2BLrFrCGwGGmt0o0aY9yXvGMfyAOwptMOzOIADC6A9-H7-sEFDi0Cw0vLlfQ1YqOx1zIbhvZzdNvITFoAHN2RenHTLxohFfDVbOq1rF1D9iy11BjbHW%2BikhaAJz7%2B0Zp2j9Blm05wXDIl1DFdDgfSAnxbM1t3WNJ%2BVTA9EAAQUufQKFHRVFRUctgxvJk71XY4m05Z9YPbC0hhGRCex-GUClPYQ4H-ANAKvGs62Ie8SPXMiYK3Sj1i%2BWjkLQjDGMVZjOQA-l8JA289R4tlHw3BsKLfdYcVE%2B0UIoWA4lyAARRBqSkjC8Ina8FMIpTiJUjowgEttNIqIZmBTSZcCyS4ABVlkWAplmlLAAHVhHgFZyy2AjlyIiDeKgUJyME1yMiGa1EK8nz-MWH55zuYLCXCyLVhtRMYpsuK7IShzkuc19MXS5MsqmHJLmEXBzjzFRpwoH5cH8GV%2BH4Us2P5HdKo8UDa3A2FEsclKXKajwhi7VrcAAJUQOAKHgEqoptZgproGauIjKBG2CerN2W-khj3Dbtt2%2BBSTiM9VSuLJ9EVBwbSGTi5oNBbFTidBbGpW45AoHCsAw3ySIa811k-RDnuleBxjBiG5mh2GLJTaBlgVKdVQAfQpCKosB%2BL5rqzokbgipNk8qY9IoFRfHOChZkEA6yomk6IDOoHI0gm71NSla6FYGiLQmNmKA5rmeeEQQ3o%2Bigvp%2Bv77ppmq6ZOUHweESHEDx3r4cR27Gv5VgRPl9nOe53msCxk2zYtuGL0J4mOdJigKap1Z9fDZSTglw4NOliBWG0%2BWvIANV5JRRHgOx%2BfLSbQ-rWqI4Zm3keZjyNpkQypzG1Pcgz4Py2OnPuPs-OnMLpmMlYTKE6mIzYCwABxbABqGgxRv9TObWz2KwNp4GHOg1uhOZlqE%2Bx025iUf9oAAayUf2t%2BwfhzmoAolQHTl3vGi0gOs6bFLDpvSJNSW7otVh1vl8kqXX7BXUWBHAhMh1agwg-TUBQrkE8mtdYWnkrfWy9886PyWrbV%2Bj1HbUjENQMu1AK7%2BiKJg3qcQZS%2BVgDkPIWBepjUvAVBuF0WgLXns-FBnxUboIwtQShURnTiEgeeCggDRAgLGtAwY19aHhyQYzReGQsQIRXibQE0wlTwngCoQcsBRriE-mbahwE4HVQQYbSRC80oeCxHLQYkAh6qmEMqfIsQADSiBED%2BDIYsLAORd4qBwQLK%2BHEp6zRnmLBhako5S35FiB2liN7eK3oCfgekDK5HJIIRAmNV5myHsNUe1AREVFgadO%2BucjF8SfmEl%2BgwsTx2iWoeiiAjJq2gCIKSHD9DwCzMA-0JloBDg5qA3RN9CnwOKbPaM-ETExzAFiEu8trHNPcbEe4%2Bk4jjjiP4e4vhHjsRoQE86EjroFyYUXGRndLFOJcV5DWfCrgxOoHEuYeT0opCFrUIpjdEGlOQccsxy9LFLOYm7BAQI-E7KqqGSwNRyghH4DIUajgxHGCAA)

### Without Stroustrup example, before formatting

```
let x = {|
   Y = 42
   Z = "string"
   Foo = "Bar"
   // test
|}
```

### Without Stroustrup after formatting

```
let x =
    {| Y = 42
       Z = "string"
       Foo = "Bar"
    // test
     |}
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub> *YES* 😃

**Comment by nojaf** [comment]
Hello, thanks for reporting this problem.
The root problem is with [fsharp_multiline_block_brackets_on_same_column=true](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPMAvGMAD4A6ATmQHYRgCahYALAEyU10D0XYWiAZywdqJAL4jIAGnBQB2LAEtqAcwGowAbVkRQdOpAAkWAJ4AHZGkjKs0nQcMA3AIboArpa339ABhn79SABJaiRqLABlRQAvZH8AiGZvMABdezF43WSjUwsNa3C7BKMXd09tBIgARkyAyABZZ1wAGWVEZsRVLAALIsqq1h9ktP0M%2Bz0643NPSE74AHkAM1bqRAjTTD7Ap1cPDQrK1lrAgFFQpZW45IhIdEXIYfTaie3cmYAjWFh0LYdSvbQBwSAGZjgYQvIKFgAGLKVwAOUQAHd0G1fvosBQPI9Rs9slM8lZPt90VAdmV9tcWGCbhEzM5oIgAEKIRawCiIAAKzgozgAtthEBRSRBMdiEiM6GN9C8HG98sSfmCSrtylSAKw0qB0hnM1ns9qwJFC6DOeQhRywU1KWDUEV8LGIHFSvHFAkfL5K-H-NWVMAANi1kB1jJZbI5AFUzBYKKbzdRLdbFLb7YtXPJnRBpXRZTd3QrPaSVRTAVSAOxBkN68OIADC6DNAlrtqEWOgWHZqfTTolT3G%2BPlRMLyvJAK8foAHJX6aH9Rz6og%2Be8hV30Bne7j%2B27B1BFUXR77KgBOae6sMG5voFNatNrnsBSVZ12THeQPcjn2Uv1VPxU4MzxAAEFFn4Chmz5PlnHtMV730R8wGzLJt2mAsSQ-VUv36Go-yrc8OQiRdFDgK87RvbtMwQ59XhQoc0O9DDS2-I4cIA4DQIIvkiO%2Ba8qRgijEOIAcaN3Yd6JLcd%2BlBFjdUAihYDcUIABFEFRTjQOgx1%2BKouVhIKWx0PEoEAiqZgg0aXAgkWAAVbpOgibp2SwAB1RR4B6e0hg3F0txfXSbH3T9GP6TU-3MyybM6E473sxyXLc3otX9TyHz7GUhMJKB-IMscjP0KpA1CpoQkWRRcHmGNnA7CgTlwMwOQEARk1IqkJ2SuDUpzdKZiysScqpKoK0K3AACVEDgCh4Di9ytWYNq6HggTczJV8erdQKJISKopyG0bxvgeE3CXIUliCfg%2BXULUqi0nzqIyyA%2BTcdAlFRVZoXZSCsFAqyUOyw9NpPP9dvZeB6ke562jeigPvUoNoG6HkGVAgB9JFXPc660uQu7VsmdbcroQYzKaWTeRMeYKFaIQpoSlq5ogBbtLzFbCl%2BzCElYbC-QaYmKFJ8nKawA6jooE6zou-qMc6rGZgep7FBexBIehoVvryVmgvZ5iuZJ5wyYpxQhFBuWFaVyqYb-OGEfbIUUbR3pJaQ3zsZZ3q-oCVgpK58yADVVSZZR4GUFRqftVqHcE6X8hx7Y8apVhTKG6EFPbJr-dCIOQ5munUg6x3bu6l21oYjb3ZCr2mkU2AsAAcWwGq6sERrbUz2nw6WnJdPfV22fdgqvbB%2BW2iZK9oAAayZXkx%2BwAR5moCJ%2BTrb5Duav0%2BK8p8bp0u6u6Lwy48GrnERRIfsGNTpVcQZSSuoRQbWoQDQgXYXxdXzT18ozemc70Td76v1WG2trVEKhqBJ2oCnW0UQQGVTcByKysAQhhCwJVJqq51wpU3JjJ2Ho6K-zdvoVgAMgGgWoCgxwhpVBP2XBQK%2Byhb5NRfpUW86D2qYKltg1CXo8E930MCX8-c5aXGaPyd48BnD1lgI1VQR8FZoNgvNXOEcOG0S4bjYu%2BMIDAk5pUSA9chSKAFOEVwABpRAiAzCIM6FgEIE9nDgJpn6Zh8j6aKPbvmFRAV1FUmBFrHRw87Gj0uAIWS8lQiIiEIgEGA8Fb13qk3agjCEhrwwd5LB%2BdOGeL3n6YEns-E8jwpfA20AKAGLhPweAEYb62mUtABsvI75yLbl1DJ6sS68ITlzPRJTDHIPQOsOSbhWxuDMOsEwmwyJ3iaZHKw0c-heOyWXHRpjzHmSFtQpY-jqCBLaIk4yPhs4M0-stb%2BuC1FZMqMCPuOj%2BlESwPUBAVxHHkXfmIWQKR4jWAENCRqGgnEgDEEAA).

`SynExpr_AnonRecd_Field` was chosen as the trivia anchor (content after). In case of a normal record the closing brace would be picked (content before).

The braces for anonymous records are not picked up as nodes.

Regular record:

https://github.com/fsprojects/fantomas/blob/4f4d646468d49f3307c47a7dc7261f36ee383576/src/Fantomas.Core/AstTransformer.fs#L257

Anon record:

https://github.com/fsprojects/fantomas/blob/4f4d646468d49f3307c47a7dc7261f36ee383576/src/Fantomas.Core/AstTransformer.fs#L268

The `StartEndRange` active pattern captures additional ranges for the tokens. (As the range starts and ends with these included).

In `CodePrinter`, trivia attached to the closing brace (in regular record instance) is taking into account the leading trivia:

https://github.com/fsprojects/fantomas/blob/4f4d646468d49f3307c47a7dc7261f36ee383576/src/Fantomas.Core/CodePrinter.fs#L2538

A similar thing could be achieved for anon records.

Are you interested in submitting a PR?

PS: As for the other problems, this is a known problem and won't be solved by fixing the idempotency issue.

**Comment by abelbraaksma** [comment]
@dawedawe thanks for tackling this! You guys are too fast for me 😆.
