### ISSUE TITLE
Issue using Fantomas 5.0.5 Nuget package in an fsx file

### ISSUE THREAD

**Issue by njlr** [fsprojects/fantomas#2567]
I am not sure if this is an FSI issue or a Fantomas one. However, I am able to use other packages so I think it might belong here.

To reproduce, first create this script:

```fsharp
#r "nuget: Fantomas, 5.0.5"

open System
open System.IO
open Fantomas

printfn "Hello, world. "
```

Then try to run it:

```bash
$ dotnet fsi ./Test.fsx

error NU1202: 
  Package fantomas 5.0.5 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). 
  Package fantomas 5.0.5 supports: net6.0 (.NETCoreApp,Version=v6.0) / any

```

Environment info:

```bash
$ dotnet --version
6.0.401

$ lsb_release -a                
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

**Comment by nojaf** [comment]
Since Fantomas v5 there has been a renaming.
`Fantomas` is now the name of the dotnet tool.
`Fantomas.Core` is now the name of the library.

**Comment by njlr** [comment]
> Since Fantomas v5 there has been a renaming. `Fantomas` is now the name of the dotnet tool. `Fantomas.Core` is now the name of the library.

Yep, works. Thank you!

```fsharp
#r "nuget: Fantomas.Core, 5.0.5"

open System
open System.IO
open Fantomas

printfn "Hello, world. "
```
