### ISSUE TITLE
Columnar alignment

### ISSUE THREAD

**Issue by anchann** [fsprojects/fantomas#2571]
I would like to implement columnar alignment in some simple cases. Before I spent time on this, I would like two things:

* an in principle agreement that should I come up with a sensible implementation that doesn't complicate the code too much, and leaves the default behaviour unchanged, the change would be welcome
* any guidance or concrete examples about how one might maintain state in the context when iterating over fields. I read the current code (genSigSimpleRecordAlignBrackets and friends), have some idea about how the basics work, but if somebody in the know could give me pointers as to how they might implement this feature, I'd really appreciate it.

Thank you for reading/considering this.

The existing way of Fantomas deals with this problem is not aligning things.

## Pros and Cons 

The advantages of making this adjustment to Fantomas are that people like me who want to reduce the mental overhead of reading code can capitalize on bringing out otherwise hidden structure through auto-formatting.

The disadvantages of making this adjustment to Fantomas are that it will complicate the formatting code by forcing one to maintain additional contextual information.

## Examples

```
type Fruit = {
    Size:  int
    Color: string
}

let banana = {
    Size  = 12
    Color = "yellow"
}
```

## Extra information

Estimated cost: M (I guess) 

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [yes] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md).
* [yes] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [yes] This is not a breaking change to Fantomas
* [yes] I or my company would be willing to help implement and/or test this
* [no] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [no] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Hello,

This falls into the category of [What we are not looking for](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#what-are-we-not-looking-for).

Your proposal introduces a *[vanity alignment](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#avoid-formatting-that-is-sensitive-to-name-length)* problem, when you add a record field with a longer name, all previous record fields are impacted by this. Leading to a larger source control diff than is necessary.

This feature has been requested in the past and is considered a bad practice.
