### ISSUE TITLE
Comments get removed for method parameter with attribute

### ISSUE THREAD

**Issue by stefan-schweiger** [fsprojects/fantomas#2585]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAspgCo54C8AOgHYQQC2idARogE5gD6AdIfougAsE1WqLAAKEWOkBtADyEAgunSsAlkwCu6RAD4AumDVVs2xWgDOq4wHMIAentg6mIye1TpASk9jKNaTBsdSp0ADM3U3RFal8GZjZOHkw%2BQQQAJl9RSQDA2mMo8zArELswR2dXAo9csR9a0X884ONwyLNqSAAacCgLfnRbC1QwGV6IUGlIABIsXBHIVu7x2hmANwBDABtNZDQxvIAGHrzIAEkqJFCAZTUAL2QTwIAWFYh9FYBfJ4m3qFnSAslj9VtNNjs9qM-hAAIwg0SQfAbAAeABljIhUYgqDZBMs8jD0oc-h9RN8VpMxDM5pDINj4AB5MLoqiIa5YLaPP7rba7EYHQLpeGrACilyZLK5py2YUgJK%2BIMpCIB8zQkCYsFgW3xVLBvMhAukAGZhRBzlR%2Bqx0AAxYzbAByiAA7lsMTrpKpdvKyYruSraRqte7QeC%2BftoWBnqaoNdsBtoIgAEKIMKwViIAAKG1YGwYOlYwdEnsQ3to5NEStBNIWge1wp5EP5EYArNHILH40mU2nMbAnWxoBt%2Bhc1rBB4NYFRC7Ri6WIOXaJWzf6a5q637QwaIwA2NsdhPJ1PpgCq2FwrEHw6oo-Hakn04gYW2-TnYAXvymK7VtenDbDULyAB2Pc4wPbt0wAYS2IcLAgycSk0aB0DTB8wCfLYX2kUky19T9q2-Ndfz1RtwzyAAOEDO0PHs%2BASAto3QzCxGw%2BdcN1fCoB-etiP-Q0xAATkosCj0QOCtnvBjnxLLCFQpP0OPVQjuM3JsCWOCN21AxBFDCfM4LoOgNlQ2cZJ9OS8MBAig2U-VVMCGE4Q0-cuxE65GDUOBxKnSSMOk5jZIreTLM4pSN1s0j7KFJytJ0-M3LoDytQkiMTP8szAos1UQussKSIA%2ByTWiztFFYWBNEuAARRBXQS-NjNYL1TJw8z2OCxZQiIlSIukGEow0pFkTOMIiAEbFriEK0AHU1HgPFo2JJrWJa5UFOBXLeIjGFW36lEhpG7ERV88a03QabZoEVDtwWtLmoy1qsva9BOvC-Ket3HbBqoMI1GRBlzw2ZDWBFZFgkQCwLDvbyIzI67RBYt82JWtq1s-LrXrEGFgI%2BgAlRA4FYeAzrmiNnlh2h4ffMAl3%2BVaOpsvK%2BNEGEKJxvG03ge1NDopkzh0OhhmjGFX0p6nqTauhNC2QZXVZa000MlQ2BIeZ6Y2glBI03H8fgfBJeljE5dYBW6rbaABGzeN8w4J0ZrxYXEarZG6fWrc8iJNsBpKnNMAZVh0SsImLujGH7eWx2HpR3U0cZ2h0kc05PdYb3ff99BOe5sJecYAXNtDu6kYeiWpbUGXEEN42lcBVXXcFKLTi9jYfb9tQrF14vS-LgGTY0s2LaQthrdti688XIKI%2Bd1GXpjiB0kKhOUQANX1RNjHgWxA9QkPFoRsPl1pp7q7s6R0j6%2BfkWtcqkMhlfLnXofUNJkeP3u2lI%2BVaOI3Sbaz4q2B0AAcX4MDUG4NIYb2DmTd4AVR6ZQDKFSeDNP7vQTnrEuGJEziWgAAa0TDmbB-ALAMioNcXMoktRcyhnkRifk4bQOfgXOBOUEFq0FFjU4joXToP4P2bEytEBVW%2BlQNQE4qCKEuLRFgrAc55FSrQ9KMCX6riYVHKen8Wb11dDYKgF8qBX0nLcLRANNDpiILAC4Vx0AA0hqhahT8qZj0YeuZhNdj4aw0fmKgVi1i9hxBItgAjjDCMhtIwItjt4iwcUopxKjEF5CNOpFBxdJSolzEweAGwoKwAhjiDhpcbFSTsaLL82Vonv1UXE%2BOgRIDALYGoBgoRtgAGlECIGwOY7E6ALi4I2LooOEYwk3SWvncOjjnqxMCEaOuVSME9KwZKCwJUyqXEdFYRAOtUGl2AemUB8F6qNUGTvYZe82pcRdkfMQRo57TOzNRdMFUW7QHUAlTxOh4DHiEZOKq0BoI5hEfk3yhTIlWVKSGcpEzT5VJqU8jp2x2SlU0AhbA7JMCcn%2BUxORt0FEMKBBPGJLDjTfyqc01pA106SKZDMqgcyMQhJ6ocSBYAKYO2OQ9U5zjzmiCNMgqpcKPLoHwAgKUoSCnhN6PoJ4iwLDWghiMWxnwgA)

#### Code

```fsharp
type MyType =
    member _.MyMethod
        (
            [<MyAttribute>] inputA: string  // my input
        )
        =
        printf inputA

    member _.MyMethod2
        (
            inputA: string  // my input
        )
        =
        printf inputA

```
            

#### Result

```fsharp
type MyType =
    member _.MyMethod([<MyAttribute>] inputA: string) = printf inputA

    member _.MyMethod2
        (inputA: string) // my input
        =
        printf inputA

```
            
#### Problem description

If you have a type method with an attribute and a comment afterwards the comment gets removed. If you don't include an attribute the formatting does not remove the comment.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2022-10-14T16:59:37Z - 35f093ce1b8a19d9e9ade3da2c0f855923d8a106

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by stefan-schweiger** [comment]
@dawedawe I just tried to take a look, but it's a bit unclear to me if the problem is with it choosing the wrong node to attach the trivia or if it's because the trivia didn't get printed in `CodePrinter`.

If I look at this code:

```
type MyType =
    member _.MyMethod
        (
            [<MyAttribute>] inputA: string,  // my comment 1
            inputB: string // my comment 2
        )
        =
        inputA
```

I see the trivia node for `// my comment 2` is attached to the `SynLongIdent_` (`string`) node, but for `// my comment 1` it's attached to `SynPat_Attrib` (`[<MyAttribute>] inputA: string`).

Can you maybe give me any pointers in the right direction?

**Comment by stefan-schweiger** [comment]
Ok, I think I found the problem. It is in `Trivia.fs` there should probably be this line in `visitLastChildNode`:

`| SynPat_Attrib when not (Array.isEmpty node.Children) -> visitLastChildNode (Array.last node.Children)`

When I add this the generated code contains the comment, but for whatever reason also an additional space. Maybe any idea why this happens?

**Comment by nojaf** [comment]
Hello Stefan, thank you for looking into this problem! Much appreciated.
You are right to add additional cases in `visitLastChildNode`.
In your case, you can add `| SynPat_Attrib, | SynPat_Named, SynPat_Typed` to the first case.
There is no need for the `when not (Array.isEmpty node.Children)` bit in this case. There will always be children for those nodes.

![image](https://user-images.githubusercontent.com/2621499/196668298-8ef92520-e4cb-4416-9cf3-9c35aafe3d99.png)

You actually want the comment to be a part of `SynIdent` here, that is the smallest node after to pick from. Adding those cases leads you there.

The result after all this will still not be a 100% what you originally had.

```
type MyType =
    member _.MyMethod
        ([<MyAttribute>] inputA: string) // my input
        =
        printf inputA

    member _.MyMethod2
        (inputA: string) // my input
        =
        printf inputA
```

The comments are printed outside the `( ... )`, while being attached to the `SynIdent` node.
It would be a bit more complex to fix that case. I can elaborate if you like, but it is up to you go far you want to go with your PR.

**Comment by stefan-schweiger** [comment]
@nojaf thanks, I've created a pull request with those changes and some tests. I will also open an issue about the double whitespace between ",  //", I know it's just stylistic but it looks wrong in my opinion.
