### ISSUE TITLE
Stroustrup style leads to half indent in match expression when returning List/Array

### ISSUE THREAD

**Issue by panmona** [fsprojects/fantomas#2586]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBPMAHmALwA6AdhBALYCGW0AFoWAO4CWWjFVYAPmADCtAM6IAjDyoDhYgExgAtAD4wAbTClIADS1gAulIgzRiAMxLVGrQE09h8pAA04KGKxZ25AOYjU61whQXghIABIsXAAHZDRILyxnQKpwgDdadABXWICQqgAGFzzQgElyJHIsAGV2AC9kIuKAFmSIfWSAX0ag1qgI6Jz4yqS8tIzs-zVeiHFukMgAWVoCABkvRBXEHy4R4vE5fN723i7k4Pn%2BmP9ILfgAeQAzNfJEKsjMXd4xrJyp4rA5HMvgBRcqPZ4NaYYB6QI6dObnL6XQYAI1gsHQnxSYXSP0mULMQJSZTEACcsAAxLwZAByiFY6HWWN4WFJ2ThJwRvXCkSucTRGOZfVxEzQf2aRNCVSitGgiAAQogHrBSYgAAq0Um0ajYRCkoUQVnsvLHKinXiI7G81HozFE76i3LFACskqg0tlCqVKo2sFYeugpjKqVggc8sEcbqNiA5Zq5o2R1wFdu5OPGvyhADY3ZAPXLFcrVQBVKIxUmBsTB0P0dgRg1gB4ZMSxiDmqiW0KJ-m2oUOjP-ADsObzXsLiEE6FEIkEEZERugWBV9cb6GbJvhZ1T1qTPftabxYqhAA5hzL897VQtENQUXrl02Y%2BvOZuE9vu4K9yL%2B8UAJynz0Fj6M7oHWbormuISmq28YXG%2BUDJr2%2B6OuKeTiIUUK5meiAAIIPFgeoztQdD1tGLZgG2PSvgMO4fqmX74v84izBhI6AaqVTXuwcAgZGULgY%2BkEbhaW7Ue%2BKYJvRh6MYCLFYbh%2BGkhx1BcRioFQqRT5xi%2BsGifBu50emDF7ISsmethpKwJk5QACKIIyykKSRbICbwUHkTBSJwUMiSfoZUl7E0OZLAQJQPAAKowWxVIwKpYAA6uw8A7G6hyadB2mebp3mIZJTqoa6GHBaFEVbMCq6vDF5IJUljD1pmqWCc%2BwlUXyUAJDlfl5SE4jZoVyxlA87AEHcZb0CqwIEFEqoiCIta8f8R4Na5QntiJrXZb5B5dbw4hDn1BAAEqIHApLwNVyVQk0S1UG5FFgB2fRee1m3IVC4gnvtR0nfANKZDeeqPCU%2BHUH4briGRd0PTyWXUJk6CeIyLwUiqdAeHqYXUS936oX%2BGFfSq8ALHDCPrMjpKo45OZMJqsoKQA%2BhwNWwml7kZVaWXPQZW0oSEBxBcs5largdykmsc7nbVbqLRDHns%2BtnMSZ1PO8HIzH-IsAukkLIti1gv3-aSgPA6Db0y2znZebD8PsIjiBkxT6OY1zr3-HIMnq4LtDC6L7BzkT1u2-b9CUxh1NagueoM4lOxm81Ony8MWNGXkcgmerwUAGrpvKXjwF43gS-W0ss5Da2DArFy5crVByIF%2B0UlZC5zTn5T54XbpXbHq0teXifO9jvMFenyzWbAWAAOLYBNU2IDNc3t8e11tCtlHxzatGK9zUJyL16fEzb6zyiB0AANbyuHJ-YCIdzkFU2rjhif3zcUGmNVpceZetCFJ-5Kd7erdIGSH2wP6LYGMYi2UGuQTgc1sLlCvAbE2-xX7LSat3NeNFxKVyVtvD6HtGTeHIA3cgTcIw1EIfQTIqowqwDKBULANY1L-H4l3Ven915YKRFXbeuN8EKXIDWVIvofAINvKSSBXgYGznvOVVh90y6YI6lvf4Zh0J72thCFY2oUTwFoBOWAs0fCANtjIiCqD37oPYYon%2B20qBmDVsUSA089TsB1JUDIABpRAiAoh0K2FgMo59aAkMlnxB8cioZdj0hvbByjihmHdo4o%2BwST4QhEOZSy5Q6RzkQITfettp7TVmtIqMzkIkKLEkol28S05JM1GxRA1lfbQFJK46k%2BF4BFmgRGWy0BJxanDM-PILCS6ywtllb%2B-dk4hDMHXdWzjWluIYegN4FlMhzjZFEN4uAPilONG-dKH85a9x8lM3%2BMyh6OK8T44K%2BsxGPGSeQVJ6wkF7HyEvAwK95E92sWc2xEAzC70casriWAFgIEhMw8JJdXD6EaPEEQFJZr%2BBYR0IAA)

#### Code

```fsharp
let y x =
    match x with
    | Case1
    | Case2 -> [ "X" ]
    | Case3 -> [ "Y" ]

```
            

#### Result

```fsharp
let y x =
    match x with
    | Case1
      | Case2 -> [ "X" ]
    | Case3 -> [ "Y" ]

```
            
#### Problem description
From my understanding, the Stroustrup style shouldn't have an influence on the match expression brackets. 

I would in this case expect no half indent on the `| Case2`.

This only seems to occur when the right side of the match is either an array or a list expression.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2022-10-14T16:59:37Z - 35f093ce1b8a19d9e9ade3da2c0f855923d8a106

```fsharp
    { config with
                MultilineBlockBracketsOnSameColumn = true
                ExperimentalStroustrupStyle = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by dawedawe** [comment]
You're right, there should be no half indent.
@josh-degraw would you be able to help here?

**Comment by josh-degraw** [comment]
> You're right, there should be no half indent.
> @josh-degraw would you be able to help here?

I'll try and take a look!

**Comment by panmona** [comment]
Hey @josh-degraw 
Have you managed to find out something about why this happens?

**Comment by josh-degraw** [comment]
Unfortunately no, I've looked into it for a bit and have yet to figure out the root of the problem. If I have time I'll try and take another look today hopefully.

**Comment by Linschlager** [comment]
I did a bit of digging, and it seems that the issue is caused by an edge case avoidance strategy in `CodePrinter.fs:3783-3800`. 

Generally that strategy works very well, in our case the list doesn't wrap and therefore seems to confuse the workaround hack which tries to indent the line one more either way

I was able to find an easy solution to this issue by checking if the offending expression fits on a single line and then ignoring the edge case avoidance part.
