### ISSUE TITLE
Comment above single parameter in brackets breaks code due to wrong indentation

### ISSUE THREAD

**Issue by stefan-schweiger** [fsprojects/fantomas#2594]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXM9YGVYBbbACwEsA7AczAH16wBeMACgEoAdS7zHLRAGcsARjAAHAIYAnSUWbcIEPIRJYKNRUu0B6HWCIBPMHCIlKWLdoispsolx6U%2BYAcIBMEmXIWVtK4jIqaitrPQNjU3NLP2sbOzlHOPjvB0gAGnAoQWwsYMFUMABtLIhQOMgAEixDcWQ0SCosDNKlKoA3SXQAV3ri1u0ABkzkqABJSiQLfHIAL2QR5IAWAbAAXVaAX0Wy1aqausLGixaKys6evpLRkR3rSABZSQAPABkqRFfEGnVT5JF3INVhttNtWuV7tVan1IN94AB5ABm70oiHwNUwf20HS6vUK12S7ju2IAopMkSiFqsIJB0IjIMCtncIdioYcGgAjWCwdBYtrnXFXalgADMxLaExy0iwADEqF0AHKIADu6A%2BfO0WGkvUZoOZezZMK5PI1UAFl3xwqW4pp%2BCk0EQACFEIjYNJEAAFVLYRDSU0QLU6uIgpRg7Qs-kHI3c3ninEWtAEuIAVhtUDtkgdztd7tesGVvugkhyE3asCLeVglH9rm1iF1of1ZyjR2NsYNFzxieFADY05AM1mXW7EABVcR1aRFkuUMsV8hVmuIro5BsQMNKCM0w2tmOm%2BNd-qjADs-cHTuH7oAwuhi4Ir1XhNroFg3UuV-Xg0zwQaW5y93G5qHkm1gABxnvaF45ogDyIEQHK%2Bu%2B6Crl%2Beo-s20K7iagGdkKowAJwQZmUEjg%2B6CLmmy7IZ%2B1ghuuTaQn%2BUBtvuQF4f8wzCgOkEAIKIgI0gPmYkg1oGNHaHRYAbrsGHssxAEdoKlo3LcXHntmI74HB5BwOR1aUR%2Ba5SQxrJMZALE4Up3Y3ESam8fxvpaUQOk8hRwpiUZ0lgFuZpmRZikJke-xinZxE8dIsDdJMAAiiBqs5AmiXWnkmZGmENE0rG4cp-zWlxTzPGMiIACqkN8%2BCkG6WAAOrkPAvxpkCqGNuhjHpVAmWWYFIHaCIqb5S8RWld8JLURVVW1fVpA1j2TW0d%2B4a-u1xzNF1wHCiIfYDYVlCIuQzzwpOkivtIJLPOI7qCIIC76cKoFzRJC2bktckrVlVlBXEIinttABKiBwNI8CTQ1VoPUokleT5%2BzLZ1AXrTc4F-QDbrwAq3Twb6SJjAIRAFGmIgpa1pnLUQ3ToHkaqojKbpEMdAnFZha3sV9hFcf9gPwA85OUx8NPSHTWCJf20CkN4L6%2BnQyp1b8ROLbJMJw2c2XWYSnGjI8LzhbIhjwtI7zCCD01pvdcvPQrRxK5CKufdY7iqRrBXa5Iuv6%2BQwjo5j0jY7j%2BMbWbMlta9ZMU%2BQVOIPzgsM0z8Ms3btka87rsG1g3Oh%2BHkf04hIti7IEvSFLMvTQH3kvYrJzMzlcTuCFjsvAAaoKjpUPAwRGzWpvNfRxNpa9VusjbPVKO4eV188MpRS%2BN3N5MbdFzWSzgxAkOpduZn9-yg-Cu4-Vj9FsBYAA4tgZ0XUI11Vu3JtL%2BsT2ByTr3%2BcrH1DxA7hbY7PNhx8jrkdAADWjo87-2wIIeElB8ByEQGRDGt1RhURQvNNC8sg7RmwrHKudsfoayVKqH%2B2ACzfEZnUWKe1KDkErJQHikxYJez9qMDyXdjI9zXstJ%2B1sX7byRonNU1BKAT0oFPKsMw%2BHHW6O6YqsAJhTCwMdG6SFEGPWQebVBWF2zP26tvNmPCBKUDke0T4VZqC0IQtIUhVAKE3XockBB4kIZ31Lhbf86CNEI2SCKdWyRHhf0pK8OQHJ4CSBvLAa6NBcHhwUXY5eDjoY7mceojhmjRgigdl40%2BvpyDRC6AAaUQIgcQ0jvhYAmEAyQgjjbClsSXWJfkFKuLjtoEUCcvG-zKf-SkghwqRUmEqYQiAuZf3DqfS6F9KDWLiIwpBLUUEPzQQkgenDkm1xaTIDS7poru2gNITJ8oBDwFHOQqssVoC3lkJQyJ1Sy5qPekk9xo80nnQyVk9A6IIrdCfN0cQ6JDCYgMtRS5TiOoVwwarOIIpd5eNyfkgqntTFIlaZQdpHxxnWBEIMG%2BK8WG%2BTYXUxJbiwUfy8a8nSqcEBUngYZJhmwshrEWI0QQMprqFCqZsIAA)

#### Code

```fsharp
let doSomething _ _ = ()

let test1 param =
    doSomething
        // my comment
        (param)

let test2 param =
    doSomething
        // my comment
        (param)
        (param)
```
            

#### Result

```fsharp
let doSomething _ _ = ()

let test1 param =
    doSomething
    // my comment
    (param)

let test2 param =
    doSomething
        // my comment
        (param)
        (param)

```
            
#### Problem description

If there is a comment above a single parameter which is in brackets the resulting code has the wrong indentation and breaks. It works fine if multiple parameters are supplied.

I know the sample is pretty simple and you could just remove the brackets. But the same thing happens for parameters which are functions with applied parameters.

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2022-10-19T15:02:12Z - 25cb8d54f9677b4920022b02295e9d00b5eacbaa

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Fix available in [v5.2.0-beta-001](https://www.nuget.org/packages/fantomas/5.2.0-beta-001)
