### ISSUE TITLE
Outdenting problem when specifying record with accessibility modifier

### ISSUE THREAD

**Issue by yreynhout** [fsprojects/fantomas#2597]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosA8lgC5IB2xAlmQOYAKATrAEZ7pgC8AOmRBMQE8ADvgDCsMgDNKNLAwCGVCZzBCGlAG6L8wMAGVExKrQCMaasQDc%2Bw8ZoAmNM1iwcYAL48efMHmJgAd0piAAsDI2oaEzAtHCx8OCkZOUVKZW5eHz5dROlZBSVeINCbCNMVWPiPL0yIP0DgsNtI%2Bxj5OISJPJTCzm8siByu5IK0osbSu1aONo6PSAAacCgAZ2baFdQwAG1lwb2%2BSAASQREtyAtFg4hjyuQ0XYGIAAYlp6gASTJyYj1KAC9kG8ngAWa5gAC6B3cwP2A2Op3uUEusMORzuW0eTxMqJ8kAAsvIAB4AGWoiBJiFooSu7xM9me4KhPhhB1A8JOwiRkCp8AIkjJZEQekEeFpWVu7XimPBEHsuMOAFFvvzBUDZVAcJJIEzoaj2RLOWc0JBnK5xXj0VKkViBgBmBU3L5rBjEABi1HaADlEAEcOSLVliAx4rqWfrwQiueczThAzcrR0Ze8QY6oHohPJoIgAEKISSwBiIOjyBToQyIBjxvjB0MDZl8Vk%2BA2WxExlxxhWSpMPDUAVjTkAzWdz%2BcLFNgAUr0Hkay%2BGlgM8K1f4IcQYcbEY5bZNser3elvfeADZB8Ps3mC0WAKpCEQMGdzsgLpdjFdgSTtNYbiBN7KRo1uT3LtE0PHYNQAdjPTMLzHItRBwWcVnEMgVlraBiELd9Pxwb96z1NkAJ3KBgIAjEjyeAAOaCR0vcd8UQdBmErbCv3XfDw0I7do13Dt91Am0NQATho2Cr0QcQcAkVjcPYrIG1-LdDWI00%2BJA8jwLpV4NSHGDEAAQUkYhK3EdB0Hkd9azknwFI8JTWx4ki1LI61k2xHEdPPUdxIMdBKDgKSyBkvD5II5siMc1TzXU1yKIGelRIMozK18-zXGktMrJ-OyuOUyLSI5DTbSyEwHU8vT9KYLBvgAEUQf0-OMqtMrXbK-zhPLjWRCh%2BKKjUTFTHTCSJD5JAAFRCKk9BCQtiAAdUoeAaTTRkOM3XKHK6i4epintNOxAchuJUaJqpRVZOm2aFqWkJ32PVbQs48LuK2lEXL24qfBMU8jpGpIiQIe9FELRUiTURAVhWN800oh6bLC-8Xu5N7Cti-b4qg36ACVEDgBh4Gu5aNRBOG%2BFs9qwBbNEVJRw0%2Brpajsdxwt4C9LAmMrfkPmM9BNjTEw2vs6nIvQXAqH9IU3ULcyjErMbo12sDPr4EwRJ0nG8fgfExcoCXEClhgZaa98YBCUssyagB9IIbp1NbFI24XXp296lY1BlB2GyqFAEAgGDJNDCdumHSYgcmhYTGmXdRj73Y894CWJb35F9-3KDQtmOYYLmeb5-rBcdyORZ1vWDaNuWFddwT3nseUdOT1OA%2BIbWcHF8ky8UY3B2gM2FAwytrcWmkC%2Bezrkejum0eVuUyoT4aADVrRzah4EiIP31hkfEbH85actemnnsQa5%2BJN1qowsZl%2B%2BNeh%2BD4nQ8hBGOs28fiF6qf3cOk%2BiRq2BiAAcUMKDcGkMxjrxDlvZ%2BTsgLORjm7GuP054l3JDmKS0AADWOY%2B7oMMCsAgZA9DyHLJJdmQUWp1keutUeL92zRSrm5AY9hMYJx9H6FBhgpxUnliIOq0gyDBDGPpb4DEs553eFle2OVqHQNoZ2ehcUsj2EZgnfS-oaBkDPmQC%2BEg-jqMUHIRAY1YBfB%2BKkDKGocIhXhk9beNDeJ0LgdXQ%2BasVGt0rGQVIGgJy0BEcxBgvDqACIkGIp4ljrJkyfpTCKW0CqT1ju8O02kkGt0oGqEkRDmDwHkAhWAUNaCsL1sFcJYdIlUyLjE2BcT4FPDtPHJ4kBgGVkoOWCg7QADSiBEBCBMVSYgXwsHyC0Xfd4YTIFRKRrI9%2B8Sal1wTqgwZ6C1QrEqrAaqrMIbGS1sgoUwCiygOCZZVqkiKZlKgIBSZisnH2lnvUnMpY6JFhqunaA6g-IeM2defhEg6rQEQqMcxIy2JjNOVGCpDiqlXKyHaY%2B9TGmvN6e0EUVU0IhiECKAQYpyHFMfjYqB5TX5TOqfaL%2B9SOldOGpnPx-J5lkEWeSEJ8VngP3DoXM5KlYn7w-gkxB9SkX%2BWbggdUgLZJtWWBCYEFwVhuihlsUZ7ggA)

#### Code

```fsharp
module OutdentingProblem =
    type Configuration = private { Setting1: int; Setting2: bool }

    let withSetting1 value configuration =
        { configuration with Setting1 = value }

    let withSetting2 value configuration =
        { configuration with Setting2 = value }
```
            

#### Result

```fsharp
module OutdentingProblem =
    type Configuration = private {
        Setting1: int
        Setting2: bool
    }

let withSetting1 value configuration = { configuration with Setting1 = value }

let withSetting2 value configuration = { configuration with Setting2 = value }

```
            
#### Problem description

If one uses an accessibility modifier in front of a record (I tried `private`, `public`, `internal`) the functions below it seem to get outdented.

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2022-10-24T07:25:37Z - 529aa7d7807a3b996045c08083a2635f9588a37e

```fsharp
    { config with
                MultilineBlockBracketsOnSameColumn = true
                ExperimentalStroustrupStyle = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this problem.

It appears we should not unindent in:

https://github.com/fsprojects/fantomas/blob/529aa7d7807a3b996045c08083a2635f9588a37e/src/Fantomas.Core/CodePrinter.fs#L3154

That should be something along the lines of:

```fsharp
onlyIfCtx
  (fun ctx -> not (ctx.Config.ExperimentalStroustrupStyle && List.isEmpty ms))
  (optSingle (fun _ -> unindent) ao')
```

Are you interested in submitting a PR for this?
