### ISSUE TITLE
Internal triple-slash comment causes record to be formatted Allman-style

### ISSUE THREAD

**Issue by LyndonGingerich** [fsprojects/fantomas#2600]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAspgEqJwBO8YAvADpk0B2EEwYAYgJaIA28AjGg4N0dRs2YB6KWHRkO2bogC0AZ24BDFQAswcALZ7Ew0U3HsuvAExoARrFjcTZ8z3gBmNAFcGHdGAC%2BkAA04FAqiOjoQgDmKqhgANqhLMnMkAAkWLjxkELowakQGQBu6tyeyGhJzhAADCE1UACSDEjCAMocAF7IDTUALIVgALqp-n0pzhlZlVB5BVPppeWz1TV8E2aQ%2BOoAHgAyQoj7RtHoWgvrlrVDo%2BLjqaCLMzlG8ADyAGaHDIjtWIpLuISmUKvE1s5LJtgQBRVpfH69IZFbifSC3MabJ5bTI4WaQOwOIFpJag1bIsBuaFpFrhMjoTgMMoAOUQAHduEdieJZBUMfcsUNpnicoTuNyoKSVuCKf1qUV2th1NBEAAhRCfWBkRAABXUZHUhnQiDIEogvMQ-OYD3E2OBuOyaAJ9nF1JB0qqFIArPKoIrlWqNVrjrA2SboJpEC1irAI1FYAwzTIyHznHdrYLniKnWKJe6wZ7GgA2X2Qf0q9Wa7UAVWwuDIEfC0dj6njid9nzK4StEBtzDtJJeOZdealBcSFIA7KXy4Gq4gAMIaFQqBcJlS86DoLVJzvcbtpzGPIUO-G5t1j8mNAAcM6VFaD2vwiD0NhNu67lsPAuPWcdUHPE9lnHCEzAATjvANK2DNduATD99y-Mx017TMcSHACRwvYCr3WeoKTLe9EAAQU%2BY0yDXAx1CTC0ewCND7Qw50iWwskZUaPgNgI2doO1doXw4OA4PbCk9wPZCj1tE8mMAxYcPYq5IJVUjyP4vRBIceDfVo78M1-dDs0wligLYwt1ipbiiOIshYG8eAABEeA4dTyJolMkPEFD6P0xjDNyYRR3ksznD4OUCJ2XYmk%2BAAVLQjHaLQtXQAB1Dh4HOJMbl01CfMHPz5lYj0Jw4n1wr2KLYqMGFEISpLUvSi5fSLLKJJ-KS-3xAqTKK0DxD4EsysihhPg4XZ3nrVstRhXZsG1FcOC0ilrxazzJP7aT8oCwqQIpPhp0GkhyHgeqMt9foVuYLy%2B0mAz-38-JttwkLbwO0gtXgZlPFfE0viaY09DiX0%2BDo66wAHIpTxyPRPG4KJOV%2BNgtT0VtyOikVHoUkKIIIw73vwGG4aORGyGRyJ31LaAtH1ZVyIAfTZNKMpBhi8rurq5NM4qamuUsIusg1MHeMhDg3E7GqWi6ICulmIaY9mcSCrnIS4xptj2fn1EF4WOA3T7vrIX7-sB3bmdy2W-Oh2GOHhxBidJ1H0e6nbGksKECI1rWRfQfGrZtu2UfJgjKeprcTXpxmLlN9rbs6ranaesxLAs1WIoANTJVUhHgGIxaTZao-Wjqcnl%2B1Fd65hLDClO9jYbwtwWhhM9aHOI6Tc6C5u3y2bjjmeopSxSur3Z7NgdAAHEImm2bEHmhNc99fPsu86Ou7PLD48xxOBpTgnraOVU4OgABrVUDWPiIVHeBh2kNRcHC%2BkTGjEjzLrWzvWbX4ze%2Bd7n9tV1kOT7wiGGIwaNcCORGj4NsxFWjPn1sbRoOlWp6RXh-UU69v4J3EJYF6qtiKcmiAwWuDB64Jk6IQ1snhtTRVgC0No6BWwNwQuJVabVC4x3QV-BWnNy4QEsNjPBsMTRMiiMUEMDBohwLfGQCBQhfANwQTUZ%2BHcwYbTurJbhfdGhuHwjvK2iJ9iGhsPAdQS5YAqBiAAm2zCX5Szfqoouw4uGlx4RSNwKsaiQCniaZyRgGHcAANKIEQNgOhfiWin3UCQ8WT9PwqPBpKGSGDNE-2cG4N2qsD5RKPoiFQ1lbKtFZBuRA8AfaE1%2BFPOaFj1xuVTMgnKqDzbqOSS4rRNQ3DJ08aqfUvFED2R1tAOQ6kRElOrD4BMjloAaANG2Gx8S1Gf1dBvYKZg3BV08d4oZfiyj-Bsp4DcKZsD-EwICDscSl6gwScKbuD1llK1WYPTxQSQkRT1tIr4WSGA5KOIokKtRJYjHsVcyGTilmYM3uINw29PG7MEt7BASJYmIRBqEYYfRcgqDYBY%2BIyj-BAA)

#### Code

```fsharp
type MyRecord =
    { Field1: int
      /// triple-slash comment
      Field2: bool
      Field3: unit }
```
            

#### Result

```fsharp
type MyRecord =
    {
        Field1: int
        /// triple-slash comment
        Field2: bool
        Field3: unit
    }

```
            
#### Problem description

Adding a triple-slash comment to a record field causes the record definition to be formatted with brackets above and below fields rather than the standard style according to the style guide.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2022-10-26T10:57:39Z - 5c54a3907483ea4936d456a69741537ad9c6026c

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by dawedawe** [comment]
I think this is in line with the [style guide](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-record-declarations) for records with XML documentation.

**Comment by LyndonGingerich** [comment]
@dawedawe You're right, my bad.
