### ISSUE TITLE
Comment is removed when using array index access syntax, without a leading dot

### ISSUE THREAD

**Issue by benjamin-thomas** [fsprojects/fantomas#2611]
Hello, I'm learning F# and was surprised when I realized my IDE removed my code comment.

I see there are a few related issues, but maybe this simple case could be a useful report?

I use the dot syntax as a workaround but it's not ideal since my IDE warns me about the dot being redundant.

---

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKsAOiB2YDKAngM4AuiAtgHQDCsANnYtCQJazZGUDiOiATi2gAdbCMYkwLbADccJWHwJgAvGAAig1uwCGigDykB2AOYAaSdhIA%2BABQBKESKmzLCgpQCC8eDaGQPGBiMRH7mAIwO2M5ybp7evpAA8nzaJoghkOYATJHRropxPn4AQqllGeYAzJFOMjGKANp%2ByanG6X4AumAA9N1gKSxE6WCpYIgAHtCIGFq4LABmYNiwEvOwAK7Y8LUu8gVN-oHBnT19A0NEI7gTUzNsc4vLqxtbmeBQQySsJkSoYA3vCCgCAgqAAEhIBCwf0gUhIb1BEEgYOk2jo62QaABiJBAAZTIDEZAAJJbOR4FgAL2QBJxEAALISIB1CQBfWkg4FEiFQzFQOEI7mo9F87F0sIcnGQACy2nGABkpIh5ThjCQABaCnFhLK4plgFmg9mErmg5GQ6FoSA4eCJeaK7CIPCQxhakHI4UYv5inFZSVEgCiWztDpp%2BqRdHmkH1hpBxtBpvdPMtUAARrB6G6kSi0V6seGwJV-WbSUM%2BCQAGJSNEAOUQAHc6EqsyCSHwMTG2f7E9mLXzIOnM8XwZ7RQX6cOkXgMNopsVEGs%2BIgAAq6bTkRBkPgtiBtjs42MQeOc-Xm3kwwd0Fse3NjulgACsk6g09niHni%2BVsHr-Gg2iGpLSLAf6zDuYB7ognZGt2p7Jv2l7XjmIregWABsz6QK%2Bc4LgoiAAKqBL%2B-6IIBwHaKBz7zGiQxQXGMFSnBF4Zlew43sh%2Bb3gA7BhWHvjhS7UHQ-5ELQHB7swChgVRdA0QeXYmrBfZMUOsGjih94ABw8TO2GftKFCpvwUnUZBcnQQpDFKVaCGsUheb-AWACc2lvh%2BuG0HQ7DGTJpmIoeYDHkCinntZzGIWpHHiviBaYTpiAePMW60OQ5DaGBEG0Ue9HclZaZhbZEUOfeYQSjFvFuUueAUII9BeZRJmZQF2VmoxoUqQxhU%2BoiOouVMCVblV5A1Z52Dpe2vmgv5gVgD24K5QO%2BWqbe6nikWZVxR4fAvPAaiIE2Q1bmN%2B5%2BfJCbBSmsKWOFy2RdqE4xbK4zEvMAAq6o4Hg6oKCQADqLDwBqYF6mZdEWTlIX8ldBU3UV4pPg9crPW9OABj5n3fX9AOas%2BqHAyd5lnZZEOXfC0PsbD2roQjT3YPMLDjIkWApHsAbjBgS5EEQ9xgRpeOTadJ5ExdApk-ZXWgmE3HUwASkwCjwJjgPPvSfMglNzVJvNItLeT4sgmEWky3LfDwDW6zkIZfB2sSZDkL8z5hI102zWeF3kOsdCsE2joVgoqVfPwL3nqLd7is5MWy3AJvSh7XtKr7fD%2B4dGHQOqa7MPwAD69b-YDTsa72xPax1MN6xAuoYY9m0pAQySKqQivYwWvP52DLVa1DOtiwWWSlfeMpytX2i13w9ckGbFv8Nbtv2wWjsg1lbea8T7ueyw3uIAnSeB8HXeh76foxUPI9jzHa8b1v5HJzFqfp1u2e55qreE%2BDwudyXus92t-ePQAarexQpDwCkMYRuPNVbMgFkFIW-Zi5ClLj3e6P85QVk2Mwe4gCtggLAcrCBBooEzXOrA9%2B8DP73iyPDZB4w1ArB4CQVm7N0hc3YDg5ueD1ZL0LhdGye8Vq%2Bipj-WO68lTFE8tAAA1sUFIEjNxEESNgPA65EAeXNqNeqPln6C1fvBRaH9u7kKlv3OsjYRGbh-DgIOWBdp0yiLMDwWx9KTz4LPe8GUF5NU4XNYmPC9H70RFkQ2-cPBNmMNgVB2B0HsApKE8i6wlwvVgKSJAlhyLc3UbJfGoMX7t28bo0h%2Bi6RZHDkEz2-BsCpNkPKdgxhHGW2sVIFgswXF0mkhk-mBMtE5O4XklqnUCyVGioIteoZ5TrlTPAbQglYBcxMMYje3k2lqwIS7VqeV2r5L8aCSofc6SQAYfwFgG4Ul0AANKIGmEkuQpIpGpFTgsiaSyOnQO0cpFivDbqIkqIffuojUjiNDEQTa206ykEQPAM%2BcdHQMI5swjgR0HmQKeYQmBrzrpkLpJUb%2BuzSh8AqogDQRBoACCGuUsg8A8JRHYLtaAQlmZpILK0hF%2BCkUrPmj4jZfDPlIN2fs4lcg0TOi2usQw6wMDOgIK6dJTKOHZOXm-Um7yKafMobss50xHoT0tnaX52B-lKmadqXE7DllENRSHTlWyBG7MFZoaUCAwz3kZU7d4HQOSwiIBWLmfwnWsiAA)

#### Code

```fsharp
open System.Collections.Generic

let inventory = Dictionary<string, int>()

inventory.Add("Apples", 1)
inventory.Add("Oranges", 2)
inventory.Add("Bananas", 3)

inventory["Oranges"] // raises an exception if not found
inventory.["Apples"] // raises an exception if not found
```
            

#### Result

```fsharp
open System.Collections.Generic

let inventory = Dictionary<string, int>()

inventory.Add("Apples", 1)
inventory.Add("Oranges", 2)
inventory.Add("Bananas", 3)

inventory["Oranges"]
inventory.["Apples"] // raises an exception if not found

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2022-11-04T13:17:40Z - 9f9d03b556b4351a0aa9f672196ecaff5b672f60

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by dawedawe** [comment]
Hey Benjamin,
thanks for raising this issue.

In general, we would ask you to use the [documentation](https://fsprojects.github.io/fantomas/docs/contributors/The%20Missing%20Comment.html) and try to solve this yourself.
But as you are just getting started with F#, that might be a bit much to ask.
Anyway, you're welcome to have a look at the proposed fix and follow along. Maybe you can learn something from it.

**Comment by benjamin-thomas** [comment]
Thanks for the fix!

Indeed it's a little early for me to dive in, I'll keep this in mind next time :)

Have a great day
