### ISSUE TITLE
Format Selection yields a type loader exception when built with dotnet 7 sdk

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2617]
`Fantomas.Client` and `fantomas` (tool) are impacted by https://github.com/dotnet/fsharp/issues/14275 when (de)serializing the `FormatSelectionRange` struct.

While a fix will eventually land in the F# compiler, I suggest we avoid the problem by changing the `struct` to `class`.

Both sides would need a new version before the problem would be fully resolved. Users that are not using format selection are not impacted by this.

**Comment by auduchinok** [comment]
> While a fix will eventually land in the F# compiler, I suggest we avoid the problem by changing the struct to class.

@DedSec256 Will that work with Rider integration?
