### ISSUE TITLE
Anonymous types in a DU inserts newlines

### ISSUE THREAD

**Issue by ly29** [fsprojects/fantomas#2621]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAgmALwA6ATiQHYQQA%2BBYsAZmAJaXrlU1j0BCjFsH5p26MAG4wAYTBoAzujLsA5lIDSAQzIAbbWgBGmdHg2adOxIeOJaAXy7Ua9WczCLllFY8gAacFDyiOjoqvKoYADaARCgPBCQACRYuBGQYn4xNEkAbuYArsho0fE0AAz%2BpQkAkpRIHADKrABeyJVVACxZEAC6WXbtsd1QyThFUBmD2Yl5OoURJVUAjFM8kACymgAeADLsiDuIXugAFplVYEsATGXDfTwDWXHxSSnjkEfwAPJMe5SIDSwlnOLxmBXGi1KV1W2QAonUfn82sMEjomJA7v0ps81qNUmhIAZYLAdCDcbN5sUUWAAMwwmqUIJkdAAMXY5gAcogAO46fZk%2BJKQqYh7Y4avMZpIkkgUJMFzCHUjr0qANbCaaCIPiIJiwMiIAAK2k0AFtgogyLKaELECKaI8eDjpm8pcTSTDcuCFtSAKwqyBqjVanV6g6wbkW6CaIK1HKwKOhWCUK0QG12iAOmhOuUugnS93i%2BWUqLUgBs-sDmu1uv1AFVsLgyFGY5Q4wnWEmU2AmOYgumwJmhqUJfioPmrZ6Fd6LgB2Cvqqsh-XSPTyeTSJMefLQdB6rs9nR90r3e1i4d497jj1FxUXAAc86D1dD60QJoMFv3vdtx6xT0LuZjm6E43tOVQAJyPouNaIBuOidiqB5HvEJ4ZmeoKAYSwHXhSt7LBU1IBguiD4EwJhkBuJompoXZpr%2Bor-uemFXoWuFgaUSwrIRlbBjBDRvqwcDwcmiHfv2g5gNmIzMdhrFelSFzXFBJFkRa-EmoJJIIdSdEoX%2BjoAZKeayeebEKcsdLccR%2BBkLA%2BR1AAIogfIaeRtFkMK9GnoxGFGRMHAgWZJaKcqhGbFs1RMAAKicRwNCceroAA6qw8CnF2txeWhPm4phkxyVO5kcX6YXbJFMVHLCh4AglzIpWlZwqqWmV6QxBlMX56QBTh8nBcs5alRFlBMKwWxfI2mi7mQsJbNg%2Bprh2InUneLU8KhA7oblnX5aZvWQvESxzoNABKiBwGQ8D1elKodKtNDrRJUkju8O2gkF%2B08EsD4nWderwBy%2BTvhaPzVCYJrhCqSziZtzqdSa%2BQ6KEfL-CyerUSEFpRZKPWFX1HGQYRp3nfA6wI0j%2Byo2Q6Nuf60AnMaO4WgA%2BtyqXpdDOWw6OXXoIFe3Ujc-rhTZZCaJgXxkHsihXY1y13b0%2BlZoZ3OveS-MXFcXEXBs2wi2LEtS%2BgANA2QINgxD1JQ1lG2czmcNk6wyOIJT1OY9jBXFh9NBXNChF6%2BLkusIopOI47FNo5NNOEXTDPkSzbNnBz7W%2BSr3Ue3hUKWdr4UAGrgnw7DwKoMtditSdKx1qe8zjnsC6F2fbCy9k7otBd1MXCddrd5dDinL1p7tuNexAVwlQ3WwObA6AAOLBDNc2IAtSYlyqZfW49yuXiZb3q1UVwDdnDtO3w8HQAA1nwovn8E8hfJQDSmrBJKA0tFxIT%2BrXecnW3cyxg%2B1xrI62suS8n2NqdAEYjhY1wE5EalBWCJkoPgOor4TYWwuLpNaite4-y3jKGuGd4hXG%2BtrfAfIVCUCbpQFuSYmgUMmvkfUUVYC1HqOgSai0vzVR7pJTerp8Hp3YkQgmpDEYWkoBwnIYYvCoI-GQWB7AEGLXQVUd%2BPCnoXn4QWf%2BhCeA0gIofUOSIdimgMPATQK5YDyFUCAp2XDkJYLahXPuWi%2BZD2pDSLWVRIDzwtKwM0HBzDqEQIgbArCjjoFqJfTQ1DZZvzEuvGGdtf7bzVu4i4NJfbaxPjEs%2BSJ5A2TsnULkihEAkyPvsee81rGbncp5T%2B2Vv5czwdone6Sqg0izt4vg2hnz6gckHaAygNISJMPAWs8CkxOWgHoUWiD7Ef0cV-ZxuDXEEKEXo%2Bu3jfHDIieYQEtl8hbmwICTAwJRLcMSbbaS20B5tIAR0se3jgmhPCsbORPwcmUDyfsFRHEyjyzAA9JJNyUkCJ0RsmgNID7eIOYJdA6wEDIniZchpA4Ag9HaOkeQLJrERDUXYIAA)

#### Code

```fsharp
type A =
    | A of int
    | B of {| B: int ; C : string; Karlar: byte ; Kalle: byte|}
    | C of string

```
            

#### Result

```fsharp
type A =
    | A of int
    | B of


            {| B: int
               C: string
               Karlar: byte
               Kalle: byte |}
    | C of string

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2022-11-10T07:58:47Z - 573d27328ad5eb8ac34cdea2a7ea5631ec5359ec

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.

I believe the problem is introduced around:

https://github.com/fsprojects/fantomas/blob/18a97bd820b82779ec78b71cd6f74c0dc3bbf800/src/Fantomas.Core/CodePrinter.fs#L3484-L3485

`autoIndentAndNlnIfExpressionExceedsPageWidth t` should only be considered when there is an named identifier present.

Changing this behaviour to:

```fsharp
    +> (match so with
        | None -> t
        | Some name -> genIdent name +> sepColon +> autoIndentAndNlnIfExpressionExceedsPageWidth t
        |> optSingle (genTriviaFor SynField_IdentifierAndType) innerRange)
```

probably does the trick. 
Are you interested in submitting a PR for this?

**Comment by ly29** [comment]
Probably tomorrow I can have a go

**Comment by ly29** [comment]
Also thank you for your quick feedback!

**Comment by ly29** [comment]
Yeah that does the trick, I will try submitting the PR tomorrow.

any guidance for where place the test and should there be more than one test for this fix?

**Comment by nojaf** [comment]
I think adding a single test to `src/Fantomas.Core.Tests/UnionTests.fs` would suffice in this case.
Please take all our [guidelines](https://fsprojects.github.io/fantomas/docs/contributors/Pull%20request%20ground%20rules.html) into account.
Many thanks!
