### ISSUE TITLE
[Feature request] Less verbose output

### ISSUE THREAD

**Issue by ly29** [fsprojects/fantomas#2627]
I propose we that allow a less verbose mode. 

The existing way of Fantomas deals with this problem is being very verbose doing `dotnet fantomas --recurse .` where is each file processed is being list..  It would be helpful to being less verbose not print any info about unchanged files.

## Pros and Cons 

The advantages of making this adjustment to Fantomas are less nosiy output allows user to focus on important things.

The disadvantages of making this adjustment to Fantomas are it is a change and someone might be dependent on current behavior of the cli tool. 
It might also might make ignored files harder to debug.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md).
* [X] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [ ] This is not a breaking change to Fantomas
* [X] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Hello, thank you for this suggestion.

This sounds reasonable to me. We could introduce a `--verbosity` setting to the CLI tool.
I think introducing a logger library for the CLI tool would also make a lot of sense.
Serilog comes to mind, but I'm open to suggestions.

I think it is ok to change the current behaviour with something less verbose and add the option to re-enable that behaviour if someone really needs it.

Are you interested in submitting a PR for this? (If so please target the [v5.2](https://github.com/fsprojects/fantomas/tree/v5.2) branch)

//cc @dawedawe

**Comment by ly29** [comment]
I will take look this weekend. 

Serilog is nice and I use it at work but have no strong opinion.

**Comment by dawedawe** [comment]
Thanks @ly29 
I'd also be okay with a less verbose output by default and the old level of verbosity hidden behind a setting.

**Comment by safesparrow** [comment]
FWIW I think there is an easy way to halve the number of lines Fantomas produces:
Replace
```
Processing .\src\fsc\fscmain.fs
'.\src\fsc\fscmain.fs' was unchanged
Processing .\src\FSharp.Build\CreateFSharpManifestResourceName.fs
'.\src\FSharp.Build\CreateFSharpManifestResourceName.fs' was unchanged
Processing .\src\FSharp.Build\Fsc.fs
'.\src\FSharp.Build\Fsc.fs' was unchanged
Processing .\src\FSharp.Build\FSharpCommandLineBuilder.fs
'.\src\FSharp.Build\FSharpCommandLineBuilder.fs' was unchanged
```
with
```
Processing files:
.\src\fsc\fscmain.fs - unchanged
.\src\FSharp.Build\CreateFSharpManifestResourceName.fs - unchanged
.\src\FSharp.Build\Fsc.fs - unchanged
.\src\FSharp.Build\FSharpCommandLineBuilder.fs - unchanged
```

Also, for me ignored files do not get listed in the output.

**Comment by nojaf** [comment]
Available in [v6](https://www.nuget.org/packages/fantomas/6.0.0).
