### ISSUE TITLE
A record with Doc Comments produces a different output than the same record with a regular comment or the same record with no comments.

### ISSUE THREAD

**Issue by sean-clayton** [fsprojects/fantomas#2630]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WASotAIJgC8AOgE4UB2EEwYpaAlretXQwwEJhsOXejzAB6CWACasYaLABhAWHacaIngBFlquaICiOoevkAxI2u6iA4hb08AEhbABfYcKy4CRfpRMMmFhVjKx5%2BQUsNBkkZewYlCLiIbUT-HkNU0IZzTKiIW1z5JwjXd3UPHDxCaCU-LMC7NL5GrIgE4Mj5FI6ksAyepogcgdawApG8sGKO10gAGnAoAGdEdHR2AHMl1DAAbUXGA4ZIABJPZDRIVXmjiFOANwBDABsAVwu924YABgX5O4AkrQkBwAMqsABeyD%2B-wALF8ALpHFwww7yU7nHZXDg3dEnJ5vD77f5gACMqNEkAAso8AB4AGXYiHpiFoG3QAAtcf9SQAmb6I5EU0B4zGXVnwADyADNGbREKCsM9oV8Hi93jtif9eRSeJB9MCZXKVSTIM9pZBBTwUUcRZSzpUsQAjWCwZ7cvX49VEr4QADMuuOQJWVHQpnYLwAcogAO7PJke0ToKjvK0MG08O2esVQF1uxN3L2EzW%2BsCwwN3UHYR7QRC8RDS2BURAABUeVEeAFtVogqAWGMnU-IkdbhaqHbhna73YG1cW0Fr5ABWCtQKs1usNpvM2Ax3vQR4rIH3WAH9awWj9iCDxBpiAZgLjnOQPMz8cEjUL0sANlXkHXtb1o2zYAKrYLgVAHketAnmerAXleYDSi8Kx3q4Y6io6lyvv2c6fp8JIAOx-gBm7AYgCjPIeSwKBeSyDtA6BNohyHPKhw5CraT5Ybm064UW%2BGLqIAAcJHVoBW7NlSiCdk6vYsSht4caOXGYZO2F8bOAk%2BiSACcYkbkB260c8CGrqx7GiCO6YYfaz44VpH46Tyvylv%2B4mIMQ0roL2tGdp2jyITeaEPmidk8S%2Bmnvt6JYkqS5JuaRRnNqCMmsHApmXuZikhbZ2YRQ50XzgRPI6olHleT5VCpZ26VumZpbBcpNmqeF6m8fmjkxV%2BcUBuVG7EFQsCvMCmiIPGtVVUFKZKVZnGZtx7XYug-FObFPLlm5NK0gC0oACocqyoIck26AAOqsPAnKIQKzX3nlxwTh8y2rd1JXyKSK5bXSu0Hay%2BhsQqJ2hhdV1cqu363XNKkLWpz3XF1xVCTwpK-t9O20NKrC0pKEGPExVD6LS2DNksSzwVlpbCVDPDWfdrX5UtCNFYJpaksR6PVE28Cg9dq6wjTDB0%2BhDOPc%2BzN4mtPU8qJnNENzkavLJvYygCPmdtsq6krlouFs%2BnavM86zxvKphNgFay9ntjqI6zcX6W5XNUPAVKG8bTJm1QFtTX%2B0Acu2NZVQA%2BjGl3XTrsNtfDOK2858j8n%2B22DR2mCSlQjL0bz4NU4LEDC6FYBZmLEUS-aUvvaIvIJaaSdUCnacZ%2BgivK1Qqvq5rbMR4%2BcNYgbRusCbiCe97Vs2yzceV2VprJ48qfp6w9Gu-3g-D-jPtuX7AeMb2Idh1yXdhYz0crbH63x31Nd0gAat6vDsPAmxZ4h1MH4Xi3H69SOlrym2X7SpgjUYhTO%2BwJH570QgLV%2BRc9YlxjuPM%2Blcvp-00LAdA1hVhExJogMmFMn6rhfndEWkcj5Tk6vA6W8c0Y1zdgPJkvBTLQAANa8A7Ew1YSxJS0FBF2CibolaUxJBZWatN5rdyjqQt8ks3rIwYLyDmppoxxjoasPcrJra4DGljWgrBzy0GIMCaSLcO4kiatDFqxDi5LUKlIr%2BJJeSy2nvGDYtAAG0CARecEzj8avGbHtWAQIQToHxhTBSgMoHvwkZ-O22oHaOKqrQYJ9wdxskMXJKgmj2A6IpsY-4Qjwk9w0mQmx0T5B%2BlctQ-uxp6RdidPAR4lFYDkzZIoweoTLIiJhmIkhhTJFl2kaWP01d-j6mJr2Vg3YOAvAANKIEQNgAJrJ0BAhYY8Nx2dBE5UIQXaBUAnqRNPhQ0Qfop7DPoasxhxoliDWGsCaM9FEAuxoYPTBpNyZ0WmkOMx9MLEwKsVFYpE8eB%2Bgvqc9syVECaAXtAKg4yIw%2BXgCBbRF4xrQCoh2XRbThFC1EYfSxz1rF9Nsf8P0v9hmYLGRMoJzxFRDVePRFM2BFSYGVJi-J4jLil09OXGR-okHDJmXM7azc0kyjObQC5TIckfW%2BLnMA%2BcHq-Pxf8wlJSjlUOGTS9K6AqQIBNLkzZXzXCLARDCK4SxTDkx2HklwQA)

#### Code

```fsharp
type RecA =
    { A : int
      B : int
      /// Yo
      C : int
      D : int
      E : int
      F : int
      G : int
      H : int }

type RecB =
    { A : int
      B : int
      // Yo
      C : int
      D : int
      E : int
      F : int
      G : int
      H : int }


type RecC =
    { A : int
      B : int
      C : int
      D : int
      E : int
      F : int
      G : int
      H : int }
```
            

#### Result

```fsharp
type RecA =
    {
        A: int
        B: int
        /// Yo
        C: int
        D: int
        E: int
        F: int
        G: int
        H: int
    }

type RecB =
    { A: int
      B: int
      // Yo
      C: int
      D: int
      E: int
      F: int
      G: int
      H: int }


type RecC =
    { A: int
      B: int
      C: int
      D: int
      E: int
      F: int
      G: int
      H: int }

```
            
#### Problem description

Take note the difference between `RecA` and both `RecB` and `RecC`. `RecA`'s whitespace and closing bracket changes while it the original shape is retained in `RecB` and `RecC`. Also, records will change their entire shape as soon as you add a doc comment--this isn't expected and creates unnecessary noise in git diffs.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2022-11-18T12:48:36Z - 25f64da33b93efb6a0f3544746c15daa4f9b47f9

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by dawedawe** [comment]
Hello Sean,
please see my comment on [2600](https://github.com/fsprojects/fantomas/issues/2600)
This behaviour is in line with the style guide.

**Comment by sean-clayton** [comment]
Quite unfortunate, I guess it's time to remove XML docs from all of my records!
