### ISSUE TITLE
OR patterns incorrectly broken into multiple lines

### ISSUE THREAD

**Issue by 2JCe7wMaKvVKYTEr** [fsprojects/fantomas#2634]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKB6dYDCsAOAnmHgIYDOALomAGYBOsAtmgBYUV5kqYA2iJdAHYA6RgEtoDMrBoVhcRukSCAtAFcy6eLAqDEFdDTIsBedDxKCA5mpJXEKuohqIng6InSl2r1YxIU0Cxi1gA6guF8FLRiPFR0AIwATADMYAAeYAC84RAQ-oEsGWAA7mIULLl5AD5gCWC1SQ1gACosTtQqAHzEdCEUNIJgoZAAYrBqgvB1ADRgSXOwdGApAIQjVRC1AG4C9d29-YPDkACk8CNgu4nhkfpgSFTQFABarrAA8gBKxLD92ZswAUgr9-mUKoDagAKAAMcxhAEpmrC5gB9JHQ1HwpEHPB9QQDIYjN4MWgTKbCDZDGpgVFgXH4wknABCOiKglgggAXu9KZBwpAZuAoGR9BQQlYyKgwABtYUQUB5PKQAAkFAIeGQaEg-UF8uVKt2PDUWtl%2BqVcPNyoAklNlBQAMpiHl6pVKgAsVoAuvqAL5CpWKt2q9Wa6U6gmu4OGkjG01yt15BIBxNQACyJHSABkQogs8orBUo4nkjDvX6UwqrSGNabIMp4B8aDm9A71XxiwajSbpQnUwsrRBIABRKZNlvISvBng0SDlpX%2B-VBpU1sPagBGsFgPE7Q5jcd7g5WU5XttFdAooxCsYAcogSjxc7u8hQ6Cb53lF4Hq2ra%2BHN9uz6qt28ZHu6J7Kg6pAeMyzhLIgAAKAgkIw%2BiuM%2BECvu%2BiY%2BguU7LgaoZ1gBO4QcBsY9mgfaJgArBBQ5QSQMFwU4WawCUrjQOQiC2tssBceKnIYWAWGIB%2BEBfnkBF7kR-5bqRP4gYeqZgAAbPRUCMcxNDwQAqngmp0Fxoq8fxARiEJGk0LGoriWAklVomq7EfJQH7pRZoqQA7BpkBaYgsE6U42AWGQZC4IIlBvs8SzCdZPC2ThFZLj%2Bskbq5ZHuaBKkABy%2Bf5gXwWmiCMOu6FWTZYlJXhKVOb%2Ba5QCRblKVRR4AJz5dBAUsYguA8JZR7xYlbq4Z%2B%2BGpX%2B6WAZlLWeamCSWipfldQAgrIri4Iw-jCaJdkOWA0lQPVLnTYpFHZfNyZHstTHdUFiAOiVEjbgNKlDVVI3Jd%2BdVpY1GVnQerUqcknW3Wt8SPeIcD9YIO1vh9SqjRJ40-ZNf2nXVs3UW6CQpKDHgrQwkzwAAIogj7iPEcPYZ9NXfdGv0RhQzXncp83gddGbpNaNBtMoDosEsFAAOpiPARYaWW1VjbVDNo0zLOA3NJZ0ZzmY83zgjDglD2CxeoviywwmqVLtMy-TK7HeGuozazQPzepavc4INBiOkHyGQESzDukeKIGFFmwxpOWm4jX1SRNDUK7bSvY0qCQ%2BU7XyIHAdDwAbEtgaHeRI-ZKNy1HNsAx5cdJnlScp0s8A3mopWuE21pUIwUoaQke355bjOMGocSxLm4x0AU8QtH%2BMcl0eCQdddyep-AaY9%2BKj56APQ-lddQTIc8riomUhtztLyOy538tF5jdvK26SSLamkBc4TdAkAQHx0DmlAZ0bwfZxAuf7YdznW5GMeF1ExJCuktO%2BdAH5PxfmISgNc650Abk3FuE925H0IvLbuvcl6IBXgEYeo9i7AMvgOJa99H7P1fhQee2D%2B5LFXnQYSMATAPy3nQHeYsixoIthgwugCiFsxAXjJ2AA1c6zIQjwAlO-YSIduER1Rnw5mQDBGXw5uAzMoxJjPEDhIqY0jOEfyzvIxyBc6yn2jFjI8SRVYaPSCTHQABxfQPs-YB05DIz%2BJiDqRxOgpM%2BsdrGO3AQvPuehmT9WgAAa2ZKwqJ%2BgyAfEEA6FCvVty1yDoNSq3i-5Wymv4yx59S4QCSInJad4Hy5lghQDiygR6ajJq7QQ5RA4rSmMVBBKCVK7QPnndBMl5ZNRUfbEB5cyGPisIILR7hBLJLEJMgIagnAtFgLaJABJzKvVTO9HJvi5IY0KYElSSQp7jPiIIcy2w8ycisB0sqdBGkhBaZyLp2zsm9N-ns-Jitx4qRSNfJyNDxQTizChdc8ASAhVgGQCUFScFxXeWbQ%2BPCBlRyGQIkZboUhgJvq41wYhUIbJ4AAaUQIgPAaz7S2liZYIICKda7MUX4n5xClQpFITfCJlgokTjIITck1d-ZUDnqEnBrinDuMitTBGOdw6mOPmi-6ATfmphSMIpazIBCFScCTWBkgCXXmFbpZpnIybQAsA-WZ9Lhphzpgosx%2ByCmWysX89RuLfb4sJRQWMbYiZRTUHgNsBAOwVQZR8juvDzH8OVayvIKRbE31JeSrm8D7lNi5YIHluZXklhhF-MAP8I2ouZcMi%2BbLgk319RIahCBJxZLDUi%2BywovQph1GQUYMLpQ7N9EAA)

#### Code

```fsharp
// Copy paste from: https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/pattern-matching

let filter123 x =
    match x with
    | 1 | 2 | Three -> printfn "Found 1, 2, or 3!"
    | var1 -> printfn "%d" var1

let detectZeroOR point =
    match point with
    | (0, 0) | (0, _) | (_, 0) -> printfn "Zero found."
    | _ -> printfn "Both nonzero."

```
            

#### Result

```fsharp
// Copy paste from: https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/pattern-matching

let filter123 x =
    match x with
    | 1
    | 2
    | Three -> printfn "Found 1, 2, or 3!"
    | var1 -> printfn "%d" var1

let detectZeroOR point =
    match point with
    | (0, 0)
    | (0, _)
    | (_, 0) -> printfn "Zero found."
    | _ -> printfn "Both nonzero."

```
            
#### Problem description

The OR pattern is broken into multiple lines. This is not part of the style guide. The examples are from the official F# documentation.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2022-11-30T16:12:47Z - ec5e33bd7516a031cc1f7290c9a018682675e624

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello, the official documentation of F# by no means reflects the F# style guide. So pulling out a sample from there unfortunately doesn't mean anything. The style guide document is younger than most of the F# documentation.

That being said, [the F# style guide](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-pattern-matching) does not go into any detail on the `OR` pattern inside a match clause.
You can open an issue over at [fsharp/fslang-design](https://github.com/fsharp/fslang-design#style-guide) to engage in a conversation.

From Fantomas' point of view, there is nothing to be done here for now.
If a conversation leads to an update in the style guide, Fantomas should be updated, but not any sooner.

Thanks for understanding.
