### ISSUE TITLE
Attribute on ExplicitCtor is lost

### ISSUE THREAD

**Issue by dawedawe** [fsprojects/fantomas#2638]
Regression with 5.2.0-alpha-002 [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKsAOiB2YDKAngM4AuiAtgDoBOl2NdJBWYAsgQMIA2AhkUWAAUPNAEtsJADRgARmIkBKMAF4wDXBDW0NEchRmJqYAG48uYAArVMAQRVgeYAO6iSACzABzRFLBEf6ppgeuQGRqbmVpgAQvYyzq4e3r7%2BJOqBmgDaADwA8jJEsFw%2BiIKUkAAisGDYsCRgAK7%2B5QoAfAC6GRDYiE6CAB7yJErKXUFsnLz8A9L9CpCS4FCpJOKeRKhgmUsQoONQACRMWJuQ4iQLO5qQBxENyGjb%2BxAADIvPUACS2EgSeKIAL2Q72eABYrhB2lcAL4g3YQw7HB5Qc6XfY3O7Ip7PACMcPGkFYPH6ABlxIgSThPO40biAEwvBFQoKwq57AlHZjIyA4eC5ABmZJ6eCYxVpQQxZnum2x%2Bzp%2BIlAFEfgKhcCERBIFx%2BZAmTD8eyJZyTmhIDJYEVxddblKsRqwABmBXXb7%2BagkABi4jMADlelxyVagiRqPc9SyDQibkjTubLc7JVxpY97aDnZq8BgeNBENFEPzYNREBYeNQeHoyNQg5oQ2H9szNKygobrTHTXGuNXE8mtvaAKzpqCZ7O5-OFimwJyGaB8RDfYywGerWDYasQWuIcONyPo43cjtdm1Ju0fABsg8gw5zeYLRYAqhgsNQZ-554ueMvV4P%2BWZ-FuIE2mgtpqe6xhanYJkePayuMADsF5XqOt6INwfBEBwK6kKG0AkIWa5gD%2BXB-vW%2BpslGoHtuBh6YjK9oABwIVm15jkWrD6IY%2BGEcR4wNgBO4cm2UAHpBNEph8ACcjEjje44YVwK6cb%2Bm4kRGZG7oJZpUSJtq0R8OJvPal5MYgNj8pWGHkOQPD4Ru-5gIB8LqVyYHxuRom9npeKGYhMlFngFCiHA8lfvaXHKTxpHNuRGnCW5OlifSUk5qZlb%2BeQgVFApg62Sp25qQJzmUa5u7uTBQQ4k63nGTY1gND8FSIAG6WVjZobhUEvH2fxRoaai2nHrpuJpoZRL9J8-IACpuDgeBuIWJAAOqiPANKDoyuV8flPWFSiEjUfFHm4gOI3EuNU04IqRGILN81LStbj4ae60RapUVOSau0XP10H2ji54nWN2D8qI-S5E%2BH6Foq-QYEW-CiFl9HPR1kVAdFO1nHt30nri8EAwASogcDUPAd2ramSOaJ1DlgMBiLo31cUDQl%2Bw4gx%2BOE4W8A%2Bg0oSGAKnxkOQGyDjidnU7T0bo%2BQDRcKsAY9B6hZWSQlYTc5WODSzkmGQTRPwKwMty%2BSivUMrLUXtAbiltmlYAPouPduobV1W2tvTmOMz9HwMheo01WWBC5NQZKkKTD2DnRFOQijjkFR9GNfZ72Nyl5HyEsS-s8IHweiKQ3O89Q-OC8Lv1i91bvx9LsuiPLiAm2bhhqycGvM%2BMdLyoZmfZyHJAG9Xtf1x%2B5uGZb1s4YY9vLTSZeuyBvUeyVB1lZodKVWno0AGq2tE4jwGsYf4ZHM9vXH3IM4vTOHXKw3r8SHp1Th8PYDvPz71P4fk8fqPvWfC8cqV9o6THVvv0KoJAADiPgoYw0QHDFcB8I5RzAFTcuc90axQvl7Z4dJ-rr0NjXck0R5LQAANbRDLKQnwRBcjYDwOWFCRQeYhQ%2BGFL%2Bsdtrxwwf-JegDcZpz9E4WueYSBThwE3RADVgbYFcE-GwPw2IFxLh8HKL08onw4fuLSSdNZtzZmnGwAZPDYHvtgR%2BK5-hGI-A0IsE1YDfF%2BCQD8T9FJXTYTTNGnCtGYOTm3bW%2BjZaGGwE44wE5sCeAUWESR4gZGYRcdxZGr1v6nxchBbRrcggOgMng6uaoSTlhkPAHg3BYBEDWAI2ucT2qUxju4n%2BKT9qX2XhAB0qdniQGgYYUQegJBmAANKIEQBgexOASDfHITwUxH8WFKTcRLCiQkvHcMafaB0Hc05EImSQtURAaqwDqlzWBZB9b4NrtA2GpTYnZTarMjxmjipLKwfsB0a82nRFLL5CRudoDUC6d6I5d5pErgatAXgZZPyVJuXUoqqTvE6IyTfNpHSfndMcVwEUtUsINAwCKAgYpvwzOduLW5pxz4PJ8Rk4BbT%2BmDNGvnMIAoNnYC2eSJRuIXhIJQbPOmnj7lGgAR8B0uC2nosCr3BA6ppmuMJUsdoIIzhEA9KUzYrDoRAA)

The Attribute on the ExplicitCtor is lost.

#### Code

```fsharp
open System

type MyClass (a: int, b: int) = 
    
    member val PropA = a with get, set
    member val PropB = b with get, set

    [<Obsolete("Do not use")>]
    new(x: int) =
        MyClass(x, x)
```
            

#### Result

```fsharp
open System

type MyClass(a: int, b: int) =

    member val PropA = a with get, set
    member val PropB = b with get, set

    new(x: int) = MyClass(x, x)

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Dallas/5.2 branch 

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Fix available in [v5.2.0-beta-001](https://www.nuget.org/packages/fantomas/5.2.0-beta-001)
