### ISSUE TITLE
Implicit module is added to resulting code

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas#264]
```fsharp
open System

type T() =
    interface IDisposable with
        override x.Dispose() = ()
```
becomes
```fsharp
module Scratch_6

open System

type T() =
    interface IDisposable with
        member x.Dispose() = ()
```

**Comment by nojaf** [comment]
Hi, I couldn't reproduce this. When did you encounter this behavior?
Using a script file? What settings did you use?

**Comment by auduchinok** [comment]
@nojaf Anywhere where the implicit module is allowed: the last file in console apps, scripts.
<img width="347" alt="screen shot 2018-07-27 at 17 42 36" src="https://user-images.githubusercontent.com/3923587/43327589-7bd936ac-91c4-11e8-90cc-9a16cb1aba39.png">
