### ISSUE TITLE
Record Type Annotation gets put onto a new line

### ISSUE THREAD

**Issue by panmona** [fsprojects/fantomas#2647]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPMAvGADoB2EEwZFNYAyrALaIAyspA5gHICGzAjITD9qtCA2ZtOvZgCYhs0WImt23PogDMQzUrABfNAFkAngBUTAB2QAacFADO2LAEtOD1GADa9yr4qQACRYVshokG5YkHZiQQBuPOgArmHe-jQADDFiUACSpEikWHQuAF626RQALJUAuv762X6xwaGeEUXRlfGJKZ4+OcJNtJBGPLgsbqyInFgAFl2D-LIZdQ3DoC0h1u0z8ADyAGaTpIh0IZiLI4EJyakDObLDNJAAogVHJxWDkOiHkGsaI1-JtrttUpAAEawWDoK4vG69e6VCCaZ4BfJOABOWAAYm5ElxEAB3dBTeG0LBYlKAijAmighHg9rQ2EUiA9O79FFgKrojl0Sw8aCIABCiEOsCxiAACjwsRosIgseyKFSaWJ6kCNt1Wjtwqy4ejOX00A8xABWflQQXCsUSqWqYnK6A8Jz5OKwV2udiqiDqxC0iD0iiMgJ6iGG1Um5GDABs1sgtpF4sl0oAqpZrFjXe7SJ7vS5fdbDoknEGDDqtm0DTCjbrbqa0oMAOyJ5P2tOIADC6DdDm77Ac6ugWClfrApfQ5c16xBuuZtbZxsRXLNPIAHO2hSmHdKjIhGJDlROpzPaFq6VWwTWoFGV43YzkAJzbu2px2D9DFnlnwOz7V52rfU7zraNVybc1aH4LIeSTHdEAAQUOJUsUHRhGB4CcAwrENmhvECoTAh8kW5JZ+DfXcuzoQ8XDgb9SFPMt-wvOcGQXW8iOXBtSPXJYnjgjtkNQmjGDo2Ef0GHCAKvICCMjYieLXZscn4NFBIQxCsVgJICgAEUQMkxNQ7DqRYmhL2Da8mU4yJwMfMjVL5OCxlwXJDjMOYZjoOYpSwAB1Fx4HmCdVhkqy5Jswi7JI5SoJofgrRc8Z3M8mZXmnM5fJxQLgoWa04zC1jAPY4CIRipTIJ5fgE2StzSEOFxcH2bMeDHLFXlwSxpQcBwi0Y60NyKiy2NDDjos6WKqqWNs6oAJUQOAsXgXKQutKphooSzK0i8NFygCqWgcvjVK3ebFqleAuCSI9lSOXIlUYDxrX4XDrL2zjGCSdBXDJU5cSlTCsFQiwdimp8xH4V84IWpb4CMb7fqmAGsSBkzE2gOZ5WFVCAH1iSCkK3t2jkI3aQ7rmOlSxBWRNXK0hUTH2LFJmHVb8s3TaIG2vCwDDUn9o6KJwccmmKLqhmeCZlmXGHa7bqxe7Hue6ridK+T2i+n6XD+xAUbR5VQe+SneOp2hZAEn5Jel1msAR7Xdf1tr0bgzHsdHZV8cJhY1bGsrycmyqIfN9SflcgA1JFRTceA3A4dmJyG338Ki8rA6O034ooWRnLD8ZcV00d+ujgo44T9aubAHn3oF2z05NuKeVkJK89wPTYCwABxbBOu6xBev68vOeTvnxoU7iM8bwZZFqsPEZ1qZRW-aAAGtRQVVfsAcfZSDoDQvxugbf2Ykf+agMml3rSfpseWafiJUlF+wZ0ZiNgzGtIFwfVIRCCgPBWVZSTMqfMeLJFLX2DjQWQZ0rZkg4KQAupAi7sBKPAtqSRpRmFgPkQoWA2r9SYplEB-tL72Uzk3aGsDUKkHwXEVQnB-7HixO-NwX9+qAJyH+YhGtSEixOmITQsE57ay+CwPgkJ4A8F7LAPq0gSS60IeeEaJU-Y8NAhPBuN8BHix+L3ZULhmBFESAAaUQIgSwOCZhYHyOvHgSCOaDC4eFHa6tU5gI0QiKmWdUSWxyJAJediV5fAcFpHSBQiTDkQPDeeute49T6kOUyGpiqyVcR9Qi94g6i1oJoUOfjRTyg-NKPSstoBYgMQSJU8B0yf3YAZaAfYFTf0UeZLao0U7pPHlfTRkCKCaFzn4vR5TDF4PQOcbSSRhzUksOcEwlwSwn2cbzM+QRBYU08eQwYmgW5+NMeY1y8smFHACaQIJUwOGQwyJXauJNz6C0yRA7JNBNCzz8eMuidsEDGzEE4lJwZ7C1GyBEBwuI+qeC4foIAA)

#### Code

```fsharp
let x = 
    {
        SomeLongName1 = 1
        SomeLongName2 = 2
        SomeLongName3 = 3
    }: MyType
```
            

#### Result

```fsharp
let x =
    { SomeLongName1 = 1
      SomeLongName2 = 2
      SomeLongName3 = 3 }
    : MyType
```
            
#### Problem description

I am not sure what the guidance of the two style guides currently is regarding these kind of annotations. I didn't find a mention of it in both of them.

With the main branch it formats the annotation on the same line:
```fsharp
let x =
    { SomeLongName1 = 1
      SomeLongName2 = 2
      SomeLongName3 = 3 }: MyType
```

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Dallas Branch

Default Fantomas configuration

**Comment by nojaf** [comment]
Hi, this isn't part of the style guide so I took creative liberty on this one.
A while ago an issue was raised that shows it could be dangerous to have the type on the same line. (https://github.com/fsprojects/fantomas/issues/2295).
So I guess, out of precaution I changed the code a bit to always put it on the next line when the expression is multiline.

**Comment by nojaf** [comment]
I took another look at this and I'm going to stand by this.
I aligned the implementation with `:?>`, `:>` and others.
See 

https://github.com/fsprojects/fantomas/blob/af1f162f656d88726362bc899be8a2ddecf8a016/src/Fantomas.Core/ASTTransformer.fs#L696-L707
