### ISSUE TITLE
Comment on first chained function call gets lost

### ISSUE THREAD

**Issue by panmona** [fsprojects/fantomas#2649]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBDADpgOgOwggDoBVAZ0QA0AKHSSugSjAHoWwBhWAW28TwAuRfITCkKATVr0mrdl178hIwuMQAtMNIaRmbTjz6DhefFlwFV5KtQAee+YaUnRaqQ4OLjK4tfXUPBSMhSAAacCgKAQEASzwAczJUMABtCIhQUQhIABIBAE9MZDRIOIEw9MJcgDd0ABsAV2LUytEABnCsqoBJPCRBAGUYgC9kTq6wABZWsABdSoBfcYyZ3IKi5NLBCq6a+qbktImwAEZlrMgAWXRbABk4xFv+eIEACx2Jk4AmNpn50SWlUyFzyhWakH48AA8gAze54RADAp1MarHK1RrNI4TL7nUSQACifVh8NRx0gdRhkD+i3OwPxoI2JQARrBYHUPgyMQc0NiugBmPE9PAUABOAgAYnF6gA5RAAdzqD05WQEoqaNIBdLR63BrPZKuy6P2WJmEEmQuyA0w6GgiAAQogYbBRYgAAroUXoPgCRCiw2ENUarr-QiA0T0qqMvVsjlCvaYw5msAAVktUGttodTpdj1g8r90HQFF61VgRdisDwAYgQcQmrD2t20c2+rjaO5puOADZ05BM3bHc7XSRsIXi4hS+X0JXq+mYfUKA2IOHCJGjbrW7GAwmeS1jgB2PsD7PDxAcOrFshcEVB6ACF01sALupLkO0oE6sFbg3x42J3lkwADmPG1BxzV1LkQbhmT9J8XzfLJQxXJsQU3Fltz-Tsk2OABOUCsyHXMuDqKt4MXet3y1T9m3QqA2x3f89z5LITg6ZN+zAxAAEEYV9UUgnQJ862XMBVxWWjvww38OxNHDPjODiTyI10BmgmI4FIudkwQyikI-CMvyZejMNkgD90+XElK43j+LU7gNPZMj0xEqjGxotCpJMmTm2wwDjhOQVrKzbjRVgBo+gAEUQJUHP44T1T00RkLE1CGTorZyiwuT-M+C0OOuWxuhhAAVV5+AGV4XQEAB1GJ4DeJ9fjclCPPSrzMsYvyLK6E40wKm5irK-gCVfREqvFOqGvedNu2a-TqMMyTjM67LzJY0QTl7AairwGEYlsKEii9B9RQJWxMFdMgyBiZzgPm5KDLXIzwTKLqcp61ijx2gAlRA4FFeApsa9NJgewgUvEsB1ygFsSjetbmOTE4QN+-6XXgGUGhgv1YW6X1uCSdMTlEqGYbWDruAaOpYiVBEJRdbgZ34krv0RrtPnwji-oB+BLmp2mHgZ0UmeiOC+2gV5PVtfiAH15XqxrSbSqMMoRsykeOH4+0K0KvXyKFRXuMhasVmb7uVtrVY69XfI+jbCC+RTyV10V9cN42BCxnHRTxgmieRy2ls8laqZpmI6cQYXRZZtmNY5rovis8k9fQA2jZiE3+fDyPo+Z8WOMl6X7z9eWzepFrUqtjcbe2dn5MToKXZuAA1E17TieA4niYHzeOIDwYgSGVZrlbbZBbqHYgL58ub2wJQi+9brwDu+m73unzBoPnuW166-jhusi+fq58i2ABAAcUQARzsuxBruXjf0wH7eJJDmMfIn+3ky+baXYFiODx7SkWgAAa3tF6MB18yBQjwAMb0552TY20scXSr9oYvR-O2O260f7fXJHKRUQDr4Fn4KzIo0V9p4BiLObifQoI+wDscVyC13LB3aitBi9dcqJ1RinJU8Q8ALzwEvKsQxBEzgaK6EqsBej9AEDOZe5ExroPJnDby2Cv64K1lzfh-E8CKOqHmBIDDYKikoXEGhy8mETDQZXMmmDpKaK5N-Y4-J2L-3DqSW43pmTwHQBeWAN0EiEMjsoxCj1Fo73flg962iJj8mdhMQkF0-QxGCPUAA0ogRAmA5FKF6BA9AIi+62IoqoxxGi4mawScnZJwDimgNJGQUK4U+hyhNogPmADI63yujdKsNiugsMiWw6JHCP7OKjJPZM-Im71M9CpRAkVM7QFFOk6Uvp4AkGoVWaK0BLwnSUfOcp9iR6wwylwg+PCsj8lnsk2+aSMl1CRGFBoJt1SYCRPkFE4SkoQyem-CZmxx4uPiQKE+yTsm5MKt7MxsIGl4CaQ8IZrE2iDzmICjBu9YncM+qIfkf9kmvI0gIS4CAyRlJUfYiIsxxilDIBKG6yQ0ELCAA)

#### Code

```fsharp
app
    .UseX("X") // Comment.
    .UseY("X") // Comment.
    .UseZ ("X") // Comment.

app
    .UseX() // Comment.
    .UseY() // Comment.
    .UseZ() // Comment.
```
            

#### Result

```fsharp
app
    .UseX("X")
    .UseY("X") // Comment.
    .UseZ("X") // Comment.

app
    .UseX() // Comment.
    .UseY() // Comment.
    .UseZ() // Comment.

```
            
#### Problem description

When using chained functions (e.g. for configuring DI) a comment gets removed in the first call, but only if there's an argument to this specific function. In the case of there not being an argument, the comment is not removed.
Also comments of subsequent function calls are all not removed.

Of course this is a very minor issue

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Dallas branch

Default config

**Comment by nojaf** [comment]
Fix available in [v5.2.0-beta-001](https://www.nuget.org/packages/fantomas/5.2.0-beta-001)
