### ISSUE TITLE
Update "Thanks to" list in the readme

### ISSUE THREAD

**Issue by realvictorprm** [fsprojects/fantomas#265]
I think the list of people to thank for their help could be updated.

My special suggestion here would be to add @jindraivanek too supported by the statistics (the amount of commits he made).

**Comment by nojaf** [comment]
I'm tempted to close this issue due to lack of interest. 

In the future I can add them more on a release base like I did with [2.8.1](https://github.com/fsprojects/fantomas/releases/tag/v2.8.1).
