### ISSUE TITLE
Double indents in piped function call

### ISSUE THREAD

**Issue by panmona** [fsprojects/fantomas#2650]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBDAdgM4DuiATgCqwCq+AlgG7mGJgC8AOvhBAI4CuiQljqx8XHmAA+APjAAzftwa50gsAFoZEyTwpkChebDIBbZgFkE-TADosZAJ77Dxs1QCCRUpRr0mZCxgKmqIOrrScgDyAA4iYrZI8rg2WABqquoALABMkAA04FAsWCL4AOaEqGAA2kUQoBGQACRYjjHIaJB0+FgF9TwtIYLVdREQAAyF41AAkvhIvQDKdABeyNPjWQMQALoDAL6bDTtQre2dUD19x4PNw5dj4wCMt5KQFrgAHgAyPYg-RAVLAAC36M2eOQmp32kiOA0auhabQ61UgQPgUXkf3wiCWbUw4KR90yj1OEByb0GAFEFlicRtyRh5JAYYdboj3udUV0AEawWDoIlch6jJkAZipEEg8xYZCwADEeqoAHKIYjof7C3QOQRsuEc07Ii5o-mC7XSkmhMUzLJSqBLGK4aCIABCiDciAACrgDOYsOQLTxdYh9Tx4ZJOXcUZdIGahVShqSbeMAKz2yCO51uj0mAGwHzQXAseYMWBF+L4IMQENhiARnhRy0x00ChNGq0jNBPCIANgzWZd7s91BiHTIRZL+DLFdEVftyXQLDrYAbJya3Nj8aDSet3aZAHYB06h7myIgAMLoYuEC9iYRkfjQLAmasKVTLiKw8OGjctvltjunZkjMAAcx7ZsOeYWIgpi8oGC4fqGX7sgiHb-lA26JsBKYRAAnBBp6ene6BiG+i6fro371r+xIYXGgHYaK+4QlMTKZieiAePIAZkHepimLgb61ihBpoX+JoAeaTHJixLyvOxg45p6SywXQcCkfOTIUchVGoZG6GSZhjEdsxtRMpChFcTx5CqaY6mCmR9oiXpYkGRJPLGdJpmyeZEKSopnEeGQsBKPAAAiiCavZvHCY+umSNRq60Vy9HXEBZk9rozx2uxnxfLM8gUCCQJLCCJhYAA6nQ8Cgm+0KiT+4l0UZ3S9BlvlZZIzzpnl3yFcVQLUkueLlfK1W1WC9q9g1rlNe5LWeW1Nw+XufkvP2fUFfg8h0F8sTkLgL5kNSXwxOehCEHOb6gbNiX6Y2hlLelMlrV1PDPEeW0AEqIHAZDwBNdX2lkd08Ela5gE2Zxpe1r1dutETPOBP1-SY8AqvwcHkFiswBqYVT2s8K6Q9DxpLaYqR0JquIKiYgmlOQFAmvDIEvAR7G-f98AWFTNOIHTZhHbFGbQCCvrOrxAD6xA1XVJMpdGrUvatCPvRSbEzB83zBQYjhRGQfzCEDU1MrdCvNalytw6rbMRDkCla-luu4Prht0MImPY2QuP44TFkWwtVsU3z-yCwzvHM6irO4boOSUuxLtu0bWC8+gIj8+HwsIexYsS8+5Ay3LYKB49HmxirG6ZUyOQBU73wZKEro9PAPTlCbN1g3sD3rotFc21XnU17l9dfAqSjPnOzcLG3Hcg13YAQ4rzbWytg9vTXvWj+FsBYAA4tgp3nUIV1iHPZsL0vltK0tWG27Hkg5JtTuh7irqkdAADWroGF-2CEFEfASxcDmBIljLSMwdKl17sHLcJl15qxrl9LWaoNT-HdFgUgQIo6IEirteglYvA81gvBQIcU9SNRotfFet94HEmrjMHIKMtYeE1OUfA498CTzECsdhR1+DnioPMRYWAjrXUQiNaBUMnpwO8ggu2ccOYsPTuQfAYimA-DEOUGC3s8E9DoJWf2kCkJSLJpuVscj6FDxmOKTW4wPhUwZD8EBvJ4C4CvLAK6FRUH83IiYyhyVqEw1anfeRD8eDikdvYo+5A6DmF6KoAA0ogRAMRhFAiwPMH+BAxZ+MkQE0mMiLHtjCXJCI4oE5a3fgQT+DJCDBVCgsNUwhEA81fogI+F1T5EHIQlcGPdpHl2KR1DeNi672NdL6KC55woe2gGQOJyoAzwFoHOSK0BrwGErHkyi903Jlz7sMmOZTdDihHtEs6sT4miPQPiEK-AHz8BiPiRwhIJG7P6fsmBN9+5rysaM8Y4ot72OSak-KXtSFYmqfgWp-wjEvAmJfAZZj6KhP+Ygmxz97F3PUqnBAjJjH5LmvWIouxNjdEIAqK61QoEHCAA)

#### Code

```fsharp
let answerToUniverse =
    question
    |> fun value ->
        TransformersModule.tryTransformToAnswerToUniverse value
        |> Option.defaultValue 42
```
            

#### Result

```fsharp
let answerToUniverse =
    question
    |> fun value ->
           TransformersModule.tryTransformToAnswerToUniverse value
           |> Option.defaultValue 42

```
            
#### Problem description
In the case of there being a piped function call inside a fun, this seems to lead to code that is indented twice.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Dallas branch

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Fix available in [v5.2.0-beta-001](https://www.nuget.org/packages/fantomas/5.2.0-beta-001)
