### ISSUE TITLE
Inconsistent styling when using Stroustrup, MaxRecordWidth and MultilineBlockBracketsOnSameColumn with or without member attach to record creation

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/fantomas#2652]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAcgIYC2iAyuotgGKwBOxAaoQDYCuiAzmALxjAAdAHYQI1AJZ1O6IqTTS64oQHNhosABlC02YnnpFK4QF9hwrLgIlylbACUubFul5rRgketESpM62h8dawA6ABU3L01tPzkooNIwiLBTISTSYgAjRDowdAALcU4w2FoGZnYuAAoASjA0XQoqUqZWDm4%2BD0ixSXi8PkCYxGD0WApDZVyCooHdJPUtXt44weHRgyUJ-MLghcGk40gAGnAoTkR0dA3OVDAAbROIUEjIABILZDRIJXQjh9FXgBurQ%2Bdz%2B6gADMculAAJJCJBCdBkcQAL2QUK6ABYwWAALp-YwYx4417vG5fRG-Z4vIEVG73aEARiJXkgAFlCAAPDRKRAaRAqfJUrqMgBM4Jx%2BPUhL%2BT1ZbxwIMgAvgAHkAGY8oQ2TAsdEkmnA%2Bk4iCilnqSAAUXhGq1%2BuhkBY6sgkoJLLlFoVuHJGVgsBYws9tI4xuhAGZzf84Wc6OgJEJWPhEAB3Fi8wNeAwcV3S90GsmfX3%2BjMQQFGtAMrGR0tkbCEaCIABCiHV9EQAAVCHRrJQ6CXRFnEDnRDL1B7-l6lUWA5Gy3SKyawABWatQWv1psttsaWDJ7LQbSIOEA2AHy6wIT9iCD4cQUfufOKn1%2BmcG4MgyuRABsq8g64bzatnQiAAKrYLgdAHmcx6noQ56Xqu6qsGct7JHm1IFlA079nOIYLtCADsv7-puQGIAAwiw2icORF4KGw0AjH2iHIUOkRSiO6HyphkDYbOhrzqC0IABzEXWAFbsBbKIJk2RXmASEsCh7FurKj7eoWL44QJeFCV0ACcYkboBba0SwF7yYpyleBxd5cZ6PF8W%2B5Z6ZEjKQouf7iYgACC6q9rRxDEIQ8k3ipuZqRhT6acW-HvqGIrMp5JEmcBZAyeIcDmQhi5WWxNmqWO6lTlpcUuZ%2BXhikZDZ%2Bb26XEJl-oWauYUFRFRVRRpWGlc5gkVeojIRsl3k%2BXQsBsPCAAiiBpg1vahXQ2bhZxkXcdFUDfNp8X4SKmK-hynIwuqoR5AKZB5PQ6AAOriPAQqrhKy12atDnrRSPxlX1i6MiunkHUdJ0CpaSnkBdsY3XdeTyV%2Bj1tStHVrV171beV30-n9XJwuq4icqqEFwfQlqctgwGcJw4jNYuwmw%2BotloS9E48Ztn26f1oiMkRGOcg4cB0PAEP3YuNOiHT97Ep1SrM71rPfaJXM8-Q8D4Gwsl0BqMKUMQ1yroyqFi-wxXksQTiXGm2rNHBvahE%2BLMft9hmeQrfNsib4hm4gFsXHJv7QHkXb1r2AD6ya3UKev2Yzb1S9S22uV44r7Vyo3dpgqp0Dy0gC1Dq7U%2BHDOlpO5LR-Ksds6aSUOgdyeEKn6eFDIKtZGr6oazJ2vfXnCOvUjxvOG7vKe1bNvS3b0KimannV7XGfoC7ffu4P3ueb7-uMdkweh1DncPhLReUrbCWRKKQ2V1y5QcI2SjwBsWfybnT3013kdI8XQao2Pe1c9QE2MRTQiX-CG%2Bm95KYmFhAUWEcC5M33iPQ%2B8dfqn05JNWA6AADi5wiYky4OTC8t8c5gLxIVHeiMSqxVgTtI%2B6NK6u3do2cy0AADWjZuyMPOJwVUQgyDWDMirHK0JWq0yIeLEhz4yEx3fl0UUnMHRJlTLyZs6A9wCmtrgaa2MhDiHgj5eE0lVbt34YtfKgj2rEO7qQ184ivpjzlg6HyaZlBCG-kIX%2BF5kQOLgmwYCoRYBwgROgOCf9LKsW3sIsxoiLElwkUfB2tjnDZATJcAEfILzKF0U3NRShNF-30V0PKISDa7xihEt%2BViuhhg8tQvudotCZHgIQSisByYqFke7IJIN8njigW9JyliZbhgrl0K0xNsjiFIIiVgABpRAVBfECnQHCZhhBnHZ1ysEh%2B%2BtOlQELkUlGpTIhhgng6OhSyGF2k4KNca8IkzSEQPAOepteSYNJjgoQOTIgCJFkIgpIidkHwoV4MMJ9BmNi7KlRAk1CjQEUA1BJtyQIaIvNNaAVFuzwTadZYx8NTHP3MbsvpZTP4OkwSMsZ-iWBjHGvRbAFBdT2i6B88BXzNmkijjA3po8ykIMGVMqgB1laqw1McoQpzeRvMquCAhED85bMcj1dlcD1BhioYMsYmVZ4IDpZEPJ6yTi4gxF8Tg1ByY3DycYIAA)

#### Code

```fsharp
type NameStepFormValues = {
    FirstName: string
    LastName: string
}

type NameStepResult =
    {
        FirstName: FirstName.T
        LastName: LastName.T
    }

    member this.ToFormValues() : NameStepFormValues = {
        FirstName = FirstName.toString this.FirstName
        LastName = LastName.toString this.LastName
    }
```
            

#### Result

```fsharp
type NameStepFormValues = {
    FirstName: string
    LastName: string
}

type NameStepResult =
    {
        FirstName: FirstName.T
        LastName: LastName.T
    }

    member this.ToFormValues() : NameStepFormValues = {
        FirstName = FirstName.toString this.FirstName
        LastName = LastName.toString this.LastName
    }

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

If user enable Stroustrup I think it should be applied everywhere and in the case of the `member` it should written with the additional `with` keyword to make the code valid.

```fs
type NameStepResult = {
        FirstName: FirstName.T
        LastName: LastName.T
    } with

    member this.ToFormValues() : NameStepFormValues = {
        FirstName = FirstName.toString this.FirstName
        LastName = LastName.toString this.LastName
    }
```

*This is just to show the code, the placement of the `with` need to be reflected upon*

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2022-12-03T22:59:05Z - 47c6ac6c15abf2830342866987ddd496be326c05

```fsharp
    { config with
                MaxRecordWidth = 0
                MultilineBlockBracketsOnSameColumn = true
                ExperimentalStroustrupStyle = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by dawedawe** [comment]
Hey Maxime, thanks for raising this issue.
CC'ing @josh-degraw in case he can help.

**Comment by josh-degraw** [comment]
So initially this was an intentional exception due to AST limitations at the time, and we haven't yet reached a consensus on the best way to approach this style. I actually mentioned [in the style guide discussion](https://github.com/fsharp/fslang-design/issues/706#issuecomment-1250136581) that I was personally in favor of using the Stroustrup style here with the `with` keyword, but since there are a few ways it could be formatted we might need to figure out exactly _how_ we're going to format it.

**Comment by nojaf** [comment]
Hello Maxime, the style guide does not recommend having the [with](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-record-declarations) keyword in the first place, which is why when a record type has members, it resolves to the Allman style to avoid having offset errors. This reasoning could be considered consistent and I could close this issue here and now.

Stroustrup is not part of the style guide so any new issue could always be closed on sight. I encourage you to engage in https://github.com/fsharp/fslang-design/issues/706 to change this.

Overall I would be ok with having the `with` keyword but your proposal is ambiguous and [should not be discussed here](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#what-are-we-not-looking-for).

**Comment by corsinpfister** [comment]
Just wanted to mention that Stroustrup is now part of the style guide (see [Multiline bracket formatting styles](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#multiline-bracket-formatting-styles)). Moreover, an exception to the rule discouraging the `with` keyword has been added for the Stroustrup style, see the section [Formatting record declarations
](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-record-declarations)

```f#
// ✔️ OK
type PostalAddress = {
    Address: string
    City: string
    Zip: string
} with
    member x.ZipAndCity = $"{x.Zip} {x.City}"
```

**Comment by josh-degraw** [comment]
@corsinpfister Thank you for the reminder, I actually added those updates to the style guide in part due to this issue, but I had actually forgotten to add the changes to bring the style in line in fantomas itself here. We'll try and get this included in the next major release 👍🏻

**Comment by nojaf** [comment]
Available in [v6](https://www.nuget.org/packages/fantomas/6.0.0).
