### ISSUE TITLE
Fantomas is replacing Windows/Unix line-endings thus losing Git history in commit

### ISSUE THREAD

**Issue by Thorium** [fsprojects/fantomas#2654]
After running `dotnet fantomas src -r` the files I've not modified at all are all changed, so I cannot do `git commit` without losing version history.

![image](https://user-images.githubusercontent.com/229355/207840961-7dacecd8-67a6-463f-ad11-64dfc181ab2d.png)

See there is no real changes in that file at all, it has to be that Fantomas is messing the line-endings.
If I do git reset all and run fantomas again, then the same thing happens again.

**Comment by Thorium** [comment]
This file was already formatted by Fantomas on Unix-based machine, and now I did run Fantomas on a Windows-machine. Can that be the issue?

**Comment by nojaf** [comment]
Hi, could you try adding the [end_of_line](https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html#end_of_line) to your `.editorconfig`?
When not specified explicitly, Fantomas will use `System.Environment.NewLine` which will differ on Unix/Windows.

**Comment by Thorium** [comment]
Thanks for the response. Could Fantomas just say "ignore if differs only by line"? Or if not, then maybe"read the line-change char from the existing file"? Because not all the time have I control to repositories where I'm sending PRs to, to modify .editorconfigs.

**Comment by nojaf** [comment]
There is no functionality like that right now. What you could do is create an `.editorconfig` file higher in the file structure and included the setting there. It should pick up settings from the parent `.editorconfig`.

Something like:
```
C:\Projects
  \.editorconfig => include setting
  \ThirdPartyRepository
     \F# files
```

This would not work when the `ThirdPartyRepository` has an `.editorconfig` which starts with
```
# top-most EditorConfig file
root = true
```

**Comment by Thorium** [comment]
The problem here is that .editorconfig modification affects outside Fantomas. If there is an existing repository, modifying editor line-endings for even non-F# files is not justified. 

Would there be a command-line option to pass settings?

**Comment by nojaf** [comment]
> Would there be a command-line option to pass settings?

No settings come from the `.editorconfig`. You can specify very specific rules in your `.editorconfig` to only target certain files:

```
[Folder/SubFolder/MySpecificFile.fs]
end_of_line = lf
```
