### ISSUE TITLE
an exception erases source file

### ISSUE THREAD

**Issue by s-trooper** [fsprojects/fantomas#267]
if target buffer is the same as source and the formatter throws an error, then the target and the source are empty and the original source will be lost.
to mitigate this problem there are a `--force` argument but this is by default `false`.

1.  it is counter intuitive that per default the files are erased. 
    could` --force` be set to `true` per default?
2.  why an extra argument at all? i don't see any user case that should allows formatter to destroy source files.
    could `--force` argument be removed and the original source be kept in the exception case?

P.S: i will make PR for case 1. but honestly i would prefer 2.

**Comment by jindraivanek** [comment]
Agree with 2.

**Comment by nojaf** [comment]
I'm also in favor of 2.
Vote **+1** for option 1, **Hooray** for option 2 and **-1** if you don't agree.

**Comment by vasily-kirichenko** [comment]
Fixed via https://github.com/fsprojects/fantomas/pull/268
