### ISSUE TITLE
Sunset MultilineBlockBracketsOnSameColumn & ExperimentalStroustrupStyle 

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2710]
In https://github.com/fsprojects/fantomas/pull/2658 we refactored`fsharp_multiline_block_brackets_on_same_column` and `fsharp_experimental_stroustrup_style` into one setting `fsharp_multiline_bracket_style`.

For v6 we should remove all traces of the old settings and update the documentation.

**Comment by josh-degraw** [comment]
Can this issue be closed now or are we still waiting on anything else for this?

**Comment by nojaf** [comment]
I typically close these issues after the official release, when everything is available on the `main` branch.

**Comment by nojaf** [comment]
Available in [v6](https://www.nuget.org/packages/fantomas/6.0.0).
