### ISSUE TITLE
Missing docs on how to use multiline_bracket_style

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#2743]
The [5.2.0 release notes](https://github.com/fsprojects/fantomas/releases/tag/v5.2.0) instructs to use the new `multiline_bracket_style`. However, neither the release notes, the two linked issues, or the docs give any clear guidance on how to use it (for example, what value to use for enabling stroustrup-style brackets).

What are the allowed values of `multiline_bracket_style`?

**Comment by dawedawe** [comment]
@josh-degraw We have something for this in the v6.0 branch. See [here](https://github.com/fsprojects/fantomas/pull/2728/files#diff-8c398a95c800a0f1ec078d842b43babe102dd037851a4c87255381d559b6baa0)
Maybe you can use this.

**Comment by cmeeren** [comment]
For the record, the correct key is `fsharp_multiline_bracket_style`, not `multiline_bracket_style`. (I was just about to publish a bug report saying that it didn't seem to be implemented at all.)
