### ISSUE TITLE
Revisit `--profile` flag

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2751]
In light of the new logging from https://github.com/fsprojects/fantomas/pull/2693 I think we need to revisit what happens when you `--profile` as an argument.

Currently, the output is full with:

```
[16:04:28 INF] Line count: 204
[16:04:28 INF] Time taken: 00:00:00.3194135 s
[16:04:28 INF] Line count: 120
[16:04:28 INF] Time taken: 00:00:00.0386711 s
[16:04:28 INF] Line count: 1536
[16:04:28 INF] Time taken: 00:00:00.0620313 s
[16:04:28 INF] Line count: 266
[16:04:28 INF] Time taken: 00:00:00.0184182 s
[16:04:28 INF] Line count: 1222
[16:04:28 INF] Time taken: 00:00:00.0366623 s
[16:04:28 INF] Line count: 368
```
without mentioning the name of the file.
Maybe after https://github.com/fsprojects/fantomas/pull/2717 is merged, we can check if we can incorporate the information better.

//cc @dawedawe

**Comment by dawedawe** [comment]
How about adding the following to Logging.fs
```fsharp
/// log a message if given value = true or the verbosity level is >= Detailed
let logIfGivenOrGrEqDetailed b s =
    if b then logger.Information(s) else logger.Debug(s)
```

and calling it in Program.fs like
```fsharp
logIfGivenOrGrEqDetailed profile $"Processing %s{inFile}"
```

**Comment by nojaf** [comment]
I was thinking of maybe using `Spectre.Console` instead.
https://spectreconsole.net/widgets/table caught my eye. I haven't used this NuGet package, but it might be nice to give a table overview of all the processed files.

**Comment by nojaf** [comment]
I think moving the profile logic to `Format.fs` might make sense.
And just add the results to the `FormatResult` somehow. (Or wrap the result in a new type and add the profiling data or something). Then in process the result in `Program.fs` using spectr.
