### ISSUE TITLE
Lists passed into constructor are incorrectly indented

### ISSUE THREAD

**Issue by JonCanning** [fsprojects/fantomas#2754]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMXEGcsBBABwEswBeMAFQOPIG0wBDffbARgG5X3sATGAC6kADTgoHLFjIA7AOb5UYRpIigIWqABIsATxLI0keVnHqtkHQDcW6AK7HVl7QAYJ27ZACScpHJYAMpkAF7Inl4QACyuIpYAvpEacdYGRiqmgRZR1naOzmpREJzJXpAAsiwAHgAy8oi1iIpYABY5xZwCbnHCiWWa5XqGzpDN8ADyAGb1cohBBpgd3rb2TipFxQJl3gCi-tOzEXEQkOhTkL39loMr6aMARrCw6MtWqwUbJ2AAzDtWfg4ACcsAAxeT2AByiAA7ugGm9tFggU4rtokjdUsMMiYni9Ebp8us0JsotF-qcgiQWNBEAAhRBTWBAxAABRYQJYAFtsIggQSIMjUVE%2BuiBlj7pk8a9-nk1oVvgBWClQKk0%2BmM5mNWAwvnQNiIPw2WD62SwOQC3AoxBorQY7S3d6S3HPGVYokK4pgABsKsgatpDKZLIAqiQjED9RwjSaWGaLSqpvYOLaIPatI7TtjHq6CXLPiTvgB2P0BjXBxAAYXQbHwlfNhBR0CwzMtSfQKZF1wdEpGUtzso%2BxJcXoAHKXqYHNSyKoguQ8%2BW3kzau2LMbls-38YOPV8vQBOCfqoNa%2Bvoc1Ljsrryiu3ijfOqDSvNDz2dDzff2TxBEKZ4IH1lyXIsJaQrXtot5pveQyPpAz47vKe6dKUn5lieLJBHOZBwOeCbfO2nY3t2Ga9jiT4Du6iGFl6XRHrSv7-phXLYS8F4qmBqZgOmKQPn2LrbpRBYjp0fyod%2BRBArADj%2BAAIog8LMf%2BoHWpx3FgJmuiwWYL67tRnTkp%2BVTVD4Uw0K0zRBK0zJYAA6mQ8BtJaPSrne64wXxUDaQhQmkl4nDKoZNQmWZzS7FelnWXZDntCq3rOURa49rxZFZOY3nDr52icL6gXGXIUxkNUEwRnGzK7NUJAsuwZBsd8o7xRBxE8e5KVeYJGXfJwJa5QASogcBAvAUWOSq0QNVokFcdBdwealOlUcJUScOOvX9cy8CQg4858tMPh4FyygqpwqnTU6s1cg46CyPCcygsywEyHyNB9ulb5LYen59QN8AVJd10NHdQIPUpfrQK0HI0v%2BAD6ML2Y5J1uTNrXZK9SFRN0fpGRJnL6BMQL1IQw0xXV40QJNakaWks1tRuumLV4AgoV6lQ1NjLC4-jZCEJt21Art%2B2HZ1CNJS1owXVdZA3YggPA09L3tW9DPbJ%2BbMcwTWC-RLUsy3GIOfmDEPNnyMNw%2B0wskclow00MdOZVoAiiczRkAGrynS8jwPIChE5a9Xm81SNWyjCtowzBlOzUoLSc2NVyO7-hez7o2k-EiUW6LmTWystvfAIAUR9UMmwFgADi2DlZVBD4LHSck-76mkTmAm0wtdsQAIOXM9CcINAyWC6s0z1GHJBVyGQ8ZEP4s684LXocS5UGI2dKXwSHeno91zNEPCChyFHcgx%2BaIS73GDgsjQsB%2BAEWBxrHl6EY1acB8vTdui3Pm5ytW9XXyci3zY2pFDTwXECEe8hx6x1nsUAi4EJpNQbpbLcb8bat1zh9J2f0yBHFqNyB48AWDVlgNXRQ3cpb31gWTeBlNNz8WQdnVBXofgfmZhXPkZAeSBHsAAaUQIgEgV9mhYD8HSTkB9iZehgfXahsFV7vw6owpmxRIB0hrHIAA1kcfAEkpL%2BGhIQRAP1MFSwrlVauDZlLCgSq5EWgckHzQ-ow5WzM6QcnQogGSXNoBAnYRCPA8AQxj3NHJaANZOTxnIVIxumRxb-TmCImkajsALH0EsVG68vA-EdkozWsT6ScmgIk4IixjjMy8dyIw8BLgLymkvLMWlg5yMVtoH44clE8L4UZHmIDpgqJYOozRlpOBuBTuTU6dTZqyJQQ44oPx85KIWN45sFQEAlOgcuVSkhhCRFMPgUE1cVCSISEAA)

#### Code

```fsharp
let testApi = TestApi[ asset1; asset2 ]
```
            

#### Result

```fsharp
let testApi =
    TestApi[asset1
            asset2]

```
            
#### Problem description

It should format to `TestApi [ asset1; asset2 ]` and it does if a space is provided between the type name and list

#### Options

Fantomas v5.2 branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Hello, thanks for reaching out about this.

This actually isn't a bug but a consequence of the new [F# 6 syntax](https://devblogs.microsoft.com/dotnet/whats-new-in-fsharp-6/#making-f-simpler-to-learn-indexing-with-expridx).

You are indexing `TestApi` with the sequential expression `asset1; asset2`.

When putting this example in F# interactive:
```
Microsoft (R) F# Interactive version 12.5.0.0 for F# 7.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> let TestApi _ = ();;
val TestApi: 'a -> unit

> TestApi[ 1; 2 ];;

  TestApi[ 1; 2 ]
  ^^^^^^^^^^^^^^^

stdin(2,1): info FS3365: The syntax 'expr1[expr2]' is used for indexing. Consider adding a type annotation to enable indexing, or if calling a function add a space, e.g. 'expr1 [expr2]'.

val it: unit = ()
```

You get a warning/info message about this.

Most likely you are using a newer Fantomas for an older project. So, in rare cases, the newer syntax rules clash a bit with what your compiler will tell you.

I'm going to leave this issue open, as we should cover this in our [documentation](https://fsprojects.github.io/fantomas/docs/end-users/FAQ.html).
(You are not the first to bring this up, see https://github.com/fsprojects/fantomas/issues/2158)
