### ISSUE TITLE
Fantomas moves comma and breaks code

### ISSUE THREAD

**Issue by TheAngryByrd** [fsprojects/fantomas#2771]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAdATugdgG0QBcwBnACwEsAzQgFQoFtESw9ZoBDPAEQ8MTAAKEoQ6ZCKAKqFoAGngBXTHwqwcASjABeLLggQAWmsTxe-AHTRMiPgPpMjORJaXWcxNpx63dOfWAAfAD4we2dHEzNnETFCAHkqX39gsCoFP3gOAE8AZVFxMABaEJiCgGowTNz8wnNuJRU1IrBrKl4s8zzYsLqGwlUcJP1ZSr6ByFlwKBIifpwAcxJUMABtKYhQfwhIABJCLIAHZDRICncJ9f1dgDcuBWPVy-8ABkmtq4BJHCR3HIoAL2Qb3eYAALE8wABdS4AX2BGwhu32R2Wp3O8KuO1ueHuyzWILAAEYMf5IABZDgADwAMmdENTEAtCGQLgTCQAmZ4Q6H%2BOGXTZbJGHB6QRnwBK0px5LIEVmCrF3B74kHsklXACi3wldLl70geCokG5sIxAtJe2FqIARrBYHhdZjsbi0Mr3gBmNXbL4zcQAMTOXAAcogAO54HWesCETD3Y2802Ii0ok42u0O7YKnFKiEQUGRyA5A4caCIABCiCosGsAAUxBwmPxMOn9NHY%2B8efo%2Bf4zZjkSLU-a1TdFXic2AAKz5wvFssVqv02AhxCYTgzL7XdiNHDNiCtxBxzsJvVJ-u2weJp3ZgkANinRZL5cr1kkByOK44a5wG84-TUO9SXAzAeEBdvoPYZn21pns2w5ZqOBIAOx3jOj7zgAwngH4kGhagiDG0CEFW-5UIB%2B7tia-KJpBKbQUOmbOo8BIABzIQ%2Bc7WGSiAMFay7EaRwFgKBCLHtRUADjB9FXiCACcrGzk%2BiA4Ww26RiReBAeR8aUSJlo0WmdGXvBIKEq8Y4FveiAAII0MuOEMAwHD-nuAlCWA4FQCeUH6ReI4umOhLEmZ05sQpORcRQcDKXx6lkVsHYgUe8qiZA4kGb5jHGaqQUWdZjZhQwEV2n%2BkbOZph7aUlulibRPlwX5bIetlM6WZgsDpKYiDhgVjZOTGsX%2BPFgmJeayVnIQEmGfVxl5mZFKUh8VC0GQjI5GQVaEAA6hQ8DMv%2BXJlQlFUjVVaLjWldUZe8hKTrNVILUtjLqjFq3rVtO0spG177XFFHdlRJ1jRN6WulshK3rd804FQFCUnEb58FW6qUgc1gkCQ4yRqC30Db9YH-cmUCA%2BdDEg-4hJIRDABKiBwJg8BvbtmPY-og2ue5QoE6dQMXaT%2BiEixVM01W8CBgo3HLgkHz8AwSyRoSLnDb2J0MAoeD9OGTi%2BlWDmEI2tCWsTUlXbJZnU7T8Bkqr6t0lrmA6z1%2BbQGQdYEcuAD6IbbbtCtHUrnNE7VJNjpy%2BZzS1yhZHEmC0iIDMfWOTHMxArOKxBAPooHRtbOygUEuSVLh9kUcx4Qovi5gkvS7L-k%2B39OmcyrasUBriC2-by76yihtGe87JZXnheR9HFAiJbTct23fAO2ZOBizxmBu7AVBuxQVdGgdQ2%2B2n-sZ8ek2XdnjV53NABqiqlmc8BnPMcf-ontd4-XIoB3vwPBzNx9Ur66QEQMF-fNfW%2BTMH7CUqjvM6mce7Zxup-Sk3BYCEAAOJECRijZg6M1BAITknKEuNQHHU5qlSBU1e7gzzsGMMdJyyECXIyTuiBuAVjOKvAYllvicXLtXAkpUfpaTrmA083lX482DhTAe4Z5g4G-jgX%2Bag-iSL4EoRAtBYBfB%2BKIX8KkxxqQ0rw8q-CCGCPPMIoOBJ2QC3EY2HAKhrgLgWBw%2BejDoY4BYbhaKuicZ8MfgIryxj5T715hAdkJtj5WwoJKek9YrSZAwrAdGCwKEt16m2PRh0DF%2ByMdzUxII3SmTzqg5cjBGSiDwAAaUQIgA4ajilfFLMoGR8cCQ6P6izPBbl8aZO7iQrYbpc4gkgKWTCOAADWESSAtTat8YMIgTBj2tk4VBqMME4C4SCHhnj9HeMMb4rJWd-Bun7v00sYhULWG4CPKwjAAz8HgJIFxahGHQEwsoTR7iWnJzaezTyJxG7zLLMoaAwyiDSllF0g%2B%2Byj79Lmc3KhAKgWEBBUCMyeE2p4QUAcdeqTN7pO3s-Xe-i34EjdB-fp5TKlzTLvPBIgyOAjLGf%2BdkID2lPx2WCwJYA3QwP6Ykqh7FEDQpbnZA4CgNEDEWegjGY51mtK8fgjJrLiHgv0G6Mh-S8iYAioQMkCAkVNP4hvGEUxITAlOCQX06NljNJADCIAA)

#### Code

```fsharp

let shiftTimes localDate (start:Utc,duration) =
    ZonedDate.create TimeZone.current localDate
    |> Time.ZonedDate.startOf
    |> fun dayStart -> start + dayStart.Duration - refDay.StartTime.Duration
    , duration
```
            

#### Result

```fsharp
let shiftTimes localDate (start: Utc, duration) =
    ZonedDate.create TimeZone.current localDate
    |> Time.ZonedDate.startOf
    |> fun dayStart ->
        start + dayStart.Duration
        - refDay.StartTime.Duration,
    duration

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

Seems like a regression/similar to: https://github.com/fsprojects/fantomas/issues/2381

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas 6 preview

```fsharp
    { config with
                MaxInfixOperatorExpression = 40
                ArrayOrListMultilineFormatter = number_of_items
                MultiLineLambdaClosingNewline = true
                MultilineBracketStyle = stroustrup
                KeepMaxNumberOfBlankLines = 2 }
```

**Comment by nojaf** [comment]
Hi there, thank you for reporting this issue 😊.

To solve this, you would need to extend `genTupleMultiline`:
https://github.com/fsprojects/fantomas/blob/18f31541e983c9301e6a55ba6582817bc704cb6f/src/Fantomas.Core/CodePrinter.fs#L1750-L1757

I think adding a case like:
```fsharp
          | Expr.SameInfixApps node ->
              match List.last node.SubsequentExpressions with
              | _, Expr.Lambda _ -> true
              | _ -> false
```

will most likely do the trick.

Are you interested in submitting a PR for this?
You can target the main branch and add a new revision to the changelog if you want a hotfix of this.

**Comment by TheAngryByrd** [comment]
Assign this issue to me when you get the chance
