### ISSUE TITLE
Inline replacement

### ISSUE THREAD

**Issue by mrkaspa** [fsprojects/fantomas#278]
Is there a flag to make inline replacement, when I use the tool via the global tool all the file content is deleted and put again formatted, this is a bad experience for formatting on save and editor integration

**Comment by nojaf** [comment]
Hi @mrkaspa , sorry for not replying sooner.
Fantomas will "delete" the file first and then write the formatted code instead.

Is this issue about not deleting the file and merely overwrite when formatting succeeded?
I'm somewhat confused by the issue title here.
