### ISSUE TITLE
invalid F# code when pattern matching on exception with long when guard and 2 space indentation

### ISSUE THREAD

**Issue by theimowski** [fsprojects/fantomas#2784]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAgmABQCUYAvADoB2EANoumAEbFlW0RjoCGAzgGswwGly4BLAGbcATgFc86ABaJqosV3QzM6jV2htdGgO7jlRsQB8wKAPxgA6omYBlWNAGMAogA9oibHRxWFp%2BMDxjFVpEADonV3dPdC8ZGVgZAGEEPHJHZzcPb1T0mKzqakRoIJCMulg%2BRHgABRlEAFsedDlWukwwADJ%2BsD5Ybv8mnhksCgIAc1UmAFoAPgsNUiMAXxpIABpwKAb0IOpZvlQwAG0DiFA9SAASLFwLyHFqdD2brkeANx46AoLtc9BAAAz7UFQACS1CQHxc4gAXshIaCAEzfCAAXW%2BmzRtyxUCeOGQaDeHy%2B9we-0BZKuRIgAEYCRpIABZHg%2BAAy70Q3NUs2UVNBTPRYKJuLE%2BO%2BdzZJJe5NU8AA8pJeRUXFgGCKxH8AUC0CCMay9V44WqNajGVA6JJIJK8ay5XqFfTIMxYLA6LqfjSDfTjXoAMymn6whpTABi7wBADlEMY6HzfWItApHdLnUTHs93Z7vanibTDQyoQAWMMQSAubA8fwAIUQknSiAmMh4bUYiBkRYg6cQma4MrELr9edeBZ9Yf1dOBNoArFWoLX64gmy3WtzYMYe9B%2BIhYb93J1gtQ%2B7IM3opcPs9SJ%2BSp0XZ6WgxoAGzLmt1xvN1sAVWwXAZH3BojxPapz2XSQAQaIcIBHLgx2rN1Jy9acc39OcjRtAB2L9V1-TdEFqfg%2BDKPh0yqdILxgug4OvJ1ZUwh8oCfGcsNfG0AA4CJ-dc-1adl2mYHtaNgwdGKzZj71JNDCw4ktAxtABOPi1w3VssjqKCbTohiNBvBC73lViPXQ59OOUqEmQhG1vzXfBJHQHssjaDoLwHeCwEQwlZMVNiLMUgN5xsll7MIgTiJcdpxDgHTxPoyTDKY0cWLkx8gswpTQtFdF1P8JyXJkGK2ji70Qk8%2BRkrEIyfJM10zPY7KQpwmzQwi-j8DSOQ4QAEUQZMyuKqqrxS6S0v8913k%2BYLsLLUVK3szkfGhSQABUohcJR0nQBxxHgYVlwlKTbxk0yMqgGbLJytrRSXZauTWzbVC8JLtt2-bDqUC93xO8azsmi6AopWaWvmt8xCZT9HtW6hJHEHwVWAzp0l8bBWj4Pgzwvbj-tq1KkPSkHrrmribPw2GACVKnSeAvqOm1y3xrg6t84Riemykyes0VeOp2mZHgOM5DaUSZDVaEXLac5lyZbz2eQ4kzLaOQ6CCZMKijdIOmOHt1rknncr0Jk1Psmm4CF9k1Y1vltZkXWRq-aAlEmetioAfVMb6HVO4zzsay7QZu1qFr0cUvxW7qO0wFUZF5SiGZ%2B5c8YVhrxyD0nwfJjFwqhDkuWjnhY-j8RKJFsWe0l6XZZteW-fqgOM5B1X1fETXEHtx39cN7PefD-L7KLkuE-Qa2247rvOid%2ByXbdqoey9g7hTTpuULMrPqVusONHRDr85WgA1AMG3eeB3lmJPcZZnFCb84GubBrfQ8hrh0SWg%2BuSjXqqjPU%2B4QvlfZczNV5A0DiTbmfdja7wep-HwfVYDoAAOLeB8BjRAWMzxAJ4jfMAbN07ryDs1Z%2BEMbTohhvnBMSY%2BRNnQLuVQBtcADQRtQMwZ58BwmEpXGQtcoReQborTm8kMIkJzuHSm%2Bd8DJlmNQb%2B1Bf4hERDIzo3REDrVgLCeEvBIKJQMgTCaRMprCJDqQqE6J%2BaSPVj2agp5fj8hCLMLh4tmHvDYSEXhoJ9I1VZnfDmRjMoKSgXdcOZsD423EFabknZmDwB4LUeoF8qEd10d42%2BBj77gPzFlUR-cNDBjsvndGPZxBdg%2BACAA0ogAImiFiwgbB2eRyc9ISVAYYh%2BxijbBLyXnUEkAGx0B4NQAQVo%2BDdVGHCBMlFGjj1thUdGmNsbuNGqkvBvila5iIdk%2BU29X4QGDIPfODZJiaVaH1Mu0AZAlNjC5eA-5WEhAGtAAZHYdHQRaQIghysg6t1meuDshR0BakwDqTpO8xDBn3r0mZ7caH-KSECkFs8OxtFwPAX2AN-ZgObo-ExYi8kf16ZUgIK0K7izVP0wZwy%2BQeJNmCXB%2BC15fJBsQ7ZL8bTBlgb0pJNDBKIGhR3Ny2A5DaLPPMjBizdJ8Oqq0jJ2KOlBLBVwYMFDelakuVUdk2QUkKwONiNEbw%2BBRmxhcLxIBNhAA)

#### Code

```fsharp
type A () =
  let b () =
    task {
      if true then
        try
          c ()
        with
        | :? WebSocketException as e when e.WebSocketErrorCode = WebSocketError.ConnectionClosedPrematurely && sourceParty = Agent ->
          ()
    }

```
            

#### Result

```fsharp
type A() =
  let b () =
    task {
      if true then
        try
          c ()
        with :? WebSocketException as e when
          e.WebSocketErrorCode = WebSocketError.ConnectionClosedPrematurely
          && sourceParty = Agent ->
          ()
    }

```
            
#### Problem description

```
(8,10) (8, 11)Error 10 parse
Incomplete structured construct at or before this point in expression
```

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas v5.2 branch at 1/1/1990

```fsharp
    { config with
                IndentSize = 2 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Siema! Thank you for reporting this issue.
This looks similar to https://github.com/fsprojects/fantomas/issues/2526.

This is an issue rather specific to the `indent_size` being 2. 

I think you can solve this by changing:

https://github.com/fsprojects/fantomas/blob/36b7325045a811ce2228090c90d6a6e6cf5ec462/src/Fantomas.Core/CodePrinter.fs#L1247-L1249

into something that along the lines of:

```fsharp
            +> optSingle
                (fun e ->
                    !- " when"
                    +> expressionFitsOnRestOfLine (sepSpace +> genExpr e) (fun ctx ->
                        // See https://github.com/fsprojects/fantomas/issues/2784
                        let doubleIndent = ctx.Config.IndentSize < 4

                        (indent
                         +> onlyIf doubleIndent indent
                         +> sepNln
                         +> genExpr e
                         +> unindent
                         +> onlyIf doubleIndent unindent)
                            ctx))
```

the idea is to just add a double indent when the `indent_size` is lower than the default 4 spaces.

Are you interested in submitting a PR for this?

**Comment by theimowski** [comment]
Siema!

> This is an issue rather specific to the indent_size being 2.

We do need to switch back to the default 4 indent size one day - 2 spaces might make the code more concise, but they encourage you to write more nested stuff and they make it harder to notice un-wanted whitespace fuckups like we had recently: by accident we moved a piece of logic after a while loop to the loop itself 🤦  

> I think you can solve this by changing

I like it how it takes you more time to guide me how to fix it rather than fixing it yourself 😂  But I mean it - it just emphasises how good OSS maintainer you are by encouraging others to contribute! 👍 

> Are you interested in submitting a PR for this?

There you go! https://github.com/fsprojects/fantomas/pull/2785 

Side note: I'd consider adding a "fast-track" contributing section in https://fsprojects.github.io/fantomas/docs/contributors for busy dads: I appreciate all the rules and guidelines there are in order to contribute, but on the other hand if you had something like a "5 steps to fix a bug" section for a new comer, it could bring in more eager contributors :)

**Comment by nojaf** [comment]
Cześć! 

Thank you for these kind words 🤗. It may seem strange that I give you a near-working solution instead of just fixing it, but the idea is that we inspire you to save yourself. As this is an open-source project, you will always have the highest stakes in seeing your own problem fixed.

I like the idea of a "fast-track" contributing section. We will give it some thought and see if we can come up with something. Great suggestion!
