### ISSUE TITLE
Record member declarations can break with Stroustrup enabled

### ISSUE THREAD

**Issue by josh-degraw** [fsprojects/fantomas#2787]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwBlWXAOgDkd8iSAdAJyfVfYG0AeASXQAXRCwBmxRAD4AupyEBPAqT4BRAG6IhYALxgAlkJHiSYTfDlzBi0hVzrNgnXIgRgYPvDR5BLAwHNnFwg6XC8ffzAAX0CIA2ExCXd7IQs2BSUwAFUCeExheBDSXTcABRZENT1YAFc8QrDfdD8o1PZIABpwKDxEQUF-PFQwLi7XUZdIABIrJSHIOI7xiCm1TAAbauQ0EaCggAZO3YmBJCEyPQAvZEOjsAAWJbBpccibsaOpma2oBbeJydWG2%2BO1uAEY-kFIABZTAADwAMgZEPDNH5BAALRa3MCggBMe0ezyCr3GoA%2B02sczMAHlRIj0IgyFY1tdHit1pshiCjriIRMVOh4LT6azsZA1qJIISXn8ybtPpS0JAAEawWBrLHygEc4GPCAAZj5ywEPRYggAYgZ1jREAB3NZIzVHHybaXE2VsimzJWq9VO-6AznbPX3I1QMiMRAAIUQolg5RKmBY9Hi-qCLsQbpcJKCcshXu%2BKrVGr57KBXJDAFYw5AIxIY3HyvDYLaRNBMD0BGpYO3%2BrB0GmXBmsxAcy48-8vnNfSXPYHddiAGw1uskBvxxDZJQsdud9Dd3tVAdh8RrHojqIe8lTn3FwdloPDEMAdhXkfX5QAwmsO3hP-3vBYapoEEeNBwgU9zyOIlsyvLUbygGd721ctg2xAAON961jDcoUQbBlREcCwEgzNoJlUlPQQos-VLFDH25XYAE4sLXHCv3VftiNIi8x3eeDFUQu86PnCtsVBA4Q1rSMAEFRHif9sGwTBiOHcj3Uo69BJo2dyVEtCwXBKTV2jdjGXwvQ4DWLiT3WKDdhg0c4PzaikJEnUxLBXljNk%2BSRDICyrJskM1Icijcyo7S3LnDyDKOUFDR8iQZJYGpBQAEUQB1sD0VMw1CoJHMvTSBO9H4hGQ-Sn3Eu4axhWE%2BFEAAVdFNDIdF40EAB1PR4AxYiCXU2CSpc7Tfhi1DqrBaspPqxqWs0FQz0ZDqzR6vrMTDRdBrCjSIq0sr5gq9zJsYoJQWXWa4QEUQ9FhaltzyeMVFhAhyjwPAj2I9CdsK8Lx0iw7xr02Kpvi18rthAAlRA4BYeB1v6sM7l%2Blwir4sAJ2WAs5mBrUqrOlxQUwyGYbhgpqgIkRaT4YRsEGMNQV45zJ207BqjWfoHQZc142UvoRCaykToYkNQRYqSyfjeAoQ5rmkV5lh%2BbyqToHRJNiHiAB9W1ev65mRtZoHjom0XsXxOq4RS5N5GpFhEW8RHNpDH6Df20rCzx-MCZDXEjLFerrcwW37b0bwaEpwiWBpumGbFt2AYOwt2c5vRucQRXlcF4XTYXW5cW8sUg5Dh3BFl1P08zvIVbFNWNZAkQdb1zEE-40bjcESrQcJiBcUSgO4QANR1KMDHgfwne%2B1GIHRlnseor2A2733ash81qnQECj1HwUJ%2Bb4iUdbzHAc9k2QdO32ZoH2F0tgQQAHFehet78E%2B-tJ7DV2hqcw356i4Tc6eR5JdMUNp7RIhjIIVsmghZKEyrddAuUjwyUFHhKmLA47YgKmjf6bcjaFmiufM2%2BcIZFwdH4dA69N59nQOcCheRqjlCarAE4Dg8hfVsstI%2BWMoA41vLRQBcVdi4hJmQ%2BIWB%2BgaGbE0NBUd4EGCQQBbidkyK7WGu7duBCAFELzjyCWAc5Z6BFPCHAypcjflgJ9JoYD07KK4d-YqGj8HTm0fjZe2J9SSTFM-EQehcBCHWAAaUQIgAgrChACCjMmTeztsQ8QcRjHhCpDqELcRfDx-tbiQCjD%2BdAABrEUeAUppQKPgfI5d5YMmfu9N%2B6BMG3GwTPXBx8k4uIETooBux9SFyyVGJMH5EDpTDtAXwOUJGIHgJkRB-ZMrQB-MmGhdj7J-T2onD2cwU6VOjMmaAeTehMnkCyLu6Tbj6n7lkipacIE7L2YIA5RyayARqIBaoBApQJLnrwheZ80nEKOPqVeYpgmhPqhHdBtIcmYHyYU4iElp5PGaUkvhQl2m-N0V0q%2BWSbEQLMpc9OikCDVEEOw-s1TX4cJCkBVRKz1FrM0W03SaLOlBH1CArJTJfAgShAgUUtx4lqNHF0aQNx5h4HNJ9IYPFIhAA)

#### Code

```fsharp
namespace Some.Namespace

[<Interface>]
type IEvent = interface end

type SomeEvent =
    { Id: string
      Name: string }
    interface IEvent

type UpdatedName = { PreviousName: string }
```
            

#### Result

```fsharp
namespace Some.Namespace

[<Interface>]
type IEvent =
    interface
    end

type SomeEvent = {
    Id: string
    Name: string
} with

    interface IEvent

    type UpdatedName = { PreviousName: string }

```
            
#### Problem description

We use an empty interface for a few things, and updating my code to run the latest alpha seems to break in those places when I turn on the Stroustrup setting if anything comes afterwards. I'll try and get a PR up for this soon.

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas v6 branch at 3/6/23

```fsharp
    { config with
                MultilineBracketStyle = Stroustrup }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Just an FYI, this breaks with other stuff as well: [example](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwBlWXAOgDkd8iSAdAJyfVfYG0AeASXQAXRCwBmxRAD4AupyEBPAqT4BRAG6IhYALxgAlkJHiSYTfDlzBi0hVzrNgnXIgRgYPvDR5BLAwHNnFwg6XC8ffzAAX0CIXGwAIxEwAA8qACEWREwAawB1PUEACwB5IpEyQQBXUVEAQTwwAHdEABsWnTAACgBKCzYFJTAAVQJ4TGF4ENJdNwAFTLU9WEq8KbDfdD8ovvZIABpwKDxEQUF-PFQwLkPXG5dIABIrJUvIA0F9u4hHtUwWyuQaGuQSCAAYDiD7gIkEIyHoAF7ICGQsAAFi%2BYGkd0iyNukMez0BUHen3xD1%2B-yJwJRAEZcSDIABZTDJAAyBkQrM0fiKpNpACZQRisUEcXdQGTCa8zMVROz0IgKvIWkiMT8-gDLtTIfz6UFICp0PBZfLVSioC1RJBhdj6RKGU9rK94rBYC0%2BfryRqqRiIABmPVQ9DHFiCABiBj%2BNEQjRaHI9IJ8AJtortasdLzQkBdboT3y9lK1vrRge%2BZEYiDSiFEsEys0wLHowhYeZcScQKZcYqC9s9UqzOfdgfVhaBxYArKWoOWJFWa5lWbBmixoJhjgI1LBV2dYOhWxB252IN2XL37hmidnXUP0xTNWPzQA2KeQGckOe1xAjJQrteIDdbuMSx7lO4gtMcR5RGmkpOgO16tiO95XMWADsL5vpW1afgAwi0a54Nhu7eCwlTQIItb7mAYEQZCIpdtBDr9lAg4IQWSHaiCAAc6EVh%2BmSMogCQiJR1EdrRtriumTFXrmw5sT65oAJw8bOWGZIRLS7iJfw0SCdHHgxfawcx8FyXeCm0uCxavhWtSiM2hHYNgmCUYe4mppJMGZiZsm3t6RbmjSdLWRhfGKoJehwJpIHFqJkEnnijHGTJN5kuZAUCipJB2c2ZARVFWlTm5ekST2UnJSxZn%2BQ%2BtIBiFtksMsRoACKtHo2AFMJRUkWJJUeWVXmXiSVWjshgWoi%2BzLJHwogACqFJoZCFLWgj5PAvJTkK7n0Z5SXeW8QiselNWQjSk7WVNM3zZoKjgYqy2hmtG3Fo%2BW19TtA17UNh0jexxY0s%2BF0sgIoh6MkxQ-uMtYqMkBCZHgeDAZRnFvUE%2BlQbtRn7cNfmjRxQQ0mhQPJAASogcAsPAT2FJRqKoy46MJWAZ75tJONpdVY20txxNkxTkyVEJLCynwwjYBcU40vFhnntJ2CVC0ZxxgqYa1s5pwiLNTq-RZp3KdZfO1vAjIK0rHKqyw6vNpRMCFA2xDNgA%2Bo0ejrTT0uY7LyXsw6x1czqVnmkyLK1CwjbyMULDst41PI-TECMzLrPez9uN-ea-LBUHU2h%2BHkfR4INCC4kwuiKLgkS-9HufVjl7y4rejK4gFtW5r2tp7rIL8rq1m55gEdR3o3gmw3Tct%2BM1svtAduNmRIjO67vLV6e5XY6nHN48W-J1dnLIAGremkBjwP4sdTijy%2BJbXrw%2B56fv4y4-ITcTYaVOgZHAUfRqn4vNNTnTl9mar2%2Bh8HWGUdTnV3skZqsBBAAHETgwzhvgRGu4z7FgvttAyntk77Uqh3cBXdAZB2jLGDkVZBDNE0FrJQrVQboAKMBWoRoBJC0ruaYqaNSor0Gs6UyBCTpdyJkHWocY-DoFfu-Hc6A4TiPGJUTIs1YDQgcEBQqsUdK9S4f1HhX0%2BG%2BQ3unFE-IeYiMViILAZwNCLk2KwkudCDCMKItpO6gCWZQAvPo1KvtOYPwgPyfW2dTZ6FNKyHA8Qxi4VgIjTYpCm4uN0toj6ujr5wQMT4ze5o-SBxRAaWGIh2qqJaAAaUQIgAgKihACAyJgd%2Bf8NGuKwRjGuXs8H8MMZ3IIfos65LSHhdA2RTR4FDk1SY%2BAJgjzNgqJB8NUHBlcj1NxwCvFHV8cWP0Pcg5pAbGFZqQ9oC%2BA6pYxA8AhgMN3K1aAeFGzSISVohm3Cr6tLrsEpuNToDZBOEqFUqzMkoj9DvXJkzG7kNnp8wQ3yzS5OIssYilQCDWiaUzdxBIU6gIEf7EEfpn5B1KeUqaRchayj6bUwZHJ2GWXjpiR5QDeFpO8XfNZWTIG5LieQtSiBgVN0cgQSogg1HoBmSgpG3VkxIqTh46S%2BCOmEK6cQ3JFRfBkUZAgKFkI4pIsONIZEbw8BhkRpcOKkQgA)

We are probably missing some `unindent` call under the right conditions.

**Comment by nojaf** [comment]
Available in [v6](https://www.nuget.org/packages/fantomas/6.0.0).
