### ISSUE TITLE
List/array applications should use stroustrup if global stroustrup setting is enabled

### ISSUE THREAD

**Issue by josh-degraw** [fsprojects/fantomas#2789]
I was just trying to update my codebase to the latest alpha and it took me much longer than I'd like to admit to track down the source of this problem. I think it makes sense to have it be a separate setting, but I think it should absolutely be the default style if Stroustrup is enabled.

Simplified code example 
```f#
module internal Plan =
    type Record = 
        {
            //
            Foo: string
            Bar: string
        }
    let canDoSomething =
        Validation.any
            [
                Validation.someValidationLogicHere
                Validation.someMoreValidationLogicHere
                Validation.evenMoreLomethingOrOther
            ]
```

```f#
module internal Plan =
    type Record = {
        //
        Foo: string
        Bar: string
    }

    let canDoSomething =
        Validation.any
            [
                Validation.someValidationLogicHere
                Validation.someMoreValidationLogicHere
                Validation.evenMoreLomethingOrOther
            ]
```

Note that the multiline bracket style is still respected if `Cramped` is specified:

```f#
module internal Plan =
    type Record =
        {
          //
          Foo: string
          Bar: string }

    let canDoSomething =
        Validation.any
            [ Validation.someValidationLogicHere
              Validation.someMoreValidationLogicHere
              Validation.evenMoreLomethingOrOther ]
```

I think how this should work is that if you have _either_ Stroustrup enabled globally _or_ you have the function application specific setting, it should use Stroustrup.

We could also have it so that if you have Stroustrup enabled globally and `fsharp_stroustrup_final_list_arguments` set to false, then it doesn't use it there, although that would require a little more tweaking, it's certainly possible.

**Comment by nojaf** [comment]
> I was just trying to update my codebase to the latest alpha and it took me much longer than I'd like to admit to track down the source of this problem.

That is a bit of a confusing line there, `6.0.0-alpha-005` was published 12 days ago. So are you referring to the latest `v6.0` branch instead?

I'm not a fan of mixing settings here. Two settings shouldn't control the same thing.
If that is the case, you cannot disable `fsharp_stroustrup_final_list_arguments` while using `fsharp_multiline_bracket_style = stroustrup` is active.

**Comment by nojaf** [comment]
After a call with @josh-degraw, we think it might make sense to rename `fsharp_stroustrup_final_list_arguments` to `fsharp_experimental_elmish` (because that is what I'm after).

And have the coding style either when `fsharp_multiline_bracket_style = stroustrup` or `fsharp_experimental_elmish = true`.
