### ISSUE TITLE
Idempotency problem with module abbreviation in signature file

### ISSUE THREAD

**Issue by EddPorter** [fsprojects/fantomas#2792]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYrLADoB25sADomWAMoCeAzgC6LqU11NscB0AFUQAPVuXKZ4ufAEEwAXjAAhCWSkyVAQwBOi8hFaMaYLYrAGIYAD5gAoiMsRbAdQAWjJzbAAtRPEgAGnAoZkRWVgBLMgBzZlQwAG0QiFArK0gAEiMaBMho1iCUjMyANy0cLGQ0ZPT0gAZguoyASTIkMlZ6SIAvZCbmsAAWYogAXWKAXwHU0ahs42qoAqLmrPLKpdrBgEYZusgAWS0RABloxFPaGNY3Vd2AJnq5ifTp4rSDhdy0SFp4ADyADNzmREPQjHh7ul1hUqglts0HvsYXZ2sDQf05hBIDggZAXlN9p8Yd8lpAAEbEHDQkobeE1bFgADMKNaZDCOlYBGiFQAcogAO44C609KsHRVQlvYlzLI5clU2A0tmwzYIplDNk4%2BhULTQRDKRBA2A6RAABV0WnQ4UQOjFVglUuarys73SJJKCrySpVcrKcK2TIArNqoLr9YbjabLrBBXboFowm1SrBE1FYGQHYZJYhpW7ZWsyT7qQ61QykkyAGxhyARg1Gk1mgCqVBoOkTybIqfTkUz2bAQIqYXzEHdVk9OOLv19ZYD6sZgzAAHZa-Wo03EABhHBJ5hbzNsSXQVimgdDnAjl1Ej7%2B70z0uq%2BcVxF1AAca71DejZsOHApdrnsOebXjKt5FveUCzk%2B9JBkuACcn6Ro2MYHjg-ZhheV51K6Y6Fl8kGUo%2B-qwRqS47I0TJ1l%2BiCyEC7A6Ae6DoFoA5OiBOE3h6d6LCWypzqRi67HsVHrihZr0BwkRwOhWaYcBo5gOOswQbxD78TBgZkY8SEGnRDGSeg0nKhhTLsYpylgJO8yEdBJFaUJzQ7Kyok0bIOiwFg7QACKICKRkMWxuYWfhpKESsmkLpW5FalRxwiC0QKCG4tD0G4pqsC4kTwLcA7PKBBbgQRanLJ0AkOdFuyhnFJyJcltB2Je4LpVyWU5XcYZVvlnFgdxqk-KVhSRS%2BTI7DWNUJWQQKRCIALtlop46A4VBmswzB9nJTJvt16S4UpoVeiV%2BRlcNcG7KuE0AEqIHAOjwG1uVhkMO1WHtlnWfKR0RfZUWvukOwfldN2mvAfJYOgAE6MCLTsOg8RhjsIVFWFR3oLgUQimCRA6CxER2oIvGndpTmIVR123fAhzo5EmOINjuOBbW0BuFaJ52gA%2BoK2W5UjfXFQNx1DT9I1Lk8tbxe5OhaIwAI6OcbAPR1W0veMXETjxAvfUWgmVUiIlLkcJyS9Lsvy6wYMQ3a0Ow-Do28%2Br-XkmjOAYxc9MLQxBO5ETjl1A8yJUcbMty5EbBUy7NNu6aDOAUzLNS2zOic9zdz2yp-PklrXw639VgPC5BvxQAaoGyjRPA0QxIrA7bWnVka5nJ3C2dSKxYXJwEF5J4bWX7SV9XT0q2Ab0HVO4VN9rFW5xADzVe3IjebArAAOLhMtq3rZmA-K3XH3TlBxGT79TIPONBsCsKFxGqw8a0F7iC%2BdNZCRBmZCyO0f6WzottLuZBV4cjQ6As7JHxFoMB4F0DayBFDEMgncyDd0zN0WBC0sBmkELANoHRWALQ2kBJqu8G58T9KAluftAZQJdnaMguDSixliJ-SGj9ogvw2j-QYWEOK7TVunFGwDD7ZynifUmhdqaYlONaCk8AtA7lgOtWIF9ab4Owtw3qDsM7EPKsfJczJKIG2WnaSINpOgVAANKIEQFQLBtBWBtGUFLBBSslycMIY7TRPtdZ1GZPrQYkBlC7jIAAa0xMwdynl2gCj4JTamtN16IDWmwoKzoeqFT5nwxUAjSQ5yZMyAOBtlC6HEg-UO0AdBGN5OweAzZn6Zl8tAXcUtX7KK4a9Hh9c3G-Gdq7ME9j9SBPCBCRgUIPHTxZAXXx4dumGgTv0rokIsQG1KdaGgARXEaN%2BFnLJQidFt18eYyx8ULaQ2BP4rQQSQkDgokPEegCx5HRAYI7RgxmRz18Yoq%2BP5ECTMjmCJiVAsA4NfnEhJplf7BX-vtW5Nl7mZLpNs55Z9fEQg8lgI8WAqA8hoTgM27kYjgxsew5oLiIXvSIepEhjywHNGZJApFEppKsEOAgBZHCFIkpCGMAY%2BRmAEHWgkcykwgA)

#### Formatted code

```fsharp
module Foo

open System
open System.Text

module A = B



module Bar =
    type a =
        | Ex
        | Why
        | Zed

```
            

#### Reformatted code

```fsharp
module Foo

open System
open System.Text

module A = B





module Bar =
    type a =
        | Ex
        | Why
        | Zed

```
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas v5.2 branch at 1/1/1990

Default Fantomas configuration

*Signature file*

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by EddPorter** [comment]
A shorter version that breaks code when formatted with 4.x:
```fsharp
module Foo

open System

module A = B
```
#### Formatted code
```
module Foo

open Systemmodule A = B
```

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue. After a quick look, I discovered this problem is related to a parser bug. We can work around this problem in Fantomas until it is fixed upstream.
Would you like a release with this fix?

**Comment by EddPorter** [comment]
Thanks for the quick work and response. I think this is working in v5.x so I don't need a release specific for this.

**Comment by dawedawe** [comment]
@EddPorter See [v5.2.4](https://github.com/fsprojects/fantomas/releases/tag/v5.2.4)
