### ISSUE TITLE
Adding space after prefix operator breaks code

### ISSUE THREAD

**Issue by ursenzler** [fsprojects/fantomas#2796]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBLAdugYmABQB%2BApJQJR7xgC8e%2BOu8AOgE4f7e%2BYcAMzABDMACMmYsAGpJ-Pj0LYwQ2LDJ1mI6h0gBGAOz6weyABYATPsgAacFADO2LAQDmT1GADajiKAQQVAAJFgAngAOyGiQBFj2-kGQIQBuougArjG%2BScEADA7BwZAAkvhIrADKuABeyEXFEBZ5YAC6SQC%2BjQGtKRHR3nGsiU0p6Vk5fk0QBj3FkACyogAeADLEa4j47lgAFqMzBlb5rR3B3UmBC2FROZDb8ADyQhv4iFURmIclaRnZ3mmMys8xKAFEKi83g1WhBIOghJAzl15tdfgN7hINOgfsk-pNAbCwABmUHJcouLhYABiBAyADlEAB3IjvXHBLBcbLIi6ovq3QaxLGwHFk8b-KZEixkuFVSKiaCIABCiHUXEQAAVRFxRABbbCILjsoKc7lNc5BS7BNF4jFDYWi-kTAFoIFNACsMqgcoVytVsHVa1gTMN0FELnKqVgYbcsHwxogpsQPMtfLGAsx2ON4oJrqJADYvZAfYqVWrEABVSLRLhhiP4KMx3BxhNqDIuFMQK1BG1wjP2rNi-Eu3IzMBGIslv3lgDC6HDThncacpugWADraE7eT5pRV35dqFg6dEsJY4AHJP5aX-erFohdRJDZvt52wN3eunD1AHdnh5KxwATivX0ywDRAl3QFsvS3dAO13Xl9y-O4BxFP9nQAo5CiJYtr0QABBIQsENJddV1URWyTN8PzAXtQm-SBfyHDCzyOOYcKnMD1SqB9cDgKD4xg18ENTJCbgYpiT1zUcjhBDi8MI4iuB43U%2BJFaCiSokSuzTcSUKPNDmNPPMxwMUl5N9fCuFgTIKgAEUQIhVKUyiuR3YoLR0sT0X0qB4nQ4yZKaAxpRw5YVlKIQABU9m2Ko9gDLAAHV2H2VtTm099dJ8wU-JGIzpLdYoDE9MLVkimLtjBOCPgSqkUvgNKvXzDKPL3a0D184YEgKkciuCAxCzKiL8CEXAVieGtRHXLgwRWSJ1ScJxm0Eolz1a4JPKy7zbS6-zesw4KJ2GgAlRA4C4eAGqaqUNqCLaaLo-o9vyqS%2BqJAxL1O86A3gelMkfQ0XlKYjdS8L0DGo7LdtyyBdUydA3FZRBqQDcisCUqKUIO1jguAnCzou%2BBFgRpHiFRrh0ZcotoD2bUFSUgB9JlUoOKGdr7Bj9rew7ihOItwqsnVwieLgNhXa6Di9db2Y65DYe59MWJM4F2LHJZViF0QRbF3AV3%2BwGuGB0HwY%2B2We062H4cR3BkYpqnDSxwYcZVporDk9WtZ18WsBJm27bR6bqZw2n6bXQ1mdZpFMsey37kVm5laCvnzPV8KADUJSVAh4A8SXWxlmPoc5l6ep53G%2BdCtPVmpWy1xW7OKjzqOvQsO6IAe4v6NLgLCqJKxSurlY7NgLAAHFsDmhbECWlb8%2Bl9v2nai35czQzy9dvmhvVxkWWIFUsBDbYncQByxvwXBY3wfCKnvQ3TbHLS2sQuW9NhySlcC-qgisY7PaIdw%2BBa74HrnGGogDpqZHVFFWA5RKhYGmitF8NVzafjfmvR0n8%2B5jisF9f%2BSl8CINSIgIMOw75Pi4GfAgl8VoPxmLBeCz9RKvxyhg3u70cH4zTqTXA0I1h6gkPAUQc5YDLR2LvZGyDGGbWXmg1hqFMGJy-kSYk2F1ZT0NLgfUrAMgAGlECIEiHA7YWByhKh1CAqWRIGHuRkS-Fe6CFHsN5sEYkasZiQCVPOfAABraETgrI2QqIyFciBiY8ORlPRay1lyuTNEwryLCYZsJdsnVxHsPFKm1FxU%2BetoBcC0XSYi8AKwXzjA5aA84dRXykbY%2B6sjaJxyGNbMm7xzEKh8dgT44RvipO-hAYkqcPF%2B1acqHU0BOlYG6b0kOOpdTRHgNHBJ20kklwVq9LBHCZjEirh4-RhjwoGwoS8LxohfH%2BNbAYfIi9O4c27u-Y8myXFBGJIPDxEj963kQCM22xBSKREyAgq%2BUSZ4xNWo-NyqDGmrycX0lR28PGfGspkFcXJIi0kIegH2Vl3AAxMXQpoNioVPX7AZRRvwk79JJH-RFnI%2BK%2BwQDCMcRKY6ODaI0OIThqTLW8ESzoQA)

#### Code

```fsharp
let inline (~%%) id = int id

let f a b = a + b

let foo () = f %%"17" %%"42"
```
            

#### Result

```fsharp
let inline (~%%) id = int id

let f a b = a + b

let foo () = f %% "17" %% "42"

```
            
#### Problem description

Fantomas adds a space between the prefix operator and the string. Note that this only happens when the string is specified after the operator. If a value is used, then formatting does not add a space.

This works correctly:
```fsharp
    let inline (~%%) id = int id
     
    let f a b = a + b

    let v = 17
    let w = 42
    let foo () = f %%v %%w
```

The current workaround is to add ( ) around the operator and value.
We use this in our tests to setup data; that's why we use strings there, not values containing strings.
It would also be more consistent never to add a space (as far as I understand it, a space is only added when the prefix operator is followed by a string definition)

#### Extra information

- [X] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas v5.2 branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.
There seems to be a difference when you start your prefix operator with `~` versus `!`.

https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/operator-overloading#prefix-and-infix-operators


> as far as I understand it, a space is only added when the prefix operator is followed by a string definition

That faintly rings a bell, I believe we at some point added this because of the operator we use in Fantomas. 
`let (!-) (s: string) = ...` where `!- "foo"` was preferred over `!-"foo"`.

Short term, I would accept a fix that takes the `%` character into account when dealing with a prefix operator. Long term, there should be guidance from the style guide for this matter.

Are you interested in submitting a PR?

**Comment by nojaf** [comment]
We have a fair amount of [documentation](https://fsprojects.github.io/fantomas/docs/contributors/Getting%20Started.html) to get started.

The Oak viewer in the online tool gives a pretty good starting point:
![image](https://user-images.githubusercontent.com/2621499/226911583-8fdc0534-11ce-4e4d-940b-b556a4a11f80.png)

Look where `ExprPrefixAppNode` is constructed (`ASTTransformer.fs`) and consumed (`CodePrinter.fs`).
