### ISSUE TITLE
Default fsharp_blank_lines_around_nested_multiline_expressions to false and recommend not changing it?

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#2807]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzMAFAJRgC8AOgE7kB2EEmOAHmWAIxW31iNgCerAEyc69XgNJgAlvgDOsALbYAFlJoBzAMqKVa9WBZZliOuuzalAFVUaAYrEpgAzGETpZiMGawBBGrCNESms9e0cAFhFuXgAvMijuegUAQyxoZQMwAHcpIwTEsAAfMAAZRFlZa2S6AFYwAFoAPjAANnzE4oB9BuaAdhF2%2BFgLXQ0AdVyMpnbC5oAHKTnES1g-AONgm3UJo34Z5tw1ZPR0PgARYZ0jPR2MmP2wavhrEwuR640AUXdEEUgAGnAUA8WCwelkqDAAG0gRBQAVIAASLB8JaQyBqLAA2H0JEAN2OAFdkGgYQUIAAGQHkqAASRoSBoWE0UhiyGp5PCOIgAF0cQBfDlw7lQZGoklQTHYhGIgnoYmQsnkthCxKQACyySYJTUiDKGiM0uVggpIr53EFOPharFaLQkBM8AA8rgdTREJoUZgjdx8USJUqCoJVb7PgyXW72SKIJB0LhIGaBarrb7bRLIAAjWCwdA%2B3Gy-2K6POEO4%2BkeShYWxHdAAOUQWXQurz3CwlGJiYtyZFSJRdqgWZzLdFcoVpOL4VLMc0c2S0EQACFELgHIgAArJSjJJRYILDiBtjsFc30S3cFP5vvpwe50t%2B%2BUB4s1KdQGdzxfL1clWBZILQZIePSeKwP%2BYKwDQ%2B5gIeiCdqe3Yyle6I3sO95jtCxYtC%2BkBvvOS4rpQiAAKpzEslD-oBNDAaBUjgZBuDHB4sEQGe9AXjGaZIdmt49gWD5FjSvRYThH74YgADC6AAbIYngbIh7QFgDh0QxMHHkmVo8Yh9rIXevFoYGiQABxCbOuGfgR6qIAoGZ7i%2B9E-ExYAscKCHipxQ66aOj40gAnCZ754auMnoLRdkqY5zlgGxopaQOXEoXp3nKlSxbYaZiA%2BLgu6UDJCgpJB0ERfBNqxZm8WeYW440mwKqpcJgUEZoVlSHAIUQWFDlqV2Gmuf2ZUeTxXn8ca-nzpl2VNQoLU5qFxaFV1cE9SVbnaeVg2Veh1VOKNGWULAhIMmcbhSFN2UFe2qmJCezHFampVShVfFVcqk6pZqTC0rgLw0JoygOFgEzwIaL6mgtN1LXdK2SkyCVDc9BRsM%2Bb1ap933fB4v3-YDwMYaDV3qeemlQxiMOPfpxZsJhyMfTQhxME6pGpA4nxMHMBEVDR7XFoZePcNdTm3ZexMPetT2bcqgnUwASogcCUPA2PKJB4S8-Q-ORdFvbC6Tovk9VxnS7LDjwLWhLWUELq0ruCgQi%2BbBFRDQt9QohLoGCTbumEKSgkElhuWTSUI35qUy3L8Dqq77u6l7qRnVh6SbnO2WdDkQNKw7hO9emIsynD4tBilNIalqPiUFufBOpQOpyYrkE8xnrFE31Oc2nnBncIItVF%2B9pfl5X1dYKb5uUJb1u2xTDcuctzuR1IHuIDHPvBP7uuB4kgjBqlvfJBXVdSHJEdu3P0cON7cepQnW4KUEKdSGnCZgwLjvsfdOu5xt7f0II23UwAav6C41DwBuHfHGNJ66Pw1k3bOb9W4f2LIIV63ctS2AOgpTmgCGQgPvi%2BFWk8orQPRC3VMbcEFI2QUwC4WAADi2AWZs3KLITmtcXwQPxt1TO09rxrXfmLT%2BEBBBUyLvWRsuolxYF-CYP2SwjqHBoLkTmfhw5WRspQceNJ5rsMWpwyGfUdKr2GkGSWRcfBNnUDQVBNB0HgRZOY1IhICIrHpIyLAqRObKU6lo8GOinbcIGrwvW5JBAGxMW7IINA3F4j1OBdQllh6yLUAo2SHjGKQMFi-Ym%2BiAlrw7sHbus9IwlG3BmeAyQJKwCYRoER88UmXT5gTRuWd3LcWyYYxIThC7kkgPQoIJ0TCuPQAAaUQIgOYzj%2Bn0gXFuKxSsOqpK8U-HxGS9E8LgXw4sTgu5dIXJJGgABrSMshS77QZPWOSiBw6z3nvQ9mTDkkvk0fUjhjSuHNNhvAmkThN5FwXJuBqiAzj72gJQE6RxdzwEIvI8CR1oCSS3GBLmNJ7LzKedol5uj0wuyPvPKZc49nmC9FGVp8N2k-3ydisRV98XMkJZBGAW4FBLHgA-BZUCmn2mIfmUhnykFdOGaM96Q9VEuh2dUA5up1HJVVryBpU8MVvIDm07gThyFdOqWI8yiBD5R3dLlOYhJXEIpuYw9xDyLr4M1hxVa-i1mBIKE4IRXSekgqUEyY43wpqyFmcWZFdS1YCiBDyDkGJZC2CYZCX1IB%2BRAA)

#### Code

```fsharp
let f () =
    let x = 1
    let y = 2
    let y = if somethingSomething x then getSomeThingFor 3 else getAnotherThingFor 4
    let z =
        match x with
        | LessThan 5 -> 6
        | _ -> 7

    doSomethingWith x
    |> pipeToAnotherThingWith y
    |> finallyDoSomethingWith z
    |> andThenDoSomethingElse
```
            

#### Result

```fsharp
let f () =
    let x = 1
    let y = 2

    let y =
        if somethingSomething x then
            getSomeThingFor 3
        else
            getAnotherThingFor 4

    let z =
        match x with
        | LessThan 5 -> 6
        | _ -> 7

    doSomethingWith x
    |> pipeToAnotherThingWith y
    |> finallyDoSomethingWith z
    |> andThenDoSomethingElse
```
            
#### Problem description

In the [F# style guide](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting), this is more or less all it says about blank lines:

> ## Add blank lines between declarations
> 
> Separate top-level function and class definitions with a single blank line. …
> 
> If a construct has XML doc comments, add a blank line before the comment.

> ## Formatting let and member declarations
> 
> …
> 
> Separate members with a single blank line and document and add a documentation comment: …
> 
> Extra blank lines may be used (sparingly) to separate groups of related functions. Blank lines may be omitted between a bunch of related one-liners (for example, a set of dummy implementations). **Use blank lines in functions, sparingly, to indicate logical sections.**

(Emphasis mine.)

I'm not sure what is meant by "logical sections" in that last remark. However, I don't think Fantomas is in any position to determine that either, and it seems to me that when `fsharp_blank_lines_around_nested_multiline_expressions` is `true` (the default), it generally inserts breaks in many places that can not be considered logical sections. For example, in the code shown above, I would argue that the variable declarations make up one logical section, and the final pipe expressions make up another logical section.

I am therefore wondering if:
* `fsharp_blank_lines_around_nested_multiline_expressions` should perhaps be `false` by default
* The Fantomas docs should list [the setting](https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html#fsharp_blank_lines_around_nested_multiline_expressions) with an exclamation mark (i.e., recommending not to change the default)

Note that I am not asking this just to nitpick. Firstly (as I have seen @dsyme [agree with elsewhere](https://github.com/ionide/ionide-vscode-fsharp/issues/1693#issuecomment-1103484635)), defaults are powerful, since many users don't change them. Secondly, I am genuinely wondering how to format my F# code. If the consensus is that F# code really is objectively better with `fsharp_blank_lines_around_nested_multiline_expressions` set to `true`, I am happy to do that (though in that case, perhaps it should still be recommended not to change it from the default).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas v5.2 branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by josh-degraw** [comment]
Hey there! Sorry you haven't gotten a response sooner. I think this is an interesting question and certainly worth discussing, but I think it might be better suited for the style guide itself, since fantomas aims to follow that as much as possible.

But since, as you mentioned, the style guide doesn't mention too much about this, I think the short answer to this is that unless there's a _strong_ desire from the community, we'd prefer not to change defaults, as that would be considered a breaking change and could cause a lot of user frustration for those who expected that behavior. 

Regarding logical sections, in this context that basically just means any arbitrary section of code that may be useful to group together. Your example of variables vs the final pipe would certainly qualify. However, as you pointed out, fantomas really isn't in the position to know about these "logical" sections of code, hence why this setting is only tied to structure (i.e. is a given expression multiline or not), and deviating too much from that can get complicated quickly.  

> Secondly, I am genuinely wondering how to format my F# code. If the consensus is that F# code really is objectively better with fsharp_blank_lines_around_nested_multiline_expressions set to true, I am happy to do that (though in that case, perhaps it should still be recommended not to change it from the default).

That's the trickiest part: there is no "objectively" better here, only consensus. Since this has been the default for a long time, I'd personally expect more friction from changing the default than would justify that change.

**Comment by cmeeren** [comment]
Hi, thank you for the response. Since posting this issue, I have gotten used to how Fantomas formats with `fsharp_blank_lines_around_nested_multiline_expressions` set to `true`, and no longer have any desire to rock the boat in this regard.
