### ISSUE TITLE
Update SDK to 7.0.200

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2812]
We should update the dotnet SDK to `7.0.20X`.
Be aware of https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/7.0/solution-level-output-no-longer-valid.

**Comment by nojaf** [comment]
True, but we should follow the guidelines and not `dotnet pack` the solution file.

**Comment by baronfel** [comment]
Pack is actually the only accepted use l! That one is unambiguous and fine to do. All the other commands have edge cases and unclear semantics.
