### ISSUE TITLE
If then expression inside object instantiation breaks when formatted

### ISSUE THREAD

**Issue by LiteracyFanatic** [fsprojects/fantomas#2819]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAwgBYCG26iATgBQCUYAvADoB2EEAtouwEaVgBuxADZgAKgEt0QxGgDO6CuOYBzMLDLjYremACqzaIUTQA1ongA6JADNiAVyHpY1gDwB9AHxgA7pMJhlRHQAGjBZIJY2ME4ePkERXQohOQUlVR19Q2MzSxt7R2d3L190f0CQsIjmFml0MGgGSLYiUnJqJqiICSk8JlZOgfFrMAU7PFLEav6BmbAAZVhOMEZIFY7ZsEQhcPWNtgA5LURdmeCTiESRHTXV6bAaFkhg8Chw9HQ02VQwAG0XiFAA0gABIsLhvpAlOgnv82CD4mNvn9ZgAGZ6zSAASWYSGY6Dm4gAXsh0TMACywiAAXVhAF9SQDKVBQThkGhIXiYUDgQi2b8mRAAIwMzqQACyxAAHgAZJSIaWTZSlLkzQUAJhRTJpUXpsMBopZ4PZk3gAHlrLLmIg5lhpCqovDhIi0MiZmqRQ6AKI482WkkCqBCayQLV0kX6h2GvmQbiwWBCe1wnlOvmugYAZg9cOx4Qo6AAYkphPtEN4hHLE1FRohQzrw0yQWDo7H45XmbykQGyVmIJA5thiNBEAAhRDWWAURAABWIFGInDabYg1drbF1UQjSabEJbCazjqEzv5swArD2oP3ByOxxP5bBvJRoMRwtj%2BLAnx8tEuRhQxquIOubCbr2UY7nGe4Nsmh6pgGABs559gOQ6juOk66NguAUE%2BL7MG%2BH6aMw362NsNYDNqa71ty27srubYHkeaadAA7Ahl7ITek74EIz6yPgWjyL%2B0BOBQRHCOE-5gIBjJUayYGtvuUEMQGAAcrFIdeqGIGKXC8CJ57EeJZFhnqkHUVAtEKR2LoBgAnGpV4obefFCF%2B%2BliaRnTkQBlEGmZMbgXRikwbMgpogGiFXgAgtYbR8ew7DEN%2BK5GXWJkyUa5kBZZKadiFwrhWxGm3nMXDiHALmEW5JESVJYDAcyfkWZBVnHqq7oFep0VtCV7BlfGrkBslnnGRupmyTRWXNTl1khZmHVRRQsB2DiAAiWziL1i7nkNUReZJPmRn5UKBS1jFRIK3bhRKkqYtYohGMwcyEBO6AAOriPAyrnpqKUUWlvnjVAx3ZdBuWqmeV1Srd92TJ6JFPS972fYQ36wT9w2paN6XRsDU2gzNqrwZDN3MNY4iSqamHEMJnqStgk6yLIBHfsp6O7SNQFjRlHLQiDSkhSxxMAErGBO8BI19XZs2we21fVjaAzzJ3Ta1AyCqpwuixQ8D7HYsQUOamLkOwXznoKNUHVuivsA4Hzlla%2BYTgl7yUKIsl88Fqp2eFItwNrYq2%2BI9uII7FDO1t4WGLOg5tG4vjIyGv3ef9h2K7j3KnQGGoIddkUUHOmCmhQsryBLKPnqzFsp1b3PpwamezGq%2BUYrn%2BfEIXxfiPIuv64bxumwG5tJ-t1cgX5NuOEHcqh%2BHrvu3j-Nuu1GJ5wXRcl%2BgAeT8HM-UxHGJR3OQmUHHH3KlXWMA7XnIe2DAxqnNLdSgAaimw5KPAaRlyz0vUhz0lXxxjfBent76XSfpKfMy0hIEXfjiL%2BZ9y5SwvpzbGEI66Rgbm6CGECVqwHQAAcSCLTemiBGYEW-hXX%2BYBZaWzHorJqGcVZnTYGqImGISxljlKOdAD5Jhu1wGtMmzBJAEUijibS%2BsB6zB2jLf%2BdUubNkmkw-GqtOhqkFivcsyhmBQIMJ%2BR64gdHUzsJOUQsBsS4nQNTZmVVDIYz%2BpfVO3NGH12YVnDWWi2jMBsfwO8KhJG6SEUoUR-FRLVWHnLRRckIIqMXvfb2LdA5%2BmlPObg8BiBcVgEzFQnDg7hPsezTGqDAExOVqolhEB0xhQxCQygG1JjWKEAAaUQIgbAljGnYmHHOAwSDZgGQ8kUxxJTnFKPkiAu%2BnR0zNxmJAYc3FmAmD9LIPOS0cQlnkOYLeds5QkIZkzMJ21fxDLkcUgBYyym3wJhmZeczhyzkcpOFaXdoCKF6j48g8B9AETWtAbic4DEFNOX-c5Ci0Hsgnrsq0PTBxmHxLaf0cTQHTMfnMnZU8YVH3hTaTAdoEJvPnLgeAicHHJycTXIBvNJk3OmeAuZrT2nXR7rpc0CziBLJWd%2BUK1DaGjwagw5RbiKkBnTDguZeTuEcS0oHYOcVsB2GsQY-ZZDDmVUGiclBFzKVXJpWoqI6Z2FzLqe8xpwg4a9VkP0mYgyaovCpKSSEsh8xM2%2BLa2kQA)

#### Code

```fsharp
type Chapter() =
    member val Title: string option = Unchecked.defaultof<_> with get, set
    member val Url: string = Unchecked.defaultof<_> with get, set

let c =
    Chapter(
        Title =
            if true then
                Some ""
            else
                None
            ,
        Url = ""
    )

```
            

#### Result

```fsharp
type Chapter() =
    member val Title: string option = Unchecked.defaultof<_> with get, set
    member val Url: string = Unchecked.defaultof<_> with get, set

let c = Chapter(Title = if true then Some "" else None, Url = "")

```
            
#### Problem description

After formatting, this code no longer compiles. I think the issue is ambiguity with creating a tuple when the comma is on the same line as the if expression. Inserting a newline or wrapping the if expression in parenthesis fixes the compilation error.

#### Extra information

- [x] The formatted result breaks my code.
- [x] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas v5.2 branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Hello, 

Thank you for reporting this issue.
We seem to be adding parentheses to the `if` when the arguments are not named.
[sample](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBhAFgQwA4BdEAnACgB0A7CCAFQEt8AbRMAXkus7DoDMx8iAVxb5MiChy5SAyrAC2LMpCWSpiRgGdEqqdQBysCtqq6ANDoCqRRmzArlFAJSVKWPIVI7OvfkJFiJE11qWQU7ZQdg9S0vXQMjWIhzIK57SkdIU3AoLXx8OgoAcw1UMABtbIhQKUgAEnwAT1xkNEgC-EzK6jqAN2xGYVKK4IAGLODIAEkKJAp8aToAL2Rx3QAWLogAXS6AX1Wqzah6ppaods6a2r6Bs%2BHdAEYDrkgAWWwADwAZAsQv8UKokujwATCMjjtOPsutUXidmqVIOJ4AB5Hg-IzSRrMYGcXr9QZoe5SEHPPEAURmaIxKyOEEgjB4kAhe2esLx8LOkAARrBYIxcd1rgS7nSwABmMndaZaIj4ABiBX6ekQAHdGL9BZwBMIWVC2Uc6o0Ea1efytccboTymK1lL6dJcNhoIgAEKIHiwIiIAAK2CI2AUHgtEB1iD11GhnHZQuNXLNAql%2BNuQzFAFZ7VBHc63R6vX9YKriNBsFppj1YCX8oYQ75dVJIZGDVc44iExbk9biVwAGyZyDZl3uz3eiy4ZpEEtligVqt0GuZnj9LQRiBR6gx%2Bmctt8xOG4UpoligDs-cHuZHiHQjFLGnQhg0Oug%2BC9taXmnDDdZMP3rdNu47A8uzFAAOM8nSHPNvVeRA5G5Yg32XT8uEbNdmzhP8oHbJMgNFYIAE5wJzYd83vRgFzFd8Vy-fUfxbU4d3NHCrTwx4xjFAcIMQABBHgPHvOQ5GwWsw1XMB10OeiTSwgDmJFVNggeJ4OPPEjvWkWC6DgciKEQj8xIksBN2OTCeVk-cWIU0EiJdXiPA0uQtP5CjglEmimzojCGP-JiLPko9FMlFSuO4ohYEEGYABF1DoRzg0zNyUO-aNf28845kAyyAseO0OPeD5Jh4GgAmkTAvXwAB1Oh4CBTNwXctDPI5UyLjkw8bUUjM8s%2BQrivEckP1K8qqpqzBax7eqktolKpK5Vq-Pa7tOAePtuoKigeDoD4UQnbAXyIckPlwb0NA0eddMzEDJs4VDxPQ5q0raDK2uAxTTzWgAlRA4CIeARtq21ruoW7DOMo1Hvmq4so6x4wM%2B76vXgPRBDg4g0UmQg5BKTMHgM%2B7Y0euRBEYfINSMeUvSEvJiBoBiXtYqQHkIjivp%2B%2BBXmJ0nfgpogqfijjoBwANn2IAB9VVqqBPGmoJ6Sno6emrJJdiJny0KAwaFEiB%2BR9-rGy6ge2ZKN1SuXIbhaGluoEFlNVz51ewTXtboR9kdRoh0cx7GxVxhq7plrdTKJkm6DJxAeb5mm6YW17dBBUkOIdp2dfwDmQ7DiO9v5iZBf9Z0PHFyWxulmavLN56Y4ZrgQSCu2PgANRFV0CngApCj12srpLk3ZsRc2OUtsUQVyuv5Qi59zubmY247zM1kNsAQfxwOIYrqH-JhkkurryLYHwABxRB8EO47EFO87Z9Ahel4DkzHuwyuler1aJhVdVfndfAi3EWnmmizaKAMHOtxGYMF3be1cn4bukky7xnMuvRaQ93oTG4hqQoFAx4UAnoYBY6C9qCG9DQWA0xZj4D2udPS1EpoeVLg9OWD8EGxxJHDFBJNiAUHIT0AsRQwHwSIP-AoQCHyUOQjdY2MC6FwN8owqunAQTM1VpzOgNIviBm5PAbA15YBnSKG-MOIjoFGVNlIvcMin6cHFCrXQkAT7EFiuIMhjAADSiBEC4BIQ46YroAxYP1pRJChiwbbh8qYi2G8rYQHFLbaxrobwUAANY0g0KFcKMwVSPkQOzJRYcT4nTOsIhKUC-ag2MYxUJA9wlinFAnCYrp-RqUQJFF20AiCxSVIQeAFhAGGGitAG8AZqwXX8fpYpy875y2DlzIw3jnTxKPliBoOJFbZSkOKWu1i05TLdMLOZ8xsS0hzgGOQzR4DMlGbfcG5cFaPxWVwcUI9rEuLcflN2fC0SxOwAkpJtYHgjGvuIoxvcQmZUqcEcU29rF6I-lBRAmzQ6-AErgQQZDBm5LPvkoZkD6zUMarQ2WJiQWILBS-axtjWkKDmP0AajkNB%2BOCFRURwM9jZC2KsNoGh5RnVKAykAuwgA)

Perhaps the this logic can be extended to also take named arguments into account.

Are you interested in submitting a PR for this?

**Comment by LiteracyFanatic** [comment]
Thanks for fixing this @dawedawe!
