### ISSUE TITLE
Fantomas is trying to format the input multiple times due to the detection of multiple defines

### ISSUE THREAD

**Issue by manxjason** [fsprojects/fantomas#2822]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAzArgOzHb6AlgOZgC0AfADoBOV2AxIemADIDyA4pwJIBynAPoARAKIAhAKqcwAH1lsuvAYI4BhAIKta9CHv16ANogAuYE4gC2AB0MBDC2AC8O3Aff6qkANrAAKoSWiADOJnY2KAASkSiWlijBwQB06KkAvmDArIgAboiGKJgAzBnAAMqwmDTQiGqw2BYAHiYohmkAupkAsiHBdsSIrQBWGQrAAAo0sNaINCaEIWnAfIgA7qyE2IhLoo011vP1aV6uDIjY8Myurh4G%2BETEp8yK3PxCYlKcN7ceSQDqNEIFj8sG%2BPwMSWEiAARphiAAKSomayYEx%2BKy2ByIZzmDH2CwASlO50u6CeLA4rxU6i0YPBen%2BgOBoLobnpDI02GChDqXNgxlYsARdPZ%2BiRKLReKxOIsNnxiBF9KJrLOFyurPZkAANOAoMFTPNsMRgqgwN5dRBQO5IAASEwATxmpsgmxM2oteltOTshkwyDQ5tuAAYdbdIDwLucTGVCAAvZChjwAFg9EHaHrSictqagdsd-qgrvd1pt3t9BcDHgAjFmDJAunZGhsttkjSYABbF6sAJiDOfT%2BkzHqtdbzTrQkBJ7HQzcQZQdxi7%2Bi9Pr9psr7m7teXogu09nS7rhnQkH7GdrI%2BXY4LkGhsH5h4gK-L65zECK289Ef1cwAYpsfRWVZDE2BM33MGg-TPQcLxzW0HXHKA7wfT9nzXANwKTT8nzKaw7BqcREHQWAaEQcY7BocJTFmR89BMSDEGgvQh30S9PWvZ1kMMWi0IrcCAFZsKgXD8MQQjiNIwVVlmaA7H1CMclgWTDmwWiIHoqD3AHZjYJLBCby4njS1XPjbgANiEyARIIoiSMQSRrBmao5MQBSlIcQh6jUsB0B9fUmIgFi9DYp8OInQzUOMl8MNuAB2SzrLE2zSLUexEl5UJIOgEwSO83zDH8rTz2HOCwqQ%2B9uMist0LNcCAA4ErwmyJMQHpLGhGihPywqDG0wLdNHfTOIqozqtMjwAE5GtE8S7LqQwvK6vzGKKmCSr0-NhpQ0qxtfW4qxDcCrKaxANHQCwaDqOI7G8jSVt64rWNKobwpGqqTL26sayOxLZtIsorEIOAFtUpaCvu-Q%2BrAILsw2xDbzenaPpintppqM6LoBywgf5RbwLugLoYGq8XvK7aS12lH3CrD8fpOjQphweAoRA7GLtuhjCZhzJns2ici3e6Lav2rCjobRoeHQPx23OMp2xIkw-kIeAO28vtVp09bBr5wsGlG5HherQSxcbSXpfOURwblhWlZVzshLM9WHrWp64ZvAWkaFjcDCrCyTYlghCEadgnIcEjdmsUjEk80H6qdyHHuC3n4Y9imDe9-Qq3i-2ACVEDgGh4Ft1WhKTeO9Ch7mQtzUmXT1wWaozvQqwa3P85I%2BA%2BEwdrZmnHhZRNISqy54n2NryxMEMeYQK2X8SMsBwLr8TaG-G6mpqOvOC-gLpJ%2Bn0C55oBeTHZyzoHbCj8IuwRVmV1WR61kmdbrt1V8%2BzdDrDcWGco%2B12BoDYoRi72zjg-V22sU7109o3cC3Zvpf0bD-Owf8AGEFCF3HuNA%2B4D28sPDW-VH5j2fhPKehAZ6IEPsfJeK9oFrwMN2LcR0kEoMASYXepDyGUMXp1I659L7ZVmDfO%2BnYwFJzds6VOo5KaG03LTBBjQABqJlxCbEuEaYB3k6rlzTInWGED3ZQLTl7WBot5G-hwNlGOKi1TqOEd5Muoi9FP0ga-Wh796HG3kcIWAJhOCmAjlHbk9QNFCS0Y4nm4jXrkykenWBfswxAXIYREw0lzjLxmFCIg2AgQx05DvKwHUaCD3xpzfBRNCGhVrhFNxVN6HZzDBoECxBsDmOwJY%2BoMZmkOCqIgEEEYkANA8njW43UIYV10RE-RW1Ko1JkfQ1uDSp6zGwB5PIgojRtUKZkzYOT6jFJGctcJ1d4LP2qUYmBtxuwby-nvQgs5WDhGhPAOwqVYDciNIk0CeVDllKrsnAyiNzl0P0EUT%2BHhIAR1mIEKMPoADSiBEDWH6VGCM4hKJtJAQc8GRz-nTP1sY24RR4HgvEPYbAABrWcwQGaVAuCsUIiAd63PIQE3oMd9keAJr80elTTmApiQSjwRRGFhnEBRP6iBhBoOgICbGKyLDwEkNk%2BoUJoD2Eoipb52LuUVJrsQ5loE0X4XJaYec9pFxv1qSCuR4L2H7y2Ea6AJrowLjAmGGV4QZjwFPDq8BziDGuKBe4kFpjwXwsReLDBhTpykrsBSqluCgzaLAJXHler4ZnIFRcoVnjwWfIdclVqBqthXQlEM7ArLo7DM5aU52ms-VEIzfyq80im7vnieCyFsqYWGEttjYImKPCjK5rqdoiYXTBF-NyU0w60hAA)

#### Code

```fsharp
fun config ->
#if LOGGING_DEBUG || LOGGING_LOCAL
            let template =
                "[{Timestamp:HH:mm:ss.fff} {Level:u3} {SourceContext:l}] {Message:lj} | {Properties}{NewLine}{Exception}"
#endif

            config
#if LOGGING_DEBUG
                .WriteTo
                .Debug(outputTemplate = template)
#endif
#if LOGGING_LOCAL
                .WriteTo
                .AnsiConsoleLog(
                    outputTemplate = template
                )
#endif
            
```
            

#### Error

```fsharp
System.FormatException: Fantomas is trying to format the input multiple times due to the detection of multiple defines.
There is a problem with merging all the code back together.
[] has 13 fragments
[LOGGING_DEBUG, LOGGING_LOCAL] has 13 fragments
[LOGGING_DEBUG] has 15 fragments
[LOGGING_LOCAL] has 15 fragments
Please raise an issue at https://fsprojects.github.io/fantomas-tools/#/fantomas/preview.
   at Fantomas.Core.MultipleDefineCombinations.mergeMultipleFormatResults(FormatConfig config, FSharpList`1 results) in /_//src/Fantomas.Core/MultipleDefineCombinations.fs:line 211
   at Fantomas.Core.CodeFormatterImpl.formatDocument@95-5.Invoke(FSharpList`1 results) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 99
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 525
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2023-03-31T07:24:53Z - 8e10a1b35f1ccd791df90e3e124cdc8f94a520f3

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Thank you, are you interested in submitting a PR for this?

**Comment by manxjason** [comment]
Not in the short term, but not entirely off the table
