### ISSUE TITLE
How to upgrade past v4.7.9

### ISSUE THREAD

**Issue by JordanMarr** [fsprojects/fantomas#2833]
This is a question, not a bug:

When I try to update from fantomas v4.7.9 to >= v5, I get the error, "...fantomas 5.0.0 has a package type 'DotnetTool' that is not supported..."

I understand from your release notes that "fantomas-tool" was refactored to be "fantomas", so I guess this makes sense.
However, I was using fantomas as a library, not as a tool. Should I be using a different package for my purpose?

More specifically, this function shows my usage of fantomas:

```F#
/// Formats the generated code using Fantomas.
let toFormattedCode (cfg: Config) (app: AppInfo) (version: string) (generatedModule: SynModuleOrNamespaceRcd) = 
    let comment = $"// This code was generated by `{app.Name}` -- v{version}."
    let parsedInput = 
        ParsedInput.CreateImplFile(
            ParsedImplFileInputRcd.CreateFs(cfg.OutputFile).AddModule generatedModule)
    
    let cfg = { 
            FormatConfig.FormatConfig.Default with 
                StrictMode = true
                MaxIfThenElseShortWidth = 400   // Forces ReadIfNotNull if/then to be on a single line
                MaxValueBindingWidth = 400      // Ensure reader property/column bindings stay on one line
                MaxLineLength = 400             // Ensure reader property/column bindings stay on one line
        }
    let formattedCode = CodeFormatter.FormatASTAsync(parsedInput, "output.fs", [], None, cfg) |> Async.RunSynchronously    
    let finalCode = substitutions app |> List.fold (fun (code: string) (placeholder, sub) -> code.Replace(placeholder, sub)) formattedCode

    let formattedCodeWithComment =
        [   
            comment
            finalCode
        ]
        |> String.concat System.Environment.NewLine

    formattedCodeWithComment

```

**Comment by JordanMarr** [comment]
It looks like the solution is to add package `Fantomas.Core` and also to manually add package `FSharp.Compiler.Service`... 
I see that `CodeFormatter.FormatASTAsync` exists after doing that. Build errors, but I suppose this is the right direction at least.

**Comment by dawedawe** [comment]
I think you want to add the [Fantomas.FCS](https://www.nuget.org/packages/Fantomas.FCS/) package instead of the official one.
Read about it [here](https://fsprojects.github.io/fantomas/docs/contributors/Solution%20Structure.html).
