### ISSUE TITLE
MultiLineBracketStyle does not work - Settings are just ignored

### ISSUE THREAD

**Issue by snuup** [fsprojects/fantomas#2846]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAgmALxjBgA6ATuQHYT0OMQCGKAljegNxgBGKAZ3SUOAczABfSABpwUAYnToxA1GADaciKCaQAJFlxrIHdDK319AN2YAbAK7I0mphAAMs11ACSNJJwBlNgAvZE9XABYLCABdCwlw7WioAxwnKFNzXT0bB3SXVwBGRMZIAFlmAA8AGQ5EasQaUXQACyyigCY3ZLiGBIsdUtSjNEhG%2BAB5ADNamkQArFsw5Os7RzUCpg6ShkgAUT9p2eWvSFspyB74ksHd4fTIXlhYW3a73PXnZIgAZh3LXwKSjoABiHDsADlEAB3Wx1N6MYSOK59G4re7GJ4vBEQVZ5DbfMARf64gLYZjQRAAIUQU1glEQAAVmJRmABbRSISg4%2BhIxAo%2Bj9Bi3SwY0ZY17-PGfDSEgCsJKgZIp1Np9PqsGhXOgzAUvissB1ylgNB5ED5AogQvoItxYqgEp50vyhIAbIrIMrKTS6QyAKrYXCUHV6mgGo1sE1msBTOwKS2SNHZQwPR1SnJrF1eADsHq9qt9iAAwrZdQIiyahJR7NB0PTo7HbPGmL1BUmhinMc9JeiPlnXAAOPPk71qhllRBs3hchtx-kt64DdGd8Xdp0Z-FfLwATmHKp96ortijisbzcYrat7buK4da-TfYJXkKHkJnpHiHwU3QXIrbLZzDRhaC6okuyZpF22IPpmT5FMUb75geDIBJObBwMepqnnOCbWkk4EjHeUG9jBW6dHulJfj%2BlAoWyaEvCehLARei7CsuEGrkR2SPqRTCFH8CEfvglCwPYfgACKIHCtFUUB1bzsxoGsfhDyZNBm6ys%2BxJvhUlTeFMAAqLSNAELT0ugADqbDwK00bdCBbZgR27EZJw67cRpRQKtpVR6YZjR7E28ymcClnWW0iqunZCkOUpTkESYrlqTKmyMIU7rebpNBTGwlQTEGzB1pQeyVNgDICAIkaYYSA5RQwl6Jo5N7OQlZhJf2vG5hlABKiBwJQ8ChTZioRLV9D1bhpBsfFqnEepKUMIUQ7db19LwBC9hTly0zeD%2BbKqIqhQ4deoq3pAbL2LYyhwnMIL0gBShcvpEFtbBvG7m%2BPV9fAZQXVddS3ZQ90yR60AtCyFJUQA%2BtCVk2UdjUnc1M1cSRHlbK%2Bpw6UJrKYBMlC1EIg3hdVo2xCxNpTSpiWzclhIdPBmNVNjzC4-jbBCOtm2UNtu37YSh32VeCN2qd52XWw12IADQOPc9NPtYwHTbG%2BzOswT6A-eLkvSwVwNvqD4O1ly0Ow208OxU103Uyjc10-xjOVAAapmVIcPAYhE9GNXmxTynGMjQzufN9AdFpDsgqJtaVa7fge6b0YjT7eFxVTrXy69iteQ7YmwOgADiijFaViDlZVnuKt7gsNRbiPxWm6c8Yr6WnFCsJ1DS6Bao0T24BJ2U0Gwxo0PgfgTlzfNeExdXk8nlupveDdo4rnWnPgcKiDQEc0FHJpBBvBX2Ay%2BmwL4-joAVlWzoFSeTX7HE9jbtNeB0S2r5dXI0BfVgak0Y-TpQfcOCD0qhPVwZ55LT0Ur7FOkEH6B1RsHCAHR3qY1%2BmwY41R2S8HgMwEssAKpNFbpLK%2B55IExWgXPWBbkEGEh%2BBjVw%2BwSpcjYByTgdgADSiBEDYFPo0dAvgqSsm3sTLw4Cb62hSKdeuj8FYMB%2BAzBhVJSw0AANbHAEEJESfgoRCEQN9NBksi5lQqpWWSyIq4TQkfoKRC8ZEZzkcrU4VIWRIUQGJdm0ARC0U-j%2BeAfoB4mgktAUsrIh4kIgWNGet8YGjDFn9OYgiKQqMUAsTASxqG2y8D8e2DDNbxOpKyaAyT0CpPSR6KsIkqz2GwJcCxx0RZI2tvAzJrgfhhwYZw7hOlOb-2mEo5gqj1HRhfKTMA416mSOatI5pT9WlZwYUQ9uY5EB5IlnUP82B7DnyHkYkuJiqqTzkuIymVCXqNzkc3BhRdmGsPPrYAKtEBAiLAdhCxcgYjhBMAIEEFU1BiIkEAA)

#### Code

```fsharp
type A = { 
                a:int; b:string }
```
            

#### Result

```fsharp
type A = { a: int; b: string }

```
            
#### Problem description

MultiLineBracketStyle setting is ignored in all versions, the format of the brackets never changes.

#### Options

Fantomas v5.2 branch at 1/1/1990

```fsharp
    { config with
                MultilineBracketStyle = stroustrup }
```

**Comment by nojaf** [comment]
Hello,

[fsharp_multiline_bracket_style](https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html#fsharp_multiline_bracket_style) has the word `multiline` in it, so that only kicks in when your record type is considered to be multiline.

![image](https://user-images.githubusercontent.com/2621499/232412049-55feed46-f78f-4929-acd7-9b1d2f4e484e.png)

The default way this is checked is via the setting 
[fsharp_max_record_width](https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html#fsharp_max_record_width)

Where the boundary is 40 characters.

> Default = 40.
