### ISSUE TITLE
[Feature request] Add before/after information to trivia in online tool

### ISSUE THREAD

**Issue by majocha** [fsprojects/fantomas#2849]
I propose we add some indicators in the Oak view, showing whether the given trivia comes from `ContentBefore` or `ContentAfter`.

Something like this:
<img width="205" alt="image" src="https://user-images.githubusercontent.com/1760221/233022364-386ed12e-0006-493e-926f-11b98de39565.png">

Alternatively, maybe just highlight the parent node on hover over trivia?

* [x] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to Fantomas
* [x] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Please open this request over at https://github.com/fsprojects/fantomas-tools
