### ISSUE TITLE
"fantomas --recurse" creates a "--recurse" directory

### ISSUE THREAD

**Issue by witoldsz** [fsprojects/fantomas#2854]
Just updated from `fantomas-tool 4.7.9` to `fantomas 6.0.1` and it creates `--recurse` directories in my modules.

Steps to reproduce:
```
witoldsz@678db1ca1a61:/app/modules/event-logger2$ ls
bin  event-logger2.sln	main  Makefile	test  VERSION  w3module.yaml
witoldsz@678db1ca1a61:/app/modules/event-logger2$ dotnet fantomas --recurse .
                                                             
  Formatted │ 0 │ Ignored │ 6 │ Unchanged │ 8 │ Errored │ 0  
                                                             
witoldsz@678db1ca1a61:/app/modules/event-logger2$ ls
bin  event-logger2.sln	main  Makefile	--recurse  test  VERSION  w3module.yaml
witoldsz@678db1ca1a61:/app/modules/event-logger2$ 
```

As you can see, the `--recurse` directory appeared.

I can see, the `fantomas 6.x` does not require `--recurse` anymore, but my project upgrading to fantomas 6 is in progress and the `--recurse` flag is still required by other modules (using older fantomas version) and there is one build script for them all.

**Comment by nojaf** [comment]
Hello,

Upgrading from version 4.7.9 to 6.0.1 entails two major version bumps, which may introduce breaking changes. Please be aware of this when making [the update](https://fsprojects.github.io/fantomas/docs/end-users/UpgradeGuide.html).

It's worth noting that if you pass a non-existent folder when multiple folders are being passed, the folder will be created as expected.

Mixing versions in your setup seems rather specific on how you choose to do things. You can detect the current version using `dotnet fantomas --version` and adjust your build script accordingly.

**Comment by witoldsz** [comment]
OK, so I was fooled by official documentation at https://fsprojects.github.io/fantomas/docs/end-users/GettingStarted.html

> USAGE: dotnet fantomas [--help] [--recurse] [--force] [--profile] [--fsi <string>] [--stdin] [--stdout] [--out <string>] [--check] [--daemon] [--version] [<string>]

showing the `--recurse` is a valid flag. I can see the tool does not show it anymore.

On the other side, I must admit this is very strange to identify the `--recurse` configuration flag as a directory name (even if it is not a valid flag) and also it is very strange to default to create any non-existing file or directory as a new directory.

Thanks for looking into my case!

**Comment by nojaf** [comment]
`GettingStarted.html` was out of date indeed, I raised https://github.com/fsprojects/fantomas/pull/2857

**Comment by witoldsz** [comment]
For whomever it may be useful, my `Makefile` script works this around like this:
```
# TODO: upgrade fantomas everywhere and remove this workaround
FANTOMAS = dotnet fantomas `dotnet fantomas --version |grep -q v4.7 && echo --recurse`

check-format: tool-restore
	$(FANTOMAS) --check .

format: tool-restore
	$(FANTOMAS) .

[...]
```

**Comment by MangelMaxime** [comment]
Hello, I often makes mistakes when invoking fantomas and because of that it creates empty directories.

> It's worth noting that if you pass a non-existent folder when multiple folders are being passed, the folder will be created as expected.

Why is the expected behaviour to create an empty directory? 

If I provide a single non existing directory then it reports it as missing which helps diagnostic the problem.

![CleanShot 2023-12-21 at 10 49 13@2x](https://github.com/fsprojects/fantomas/assets/4760796/8303584b-529d-4367-a477-afc0ce616186)

To me it feels strange to me that a formatting tool create additional files and not just consume only existing files.

**Comment by nojaf** [comment]
You could format a directory and output it into a different directory.
If that destination directory does not exist we create it.
Because the source and destination are the same that happens.

**Comment by MangelMaxime** [comment]
Sorry, I don't understand do you have a command example?

Looking at the help message:

```
USAGE: dotnet fantomas [--help] [--force] [--profile] [--out <string>] [--check] [--daemon] [--version] [--verbosity <string>] [<string>...]

INPUT:

    <string>...           Input paths: can be multiple folders or files with *.fs,*.fsi,*.fsx,*.ml,*.mli extension.

OPTIONS:

    --force               Print the output even if it is not valid F# code. For debugging purposes only.
    --profile             Print performance profiling information.
    --out <string>        Give a valid path for files/folders. Files should have .fs, .fsx, .fsi, .ml or .mli extension only. Multiple files/folders are not supported.
    --check               Don't format files, just check if they have changed. Exits with 0 if it's formatted correctly, with 1 if some files need formatting and 99 if there was an
                          internal error
    --daemon              Daemon mode, launches an LSP-like server to can be used by editor tooling.
    --version             Displays the version of Fantomas
    --verbosity, -v <string>
                          Set the verbosity level. Allowed values are n[ormal] and d[etailed].
    --help                display this list of options.
```

It seems that if I do `dotnet fantomas dir1 dir2` then both `dir1 dir2` refers to `<string>...` which is the `input paths` arguments.

I also tried to use the `--out` option as I was thinking this is what you are referring to when speaking of a different directory but I was not able to make it works.

`dotnet fantomas src --out fantomas` fails with 

```
➜  Glutinum.Converter git:(main) ✗ dotnet fantomas --out fantomas src      
                                                              
  Formatted │ 0 │ Ignored │ 0 │ Unchanged │ 0 │ Errored │ 30  
                                                              
Failed to format file: src/Glutinum.Converter/Utils/Keywords.fs
Failed to format file: src/Glutinum.Converter/Utils/Naming.fs
Failed to format file: src/Glutinum.Converter/Utils/String.fs
Failed to format file: src/Glutinum.Converter/Reader/TypeParameters.fs
Failed to format file: src/Glutinum.Converter/Reader/ClassDeclaration.fs
Failed to format file: src/Glutinum.Converter/Reader/Types.fs
Failed to format file: src/Glutinum.Converter/Reader/ModuleDeclaration.fs
Failed to format file: src/Glutinum.Converter/Reader/TypeNode.fs
Failed to format file: src/Glutinum.Converter/Reader/FunctionDeclaration.fs
...
```

Even if `dotnet fantomas src` works.

**Comment by nojaf** [comment]
I really don't quite remember how it works. This seems to somewhat works for me: `dotnet fantomas .\Style\ --out Foobar`. Folder `Foobar` was created and contains the formatted files.
However there is something weird with the output file name.

**Comment by dawedawe** [comment]
See [3024](https://github.com/fsprojects/fantomas/pull/3024) for a possible fix.

**Comment by MangelMaxime** [comment]
> I really don't quite remember how it works. This seems to somewhat works for me: `dotnet fantomas .\Style\ --out Foobar`. Folder `Foobar` was created and contains the formatted files.
> However there is something weird with the output file name.

Ok perhaps, there is something strange in my project
