### ISSUE TITLE
Semicolon separators should be added when formating a multiline record

### ISSUE THREAD

**Issue by DedSec256** [fsprojects/fantomas#2858]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAbRAXMBbAngEqJwBO8YAvADoB2EwYAMogG6LpVgCMYACqVgBzUogDOYrtUgAzWLGlgAQgENSUyACM1igMpZR2DaoDWiUmIOJsigHIBXXJvNcALACYwAX0gAacFBi2FgAlrRCYqhgANoBDHEQUAAkWPgADshokGFYfgkQkEmsKuj2mTH5iQAM-ol1UACStEi0WLohAF7ItfUQrpUAuglePfG9hakZUdmteeNFJWVRsb0Q3KP1kACyKgAeTGGILOFYABZzq9zuVYPDG6Dzk%2BWQiM0A8jIHtIj6%2BJgXdUKxVK5RWq3cG0BAFF3p9DgDNugZJBbnURgkHpsUulnpp5OgEQUFiDlpUIABmSGJSBNIKkLAAMTCJVsiAA7uh4VSIAYyqjEui6pjAdiplk8bACVSgYtQWSwK5uVBdGkVNBEEpEHJRHw1CpcNhzITErzEPyIILEsLqaLcfjjTKSWgwb0AKxKyAqtUarWwURMWBs8zQFRBJqsWAh0KwWjGnmkPm9IZo%2B6VCY46YSqVp4lLZ3ygBsHq96s12sQAFU0hlSCGw7QI1GQjG42AZCUgubvKnHhnxfbpbm5aswAB2Yuq0u%2B0QAYXQobEM5jlgT0Cwftb7fQnaTdwxOaemYHOeBeYqI4AHBPvWW-YgtognEalVud-VkwKe1jD-3JQ6h6SI4AJzXlO5ZLugLYvh2Zq7im%2B69mKUBZv%2Bp7DpcNTyp6k6IAAgjIWDmEuuC4Coraml2lpjN%2BfbIce8xoYBlzrFhJY%2BuWuiPiEcCQbG0HbrB757kKB60Vo9FYox%2BYjlcoF4QR5icbg3GSlB8oUXBn4ITRSHiX%2Bg5SeelyUqxOG4YI9jNAAIhwITKYRpDkQmgl1B%2BFpfiKP5QDkqGykxvTcIqWE7LsDQyAAKqcry6KcfpYAA6iE8BnK2Nyae52meWJPkGX50mXO6wV7GFkWvFCAkxXFiXJecSoFmlQnwSJiHPDlJ55UZAVFkVoW0DIIS7G8NYqOupBQrsaSiBIzZ8fKF4Na5wlWqJultQxHUuvU3Djj1xBkPA1UpUqrgLYkbndplNpeTMuS5U6nVbVeu0kH68AOE%2BpAfA0hG4JESrcJRHlXWJuD2OgoSct8DJ%2BqRWAOeFGZ3Wem11NwIFYXtr1bGDEOHNDpCww5rYwKcepruYAD6bJJSlgOXUS11rZJG3ytcHoheZpAqPgbykAcliHbVc2nRA51UWA1oM9lsxI%2BhvTuCxI7bHsnPc7z-NYO9zifTI32Pn98oA%2BlF3NTpzyg%2BDISQ4g%2BOE%2BYCNTLL-n1O4EJYarPN8yEljY5b1u2yNRMetApNc%2BTpBUzT5x06bWWrTL7X3SjiTuCZSshQAarKShhPAYRCILrbzTHy0tdMTMioZycQO4QXp3sDKWWuM0580%2BeF8dItgGLQNS-Ht2J8jrOFfXuxWbAWAAOLYONk3iGIM0d8LJfUXHdr6YPcsu91SushyhyalgQavA7iA2f1tAhNGtC4c0D4fQbI4aY1Wmx8DukoU7%2BXyztSu4ZyQhaCN1oM3GM7RAEjXsKIcKsAmgtCwCNGam4YIrwlitde2Z1pJ1Zk9P%2B4NzC0EQewAM4R77a3PmEK%2BM1H6rFfC5M6S1V7vwwb5bBI53Do3TjjEIXwjj6k0PAFQc5YAL3CHva2yCBKoMlska6n9N7OzqOSTCStZ7mDsq8BB6AADS1g0hwM0U0JQXMQFCxHHQ6R6CjwbywUPEc5JFarEgEoectATC8LEOZWAlk3riEIvAX2uNvizymgvZcTlEwvwym-PuLCv4PSUW7JWqhSC3lEFZb20BSB2WZP4isl8Yw2WgPOLm19JFvkWk1UuZtpgWyCRqMOZg2ipH%2BPE6uYByRpycYEq2B9GnYF%2BK0rCWT9QZHgCiY24sZHpn7qwuxqxyR1ycboxAaQQpa3MB8FxKg3EeNbNwKoXce701kWJeRtit5KJHk48RB9pz3m4dbYiaR7AIOviE%2BeSClTP0qa-apa9rGYOZmwhZO8nFqOyQaVoJRyrKTEGY2hKDJkBAGD0bIYgGQLyiBYrwQA)

#### Code from [documentation](https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html#fsharp_multiline_bracket_style)

```fsharp
let myRecord =
    { Level = 1
        Progress = "foo"
        Bar = "bar"
        Street = "Bakerstreet"
        Number = 42 }

```
            

#### Result

```fsharp
let myRecord =
    { Level = 1 Progress = "foo" Bar = "bar" Street = "Bakerstreet" Number = 42 }

```
            
#### Expected result

```fsharp
let myRecord =
    { Level = 1; Progress = "foo"; Bar = "bar"; Street = "Bakerstreet"; Number = 42 }

```

#### Extra information

- [x] The formatted result breaks my code

#### Options

Fantomas main branch at 2023-04-20T06:35:38Z - f94d4ee80cfefe66b5324d315d021acc77922a90

Default Fantomas configuration

**Comment by auduchinok** [comment]
The result formatting is correct for this input (i.e. a record expression with a single field and nested application expressions on the right side).

I think the issue is that the docs miss the semicolons?
