### ISSUE TITLE
Different infix operators not aligned/broken correctly

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#2863]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEIBtEBczYDsBnMAXgB0AncgjOsHATwAdEB9Km%2BjAPgFoeYAPIAjIokoA3AIY4AlrAIAVFogB0zAK4jMcogAtE8UeKmyFBDtVrcwPAPyCACtt0GjJiTPmKAIrOk1fWkiAFEADxxEAiR4ADU9ORE5XSY2SAAacChxHHkCAHMiVDAAbWyIUG5IABImVhLIOQIcTIqMWplMTWQ0ctswAAYsgcgASRjonABlOQAvZBHbABZ2iABddoBfJcq1qDrVRubW3Y6arp6S-tsARjO6SABZaXCAGWbEN%2BiCnH02ga3ABMg32mzoO3aVXotXqvSg0WMADMPgRENMmNgATCLtJuvCbtwgQ8OqEYkIUZ9sdVMEjIGDtmdoY9Dg00JARLBYJhqedLgT9hAAMwkiDjYgSHAAMWaeIAcogAO66NG8ug4Sg9BkQpn7WFHdmc7lqg7866CsDLUVQabMaTQRAAIUQSNglEQTmklGkAFtcBITRANVruOCMJC6MzznDGkaeSTOnirn0LQBWa2QW32p0ut1fWCKiTQEKICaSWDFnwEQMMTWIbXh3XVVnwjlc%2BN63H480DABsGazDudrvdAFVmKxKMXxGWK%2BZFDWkXjxA2IBGMFGxS3Y%2B2TYnuymBgB2Ad2oe590AYUwISIl8URGD0BwbsXy-rocZUM7McNu4TXbJmUFoAByntmw55k8iA%2BiIAbWkumArp%2BOrfs2v5QHGe6AQKAwAJzgeeI6IPemALgh76rmA657OhBqYf%2BnZmoedzDBamZnogACCSJRJQ94%2Bj60g1sGH70GGa5NjiGFtsaAHMcBgL3Oxg45sR0wwXIcBkdWFFIWJdASdRUksjJWHyUmuF3MSKmcTxfEaT6WncuRFqiVRNFgJuBxmYxzYKYS9C3CKtnZlxlCwJoMS%2BIguhOXxIl1h5JnRvRTQtNhAUWrcVrsS84RjEiSiGAQ0z6G6OAAOpyPAfw1qCKGNmh0lpScmWWT2dzpnlryFcV0ShPpZUVdVtX-NavYNeJX6Rj%2BrUZRZB6KXc-Y9QVBBInI4RCJOshuhEzDukQRAWDWIFTYZM0bnNbJQG1i1AYFdC3Cea0AEqIHAlDwKNdXWssF0YEZnnefqt3pacTEdSx3C3GB72fW68ByposESBSYxRD6xTWrcyXNaZaU%2BpomDyCqiBSm6Ql5BIKgNA9VmwwR7EfV98BPCTZOfJTlDUwlGbQME3rPhIbCKjVdX47NdHg-dUNLU9GAghm%2BXhd6jBCJQHyPr942gYDGxXbRLWywt8uPRaQLKaMquUOrmvazgKNo5QGNYzj2VS9dMutsTpMpNzVOyHxdOLObjP0ECNmjGr0ga1reg4Bz-vkzzfPwexgtevafFixL-xe8bhOm5D-nQ8tRIhTbrxxJZjrNPAzQFLrZ0G2AwMpVuMly2XCuW7l1fhFKUXPhY9cxE3Lf-W3HcE6lJftX3AxAt1g%2B%2BLAOAAOK4AdR0nYoU-64XXk3a25nh51RKraMCrKp8zo4IW0ShzFm0EHIVZcTE0Eux7AzuY1SSc8u5pXPr3C2y9Xox10AUAgw8CCj0ULMWBshNDuiULACYSAWjzl0haRCyFpqoWlibM%2BfkcRZWXvDaBfECDmEkPmQoP84KUFfs0D%2BFg-62AIQZIGRsT4%2Bx3HJC%2BMNI7MxtpzOQqIvi%2BhEPAaQ15YAnUKLfcmb59LH1BtuP8wjwERzoEKNiowDoSDkH6HBmAADSiBEDMCwVMCYjpvQIL1gMHhmjT5CI7Hoy%2B9AhTW1sJAR0N4CAAGtpFEHCpFGICpHxGGTlzNEu9EDHU4YlEMRCmokOLmQ3RFDy6K2FNHQJjovSQXdL4PQ0BKBmNlFEeAo535%2BE%2Bjeb0VZ1GEMusQ72pDGh%2B0SU6YWoTcAYkYFiBmviDFV0CQkgOaInH2mGTMTEYdRjVN9KweA9JAHGWAT5eapd8lL1sEKAegTrG2Pys7FhFJgnSDCREmstxBgz34Vo3yeSWSUJOavQJqj74XkQLM8mAktA4Fwck1Jrl-5JR2SDTxOjvFHIgSc6%2BgSTE1PMeCzAg0nIGA6bww2EJsjrCWE0IgUoTolHcVsIAA)

#### Code

```fsharp
let lens =
    type_
    >-> ObservationType.publishedObservation_
    >?> PublishedObservationData.hasExtendedVisibility_
```
            

#### Result

```fsharp
let lens =
    type_ >-> ObservationType.publishedObservation_
    >?> PublishedObservationData.hasExtendedVisibility_

```
            
#### Problem description

The initial code is how I would expect it to be formatted.

Note that it is formatted correctly if using the same operator for both (whether `>->`, `>?>`, or something else, like `>=>`).

(For those interested, these operators are from [Aether](https://github.com/xyncro/aether).)

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by josh-degraw** [comment]
So short answer here is that at this point, this is actually a feature, not a bug: there's a specific handling for if the infix operators are the same. If guess this is mainly there to treat pipe-like operations the same but it doesn't account for situations like this where there are several similar but different operations like these. 

If this behavior is unwanted the best way to work around it for now is probably by utilizing `fsharp_max_infix_operator_expression`.

If that is not sufficient for your use case, please feel free to open another issue if you'd like to suggest a new feature to handle this differently.

**Comment by cmeeren** [comment]
Reducing `fsharp_max_infix_operator_expression` causes too many other unwanted changes in my code. Also, it doesn't catch the case where the operator arguments are sufficiently short.

I think this can be solved by https://github.com/fsprojects/fantomas/issues/988#issuecomment-670365098:

> I think this may be solved by Fantomas knowing about [operator precedence](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/symbol-and-operator-reference/#operator-precedence).
> 
> Quasi algorithm:
> 
> * If line is too long, find lowest precedence operator and break on that (break on all operators with the same precedence)
> * If some of the broken lines are still too long, find the next lowest precedence operator(s) in those lines and break on those, but indent as demonstrated in this issue
> 
> Do this recursively, of course.

In summary, I think this can be solved by Fantomas considering operator precedence. Instead of breaking chains on _identical operators_ as you describe, break on _operators of equal precedence_. The operator precedence rules for F# are AFAIK well-defined (also for custom operators) and could be hardcoded in Fantomas.

**Comment by eithermonad** [comment]
I've been running into this same issue.

When using `|>>` as a generic map operator and mixing it with `|>`, this code:

```fsharp
let test (x: int) =
    x
    |> computationOne 
    |> computationTwo
    |>> Option.map ((+) 3)
    |>> Option.toValidOr "Problem"
```
becomes

```fsharp
let test (x: int) =
    x |> computationOne |> computationTwo
    |>> Option.map ((+) 3)
    |>> Option.toValidOr "Problem"
```
Which, in my opinion, is much less readable.

Similarly, applicative-style expressions are affected, with:

```fsharp
let result =
    create
    <!> validate 1
    <*> validate 2
    <*> validate 3
    <*> validate 4
    <*> validate 5
    <*> validate 6
```

which is fine as-is, becoming

```fsharp
let result =
    create <!> validate 1
    <*> validate 2
    <*> validate 3
    <*> validate 4
    <*> validate 5
    <*> validate 6
```

Setting `fsharp_max_infix_operator_expression` to a lower number isn't really an option because it affects non-pipeline expressions. I, too, will likely resort to using an `//` to force a line break, but it's less than ideal and adds noise.
