### ISSUE TITLE
Invalid location of comma when using named parameters for a class

### ISSUE THREAD

**Issue by MNie** [fsprojects/fantomas#2865]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAspgMIDKAFgIYBO2RANhQM6MAUAlGALwA6V3AdhAgBbRMIBGiKmABuFOmAAKVWNi5gADADoNwsAHcAlujJgA5onQAaMI0u8BQsKIlTZ8pSuwAmddt0GxqYW1rb2fPwO-Fi4YABi5NTYACo4eJxgwFFOJLCiAGryAK6IaIzoVIb8ZmCq6IawkREAvlFRdJay6sBguQXF6b15eNyQ5XyQYK0R7Z1V5RT80IPZQoT0TKyrThDKqurbO07CFOjQpnJ0JVp9iIVXeEYmYIdHEAA%2BQ6JgAPpgALQAPk0OmErzenwAco08ECQbpwRArIjPKpfDwIm8diczhcBjdhvcSoETCinJ9br8AcD-GDMVihFCYdT4XTHEI2JArOAoHZ0PVqoxUGAANo8iCgI6QAAkMWQaEgVXQXPFQhllxKwrFWI03KxkAAkvwkNESIYAF7IPVvAAsqogAF1Vc1rRL7VBZWlhYroiqpdKNfLRe6IABGV07SD4CgADwAMlVEHHENUTH63qHvBp3U6nC7VZLI57cN6U-AAPIAMwT-EQJCwHXTTnVAy1IbA3gjzYAosaqzWre3IHRK5Ac86I4Xm8Wg5BxLBYHQm2qA620Nq3gBmLtqo12KjoOJVeSQxD6OiJ5dOColcd5yfumVy73zxdXj2BttYm07iCQEjYBQywAEKIJWsBUIgijUBQojoFI74QDeiB3kI%2BZOFOK7Pgqr5LjuLYPF%2BbwAKy-lAAFAYgoHgZBcawPoUjQEwiBGjIsBMfUjSIWAyGoRA6FCJhf4zi%2BC54Y%2Bq6Eeu7YAGxkf%2BgEgWBEGIAAqtguBUExdisexpwNPw3GVvIdh8VMD7%2BthUC4e%2BBGatJWIAOzyRRSk0YgGzMEQjTjEU0DoBBRkmShRy5mhFlFlZc5ibZkn2cGWIABwuYpVHKZB%2BBiJIVBBXQpmhROBYSVFNn4XFQYbkcACcKWUdRKneXQXFkcZeUhTsYX8RF04lTFZWfg5Ga6kOrmIAAgpW8FUN5wgnNxvEFfeRWWV6OF9RJA0JRm4Yjal9WQSQYiGHATWGS1wVmQJborSWa1vv1a5bUcma1csE1TYdwjHYuzXtgtHWFRhxWrdZ63%2BptlU7KG267ZRY0qEUxoACKIBeX1TfNVC3ot4XLZFIM%2BsqD1SU9UM-kO0YxgalbJGQKbkBB6AAOqGPAaZkdmONdXjPUE0qsUQ%2B2oakRTsbU7TKbdm1DMHizbNkNxMmcwDS1Azds788T8WQ04oZyaLVP8JWhgxuWmmnBB3YxtgkHMAZ3GJcrTideZPNYXzvpaxVQvOQbABKiBwFQ8By%2Bz7Y2k7Qgu1dmTA7dUCaxtj060IobJf7gcQfAkJFK4VBVga8HCEKZGhpd3Xu-HkDCEUdD1BetZxBBOJTakJZe0Rz01UOAdB-A%2BC1-XiZN1QLcIfJ5wwf5Ug-EY8tjlzrtq-jVeJ%2BDyftlm8mU-DVAUJg5ZUAm5ShwrZGO%2BXbvCVFa9FoLWLeDt%2Bo71Qe8H0fhjlDnecF0XJdC5fZevMq41zroYBuiAR5jyoG3Qc68SYpwgN4TsQ5d770PsfdAA8wEQKgacDGE9KB72nlQWerM0yAMEnHDWnsk4IM3jDZ%2BsYiRUSqPAKoZhT4O0jo6QGVD1belvtOe%2BbxvDkyYTGOIiN-IGWAmwjhXCyIR0oddFeNCiZ0O1pvEWEikawHQAAcUsFbG2iA7aNEUe2C%2Bi8Y5CQ9L1e6mjvYP31vqU855EygXQAxFMsCUbG34MYAyY1jSZTzv-LE-1nZ8NUcA2cpUnGdx2N4X2%2BoxoXjMPwKRSxOL8DNJk04RRILJFgEaE06B9K-SxK1fKKtcZAMrvEsGd8N4P3TmkuuUh%2BD6RkEmRoZgwnZX8VUIJPlcq1OiarfhajRKOPgVoh%2B3dn6D0MAOOMsFxDwAoPQWAjAOHuIgeM9qkz6nTLibM8S8znFbmGvqExUhDCiGiPIAA0ogRA2AykpnQEaYCe8lhn3bDU45UcYmxwEXdS5LT6FYk3E-N4kBgIMH4AAawHIweGsBEbZzMfBfuKyIEmNtnssZZEomgqmbExpFyBatK3Cg-UwFqD7UQEjT%2B0BKhfW6Xi1SgTGgo2gAwPeuSjkqPBTMhUoCh61j%2BUBFFlh6yYEbB3QaRxNyMIRdg6VVFiHyvQIq5VQ4OWwVwPABedTuYNOvh7DRVyklOE3OIhFbyPmU2-tlKsSLFhosTBEoaPCwDRwrtaquCS7Wqp2JuHRCKDmePSogLV4DEwzWwEUCpuSiVmJJWdP6WMQW8MpeK85kLaUwq3K4hF9zOXfPkFLL6jBAXVIujYnkDprSKkYHEPZwpgUgGaEAA)

#### Code

```fsharp
type MyCSharpClass() =
    member val Prop = 0.0m with get, set
    member val Prop2 = 0.0m with get, set

type FSharpType = {
    SomeValue: string option
}

let v = { SomeValue = Some "str" }

let instance = 
    MyClass(
        Prop = 
            match value.SomeValue with 
            | Some _ -> 0.0m
            | None -> 0.0m
        ,
        Prop2 =
            match value.SomeValue with
            | Some _ -> 0.0m
            | None -> 0.0m
    )
```
            

#### Result

```fsharp
type MyCSharpClass() =
    member val Prop = 0.0m with get, set
    member val Prop2 = 0.0m with get, set

type FSharpType = { SomeValue: string option }

let v = { SomeValue = Some "str" }

let instance =
    MyClass(
        Prop =
            match value.SomeValue with
            | Some _ -> 0.0m
            | None -> 0.0m,
        Prop2 =
            match value.SomeValue with
            | Some _ -> 0.0m
            | None -> 0.0m
    )

```
            
#### Problem description

It seems that when we have multiple match statements passed to named parameters for a class it places the `,` in the wrong place. That results in a `dotnet fantomas` error.

Known workarounds are:
1. surround the match statement with `()`,

```fsharp
let instance = 
    MyClass(
        (Prop = 
            match value.SomeValue with 
            | Some _ -> 0.0m
            | None -> 0.0m)
        ,
        (Prop2 =
            match value.SomeValue with
            | Some _ -> 0.0m
            | None -> 0.0m)
    )
```

2. extract the match statement to an explicit variable. 

```fsharp
let instance = 
    let v1 =
            match value.SomeValue with 
            | Some _ -> 0.0m
            | None -> 0.0m
    let v2 =
            match value.SomeValue with 
            | Some _ -> 0.0m
            | None -> 0.0m
    MyClass(
        Prop = v1,
        Prop2 = v2
    )
```

#### Extra information

- [ ] The formatted result breaks my code.
- [x] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2023-04-20T16:04:28Z - 4ed1e9d49b17d6045fc0188336c2a282ae245d6c

Default Fantomas configuration

- Fantomas v6,
- .NET6

**Comment by nojaf** [comment]
Hello, 

Thank you for reporting this issue! 
I think you could extend this check to include your use-case:
https://github.com/fsprojects/fantomas/blob/f144756d7849a29438c84872f61d043be95fcc67/src/Fantomas.Core/CodePrinter.fs#L1876-L1895

Are you interested in submitting a PR for this?

**Comment by MNie** [comment]
@nojaf will try to do so at the end of this week : )
