### ISSUE TITLE
Insertion of a newline changes precedence of the `||>` operator

### ISSUE THREAD

**Issue by ljb** [fsprojects/fantomas#2866]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAKogM4AuAOgE7kB2VtepY0liAhqYgVgA55gAKNmjKUAljQDmASkEAjEaXFTZAXjBsANGDn061GozAA3Njiz5VeiBHQdoACzDlIoiZJdgA7mNIPrNgA%2BzpCm5oieALQAfCEAjC7aLgBMLgEQwQD6YDHxcfkFhUXFJaVl5RX5iSHJtXX1DY1NTWkGNmCBgbEs7JzcfMia4FDEiKSk7sSoYADawxCg7RCQACSkAJ48yGiQEqSQQ0tQK2EW03NHEAAMh5eQAJI0SDSkAMpiAF6D80sALD8QAC6PwAvrcFgDjhsttNdi8DpDVqdtrNIRA4uClpAALJsAAeABkJIgCYgpH4EZcwHFkldIcD2mCfossWtNijIGT4AB5ABmRJoiFeGzwlNZyPOaLAyUx7UgAFEnnyBd8qZAcLzIPTQZiWXK2TCdnJYLAcGL9RK0BdLgBmWU2B40UaUUgAMQkZgAcogvDhiealkoLNrGbrEQaOcbTQHliczGcrVLfvblq8eGxoIgAEKIXmwVgABTYlDY6DGiEoMZsQcQIZsTPaeodEdhUbN9qR8ZR1qOAFYU1A0xns7n8yTYF4K9A2KNHsZYNOJrAaFWIDW6xAGzYm7HoZGTe3w5bUVSAGwDyBDzM5vOsACqPC2lGns5o88XYmXq7AvLMow3YBbhCRyrHurYHlWnbhJKVIAOwXleI63ogADCOAzsQKHLqIWDQKQ%2Bbfr%2BOD-kcDL1mGIEtkaEEdnG0GJlSAAcCHpteo6sNiiDoHIFaEX%2BtakTqzLhmB1HRrRx49ksACcLHDjeY5YTgX4DkRJFLGRm4UayolQG2kF0QmJ6XHENxSperGIAAgrynCUFh6B2N%2B66CaGwmUbpkD6RJXYwSZGLmYhCmsK8XFiHAykrqp-EAUBYA7lC7LgeJR6%2BQxJkyoFlk2XZoXoOFpoqVKLkaUJjYiUlYmHpRklSnEdpZcOVmULAWBPAAIogfr5XZzmUMGrnke5OmVVAewGbVVJxMm5m4ni9y8gQDhkq8Dj5qQADqYjwBSA50oNWnDfqnnjT59HGUccT9rN%2BILUtZLysRQprS6W07Q436nvtpVueVHmjXC%2BxnUZUntHE543fNNC8mIeLck%2BHD5vKeI8KwxDEJ%2BUVSox33tJpgHacdAOnal52gzYcTwZDABKiBwJQ8BvbtSa4zY%2BNxQloHE-CwPdnVzE03T%2BbwJ6WDcRWfL3Jw6BTAOcSxYTzaeeguATH6gquvmdjjBWBBJbzfmXbJ5m0-T8DYqrYjq4gmuUNrvUXo4xYZnZmQ%2BO9WoHQTR1K9zQOkyDUq0hec3NSW6zcpQRJkEzH0DjjCs%2B7ufsTWlF1LMkAVqqHlDh5H0ekKL4uUJL0uy3Vid-SNhoYJb1u2-buv6wHfNUrUF5h2wEdR2IZAWzgavEg3HAO%2BZTslnhFZu9tFKV9uFU14Dqdk0HDXZ-iABqXZZhI8DuLH34J17HMLxyJM1Wn5MQMkM3r3irptXhmM708%2B8z3HLNz8B1dnzzLeGxna6d92qwFIAAcTGMjVGJAMbLgPvHVmQIyrz3%2Bovby-90pHGSBDNU3pfTEhzKQScZI9ZbE6jDGgvhMZWSeJxYu5cqQlTxsg7%2BRM0E0QwendoyQqZqisn6SQNAH40Cfsud4giOBYFYAQWAjxnikA4JjPiT0v7xVPslaq4pL5BwFnwgeFYaCKOMOOKQdCeKUHIRIKh2FlHqWYb9FBP8NHL0Dm3Y22dLYqgJKWOQ8A2BoVgBjKQeDra2IEj9IaVc2H7hShfFeVIbRmTVFAisYgywvDMAAaUQIgHgciySkEeFmEsIiP5UjUuE%2BxkTHHROcQbTBSwbRZzuFmdCNAADWKpiDNVak8b0ZBEDmzrsSKBaNYFOj6gNCJh0om%2B3YbErR8TbSZTVFmYswVEDtV7iwNJHpODwDvJQ5cnVoDoRLEuLG5SYrH0VsnReKsB5WwIRPdpYxhTrFFPUrhNgbRrzuP3QegpikZleW8EUqo7gsFLFseAntpne1mXc3%2B-s4muNtLfO42TclzSLuYvkrS2AdK6d%2BUyiCwDs1uYleZmiLTaISUAu4ISCHsUQACp5goHI8CwAoi5oyYFKIHEwtmLC1GoJiTS5sk1bQ4LuCk8Q6SFE4EevlYgZTLgVNisMQEtxdjEFdBjaYGqQRAA)

#### Code

```fsharp
module Test

let createTuple (a: string) (b: string) = a, b

let value =
    match "string" with
    | "value" -> "1", "2"
    | _ -> "111111111111111111111111111111111111111111111111111111111111111111111", "22222222222222222222222222222222222"
    ||> createTuple
```
            

#### Result

```fsharp
module Test

let createTuple (a: string) (b: string) = a, b

let value =
    match "string" with
    | "value" -> "1", "2"
    | _ ->
        "111111111111111111111111111111111111111111111111111111111111111111111",
        "22222222222222222222222222222222222" ||> createTuple

```
            
#### Problem description

Running version 6.0.1 of Fantomas locally results in a slighly different formating compared to the online version:
```fsharp
module Test

let createTuple (a: string) (b: string) = a, b

let value =
    match "string" with
    | "value" -> "1", "2"
    | _ ->
        "111111111111111111111111111111111111111111111111111111111111111111111", "22222222222222222222222222222222222"
    ||> createTuple

```

Both the code generated by Fantomas online and localy results in the same compilation error. Running `dotnet build` with the .NET SDK 7.0.203 will give the following error:

```
C:\repos\test\test.fs(10,9): error FS0001: This expression was expected to have type↔    ''a * 'b'    ↔but here has type↔    'string' [C:\repos\test\test.fsproj]
C:\repos\test\test.fs(10,51): error FS0001: The type 'string' does not match the type 'string * string' [C:\repos\test\test.fsproj]
```

The problem is that the call to `||> createTuple` will be run on the entire `match`-expression when there isn't a newline. When there is a newline, it will only be run against the line above.

Adding parenthesis around the entire match expression before calling `createTuple` is a workaround. 

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 04/26/2023

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.

We have seen this problem pop up as well when the `indent_size` is 2.
As a workaround there we have wrapped the match expression in parentheses (as a last resort).

https://github.com/nojaf/fantomas/blob/f144756d7849a29438c84872f61d043be95fcc67/src/Fantomas.Core/CodePrinter.fs#L2083-L2103

I think we could extend this check to `ctx.Config.IndentSize - 1` (as seems to be the case for `IsIfThenElse _`).

Are you interested in submitting a PR for this?
