### ISSUE TITLE
Online formatter URLs do not remember stroustrup

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#2878]
1. Go to https://fsprojects.github.io/fantomas-tools/#/fantomas/preview
2. Enable Stroustrup style
3. Enter this code:
    ```f#
    type A = { A: int option; B: int option; C: int option }
    ```
4. Verify that the above is formatted as 
    ```f#
    type A = {
        A: int option
        B: int option
        C: int option
    }
    ```
5. Copy the URL
6. Open the URL in another tab
7. Observe that stroustrup is no longer enabled

I would guess this is related to the renaming of the relevant config key/value around v6.

**Comment by josh-degraw** [comment]
I'm not seeing this behavior anymore, are you still experiencing this issue?
[This repro](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAgmALxjAFoCWAdumLNuhbFQNxgBClNdDTrYAYS616jZmAC%2BkADTgoAZ0TpGVAObzUYANpyIoCAagASLLk2Rq6GboOQjANwCGAGwCuyNDsOGADLO%2B2AJJUSDQAyhQAXsj%2BAWAALDYQALo2ErF6ScamHlCW1gF2Tm65XnEAjBnekACyjgAeADLUiI2IaugAFgUVAEw%2BWamG6Tb61SY4uZDt8ADyAGbNVIhhWM4xWUUu7pplAb1VhpAAoiELSxtxUM7zkINpVWNHE2ZokABGsLDOPc-FO54shAAMyHIJURQAJ3QADFqC4AHKIADuzhav286Eh7nuw0emxeU0%2B3wxEC2JV2QISYLJYWwjmgiHYiHmsEhiAACo5IY4ALZKRCQ0kGLE4gJDAwjQxPWyE8zEn5g8kA7RUgCsNKgdIZTJZbNasGRgugjkUwXssBNYiowogosQuMl%2BMKcreCuFytKVIAbJrINrGczWeyAKrYXCQk1mqgWq18W1geYuRSOiBSgwysmuqDupUObZeq4Adj9Ad1wcQAmcpvkAmY8lF0HQbITSecKfFD1GBJy8q%2BioJ-0LcQAHKX6YG9eyaohee9Ba3kw7O3juy7e27%2Bx78xTAVcAJzjnVB-V15zMRft5feCVp53jDc5rd5oeUq7lPxU-0TxD4eboQU615XlHATe1U0ke9nkfD5n0HAs3wqSovzLE92TCWcKDgc8bU1NsOxvLtpR7SY%2BxJF8EL3Poj0ZP8AMhDDeSw74L01cCVydNcH1IzdyPg3dVXfUEUJ-fBIVgVwQgAEUQNEmPosDsWvQxb0grjoJ4vIaG3V8qICcp4j9Op6kCeYABVOnaMJOjZdAAHUKHgLoEwGDi73U2UYPyCiBL2bxyg1L9jNMiz2mOK9rNshynO6TVvVcwjV2I9dNIsbSfJVPzDHKX0goaYJ5goepZgjRxm0hY56mwdl5HkeNNRHBKVKIjMSNeLSrAy4d9JLPL6gAJUQOBIXgaLnM1eImoMVT00yFL2rSzr%2BMyqlyjHPrBuG%2BAEVcOdBQWQIAN5DRNXKCDZtINqpl5VxnEYNFlhhNkQOUQUzNIrrEP0w8v02tl4BqW77paJ7IRehS-WgTpuQZeiAH1kUc5zzqgzzUu85buu8fojIaMSeUwWZIWaBsxtiqlGpRjysy89LMa%2B7HkKuWo8chAmiZJ9Adr2yEDqOk7Vqp5LuIWm67ooB7EFB8G3o%2B%2Bm9Oxg4v3xxxCeJigG0B8XJelsqIa-KGYabQUEaR7ohda%2Bapgxl1dMEuJemE5njIANQLdhqHgahVDJhNKbctThY0habfGO2soMXpDL6mFJKbPgPZCb3fYmqaUhauaRetunbco%2B39kC52Gik2B0AAcSUSrqsQWq%2BBTim07AGbUZp1Lc3l-Psdy5mkVRFpmXQI12ne3AZMKqgKGtfAQhnHmBaudjEs4oO0YW9vc98qlel65n8DRVQqFjqh4%2BYCID7K1x2TM2BglCdAyvqql8OU6aM8uq2yIHDeVquXp1t3u6goqAP3sAaNQs95yQjHtQSefB55xGfhbTOwciRwW-ljQwvQfrOyBhQC4jQ%2BTvHgI4KssA6pqF7pLS8BFmpJUtlnT%2BOk84RxBJ%2BZmVdBQUH5DQFwABpRAiBsC33aOgYI7AeTH3JlcRBAcLqZmyG3NBYdmFUmBEzOIkB2DVioAAawuPIMSEkQhIgbIgAGuDJZVxqnVesikxRL3civVua8lF-BUVcYEStmbsG5GhRAUkNbQEhFw%2BEAF4AhgnswGS0Bqw8mtNQl%2B6c6HINXtdCx-ceTQB0UoVYmB1hMM3h4p2GitbA2WOIhk2T0C5PyX6Bs4lXD1NcNgO4siW4KJDjnZRhS4jAmjszfhgjjLc0gQsLRjhdH6ITB%2BRuzdqYdNQXxdBDNDDAkLhoyh-cpyIFKRLFoQFsCuHvtaKxNcbG4SpIvWhy96EoMYZ9BWqzu4aI4cE7h99nDhSYvIKRCClznTkMkWIFh5AwjqpoRBEggA) works fine for me at this point.

**Comment by cmeeren** [comment]
Yep, seems to be fixed
