### ISSUE TITLE
Option for consistent indentation style of all pattern matching branches

### ISSUE THREAD

**Issue by iblazhko** [fsprojects/fantomas#2885]
I propose we add an option for consistent indentation style of all pattern matching branches.

The existing way of Fantomas deals with this problem is that it takes into account line length of an individual branch expression.

As a result of that, some branches may be split into multiple lines with indentation, while other branches are in single line.

I believe it would improve readability (at least in some cases) if all pattern matching branches were indented consistently.

## Pros and Cons 

The advantages of making this adjustment to Fantomas are:

* long match expressions are more readable

The disadvantages of making this adjustment to Fantomas are:

* short branches will be indented although they would have fit line width without indentation, so some may consider it unnecessary

## Examples

Consider this initial source code:

```fsharp
let fromDomain (evt: InventoryEvent) =
    match evt with
    | InventoryCreated x -> 
        x |> InventoryCreatedMapper.fromDomain :> CqrsEventDto
    | ItemInStock x ->
        x |> ItemInStockMapper.fromDomain :> CqrsEventDto
    | ItemWentOutOfStock x ->
        x |> ItemWentOutOfStockMapper.fromDomain :> CqrsEventDto

let toDomain (dto: CqrsEventDto) =
    match dto with
    | :? InventoryCreatedEvent as x ->
        x
        |> InventoryCreatedMapper.toDomain
        |> Result.map InventoryEvent.InventoryCreated
    | :? ItemInStockEvent as x ->
        x
        |> ItemInStockMapper.toDomain
        |> Result.map InventoryEvent.ItemInStock
    | :? ItemWentOutOfStockEvent as x ->
        x
        |> ItemWentOutOfStockMapper.toDomain
        |> Result.map InventoryEvent.ItemWentOutOfStock
    | x ->
        raise (EventDtoMappingException $"Unknown event DTO type: {x.GetType().FullName}")
```

Fantomas 6.0 with default settings will produce following formatted code:

```fsharp
let fromDomain (evt: InventoryEvent) =
    match evt with
    | InventoryCreated x -> x |> InventoryCreatedMapper.fromDomain :> CqrsEventDto
    | ItemInStock x -> x |> ItemInStockMapper.fromDomain :> CqrsEventDto
    | ItemWentOutOfStock x -> x |> ItemWentOutOfStockMapper.fromDomain :> CqrsEventDto

let toDomain (dto: CqrsEventDto) =
    match dto with
    | :? InventoryCreatedEvent as x ->
        x
        |> InventoryCreatedMapper.toDomain
        |> Result.map InventoryEvent.InventoryCreated
    | :? ItemInStockEvent as x -> x |> ItemInStockMapper.toDomain |> Result.map InventoryEvent.ItemInStock
    | :? ItemWentOutOfStockEvent as x ->
        x
        |> ItemWentOutOfStockMapper.toDomain
        |> Result.map InventoryEvent.ItemWentOutOfStock
    | x -> raise (EventDtoMappingException $"Unknown event DTO type: {x.GetType().FullName}")
```

Note that the branch `:? InventoryCreatedEvent` is indented while the branch `:? ItemInStockEvent` is not indented.

I don't mind the changes in the 1st `match` in the formatted output, but to my eye 2nd `match` looks misaligned, it becomes even more apparent when more branches of mixed length are added to that `match`.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M? (No idea TBH) 

Related suggestions: N/A

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to Fantomas
* [ ] I or my company would be willing to help implement and/or test this
* [x] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting): ["Use consistent indentation"](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#use-consistent-indentation), however I realise that this may contradict ["Avoid extraneous white space"](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#avoid-extraneous-white-space) guideline
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Hello, thank you for your interest in this project.
This request has been raised before and is being discussed at https://github.com/fsharp/fslang-design/issues/650.
This should be settled by the style guide.
See [what-are-we-not-looking-for](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#what-are-we-not-looking-for) and [Default-style-guide](https://fsprojects.github.io/fantomas/docs/end-users/StyleGuide.html#Default-style-guide)
