### ISSUE TITLE
Idempotency problem when reformatting type declaration with large when clause

### ISSUE THREAD

**Issue by etareduction** [fsprojects/fantomas#2896]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBLAdugYmAGYCu%2B0AOgE7X4QQAUAhrQOYp0NN9gByVmADuAC0SMhaZgFtEsgEaJaYVmgJYAlGvzxB6sHIXLVijfm2790o-KUqw0C1dZ6DM%2B6bDwXOtzaGxg6qiH5aPIxMALxgAAyRkAA04FAAzthYBBxpqGAA2qkQoPxQACRYAJ4ADshokJrJRUyQZQBurOjkdQXNfHEppRCQAJJ6klgAyrgAXsiDQwAsfWAAus0AvgvFK61VtXkNlk2lrR1dPYVDYACM2-yQALKsAB4AMsRvkhxYYidDNwATHEVus%2BFtmiUHhUaj1IJJ4AB5UgffCISZVTD-PhnTrdPJXIaA%2B44gCiemRqPmK2G6FIkFBm3uUJxMIO9UUsFg6GxLXaeMuNLAAGYSS0xhlaFgAGIEToAOUQIiIaN5fCwtG6jPBzN2bLhnO5avK53xaEJpUWYuGk2qrGgiAAQohSLBaIgAArsVjyLAqY0QDVa0pgpgQvgsvn7A1cnli3EXAlCgCs1qgtvtTpdbsQb1gIhU0FYGTGbVgRaysHwAbAQcQ2rDutO%2BsOhrjetNguuADY05AMw7na73QBVaq1WhFkv4MsV3BVmukToZBsQcNMSPDFsc2PGhNm3rXADsfYHWeHiAAwuhi2lL1W0kHoFg3Yvl-WQ0zIXro63d-H%2BUTc0hQADlPO1B2zd1HhMf00yXdAV0-HVv2bX8dyNADOyTa4AE5wMzIcc3vdAF3g99VzAdcdjQ2E-0wjsBRwgEBiFfsIMQABBUg-Voe9ZFkVgazrSjqLATdynQqA2z3QCDwtfgbjuNizyI91JgUXA4FI6tyMQj9%2BFDNcm2hKTIBkrCmOA64gQIh1uN4jTZC07kyKFETkMbVDTLojD22bbDrIBUUVI4zjaFgSh4AAEUQIhnN44TNQMvgjKokzWTMxpLKAw8AStNjnheEZSAAFQkfBJjEN0sAAdVweBfhrEFPOM7zMt8qBssY3KFL4G5U0K14SvKyRSX0qqavqxq-jTbsWsMr8Ix-TqjiwWTAry0obl7IbivwUhcBeREJ1YF9aFJF5qndNI0nnXTQIW1Klo3Fb2S644cvkoUbhPPaACVEDgWh4Gmpq00WJ6mDSsSJL2VbuoCqytsUsCAaBt14HlcgQmREY-VkXI0xuUSMqjVbZHIdAshVRBpTdQSsF40q6K%2BrsAXwtjAeB%2BBHipmniHp2hGcSvtoDEb1nxUAB9EQGqa0n2vJ961o25G%2BqYYE%2ByK8LaFYSpEVoD5HzB2bHsV5baJVxHoU2jWIEBZTrieV5df1w3jawbHcdIfGFCJn6Ldeq24Up6ncFpoWRZUFmDjZ5jSkBYk2Ldg2jdwR8%2BfDyOGbO0W2PFyXeNl%2BW-iDmifOtz6eu%2B65ARC52ioANQFR0CHgbJTZrECoYgGGya3LLq6R3qhUBArG9eaVKGfe6270TvS5rSHy-Et64Rt1k7bHwbJ5eaLYCwABxbBLuuxBbvuru0x71e4e3aT-xr9nE9253FWVYhnSwAtJFjxBYqHXwLgSs%2BBOJ6BgiEAO1wPKLRQpbSuMYGIj1rkSP6ztOJEA4PgaeVBQHTGwWdcg7pSqwDGEgSwZ17pvn0nfde9F-K23VmPNGGDqYqHwFQtouYqwcEgaYQBBAQH3WgUMBCSE4FeQQR1FWFln4J34ICTmjd%2Ba4CpG8H0ih4CsGvLAO6%2BAOAf1pjQiRz14HB0QQwtWo9rjClYs7M%2BKhcDyEoegAA0ogRA1RyETDGI6PWVAzbXHESlaGL0K4yKQYwrezDbFOyGJAR0N58AAGsqRpHCpFPQipHyIF5qo2mZ8bp3QfElYMki2rSOVlE6xqDSjCmTs7R07A1IAIztAWgzi5R%2BngCOYBVZYrQBvHrUBJjQl93CWvEOhww4CzRP4%2B0KTsAYkqFieOQV6kNwSVnOZTo9bQCWVMTE1JnYdJ9LUeADJWrpSVoPBGw8mE2KGMKCeCSPFeKKt7UwyIkluDScQUR204i9zWJM%2B%2BZk5EoJfvwYUu8ElGK-lBRAOyI7EH4tUcgWAqFViKRfEpD0YHJTodMvytToV8GFG-BJjjOkuKxegcazk0hBLERRa5GxUirAWA0NI0o7p5BCSADYQA)

#### Input code
```fsharp
let inline func
    (arg:
        'a when 'a: (member a: int) and 'a: (member b: int) and 'a: (member c: int) and 'a: (member d: int) and 'a: (member e: int))
    = 0
```

#### Formatted code

```fsharp
let inline func
    (arg:
        'a

                when 'a: (member a: int)
                and 'a: (member b: int)
                and 'a: (member c: int)
                and 'a: (member d: int)
                and 'a: (member e: int))
    =
    0

```
            

#### Reformatted code

```fsharp
let inline func
    (arg:
        'a

                when

                'a: (member a: int)
                and 'a: (member b: int)
                and 'a: (member c: int)
                and 'a: (member d: int)
                and 'a: (member e: int))
    =
    0

```

#### Reformatted again
```fsharp
let inline func
    (arg:
        'a

                when


                'a: (member a: int)
                and 'a: (member b: int)
                and 'a: (member c: int)
                and 'a: (member d: int)
                and 'a: (member e: int))
    =
    0

```
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [x] I would like a release if this problem is solved.

#### Options

Fantomas v6.1 branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.

I think:
https://github.com/fsprojects/fantomas/blob/f95faa9845031b1c49fd7d5ab5deb80dda33efe1/src/Fantomas.Core/CodePrinter.fs#L3065-L3071

can probably be simplified to:
```fsharp
    | Type.WithGlobalConstraints node ->
        genType node.Type +> genTypeConstraints node.TypeConstraints
        |> genNode node
```

`genTypeConstraints` already seems to deal with the multilineness of things.

Are you interested in submitting a PR?

**Comment by etareduction** [comment]
> Are you interested in submitting a PR?

I can look into it in a few hours, but I'm not familiar with the codebase.

**Comment by nojaf** [comment]
We have quite some documentation on the codebase at https://fsprojects.github.io/fantomas/docs/contributors/Index.html

I think in this case, you can follow the [pull request ground rules](https://fsprojects.github.io/fantomas/docs/contributors/Pull%20request%20ground%20rules.html), add a test in `src/Fantomas.Core.Tests/FunctionDefinitionTests.fs` and see if the suggestion works out.
Maybe it does and that is all there is to it.

**Comment by etareduction** [comment]
> If so you should be able to build the solution.

Just tried running `dotnet fsi build.fsx -p Init`. It runs successfully, but doesn't change anything. `dotnet --version` is `7.0.400-preview.23305.1`

**Comment by dawedawe** [comment]
Mmh, that's strange. The `dotnet restore` should take care of that iircc.

> > I'm guessing you don't have the right preview SDK on your machine. Can you run `dotnet --version` please? If that indeed is `7.0.400-preview.23272.51` or higher, did `dotnet fsi build.fsx -p Init` work for you? If so you should be able to build the solution.
> 
> I've installed the preview sdk according to instructions in the docs you've linked to me. The thing i missed is `dotnet fsi build.fsx -p Init`. It seems to be missing in the getting started, and only exists in the last chapter of contributors guide. I'll try to run it later today.

Mmh, that's strange. The `dotnet restore` should take care of that iircc.

**Comment by dawedawe** [comment]
> > If so you should be able to build the solution.
> 
> Just tried running `dotnet fsi build.fsx -p Init`. It runs successfully, but doesn't change anything. `dotnet --version` is `7.0.400-preview.23305.1`

What change did you expect? Did you do a normal build afterwards?
`dotnet fsi build.fsx`

**Comment by etareduction** [comment]
@dawedawe 
> What change did you expect? Did you do a normal build afterwards? `dotnet fsi build.fsx`

Yeah, i did. The change I'm expecting is that `dotnet test` and test runner in Rider start working. Currently they still spit out the same error I've mentioned above.

**Comment by dawedawe** [comment]
Okay, maybe let's start all over again. The following steps work for me:
```
mkdir fantomastest
cd .\fantomastest\
gh repo clone fsprojects/fantomas .
dotnet tool restore
dotnet restore
dotnet fsi .\build.fsx
```
After that, I'm also able to do a `dotnet test` in the root folder and the test support in Rider works.

**Comment by etareduction** [comment]
> After that, I'm also able to do a `dotnet test` in the root folder and the test support in Rider works.

Yeah, I've just figured out that running build script and then dotnet clean followed by another dotnet restore fixes the problem.

**Comment by etareduction** [comment]
@nojaf  When i was able to look into the output string more closely it became clear that suggested change fixes the problem quite well. I'll open up a PR with that.
