### ISSUE TITLE
[max_line_length] does not work

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/fantomas#2911]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBtAPAQQK4BdYB5AB0QDsA%2BAXQB0AnW8gWwVwBtExsSSBhWOQBmASwDmuegEN8IwQGlEATwBqU9rkQBnMAF4GTA%2BQgRO%2BMPW2xJ0RABUlZPWABKVm-cdcAFLUgBZEWh6WC1YIXwAOh5%2BQVEJaVlBAHo4YXFJGTlyAGVCSy1kgGtlNQ1tPwAaMD8AJgAGWoBmAFp61vqARj8ASiMjSErwKC1EfFlyMS1UMHRhiFATE0gAEnwvGcgRcnxB%2BeWVgDd1TRm5paX6oYvlgElyJB2ckQAvZGubsAAWfYhqfYAvh8Fr8oGsNmgtjs9jdVsdymdQRBOsCLgEpAAPAAy20QWIoYnwAAsYZ9Ol96qD-ksgftFmjwWRNhR4EQhDjyIg8kpOKSlnCTsg0OdPrVUfyAKIPNkc95IqDsISQKmA1H0-mMoVQABGsFg7D5B3hp2F8qa4ru5FG9HwADFtuoAHKIADu7FxhqW%2BHomhVNLVoNW6yZkN1%2Bs9YONWpFNy%2BFogkByJCktgAQoghLBLAAFKTSZhjRD0CMQb2%2Bm7Uky0pbqg7BrWQMMGi0ChGmz5gACs8agSZTiHTmcsWNgLqL0Cko3uh1gE6S5BLYDLiD9VYDsM1mybEdbJtm8oAbD3E8m0xms4gAKq8ceTxDT2dZQSLoTqUariDVky1hOb0N65tAyOQVEQ7AB2Y8%2BzPIdED4dhJy0AQrTLaB8hfN8VwrVU6SA%2BstwAndgLbfcOwADkg08B3PSx-EQZhtSLdD2HfLD-Rwjc8P-cMWyIvcYwuABOCj%2B0HC8BHYZ8e1fZjMIuStP3XBlOJ1AieKjUCySueUT37bAIiLARmGYKRF2XD8wC-EEOIhFTuKA9T2zJFFtKgqiYJyOign1ST5Wkli5OwmtcJsxtVPskDHJuToxRcyi9PwIsPOYLyJIXHszNYtd2KUkLtzUiKSLJc1Yt0kJcAeAARRB3WShLi3Sn1ZKWeSLMUjVlKhXZ8uI-ilnJY9-ExW4hDsIkKByIks3wAB1ER4GJRdKUyhTsvakLti68KevlTpu20waMWG0aKAlGSJqm2b5pJHsDyWgK2KC6yQygDbCIcwqoqPfahvSDFSCLGQswlDESAKLRskXUi7uawLv2C57OregrepMToIO%2BjE3Dgeh4EuhaewpczLLAH8wQ617ur4nbyIxrGs3gR1cHoos2VuBLmGmHtOiJtq6xC5gOFkd1OVtLNjPGIsHCZSnox2oTtLpnH-EFkRhcQUX6HFurFxgIk8xTOqAH0XTmhaedWvmEYpraqY7BoBsxbB6GkJQiHoHEtBm03rvlKHzcenKrehGWNJuWpnI7dEMSdl23Y9-BGeZ%2BhWfZzmdv9uGnobAX2CF3ENa1yWNhDyKLlqGLI5jqRXfdkRPeV3PVfzsWZG149oD16RUKLY3veVZbWot39yeDm3Zbt4rI4OspNFTbZ4G2MQ8Z9sjoZMFridJoN1tHjd3pRiBajjDHbXK1Dsjnh5F%2BXxdCYHzf4Yba29%2BR%2BVaj2qfMQq2B8AAcTGYGoNtDg0EDfHsft7682HrlMKL9tp2y%2BpHZ0bpcTpnwGOCgUtEBVVEOQEQ85sAPFoknNOHYMr3SygHNaCM8pj1DmXdGld3RiHIKfcg59BDPBYTISQ9hYD3EePgJ8aVfIYQzlZQODZaFwNtqKGmTC6rkCyIcPEggxDEIYvQHB2x8HZFIZ8PyTV16wwkdQqRsCGT7zfvLKeKtZRYikPReAUg4KhEXsgtWTF-IwwepnSR%2BE7IyPHp8JoWlI6AKLCIAsOx1CKEQCQARFB8D3FTNIdhK8DFiMgUPMmMDAmWNfh2JoEdPiQFTPBcgRRZRaCdtYB4zpPaIHgA3POnJAFgz0aZRq4iSaPwCYBIJ9ClhNArqU1MeZRKWAqnXYIUSHQJXgJePBggqrQHgokCGUkskUJWlQy22cVZq1SSmEo%2BBuS8hLh9C4TRJ6lJaU3TkxzoCnPOXKSOwRHFkHgP3HZg89nQKDptQZpdhnH0jnEkgB1E6aLZOUqQlTqmLk6PUNefwTG9Kzv0pG8CQkf1KR41B1FED3LVoZEgBBhHtOAZs%2BU5CfGUL8WYrFlyD5gCaIg0pET6BRKSeoU6yUtAZJuIYomwxqAfC2FoW04MZgioBEAA)

#### Code

```fsharp
[<AutoOpen>]
module AppConfigurationKeyValues =

    let resourceType = ResourceType ("Microsoft.AppConfiguration/configurationStores/keyValues", "2023-03-01")


```
            

#### Result

```fsharp
[<AutoOpen>]
module AppConfigurationKeyValues =

    let resourceType =
        ResourceType("Microsoft.AppConfiguration/configurationStores/keyValues", "2023-03-01")

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas v6.1 branch at 1/1/1990

```fsharp
    { config with
                MaxLineLength = 140 }
```

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by dawedawe** [comment]
Hey @xperiandri,
I think what you want to use here is
https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html#fsharp_max_value_binding_width
Could you check if that works for you? It does in the online tool.

**Comment by nojaf** [comment]
I'm going to close this one, as there is nothing actionable left.

**Comment by xperiandri** [comment]
Works, thanks
