### ISSUE TITLE
Shifted Quote

### ISSUE THREAD

**Issue by IgorErin** [fsprojects/fantomas#2921]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBXAdgJaz4AqiAzlhWHPlogB44C8AOgE5v4QQDaYAA4MqABQ6xBiDlgCeYABQBbShQCGAc0Rg2kAOKJ80wtAAiAVQA8AI1ix0AGjAB5YcXw276AHzfdASk5uXl5LAB8wADMCRXg1LDU0AyMOEwtPeydXLHcMn28%2BAF1-MABaPy58IJ4Q2pEscUlpOUUVCnUtHX1DY2gAJUQ4DnhLbNzCem8stxJLCawANgAWXwDq2trwqJiFOISkntT%2Bwdhh0ZmPeamXC7n6Zd8ikvL1jbfCSLA9tQA6ABlDBosAALMCWbxgAAMYBBhlebwRtGBgwA1l94mp4YiNltojxMPggaCXpVsWSwQABLHk7F4xQcNSExBoPqMrQARlMJQU1lwkUi0jQAGF0ABBDgM2SWAD63meFWCNKVEAUgUq1Q16q13E1Ou1VX1uoNepNxrNRupyogFIhhUgDnAUAo2ByhIoqDAfEdEFAG0gABI5FIPZB5vbvbwAwA3NToXDINBehGQh0IyAASXwSHoAGVCAAvZCpt5LCMQQoRgC%2BxZ9ZaggdkwbQofo4b9-pjcYTnrrEHZNdqkAAsmpGH8JogAYSQW23uyAEyQusVkLViO%2BwcNptQQzwZyRcdGHNyTCzkLR2Pxj1Jt7zgfngCiWf3h6LvYwkUgy6rA435633aQLY9hnpGHaXt2N4bAAzPekaZs6MgAGITLGAByiAAO7oBOoEhFgHDxt%2Bq6-nWAZBoBwHoHh9adleibvkscEQJAOaCGo0CIAAQogkSnIgohqAyKgMBwNEQARREbCuvBriEf5gRRIZUTRF5dte74AKzMVAbEcdxvH8X8sCYdI0BqM6mZRrA5k5CQ4kwoRiDEbJpHtkpzYqXBan0T2CILDprHsZxPF8RwiDmIIUgcOZln4NZtnuA5kSxs6LkQHJvAKSxAHKV4qngepDEIgA7IFekhYZ4UihZFBCiQVCEdAWCnMlqXOdJP7rmRuWefl3mFb5UG1AAHOVwUGWFiBDogSjWNIbXoGlnUkd17mNpR-U9XRkHvgAnON%2Bmhfx9XoPZOkpUtHW1DJGVuZuHlQF520QRpCLsim75BfpoqRKJ9VKEoagOZJ10hLdYCZbW63bkBW3tjtb1zv2X0VZN-E5rNJj2Od76XctN1dfJPWPXDIEDYjxVzneqMTb9omY0o2NnfgINOelkP3f%2BpPPQjr1Uxs7KwbTP0SAQ8CmIgOFM6JbNSYTq3EzDgFhhT-N%2BXOTFfSOjDppEpDIvgObAqcWAAOqEPAM46UuK2uWtD0bSGqsvUVGuC9p2ujnrBuGA%2BV3G6bFtW8CDkLLbCv20rjuwy7fNu8NITsgFXu6-gkSEIwrjSPEpwPowgjhe0SU6SNEfg0TWUk07zZx5ulPu7U7JlanAxDPAwfW4x5e8BDUNgNl9ak3X-4N4nvDsmNrcnMMaG4HN0j7umDBKO6Onshz-eD%2BRNdQEouDoDkOFGEhpxA1gomkE7asJ%2B%2B7IHV9benPAQ4H0fE6nxw5%2By4F0DAkJHFRLSkwpbGcm8uaKV3i2LABUx7vkXIFHW4pJTOA4OOKgndQ6lx7uWSu0MY4q1bDfIa8CUZpiQRKNQshUHoKwHPBeHAl4rzXnfcBDtuZQP3ofQgx9ECf2-tIK%2BwZiG7QRPOGmaZkFUJoYQKgr9uG8P4fEH%2BX0-4AOatIYBoDQ5sOjhw2ORDXYkLEcLcho4ABqEEuITHgBMDQmCHJl10VXZWztDHx2MbeLWZjGBIQIM1dw1isx2IcTpJYOCwB9wgTlYe7j67q3HhAecnsfGmFgFgAwWB86F1UO4UJ74nF2zuuwyBsNebxNvmIlOaYMLYQnDxLAplDBCMQJLDORA7L4FFFmGaDCWEIlBs4-B%2BjNrkyMaI28LdJE4Q0PgPx%2BAAkkDzLM%2BIuBwqkFgJmbMCROmLQJhXRWLiCF5TGR4iZGx5xT2maJfA8RCBRknCQDQvT5ocDaRMQgnT%2BlvHxmDXueCB7VzKfDCpniLkP3IW-Qgr4-hqDmnEEUsAKB2NqbwvZfzcGHOGaU0Z1ERFIxgp9NM2TjAqHoLGAA0ogRAggtmGCwJmLiDIFlYLxu1IZgLXF9VOaC85tRoJkLeJALi6BGQolfBQcUsBxYYSoIgF%2BULeHZKLsihqcsMWRIBdvXqT0QWjwSe%2BaCEihVcSEsdcKphZHQFSEzW5DB4DmCICQSW0BRUMl2RddlRTOYlJiZwxV9SGTQBRNgY8shTz4oFvy0xQr5HvyMEyjiIasBhojao4SUh4Bfm9VvIFhCYGRsbiEaC3ihVUppTrehrz9wirFRKhyH0IlRN9UPKB5T9WVLeNBFJQrUX1KqtNANRgAaCFwDs9wyrcm4wGezHN0TW3Ap5R2sF-LqlCpJTa%2BlsZ-ZMwoKyhEvzN6OkKMWUMFAkLIo9IeysQA)

#### Code

```fsharp
let unionTests context =
    [ ptestProperty (message "GenericDU<bool, Option<bool>>")
      <| fun (data: GenericDU<bool, Option<bool>>[]) ->

          testProperty (message "GenericRecord<Option<int>, Option<int64>>")
          <| fun (data: GenericRecord<Option<int>, Option<int64>>[]) ->
              if data.Length <> 0 then
                  check data
                  <| fun length ->
                      <@
                          fun (range: Range1D) (buffer: ClArray<_>) ->
                              ()





















                      @> ]
```
            

#### Result

```fsharp
let unionTests context =
    [ ptestProperty (message "GenericDU<bool, Option<bool>>")
      <| fun (data: GenericDU<bool, Option<bool>>[]) ->

          testProperty (message "GenericRecord<Option<int>, Option<int64>>")
          <| fun (data: GenericRecord<Option<int>, Option<int64>>[]) ->
              if data.Length <> 0 then
                  check data
                  <| fun length ->
                      <@ fun (range: Range1D) (buffer: ClArray<_>) -> ()





















                      @> ]

```
            
#### Problem description

Fantomas himself says that this result requires formatting

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by nojaf** [comment]
Hello, thank you for showing interest in this project.

The online tool actually formats the code twice and verifies the first formatted result is idempotent.
As it is not reporting such a problem, I'm not sure there is a problem here.

Two things might be happening:
- You are on an older version of Fantomas and the problem no longer occurs on the latest main.
- You didn't enter any settings that are required to draw out the problem.

Could you verify these things, please?
