### ISSUE TITLE
block comment between ^- and exponent in SynMeasure.Power is lost

### ISSUE THREAD

**Issue by dawedawe** [fsprojects/fantomas#2937]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAmAzAFgDwFsA9AWgAoAqMAIwEMAnMcgSnQD5IAacKAZ0QBd%2BASwB2Acx6owAbW4RQERVAAk-AJ4AHZGkij%2BnOYsjKAbjQA2AV20zDSgAxclSyAEkRSEfwDKQgF7ITs4Q2HZgALqGAL5B8mHG6lpSul4GwcZmVjaywRAAjLHOkACyNAAeADKiiBWI4vwAFmm5eej2YZFKMYYKRaqaNpB18ADyAGZVIoje6uaB8aYW1lI5ueiFLgCiHuOT87lQ5mOQHdGFvS79STpUsLDmzZeZy2irwZgbRu58dPwAYqILAA5RAAd3M1Uezn4dGspy65wWiUGt3uUIgGSW2TCIU%2BGO8Gho0EQACFEGNYHREAAFeg0fACRB0dGKGFw4KdRTdJQXIxXFF3B6fTFZFY4sAAVjxUAJRNJ5MpNVgoKZ0BofHcJlgauEsBELIgbMQ8K5iPS-OSqKFC2e2IOADZpZBZcSyRSqQBVDRaOhqjUiLU6oR6g1gMYWPgmiDcxS8jEWm6Clkil62A4AdidLvl7sQAGFzOqeHm9Tw2dB%2BJTQ%2BHzJGOWcekiBpak8LFqLXuKABxZwmuhVU4qIfBUJnViPG%2BsIxvm5EttFt21ig4ATl7crdipL5hD0prdecnOjZr6c8TC5tWOXLUc4udfcQAEExvwmSX8PgaKGjVGwDG4rOzbnta5pLp2Bx5AUd7ZpuVLeMOQhwDu%2Bp7hOv7-mAcYqGeUBWsm7apm8zitOuxLPq%2BdDwfgiH3Lu4o-lOpozqeQG4a2l4dmmLQfNBD6PnQsCWB4AAiiAQtRFHfrCk6Hg2PJNtcUB6PhYFccEeTYE6pRlK4YwACoNHU3gNJS-AAOpCPAjShu0jHHsxlw4Sk%2BiLle4EtFKd7abpBl1JstbTCZvwWVZTTSvatmydO8mAYpzkqW5anEY6XnlO4YxCGUIw%2BjQlZ0JsZQaFSPA8MGKHdpFShHn%2BJ6Oax8WuZxRFKHkmapWUABKiBwHQ8AhdZ0rYJVijVRhWEJPVymNYR4p5D27VdT18BApYI5MuMrivvgkjSnk6G1XyTn4JY5jCBCUx-JSn6CEyenNtNdotGud6LZS8DFCdZ3VJddDXZJTrQA0dIVkyAD6oKWdZ%2B0OYdk2pA917BG0WnlPxdA0GoIx0FUZb9WFFXQzFLFxVNHEzQc6BQQcJSo3Q6OY9jQhlita10BtW07bNhOxgpgzHadQjnYgP1-bd91k49SPrHeaMY1jOP8B9AtCyLuX-XegPAxR4OQ003MAcTgyk6BiXNYoWAo2UABqWIkqI8CiGIeOhl2w0QKNB3xk5xt9KpZsQOgmntX8QkVmVdseI7zuDW7ERyTzsVG-DEuI846CedT2nCbA-AAOICAVRWICVZXRwTdk1TDXv1XhCPuUjKXUyC4LVGS-AqnUd1aKJGUiEIuoiI%2BHhDqznMHAxUVMUTdVxbXKf12nbXU4%2BEJiCIIciGHeq%2BGvuWWFSemwO4nj8LlZXjgF%2BuYbz84gb7pviug83L6dTIiGfJhKuII%2BjnQPeiP3MqY9cj7hklVeOBsZ4CgvCbJqj9nqZ0%2BkIPYFR6RUHgDQAssBSriGbkLC%2BB5wHRQTobW%2BCU4EHEwLeamhcmRCAZF4CwABpRAiANDHzqPwdwJJ0ab3xgcUBV9xoJjYjA%2B%2BFDciYCprkSAJJCwiAANZ7B4PxQSHgQRlkQO9JBQtC7FVKqWKS7JJ72WnrDWe7FYHk0kdLamJJ6CwUQMJJm0A6D0MBK%2BeAHo%2B56lEtAQs6MB4ELASNCB19E7JH5l9KYPCiQKIEDMNQcxyHWPeDxRBytW7o2gPEnwsx9gyNcfSLQ8ATgVzGjfHQPsngP0oUHamLC2HaRZr-cYciaCKOUaGPI9hY4eyrthGuljxGpOcJgDOMi8GtwHIgJW0T8ywHwBoSwp8B56OLgY8q49pJCMqaIu%2BNSJHvEbjI2hbiGGn3MP5aiPB%2BEgLQuU7g4Qgi6B4H8UqUhBFRCAA)

#### Code

```fsharp
234<m^-(* bar *)2>
```
            

#### Result

```fsharp
234<m^-2>

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 2023-07-24T13:06:38Z - 0e07caba6301511d70a8187d5b6a1982d6c98638

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by nojaf** [comment]
Catching up on the `SynMeasure` stuff. Great work @dawedawe!

**Comment by dawedawe** [comment]
Thanks. Having @josh-degraw for the reviews and all the automation made for a smooth ride :)
