### ISSUE TITLE
[Feature request]Reset button in `try online`

### ISSUE THREAD

**Issue by IgorErin** [fsprojects/fantomas#2941]
The reset button in `fantomas try online` is often missing.

## Affidavit (please `submit!)`

Please tick this by placing a cross in the box:
* [x] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to Fantomas
* [ ] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Hi there, this would be more suitable to discuss in https://github.com/fsprojects/fantomas-tools as this is not actionable for this repository.

Feel free to open an issue if you are interested in contributing to the online tool.

**Comment by dawedawe** [comment]
@IgorErin Clicking on the Fantomas logo in the upper left corner might help you a bit.
