### ISSUE TITLE
Removes type annotation without brackets

### ISSUE THREAD

**Issue by artemiipatov** [fsprojects/fantomas#2942]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXM10CVF4BXaIgNQEN1jEBnAGl3QDEBLAJzqwEFoti1ANKIAno2YBlRHAB28PgOFi6aAMLoeHDpVEAeAOSUAfGABUYDVp362srKYtXtuvXYdgAvAB1ZECBxEpIhgAA4csGR0dLAcYAAiiABubGQA8rLoomCBdMToWAAyiLIA5lgAFsxpAGY1dNh0zOxcWCLiUjKw8u1NeFQ09JAM4FANWFh2pXSoYADaoxCg-v6QACRYoqHIaJDuw4ura0nUtLMLKysADCOXqwCS8iVYkmwAXsi3d2AALIcQAF1DgBfL5Lf5QDZbHZQfZgo4nQbnCEQACM8JWkAAspQAB6FOyIYplSoHb5gVEAJiuEKBK1Bh2Wl3Wm22s0gJXgtQJskQkk2mDJzOOpxhF2%2BlIxqwAovJuYShXdIOgapBaSD4UzMVC2bsAEawWDoRUI0XI8kAZilEEgjwaHCw7Fk1AAcogAO7oBXWsBYDi0dX0zUQlnQ9kGo0mm0ipFocV3H4%2ByCSUKUMgAIUQNViiAACpQdABbbCIDhR-x%2BgN3On%2BBkrLVHVkwyAR41S9aIs5xlFgACsSZTacQmezgUKsHdpeglAajySkUok265YglcQgdrwaVOubrfLHbN3fJADYB6mM1mcwBVULbDjT2eyefTpeyFdgGrUBobiB1-wN6Mm3DQ02xDGMu3mHsAHYzyHEccw0Gc6DUbpuH9fhYnfT90G-asNUZMCgP1ED93AsUewADlgi9R0QLFEELPVSywr91zwoMCO3IioD3dsyPNb4AE5qOHS9AhQ9Blx9bDcMuGtfy3YVuJbEi%2BM7cjyVRG4e2Tc9EB4GosFLFDC0LSh3zXH8wD-cEuLDYjIzUw9IM09EdMHGic2kQtUiNKSexkti5Pw%2BtCPsnjVLA9SBLuKkRIMoyOG83zJLfH1LPYzdOKU8KVMcqLnPjS5UStdy9K0WBiHkRIvR8xKLP9IKVnk6zFO1ZS4QK2MXO%2BVFEx0nFcXuGoABUKhKSQKliLAAHU2HgUkfRpTKFOy9rcs67doqPXr%2BwGvFhrGkppRwvkpodOaFoqd9j2W4KONCuzdVhexSO2nrYtPfahtkGo2FxNI70XWJpVxcJ6DoNh-PJCi7uakL-zC569lepzuqKlZURg77CDgDh4Euxaex%2BOH-BamywAAyEOtRrqIIx-xUSonGunxl1iEY0tanuIzCxmH1USsimqdDZHC3ySYvV5FhYjMiZSxGsM0fpntUWEnTcdieAsQltgpcQGWODl%2Bqk2gCoCzTRKAH13Xm0khbaxsNtprbCp7akk0G6xdDSDgCW4Qnrp9WGHbWp3kc24V3oZiBKTc8lsTxb3RF9-2sHZzmOG53n%2BdV0PHpysXdf1w3jYVpW6Y0iVJR05PU7YbgdYKPXCVLxcTZ0s2Lf4Usbbt6788Rp7m0j7Vo-d0qE8GgZaHTOx4CmQP3xDlbWrDwDnawN63fJSl%2BqnvEWCq-godkOf5EX-v3xJwfbMLkeXajneJT2g-cXiWAsAAcWwUHweiU%2BS9g6k0BAjO%2B61ka8UrjFS4lIvoJzdJ6QkmYsCThKIrbYiQ-qyDYK%2BHg8h6KZ1zuSDK90soFwgbuSKrt0bu2xgnHgXpSiyCPrIE%2B3RXjMMXMQQII1YCPCQPYRcp8WKnVvpTJGVD8o0JVrvZmDCCilmdJMJIRJuilEIUxDgWC7C4NPsQ74gVxEix3MBaRT9aG73VlPXWPIiSUEYvASgGhYCQzKIg-WojZLwwekPe%2BZjQIyKrncC02kE5-1LGwYsQj0AiEQKEARzxHjph0GwoOAVWLGMkQE7eljvgWnjt8SA6Z0CUFkAAazsXQCqVV4Bum4EQJuktCR-1yJDVCDUqxkNWhQ8OUjAkWNkfkmuCd0wFngoEeIDdoAcCiXYRcRArw4O6IkPAFtXxeKamTMBEjh7snFs3fWKS0zlOwPyUQgplbBMuBaSeRSmkt15Mc6ApyXgCk%2BJ3Is2x4BqlXsLbJuxR6mjySE-eRS4mhEGhnLRtQSllMqYSAxsUrggLAOTR2G9IHUMGdclYFpX5FI8cgsSdFi6EhMqEYgWBhHdFaRDER6VGpZL2Q5AZY9n4hPgUUiJszonUvQCdHydB0nkiMX80YAIvh7DoCwSGswjHAiAA)

#### Code

```fsharp
let clReducedValues, clFirstActualKeys, clSecondActualKeys: ClArray<'a> * ClArray<int> * ClArray<int> =
    reduce processor DeviceOnly resultLength clOffsets clFirstKeys clSecondKeys clValues
```
            

#### Result

```fsharp
let clReducedValues, clFirstActualKeys, clSecondActualKeys =
    reduce processor DeviceOnly resultLength clOffsets clFirstKeys clSecondKeys clValues

```
            
#### Problem description

Fantomas removes type annotation without brackets. But when brackets are placed around names, annotations are not removed.

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by nojaf** [comment]
Hello, thank you for your interest in this project!
Tuple bindings are covered a bit differently due to historical reasons. Which is why the return type is missing.

I believe the problem is centered around:
https://github.com/fsprojects/fantomas/blob/0ce91b778f216c2d7fa8286d1aa4aa5dbf835bcc/src/Fantomas.Core/CodePrinter.fs#L2866-L2867

There we could do something like:
```fsharp
let genDestructedTuples =
    expressionFitsOnRestOfLine (genPat pat) (sepOpenT +> genPat pat +> sepCloseT)
    +> optSingle
        (fun (rt: BindingReturnInfoNode) ->
            genSingleTextNode rt.Colon
            +> sepSpace
            +> atCurrentColumnIndent (genType rt.Type))
        b.ReturnType
```

to print the return type when it is present.

I'm not sure how well this exact fix would play when the tuple is multiline. 
Something like
```fsharp
let a, //
    b, //
    c 
         : int * int * int = 1,2,3
```
Might be a corner case.

Are you interested in submitting a PR for this one?
