### ISSUE TITLE
Opening parens make unstable/incorrect indentation for an Enum wrapping a record

### ISSUE THREAD

**Issue by pbiggar** [fsprojects/fantomas#2943]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAKdBhWBbARrGMGIgIxgC8YAOpALICGA1gJYB2A5mAC4AWrAM5gANrC5hBRVjzCdYiYeLCMw7RAHdRHRGs3b1erSJ1GDu3Cw7cZo8dylhb8xWGWr1x05-N0wAXwBKQJp2SAAacChBRB4ea0FUMABtKIhQCEyoABIeAE8AB2Q0SA4eCLTMyGyAN0YRAFdilMqsgAZIrKzIAEl2JHYeAGVWAC9kTq6IACZWsABdSv9J9Lnq-KKk0sGKqeq6xubUqYgyFa6GRgAPABkdG8Qufl2Tsmm2ucWs5cqMi9zCs1II94AB5ABmd3UQ3yIgma1q9SaSWOJ2m526AFF%2BhCofCTlARODIJ8luc-t0AZsSoRYCIXpSDsi0KipgBmDFVPoxABOPAAYhx6gA5TQmdQMro8HlNUnfckIjZA2n0zn7JFHOYQAAsnIgkCGBUY0EQACFEODYDzEAAFRg8xi4WKIHmSrLS2VTL6ZH5ZClVKnK2B0t05JmagkAVj1UENxrNFqtiBusA0LugjBifRqsAz8XEoYgHsQcp9Cr2ga2KtD6sOKK1YAAbDGDUaTebLdaAKoFIo8jNZ9g5vOsAsx8H1GKliC%2BzL%2B-WVmnB1UI8P1gkAdhbcfbietWBEmcEOHYgg90B4VsLYAnIinXrJv0VgKry5riLrLIbAA5t22E52iD0IgBAutet73l03ozuW-xKq%2BIZqh%2BzItASACcf7xh2SY4GIYTjpOJYPvKT4VvBS6IauGrrq8HQNq28YAILgjwLo4LgljXsW04BLBlLkVA1ZIWuX4EmQZz0TuAFJkMIGsHAeHgYRPGzqsZEvhRK4ViJqGvOikn-sxrE8rJuDyXSY4NtxxFlqRcEaYJb7CdRomvByBlMTysANP0AAiiAmGZxlcTKRFQY%2BfrPtSUBlO%2BOmsl0ZC6vRTBXD04IACp8I8Qx8FaPAAOqsPAzwxh8NkwXZ-EOds5TOZ%2BulTGQ0Ypdc6VZY8mJ3oguX5UVJV8NejbleFJGRep0W1XFLmNYlzatWl7DgqwVygn2jCXjymJXAU1qCIIo74T%2BI1ZNBvFVQGAlTfVKEJVkZBbgtABKiBwDy8D9aVDbaidmRnapxBRUCsU3RGry-s9r1WvAwoNKBPIQj0rG4IkMZkCpfGXTVuANCI8Tiog-JWpYcQuhlL6gzRTUYfRL1vfA9C4-jOhEzyJPBS20B8PaxrGQA%2BhoxXPBjF0LldINUQ1d2ZO8LapYxPIOnkoI8ncZ6fYNMbfr9ED-ZjYs1RL2kzdLMwSQSlxXArSsq2rPCw-DiPI6jDboxV53jfZk043jrAE6z7NkxTku3Q20z6Rb1uMMrqtCDwjO%2B-7xMbRz9FczzF4ugLQuDSLnvVZNRv-PFYfuRbqUAGoaqaHDwNYGvXtredzkDWxF4yJth8l5fXPyPkXodNf9PXOfXj9zdqV7wM7JTrlTNMLU91cvmwDwADisTbbtigHeIDdazrCwRS3E1BpRxtS2H80W6KGgE%2BaPBpo85NFP5y3sDIh2Mf0wHwy7BLWVGrZfOWNJpCRDmDeej1I4mE4OwPu7AB7iBGHAjaDRrQZVgH0AYPANqHSUt1CegNT4IS0sXTuBJpgQxgcZdgeCajJnsL-fALo34cE-uIf%2BJwIJhVOsfSeBcz5kI7pfShNNy5M1YHiG4jp8DwEYAeWAB0uC3wJgQyCfCxonynqQ6aoiThsjohbLeLpWBOkGPUAA0ogRABRsGPB4H0U0DpEGawbDwoh84chXXARfUOBI2TmxOJAU0h52DMDxIIBW3l%2BiijPIgBmkiCZbz2rvU8IVPRAMqiAg2YCnIQKpl0NkEdgmmntNha0vkhDQB5GYoUrF4Bdg-uIfy0BDwOnzEdAkHj3YAy8esbGSSdDOONMwWIMI8hwj0f4gxZdgkJ2ZuoEZ0AxnDFhPiYJNTHRFHgCSXp%2BtvGGxngUueRTu7BOsbY1KDsWEI3BKExg4TInXjIG0Q%2BetRaHLyefch%2Bj2SL2Cao4Ze4gJDPUOxAoDRcGdJSTvfBMZAGaOAdowRujZ6zSyGya%2BwSTG1PMbgkQXUzKCDcd05SvSojzEmKUQQ-IDpJA8f4IAA)

#### Code

```fsharp
((Combo { e1 = "Making this long so it goes on a new line new line new line new line making it long so it goes on a new line new line" }))

```
            

#### Result

```fsharp
((Combo

  { e1 =
      "Making this long so it goes on a new line new line new line new line making it long so it goes on a new line new line" }))

```

#### Expected Result

```fsharp
((Combo
    { e1 =
        "Making this long so it goes on a new line new line new line new line making it long so it goes on a new line new line" }))
```
            
#### Problem description

AFAICT, this only happens when we have 2 parens around this, which happened in my original example because I was piping the result.

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [x] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 1/1/1990

```fsharp
    { config with
                IndentSize = 2 }
```

**Comment by nojaf** [comment]
Hi Paul, This is an interesting case. Thanks for reporting it!

My first impression is that the parentheses turn the application into a sequential expression.
Something where `((a b))` becomes

```fsharp
((a
  b))
```

Where `b` is no longer applied to `a` but the two are indidual expressions in a sequence.
I'm able to replicate this with indent = 4 and 4 parentheses.
The additional newline is introduced because the `b` is multiline and that follows the newline heuristic.

I'm not sure what the best way would be to solve this one. Changing this behaviour will for sure break something else.

**Comment by pbiggar** [comment]
I'm not sure I follow. Are you saying that `((a b))` is semantically the same as

```
a
b
```

That seems weird to me but it could be the case.

**Comment by pbiggar** [comment]
Oh right, that's what I thought. I got confused that changing the behaviour will break something else - what are you thinking of there?

**Comment by nojaf** [comment]
Well, this is tricky as there a multiple places where we deal with parentheses.
But right now we do:

```fsharp
(a
    b)
```

Where `b` is indented from the point of view of the `(`, following the normal flow.
`b` will be placed at one `indent_size` unit.

I initially was thinking of maybe touching this and having `b` indent from `a` offset instead.
This would of course mean one `indent_size` + whatever offset `a` currently has.
The trade-off is that `b` is put on at column which won't be a multitude of the selected `indent_size`.
This upsets a lot of people of course.

Now, we might want to have a sanity check on the formatting of the application.
If we could assert that the arguments are at least one space further we could add an additional indent if that is not the case. The downside here is that applications are also covered in a lot of places.
Meaning, that we might be able to fix the problem at hand but it might surface again in a slightly different code sample.

I took a stab at this idea at https://github.com/fsprojects/fantomas/pull/2946
I'll probably consult @dawedawe and others next week on this one as well.
