### ISSUE TITLE
Backticks in optional parameter gets removed

### ISSUE THREAD

**Issue by jindraivanek** [fsprojects/fantomas#2954]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAwgBQCUYAvADoBOFAdhBAM7oCG6AltGALaLcBGiKmABmsWIQD8AA2lZcs0mTCz5iWdToNtYTbUgAacFEaJ0HWgHNGqMAG1jEUDqgASNbcjta6Q44aQrgBuLAA2AK7IaA4uEAAMRrFQAJK0SD4AyuwAXsiJsQAs-hAAuv4AvvlOxW4eaF4%2Bfi6BIRFR9jUQAIxVOpAAsiwAHgAy3ogjiFboABZNsV0ATHE1ZdqV-s597jjtkFPwAPIiY7SIGViheTUtYZG2MbGLvdqQAKJpx6fXSZChIpBVhVeltXjtcJ5%2BOJQvMwa17tFOmAAMwvAKpUxUdAAMW8YQAcogAO6hcawnToKiRIHrEE3cF7KGwGFo25tB5IgpoiCQDLYFjQRAAIUQYioiAACiwqCxeOghOTtJTqS41gwNtpQQEGZDoYq3PD2o8XABWblQPkC4Wi2DikawIlCaAsUypIKwZ0cWD6c3KxA09V05o6%2BpMln0w0cpIANnNvP5gpFYsQAFVsLgqM7XbR3Z72N79RARGFTAGIBqGFqeSGoGH9WyER0kgB2OOWxM28X4UIuxj4b3MKnQdC2wuiEv%2B1XAzb0uq1vWs4J3I1IgAcbYT1uT-T4gioY%2BLoVLU9pM%2BDc8gdcXkcRSQAnBurUnbYh%2B6EC%2BbD8edGry0HtheV4RsuUYLAkSLxlaACCIjylQ-bcNwLBjn6ZZgBW1TnrsurMvWS7sreCw9BB7Zbi%2BGR8JwzIfkiX6Tj%2B06arO2GhguwEEU2CzPCRm4wXBFHcFR74%2BkiqEnoGZ4ASx864deIGES4XSojx0FULA4RpAAIogpKCXBKFUvR2i-uh-5ghe3i%2BHJHHGjoXRchBgxDMkIgACozFMGQzLa6AAOrsPAsxjis4l-pJ5nSQ0VnsY2tnaF0ZqOcMLnuVMbxHuc3lYv5gVzOa0YhQxp5MVhEL1JZeE3pximxklzm0CI7BDIcGZsLabxDNg4qMIw%2BYiUkq6FcZjGVsxZVQBV1mxUiXStnVABKiBwFQ8A5UF5oFENDAmRhYBVrUkWTTFK5JF064LUttrwPi4QCEIxzJPK3A2OaXRobt%2B2BBe3DhKEHCkmc2K2kh5hCK52FTSdCwPhBi3LfA-S-f94xA1QIP6XG0AzNKApwQA%2BkSAVBe9ZnahZjSQ6BLjLHGTlQVQMqYIcVBjMwa15WuW2lCNmFSeNUWVfJ1U6IsxG-HTDMsEzLPsMwN13VQD1PS9M0k%2BFZORT9f3sADiCo%2BjYMQ8dVMi9xvz04zzOs%2BgiPa7r%2BtsBjEFYzjw5CATRNzGrJV83sR3BlVcUMIsyni8MABqy5Ct48DeJY7NjoN3ujaVfsU8bCkiw5YdDNiGnDn10dpHHCcbVzYA7aT1bk9FAdC0HECLIlOeabA6AAOJmB1XWID1fWl5zye8xF-NAXXNlIostW-ISJLjCK6COlM4O4NpjW0OwXq0FBaQ7grKtJGJRUST7I%2BMmx4-TUkixzebpKWLQee0AX3pZA-bDhOKrmwKk6SsFvB4JxDz2mNc%2BskM7C20Isc6d84K0DYOwIIExvSWD3nuNe3hN59QPrEOiwDPo1kvBfbYgdJ4w3Fkjdg3wRiyn4PAFg3ZYC9SsLPXWgCMr4NAThcMl8oYuGROBX43chDsF4D4MIABpRAiBsC-ymOgVIQoZTPw5kkPBoVTLq2rpFMeJD65ImRGLWIkAhQ9loAAa2%2BIwem6k0iEmYIgBGlDdbd26r1AcBkVTHzCqfDWo9iFwn0UkZEZtjFCmlM%2BcUmlZbQCoKIvE8p4Apg3t6bS0AewygAZ%2BIBGiPpcPqFrZGZwlECnMWYC4mAriCwnsE0OxjbZFOFDKaAZT0AVKqZjGU3BcDwEBLkquB1%2Bb%2Bz0TU2IyJs7GKkTIpy8s9zHFMSwCxVixxdDiOXSuWjBlgJ4SMq%2BYzm7GNYfPTsiAGk63GAhbA4R-59Vcb3dx-VYhH2GsVFOvtuHVL2fw6exjhFxLEawUI6VBKMFUbgnJ3j0LGBKPkLwjBsS9VsHg8oQA)

#### Code

```fsharp
type C() =
    static member foo(?``type``) = ``type``
        

```
            

#### Result

```fsharp
type C() =
    static member foo(?type) = ``type``

```
            
#### Problem description
Backticks removed in `?type` - incorrect code.

Probably related to #2731.

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 2023-08-31T06:37:49Z - 369faf81362e7ddb3fce3bd4505216055af35347

Default Fantomas configuration

**Comment by nojaf** [comment]
Hi there,

We don't process `SynPat.OptionalVal` correctly in 
https://github.com/fsprojects/fantomas/blob/bbecd22a6bffd54ea662887366a1b074df5e8c44/src/Fantomas.Core/ASTTransformer.fs#L1633

It should be more something like:
```fsharp
let identNode = mkIdent ident
SingleTextNode($"?{identNode.Text}", patternRange) |> Pattern.OptionalVal
```

Are you interested in submitting a PR?

**Comment by jindraivanek** [comment]
> Are you interested in submitting a PR?

Yes, it looks simple enough :)
