### ISSUE TITLE
Wrong formatting in this line At["serviceType"; "case"]

### ISSUE THREAD

**Issue by RicoSaupeBosch** [fsprojects/fantomas#2955]
fantomas removes the ; and breaks the code of the decoder.

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAbRAXMS5LQBFF9EAnAHgFkBLAczIEMsbYA7AZXIDcbpEAfGAC8AHTKi2EadOKkAdLABGAKxI4AFADMArlK01E6eAGcwAWgHjJM29OBguZXvwCS8EWANHT8gEqIAI46NGSI8PIAYobGYKKQJjx8iO7xjkluEXgIiNZSdgVOLogAKgCeAA6IInkFdV4xvgHBoeHyAIJYANrxic7J5VXxANxxMIyJ8QC6cjnyJlhkNGx0tfV2AD5CWmSwALYci8t0FEUDlYJr6zJbYADyFSzs8nTYV9cAcox71cINPiZ-EEQmEIp0epA2N9cpAZiQ5gslit3usiuRPN5jIDmiC2uDejxyNNZkh5kdkRJ8tcwFRGAAPVxsBaMNj8Mx-TFNYGtMHdeJ7emM5msxAmYnw0nLLAo%2BrtbiMGjoRhKTBCrAstkYxqAh5PKHoDp8yAChlM9UisWwkmIeRSmV1droGjcUqwADWiCkHO1QJaoMNEMYTpdJXdnvFCngzGwNB%2Bdy0WkSOAAvgBKSAAGnAUCTLBWJlQYC62YgoDskAAJFgLoXIFLMyXpJX5egdMg0MW6gAGLN1SCMpBsLAcGgAL2QvYKABZGxApo3k5PS7OoFWa2g60OG%2BWKy224XOwUAIxL2yQWl0gAyy0Ql89dCwAAtt8eAExdlfzmSLxtls9rqpa09eB42vNhEEOMpMBfGRmyDfcOxXCBX1PWCAFE2BArQwInJCMC0SBPwXU8-1ggD2ygJRYFgdAYKbXd4Iow87AAZlQpshXILBon1D5EAAdydcC6JkRY2yI78SJXStq0AjcqJokTVz3Ji8KndiIEgDgKkYfgACFEC0WAwgABUYJgfiwcglIgMTEAk6QfxkUj6NkijIAU2j2Lg1tVLqABWDSoG03TEAMoywkvWB%2BPIaAJhSNhuFgOK9RssA7IciAnPsaTyNrTylJ8hCizwgA2IKtJ0-TDOMxAAFUKiqMg4sSRkkpS1g2DSrQg0STKwGy5cdzc-LqK83KVIPPCAHYKpC6qIsQABhJUTBMJb2ERHRoCwYzut6%2By7C-RypOG9dKLGwqGN8qa6gADjmqqwpqsIqEQPYlGsoKevQPqjuI39cpG%2BTLu867iuY2wAE5HtC8Lao29B2H237DtsY6stO-9gYuxSwcmxC6iPHs8Mq0L2i0KyyA2vYBTSjL-skwGzrk3Hxp3AmSqJk9Sfm57Fq4PY%2BBo5HvoO-rBrAFzNLykG8YmxjbrfWH%2BApqnBeFpGuqChn0YB5ygfOjzQYVm7CePNjeae9pdj0eBiCdIWqfpshxMZk7mexo363xxXzbsI91NJi9XC0EpH09DhH2MrAAHUaHgJ80o-d3Mc9sicc3LArs5yGZCPQLg8FMOI7YNDUajmP48T58gtKlO9aZg2Wfcn3TYhvCj3KovTQMOkHnIZhjLQukKjCNbOrSu6G5kDGBqxjPva3X2za549Zp7gI4DIeBq6ToKpxn6Q58l6XV0ztuOb9teA4ezf4R3j4dA%2B8h41cKy9gLIKjwlhfXKNvYOh0AsCEogSIxkBRYCpoMXCV9V552kEeGGpMt7GXgFQIBICbzgLIJA52FVoCPnMrpKmAB9fiCck6-3Tv-VmWcc7XwQchEmfYLw2yYGUO4ZBrwLD3rXPC09qHNy9nQy%2B-5c54VfDzVh9J2GME4dwmgCwn4vzIG-D%2BX9O5CJyi3WsgDgGKmwRA5g0Cawrw7nUV8KFSZyIUTwrAGCDGgJwXgr6pNCHEJ2uQchlDnzaKGiI1uy925%2BQKK%2BS2Mi6QADVGJ6WWPAY4fCp5HznPrHRgTaxiLIhIyxQdImRD0DtTqcTMKJN8WlQ%2B-ipaG1EcEuBFiwmF0iYQWAWAADi2AR5j1FCYTqSSgqCNTvPGhMtM4FXMaEuwr5u59j4oJG8BksAxU9DA4gBg2A0D1O0TCb1VGaLqLrWeaSAmLzoeMkJSspkbz7I6egbACmsj1COOgUIsA6DCKGAcnp1SpTFqjKpZ8ZJG3OfUyZthXx3xucA8grznS3nYHQXZn0yBrOWJszq%2ByCg-T%2Bo3D2wjTnuRBeIxhkjkGsMwTQHCl5vhKCjCtWAvSVhzNASjHFRym7pIJaNeWoLLm2BYiwgokAunkFjN8oMABpRAiAKhfKHIyPSTBWT8LqNitG7K8WctoYSk2vL-b8ukUKvSSo2BuhwiYG2sA7Z8QWOERxWDwJdPHr0zaLs3a4rTvi7V3L2bEvgXhFi1i%2Bx6XMvDMIhAlHQCWELV54Q6obPYHIJUTBfl4TVQCmp7l9EOrCkwaAHphzVmghMvlMgWIRKFfawx4FFW6QLZBYt7iLJVHgIRIZp9M2ZLqX6hprE8lCqlTKi8KjkXxmNSyM1N5MUBy7CksAJ8-6jOBbqntYKy1NKFcyhZL1EBVtATTCoOgfmdSdT0yeOtXbquPsc6pui5a%2BuySSuoLEZlCpFdG8V6By5CxMCqrF4t23ZimJOOsJhIi9MLOm5MQA)

#### Code

```fsharp
let decode: Decoder<MigrationService> =
        Decode.object (fun fields ->
            { ServiceId = fields.Required.Field "serviceId" ServiceId.decode
              ServiceType =
                fields.Required.At["serviceType"; "case"]Decode.string
                |> fromString<ServiceType>
                |> Option.get
              Name = fields.Required.At["name"]Decode.string
              Server = fields.Required.At["server"]Decode.string
              MaxInstances = fields.Required.At["maxInstances"]Decode.int
              AvailableInstances = fields.Optional.At["maxInstances"]Decode.int
              AliveToken = fields.Required.At["aliveToken"]Decode.datetimeOffset })
```
            

#### Result

```fsharp
let decode: Decoder<MigrationService> =
    Decode.object (fun fields ->
        { ServiceId = fields.Required.Field "serviceId" ServiceId.decode
          ServiceType =
            fields.Required.At["serviceType" "case"]Decode.string
            |> fromString<ServiceType>
            |> Option.get
          Name = fields.Required.At["name"]Decode.string
          Server = fields.Required.At["server"]Decode.string
          MaxInstances = fields.Required.At["maxInstances"]Decode.int
          AvailableInstances = fields.Optional.At["maxInstances"]Decode.int
          AliveToken = fields.Required.At["aliveToken"]Decode.datetimeOffset })

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 2023-08-31T06:37:49Z - 369faf81362e7ddb3fce3bd4505216055af35347

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by nojaf** [comment]
Hi there, this looks a lot like https://fsprojects.github.io/fantomas/docs/end-users/FAQ.html#Why-does-Fantomas-format-my-lists-strangely-when-I-pass-them-as-arguments

`fields.Required.At["serviceType"; "case"]Decode.string` needs spaces in order not to be confused with the new indexer syntax. `fields.Required.At ["serviceType"; "case"] Decode.string` formats correctly

**Comment by RicoSaupeBosch** [comment]
@nojaf  your are right, with that it formats correctly and its even adding spaces inside the brackets.  Then maybe fantomas could check for that and already format this correctly. Currently without any spaces after the At its not doing anything.

like that line

```fields.Required.At["maxInstances"]Decode.int ```

to that 

```fields.Required.At [ "maxInstances" ] Decode.int```

![image](https://github.com/fsprojects/fantomas/assets/83805528/e8746d64-c5a5-4841-abf1-7e011421d7d1)

**Comment by nojaf** [comment]
Bad input will lead to a bad format result, this has always been the case for Fantomas.
I'm actually surprised you are not getting warning `FS3365` for `fields.Required.At`.

![image](https://github.com/fsprojects/fantomas/assets/2621499/1ddc3e3e-5a16-4101-8890-832f2c8efc42)

I don't think there is really anything actionable on Fantomas' side. 
I'll open an issue at the compiler for the missing warning. Thanks for understanding.
