### ISSUE TITLE
VS2022: "fsharp_multiline_bracket_style = stroustrup" Not working

### ISSUE THREAD

**Issue by YkTru** [fsprojects/fantomas#2983]
1- initial:
![2023-11-14_031735](https://github.com/fsprojects/fantomas/assets/125092692/55451e9f-0334-4bca-8de5-40547ab49170)

2- settings tweaking: Working and exactly what I want, I then copied the settings: 
![2023-11-14_032250](https://github.com/fsprojects/fantomas/assets/125092692/ee339ad6-c614-4b28-81f6-baf915822f89)

3- editorconfig + build: 
![2023-11-14_032537](https://github.com/fsprojects/fantomas/assets/125092692/e8248970-55e6-46fa-999a-5f29cf93df00)

4- All working but stroupstrup: Anyone knows why? 
![2023-11-14_032547](https://github.com/fsprojects/fantomas/assets/125092692/68a28570-2391-447b-9f7b-7a327d562d5f)

5- Profound sadness

Thank you

**Comment by nojaf** [comment]
What version are you running?

**Comment by YkTru** [comment]
Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.6.5

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <TargetFramework>net7.0-windows7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include=".editorconfig" />
    <Compile Include="Program.fs" />
  
  <ItemGroup>
    <PackageReference Include="Elmish.WPF" Version="3.5.8" />
  </ItemGroup>

</Project>
```

![2023-11-14_042623](https://github.com/fsprojects/fantomas/assets/125092692/36c12f3d-628b-4c35-b605-40c8dc4b0214)

Otherwise should I install any of these nuget, and/or uninstall the extension? I get errors when I try to install the first one:
![2023-11-14_042753](https://github.com/fsprojects/fantomas/assets/125092692/8deadf2a-f69e-4f44-b93e-5d70e4b3f067)

**Comment by nojaf** [comment]
I believe you need the extension and a local install of the tool.
Please close VS, install the tool, run `dotnet fantomas --version` to verify it is installed properly, restart VS.

**Comment by YkTru** [comment]
```
dotnet tool install fantomas

You can invoke the tool from this directory using the following commands: 'dotnet tool run fantomas' or 'dotnet fantomas'.
Tool 'fantomas' (version '6.2.3') was successfully installed. Entry is added to the manifest file C:\Users\YT\.config\dotnet-tools.json.
```

```
C:\Users\YT>dotnet fantomas --version
Fantomas v6.2.3+5a8458e7efaf4085a21e0123776ac89b51764c9e
```

- I installed the most recent VS2022 update
- I disabled all extensions
- Installed this Extension: https://marketplace.visualstudio.com/items?itemName=asti.fantomas-vs22

After "format document" still:
```
type State =
    { ClickCount: int
      Message: string }

let init () =
    { ClickCount = 0
      Message = "Hello Bitch" }
```

Am I the only one?

**Comment by YkTru** [comment]
Though when I write this in VS2022 DevPowerShell:
```
dotnet tool install fantomas 

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-fantomas does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

And if I try to install from the VS Powershell:
```
D:\Projects\Elmish\Demo1> dotnet new tool-manifest

The template "Dotnet local tool manifest file" was created successfully.

--

D:\Projects\Elmish\Demo1> dotnet install fantomas

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-install does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

```

I'm honestly clueless

**Comment by YkTru** [comment]
I had a global version installed... that was the problem. Uninstalled, then installed from the VS22PS using the local command

Thank you for your time

**Comment by YkTru** [comment]
I had a global version installed... that was the problem. Uninstalled, then installed from the VS22PS using the local install

Thank you for your time

**Comment by nojaf** [comment]
Yes, the `stroustup` value only works from version 6 on.
