### ISSUE TITLE
\n in single-quoted string literals gets turned into newline

### ISSUE THREAD

**Issue by piaste** [fsprojects/fantomas#299]
```
      |> Array.fold (fun s t -> sprintf "%s\n - %s" s t) ""
```

became

```
      |> Array.fold (fun s t -> 
           sprintf "%s
 - %s" s t) ""
```

which causes a syntax error.

**Comment by nojaf** [comment]
Could not reproduce anymore [online](http://ratatosk.dynu.net/fantomas/#?code=NoHxF0FgCgQPgAQEEBOKCGBPAdAMwPYA2AJggBS4CuAdggM4IAuCAtInQA4oCW1juCAEQBSOgB1aLBKMH0mASiGCgA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA).

Please re-open if still an issue.
