### ISSUE TITLE
Unable to format Fable line (cannot determine if Expr Paren Fantomas.Core.SyntaxOak+ExprParenNode is uppercase or lowercase)

### ISSUE THREAD

**Issue by cr3wdayt5p** [fsprojects/fantomas#2998]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview)

#### Code
```fsharp
let statusBarHeight = (window?getComputedStyle document.documentElement)?getPropertyValue "--statusBarHeight"
```
            
#### Problem description

This valid line of Fable code throws:
```
System.Exception: cannot determine if Expr Paren Fantomas.Core.SyntaxOak+ExprParenNode is uppercase or lowercase
```

The issue is present in both `6.2.3` and `6.3.0-alpha-003`.

#### Workaround
```fsharp
let statusBarHeight =
    let docStyle = (window?getComputedStyle document.documentElement)
    docStyle?getPropertyValue "--statusBarHeight"
```
This minor refactor is no problem for Fantomas.

**Comment by dawedawe** [comment]
Hey @cr3wdayt5p ,
thanks for raising the issue.
If you want to work on this yourself, I think a good starting poing is [here](https://github.com/fsprojects/fantomas/blob/7e7a90ac7e7a6f19821c31b6e10ac9316e168310/src/Fantomas.Core/CodePrinter.fs#L33-L60)

**Comment by josh-degraw** [comment]
Looks like the function that @dawedawe mentioned doesn't seem to explicitly know how to handle the `)?`. Do we not include dynamic expressions in chains?
