### ISSUE TITLE
Triple-quoted string literals become single-quoted (even if they contain quotes)

### ISSUE THREAD

**Issue by piaste** [fsprojects/fantomas#300]
```
        printfn """    /// Arguments are statically typed (like printf). Ex. Log.%sf("Key %%s n. %%i", "asdasd", 10)""" level
```

==>
```
        printfn 
          "    /// Arguments are statically typed (like printf). Ex. Log.%sf("Key %%s n. %%i", "asdasd", 10)" 
          level
```

which fails to compile due to the single quotes breaking the string literal.

**Comment by nojaf** [comment]
@piaste is this still an issue, seems to work [in online tool](http://ratatosk.dynu.net/fantomas/#?code=AQgOCcEsDsBcDNrAESpCA9F4BBcBzAVwFsBTOAZ2AENxTgLZrZIBjagGw4E9hZvQpACbAAFB0gBrehBgIAlADpgAUQAeygDIB7fIoCkFeKOQBpUr32Hg0ZVcjIANCmoUhroU+ABGAAzzUZGAOUgA3Ug4gA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA).

Perhaps more input is needed to reproduce, couldn't find any traces of a commit that fixed this problem.

**Comment by piaste** [comment]
I tried it now and it works, the triple quotes are preserved. 👍
