### ISSUE TITLE
Backpipe is not taken into account when splitting lines

### ISSUE THREAD

**Issue by piaste** [fsprojects/fantomas#301]
```
  let token =
    JwtSecurityToken
      ( issuer = ISSUER
      , audience = ISSUER
      , claims = 
          [ 
            Claim("UserId", sprintf "%A" userId) 
            Claim("LocationId", sprintf "%A" locationId) 
            Claim("DeviceId", sprintf "%A" deviceId)
          ]
      , expires = (Nullable <| let now = DateTime.Now in now.AddDays(TOKEN_EXPIRATION_DAYS))
      , signingCredentials = credentials
      )
```

becomes

```
  let token =
    JwtSecurityToken
      (issuer = ISSUER, audience = ISSUER, 
       claims = [ Claim("UserId", sprintf "%A" userId) 
                  Claim("LocationId", sprintf "%A" locationId) 
                  Claim("DeviceId", sprintf "%A" deviceId) ], 
       expires = (Nullable <| let now = DateTime.Now
                              now.AddDays(TOKEN_EXPIRATION_DAYS)), 
       signingCredentials = credentials)
```

which fails to compile because the `let` after the backpipe doesn't create an indentation scope, so `now` is not recognized

**Comment by jindraivanek** [comment]
This is now formatted to valid code, see [online](http://ratatosk.dynu.net/fantomas/#?code=ATA2FMBdkh7BrcA7YBeAsAKBCAUgd0gGVwBjAVwCcBLSATwBUFksccAKYagZ2-PEppgASSJEAqgFEASqzbAANMACG5ACbVkpcENESZctktKhl1ALbchh+SADawG7ZABhUxfYAicdwHC1nkrcAA40SJAAZsCeAKQAgp7A5L6U-gCUjtjObG5m5l4AMrCkypDUsEj+gcAhYZHR8YmgxaXllWoZTs65Hp4AIuAAbtTaVUGh1OFRsQnAakMj4OldbAC6XUrgAB7B1JTgVqjA7ABy5KCmAEYQwAA8AD5gUMBIsPhCfaXgDBbgAHQnN5cFCvfB-OJqNSfOjcdgMADyAGlJCcAPqSAAaAAVhNI4gxhPC0X04gBNIhpNIbGrUADmSEmtJc+3m4WoylAh2ApBZyDKHO4XTSQA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA).

Closing.
