### ISSUE TITLE
Fantomas does not support extended interpolated strings

### ISSUE THREAD

**Issue by DedSec256** [fsprojects/fantomas#3012]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKASTAdSOfAIFYBfUvXSSAGnCgGdEAXRgSwDsBzO1MAbVoigIwjIwCeAB2RpI7RtQHDI6AG4BDADYBXaX0UiADDREjIASTZI2jAMosAXsmMmIAFn1gAuouLPBH5XEpHllrBRdldW1dfhcIAEY-E0gAWTUADwAZdkRMxE5GAAtwuPiAJgMPbxFfRSFk9CDdSHz4AHkAM2y2RBtxDScA1U0dHli4sqTTAFFLTu7BuKgNDsgqnyT600bJZoAjWFgNEu2o0bRxlwBmKaULBgAnRgAxdk0AOUQAdw0ck5NGA8dOsapshk0Qgcjv8IJERjEPG5brCbBI1NBEAAhRAdWAPRAABTUDzUAFsmIgHjDhIDgS5qsJaiItkodsEZFDjrc4dExoiwIRkVBUeisTi8blYF9KdA1AwLCpYLLWLA2NSILTECDGWCImz9ocuUMzgilgA2IWQEUY7G4-EAVQkUgesvlbEVypYqvVYA6mgY2ogTOELNh%2BshhupPPOeiWAHZLdaxXbEABhDRyuip1V0WnQRh4n1%2BjQB%2BkbOrg3YR6Hc4a8i78gAcibRNvF%2BJSiFJe0pRf9WrLoIreohHMjtZNfKWAE4W6LbRLsxpvULi6WTAyg7qGqOoJyo3WY5cTPEjPyra3EABBDqMSnZ0mktQ%2BzWBsDB-wjqtjmvG%2BFT0pEnPJMF3xGwuxYOBlzVVd%2BzfD8wFDURvz3cc-3rWNSkmYDLxvO8HnA0lIKOFd%2BVfQcdWHHcUMgfcJ3-BslniG4cNFK8HlgLRLAAEUQX4iPwl8gQHDdy2ZSt2SgOQD0nRjSlcS00nSMwOgAFUKfIbEKPFGAAdRYeAih9SoKK3Kjtl3UJ5HojDjxEeJBXPJSVPU-JphLXptKefTDOKIUzRM0Sh3Er9JKsmSGMwlx4gtJyMgsDoWHSNpnTUAsHmmdIJHxOg6C9GCm0CkRN3fbcLJo6SbKPfl4gTOL0gAJUQOAHngHyjKFVwiuEEqEKQwIKrCKrTVKZt6qalr4HeLRu0pTozDvUluCFeJ4LK1lLNJLQNFYX4emePEn2YSlVKrYaAOi2dzwmvF4BSbbdpyA6HiOwTLWgQpiXRfCAH0vgMoy1vMjbBus9DqqWCpFIydiSTENoHmyXN2r8wqgZC6iwsq8GRpcMogKWVIYYeOGEaRxhptmh55sW5aavRkMJOaLadpYPbEGe16TrOnGLpMMpsMJ2G1HhxGWFze7WfZzm0re88Pq%2B-NKT%2BgHigZz9MeabG9VkqL%2BZYwmlIANXhTF2HgdgOBRn1G26iBevWsNLO1hpdbs4QygU%2Brni4-N8rNyxLetzq7a8MTGdCrWht5uS8ccw2Mm42BGAAcSYTLssQXL8uDtHTNK4GnZouiY71kQyliwnPh%2BHJsUYaV8lOqReMStgWBVNgr0sTsqbppZyKCyiMfKsKS51yL3YgMo6qF34ODYH22D91U7HntKtHxVTYAsKxGDS-K%2Bw89XEKZ6sjXH2z%2BTKMbZ-wth95USVOB7nsHhb9h2-yvu4jXETivDjWI8DS-gvhDCYV1DYPRYAsTIZI9jwDUOmWAeVODV3Zofdc-9goR01mfCKl8lhXDPITDOlIWDkmsJoAA0ogRAEgd75EYBYTEJIl6oyWL-Y%2B-Vww-nPq7Ce-IrgEziJATEGY2AAGsFh0HYpxSwnxcyIDulA9mGccp5RzEJOkg8zLDxBqPNCoDcYmCuILERmJiSgUQNxcW0AHjkLeHeeA9o26ql4tADMJIO4YL-j1ABJ9I4hBZo9HoLD0QSKYH0MQAx8FgOuAbERksQlYhJNACJth%2BiLBEXYskUh4BrHzn1U%2BMgXanAEYQr2hMaF0KUpTV%2BnQxFqEkdIn0p5Q4O0LshAxID%2BEELiFceOIi0G13bIgJJbMcgPgkFoPeHc1FZw0QVfuwkuHFNQj0spfTriVxEaQ%2BxFC94aHckROg7Cf5wUKbQTwzhZB0GeHlHgnDiBAA)

#### Code

```fsharp
$$$"""{{{5}}}"""
```
            

#### Result

```fsharp
$$$"""{{{5}"""

```
            
#### Problem description

Fantomas eats braces

![image](https://github.com/fsprojects/fantomas/assets/26364714/0fc16e98-e696-4a6a-b5d9-bb613121f5db )

#### Options

Fantomas main branch at 2023-12-06T16:47:58Z - 0f8ee237a452f3772afe7989e031b5f65ba389f5

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by nojaf** [comment]
Thanks for the report Alex!
We'll take a look at it in the coming days.

**Comment by nojaf** [comment]
So, this is a lexer problem, reported https://github.com/dotnet/fsharp/issues/16418.

**Comment by josh-degraw** [comment]
While we wait for the compiler to fix the range issue here, would it be feasible to calculate the correct range based on the source text & e.g. taking the number of `$` and just generating our own, more correct range that way? Or would you expect that to be too error prone? Depending on how long we'll need to wait for that fix, it may be worth just monkey-patching this in the meantime. Otherwise I'd be happy to take a stab at trying to fix it in the lexer, though I worry I may be fighting an uphill battle if you and other core contributors already took a stab and couldn't figure it out 😅

**Comment by nojaf** [comment]
You will wait forever if you expect someone else to fix the compiler. The team isn't going to pick this up, so I would suggest you take a stab at fixing this problem in the lexer.
