### ISSUE TITLE
Unmatched '{' error when formatting the code

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/fantomas#3017]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAdAdgG0QFzADEBDAI1wGViBbAB1wFEAPWxaPReMFAYQAtimAOaJssIQGcwAXjDAsECAFVMAJ1GJiEzjLAVY1RHIWLT-QSLFCAIsTzEAdNcQAzYgFdsBAO4BLPHwmpsFEvkw60kEh0ZiwqtTE2L4AXogAcojeSZiIUdH5YOiQRUUAxOWlYAAKAJ4BsJhYJcXFmKYAvlEAShpaiFKyANp5ivqGxm0FEObCouK29k6uHl5gfgEjUzMiXJGTU-mx8Ykp6ZnZRs2bYJ37YAC6WLeQADTgUNp4eL7CEqhgg3eEFAIUgABI8DVWP9ID88K8gYpwQA3RLuZBoQH5AAMb3ykAAkpgkJg8BRTgj8gAWREQe6I9p4xQg4LgyHQtCw0mU1lg1HYdH-LHRACMTNBAFliEwADI-RAyxDCAI8kIigBM2NpDwZ4rk2rZUIxUCV8AA8i45TkKJDcKqkXy0cbhSF1XrTJAGMSLVbkO6kdgXJBtfSOnqWR6IUaYaRYLBsPaICinULtRAAMz%2BpNE7SqPCEH6JDJZeWJxR4VTokO6xERh3s42QWPxsvJgXOtNgKlZqAUWjEaCIABCrjiiCqxFUNHwiFUZYgFarIVDikZtYNUY5UGbCf9bcFmM7AFYe5A%2BwPh6P1DLYN5Z9A%2BkTkbAH98GvOwIvENWw%2BvQZvGx3VtHXbVN8gANlPc9BxHFwxyUWhWFUB9tCfF87F8d8ezcbBtB-Vdww3BsYzjXcN35A8AU7AB2KD%2Bxgq9EB4bAtAkHgGgkRd2DiD8cLw5ca1MOskwAkiWz3EDKJdYIAA46IvWCxwlRBqFIWdeMSfjghXCA1yEojo05ICJIojt8gATnkhi4PUdixEwDTcO-ATf30-9iKM0jgNMsDRVxTsz3oxAAEEXA4VR2OoBIPy-fDdMI9zDO3LyTJTQ98hFMUAugy8bMQCgVN8OB7McrTTB0m4Et5DzkvE8i0qojK3WyoLQvCgrqCK%2BMsM7WKXIIv9qqSpsUvq0D0tFTMWovYLVFgdxiWcJJOvCmLK2c7TBOZAyty5eFUvGxrRW7AKpSYAkXAAFT4JUKD4OI8AAdV8eAVR7LV%2BviwbIxqvbvIa6TTBFE9TulC7rqVBgnLuh7ntevgP3Aj7Ntc7bEt2uF-sOwHFBFSDQfOzAXDCM0kLsOJmFodQJAkTCHJ7GTkfKrbgR2xtMYOqTOxFWiCZ6OBVHgOG3s7KkmcUCq9LRoaMe5TmzNFOS%2BbYOJ4DSdxVNnC0CQ4ag-h7EU4sq7762G6hPG%2BC5CDiBIvlnS7o3l3y1UsgL%2BdViULd8K2bbsVbT2gAQp3YWcAH0-Hh4NPuNtyZfZuWxq5-JNVPM7ZqnGozVUOVOOFhGGfFukWf1dH4-2xOFddLL8TT1QM6znO8HVzXVG13X9e5o2pdZ0uYXNrxvfla3jjt1QHehJ2JtdZr8XT4hM%2Bz3xOM9gefZH-2AsDycB3C8OXpVLuqp%2B4aOYr53gnVKaa%2BlAA1J0hx%2BeAfiEPOP0Zw%2BTZE37T--Hyp4vk618mCEAWuwOmD9iTP1fj2MWH9Y7H1luXX%2BANOzqhBkA6wsA8AAHF8CU2prTBo0DOzv2jt3EuccxJkWQdjVB%2BN8TFguCOPAd4lTj0QM4YmmB-B02CsSZSLcO75D6ijAa8DTa7WMmff%2Bph1S81nkkIQmAQGYDAQ0ckSi7DuHUJdWARIST2DfPTTsfENrM1Rj3Shnk6o0KTtEdUSsFHhUwBhZECoGhCAEWpVQnCfg8I4qVMxEti7CSgKJax1DeR-yOq6V2Ncva%2BhlDQUg8BiDMVgLTYQjDSzYU0kEouFiKEIMAqNWxldgjpn8viSms5fCGFJIkAA0ogRAtB9FKjwESIcU5VH5xMXkuB0tilUKxnYkI6Zq7REgEOFimAADWvoJCzXmsSDInFOAr0tvKfB-RCGYCEdEER5ixFDIkSUmxUSUH5HTDPKZQ5JyKXUNYJe0BVB1MLBweAKg6bOGgCxKcRjAmDMscMzk-ctk5G6QOOZ%2BAbQ1DtJPGJFSr5TM2YPSFwcYVkltH6TeU46CcCjqIr64iv4nwTmU8%2Bph0yAKmc01pZ1m7eItDMwQCz5QHLVNiQuOpCmhMNJI0plzaHXPQVM7JkLGJoouJFWg7hDF0x2TTOma0lzEpjqcslgqLmRmiTjDM9Cpk1LefU%2Bw2AoadQkH0-Ipiu7vHuEyWEEhCC03%2BLa9oQA)

#### Code

```fsharp

let FableSampleExpected :Changelogs = {
    Unreleased = Some {
        ChangelogData.Default with
            Fixed =
                normalizeNewline
                    """#### Python
"""
    }
    Releases = [
        Some {
            ChangelogData.Default with
                Changed =
                    normalizeNewline ""
        }
    ]
}

```
            

#### Result

```fsharp
let FableSampleExpected: Changelogs =
    { Unreleased =
        Some
            { ChangelogData.Default with
                Fixed =
                    normalizeNewline
                        """#### Python
""" }
      Releases =
        [ Some
              { ChangelogData.Default with
                  Changed = normalizeNewline "" } ] }

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 2023-12-13T08:46:10Z - 2e2e9e009cb1281c4a92549170304d8a97d5f80b

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by MangelMaxime** [comment]
The problem is coming from the line `""" }` indenting the `}` makes the error go away, I am not sure why.

https://github.com/fsprojects/fantomas/assets/4760796/d865558f-3673-486b-b900-d50b5d599e15

**Comment by nojaf** [comment]
Thanks, this rings a bell.
