### ISSUE TITLE
Breaks shorthand lambda atomicity for lowercase method invocations

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#3023]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAPMAfAfGA8gA4AuAlrAHYB0AtgIaFgD6VAzogE6l0A2pAXogAUASkgAacFHbEyFAOatUYANpSIoCFqgASYgE9CyNJFIViE9Vsg6AbrwCux1Ve0AGSdu2QAkhSTmAMoCyJ5eEAAsrmAAulYAvmEa0TYGRsqm5pbhNvY8Tspq4RAAjElekACydOgAMmaItYgKxAAW2cUlAExu0XHaiVaaFXqGzpDN8PgAZvUUiIEGPKEpdo7ORcVd5d4Aov4zcyvFUDzTkH0J5cPeo%2BkmAEawsDwdt3kFaJvhAMw71n52BxiAAxMy8AByiAA7nx5m8vMQOE5LgNrqs0uMni8ERBcutCtFIv88YFCHRoIgAEKIaawDiIAAKdA4dBoiGInFxWiRKPC-S0g20N2sdyxz1e-3x%2BQ2RLAAFYSVAyRTqbT6Y1YNDONA6Ow-LZYLqyJRuRBeYhUYL0TkxRlsZLVh9ZScAGxKyAqyk0ukMgCqhCMHF1%2BoohuN5AoZrA0147CtECFWhFeLtjwl3OlnxcJwA7B6vWrfYgAMI8PWsEuUVi86DEenR2M8eP8q5DDFje0ZqVrGWEk4ADgL5O96oZlUQNAeXKVTZbXgFiZtI0xXZxPed-eKAE5h6qfRqqzxTbO45bW2j27bV%2Bn106CV85SUPHLPSPEABBaacjhVmj0aMLQTMAk2Sa9O1vR1bU3R8ThKMpX0LA8GUCSdSDgY8o1PZtzwXNthQ7e4oAdTNe2zb4vG6PdKS-H9UJodCXhPOUgIva0rxXCDiO7e8%2B1gzo-kQ98Pw4WAHH8AARRA%2BAYn9AORXDtEXEDl1uG8oDMCwNwfHNOgiD1qnQHxpgAFVaZpAlaeliAAdVIeA2mjXo2KXDi1K4zItN48in0VV9DOMszml2HDLOsuyHPaJVXWcvDLwI8CiM80iYN08ISndfyaj8aZSHQIhODoesOF2dBCAZVhWEjaMB1ipT8OTQjxk0lKdIo7QSnzLL0AAJUQOAOHgCLHKVCI6q0ZTQLAFNdHU5LtL4tLKKHbq%2BoG%2BAIQcKdOBmHxORoJQlRKYCppm1IPJoBweDIOFEBBel6FkTgTM7BafLg3dXzW%2Bl4EqK6boae6OEeuSPWgVoWQpH8mGhezHJO1TRTmlq3pdLYXxOKoahE1l9HwDh6hrYaorlWqEbcpGPJR7y0fCLoEMxwycboPGCdIGtNu2jhdv2w6n3JhLOKSy7rtIW6gZB57Xpprc6e2V9mdZwniD%2B0XxYeorQdfcHIbrTgYbh9oBcaxLmqyVHZa8LpBMZmoADV1ipMx4DMeRiZq8aIEmxHU2R82Zf4un9O6kFxLrSMnf8V33dGz3YgasChbNrzoLauUuj8230Ak2BiAAcQ5UrysQSrIxj0m4%2B9infY8kiLcDq3MsxqFYQaGliG1ZoXqMKTcooUgTQoD9-AnLm%2BZOVi4vYwX3KSuuA6W7Qui6zGPz4eQKFDihw8oYIN6KhwGRM2A-ACYgiuq7D53q%2BKTaTtcoJGVL2q0LoVtX67OAoC-bE1BRR%2BnBwXuZgB6RnHsUOcikJoJ2mk1B%2BrVFovwgF0T6jN-qkCOLUNkDx4B0DLLAKqCgW63UbGeY2idZ7ijvKnRBcofgY2KJAIunBSDsnMLwAA0ogRAhBT7NGIH4KkrJt4kxOJA8hsDTbwProvLQPwGaMKpOWCgABrI4rARJiX8FCGsiBfroNukXCqVVqzyT5FPVyM9KZzx4jQ96xQfjy0xlSFkyFEASXZtALgDFv6cngH6fulApLQHLKyQepCcISLOmmKAIsAbzCERSFRHJFj6GWAg%2BxvwbaMNVvE6krJoDJOIKk9JYNWQ0CMPAC4LkVLV1mlTf2djaZeB%2BMHTGXCeGGU5oAmYSi6CqPUdGZ8lcYHRLmvPJplttA-Ezow4hbcxyIFyWLBof5CAOHPoPIxJcTFYRYgpKJcDIIZOadMpujDmHeP4bwEKDFWCiIgWQmp8QpAxDCKYVgIIqrKHEfEIAA)

#### Code

```fsharp
x |> Option.map _.serialize()
```
            

#### Result

```fsharp
x |> Option.map _.serialize ()

```
            
#### Problem description

If the new shorthand lambda syntax is used with a lower-case method invocation, a space is added and the code breaks because the lambda expression is no longer atomic.

Workarounds:
- Rename to CamelCase (not possible if you don't control the code)
- Don't use shorthand lambda in these cases

This is likely related to how Fantomas handles uppercase vs. lowercase invocations. I hope a special case can be added to never insert a space in shorthand lambda expressions.

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by dawedawe** [comment]
Fixed in [6.3.5](https://github.com/fsprojects/fantomas/releases/tag/v6.3.5)
