### ISSUE TITLE
Consider relaxing ASTTransformer treatment of ranges in record fields

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#3026]
As used in Myriad, `SynExprRecordField` requires a range in the second argument (the "where is the equals sign" range, `mEq`) or else the conversion to an `Oak` will result in having no fields in the record due to https://github.com/fsprojects/fantomas/blob/fc341e88f36ab28c3331e0e6455a0f848bf44f33/src/Fantomas.Core/ASTTransformer.fs#L979 . (So currently you end up with `{ }` instead of a record with any fields, if you didn't supply the equals range.)

Would it be reasonable to treat `None` the same as `Some range0` here? (That's what I've done [in my client code](https://github.com/Smaug123/fsharp-arguments/blob/0f42e6fda9d7072044700862e3c64d61b12f3c3c/MyriadPlugin/RemoveOptionsGenerator.fs#L22) and it seems to be fine.)

**Comment by nojaf** [comment]
Hi there, similar requests have come up with this in the past.
Fantomas expects a valid syntax tree, as the parser would produce.
We don't want to take any requests to process imperfect syntax trees.
This is somewhat mentioned in the [docs](https://fsprojects.github.io/fantomas/docs/end-users/GeneratingCode.html#Match-the-AST-the-parser-would-produce).
