### ISSUE TITLE
Multiline secondary constructor

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/fantomas#3037]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAkgHbqIBOAzotOgJayEDy2t95AOoRBNqTQG4BDEhy5gAFCNFceNALYDSmNACNYsADYAaSVLAB%2BUmvRoAousSzExbZ137DsdAFkFAcxqE05dL0KubdvroABakiOTBGvBoAErhNABeiACCpKQCmAA8AGbqsEIAfAF2ej40rq5kDITQiCpq6jpgAJRNALwcTYSIAO5iBkam5pbWTaIDji6k7p5g3r7%2BY1yloeGR6tFgceSJKWkZOXmFxbqlvBVVNXVgqhrNYB2ESxBEJBRULIzMdITkYj4AV0QrSetgg3iENGgYEssmUZDAABVwuhnuI0eMHMYwGYLFZ0CdAvYjFMZl4yn5CYEVmEIlFYvEkql0llcvl0EUMcsyhdSNVavUNGiQYFHoFsgIaOoejQQmA2JAAHKOMBybDDfGIeAKyCacBQSjoWh%2BcioMAAbX1EFAukgABIsLgzZAPOhdVauPbBOogWbLYEAAx6wKQIhIYgAZV27sCABYPRAALoegC%2Bwa4Nqk9sdyDQLuIMazdu9vrQ-rsAEZ07aXAAPAAyHkQ9asrhChd0AA4AwmwMnRGmPZnRNmcLmoFZ4Axso3uhGsOYO57iwIfePy7oAEzVrMmQhTmdNpcj9TZSC9-tcQeiYfLnPO27qY9QFdrv29iAAZh3I6IlFI6AAGIeKuiq9OoR4-lwgKIBeqY7reECjk6eaPs%2BXqrqWFofmAsZQUhEbYAItQAEKINksBhAACgoAiWG8z4QDBcEDghvbIeOkBoVBGFvmWOEAKz4VAhHEYgZEUWE9awD0ZDQAIlBEHwsDyZ8jFgMxuiXhA14ZuxDpjg%2BDToa%2BWEblIABswmQKJpHkZRiAAKrYLgpDyYphDKapPzqRK6iUCxV5sbaBkoVA3H6SW644QA7NZtnifZYQAMLqAp5DJawgLUJRvmrgFWnwUO%2Bn3qhxk8aZ0WBJ28VEXZkmIE4FjwqQeX%2BbBhWscVIWleF5WRZhVV2AAnLVYkSQ5mV5IQbUFVI2lgLp1olYZZUaCZUXvoEFZBjhNl1Sk2RvJlsjyOpmnzUVN4rWFXH9SFm38dtVZ7QlE1hBGFhQho9CzR1l1dddPWrX160VY92Hbdur0HckR1kJ9sjfdN52kECgU6cFRa9XdYMDXxkOVt%2BMNiaksAAvuAAiiAQUjDHCRdogLUtYCIS%2BOOuhtg1bZWeF7XW%2BDZIiwRWBGkQAQA6jQ8DtsJPadUF3XYyD%2BZuuD3NPZWQn8wItaC8LVhmJQYuUegUsy8E6kWfLAOK0Dyu3Zz6sE%2BZogVlZOt64Q2Q0LWTBkEIlEmLWPDhDsv3Cd2GOLVjI6hZxTv42ZOEVnFntxHApDwObss4bGNtM1denA47BbO8n201enVCUfAioAnCVTZPgJCyKawkVtHLNsxxzqyAC6i0BB3SAZR8hGmQiKGeXQ26BWo17RntdOAPQ9NqPpDj-Te3QMEtHUGQAD6MoW%2BeCuY0rccc2XSez1Im67SGdbMhkDCkI23g55bkcF1wzOx3eFWicHoa0JluF6T9dYv0wG-D%2B6B66Nz5M3Vu7cU5dwAUheOfdV5SnXmPIQbwp5OhnjzLc0MQzQNgTQbwK9B64JHvgierVrK733m8Y%2B0t2zoMvoA0uatb6kPvsTSBtYABqg0SIeHgB4VwX91JR3PjHHhmDr78JAS7HCm4%2BYiMAhTagPxJH7hkXI4S%2BduH2yvkAm%2B6iK52E3NrERlNHAAHFEDoGDqHcg4dCAmJwgo22F8LG8M4hFGxd9RCbg9iGMCPRh6JXQLJKwRDEDUx9oQWUPxkj7iaog1BgRGZ-yLstEuIT7pFghq7Lgm404UIgq4QguiaifCjPUoQAIwiIlgGGfEkII44T8nNQugNi4O1KXjMJgiIlV1qW8QgkI%2BDNnoK4HJLVUkeAyawP65iRmWNuqE8poDKkQE3AvJ%2BODZzNjosoeAAhUqwB2H4GJcStmKO7jdMZT4SGa10J%2BR%2BdhIAeLIHIHp6gADSiBEDYG6cQIgJF0g1G-v0-K-0hl2x2cEoy4yDkaMCJ%2BCB-ySJpUIAAawueQMmFM64oi1LQte3QPG0m8XkuwBSkxFNZu8zFnyBHfKkJ%2BchBKFDvRSdQ6AvAkZzJIPARy6T6DU2gGldIalhIDJRYU4ZxTRnYLoXEuFxFiVuPnJgRcXywF8uEf82l9DxLpGgAa9ARqTV7XmOTeYAJsBnwCUooJKirFqOxbYn52j-ngshXWBBLVpyEoECSsl6kdq-zZRqjlJSuVcxxXYT8Dj-lPKbMKq1cSTrYABOgXphAGVhx8gzNGaqk1os1bsj56bA18qif8wF4qQVmCRhEF5XqUz6kTOmF05BAI7DNKqkAKYgA)

#### Code

```fsharp
type IntersectionOptions
    private
    (
        primary: bool,
        ?root: Element,
        ?rootMargin: string,
        ?threshold: ResizeArray<float>,
        ?triggerOnce: bool
    )
    =

    new(?root: Element,
        ?rootMargin: string,
        ?threshold: ResizeArray<float>,
        ?triggerOnce: bool) =

        IntersectionOptions(true)

    static member Test
        (
            ?root: Element,
            ?rootMargin: string,
            ?threshold: ResizeArray<float>,
            ?triggerOnce: bool
        )
        =
        failwith "Not implemented"
```
            

#### Result

```fsharp
type IntersectionOptions
    private
    (
        primary: bool,
        ?root: Element,
        ?rootMargin: string,
        ?threshold: ResizeArray<float>,
        ?triggerOnce: bool
    ) =

    new(?root: Element,
        ?rootMargin: string,
        ?threshold: ResizeArray<float>,
        ?triggerOnce: bool) =

        IntersectionOptions(true)

    static member Test
        (
            ?root: Element,
            ?rootMargin: string,
            ?threshold: ResizeArray<float>,
            ?triggerOnce: bool
        ) =
        failwith "Not implemented"

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

The secondary constructors should follows the same indentation styles as the primary constructor and the member declaration.

```fs
type IntersectionOptions
	// ...
    =
	
    new
        (
            ?root: Element,
            ?rootMargin: string,
            ?threshold: ResizeArray<float>,
            ?triggerOnce: bool
        ) =

        IntersectionOptions(true)
	
	// ...
```

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 2024-01-11T10:58:46Z - d8f44dbe6c47bfb6371aed1dce9ee5227bf773c8

```fsharp
    { config with
                MaxLineLength = 80
                MultilineBracketStyle = stroustrup }
```

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by nojaf** [comment]
The current situation is that the formatting for implicit constructors is not influenced by the MultilineBracketStyle setting. So it gap is more with secondary constructors in general.

I'm open to implementing this feature, but I would like it to be clearly explained in the [style guide](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting). While I believe there's no need for extensive discussion on this matter, updating the guide on [dotnet/docs](https://github.com/dotnet/docs/blob/main/docs/fsharp/style-guide/formatting.md) could be beneficial in preemptively addressing any potential concerns from the community.

Could you send over a PR for the style guide?

**Comment by MangelMaxime** [comment]
> I'm open to implementing this feature, but I would like it to be clearly explained in the [style guide](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting). While I believe there's no need for extensive discussion on this matter, updating the guide on [dotnet/docs](https://github.com/dotnet/docs/blob/main/docs/fsharp/style-guide/formatting.md?rgh-link-date=2024-01-11T14%3A15%3A16Z) could be beneficial in preemptively addressing any potential concerns from the community.

Indeed, I think this case is cover by this [section](
https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-function-and-member-arguments) to be more precise this paragraph:

![CleanShot 2024-01-11 at 16 22 11@2x](https://github.com/fsprojects/fantomas/assets/4760796/37e3815d-2481-4762-afb8-3d737c533ad4)

I can send a PR to add an exemple for secondary constructors.

**Comment by nojaf** [comment]
> I can send a PR to add an exemple for secondary constructors.

Thanks!

**Comment by nojaf** [comment]
Available in https://www.nuget.org/packages/fantomas/6.3.0-alpha-007
