### ISSUE TITLE
Equals sign should only be on same line if last tuple is multiline

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#3040]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEIBtEBcwAcAnWaRAZzIGUA7AS331wBlbrEAdQ96jXsACmgALRNADWAJXIBXTDjJoAYpSEBDQvgDCI8YtrYpZWfICUnbnwz8yiALarqOWtAkOA5uTSU7Dp9E2YqhS0AGbOqk6w1ACSOHZg6oSqAJ5mXDyWApisnmBkOISsbgmESanmGZb82WxorDgANGA1iAAqsGKI1ApgNPSMOCxsaRaZALwVmc24zTmUBWBjs2xkAHQA2i0AupOZ-CaQDeBQNjhO1G5kqGDrxxCglpAAJDjJjNeQ9Yd3GM8AbqpMNJkGhblMAAxHKaQaLUJCOSi0ABeyChmQALD8IFsfgBfNH3LFQF5vEFQL4E35PAFAslgzIARkpvEgAFlVAAPIaIJhdNw4ITfKYMgBM4KJON4%2BJ%2BDz4z1e7zQkC68AA8iFufNktghXLqYDgdd6ZYRczfgBROHq7m6x6YEKQCV4ymylkkxVQABGsFgmFtVJphtBRIgAGYzRAYd1EIQcHpqICAHKIADuLX9vAKwKdUpdRPlpI%2B3t9GeJgbpIbA6IjUEo%2BFUpAAQogQrBCIgAArqVS2XAx0sQLOIHMYaW8V1UhVkyDFv1m-4GitTACsNcgdYbiGbrfbTFgKZj0CCiFhfxIEVoUQHYCHI4gY4wE8j7uns9LC9pRsrADY1xumy2baIAAqgwh7Hqe56RNQ14hICNh3mAD6Eo8L5Fj6c75vqn7BlMADsf71gBO6IAEQRkJoUT5IQ0jQDgbawfBw6WJKo55qhU7oSW87YUGNyVgAHIRm7bkBrJ2J6-Y1nBmAISxzoylhnFKm%2BPHll%2BUwAJzCcRQGUZgV7SUxiHIWAT7EspXoYe%2BvFLoykKVuuRGIAAgiEcSEJRtj2Net7ybmikcYWKnWWpi4aYyTKOf%2BW6Ae23i2M4vqGZWMlyXwrH3uxeqWTOoVYepuGMqa0XOW5HkJUlBkwTWfkZQp45KcFVncQV4VFZYDLhqVm4ucQ0hwgAIog2SJR5vk0cx9UBY1QUep8jg2YV-HCtWjnshy0QhK0IjUCobY4AA6rQ8ACte4r%2BWxgU5c1C04Et7UrYyq7rZyW07V05qyYg%2B2xsdp2CjW34XdNV2zTd80Um1OFPZ1v6vZt1BhByqqMEk9GEOaHJEOQZCXjVgkg7wmVIdlbq5VDqHLcafAMgRCNSHAhDwP9Z01uiRMYCTpnmQWkOLWFMM07wDJCQzohtvAibSLYkmEOqsR2FcNYMiZZOTrdtjGPoOSKG29hnDGrSFoLfHCxgDLaY5jOS6y2stHrhAG%2BNa7CN2dExgA%2BimJ1nWr13k7dlN6tTlZimuG19WUqqECw%2BSs4DhP%2B%2BDgf8-dpt2SaUXQpHpQpDHcc4NLssxgrcS2Mrlaq5dWUBxr81a3IOtsI7ztGyb0Nm2HJXQlH%2Bex7Q%2BR203Dv6xELuOW7SQe4Q3u%2B4KyePk1acPULYfdTnnIAGqLo2rDwEUCfXgJnPYg1S9zdOwduqHUwimtm8cooA10fje9wof8-Xhzi8oRDV8C07pnPgIoXqP0GrAHAABxXAWMcbBCiEfGsJ9f5mWXq%2BfKVNHrmwgCKeG0JkxphyM2HAB4ujG0YMNMIdBoIuThOJEuhBK5TDqsTc%2Bf9U4YNalgted96a92yG4agz9qCvyiIiIRERpDtnaLCeEOALwpSmGlKabCZoX3-lxTCPCu53zFgIjyCYnB-B5FENwDC5ZUNYLQaCzDMgqNQbzNCIVuEh2wWHK2OdtbciYD2T08BVABFgHjC4hD0xGW%2Bo49BWjV66MyKGBy0I4ExloL2RwgIADSiBED4DkV0HAsJGxJFEYnZRxka6kzrs%2BXKqkgERUsKGbOmRICNkCNQMQ3IyB9VgANKW5A4jwGHk4FocD2wIO6BNbMFSebRJcdotxvD4k92aY2dQol2yDUHtAQoiUjGIHgMBOgURhrQECOjfGjFInTPVtUzW9tiHT06DgLUOoM71L4KGDezShnNy3I83ALzUSTySLYRg8BHTXKqRZIOgCdHAN4KGB%2BzSsk5I2sXOW6pWkOA6TkOxnVwSnzANzG50L5q1Lhe8hFYDmlhOIXFRAPyWheXwNIBR0FRm4wubVSaUTL4xLeR1D5%2BDmnJJ2fkwEX1EpkFKfY8poN7zHC2GiT4ZBFB42uA43EQA)

#### Code

```fsharp
    let processSnippetLine
        (checkResults: FSharpCheckFileResults)
        (semanticRanges: SemanticClassificationItem array)
        (lines: string array)
        (line: int, lineTokens: SnippetLine)
        =
        let lineStr = lines.[line]
        ()
```
            

#### Result

```fsharp
let processSnippetLine
    (checkResults: FSharpCheckFileResults)
    (semanticRanges: SemanticClassificationItem array)
    (lines: string array)
    (line: int, lineTokens: SnippetLine) =
    let lineStr = lines.[line]
    ()

```
            
#### Problem description

Related to the changes of https://github.com/fsprojects/fantomas/pull/3038.
The `=` jump to the same line as the style guide suggests this for multiline tuples:

```fsharp
let a
    (
        b: c,
        d: e
    ) =
    f
```

If the last tuple isn't multiline we probably shouldn't go for this.
Thoughts @josh-degraw @dawedawe?

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by josh-degraw** [comment]
Yeah I feel like definitely should only apply for multiline ones.

**Comment by dawedawe** [comment]
What Josh said.
