### ISSUE TITLE
Inconsistency in choosing multi-line vs single-line constructs

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#305]
Before
```
    if xDeclaration |> isNull |> not then
      let xmlDeclaration = xmlDocument.CreateXmlDeclaration(
                                        xDeclaration.Version,
                                        xDeclaration.Encoding,
                                        xDeclaration.Standalone)
```
After
```
    if xDeclaration
       |> isNull
       |> not
    then 
      let xmlDeclaration = xmlDocument.CreateXmlDeclaration(xDeclaration.Version, xDeclaration.Encoding, xDeclaration.Standalone)
```
In its desire to use the available line width `fantomas . --recurse --indent 2 --pageWidth 132` flattened this expression
```
                                                 let xpath = ".//SequencePoint[@sl='" + sl +
                                                                                        "' and @sc='" + sc +
                                                                                        "' and @el='" + el +
                                                                                        "' and @ec='" + ec +
                                                                                        "' and @fileid='" + uid + "']"
```
to nearly the whole width of the line
```
              let xpath =
                ".//SequencePoint[@sl='" + sl + "' and @sc='" + sc + "' and @el='" + el + "' and @ec='" + ec + "' and @fileid='" 
                + uid + "']"
```
and this function
```
  let private FromList name (s:String array) =
      (ListArg name s, s.Any())
```
is flattened to 
```
  let private FromList name (s : String array) = (ListArg name s, s.Any())
```
yet this one
```
  let private IsSet s =
      s |> String.IsNullOrWhiteSpace |> not
```
is stretched out
```
  let private IsSet s =    s
    s
    |> String.IsNullOrWhiteSpace
    |> not
```
but if I write it instead as
```
  let private IsSet = 
    String.IsNullOrWhiteSpace >> not
```
that gets flattened to
```
  let private IsSet = String.IsNullOrWhiteSpace >> not
```

**Comment by jindraivanek** [comment]
This is because Fantomas (almost) always put `|>` on newline. I would also like to see this rule to be relaxed, but question is how exactly.

Details:
Infix operators from this set: `["|>"; "||>"; "|||>"; ">>"; ">>="]` are always on newline except for case when there is only one of this operators in expression and nothing else cause multiline ([code](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/SourceTransformer.fs#L63-L66)). That's why last example in one-liner.

I personally would be in favor of removing "at most one" constraint (make multiline only if it exceeds `pageWidth`).

**Comment by nojaf** [comment]
The `|>` operator is a tough one, sometimes it makes sense to put it all with a newline and sometimes you just want to inline it completely.

```fsharp
someFn a
|> otherThing b
|> anotherThing c
|> printfn "%A"

// readable right
```

```fsharp
someBoolThing a |> not
```

I can't really think of a good business rule when to add newline and when not. Exceeding `pageWidth` might lead to long unreadable lines.

**Comment by SteveGilham** [comment]
Related sporadic new-line insertion issue -- on reformatting  a FAKE build script by `fantomas . --recurse --indent 2 --pageWidth 90`, most of the targets were formatted to be like
```
_Target "SetVersion" (fun _ ->
...
```
Understandably, long comments after the `->` led to line folding
```
_Target "Gendarme"
  (fun _ -> // Needs debug because release is compiled --standalone which contaminates everything
```
but occasionally there would be cases where a newline is introduced, such as
```
_Target "UnitTestWithAltCoverCore" 
  (fun _ -> 
```
which isn't even due to the length of the target name, because
```
_Target "UnitTestWithAltCoverRunner" (fun _ -> 
```
was not so folded

**Comment by nojaf** [comment]
Closing as this is a rather old issue. A lot has changed since then.
A lot of single/multiline line decisions are now based on configurable settings:
```
max_line_length=120
fsharp_max_if_then_else_short_width=40
fsharp_max_infix_operator_expression=50
fsharp_max_record_width=40
fsharp_max_array_or_list_width=40
fsharp_max_value_binding_width=40
fsharp_max_function_binding_width=40
fsharp_max_dot_get_expression_width=50
fsharp_max_elmish_width=40
```
