### ISSUE TITLE
--preserveEOL adds newline at end of file if not already present

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#306]
I would not have expected this when using this switch, issue #250 notwithstanding

**Comment by nojaf** [comment]
Hi @SteveGilham , fantomas will always add a newline at the end of a file.
This behavior should not be determined by `--preserveEOL`.

Could you try this without the `--preserveEOL`? I would expect that the newline is added as well.

**Comment by SteveGilham** [comment]
Yes, this behaviour also happens w/o --preserveEOL, but then in that case I'm not asking it to preserve what's at the end of the line, so that's allowable.

This issue is that `--preserveEOL` isn't preserving everything it would reasonably be expected to.

**Comment by SteveGilham** [comment]
See also #250

**Comment by nojaf** [comment]
Hi @SteveGilham , could you perhaps provide a code sample on [the online tool](http://ratatosk.dynu.net/fantomas) to highlight what the remaining issue is here.

**Comment by SteveGilham** [comment]
Simply this

![screen shot 2018-11-27 at 08 27 55-fullpage](https://user-images.githubusercontent.com/7460854/49068723-5e039080-f21f-11e8-9477-bdca334d0632.png)

**Comment by nojaf** [comment]
Ok, I'm afraid I'm going to close this one as `won't fix`. We discussed this and would like to remain opinionated on this.

Having a newline no matter what settings was in the product from the very beginning and has [its benefits](https://robots.thoughtbot.com/no-newline-at-end-of-file).
