### ISSUE TITLE
FormatASTAsync loses single quotes for characters

### ISSUE THREAD

**Issue by ErikSchierboom** [fsprojects/fantomas#3076]
I've been using `FormatASTAsync` to format my code, but I found out that it is removed the single quotes from characters.

```fsharp
let code = "let x = 'A'"
let tree, _ = parseFile false (SourceText.ofString code) []    
let formattedCode = CodeFormatter.FormatASTAsync(tree) |> Async.RunSynchronously
```

I've also tried:

```fsharp
let code = "let x = 'A'"
let [|(tree,_)|] = CodeFormatter.ParseAsync(false, code) |> Async.RunSynchronously
let formattedCode = CodeFormatter.FormatASTAsync(tree) |> Async.RunSynchronously
```

But that has the same issue.

I'm using:

- Fantomas.Core: 6.3.2
- Fantomas.FCS: 6.3.2
- FSharp.Core: 8.0.200

**Comment by ErikSchierboom** [comment]
I've just tried reproducing it from within a test in Fantomas, but that _does_ work 🤔 I'll do some more digging.

**Comment by nojaf** [comment]
Yeah, this is more or less to be expected.
We don't seem to add the single quotes in https://github.com/fsprojects/fantomas/blob/4d5e5e26fbf4e0d3059bdc20453c01432c679070/src/Fantomas.Core/ASTTransformer.fs#L142

In practice, the value of `SynConst.Char` is quite unreliable, so Fantomas will normally reuse the char content based on the original source code. This is why this works in the test.

`let formattedCode = CodeFormatter.FormatASTAsync(tree, code) |> Async.RunSynchronously` probably would be another workaround.

I would accept a PR fix for this.

**Comment by ErikSchierboom** [comment]
Thanks!

```fsharp
formatSourceString "let s = 'A'" config
|> should equal "let s = 'A'\n"
```

works, but

```fsharp
formatAST false "let s = 'A'" config
|> should equal "let s = 'A'\n"
```

doesn't.

I'll see if I can figure it out :)

**Comment by ErikSchierboom** [comment]
I've opened a PR: 3076
