### ISSUE TITLE
Regression: An empty line or comment at the end of a list breaks Stroustrup formatting

### ISSUE THREAD

**Issue by Linschlager** [fsprojects/fantomas#3079]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBDATvrgJ5gC8YA2gD4A6AdhBAM6wC2iAklomww9QC6DSABpwUZtiwBLegHNmqKhIigmTSABIsxAA7I0kOVjGrNWgG650AV0MqNGgAzinmzvST0sAZRkAXshu7mAALOYQguYAviFqkVA6%2Bg7GPmbu2tZ2DpSJEACM8U6QALK4AB4AMnKIVYgKWAAWGaEFAEzOidEacebqJckGypAN8ADyAGY19Ii%2BupitGlk29sp5oWDtxcsAol5TM8H5GJOQ3bHFA8tDqQBGsLDoSxbZa2gboQDMOx70UvgsAAxOQ2AByiAA7uhai8NFh8PYLr0roltLphkYHk84Uk3rkTmFfhBIL49LhoIgAEKISawfCIAAKBFwHB4%2BFxEARSPcPSYfQ01wsGPuj2evxWOXWJwArMSoGSKdTafS6rBIYh8NBcFJPJZYNrZLB6JywNzEMj%2BajMrcRtjxWirKsCZsAGzy0nkyk0ukMgCqegMWp1XHo%2BsNMmNpsmNiklogAqYQpJtqxYtxkvejlCAHYPYrvSqGQBhdA65jF43MbnQLD06Oxi28y79R0iu3piVOqUfE4ADnzXuVvsQpV4d01DfQcebKNbNvbaZxXfx0s2AE5B0qfarK%2Bgo-KY9Om04%2BQnrYNF1B7Rnu1nPu4Cq4Tp6lQBBSbsytsNi4U3m%2BMwETBIFxSDtl0dVde02AoihfAth1VXxeBkOB9xNQ9G0A4CwGTJIr0gG8V2dNc2m2eChw-dlkLYVCngPE4ANnK150vMClwdG0oOzR8fgo998FgWwvAAEUQGFaPZf9ERPDQzyAi8bgIkxb24h8nAKIkX3KCpOEmAAVJoGl8Jp6SwAB1GR4GaU0umY89WKU9ioBU4iex4jS5W0yo9MMhpdmPEyzMs6yWnlV07NPFtBTbZy0lMNz7xOAp3W83T6EmGQKnGINcDrfBdgqPQGWYZhIww-tIrk6Kk1izEXPSRKXTaPM0oAJUQOB8HgEKbPlMIqqYeScLw9E4tcyCSOgtoB3azr6XgMFbDYCd8CmbheCUeUCmwxThTithbHQWQYVmIF6V-LB2X0sCmtIx9NxfDquvgUojpO2pzvwS6pI9aAmhZWtNQAfUhKybN2xz9vq%2BLVKmjyNE6D0dLfQgSHGfAamrXqwsqyGYtAmGJq4%2BH1MRuDNjKSpUaIYgMaxrAlpWzV1p4NgtuS-HasJ1JDuOmRTsQL6fs1G7hju6b3HacjKZp9HMZkas3v5wXhby36X3%2BwH2VB8GWi5kC2KJxrJvcsmmHaPjKZ0gA1Z0qTkeA5HkHHTT7Qaohqw2nONhLTaSzZ2i063KiBYTa3Kh2vGd13%2Bo9sBhr2lNlJNkmzZOdovJDioRNgLAAHFsEK4rEFK8rY7x%2ByFKh5O4qI-3mql1LKYhaFahpLANQaMXEDEzL6BkI16DfLwx2Z-AOc2JiornAmjdFCC04D0J2la2WYXkegw-oCPjX8Te8tsBl9NgTxvCwPLyqnGcZ5YuefYXzjBjUjPZvX9l6Evyw1QUMfVr7uQg9yqT1CEeG%2B1VZ7c3nuBJ%2BNwX6B0etbd6MgjhVFZHceAuBSywDKgoVugtr6ySGl7XCdVH5w3TpsL4z5KbF01DIDgPgbAAGlECID0GfBoWBPBUiIDvXGmwwFEM9pA720NyESwRkwL4FNQiQCpGWegABrI4zBUZCS8BCasiBXrIMFsXEqZUqzSR5LfBy99xEwIocvdwXwZZyKpAQHcDIRKK2gPgBhoIeDwD9APY0YloBliIEPQhBtSE8xGHzD6sxeEUiUdgeYxBFiSPNhAL4Vs5HK2idSIg0B4l%2BAWMcSm1ZBK2BKbYPQ5wq4jTISMYmz9SYnC%2BMHORrD2E6SZqtKYCjcDKNUaaJ88dE413wnXTsDd7pOC%2BFnOR%2BD25FlHHo2o349C2AvkPAxpcjEVSnjJMJo1UzXnGUvRuUzm5yLoR4xhF90ABVoswARoRp4QP5BIQQIRjDMCBGVZQQiQAxCAA)

#### Code

```fsharp
let array = [|
    someItem

|]

let array2 = [|
    someItem
    // comment
|]

```
            

#### Result

```fsharp
let array =
    [|
        someItem

    |]

let array2 =
    [|
        someItem
    // comment
    |]

```
            
#### Problem description

Placing an empty line or comment on the last line of an arrow, list or similar breaks Stroustrup formatting

#### Extra information

Might be related to one of the following:
- https://github.com/fsprojects/fantomas/issues/2990
- https://github.com/fsprojects/fantomas/issues/3069

--- 
- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 15/4/2024

```fsharp
    { config with
                MultilineBracketStyle = stroustrup }
```

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by nojaf** [comment]
Hi, thank you for this report.
This may have been introduced by https://github.com/fsprojects/fantomas/pull/3071.
Are you interested in submitting a PR for this?

**Comment by Linschlager** [comment]
@nojaf I'll give it a try :)
