### ISSUE TITLE
Inconsistency in spacing between function names and arguments

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#308]
Using `fantomas . --recurse --indent 2 --pageWidth 132 --preserveEOL`
```
        transform.Transform (intermediate, output)
```
becomes
```
        transform.Transform(intermediate, output)
```
with the space removed, whereas
```
      |> Seq.iter(fun n -> let text = n.InnerText
```
becomes
```
      |> Seq.iter (fun n -> let text = n.InnerText
```
with an added space.

**Comment by jindraivanek** [comment]
AFAIK this is intended. Member call `transform.Transform(intermediate, output)` without space, function application `Seq.iter (fun n -> let text = n.InnerText` with space.

**Comment by jindraivanek** [comment]
`()` have exception - no space before.

Here is code responsible for "space before parameters" behavior:
https://github.com/fsprojects/fantomas/blob/de8b3bb9133ffab72d5d70ba266796a857c899d7/src/Fantomas/CodePrinter.fs#L40-L48

It depends on whether first char of function/method is upper case - in that case no space.

**Comment by nojaf** [comment]
Multiple settings have been added to control where there should be a space.
```
fsharp_space_before_parameter=true
fsharp_space_before_lowercase_invocation=true
fsharp_space_before_uppercase_invocation=false
fsharp_space_before_class_constructor=false
fsharp_space_before_member=false
```
I think the situation has improved here.
