### ISSUE TITLE
Non needed parentheses are added around lambda call from tuple/members

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/fantomas#3082]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAzArgO2mAFADqQD0AFogIYA2ALmcQDRhbZiVgBGYAtAHxhixAJSFskRuCgBnRLVoBLbAHNpqMAG0pEUBD1QAJLQCeAB2RpIS2hO17IBgG41MFzXf0AGSfv2QAkthI2LQAygoAXsg%2BvhAALB5gALp2AL4xOokOJubqViG2sQ7O1K7qWrEQAIwZvpAAspQAHgAySogtiCr0hZVVAEyeiSn66Xa6dUZmbpBd8ADy6G3YiKEm1NFZTi5uFZX9tX4AokGLy5uVUNTokMNptRN%2BU7mWnLCw1L1PJWVoe7EAZkO9kCsgATrQAGJKGgAOUQAHdqO0vr5aGDXHdRg8tjkZm8PqiIMUduVEvFgcTQqZKNBEAAhRDoWBgxAABUoYMoAFs5IgwUS9OjMbERnoxvpHvZnvj3p9gSTSrtyWAAKyUqDU2kMpksjqwBH86CUWSBRywY2KWDiDXCxBY8U4ooyvIE%2BVbH7Ky4ANg1kC1dMZzNZAFVTOYwcbTdhzZaFNbBRB0DRZA6IBK9FLiS7XnLBYrfu5LgB2P0BnXBxAAYWoJukVet0mF0FoLMTLBT9tF93GuOmrrzCu2SrJlwAHGWaYHdaz6ohuZx%2Be3k9RU93sb3nXiB4Sh57R5UAJyT7VBvUN6gJjUrte%2BMXpp2Tbe53ce0l-FVVbwq-1TxAAQXQWh%2BQbbluUods7TTMAM0yLd%2Bxfd1nX3D9LiqGof3LM9WVCecFDgS8bRVG8uzvHtJT7F4oDdfNh0Lf5fAGE86UA4CwVw7l8I%2BK8VSg9dHU3J8EOowc3xHVC%2BiBTC-3-MFYBweAABFEGRTi2MgjFSP0e8YMfJ5nygaxaJQos%2BjiP1Giafx0AAFQobBQjIFlaAAdQUeAeg1IZ%2BIfQT9OE-IbD3d9TNiKp1R-SzrLsrojlXVYnIhNyPLIdtvW8siNwo%2BCqMC4yQoY-Qql9SLmkCdAFCaeYI0oVswSOJpTFZaRpHjIjxwy7TyMzSiZiM4LxNCxjS1KpoACVEDgMF4GSzyVTiTq9B02CwCzQwDLygb6M-CdRomqb4FhTAF35RZ-GA7k1A1KpoJWtbsgC7lMDoBRkRWSEWXA%2BR%2BRs-stq9Ppjx-faWXgepnsUN7EA%2BsEvvUv1oDITlaTYgB9BF3J6W69OlDb%2BrE7bLkGCzmlkrljHmME2ibWbUo1MdFogZacezPGCn%2Bg9Yn6DDLgaUmwXJynqdoI6TrBM6Lquz9sb83HHoh172hhuGfr%2BgmAa5g4fzJygKaphQm3Bl6oeV2r4Z-RHkZbfl0cx1KZeyoTcvx5CCpVfopN5yyADUdnpJR4CUZRafbBmHZ6nK%2BvZ9XOd8fpzNGyEcBbNr-aCIOQ41Bbw7gp2o6CmOJK5iKveaRTYFoABxOQGqaxAWrazOVTDnzdNl1mApojmi7jkrefhJF2kZWhDS6X7zGUirsAUK1sH-II5zFqXLj4zKBMd-zcq7wuhv0foRt5-9kWUbAk9wWfwhP2rMFZGzYECYJaFqtrl07HPVt6nckMmEzCr0fpdqHzoPybAz9HD6hUIvRcYJJ5KBnm1ZelQSLv3ujmESr5XaDT-hAfoQMvYK3OC0HknB4CUBrLAVqKgB5Q1fvFFBn9EL5SwSqAE35ea135AoXkIQaAAGlECIFMA-LotBAj0i5LgOmxE36tzugw9B39vhu0uACHmlRID0lrNgAA1ucaQsl5JBHhE2RAYMFZQ1rs1VqjYNIijXr5Decst6iUwYTSoAIta83pJybCiBFIG2gGCLhMJgLwBDNPa0yloC1i5LPWht4upZQjnnPIT1jZDy5NAbRcg1jGA2EwtxgJPbqKNpDDJtJslhHWBcdRgSeTmHgLcWRLN1oBRdj-ZR7iE6834YIyyotoGLE0ZQHRej2xfkZskbqudN6ygwR05hKiS7qOoUPGciBSmKxWKBUwmAn6z0sfXax7VKir0SevZJsyv4FI1r4AEfd1EcKCdwp%2B1A4qcWkFIy4yDZFSCSDEKw0hIStXUMg1IQA)

#### Code

```fsharp
func ("/health", fun a b -> "")

```
            

#### Result

```fsharp
func ("/health", (fun a b -> ""))

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

Fantomas adds non needed `()` around the lambda declaration.

> [!NOTE]
> This does not happen if you have a multi line lambda
> ```fs
> func ("/health", fun a b -> 
>     // Force new line
>     "")
> ```

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 2024-04-16T07:11:28Z - 873d9d70d755f2c058f49b4712f3d22abb28dce4

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by nojaf** [comment]
Hi, thanks for the report. This is one of those things where we add them because it is the safe thing to do to avoid another related problem. I would accept a PR for this if you are interested.

**Comment by MangelMaxime** [comment]
> This is one of those things where we add them because it is the safe thing to do to avoid another related problem.

That's what I supposed.

> I would accept a PR for this if you are interested.

I suppose it should be a small changes, I can give it when I have some time for it. Any pointers, to nudge me in the right direction?

**Comment by nojaf** [comment]
Step one would be to add a new test in `TupleTests.fs`:

```fsharp
[<Test>]
let ``maxime thing`` () =
    formatSourceString
        """
func ("/health", fun a b -> "")
"""
        config
    |> prepend newline
    |> should
        equal
        """
func ("/health", fun a b -> "")
"""
```

Then take a look in the online tool what `func ("/health", fun a b -> "")` produces (Oak tab), the tuple is stored in `ExprTupleNode`.

Next look in `CodePrinter.fs` where that is being processed:

See `let genTupleExpr (node: ExprTupleNode)`:

https://github.com/fsprojects/fantomas/blob/873d9d70d755f2c058f49b4712f3d22abb28dce4/src/Fantomas.Core/CodePrinter.fs#L1872

seems to add the parentheses.

Commenting that out will make the test pass and make 31 others fail.

**Comment by johnW-ret** [comment]
Hi, aspiring first-time contributor here.

I can confirm that the new test and all the other tests pass with the following change
https://github.com/johnW-ret/fantomas/commit/38bd8e77191675c90e1b8a95a1b985beac4a85aa#diff-3d57bb1d03e9421fabae5612ab78edb3f1e8613313c0cc6def2d7bf97e331bfeR1890

(except for a minor change to `piped tuple on a single line` which expects the old behavior)
https://github.com/johnW-ret/fantomas/commit/38bd8e77191675c90e1b8a95a1b985beac4a85aa#diff-6803f640de983e89e1830256dff8c61b0e20a56daa0f66b07d506218630a7cc2R1357

I would appreciate any additional test ideas. I have not submitted a pull request because I am unsure how "hacky" my change is.

**Comment by dawedawe** [comment]
@johnW-ret please open a PR to make reviewing easier for us. Thanks!
