### ISSUE TITLE
[Feature request] Make newline experience consistent across match branches

### ISSUE THREAD

**Issue by Lanayx** [fsprojects/fantomas#3083]
I propose we add configuration (or make default) for having consistent indentation of match cases.
So:
1) If all branches can placed in the same line, do that
2) If any branch must be moved to new line (due to length or multiline), move all branches to the new line

## Pros and Cons 

The advantages of making this adjustment to Fantomas are  - more consistent code look and feel.

The disadvantages of making this adjustment to Fantomas are - reformatting existing code base (could be fixed by disabling feature by default)

## Examples
[From Oxpecker](https://github.com/Lanayx/Oxpecker/blob/develop/examples/CRUD/Handlers.fs#L66-L70)
Existing formatting:
```fsharp
match result with
| Ok _ -> return! ctx.Write <| Created()
| Error error ->
    env.Logger.LogError(error)
    return! ctx.Write <| BadRequest {| Error = error |}
```
Proposed formatting:
```fsharp
match result with
| Ok _ -> 
    return! ctx.Write <| Created()
| Error error ->
    env.Logger.LogError(error)
    return! ctx.Write <| BadRequest {| Error = error |}
```

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to Fantomas
* [x] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
This falls under [what-are-we-not-looking-for](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#what-are-we-not-looking-for).

You are in luck, however, that this was discussed at some point in the style guide: https://github.com/fsharp/fslang-design/issues/650.

I would accept a PR for this.
