### ISSUE TITLE
[Feature request] Keep `interface end` on a single line

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/fantomas#3089]
I propose we format single "marker" interfaces on a single line e.g.

```fsharp
type Customer = interface end
```

The existing way of Fantomas deals with this problem is ...

```fsharp
type Customer =
    interface
    end
```

## Pros and Cons 

The advantages of making this adjustment to Fantomas are that the interface / end pattern is common when using e.g. phantom types or otherwise, whereby you may have a list of single marker interfaces used to distinguish one kind of a type from another using generics, and there may be many of them in a file e.g.

```fsharp
type Customer = interface end
type User = interface end
type Office = interface end
type Manager = interface end
```

The current formatting strategy uses up four lines (including the whitespace line) rather than a single line. More importantly, I think it's much more readable with the single line approach.

etc.

The disadvantages of making this adjustment to Fantomas are that it is extra work.

## Examples

See above.

## Extra information
I believe that this should be something that has a fairly low cost to identify and format e.g. interfaces with no members?

Estimated cost (XS, S, M, L, XL, XXL): XS / S

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to Fantomas
* [x] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Fantomas currently works like this, as noted in our [Changelog](https://github.com/fsprojects/fantomas/blob/main/CHANGELOG.md#630-alpha-001---2023-11-03).

Here's an example:

https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAwgK4DO6sAtogE5gC8YAlgHbrUBmAhtHok-JABpwUYonTpmAc2KowAbWERQEFVAAkWXLMjN0gxSshqAbhwA2hZGgWrVABiG3DAST690AZQYAvZI6dgACwGEAC6BgC%2B-koh6ppWULr6TkamFgk2AQCM0baQALIcAB4AMsyIJbyS6AAWydkATHax4apRBsp5GjgJkLzwAPJsZUyIHlhmfrGp5paymU4NuaqQAKJ8QyNTAVBmbJAtkbmdK91aaJAARrCwZvWnaXPWsRAAzMsuTKJU6ABizOYAHKIADuZnK91s6ColkObWO0zOvWut0hEBm6XmLyCH3RHmwXEQACFEGxYFREAAFDhUDiUVhUNEqaGwpytFTtVQnQxI7Qou4fDFPeTYgCsuKg%2BMJJLJFJKsBB1GgHFErmMsGVElgTCZEBZiDhHIRKV5F35TKFGWxADYJZApdwZeTEABVbC4KjK1VMdWahja3VgThmUSGiCclTc9GmqDmwUmWZWnYAdjtDuJpOd%2BDMKuI%2BG1pBh0DIjIlwdDbKOHUR8T5NwFiMeSYCAA40wTHZmKflEORLtRA%2BWDZX4dWTbWzfWLQnMc8dgBOdvSruIfNmANl8wV2zs8PGroT2NT%2BNNrE7LIObH2juIACCbAZ%2BfI5A4gf1YbAEZi456ddRJ8TM9shyK90ydCkPF7Bg4HXHVNxDYcdyrLka1-Sd-0bQC50aJduHvBlIPIaDbg3bF3xHI0xwPNCjwwk1T2wpwsneUCb1vKhYEIPgABFEHBIiGTfGFENUXdP33U5Dx0FhpwYkVz0CO1CiKZw2AAFRqXgPBqcl0AAdQYeBakDZoKL3KjJJo6S9AA2d5OycUr2U1SNN4VYEO03SDKMuoJWtUykNHFCf3ORIZNs4UFlsLJbSc4pXDYBgigGD0OBLVYimwCliGIf04OxFsAtE5DI1Q0LrNkrD7KY1M4qKAAlRA4CoeBvOMiVAiKlQxK-MAoziKykgi5smLbOrGua%2BBAUIPtqCGZxWHIGQJSyD9ev6owpPIQgzAkcFRl%2BckX3Eag1N-YagKYxcrwm8l4HyHa9vKQ6qGOwS7WgGoaS4BkAH0QUM4y1oknkpKGzC7Ki1QmiU4p2NpTABioMpSDa3yCq6sISu-ajyvB%2BiqqhlQGhAnYCjhqgEaRlH0Gm2aqHmxbluxVazPEizQas7bdoYfbEBet7TvOiHIuxBoliveGOER5GGFIB6eb5gW0veq9Pu%2B4tqH%2BwG6mBjnozB8KRZG2wGhYsnlIANUTIlmHgKQ0cDQq9eC3Henxro5KJiAGkUurfi44s8ttvgHZ1wNOpd0qQvdo2CchsXHIt4puNgdAAHExAyrLEByvLHYlZ22fWsrkWPY3LtN2KyeBMFyhJdBFV4M7cF4xKmAYLUmFvPge3p5mdnIwLKNdyzyrjCvGNN2qydvcFJCYAOmCD7UvAXtLCApNTYFcJAWDSvLBy3ETuuxvrS7-Bt49FnYGjG2fduoJgD%2BMCptUkPv%2ByoNvmE7vKB4CEOKOOMx5lzop7QmYtroW0egwLYJQ6SXHgBwbMsBcpMEkLXPmR8ELAPPjHS%2BlUE47FeJeMm2dqAMEoPvMwABpRAiBsC73cK4IktJl7ox2EA4uIMDZWQntfE2qhXikwCJAIkOYmAAGstjEHYpxPgwJSCIHurAvm2dsq5QLEJVkw9zKj05uPcugjK7CIlmTIkNJwKIG4nLaAVAqEAlYPAF0HdtS8WgDmWkXccHbmKkFaObttDcyeqMNhXApFiHGJgSYRCb4BFeObMRCtQnElpNASJngJjbDEfYukuB%2BB4I2jGCqF0p7CL9mTehjDlJ0y-kMCRHBpGyMDBeTGYAeq8IGkY8BDxIEkKTmIrB9cVwpN5uUJ82BCDoAPtqDRuctH5UHsJIpF90JXwgcQhJ1cxEUIcdQmZZh3JEWIJwwBx81rCFCP4HQxBfi5VkEAiIQA

Check out this [GitHub issue](https://github.com/dotnet/docs/issues/28103) for more details.

If this were a brand-new feature request, it would also be closed, as outlined [here](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#what-are-we-not-looking-for).

Please avoid opening similar issues in the future. For discussions on these topics, visit the [F# Style Guide](https://github.com/fsharp/fslang-design/?tab=readme-ov-file#style-guide).
