### ISSUE TITLE
Over-length line not folded (inside #if block)

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#309]
Using `fantomas . --recurse --indent 2 --pageWidth 90` left a >130 character line was left unaltered

```
#if NETCOREAPP2_1
#else
                     |> List.filter (fun f -> isWindows || f = "Sample1.exe.mdb" || (f.EndsWith("db", StringComparison.Ordinal) |> not))
#endif
```

**Comment by nojaf** [comment]
This problem no longer occurs with [the latest code](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=MQSwZgBAcgogKgYQPICUYEEAKmBMB9ARgFgAoYAUwBsBnc0iBxp55gbQF0IAfAPggBkQ1AC4A6MCErDyAJwgAKMAFcAdhEgBaPkIDqIFQBMA9gHdq3LuogBeCACIAygEMAtgAdK5AqPIAPcqIuBgBGdhYKYKIwhtR6wgAW8nYhdgA0EA7CMvoA5ghG7k7Z1EYqokgyBvpOlACU3HwqRsK1taQUhuBAA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA).
