### ISSUE TITLE
Regression since 6.3.5: Shorthand lambda pushes args far out right with name-sensitive alignment; discrepancy with normal lambda

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#3097]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB3WAnA1gZwBcBDAgS1gDs8AdLaigHwD4wBlRARwDo8BXAWwBCAT1r0IEAPpcA4ogIB1RIhwAbYQDUiq3ogWkCAC1i8CAQWjREePAGFDiaDgAUYihI9hhiIlgA0bp4S6Mo4AXTuQWC2RAAORNAGwmYA5ilYiCkkiFo6iAAqwrGIXLawhAAKWKRW4eJR0Nkp2KIRHgCUbpB%2B4FB48mQUKXioYADavRCgQZAAJARFyGiQpBQE3ZMScwBu2rqjE1FgAAw9R5AAkhRIa6ykAF7IZ1EALJsQALqbAL7PU%2B9QeaLUYrNYbGazXZ5A4AiAARj%2BnkgAFkiAAPAAyq0QGMQQyM4KiAFZjgCvh5fptpkigcUQXj4AB5ABmWIoiFYC1UTwBOz2S3GsLAACZER5IABRa4stk886qZmQMk-RHU8W0gWQABGsFgqkJ6qh%2BzQhyiAGYxVsrv0sAQAGKrbQAOUQ6FU2INngIWF0yopqt5GpBOr1nogfOhJqFL0t4dY8SsgkQzOwiAqviI-HkiCwYYk3t9QXJEkpHjVWyDyxD%2BstEeNgqORNjUHjCUQSZTGQxsBCWEa-Su21gjTIlDzEALiD9JYDEIWdKruprgaNAtNQQAbM3IK3E8nUwBVWLFPtEAcUIcj8gUcdgZnafrTiCliTl8OVqDVvN1tdCgDs267u2%2B4ZLYqhnnYlCED60AENgt73qoj5FiqVKBvOmpfrWkL8jCRwAByAQmwGdogyKIPwWo5ghD5Tih-poXOwKLqG2GrnhUQAJxEW2HapmUqhjs2iHIZ4xbPrONIYcGS7fjhkYNlEcKnEKO7EWYzIEDmZT8PwRC3pOT5gC%2B-xMQun6yWxuFRkccIIqpQF8Rk7D8DUepCUKIl0WJqFluhzEWaxK7WYpQRwqKDnqZpOYuW5gk3s2hn0TOjFSQF2qWcFCnrp4cIWpFbZmFgJjXAAIog7quVpuaJT63keOJxmSeq0nLKs6xWdlQpwjGqmomiFzMvkDgUKwxi2vo8AEs2pLJRJqUtel7VyexNlKU2fXooNw14hKSEcuNiikFNhi3hus0%2BQxflmZqy2dfWOUeHCW6bQNFDMqQaKMieJDYBKaKxBkNjXre%2BEXQ1vmvv55mgh1WUPd1AGvQASo42DwJN03RuDEiNSZYBvoCrVQHd8O-rZhEo2jWDwE6AhUVgLIXFp-AjM2cJGfjhNzMTkD8LwqhkO67J2tgekENVhR0vd5NKdxqmo3ANPIgLQvYqLWDi9Vt4wIYGawTmkjoMdBKc81Fa86TEKraFnjCip5z9UVWBEMIjJYFihCY6dzZg2bC0W0tYIyxxQTCvZjvos7rvu57BB05ROZMyzbPdf711pTD-OC6QwuIBrWs5lLco0jbj0SMKEXnNHbse6QhAqznecFyQ2vbtAesuwbWBGybp3p1DN0glbpcheXEDCvlkdorkuiCKs8CrCk3ugzjnyQ6Zme3cHZOh3bvXT3avAULB17z9cS8r82Lxr2AePm%2B%2Bls79bY9CsKG3T6VsAEHIBD-YD1g8DXivkKP2c0moB0fulLCu81phxeucF0bpsRJgICEPExdyofQoAYa8ZhrjkUTlgVORwkqXRShnRaMMYEvy6kcYUSNq7uhSBQI%2BJ9RyjVICwkgvAMj5FgFcG4xAOE0X2gPTeVDMKZVoQjehlMmHVQoCQUg2wcSUBSIQhmWDVi4KgqI0SEMrqDy3jJIKMjZZh3lo7VWpBZQYkzFqeARAwLlCXkgvO%2Bj6q4w3gTaGUizGjzoeaB2URJQAxzKQLMaxtAAGllCxEEXiAgVxBAuxPj7TytFxG%2BKHixZc5i94eDNBHUJghwIUBwLKPARUSq02sFpeAjc1bsn-kDIBejaqFnIfNShgdqHSMCbI80VdSm%2BCcogUq9doDVFckohpB4cGUHKtAcCLsRHCSyeArmfiQTZ2ae2LuOB5CcmENyFar8jhminqEppucUGHOOVyEuMxpmZmKPAJUWyH5EyDnDApcDPBmgPqEuJiBYj9QTgzFkZSiAVKqbeZSt976QJ%2Bf0gJhoLnmg-qE9xKCQJkRsXnHSsRTDKMoK0wBINOlePXkYiRfT-H5MGRYwFCDQn-wiVE4gqg9quTwBko4XlOa9A%2BM8FYeA7RANGEK74QA)

#### Code and expected output

```fsharp
workstations
|> Seq.sumBy
    _.GetWeeklyValueWithoutAccessCheck(
        year,
        week,
        CapacityAggregateValueType.CostPrice,
        category
    )

```
            

#### Result

```fsharp
workstations
|> Seq.sumBy
    _.GetWeeklyValueWithoutAccessCheck(year,
                                       week,
                                       CapacityAggregateValueType.CostPrice,
                                       category)

```
            
#### Problem description

This regression appeared in 6.3.5. (Fantomas 6.3.4 correctly formats it as the code at the top.)

Note that this does not happen with a normal (non-shorthand) lambda. Fantomas correctly formats this:

```f#
workstations
|> Seq.sumBy (fun x ->
    x.GetWeeklyValueWithoutAccessCheck(
        year,
        week,
        CapacityAggregateValueType.CostPrice,
        category
    ))
```

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [x] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 1/1/1990

```fsharp
    { config with
                MaxLineLength = 50 }
```

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by dawedawe** [comment]
Hey @cmeeren,
thanks for raising the issue. I'll try to find some time for this soon.
