### ISSUE TITLE
F# Range Operator (..) with negative numbers produces invalid F# code and idempotent

### ISSUE THREAD

**Issue by berkhoutalex** [fsprojects/fantomas#3105]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBtAPgWgEwBYA6ABjEMLGwEYSyLsBmYkzAXUgBpwoBnRAF34BLAHYBzHqjDpuEUBAVQAJPwCeAB2RpIo-p1kLISgG4BDADYBXLdIOLiXRYsgBJEUhH8AykIBeyRycIfDswVgMAX0C5UKM1TSkdT30gozMrGxkgiCpop0gAWVMADwAZUURSxHF%2BAAsU7KpcYlDwxSiDeXyVDRtIavgAeQAzcpFELzVzANiTC2spLOzcPOcAUXcRsZnsqHNhyFbIvK7nHoTtACNYWHMGs-SFtCWghlXDNz4AJ34AMVELAA5RAAd3MFXuTn4X2sR3aJ1m8T611ukIgaXmmVCwXe6K86lM0EQACFEMNYF9EAAFUxfUwAWwEiC%2BaIU0NhQTaCg6ilOhnOyJud3eGIyi2xYAArLioPjCSSyRTKrAQczoKY%2BG5jLB1cJYCJWRB2Yg4dyEakBYkUcLZo8sbsAGwyyByomk8mUgCq6k0X3VmpE2t1Qn1hrAwwsfFNEB5Cj56MtVyFrNFT1suwA7M7XQqPYgAMLmDU8fP6njs6D8ClhiPmKOc46dRG9K3JkVzMXPCUADmzBLdispBUQ9MuzJrkZNDfhTYtSNbqPbdvFuwAnH35e6laXzKGZbX604uTHzd150nF7bMSvGg4JS7%2B4gAILDfjM0v0%2BmmMPG6NgWMxHOLYXjaFrLl2uxULk945lulJeCOQhwLuBr7pOf4AWA8bKOeUDWimHZpi8ThNBuRIvm%2BXwIfSSG3HuEq-tOZqzmewF4W2V6dumjRvDBj5Pl8sCWO4AAiiDgjRlE-jCU5Ho2vLNhcUC6AR4HcUEVD4M6RTFC4wwACq1NUXi1BS-AAOpCPAdRhi0TEnixZy4UkehLteEGNNK946XphnVGsdYTKZPyWdZ9Qyg6dlyTOClAUpLmqe56kkU63klG4wxCMUgy%2BqYVZfGsxTqJSPA8CGqE9lFijHv%2Bp5OWxCVuVxxGKFQWZpcUABKiBwF88ChTZMr4FVCg1Zh2FxA1KlNUREpUL2HXdb18CApYo7MiMLhvvSkgylQGF1fyzn0pY5jCOC4y-BSX6CMy%2BktjN9qNOu95LRS8AFKd50VFdXw3VJzrQLUtKEpRAD6IJWTZB2OUdU3JI9N5BM02klAJdKqIMXzlOWA3hZVMOxax8XTZxs27Lg0G7IUaNfBjWM4-wq3rV8m3bbtc2E3Gil9CdZ1CBdiC-f9d0PWTT3Iys97o6YmPY0I5affzgvC3lAP3kDIOVsyENQ-UXOAcTfSk2BSUtQouC8dTOkAGqYsSojwKIYh42G3YjRAY2HQmzkm90anmxABCo8UvzCZW5UO%2B4zuu0NHthPJ3NxcbCPi0jTi4F51slCJsD8AA4gIhXFYgpXlbHBP2bVsM%2Bw1%2BGIx5yOpdTwJghUpL8Kq1T3ZoYmZSIQh6iIT7uMOLMc7sjHRcxRP1fF9dp43GftdTT7gmIIhhyIEf6j4G95ZYlL6bAbgePweXlROgUG1hPMLqB-tmxKuALavZ3MiIF-GMq4hj2OXx91EIPcqE9sgHlktVROhs56CkvKbZqz8XrWy%2BkIbYpQGSXHgKYQssAyriFboLK%2Bh5IExSTkbe%2BiUEG7CYM6YuzIhCMk8BYAA0ogRA6hT7VH4G4YkdJt7412OAm%2BE1EzsTgY-Kh2QGBU2yJAYkRYRAAGttg8AEkJdwwJyyIA%2BigwWxcSplTLNJDk08HKzzhvPDi8DyZSKltTYktI4KIBEgraAXwGEAjfPAT0A99RiWgEWOkQ8iEQNGlA2%2BydEh82%2BuMXhhJFECEmKoaYlCbGvCtrIpWMSSR0mgAk7wUwdiyLcQyTQ8BDhV3GnfbQfsHhP2oVpe8rD2E6WZv-EY8jTBKJUWGKgxB45exrjhOuViJFpKcAwLOsiCHt0HIgLJAsKgfnUJYc%2BQ99Gl0MRVSeMlhHVLEQ-OpkjXjN1kXQ9xjDz7mACjRHgAiwHoUqdwVggQdA8F%2BGVKQQiIhAA)

#### Code

```fsharp
[|-24.0 .. -1.0 .. -30.0|]
```
            

#### Result

```fsharp
[| -24.0 ..- 1.0 ..- 30.0 |]

```
            
#### Problem description

When making an F# range with a negative increment, the formatter produces invalid code after the first run. Then after running again, it produces different invalid code

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.
- [x] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by berkhoutalex** [comment]
As a workaround, you can rewrite it as
`[|-24. .. -1. .. -30.|]`
and it seems to work correctly

**Comment by nojaf** [comment]
Hello,

Thank you for reporting this issue. I believe I have found a fix for this.
