### ISSUE TITLE
Fantomas deletes attributes from getter 

### ISSUE THREAD

**Issue by nneeoo** [fsprojects/fantomas#3113]
Fantomas removes attributes from getter if attributes was set for getter and setter.
Code like this:
```
[<Erase>]
type Object3D() =
    let mutable _position: Vector3 = null

    member this.position
        with [<Emit("$0.position")>] get () = _position
        and [<Emit("$0.position = $1")>] set v = _position <- v
    
```
Willbe formatted into this:
```
[<Erase>]
type Object3D() =
    let mutable _position: Vector3 = null

    [<Emit("$0.position")>]
    member this.position
        with get () = _position
        and set v = _position <- v
```

Better example in [Fantomas online tool](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKBtAPAUQE4EMBnRAPgF0AdXCgOwBcBPAB0TAHkAjAK0WjoGYAIgAoAlGAC8VWhAgAbRHTABbAK518HBWAD6TWIQCWdQ7BpoAarzqxc-SWBqq5c6TTeyViZR0S4wdAAWhoQAdPpGJmYenrIA7saBYFjYysbCFJAAJAAM4QbGpu6QouRgxEoAbg56BVE0YJgAtGDVMbFg%2BDTwyThpdBnZeRGFZg5ZAIyZpWRgAOaKYGI1I-XtYG5uKQTE5G6MLOzc1gAsIuJS1A2yCkpqGlqstZFFlta29hKOzq5X68reXz%2BIIhfIvaJXDoQBJBXqpdKZXJg0bFGbzRbLL7PFEbSFQro9FL9QZI1ZFcZTEplCqtFZ1cnNWnrSAAGnAUAqJhoc0IqGS7IgoA62QOyDQkEM9FZAtk2Uq%2BDkqjF-KhYBybNVkAAkt1EPQAMqGABeyA1UJOMogZBlAF8zYLLVAsqK%2BRKpfbZVl5YrlehHRAJh7PJAALL4AAeABlJYhI3q5kFpaqJgAmHKO62eO0yoWxEXMZWQPXwNgAM2jNEQ%2BsYCiTea9CqVfL9qpTQdl2G6ZYrpv9UDkpcgGdtHtzwedBddHFgsDkdfH3qbaBbUP47Yg2poxFwdAAYpKFQA5RBxOQx%2BexOi4JXDrOjx35lhTmdz9tyxu%2BvsnddQfVMfDQIgABCiClrYiAAAr4AQAJ0H4F6eFeN4dJmsjZp4Y6ei64rTrOCFOoun6qgArD%2BkB-gBwGgeBkawHEfjQEQiA6pUsCMfU%2BEQEhiC3mh97ChOT44S%2B%2BHvj6zZ9gAbGRFGASBYG4IgACqTAsLgjHECxbH4BxP6lgqxC8RA6GyJhG6CYWuGvg%2BDbicufYAOwyf%2BcnUYpADCchEIQ7lmIQSF8LYnFgPpciGShI45jZ2FQFZom2UuKpQgAHM5lHyeBIaAvBekGTxEV3lFAkxZAcVvglRFQgAnGlrkKYgvlyGYwWheFsSocZ-H1iVZU2YREnJuqfbkS5iAAIKlnBuC%2Bcoyj4MF3FGWAJkOsVk7CXh5X9fZyaBsNslUfV%2BreIYcBNTQLV5UtK1gGZTo9SJW0fgNUKprV42TX4x1pGdzU-otBV8UV3XrbFj19c9O2vWu%2B2jWNuCwKo3SCIgZ79DlfYA%2B1kUYdFoNunQ8XbUlHQTN%2Bw1huGWqlgAKoEer6oEth0AA6oY8CJj%2B6aA51wPjiVkqE09dkk7EEykRTEbU3TerYGFVZMzubMc4EwWSdz2OFbja1CVAgtE5DoueBM0mS1TNCloY4ZsGpOm2Ng4ZMIphBGH9fbJRrngdctXX8-j%2BvC4lK6k05ZsAEq8LY8DK5zX6e7I3s3Xdj6FgHEMi8HYupeHke4PAh6qD4fhllqcHKLyP4TNdvtYfjahyCYZ6VruthzXQU005OgeVaTNXDRHcB5yGziNzGLe4G3U3BTAgTQQBU06AkKtDjzPt87XusEwbGd9mmZGU-DBAMGwuDRv5Meqz%2BHvV%2Bv5kC%2B66dB7ve2agfuBHyfZ90AXRe4CXZcVz7FXVeSc8ab3rqPZurcdIdy7o-HusQUxtmGoffAx9T4hDoMPBuhgm6IHHpPDGmpoCzwIHwPwi92aJhvtrEGm804CWJpnTwKYYavwjBYD8QFJTwElHMC%2BwVr4gJrnff2D9GGG2YbIFM5N2Hhl3EjPgRRuHdD4QIn8Jx45WhxqZMBqdxH1iYbvCWcjBCwDoAAcUUA7J2iAXZFHUe7LRYBE4iPuvjXqEid6tlNpqY8p4YwgToPRPUncWAo0tjQFEY1uhZV-oA1UWMvY6NWnQyy4MvFP1bKHTUY0zxzBoAomgSizCGgKTpVQikaawB1EgegOkiiXXljQ3ROt0mbXgS9DoKZs65Ibn4GgDTKixjMHMOJQIImShRAkqErV8qayBrQv2m9PGGMkbvPur8R6GB7JGfAPh4D4E8gUbk-i8FNLaskrWrS0nPg6ZkhBnh%2BBDU1DYvwhgAT1LkAAaUQIgJgtS9R0B1EBAgxTL59jmS01Jyz2nWQeV02I-AX5QkgEBLyNAADWPZCDw0Rt0Y8-lEDwGwZAxANjnauy3Ata88yrmLJubCu58K1neNXMgzUQFoIZUUoIEI0BcAfIPHBeASkolmBRtALyBBdKQqusI2%2B7jwHbLwaCgCmLFDVgYLWbuiKnlsNRaS3BgSyEaroFqnVw0BX7JYPAFeCzeZLI3vooWnSoYdH4LI1Fvz-mUx-kCMs6KujYpjDM0mORnGuMVSnZl28smrhMais5gS3KICNXgmaTB1ANLMBSuxVKaXIQdWvJ1oiVkZNZfGj1vjUVvMFZ8jQcg5ZpEIBC1UUKQHsjIGaCUhBdxGD5FCm0QA)

**Comment by nojaf** [comment]
Hi, there is a red button at the bottom of https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKBtAPAUQE4EMBnRAPgF0AdXCgOwBcBPAB0TAHkAjAK0WjoGYAIgAoAlGAC8VWhAgAbRHTABbAK518HBWAD6TWIQCWdQ7BpoAarzqxc-SWBqq5c6TTeyViZR0S4wdAAWhoQAdPpGJmYenrIA7saBYFjYysbCFJAAJAAM4QbGpu6QouRgxEoAbg56BVE0YJgAtGDVMbFg%2BDTwyThpdBnZeRGFZg5ZAIyZpWRgAOaKYGI1I-XtYG5uKQTE5G6MLOzc1gAsIuJS1A2yCkpqGlqstZFFlta29hKOzq5X68reXz%2BIIhfIvaJXDoQBJBXqpdKZXJg0bFGbzRbLL7PFEbSFQro9FL9QZI1ZFcZTEplCqtFZ1cnNWnrSAAGnAUAqJhoc0IqGS7IgoA62QOyDQkEM9FZAtk2Uq%2BDkqjF-KhYBybNVkAAkt1EPQAMqGABeyA1UJOMogZBlAF8zYLLVAsqK%2BRKpfbZVl5YrlehHRAJh7PJAALL4AAeABlJYhI3q5kFpaqJgAmHKO62eO0yoWxEXMZWQPXwNgAM2jNEQ%2BsYCiTea9CqVfL9qpTQdl2G6ZYrpv9UDkpcgGdtHtzwedBddHFgsDkdfH3qbaBbUP47Yg2poxFwdAAYpKFQA5RBxOQx%2BexOi4JXDrOjx35lhTmdz9tyxu%2BvsnddQfVMfDQIgABCiClrYiAAAr4AQAJ0H4F6eFeN4dJmsjZp4Y6ei64rTrOCFOoun6qgArD%2BkB-gBwGgeBkawHEfjQEQiA6pUsCMfU%2BEQEhiC3mh97ChOT44S%2B%2BHvj6zZ9gAbGRFGASBYG4IgACqTAsLgjHECxbH4BxP6lgqxC8RA6GyJhG6CYWuGvg%2BDbicufYAOwyf%2BcnUYpADCchEIQ7lmIQSF8LYnFgPpciGShI45jZ2FQFZom2UuKpQgAHM5lHyeBIaAvBekGTxEV3lFAkxZAcVvglRFQgAnGlrkKYgvlyGYwWheFsSocZ-H1iVZU2YREnJuqfbkS5iAAIKlnBuC%2Bcoyj4MF3FGWAJkOsVk7CXh5X9fZyaBsNslUfV%2BreIYcBNTQLV5UtK1gGZTo9SJW0fgNUKprV42TX4x1pGdzU-otBV8UV3XrbFj19c9O2vWu%2B2jWNuCwKo3SCIgZ79DlfYA%2B1kUYdFoNunQ8XbUlHQTN%2Bw1huGWqlgAKoEer6oEth0AA6oY8CJj%2B6aA51wPjiVkqE09dkk7EEykRTEbU3TerYGFVZMzubMc4EwWSdz2OFbja1CVAgtE5DoueBM0mS1TNCloY4ZsGpOm2Ng4ZMIphBGH9fbJRrngdctXX8-j%2BvC4lK6k05ZsAEq8LY8DK5zX6e7I3s3Xdj6FgHEMi8HYupeHke4PAh6qD4fhllqcHKLyP4TNdvtYfjahyCYZ6VruthzXQU005OgeVaTNXDRHcB5yGziNzGLe4G3U3BTAgTQQBU06AkKtDjzPt87XusEwbGd9mmZGU-DBAMGwuDRv5Meqz%2BHvV%2Bv5kC%2B66dB7ve2agfuBHyfZ90AXRe4CXZcVz7FXVeSc8ab3rqPZurcdIdy7o-HusQUxtmGoffAx9T4hDoMPBuhgm6IHHpPDGmpoCzwIHwPwi92aJhvtrEGm804CWJpnTwKYYavwjBYD8QFJTwElHMC%2BwVr4gJrnff2D9GGG2YbIFM5N2Hhl3EjPgRRuHdD4QIn8Jx45WhxqZMBqdxH1iYbvCWcjBCwDoAAcUUA7J2iAXZFHUe7LRYBE4iPuvjXqEid6tlNpqY8p4YwgToPRPUncWAo0tjQFEY1uhZV-oA1UWMvY6NWnQyy4MvFP1bKHTUY0zxzBoAomgSizCGgKTpVQikaawB1EgegOkiiXXljQ3ROt0mbXgS9DoKZs65Ibn4GgDTKixjMHMOJQIImShRAkqErV8qayBrQv2m9PGGMkbvPur8R6GB7JGfAPh4D4E8gUbk-i8FNLaskrWrS0nPg6ZkhBnh%2BBDU1DYvwhgAT1LkAAaUQIgJgtS9R0B1EBAgxTL59jmS01Jyz2nWQeV02I-AX5QkgEBLyNAADWPZCDw0Rt0Y8-lEDwGwZAxANjnauy3Ata88yrmLJubCu58K1neNXMgzUQFoIZUUoIEI0BcAfIPHBeASkolmBRtALyBBdKQqusI2%2B7jwHbLwaCgCmLFDVgYLWbuiKnlsNRaS3BgSyEaroFqnVw0BX7JYPAFeCzeZLI3vooWnSoYdH4LI1Fvz-mUx-kCMs6KujYpjDM0mORnGuMVSnZl28smrhMais5gS3KICNXgmaTB1ANLMBSuxVKaXIQdWvJ1oiVkZNZfGj1vjUVvMFZ8jQcg5ZpEIBC1UUKQHsjIGaCUhBdxGD5FCm0QA

We expect you to create your issue using that button, thanks for understanding.
