### ISSUE TITLE
Indentation misses a space after boolean operator when multi-line

### ISSUE THREAD

**Issue by ursenzler** [fsprojects/fantomas#3117]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBLAtgCoBOAromALxhZmIA6x9AdpjurgM47UDaYARgDcAJiEBmALqMWM1tjAA3AIbpyVPETpgAZDrAduYAD4A%2BMABkuWAHT5lABzAAKAGalmeMAFpzuAFQiAJQm5gDKCmZgEbZYsFZGUQmxsDGh0dg2XACi%2BA5YAJ6QADTgUJzYWLjMAOacqGC8ZRCgEG1QACSFDshokNVYJc1tkB0qar2Nw%2B0ADKXt7ZAAksxIzFhhuABeyPMLEAAs02CSwwC%2Bey3Ho92T-etD%2B6Pj5A1N%2BxAClwuQALLKAA8rMxEBZELUsAALR4fAQiGbHU7tC7DVo-LoFHoNSDg%2BAAeVcwMQYUKmBhizGqleaHeHxE30W2VWBKJ5J%2B6FckER52%2BaIpt2xACNYLB0GyIM8qZNaftxAyRisKsQsAAxaqqAByiAA7hwQeK2rRyNzkbzrhisX1haKDZKJm9jod5RKwg5lNBEAAhRCuWDERAABWUxGU%2BGwiGIBogRsQJraKPafJGFru1rF8rt1KmHzAAFZnVBXe6vT6-aDYNqI9BlBUVopYNWqrBmFGaHQ4xAE20kxKU0KRenzS9pY6wAA2AuQIse72%2B-0AVQcPWI1drzHrjdwzdbrlUFQ7YC7VyefatA9tlPtNNHAHZJ9OS3PEABhdA1zjP5vcMjQOKRgu7ug%2B77Ei8ZmieApnjaGaXlmMoLAAHPebozqW-q-Ig%2BCChGO57rGIE8qi5qQVAaYXsODo5gAnMhxazmWn7oNuAF4QeR5gD2nQkZAZEwRR145gIcyjlOKGIAAgq4WARp%2B%2BD2K2MZseB6LcbxQ5SpRsJfCJD70f6ET4LgcBMS2LFAfhCygZ2yn8piqbnnxGkCbC9I6WJknScQBlGaKzGjopBGmkREF2f20HqVe2awnKbnFuJxCwB48AACKIBwhmeQp7aBWBwUqaFfQDORTlRfsAgHJO-wAksriEJC4JhJCfpYAA6rg8BQq2CI5dZeW2ZaUBFY5kXwe0Aj5iJVU1XV4LZOZjXNW1HXQgWY7dZZhGJsRBWDQ8w1waOAgTpNgIrK4uAAniy7KH%2B2QAg4-qcJwW6maOCHre0VmHjZybcUNEUHYJd4nQCABKiBwMQ8BLZ1BYHB9bRfexnE3Dt9yDPtI6CUhIPg5D8AaqQWERgSSzSfg9QFgISl9b9aP4KQ6BVHqiAqn69hYJ5hChZjmllTRIl4368C-IzzPVKz7M3Zlk7QJCwbup5AD62rtZ1NNbSFA3o8VI2jvClWAvFIYFHixDJDDK1vQjEBIz9vZ-XtANY3S2k5n8RvECbZvJITxPEKT5OU4dGvdtt2sM0zuAs2zxAc1zPPO3zCwiK57vG8opvm9YotRzHUuczhsvyyGv4RiravQqHx75dr-0nvxpUpzF7tVQAalKnrVPA1Q1JbrbvdXHHh3c9foo3o1tCIFUgyqHi-i9XerL3-dwzbJybWHWuj07DclZPEAiBNreAslsBYAA4tgd0PYgT0vav1tDyjp6kQ5SfOfsIjHe7Wq6hL3osCVnBNzHoqVzrMFwE2Zg4lVgYX9sHHMAUNpBU1rXey4U956xzCIYG6cOA1GYHPZgC9mybEITdUg-pCCwBWGsLAN0Xq4XMs-EeYVBxYMBnSHG%2BDPLMEYYocstR4HYWIOA6oUCXqII%2BIBYCKDcpoP6hgjh49976wFq3MWuAiQWFDIKeAyhXywGerUP%2BLNmFyM%2BpvGuSj2G6y4bKYS7sb4RgIOCBh6AADSiBEAODoe4lYnoQwkKtjmWRFkrGoK3uguxvNP4LHEG7D4kBPRvmYAAayJJweKiVVham4IgEWWiWY30es9L8WVjQ9W%2BrTB2aM1KcJdrKNOyTPTBj0ogZKXBoDEAIOqaS8B5yQObKlaAb4QzQIsRExG1jh7b2xJHcWIIgnunSdgEkBQyRxKbu0cQLdkm5yWV6UuayNikl2CJHpoYejwC5NU5GbDCq71Udgj44gZ7u28b4qqftREElScoDJWTWxCXXnbWpXF6nv0acnXZx9klmIAWhRAhzo4S1kg4UgDDoGlLvuU16SDsryN6ooum2sGkvIcQkn%2BySXG9LDOsVQc1DKcFCTI1i9yyiSD2P0TgKpnoNHCSAM4QA)

#### Code

```fsharp
let imTrue = true
let list = [ 1;2;3]

let value = imTrue && list |> List.map (fun i -> i*2) |> Set |> Set.toList |> List.toSet |> Set.isEmpty
```
            

#### Result

```fsharp
let imTrue = true
let list = [ 1; 2; 3 ]

let value =
    imTrue
    && list
       |> List.map (fun i -> i * 2)
       |> Set
       |> Set.toList
       |> List.toSet
       |> Set.isEmpty

```
            
#### Problem description

The result should look like (one space more indentation):

```fsharp
let imTrue = true
let list = [ 1; 2; 3 ]

let value =
    imTrue
    && list
        |> List.map (fun i -> i * 2)
        |> Set
        |> Set.toList
        |> List.toSet
        |> Set.isEmpty

```

The F# style guidelines use 4 spaces in their examples. I stumbled over this because I use IndentRainbox Plugin in Rider and it shows the indentation as wrong, which is a bit annoying.

Thanks for all your work.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [x] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 1/1/1990

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello, thank you for your report!

This is a very complex problem to address. Operators in F# are challenging to format while ensuring the results remain valid. I took a brief look at the code, and one change in that area leads to multiple tests failing.

That being said, if you're interested in diving into this, please feel free! I would be open to revisiting some of our current practices after receiving approval from the style guide.

However, if you're not interested in submitting a PR, I would prefer to close this issue. It's unlikely that someone will jump into this complex situation, so I don't see the point in keeping it open if there's not enough motivation to act.

**Comment by ursenzler** [comment]
I don't think it's a big enough problem to spend so much time on. Thanks for taking a look.

**Comment by nojaf** [comment]
Thank you for your understanding. This is indeed a larger epic than just a single alignment problem. If anyone would like to revisit this in the future, please feel free to speak up.
