### ISSUE TITLE
Indent level context lost in record initialization -- causes compilation failure

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#313]
Using `fantomas . --recurse --indent 2 --pageWidth 90` again

Initializing items in a record

Before
```
                                       head = [ Doc.Verbatim """<script src="/script/modernizr-custom.js"></script>
...
}</style>"""                                    ]
                                       header = [ Doc.Verbatim """<h1>&#8220;Acrete&#8221;</h1>"""]
```

After
```
                              head =
                                [ Doc.Verbatim """<script src="/script/modernizr-custom.js"></script>
...
}</style>""" ]
                              header =
                                [ Doc.Verbatim """<h1>&#8220;Acrete&#8221;</h1>""" ]
```

where the closing bracket needs to be at least as indented as the opening one to compile.

**Comment by nojaf** [comment]
Hey @SteveGilham , this sounds like something similar to the fix in https://github.com/fsprojects/fantomas/pull/434/commits/e76f0e341ec8ac24ee95bce091db8dd3168cc3dc.

Could you provide us with a complete example to reproduce this?

**Comment by SteveGilham** [comment]
The file that showed the issue no longer shows it in 3.0.0-beta-002, as there has been some more aggressive folding of the earlier parts of the initialization; however, for the record, here it is

[acreteScript.zip](https://github.com/fsprojects/fantomas/files/3559311/acreteScript.zip)
