### ISSUE TITLE
dotnet tool install fantomas fails with System.ArgumentException: '' is not a valid version string.

### ISSUE THREAD

**Issue by sridhar-wtw** [fsprojects/fantomas#3139]
I am unable to install fantomas tool with .NET 9 GA release.

`dotnet install fantomas --version 6.3.16`
fails with
 `System.ArgumentException: '' is not a valid version string.`

The issue full details are in this link but it is closed there
[https://github.com/dotnet/msbuild/issues/10958#issuecomment-2503052283](https://github.com/dotnet/msbuild/issues/10958#issuecomment-2503052283)

**Comment by andi0b** [comment]
It would be great to keep this issue open until it's fixed in the .NET SDK, would make it much easier to find. Maybe even pin it.
