### ISSUE TITLE
Parse Exception When Using Preprocessor Directives

### ISSUE THREAD

**Issue by 1eyewonder** [fsprojects/fantomas#3143]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBiATmAOpAdgK4DmiALmgKIAeADotGbHjpjvq%2B%2BgJYBmYAMQCCAIQAylAPoBhAPIBZAAoBJCQCVJigJoAVABKyAcp3yx6%2BQQEMARgBtEAOkUBPOgyYn0ifPD6e%2BgqISMgoq6pIAUkIAakIAytJqyoo6JmbeVnaO8rDQABaWnt6%2BvP78AITC4lJySqqUamnmYDT0jMxsHJ0A2gA8OogAzmSDAHwAumAA9FP4iIhI8GC8sNgABvCwZHNkYGRDZGt7sGAA7qsA1kU%2Bfp32u5a2tgPDg2AAvHsHYtzDuJBCJ5gF4jPBgbpgcYmEx9Sj4MiYZyKWDceETEz3MAAW0sqLAlkwxAAbh8yoFqiE6uFtPojCYIBAXG52g5MIR8CC3o9ngdBtcSmSqsFamEGpEYvFEslUp0GWAcvlLKz2Zz8U9OfzblwApUgjVQvVGrKGZzlRzeQB1bhkPLSMTKISEt7dSYE4lqnmvTW8SAAGnAUEG5DIqOIg1Q4IDEFAcogkAAJGRnPQI5BUWQ-VGGQmiY9CMg0N0s3KAAz%2B2PZ5Q%2BbxkOLcABeyHLFbAABZi5CswBfZvRjsJpMptBp%2BGZis5vMFyMtsAARl7scg8ks1B%2BczE3mINrHLdnACYSx3xt2FzHF4nk1PIMVZLw14g4kn7Du5RPbPmI0WZ3uF6%2B4fBb3vF9F1sH0jxPLMz1fC8hygaxYFgWxgLjeNc3fKcvxbABmX9K3wINMDIARUUeQxEFOWxUSbDsIARfNwLlHtIP7GCr3gxDkKgVDJ0-Gi21wuM4loSxoEQEREBWTBEEUAlLCxchEEwTjaLZRAGIZJi5Sg7NWNTdikNwt8P0LPiAFYBKgISRLEiTVkQMRYFORToEsIMqyJXJLBDWB8GUvZVPUiBNIZbSUMHNiEIMli0OM6cWwANgsyArNE8TJMQABVWh6EwFy3PwDyXO83yLN4R4g0CsBgr7cddOHfTOKMjC%2BIAdiSlKbPS6RbFcwZpB84Y2XaJTSvKtSK2PRjTxY8K9MixruPQ3iZwADna4TUtsqT5EQLFrEUvyytsCqJogrSZsvOaOMMxbYswisAE51ustK7P62wfMOsbKuqsBQq42b6vmm6YuamdZzLPjko2xAhF4fZMH6rEcT8ujxtjSaNOm2rAbg4Hop4kzwfnKGOteqS4l27g4A%2Bkq%2BKOk6MbOkKLtgyAGpBwm4orfdntEuGEcprFqcQz6LLRn7sfPXH2fx2rQeW3ccNJmHHVgdl4AAEUQSjhYR1GAtOqbmJxy7h3TBaFaJ3dWyS5dqGUXgdDybw4jyVYyCteBtwsw8jaxk3pbNqALc5pbrZ58yoftx3ne8Shjofd3CK9n2%2BPiv2meN87TbZ0OCfD7nY1nRLo5XKteG4ahZByrzVlaKTBkGbgxb4lbM7lTGgql6CZfz%2BWufu4u2rL6g1AYVZ4FTvI-NbDuGS7qqe50vvRzDu6%2BNnNbR-HuBMHgQxCD2xTb2UfYsXDCzZ0lwPe%2BDyAsUIWwQ0ouYBFWHEyARnRLvXsHdyelDXek95BPxflRd%2BmBP76ySoqTAIkEaSFONwb2M8b45yDnnNeBcN7fkhjOJcK5HTwOcLITAPxhjTz8u3dBLNc5Xn7ueK2Rc5R7hJgQ%2B2xDLCkPIb8Mgh9j6YFPufS%2Bm9aE1UwVeR%2Bz9uCv0QJA6Bikf4pj-orCse4fxQy4TwihZBQEyLkQoryMCoZwIQYpJBKDtziL%2BqzBh2CB6FyHqw5WHCVzREnCIVEvh8DECoRZGh-tu63xXvfRh0FmHOIZHuW2o8BDskYC3fAXibi%2BP8XxOeNj-oDjCQ4phg8%2BJ7ijm46gmstgAHFyANyGM3Hy6TVrzwgIvX62S6p42ujg-%2B6jS4ELIhRKi4kyBOW8MoxA2tK74GtEkoQPgdqCNETOCWQSl4hLCvfDmnS1Gxj3CPAhgJuDEHwPE-AiSfJ1kOV5QgUkdCwCrEgeEXkklfUTlkuxV0oqONwS2Pc289nP0UvgR5RJ7I%2BWIHM-amBxmoimQNZ5jNO7MwkXfNmGzPldO2YAjhYDuD3jEHJaw8BLDdVgM3XxfS5FwvRgi7OdDJHvMtgUmcWF8EtkgK0RS3B5IPNsAAaXmLQO5NYqwiHgScmeo0XnLJaW8oGHS0VbLlFhdhrKRA9XwBce8gw1YazIsMBY%2BjwFzGqU3JJCyWxLKzgHDByKIpyvyU4viWFNEEJEAScmYzfjQEwJyki%2Bx4AZUmT5bW0AerwOKpS159DUzSMNWJeB0ALjkEfM4Z8qiI6xiwq41lBrZEDPjYm2sT5qIEK9XJeg8BICRrpebPJETGXYViQQvliBaD2wERC28qrLDqs1X5CGjTOw0qRaElFct7VfIrFhYprLyUDK2ogHNcika0EIGQR5PljW1Lposw2lrgnWpHbaj5470WKp6ay9l3quVrtsAnYWgxxX02%2BlKgM4xmxpkGAIZuEYGZqS7EAA)

#### Code

```fsharp
#r "nuget: Expecto"

#if FABLE_COMPILER_PYTHON
open Fable.Pyxpecto
#endif
#if FABLE_COMPILER_JAVASCRIPT
open Fable.Mocha
#endif
#if !FABLE_COMPILER
open Expecto

[<Tests>] //needed for `dotnet test` to work
#endif
let allTests = testList "All Tests" [ ]

[<EntryPoint>]
let main argv =
#if FABLE_COMPILER_PYTHON
    Pyxpecto.runTests allTests
#endif
#if FABLE_COMPILER_JAVASCRIPT
    Mocha.runTests allTests
#endif
#if !FABLE_COMPILER
    Tests.runTestsWithCLIArgs [] argv allTests
#endif
```
            

#### Error

```fsharp
Fantomas.Core.ParseException: ParseException
  [{ Severity = Error
     SubCategory = "parse"
     Range = Some (26,0--26,6)
     ErrorNumber = Some 58
     Message =
      "Unexpected syntax or possible incorrect indentation: this token is offside of context started at position (17:1). Try indenting this further.
To continue using non-conforming indentation, pass the '--strict-indentation-' flag to the compiler, or set the language version to F# 7." };
   { Severity = Error
     SubCategory = "parse"
     Range = Some (26,0--26,6)
     ErrorNumber = Some 10
     Message =
      "Incomplete structured construct at or before this point in binding" }]
   at Fantomas.Core.CodeFormatterImpl.parse@39-6.Invoke(Unit unitVar) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 47
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
```
            
#### Problem description

When working on a [PR](https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/288) over in FsToolkit.ErrorHandling, I came across this parse exception. Here is the link to the [actual code](https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/master/tests/FsToolkit.ErrorHandling.AsyncSeq.Tests/Main.fs). We are currently working around this by utilizing the `.fantomasignore` file.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas main branch at Dec 17, 2024

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by nojaf** [comment]
Hello, do all combinations of defines lead to valid code here?
If so, more information on what happens can be found in our [docs](https://fsprojects.github.io/fantomas/docs/contributors/Conditional%20Compilation%20Directives.html).

Are you interested in submitting a PR for this?

**Comment by 1eyewonder** [comment]
I see what you mean in regards to all paths needing to be correct i.e. the `main` function needs to have a return if none of the flags are true. Adding the one line allows fantomas to parse correctly.

```fsharp
#r "nuget: Expecto"

#if FABLE_COMPILER_PYTHON
open Fable.Pyxpecto
#endif
#if FABLE_COMPILER_JAVASCRIPT
open Fable.Mocha
#endif
#if !FABLE_COMPILER
open Expecto

[<Tests>] //needed for `dotnet test` to work
#endif
let allTests = testList "All Tests" []

[<EntryPoint>]
let main argv =
    printfn "Running tests" // added for sanity
#if FABLE_COMPILER_PYTHON
    Pyxpecto.runTests allTests
#endif
#if FABLE_COMPILER_JAVASCRIPT
    Mocha.runTests allTests
#endif
#if !FABLE_COMPILER
    Tests.runTestsWithCLIArgs [] argv allTests
#endif
```

I did go through the exercise of refactoring where I would consider all paths as valid and ended up coming up with the below code. Changing some of the `#if`s to `#elif`s makes more sense (at least to me) since I don't believe we can have more than one compiler directive at a time. However, fantomas does encounter some issues with this approach.

```fsharp
#r "nuget: Expecto"

#if FABLE_COMPILER_PYTHON
open Fable.Pyxpecto
#elif FABLE_COMPILER_JAVASCRIPT
open Fable.Mocha
#elif FABLE_COMPILER
#else
open Expecto
[<Tests>] //needed for `dotnet test` to work
#endif
let allTests = testList "All Tests" [ ]

[<EntryPoint>]
let main argv =
#if FABLE_COMPILER_PYTHON
    Pyxpecto.runTests allTests
#elif FABLE_COMPILER_JAVASCRIPT
    Mocha.runTests allTests
#elif FABLE_COMPILER
#else
    Tests.runTestsWithCLIArgs [] argv allTests
#endif
```

After running fantomas, I get the following:

```
[20:30:46 ERR] Failed to format file: test.fsx : ParseException
  [{ Severity = Error
     SubCategory = "parse"
     Range = Some (5,1--5,5)
     ErrorNumber = Some 10
     Message =
      "Unexpected keyword 'elif' in directive. Expected identifier or other token." };
   { Severity = Error
     SubCategory = "parse"
     Range = Some (7,1--7,5)
     ErrorNumber = Some 10
     Message =
      "Unexpected keyword 'elif' in directive. Expected identifier or other token." };
   { Severity = Error
     SubCategory = "parse"
     Range = Some (18,1--18,5)
     ErrorNumber = Some 10
     Message =
      "Unexpected keyword 'elif' in directive. Expected identifier or other token." }]
```

---

Peeking through the code I think [this](https://github.com/fsprojects/fantomas/blob/main/src/Fantomas.Core/Context.fs#L22-L29) may be the area to start looking in regards to supporting `#elif` if we think that is a desired feature. Just let me know how I can help if we see the `#elif` as a desired feature and I can try submitting a PR 😄

**Comment by nojaf** [comment]
`#elif` isn't a thing, https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-directives#preprocessor-directives

https://github.com/fsharp/fslang-suggestions/issues/1370

**Comment by nojaf** [comment]
Alright, anything actionable left for Fantomas here?

**Comment by 1eyewonder** [comment]
Nope! I feel silly but happy I learned this about F#. I didn't know it had different directive support than C#
