### ISSUE TITLE
Fantomas 2.8.1 introduces a regression where formatting with just an AST *no longer works*

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/fantomas#321]
This is because of a change where it is assumed that source is always Some even if an empty string is used:

https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodeFormatterImpl.fs#L353

This has the effect of making the following error always occur:

https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodeFormatterImpl.fs#L366-L368

As you can see before this change it was possible to supply None for the source code, now this simply fails with:

>Incomplete code fragment which is most likely due to parsing errors or the use of F# constructs newer than supported.

whenever just an AST is supplied.

**Comment by jindraivanek** [comment]
Fixed by #322.

**Comment by nojaf** [comment]
Hi @7sharp9 , sorry for this regression. I was planning on release the next version by the end of the month.
Would that be ok, or you prefer an earlier release?

Are you using this in a open source project by any chance? Might be interesting to include in #254.

**Comment by 7sharp9** [comment]
@nojaf Yeah I use Fantomas in Falanx.  Theres a dependency on Fantomas 2.8.1 in FsAst which I need to update to the patched version at some point.

**Comment by nojaf** [comment]
Ok, I'll release a new version this weekend to help out [falanx](https://github.com/jet/falanx/)

**Comment by 7sharp9** [comment]
Any news on a new release?

**Comment by nojaf** [comment]
Hi, sorry didn't get there yet.
As a workaround you can use the artifacts of [AppVeyor](https://ci.appveyor.com/project/nojaf/fantomas/builds/19403105/artifacts), that should also work.

**Comment by nojaf** [comment]
@7sharp9 [2.9.0](https://www.nuget.org/packages/fantomas-tool/2.9.0) is out.
