### ISSUE TITLE
CLI arguments not accepted

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/fantomas#334]
The following command

```
fantomas . --pageWidth 120 --noSpaceBeforeArgument false
```

Gives the following error: `Input path should be a file or a folder.`

What am I doing wrong?

**Comment by nojaf** [comment]
Hmm perhaps try ".\" instead

**Comment by jindraivanek** [comment]
`--noSpaceBeforeArgument` dont expect any parameter, it's just flag. Fantomas thinks "false" is input path in this case.

**Comment by nojaf** [comment]
The [documentation](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#using-the-command-line-tool) actually seems to cover this. I've added a link to the documentation in the help command `fantomas --help`.
