### ISSUE TITLE
Recurse option with globally installed dotnet-tool traverses 'obj' directories (2.9.0)

### ISSUE THREAD

**Issue by bdube** [fsprojects/fantomas#341]
Is this intentional and necessary?

**Comment by nojaf** [comment]
I believe the answer is both no,
Files are found via:

```fsharp
/// Get all appropriate files, either recursively or non-recursively
let rec allFiles isRec path =
    seq {
        for f in Directory.GetFiles path do
            if isFSharpFile f then yield f
        if isRec then
            for d in Directory.GetDirectories path do
                yield! allFiles isRec d
    }
```

We could add some logic not to look into the `obj` folder.
Not really a high priority for me personally.

**Comment by bdube** [comment]
It's not a terribly high priority for me, either. But thank you for including the relevant code so I can work on a change.
