### ISSUE TITLE
Make the link next to repo description point to Fantomas online

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsprojects/fantomas#344]
It'd be very helpful if this pointed to http://ratatosk.dynu.net/fantomas/ instead.

![image](https://user-images.githubusercontent.com/8275461/47709874-98ced480-dc31-11e8-8ba2-d40cf9a3de66.png)

**Comment by nojaf** [comment]
Done!

**Comment by realvictorprm** [comment]
Thank you fellows!! :) Good job :)
