### ISSUE TITLE
Add option to not insert pipe before first pattern in single line match expression

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/fantomas#364]
Currently this line
```fsharp
match user with Ok _ -> 30_000 | Error _ -> 3_000
```
is formatted as
```fsharp
match user with | Ok _ -> 30_000 | Error _ -> 3_000
```
I'd like Fantomas (optionally) to not add this pipe before the first case.

**Comment by auduchinok** [comment]
I think the best approach would be to preserve the initial style.

**Comment by nojaf** [comment]
I'm against introducing a new setting for this.
If everything fits on one line, it should not add the first pipe.

**Comment by nojaf** [comment]
Fantomas does not seem to format `match` expressions on one line anymore. See [online tool](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbAhgF2gCzAFcBnRAJzAHcBLbAgeQGswB9MAWgD4wBmABhZ8hYAD5gAomTKwKbLr0FDIAGnBRS2bNQB2Ac2KowAbTURQEC1AAk2AJ4AHZGkg7sK0xchWAbpgA2hE7GHpZ8qpaWkACS2kja2ADK1ABeyOEREAAsIWAAuh4AvulmOV52joYu8e4ZXr4BQSYZEACMxRGQALKYAB4AMjqIfYh6dDXNLQBMfDn5lkUe5h02DkGQAEawsH7jkT7%2BgYZNzZPtkQmI6NRwfrDaAILY4rH0AGYD2mk5EK-%2BpLOFdpLPblNabba7Tz7BpHb68M6eBL2TDQRAAIUQrxkiAACpgyJh0IhsORIZZsGRAgD5kDSisKs5wTsEXUDo04ZkERBIEiUejMdi%2BrBKORoJhSDFvLAxVo7mSLBSqRk5hYFpZgVDQZUmfLWTC0McMgBWLlQXmojFYsiIACq9kcZDFEu0Upl1Dlpt%2Bfn%2BysBizpWsZW2ZdPqhwNcIAbKaeciLQLrQBhPzi4iJu7ERXQbAyeU-P6Iamq2m1elg4O66Hh4LNMAAdhj5v5VsQnUu61JnoLRYgaosGu5Ze1FZZVfZtYAHI2483senbto82AvT6IireyXloGoDrR2Hx80AJzTvn3V4ksjp9BYJeKwu%2Bmn%2B0vbjYj0Ns2G1lphOGxvmW7ELiuG4PThFd7zXP11QDVZhwhPcPwjL82l-JszwvIDrm2UDazvHswD7Epn1goN4PffUawmU5fxiOJsHobQABUyFsAB1Wg8CXcD8MIsAB2sF9d3I6tDQiFoeBPVF7mkQhYgAEUQPxqCuC9b0pCDLHXAjNxBEioFcSt90-CZOV-boeiiV5GLwEZxG9RAEjwGRsHY%2BAxlNTIZgfYsny3PSqjcBCKNEywWhNMzehiV5qB6egHRwGRxB6exrWIYh3UXU0jS8yDH2g4iGX06ogpEuEWmjCKegAJUQOAyHgVz3I5HLNKg-sYMKgLDMQyiMhaBtKpqur4AAOUIdAOzIN4ohJdADFNFoeJ0zV-PQQg-C0JTPgAMRkLBNHIRjYJKg8%2BqnX8hpkeBOnWzbBl2sh9tUmN8HxFELxYGg3M4pbfN0zqDJO4y%2BuPSrpIJWx6DIAZM0aziPJaiwtN4-iyn8wHhNOiJphjczwcwSHoeoTMxom8hptm%2Bayt%2B-K-M6taNuoLbEAep7DuOzHgexlDa0gfHCZh7AbsZ5nWZwZ7f1egls3IT7qG%2ByAafagq1gx0sjKQk5qN58yADU2TRHR4B0XQ4aXTylaIunVeKznNYySYJMq7bZOzDLDdiE2zYRy2%2BI6m3Art3rsdMnXejk2BsAAcWJJKUsQNKMu9uFst91Gh1IkN1Z6kKLEmcKddupnBjRW5oEYNFpcYYliAYhJCUQedxsysDu28jc-pWzqhOz4K4UmCreZGxBKGZjFsBFEYjscBTou0WgMvuWI2zJsgqdrbj2%2B0zvB0Et9e9K2tJgG3mAGlEEQexLOskYYnrokPi%2BDe29ynzaf%2BgPur7o-zrDno7KuMQPAydawWy3ijf2cEs7LA1sHSwkxQa8ySHoPwiBpK6HGiMFyiB1idAQE-Zom9X4d3fl3csZED5Y0sPwGM9wlK6G0C7bQbs7hJAYTgQg1pGKwFolgnAGUuIv1anlZW1soFf0Ps0HgPNmh8w2uQbQ-DvBDDuLoFek1Z46AXhmQR9k06QMzhIqhFgeDa1kcLLQj8%2BiEnWPATAyZYDpT0MPUegw1JKmIdvUhu9-I9xgTnOEPAna8zksTTA6xUEAOJngBIth4i9F0auYRb9REf0qCMeAbxH4JDsKgoxXNqGh1kc8TJ7w3EvTIH4V4itwHLR8d3fe-jv5SILrI8%2Bl9eHxBiJXTAzD4atz0bUneAlfGNL2LA3OEAeCD1kaXXpjBH7EGkrAWSo0E4kmukXZmcdUrpR0aaPCQzvEjIaRQppkiMg8BPrM-EAFrShOINAMgykdA4EQPAG0887gKWgCmAksoW7P0GZ4iBKtxFA3thEHgv9ZE5OedmPBSBEkaSRoUNQuR0guGINtdKhhuIFCAA).
If this recommended by the F# style guide, I'd like to have guidance on that first.
