### ISSUE TITLE
Adjust defaults to F# code formatting guidelines

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsprojects/fantomas#372]
Three of the default settings doesn't seem to match the [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-lists-and-arrays). Maybe they should be changed?

- noSpaceAfterComma -> should be false
- noSpaceAfterSemiColon -> should be false
- noSpaceAroundDelimiter -> should be false

**Comment by alfonsogarciacaro** [comment]
Hmm, wrong place, I think this should be reported in the VS Code extension.

**Comment by nojaf** [comment]
Perhaps not entirely, would you dare say that the [Fantomas defaults](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/FormatConfig.fs#L28) are correct?

**Comment by alfonsogarciacaro** [comment]
Thanks for the pointer. Hmm, according to the samples in the guidelines I would change these two:

- SpaceBeforeArgument -> false
- SpaceBeforeColon -> false

> Preserve EOL is debatable for some (I use it), but it's not directly related to the guidelines

Apparently the VS Code extension has taken the cli arguments (with `no` in front) but it's using the defaults from your link above so the effect is the opposite.

**Comment by alfonsogarciacaro** [comment]
Ah, you're right! I was thinking this would add a space before the first argument in methods 😅 I guess it's fine then :)

**Comment by nojaf** [comment]
So only action point remaining is to change `SpaceBeforeColon` to default false?

**Comment by alfonsogarciacaro** [comment]
The guidelines don't include a specific rule about this, although most of the samples don't have a space before the colon (with a couple of exceptions). But in the Tour for F#, for example, it's more mixed (there's usually a space before the colon in record field signatures) 🤔

**Comment by jindraivanek** [comment]
Related docs issue https://github.com/dotnet/docs/issues/7262

**Comment by nojaf** [comment]
Hmm so if the list has primitives it should not have a space.
```fsharp
let x = [1; 2; 3]
```

But if it contains records it should have?
```fsharp
let x = [ { Id = 1 }; { Id = 2 }; { Id = 3 } ]
```

If I read [the guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-lists-and-arrays) correctly?
So consider removing `SpaceAfterSemicolon` and `SpaceAroundDelimiter`?

**Comment by jindraivanek** [comment]
There is space after semicolon in both samples.

Looks like `SpaceAroundDelimiter=false` for `[ ]` and `[| |]`, but `SpaceAroundDelimiter=true` for `{ }`

**Comment by nojaf** [comment]
Space indeed after semicolon, so maybe we don't need the option and can be more opinionated about it.

> Looks like SpaceAroundDelimiter=false for [ ] and [| |], but SpaceAroundDelimiter=true for { }

I don't believe it has something to do with `[ ]` or `[| |]` but more with what is inside the `[ ]` or `[| |]`.
`1; 2 ; 3;` are primitives so no space. Use space with record types.

**Comment by nojaf** [comment]
Heh just discovered that the style guide uses [fantomas docs](https://github.com/fsprojects/fantomas/blob/master/docs/FormattingConventions.md#lists-and-arrays).

**Comment by nojaf** [comment]
Still having some trouble with letting this go.
I noticed that the REPL will print lists and arrays without any spaces.

```fsharp
let tuples = [ (7, 8);(9, 2) ]
let strings = [ "a"; "b"; "c" ]
let strings2 = [| "a"; "b"; "c" |]
```

```
let tuples = [ (7, 8);(9, 2) ]
val tuples : (int * int) list = [(7, 8); (9, 2)]

let strings = [ "a"; "b"; "c" ]
val strings : string list = ["a"; "b"; "c"]

let strings2 = [| "a"; "b"; "c" |]
val strings2 : string [] = [|"a"; "b"; "c"|]
```

```fsharp
type Point = {X: int; Y:int; }
let p = { X = 7; Y = 8 }
```

```
type Point = {X: int; Y:int; }
type Point =
  {X: int;
   Y: int;}

let p = { X = 7; Y = 8 }
val p : Point = {X = 7;
                 Y = 8;}
```

I just wish that we could be somewhat more opinionated and end up with no settings at all.
elm-format has no settings and people are ok with it. You might not like everything without settings but if everyone is aligned I guess given time, you wil accept the formatting.

**Comment by alfonsogarciacaro** [comment]
Yes, I agree the less settings the formatter has, the better (both to users and maintainers). Personally, we're using fantomas in our project with all the defaults except `SpaceBeforeColon = false` but we had some doubts so we would be ok to activate them again.

Maybe we can add @cartermp to the discussion, agree on the missing points from the F# Formatting guidelines and incorporate them to Fantomas defaults and guidelines?

**Comment by cartermp** [comment]
I actually prefer this for lists:

```fsharp
let xs = [ 1; 2; 3; 4; 5 ]
```

That section in the docs sort of glosses over that without clarifying what the formatting is. I can adjust that.

I also don't think we should match what FSI ouputs. It prints things a certain way to save space in more space-constrained environments.

**Comment by nojaf** [comment]
I'm ok with spaces after `[` as well, as long as we have a clear rule when and when not instead of leaving it up to choice.
Preferably there is no situation when not (that would make our lives easier 😉), however I just dream removing the setting. Hope that could be doable. Is there an issue we can track on the docs repo?

**Comment by cartermp** [comment]
Added.
