### ISSUE TITLE
Indentation incorrect for code with chained fluent interface method calls

### ISSUE THREAD

**Issue by bentayloruk** [fsprojects/fantomas#379]
Issue created from [fantomas-ui](http://ratatosk.dynu.net/fantomas/#?code=DYUwLgBAzmCGBOkAUCDmUBcECSBBe6AlBALwBQElEA9NRAMojwCWwA9qhAMZsB2AZs1QBXeLDDM+FKgBkOAOjmpUTCAB4AtNKqyOK+AGE+gkWIl8khbTpvyAss17MAtsOcyQANxDB5AERAAI2FUS2sbKntHFzcPb18AeW94FgATECQAIgcueDYoNn4wTIAaCCUAUW9eMDifeWwBNnhncUleKwiI+QreFi4AC3kAMTz3DiMakAAPMDCu2wB1FjAQABU2eUmC0HmFyOXmVY2R1gyABXEho2dAxwy0KC2+VZqAJTY2MDLM1ecAB2o7FQ8jAs0yhE6+0oW3gIHEICU+jC1jA8AAnuEqGjMdDKKBIKhmGJ+PwQLh-v9SNxjEJRCAAOLE2Ck8mUiCPLERRZBAAS+TAsPhqwC-FgwmAYAAQsJWOl4Hs8ZEAKpQEA8wIfL4oAhPAzAZggGqXMADKFKygAYmY-AgfgqUuVDK5+3kqpAk1eYC1c0ezym70+YHNFrdauV8GAUB16Hk-JgEAA1BBMhhMknoGjHJw-edmsGXQtLUbUjbC10wyBGCxgYrQ5MTPSkLguOZeGo8JSDVw2nwZXKmAA+JA8AR0uEUqlEklkyeQ8vdBvjqtMTzMLggaOjxtw6trjdQDm6kNK+T94CpOunt7CXhXroABhdAHcjgMIDMIBpBwvygphuIsDAEgMw-PGkCrC0jgIqkEC3jM-wgK2ICpMA6IQr+ACM1iCLwQFoS6ShbOwaq4LwqTDMAwhQAMYRAA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA)

Fantomas has made a mistake with the indenting of method calls in a fluent interface call chains in both blocks of the following code sample.

*This automatic issue creation from fantomas-ui is amazing!*

#### Code

```fsharp
let start (args: IArgs) =
    // Serilog configuration
    Log.Logger <-
        LoggerConfiguration()
            .MinimumLevel.Debug()
            .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
            .Enrich.FromLogContext()
            .WriteTo.Console()
            .WriteTo.File(Path.Combine(args.ContentRoot, "temp/log.txt"))
            .CreateLogger()

    try
        try
            let giraffeApp = configureGiraffeApp args
            WebHost.CreateDefaultBuilder()
                .UseWebRoot(args.ClientPath)
                #if DEBUG
                .UseContentRoot(args.ContentRoot)
                .UseUrls(args.Host + ":" + string args.Port)
                #endif
                .UseSerilog()
                .Configure(Action<IApplicationBuilder>(configureApp giraffeApp))
                .ConfigureServices(configureServices args)
                .Build()
                .Run()
            0
        with ex ->
            Log.Fatal(ex, "Host terminated unexpectedly")
            1
    finally
        Log.CloseAndFlush()

```
            

#### Error

```fsharp
let start (args : IArgs) =
    // Serilog configuration
    Log.Logger <-
            LoggerConfiguration()
        .MinimumLevel.Debug()
        .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
        .Enrich.FromLogContext()
        .WriteTo.Console()
        .WriteTo.File(Path.Combine(args.ContentRoot, "temp/log.txt"))
        .CreateLogger()
    try
        try
            let giraffeApp = configureGiraffeApp args
            WebHost.CreateDefaultBuilder().UseWebRoot(args.ClientPath)
#if DEBUG
                   .UseContentRoot(args.ContentRoot)
                   .UseUrls(args.Host + ":" + string args.Port)
#endif

.UseSerilog()
                   .Configure(Action<IApplicationBuilder>
                                  (configureApp giraffeApp))
                   .ConfigureServices(configureServices args).Build().Run()
            0
        with ex ->
            Log.Fatal(ex, "Host terminated unexpectedly")
            1
    finally
        Log.CloseAndFlush()

```
            
#### Options

Fantomas 2.9.1

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `80` |
| `PreserveEndOfLine` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `true` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `ReorderOpenDeclaration` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `StrictMode` | `false` |

**Comment by jindraivanek** [comment]
Minimalized repro [here](http://ratatosk.dynu.net/fantomas/#?code=DYUwLgBAzmCGBOkAUCDmUBcECSBBe6AlBALwBQElEA9NRAMojwCWwA9qhAMZsB2AZs1QBXeLDDM+FKgBkOAOjmpUTCAB4AtNKqyOK+AGE+gkWIl8khbTpvyAss17MAtsOcyQANxDB5AERAAI2FUS2sbKntHFzcPb18AeW94FgATECQAIgcueDYoNn4wTIAaCCUAUW9eMDifeWwBNnhncUleKwiI+QreFi4AC3kAMTz3DiMakAAPMDCu2wB1FjAQABU2eUmC0HmFyOXmVY2R1gyABXEho2dAxwy0KC2+VZqAJTY2MDLM1ecAB2o7FQ8jAs0yhE6+0oW3gIHEICU+jC1jA8AAnuEqGjMdDKKBIKhmGJ+PwQLh-v9SNxjEJRCAAOLE2Ck8mUiCPLERRZBAAS+TAsPhqwC-FgwmAYAAQsJWOl4Hs8ZEAKpQEA8wIfL4oAhPAzAZggGqXMADKFKygAYmY-AgfgqUuVDK5+3kqpAk1eYC1c0ezym70+YHNFrdauV8GAUB16Hk-JgEAA1BBMhhMknoGjHJw-edmsGXQtLUbUjbC10wyBGCxgYrQ5MTPSkLguOZeGo8JSDVw2nwZXKmAA+JA8AR0uEUqlEklkyeQ8vdBvjqtMTzMLggaOjxtw6trjdQDm6kNK+T94CpOunt7CXhXroABhdAHcjgMIDMIBpBwvygphuIsDAEgMw-PGkCrC0jgIqkEC3jM-wgK2ICpMA6IQr+ACM1iCLwQFoS6ShbOwaq4LwqTDMAwhQAMYRAA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA).
