### ISSUE TITLE
"Better" support for nesting complex expressions in async { } blocks

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/fantomas#386]
`let!` bindings don't indent the same as non-let! ones:

```fsharp
let x data =
    async { 
        let bar =
            data
            |> Array.map id
            |> Array.filter ((=) 1)
            |> Array.countBy id
            |> async.Return
        return bar
    }
```

But if you change the `let` to a `let!`:

```fsharp
let x data =
    async { 
        let! bar = data
                   |> Array.map id
                   |> Array.filter ((=) 1)
                   |> Array.countBy id
                   |> async.Return
        return bar
    }
```
This uses up lots of horizontal space and doesn't scale well if the expression is larger.

**Comment by nojaf** [comment]
Please mention your configuration. What is the value of `PreserveEndOfLine`?

**Comment by isaacabraham** [comment]
Just using the default settings e.g. create an empty fsx file, put in the code above and use `fantomas foo.fsx`.

**Comment by zakaluka** [comment]
Re-create:

`let`: http://ratatosk.dynu.net/fantomas/#?code=DYUwLgBAHhAmCGZ4QLwFgBQFsXgZwE8A7AYwgG8JMcaJRIAjeAJ1Wto4SXY5oB8AfBACCzZvAIA6ALbwADhACWsHr2yCRYiZIBmi4GBCsAFMZQBKCAEZzqtRtHipJAPYBXImABCBJSqxqOBr4xCSSAErgbsxEdjjMUTEQTMyqAL5AA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA

`let!`: http://ratatosk.dynu.net/fantomas/#?code=DYUwLgBAHhAmCGZ4QLwFgBQFsXgZwE8A7AYwgG8JMcaJQwBCCAI3gCdU5F5ra-+APgD4IAQTZt4BAHQBbeAAcIAS1i9+G7MLESp0gGbLgYEBwAUZlAEoIARivrNgkeMkySAewCuRMACECFTUsJw1tfGISaQAlcC82IkcaNjiElnZHAF8gA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA

**Comment by isaacabraham** [comment]
I think the second one should be http://ratatosk.dynu.net/fantomas/#?code=DYUwLgBAHhAmCGZ4QLwFgBQFsXgZwE8A7AYwgG8JMcaJQwBCCAI3gCdVrbuEkvuaAHwB8EAIJs28AgDoAtvAAOEAJax+A7CPGTpMgGYrgYEBwAUZlAEoIARisbN2iVNkkA9gFciYAEIFVdSxNHG18YhIZACVwTzYiRxw2WPiWdg0AXyA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA

**Comment by nojaf** [comment]
This behaviour has been improved by now.
I did encounter one minor [related bug](https://github.com/fsprojects/fantomas/issues/819).
