### ISSUE TITLE
Fantomas 2.9.1 formats F# Asp.net Core template into code with compiler errors

### ISSUE THREAD

**Issue by DavidKarlas** [fsprojects/fantomas#403]
Issue created from [fantomas-ui](http://ratatosk.dynu.net/fantomas/#?code=HYQwtgpgzgDiDGEAEBhA9mOwCeA6A6hAEYCCMMANgJbwgAuVawAjAFCtowTBIDK2UOhDAcuPfoOG50FChHgMmUXAHFuEAE41R3PgKFhcASQDyO8fqkAZKsACO5vZMMAVABYaIIACa2A5rguIFAA1lCOALI0GmhQaABmdLgksAByEHTonpHRsQlJKTDpmWieuAASsQzAfjnwMXGJuACiAB5CwFCMndJM8VR+AK4a9N11Dfkt7dxdSrhWaH5+-uxgaN6DckgACjF+I2BIALysSGdIcnRIEK1UJd7IR0gADOznFxlIAEKDVBTehCIlUESBAGj8UGOp3e50BwLo0JhMOknnoEAAIhB4iBNnQfn8HhoABRgiEASkRSPOuAAqlAILw6GC6IMYAAeRnM1kAPiJFKpyPx-z5b3OAG02c1gHQNNhtmhbHRuQBdSmXJBgEC2UHgyEnAVCgHEeEk3Vk3AAJUGwBFlPeNzu6AerCAA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA)

Compiler errors:
Program.fs(13,13): Error FS0010: Unexpected symbol '.' in binding. Expected incomplete structured construct at or before this point or other token. (FS0010) (fsharp1322)
Program.fs(5,5): Error FS3118: Incomplete value or function definition. If this is in an expression, the body of the expression must be indented to the same column as the 'let' keyword. (FS3118) (fsharp1322)
Program.fs(1,1): Error FS0010: Incomplete structured construct at or before this point in implementation file. Expected incomplete structured construct at or before this point or other token. (FS0010) (fsharp1322)

#### Code

```fsharp
namespace Company.WebApplication1

open System
open System.Collections.Generic
open System.IO
open System.Linq
open System.Threading.Tasks
open Microsoft.AspNetCore
open Microsoft.AspNetCore.Hosting
open Microsoft.Extensions.Configuration
open Microsoft.Extensions.Logging

module Program =
    let exitCode = 0

    let BuildWebHost args =
        WebHost
            .CreateDefaultBuilder(args)
            .UseStartup<Startup>()
            .Build()

    [<EntryPoint>]
    let main args =
        BuildWebHost(args).Run()

        exitCode

```
            

#### Error

```fsharp
namespace Company.WebApplication1

open System
open System.Collections.Generic
open System.IO
open System.Linq
open System.Threading.Tasks
open Microsoft.AspNetCore
open Microsoft.AspNetCore.Hosting
open Microsoft.Extensions.Configuration
open Microsoft.Extensions.Logging

module Program =
    let exitCode = 0
    let BuildWebHost args = WebHost.CreateDefaultBuilder(args).UseStartup<Startup>()
            .Build()

    [<EntryPoint>]
    let main args =
        BuildWebHost(args).Run()
        exitCode

```
            
#### Options

Fantomas 2.9.1

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `80` |
| `PreserveEndOfLine` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `true` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `ReorderOpenDeclaration` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Latest code from master formats as followed:

```
    let BuildWebHost args =
        WebHost.CreateDefaultBuilder(args).UseStartup<Startup>()
            .Build()
```

Could you try [the nightly version](https://github.com/fsprojects/fantomas#early-builds) and verify it is still a issue?

**Comment by DavidKarlas** [comment]
I tried to add 2.9.1-latest but I'm too much of noob with paket to convice it to pull from myget, can someone else try?

**Comment by jindraivanek** [comment]
@DavidKarlas You can try it as dotnet tool:

`dotnet tool install fantomas-tool -g --add-source https://myget.org/F/fantomas/api/v3/index.json --framework netcoreapp2.1 --version 2.9.1-latest`

then you should be able to run `fantomas source-file.fs`

----

It looks like that we have bad formatted `dotnet tool install` command in README, if I copy-paste it don't have `https://` before `myget.org` and it fails.

**Comment by jindraivanek** [comment]
And I can confirm it works correctly on my machine.

**Comment by DavidKarlas** [comment]
I guess we can close this, when is 2.9.2 planned?

**Comment by nojaf** [comment]
We have somewhere begin February in mind.
