### ISSUE TITLE
Attributes followed by unit literals aren't formatted properly

### ISSUE THREAD

**Issue by ForNeVeR** [fsprojects/fantomas#405]
### Description

I have this code:

```fsharp
[<assembly: AssemblyVersion("0.0.1.0")>]
[<assembly: InternalsVisibleTo("Nightwatch.Tests")>]
()
```

After formatting, it looks like this:

```fsharp
()[<assembly: AssemblyVersion("0.0.1.0")>]
[<assembly: InternalsVisibleTo("Nightwatch.Tests")>]
```

Fantomas shouldn't change the order of literals and attributes in this case.

### Repro code

Here's the [repro link](http://ratatosk.dynu.net/fantomas/#?code=HYQwtgpgzgDiDGEAEA5AlgcwBYBcDuIO8WAsAFDkD2MEwSAygJ5Q4RgB0AShAGYA2EeDjSVgVGnSYs2XAK7BhkdgGFKYGGgEAnehC0A3NIijlyAbQA8IKFDYAjPowBcSAII37jgGp6oI4AAUAEQADOxhAIzhQQCUAHwAuuZWHmAOzkgAkgp6oHxQXmh+DhAAKpTB6Nj4hMTspdA4ULGJpmQBMUA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwi8XjhjlEMPA3QB7ADZ6IAQXiSoshUqIzUBoZrSYAQjBl7+J3tXxx4KmoaICgYMG4e-ADChsaB6k5hJjLwwjF4eKjxwaGYyam8Wjr6RhDZ5JCwCFIQACq8AJ6MrLb2jiAASjCesLxSyHAAIjDoBqi8qPAMcYR2DjnOMN56ONDDBgw6BeUhqrrwALJ6sK3zAL5AA), note `PreserveEndOfLine`.

**Comment by nojaf** [comment]
Hello @ForNeVeR , in #390 we have decided to sunset `--preserve-eol` in the next major.
There is no issue if `PreserveEndOfLine` is false so it is unlikely this will be fixed by us.
I'm leaving it open in case anyone from the community wants to pick it up.

**Comment by nojaf** [comment]
Not a problem anymore due to #434.
