### ISSUE TITLE
Compiled operators names are replaced with source names

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas#409]
Sometimes using compiled name is preferred as source name produces a warning in this particular case. The problem is FCS replaces all source names with compiled names in AST idents and we don't know whether compiled or source name was used in the actual code.

Issue created from [fantomas-ui](http://ratatosk.dynu.net/fantomas/#?code=C4TwDgpgBAKgFASigXgFBQ1AzsAhsASwGMoBbCUgIwgCcoB7MAfQBkIssYALXAOzlwAaKJSTIouKAB4RQA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwi8XjhjlEMPA3QB7ADZ6IAQXiSoshUqIzUBoZrSYAQjBl7+J3tXxx4KmoaICgYMG4e-ADChsaB6k5hJjLwwjF4eKjxwaGYyam8Wjr6RhDZ5JCwCFIQACq8AJ6MrLb2jiAASjCesLxSyHAAIjDoBqi8qPAMcYR2DjnOMN56ONDDBgw6BeUhqrrwALJ6sK3zAL5AA).

#### Code

```fsharp
type T() =
    static member op_LessThan(a, b) = a < b
```
            

#### Result

```fsharp
type T() =
    static member (<) (a, b) = a < b

```
            
#### Options

Fantomas 2.9.1

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `80` |
| `PreserveEndOfLine` | `true` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `true` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `ReorderOpenDeclaration` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Hi, I have a fix for this in https://github.com/fsprojects/fantomas/pull/434/commits/112452e20b0f53b098594054f9ab7be7589f2215.
However, I'm not 100% sure I covered all the possible cases here.
Let me know if you find scenarios where it is still a problem.
