### ISSUE TITLE
Latest FCS breaks fantomas

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/fantomas#410]
### Description

Latest FCS breaks fantomas, `Microsoft.FSharp.Compiler.SourceCodeServices.FSharpLineTokenizer.ScanToken` has changed.

### Repro code

Build with latest version of FCS

**Comment by auduchinok** [comment]
I tried building Fantomas with a newer FCS some time ago, the needed changes were: https://github.com/auduchinok/fantomas/commit/4848b8d0a765d06aedc354ff7ebdb9c7b3efeb3a
I didn't do much to support newer features, so please check/update/implement needed stuff if cherry-picking.

**Comment by nojaf** [comment]
I guess https://github.com/Microsoft/visualfsharp/issues/6189 will lead to a newer FCS.
Will wait for those changes.

**Comment by cartermp** [comment]
Anonymous Records are now a part of the expression API: https://github.com/Microsoft/visualfsharp/pull/6257 - FCS 27.0.1

**Comment by nosami** [comment]
Looks like https://github.com/fsprojects/fantomas/pull/427 fixes this. Is there any chance of getting an updated NuGet package so that I can update Fantomas in VSMac without building it myself? Cheers

**Comment by nojaf** [comment]
Please consider the nightly build, https://github.com/fsprojects/fantomas/blob/master/README.md#early-builds

**Comment by nosami** [comment]
```
Œª any ‚Üí Œª  master-vnext* ‚Üí pwd
/Users/jason/src/monodevelop/main/external/fsharpbinding/packages/fantomas-tool/tools/netcoreapp2.1/any
Œª any ‚Üí Œª  master-vnext* ‚Üí ls -la
total 36128
drwxr-xr-x  25 jason  staff       800 May  2 23:28 .
drwxr-xr-x   3 jason  staff        96 May  2 23:28 ..
-rw-r--r--   1 jason  staff       197 Feb  2 11:10 DotnetToolSettings.xml
-rw-r--r--   1 jason  staff  14734336 Sep  5  2018 FSharp.Compiler.Service.dll
-rw-r--r--   1 jason  staff   2701360 Nov 26 17:51 FSharp.Core.dll
-rw-r--r--   1 jason  staff    743424 Feb  2 11:10 Fantomas.dll
-rw-r--r--   1 jason  staff    172596 Feb  2 11:10 Fantomas.pdb
drwxr-xr-x   3 jason  staff        96 May  2 23:28 cs
drwxr-xr-x   3 jason  staff        96 May  2 23:28 de
drwxr-xr-x   3 jason  staff        96 May  2 23:28 en
drwxr-xr-x   3 jason  staff        96 May  2 23:28 es
-rw-r--r--   1 jason  staff     54121 Feb  2 11:10 fantomas-tool.deps.json
-rw-r--r--   1 jason  staff     57344 Feb  2 11:09 fantomas-tool.dll
-rw-r--r--   1 jason  staff      9136 Feb  2 11:09 fantomas-tool.pdb
-rw-r--r--   1 jason  staff       154 Feb  2 11:10 fantomas-tool.runtimeconfig.json
drwxr-xr-x   3 jason  staff        96 May  2 23:28 fr
drwxr-xr-x   3 jason  staff        96 May  2 23:28 it
drwxr-xr-x   3 jason  staff        96 May  2 23:28 ja
drwxr-xr-x   3 jason  staff        96 May  2 23:28 ko
drwxr-xr-x   3 jason  staff        96 May  2 23:28 pl
drwxr-xr-x   3 jason  staff        96 May  2 23:28 pt-BR
drwxr-xr-x   3 jason  staff        96 May  2 23:28 ru
drwxr-xr-x   3 jason  staff        96 May  2 23:28 tr
drwxr-xr-x   3 jason  staff        96 May  2 23:28 zh-Hans
drwxr-xr-x   3 jason  staff        96 May  2 23:28 zh-Hant

Œª any ‚Üí Œª  master-vnext* ‚Üí dotnet fantomas-tool.dll --version
Fantomas 2.9.2.0
Œª any ‚Üí Œª  master-vnext* ‚Üí ~/.dotnet/tools/fantomas --version
Fantomas 2.9.2.295

```

If I install the dotnet-cli tool I get the latest nightly version, but the nightly nuget package seems to be old. I tried both fantomas and fantomas-tool from myget.

**Comment by nosami** [comment]
Never mind... looks like the restore went wrong. I can see the latest package that references FCS 27.0.0.1 on myget. Thanks!

**Comment by nojaf** [comment]
[Trivia branch](https://github.com/fsprojects/fantomas/blob/trivia/paket.dependencies#L6) is now on FCS 31.
Don't hesitate to create a new issue if you wish to have a beta on NuGet for this.
