### ISSUE TITLE
Intrinsic type extension member signatures are erased

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas#413]
Consider signature file:

```fsharp
namespace ExtensionParts

type T =
    new: unit -> T

type T with
    member Foo: int
 
```

It's being formatted to the following with extension member signature being erased:
```fsharp
namespace ExtensionParts

type T =
    new : unit -> T

type T

```

Format config:
<img width="308" alt="screenshot 2019-02-07 at 17 42 07" src="https://user-images.githubusercontent.com/3923587/52418772-da5bff00-2aff-11e9-8b09-709f89fe8536.png">

Parsing options:
<img width="1030" alt="screenshot 2019-02-07 at 17 42 45" src="https://user-images.githubusercontent.com/3923587/52418810-ea73de80-2aff-11e9-8d5e-07d23b52972b.png">

**Comment by nojaf** [comment]
Repro: https://jindraivanek.gitlab.io/fantomas-ui/#?code=HYQwtgpgzgDiDGEAEBRAHgFwsKBLA9sAAogBOGUAsAFA0YCeMyAKkgLw1JdLAQDuALiQBXYLgxIAtAD4kzGnUYskfcQAtO3SGABGEUkgBi+fENzAMNIA&filename=C4WwDgdAZgzglkA
