### ISSUE TITLE
Is Fantomas still supported for VS? Couldn't find it?

### ISSUE THREAD

**Issue by halcwb** [fsprojects/fantomas#415]
Is this still supported for VS? Couldn't find it?

_Originally posted by @halcwb in https://github.com/fsprojects/fantomas/issues/3#issuecomment-463985248_

**Comment by nojaf** [comment]
There is no recent VS extension for Fantomas.

**Comment by halcwb** [comment]
Ok, I just made it an target in my build file, so that is fine now.

**Comment by Chiel92** [comment]
@halcwb Could you perhaps post what you did to make visual studio use the formatter?

**Comment by nojaf** [comment]
Hi, @deviousasti made an extension for this https://marketplace.visualstudio.com/items?itemName=asti.fantomas-vs

**Comment by dsyme** [comment]
Repo now at https://github.com/fsprojects/fantomas-for-vs
