### ISSUE TITLE
When running the tool for a fairly large script file (1000 lines) nothing happens

### ISSUE THREAD

**Issue by halcwb** [fsprojects/fantomas#416]
### Description

When running the tool on a script file, nothing happens

### Repro code

[Script.zip](https://github.com/fsprojects/fantomas/files/2868830/Script.zip)

**Comment by halcwb** [comment]
Actually, the command line tool is doing nothing at all.

**Comment by nojaf** [comment]
I'm actually able to format this with the command line.
What settings do you use? What OS?

**Comment by halcwb** [comment]
This happened with git bash on windows 10. But using powershell it runs fine.
