### ISSUE TITLE
Blacklist files or code blocks

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/fantomas#420]
If one reaches a file that Fantomas can't handle for whatever reason, currently you're just "stuck" (unless you maintain a specific list of "good" files). Is there a way to provide a list of files that fantomas should ignore?

Alternatively, is there perhaps a way that one could have fantomas ignore specific blocks of code in a file?

**Comment by prosconi** [comment]
Are you thinking of something like a ``.gitignore`` ... ``.fantomasignore``?

**Comment by jindraivanek** [comment]
I think something like

`//#FANTOMAS OFF`

code block that will be ignored by fantomas

`//#FANTOMAS ON`

will be good addition.

**Comment by nojaf** [comment]
I would prefer that the comment marks the entire file as not to be formatted.
Having a mixed model of some blocks formatted and other blocks not will lead to a headache for sure.

**Comment by nojaf** [comment]
Hi @isaacabraham, we are thinking about introducing a new directive that we always add when we format the code. That way we can ignore the block that negates this directive.

For example:
```fsharp
#if !FANTOMAS
let foo = 42 // Never going to be formatted
#endif
```

Would such a thing work for you? Then I theory you could have pieces of a file that is not being formatted.

**Comment by ErikSchierboom** [comment]
I would love to have a `.fantomasignore` file. It is similar to e.g. how git and prettier work.

**Comment by nojaf** [comment]
I published a first version with the new `.fantomasignore` file support: https://www.nuget.org/packages/fantomas-tool/4.1.0-alpha-001
Please give this a spin and let me know if this is workable.
You can find some docs [here](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore).
