### ISSUE TITLE
Formatting of ast nodes results in incorrect formatting

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/fantomas#424]
### Description

Formatting of ast nodes results in incorrect formatting

### Repro code

![screen shot 2019-03-04 at 16 29 19](https://user-images.githubusercontent.com/588746/53747277-ca370580-3e9a-11e9-82bc-625b6fb37395.png)

```fsharp
        static member JsonObjCodec =
            fun (bb : option<Int32>) (oo : option<Int64>) ->
                { bb = bb
                  oo = oo } : TestFieldOrderings.NestedMessage
            |> fun (f : option<Int32> -> option<Int64> -> TestFieldOrderings.NestedMessage) ->
                Fleece.Newtonsoft.withFields<option<Int32> -> option<Int64> -> TestFieldOrderings.NestedMessage, IReadOnlyDictionary<String, JToken>, Fleece.Newtonsoft.DecodeError, TestFieldOrderings.NestedMessage, String, JToken>
                    (f)
            |> fun (codec : (IReadOnlyDictionary<String, JToken> -> Result<option<Int32> -> option<Int64> -> TestFieldOrderings.NestedMessage, Fleece.Newtonsoft.DecodeError>) * (TestFieldOrderings.NestedMessage -> IReadOnlyDictionary<String, JToken>)) ->
                Fleece.Newtonsoft.jfieldOpt<TestFieldOrderings.NestedMessage, Int32, option<Int64> -> TestFieldOrderings.NestedMessage>
                    ("bb") (fun (x : TestFieldOrderings.NestedMessage) -> x.bb) (let _bind_72,
                                                                                     _ = codec
                                                                                 _bind_72,
                                                                                 let _,
                                                                                     _bind_73 =
                                                                                     codec
                                                                                 _bind_73)
            |> fun (codec : (IReadOnlyDictionary<String, JToken> -> Result<option<Int64> -> TestFieldOrderings.NestedMessage, Fleece.Newtonsoft.DecodeError>) * (TestFieldOrderings.NestedMessage -> IReadOnlyDictionary<String, JToken>)) ->
                Fleece.Newtonsoft.jfieldOpt<TestFieldOrderings.NestedMessage, Int64, TestFieldOrderings.NestedMessage>
                    ("oo") (fun (x : TestFieldOrderings.NestedMessage) -> x.oo) (let _bind_74,
                                                                                     _ = codec
                                                                                 _bind_74,
                                                                                 let _,
                                                                                     _bind_75 =
                                                                                     codec
                                                                                 _bind_75)
```

This should actually be rendered like this:

```fsharp
        static member JsonObjCodec =
            fun (bb : option<Int32>) (oo : option<Int64>) ->
                { bb = bb
                  oo = oo } : TestFieldOrderings.NestedMessage
            |> fun (f : option<Int32> -> option<Int64> -> TestFieldOrderings.NestedMessage) ->
                Fleece.Newtonsoft.withFields<option<Int32> -> option<Int64> -> TestFieldOrderings.NestedMessage, IReadOnlyDictionary<String, JToken>, Fleece.Newtonsoft.DecodeError, TestFieldOrderings.NestedMessage, String, JToken>
                    (f)
            |> fun (codec : (IReadOnlyDictionary<String, JToken> -> Result<option<Int32> -> option<Int64> -> TestFieldOrderings.NestedMessage, Fleece.Newtonsoft.DecodeError>) * (TestFieldOrderings.NestedMessage -> IReadOnlyDictionary<String, JToken>)) ->
                Fleece.Newtonsoft.jfieldOpt<TestFieldOrderings.NestedMessage, Int32, option<Int64> -> TestFieldOrderings.NestedMessage>
                    ("bb") (fun (x : TestFieldOrderings.NestedMessage) -> x.bb) (let _bind_72, _ = codec
                                                                                 _bind_72,
                                                                                 let _, _bind_73 =
                                                                                     codec
                                                                                 _bind_73)
            |> fun (codec : (IReadOnlyDictionary<String, JToken> -> Result<option<Int64> -> TestFieldOrderings.NestedMessage, Fleece.Newtonsoft.DecodeError>) * (TestFieldOrderings.NestedMessage -> IReadOnlyDictionary<String, JToken>)) ->
                Fleece.Newtonsoft.jfieldOpt<TestFieldOrderings.NestedMessage, Int64, TestFieldOrderings.NestedMessage>
                    ("oo") (fun (x : TestFieldOrderings.NestedMessage) -> x.oo) (let _bind_74, _ = codec
                                                                                 _bind_74,
                                                                                 let _, _bind_75 = codec
                                                                                 _bind_75)
```

**Comment by 7sharp9** [comment]
This is to do with intermediate let bindings in ast elements, for example a quoted expression such as this:

```
Expr.Lambda(codec, Expr.Call(jfieldoptMethodInfoTyped, [fieldName; getter; Expr.TupleGet(Expr.Var codec, 0) ; Expr.TupleGet(Expr.Var codec, 1)]))
```

Where there are let binding interlaced in the fanal expression: `Expr.TupleGet(Expr.Var codec, 0)` etc

**Comment by nojaf** [comment]
@7sharp9 any idea if this still is a problem?
[This seems to work ](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAYrLGALwA6ATmQHYQQA%2BYAQgIYViwBmYAltepRp0wAZ3Qt0PaGAC2iGQCNE7AFIjY1APIKAVgGEEiaeSq1hdTgFdaACgUKwaWNkkaAPAEl%2BAZgBMAPgBKMBsiRw4XHncvdAA2ABYgsABaf0Ezc3NgMHtSHIV0zKK6MJIOYgBfcIAVRDF8HkQAG3hNCiQKPgBzEQA6ADk69ER4AFk6kRYuxEKi%2Bn8wK1tuJ0jonwCUhedXak9%2BBIXUsFr6xpa2ju6%2BwbER8ZFJ6eDU2eKIfCbEI0QBxAB3dAadScdC9f48dAACwazXgIjcOyiexifiO2zWKIOiS2JyGsIu7WU1z%2BdzGEymiAANGAPAAlRAsVrUJqYAAiUl2bEwbgAyuhOtQujSVNVYABrRDUfw0z7faC-QaA4FcMFsoyGACiFAosAoNNO6AJrSJgp6pOG5MelJp-LNIrFkulb3ewhsnECLuE80W1hCcCQ0jQNnpjOZrI50C5FB5du6DolUvRYAZIksTXQiMx%2B3QaNxSPWcRxx0NxsuxKFNyG9wp01lXx%2Bf2V1BBao1SG1uooSQAVCFS%2BcTVdKxaa9bprjQ0zNCz2Zzkdy%2BQL42BRYnpYEXmlTK6Pg2FU2gS3Vb0dJxB5oXG4B3Dy2aq2SHk9qbSNjSC1ii8mb4Th%2BbbpaT6UtuQi7m6ZCQPYEHBO6fo2AAHjU%2BIXqaJIAWOz5bmA8G9PYMFfOgYAAPoKHw8BEQA7L4NJEXkAZGF6YFMcxLGsRAJFkZR1GMWxvF8fxBHETRpHUORFHeKQPH8dJMnMfR0BSbJSnKRxomUd4no7nMCxLP6hhBiEU7hnOUYLjGS72qujpJriqbppmH45ocuI-kOFb-tWVrPvW8qKgCR6tr06r0Z2eq9v2yG3qhI7oV5lKTgy06zpG0axsuQoJk6QRbopdByo2SoBSeZ4Xlerl3mhnlAXWr5FgakW-u5D6AbWiAgRkTE2BBRDQSEukIUhZxRX%2BzUYZSWE4UQ%2BGIIRqlifENF0fpuXKatrFzZRC0rWtO3MYJRHCZxFEAKxLYG227Zd7wbSdgSQFS4BQCIM2SJWqBgAA2o9ECgJkkAACRYLg72QHw6D3d9dAAwAbiwTSWMgaBfcUAAMD3FJAXhIPwvI8AAXsg6NFPEkMQAAupDFREz9pNQIDOCI1AYMQ39-2w-DjPI0UACM1PmJAowsPBAAyfCIMLUpdNCLM874KO0xTwhU5Dv38-TwNoJBRBNDLwgw3DCPvVzmTUbTECQLy8hSLATQaAAgugmqiZonCi9QhNm4scPPQrlN86revq4zWs27rUNswbnOe94fN67y2AsAqTCIJweqIAACmwLByMMFBh8IAoI77Sv%2B7TANA8HCja-ndPs4bSOewtnsWwnScp2nwuwP8yjQCwz1eNDsC97sNcQIXiDF3QyvCAH4cVyDVeh7HteR0bnvHcv5vx4niDJ6nFCIAAqtguAUL3-fUIPw-IqPXtND7mSK1Ppes-PmuLzry-6xza-FLEm9QG3m3feiA9BND7iIAwLZC5Rj1LfTg3sJ6Pz9irMuQcF7Vy-hHH%2BDdigUQAS3Hee807jEUMoeBiDJ4QGnnQWe5t0Hv0wWguuUdigAA4CFAN3u3A%2BBhbbUAoffJB5gn7UJfmrN%2BUAP412-vXT6nsACcnDW6IDtqCZQBgZAyBYLfceVCwA0Jpq-BmGCl7MNXrgnmaNm5cOIQfS2Mhrb8MEQ-ERKCZ5oMkSHT%2B5icHyOKNzXmNiVFqNzg4pxGhdEUCLsgkuqDjEaykUw1mLDf6ywIVjKU6AZzVBjAAdUhFCFxwjhCiIMeIwOXjpFYNSZYzI3MY7BJ3nbXU1h4DqiaDwRxucokxLcXEjxCTg7MxqRY-xPMm4Y0FvBDwnBqhQilJqIRvIoR6nQAU%2BA0sAHxHlrE5%2B8SJEmM1iM3xcjjbmG5hvZu0yvDnngpeZQEg9SangtgA%2Bjwb4AOOrs-p%2BzBmHMSaDfgMjsFnM9tzf%2B1yhYMjgO0DZWzG4-NKe42hnijlM2BaMvx5zhDc3wVC%2BCLSKAsEwG0UWYh4VFO2UiugZTDFgDoXTLxJyUljJxXQbmHCCUADVI5MDIt0Slt8dn6PpYy8u6KgXgyxWCgJSiCX4GsKZDQ-LRKCp4JsqliLRUVLnpKllatanjJNtYqZQs2SwHQAAcRmi8t5ExkRCq%2BTS8mKKjEAsrskw1bLPa%2BCCVM%2ByPBOnuyYLbaA4omDEvDTNEQM5eTZ1ATbSwMgBEAIQUInVBzKmSuqac1hRRfCmwxkqYN3D0DdylNUBm6pzzUEhMiO2olSFKAoCIYpmb-nZsBbm1l2LfWNIxgAaW%2BNgWZ8ypReHjXIN2HtijptccigZqKhkgwNYHI17KIC%2BEmUUAWQslmOJEFCJ12q9liKzXq7tXr10%2BuKL4K5GNcZCi%2BC0royasl5MQAoUYhh21nvKRe%2BhVTr3hw3b6yFGM7adK6NQRV1BlXUFxjBiQlgD5ikyfwCQnzPbzpKbSt1DK0VXrMb22VBb8WQYzMoagWHobiw0F0Ztyga18HrcCP9vzz2dsvZ6kj3q%2B13q5Y%2B5cUYf1IA44uqej0yZE1BiIfAIgeDvVwyACoQA)today but I'm not sure if that tells us anything.

**Comment by 7sharp9** [comment]
Im not sure, Ive not use Falanx since leaving jet.

**Comment by nojaf** [comment]
Anyone at Jet we can poke to find out maybe?

**Comment by 7sharp9** [comment]
Jet is no more.

**Comment by nojaf** [comment]
Ok, then I guess I can close this here.
