### ISSUE TITLE
global.json specifies outdated dotnet sdk

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas#426]
Having a newer SDK installed I cannot build the solution in command line.
```
eugene@unit-937:Developer$ dotnet --version
2.2.105

eugene@unit-937:Developer$ cd fantomas/

eugene@unit-937:fantomas$ dotnet --version
A compatible SDK version for global.json version: [2.1.503] from [/Users/eugene/Developer/fantomas/global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

eugene@unit-937:fantomas$ ./build.sh 
A compatible SDK version for global.json version: [2.1.503] from [/Users/eugene/Developer/fantomas/global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
A compatible SDK version for global.json version: [2.1.503] from [/Users/eugene/Developer/fantomas/global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
./build.sh: line 8: .fake/fake: No such file or directory
```

**Comment by auduchinok** [comment]
The problem is link in error output make one download the latest version, 2.2.105.
If I download and install 2.1.503 manually it starts to work.

**Comment by nojaf** [comment]
Hello, it does make sense to me that you would need `2.1.503` on your machine.
The go.microsoft link leads me (on Windows) to https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x. So I'm not sure where it is taking you.

Anyway, what actions do you suggest we take here?

**Comment by auduchinok** [comment]
> Anyway, what actions do you suggest we take here?
I'd probably list .NET Core SDK 2.1+ as a required tool in readme and wouldn't enforce that particular version as people may have different (especially newer) ones installed that are fine for the build.
