### ISSUE TITLE
Change space before colon default to false

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#429]
I propose that we change `SpaceBeforeColon` to false as a [default](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/FormatConfig.fs#L31).

[Example](http://ratatosk.dynu.net/fantomas/#?code=C4TwDgpgBAYg9nKBeKBvKAhAhgJwFwDOwOAlgHYDmA3NjgEx7nAC+AsAFAcA2EwUWUPFCbIoADiA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsa2GiEOYTAmMvDCMXh4qAFBiY6Yqem82roGRhC5weSQsAhSEAAqvACejKzx9gBKMB6wvFLIcAAiMOhqqLyo8AxxhKoJoU5e+jjQo2oMusVV+YF68ACy+rCdMAC+QA)

[The style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-record-declarations) doesn't have this and Don seems to have made it default in the [compiler](https://github.com/Microsoft/visualfsharp/commit/d5f5bd005aebdd20088a4be20939aea0e9da29fb).

@jindraivanek thoughts?

**Comment by jindraivanek** [comment]
I agree, we should align default style with the style guide.
