### ISSUE TITLE
Excessive line breaking

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/fantomas#43]
I have line breaks set at 120, and I had this line:

```
              let details = cells.[4] |> element "a" |> attr "href"
```

which ended at line 79, but it was still broke down like this:

```
              let details = 
                  cells.[4]
                  |> element "a"
                  |> attr "href"
```

I actually don't mind in this case, but just posted the issue to make sure this was intentional and not a bug, as it doesn't seem consistent because fantomas does the opposite for functions. I had this:

```
    let radians2Dist radians radius = 
        radians * radius
    let degrees2Dist degrees radius = 
        radians2Dist (toRadians degrees) radius
```

and it was converted to this:

```
    let radians2Dist radians radius = radians * radius
    let degrees2Dist degrees radius = radians2Dist (toRadians degrees) radius
```

**Comment by nojaf** [comment]
> I need empty lines for readability purposes

The situation has improved in #434, please create a new issue with additional suggestions if necessary.

**Comment by OlegAlexander** [comment]
Hello. I also feel that Fantomas adds too many line breaks by default. Thankfully, I'm able to control this with the Max... settings. However, I can't find a way to control the following examples:

Code:
```fsharp
open System open System.IO
```

Result:
```fsharp
open System
open System.IO
```

Code:
```fsharp
type JpgDir = string type TifDir = string
```

Result:
```fsharp
type JpgDir = string
type TifDir = string
```

Code:
```fsharp
module A = Array;; module L = List;;
```

Result:
```fsharp
module A = Array
module L = List
```

Code:
```fsharp
let trace x = printfn "%A" x; x
```

Result:
```fsharp
let trace x =
    printfn "%A" x
    x
```

Code:
```fsharp
let boolToInt x = match x with | true -> 1 | false -> 0

let boolToInt' = function | true -> 1 | false -> 0
```

Result:
```fsharp
let boolToInt x =
    match x with
    | true -> 1
    | false -> 0

let boolToInt' =
    function
    | true -> 1
    | false -> 0
```

Of these examples--most of which I realize are not idiomatic F#!--the last one with the pattern match is my highest priority. If you'd like, I'll be happy to open a new issue just for the pattern match example. Thank you.
