### ISSUE TITLE
Using fantomas with dotnet-format

### ISSUE THREAD

**Issue by cartermp** [fsprojects/fantomas#430]
We'd like to pull in a dependency on Fantomas for the dotnet-format tool (tracking issue: https://github.com/dotnet/format/issues/39).

Technically it would be straightforward to do, since the tool just does some orchestration of the C# and VB code formatters today, and it would just shell out to Fantomas when encountering F# projects. But there is a question on policy, which I propose as follows:

* Issues for F# formatting are moved to this repo
* Since Fantomas is an OSS project, there is no support policy that either Microsoft or Fantomas maintainers must adhere to

Thoughts? cc @jmarolf

**Comment by jindraivanek** [comment]
If I read that policy correctly, it doesn't mean any change for us, so no reason to disagree with that.

It would be great if new F# formatting issues would be created through http://ratatosk.dynu.net/fantomas site.

**Comment by jmarolf** [comment]
@jindraivanek sounds great! Just wanted to make sure it was fine to package fantomas inside _another_ global tool.  I'll make sure that people posting on the dotnet/format repo know to file bugs on http://ratatosk.dynu.net/fantomas if they are fantomas specific

**Comment by cartermp** [comment]
The main thing is it may be reasonable to expect more bugs coming in as this does open up fantomas to more use. Just wanted to make sure that was okay 🙂 

I'll close the issue as we'll take care of thing on the dotnet-format side. Let us know if you have any further questions/concerns!
