### ISSUE TITLE
Record option with attribute gets an additional space with PreserveEndOfLine

### ISSUE THREAD

**Issue by ForNeVeR** [fsprojects/fantomas#442]
### Description

When formatting this code:

```fsharp
type Options = {
    [<DefaultValue>] a: string
    b: bool
}
```

with `PreserveEndOfLine` enabled, it gets an additional space:

```fsharp
type Options = {
     [<DefaultValue>] a: string
    b: bool
}
```

When formatting the resulting code again with the same option, it will get another space. Each reformat will increase indentation of the first line by one

### Repro code

[Repro link](https://jindraivanek.gitlab.io/fantomas-ui/#?code=C4TwDgpgBA8mwEsD2A7AzlAvFA3gWACgpioBtAHgBEIAzAQwFcAbYANTqYYgD4BdKOgC4oaYACcEKAOaESUAEbD5SJE0IBfIA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwi8XjhjlEMPA3QB7ADZ6IAQXiSoshUqIzUBoZrSYAQjBl7+J3tXxx4tvaOICgYMG4e-ADChsaBDhohzjAmMvDCMXh4qPHBoZip6bxaOvpGELmJkLAIUhAAKrwAnoysleQASjCesLxSyHAAIjDoBqi8qPAMcYR2CU5h3no40MMGDDpF7SGquvAAsnqwlQC+QA)

**Comment by auduchinok** [comment]
This happens for other cases with attributes as well. I've seen it for parameters patterns too.
I hope https://github.com/fsprojects/fantomas/pull/434 will fix them all. :)

**Comment by nojaf** [comment]
This behaviour can't occur anymore after #434.
