### ISSUE TITLE
PreserveEndOfLine+SpaceAroundDelimiter add an unnecessary space before closing brace

### ISSUE THREAD

**Issue by ForNeVeR** [fsprojects/fantomas#443]
### Description

This code:

```fsharp
type Options = {
    a: string
    b: bool
}
```

Gets formatted as this with `PreserveEndOfLine` and `SpaceAroundDelimiter`:

```fsharp
type Options = {
    a: string
    b: bool
 }
```

### Repro code

[Repro link](https://jindraivanek.gitlab.io/fantomas-ui/#?code=C4TwDgpgBA8mwEsD2A7AzlAvFA3gWACgpioBDALijWACcEUBzQkqAI0taSQBtCBfIA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwi8XjhjlEMPA3QB7ADZ6IAQXiSoshUqIzUBoZrSYAQjBl7+J3tXxx4tvaOICgYMG4e-ADChsaBDhohzjAmMvDCMXh4qPHBoZip6bxaOvpGELmJkLAIUhAAKrwAnoysleQASjCesLxSyHAAIjDoBqi8qPAMcYR2CU5h3no40MMGDDpFKmqJiKq68ACyerCVAL5AA)

**Comment by nojaf** [comment]
PreserveEndOfLine will be deprecated soon, it looks ok [with the latest code](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=C4TwDgpgBA8mwEsD2A7AzlAvFA3gWACgpioBDALijWACcEUBzQkqAI0taSQBtCBfIA).
