### ISSUE TITLE
Include directive with __SOURCE_DIRECTORY__ is removed and replace

### ISSUE THREAD

**Issue by halcwb** [fsprojects/fantomas#447]
### Description

Install fantomas as a global tool on mac os. Create an fsx file. Add the following code:

```
#I __SOURCE_DIRECTORY__
#load ".paket/load/net471/main.group.fsx"

```
Run fantomas

### Repro code

https://jindraivanek.gitlab.io/fantomas-ui/#?code=PQgEGUGMCcEsAcAusB2BzUiAWBTUOVlo8BJAYQFVQBDeeAKBGHoGITQB9D8AeQoCUyAUQ4AREvyFkAKj34BNLqwA2Ae2oATUACIAdPGoBrHImBrNwFCYAsAdgCMwALbVUutNFUBXeLoBmAM4AHtr0QA

On mac os this is replace with just `/`.

**Comment by nojaf** [comment]
Hi, I think I was able to reproduce this and found a fix.
Could you verify by downloading an [early build](https://github.com/fsprojects/fantomas#early-builds) and testing it out?

**Comment by jindraivanek** [comment]
Closing as it is [fixed](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=PQgEGUGMCcEsAcAusB2BzUiAWBTUOVlo8BJAYQFVQBDeeAKBGHoGITQB9D8AeQoCUyAUQ4AREvyFkAKj34BNLqwA2Ae2oATUACIAdPGoBrHImBrNwFCYAsAdgCMwALbVUutNFUBXeLoBmAM4AHtr0QA) in v3.0
