### ISSUE TITLE
Publish 3.0.0 to NuGet.org with a preview flag

### ISSUE THREAD

**Issue by nosami** [fsprojects/fantomas#448]
### Description

I am currently using fantomas from the nightly feed because I need the [FCS 28.0.0 commit](https://github.com/fsprojects/fantomas/commit/6b2133c8fa9018f1183308040c516c38b0de4c42)

However, the VSMac build has broken [3 times](https://github.com/mono/monodevelop/pull/8191) in [3 days](https://github.com/mono/monodevelop/pull/8186) because the version that we reference keeps being [removed](https://github.com/mono/monodevelop/pull/8167) from the myget feed.

Would it be possible to put a 3.0.0 package on NuGet with a 'preview' flag set? Alternatively, I could create my own forked package but this doesn't seem desirable.

Thanks!

**Comment by nojaf** [comment]
Hi, I've just published 3.0.0-beta-001 on [Nuget](https://www.nuget.org/packages/Fantomas/3.0.0-beta-001). Should be visible in an hour.

**Comment by nosami** [comment]
Thank you!
