### ISSUE TITLE
Preserve more newlines

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#449]
In light of recent improvements by the Trivia PR (#434) we would like to discuss the addition of a new setting. 

With this setting, we could preserve newlines that were found in the source after certain tokens.
Example:
```fsharp
let add a b =
    a + b
```
This sample would now be formatted on one line as it is very short.
If personal preference allows it, we could keep the newline after the `=` sign.

A similar thing could be done with chained function calls.

```fsharp
let config =
    Builder()
      .A()
      .B()
      .C()
```
Fantomas would format this one line because it is short.
With this new setting, we could detect that if a line begins with `.`, we keep the newline.

By default, we would set this setting to false.

Thoughts and opinions?

//cc @jindraivanek @auduchinok

**Comment by auduchinok** [comment]
We'd enable such option by default in Rider to work similarly to other languages in the platform.

An exception where I'd expect these newlines not to be preserved is when the line doesn't fit to desired width.

**Comment by nojaf** [comment]
Another example I can come up with is pattern matching:

```fsharp
match meh with
| Foo -> 
  printfn "foo"
| Bar ->
  printfn "bar"
```
We could detect that nothing (or all spaces) follow after the `->` sign. Meaning we should add a newline after the pattern.

**Comment by reaysawa** [comment]
When I'm writing something, I always do line-breaking regardless, be it after = or ->. That's because I'm still figuring out what I exactly want to do and I want to keep typing forward without causing problems.

On the contrary, imagine that as I'm typing something, I need to constantly keep thinking about whether I should've added a newline or not, way back there; that's just interrupting my train of thought to care about formatting, **something Fantomas should care about for me**.

I'm also afraid that such option would make the code look inconsistent in general after refactoring. Imagine another case where you refactor a large function with a lot of code

```
let bigFunction myArgument =
    let myVariable =
        myArgument
        |> function1
        |> function2
        |> function3
     ...
     ...
```

But later you break this big function into two separate functions and its body becomes small

```
let bigFunction =
     bigpStep1 >> bigStep2
```

Now you have a "lingering" newline there that's probably unintended, [as trivia would normally format everything in a single line](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=LAKANgpgLgBARgSwOYDECuA7AxlBB7DGAXlBjLMSQAcBlKCKgRhgD4X5k6GAmIA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsa2GiEOYTAmMvDCMXh4qAFBiY6Yqem82roGRhC5weSQsAhSEAAqvACejKzx9gBKMB6wvFLIcAAiMOhqqLyo8AxxhKoJoU5e+jjQo2oMusVViQDSMDDIWDAA7ptKRcKd+YF68ACy+rA3AL5AA). I guess it also opens up the question of whether composition/piping operators should always split everything vertically, because I'm noticing it only splits up the body if there are three of more functions being chained in a row.

**Comment by reaysawa** [comment]
> Another example I can come up with is pattern matching:
> 
> ```fsharp
> match meh with
> | Foo -> 
>   printfn "foo"
> | Bar ->
>   printfn "bar"
> ```
> 
> We could detect that nothing (or all spaces) follow after the `->` sign. Meaning we should add a newline after the pattern.

Now, about `match` my opinion is different. I think code looks disconcerting when it's like this:

[One of the branches is small, so only that one branch is in a single line](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=LYQwLgxgFgBMCeA1EAnAliARgGwKYwHc0woBYAKAB8YBvGAMTV2wBMYBeGARhgF8YAtAD4YIRLhTwAMqgDmuegFcAdhDBoA9soBCGlvADqxKFI1gAzgHkAZgGE9uAJLLzaFrgrU6jZm04AmPkERc1BsbCVlT1oGJlYOGABmIOFRcUkZFHlItU0dPUNjUwsbe3dnV3cgA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZHEAM5FATjAM4weANxgBRaAHkAZgBkGEGEWmoANoPKIYeBugD2qvRACC8CVBnzFytRpAoMMAEIxpevsZ7V8ceEXg8ODCaaJgubnwAwgZGNurB9qEwxtLwQtF4eKj+gQkOmClpPFo6+oYQOUHkkLAIkhAAKjwAnoyscXYASjDusDySyHAAIjDoqqg8qPAMsYQq8SGOnno40COqDDpFlQkA0jAwyFgwAO4bioVCHXkBuvAAsnqw1wC+QA)

If one of the branches need to go to the next line, then every single branch should follow suit and go under also, but maybe that's a different setting or something.

**Comment by nojaf** [comment]
I would also like to preserve newlines before `|>`.
Consider the following code:
```fsharp
    let watchFiles =
        async {
            printfn "after start"
            use _ =
                !!(serverPath </> "*.fs") ++ (serverPath </> "*.fsproj") // combines fs and fsproj
                |> ChangeWatcher.run (fun changes ->  
                                      printfn
                                          "FILE CHANGE %A"
                                          changes
                                      // stopFunc()
                                      //Async.Start (startFunc())
                                      )
            ()
        }
```

When this is formatted it will look something like:
```fsharp
let watchFiles =
    async {
        printfn "after start"
        use _ =
            !!(serverPath </> "*.fs") ++ (serverPath </> "*.fsproj") |> ChangeWatcher.run (fun changes ->  // combines fs and fsproj
                                                                                                      printfn
                                                                                                          "FILE CHANGE %A"
                                                                                                          changes
                                                                                                      // stopFunc()
                                                                                                      //Async.Start (startFunc())
                                                                                                      )
        ()
    }
```
If #559 was not a problem I would have a workaround for this so it is not a big must to have this.
@jindraivanek what do you think? Does it make sense to you to also include `|>` as scenario for  `KeepNewline`?

**Comment by nojaf** [comment]
The `KeepNewline` setting will be removed in v4.

**Comment by reijerh** [comment]
@nojaf I think I'm running into a situation where this featured would come in handy: [example in online tool](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpExEAbbASzwAsB9cqgIwB0AnV9Dr2AxdGACilGrQB0AdQAKAMR7dO6APTKwAYUzoA5ABcwAMyoBzAK7tSsU-tqwA7mF2wwtTADdS6KiTBM8uvDAAQQA5ABEwLx8CKhj0YzBMfV1aUjwcUl0qXAVVMABJAwKwPER9bQBZTAAPfPQjaoB5fnYk2HYhaoILPDwqWB1HZ0wXE1owN0xyU1J8l3dPb1I-AIAaMGZrR1SwGP54MGgp8kDMCzBsWA8DpzAB5ap0RFzlF7BmrIHAuaPBFMeANZ3AwoN4ARnEYAASvh%2BNB9E87EwnoEDO0wI8GmQuj0%2Bl83gAmSEACQWJThVCmjgsSVw6H0aPYu1iFEelhabXYeAUb3UA107Co1wU5DKG0wAC8wAAKACUYAAvGAANoKCAQNGwZhnMCsSCYPDwdJGzDwA1Gk1mw3mm3Ww3pU0Ou1Wy3Gt2O03m9J6tXqvVej0u%2B2e522oOYD1hgOuwPGgN6sAAHwAfIZYFqzr6IHqCT6lOq0xmmXqACx5rgF-3Bo0JlOF7WcfN%2ByAAVnL6AAujylHkYVMALR2drkeAisXMR7wR7GQJyxUqrO6yB80z0xDsABqUxmtdTACFJ9PxPdJJgAJ4ygyri5gfup7DiFf02WLvVhRDQCx03S7sAH9BTvE4jQNgBzSlegjYLeqbvp%2BiDfi%2BTYQHkACq6CmHgphTOsmz6HQ9iBCkpBTgYBjrgIJCLv%2BgHGMBoGXteUF3gU6BwQhS7RnG9qWlGobBpGfExkJXEmu2laQAAyroiAEBJVASs8kBJvuh5AboQ6nhe0rgYx0GGOQsBJBc4hSTJckKbK6w6YIiJbuQN7MY8CKIHYdnKWAEllKZsnyYgsrygoXZKGODLpg2iqLsqYBggA3GABJgEFFbqnWAAyNC6OI2CYAQDGCNUekFQA1NFiHJRAaUZVlOV5WABXMcV8VlYIKWpiY6DtMgqzgFApS6Fk8R4KgKo9RAoAFhAkAACS6Ge-DDZATmQN1E1QFNkzTMgaDKqNE0AAwratUB1Eg9LmV1u0FiWl2JbtAC%2Bh1jTd02zfNaCLfSy3Pet25bSNR3RY9E2QFU1TpU8qUCMYKRfQDYIEntN0dvdQPjcDM1zX9kDMOm5Cw%2BjG0zMNO0AwSQMFpJ8HeLABnoEEuhCABjQGODF0AwYUylEjKO7WjFMY29UA4zT%2BP84Tf0k0dADM5PqpJRAkHuiCMog0hnBk0nsKLE0CjM3MFg9vPfa9WPC3jsvTeLxM3RAJay5NEkK4gSsq6l9jrkcpR1G4sBHJ86DawWuuIPr6qGwWfNywLpu44Ha1W9tNtgC29tQI7xDO8rnUoQQLSe4g3u%2B0k-QB6nHMnCHq3IwbqPG5jC1m3Hlu-dbAMAGyp-LGcu516jkAaeB8ug-jsKY8LtHHGqc5XE3V2HterS99fvY3Fs-ZtrdHQA7J36eK1nFgVPBzDrpPhjT6HEDh%2BqkeTdHDex2vCf-UdAAcu9Oz3Fh8rTZ-l1zVceYRzroLbGj9vrP0lqtAAnB-DOQQDCaz5NgbKZ9g6XzANfJ6i974r3ATgyBScwQHSTl3feKtPLUDgL-MuF9AE1yNjgk2D8RZPxbonOGYI4EkAQZrSh1MaFJ3QfQ%2BejD0bMLwawiB7CX6rXhp3E6AhdCNHQAAFXYGeSQVAYa0IrhgrBYBb5rQkULfBBMZFQImmCGWpC96ICCOwKwAF3xMGoJrNBo8Z4FjnlfBe4jl5QCWmwjeHCjpgjtqQ0GhRVGpHQCIUoElbDsF0Fo%2BAOik4lkRiI3xYj%2BYmI%2BroJu68iahLkSnSJNQ6gNGaOuTknRuj4DxKXJOLYsmzyATfEBWMgnSJCbIqxHcKnVBhHAdg8BUnpIBpk-Rfi8kBIKUUwhcMd5DJGe0eAIRTDYBPuwZm%2BRpLYCGqnMEMzclR3ydgUw5AsjIkQLIdo2V%2BrrlUfXYJJT%2BkFjBO-UhayxkVCuTctk9z2CPPcZ3aArhWjwnXPQOwVA0m0EgKc4BTD5k9IIRYohsChkONaGeRo7B0r%2BAmYi1O0zsmYNmectFn03kSyTgjTuoNcXngJUS3Qmztnrj2Qco5RDkWdNRaAy51yqC3OBaC55rzenvMsQWAkXDSEsvxYSjK-zRXioeUkMFpCIXq2hewWF8KYYCuwf40B6LzF9LleqAkZMhl2RmNRacJKz6vzad4jpZq5kWtpTK%2BlpMbEAxBjUWQq54Ql2dfEV1ZKPXqh8ZSs5d98mWrFpi0mETg2gzCLAXQABxMo9TcQlxjS0uNEAE0GKMUvUBq9-Wb1WgScpWaAVirZHuAy0AAR7ihQCMoeAVESQyD-LZzT2Z0PaQwlF5qY5SIxdahlgzg0hBcrcpW6lEACBefwd8RgvD%2ByCABI%2BXKuR-wnZ6qdgqZ0sPNvW0pE0CQrODQAaU3QQaJsS6hDtwKzM9eiKVVq6QtVNUcllHQJN8rNNQRDUDoKWqZ5bbqXu9dS2tZi00LtJti4Ncl4iigcWYb8khEDMAqAgNmR1-5ePjV6wxQHJG3vnbKpOUsSHBqCEwYw6Aw2sX9nJLjSRzCIFUbARR9Ji4DD-QAydojp0%2BtnYxq1zGAZS0Vex6564sBZA8G7eIx6dm7seNokufLx3-pkzkuTqGFOLPTdLe1LbRWs1SjgZgZo%2B6wD6PEFdSI2RSeoxW2j1bcGmLnUpgN0sg1HUgGEGgmBmCihg2ICSZ5xPVH86aujQqsYCHgMzVmUkzyils5h6WmbouMzyyzPz4L2DkAMEigDVLk3zLrUxiLq0pbNui6%2BmSYndB1B7VoCFGWmtJuMa19DoG7OdaXdFjtWgASszwA4pxGz8DSXgOqwFTwi2NJMx4vWY2rMtbQ2FjDynpZPvm2cL%2BiBYt4E-NkR4SREDwDQiXWC-dWj%2B1GxZxNJ2JtncUxdjrE0paQei1JQU8IyNID%2BxesOPUOyHUWngWQfRhpUZAHdIAA)

Perhaps I'm just missing some obvious setting, but it's the first thing I ran into when trying to use Elmish.WPF in Rider.

```
// Can't figure out how to have nice lists AND nice piping at the same time
// If I set 'MaxInfixOperatorExpression' to a high value I have nice lists, but the piped calls are moved to one line
//
// Options I can think of:
// 1. Respect newlines for infix expressions
// 2. Have special treatment for pipeline operators

// Contrived
let baz () = [
    foobar "asdsadsadasdsdsadasdasdasdasdasdsaadsaasdasdasdsadsadsadsadsadasdsa"
    "asdsadsadasdsdsadasdasdasdasdasdsaadsaasdasdasdsadsadsadsadsadasdsa" |> foobar
    "2"
    foobar "4"
    "asdsads" |> foobar
    "5"
]

// Real-world
let bindings () = [
    "CounterValue" |> Binding.oneWay (fun m -> m.Count)
    "Decrement" |> Binding.cmd (fun m -> Decrement)
    // Unusual, but shows the difference
    Binding.cmd (fun m -> Increment) "asdsadsadasdsdsadasdasdasdasdasdsaadsaasdasdasdsadsadsadsadsadasdsa"
    "StepSize" |> Binding.twoWay ((fun m -> float m.StepSize), (fun newVal m -> int newVal |> SetStepSize)) 
]

let foobar =
    [ 1; 2 ]
    |> List.map (fun x -> x + 1)
    |> List.map (fun x -> x + 2)
    |> ignore
```

**Comment by nojaf** [comment]
Hello, this feature was removed for good reason.
Are your examples in the same file? Perhaps you could tweak some values for a specific file.

**Comment by reijerh** [comment]
Yeah, I mean this is just the basic Elmish sample app, but I suppose it happens anytime you have a longish pipeline expression and a list with a pipeline expression in the same file.

Per-file style configuration doesn't seem really viable to me in the long term for larger (team) projects, but I'll look into it, thanks. 

I guess it's just an odd experience that newlines aren't preserved coming from e.g. R#.
