### ISSUE TITLE
Incorrect handling of attributes in static method

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#452]
Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=C4TwDgpgBAglAUBKKBeAUFTUDOwCGwAlgMZQC2EZARhAE5QBiA9kwgNoA8AShAGYA2EYsAgATACJ9CAO0JEm0qMFoBXCAD4AulDzJ0WAwkRA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sJUAvkA)

Fantomas removes the space between "ReflectedDefinition" and "true", resulting in code that does not compile.

(I discovered this in the course of G-Research's testing of the preview version of Fantomas.)

#### Code

```fsharp
type A () =
    static member Foo ([<ReflectedDefinition true>] a) =
        ()
```
            

#### Result

```fsharp
type A() =
    static member Foo([<ReflectedDefinitiontrue>] a) = ()

```
            
#### Options

Fantomas Next - 3.0.0-7/20/2019

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| **`PageWidth`** | **`80`** |
| `PreserveEndOfLine` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeArgument` | `true` |
| **`SpaceBeforeColon`** | **`true`** |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `ReorderOpenDeclaration` | `false` |
| `SpaceAroundDelimiter` | `true` |
| **`StrictMode`** | **`true`** |

**Comment by jindraivanek** [comment]
Fixed by #455
