### ISSUE TITLE
Feature request: Prefix generic type parameters

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#460]
Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=C4TwDgpgBA5AhlAYge2VAvE1VkDNZwBQQA)

G-Research has a fairly strong norm of using prefix type parameters. Could we please have an option to keep them as prefixes?

#### Code

```fsharp
type 'a Foo = Foo of 'a

```
            

#### Result

```fsharp
type Foo<'a> = Foo of 'a

```
            
#### Options

Fantomas Next - 3.0.0-8/10/2019

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `PreserveEndOfLine` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `ReorderOpenDeclaration` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `KeepNewlineAfter` | `false` |
| `StrictMode` | `false` |

**Comment by jindraivanek** [comment]
Because information about used style is present in AST, it was easy to add: #461
