### ISSUE TITLE
Online UI tool doesn't understand F# 4.6's {|  |}

### ISSUE THREAD

**Issue by drhumlen** [fsprojects/fantomas#467]
### Description

Online UI tool doesn't understand F# 4.6's {|  |}

### Repro code

Link: [Code example](https://jindraivanek.gitlab.io/fantomas-ui/#?code=DYUwLgBAFizA9hAvBA3gHwgQWRAjAAwToC+QA) 
or:
```F#
let hello = {| A = 10 |}
```

**Comment by nojaf** [comment]
Could you try the latest version please? vNext 3.X
Looks ok to me there: https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=DYUwLgBAFizA9hAvBA3gHwgQWRAjAAwToC+QA

**Comment by drhumlen** [comment]
Yea, that version you linked seems to work :)

(I used the link from the top:
"FSharp source code formatter [https://jindraivanek.gitlab.io/fantom](https://jindraivanek.gitlab.io/fantomas-ui/)…"  which seems to be Fantomas v2.9.2.)
