### ISSUE TITLE
'with' incorrectly removed

### ISSUE THREAD

**Issue by pviotti** [fsprojects/fantomas#469]
Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?code=C4TwDgpgBAsiAq5oF4oFEB2UA+UCSwOUAYgE5QDuAlsABYBQUTUA9gG4SmlUAm0dVAM4A6eCwDKwbhgDmACgCUUVMAlSqsqAMGNmg4AENgVAMZQAthHMAjTlABmpFucnSZUQcodOX62QB44REgAPg8gA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZECMATAAzkUBOMAM4x+ANxgBRaAHkAZgBkGEGEXj8cMcohh4G6APYAbAxACC8aVHlKVROaiMjtaTACEYcg4LP9q+OHg1DS0QFAwYDy9BAGFjU3tHZzDXGDM5eFE4vDxUYM0XCPTM-h09QxMIfNDIWAQZCAAVfgBPRlZEp1CAJRhvWH4ZZDgAERh0I1R+VHgGBMIHLsLMXwMcaDGjBj0S6vIAaRgYZCwYAHctlWLRTuTEdX14AFkDWFuYAF8gA)

The keyword 'with' gets incorrectly removed.  
Similarly to what pointed out in #388, which for some reason has been closed: has this been fixed? If so, could you advice on which version contains the fix? Thanks in advance.

#### Code

```fsharp
type MyType = En | It | Fr with
    override this.ToString() = toString this
    static member fromString s = fromString<MyType> s
```
            

#### Error

```fsharp
type MyType = | En | It | Fr
    override this.ToString() = toString this
    static member fromString s = fromString<MyType> s

```
            
#### Options

Fantomas 2.9.2

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| **`PreserveEndOfLine`** | **`true`** |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `ReorderOpenDeclaration` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `KeepNewlineAfter` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
I think fantomas will never print out the `with` keyword as it can be left out.
We could tackle this in the trivia branch to preserve the with keyword.

**Comment by jindraivanek** [comment]
Yes it is [fixed](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=C4TwDgpgBAsiAq5oF4oFEB2UA+UCSwOUAYgE5QDuAlsABYBQUTUA9gG4SmlUAm0dVAM4A6eCwDKwbhgDmACgCUUVMAlSqsqAMGNmg4AENgVAMZQAthHMAjTlABmpFucnSZUQcodOX62QB44REgAPg8gA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZECMATAAzkUBOMAM4x+ANxgBRaAHkAZgBkGEGEXj8cMcohh4G6APYAbAxACC8aVHlKVROaiMjtaTACEYcg4LP9q+OHg1DS0QFAwYDy9BAGFjU3tHZzDXGDM5eFE4vDxUYM0XCPTM-h09QxMIfNDIWAQZCAAVfgBPRlZEp1CAJRhvWH4ZZDgAERh0I1R+VHgGBMIHLsLMXwMcaDGjBj0S6vIAaRgYZCwYAHctlWLRTuTEdX14AFkDWFuYAF8gA) in 3.0 (trivia) version.

I think removing `with` when it is not needed is OK.

**Comment by pviotti** [comment]
Nothing against removing something that is useless, but, to be clear, the `with` in the example above should stay, otherwise it does not compile, saying `error FS0010: Unexpected keyword 'override' in definition. Expected incomplete structured construct at or before this point or other token.`, using donet version: 2.2.108 and fsharpc version 10.2.3 for F# 4.5.

**Comment by jindraivanek** [comment]
> otherwise it does not compile

That's true for current version (2.9.2).

In newest version (3.0) it is formatted as
```
type MyType =
    | En
    | It
    | Fr
    override this.ToString() = toString this
    static member fromString s = fromString<MyType> s
```
which is correct. So, this issue is already fixed, just not released in stable.
