### ISSUE TITLE
Long text lines cause out of range exception in 3.0.0-beta

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#472]
### Description

In a multi-line string, if an individual line is longer than --pageWidth
```
The following exception occurs while formatting stdin: System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: totalWidth
```
happens in 3.0.0-beta, but didn't in 2.9.2

### Repro code

Here's a link to [an example using the online fantomas tool](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=HYQwtgpgzgDiDGEAEB3CAjA+vA9gJwgFgAoEnGCYJAdQwGUALEPCvAOgFUBJEksHACYBXADbIAsiACWwAC454SALwkkSMbKQAFEAHNkK4mrUBvJOICeO-WwDCBELIgAKAJSopshknSCLy1WMg4JDQkIBtJAARBTYANQg8dEcpMCQAIkySABUGKSgkfKQQJAA3RP8RHGBddRlkGWKkMFFZKQBaEXqkKFk8GV0AGh6cdWraxoAzBE0vR0LNIqqaxKQ5qjnNOH0PAS810ZQ8+G8uYrS+iwGDpFxgXrxpKghyvAsvAeGQYAERhaRdDhoD5vro2GEIRCSJl0kgALpIAC+QA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZECcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsa2GiEOYTAmMvDCMXh4qAFBiY6Yqem82roGRhC5weSQsAhSEAAqvACejKzx9gBKMB6wvFLIcAAiMOhqqLyo8AxxhKoJoU5e+jjQo2oMusVViQDSMDDIWDAA7ptKRcKd+YF68ACy+rA3AL5AA).

**Comment by nojaf** [comment]
Hey, thanks for this. Could you try again?

**Comment by SteveGilham** [comment]
That seems to have fixed it in the on-line tool.
