### ISSUE TITLE
Multiple extension members cause additional lines to be printed

### ISSUE THREAD

**Issue by Shmew** [fsprojects/fantomas#473]
### Description

When using the Trivia branch if there are multiple extension members it will cause an additional line to be added above the member. If formatted again with the output of the first, it will add yet another additional line.

I can't change this behavior with any settings changes except for StrictMode.

### Repro code
[Start](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=NoHgogHgLgpgdgZwJYHs4D4C6BYAUFATwAcYACAFRgSklkVUVIF489T3TRb5k0s2O1AIZQkAY1IBbGJIBGMAE6kAyimnd6aABQQAlM1IAiQ61wdO4aDwb8zgqCPFSZ8paukB5KAAtFG3nA6+kxGJrhAA)
[Running on output](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=NoHgogHgLgpgdgZwJYHs4D4C6BYAUFATwAcYACAFRgSklkVUVIF49XdSPTRb5k0s8nUtQCGUJAGNSAWxjSARjABOpAMopZPemgAUEAJTNSAImNtBnbtF4MB7TqPFTZC5Wo0wA8lAAWyrXxweoZMJma4QA)

**Comment by nojaf** [comment]
I'll have a look at this.
When strict mode is enabled no trivia will be processed, so indeed problems with newlines can't occur over there.

**Comment by nojaf** [comment]
Looks like this is fixed now. Many thanks for reporting these kinds of issues. Keep them coming!
