### ISSUE TITLE
[Trivia] Significant spacing added after let binding in function

### ISSUE THREAD

**Issue by Shmew** [fsprojects/fantomas#478]
### Description

If you have a let binding and then make >1 function calls that return unit everything gets formatted to line up with the ending of the binding.

### Repro code
[repro](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=DYUwLgBAzg9gtiAYgVwHbXiASiAhsYATwBkYzyLKZUBzANX2RAgF4BYAKAm4lElgQNgTVhgQ58RUlRllaQpp048xIAPJgAFiABOKdAEYIAZiVceA9Vt0btetBABMEACxA)

**Comment by nojaf** [comment]
@jindraivanek do you somewhat agree with this fix?
Not really sure how to tackle this in another way.

**Comment by jindraivanek** [comment]
@nojaf Agree with fix, only minor comment in commit
