### ISSUE TITLE
#if/#endif lost with v3.0.0-beta-004

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#482]
### Description

The command-line tool just drops the lines beginning with `#`; the web tool faults differently

### Repro code

[example](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=HYQwtgpgzgDiDGEAEBBANgFwMIHsBuEATgLABQZOMEwSAygJ5QYRgVU0NMsB0AIgJYgA5sBxN+8KN1wATCClBpG-KG2p1GzMNwBKAV2AZ+kaTjAx+aIrSJ4J0NR0099h4xG4BJQ0Uo3Cdoiq5KQA2gA8IFBQLABGSgBc3syEilAAair88RAAKjgAFABE6Nj4RNwAYrQoFgA0SAAKevESANIQ9AC8AAw9AEwALH0jgwAcI30AnMOTfQBsA3MDs30ArP1rAMyDAIxbu6Nzh30nU7vzg4NbKP0Aone7vP0zd2NYlSgA7PO-lQBCW0qa12-V4UymY14XywdxQWEGUx6UzuWzWd14-368N2jx6g14d3mYzGSJQUy2XwuvCeuwpu0qX36-TGKHhPQ2Wyw8OBPUqvDG-SwmMGWA+g0qlUG-0qPUJ4PRNy2YyBEspuK2-0FCLWawGsK+BK+vDWTLWKsRGx67zpHLufNxrK5sN+CKwX3RopQW3uUxQY0qUIel3taymWDlEf6vzezyw-3m0Lu-14g0u-0GX3t836gZ6Ca2vC2SNRpP6uy+AK+RQAlAA+AC6ZAAxPwAGZIAByd1yWAA8jo4Y1Gv0APo9MgRKIxMDxehJHypEBoDJZHL5YoyHAYYAQDAAWmXGHg5UIDWarXgHW6fSGc3Gcxmyx6i36yzvIw22z2ByOkxOPRnBcVw3PcjzPK87yfD8fyAsCoLgpC0KwvCiLIqi6KYtiWC4ocBJEiSZIUlSia0vSjLMqy7KctyHx6vy2oimKUqStKsrylMireiqLHqqiWpCoMur6nchrQiaZoWpxb42ki6IOm83pikS8xuh6dxej6dx+gGQZEoMobhpGAwxlCQoJkmKZptKmbZrmEwFkWJbKlM5aVv81b1k2YSRNEcSJMkRBpJkUDZFYG5FEIaA4LEy6HpgJ4EGeTQtGg7SdL0Kz3hMkxPssr7vqsHKbDs+wAUVgEjEBlzXLcDxPC8BlQd8vzzACQIgmCEJQjCcIIkiKJohiWI4ni+HEqSPTkuqpE0uRTIsmyEY0Ty9ECkKTHiqxMpyhinGotxqqVHxmrakJepCqJRoSZsUlWrJdoKU6ymuqK6mab6-qBoS+mGRGvBRqZcYWVmVnprZL72fm8yFsWPSlq5FZVrWjYttQMjtpOvkznOCRYAAMrQuDmGlICGAUGCEHoEBeVj07+fOxMhWFEAFG2y4xLTPn07OiScFoujQDgeiEEE3CdhAeiU8uOhCyLQT42TQh6MI8gYJT2RS6zRTUPuADi-wow2QA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZECcADAL5A)

**Comment by jindraivanek** [comment]
Provided example is not parse-able code, fixed [repro](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=HYQwtgpgzgDiDGEAEBBANgFwMIHsBuEATgLABQZOMEwSAygJ5QYRgVU0NMsB0AIgJYgA5sBxN+8KN1wATCClBpG-KG2p1GzMNwBKAV2AZ+kaTjAx+aIrSJ4J0NR0099h4xG4BJQ0Uo3Cdoiq5KQA2gA8IFBQLABGSgBc3syEilAAair88RAAKjgAFABE6Nj4RNwAYrQoFgA0SAAKevESANIQ9AC8AAw9AEwALH0jgwAcI30AnMOTfQBsA3MDs30ArP1rAMyDAIxbu6Nzh30nU7vzg4NbKP0Aone7vP0zd2NYlSgA7PO-lQBCW0qa12-V4UymY14XywdxQWEGUx6UzuWzWd14-368N2jx6g14d3mYzGSJQUy2XwuvCeuwpu0qX36-TGKHhPQ2Wyw8OBPUqvDG-SwmMGWA+g0qlUG-0qPUJ4PRNy2YyBEspuK2-0FCLWawGsK+BK+vDWTLWKsRGx67zpHLufNxrK5sN+CKwX3RopQW3uUxQY0qUIel3taymWDlEf6vzezyw-3m0Lu-14g0u-0GX3t836gZ6Ca2vC2SNRpP6uy+AK+RQAlAA+AC6ZAAxPwAGZIAByd1yWAA8jo4Y1Gv0APo9MgRKIxMDxehJHypEBoDJZHL5YoyHAYYAQDAAWmXGHg5UIDWarXgHW6fSGc3Gcxmyx6i36yzvIw22z2ByOkxOPRnBcVw3PcjzPK87yfD8fyAsCoLgpC0KwvCiLIqi6KYtiWC4ocBJEiSZIUlSia0vSjLMqy7KctyHx6vy2oimKUqStKsrylMireiqLHqqiWpCoMur6nchrQiaZoWpxb42ki6IOm83pikS8xuh6dxej6dx+gGQZEoMobhpGAwxlCQoJkmKZptKmbZrmEwFkWJbKlM5aVv81b1k2YSRNEcSJMkRBpJkUDZFYG5FEIaA4LEy6HpgJ4EGeTQtGg7SdL0Kz3hMkxPssr7vqsHKbDs+wAUVgEjEBlzXLcDxPC8BlQd8vzzACQIgmCEJQjCcIIkiKJohiWI4ni+HEqSPTkuqpE0uRTIsmyEY0Ty9ECkKTHiqxMpyhinGotxqqVHxmrakJepCqJRoSZsUlWrJdoKU6ymuqK6mab6-qBoS+mGRGvBRqZcYWVmVnprZL72fm8yFsWPSlq5FZVrWjYttQMjtpOvkznOCRYAAMrQuDmGlICGAUGCEHoEBeVj07+fOxMhWFEAFG2y4xLTPn07OiScFoujQDgeiEEE3CdhAeiU8uOhCyLQT42TQh6MI8gYJT2RS6zRTUPuADi-wo95VgYEgbY4DgSBdEgBQ1kAA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZECcADAL5A).

`#if` is duplicated and `#endif` is missing.

**Comment by SteveGilham** [comment]
My bad -- I thought "all the rest of the file is comment" and forgot the closing ().  [Actually fixed repro here](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=HYQwtgpgzgDiDGEAEBBANgFwMIHsBuEATgLABQZOMEwSAygJ5QYRgVU0NMsB0AIgJYgA5sBxN+8KN1wATCClBpG-KG2p1GzMNwBKAV2AZ+kaTjAx+aIrSJ4J0NR0099h4xG4BJQ0Uo3Cdoiq5KQA2gA8IFBQLABGSgBc3syEilAAair88RAAKjgAFABE6Nj4RNwAYrQoFgA0SAAKevESANIQ9AC8AAw9AEwALH0jgwAcI30AnMOTfQBsA3MDs30ArP1rAMyDAIxbu6Nzh30nU7vzg4NbKP0Aone7vP0zd2NYlSgA7PO-lQBCW0qa12-V4UymY14XywdxQWEGUx6UzuWzWd14-368N2jx6g14d3mYzGSJQUy2XwuvCeuwpu0qX36-TGKHhPQ2Wyw8OBPUqvDG-SwmMGWA+g0qlUG-0qPUJ4PRNy2YyBEspuK2-0FCLWawGsK+BK+vDWTLWKsRGx67zpHLufNxrK5sN+CKwX3RopQW3uUxQY0qUIel3taymWDlEf6vzezyw-3m0Lu-14g0u-0GX3t836gZ6Ca2vC2SNRpP6uy+AK+RQAlAA+AC6ZAAxPwAGZIAByd1yWAA8jo4Y1Gv0APo9MgRKIxMDxehJHypEBoDJZHL5YoyHAYYAQDAAWmXGHg5UIDWarXgHW6fSGc3Gcxmyx6i36yzvIw22z2ByOkxOPRnBcVw3PcjzPK87yfD8fyAsCoLgpC0KwvCiLIqi6KYtiWC4ocBJEiSZIUlSia0vSjLMqy7KctyHx6vy2oimKUqStKsrylMireiqLHqqiWpCoMur6nchrQiaZoWpxb42ki6IOm83pikS8xuh6dxej6dx+gGQZEoMobhpGAwxlCQoJkmKZptKmbZrmEwFkWJbKlM5aVv81b1k2YSRNEcSJMkRBpJkUDZFYG5FEIaA4LEy6HpgJ4EGeTQtGg7SdL0Kz3hMkxPssr7vqsHKbDs+wAUVgEjEBlzXLcDxPC8BlQd8vzzACQIgmCEJQjCcIIkiKJohiWI4ni+HEqSPTkuqpE0uRTIsmyEY0Ty9ECkKTHiqxMpyhinGotxqqVHxmrakJepCqJRoSZsUlWrJdoKU6ymuqK6mab6-qBoS+mGRGvBRqZcYWVmVnprZL72fm8yFsWPSlq5FZVrWjYttQMjtpOvkznOCRYAAMrQuDmGlICGAUGCEHoEBeVj07+fOxMhWFEAFG2y4xLTPn07OiScFoujQDgeiEEE3CdhAeiU8uOhCyLQT42TQh6MI8gYJT2RS6zRTUPuADi-wo95AD0xtTn5vPzrQegwDAhDQFAACyDuq8UjsSIQYg4G2GB8NA-AiEUdRkKbSBh+HEeR1HUdFNyhxhgkzuzkQUC0AAFsLaAyJ2253AAHjAYgQFgRAYCA-DALgwDwPbzC5PQVBQEHIfG9Hbft+HtAnlQSBdEgRSQMnhDN6Qocd+Pke5CAhBCHuvf96UuBJaYYBgGTMhSFXSUYPkAAavA4PAeiQIYxNr8AMjcM23DwBgOCEAU-M8LvYBoNwL9oAfR8nxgNYj2PE9AHO2iKrTwMh55FCftoD+79X45zkP-VugDAEACk9DiDbBIEARgcA0D7kUE8wBt5QCQIQmue5kAYAbtAI2ZACg1iAA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZECcADAL5A)
