### ISSUE TITLE
Over-aggresive folding breaks nested lambda expressions

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#486]
### Description

After processing with 3.0.0-beta 4, the function starts at line 423 of the containing file; at that point these intellisense errors are shown

The type ''b -> 'c' is not compatible with the type 'seq<'a>'. See also Visitor.fs(425,7)-(425,18).	Visitor.fs	427
This expression was expected to have type
    ''a -> 'b'    
but here has type
    'Node'	Visitor.fs	446

Also identifiers `targets` and `included` are greyed out as if unreferenced.

### Repro code

[example](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=ATA2FMBdgBwJwJYDcCGlzAMqRXSA1BAZwWgAoY0ALI4ALmCPAEcAeIyRAOwHNgAqRpwS8wxSAD4AlMABGAVwSgAJphbzwXAMYYAvAFgAUCBCVINIyeAAfCVhYA6LQHtQELeQBm8rsArUAGmAcOB4oIhkAWjszKksrBMSk5JSTWz8AQSImAFtZUABPABFwTxFSBGcuBwAlcBRlLNz8gvjU9o7OiTsyb18AD2Bots7RsZN+kfHp9vSULS15HPlQNGc4BwzlZSmZvcT0hB4udfAjXf3L4AB6a+AtFC4AcmhlcFWC4Dh65RE+IgKeVctEenxypwuVz2AAU4M4eHAUDkimgULIUExaj9MIDZMCyP0pOdjFDSbdgHUAFbgDz3Zw5GAQdCFYAITzAMqgdDfZTAKjgb6Q0njJmsrhEGA0yCVXy6YAASSI8u0oHkb15k0MQuFo1FIi0qvVwAMJJ1VxEEqlMps1msrPZFslHmtcuVlo8DjdnCWmkg2rNAZMADIgxTwDB1pAAGLrHJoMgyOUAIQx4CxEbwMbgccgDgA8pKuABhZxIAUAdVIVAAKoitABrP7Bflcf2Bs1up252vzett9tQ95MBXirue44Q00D0ZNcB5QoEoL6w3gZRBEJhSARKREqfjbpyRQqNTMDTacC7oA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZECcADAL5A)

**Comment by nojaf** [comment]
The [formatted code (of 03/01/2020)](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=ATA2FMBdgBwJwJYDcCGlzAMqRXSA1BAZwWgAoY0ALI4ALmCPAEcAeIyRAOwHNgAqRpwS8wxSAD4AlMABGAVwSgAJphbzwXAMYYAvAFgAUCBCVINIyeAAfCVhYA6LQHtQELeQBm8rsArUAGmAcOB4oIhkAWjszKksrBMSk5JSTWz8AQSImAFtZUABPABFwTxFSBGcuBwAlcBRlLNz8gvjU9o7OiTsyb18AD2Bots7RsZN+kfHp9vSULS15HPlQNGc4BwzlZSmZvcT0hB4udfAjXf3L4AB6a+AtFC4AcmhlcFWC4Dh65RE+IgKeVctEenxypwuVz2AAU4M4eHAUDkimgULIUExaj9MIDZMCyP0pOdjFDSbdgHUAFbgDz3Zw5GAQdCFYAITzAMqgdDfZTAKjgb6Q0njJmsrhEGA0yCVXy6YAASSI8u0oHkb15k0MQuFo1FIi0qvVwAMJJ1VxEEqlMps1msrPZFslHmtcuVlo8DjdnCWmkg2rNAZMADIgxTwDB1pAAGLrHJoMgyOUAIQx4CxEbwMbgccgDgA8pKuABhZxIAUAdVIVAAKoitABrP7Bflcf2Bs1up252vzett9tQ95MBXirue44Q00D0ZNcB5QoEoL6w3gZRBEJhSARKREqfjbpyRQqNTMDTacC7oA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZECcADAL5A) produces [valid code/AST](https://jindraivanek.gitlab.io/ast-viewer/#?code=DYUwLgBADgTglgNwIZhBAymJMwDU4DOckAFFCgBYEBcEBIAjgDwFjwB2A5hAFR1twuEYITAA+AJQQARgFc4wACbpGskOwDGaALwBYAFARolAgaMAfMRkYA6DQHtgoDWDNH3EEgDNZ7T+TAKABoILBhOcAIpAFoxNw93AIp4hIhLTwBBAnoAW2lgAE8AERAvQWI4e3YbACUQJEUs3PyClNT3MStvXwgADwhYtva+ofb0pA0NWRzZYBR7GBsMxUVR1PS4TnYFkAM1hIB6A4gNJHYAckhFEDmCiBh6xUFuAgK8xwIIM7ucnf2PAAKMHsnBgSByRRQSGkSHotUe6De0g+JF6Ej2hmGHiOEDqACsQC4TvYclBQKhChA4F4IGVgKgHooIBQQA9-u5yVT2AQoISwJU-NoIABJAjCzTAWTXJm9DFYjycwQaSXSiB6THy9yCHl8gVpczmKk07W8lx6oXinUuGyWtjTdSuDWa53tABkrtxICgCzAADEFjkUCQpOqXWHNQAhWEgeHenD+mCBsA2ADyvPYAGF7AhWQB1YgUAAqYI0AGtnqEWex2eHUpbTcnixNSzXa0YbvRW22jPW+Tatn8nVimiA8oVUSElSqQIoQmEImAohJ0UOOlY5AplKp1FoV0A&defines=Q&filename=MoYwTglgDgLgdAMwM4A8g) for me.

Please reopen if this is still a problem.
