### ISSUE TITLE
Combining lines breaks function precedence

### ISSUE THREAD

**Issue by ChrisCanCompute** [fsprojects/fantomas#488]
### Description

When some a line of code has an operation on it, and the line is then piped into another function on the next line, fantomas will combine the two lines.
This will break the code if the precedence of operation on the first line is lower than that of the pipe function

This is an issue on all versions.

### Repro code

Before, there is a `(unit -> unit) option` function.
After, there is a `unit -> (unit option)` function.

[simple example](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=GYVwdgBAFAlBC0A+aMCwAoAPsgygewFsBTDIA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZEAcADAL5A)

**Comment by nojaf** [comment]
The [provided sample](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAzArgOzACgEowBaAPnwIB0AnS7AH3IGVYBbRGuyAGnCgGdEAFyEBLbAHN%2BqMAG0%2BEUBGVQAJEICeAB2RpI4oTwXLIqgG4BDADaZdc4yoAMvFSsgBJbEmxCmogF7ILq4QACwOYAC6xgC%2BwYoRppo6Mvo%2BRiGmljZ28iEQAIzxrpAAshYAHgAy4ohViJJCABYZ%2BQUATI4R0Spxxkol6tp2kABGsLBWrW7m1rYyefntxW5MiKyicFaw2ACCQgCiXgDy6DXYQREQ6NaC3bHFAzPJI%2BOT0yazOQtXYADMKxMTC0FmgiAAQoh0LBqIgAAoWagWdhCRDUD4qITUWz3XqPRJDFJ6N5TQFZOa5X6hQEQSDA0EQqEwuqwADuaOgFkEnjMsE5Yh2GOUWJxIR6yj6KienxeqRJQvJ3zQixCAFYaVB6WDIdDYQBVLQ6aic7nYXn80SCjU3Kx3MUPfoE2XEiakgnZebK34ANg1dJB2qZsIAwlYufxgzt%2BCLoEIYULrrdELiJfjMoTXq6FV9PfZ8mAAOx%2BrWM3WIUrrUZohNgG121ziiCS5TS2kZuVZsk5yn5gAcxYDpeZke22BrdeT9rxjvTzqg8q7Hp7%2BQAnAOGbt0KjqJHWKwLDWRZOGw6pU7hh33ouKT98wVnL9-Qydcy1hstlbfhOU0204M52MnbujeXp3kUj4lpu25vpskyfvmR4-mAzYJLOF4ulewFKnmbTLI%2BnjeEIxzYAAKtQGgAOqiM045JkhKFgK2agAQuWG5iqrgFACEGDrs1CwDg8AACKIFYogbNuh7YseKiNshf7POhUAGNmS63m01KPuUFTuOgJFNA0By2ogTBNDCQhUfANEaqEXRTqmM7-kpaSGNe2EcSoBTqlplSeOgogVMcRoWHG1AHBUWiwvw-CWmOGqqnZJ7TmeaFEsp6RuexvwFL6PkVAASogcDUPAlnWVSiWyaeLbnmlLmqSBOEhAURZ5XxSIaMc1A1NGZUtDZlXKHJDFMUkzkqZly7Nf2bXUB1XU9UIABymCsFW1CnO4qKsNIGoFPRCkys5rCYFYYhiRcABiML7iIaIkRek3qc1a6Pu1Fidd1ojRqUp3nbU13ULdkl%2BtATSIqC24APqsqIVktAdjmKXVE1sVNridH62kAGoUuC4jwOIEh9TWtmIylTkoxlaPPRj4H5mUlSXTgsaxfjXhEyTA3kzVqUjKj6ZqaBSx4Qz2lCbAQgAOLCOFkWINFsVc78CU86hlOZphguNR5yjtNxYt-aIF0Qts0AANbgkiFvCPwxFMMiiAjqtcVfnR9m-kjR11ax2vub87SaQzS2IKyJuQkI7INA9Ogif52DUbFuxeBWa1ortbvGWrjG1Zrbp%2B1l%2BbtN5DMANKIIgWi6fpDSeA77DnJc%2Bbfh78le22AEC4MQtNRjuVi5URkbPwTTK-mZOtyNueXvn3c6wHrUM34khWIgfESKtDQWYgoylAgTf5C3SUORTyN5w1-tFzNDO7GJEjYMz2Cszsfj3yFmCwiRsAEVvIWxbRWdJ6HQ7s5X2c9L5LFejfM6aJsB-zMCySQqd1px3EInKMAD6xVWSrzDWM8L6F3yH8B8S8sSbCEHvJAmCZJDViHwSIwR9D8EujFGQ34YhAA) is formatted correctly now.
This was solved when https://github.com/fsprojects/fantomas/issues/942 got fixed.
