### ISSUE TITLE
Long function signature broken into two lines

### ISSUE THREAD

**Issue by ivan-brko** [fsprojects/fantomas#492]
### Description

Function with a lot of arguments gets broken into two lines, which is ok. However, second line then blends in with the body of the function, as it is indented at the same level and there is no line break between the arguments and the body

### Repro code
This
![image](https://user-images.githubusercontent.com/25389931/65933872-8ba70080-e413-11e9-808e-52f38cf9385e.png)

turns into

![image](https://user-images.githubusercontent.com/25389931/65933843-70d48c00-e413-11e9-92e0-f6bdf381b14a.png)

[Link to online example in fantomas tool](https://jindraivanek.gitlab.io/fantomas-ui/#?code=DYUwLgBADgTglgNwIZhBJATDAVJBnAa2wHsBlAYwAsQMBXUGCACjypvpEYC4IBJC6nQYBKCGHwEAckgC2acYQDCMYgDto8YswUEIPWqriQAtAD4IBo6IDmK2lGlyIAXgBQED54+hIM2uIAjUAgAK2IAgBEUJABZJCgXCAApcKjxOKgmYXcvTzDI6IyAOgBtACIdMoBdCAAeYzEJHNyIH1Dwl2aWzxSAgCFaOGAMTiLlEBQQWoB1GHioTl7TLKKAVTw4VWtetKQmfN2M7O6TiCLpo0peEdUwIwBPJh1HEAAaCFtiexfhIoGhjBZLpeACMQA).

**Comment by ivan-brko** [comment]
This doesn't seem nice to me, but if it is supposed to look like this please close the issue.

**Comment by nojaf** [comment]
Hmm I count 112 characters for `let private addTaskToScheduler (scheduler : IScheduler) taskName taskCron prio (task : unit -> unit) groupName =` so I would expect it is on the same line.
Seems to be working for `2.x`.

**Comment by ivan-brko** [comment]
That depends on what the _PageWidth_ is set to? 
If I am not mistaken, it's 80 by default? I can see that even on the _online fantomas tool_ (v2.9.2) it is set to 80 by default.
Still, I don't think splitting the arguments in two line is problematic (that will happen with a longer function signature even if I increase _PageWidth_) but the way it splits the arguments which makes it look like the second line of the arguments is part of the function body.

However, I didn't spend much time with formatting F# code before, I usually just write all of this on the same line, so I don't know if the language itself allows any prettier formatting in this situation.

**Comment by nojaf** [comment]
PageWidth on 3.x will be 120 so something doesn't add up.

**Comment by nojaf** [comment]
A very good question. Personally I would say that the function definition should be on one line for readability but that is only my opinion. I can't find anything immediately in the [F# style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) that supports this.

So we could modify this behaviour if we want. Any thoughts @jindraivanek?
