### ISSUE TITLE
Format selection problems

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/fantomas#494]
I've been testing a new Fantomas integration with FSAC/Ionide and I've encountered couple of problems for selection formatting:

1.  Indentation problems 

Sample recorded in: https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/ProcessWatcher.fs

I've attempted to select 2 last functions and format them - formatting breaks general indentation of function signature, original indentation should be kept.

![Fantomas_bug](https://user-images.githubusercontent.com/5427083/66047649-67891380-e528-11e9-8ac3-cd620b8f2b1b.gif)

2. Breaking formatting when we select "exact" range

Sample recorded in: https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/State.fs

This works just fine if user selects empty line above record - tho, it removes this empty line, it probably should be kept. Sample is showing this on record but I was able to repro also on selecting just a single function

![Fantomas_bug2](https://user-images.githubusercontent.com/5427083/66047811-b9ca3480-e528-11e9-88df-afbbe6841379.gif)

**Comment by nojaf** [comment]
Thanks for raising this issue I sorta expect that format selection has multiple issues.
The first thing I notice is that the file uses 2 tabs as indentation level while the default configuration takes  4 so that could explain it somewhat.

**Comment by deviousasti** [comment]
I'm encountering breakage in format selection as well.

Here, formatting the range (8,0)-(13,0):
![image](https://user-images.githubusercontent.com/2375486/86341759-5a927f80-bc74-11ea-85b6-4e8968606551.png)

Gives the result:
```
type ABC =\r\n    | A\r\n    | B\r\n    | C\r\n    | D\r\n    | E\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nle
```
It's grabbing some characters from the next line. 

However, (8,0)-(12,0) works fine. 
Any clue why this is happening?

**Comment by nojaf** [comment]
Format selection is something I'm not that familiar with.
I think the concept as a whole could use a revision.
As it is very hard to nail down: if you have a selection, it tries to match the range of an AST node, then it formats the entire file and it will cut out the result and try to replace the fragment in the source file.

**Comment by nojaf** [comment]
Format selection was overhauled a while ago for the v5 release.
I'm going to close this issue here. Feel free to raise any new issues you may encounter.
