### ISSUE TITLE
Page width is not respected when formatting a function signature

### ISSUE THREAD

**Issue by breki** [fsprojects/fantomas#495]
Even though the page width is set to 80, Fantomas, when formatting the code below, places the whole function signature in a single line, which is then 108 characters long.

Could I suggest the formatting algorithm should format the function signature by trying various approaches until it finds one that adheres to the page width limit (in the order of preference):
1. Put the whole signature in a single line.
1. Place all of the function parameters and the return type in the separate line.
1. Keep the function name and function parameters in one line and the return type in a separate line (that starts with the `:` token).
1. Put the function name in the first line, function parameters in the second line and the return type in the third line.
1. Put the function name in the first line and then each function parameter in its own line, and the return type in its own, last line.

Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?code=DYUwLgBAZg9sAmECwAoC6IAooFcB2AxgM4BcEASiETsGAGL4EA8A5AJJ4AOOYANCwHke3PiwAqAUQBOUmFIB8EIiACOASmRoMmAJZceZdvrBrUGCGUrVarIWBERgOonwjjpsqY+dhFAXjMMUEgAWx4AQwAjUAhwvABPDzkiCD9ocOBlQPRgiDCwKJiCOFACMBB4OxEUtIBtAF1sx3A8iOiQCGLgUvL4JKkaiAbUJtypfAA1DJ14cLA5LAA3adn5qUsqGnpGVg4RfiqefkkZOXkNPQcArXMcluWnVbkrLdSIB5m5hcueJvMQuYEAAW7xWXykL1oEAA7jowEC-hgAD4QfoQECnLwAWkUiNusQS-RSTCxEDA4xAeNuXR6FSJEBJ6MxFjINJAZTpmKIVJRAgA1hAYMIeBAcVTzGyOZVhWBiaShfYRSRWSV2b1DrKRjdoIwUk0kYoAMqqAB0cIx2HwoMe4NFinGeCmNrW1s+Lp+Ji1-0BILiiS5MLhCO1KPJOA6ONRzMlvSJ+vSmQjin5nVVUo13JQQA)

Please describe here fantomas problem you encountered

#### Code

```fsharp
let fold 
    (funcs: ResultFunc<'Input,'Output,'TError> seq) 
    (input: 'Input)
    : Result<'Output list, 'TError list> =
    let mutable anyErrors = false
    let mutable collectedOutputs = []
    let mutable collectedErrors = []

    let runValidator (validator: ResultFunc<'Input,'Output,'TError>) input =
        let validatorResult = validator input
        match validatorResult with
        | Error error -> 
            anyErrors <- true
            collectedErrors <- error :: collectedErrors
        | Ok output ->
            collectedOutputs <- output :: collectedOutputs

    funcs 
    |> Seq.iter(fun validator -> runValidator validator input)

    match anyErrors with
    | true -> Error collectedErrors
    | false -> Ok collectedOutputs

```
            

#### Result

```fsharp
let fold (funcs : ResultFunc<'Input, 'Output, 'TError> seq) (input : 'Input) : Result<'Output list, 'TError list> =
    let mutable anyErrors = false
    let mutable collectedOutputs = []
    let mutable collectedErrors = []

    let runValidator (validator : ResultFunc<'Input, 'Output, 'TError>) input =
        let validatorResult = validator input
        match validatorResult with
        | Error error ->
            anyErrors <- true
            collectedErrors <- error :: collectedErrors
        | Ok output -> collectedOutputs <- output :: collectedOutputs
    funcs |> Seq.iter (fun validator -> runValidator validator input)
    match anyErrors with
    | true -> Error collectedErrors
    | false -> Ok collectedOutputs

```
            
#### Options

Fantomas 2.9.2

| Name | Value |
| ---- | ----- |
| `IndentOnTryWith` | `false` |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `80` |
| `PreserveEndOfLine` | `false` |
| `ReorderOpenDeclaration` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `SpaceAroundDelimiter` | `true` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `true` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Hey @breki , thanks for this thorough report.
I think this is debate whether we want to hang on to the PageWidth setting or improve readability by leaving the signature on one line.

Personally, I like the algorithm you suggest. What do you think @jindraivanek?

**Comment by jindraivanek** [comment]
I quite like the alg, but it would need to create some new abstraction in Fantomas code to allow this multi-step newlines.

Right now we can quite simply implement binary variant (points 1. and 5. of alg).

I think it is up to debate if we want points 2. - 4. and if it should be by default or opt-in/opt-out.

**Comment by breki** [comment]
Thank you for considering this one.

Let me explain my reasoning behind this. For ergonomic reasons I'm coding using large(-ish) font sizes, so I limit the code lines to be 80 characters wide. On the other hand, the primary factor in code readability (for me) is being able to see the whole line without having to scroll left and right. 

When coding in C#, Resharper (mostly) takes care of this - you just set the line width and then tell it to reformat the line to adhere to the width. It doesn't have as sophisticated algorithm as described above, though - it either keeps everything in one line or splits every parameter into its own line.

Since there's no such facility in VS for F#, I now do it manually, so an automatic help from Fantomas would be great.

**Comment by nojaf** [comment]
I've created an implementation for ` binary variant (points 1. and 5. of alg).`
@breki could you provide some more examples where this occurs?
I'm guessing function signatures won't be the only place.
