### ISSUE TITLE
An option to preserve empty lines between logical blocks

### ISSUE THREAD

**Issue by breki** [fsprojects/fantomas#496]
### Description

I tend to add empty lines between logical blocks of code inside functions so the code is more legible (it's a matter of taste, I know, but I imagine I'm not the only one doing this). Unfortunately Fantomas removes these empty lines (and using `PreserveEndOfLine` is an overkill).

### Repro code

Example code:
```fsharp
    let runValidator (validator: ResultFunc<'Input,'Output,'TError>) input =
        let validatorResult = validator input
        match validatorResult with
        | Error error -> 
            anyErrors <- true
            collectedErrors <- error :: collectedErrors
        | Ok output ->
            collectedOutputs <- output :: collectedOutputs

    funcs 
    |> Seq.iter(fun validator -> runValidator validator input)

    match anyErrors with
    | true -> Error collectedErrors
    | false -> Ok collectedOutputs
```

gets formatted to 
```fsharp
    let runValidator (validator : ResultFunc<'Input, 'Output, 'TError>) input =
        let validatorResult = validator input
        match validatorResult with
        | Error error ->
            anyErrors <- true
            collectedErrors <- error :: collectedErrors
        | Ok output -> collectedOutputs <- output :: collectedOutputs
    funcs |> Seq.iter (fun validator -> runValidator validator input)
    match anyErrors with
    | true -> Error collectedErrors
    | false -> Ok collectedOutputs
```

**Comment by jindraivanek** [comment]
Fantomas 3.0 keeps empty newlines by default: [link](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=AQ4GwUwF2AnBXAdgNQIZgJYBNVQPazAAUAbutrgQFzABKEAzvGFAGJIDGAPAOQCSiAA7woAGh4B5EcLE8AKgFFYsAgD4AlMAxCRwALwBYAFChT4aMDKYc+WPSYt9l8jYJadUY2dABbXBwALZ2tKO0ZmGAB3DCgAr29gAB9gJRVCCGU3AFpVYHiE0FREAE9UggZgLizgKAQIfILgDjwwSA4oCCwy2Aqq4Ay04CoaZtaIds7uhgbTZIkAa2A8aV0cmYTRto6sKSgZXurlvd1hppatzt394waAM04KhsTcgGUIAEcAOhiMonvEYIUWzAHJwJBoELAqxAtzaGTqG4mXz+IJFUqZHrAaKxJ41Oog3LdM5jCZdDHTJEgZK3dAMCAE4ALYkXHYrKAUoA).

Please re-open if you find another problematic case.
