### ISSUE TITLE
--noSpaceBeforeColon doesn't work

### ISSUE THREAD

**Issue by FraserWaters-GR** [fsprojects/fantomas#499]
### Description

--noSpaceBeforeColon should toggle the FormatConfig.SpaceBeforeColon option, but because SpaceBeforeColon defaults to false, and the --no flags can only toggle an option false SpaceBeforeColon is always false.

SpaceBeforeColon should either default to true (like the other SpaceBefore options) or the cli parser should be extended to allow --noSpaceBeforeColon=true/false.

Also documentation.md has a list of the default values of these options but it doesn't match the code in FormatConfig.fs.

**Comment by nojaf** [comment]
Ah yes, documentation might be out of sync with some new defaults and cli should be updated as well.
