### ISSUE TITLE
Inconsistent configuration between fantomas and fantomas-fmt

### ISSUE THREAD

**Issue by tqa236** [fsprojects/fantomas#507]
### Description

In fantomas, the flag noSpaceBeforeColon is enabled by default.

```
fantomas --help
 --noSpaceBeforeColon: Disable spaces before colons (default = true).
```

In fantomas-fmt on VS Code, the flag "enable space before colon" is enabled by default.
![image](https://user-images.githubusercontent.com/25203655/66696558-474a1900-eccd-11e9-8dbf-499f0b0c7086.png)

I format the code on VS Code terminal, and it works incorrectly no matter if I turn on or turn off the fantomas-fmt flag above. However, if I use the ` --noSpaceBeforeColon` flag in the command line, it works correctly.

```
fantomas .\TwoFer.fs # Wrong
fantomas .\TwoFer.fs --noSpaceBeforeColon # Right 
```

### Repro code

In my test code [here](https://jindraivanek.gitlab.io/fantomas-ui/#?code=LYewJgrgNgpgBAFQO4gGIwE4FgBQvYAucBK6GcAFAJYB2ADhEQFxwDOBGtA5nCHQVRA0AlHBbtONHgF5cceXFoMCchQB8AfHADy-QTQB0YGADMAhtAIA1M1AjwARAE8QEB6vma2dSQRNwHbRp4ExByAFJWABpeYLhQ8mAYAwcgA), fantomas-fmt gives me an extra space before every colon. 

I don't know if you also maintain fantomas-fmt, but I cannot find that repo online, so I created this issue here. I'm sorry if it's the wrong place.

**Comment by nojaf** [comment]
What version do you have of fantomas-tool?
Check with `fantomas --version` please.
Some settings have changed in version 3 and we are not responsible for the fantomas-fmt plugin.
Maybe an issue needs to be opened there.

**Comment by tqa236** [comment]
Sorry. I forgot to add. It's version 2.9.2.0, the latest one on VS Code. I will open an issue there.

**Comment by nojaf** [comment]
Ok, please re-open if any action is needed from our side.
