### ISSUE TITLE
(Suspected Fantomas issue, not sure) Formatting adds a newline containing the last character of the file

### ISSUE THREAD

**Issue by OmanF** [fsprojects/fantomas#515]
### Description
(Let me first say I'm coming here on advise of the `Ionide` project, since, apparently, they use `Fantomas` as backend formatter or what not and ask all formatter issue to be posted here as well).

When formatting a file (using `Ionide` as formatter), the formatter adds a newline containing a single character: the last character of the last line of the code (before running the formatter).

So, for example, if taking the previous text as an example, after saving the text would look like:
```
...line of code (before running the formatter).
.
```

If I remove the offending character and save again, nothing happens, file stays the same.
If I add more code to the file, making the formatter re-format the file, since there were changes, it will happen again.

**Comment by OmanF** [comment]
Hey @nojaf.
Just tried the online tool, use as simple as `let a() = 1` and an entire production file I use... neither caused the issue (using _all_ 3 versions of the parser available, and with _all_ the settings turned on... just like I have it in VSCode).

Tried it again on VSCode, to make sure I'm not crazy... reproducible every time.

I'll make a GIF and upload it in a second.

**Comment by Krzysztof-Cieslak** [comment]
@nojaf, maybe it’s a bug in FSAC in translation/calculation of the ranges that we give to Fantomas?

**Comment by seangwright** [comment]
I'm experiencing this issue as well (also came here from Ionide https://github.com/ionide/ionide-vscode-fsharp/issues/1234

Here is the file which is showing this issue:

```fsharp
module Game

type Details =
    { Name: string
      Description: string }

type Item =
    { Details: Details }

type Exit =
    | Passable of Details * desitnation: Room
    | Locked of Details * key: Item * next: Exit
    | NoExit of Details option

and Exits =
    { North: Exit
      South: Exit
      East: Exit
      West: Exit }
      
and Room =
    { Details: Details
      Items: Item list
      Exits: Exits }
```

Formatting the document in VS Code (alt + shift + f) results in a new line being added above `and Room =`

If I add a comment above `and Room =`, the newline is added above the comment as well.

If I have no extra newline between `West: Exit }` and `and Room =`, a new line is still inserted before `and Room =`.

Before formatting:
```fsharp
and Exits =
    { North: Exit
      South: Exit
      East: Exit
      West: Exit }
and Room =
    { Details: Details
      Items: Item list
      Exits: Exits }
```
After formatting:
```fsharp
and Exits =
    { North: Exit
      South: Exit
      East: Exit
      West: Exit }

and Room =
    { Details: Details
      Items: Item list
      Exits: Exits }
```

I'm using Ionide 4.2.0 and VS Code 1.39.2

**Comment by jindraivanek** [comment]
Can confirm the issue: when file don't ending with empty newline, newline with last character will be added. Happening only from Iionide. Workaround for this issue is to have empty line at end of file.

**Comment by jindraivanek** [comment]
@seangwright This looks like unreleted issue, can you please make new issue for it?

**Comment by OmanF** [comment]
@jindraivanek , thanks for the workaround.
Why didn't _I_ think about simply adding an ending newline?! 🤣 😆 

@seangwright , I don't know, I'm no expert at F# formatting, but I think _your_ use case is by design.
I know I, personally, for example, always put a newline after an ending `}`.
I honestly think your use case is one of the formatting rules, making "walls of code" easier on the eyes. But we'll just have to wait and see what `nojaf` says...

**Comment by nojaf** [comment]
I agree with the two comments of @jindraivanek: the actual issue here is one to be fixed in FSAC.
@Krzysztof-Cieslak is right: something is up with those ranges. I'm a bit confused myself as to how Fantomas interprets ranges (0 or 1 based) when calling FormatRange.

@seangwright I think you found a trivia issue, please open a separate issue for this.

**Comment by seangwright** [comment]
Sorry everyone, I wasn't clear enough in my comment - the new line gets added repeatedly. As in, if I format the document 20 times in a row (without any code changes), 20 new lines get inserted, to the point where the last block of code is 20 lines lower in the document.

So basically after every few formats I need to go and delete several new lines that were added.

I'll open a new issue.

**Comment by allistercsmith** [comment]
@seangwright I opened an issue focusing on the problem you're seeing: https://github.com/fsprojects/fantomas/issues/535

**Comment by nojaf** [comment]
I tried this today in vscode and I didn't have the problem.
I'm going to close this as I don't think there is anything actionable from Fantomas side.
