### ISSUE TITLE
Improve formatting

### ISSUE THREAD

**Issue by JaggerJo** [fsprojects/fantomas#518]
### Description

Sorry for the bad title. I just played around with the web UI and noticed that the formatted version of a few experiments was harder to read than the non formatted version IMHO.

input:
```fsharp
let square = (fun b ->
    b*b
    prinftn "%i" b*b
) 
```
formatted:

```fsharp
let square =
    (fun b ->
    b * b
    prinftn "%i" b * b)
```

input:
```fsharp
let changeAge (person: Person) (age: int): Person =
    { person with Age = age } 
```

formatted:

```fsharp
let changeAge (person: Person) (age: int): Person = { person with Age = age }
```

### Repro code

https://jindraivanek.gitlab.io/fantomas-ui/#?code=DYUwLgBAzgjgrgQwE4ggXggCgGZwHYQBGEAtAHwBQE1RAVIVTQA5ICWe2YBARAKSvc6DAJQQKFMAE8mqAAogkUAPYE0jagG8IAMVaKwAOQQBbVAC5oYNngDm6mgBkEUQyfOXrdmjQCCN9+yQAL7ioJAAxgAWCLYgfqiYMooqFvLJeKKYCP4WgaKpCsqq9lpJRRAA7qxgkRDx6BDZqEFiFGEQUTH+RqZYZSkQaUWZ2HouFi6emcDOYBNW7Db5g4Uq6CUQ-QRVNfbeuvo9qBij+nuOs0cNMy4QLUA&config=N4Ig0gphAOByEHcA2BLAdhAggMwC4QCcQAuXAgVwgF8g

**Comment by nojaf** [comment]
I noticed `KeepNewlineAfter` is on in your settings so I would expect that `changeAge` to still have a newline after `=` so that might be a bug.

Maybe the lamda between `(` `)` could use some indentation after the arrow. What do you think @jindraivanek?

**Comment by nojaf** [comment]
@JaggerJo could you maybe split this issue into two?
Those two examples are not related to each other.
And it makes it easier to give a better title. 
Maybe go for: `Improve formatting of lamba between parenthesis` and `KeepNewlineAfter not respected in let binding`.

**Comment by JaggerJo** [comment]
https://github.com/fsprojects/fantomas/issues/523

**Comment by JaggerJo** [comment]
https://github.com/fsprojects/fantomas/issues/524
