### ISSUE TITLE
Formatting document continuously adds new lines each time it's called

### ISSUE THREAD

**Issue by allistercsmith** [fsprojects/fantomas#535]
### Description

This issue relates to [this original issue](https://github.com/ionide/ionide-vscode-fsharp/issues/1234) in the Ionide VS Code plugin repo, and also ties in with [this comment](https://github.com/fsprojects/fantomas/issues/515#issuecomment-543755731) in this repo.

In both the above issues, it seems there's two separate problems being raised:

1) The last character in a file is duplicated to a new line when the file does not end with a new line
2) New lines are repeatedly inserted before attributes on format

**This issue focuses on item 2 (I cannot replicate item 1).**

I captured a GIF of item 2 in action here:

![new_lines](https://user-images.githubusercontent.com/7033564/67288650-a550da80-f4dd-11e9-9f04-8c3e5801359e.gif)

Please shout if you need more info.

Thanks! 🙂

**Comment by mrkaspa** [comment]
Having the same problem here it looks like it is for this

```
namespace Book

[<CLIMutable>]
type Book =
    { id: string
      title: string
      author: string }
```

the tag [<CLIMutable>] causes this happen because if I remove it it does not hapen anymore

**Comment by nojaf** [comment]
@mrkaspa I think this is fixed by https://github.com/fsprojects/fantomas/pull/509, see https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=HYQwtgpgzgDiDGEAEAhA9mg1gWAFB4G0AeAYQBkBJAWQFcAXEAIwBsIA+AXTzoE8Zl0WJAF48ScUgDeSAJYATAFxIodAE4zgAczETxdGXVZKV6rTt0h6ACzSrjajZqQBfIA.

@allistercsmith could you try your code as well in the online tool. Use the preview mode please.
![image](https://user-images.githubusercontent.com/2621499/67523142-5312e380-f6ae-11e9-8d57-5524836e8bfa.png)

**Comment by mrkaspa** [comment]
@nojaf looks like it is fixed now thiw should be shipped on ionide to make it work right

**Comment by allistercsmith** [comment]
Hi @nojaf 👋 

Thanks for the update!

I may be missing something, but doesn't look like it's fixed when I tried with `fantomas-ui` on preview mode:

![new_lines_2](https://user-images.githubusercontent.com/7033564/67616178-f90d3d80-f7d5-11e9-8a09-669124bd5ec2.gif)

I made sure to copy the formatted code back to the input before hitting format again, to simulate how it would work in an editor.

For reference, I'm just using the functional _Getting Started_ sample (the second code block) from the Giraffe docs here: https://github.com/giraffe-fsharp/Giraffe#doing-it-manually

Please let me know if I can help test anything else on this.

Thanks!

**Comment by nojaf** [comment]
I think if https://github.com/fsharp/FsAutoComplete/pull/510 gets merged it should be ok in Ionide.
