### ISSUE TITLE
Record update indentation incorrect around comments

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#537]
### Description

If there's a comment line, the following line(s) can get the wrong indent

### Repro code

https://jindraivanek.gitlab.io/fantomas-ui/#?code=ATA2FMBdgQwJwOYGdgF4CwAoEIAUBvYAQVEgGEB7AN3DgDoAFeGAWyTrLnBknGAAcu-YAHcAlpAAWwACoUKoJlLTAAypDhiAdgjoBRFv0gBPLDnMXLV61YD0tuQpnH+fVMVKUa9R6Geu6AHFQCgAjGFAzG2iYmwB1CjgAa20EABExLgBjSETjFQAiOgLgAF8onAAfAD4PcmpaOiyKQwokcEoWFhgtABMAGW1wAEoOFu6+wa1wIA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZECcADAL5A

**Comment by nojaf** [comment]
I think this is ok now.
[Today (03/01/2020) this formats](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=ATA2FMBdgQwJwOYGdgF4CwAoEIAUBvYAQVEgGEB7AN3DgDoAFeGAWyTrLnBknGAAcu-YAHcAlpAAWwACoUKoJlLTAAypDhiAdgjoBRFv0gBPLDnMXLV61YD0tuQpnH+fVMVKUa9R6Geu6AHFQCgAjGFAzG2iYmwB1CjgAa20EABExLgBjSETjFQAiOgLgAF8onAAfAD4PcmpaOiyKQwokcEoWFhgtABMAGW1wAEoOFu6+wa1wIA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZECcADAL5A) to
```fsharp
let args =
  ({ AltCover.Params.Create prep with
       ToolPath = String.Empty
       //ToolType = AltCover.ToolType.Global
       WorkingDirectory = "." }
   |> AltCover.composeCommandLine).CommandLine
```

and produces valid [AST](https://jindraivanek.gitlab.io/ast-viewer/#?code=DYUwLgBAhgTg5gZwgXgLACgIQBQG8ICCwYAwgPYBuIMAdAAqxQC2CNJMIUYIEADh7wgB3AJZgAFhizSsAFTJlgDCSggBlMDBEA7ODQCiTXmACeUmVgD0l+YtknePZIWLkqtW8HuOaAcWBkAEZQwOYWAOpkMADWOnAAIiIcAMZgUSaqAEQ0mRAAvmEAPgB8LqSU1DTJZEZkCCDkTExQ2gAmADI6IACUbDXNbZ3aIBhAA&defines=Q&filename=MoYwTglgDgLgdAMwM4A8g).

Please reopen if we still missing something here.
