### ISSUE TITLE
Lack of simplest possible usecase coverage

### ISSUE THREAD

**Issue by wrodemy** [fsprojects/fantomas#543]
What I need is just format F# singlefile code as a string with simplest possible/default config.
For isntance:
 
`let code = """some f# code"""
let formatted = code |> Fantomas.format`

Can't find any example of that or anything similar.

I looked at code of fantomas-ui which do more or less it, however it is very complicated for such a simple purpose and it looks like I cannot use Fantomas for plain strings: need files instead?

**Comment by smoothdeveloper** [comment]
@wrodemy could you check if https://github.com/fsprojects/fantomas/blob/e29566225aa66a008fc2790c70abe074bd718b55/src/Fantomas.Tests/TestHelpers.fs#L23-L25 does what you need?
