### ISSUE TITLE
SpaceBeforeArgument inconsistency: should apply to both camelCase and PascalCase funcs

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#554]
### Description

The `SpaceBeforeArgument` option doesn't have any effect to functions with PascalCase names, as opposed to functions with camelCase names.

### Repro code

https://jindraivanek.gitlab.io/fantomas-ui/#?code=PYBwpgdgBAygngZwC5gLYCh0BsxKgYwENUwsBhQhMACgDNhgAuKAIUICcBKZtgLygC8Uap0w48ABUpFylGvSasO3JfyEigA

```
open System

let camelCase(foo: Bar): Baz = ()

let PascalCase(foo: Bar): Baz = ()
```

Current results:
```
open System

let camelCase (foo: Bar): Baz = ()

let PascalCase(foo: Bar): Baz = ()
```

Expected results:
```
open System

let camelCase (foo: Bar): Baz = ()

let PascalCase (foo: Bar): Baz = ()
```

**Comment by nojaf** [comment]
I think `let PascalCase(foo: Bar): Baz = ()` is something you would never write as F# functions typically start with a lowercase letter.

> Use camelCase for class-bound, expression-bound and pattern-bound values and functions

See https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#naming-conventions

So the current behaviour will probably assume that uppercase identifier is part of a dot expression.
F.ex. `foo.ToString()`. This seems very weird to me to write like `foo.ToString ()` imho.

Quick search on Github:

**Comment by VelocityRa** [comment]
@nojaf I don't think naming conventions should affect the output of a format tool. At least that not the case for formatting tools that I'm familiar with from other languages.

If the language/compiler enforced them, probably, but that's not the case here.

**Comment by knocte** [comment]
> A quick search on Github:

That only demonstrates that following the SpaceBeforeArgument convention (in our case, formatter flag) option is less preferred than not following it. You would need to find people using things like `if fooBar () && foo.Bar() then ...` in the same codebase to support this point of view.

**Comment by smoothdeveloper** [comment]
AFAIU it would be possible to replace the convention about PascalCase / camelCase (not entering on the naming convention side of the argument, I think it needs to be mitigated with function code and OO members and idioms adopted in F# for long now)

```fsharp
let camelCase (foo: Bar): Baz = ()
let PascalCase(foo: Bar): Baz = ()
```
we could consistently put the space here, because we aren't in a member definition.

I think the Pascal/camel convention can still be observed at call sites, if it is a LongIdentWithDots:

```fsharp
let a = PascalCase()
let b = camelCase()
let c = something.PascalCase()
let d = something.camelCase()
```

would turn into

```fsharp
let a = PascalCase ()
let b = camelCase ()
let c = something.PascalCase()
let d = something.camelCase ()
```
