### ISSUE TITLE
Strict mode strips literal strings

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#560]
Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=DYUwLgBAzhC8EAEBEAdJQ&config=N4IgygDghgxgpgQQGYBc4CcDCB7AtrqEALiSgBsBnOAGnGnmTXTDlwEsZszsA7Y0yjTqxE6bAFceAEwAicMm3ZN+5KrUgiAQnCTZ0ogObjccHihWD1KdBxQBZbFLjFr4uAF8gA)

Strict mode causes the `@` to be stripped from strings, possibly causing code to stop compiling.

#### Code

```fsharp
let s = @"\"
```
            

#### Error

```fsharp
let s = "\"

```
            
#### Options

Fantomas Next - 3.0.1-11/13/2019

| Name | Value |
| ---- | ----- |
| `IndentOnTryWith` | `false` |
| `IndentSpaceNum` | `4` |
| `KeepNewlineAfter` | `false` |
| `PageWidth` | `120` |
| `ReorderOpenDeclaration` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| **`SpaceAfterComma`** | **`false`** |
| **`SpaceAfterSemicolon`** | **`false`** |
| **`SpaceAroundDelimiter`** | **`false`** |
| **`SpaceBeforeArgument`** | **`false`** |
| `SpaceBeforeColon` | `false` |
| **`StrictMode`** | **`true`** |

**Comment by nojaf** [comment]
Hello @Smaug123 ,

Strict mode means it will only use the information found in the UnTyped AST to print out the formatted code.

The AST, in this case, looks like this:
```
ImplFile
  (ParsedImplFileInput
     ("Script.fsx",true,QualifiedNameOfFile Script$fsx,[],[],
      [SynModuleOrNamespace
         ([Script],false,AnonModule,
          [Let
             (false,
              [Binding
                 (None,NormalBinding,false,false,[],
                  PreXmlDoc ((1,5),FSharp.Compiler.Ast+XmlDocCollector),
                  SynValData
                    (None,SynValInfo ([],SynArgInfo ([],false,None)),None),
                  Named
                    (Wild Script.fsx (1,4--1,5) IsSynthetic=false,s,false,None,
                     Script.fsx (1,4--1,5) IsSynthetic=false),None,
                  Const
                    (String ("\",Script.fsx (1,8--1,12) IsSynthetic=false),
                     Script.fsx (1,8--1,12) IsSynthetic=false),
                  Script.fsx (1,4--1,5) IsSynthetic=false,
                  SequencePointAtBinding
                    Script.fsx (1,0--1,12) IsSynthetic=false)],
              Script.fsx (1,0--1,12) IsSynthetic=false)],PreXmlDocEmpty,[],None,
          Script.fsx (1,0--1,12) IsSynthetic=false)],(true, true)))
```

The `@` sign is not part of `Const(String ("\",Script.fsx (1,8--1,12) IsSynthetic=false),` so it is inpossible to know without looking at the original source code.

This is a known limitation and your best bet to resolve this is to open an issue at the [dotnet/fsharp](https://github.com/dotnet/fsharp) repo.

**Comment by Smaug123** [comment]
I'm not convinced that Fantomas should just pass this off to the F# compiler. Isn't the `"\"` that you quoted just an unescaped string? It's possible to format an unescaped string canonically, by printing it with an @ in front of it and duplicating any double-quotes inside it, if I understand correctly.

**Comment by nojaf** [comment]
@Smaug123 as we currently don't have this issue in a non-strict mode, I made a suggestion to store this information in the Syntax tree compiler https://github.com/dotnet/fsharp/issues/10209.

Yes, Fantomas could try and detect this based on the content of the string but the compiler at some point has this information, so it seems like a good case to get my feet wet in extended the compiler itself.

**Comment by Smaug123** [comment]
Good idea - this is certainly not a high-priority ticket, we don't expect to be using strict mode.

**Comment by nojaf** [comment]
Following up on this, with a lot of help of Chet, we were able to submit https://github.com/dotnet/fsharp/pull/10769.
This could provide the missing information in the AST.

**Comment by nojaf** [comment]
[FCS 40](https://www.nuget.org/packages/FSharp.Compiler.Service/40.0.0), has what we need for this. Looking forward!
