### ISSUE TITLE
Fantomas keeps adding new lines between two interface member implementations

### ISSUE THREAD

**Issue by ivan-brko** [fsprojects/fantomas#569]
### Description

Fantomas adds a new line between two interface member implementations each time the file is formatted
### Repro code

```
namespace Quartz.Fsharp

module Logging =
    open Quartz.Logging
    open System

    //todo: it seems that quartz doesn't use mapped and nested context,
    //however, check if this is the best implementation for this interface
    type private QuartzLoggerWrapper(f) =
        interface ILogProvider with

            member this.OpenMappedContext(_, _) =
                { new IDisposable with
                    member this.Dispose() = () }
            member this.OpenNestedContext _ =
                { new IDisposable with
                    member this.Dispose() = () }

            member this.GetLogger _name = new Logger(f)

    let SetQuartzLoggingFunction f =
        let loggerFunction level (func: Func<string>) exc parameters =
            let wrappedFunction = Helpers.nullValuesToOptions (fun (x: Func<string>) -> (fun () -> x.Invoke())) func
            let wrappedException = Helpers.nullValuesToOptions id exc
            f level wrappedFunction wrappedException (parameters |> List.ofArray)
        LogProvider.SetCurrentLogProvider(QuartzLoggerWrapper(loggerFunction))

    let SetQuartzLogger l = LogProvider.SetCurrentLogProvider(l)

```

[The link to fantomas tool example.](https://jindraivanek.gitlab.io/fantomas-ui/#?code=HYQwtgpgzgDiDGEAEBFAriATgFwF4DoAxKACyxgCgKwB7AEzQBtkAZGgc3YEth2kBeCkmFIaMCMFQYcBNpx7shIsRKQBlAJ5RsEMFRFIA9Iez0aALiRdsSKBF1Qk2MjYCO0vEjo1owAOQ2aHZIYCAw4nRIIMCRwNA6kfA0wDoAHtgANErCxiQ0AO4QAG4QmBlI8CQQ8ADWVgBmTiRcji1NyABG8VZgMMyQKSDYXMlI9TSYTW08Opj1CBDZThriSDCYXEVDyOhYeHLspQDqmGHimAAU9QCUAksGM6XziEgAknIACpg0RVx0pUh8tYSPoDGDhJAwF1Js4WvgAPLiYAAWTOEDoAGFkmlsBcAPrlPG3QTg0kiADeSDi+TeABEWjAaFAQB1mIDgfcyaTIdCplB8PTYEyIBdiUhRUgAL6grkhXS82H8xESABy8XRWJSEHSSDxd1l4Mp1LpDKZLLZQOcnINIh5AMVAtNdgl-HFt2l1rBdphzX5AHEINgDgC8aBIAIqRAacHLjcZUhmDY1IHdjIDgpCGhgPBhqNGiTSYmExxDphM9nc5JmCVGOL6ln4JZy-AADzaDa8AB8t218DWWHAgdKjgLsqL+VO4XRzcrEYAEhBGOd+cAmIwAGogRhoaAAFRoiMrjiuWfFqSbDbb2A77G7SAAtJ266eJY+kKl8K9gEUaDURdcALGBtPQMcdJwiABRVJEBgWdXQXJdh3wVdGA3LcdygfdDxGYBWkiXsQJERpq0XQFwOnBtZwnNE6CgmDZwuOBTkgWZHAAHyfFgWmwfAaHqABBTBTg0a5PU+b5fn+TB8GTbAMTQISJCDDgvh+P5SguVN9hLY5yMuRgdLLSicIA+Mi1krTcBjBMI3EtSpJkwN5MUlI7MkjTGFEoA)

You can check if you copy the formatted code from the right to the source and format that, it will add new line after line 17, and it keeps doing this forever.

**Comment by theimowski** [comment]
Minimal repro I could come up with: https://jindraivanek.gitlab.io/fantomas-ui/#?code=C4TwDgpgBAggFASigXgFCqpqBbC2BGEATlMABYCWAzgHQCyehRMKGW7FAZqUQK7TkIAOygAGKBAA2VaAEZ07XAWKlKtBsqIAhVuw7dgfAWWFQATBOnQAzAqxKmq6vUbEAwijGogA

**Comment by nojaf** [comment]
The problem here is that Fantomas adds a newline between each found `SynMemberDefn.Member`.
However a blank line was found in the trivia and is also printed.

So you end up with an extra newline. We have encountered this issue on other places as well.
The fix is to use the [sepNlnConsideringTriviaContentBeforeWithAttributes](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L199) function instead of sepNln. I would need to debug to see where exactly this should be done...

**Comment by theimowski** [comment]
I started looking at that, but I'm completely new to the code so I can hardly understand anything yet.

What I found is that there are two pattern matches on `MultilineMemberDefnL` in `CodePrinter`:
* [MultilineMemberDefnL(xs, [])](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L1922)
* [MultilineMemberDefnL(xs, ys)](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L1942) 

and for my above snippet I end up in the later one, while if I remove `MemberC` then I end up in the first one and the extra newline is not added

**Comment by theimowski** [comment]
Ok I think I got it, bare with me - a PR coming
