### ISSUE TITLE
Empty lines in multi-line string get moved

### ISSUE THREAD

**Issue by theimowski** [fsprojects/fantomas#577]
Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?code=DYUwLgBAHhC8ECIkGcD2BbEAoLBjVAdmCETgO4CWYAFhCOgA5gCeEwFBIySCQA)

As in the example - looks like the empty lines from the string itself get moved before its declaration

#### Code

```fsharp
let x = """some

content

with empty lines"""
```
            

#### Result

```fsharp
let x


 = """some
content
with empty lines"""

```
            
#### Options

Fantomas 3.0.0

| Name | Value |
| ---- | ----- |
| `IndentOnTryWith` | `false` |
| `IndentSpaceNum` | `4` |
| `KeepNewlineAfter` | `false` |
| `PageWidth` | `120` |
| `ReorderOpenDeclaration` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `SpaceAroundDelimiter` | `true` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Fixed by https://github.com/fsprojects/fantomas/pull/593
