### ISSUE TITLE
Empty line added on each format

### ISSUE THREAD

**Issue by vilinski** [fsprojects/fantomas#597]
Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?code=HYQwtgpgzgDiDGEAEBpATggFgKG2A9gCYCuANsgErHDARpIC8uSLS5ALkmAAp0DKEePmCFGSAIwAGaQB4wAeiiDhhAHzNWAbRkBZCCCjE0EVQF1srJOwCeMZNzT5EUKAElRTS5fikDUC14sECLYQA)

Each format adds a new empty line after `let mPerSecond`

#### Code

```fsharp
namespace Krach

module Runner =

    let mPerSecond = 1000<m/second>  // after this line is a new line added

    [<Measure>]
    type ProcessId =
        class
        end

```
            

#### Result

```fsharp
namespace Krach

module Runner =

    let mPerSecond = 1000<m/second>


    [<Measure>]
    type ProcessId =
        class
        end

```
            
#### Options

Fantomas 3.1.0

| Name | Value |
| ---- | ----- |
| `IndentOnTryWith` | `false` |
| `IndentSpaceNum` | `4` |
| `KeepNewlineAfter` | `false` |
| `MaxIfThenElseShortWidth` | `40` |
| `PageWidth` | `120` |
| `ReorderOpenDeclaration` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `SpaceAroundDelimiter` | `true` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
This is already fixed and will be available in the next release.
See https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=HYQwtgpgzgDiDGEAEBpATggFgKG2A9gCYCuANsgErHDARpIC8uSLS5ALkmAAp0DKEePmCFGSAIwAGaQB4wAeiiDhhAHzNWAbRkBZCCCjE0EVQF1srJOwCeMZNzT5EUKAElRTS5fikDUC14sECLYQA

**Comment by nojaf** [comment]
@vilinski you can use a pre-release from MyGet if you want, https://www.myget.org/feed/fantomas/package/nuget/fantomas-tool
