### ISSUE TITLE
Invalid code produced when formatting type alias for struct tuple

### ISSUE THREAD

**Issue by maxdeviant** [fsprojects/fantomas#605]
Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?code=C4TwDgpgBAKgrmANhAysATnAxsKBeKACgGcNtcSMBLAOwHMoAqKU9WugSg6A)

When formatting a type alias for a struct tuple the resulting code is not valid F#.

#### Code

This compiles correctly:

```fsharp
type TupleStruct = (struct (string * string))
```
            
#### Error

This no longer compiles without the wrapping parentheses:

```fsharp
type TupleStruct = struct (string * string)
```

Note that this seems like it might be a shortcoming in the F# compiler: [dotnet/fsharp#7014](https://github.com/dotnet/fsharp/issues/7014).
            
#### Options

Fantomas 3.1.0

| Name | Value |
| ---- | ----- |
| `IndentOnTryWith` | `false` |
| `IndentSpaceNum` | `4` |
| `KeepNewlineAfter` | `false` |
| `MaxIfThenElseShortWidth` | `40` |
| `PageWidth` | `120` |
| `ReorderOpenDeclaration` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `SpaceAroundDelimiter` | `true` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
I think it would be possible to always wrap struct tuple in parentheses.
