### ISSUE TITLE
Adjust default configuration to be more F# idiomatic

### ISSUE THREAD

**Issue by dungpa** [fsprojects/fantomas#61]
@dsyme's suggestions:
1. Set `SpaceBeforeColon = false` by default.
2. Set default `PageWidth = 120`.

Steps to handle:
- Adjust default values in https://github.com/dungpa/fantomas/blob/master/src/Fantomas/FormatConfig.fs#L26
- Fix failing test cases

**Comment by nojaf** [comment]
PageWidth is now 120 and SpaceBeforeColon is false, see [FormatConfig](https://github.com/fsprojects/fantomas/blob/c9fc003787e5c183f73e7acbeb946a38bd7529ad/src/Fantomas/FormatConfig.fs#L30-L34).
