### ISSUE TITLE
Extra newline between attribute and function

### ISSUE THREAD

**Issue by martinbryant** [fsprojects/fantomas#611]
Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?code=PYBwpgdgBAygngZwC5gLYChSSgGQJYBGATgIZFzroDaAPAKIRLkAKwejAfALqW-oA2YJFFQl2UMgHMAblAC86KEqggi7JADNoAIgByeAMZgoB4KlEQAJgFp+7Y1ICuqSEgQBCKAAkwRMAHIEKAB3AAsSYQApGAB5XQA6XToAFShwoKRgKAQSOAkCYEdhJFC0AC5tCSIZRWUAHw4oAEEiUjh40RAoSSFIhGAIXV7+6Abm1tz4vBQiKAAKVXUtKG0AUgRtAEooWqUABigAekOoPyRHImgSaHUwHtmwAA9pk2BLMCA&config=N4IgygDghgxgpgQQGYBc4CcDCB7AtrqEALiSgBsBnOAGnGnmTXTDlwEsZszsA7Y0yjTqxE6bAFceAEwAicMm3ZN+5KrUgiAQnCTZ0ogObjccHihWCAvkA)

Using the CLI and the online tool both have the issue

**Actual behaviour**

v3.1.0 - Does not remove the extra whitespace in a file

**Expected behaviour**

v2.9.2 - The extra whitespace is removed

**Steps to replicate**

- Click [here](https://jindraivanek.gitlab.io/fantomas-ui/#?code=PYBwpgdgBAygngZwC5gLYChSSgGQJYBGATgIZFzroDaAPAKIRLkAKwejAfALqW-oA2YJFFQl2UMgHMAblAC86KEqggi7JADNoAIgByeAMZgoB4KlEQAJgFp+7Y1ICuqSEgQBCKAAkwRMAHIEKAB3AAsSYQApGAB5XQA6XToAFShwoKRgKAQSOAkCYEdhJFC0AC5tCSIZRWUAHw4oAEEiUjh40RAoSSFIhGAIXV7+6Abm1tz4vBQiKAAKVXUtKG0AUgRtAEooWqUABigAekOoPyRHImgSaHUwHtmwAA9pk2BLMCA&config=N4IgygDghgxgpgQQGYBc4CcDCB7AtrqEALiSgBsBnOAGnGnmTXTDlwEsZszsA7Y0yjTqxE6bAFceAEwAicMm3ZN+5KrUgiAQnCTZ0ogObjccHihWCAvkA)

- Change version to 2.9.2 and see the whitespace removed

#### Code

```fsharp
open System
open Library

[<EntryPoint>]





let main argv =
    printfn "Nice command-line arguments! Here's what JSON.NET has to say about them:" argv
    |> Array.map getJsonNetJson |> Array.iter (printfn "%s") 
    0 // return an integer exit code
```
            

#### Result

```fsharp
open System
open Library

[<EntryPoint>]






let main argv =
    printfn
        "Nice command-line arguments! Here's what JSON.NET has to say about them:"
        argv
    |> Array.map getJsonNetJson
    |> Array.iter(printfn "%s")
    0 // return an integer exit code

```
            
#### Options

Fantomas 3.1.0

| Name | Value |
| ---- | ----- |
| `IndentOnTryWith` | `false` |
| `IndentSpaceNum` | `4` |
| `KeepNewlineAfter` | `false` |
| `MaxIfThenElseShortWidth` | `40` |
| `PageWidth` | `120` |
| `ReorderOpenDeclaration` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| **`SpaceAfterComma`** | **`false`** |
| **`SpaceAfterSemicolon`** | **`false`** |
| **`SpaceAroundDelimiter`** | **`false`** |
| **`SpaceBeforeArgument`** | **`false`** |
| `SpaceBeforeColon` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Hi @martinbryant, thanks for reporting these issues. I'm sorry to see that you had a bit of a rough start with Fantomas.

Regarding this issue, do you mean the blank lines when you say "extra whitespace"?
If so then this is by design actually. We preserve newlines from the original source code.

By that logic, the bug I see here is that an extra newline was added after formatting the code.

**Comment by martinbryant** [comment]
Ah @nojaf no problem. Been quite a learning experience to be fair.

Yeah I would have thought that the extra whitespace would be removed as it was in v2.9.2. Any formatters I have previously used(Prettier, elm-format) would remove any extra whitespace to provide a consistent experience.  

Appreciate that the behaviour would change between versions though. Maybe we could get another cli flag?

**Comment by nojaf** [comment]
preserveEOL introduced a lot of problems and just didn't work in certain settings (f.ex indentSpaceNum = 2).
It became unmaintainable, to be honest.

I understand that the current behaviour isn't really what you expect coming from other formatters.
However, the most feedback I received about preserving the newlines from the original source code has be genuine positive.

Could you maybe create a new issue to discuss the removal of newlines? Maybe we can consider a setting to set a limit to the number of newlines.

I would like to use this issue to solve the problem that [a new newline is introduced after formatting](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=PYBwpgdgBAygngZwC5gLYChSSgGQJYBGATgIZFzroDaAPAKIRLkAKwejAfALqUA2YSKKhLsoZAOYA3KAF50UBVBBF2SAGbQARADk8AYzBQ9wVMIgATALS92hiQFdUkJAgCEUABJgiYAOQIoAHcACxJBACkYAHltADptOgAVKFCApGAoBBI4MQJge0EkYLQALk0xIil5RQAfDigAQSJSOFjhEChxAXCEYAhtbt7oOsbm7Ni8FCIoAAplVQ0oTQBSBE0ASihqhQAGKAB6fagfJHsiaBJoVTAu6bAAD0mjYHMwIA&config=N4IgygDghgxgpgQQGYBc4CcDCB7AtrqEALiSgBsBnOAGnGnmTXTDlwEsZszsA7Y0yjTqxE6bAFceAEwAicMm3ZN+5KrUgiAQnCTZ0ogObjccHihWCAvkA).
