### ISSUE TITLE
--help and --version return exit code 1

### ISSUE THREAD

**Issue by martinbryant** [fsprojects/fantomas#612]
### Description

I have been looking into the [fantomas-fmt](https://github.com/pd29/vscode-fantomas-fmt) vscode extension issues and came across this issue when using node child processes that check whether the fantomas tool is installed before activating the extension

**Actual behaviour** 

When calling --help or --version, an exit code of 1 is returned

![image](https://user-images.githubusercontent.com/25330805/71519723-a53fd300-28b0-11ea-9888-618b9002962e.png)

**Expected behaviour**

An exit code of 0 should be returned as there has been no failure, as exit code 1 is for general errors

### Repro code

n/a as this can be reproduced on the command line

**Comment by nojaf** [comment]
I can reproduce this in Windows as well.
I'll try and fix this in https://github.com/fsprojects/fantomas/pull/607.
Thanks for reporting this.

**Comment by nojaf** [comment]
Fixed in 3.2.0
