### ISSUE TITLE
Assembly attributes create over-long lines

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#629]
### Description

A sequence of [<assembly:... attributes, one per line, get run together into a single line, ignoring the page width set.

### Repro code

[Example here](https://jindraivanek.gitlab.io/fantomas-ui/#?code=HYQwtgpgzgDiDGEAEBBANgFwMIHsBuEATgHQBqAllAK4hrkBeRAsAFCs4wTBIDKAnlAwQw7Tt36DhxAEoQAZmgjwM5HMFFdeAoWBlVgKyMQCSBohx5E85RFFasA2gB4QUKMIBGaPgC4sAGR5cMBg6EAMACgxCKggASgA+AF1HFzdPbz8cMAooci8ICLlad0SUlmdXdzAvXxR0mu8AFXIMRQiAInRsfCIySho6RkIOstSqjLqG2oARaHhCchgVNU7cAkIQAHNkcIATJEEQFXgkcNoBSiRraloGIiQ5HEIkADl1h4iYHDd87yQIAAPITAPYQPZxM6gpAAeTEHxGYwqaWqtR8Eh0MmgOCohFsxFeECo0VosigOLx0H84S2NB2KAw0XyxMKHS4AFoAOIAIVGyVYETiQA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZECcADAL5A)

**Comment by Swoorup** [comment]
Another example still occurring on master: [Asp.Net controllers](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAdAdlg9Dg2gDwCCADgJYCiAHqQDawBOijAyogC4fmYDmAzgAoAkr0xNEZcmAC8YDowCuiAJQA%2BALpYiAJViKOiQekgBDCjgBuARhyn4AWx45yD0kw4n1WzBwCepIhgenSSjjzCbh4AwrC%2BjLB0oYyCpgDWaabsjJbk0IhoxBlZLLn5KrJYEDwAFizkHGCx8YnJgipYVWBEABJcpADinMaQAFawAEb8dkleANxdEAAKCfCK%2Bfw6iPzumPyIACoBRv6BsABmhBOwiWoANGAATAAMzyoLmBDLq%2BvbWztxfZHQKCAAsz1B70WYGIBhqTHIAC8jLCOPDGEjTNw4qw4IElok8uRtgA6Lb2bxdByIBwTFhgAD6JIAMuR%2BBwAFKTIQqNAHUz8NKEACq%2B0Y0Qc8H%2Bu32AFl%2BLw1JVPl8OAK0mBgNCIMwOIpGJgAITar7pTLZMqIEmRdyMQxsPzsmkkqSygX2sCEAD8MIobqdjHlvBJQw4xCSXKmEvg0IAvp0Vb1%2BgT2SNxlMcNBmFjEPNoQARNmmCahLYAR2U7NYSMQrKcHA%2BX2CiAr2w4ADEmA46w0hLLFHRuKRTHaAEIIPzMxB8NE9xpyACszwAnAB2awLl7PZlQlXfBC-TbbGWHY6CU6IC6EEKIaI1Ux8RCsRQOBwjvz5jiwMB0Nkce5PK8u5NisB4bNKgKniC4KQo2XyouiNaCAhCKIli5A4niiAEr%2B0DEvwJIAOoYoYlIqtStL0kyrBqnakaCOc5ChGgwidowDjtkxiAPEQ7YJA4ACKyiMH4mhgCOAgsVEdosJGxCMAIFQyNCoSNK4toenIZolDkeRWjaHgsKwjqGA4CZNsQ0DYpg-wDhwJIXMQ-B%2BJg0C2YOnoAD7ic5rnuY0Wp7l8qmGmA7I5sqTZNoIzKwAA7iw0QCk%2BCg8MGWaIBFEkETROYPIxoQdEFTaeUqFCBAA8hMoyIFZBw1Akii8DUABqpi-vA6FxN0YAMeyPHhYYwj8G1HUaO8vX8Jg8A8QxiifPwYAALRKhVGr8Co41gD4UVfCaIVgAV2FYjUshgGxHFcSS8DxZgDD2E5Bw0qQh1ceZUWqWA6aRbtmpgJGwJBHIlD8Bi47zZ1IkGXaJpNpxoQHLA0Pzq9oRLCdsNfLlhhnYNubFVF%2BYiTo81ndlJJE34JOfPG2AE%2BphmMC6fruvShChbldrI9GX2TCaur6p8a28xMcZYJAdzgFA%2BxcGl-CoN0UsQKAu2QAAJBeCuQDwHAS0rXzq5Y7XKAr%2BD602zyS79UDCNN04cKww75AAci%2BevW6C5vbfrsZW18KtRermtoNrvju4HatG3QJtoGb1vWH7qvo7wiCEeQ8BouHu3WC8XsaD7ieal7QfHFr1yJFnBuR8byCx17ECPIXTaQOwThwAwmDEBwlDTRV5yspgyBN185ztfsecF-rAfNxrpch%2BXdCVxAhs16b9dgAAzMPy%2BO6Y%2BSjog5wSOjjCmNS9pL6qSiIBPTa%2B1Pxez4EZc3Ivw8r9HteKx729QLv%2B%2BHwkLFBKjBoDJVtpYWAYDrKXwgAoZQt8vj3ybNPKuwcoAL0vh-GO39foLl-i3J2iAD5H2YMKUggRQHgMwJA6BGFMCwMOmPG%2Bu18530Lqg5eT8v6QEwe-aun817WwAGwEP-sQwBzBoh0AFPwZo7IlBWSYIw0edBx6sMnigx%2B6DeGvywQInBcdfqrjEUQkhEhZQ0jpIwFRzDEEQGQf7bRc8MF6P4VHQx68AAcpi94SNIbeRIcRbFqJYVFNhSCOHOOfvPNxj8PFfyMbtZcvj8jEHOPaWIr5TCMPgWEpsESHFRNVtwl%2BFd3GrzrvHS269CF%2BPMcwVueQgkMN-qo9R4TNFOJKTovh8TKm4OzgnWp4j0n2iae3YJv88n2LAI45W0SeF9JKQkoRv0c4ENtkgXwFVMAHBEmnTObS7EaPYQ-HpLjdHlP6YIqp6yt4jKIfJfQ018yIF-PWFguTr6zPmUXC5MSoA630asu52dQQELdNQYQ5x6rTkoKE1g6IOBpwzjURh4JfnFIjjo4FFTbmDKihuSFphoWYEYtQCqlCsRMBoKQZg-B%2BD0MYUuLF5ycWXLxTczx8dRG1KhVsOAjB4CoqOevTFpzInspnrisO%2BKeXrJMfy0l8lT5%2BAqowVk7JRXot-hKzpZytEAp4VylZAyklEp8cq6gU4OCjh4PANKOqMXPDZUajlgKrlv25Yk9e1gUn8rskxHgxCGDQDSKOU%2B4bOD8F2awM%2BgTo4OFaevdp%2BSviFLmdimVlzlkR1BYSpsLwCHO0QHFX8g8D4cAStOQGbzGKYAaPQ4g01LGUUYPLY5oS3XdI9UsuJZqCUWqLcM62kAADSiBECkBhXCzAtt43UgHkPVNJyDVSvdTmz1eaZ4FuHV8R4jcRmpSsrKBAK7rZpt%2BVLDQfttb8HbEyhWV7YxAA)
