### ISSUE TITLE
Conditional code block deeply indented with no cues to do so

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#637]
### Description

Possibly related to #636, the contents of a `#else` are deeply indented and not aligned with anything in the surrounding code.  Obviously, this leads to compilation errors.

### Repro code

[Here](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=ATA2FMBdgSwO0uATnAhqYB1JNEEEBnA8AWwCNQBPYAClSNIuoC5hDjyqARcAM3lwwA9nACUtAA6pIAC2CsCkHHADm4gLwBYAFAgQEaBIDW4auuABZEUIB0AYXABjGKBvZcyAAqokqElGQCGlEdPTAoWAJMeAATIQB3AmBzAGVKRVIbAFE4ADcYJBF-BBsAcSgc-MK4YsgANR8YVApwGgAiAHkUto1gNui4OMSAfQA5ABU2nVC9A2AJGLJkmbDPQpVfEi5pZvpwMqhPRejZADF0UDJURyNgeg4mFb0AHwA+YA6JSGE4GxUoDpILKgYh9AAeNgWZCmujCwDewG8sgOkCyYMQcAIPx0AGIYLxgKMsuM7B0AEpZPCeTwAJmGAAYnnNiFJfIgjkstLDVutNttILtiCiOadCiQAJIkVD-O4MTiUJ4gBGfb4iGz8UCIJC0XgAVzgwCSAFp3kkADzvOhypg2UZ+fZ2-zAADUfUhix6IW5L3eKp+NhgBBSQn8029AHpwx84I5wMAHM4MPSbABGenAMhQVAANkiwAFJgNQl10CEBNkcfAAEdddIfgAafMyQPAeJCJBGAhPSN3VnQXhi4BIcBoEjwFSyh6gGDgJLTkxsTV2IS5ZA2MlOdsxZD5oSLyDL1dIdebpDb48qbtR9vAXg3+6Maez1u4OSMcAxbcxYDupbwO9IFKqoGjQIjAAAVHAMBgl6YTGKYbg4IgaTkEIILAGaRq0IGAxDEkzzPIa4CstI4AcuIABkFGTo+lA2BYqDwFYMS6hANgABL0ChZBoV23rwXR3Foe4WprCuMDnhhRqKsAQGOHINBQo2AmIR4QkguI8SvjJhHtL+bSNkourgOIJqWNY9hOC4NgcjZxxIV4hT5OewTyO84rqSJjnieeOm0MMhlIMZpnvFYcC2Am1kWIs9H2R4SBic5yCucw7meQ5CVORJyB+cMwBmXArGgLi4AguAV5sNaVAvrI8yLK2SHjrejHoWBJDWMAYG4QkSTxDII4NYIqg1TIFVpBkJC2kVG68MgI6xmisZfD88gfGQABWTjQMOs3DjGcbhdAxDQJAe6oAa8CKOdsadQS52dRtW02BVA4hsA27EbAmLZfGVnFRGUYcoN3zDbwLVJG1HVgeFcBGt1iQjWN6SIJNXCgKAoxCJApzFoMi3EcBq1oeAADMNI2DE6MVXc0A0PEvgSBIO5Smg-wxEap1Gmg3yruIYURX9dlkDYKFeUgzDLnYw6keKmICvtFXRUs9NDRO4XxM1LhJPAP5wBEA72m2HaNrgTaFIkisWcuJASC4yApMg+SxgQIuUKhoBi-R1jqacdv48tYHMBV-uE2W+aUEzwAAOT8-YIa2xASAO0gTuzq77ue-zPt+2CS3AVHrb0GbCS-BV4rlv1w53FXEjtgKLQ-lCEMGu14WGTIQigmDLi7sD4CGUIe5abIlvhXHNt20njswM76c8R7GVe+F2cQCHK1BwDwBr2BYeQBHcYx1b8eT8nqcu+l8VL0IK-gNvcAF-EReyObpf8SYdFeep5pYThsQ9U8KkL6iSypJTCMkpbgFIkAncUJIjwySK3IQZJ9TfFDNoHEI4Yj4ieAAaXVnAHBpgaLyltPaJ4yoA6-HijqfUwB375XeIApQIgVCOnAIQygAAhUAQgliYToQhbhvD4TvAADKBkgDYU6eAkC+EoF6JkERK5xnMFwAoW12x0XKAeXUsiRyQDUcORwp0kCUGCE8JQCpvQgEMRo0xIsoB2F0XtAx6jjGaJoEiGQKJbHuNMWwxS0gZCiFgnCOYKtEC0FQKtdgtEeD8CgsBcQEh5i3C5HCPQupQRYjgGk4Avs2KfBHIpRsBTwDMX2BA0ipS7Z4EcM7F2G5UAxC8qEjJqBVKIBoDkowykjAKOseEbas40JHmSMQm0DEmJCBYmxWJ8oNwEFGTlQZ7FB5GEWcs7Uw4lmgCPDJCJcYHzynmEE1JpgngJIuFYjJviTGCUcc4-RdyPHKK9EAA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZECcADAL5A)

**Comment by nojaf** [comment]
I don't think this is an issue anymore. See [online tool](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEA2iAuYCWAdtogE4ECGGYA6iXsQIIDOTiAtgEYYCeYAFORbsuvNM1aceAEUQAzQvTywCASn4AHctgAWYNE2x0CAczUBeADokLBCJhxh1Aa0S8zYALLLYAOgDCiNB4GD609KQACuQk5Gw4pEx8KlY2dmBYuHhM1ITwsADuTGDuAMrcBuw%2BAKIEAG54JMpxRD4A4jg19Y0EzdgAatF45FyIfBaQAPIl4%2BZg4zkEeYUA%2BgByACrjKQTbaRmO8BzFu2lgEY3GMWxSWsOCiG04EYc5OgBilBgc5NBOYIISEQnNIAHwAfGAJupsEoCD5jDgJiQqhhWHNIAAPHzqQ5bay2U7gs5abSPbBVDHEAhMWHbADEeFkYFWVXWfgmACUqgwIhEAEzLAAMwPSDlYmhixGeR0s%2BNOZwuVxu2DurDJ0rejTYAEk2OQEf8hJJuCKIESoTDlD55BhiCR%2BLIAK62IoAWghRQAPBCBEaRD5VrEHoG4mAANTo7G4yAqZJywkQi2wnxZEqwOLbEUAeizkII0EQYACQSogp8AEZBWAODhyAA2fBFFUuWywR24WBMnSFxAAR0dWlhABowDosmB8rASE4mNnc%2BQJbhZFqwCREBQ2IRjIbARg8IginuXGAGLa-LBaqQfBzAlOkPbsLAT2eL1eb3ASPf4XOwFOwLI-wBYQ9wPCd6F0YREHgJB4DAKMjkIACSD1S1bD4ZQwAAKgIPAMTjVI7GcVxQjoYgyk4WBUTAT1XX4LIFiWIoQRBMBxWiLREGlNQADJuJ3YDuB8DxyEILx4EdLAfAACUEciOEo2d4wgIjBLkyiwjtc4Lzwe9qNdU0wBQ6BdD4HEOBHFSSPCNTUTUfJwIMlixkgeDxhHQxHUQNR3U8bx-ECYIfGlIKXlIyJGnqe8kj0CFtRsjTwu0%2B9HP4ZZ3JITzvIhLwCF8YtAo8Q4hNC8ISC0yLSGilBYvisKyoinTSBS5YwB8ggJIwelEFRRAf3EASwJ0A4jnyUit3-ESqIwthvF-WwGIKIp8m0dcJzGkxBu0H8ygqNgAw6m9ZFIdcCwpAtoVhPRIQ4AArQJcDXI613zQtctwVhcEff5bEIAxyBe38mX%2B39bvunwf2XdMwCQRB1HwalGqLALOqUsAczOQ41sUDbZEmopptmjDcoIV0FsKTbtvKYg9qkDAMFWWBsDeNtFjO2HUKuyjEAAZj5Hx4Dpn9-lwPhRoXdRSEM-79Sg11H1dCgYUvNQcry5GQo4HxyISkgUHPPw1w47VqRVF6f0Kkb1u3XL8gm4IikIOCCAcZcg0nacR3oUdtEaQpzb8882HUYJSBKUh6gLJgte4CiMB1oTvBst4Q7Zi6MJQH9U45ztR24CWwAAclV-x02DrASDDkgI4PaPY-j1Wk5TjFztQguJ0Eb3fbhH9tS7Fa13%2BAf1CnFURjgsz8dsGbcvc7RYDRXHglHJ9RvCdzYBXhzUfR4vA7L0Pw7wSPa-kuO6oT3LG6wLPLoz7fcxvjCc%2BwPPCyLgPS5DivD%2BP2rSov2AV9ECPwIG3fIHcdBd3BqjSyCUbJelovRXIi0RSWT-ppBqukaIGQNogDi6DJZmUbGTIo09YAcmdDCDM%2BI6TrngIyEUABpG2BBGGuH4saAMQYRTmjTnCUqDpnRgBcLwHyaDDDKGMCGRAbDuAACEMCwCODRYRxEFFKLAESAAMlkbAPhHwMBIDEbg%2BEdio32P3Qs7gpANHulOQS7RsB%2BEdEY9c2AbFrmgI%2BEg3AkgikMCaVGEAPF2J8VrHAzjXFEBCV4%2BxfAog6DJDE7x3BpGmRJLGAy%2BxV7EH4OQK6-VjQyHkDhVCag4bOGOEEuwjo0Q0gIH8dwydJJQnXKZEczTEBiQeLgjiHSQ4MGgJHKON5yDwASqY%2BUEByBWWIHwepTgLJOFMVkhwa4mCUUvPadwQFOHCVEggCSDxCkiBvBsjAWyDJSQ3k4M5mzJbrPudYapOTCy7JEI4EkjgREihKZ8QJBE0jJPseEpxLjnruNsbEnxfBLGmMgEOcAUAPowhMEwVAYAADaSKICgHlJAAAJC-CWGLICEGwAinFdhCW1EoJ5DF2KplgEFIiplkBjZICICUPAAAvZArKpkABYqUQAALpUoAL4CtxSKqARLX6kvJZS-FBLaUYHpWgRlUzyzStOJAYSGIdHOy0euYwOhlXar5IKWV4q0hSqpXivV8qSVoEgPJSiFq0g0rpcgTVsqIB8l1V6sOm44CKIIAwckiwJiyCNfy-1E0eo2slbqx1XrnW%2BqgO6jAnrqWqp9QyhN3Mg3UpKJoAsci5BTk4uxOIdpc1pA8ogZNdrU2ysJcSzNbqN45pLd69VmatXykFSWiAkAy0-EQJWpCiAtEFFINAe4xtaiwEXahBtdgm0trsPatIaa82dtJdmjd-aNVYoTQAVlHVACdFaq1rgAKrqAliQRdrBl2rsHMoDdEBcZJvlLandbaVWHtdcevt%2BaB2FqZXWa947y1TvvYgPwGAATnhNhlaFP7E2sG3RAXddh91jozUentJ7INnqHacAA7HB29iGZ0eEgiQbDf7cMAZTQ69tJGwNkYg2qyjCaAAcdGEPTureecNrHKDsdOIB-DwGnWgazXx7jAnB0JoAJyicnQwWQdpA56mw1ujjrauMgYVbxj1-GC1%2BqZZWHTd6Z0hqPpRb9162PNtM0B8zSnLMqes2p2z577M6oTfB3T%2BmD6hrcwQYzGUvNyc43u7jynu2BZVep6Dlq4McrcRMAg6wfGvG0NJ-9SWzMpYsy6gLvagtQbs9q4t4X6OGJZvAGQe5Nz1uvSZirPmqt%2BZq2Sog5GsuNflOWEd4WDW93WCtAgKJWAlDniQbAOR4DmuvYK613mFO%2BfTWlpVNmGshe1Vemb5AMTG3kBiVpkopwUnUOsmk7nL27f6-twbh3-MjYpSdwT9nYOXYxO%2BO8G2tsJp23hsABGZXVa7cd%2BrgPtW0ZB4Y4xSIdEGAh6V7bH20jydh4pn7w2keZeC1RtI5YRMg4GAOuRuQty4%2Bw9DvbxODsHt%2B%2BTp142zuTe0yDt4zovGwkZ4sZnOlIdMrZ59jn32ufDfA8jjTTKrVwY8BJGEe5nbqN%2BHImIvwcBMAKyUIMknHRsDix5mTiXCfJcI6l37yuKenap3YPkYW2WrEQPkHXiHsD5EQOudYr9ikKFQgwRYTHOAJDK7J%2B3lXHcI9Ixl3nlOE18kDeFthsM5sLeNmbuIcb4927sETuHYAiNyqO6NgHqupl8ma2yg1KJNxMG0Cz-HMPK-V47c71TruUfyj5NNtl3KTBYEMcYS3bjqCIA4N00vPeSeK67S79PbvM8XbZaePAxgCDC-zKhblB%2BtAuMQOsWAeWiBfutwmzzK-OfEbSxv9NfP3cBuB7v20pBFZ4EvDnRMBjxrBIHD1KVhHRRt3K0TwG2TyG3X0H032H1OD5DR3H0MCPmwCX2gIT3L0lSRVFQFTJSYDeBpAxUfwlSAA).
