### ISSUE TITLE
Concatenation of multi-line `"""` strings mis-indented

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#639]
### Description

The `+` operator on line 21 is mis-aligned, resulting in
```
Error FS0001: The type 'string' does not support the operator '~+'
```

### Repro code

[Here](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=ATA2FMBdgBQJ3ABwIYIErmQEwLLmCgMYDWAlgHYDmAwgPaICecplAFtALwCwAUCCBGgJsAW3wdYySKwB0lKADEArqFAA5ZGOAAiNAFEAggBEcemSKzbe-MFGBZahJWPKdgC0hBkZsB1QBVwAA8hTCwxa35BYBFUYgcAd3JgCRw4xPIACgBKSIE7B0IACUgRUBSdbW0AHgB+ILLgADdwOABnUlpyDm0ARhkABm0QcHJCWiwKSh6lSAAzAFoADm1agD5eaoBCIwB5an8ATRg9YHYyjZ5q8-LQZCoe0e1L67CXyFJICDW-SDoWuDAfTGUzVAD0Hy+4BebUgDG+vAARhMGAAaM6lcoAb1441AtDgAC5gABiAbkgDcwERyBIlDgtCU5CwCzxBOJJPAXIpvDmXUgCzmmk8DGJAHIAMrgSi0fAAVQAkmL0WLdohRsAJfc2srgNRkKBSIjmOiAVh7sh0axwKAWh9CJbgKhSAb0W1tQs2q1SHMeTxELQOh8usTkIi2rRQLNwFTIPRiQNEEEqQlSFhpMSAKwDcAiCmxOCUCjE3q5qkoLCTKiEgZ+gC+vGQwCxbKJpIALJ3Y8EBVhwOM4FJOuRieQujHgHzXAsEuAWOxicjQFgKQ2eMhCaxaADm62Of3CKvNmDYfDocfrdgXsisAxLlVhjYn0+ANQxdK0JIyfyD8htPlwCI9iOM4ozQG+D6bHytCQK0azVIgwCnhAPSwSECwGiwI7AIQYGtM8D7AG+RBkFQdCMMwbDgZUNRgogLxgtBsFwAxN53hemL3lUeS2NADSgABQESAAGkYIEuJAMgwKgXrAcUmI8dEbEVPxgkyEY4BtLhzL3JAbSZMJGhiDIADidjaGx2i5HwUR2DapAiBQUjiMAADaOh0K4FBKIybTAAqrjSoOwbkNoVLaAAQkonhVpQYU6P4rD3MQflxsMAC6il2MQXKIRICBzMAkBwEo4C8Fl0BkKoKQ8SAbEyHoEASfp1nPgAPmsmrgAAjuYyCIZkcxMsAQTAAslzPk+sSQIQrAjTIRngDIAAyjgGotwCptItXtTorAAEzDONO2TSAOVICdp2EhImTLaQsIyMVDAeMywCDcN+DjcALkSsVUwyJ5DqQJkQQLRMmk5Nk2TfYajnkM5rWnUjHXAGqIUyPdajjpd-BtToTH4WNnXnYh11FSVZU2cjwAAPpE29iNIz6wBbCTRXWskWPkPgNqyRKtBaEEjO451Uq9XGd2wjxVWgDxKNixjzFvUNyTdUTOPTbNwBq1trA43j-OC-ToMYCI27gDk+u0-TkMVQQtLEGGEAVNJ0hyIoKjqJo+DaDIYI0xFTnMJpYLAiYZg3FYVMjWUalai09skE7lNAA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZECcADAL5A)

**Comment by nojaf** [comment]
I think this is no longer a problem.
We can add a regression test for [this](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEA2iAuYAKATogA4CGRASoqfALKJhnQDWAlgHYDmAwrMQJ4FWnABa4AvAB0Ck9hEw4wRGgFsG4-KWwiAdJxwAxAK4YMAOVJqwkyBQCiAQQAitOzpXwb02fLBZc8LDQRmrsEmAGrFg6VDQOpgAqiAAeuMrwat5y8v5gKuTMgQDuchq0BcXsABQAlFm%2BuYHQABLYKhhgGl6QNgA8APzJ7WAAbogEAM6ssOxSkACMOgAMNhCI7HDwHJxzRtgAZgC0ABw2-QB8Wb0AhE4A8twJAJp4dmBi7Zcy7L0fHRikLhzdY2L6yX7UeBgn7YVjYLDneLYXhjAhgezOVy9AD0sPhiGhvQm2H4CKyACMEPwADTvNodYBZOAYWAENAAYiWXIA3GByaQWJwCLAjOx4IdmayOYgZdysvsZthDvtLFF%2BGgAOQAZUQnFgDAAqgBJDW0jV3YjrMBawETU1gbikDCsclCWmo%2BCA0i0kSIDBjWHQb1gcisJ20ia2w4TcasfZy77EWBTWEzNCkckTWAYPaIXnYPhoJbEZK8oqseDaNAAViWiBU3PyBE4HDQ83rvLI8C2XBQSwTsgAvllSGBgJK2WB2QAWWf5lJKpBwAhaabsNDsGZ5sAKsKHIqIYRiNCUjDwbnD76kFAiWCoscT6XQaAXq7Y4mkglv300QmU%2BD8NC3SrL4oGgQA1HkFSwCUOgJCu7ATAqBAqGATQhOsuCQcBPTfL0CqwNg4znL0xBgB%2BWBzERqSHE6wjrmA0CYeMoI4WAkFMGwXC8AIQiiFh1g9EJOLEIS2IEURBBif%2BgHfvSQFCV43wNIoQwYMhqEaAAGk4QQYWEOh4OQMZoUErTtPUOSKDJnRgGpGk6E4iATExYqAtgExVFpFhqDoADiig2DJNh1MpVm4H6rAqBwWjqGAADagm8GEHBGCKExgEaYS6iuqbsDYvI2AAQkYUQ9pwBWCQkIiAswGUFqsAC6lkKLgzAymRGhEPsYDYAQRiIFkLV%2BIobCmJ0w0QDJOh2FgoQebUk1gAAPuc1qIAAju4pBkVU%2ByinZYCHNCYGgfk2DQCIdk6D5iA6AAMkETq3WA5baEtoHLYJIgAEyrMdH2nWA7UkIDp0oBoVT3awxI6H1-CRGKYB7QdDDHWAcVan12w6MlQbYFUyQ3Qgzm1DUNQY860XsLFoU%2BEDDOrWAFp5ToMNmFuYMQF9NgSSxkBHWtINkRDvX9YNYWM2AAD6gvI3T2QM3GYDXMLvW%2BnIHPsAwfomVqsBWMkCtgUzOpbQW0PEsNY0YMNpubWzknI-tcgbYLYPnZdYBu29Ihg19%2BuG3LRNUCod6IItksmzLctk8NuScRmWC2UZ2h6IYJjmJYDA2Do2LS0VMVCM52IYi4bh-Ep9MQPZrIqDoNpjIwArMEnEuyJA1LgFAMbYLCXATKgCXdxAoBgZAAAkJKWkPkAcNgncj-Ik8jE6A1D-FS%2B%2BEsXdA5AWVIGEWqsAAXsgu%2BndOW9gI1S%2BDhfo-X5P0-IGgc9hIv48T6vOav8PQPzAfqBSA5RkjQ21vddYnBtCf1OvMH6Sxr6318PfJeY9gFT34DPN%2BlJsywN8CvNef9N5Ax%2BkAghOpoqSnYA4bAdgxR3H2OA8%2B18IAqgwDGJBd8gHoIIZg7BUBcEYHwcvb%2BRCN6sLAAAZnIcvLUTBEBFUQMhRARkVxqEkiI3wfUBpcJQTwp%2B-C-6QCEVoqAYjf4SKBtOWREBIDyIFIo5RrJECPQPAQIMMYsojCenlMxEAdGID0fIVBvheGiJfrPUxsjCGWLQCQ061ZbFQAcUxJRKiDTEEtB40gXj2A%2BPxmufxO4nScLAsgkJBiv6RJwbAPBMSLHr3iZIgAbMk%2BxCj0kuO4ACCYExkrEn6tAAsBBinsLKaBCpEBQnyHCXYoxUS6nCIaT-Jp-9ToAHZ2mpKcSo%2BgKhyTjDGaUoJ5TuFoMMTUwRSyzGxLWQksCxxtmdOcUQXgLJ2DHI4acyZ5ywmXKwcY6JhjVnEMkQATmeY4hw%2BxJK8BUPkYpgTgnTKqRgq5JibkrPEc0gBO9JEdMcV0oglDWDUK%2BRM3wUywAzMftUwFiz6kgpxessC8xAEEp2TCySpLyXJORWc-RFz6UCMxUyr%2BoKrFwLIQSg%2BmE7jsHgvwAA6nCEQFKflUr%2BbMgForgUSpZQ80C8wZGcoUQ4YUop4BOSpnCI5-LxYoppWivhGL563MaWCgBNiCWgKNPsaq6xZoxi1LeAg2BVWVnVck6ciDBWVOFeihlb93XYriay41STfWkGSFlfYrBkgWnGFoVkdhkjECIH0opyTaxOtpWOXVxjU3MvTUa3w8w2nZuSFQZc8BI0wJjXG35Qr-kiqbR-NN9zJHzC2V2i1K5%2BB3AIJbCNFYB2SNjXWl1ETk1QGbQa1t06nldoAGpEMLmKbY-bo0bqHVqkdOqx2z33RgyVuK4GQq7cYDYeUL3lWvcUzd8bUWJtdbu9%2BC9J1etOgg9poDdLYACnQ8tlapgzAAzWu98hqX1rmeYjF%2BrX2GskT9Dle9aAmFhM6bWRUWQsCKiuFgOAJgKptGod5IRPnJPGZq7D2q6VJr1ViltU7SEyr3mYRARRqNOOwAedYCRAVOXzewOEa4HBin2YcyYGqt2gZ3UJ8VRHD2kNNXvAA0h1f1gb2BZTY64jgLCgY8b06OwT47IMieg2BH6PryM5tmtFCYIgMO3tc4%2B9zjLllealT5rNe9j5cCwBazg%2BkI2IHJLQEmungPOv0-MgjwmD2iZg52ve8R6LfuGWuY%2BnAabYCMEQBIsA5VhFXDMHLw6E1ubA4Z6LxXvOgR%2BrO8rGBJL1dYGMR6XAtPjGUxwNTMxB7cZOeFgTvWgVFeMyVnzx6EvY2GVlpAnX70hO7o1C%2Bc8JgGCmEPFzg4gA).
