### ISSUE TITLE
Conditional compilation of a declaration is lost

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#640]
### Description

A conditionally compiled modifier in a declaration is squeezed out of that condition, leaving the condition empty.

### Repro code

[Here](https://jindraivanek.gitlab.io/fantomas-ui/#?code=ATA2FMBcFgCgGICWAzYARAogIQKoHE55xQBncOES4RAO1FvIXBoBMUKrPLbJwAnGgENQwAJIkSAV3AB2AIwB1PoIAOK-sABuiEokglgAWwD2LSRFEtgACz0AFYz0vAAxsZq8AHpBuDWEPmBBFisAXg4QSD4ATwjKYKttXX0jU3NwZ1tIBycrNw9wbziAdz1rYE9gAFoAPjiQQ0FIF3LK0shreuAAH2AALgB+YABpcGiAOWNIADFjSVYMTxdwFUhEdy7eweBx81AAJXBkfmZlxeXV9ZpN-qGAQT4Ac0lDZkhd0FBzlbX3aprfP4NCYzBYrFkch5nPkvD5PDcAPr-YB8fiCHTgAAUAEo4EA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZECcADOShjAEIwAZgHsATjADCIgDYiIReGJwwAvkA)

**Comment by nojaf** [comment]
[Repro in fantomas-tool](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEA2iAuAdATrgHYDEAlgGZgAiAogEICqA4gcSYhgM6JtEQCwZIhmG9CpREXiU%2Bg%2BYOHZE%2BIgEMMYAJJcuAV0QB2AIwB1fGoAOllWABuZLmWxcwAWwR6sW%2BGAAWzgAKsEo%2BYHBEygAe2P5q0lj4YGrwvgC8cgLY%2BACemYIpvg5OLu6e3r4B2MGhvhHReBKCAO7OfmBRYAC0AHz5Am5q2NDtna3Yfv0QAD5gKAD8YADSiDkAcrDYAGKwetK0UdCIlthksERTYLMLYGteGABKiBQqUkcHRydnF03y14sAQXwAHM9G4pNg7hgMB9jqdzt0enEErYPPAvIgwlUapEwvVEDEOpdZgB9RFgfAqNSORAACgAlHxIAAacBQHjYU5EYFcVBgADabIgoAUkAAJNgcjY%2BZAlCyhQJxXYNAY%2BYKFBAAAysjVQLTSCEAZTIAC9kDqNQAWBUQAC6CoAvhbhTaoBKpcg0LLIvLRWLlRhVWh1RrjM75JAALJqKIAGTEsakwImvtDACZNa77YInQqRRH3dKvQAjWCwDCpwRKlWegWuiBp8NVw2INxkOAYc4A7C0aQAeQo8aI5vrYAoGh4Wcd4fzVcLtcgpfLlcV-pratHAGYm4rDZY1Ed6M9YJTAmoLODlPgV4JsgYpzmZ67xZKi1AlxWd9XA7WQwpLTuECQHuB6IEeFAnogsawM0KjQGoPD6nYsDwfCRA3lk%2BD3go2YCLmgizqur4Lh%2BGHfkGda6gArIBUAgYex6Uow1hwQhmJEMhqHfBhEDjtwiAPnhT5%2BsRMqkV%2Ba4-huuoAGy0cB%2B4MRBlIAMIYAhXAqecXB3tA2AnjxY4TgJOHTnmz7zmJZafhZAYUX%2B8iGPJ9FgYxiCRq2xYqIZfGTqZj7mSJHpWcuEl2b%2Bo4ABzOYprnKYgWmduhtG%2BSZ8i4RA%2BECIRQGWSW1lkZJ9mjgAnDFoEAhQV5aW4gyGXeaWCBlYBZS6QVvouBVheuwajsY2qjgpoHgZBLZth25w%2BcZgmZcJBaifloW2T1lGhmGg0uZVV5je25aTbRDUzS1c1zgt75dctUm9bqxiNoN%2BpIJEfZEAAKrkphtFN-FHa1YA5W6Z2dUtfrhdJobbhtsVArs0jUJwZBtle9VYY1AjNb9-0vsFXpyt1V2rQoxgAYN0ZRFoFAvX4Ui0Pxhp%2BCe2AffAKa0Zamb%2BUJgXzdjUC45dxU3TRJMxvqFBkFEfY2BY%2Bn4AcliUro3G0VR7PpWZBEWYDfMgytDmCMYcnC1ETxwPg8BMyzo5sz9J1ETz3rYIVoPXaGTlG0CFg5H2%2BDxjpFt%2BIZ1sc7NXOnfb2sFs7BPyMY0VGwAajW9DCDI3L%2B4HqtNer2Wa%2BHPp4wLoZlUbWx7Hp3zJ9IwjAunrOZ2j2dtdzHUR3OUd6wIGbyaT1CbMwOBywrTjnLXo4qzbod2x14n8xFupputupRl4pyiMO9CdtAADW9AWNvOBcM9hpqOCiVgslo6pRPGvtSRF06-jHcNndS9rIgzRr652CwVIL0enDYsiDOG%2BACaQHk3BeXwLyFK01g7HUnrlQGM8H6FwUGmCGS8VjHHJpTKQ%2Bpj7giHCOXUV84EY1zi3fOs8wZoOJkvUmNM2xcD8KPXUQc1YBRvs3O%2BwNI661HGmIWS9jTciwECUE4JIimEQMWSMCBiEalIRwzmXCw7T3vnwx%2BAjDZLwBKIYERBS5EHLucY0Bihh6EpC9WAD0IRDCVpfWByiQ6qKnjwmyKC54ajTG7XRGArzqFOHYKC5xgTgMgQA4QwDtJfT8s4%2BBrjEH22QZo1B8g0xx2Edkds2A5FIFiajO0jo2S2gtLKLgWwnB8ivg6IAA)

**Comment by nojaf** [comment]
Fix available in [v5.2.0-beta-001](https://www.nuget.org/packages/fantomas/5.2.0-beta-001)
