### ISSUE TITLE
Sunset setting `ReorderOpenDeclaration`

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#645]
### Description

The feature `ReorderOpenDeclaration` introduces a problem when two namespaces expose the same function.

For example

```fsharp
module TriviaTool.Client.App

open Elmish
open Elmish.React
open TriviaTool.Client
open Elmish.Debug
open Elmish.HMR

Program.mkProgram State.init State.update View.view
|> Program.withReactBatched "elmish-app"
|> Program.run
```

After formatting it becomes 
```fsharp
module TriviaTool.Client.App

open Elmish
open Elmish.Debug
open Elmish.HMR
open Elmish.React
open TriviaTool.Client

Program.mkProgram State.init State.update View.view
|> Program.withReactBatched "elmish-app"
|> Program.run
```

The problem here is that `Program.withReactBatched` was used from the `Elmish.HMR` namespace initially but after formatting, it uses `Elmish.React`.

Another problem with reordering is trivia, consider the following example:

```fsharp
module TriviaTool.Client.App

// Super nice comment
open B
open A
````

after formatting this becomes:
```fsharp
module TriviaTool.Client.App

// Super nice comment
open A
open B
````

The comment is still linked to the first open statement after sorting, however, if the comment says something meaningful about the other statement that is now shuffled.

On top of my head, I don't see any way to resolve the first problem.
It will most likely be possible to change to solve the trivia case.

I'm in favour of dropping the functionality all together as it can lead to code not compiling anymore and might not fully be the responsibility of a code formatter.

Thoughts and opinions @jindraivanek?

### Repro code

[Fantomas online](https://jindraivanek.gitlab.io/fantomas-ui/#?code=LYewJgrgNgpgBAFQE4EsBuKCGCQigOgGEoUYA7AF3wEEAHWgWAChmRby4BRKYFAZwAWrdmS49+A-ACUYmAMYVhHZOiw48REuUVM2Hbr0H4AIjABGEAOZLRBifgASAWSnNmABSQhLSTMHzAANae3r7AcADKFJgUMPgoZCgUkdGx+BC0YDHwAGqkAO74GDD5zAA+AHxwIT5++PlJAjLyFABCMXICMGBwAEQw4oIAtJj0veVVNWH4SBBkQA&config=N4Ig0gphAOByEHcA2BLAdhAggMwC4QCcQAuXAgVwgBoQAlCAewIBNCB5aCNAEQgGMkAQwKDcKBmhJlKAXyA) and [second case](https://jindraivanek.gitlab.io/fantomas-ui/#?code=LYewJgrgNgpgBAFQE4EsBuKCGCQigOgGEoUYA7AF3wEEAHWgWAChmB6VuAZQlpiTjIoAxvCEhgwchWYheZOACEZcuNSA&config=N4Ig0gphAOByEHcA2BLAdhAggMwC4QCcQAuXAgVwgBoQAlCAewIBNCB5aCNAEQgGMkAQwKDcKBmhJlKAXyA)

**Comment by jindraivanek** [comment]
- its true reorder `open` declarations can lead to compiler errors, or even to subtle bugs.
- I agree with removal of `ReorderOpenDeclaration`, because it can break code (and I think Fantomas shoudln't break code in any setting).

**Comment by nojaf** [comment]
Ok, I would approach this somewhat gradual:
- Output warnings in the code that we will remove the setting.
- Don't fix any new bugs regarding the setting (like #644).
- Only remove the actual code when development for the next major has begun.
