### ISSUE TITLE
Allow to configure spaces before and after colon

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/fantomas#651]
In addition to 
``` F#
type Planet = 
  { mutable X: float
    mutable Y: float
    mutable Z: float
    mutable VX: float
    mutable VY: float
    mutable VZ: float
    Mass: float }
```
``` F#
type Planet = 
  { mutable X : float
    mutable Y : float
    mutable Z : float
    mutable VX : float
    mutable VY : float
    mutable VZ : float
    Mass : float }
```
allow
```fsharp
type Planet = 
  { mutable X:float
    mutable Y:float
    mutable Z:float
    mutable VX:float
    mutable VY:float
    mutable VZ:float
    Mass: float }
```
```fsharp
type Planet = 
  { mutable X :float
    mutable Y :float
    mutable Z :float
    mutable VX :float
    mutable VY :float
    mutable VZ :float
    Mass : float }
```

**Comment by auduchinok** [comment]
Why do you want this style? Is it used in your code base and Fantomas constantly rewrites it?

**Comment by vilinski** [comment]
just my personal opinions: 

- I don't like variants 3 and 4 and would disable that in my code base :)
- Said that, on one side it is not harmful to have additional formatting options.
- On the other side - less is more. I would prefer more dictature from the community about what the code style should look like (GO community as an example). Currently fantomas is the only F# formatter and it sets the rules

**Comment by auduchinok** [comment]
I don't think wish add new styles like these without actual current usage in the actual code bases.

**Comment by xperiandri** [comment]
I use option 2

**Comment by smoothdeveloper** [comment]
It would actually be interesting to have settings that enable __allowing__ code styles rather than formatting all through a single comb "magical" perfect format.

If some code passes any of the __allowed__ styles, it doesn't get reformatted.

Such approach would make a formatting tool more useful outside of context of code 100% formatted no matter what codebases.

**Comment by nojaf** [comment]
> It would actually be interesting to have settings that enable allowing code styles rather than formatting all through a single comb "magical" perfect format.

This goes in against the intent of the project. As stated by the original creator:

> This project aims at formatting F# source files based on a given configuration.

See [Propose](https://github.com/fsprojects/fantomas#purpose)
You should get a uniform result after formatting based on configurations.

> If some code passes any of the allowed styles, it doesn't get reformatted.

Fantomas right now is an all or nothing process, all code is rewritten based on the parsed AST.
It would be an ugly mess to only rewrite certain nodes in the AST, I can see a lot of problems pop up just by piecing the fragments back together. Indentation might make the code invalid for example.

As for the original issue I don't really see the gain here right now. Nothing in the [F# style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#naming-conventions) backs this. That is never a good start of introduce new things 😉

I'll keep the issue open for now, maybe more people will express they want this.

**Comment by nojaf** [comment]
Closing due to lack of input of our supported style guides. Please review our Contribution Guidelines.
