### ISSUE TITLE
Formatting of long parameter lists

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#657]
[Online here](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=C4TwDgpgBAShCOBXCBnYAFAhgJxRbAPAOQDGwAHgDRRGYB8UAvFAJYB2w+bmANlAN4BYAFBQoJAPZsUiALYQAJgDEWEHgpQAuKAGUIwAgGEpM+ctXqAcpnl0RYsDjzbSFKAFoGcJKmAeGUACCKCBsJARwMjwGtNQAotjYEthQPCxodHaiUGBJABYsAEYsnAra6PlFJYreyGgA4vqcKWloIgC+UADuJXki9lBomMAsJFDysoX4rBxcvFCG2BDDEAAUktJyiipqGtSOuBAuZOT+sAh1fp5BIWERqIjRxJjxicmp6cCZAJRQ2rW+LCHQiuKg0ehMAZiITZMRiDambYWDRMcQmLbmXYoKFwg54VF4iA4hyVYqlVEAbQAujj2kA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZEAcADAL5A)

Input:

```f#
type RequestParser<'ctx, 'a> = internal {
  consumedFields: Set<ConsumedFieldName>
  parse: 'ctx -> Request ->  Async<Result<'a, Error list>>
  prohibited: ProhibitedRequestGetter list
} with

  static member internal Create(consumedFields, parse: 'ctx -> Request -> Async<Result<'a, Error list>>) : RequestParser<'ctx, 'a> =
    {
      consumedFields = consumedFields
      parse = parse
      prohibited = []
    }
```

Output:

```f#
type RequestParser<'ctx, 'a> =
  internal { consumedFields: Set<ConsumedFieldName>
             parse: 'ctx -> Request -> Async<Result<'a, Error list>>
             prohibited: ProhibitedRequestGetter list }

  static member internal Create(consumedFields,
                                parse: 'ctx -> Request -> Async<Result<'a, Error list>>): RequestParser<'ctx, 'a> =
    { consumedFields = consumedFields
      parse = parse
      prohibited = [] }

```

I strongly dislike code that is indented far to the right to "match up", for the following reasons

* Important code moved far to the right
* There is little space left for the actual code
* There is an unseemly gap

I usually format it like this:

```f#
  static member internal Create
      ( consumedFields
      ,  parse: 'ctx -> Request -> Async<Result<'a, Error list>>)
      : RequestParser<'ctx, 'a> =
    {
      consumedFields = consumedFields
      parse = parse
      prohibited = []
    }
```

* Every parameter on its own line
* Commas after each parameter (could also be placed first as suggested in #232 - looks weird to me, but could probably get used to it if necessary)
* The last line has the colon and return type

**Comment by cmeeren** [comment]
For the record, https://github.com/dotnet/docs/pull/21690 was just merged, so now this issue has style guide backing.

**Comment by nojaf** [comment]
@cmeeren for my understanding of the guide, would the expected outcome be
```fsharp
type RequestParser<'ctx, 'a> =
    internal
        { consumedFields: Set<ConsumedFieldName>
          parse: 'ctx -> Request -> Async<Result<'a, Error list>>
          prohibited: ProhibitedRequestGetter list }

        static member internal Create
            (
                consumedFields, parse: 'ctx -> Request -> Async<Result<'a, Error list>>
            ) : RequestParser<'ctx, 'a> =
            { consumedFields = consumedFields
              parse = parse
              prohibited = [] }

```
?

**Comment by cmeeren** [comment]
The style guide doesn't say this explicitly, but as I interpret it, members should be indented relative to the type declaration, not the constructor/fields (which creates one extra level of indentation without any benefit and breaks consistency with how class members are indented). So this is my interpretation:

```f#
type RequestParser<'ctx, 'a> =
    internal
        { consumedFields: Set<ConsumedFieldName>
          parse: 'ctx -> Request -> Async<Result<'a, Error list>>
          prohibited: ProhibitedRequestGetter list }

    static member internal Create
        (
            consumedFields, parse: 'ctx -> Request -> Async<Result<'a, Error list>>
        ) : RequestParser<'ctx, 'a> =
        { consumedFields = consumedFields
          parse = parse
          prohibited = [] }
```

However, I see that:
* The style guide examples indents parameters only 2 spaces from the opening parenthesis, without saying so explicitly
* This kind of indentation looks weird with only one parameter

I will seek clarification for these points back on the dotnet/docs repo.

**Comment by nojaf** [comment]
> I will seek clarification for these points

Thank you @cmeeren!

**Comment by cmeeren** [comment]
@nojaf I think the question is resolved in dotnet/docs#21690. AFAIU the snippet I posted above should be correct.

**Comment by nojaf** [comment]
Well, I'd like Phillip to confirm here ;), so I'll wait until things are official ;)

Also, should it not be:

```fsharp
type RequestParser<'ctx, 'a> =
    internal
        { consumedFields: Set<ConsumedFieldName>
          parse: 'ctx -> Request -> Async<Result<'a, Error list>>
          prohibited: ProhibitedRequestGetter list }

    static member internal Create
        (
            consumedFields, 
            parse: 'ctx -> Request -> Async<Result<'a, Error list>>
        ) : RequestParser<'ctx, 'a> =
        { consumedFields = consumedFields
          parse = parse
          prohibited = [] }
```

I created https://github.com/fsprojects/fantomas/issues/1300 for the static member indentation issue.
But the tuple should be split over two lines. `consumedFields` is just not named.

**Comment by cmeeren** [comment]
> Also, should it not be:

Yes of course, my bad. I didn't see there were two parameters.

**Comment by cartermp** [comment]
@nojaf that looks reasonable to me.
