### ISSUE TITLE
Indenting of record definition when internal

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#658]
[Online here](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=C4TwDgpgBAShCOBXCBnYAFAhgJxRbAPAOQDGwAHgDRRGYB8UAvFAJYB2w+bmANlAN4BYAFBQoJAPZsUiALYQAJgDEWEHgpQAuKAGUIwAgGEpM+ctXqAcpnl0RYsDjzbSFKAFoGcJKmAeGUACCKCBsJARwMjwGtNQAotjYEthQPCxodHaiUGBJABYsAEYsnAra6PlFJYreyGgA4vqcKWloIgC+QA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZEAcADAL5A)

Input:

```f#
type RequestParser<'ctx, 'a> = internal {
  consumedFields: Set<ConsumedFieldName>
  parse: 'ctx -> Request ->  Async<Result<'a, Error list>>
  prohibited: ProhibitedRequestGetter list
}
```

Output:

```f#
type RequestParser<'ctx, 'a> =
  internal { consumedFields: Set<ConsumedFieldName>
             parse: 'ctx -> Request -> Async<Result<'a, Error list>>
             prohibited: ProhibitedRequestGetter list }
```

As mentioned in #657 I strongly dislike code that is indented to "match up".

I usually format records like at the top (input) because it's the easiest format to extend (press enter from end of last line to add new field, don't have to worry about placing cursor inside the brackets and spacing them correctly at the next line). But another alternative to the current Fantomas behaviour that does not indent the whole definition due to `internal` is this:

```f#
type RequestParser<'ctx, 'a> =
  internal
    { consumedFields: Set<ConsumedFieldName>
      parse: 'ctx -> Request ->  Async<Result<'a, Error list>>
      prohibited: ProhibitedRequestGetter list }
```

**Comment by cmeeren** [comment]
Note that this goes for the `return` keyword, too:

[fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzMAFAJRgC8AOgE7kB2EAhgM4CeN0YwVtEEmOAHmTAAmLnR6VsAV0p1GsALaIwlelgAWiSmHSwaAczAAfAHxhGWKbnwa1xs1MaJGYAA4BLDwftgssAORgSAp6FqpYyqa%2BmmDujIxSiGIQAL6QADTgUE5YWO4GjKhgANpZEKA8PJAAJFjMrshokPlYGWVV1QBu9OiJRaWVlQAMmYNVAJI0SDRYAMruAF7Io2NgACztEAC67Skr5ZtQtfWNUC1tYzXdvacDqwCM%2B4OQALL0-AAy%2BYgfiAYaFwewiGhx2lT27Qqz2ODSKkAARrBYOhAZUrj0%2Bmg7mNhE80bNEAp3HBdDQAIJYACiUwA8rgvjRlocILgek5QbsnlC0TDTgikSi8UdrpiSsywABmIUQSCzVz0aCIABCiFwsEkAAV6KolBFKKjBlhKIkOeCuYcanVYU1EciDTKuhjbuK1tKoHKFcrVeqfrAAO5aaBMRCTTqwIN5PT2nhGk1jME8CGVbkdK1822Ci2Om79cUAVjdsvlipVaskAFVXA1KEGnKHw2p3FG3az0Oz45zIVm03CM9H0TmseKAGyFj0l72SADC6CYjCnoVj0D8%2BpbbMQpsT5suvN7Av72dF2MGAHYx8WvWXEC9CfCtNGWevN6lt9Cezb90KB0fxQAOc%2BeqWPoLqSD54E%2BHZml2O7vlAfZfoezqrGAACcAGKmSuB6guCgKPQYGxhukFbtBb4nHudoISKSEPCM4pFoBk6IASRIks24qtu2gwJi%2BpE8rB-KUVm1G5sh9yPPR46IJheoscSyLschhHPmASY8CmDoCfBwlOqJQKFpM0xYDSNAACqUMwADq7gAmubZEdxnbJt25EfkJO4iUOYlSpJF5kpQsBSFMAAiiDoO4RJ6gRxoOZUPGqa%2B-GuWcMwHp5Ypia69FvPw4y4KZmg0JS9mzOo6pYNZ8C2S6ILEbxzkwclzSpVRuleQ8BbZe8ky4O4-A0tWajqpS-CuJI8RNjQYF5rVjlQQ1ZHWilrStYOGUPKOXX8AASogcCUPAlXVchayzXFTnqS5S3NStOlrcelT3GeW3%2BaozA0pQXwWEd6hgadKlqQcjXXecq0-mJ-5bQAak6Sr5PA%2BT6D9f1nTw8WAxwV18qDd3gw8aFbQAYkFy6TXDUyI8jbr-XVCV8amTXaR5bXrTidHIa8UjoHk4WMkqujQAA1kqqhC9gjAmbM9BKCBUgKFNdlced82XcD6afrjNE4hJHMAHKIH6vNelgAZ-KZJyhb1NA2ZNZJTDeCh3pQhSK7FaMXUDi3q%2B50LpQ9PDCLi9EANKIIgrh5QVfyTFLSgMkyyGcW72we5jatwjjzP3eKwg%2BRzOXFUSjDqFTNUA4lDPXUzvss-7EDCFlHPzAYmD%2Bfoct-BViDwi8CAJ6sSfl-TmmMxrWd4zinUc2S4X6DQxNsJGNDzHPagyIgpmwIZneNopA8QXNJELUlVdjzX2fIcIm3T9zWg0I2nS%2BgYDtO5b%2BQ26EYGD7TGMaUcWlnx5H7HOz0m5GmJFgXuSAv4H2VomLIWwVjNEYITRg7giiDxSEAA)


#### Code

```fsharp
let f () =
  async {
    let x = 2
    return some rather long |> stuff that |> uses piping |> to' demonstrate |> the issue
  }
```
            

#### Result

```fsharp
let f () =
    async {
        let x = 2

        return some rather long
               |> stuff that
               |> uses piping
               |> to' demonstrate
               |> the issue
    }

```

#### Better (IMHO)

```fsharp
let f () =
    async {
        let x = 2

        return
          some rather long
          |> stuff that
          |> uses piping
          |> to' demonstrate
          |> the issue
    }

```

**Comment by nojaf** [comment]
@cmeeren could you create a separate issue of that one?
In AST terms, they are different constructs.

**Comment by cmeeren** [comment]
Created #1062
