### ISSUE TITLE
Do not remove property setters

### ISSUE THREAD

**Issue by aspnetde** [fsprojects/fantomas#664]
When formatting

```fs
type IPlatformViewFactory =
    interface end

type public PlatformViewFactory =
    [<DefaultValue>]
    static val mutable private instance : IPlatformViewFactory

    static member Instance
        with set (value) = PlatformViewFactory.instance <- value
        and get() = PlatformViewFactory.instance
```

... this will result in 

```fs
type IPlatformViewFactory =
    interface
    end

type public PlatformViewFactory =
    [<DefaultValue>]
    static val mutable private instance: IPlatformViewFactory

    static member Instance
        with set (value) = PlatformViewFactory.instance <- value
    static member Instance = PlatformViewFactory.instance
```

([Repro](https://jindraivanek.gitlab.io/fantomas-ui/#?code=C4TwDgpgBAkgCgGwIbAGYHsBOBbAagSwgHcAxJAY2CxCgF4BYAKChanwDtgJNULoJ2AEyZNQkKGACuAIwT5yURCgw4CxMpWp0mrKAG0APABEIvSQmC4kCSRAB8AXR2sAzsBTyoAN2tRsk91loMEx8Hy42djckdnJoAC5YJTQsPEJSCipMEBFmV3dgT2wIbGluWCj3WIhnXRYifGAACygXCGAoAAofGwgASjpFZBTVdI0skAA6DmjqqAMAWm9rW1q6mMEoAHN2zoHaIeVUtQzNbOnKmLimIA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwC+QA))

Is there a reason why the getter of `Instance` is being replaced?

**Comment by nojaf** [comment]
At first glance, I would say that this is a bug.
I would expect that same behaviour as in this[ test](https://github.com/fsprojects/fantomas/blob/3d8916213723bce9443d71278fd5b3f0fc0d8125/src/Fantomas.Tests/ClassTests.fs#L310).
Should debug this to see what is going on...

**Comment by auduchinok** [comment]
FCS reports properties with multiple accessors as separate type members. This is something we've had to workaround too.

Look at how they're processed:
https://github.com/dotnet/fsharp/blob/e43e7d74b05160d97db35c7aa4dcddd052bce457/src/fsharp/pars.fsy#L1648
and where multiple accessors are reported:
https://github.com/dotnet/fsharp/blob/e43e7d74b05160d97db35c7aa4dcddd052bce457/src/fsharp/pars.fsy#L1615

These property members have wrong ranges and it's something that can be checked to recognize them, like we're doing here:
https://github.com/JetBrains/fsharp-support/blob/6de2627fc1dc58ad235fcd79ef79758d0b53ecfa/ReSharper.FSharp/src/FSharp.Psi.Features/src/Parsing/FSharpImplTreeBuilder.fs#L300-L303

**Comment by knocte** [comment]
I've found getters being removed as well.
