### ISSUE TITLE
Unwanted new line added 

### ISSUE THREAD

**Issue by JonCanning** [fsprojects/fantomas#667]
Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?code=C4TwDgpgBAKhDOwAUBKKBeAUJqUA2EwUAZgIwY676FQAeGUpluq2uBRxATBVdUfXSNmUVn0ocSAZgaogA)

Please describe here fantomas problem you encountered

#### Code

```fsharp
type Test() =

  let f1 =
    let x = 1
    ()

  let f2 =
    let x = 1
    ()
    
  let f3 = ()
```
            

#### Result

```fsharp
type Test() =

    let f1 =
        let x = 1
        ()


    let f2 =
        let x = 1
        ()

    let f3 = ()

```
            
#### Options

Fantomas 3.1.0

| Name | Value |
| ---- | ----- |
| `IndentOnTryWith` | `false` |
| `IndentSpaceNum` | `4` |
| `KeepNewlineAfter` | `false` |
| `MaxIfThenElseShortWidth` | `40` |
| `PageWidth` | `120` |
| `ReorderOpenDeclaration` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `SpaceAroundDelimiter` | `true` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Already fixed on the master branch, see https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=C4TwDgpgBAKhDOwAUBKKBeAUJqUA2EwUAZgIwY676FQAeGUpluq2uBRxATBVdUfXSNmUVn0ocSAZgaogA.

![image](https://user-images.githubusercontent.com/2621499/73655419-5266f180-468e-11ea-9b6d-1cdb4f0e5710.png)
