### ISSUE TITLE
Problem with --config and directory names containing "."

### ISSUE THREAD

**Issue by tcallan** [fsprojects/fantomas#694]
```
$ fantomas --version                            
Fantomas v3.2.0
```

Given a project structure like the following:
```
$ tree
.
├── Code.Dir
│   └── Program.fs
└── fantomas-config.json
```

This works correctly and applies settings from fantomas-config.json:
```bash
$ fantomas --config Code.Dir/ Code.Dir/Program.fs
Code.Dir/Program.fs has been written.
```

This reports an error and ignores fantomas-config.json:
```
$ fantomas --config Code.Dir Code.Dir/Program.fs 
Couldn't process one or more Fantomas configuration files, falling back to the default configuration
System.Exception: No configuration files were found for Code.Dir
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1637.Invoke(String message) in E:\A\_work\130\s\src\fsharp\FSharp.Core\printf.fs:line 1637
   at Fantomas.CodeFormatterImpl.readConfiguration(String fileOrFolder) in C:\Users\nojaf\Projects\fantomas\src\Fantomas\CodeFormatterImpl.fs:line 679
Code.Dir/Program.fs has been written.
```

Note the lack of a trailing `/` on `Code.Dir` in the second example. I've reproduced this behavior on both Linux and Windows 10.

I believe the problem is the following line:
https://github.com/fsprojects/fantomas/blob/3d2e39eb838a83cc9ce3127d48e2cd65405ab656/src/Fantomas/ConfigFile.fs#L26

```
Microsoft (R) F# Interactive version 10.7.0.0 for F# 4.7
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> open System.IO;;
> Path.GetExtension("Code.Dir/");;
val it : string = ""

> Path.GetExtension("Code.Dir");;
val it : string = ".Dir"
```

**Comment by nojaf** [comment]
Hey @tcallan, thanks for reporting this problem.
I know this is probably not the answer your looking for but would you be up for it to fix this yourself in a PR 😅?
There are not that many active contributors and you don't really need a lot of knowledge of the internals of Fantomas to solve this.

If you want to tackle this, you can start by writing a failing test in [FormatConfigJsonConfigurationFileTests.fs](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas.Tests/FormatConfigJsonConfigurationFileTests.fs) and indeed apply a fix in ConfigFile.fs.
