### ISSUE TITLE
Multi-line arguments to chained method calls produce invalid code

### ISSUE THREAD

**Issue by evenbrenden** [fsprojects/fantomas#702]
Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=AQ4GwUwF2BlALA9gdwQQwE4BMDOBhRAW0LQDstgBeYAWAChRHgDiysARCAMwEtSeoPRKQBCAVx5gsEDAAoAlPSbLgAOgDqA+ADk0hCLIBEOJMkOKGKxhq2ccAYww8ADoOFGEKHMBOZcwPmA0YHswMRwoGXMlK1AbKHgAQQwAczF9UihZLjFSYAAjCSkZYABaAD5aS1imQslpDBiaq3idPQNDDAgUoVJo6ublVrtHFzdSI119YEQuYASIH3g-YC6e4WAuDCJgZHgee3glv28TRDEpAsWz5D6LQZaASRwAWTY0KEQMAE9ZKAwxBB7g8hpoErBkAJDkZShh+iDQVoIVD4DCAErmKoIpgAH0qPBSpC+QKasVU4nqCnoQA)

#### Input code

```fsharp
    let ShowShardsCommand = 
        CommandDefinitionBuilder()
            .WithName("show")
            .WithDescription("Shows shards in a cluster")
            .WithArgument(fun builder -> 
                builder
                    .WithName("region")
                    .WithDescription("Name of the shard region from which shards should be shown")
                    .IsMandatory(true)
                    .WithSwitch("-r")
                    .WithSwitch("-R") 
                    |> ignore)
            .Build()
```
            
#### Output code

```fsharp
let ShowShardsCommand =
    CommandDefinitionBuilder().WithName("show").WithDescription("Shows shards in a cluster")
        .WithArgument
            (fun builder ->
                builder.WithName("region").WithDescription("Name of the shard region from which shards should be shown")
                       .IsMandatory(true).WithSwitch("-r").WithSwitch("-R") |> ignore).Build()
```

#### Suggested output code

```fsharp
    let ShowShardsCommand =
        CommandDefinitionBuilder().WithName("show").WithDescription("Shows shards in a cluster")
            .WithArgument(
                fun builder ->
                    builder.WithName("region").WithDescription("Name of the shard region from which shards should be shown")
                           .IsMandatory(true).WithSwitch("-r").WithSwitch("-R") |> ignore).Build()
```

#### Compiler error

```
Successive arguments should be separated by spaces or tupled, and arguments involving function or method applications should be parenthesized F# Compiler(597)
```

#### Fantomas output

```
The following exception occurs while formatting stdin: Fantomas.FormatConfig+FormatException: Formatted content is not valid F# code
   at Fantomas.FakeHelpers.formatContentAsync@53-3.Invoke(Boolean _arg2) in /home/evenbrenden/src/fantomas/src/Fantomas/FakeHelpers.fs:line 55
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 417
   at Fantomas.CodeFormatterImpl.isValidFSharpCode@377-6.Invoke(AsyncActivation`1 ctxt) in /home/evenbrenden/src/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 377
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 350
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 882
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 890
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 1154
   at Program.processSourceString(Boolean isFsiFile, String s, FSharpChoice`2 tw, FormatConfig config) in /home/evenbrenden/src/fantomas/src/Fantomas.CoreGlobalTool/Program.fs:line 104
   at Program.stringToFile@307.Invoke(String s, String outFile, FormatConfig config) in /home/evenbrenden/src/fantomas/src/Fantomas.CoreGlobalTool/Program.fs:line 313
```

I'm not able to tell this apart from https://github.com/fsprojects/fantomas/issues/498, so maybe a regression? Reproducible on 3.3.0-beta-002 and current master (cf09a21062).

#### Options

Fantomas Next - 3.3.0-2/27/2020

| Name | Value |
| ---- | ----- |
| `IndentOnTryWith` | `false` |
| `IndentSpaceNum` | `4` |
| `KeepNewlineAfter` | `false` |
| `MaxIfThenElseShortWidth` | `40` |
| `PageWidth` | `120` |
| `ReorderOpenDeclaration` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `SpaceAroundDelimiter` | `true` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `false` |
| `SpaceBeforeSemicolon` | `false` |
| `StrictMode` | `false` |

**Comment by quintusm** [comment]
Personally I think the formatting of chained method code is really ugly at the moment.  I would prefer if it could produce code looking more like the input code which is easily understandable and less like the suggested output code which seems to me to be hard to read.

**Comment by evenbrenden** [comment]
> Personally I think the formatting of chained method code is really ugly at the moment. I would prefer if it could produce code looking more like the input code which is easily understandable and less like the suggested output code which seems to me to be hard to read.

I agree, stacking all the method calls on a single column looks tidier to me too. The suggested output code is the smallest change needed to make this compile (that is, getting the opening parenthesis before the lambda on the right line) compared to the current output.

**Comment by nojaf** [comment]
I think this is no longer an issue on the [master branch](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEIBtEBcwGUALWAdyIEMAneAZwGFYBbR8gO3jAF4wAdSn1hiFgGzNvAAiiAGYBLVrJyzYrAEIBXWZiSUAFAEo%2BA4SbAA6AOqLCAOXKNEunpBrESzw-0Gmhl61JpoSlkAByUVJ0giUhowVypaMHkwcjBoTHUaHER%2BSE9jHww-HEIAQUoAc3UHVhxdaXVBACNNbRywAFoAPl4vQtMWrR0jb36fYtt7R2dKRArlVg8RscKJgKDQ8NZIuwcwWGkwEsQ4wgSwWfmVMGlKJjASQlloQlOE2NdYdW0wJpPPkiLPLLFamMwASRoAFlxOQcLBKABPXQ4SjqRD5Uag3xWEr4EiKF6RDq5THYkwTfGEwjEgBKHl6BXJGAAPj1ZBVWAiMSD%2BmYNEMDJAADTgKA0XBKVgVGioMAAbTFEFAJkgABIcIiQsg0JB5DgRUqMOqAG7kDI6hVGoQABlFPkg4PYiFq%2BFkAC9kPbTAAWa1gAC6RoAvt7lf71ZrtXK9bVDaq1WaLXLFT4AIxh4SQGEADwAMvJEHmXRUSvHTGmAEw2-1BoSho0qrMarWWyBNWCwTDloSm83olP%2BiCVzO9-CIRjPLsqUo4ACi7AA8tIC6wvUObuaJbWQ5mm72W9HdR2uz3jYn%2B5bU6YAMyj434ELkaCIVQybkABSoU2ylDPQlRdEd3rPcI0PNsT27e8%2B2TNBrxMH17wgKInxfN9pG5PNSByaByAlJ0TVgXCtn-DBAMQYCMAbIR93PKMIM7KCwKTAc4I3ABWJCoEfZ9X3fWYAFUQm1ShcPw1hCOIhZSIgaQtwokw6yo0CE3omNINImDWKtHwADYuJQ3j0O5OhMDw%2BgVCyNFoHhP8uLkzBt0U3dGzAtTj0YzSL1gnTTAAdgMni0P4xAoQnP47I3BynOEJSIGojBaOQ8D1M86DvO0%2BDhAADkC1C%2BIw2YGEwFQZM3RyFNilyaLc1tUtPdKWKvDcAE48t40ppF-UQWDK8jKPilTm3cqANMay9B3TO0N0M4LCsQcdJzgErWDK6LKqEOKwAS8NVLqjyGuYia2PTDMZqCxBOt-RapxWvq0Q2jAtp2sAkqgFKDqYhMmsmisRxmp0kFqRdWAAFSRXFCDW%2BSBu2oaDxG9s0qOnysqENM73O-Lyi%2BdgpEwWRJ1-e6gOckDXL2o8oH1LyfpOitEJm3NwWkUHCBdOcKuiSgcCseAyy4n0azJ5SKeG-bqbjcbUY3NNOKZ8gcydOQc0XES4QROccxCWYaBoaSuPY4WqvJmrKbbGnpcy2X9IVnNaUQOBqD5gWNyF2GXreyMJdjA0rea9MArt8pKHIRFF0oAsshdqHBeNzbqsS2qqd92njt8kw01yu2ADVL1UeR4HkCoY7K92RcGsWEZ9y2Uet9M2rtgAxRobIWAv2GL0u449%2BG6J9sa64D0xqwMqFviUAm11UEroAAa1UUP59wGgQfwKZiuqVb7Jhiu4ar-uU8H7707RjBKzOh0bEQEgp74nASEQF1QdbKQ5AULZSnYMLGAi2Ud4qr3A%2ByVEbH2bHTDOwhKz-QdAAaSfiEFmbMXROnXg4Vc64fDrSAWbcWKda4nxlj4SsmMHS5k5pOVw3c3bxyeonXaeCGKHUIfXEejMHRumlNgcoVQai80QE0KECBMGmGwXvT2ycmFfXAafDclZ5YOlKATTkLdWBtxUG6TkcJ1CzFBrAQGLocBwgNlFXeJtRa4OrkfZGLDh4mErLbRRmBfysGMSaIsKgKg-wim-eQigFj-1MYA8RfcQEDxsTIohI8g4cNRM8HAQikDQ2CeY%2BKYoAzej1DQJu%2Bs5TYODEAA).
As for the style change, you can track https://github.com/fsprojects/fantomas/issues/501
