### ISSUE TITLE
Feature request: normalize generics usage

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#712]
I just wanted to leave this here: https://twitter.com/7sharp9_exhumed/status/1235357140488982532 :)

**Comment by jindraivanek** [comment]
I agree that we should be opinionated towards recommended style, including this.

Its interesting that style of generics is actually present in AST https://jindraivanek.gitlab.io/ast-viewer/#?code=C4TwDgpgBA5AhlACgJwgMwJYA8oF5YIDKEwAsAFCiRID2AzsJlgDzwB8eUxwrcbQA&defines=Q&filename=MoYwTglgDgLgdAMwM4A8g

Which is quite weird, because typically pure stylistics choices are not present in AST..

Fantomas right now just respect AST (that means it uses original source style).

**Comment by nojaf** [comment]
Agreed, https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#use-prefix-syntax-for-generics-foot-in-preference-to-postfix-syntax-t-foo

**Comment by knocte** [comment]
My team at my company has worked on an implementation for this feature. We have it mostly working with almost all tests passing. And I say "almost" because we have found an edge case: unit of measure.

Take this example (from a unit test in fantomas actually):

```
[<Measure>]
type m

[<Measure>]
type kg

[<Measure>]
type s

[<Measure>]
type N = kg m / s^2
```

And the formatting result after using our patch is (showing only last line):

```
type N = m<kg> / s^2
```

I guess you understand now what the problem is. As far as I understand, fantomas is not type-aware (and it shouldn't be). So is this problem really solvable with fantomas or would it need to be implemented by a tool that can know if the type being used has a `[<Measure>]` attribute?

**Comment by nojaf** [comment]
You are correct that Fantomas has no idea what `kg m / s^2` means and is indeed not type-aware.
So this indeed may be something that is a better fit for a refactoring action inside an IDE.
There, with more information, the correct behaviour could be more achievable.

**Comment by knocte** [comment]
Thanks for your point of view @nojaf. Do you think a rule in FSharpLint would be a good fit? Is FSharpLint more type-aware?

**Comment by nojaf** [comment]
I'm not entirely sure that FSharpLint uses a Typed tree.
Perhaps this is more something you'd like to implement inside of editor tooling (Ionide, Visual Studio, Rider, depending on what you are using). I don't know for sure, so you might wanna open some issues on those repositories to get a better answer.

**Comment by knocte** [comment]
Fair enough. So I guess we can close this one now (sadly). Cheers.

**Comment by knocte** [comment]
I forgot to say that actually FSharpLint has had a rule for this for quite a while: https://fsprojects.github.io/FSharpLint/how-tos/rules/FL0011.html
