### ISSUE TITLE
Example of using Fantomas, Fantomas Configuration file and FAKE together?

### ISSUE THREAD

**Issue by zakaluka** [fsprojects/fantomas#727]
Hello,

Is there an example of how to use an external configuration file with FAKE?  I thought that the JsonConfig module would have been the correct one, but that is marked as `internal`.  Any advice on how to do this?

Thank you,
zakaluka.

**Comment by nojaf** [comment]
Hello, you can check out https://github.com/nojaf/trivia-tool/blob/master/build.fsx#L24.
Maybe we should update our FAKE sample with this tidbit as well.

**Comment by zakaluka** [comment]
Perfect, thank you!  My personal recommendation is to add that example to the FAKE sample.  Please let me know if you would like me to keep this ticket open to track that change.

**Comment by nojaf** [comment]
Yes, please leave this open and we can pick this up.

**Comment by zakaluka** [comment]
Here's what I ended up using:

```fsharp
    let fantomasConfig =
        match CodeFormatter.ReadConfiguration(Shell.pwd()) with
        | Success c -> c
        | _ ->
            printfn "Cannot parse fantomas-config.json, using default"
            FormatConfig.Default
```
