### ISSUE TITLE
Broken links in Readme.md

### ISSUE THREAD

**Issue by milbrandt** [fsprojects/fantomas#791]
Seems like Readme or at least the section [Upgrading FSharp.Compiler.Service](https://github.com/fsprojects/fantomas#upgrading-fsharpcompilerservice) is not maintained for some time.

- _Update AST Viewer_ link leads to 404 https://github.com/fsprojects/fantomas/blob/master/.%5Csrc%5CFantomas%5CAstTransformer.fs
- _Update F# Tokens_ leads to an archived , now read-only repo

Didn't check the remaining links.

**Comment by nojaf** [comment]
Hello,

*F# tokens* was literally deprecated yesterday
![image](https://user-images.githubusercontent.com/2621499/80276039-f7b9c080-86e5-11ea-9222-3704b5e2a364.png)

The main gist is that the tools listed in the `Upgrading FSharp.Compiler.Service` are now combined into one tool: https://github.com/fsprojects/fantomas-tools

I'll update the readme.

**Comment by milbrandt** [comment]
Thanks @nojaf 
On F# tokens repo I saw only the top banner of Githup and didn't checked when it was deprecated. Obviously I had bad luck with the moment in time. I came from your issue at FSharpLint and didn't digest that deep.

**Comment by nojaf** [comment]
No worries @milbrandt, anything I can do to help you with the investigation of the FSharpLint?

**Comment by milbrandt** [comment]
Sorry no, I'm not further investigating - but I know the issue there for multitargetting projects. But someone now added that he has the issue also for a single-project case.
As I suspect it's an issue in `dotnet-proj-info`or the usage thereof I opened there an issue.
Actually, I'm only using FSharpLint in another project.
