### ISSUE TITLE
Is it by design that "--preserveEOL --intend 2" doesn't change intend from 4 to 2, but "--intend 2" does?

### ISSUE THREAD

**Issue by mattiasw2** [fsprojects/fantomas#793]
I prefer to decide myself where I want my line breaks. However, I have code with mixed intend and wanted to use fantomas to standardize.

Only running with "--indent 2" makes the necessary changes but also combines my separate rows in an unwanted way. But when I combine it with "--preserveEOL --intend 2" the old indentation is kept.

Is this by design?

**Comment by nojaf** [comment]
Hello @mattiasw2, `--preserveEOL` was removed in version 3.0 so it is gone for quite some time now.

What version are you on?
Could you try `fantomas --version`, if that doesn't exist try `fantomas --help` and check what options you have.

**Comment by mattiasw2** [comment]
Fantomas 2.9.2.0.

Ok, then it is by design :-)
