### ISSUE TITLE
Return attribute deleted on reformatting

### ISSUE THREAD

**Issue by sadgit** [fsprojects/fantomas#800]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzArgHbRYCWshAjBDQB5hoDaAPAE7b6uFoCyAngGF8AZyywAtgEEsWVqQBG%2BLIgAqACwCGWAOqxWAa2EB5QgCUOXYQD4AumFKEcAXjD0A1GEqQANOCjDsMkIAc2FUMEY-CFAaGkgAEiw%2BAAdkNEgHLB8ouPiANw10fDSInNiABl9Y2MgASUIkRwBlZI1oRAA5fHFs6poAFjKwGxyAXyqaGOqEpNTwjMde6fzC4vDIvohKCb7IAAUNYMRtUngsNSW%2BygAmcqGR2PGcqZrElJLIeVhYdEvcgqKJQ2m2uO2mTUQ4lIcHQFGkAFEGkZcAAZBzIMGxXCFAL3MZgl65WYfL4-P4QBIAtZMIYQADMmLiLTaiAAQohcHpEAdWBpxNhEKxyTRZMU8Y8CUMZu95qTfozKasgbSwP1GRTme12Zz2CjYAB3QXQDQBep5WDGsgUYUQUWIcU0J6xQkUt5zdJy4WKwHrFUAVnVUE1bI5XIAqslUqxjabCObLeRCDa8Dj7X0Ho7Jbs3STvvKpSsfTTNmAAGyByDB7VcgToE3CAQUUSsfAkPTJ7HoXHp-HPAvE2V5r2F6mlEsAdgrVdD7B4kPkgo7qYdECdk37Mo9Q4VI%2BVJYAHFPWlqZ4hG7Ck4HO93qhnV1nlgOt2Sd1S95sAJxHlmSXDKViNuI4gaMmdormAa7RBu7pQJ6r5Kr6JaUJUKqVseIY6ogEJQjC1pXsuPYSn22ZPrB24Fm%2BiGbJQ2yocGv7-th0I-HhKpgYRmbEY%2Bm5kS%2BFEIcW1Ggqh9SNFgJgqKwfAnOcS5dmmt69s60G5nx2aUYJVwMnR6GSKwsBEPAAAiiDoKQUL-qBLYKbEd4QQ%2BrykQsWTwUWY7UWqqE8BotC1Lg6iIIQ8LyU0ah6DopyyYG-R3Bx95cY5PHOcOGnuVcAZeT59S4KQtBGFGWh6PCtDJOwwjCImyZ%2BrFilEcpJFJZkKUCWl1SUOWmW0OYcCsPAJxnBc0U1bZSnrg1MHJa5o7Alck6dXpvJ8EYrBoqI-VRSqMXgZBYAulAObzE1U3vlch6dSi2Csg48AOME62DZtw00HZO17dKE1wfxbkzW1X5efg6BkGZhBsrC0D6KyvLg9gxiEE0fJnj83SXiq142c9o1QeNqn5upLU-bEtwVh0iD6sDIZYIagUqO8Jk5YQpBWoQkgNHO4gLqwYT4fJ20OUSSWfXj30qtctElpWsjQlgPAIBiqMEbVjp%2BDYEwZMIABiFXhGjICjEAA)

**Please describe here fantomas problem you encountered**

Fantomas has deleted the return attribute - this breaks the code

#### Code

```fsharp
let function1     x : [<return: MyCustomAttributeThatWorksOnReturns>] int = x + 1
```
            

#### Result

```fsharp
let function1 x: int = x + 1

```
            
#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Hello, this is an AST bug.

The attributes of the return type are stored in [SynBinding](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-ast-synbinding.html) -> [SynValInfo](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-ast-synvalinfo.html) -> [SynArgInfo](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-ast-synarginfo.html) -> [SynAttributes](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-ast-synattributes.html).

So the [LetBinding active pattern ](https://github.com/fsprojects/fantomas/blob/97ddb311774053f55b183b9caa14ed48e5e5202c/src/Fantomas/SourceParser.fs#L466 )should be extended to also capture the synValData.

And then the attributes can be generated in [genLetBinding](https://github.com/fsprojects/fantomas/blob/97ddb311774053f55b183b9caa14ed48e5e5202c/src/Fantomas/CodePrinter.fs#L511). 
I believe the additional attributes should be passed to [genPatWithReturnType](https://github.com/nojaf/fantomas/blob/97ddb311774053f55b183b9caa14ed48e5e5202c/src/Fantomas/CodePrinter.fs#L2635).

The attributes themselves can be printed with [genAttributes](https://github.com/fsprojects/fantomas/blob/97ddb311774053f55b183b9caa14ed48e5e5202c/src/Fantomas/CodePrinter.fs#L415).

Could I persuade you to tackle this issue yourself?
Check out [this video](https://www.youtube.com/watch?v=UFUOYc22rkk&list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K&index=2) if you are less familiar with AST.

**Comment by kontomondo** [comment]
@nojaf From what I could tell, the `genPatWithReturnType` is never called in this case, under `getLetBinding`, the below code is hit:
```fsharp
       +> leadingExpressionIsMultiline
               (afterLetKeyword +> genPat +> enterNodeTokenByName rangeBetweenBindingPatternAndExpression "EQUALS")
               (genExprSepEqPrependType astContext p e)
```
and in turn in: `genExprSepEqPrependType`:

```fsharp
        (addExtraSpaceBeforeGenericType
         +> genCommentBeforeColon
         +> sepColon
         +> genType astContext false t
```

since this is called from a number of places, I triedd introducing an option valInfo in there:
`and genExprSepEqPrependType astContext (pat:SynPat) (e: SynExpr) (valInfo:SynValInfo option) (isPrefixMultiline: bool) ctx =`

and pass it from `getLetBinding`, then I added:
```fsharp
        let genMetadataAttributes ctx =
            match valInfo with
            | Some(SynValInfo(_, SynArgInfo(attributes, _, _))) -> genAttributes astContext attributes ctx
            | None -> sepNone ctx
```
and
```fsharp
        (addExtraSpaceBeforeGenericType
         +> genCommentBeforeColon
         +> sepColon
         +> genMetadataAttributes
         +> genType astContext false t
```
when formatting `let f x: [<return: MyCustomAttributeThatWorksOnReturns>] int = x` gives : 
```fsharp
let f x: [<``return``:MyCustomAttributeThatWorksOnReturns>]
int = x
```
note the extra new line and the return in quotes, am I on the right path here ?

**Comment by nojaf** [comment]
I think you are on the right track but again this is hard to read.
It is really encouraged to make a (draft) PR, by correct linking you are letting other people know that you are working on this. As for the extra ` `` ` I think I know where those are coming from.

**Comment by sadgit** [comment]
That looks proimising - now we have to fix the back-tcks on the reserved
word return

**Comment by kontomondo** [comment]
@nojaf @sadgit this can be closed as the fix has been merged in
