### ISSUE TITLE
Comment removed in multi-case pattern matching 

### ISSUE THREAD

**Issue by theimowski** [fsprojects/fantomas#813]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzMAFAIZoCCAlIQEZoBClAvADoB2EEAtkVtABZhEANGCpgA7gEssvVuzAAfMKWG1Z7APTqw0iQGcwcDh0QscesOli6saiIoDCwgCJgAtAD4wAZVjHC5WwUwAH03TwA5WBZkQXAoXWwsCRYAc11UMABtOIhQOQhIABIsAE8AB2Q0SGSsSFj8qEKANyJ0AFdKrJz8gAZ6hqgASRYkUy8yomhEcLaOOu65ABYFsABdboBfftyVotKKjOrTeYailvbO7IGwAEZt-MgABSIUxAB1CXhpE4GbgCYeit1nItt08g9iuVOpAqLBYOgfnIzq0OhkrgM-vckV5EBwJHBLCxSFgAKIjADyuAAMskYisILhWgkgZt7uCkZCDlVYfDEexkRc0fSwABmLH88aTRC0RC4WAAJ0Qz3lRGMWEQ8r5ciw8o6LJBbN2nOhPIR4oFqLQ6Iai3FBUlUxlcsVVNgYg10CICWGTVgnqSUS17B1eoawPYoLk7P5xsOpqDFsuwoArHaoA7pbKFYgAKplCryz3eli%2B-0SQNpxnoZlh1lgo37E1ws1G86WrrXABsacgGad2fs6C9unsUWsuugWAVQYZTMQ%2BojhtOse5zYTzRRSeuAHYe32s4qALK4qgamd4OcLiCR9jRgorqDx80bwVW4UADj3E0dB8Qo8J55VjW%2BThteS4Qo2cZrs%2BbZbgMACcX5SqQuDqvKo5GEQ54hvOtYGvWy6QauvIwZuQrXDcfTCr236Zs6iA4niBIVsKQG4SBdZRg2UJQSRrZkW%2BFF3NRGYoWhjH4vCLHXDhV5gDeOyETxxEtsusHkb8mLUcMoxYOSLAACryiUHzfJWl54YuBEQcpj7Qfxr4dr8YoibRpDyrAbQjE4iDoBIeJodhursXIoHyeBHJEVANTrupgm-La1GHkQAAegy4AZvAmCS1YMbwCpYB8Xy8OeiyApZYHWZFtlHLUpGOda%2BQ3KmSWpcMuASCl5IFtwCokilZSKroujliw57JuVHH4VxSlctFxz1e2jVyDc3atSlABKiBwPK8BFWZwplXJClgHejRRbVsUCU5DQ3Lu63uSqJTkvKNLWPtJVpkdFXhVVMYXTFi1wbdn7rVS2C0Mk8DJCkH2lZNoWcbe3FzTC9lqddy3sDciFJW06BJH50S0JY0AANa0Cq5PYLo%2BleKqf7wrMY3mblx0Rf9NVPg5S3CgCPbhIgYhE5mWDuiYBlQj5HUsFIo2kCMx4cKe8rpKzwGI9NyOzU2fEYw1fPCdcvY6viWCHggdLXGxx1xKs-TVLoABiI0ZDbGxAA)

When there's a comment between two pattern matching cases that end in some branch, it gets removed

#### Code

```fsharp
let f (a: A) (b: B) =
    match a, b with
    | A, B
    // this comment is lost
    | C, D -> Some ()
    | _ -> None
```
            

#### Result

```fsharp
let f (a: A) (b: B) =
    match a, b with
    | A, B
    | C, D -> Some()
    | _ -> None

```
            
#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
The found comment is assigned to the `|` token before `C, D`.
![image](https://user-images.githubusercontent.com/2621499/81408990-914d8d00-913e-11ea-87fd-b5201b712c45.png)
![image](https://user-images.githubusercontent.com/2621499/81409025-9f9ba900-913e-11ea-89a9-f94401b5355a.png)

And no trivia is generated around [PatOr](https://github.com/fsprojects/fantomas/blob/97ddb311774053f55b183b9caa14ed48e5e5202c/src/Fantomas/CodePrinter.fs#L2569).

Most likely enterNodeTokenByName before the pipe might do the trick.

Check out [this video](https://www.youtube.com/watch?v=FCrkUqCCzgI) to learn more about trivia.

**Comment by kontomondo** [comment]
@nojaf Thank you for this project! This is my first time seeing this codebase, but I figured I could try tackling this one, I had a test added in `CommentTest.fs`:
```fsharp
[<Test>]
let ``comments in pattern matching cases should not be removed, 813``() =
    formatSourceString false """
let f (a: A) =
    match a with
    // comment for case A
    | A
    // comment for case C
    | C -> Some()
    | D -> Another()
    // comment for _ case
    | _ -> None""" config
    |> prepend newline
    |> should equal """
let f (a: A) =
    match a with
    // comment for case A
    | A
    // comment for case C
    | C -> Some()
    | D -> Another()
    // comment for _ case
    | _ -> None
"""
```

and added `enterNodeTokenByName` where you suggested, however I hit an issue with an extra new line being copied
```fsharp
    | PatOr(p1, p2) -> genPat astContext p1 +> enterNodeTokenByName pat.Range "BAR" +> sepNln -- "| " +> genPat astContext p2
```
so I went with 
```
    | PatOr(p1, p2) -> genPat astContext p1 +> enterNodeTokenByName pat.Range "BAR" +> sepNone -- "| " +> genPat astContext p2
```
but that may introduce its own issue I figure?

**Comment by nojaf** [comment]
Hello @kontomondo, thanks for your kind words.
It is hard to say what the impact is of changing `sepNln` to `sepNone`, I would think that you might need to make a decision based on the trivia of the BAR token to choose one of the other.

Could you maybe make a (draft) PR with this code? Then I can easily check it out and we can see if all the other tests still pass.

**Comment by kontomondo** [comment]
@nojaf Thank you for the reply! I've opened https://github.com/fsprojects/fantomas/pull/834 draft PR

**Comment by kontomondo** [comment]
@nojaf this issue should be closed since the PR is merged.

**Comment by nojaf** [comment]
It seems like the linking of the PR with against didn't happen alright.
