### ISSUE TITLE
Something like MultilineBlockBracketsOnSameColumn but for tuples

### ISSUE THREAD

**Issue by lydell** [fsprojects/fantomas#814]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMiAeADotFovGALwA6ATlQHYQQAUAogG6L1YB0AggFcsAC1g0wVSACtYw%2BpIA0tBkwgBtMBy68ASok70BiZY1Wq2B3fq5GAkuUkBGAEwBmRSbNmt3HgFkAQyxoYU8vcOAwLBoA%2BgBnAJIAS1h6e0owR1dXAHYw8PCAgFtYAW44ynyC6sisWCwA9AznAFYABg6OgBkq6ur2IIyANlbOrrAAX0mASjAAXWmTSAVwKDjsLCT6AHM41DA1VYhQL0gAEiwATyJ9yC2sZaOmc4H0I33DgraVgshbeiQ3AAygREogAHICIqPAoAFieEDmTwmPyYJzM5yuNzQd24MIxZ1e7zQn3CjlRpwACgFtogAOpJeAifFeFxtBHzZEUsDo1SY67IHEAI1gsHQLOehMaxIOHIgzm5fKBiCKSTg6FSfCwrABAHkAGZdLbIRVMfWNdYcpGqFFPXmSrGCqAisUSiAvaVO0leVym90gsEAIUQ%2BrEiGpMSK2EQNDdTGiRitXLtHP52OdovFpo9by9crAsL9UAD0EQwdDNEQXVgAHcY9AAut-uxYA3Nqk4xAE4gkzbufb3RcBbcXVnU1Lcx98y0i5AS2WQ2GAKoEIg0BtN%2BgttspeidsDm9CWrzWpi21QDqBD9OQUdxnMy71mIaz%2BflsMAYXQjbiH9ScQTEgxH3Q9jzMU8IHPNFx0dEdM3vCdH3zHJX1BUt30rPwVSFGMQItHsT2TC8YOHYV4OzRC8wKAAOVCg0XSs-w1Pci1AgjwKI6DTmvJ1b3I8ciSo8IAE46NLPh9VIGg-yKIoAn3btezPfsSJvO8KMEqcCkcb58znNCFwrRBlVVdUO1Y-ClMglTuNgsjXQ0z0tLJck9PnCSpJMtUxXM-NFMIvsU1s0iMwcgSnJJfMXFnf5ASwXV6AAFRoS4GWZCyj3Y1QIMmGyCTs0Kx24zTIu0303IMvgaFKAEABFEHQJJVSkhSaETALlKC-KQtxB5HMnUqyULPTAjwWx9US4QuFYTKgVEGgsAZJlhH3WF2Q66yur5HjbnuBCStlbSZxGgIxvofUkjwXU1yCMRWEISs4jiXd93aKzcq2h0er2-qkO0l8TrwPQ4BoeAlvS-M1veqDjlU3ifvCgbDrJFDAaqmJLl1GgjQA8GVqLKGNo%2B4jgpvBHioi5HWVowGumwQMtngLZtjx1b1o4wKSe6tT%2BIppGn1URxRJGgR0E2Rr6DLDVoAAa0DGJZewOIEqBYpECYqEWL8tqsqYHKYZ5OG4LCvm-vCZxdN%2BcFEBrCWFywOsuESgV6ou%2Bgknbeg%2BABLCihwmg9gysDss42HSd49TEbNrxnFc34gWiNUsD8BATXzNjodWOZUTuOIADFnv2DOJiAA)

Thanks to #453 we can now have `[`/`]` and `{`/`}` on the same column for multi-line lists and records! 🎉 

It would be great if we could do this for tuples as well!

(See also #815)

Motivation: It makes the code easier to edit.

#### Code

```fsharp
let expected =
    (Event.Author "john",
     [ Event.Revenue
         (Event.RevenueId "123",
          Event.Match
              { transactionId = 1337
                amounts =
                    { total = 2500000L
                      vat = 625000L } }) ])

```
            

#### Result

```fsharp
let expected =
    (Event.Author "john",
     [
         Event.Revenue
             (Event.RevenueId "123",
              Event.Match
                  {
                      transactionId = 1337
                      amounts = { total = 2500000L; vat = 625000L }
                  })
     ])

```

#### Suggestion

Something like this would be great.

```fsharp
let expected =
    (
        Event.Author "john",
        [
            Event.Revenue
                (
                    Event.RevenueId "123",
                    Event.Match
                        {
                            transactionId = 1337
                            amounts = { total = 2500000L; vat = 625000L }
                        }
                )
        ]
    )

```
            
#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| **`MultilineBlockBracketsOnSameColumn`** | **`true`** |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
I'm going to close this as it falls under [What are we not looking for?](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for).
There is no interest to pursue this.
