### ISSUE TITLE
Something like MultilineBlockBracketsOnSameColumn but for parentheses

### ISSUE THREAD

**Issue by lydell** [fsprojects/fantomas#815]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBzRAXAqgZ0QCcAhATwEl4wBXAwygHUIYDsAfAPjAEE9SXoAJUR5qAGywA6ALYBDAA4BRQoViEwACSxZ5AcWzLVzZuy69%2BQkeKkAjAJYsqACgBm1AVjuwWTVhAhsYADKsNKINHRgALQcviz%2BCTTy8LJYiPhEYMARmQDudlgAFmBYsADWiPEAvCXllWAAvnEJgQBy3uExzYkQhO4A6gWFADKw6OgO6N09CU7QhIip6XTTMz3ZdlQ1GfRUAAyraz0uaoh26CyUYDVwLFiy0FKbh0cJLLJh12C394%2BS72EXq8IKUKtVamDGgBKKGQAA04CgBG0kzwqDAAG1ERBQD1IAASLCkeTINCQBxYeHY-wEgBusjE1FJmOpCT2CLWkHIjkqWCC8geiFa1GkVLWABZWWAALrUhoc-y4xIEokk9Hku5i5X4%2BmM5lYtYARgVeIACrJMIN4EUtT1DQAmPZS2UJeXUpUJFXE5mQGywWBiW00nUMpnog0ze0m5VBRDSOxwMTebhYRSOADyLmGDmQ0YSLgZBGdcujHuDqp9foDQYgdND%2BqlEAAzHmafzBcRECcFubCB9sEQa-4sH1EMXXaWpV61WSq4HW3W9eHG2Bxa3a%2B3oIhO93EKNckRoLICNzabAj55vEOQaPx-43Qky7XCd71XOh4uw2gIz0AKzrqBN23LtThweQSUII8TxYM8Ly8FhrzAAsxCLHoXXvSc8RfGcoHfBcQyXb8VwANgAyAgJ3U4AGExGPPAqO8PAR2oR41EQ5DUMSdCIAfRUp2wyt-XnfjdS-Fk1gAdjIiiQIWABZOMbEHACOLHNCS3dfiKzfISPwIsSf0SAAOaSBS3SiFgYpMEJUws1K4jTHy019Z10-DRIbNYAE5TMFbgXDSQgGOkOREOY%2ByEm4xpMO1bTXOrdz62XI12RXcizOA3dY3jRMr1slCIv8KLeJxZycN9NyRKSoijWNNKgP8wLsoTAM8pXcK7x4mLPQEnSEqqwjxJmB0yO5JA7nTFgABVCFIQYbXyzjIscvisLi3DKqwjzkuGlt6oy7hVHceAABFEDEOx40CsLb3UidNLWlyoApPTtpq4a1zSuTZAAD3IFwpsKSpFAKoJCjULArQWldxSdO6MIe2Kno1SlEsGwyEkNf8vt%2B7kXDsH70wg1I1EUH75AWPA8HgxDfzhhz7qcx7ypetGDJXQ1SJxn7hDgQh4ChwpENhzrosRnr1pR17qqGu0pO5w6%2B1IdNCGzJjBeF%2BnlsZ1akZZzU2c84aTO54ZsGIBx4EmDWAJF%2BGuvF8tkbwgb2aNHyvusOwLpYbck2gMpiD7APsDwSagn7KyRRs9rboZhGmb1wT%2Bq2mWMf8R0yNaRBch94CsAPSopu9M78ZYAp4O4RwFOkJTCDRRbCogYruqd8qXdT9GV3tOrOSCEcEywOSEFzFdVNFhpEWlBVyTwAAxan0XHhogA)

Thanks to #453 we can now have `[`/`]` and `{`/`}` on the same column for multi-line lists and records! 🎉

It would be great if we could do this for parentheses as well!

(See also: #814 )

Motivation: It makes the code easier to edit.

#### Code

```fsharp
getUserById userId
|> AsyncResult.mapError HttpGetError
|> AsyncResult.bind (function
    | Some user ->
        updateUser { user with token = token }
    | None ->
        runWithLogging
            (createUser
                { id = UserId 0
                  foreignId = contact.id
                  name = contact.name
                  token = token }))
```
            

#### Result

```fsharp
getUserById userId
|> AsyncResult.mapError HttpGetError
|> AsyncResult.bind (function
    | Some user -> updateUser { user with token = token }
    | None ->
        runWithLogging
            (createUser
                {
                    id = UserId 0
                    foreignId = contact.id
                    name = contact.name
                    token = token
                }))

```

#### Suggestion

Something like this would make code easier to edit:

```fsharp
getUserById userId
|> AsyncResult.mapError HttpGetError
|> AsyncResult.bind
    (function
    | Some user -> updateUser { user with token = token }
    | None ->
        runWithLogging
            (createUser
                {
                    id = UserId 0
                    foreignId = contact.id
                    name = contact.name
                    token = token
                }
            )
    )

```
            
#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| **`MultilineBlockBracketsOnSameColumn`** | **`true`** |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
I'm going to close this as it falls under [What are we not looking for?](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for).
There is no interest to pursue this.
