### ISSUE TITLE
Brackets around lazy invocation

### ISSUE THREAD

**Issue by JonCanning** [fsprojects/fantomas#816]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMWAWAlgHYDmYAvADpEToCGAXgJ7US3ZgAeFYAjK20w4mPAEwCInADRgmkKeCgBnbFmIklqMAG1FEUGzaQAJFiYAHZGkjEs8vUeMA3OugCuVnQ8MAGBYcNIAEkiJCIsAGVzOmhEADk3AFt7ALYAFm8wAF0HAF9-NgMAkzNLLRtwlOLnVw8tXVSIXgLUyAAFOhJEAHUCeHwq1N5RH0ycw3yHIsDTC09IACNYWHRBxxd3TwbG0RbiiMREgjh0WCIAQSwAUVCAeQAzABliZD3De9cVMby96cdS%2BZLFZrCAmDZ1NDbVIAZjeRiiMUQACFEPdYAAnRAddF0RLYRDokFsLDojzfCa-TIlOblIGrOFg2pbTIQNJw0EI2IotGYx6wADuBOgdBUIScsGFajORIgH3QX1S4zYk0Mf1BszK1jpRMZm3qLLAAFZ2VBOcjURjEABVcyWdHC0VEcWSgjSk1yhUBJUQFWFKkawHLen%2B8HMxpgABsJsgZu5loAwvQlEp42clCS3NAsBiZWAPYhycrKa0A7SgzqanrIQaAOzR2MWzEAWUOCwJufzhZ9xeqALLwIZlYhXnDAA569EuY3EKnTkQO58C4qflN-X2teXB6H9eGAJwTxHne5YAmpxKJOi5jNLr0r1Vrmkbgchpk7xq8PwGmOT808xAHI4TjdA1O2XClVxLdcoG1LdX2rcNeGaL8zSPE90QA44VmA8Nry7MBfX0B9NWgzcXyrEd312L8QjCLBbiIAAVdEmF6AZ3UXPCCLANUoFLJ9gxLbd4PfWFkJ-c50VgNxQgAEUQdACCONCr1JG9DG9fCexmKCKjsWDyKhAJeDZL8mzoTggnuBi8EQIgrnlf88AxLBen6PBczSUYwKLCDe0fKBbArISKKGY1TPMkJ7gIThbjtOhs3RK5OHMTFk1decTUNLzb3A%2B9IP83SgrgkKjKjcLOAAJUQOB0XgVy2INTzOK0-4CsC-Th0MwxeDrcqJJxJhbnRZ503q9yTSa7zu187S2sqDqw3fcdysebAkWIeB1DGjzsvUu8-Xy4jFlIwTiq6theH3Uy3HQNQFKIZFTmgABrJEcRe7AlHoiJcRnFYkgykCOKmzSZtao6YLIzqDRGaM4kQfl7vNLBBVshi5jkqKiAIKULlCFtEjbdFNHYhzmrB9UdMh06DJhpDwxjEljiwJsEFeIGyZB3JFCyAobCUAAxJQCC0TtciAA)

**Please describe here fantomas problem you encountered**

#### Code

```fsharp
let thing =
  lazy
    let x = 1
    let y = 2
    x, y
```
            

#### Result

```fsharp
let thing =
    lazy
        (let x = 1
         let y = 2
         x, y)

```
            
#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| **`SpaceBeforeLowercaseInvocation`** | **`false`** |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `StrictMode` | `false` |
        
Could these be optional?

**Comment by nojaf** [comment]
Hey, maybe it depends on what else is happening in the code I think.
If the whole expression is followed by an [infix operator for example](http://localhost:9060/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMWAWAlgHYDmYAvADoBOlRE6AhgF4CeNdED2YAHhWACMHel0w5WAgEwiufADRh2tUQB8AfGABmsWLLAjxuQqQr6mbfRAAUR-uSFXuE6U4VKAlPo3bdkeeBQAM7YWMQkQahgANqBEKByEJAAJFisAA7IaJDEWP5xXCkAbozoAK5ZMQVyAAwBiYUAkkRIRFgAyumM0IgAcmUAtvkNEAAs1WAAugUAvvVcCYkpaZlROW3DS8kl5ZWxI0LzDZAACowkiADqBPD4mw0AbDUT03JzBYtyyxmVkABGunQ90K21KFSi%2BxGUiOS3aiAGBDg6FgRAAglgAKItADyWgAMsRkDC5FpSiEXrMYZ8QStfgDYEDiVBQbsIRMIABmJlJTrdRAAIUQOmoiDO1EYA2wiGowLkWGoFQpbypE2%2Bq2y9MZqpZ4LQkIao25UF5PUFwsQeNgAHdpdBGCFmkVYHawijZVx5YqGq8uO85NSkqkfmtNe7imC9uywABWI2QE0CoWwEUAVXSmWododRCdLoIbqNpPQ5O9lI%2B2tpIcBYZ1kYODzjCbNycQAGEmEEgq2UUFPdAsMn3RAiyXEj6IH6FhXgxrq0zw6y9VGAOyNrqmpMigCy8L%2B0qH2jJiCVvpVxyD6qgofntbZBwAHGu%2Bc2Rd3kUQDyPj6XleXz5XZwZGsdl1KoDgATifHpUS0LBpW7AYBkYA9PW-Mcy39adL3%2BOdtRAusRkEOoo3jddE3NOEESRAsoy-E8JzPLYAKvXDz3wu9CMEKDEBguDqEoxEGRog5UPosBJ3iLC6VYrZ2KXA5BGhEjmlaLBsSIAAVahWGuO5CyPMSJLAANmWYnCgJvOSwMIrkSITVFqFgMoWgAEUQdACARPiUIVNC5HHcTGK%2BC9flyYCIw4hpBENEit0YXhGi0DS8EQIgMWLRB2jwZMsGuW48APUZnh-U8-yYmcoDCyyIvkwjY1i%2BLmi0AheGxDNGAHagMV4dIRU7fMPyNaNivQ39MP-Cr1jyarF2sqKGwa3gACVEDgah4DyvSoyKwygppSaqrwmq5sSQRV0WhzxVYbFqAJXtNoKo0dpKhiyuCszDrY479VOx9FrxbB%2BWIeBwgewqRv8jCpwm7DryO2afrkQRINisp0DCDyiAFZFoAAa35cU8ewIJ1PaCU2wZQZBtogyXsCt79thmTgqsxGuCkYiDkgXpECtTHEywG1Uo0n43OaogCFdNEWh3AY92oSJ9Iy3aGcDMy4a%2BhGoykLi7PlREsC3BAiRp5W6ZmQJJnmHIggAMSCAgojomYgA).

Could you try and come up with a rule when we can leave it and when not?
I know from [existing tests](https://github.com/fsprojects/fantomas/blob/64b8fe364f3956c563237804f5b84b046d23479d/src/Fantomas.Tests/LazyTests.fs) that the safest bet was to have the most construct wrapped with parenthesis.

**Comment by JonCanning** [comment]
I just noticed the change from the previous version and preferred it aesthetically, but if it improves safety then that's more important
