### ISSUE TITLE
Updated value not indented correctly

### ISSUE THREAD

**Issue by JonCanning** [fsprojects/fantomas#817]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMiAeADotFovGALxjBgAqAFgJYDOAkswIIOMB2A5gDoAogFsCWAJ5gA7oyz069RADlE0gGoBDdAFdElMAEYwAXwA6PSABpwUZtiy8%2BzVGADatiKAg%2BoAEkkiV0heLGtPH0g-ADdtPVcPX18ABhskyNYeJB4sAGUCTWgVHRFw9IgAJgiIAF0IkzSfbySowOQ0EJyylpi49vdqn0NG9MgABU0%2BRAB1Rnh5bvTDCuTBut8GiObfVokgjoAjWFh0Rcje3X7E8oqRltzEEUY4dFgeDiwhLIB5ADMAGV4yDuvl%2B2nsa3qd225zawSOJzOECisUuCUGEAAzCDIvlCogAEKIX6wABOiAmpM0ImwiFJSJ8WFJekhG2hg12%2BygCNOOJRfXR5TAABYcci8UUiSTyf9YNI6dBNPZMtFYIrHG8GRAmSz0usfJtfDDkQE9v1IDyGfy0WhrukAKxiqASwnEsmIACqBCIpMVyp4qvVjE1TrB6AheqhWw5pq5FuOvJjqPitoxYAAbE7IC6pe6AMLoJXMPNvZg6khkrVgMMRpL6iCGpoxuGHBNWi4pgZCgDsWZzbvJAFlHgc6VWa4hWQb2aNY%2BbLXyO1c0wAOPsFSUDxAl16WUPgyeRtnR2ct7ltxfJ5dCgCc6-xHF%2BpFJJZEIk0VZ1h7rUaNzbN8IXkmAqpkKhipGm2Ybq60qIA8TwvCGaYTlODYzj0Z7xoil4gV25SGMMkEuo%2Bz7wc8JxIUKX6oaY6E7HOgHYcBNp4UstyQZk2RYN8PC0KSEizAs%2B7ht%2Bvj1rRJ4YQBrZMbOV6Cvh2JEdBHCkrAOhZAAIog6CME8z6fsyok%2BOJjZeP%2BcahO28mgfhoqQYOmh4KwvwMIgPBCCJuT0GSWCzPM9BVsKqxHtOkn0ZhVk4SxdpJIYjoOU5mS-IweDfD6mhYGSQiEOSzDMMGe5pvaIU-sef6ntJUBRcxnaxb4hiZoleAAErEGS8D%2BUJabBTRZnUBZ5o1XJuH1UMvbNapVISN8pKAmWXWBU6vWhWh4WwlVnRhNFdVpoYa7Nf82AErw8BOItQWlWJv5NpVcYLrV174XeDk6Ogji6TwhKvNAADWBJUn92DMDxuTUtuJwlEVVFGX1dEbfdQEjTFaYrFmqjSJ9rpYPK7m0Ga2kpTwciFRwWTDiIo6ki4wm1td5W3VJiOyT0NmsUkFSEUK2ZMs8WCDggwLIQefW2DUjQhMwABiBWuChJhAA)

**Please describe here fantomas problem you encountered**

#### Code

```fsharp
let expected = { ThisIsAThing.Empty with TheNewValue = 1 }

```
            

#### Result

```fsharp
let expected =
  { ThisIsAThing.Empty with
    TheNewValue = 1
  }

```
            
#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| **`IndentSpaceNum`** | **`2`** |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| **`MultilineBlockBracketsOnSameColumn`** | **`true`** |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Not sure this is a bug actually. Is your code not compiling anymore?
The `MultilineBlockBracketsOnSameColumn` was introduced to comply with [this rule](https://github.com/G-Research/fsharp-formatting-conventions#formatting-copy-and-update-record-expressions).

> And as with the record guidance, you may want to dedicate separate lines for the braces and indent one scope to the right with the expression.

One extra scope was added to before `TheNewValue = 1` so that seems ok to me.
Am I missing something here?

//cc @Smaug123

**Comment by JonCanning** [comment]
It compilies but I get an indentation warning, but if you disable `MultilineBlockBracketsOnSameColumn` it works. It's only a problem if `IndentSpaceNum` is 2

**Comment by nojaf** [comment]
I believe the problem is resolved if you put `TheNewValue` one space further than `ThisIsAThing.Empty`.
One space would be weird so another indentation would make more sense.
I think we can add a check for this, should look into it more to be certain.

**Comment by nojaf** [comment]
@JonCanning I released [alpha 005](https://www.nuget.org/packages/Fantomas/4.0.0-alpha-005) with this fix.
