### ISSUE TITLE
Class type with long variable names results in invalid formatted F# code

### ISSUE THREAD

**Issue by Bobface** [fsprojects/fantomas#841]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAyrALaIAqOiAFADax30ONMMB2A5gIxoDO6ATgEt2AGjC1mEyewBMPfkLajxklazYBmOYPZgAtAD4wvbWwCUYALwAdPlZYQIJIgCNEfMOgAWA7gDpCJACyiF4IYJTm1rb2DrFWkL6J8ZDC4FDcIegK3KhgANppEKCxEJAAJFi4uZBC6CmFDuUAbgCG1ACuyGgFJQ4ADKm9pQCSLEgs6PjYLdCIAHLtRPVDYAAsDRAAug0AvoMOxSXllV1QtctHZa0dpz1DHPu9kAAKLWyIAOoC8F4XvRzSPobMDbWJ7BqHWLHCjVZx0ah-RpXNqdXJ3XrSR5HfCIIgCOC0FgAQXQAFExgB5ABmABkhMgsbEqW0MsDQQ5wbFIUiTrD4YjSsibmjgRB1IzGlMZogAEKIKmwPiIV58FokdBuAUOfidNm7LHcwW8tCQOGwBES5oo26itYS0pS2ZyhVKmmwADubmgLQyoyasG9WVgLC1EB1iD1YINwOhVRNZotMaFqO6toArPaoI7ZfLFYgAKrYXB8b2%2Blj%2BwMCYOhsDM6is3rsiCcg5J41QBNaq3C1MrABsmcg2edeYAwtQfdxR8HjO1oOhFTW6w2Sk2wC2im2YfH%2BZbkzaVgB2QfD3NK4IuTWZ5cRxv6iFbuMd3dJ64p-K2gAcJ%2BmTrPiGnQklxZW9V3vLlH1OU0XyefcRRWABOH9pSJKkNT4aciCIFoa3DSMOWjWD22g80uzg3t7gGW0h1-HMXUQHE8QJatrxA-Dm0Iy5iM7Pc3wPe4Hmo7NUPQxj8XNFjbTwu8owfIjt2fUjeOteD7kxajRnGdAKRYUg%2BEwL5flY%2BtQNiNcNzAQ0oAqBSSMTWC%2BNU-5xSE2iiT4WB2jGAARRBqAEPF0NwvhdRkgi5K42zzmUnsPxWDhVkHQIWgAD2GKlSE8RAWFJEz8E8RV0C%2BH5PBrVYgTCjiIqhGynxqCYyMcij-gzajkrSlgqQEFKKWLFoFz4UkUuwJVuG4KsQ0zNMKrA2SIPkurotfFTmpKDgBza1KACVEDgPh4GKozbXK9j104mriKWhyVri%2B5j02lL3NVTAKT4OleEO0rMxOyqzuqnkooamL33RNbvwemkQhlIR4AUT6ypmszwNbBaoJ45bYtB2IOCQtr2moLJ-JYWVaGgABrGVVXJkJuB0-A1QA81Fkm20b1OiyrNjNGYMuJrboxKiVkgOZEHdImc3QT1svIXBfK6lgBCDYkxgvVw%2BByYyVyRuaUciur0euzHbWkQShYAaUQRBsHSzLstGemSDpYngJM9nzoB-WeZqvmsYcaR1KF-B5HnQIEAZVm2N%2BnY0k2fYam4AAxcbcjZnYgA)

The formatted result for the code below is invalid F# code: The variables in the result are missing a comma `,` at the end of their corresponding lines.

@nojaf I would like to work on a PR which implements the commas at the end of the lines. Let me know if you agree with this fix.

Edit: It seems like there is already a test in `TypeDeclarationTests` which checks for this behaviour:
```
[<Test>]
let ``long constructors should have parameters on separate lines`` () =
    formatSourceString false """type C (aVeryLongType : AVeryLongTypeThatYouNeedToUse, aSecondVeryLongType : AVeryLongTypeThatYouNeedToUse, aThirdVeryLongType : AVeryLongTypeThatYouNeedToUse) =
    member this.X = 42
"""  ({ config with SpaceBeforeClassConstructor = true })
    |> prepend newline
    |> should equal """
type C (
    aVeryLongType: AVeryLongTypeThatYouNeedToUse
    aSecondVeryLongType: AVeryLongTypeThatYouNeedToUse
    aThirdVeryLongType: AVeryLongTypeThatYouNeedToUse)
    =
    member this.X = 42
"""
```

However it also checks for the wrong result.

#### Code

```fsharp
type SomeType(looooooooooooooooooooooooong1: string, looooooooooooooooooooooooong2: string, looooooooooooooooooooooooong3: string -> string) =
    member this.SomeMethod () =
        "..."
```
            

#### Error

```fsharp
Fantomas was able to format the code but the result appears to be invalid F# code.
Please open an issue.

Formatted result:

type SomeType(
    looooooooooooooooooooooooong1: string
    looooooooooooooooooooooooong2: string
    looooooooooooooooooooooooong3: string -> string)
    =
    member this.SomeMethod() = "..."

```
            
#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

**Comment by knocte** [comment]
I think this is a regression introduced by this commit: https://github.com/fsprojects/fantomas/commit/ef2e6f3f51b7ed423d2ca0309af05378af3c375b

**Comment by knocte** [comment]
The culprit of the regression is that the unit test is actually wrong, it's missing commas. This is something I noticed myself in G-Research coding guidelines and I fixed with a PR here:

https://github.com/G-Research/fsharp-formatting-conventions/pull/1

**Comment by nojaf** [comment]
Hey @Bobface and @knocte, good catch. I just copied that example from the G-Research style guide and missed the comma's.

We need them in this case, so @Bobface it would be great if you could work on a fix.
I'm guessing the fix will be [changing sepNln here](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L2689).
Not sure though, can't look into great detail now.

**Comment by Bobface** [comment]
@nojaf Yep that one worked for the member tuples but not for the constructor tuples. Am currently looking into where the constructors tuples are implemented.

**Comment by nojaf** [comment]
Probably around https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L2527
