### ISSUE TITLE
Verify all unit test whether the formatted code is valid

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#842]
In light of #841, we should check whether each unit test is producing valid F# code.
We currently only compare afterwards if each test is matching the expected string.
This is not enough, bugs can still slip into this if the result is not valid.

//cc @knocte @Bobface

**Comment by knocte** [comment]
And in light of https://github.com/fsprojects/fantomas/issues/868 maybe it should check for warnings too?

**Comment by nojaf** [comment]
Yes, seems like a good idea.

**Comment by knocte** [comment]
The commit 17fa4cb803b470bae315b70248f14eaa8e7285ff doesn't seem to fix this issue, @nojaf typo in commit message?

**Comment by nojaf** [comment]
Indeed, I tried to remove the link in (https://github.com/fsprojects/fantomas/pull/1015) but the commit message still triggered closing this.
