### ISSUE TITLE
Wrong indentation in member definition

### ISSUE THREAD

**Issue by Bobface** [fsprojects/fantomas#844]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAyrALaIAqOiAFAJRgC8AOgE4MB2EEJRARokwcUQBZRDz6UANrGkzZc%2BQoWsA5gEY0AQQA0YKYv0GlygEybajFuw7XsTAJat0AM3YNIAQzfM21628%2BQ3la%2BYEHWXLz8hCQA8ugAFnwiYvw09GEhYLYOzq6Q3G6QWuBQAM6I6OgOyqWoYADaJRCgIZAAJFi4dZA5RU0c7QBu7hIArshojZlgAAzF05AAkqxIjvjY7tCIAHKjRH3TACz9EAC6-QC%2B8xwtvu2dE1C919ZDI%2BN1U5mqL3cACu5lIgAOp2eAJA6ZAAcMxOYHO1iu-Vurw6FG63GkEkhqOGY0eXxCxl%2Br3wojscCkrA06AAoisYk4ADIOZAkjhOEblOEIjhI6wogZorpofJYnFCvEfSZwiAAZnZEEg602iAAQognLAmIgAUx3CR0HwJdZ0ExxjzLr9BUrhY8xbBsey3vjPrKwIdFVAVVsNVqdUzYAB3PjQdzlZaDWBhqqwVgmjhmi0hXkQfk3OH3dGizGOhMu6UNd0AVi9yo2vs12sQAFVsLgmGGI6wozG7HGExBORJuSmrcjM3aMeLnW0pQT3QA2Ms%2B9VVnUAYQk4dKC7jpST0HQ2s7YG7vd8qbA6eag4ew7zo-HbumAHYZxW5-7hKJIrv94hLYjrWfs1Bc06g7XjK0xQg%2Bqp%2BtWa5Uu%2BXKfn234Dq0Q45iOQHvBO0wAJzgVsGhOEaTBrkQRDuLuSbwYe-YCr%2BIr-mhyHAUW0yqHM7rlhB86IGSRAUo6HZeh%2BX58j%2ByHnqhl7oa6IHfD87GzvhhE8XxMFehRwlpqJdwofRkmMRhN7fMS7HLKs6AxKwpBMJgoIQoJcEaceWmouJumAfp0nMd8CryY%2BGhMLAowrAAIogEh2LxhHkealHWEeJ5gDaUA6T0jj5mOBkySEqieuxQjuAAHosTikIkrC0j23HxNq6CguC8S7ocsIISJSHaa5qXoOlTGEr4qilnlhXLE4dgFTEDbuNuTC0gVtiIKUpTtvGXrFs1VGITRYl-p13WZV52XToNBUAEqIHATDwHVdnuk1jkJUlWZ0TtV57b11iqPeR3%2BfqmAxEwLIbldDVerdLWaW1Lnbc8UmFm9HCqGBR1MhUaoOPA1RA41a1xdRGZbU9AG7Z5cMQKoOF5aMEhVOFrDqlI0AANZqvqjMVKUFn4AaiDQXsy3ukJYNORDQodYTL3E%2B6xhsQs2yIEGNNzugIaIJZFChSNrB2LG1IrMkkS1PZlV3c5IvbWLMOYZkxhyQsADSiCINgxWlSryycyQLK07BRuC-dtH2ubHmw5LxkLPgZoUugQgIGy-MOb7JSnNcPSlAAYotdRCRcQA)

When a member is created with arguments which exceed the `PageWidth` they get split into separate lines. The body gets indented too much which can result in indentation errors further down. In the example below `SomeOtherMember` is indented one indentation too much. Also an additional newline is added between the `=` and the method body - I do not know if this is intended.

From my testing it seems like this condition must be met for the error to occur:

The parameters are spread across multiple lines **and** the body of the method is longer than one line. If we remove the `printfn "a"` in the example below it is formatted correctly. If we remove one of the two parameters the result is also correct no matter the length of the method body.

#### Code

```fsharp
type SomeType() =
    member SomeMember(looooooooooooooooooooooooooooooooooong1: A, looooooooooooooooooooooooooooooooooong2: A) =
        printfn "a"
        "a"
        
    member SomeOtherMember () =
        printfn "b"
```
            

#### Result

```fsharp
type SomeType() =
    member SomeMember(
        looooooooooooooooooooooooooooooooooong1: A,
        looooooooooooooooooooooooooooooooooong2: A)
        =

            printfn "a"
            "a"

        member SomeOtherMember() = printfn "b"

```
            
#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| **`PageWidth`** | **`80`** |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Thanks for this report @Bobface, I'll look into this as I'm most likely the one who introduces the bug.
The first thing that comes to mind is that I forget to add an `unindent` somewhere.
As for the extra newline, this is not intended and also rings a bell what might happen there.

**Comment by Bobface** [comment]
@nojaf I am already trying to find where the bug is caused. Any tips would be much appreciated!

**Comment by nojaf** [comment]
So going back to the scene of the crime: https://github.com/fsprojects/fantomas/pull/818/files#diff-a1b0b9a30fd94fe61b35a1a52ce27955R689
I think the helper function `autoIndentAndNlnIfExpressionExceedsPageWidth` should end with an `unindent` at the end. 

As for the extra newline, not sure right now. Can't really look in detail right now.

**Comment by nojaf** [comment]
@Bobface might need unindent after this expression: https://github.com/fsprojects/fantomas/pull/818/files#diff-a1b0b9a30fd94fe61b35a1a52ce27955R2660

**Comment by Bobface** [comment]
@nojaf That doesn't fix it unfortunately.

**Comment by Bobface** [comment]
@nojaf I am assuming the problem might lie here:

https://github.com/fsprojects/fantomas/blob/4c8aeb8524b5469828654c4fcac068d3244381e5/src/Fantomas/CodePrinter.fs#L1188-L1211

**Comment by nojaf** [comment]
@Bobface I found the problem.
