### ISSUE TITLE
Member return type and equals sign on the wrong line

### ISSUE THREAD

**Issue by Bobface** [fsprojects/fantomas#846]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAyrALaIAqOeAvADoBO1AdhBAM7oCG6AltGCUQCNEtAsUQBZRIOFgAFABtYS5StVr1GzVrUMA5gEY0bWlz0BKOYu3Wbtu%2Br0AmI%2BhPmwLt7rA16TZtSQ7IGQADTgUCyI6Nx6LKhgANoREKDMzJAAJFi4CZCm6GEpGZkAbuzyAK7IaMnp6QAM4fUZAJIMSAzo%2BNjs0IgAcpVERS0QACzFEAC6xQC%2Bzcxp9Vk5NVAFoytlFdUJdWP6iy2QAArsuogA6lzw6AAWWy36jg1TYLPpC8XL6asUeQESnkTxK5Sq6wOLUcxxW%2BCkPFgigYAEF0ABRDoAeQAZgAZUzIWHpHEVKLvT7Mb7pX4lNaA4GgiBZcF7WrvCAAZmJGR6fUQACFEDjYLREOdaOwSOhhEzmK5qhT5rDaczsgC0JAgUi5SzdpCOWBxjzmXz%2BkKRWK8bAAO7CaDsKLtUqwB3cWAMOUQBWIJVfFXvf65TXakE8vUQ-aGgCsJqgZsFwtFiAAqthcLQHU6GC63VwPV6wKT5OSWpSINSloH1cGoKHdTtI%2ByxmAAGxxyAJi3JgDC8kdLB7HuMlWg6FFheLpfq5bAldS1fpIcZ4cbbKShoA7B2u0mxZJpLRJ2TfWXlT9Fxq6yvq6yDS2ABw73rmveIIfI48l08z880y%2B1lqN4nGu95jAAnM%2B-IojiMq0EORBEOwhY%2Bn6VIBiBS7Xjqq53lGLb6E0hqdi%2BiaWog8JEIin5xlOP7pLO85gKqUA1usQE4be%2Br4YcRzEQmMFwZR1EFnGqFnv6F6YVeHFhlxTYbgRMLEe0nToFiDCkLQmA3A8X7Tgxf5VtJgH1rh3HNoc3L8aRKK0LAlQdAAIog8hcFRcEobQioSehUnbFh%2BRdA2eGWc8xrEeI7AAB6tDipD3IgDDot%2B%2BD3KK6A3HcjxxuMby%2BRWGEBTJmzmQpUL1PosaRTF7Q4lw0VYhmnCiui0XYGKLAsPmnpxtG%2BW-pJ-4mexpXyeuFXpPo7Y1dFABKiBwLQ8BZXpuUDYZQ3GcVgFjSBoWKYc26zXZkqYFitAEmwq05YaeVoYV-l-GxeR7dsB2Tcw%2BhPrNeLRAKpjwKYug3YW90FXORXPYFZnjWBzyQZFlTyNwbkMIKijQAA1gKkrY9ELAafgUrvkiwy9YadEPZDT10jJsP7RZh3QkRLaQAMiA2mjiboHaSXkLgLn1QwXDuqiHQHkItDxLRJ7U0xLFBuxDPvUzn0QI4fFswA0ogiDYHFCVJe0xMkAS6P6fRzCMVDdOmcBqvlYajjKWz%2BCuDw6DiAgRKU3LENzBE0yLPkLAAGLdQkVNzEAA)

In the result below are two problems:

1. The return type `: string` and the equals sign `=` have to be on the same line
2. The return type with the equals sign `: string = ` have to be on the same line as the last parameter.

#### Code

```fsharp
type SomeType =
    static member SomeMember (looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong1: string) (looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong2: string) : string =
    "a"
```
            

#### Error

```fsharp
Fantomas was able to format the code but the result appears to be invalid F# code.
Please open an issue.

Formatted result:

type SomeType =
    static member SomeMember (looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong1: string)
                  (looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong2: string)
    : string
    =
    "a"

```
            
#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

**Comment by Bobface** [comment]
Here is where the formatting is applied:
https://github.com/fsprojects/fantomas/blob/5035a1d5b2b341fe8bf2fe26ce28d51bd07e3a2c/src/Fantomas/CodePrinter.fs#L675-L682

The `prefixIsLong = true` branch of the `ifElse` is taken. The formatting is correct if the parameters are defined as a tuple but is wrong in case of multiple separate parameters. The fix is probably to check how the parameters are defined.

**Comment by nojaf** [comment]
Hey @Bobface, the code is not valid anymore so we definitely need to fix that.
However, I'm not sure about:

>The return type : string and the equals sign = have to be on the same line
> The return type with the equals sign : string = have to be on the same line as the last parameter.


```fsharp
type SomeType =
    static member SomeMember 
        (looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong1: string) 
        (looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong2: string) 
        : string 
        =
        "a"
```

This seems to compile just fine so I think we indeed need to format the parameters a bit different if it is not an single tuple.

**Comment by Bobface** [comment]
@nojaf Hmm, it did not compile for me with 
```
...
: string
=
...
```

I will play around with it some more. In the meantime I have opened a draft PR.

**Comment by nojaf** [comment]
I do have an extra indent there, you might not had that when you tried it.
It is further away from the `static` keyword.
