### ISSUE TITLE
MultilineBlockBracketsOnSameColumn not working properly when calling base constructors

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#852]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAyogE4BuxAwgIYB21s6AQogEqIDOsANmfAKIAe0RNnQBLWNTABeADqSIYUdQAWxUejDlYAW20BXaqOiUxEgKrU2e6ELZsAZns4ChI8dTlyFYaogDuABTa7GyUAOaIAJTSXt4KwIoqahpaugZGJu4WVjYhjs6CwqbUQSHhUWAAvpAANOBQbIjoYtRhbKhgANr1EKBxUAAkWLgdkErotT0KkAMklJx6yGjd-RAADHWrUACS1EjU6PjYlEIAcnrak1sALFMQALpTlZvxd4PDS1DjV3EzcwufFarACML36kAACuUAOqieDoZQ-frAgBMazej28zymfV%2BQxwn0gACNYFwkdNZvNFh0gf0UWDfoRtEYuBIAILoXh7ADy9gAMkpkAzvPZ5o0MU8GbjvDMPqMSWThYN-tTlm8IABmJUQSBHE6IJj2WBERBQoiUYLoYjk7zoIiLCVYqVvWUE%2BWkzg25VUwHqsDXbVQPVCQ3GxB82B%2BYjGRq7EiwYzFL0QO0O-qYhTY7zSilytDEj1ev4%2Bml%2BgCsgd1xxDiCNJrM2FwRBjiDjCcyEmTYFFnHF6clOJd%2BJG%2BYVnqVxYBpa2ADZK8GDbWw%2BROJQ7FpLKnoOhjV2e324hmIFnXuDh4Sx0XKVO1VsAOzz6uLuuIACyiG0ROtgf3iEdmedM88ygS8J2vVUuj9AAOR99VDE0tE4TsfzFP9%2BydQcgLdUdCzAlVfS2ABOWChDZewrSIVJtEoLtUzQw8B2zIdgILRUh3w6cQQ2P0qzgpcTSZFkkOoPdUP-Y9ALxFjQPYktbxBUEeIXMiKMEuBhNo%2B16O8I8qkkmVz3dNizw4%2BTkXpHjdn2dBuWoAAVIhMFhBFRN7bSFF0k9emY7CQNw2Sb0grZgS1JSnzZIhYAMeAABFEE4URmQozS0wYjCmKwkcvgOK9TKCkEAx419KH4bZ7Ds1RqF4Nz8GUY10FheFEUDa50XQgDMKk3yxhyvC5Py5EKyKkrdnsUR%2BG5JsTGNARsBNOx3C7Ms2rSjqMq6rKeomPrAtpOJgTnYb%2BFYOAiHgRqXJaladMY08NsJb4dogvbvGBB8joi81MG5IgBTYBq4Uuv1WvEvTOoMljHoC56-WBGCjr5JoGCUeAlDCC7muB66PNu7zMovfyTP6l6FGBYiiqcMQEt8BgkOgABrBhzQZpo2Fs-ALUQRCLhEwM6NBrywBzHVDJw4y8TykmIDRStTn8anF3QKNEHsgk4rGwxijZPZ30-Yh2hQtyBf03Nupkondr9FFFK2SAAGlEGEMqKpV3YOeCAVfFcg8bvSu6IbNwmJeJq2LNt-A7SMdBXwQIU-V-AX6nuF4xjYAAxNhRA6BPKiAA)

**Please describe here fantomas problem you encountered**

#### Code

```fsharp
type ServerCannotBeResolvedException =
    inherit CommunicationUnsuccessfulException

    new(message) =
        { inherit CommunicationUnsuccessfulException(message) }
```
            

#### Result

With MultilineBlockBracketsOnSameColumn disabled:

```fsharp
type ServerCannotBeResolvedException =
    inherit CommunicationUnsuccessfulException

    new(message) =
        { inherit CommunicationUnsuccessfulException(message) }
```

With MultilineBlockBracketsOnSameColumn enabled:
```fsharp
type ServerCannotBeResolvedException =
    inherit CommunicationUnsuccessfulException

    new(message) =
        { inherit CommunicationUnsuccessfulException(message)

        }
```

Expected results (with MultilineBlockBracketsOnSameColumn enabled):

```fsharp
type ServerCannotBeResolvedException =
    inherit CommunicationUnsuccessfulException

    new(message) =
        {
            inherit CommunicationUnsuccessfulException(message)
        }
```

#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| **`MultilineBlockBracketsOnSameColumn`** | **`true`** |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

**Comment by Bobface** [comment]
@nojaf In the tests I can see that sometimes the first element of a record is expected to be on the same line as the opening bracket. For example:
https://github.com/fsprojects/fantomas/blob/694f4c3f700eafed24ecc8554ba8687f145b3b52/src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs#L574-L583

Is this expected? If so, could you clarify in which cases this behaviour is expected?

**Comment by knocte** [comment]
Remembering the github issue that inspired the MultilineBlockBracketsOnSameColumn setting, I'd say that any person that enables this expects always to have things like:

```
StuffHere
    {
        MoreStuffHere...
```

So, with this setting enabled, nothing should be in the same line as the opening/closing braces.

**Comment by nojaf** [comment]
@knocte this is by design. See [unit test](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs#L100) .

In alignment with how [update records work](https://github.com/G-Research/fsharp-formatting-conventions#formatting-copy-and-update-record-expressions).

**Comment by knocte** [comment]
> @knocte this is by design. See unit test .
> In alignment with how update records work.

Those unit tests and the update records cases have more lines. Look at my original testcase, it's just an inherit line, not more lines. If anything, it should put the closing brace in the same line.

So, either this expected result:
```
        {
            inherit CommunicationUnsuccessfulException(message)
        }
```

or this one:

```
        { inherit CommunicationUnsuccessfulException(message) }
```

but not this:
```
        { inherit CommunicationUnsuccessfulException(message)

        }
```

**Comment by nojaf** [comment]
`{ inherit CommunicationUnsuccessfulException(message) }` is 55 characters long so that crosses the boundaries of the `MaxRecordWidth` (40 in your report).
Leading to the current style (where `{` and `inherit` are on the same line.

**Comment by knocte** [comment]
> so that crosses the boundaries of the MaxRecordWidth (40 in your report).

But this is not a record! I use short MaxRecordWidth (in fact I set it to 0 in my project) because I don't like the use of `;` to separate record members, but we're not talking about the same thing here.

> Leading to the current style (where { and inherit are on the same line.

I guess you actually meant `where } is on a separate line`. I don't have much issue with the opening brace so long as I don't see that weird way of ending it. To me, fantomas should behave in a way that a sane developer would behave, a way which could be possible to encode in a code-style guide. But telling anyone to write this...:

```
        { inherit CommunicationUnsuccessfulException(message)

        }
```

...doesn't strike me as something sane at all. I hope you agree that we need to fix it (even if we disagree on the way to fix it).

**Comment by nojaf** [comment]
> But this is not a record! 

It actually is from [AST perspective](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQAuAngA6wwAZVgAnAG5iAwlWTJWXAEKwASulY1J0AKIAPZrD5dErZGAC8AHVGWzEMCgAWYxFzBTWAW08BXZImYqY1MAVWQ0H2YDNDR4Hxo9AyMTZGtbNLsIVAB3AApPdDQqAHNYAEoLDPtqsGAHZGdRV3cvX39A4OQwiKjCuIT9Q078wpLysABfSBAJoA).

![image](https://user-images.githubusercontent.com/2621499/82661522-7abe3000-9c2c-11ea-8ae8-2e6c0feca220.png)

I guess we can add an exception when the `inherit` part is not followed by any record field names that we just go of the single line formatting.

**Comment by Bobface** [comment]
@nojaf How about if we use the Context to check if we are inside a `new` and apply special rules if that's the case?

**Comment by nojaf** [comment]
@Bobface you don't really need the Context here, the information is all available in [the AST](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQAuAngA6wwAZVgAnAG5iAwlWTJWXAEKwASulY1J0AKIAPZrD5dErZGAC8AHVGWzEMCgAWYxFzBTWAW08BXZImYqY1MAVWQ0H2YDNDR4Hxo9AyMTZGtbNLsIVAB3AApPdDQqAHNYAEoLDPtqsGAHZGdRV3cvX39A4OQwiKjCuIT9Q078wpLysABfSBAJoA).

The empty list on line 57 are the record fields I believe (matching [xs here](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L888))
You can do a check over there I think.

**Comment by Bobface** [comment]
@nojaf AFAIK there can also be values declared even when `inherit`-ing:

```
{
    inherit CommunicationUnsuccessfulException(message)
    SomeA = ThingA
    SomeB = ThingB
    ...
}
```

This would be matched as regular record again as the empty list in line 57 would (I believe?) not be empty anymore.

**Comment by nojaf** [comment]
When empty I would go for:
```fsharp
{ inherit CommunicationUnsuccessfulException(message) }
```

when not empty:
```fsharp
{
    inherit CommunicationUnsuccessfulException(message)
    SomeA = ThingA
    SomeB = ThingB
}
```
