### ISSUE TITLE
SpaceBeforeUppercaseInvocation applied in the middle of a invocation chain

### ISSUE THREAD

**Issue by Bobface** [fsprojects/fantomas#853]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAyrOogLLZ5gC8AOgE40B2EEeALmACKxElsAWAS0YBzMAAoAhil6IAKgE8ADogCU1ekxbaw7MAGdiiAGqScWfFTCSAdLJtyho8TUiT3r1TYDaABgC6msw6EIYkpubIADTgUPqIbGzCIvqoYN6xEKAhkAAkbMrIaJDCbJAxObkAbmYWaRkhEL4VjZAAkoxIjGwESpLQiAByWOjlmToALOMQ-uMAvi1Z01D5hWkl3WOVNZH1yxAAjIs6kAAKkiKIAOqC8AJbjQcATL7Ls9oL49knqyrrAEawWA4B7aPI7OpoBqNJ7HMEERDoQRwHCwRgAQTYAFFOgB5ABmABlhNF9mB8WZ4m95sdvmDfkUoIDgaCWODaozoSEAMxwtm9fqIABCiHxsDoiHOdEkfEQdFZ2jYdAs1I%2BtOWeQKf2KzJBfPZuyhZImfIgkAFAxFYolhNgAHc5dBJPEOlVYE6kmiFSwlSqQu8WJ9tHS2QyAUC9Rrqhy9o0wABWU1QC3C0XixAAVSUKjoTpdjDdHsEXqTvsQqsD6sqWsZkF13oNkPSZIAbEnzX1LWmJQBhHDO-Q9tH6X3QNji70QCk4Kn%2BmlfKM18Ms-XRw3NuMAdnbKat6dIiP%2Bcsn5Mp5bnaoX1bWOojDbXTa5OgAHDvO6nrYgh6jGCfp7OdADCAgxYEMzTDW8VyjCFOTJABON9BXRfE2DlId0HQSQTzLCtgKrH4l0gyNthjI04wOZoyQ7QU9wlBEkRREsyX-c9APnYNFxvJk71XGDY0eI4qJTZDULoejkWBJi4xwi9KyvAiuLrHjoNIjdHlhKiOi6NhcUYOQ6AUG57iTFjcLAEClmvbVuKgkj1yfbQDl5IT33ROhYCwTpOEQHBBCRUTsOVVjtCA8z8PpQioFKe8%2BLIx4TSo0hJAADzafFHEQRgsRnRACH4cU2BuO5%2BBPCZXlkvD5IixTot41SHJYA5E0SlKOnxQRktxHNJHHOgsWSpQJX0fRi1-JN43KtjLw4qza1qlT7LJA42xa5KACVEDgOh4CK4zjUmkL2NAzjrI2Mo6sW8jt1WtzpQUXE6GJEddpKpMyrMiywDAlZIrOmL6qW19VsJBIhWEeBkhe0qDpYULPu%2BzVFPrC7HyWhDEtwJJfMYYVUWgABrIVpQJhJ9F0ggZS-YERjG5izw%2B8LQ1%2B5GFtRuMXnbQZEDtbHUzYB1MsUFRvPaxhBE9DFOgPdAjzoVITPpiqwqqpmkeUuy2ZhQS40gABpRBECUNKMsYDoKZIYkcb-RWprkmaFNOlmNdg9mNJ1gglWRNhyCQa2co%2B2J-BaEp9AAMRGtJTLmIA)

Notice the space between `a.Some.Thing` and `("aaa").[0]`. That space makes it a different expression, namely `("aaa").[0]` is interpreted as parameter to `a.Some.Thing`.

#### Code

```fsharp
module SomeModule =
    let DoSomething (a:SomeType) =
        let someValue = a.Some.Thing("aaa").[0]
        someValue
```
            

#### Result

```fsharp
module SomeModule =
    let DoSomething (a: SomeType) =
        let someValue = a.Some.Thing ("aaa").[0]
        someValue

```
            
#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| **`SpaceBeforeUppercaseInvocation`** | **`true`** |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

**Comment by knocte** [comment]
@Bobface not sure I understand; this leads to a compiler error or...?

**Comment by Bobface** [comment]
@knocte Yes. The original is interpreted as (with extra parenthesis):

`let someValue = (a.Some.Thing("aaa")).[0]`

The formatted is interpreted as (with extra parenthesis):

`let someValue = (a.Some.Thing)(("aaa").[0])`

**Comment by Bobface** [comment]
Note: Knocte and I have agreed to fix this on our side by applying parenthesis like this:
```
let someValue = (a.Some.Thing "aaa").[0]
```

**Comment by knocte** [comment]
Yes, otherwise fixing this would break the purpose of SpaceBeforeUppercaseInvocation setting.

**Comment by nojaf** [comment]
I feel like we should still fix this at Fantomas side as well.
Take [this example](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBlWBbRAVAFgJYB2A5gHQBissAFAJTkBCAhgE4A6nxmOALkTLlcsdHzYlSDSABpwUAM6I%2BfSQtRgA2vIigI%2BqABI%2BATwAOyNJBJ9ZO-ZEMA3FgBsArpa32DABjkGBpAAksRIxHzoZizQiABy7lh2gfoALD5gALr2AL4B%2BnqBjqYWGtYRyUXObp4a2ikQAIz5KZAACiykiADqhPAClSmNAEy%2BGdkGefaFQcbmXpAARjSugw7VHl71DcMtReiIWIRwrrDEAIJ8AKJhAPIAZgAyJMh7BvduSuO5ezPrJQtlrBVm8jC5NnUMhAAMygiCQKIxRBMRD3WBsRAdNgsfiINhrAziTzfSa-DLFeZlIEg8kbWpobYpVJwjDRWIotEYx6wADueOgLCUoScsAFqjOBP0RMQJP0UwMf3hc1KVmpksc4Pp3gaYAArCyEWzkaj0YgAKpmCxsAVC4gisWECUs6WyiDygq0gFUlbqulbKFgABsBsR7JNGIAwq5BQoI2cFEToHx0ZKIB9XF8UhM5WTWsrAT7QRqav6dQB2ENGjmmgCyh0WeNTYHTmcC2bduaqXtVhdpmtLDQAHJWkdXI8CnQGWzKsz9pp7KT3gb7%2B5CdQBOEexc73Ph4uNYLAsJsu2ek%2Bd57tQNVFv1rhqNfwBw2j8OIA5HE6TnXT11gd26AuKrXr2eargyAaNM0z6hogO57mwH7HBOxAnmwxJnjmF5douIHLre4Hag%2BuzPqE4R8LcxC4GwJi9AMLK-phHbYbMV5LKBVSEYygSNLCMFGucbCwO4YQACKIK4hBHAhaEYW2c4KkBCw2CuJb3kMzLPjWLAAB7BPcBCIMQVwZu%2B%2BDonwvT9PgTapGMTH-p2rG4eUtgEWpEE6o0%2BpabpoT3IQOm3FaLDJmwVw6WYGIKAojqoSyur2fJ56KZeLkqe5EKeQ%2Bwa%2BTpABKiBwGw8BWfRAZ2X%2BAFgIqRhsRlfYeURQwVnlgnYiYtxsM8CZlTZLKVQ51W1RSwGuapWXNTxw55Y8yhMCQ8CSH1tlJQY7aOSx-wuTejWTdxBiNJuWnuK4qiScQyKnNAADWTDYrdygKJR6A4ogcYeFg8VTp8M7JVhqU4WNu1gU1B36KMBpxIgPIXcafB8kZuDzOJAXEIQ4oXGEdZYA2bDqAxv1VU523AxxsxcQGwzQTqkAANKIIgZj6YZxChK9ODPJdTaMf9zGA85ZP4XtWrgxAwwkbTYgSEmNYIK8P2mVV8iZPk1gKJQsUaL%2BORAA).

We don't add the space in the first line to indeed not break the code.
This feels like a variant of that.
