### ISSUE TITLE
Incorrect end of line added after "("

### ISSUE THREAD

**Issue by michalkovy** [fsprojects/fantomas#855]
This code will get wrongly formatted:

```FSharp
type DeviceNotificationHandler<'Notification, 'CallbackId, 'RegisterInputData, 'RegisterOutputData, 'UnregisterOutputData> private (client: INotifications<'Notification, 'CallbackId, 'RegisterInputData, 'RegisterOutputData, 'UnregisterOutputData>, callbackId: 'CallbackId, validateUnregisterOutputData: 'UnregisterOutputData -> unit) =
    let a = 5
```

**Comment by nojaf** [comment]
This is a poor report I'm afraid.
Why didn't you use our [online tool]( https://fsprojects.github.io/fantomas-tools/#/fantomas/preview) as was asked in the bug template?

**Comment by michalkovy** [comment]
I will recreate

**Comment by nojaf** [comment]
Many thanks! And sorry if I replied a bit too strict here.
I really appreciate you taking the time to report a bug.
It is just with the online tool, we have all the information we need.
