### ISSUE TITLE
Incorrect end of line added after "(" which makes the code not to compile

### ISSUE THREAD

**Issue by michalkovy** [fsprojects/fantomas#856]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAIogG4CW0iAcrOiQGZkCGNsAdgBIMvwA2iATgB4A5FRr1oTEqwA0YIQGEG3bgCMG0ANYBJeLKEAlRAHMSAZ3T8tLbAFd0%2BJgz2GT5-gHk7t%2B470BVFj5jMws%2BT3RvB3QGAD4wbD4SIiY8AApobhJEFnQ0LVE6RmYWU2EC8UkZOUVlNU0dZ2C3PitI3zkXEI8vOyinOQCg11DwtuiY2Qla9W14NAUlVRmGsGTM%2BBTBppGen2j5reHuiN7HMABaOJsWEnQASjAAXgAdPmeWCAhedDAGJ7AAKyvd7AlgAbQEAEEVOY%2BOp0PJuAxTKYANxgADKiCUiHgMQAuqCsLgwAAxDEACwYfGwbEQ3FwfFSDxebw%2Bn3MkmgYAAtogeSp%2BGB9AAFLHocpFKQsABCmBqS00AFEAB6pbiwExTEWJHKWOZgAAymsY3B1JD1LV0oM%2Btrt9odjqd9qmio0aEM5BI2HQ5stdKU6ApGOi6BspnkVJYRlxCplM1k4f4fQAjHkciL0HxpDbnXn8wWwEm%2BH0AEzp31Z2QQ8IEsCuuqzNAqTBBWgCT2Ib2%2B3WhBWNnQxO4exBen1%2B0KGUw2bg-VnvR2i8WSiTFOX9mapABkDeWujAGq1Sgn%2Bsmi0bidMyccKcv1%2BipbukGk4CgV-QNGjplQYDBr4goD2pAAAkxLIGgkAWugz7-p8IFrDY4G-rBtoAAwvo6kBWEgOQYtg6iUDYPIwY6AAsKFgPisEAL4YZ8gF2iBYE-pBOQkYxwEIUhf6OreFEQJAIoMDGADqJDwEG7H2impaoRRVG2rRsEMbaTE4EhkAqLAsDcFJcGcUoiE-jxDqlnRQFYjyZA6awkLoEqXDuLQhoWsg5l2rQShXvJNHuSp%2BnMRBWk6XpAkGdwRloCZ9oAMzuapeEETKiC0LAQRCXCfKhKFnxZohPmKX5FFqbgLHBbp8VQOFkXIWRlUCYl5DJalQTGgA7vwEhXlYRCwKu0o5RAeWIAVnxKba-lhYFUDlTl8GGdx-GAvVUCNYgzVpYgfjYIyXWID1fWVCwg1gJ53DefaCljUVQGgepZXaRVxXVYtjoAGwrZAa0bUEiLIhGrCwjY0DoGlJ1nRddpXRA430c902aY9c0vcZS0AOyfd9KWbQAsvygp8ODXkjZdvnKfD91BUjlXzRFr0OgAHJj%2BFNdjv02cdK0QyTUNkxNFOlVTIU0yjUVLQAnMzBGQrQfawDyPIMCdw2jTDN0cQjs0i1xqO8ehS1fSz61s4glnWRqnNLdzqtgLDAECxpWvPTrYu8XxmFrTLoRm3AFvK3w%2BWk4V5O3Zr1POwtusOjJn3Ydk6DuCwAAqfCYGJklc8TNt22Ak1VWHwsR3TUfSXFBue3wsDXPAhCZFZ2UrSrQfXSHGuU1AUHIy7tXR6Rn04wwKpaLQScUtkSrnabFJpegYkSRSJ2kXJzdq63ql3YLHdsdrkeu9HAL94PVj0Cq7iMkwaWqgkiAogNK0AsvvPB-zoft6x0E78Xe-SR9BsDyqno0rwDnhnJaS9s7q3XgjTun8arRTtCmDGf9B6Qj4HCTA7g%2BAuXMCAheK1wEr1tpAgKb8YFFzgUtFMTNkEqkNIgdAMoLTwAtEYXBi9H62mhkQteJDN6I0Lrdbu8DbQpkln-GcNBMgsHWhqTQMo4SaHoaYROGIGB8nkDpIiltHTW0ITnPOJVHbh0EbvHu9pZKfQoIgNqUjjboA6tkJO6lCD0BuMUSEXA8YCn4N%2BTOk8IE8Kmm-J2Jiv5mLtKWd2DpIAAGlECIGwMPUe2QrCqL5C5aRRN-F6OIUEvhISOJCKWqWMy5csxkHQDjBAbkrZZz0a%2BfEdFIKmFJKYEgP5rbUSAA)

The code won't compile after formatting.

#### Code

```fsharp
type DeviceNotificationHandler<'Notification, 'CallbackId, 'RegisterInputData, 'RegisterOutputData, 'UnregisterOutputData> private (client: INotifications<'Notification, 'CallbackId, 'RegisterInputData, 'RegisterOutputData, 'UnregisterOutputData>, callbackId: 'CallbackId, validateUnregisterOutputData: 'UnregisterOutputData -> unit) =
    let a = 5

[<AbstractClass; Sealed>]
type FSharpHelper() =
    static member RPSetNotificationByCallbackEx(logicalPrinterId: LogicalPrinterId,
                                                callback: ReceiptPrinterHealthStatusChangedCallBack, userData1: IntPtr,
                                                userData2: IntPtr, [<Out>] callbackId: byref<ReceiptPrinterCallbackId>): ReceiptPrinterResult =
        RPSetNotificationByCallback(&callbackId, logicalPrinterId, callback, userData1, userData2)
```
            

#### Result

```fsharp
type DeviceNotificationHandler<'Notification, 'CallbackId, 'RegisterInputData, 'RegisterOutputData, 'UnregisterOutputData> private (
    client: INotifications<'Notification, 'CallbackId, 'RegisterInputData, 'RegisterOutputData, 'UnregisterOutputData>,
    callbackId: 'CallbackId,
    validateUnregisterOutputData: 'UnregisterOutputData -> unit)
    =
    let a = 5

[<AbstractClass; Sealed>]
type FSharpHelper() =
    static member RPSetNotificationByCallbackEx(
        logicalPrinterId: LogicalPrinterId,
        callback: ReceiptPrinterHealthStatusChangedCallBack,
        userData1: IntPtr,
        userData2: IntPtr,
        [<Out>] callbackId: byref<ReceiptPrinterCallbackId>)
        : ReceiptPrinterResult
        =
        RPSetNotificationByCallback(&callbackId, logicalPrinterId, callback, userData1, userData2)

```
            
#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Would it be possible to also share the code of the `INotifications` definition?
I believe we need to take the access modifier (private in this case) into account when we format into the long format.

Does it compile when you write it like:
```fsharp
type DeviceNotificationHandler<'Notification, 'CallbackId, 'RegisterInputData, 'RegisterOutputData, 'UnregisterOutputData> 
    private (client: INotifications<'Notification, 'CallbackId, 'RegisterInputData, 'RegisterOutputData, 'UnregisterOutputData>,
    callbackId: 'CallbackId,
    validateUnregisterOutputData: 'UnregisterOutputData -> unit)
    =
    let a = 5
```
