### ISSUE TITLE
Add unit tests/performance tests.

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/fantomas#867]
Im finding that formatting takes ~4 seconds for an 800 line file it would be great to know the areas that are slowing things down so this could be improved.  Im finding myself not wanting to use fantomas as I know I have to wait every time I use it.  Similar tools in Elm,Go or Rust are instantaneous and it would be great to know where to aim improvements in this library.

**Comment by nojaf** [comment]
Hey @7sharp9, yes Fantomas isn't that fast when the files become larger.
I'm don't really have a lot of expertise in finding this kind of issues so I'm open for suggestions here.

**Comment by 7sharp9** [comment]
I was surprised the 800 lines took 4 seconds, most formatter don't have a perceivable latency.  Benchmark.net is good for analysing but the functions that comprise fantomas would have to be tested in sections to see which parts are slow.

**Comment by jindraivanek** [comment]
Biggest performance issue right now is Trivia collecting and querying. https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/Trivia.fs

**Comment by 7sharp9** [comment]
```
    let triviaNodesFromAST =
        flattenNodeToList node
        |> filterNodes
        |> List.map mapNodeToTriviaNode
        |> List.choose id
```
The filter, map, choose  can be combined to avoid extra iterations, as choose is the map+filter optimisation.  Not sure if thats a slow bit though :-)

**Comment by jindraivanek** [comment]
Slowest thing is probably that we use `list` to store `TriviaNode`s, and go through this list for every Triva query. Change it to something like `dict<LineNumber, TriviaNode list>` could be big perf win. Something more sophisticated like [Segment tree](https://en.wikipedia.org/wiki/Segment_tree) may be better, but maybe it is overkill.

**Comment by 7sharp9** [comment]
First thing I guess is to get a baseline with benchmark.net

**Comment by nojaf** [comment]
Ok, I'll try to set up a baseline with benchmark.net.

**Comment by gerardtoconnor** [comment]
If performance is a concern, you should restructure using of list piping in all the private query functions and potentially use an optimised tree structure as suggested already. Using streaming source/sink pattern is more performant but cannot use compiler hack on list creation head first

**Comment by gerardtoconnor** [comment]
Profiling with Perfview will show where time is being spent, what is allocating heavily, just collect, run, stop and find process in profile export

**Comment by 7sharp9** [comment]
Isn't preview a windows tool?  I mean, who uses windows?

**Comment by gerardtoconnor** [comment]
:joy: I do, it was that or a MBP :mask: :stuck_out_tongue_winking_eye:

**Comment by nojaf** [comment]
@7sharp9 could you share that example file of 800 lines you talked about?
I'd like to have some more insights in your particular case.
Are we talking about regular formatting here or generating code based on AST nodes?

**Comment by nojaf** [comment]
Just letting you know that we are on the right track here:
![image](https://user-images.githubusercontent.com/2621499/83967072-a133ca80-a8be-11ea-8524-42ffd3e4f368.png)
