### ISSUE TITLE
Pipe before and inside lambda leads to wrong indent of following lambda

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#870]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEA2iAuYAOATrAFaLTYCSAdtrALICGe%2BRp5AlrFWALwA6BPtwhgAZgFduAZ2wNsiMIgBuiGgFEqKjLDwKAtAD4BQkSJlzEx4aYA%2BBsIzwA6bAQCeAMXZV4iles1EbV0nOhwGeDkGJwBlWHECaEtBaxE7MAB5PGxOKickUQZxDGwANQYMcQVCEjIcridqdmwrUwh0iW4atnqqGNl5MEM-VWwNLR1EJzV-XHTuutynAFU8SMGFji5%2Bi1a2jskwKkQAdx3B4fNB9McnCN9lUfGgydDw9ei4hKSj0-PkoRWLC4TaUGj0JgsWpbbj8FIQTpgK4KR4BCa6IZGeFmAYA1I3JgudxeHwjNEvEJhWQfWLxRJ42z2LK9fKIQrFMoVKpQnpLJotbHteyI0G5f6YvamVFjQLBKYzUaStL2UUNVbraqsRbbXFKg7cY5nXESwU43amoUOQn3Mky9FTKkRKK074KQ3-SAAGnAUCkOByVAA5lJUGAANo%2BiCgNpQAAk2DculDkG82C9kZEkFjSi5yDQEZjEAADN7C1BqEgaDE8AwkgA5cQAW3TZYATBmIABdDMAX1LImjbSzCaTaBTNBbQ%2BzudDBcLAEZ%2BzHIAAFBiBxAAdXY8GwAAtJzH562ix2wN3TH2M4PTMPE3moAAjWCwDCHzPTyoPucx1tLocxIgjbsHA2hUAAgjK8AZKIAAy3jIP%2BpiFBgfpnheIhXqYN4fiOD6QM%2Br7vhAWY5l%2Bs5nhAADMSGZtWtaIAAQmysAEIga4EAwjY4IgBDESIrhVOhvb-jhJHxveyaEW%2BtGkTO%2BaUWAAAstEkfRSTMaIrGILBsAnLx0AMH61BKLAhm9PxECCYgwmXqJZ53qOT4vjJDmflUFFlgArKpUDqUxLFsasuiJEZiAmWZci5JZYDWbZmH2cuElOQRLn8XJ5EKWWABsvmQP5mnaQAwhgRlSEVXAyAQ4jkKxMUoWhMYYRAWEDm5eFSWlsnud%2BikAOx5QVgWIGEjaPrx9UVI1bTNWArVRu1kljtJ6U9Z5hYAByDTWGnDRVYExXFTUidei0pSt3VkR5WWFgAnNtDHgaI8gEBVjaNgwk2oTZx12adSUdctXVuVdvVlvOJaKflO0BVpbGAcBoFcF902mLN81gGJcaA85RGXfJ4aKfOi5Q-5T0vQjIGvsjvlHTNJ3YWd%2BEXSDBM-m0x55RWowZFQAAq7jbvuKM-fTf2MwDS2465SWg%2BtR40aTMPgUQkjwAAIkE7DAS9IvxS1iVTjj45pvjmWE%2BDKlQ4wAAeFCiHze6qGo30xHurHYNuu4Hr5Smnr9CX-UbUsm6tcs3UePnWwwdtUKI7A21kvFyKxag24QiBSFI0W%2B-7YuBxLwcpamYds0TuXRzbABKZCsfAXvC7n%2BtzYbt7JfhJdm9dFsLgNlcq5xbgZAQ8EyA3PuKX7zcY1jjkdxOXdgwuW2V7BOCMd48DeIG48xdledowzbWS%2BdwOy2X4P3dbHLsBgCGMdo0AANaMZxz84FIvMxFxiD7U2VCHWqqLQ%2B4tj5F2ZmfKc4ce6-khmWSAdZTh32OMxbA%2BlVB83vJreOVBmi5HAj4Ua40CAhl8g1YBIh0at1wiHFm59zbs1MK2Em8CADSiBEB4Hto7VQ1Bv7cXgscPWAcDZBzbsbOhUCL6FlbH%2BUmrgQLYDoAgRCilyHTx9J2fsKYpAeGzqGdRPYgA)

```fsharp
      |> fun newState ->
        state
        |> Map.add eventEnvelope.Metadata.Source newState
```
is indented at the same level as ` |> projection.Update projectionState`, this probably has no impact on the code in this case but the result should produce twice the same output.

#### Code

```fsharp
  let projectIntoMap projection =
    fun state eventEnvelope ->
      state
      |> Map.tryFind eventEnvelope.Metadata.Source
      |> Option.defaultValue projection.Init
      |> fun projectionState -> eventEnvelope.Event |> projection.Update projectionState
      |> fun newState -> state |> Map.add eventEnvelope.Metadata.Source newState

let projectIntoMap projection =
  fun state eventEnvelope ->
    state
    |> Map.tryFind eventEnvelope.Metadata.Source
    |> Option.defaultValue projection.Init
    |> fun projectionState ->
      eventEnvelope.Event
      |> projection.Update projectionState
    |> fun newState ->
      state
      |> Map.add eventEnvelope.Metadata.Source newState
```
            

#### Result

```fsharp
let projectIntoMap projection =
  fun state eventEnvelope ->
    state
    |> Map.tryFind eventEnvelope.Metadata.Source
    |> Option.defaultValue projection.Init
    |> fun projectionState ->
      eventEnvelope.Event
      |> projection.Update projectionState
    |> fun newState ->
      state
      |> Map.add eventEnvelope.Metadata.Source newState

let projectIntoMap projection =
  fun state eventEnvelope ->
    state
    |> Map.tryFind eventEnvelope.Metadata.Source
    |> Option.defaultValue projection.Init
    |> fun projectionState ->
      eventEnvelope.Event
      |> projection.Update projectionState
      |> fun newState ->
        state
        |> Map.add eventEnvelope.Metadata.Source newState

```
            
#### Options

Fantomas Master at 5/25/2020

| Name | Value |
| ---- | ----- |
| **`IndentSpaceNum`** | **`2`** |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| **`SpaceBeforeUppercaseInvocation`** | **`true`** |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| **`SpaceBeforeColon`** | **`true`** |
| **`SpaceAfterComma`** | **`false`** |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| **`SpaceAroundDelimiter`** | **`false`** |
| `MaxIfThenElseShortWidth` | `40` |
| **`MaxInfixOperatorExpression`** | **`40`** |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| **`MaxLetBindingWidth`** | **`60`** |
| **`MultilineBlockBracketsOnSameColumn`** | **`true`** |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
@jindraivanek I think we can solve this by doing some extra check in [InfixApps](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/SourceParser.fs#L707).
But it is a quite challenging to detect 😅.
Any ideas?

**Comment by jindraivanek** [comment]
Key thing here is 2-space indent. With 4-space indent it works as [expected](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEA2iAuYAOATrAFaLTYCSAdtrALICGe%2BRp5AlrFWALwA6BPtwhgAZgFduAZ2wNsiMIgBuiGgFEqKjLDwKAtAD4BQkSJlzEx4aYA%2BBsIzwA6bAQCeAMXZV4iles1EbV0nOhwGeDkGJwBlWHECaEtBaxE7MAB5PGxOKickUQZxDGwANQYMcQVCEjIcridqdmwrUwh0iW4atnqqGNl5MEM-VWwNLR1EJzV-XHTuutynAFU8SMGFji5%2Bi1a2jskwKkQAdx3B4fNB9McnCN9lUfGgydDw9ei4hKSj0-PkoRWLC4TaUGj0JgsWpbbj8FKmTpgK4KR4BCa6IZGeFtCDIvY4m5MFzuLw%2BEZol4hMKyD6xeKJAGpWz2LK9fKIQrFMoVKpQnpLJotbEE%2ByI0G5f6Y-E4kSosaBYJTGajaUysDzViLBqrdbVTUw-6qtKiw7HM4DfRYkxqswWo0ihxE%2B7k%2BXoqbUiJROnfBRm-6QAA04CgUhwOSoAHMpKgwABtYMQUA4yAAEmwbl0Mcg3mwgYTIlTSh5yDQ8bVAAYg2rINQkDQYngGEkAHLiAC2ebVABZ8xAALr5gC%2BVZESbaqfTmbQ2ZonfHKaLlRLcd7IgAjCPkwAFBgRxAAdXY8GwAAs5zi1wAmcurgemYf5semCcZ5eQABGsFgGHPBYXxZjMsZUvTdxxiRA23YOBtCoABBeV4AyUQABlvGQUCEQqUNbyHUCnz-Sc30-b9fwgQsANLVcIAAZgwgsGybRAACEOVgAhEB3AgGDbHBEAIUiRFcKocPvPDVxfKcoGIn86PIpdAKosAuzosiGKSFjRDYxBkNgE4%2BOgBhQ2oJRYAM3oBIgITEBEkQH1MfCyLTV8s2kgS5KqBS1QAVhUqA1OY1j2NWXREkMxBjNMuRcgssQsOsnE71ssTkycySPy-GTxP-eTKLVAA2XzIH8jStIAYQwQypFKrgZAIcRyDYmLCgwbCEtwx8ssIlyMrc7KPNymUAHZCuKwLEDCNt3z4pq4psiA7NHTrnOnVzZL65cgJxAAOEbG3UsbqpgmaWvitpEvm5L5y6laerWxd%2BpXNUAE5dsY2DRHkAhqrbNsGBiqy5rABbEyWtLVqy%2B6NsUtdK0Uoq9oCzT2PAyDoK4Y7WrO9r7NBojbohijHplNcNzh-z3s%2BlGoO-dHfIBtrRI6lLrqk-GUshzziZAuHa1GDIqAAFXcQ9Twx07THOoHLufVK8ZIu7Cc2to11osmEdgohJHgAARIJ2Egz7-rq8WREl4GwAcqBZazHNeo5gaL2UuHGAADwoUQBZPVQ1BOmITzY7BD2PM9fK7G8GaSpmruWqBbYVnKiYvHznYYN2qFEdgXayPi5DYtQXcIRApCkaLfK88OscZnHmZjmdc3jh6ldMNcCpTl2ACUyDY%2BAg9F0OK4l7HFprtK44JhOm-XYa241ri3AyAhUJkXuQ8UsPAfNy2JLfMf2cV6Gdrb5CcCY7x4G8CMV5i9eI4uqOZZZ9L5fHxvoZe52uXYDA0KY7RoAAayYlxABOApD8xiNxRAh12xUDFhvaWBFa7gz3hPRS15CrNlON-Y4LFsB6VUALV8usM5UGaLkWCPgJpTQINGXyzVMaDyrsPaOYM2bzntonNol5SbVgANKIEQHgd2ntVDUAgTxVCxw4G3ylvfRBrDn4oNfmqS83Nqz9AIFBbAdAEDoUUvQk2-YhzBj7CObMUgPAlxjAYkAg4gA).

Problem with 2-space is that block need to be indented farther than `fun`.

This
```
let projectIntoMap projection =
  fun state eventEnvelope ->
    state
    |> Map.tryFind eventEnvelope.Metadata.Source
    |> Option.defaultValue projection.Init
    |> fun projectionState ->
      eventEnvelope.Event
      |> projection.Update projectionState
    |> fun newState ->
      state
      |> Map.add eventEnvelope.Metadata.Source newState
```

is actually
```
let projectIntoMap projection =
  fun state eventEnvelope ->
    state
    |> Map.tryFind eventEnvelope.Metadata.Source
    |> Option.defaultValue projection.Init
    |> fun projectionState ->
    eventEnvelope.Event
    |> projection.Update projectionState
    |> fun newState -> 
    state
    |> Map.add eventEnvelope.Metadata.Source newState
```

Same problem with 3-space

**Comment by nojaf** [comment]
@jindraivanek thanks, great catch.
Maybe we can further indent lambda's if we know that there are infix operators involved?
Or add parenthesis?

**Comment by jindraivanek** [comment]
Maybe add `atCurrentColumn` after `fun ` in lambda?

https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L1053
