### ISSUE TITLE
Incorrect formatting for chained class members using Websharper

### ISSUE THREAD

**Issue by baronfel** [fsprojects/fantomas#871]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwAZWAcwEt0B1agFwAsAhAVwBttMAVdxrABO1TJwA6Q8eknTYBROjABlAJ55GibLPTzFYOogBGy5piEKpU3QqWGTZi4iEA6AFKYAbpmXQRBRh09O2NTc0t3AEV2Z1Ug2wNQxwiAVQBJeP17MKdXdJcAYU5qRUDrYMSHcOcXfIA5WEZMRmpYGXKE7OSa-N4tAk5m2kodHQBtAB4Pb19-RgA%2BAF0dbAQuUiKS9EYwAF4dCAgAeiOwXmZSTWwB5vwwc1JOWEwkeDAAMyFYbDAWUgARADyAFkADRgPCwMCqWDsMAAK3YGjA0EwSkQ8CYYFoSAAHi5mIxsBJrIcwCd7ug3kJEJ98MxobChGAjF8AO54Zzg3RgdCIDG-KE0uDXaicUjsdDivB4Rlwl5vYRgGmrTykZiwaUuA6HRiqBRgYGqZQABQAgnszv1BpoJuJIGzHV9GkccYh8YTifbwZtShQXi4AGJfbD-WDQdi4bbzUakw6TU1mgCi2yEqhNsFoC2WcYg4p2wMwtDAAAoAJR7HVkvOIHZEGVs4TwABqYmob12YFbrgKNNuvyEMSr1fzYC0Rc4reKHa75kKfc0A6H1mHZKNifLq%2BrEBcZsYjCEJswDabJb3B8KgxlJppb3t1DwAFp4GjKM57aXdHXj3hG0IW228AuM2ZZllu267vuQhJjwYpnlBl4-jeAr3k%2BL7oG%2BUiQJ%2BjRjrBk6AcBoHgdWLgUDQ6Alu8kpjmAj4xrm25MWS9a-k2U7tiRzFkignZfqWygHsMLhpHgdRcJwgJCHQzBMIgyhECQY7AeYeAuEeJ7-ipnAxGBjHcUx45ihx8BcQZYC8byuEloJIgYSJYkSVJMlyQpxCkIgKlCGpMETtpumxtI5ncdQ7xgKxf4AdO-mkAAZLFeETiZMVmQZfxKG4yi7uKQiMCWhB2YwYX2gAmkyiVitisoAKR4B%2Bnndj5%2BExXpQXBYZLhJmq2zqTS3WMP8tKYFweWtUo5ljcFLisDi5aQKC4BQJy%2B7DHgqBgGMi0QKA26QAAJHqCjrZAWbzVthz7d4OnIGgm3MQADAtzGQGkVKlG5JDidgZ3MQALOdECLOdAC%2BT2HDt1b7YdN1QKdYNkpdYgxOtd1MQAjPDkNHm%2BDDwCwP3owATPdANgEDZKg%2BdEMIwd%2Bow5ARiwJqBM01dyO3aTECE5jCPKFo1BwE86B7im8CAu8ZC0MgPOHO8YicqT5OHJTZLUxdtNHWgDNM5wLPq2zMOo9uADMMsQJAH2IKwtLCIgR5CDgtbOHrZIHjEisg5javmxr9OM8zMuI9dKOc2Av1m1AlvW%2B8tsUGyziopyr2eOGQxtC7uqDogHsU17pNQ3Tx3%2B7rgd7QbIfMQArBHFuKVbNs0ikBCWIniDJ6nLTpxHcucAr25KxAKvg-nvtFzrGdB%2BzG2hwAbDXUcN4gRQ-gUbQaIO0CCEIGcQD3ffVgPYBD9tI-Q2PAcj%2BXHPMQA7PPdfR7bwJaEYzvd-L2f957VOn4XWvFxPMuSNDahwABz33co-Gkq8hY7w%2BB-HOys867VHv-cepcr7T2YgATggSQM07xNBCFXtgHgcC3afwPt-VWv9NZQAARg4BFd0aPVDrXSBi8%2BbYAFpqLuoc96ULJIfY%2BYBvZQFQfQ9Bl8mHX3RhjNhlsCFEK4Tw2BEcKGIMHsgyGEjtYXxQZgo21Y0bczYa9JA2xAToF4GmBg%2BN3690EYcYR2iaZnzQfonRhjQ5o1NgouuZoviSngINYo3CiHkKzpoo%2Brj1buNhtsQB3jmJo3DmwwsuI0jvHOIoJMjjTDCEYLjexodfoky-rnH%2BKD4knUSYw4Osjtxo2rukzAmT0DvGoLiQElhmjCCTLiAgNIZStHQHAyu5SqGVJodUv%2BCTGBJJkVg9Gc9Wm4gAEqIDgP%2BYpzA4FlOiSIsRBc6G1IWfUqeRiyRozvmswJDtVBSUlhoXZ%2BzJlCOocPWZpy4bSIacspp4C1lkFrDNKkwxXkRwORUpBVSdE1IYX8y5PjcHpJGmKKWrAnjQAANasAdri2seArHKEdjAyMYyHH7w%2BdMr58K5l6JLkikBzFiY1zqIgNkxQ%2BTW0YPHRQvA6aDU6egJgoyzRUmftgV%2B3k4ECMObEn2CKpEGKWVcw4hN5HPQANL8gIFknJ6BXqktwJLPkcqEEwq0XCtxDLEWqv%2Beqrmpjnq2QFowYECBpb8MtVM5Wi1FhgxOngQMeBqDrXlcDIAA)

**Please describe here fantomas problem you encountered**

This was reported in https://github.com/ionide/ionide-vscode-fsharp/issues/1372, and I've reproduced it here with the associated fantomas-online link.

The issue seems to be the indent level of the class-members chained, the indent level of `AttrPassword` is further in than `AttrEmail`.

#### Code

```fsharp
namespace LoginWithBulmaTutorial

open System
open WebSharper
open WebSharper.JavaScript
open WebSharper.JQuery
open WebSharper.UI
open WebSharper.UI.Client
open WebSharper.UI.Notation
open WebSharper.UI.Templating

[<JavaScript>]
module Client =
    // The templates are loaded from the DOM, so you just can edit index.html
    // and refresh your browser, no need to recompile unless you add or remove holes.
    type MySPA = Template<"wwwroot/index.html", ClientLoad.FromDocument>

    [<SPAEntryPoint>]
    let Main () =
        let passwordValid = Var.Create true
        let emailValid = Var.Create true

        MySPA()
            .AttrPassword(Attr.ClassPred "is-danger" (not passwordValid.V))
            .AttrEmail(Attr.ClassPred "is-danger" (not emailValid.V))
            .Login(fun e ->
                    passwordValid
                    := not (String.IsNullOrWhiteSpace e.Vars.Password.Value)
                    emailValid
                    := not (String.IsNullOrWhiteSpace e.Vars.Email.Value)

                    if passwordValid.Value && emailValid.Value
                    then JS.Alert(sprintf "Your email is %s" e.Vars.Email.Value)
                    e.Event.PreventDefault()
            )
            .Bind()
```
            

#### Error

```fsharp
Fantomas was able to format the code but the result appears to be invalid F# code.
Please open an issue.

Formatted result:

namespace LoginWithBulmaTutorial

open System
open WebSharper
open WebSharper.JavaScript
open WebSharper.JQuery
open WebSharper.UI
open WebSharper.UI.Client
open WebSharper.UI.Notation
open WebSharper.UI.Templating

[<JavaScript>]
module Client =
    // The templates are loaded from the DOM, so you just can edit index.html
    // and refresh your browser, no need to recompile unless you add or remove holes.
    type MySPA = Template<"wwwroot/index.html", ClientLoad.FromDocument>

    [<SPAEntryPoint>]
    let Main () =
        let passwordValid = Var.Create true
        let emailValid = Var.Create true

        MySPA().AttrPassword(Attr.ClassPred "is-danger" (not passwordValid.V))
            .AttrEmail(Attr.ClassPred "is-danger" (not emailValid.V))
            .Login
                (fun e ->
                    passwordValid
                    := not (String.IsNullOrWhiteSpace e.Vars.Password.Value)
                    emailValid
                    := not (String.IsNullOrWhiteSpace e.Vars.Email.Value)

                    if passwordValid.Value && emailValid.Value
                    then JS.Alert(sprintf "Your email is %s" e.Vars.Email.Value)
                    e.Event.PreventDefault()).Bind()

```
            
#### Options

Fantomas Master at 05/27/2020 09:30:01 - 9df884b6e117016e2ee514557d6d6a29b104139f

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Problem here is the 
```fsharp
            .Login
                (fun e ->
```
It should be `.Login(fun e ->` to be valid AST.
