### ISSUE TITLE
Leading `|` in single-case union type with access modifier

### ISSUE THREAD

**Issue by iblazhko** [fsprojects/fantomas#889]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKsAOiB2YDKAngM4AuiAtgDrbUkFb4kBOAltgOYCsADGALxgMrAG4BDMo1YceYWADMwpKe0gAacFCKISJNuyKowAbQ0RQEC1AAkdLIchsSa0xchWxAGwCuyNCcuW3OoBrgCS2EjYJHgYotCIAHJe5M4hEAAsLhAAui4AvsEW5gFutr5Qjqkl7qLe5f5pAIyFIZAACqLsiADqLPAkABZVIY0ATNxZYLmWBS7FlqX05ZAARrCwHsOuNXWGDSGjLSV4FCxwHrDYAIIkAKIRAPJyADJsyEeWcrVak9MWs5Z5tsyvY1hsthA3J4fHtJhAAMwfVwxOKIABCiDksCYiA6TFE5G0iCYEIszB8v3yRyBkJsS1B602SKhtRhfjhYHSSMhKPiGKxOOesAA7sToKItOFhLBxbpLqSIOTEJSZtTJos7GhVozSSzduy0mBONyoLz0ZjsYgAKoYLBMcWS7DS2UseUmr4eH4hP4QAFFdV0zVQMFMgPQ%2BocgBsJsgZv5loAwh4JUQE5clF5oCRsQqwB6vQEfWA-WYAyCtSHdTs2cYOQB2GNxi04gCyFBWxNz%2BeV3qpczL9IrOuZ1YjhoAHI3Ynzm4g0xdsF3vj3C33AQOg9rwSPw7DDQBOKeoq5yMhMNPkciiXNKlX-NWtQPLSs71ljppBDmx6fmgWIE7kGcGxuhy3Z3r6D7VOWwbDmGb57k0zRfmaJ5ngBQELjeTAUr2qr9o%2B0FbqGj67gaTSHF%2B4SRCQDzYAAKkwBC9IMS6eiulhFiWYA0tYhEvnB%2Bq1oajSIshP5XEwsBeBEAAiiAeCwgFnlhOGrnh64EYOFRRFWpFCU0XJfi2ogAB6hHIdEDDgtxsXgAzYiQvT9EMJrpBMuH3vhUFaQ4OmvoJ%2BwBI0xpGaZ4RyCwJkPHa4jYrcJlCIgRBEK6i4mjw4HFpBCxPvYlT%2BTWgWWI00ahSZABKiBwEw8BOSxrnuWpnkad5m75QJhUco0DZlRJ%2BIEA8TCvKQdUuRybmZVxPEass7UkfBZEjJOZXPNoaJsPAeijbmE0eRBXk5XxsHzQFXWHkZXgeLoCnYOiFzQAA1mi%2BKPdoRC0XgBJzhsyRpaBy6TdlwI%2BfxJ2dYa4wxgkiDCjd5okKKOB0UsckRdgLBytcERtuQHZMAY7oA3tWUHcDm6g9UelFRYoxIYakAANKIIgGDmZZODhJ9hKvLdrEFhxa7%2Bpp5PHZTC36QcFH03gzBnCQLYIO8HK3sTeQaNkhQOEQABiKWGGBeRAA)

Single case union type with access modifier has leading `|` after formatting.
I do not see an option to suppress that. For the example below I expect the formatted output to be the same as the input.

If I remove `private` access modifier, there is no leading `|` in the output. 

#### Code

```fsharp
open System

type String50 = private String50 of string
```

#### Result

```fsharp
open System

type String50 = private | String50 of string
```

#### Options

Fantomas Master at 06/02/2020 18:39:46 - eee0f3278301dba9302a30d1888e78e602b6950a

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| **`StrictMode`** | **`true`** |

**Comment by nojaf** [comment]
Hmm, this is related to https://github.com/fsprojects/fantomas/issues/561.
There the pipe was necessary, here we might be able to drop the pipe because of the `of string` part.

**Comment by nojaf** [comment]
@iblazhko could I persuade you to give this a shot yourself?
The [AST](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWSsAOsyYAZQCeaAC6wAtgB0ATlOSz5oob0GiZKAOYBWAAxgAvGG4aAblXFqNyHftbwwY65sggAvkA) indicates that there are fields in the union case.

So I think the check of [hasVerticalBar](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L1929) can be simplified and should not take access modifiers into account.

If you watch this [video](https://www.youtube.com/watch?v=UFUOYc22rkk&list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K&index=2&t=0s) you will get an idea of how to get your feet wet in the code base.
