### ISSUE TITLE
Plugin AST modification?

### ISSUE THREAD

**Issue by Thorium** [fsprojects/fantomas#893]
Would Fantomas to be open for AST-processing?
I'm kind of open to any solutions to [Expression visitor in FSharp.Compiler.Service](https://github.com/fsharp/FSharp.Compiler.Service/issues/938), but in similar issues [Don has referred possible solution place](https://github.com/fsharp/fslang-suggestions/issues/871#issuecomment-635942019) to be first in Fantomas.

Is Fantomas OK to expose the types used for syntax trees?
For example SynExpr seems not to be internal.
Would it be enough to solve the issues?
1. To user be able to parse existing ASTs to collect data (and custom ASTs).
2. And also push the modified AST back to get the F# source code. So not (AST-> Unit), but (AST -> AST).
3. ...and maybe even generate F# code from custom ASTs.

**Comment by jindraivanek** [comment]
I think this is exactly what [Myriad](https://github.com/MoiraeSoftware/myriad) project is doing - AST->AST transformation, then use Fantomas to output source code.

Also note that Fantomas and Myriad use AST, but example in link (`BasicPatterns.*`) is for TAST.

**Comment by nojaf** [comment]
I think, in general, this might be more relevant for the [FsAST project](https://github.com/ionide/FsAst).
> Is Fantomas OK to expose the types used for syntax trees?

Fantomas uses everything that is part of the [FSharp.Compiler.SyntaxTree](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-syntaxtree.html) module from the FCS.
So I'm not really sure what you mean here.

> Don has referred possible solution place to be first in Fantomas.

That language suggestion where Don mentions Fantomas, is about AST -> string.
Which is something we have right now in our [public API](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodeFormatter.fsi#L15).

> Would Fantomas to be open for AST-processing?

I'd prefer to keep Fantomas the `AST -> string` and `(string -> AST) >> (AST -> string)` solution to be honest. Other projects do other stuff with AST as well, I feel like your suggestion might be better suited over there.

**Comment by Thorium** [comment]
How hard would it be for anyone to do a [ReSharper for F#](https://github.com/JetBrains/fsharp-support/tree/net202/ReSharper.FSharp/src)
but instead of OO-refactorings, focus on functional programming? (For example [these](https://www.slideshare.net/thorium/possible-fsharp-refactorings-could-be).)

The interesting part is the AST optimization [(some AST-optimizer sample here)](https://github.com/Thorium/Linq.Expression.Optimizer/blob/master/src/Code/ExpressionOptimizer.fs) but before that, we'd need a common (AST -> AST) transformation tool, and "AST back to code printer" tool.

Then use [F# Analyzers SDK](https://github.com/ionide/FSharp.Analyzers.SDK) for VS Code and fix a [corresponding VS2017/2019 solution](http://www.fssnip.net/7SQ/title/Visual-Studio-2017-extension-Displaying-Light-Bulb-Suggestions-) for the editor IDE suggestions.

But turns out it cannot be done quickly, these existing projects don't yet play well together.

**Comment by nojaf** [comment]
I'm going to close this as we don't wish to pursue this with Fantomas.
