### ISSUE TITLE
RFC: self/this/xxx consistency?

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#904]
Just wanted to ask if this is a worthy goal for fantomas?

First: I'm not sure if MS style guidelines recommend a specific word? Is it `this` to make code more similar to C#?

Maybe it's just good enough to keep this under a setting? i.e. in case the guidelines don't say anything about this, let fantomas not change anything but allow adjusting the consistency with a "string"-typed setting named `EnforceNonStaticThisName` or something like that?

**Comment by nojaf** [comment]
I would prefer not to have these kind of things in Fantomas.
It is dangerous for Fantomas to modify existing source code as we have no idea what the code does.

Extreme example:
```fsharp
let this = 8

type Foo() =
    member bar.DoSomething(a:int):int =
        let bar = 4
        a + bar + this

Foo().DoSomething(1)
|> printfn "%A"
```

after replacement:
```fsharp
let this = 8

type Foo() =
    member this.DoSomething(a:int):int =
        let this = 4
        a + this + this

Foo().DoSomething(1)
|> printfn "%A"
```

The result would be different and we would have broken the code.
I think your suggestion might be useful in a tool like FSharpLint or as a code refactoring suggestion in an editor.

**Comment by knocte** [comment]
Good point, then this might be a candidate for a subtask for the "Resharper for F#" wishlist: https://github.com/fsprojects/fantomas/issues/893
