### ISSUE TITLE
Shouldn't break line in two (match pattern) unnecessarily

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#905]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAwgIbQAWAlgHYDmYAvADqUQQAuAngA74CyRVxMogAUASnpMWUsOkToARogBOYTkvIA3Iq3wB9XQDoAyq1hLEAFSVFKAZxKtysSgCVEcJfDDCi8eOdtbNAAFLHkccmgAQT8A21FJaSTklNS0lmFoLCVzSmh2NAJs3PyE5nSKyorhVgAPAEl4NFtWdRoyqs6uqR9MLEpWNCRocnQiHHFGcrS8VjBHWXowABFtS1HEAwBVVmgAOVgAd0SZ2GgAazBoElJEADFyPFsDQVv4PcRWQ7Nz1dYibwAM36YF0YAAtAA%2BE6VWZgSiIQ5FHKIPLsGL%2BRCBLESabdMa7UhgWxY2xOSivRDvT7fJS-bREAwAeSwrGosCo1CsNns0EczmeVnYD0oXiyKLRYEO5FYpBhXQAPmADgiIdC8d0WHxOAY5JwOPLOkqjLBFuKSujYqScVDDZrzaj8hi4li7akxG6pB10mJIAAacBQEmsRw0WyoMAAbUDEFASUgABIONwI5AqKx-TGWImtDgsMg0NGUgAGAMpSD1UWo1hGTgkRB7LDoTMpAAsWYgAF0swBfMssOPSRPJgtQdMtocJ3P5iNF5IARn78eCRGoiAA6uR4LKJ0kABzFjtgbtSPtZwdSYdcUeQeSwWA4XfZqfjGeFo8QABMS6HRjkkQfZwolYABRUUmUBAAZKhkB-KRAXGEkjxPFgzykC9nxHVM7wfJ8IBzV9RznJIAGY4OzWt6wAIUQQEzEQFdrFkHQlDwlhWnzZDex-DD8KTa9sPvR9yIIvMiI-MBW3I-DKOgRAaLo8xIKOZRrhJSsNDObRyTYtglE4pIUIgNCByPK8UzQW8hLY0S3yjCSAFZpKgWT5No%2Bitk4bglDUxANK0-lKF0sAEJwJDDO488zP4iyoBw4TouncSUgANmcyBXIU%2BiCBwIhAgIAUOL5MxgtC8LpCMsATNjaKsMs%2BKbJfMTZwkgB2dLMvc8weDkRRWOcsrEC408eNqgT6uskSmrs4jpD3Dq6zkrLzAKnBnFKxChoikaovjGKbwaqakpalIAE4FvrKJARYgr0DGYKOK2irIvQsbYqs3CjsIk6F1LCSMsWtzFMQP90AAtagoGzbhtQ0a9rquLJsS773xSedF3%2B1yrpY0HwfW5zHph4y4cnBGPoSvbjtRhdv3%2ByskAGJlKCFTcdyhsKnqkSrqrAXioH2wTPuR5rqaSecyMxwGoiUWB%2BngZZEAiMGWIe-TOZYbmScvAXLPHL6RfstGpP%2BvgGkBCxbkoECOaMUgzFYTdt1IYLW0PbbYd20nxrHAZGqpw2Fyck2iAaShAXIWomW87QzBA2o1FJHTnIct3np2174e9tNff1maJPnNLg9qNwPHgR22Yk12iaqrXMKzvXhbztH2qL6XrHYJklGglpy%2Bd5yq-d4nPe1smG8plGA7F%2Bai4ANUIqiqHgTle5d1OuZe0zM-esfJ392apHnc6i7ufo%2BXJBfRWXrcK5Laueb58yDqR8eDf3lhPz%2B8seFwRwIgRKi1oXCotYC4nxbBMyMEQWQq0myQwkoNO%2Btc%2BJk0Oo3ZKyRPwY3LB8Q4f83JfEQKiCw14Fbh0oDKckURRQ9QUMocM7Nyrr3TpvL271UEvybhg2m5YADShDOD1HNpbSskDZDQQRBtDmiDh51zYc-XeE835fgluWEw6g%2BQ8AQLBeB0NB5VUDJ2fsaZbB3DJBGBBPYgA)

**Please describe here fantomas problem you encountered**

#### Code

```fsharp
module Caching =
    type MainCache() =
        member private __.StoreTransactionRecord (address: PublicAddress)
                                                 (currency: Currency)
                                                 (txId: string)
                                                 (amount: decimal) =
            let time = DateTime.UtcNow
            lock cacheFiles.CachedNetworkData (fun _ ->
                let newCurrencyAddresses =
                    match sessionCachedNetworkData.OutgoingTransactions.TryFind currency with
                    | None ->
                        Map.empty
                    | Some currencyAddresses ->
                        currencyAddresses
                ()
            )
            ()
```
            

#### Result

```fsharp
module Caching =
    type MainCache() =
        member private __.StoreTransactionRecord (address: PublicAddress)
                                                 (currency: Currency)
                                                 (txId: string)
                                                 (amount: decimal) =
            let time = DateTime.UtcNow
            lock cacheFiles.CachedNetworkData (fun _ ->
                let newCurrencyAddresses =
                    match sessionCachedNetworkData.OutgoingTransactions.TryFind
                              currency with
                    | None -> Map.empty
                    | Some currencyAddresses -> currencyAddresses

                ())
            ()

```

#### Expected Result
The line with the `match` keyword doesn't surpass the pagewidth of 80 chars, so there's no need for fantomas to break it in two lines.

#### Options

Fantomas Master at 06/10/2020 08:33:01 - 50ed1b7aab9bde89ea4d5d3fc6fd44b91f0741cb

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| **`PageWidth`** | **`80`** |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxValueBindingWidth` | `40` |
| **`MaxFunctionBindingWidth`** | **`0`** |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Looks correct behavior to me at first glance:
![image](https://user-images.githubusercontent.com/2621499/84635127-145ac380-aef3-11ea-89e6-43d78d288c76.png)

The entire line is longer than 80 right?

**Comment by knocte** [comment]
> The entire line is longer than 80 right?

Shit! This made me realize that VS4Mac's default settings for F# vary compared to C#'s defaults (120 for the former, 80 for the latter). :sob: Sorry for the noise.
