### ISSUE TITLE
When cutting off function invocations, should place each param in its own line (or align them to the 1st param)

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#907]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAwgIbQAWAlgHYDmYAvADqUQQAuAngA74CyRVxMogAUASnpMWUsOkToARogBOYAPqqAdACVErJeUQA3RABkiAZ1YFY6TrCyV4AISI4ilaPmFF48JYnNzNAAFLHkccmgAQV9-QNFJaSTklNS04WgsJX8PdjQCLJzodlE0ADlYVgAxONIAHiRocnRXAD4JZjSwHFhoAGswaBJSRCryPHMNQRH4Mt0Ad1glPoARIlYiMGEAMwc1MABaVsSulhbWMjB5V3dPMHnyVlIT07AAHzAK1ijDfjdw-BHT6VH5-IgAl6nD7TRDwLbXNweRAAGjArGaiHER0hrwg5G2gxsdgczhuSLAdTAAAYNFT0GiRpQcbipDo7EpWMElLAAfS4LZ7I4XIi7hVKPhMtlELkwD4-AFzGBzAryLBKDDZgslqt1kRma8xPqpAlOulRJBkeAoMrWOiaOZUGAANpWiCgJKQAAkHG4jsgVFYFtdLC9vxwWGQaBdKSplpSkAAko5pawAMqcEiIMpYdBBlIAFmDEAAusGAL5xlju6Ren2RqABvM1z1hiOO6PJACMlY9wSI1EQAHVyPAnk2kgAOKlFsClqQV4PVqS1rj1yDyWCwHDjkMt1xtqMziAAJh7NdTckiW7VUVYAFFHAB5bYmKjIM9SbauZUzucsBdSEuu51n6G5bjuEChvu9YdkkADMH4hummZOIg2xLIgfZKEQsisMoEEsHoEa-uWZ5AZB3qrqBm7bohUHhjBR5gPmiGQchnioeh-gmLA8zKEMypJoYvTrKqlAEWwSjEUkf4QABVYziuvpoOuNEEfRB7OkxACsrFQOxiCcRhACqnDcEoAmIEJInomqElgF%2BOA-jJpGLoplHKVAYG0e5raMSkABsemQAZRn%2BAQbiBNYlCWFJ0CsEs9mOc50iyWA8luu5IEqd56l7gx7ZMQA7MFoVoRhPByIoShJd%2BiAkfOZFZVROVqXR%2BWabB0gTqVGYceV4XXuJenJfVLmNW5HoeWuuXtX5hUpAAnL1mZRNseFKNY6AtPZRFjalrmAc1nmqeBc3QQtXaxkxIV9YZA2IBe6BXj0w1MaNDX-k1U3ZV5bW%2BRdh4pJ23Y3QZa0bU9L12Xpe2fXJ33Nr9p0%2BVN81A12p43UmSCUKwj6UAAKko7DDmOI11fD6WI8u03UWdAMFRjSSdghYN3VE3IkisiARM9G27VJ%2B1SGlGVgORUB0ypjbnUzWnAyxN18AAHgm2yE4yd5OY9pBLKww6jqQ9n5tO41fZNSMtQ2eN5ej8tdrpStEKrlDbOQyuPuZ6xLHeyucHE5hifZ2mmwdE1HT9Vv%2BjbsudUxnZBU7ys6HASjwAb5NMSbVNixLSlrjLjNx8DJVJ5z2HsI%2BSivpYGdG3p2dmwjFu08jhdo4D9ssz1ScAGrQU4VDwFQ1B18boci4dCmRyd7fNnbXVSJ2y1J1UDjxWJg%2BOCPY96RPLCizTwFR7NRf%2Bckx7XfGPC4OiETik4PT9E42H9Lo5gE6mOGINY4boG9KQPpN2pi3Y%2BJ1T4dzlovFgx5QbxjmPMe%2B91WB8WlITVcPM3aUEeGJKIjhKoKGUA6Cm2sc5HwosjCB89O7QJPFjeMABpRAiBOBqw1tKJMX9ZCvnFLVUhwDc7HRmv9SBxcL5s3jKmPQkRWA8AQO%2Bd6lMBFWmLJWf05gqiB0dB9MsQA)

**Please describe here fantomas problem you encountered**

#### Code

```fsharp
module Caching =
    type MainCache() =
        member __.RetrieveLastCompoundBalance (address: PublicAddress)
                                              (currency: Currency): NotFresh<decimal> =
            lock cacheFiles.CachedNetworkData (fun _ ->
                match balance with
                | NotAvailable -> NotAvailable
                | Cached (balance, time) ->
                    if compoundBalance < 0.0m then
                        ReportProblem compoundBalance None currency address sessionCachedNetworkData
                    ()
            )
            ()
```
            

#### Result

```fsharp
module Caching =
    type MainCache() =
        member __.RetrieveLastCompoundBalance (address: PublicAddress)
                                              (currency: Currency): NotFresh<decimal> =
            lock cacheFiles.CachedNetworkData (fun _ ->
                match balance with
                | NotAvailable -> NotAvailable
                | Cached (balance, time) ->
                    if compoundBalance < 0.0m then
                        ReportProblem compoundBalance None currency address
                            sessionCachedNetworkData
                    ())
            ()
```

#### Expected Result

The way that fantomas has cut off the parameters to the `ReportProblem` function looks a bit weird.

I think it should either do this:

```fsharp
module Caching =
    type MainCache() =
        member __.RetrieveLastCompoundBalance (address: PublicAddress)
                                              (currency: Currency): NotFresh<decimal> =
            lock cacheFiles.CachedNetworkData (fun _ ->
                match balance with
                | NotAvailable -> NotAvailable
                | Cached (balance, time) ->
                    if compoundBalance < 0.0m then
                        ReportProblem
                            compoundBalance None currency address sessionCachedNetworkData
                    ())
            ()
```

or this:

```fsharp
module Caching =
    type MainCache() =
        member __.RetrieveLastCompoundBalance (address: PublicAddress)
                                              (currency: Currency): NotFresh<decimal> =
            lock cacheFiles.CachedNetworkData (fun _ ->
                match balance with
                | NotAvailable -> NotAvailable
                | Cached (balance, time) ->
                    if compoundBalance < 0.0m then
                        ReportProblem
                            compoundBalance
                            None
                            currency
                            address
                            sessionCachedNetworkData
                    ())
            ()
```

or this:

```fsharp
module Caching =
    type MainCache() =
        member __.RetrieveLastCompoundBalance (address: PublicAddress)
                                              (currency: Currency): NotFresh<decimal> =
            lock cacheFiles.CachedNetworkData (fun _ ->
                match balance with
                | NotAvailable -> NotAvailable
                | Cached (balance, time) ->
                    if compoundBalance < 0.0m then
                        ReportProblem compoundBalance
                                      None
                                      currency
                                      address
                                      sessionCachedNetworkData
                    ())
            ()
```
            
#### Options

Fantomas Master at 06/10/2020 08:33:01 - 50ed1b7aab9bde89ea4d5d3fc6fd44b91f0741cb

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| **`PageWidth`** | **`80`** |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxValueBindingWidth` | `40` |
| **`MaxFunctionBindingWidth`** | **`0`** |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

**Comment by knocte** [comment]
And from the 3 possible expected results I gave above, this would be more in sync with what fantomas does currently, if the parameters are not currified:

```
                    if compoundBalance < 0.0m then
                        ReportProblem
                            compoundBalance
                            None
                            currency
                            address
                            sessionCachedNetworkData
```

**Comment by nojaf** [comment]
It indeed makes most sense that Fantomas would go for:
```fsharp
     ReportProblem
         compoundBalance
         None
         currency
         address
         sessionCachedNetworkData
```
