### ISSUE TITLE
VS Code | Extra white space added to record definition

### ISSUE THREAD

**Issue by lqdev** [fsprojects/fantomas#910]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAwrALZGIB26iATmALwA6ZEEwYA2gDwBSAzrGQAUqsXFSwAKepHgBLHtgA2AQ0wB9MktJSAlAD4Auo2bMAInMUqAcpsRoe6KjLIBzMAF9GjLLjABZRDw8Ss54DEzMrJy8-EIi1BJSAEYImDoGRsZgAEIpdg5Orm6QADTgUDyI6OgFPKjsZSwNzJAAJN7IaJBO6CVNEK0AbkoKAK4d9ZnMAAylk-0AkmRIFADK2ErQiJYjRL1zYAAsfWD6TW6zEcet7XVdFHuZg8NjdWzHEACMF5OQAsGIAHUZPB0AALB6TD4AJimx1OxnOTVAPzaOHGkGSsAUEOaLSGo3Gb32UO%2BjxWiCIMjgCn4AEF0ABRJYAeQAZgAZJzIUnGVnDCpws6k5GPVG4W6Y7E8qB456E95gADM0v6aw2iCyiFZsCoiD%2BVBslCoOOMDjGgoRwquYvRkpNMvxLzQRLmBxVUDVm012t17NgAHdqNAlBVFgNYMHqvx7RAzYgLcxEcYRcZrmiJbAsfangTXgqAKzuyCejVanWIACq2FEwdDZHDkZk0fdfIUAsm8MTVpRN06dulOadEzmADYiyXveX8MpAoQyPYqCNoOgdTGwK325lOxAk5ce%2Bm%2B5mpdbHfL9gB2cfrL1l3X%2BIiJahrjfxjtCpHW3tQfsnuV5-YABxXuqk66oQNJkM%2B-Kvlu77Jp%2BB7fke2ayrmzoKgAnMBmy0qyRqECQShrnGCY7t2opfhiyEDqhQ4upCMwKsW16lj6iDkpS1LNgqL6ke45GpjaGZZjRp7-nMHxfExJa4UaHFUli3H7CRb6Wh%2B%2B7ioeIm-mhw6QiSTGLMs6DMmQAAqVCYECYJQW2MHGNu-HqRRiFUdpKJieh%2BwfMq0ksbSwgjEsJiIAoMiUkaxGLvZzCObujQaei3QoZ5emZB8bpMb4SgAB7zKyZmguQDJ2SsoI6ugQIguC7oHLCqlds5gmUclol-l5EmFlluWLKyMg5cyohKCuVAMjl2C6oETaQe6%2Bb1bBanwYltytTpdEKh8Y7dTlABKiBwFQ8BVTZtXzQ5cF7i5mlQKtHntWlxgfJe20BQamDMlQnL2MdNUKnVfHxWAKa4i19xtbp9HpUB20AGpylkTiyC4P1rv9DVkU1IOubdoqpZDj1YdtABiQXLtNCNLAUKOnQDAlY9dbnHndEMKjCRa%2BCMCjVGFZAajS0AANZZAaguVDwpkrDY4E7DNPHQbTmP9EJWlM7j9348wUJSfskCWIg-o86W6CBuQZloiFfVkDIUZkLSSz3o%2BVC1C28vo05S1Xba1FrWecxQgZOsANKIIg2D5YV5CLJLpCcrztmbudi2Xc1rk-sz63Er5OsrPky6%2BAg3Jy3ZANlPoFxdDwRM8DIdS8W4QA)

**Please describe here fantomas problem you encountered**

Using VS Code with `editor.formatOnSave` set to `true`, given code like the one below on an _fsx_ file, an extra line is always added to the first record type definition (in this case `Commenter`). Each time the _fsx_ file is saved, a new line is added. It only happens on the first record type definition though. All other records are not affected.

#### Code

```fsharp
type Commenter =
    { [<JsonProperty("display_name")>]
      DisplayName: string }

type Message =
    { [<JsonProperty("body")>]
      Body: string }
```
            

#### Result

```fsharp
type Commenter =
    { [<JsonProperty("display_name")>]

      DisplayName: string }

type Message =
    { [<JsonProperty("body")>]
      Body: string }

```
            
#### Options

Fantomas Master at 06/11/2020 06:46:37 - 57496fa91d49578bbfd15b40f79df162478cdcee

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxValueBindingWidth` | `40` |
| `MaxFunctionBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Thanks for reporting this @lqdev, this rings a bell.
I'll check this out probably tomorrow.
