### ISSUE TITLE
Fantomas wraps extra set of parenthesis around parenthesis.

### ISSUE THREAD

**Issue by andrew-russell-ps** [fsprojects/fantomas#921]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMA3AhgE4CW%2BARpmALwA6hNAdhMy6xABQAi%2BW%2BAgtGiIAzsIB0Ac2wAhAJ4BJeGAC2CAK6YAcvmWIxhRPnjdedRmwuWWwMIuphoBnogDyZAFaJoWMXYC%2BZkxWwWAAPgB8YABKIho%2BsADWAGr46GqIAJRiKWnIADTgUMLYWMQMEsKoYADahRCgbJAAJFiyAA7IaJBlWJAFjU0EuVW1lgAM-RaQ8gxIDFgAym34Qppqyn11rAAsWxAAult%2Bk-V7UC3tnVA9mwND6SNnEACMJ6yQAAr4UgDqxPBYAAWtwszwATGMzocWMctg13hcOlVIGRYLB0CCWM17ldRhYwW8sQtEMpiHB0LAGHwsABRWYuABmABkyvknmAGalilCjm94VjEVcUWiMYTzjjHpYAMxiiCQJYrRDSRAM2AGL6EHTYRCETGsLCEdI8mF8s7NVpIrqo9F6uWDVIPNB4tjbWVQBVCZWqgxM2AAdx10HwxRmuFgQdKlNtzANRrY0OYsOsZsFyOtopTEqd7IArG75ctPSq1YgAKptDqEIMhhhhiPEKNuznobnx3lwlMWoXp6PYh249kANnzHqVxYMAGF0MHhBPKcJY941dGIM3W6wExAk8x%2BcxzZc0yLe-bhtnLAB2EeFsfexAAWRJZB1K45XMQxsTpoGXcPNrFfdPGp2QADivRUvRLOcKQYF813fNsTQ7b8DytI9-xPR0gMsABOMChD4BksB1OdlGUfAX1jeCN3bZNkMtKAe3QrMsNBCZ2QLcDx0QYlSXJRt2Tgj8ty-BEf1Qv9M37SVQVedjRwIojCB4sl0X4yxKKEsBt1OOjuzQyTAOdVhwXzGY5iwFwGAAFUIWQ-iBWC3007SwF3O0xIY-S7iks9QRlOTrz4QhYDUWZOEQdBiFJRSKMNKiWE3LSRIFDzunmY9mKMlhnlddi73wAAPeQGSswFEAYGkW24wE1SwP4AWBN1tkhBDPyQ0SUOudKmJ8li2GePM8sKmYGWIAqXErHg1RpAq2gMUQGxgt0cxa6jENojr6LS3oesM9lnmHIaCpiOBCHgeqHKa1aEpondO067aMt6rLmGeS8jqCzVZBcQgWQXC7GvZZrnOSvdUy6G5dswl6XlAo6cnSaQyngMoJABl9gda4T2pSh7IYM6H9two6ADFQu8RakdmVH0aukGcbB1LGIJgdLAhfM7ziYhIoYJUKWgBJpE1AXsGESyFi1KD1iWgSnKxpKGfch7me8va2dkyxIE0RA-R5scsADcqrMucLRoYYhIypWYH2UJ9CEqJs5bWtqNtxraVYRTL2TBAl2IAaUQRA2mK0rypmCXdBZXnHKq%2BnXcZ5WvM957vf8zWFgNMksDvBA2UsQT5b8Qp9kmbphBJ4RiCqQS-CAA)

Fantomas is adding an extra set of parenthesis. DataAccess.getById returns a result type. Result.okValue extracts an option type. This is all wrapped in parenthesis, then we are  extracting the value with .Value. When we run the formatter, it adds an extra set of parenthesis each time.

#### Code

```fsharp
let variable =
                (DataAccess.getById moduleName.readData
                         { Id = createObject.Id }
                     |> Result.okValue).Value
```
            

#### Result

```fsharp
let variable =
    ((DataAccess.getById moduleName.readData { Id = createObject.Id }
      |> Result.okValue)).Value

```
            
#### Options

Fantomas Master at 06/13/2020 12:50:29 - f502c77f041ab51647d9f271932036d4de75de58

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxValueBindingWidth` | `40` |
| `MaxFunctionBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
I think this bug is related to the changes of FCS 36.
Are you using Fantomas 4.0.0-alpha-009 by any chance?

**Comment by andrew-russell-ps** [comment]
Yes
