### ISSUE TITLE
Feature request : Support braces with the first one being on the same line and second one is aligned.

### ISSUE THREAD

**Issue by OnurGumus** [fsprojects/fantomas#927]
I would like to have support for the following indentation
```
Html.div [
    prop.text "test" 
]
```
Is much neater than the other alternatives offered by fantomas.

**Comment by nojaf** [comment]
@OnurGumus would you be willing to contribute this feature yourself given enough pointers?

**Comment by OnurGumus** [comment]
Perhaps :)

**Comment by nojaf** [comment]
@OnurGumus this was all still quite fresh in my memory, I ended up tackling this myself 😅
