### ISSUE TITLE
Question: Semicolons at beginning of line for multiline lists/records?

### ISSUE THREAD

**Issue by vsinha** [fsprojects/fantomas#938]
I'd like the formatter to emit something along the following lines (for lists/arrays/records):
```
let foo = 
  [ "one"
  ; "two"
  ; "three" ]
...
```

I think the semicolonEOL option is half of what I want here, but really it's 'semicolonBOL" or whatever. I'm willing to make source changes to a fork for this, i'm poking around in CodePrinter.fs but would love if anyone has some guidance or an idea for where to best make this change.

Thanks!

**Comment by vilinski** [comment]
but why noisy haskell style here at all? in F# you can just omit semicolons without compromising readability!
please don't bring complexity into formatting

**Comment by nojaf** [comment]
Please create a proper issue according to our [feature request template](https://github.com/fsprojects/fantomas/issues/new?assignees=&labels=&template=feature_request.md&title=%5BFeature+request%5D).
Thanks for understanding.
