### ISSUE TITLE
Insertion of space before function application can break dot-chaining

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#943]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAzWsB0AhAhgE4AUAlNgNoCsAupADThQDOiALmwJYB2A5s6jAUmEUBHFQAJGwCeAB2RpIPNgxHjIkgG74ANgFdFQ9RIAMjCRMgBJbkm5sAynPzREAOX0BbNZfEAWEzAadQBfC3ExS01ZBUFlB19o7T1DQWE-CABGCL9IAAV8XkQAdU54NgALJL8sgCZTIJCJcPUoq2l5I0gAIyxdGo0UgyMMzLrc6MdEL044XVhuAEE2AFE7AHl0ABkeZEmJdD1WJrDJ9qHY7r7YAYOpHRH0oIgAZnuISGdXRFxETEIiEKhHwXnYiEIgwkbEIhlOLXOQRiXXiNzuSOGaTQYz8-g%2BUG%2Bbj%2BAMQ21gAHcIdB8KxbFpYNSuIsoeIYXC-M1xK0JBdPp04ko0SzNI8scZMmAqPivi4if9YICAKpyBSEam07j0xmcZn4tmIeFcxF5fnXfrCzGjF5gABs0sJv3lgIAwroacxnYtmGzoGwFSyIPrDRBuZEMVdUeb7iLUlaJQB2e2yx0kgCyMx6EIDYCDHLObXDKMFUYxorjmQAHEmfsSFYhPQtuNnc5ZOSHjckI8Xbhay88JQBOatuJboNgQz1eLz4Zuwg15hEFk1dqBC6OW-uZLLma0ymtOxDTWbzXXWlsSNtgUOiQsC1clk197HWrI5XcO0fjwhHua3U8S89xEva8wF5KQV16B9kifcUtwmXdbHsNgNm4AAVQgZDKKpsyOXQTgXI0l07It7x7dcYJxSwsned9kyWQhYH0OwABFEF0ThZi-Wd2VbfMeVvboVF7WNN1qPFd1TfAAA9rHQVDKkQbhVjww9KgVNgygqap8X8RoCPbIiOggoTyJE58JSyKUJOk2x0E4KSNlVfA-UIVYpLkQFmGYHUm3xKg9N4xd%2BOXEiElUUynnMrc7WsqSACVEDgQh4E07CdICi8%2BLDEK7zC4TItg2pE1i%2BiQRkDZCF2b1Uu061dODK8OyM0KTNLMzCqoqtYoANVjXAeHgHheBq7N6v0xrDMuFrEgisVKIkLIh1igAxJjfR8-q7CGkb0oakCwORXK1zagr5vEBppVTfRdC4djuF%2BBZoAAa1wEFnvYZgUMcUF61ubxfLPOc9qaqajqgjoKOtOo3wlSB3EQck7sdNhKUU1CulYuzuE4JlljsdMvEzQgBD1IHxv2gTIzIk65qh%2BDYYAaUQRA5Fk%2BTFNsb6wV2e7uPnQLCOC4jctax92rOiA6ho2HJKk5TZmYSodrqjKgKym8crNamxdOqHxNhxwht0RB6N4bxFI0xAelTBB9mtXD8IFgyheasHteg8Woasg2YTmNgbaQHDjn5zKWiYGgImUZhlu8wQHYNUIgA)

#### Code

```fsharp
foo.Bar().[5]
```
            

#### Result

```fsharp
foo.Bar ().[5]

```
            
#### Problem description

The space was necessary so that we could continue dotting into the expression. Looks very similar to #566.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 06/30/2020 07:24:01 - dcc70c330998047375f7ad1f84c7d88a50378e72

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| **`SpaceBeforeUppercaseInvocation`** | **`true`** |
| **`SpaceBeforeClassConstructor`** | **`true`** |
| **`SpaceBeforeMember`** | **`true`** |
| **`SpaceBeforeColon`** | **`true`** |
| `SpaceAfterComma` | `true` |
| **`SpaceBeforeSemicolon`** | **`true`** |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxValueBindingWidth` | `40` |
| `MaxFunctionBindingWidth` | `40` |
| **`MultilineBlockBracketsOnSameColumn`** | **`true`** |
| **`NewlineBetweenTypeDefinitionAndMembers`** | **`true`** |
| **`KeepIfThenInSameLine`** | **`true`** |
| `MaxElmishWidth` | `40` |
| `SingleArgumentWebMode` | `false` |
| `StrictMode` | `false` |

**Comment by knocte** [comment]
I think this is a duplicate of https://github.com/fsprojects/fantomas/issues/853

**Comment by Smaug123** [comment]
Yep, thanks for finding the dupe!
