### ISSUE TITLE
`with get` removal in FSI invalid

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#945]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwAhAHXQBcBPA0gMVljAF4qIIAfczAJzCwAZmACWNTl1zYARokEBJaomxg0AV3RjqYALQA%2BcTTAB3HQAswAc0TVIAGnBQ8d6hOt5UYANrOIoFxckAAkdAzekBL2TkEQoQBumAA2GshofnFcAAyxWVCK6Eg0AMpEJAByGtiO-nEALHUQALp1AL55AU1QYfTpUNG1WYkpad6Z%2BQCMnXGQAAqYtgDqYvDUFkNTAEzZ3a1BHXWBs70RaJCyLMmbQSOp-RNZWzO3JapicMmw6ACC1ACiRQA8sIADISZAvLjCFKuPbtGbHW6nfoXK43YIhJL3cbdCAAZih8TKxEQZEQwlg-EQC34ODsCgxQWo-DS8IOiO6oXCqMusGuULuYwyeLA9SJUBJJHJlOpoNgpgU0EwrkKCVgyvc3yZXBZbKy%2By4hyCSMxPMifIFXKxoweooArBLIFKyRSqYgAKoEBj8ZWq9DqzVibUSvWIdlGznDFEW9GCm04kX5MAANidLpl7oAwskVXgs988HroNQqTqIGGIxBjVxTfEY%2BdLTqhXbkwB2dPlV2yxAAWVU8n45bAlYNCKO1vNjbj1uxwt8ooAHJ3SZnqQWvuhh6O4obq1GTlOoE343PW-kAJwrkg-YQqfgF7DYTDb1nhsccifRo9o-nNhPzo8cSTLkorOl2a6IG82AfPyIaijuQR7mANZdN%2BfSxn%2Bp62riyaTNMYEure97QbBm6vvqu7jiak4YdOWGzjhSbbE6hTFNQQLoAAKvwtArOsw4wskcIfpGX6HnRx4ztGZ64VMhKEV2Pz8LAWjwAAIogyRiDB94Ue%2BVGfjR6FnAMND-rJzFZJM4pgb2mAAB6KMIXEWIg6D-MJUEWFS1ArGsGwSvUuyifu4nIj%2BgzYYmC54Y6dmOYUwhiA5QI%2Bpgpb8P8DkENSeB4MGW4SvaIWGWJxkSaZUTmdFgGipMaYJQ5ABKiBwPw8D%2BQJQWlUh1G1rRVVRYxMVAUEkwdk1yl0rQQL8OCRZdYForBVWKEHhFknVTEI11Xhy5NQAaraZASPAHhLcOq2het4Vmltw0yUxsVTFeTWMFoJaFadRQXas3Urb1XDIahYB1j0P4nrt55PKByaQL2GjJO42noGSXzQAA1mQdJY3YeCcSU9IbtURUIW%2Ba2g%2BD3JbVDT2jaKWwEfDFSIKYqOutQiruVxfSacl2har8RT9nICheKGFM3VTg28tJJyWS9TzPGBADSiCIAQzmue5hRE7g4Jo-plMbfdQ01dDclPAp8P2Q5nkwXgFiXT1Jt3fWkPy8iitjVwWy2fDJQeMkiDKdY1TuX5iCyL2CCQqKQkiWVYUVZtVV0wrz2%2BxAWzxYHLIfNQsdIIJsIGX1BzOM0eRRHgjAFd4lZtEAA)

#### Code

```fsharp
namespace B
type Foo =
    | Bar of int
    member Item : unit -> int with get
```
            

#### Result

```fsharp
namespace B

type Foo =
    | Bar of int

    member Item : unit -> int

```
            
#### Problem description

The implementation was
```
member this.Item
    with get () = 3
```

This implementation became invalid when the signature file's `with get` was removed.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 06/30/2020 07:24:01 - dcc70c330998047375f7ad1f84c7d88a50378e72

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| **`SpaceBeforeUppercaseInvocation`** | **`true`** |
| **`SpaceBeforeClassConstructor`** | **`true`** |
| **`SpaceBeforeMember`** | **`true`** |
| **`SpaceBeforeColon`** | **`true`** |
| `SpaceAfterComma` | `true` |
| **`SpaceBeforeSemicolon`** | **`true`** |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxValueBindingWidth` | `40` |
| `MaxFunctionBindingWidth` | `40` |
| **`MultilineBlockBracketsOnSameColumn`** | **`true`** |
| **`NewlineBetweenTypeDefinitionAndMembers`** | **`true`** |
| **`KeepIfThenInSameLine`** | **`true`** |
| `MaxElmishWidth` | `40` |
| `SingleArgumentWebMode` | `false` |
| `StrictMode` | `false` |

**Comment by knocte** [comment]
what happens if you use fantomas on the implementation?

**Comment by Smaug123** [comment]
To an extent it doesn't matter: Fantomas works file-by-file, and if I edit an fsi without correspondingly editing and formatting the fs, it may break. However, the answer is that Fantomas leaves the `with get` in the implementation, breaking the code.

**Comment by knocte** [comment]
You're right, but I'm really curious of how this issue overlaps with one I reported a while ago which in the end we dimmed as not an issue: https://github.com/fsprojects/fantomas/issues/733
