### ISSUE TITLE
Fluent API calls getting condensed onto single line

### ISSUE THREAD

**Issue by reinux** [fsprojects/fantomas#960]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAdATugdgG0QBcw4cAzASwHMBXTRAZUUwDcLpEBnMACk%2BbYduaAJJNW7RAGFYeAtEIVYOAJRgAvFlwQCxQgAtYBjWAAqhgwDoAUp2WWA4hUwBDMmUSXzR-eIou8CgAvZh5EAA9CVxNbZRkkTE5LCKiXThUtHAh%2BCSFLAEF4eBEkHEVCAE9xFlCM7CyIMAKigBFEGrxYAAdmBmocChwqKXpSxQCeOu1G5uKcAFlEAFtYTAr8rooGOB7OHhdN7e6uKYaIWZEF5dWKqUDEMr3oe8fTxqbC%2BFMuQgBVHL2hB%2B-2Y6Uy7wAPgA%2BMD9VaITKZSAAGnAUH4hEUQ04qDAAG00RBQO8IJAACSVHq4yCDQgowmNcksAI0ZBoAkkxoABlRnNJlzGfRC9L5YAALAyIABdBkAX15jWJJPJlLZUFpIuVZOZeFZuI5fIAjArOZB5i5wgAZQaIS0PKgGTWcw0AJi5krAMve8oZSveKoqVLQkAARrBZE7GdqWWqDZyXSblUwluxZMp8oQAKI4eAAeTI1pwyET7zIAX4Hq9jR97z9UdV1LDEZLUGjutjHogAGYW6SGF0XBwAEKIMjwgAKLlcSyIzEj7yirMrcsTddJFMDatD4bw89bOr17M74t7UH7g8QI7H9EtsAA7sxoGlEJcWLAn4plHuIIvEMvvauHoBkGUBNruLZMjG%2BrHgArKekDnsOo7wr8XQ9JgT78K%2B74uJ%2BODfmAZZ4BWnJVhANaKkBG4gduzZUQeHaigAbPBiGXsh9B3GknAyDgnCLgoqwEURJEkmRYAUUSVENsGYF7pB7bQaKADsrEDkh16IIsSwhnOp4iX%2BpErr60mbo2O7yW2h74seAAcakXle8IyJ0%2BH6eWhlicZtamTRckQVZjF8gAnA5HD5GQQKYDISxLC4BG-v%2B1aAaa1Fbv59FQUeoqGjyx4Iep7GacmqaucJHlJeRKVajJoEWQFDFKUaxr5WxEVRSVcBlaeiVGQBJmpbVtHgZlinZUaCb5QKDyELmOCmGsADqFCOu5xGee84mSWAa6tkNGWpY143Oj2rWFfkmCwDQOZtIEKZRQlmBLn1yUDTVZnBhqDVZTZOVivB5rhCIZDmA8mbrQwhiYIQy3wKtx5iu6L1VW9-ppdSX2jdZcYkoacH5YDlyUOEubobhqyZuEXT0JwnBKG5sFI15-U%2BYNH3qmUllHb9RosQTFoAEqIHAmDwLD8OiojlUSdVaNDZjh0-Tj7yGqp-PhBdrgVLmmDWvx4v6ARUvIzLqP1uzNKc99Y08869nqwAajGQ6DPAgxUAbRtM5t3mUWzNEK1q3PK40hqherABi10KPTLs5u7nunsbzOvaz71%2BfVWNBfGeWimaNB4IogRFkOnTQAA1kOrgV0QnBzQwLgzi5NBLAzooGdL227cB6WZ4rNshxALotXnAByiB3sX7GEA%2BDymJubSUAMeH5Dm2m6Yk5XrZ3svmxndH99jx4upNecANKIIgXTA6DOCXA3M6FsWx4dybXe%2BVugdo8Hx%2BnXngPgxTJwfQicEbe0aFtXe659p9yDkrY%2B-1WruwIBdWgM4yiLUQCGeYCBn7twqm-KBe0LYHTgQPY%2B%2BM84MCiOwQgOCkBb1Ej7b0aIpQKhpJwCOdNcQd1lEAA)

#### Code

```fsharp

let configureServices (services : IServiceCollection) =
  let thoth = Thoth.Json.Giraffe.ThothSerializer(extra = JsonCoders.extras)
  services.AddIdentityServer()
    .AddDeveloperSigningCredential()
    .AddInMemoryApiScopes(apiScopes)
    .AddInMemoryClients(clients)
    .AddTestUsers(testUsers)
    |> ignore


```
            

#### Result

```fsharp
let configureServices (services: IServiceCollection) =
    let thoth =
        Thoth.Json.Giraffe.ThothSerializer(extra = JsonCoders.extras)

    services.AddIdentityServer().AddDeveloperSigningCredential().AddInMemoryApiScopes(apiScopes)
            .AddInMemoryClients(clients).AddTestUsers(testUsers)
    |> ignore

```
            
#### Problem description

Please describe here fantomas problem you encountered.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 07/10/2020 17:03:37 - 17bfa28ad4173bcb7c6afc07791787c0a72a795b

| Name | Value |
| ---- | ----- |
| `IndentSize` | `4` |
| `MaxLineLength` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxValueBindingWidth` | `40` |
| `MaxFunctionBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `MaxElmishWidth` | `40` |
| `SingleArgumentWebMode` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
@reinux could you please describe the problem here? This is normal Fantomas behaviour at first glance.
Please create a [feature request](https://github.com/fsprojects/fantomas/issues/new?assignees=&labels=&template=feature_request.md&title=%5BFeature+request%5D) if you have stylistic problems with the way this is formatted.

**Comment by reinux** [comment]
I could have sworn I saw fluent calls being kept on separate lines. Maybe I was mistaken.

**Comment by nojaf** [comment]
Well, maybe the following happened: when Fantomas cannot process the file, to begin with (for example by some uncompleted code fragment), it will restore the original input.
So maybe something else was going wrong, you pressed formatting (and nothing happened) and you got the impression that the file was reformatted.

Please let me know if you can reproduce it still.

**Comment by reinux** [comment]
Actually, I think this is a duplicate of #501 . My bad.
