### ISSUE TITLE
How to place a single pipe on the same line?

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/fantomas#969]
I have a single case DU creation like this
``` F#
ID = "FED18745-7C4D-4491-9323-CBC28746631F" |> DomainID.ofStringOrFail
```
Because logically I don't care about the function after the pipe. The main point of this statement is that some GUID has the name "ID".
But then it is formatted as
``` F#
ID =
    "FED18745-7C4D-4491-9323-CBC28746631F"
    |> DomainID.ofStringOrFail
```
Can this be changed?
Is it possible to at least format like this?
``` F#
ID = "FED18745-7C4D-4491-9323-CBC28746631F"
        |> DomainID.ofStringOrFail
```

**Comment by nojaf** [comment]
I'm not entirely sure I understand what you want, but you can tweak [MaxInfixOperatorExpression](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBJAImAvGAOpAGICimAjABwDsALAKwC01AwrZo7bQJzmPcBmAEwDGLAEIshNWgDZZA8kUJgAPgD4wmWAFsAhgEsAdlgB0sAGYBlAC4AnYwHMA8naKGANpAA04KAGdEGxsnf1QwAG0-CFAIOKgAEhsATwAHZDRIYxsfaLjIBIA3PQ8AVwzIvPiABl94%2BMh0IyQjGysDAC9kOvqIWiqwAF08gF8emIGClPTwrNbc3oLisoqo3ohycfrIAFk9AA8AGWNEQ8QjRxsACwX18iFqgeH4sbzY7aS0isgAI1hYLxbCBLErlcJrdZCIH5KyIHQGOAeWBGACCNhIzWcFmORm6AwgFhKgSeoy27wanxmmT%2BANuFOWYLQEN6AmhwKsqT00EQ4kQFlgdkQAAU9HY9Dogog7HT6vZyiSXmTJpTvjTAcqGat8WBaGyoByuTy%2BQLTrAAO5S6B6QJNQqwK0hZEy%2BJyxAKuKveLk-Iq2Zq52JTXg7X0PWQA3c3n8wUAVVS6TsVptRjtDoMTr1hI8xN6zw9SsWvup-3VhaDTO1sjDEaN0cQLA81v8LGR-jl0BsAoDBKJbtzpLeyumqpLAZBK2D6zA1GrnMjxsFOzhPyl3bAWZz9TzEE9cW9wKLUH90PHjMqU8os8NUZNLaRRjXG77W4HXqHXz9o5PRVBWqn3CvbkUQsGwpRbHR9DXV13R3AsPmHT9aW-ctzzuWptXDOdaxNWF4URDNtSfGCwF3CZCwQ4skI1X9JzuTYMJrYDQLsXCEQBAip2g-tFUHciP0o0sPhQ5l6nuMMmhaGxnCMAAVOxkgAdQMa5H17YjSLAfdEgoo8v2oicKynchWQYrCUTsWBSmaTBEA8Ax4WYqC7Hlbj814%2BD%2BKgbIxx-AzUN6chdQwvZ9nQCwZKuc4SGzRArCuAUbCU%2BAVL1WhHlc2D3IpHS5hyZCaMMu5Q2Cg4mgsAx9mcBM9E7OwSH2VJBX8fx0wfPV7nSl8eLfPiqS8%2BZ8r8kT4nIKsSv2AAlRA4DseAkpS7U0vUuDss83KfOE7VyBncbzLFZJXGONt5puVLOvibcSJWn0cu8waz2GuIqDDEKADVf3EYx4CcE61yWjKrqym61ru-SHq2gDxqIKyO1az7mh%2BgxktOxbzriS6NK0qY1uPMG-0hdCp12UoPBCOzcXEJFoAAa3EMUaaCfxpKscV6wBUodDawi1IBzH3z6349LLAr-PqIR6KJgA5RAzXJo0bAtc4ZK%2BGzyqMZTWpRZolx0Fc7DCTMea6tyeo8gXceFobtSEKEMIAaUQRBUjCiLziaFmJRxPEpyI3nroPW6Brx2jehEF6Dmi%2BF-CuX6zuWoGA5xoWhJFx6ICEIKifaC4PEQczHA585EsQH4dgQb31l943MtN1bzeT%2BlU%2Bt4qiZROzHCMaGjFh5F2g7mrSkFGTYAkouata1SYvj2vgfrqjLfBqchDG1vSalIxx8KU0Lh1vXVeMDXW0nzcLtfPd%2BZHeeU6tpedqz%2BwERsMukGP59T5ePxBh6LJ-CIFrwiIiMIAA) here maybe.

**Comment by nojaf** [comment]
Please reopen if any action is still required.

**Comment by xperiandri** [comment]
Yes, `MaxInfixOperatorExpression` looks like the right thing.
Also, max infix operators count on the same line would be nice to have.
