### ISSUE TITLE
[Feature request] Add option for semicolons at the beginning of the line

### ISSUE THREAD

**Issue by vsinha** [fsprojects/fantomas#980]
I propose we add a new option fsharp_semicolon_at_beginning_of_line to match the existing fsharp_semicolon_at_end_of_line 

Currently fantomas doesn't support this option, though it does support the end_of_line version.

## Pros and Cons 

The advantages of making this adjustment to Fantomas are increasing the compatibility of the formatter with various orgs' style choices, and mirroring the options provided by existing functionality

The disadvantages of making this adjustment to Fantomas are that it adds more options to the formatter, potentially resulting in more complex conditional code down the line

## Examples

With semicolons at the beginnings of lines
```fsharp
let foo = 
  [ "one"
  ; "two"
  ; "three" ]
...
```

With semicolons at the beginnings of lines
```fsharp
let foo = 
  [ "one";
    "two";
    "three" ]
...
```

With no semicolons
```fsharp
let foo = 
  [ "one"
    "two"
    "three" ]
...
```

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS , I've made this change locally and it's 1 line of code plus adding the config option.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to Fantomas
* [x] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
> I've made this change locally and it's 1 line of code plus adding the config option.

Could you show that change please? I think `semicolon at end of line` is also used in other places as well.
So the premise of `one-line change` might be a tad optimistic here.

> various orgs' style choices

I'd like to see this in the wild as well. I have never encountered this anywhere.
The example doesn't really illustrate the gain here IMHO.

**Comment by nojaf** [comment]
When I asked for an example, showing some other language was not what I had in mind. Do people write F# code like this today?
You could look at Elm, Haskel, OCaml and yes you will find different code styles, but does that mean those are widely adopted in F# as well?

If we were to have to this feature I would want it as a complete counterpart for `fsharp_semicolon_at_end_of_line`.
The code change you listed changes this
```fsharp
type MyRecord =
    { FirstName: string;
      LastName: string;
      Age: int;
      Street: string }

let someArray =
    [| foo;
       bar;
       fooooooooooobar;
       otherBarValue |]

let someList =
    [ foo;
      bar;
      fooooooooooobar;
      otherBarValue ]
```

into this:
```fsharp
type MyRecord =
    { FirstName: string
      ; LastName: string
      ; Age: int
      ; Street: string }

let someArray =
    [| foo
       ; bar
       ; fooooooooooobar
       ; otherBarValue |]

let someList =
    [ foo
      ; bar
      ; fooooooooooobar
      ; otherBarValue ]
```

I fear to get this right it will require some impacting changes to formatting Array/Lists and Records.
It wouldn't just fit into the `sepSemiNln` helper function.
Similar to how the setting `MultilineBlockBracketsOnSameColumn` didn't fit in the existing structure.
I had to write [separate implementations](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodePrinter.fs#L1983-L2029) to properly tackle this.
So your proposed setting potentially would split both of these things again up into two implementations to really get it right.
And you will also need to take `SpaceAroundDelimiter` and `IndentSize` into account.

I hope this explains my sceptism in regards to this request.
The next couple of week I'm on holidays so please don't take it the wrong way if you suddenly don't hear any more from me for a while. I'm open to discussing this further.

**Comment by vsinha** [comment]
Okay I appreciate this answer-- I hadn't noticed the other impacts. I think for now I'll table this with the group I'm working with and we can perhaps revisit later. Thanks for the well thought out response!
