### ISSUE TITLE
Shouldn't cut line by the `+` operator unnecessarily if it doesn't exceed MaxLineLength

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#983]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBlAhgG6IDyArlgOawCWAdpQCoBO%2BdAzvtFjbHQJJ0AwlwAWiMFlYcuPPgAVmsAA6xO6MAAoAZokRp%2BAIXSxoAa2ij89AGJ7B22AEpJAD37wwAXgA6dCBCYOPgAtrBkdFgsbOy6zMyI8PLoZOx2iPzaQmTxiHTQAJ7pALL4WJaI7N6S0pzcvHSKKmr46AB0AIJhEVhtAGqtZIiMsLh5ngDUYLqIbekDKYh%2BAVpOkAA04FDs2DwM7KhgANpbEKArEJAAJFgFyshokPRYG6cB14SDD8dvKwAMmwu70ESEiuBoAC9kICgWAACy-MAAXTeAF8YWdEddbvdDk9Iq8gR8vocTrCwABGDEXSClVwAGXoiHpeUoWFEhNhFIATH9ESiVui3ucaTc7t9IAAjWCwdCclbExakxEQbnUhVjEI0OAmOgdLAAUTo8BI2kZdGhKumrR2-LR1JFCrFuMe0tl8veV0%2BSrQZNhAGZ1e9cMouIhDIhHAl5PhWCFsIhmB6VlIhnbBQ6sc6JW65UHFUNleS4UHLiGwxGo8zYAB3RPQfA7QSEUxlBrJgKpxDpgJClaOz04nMyvNZ72F31WgCspag5eg4cjsASAFVlPdmA2m3QWw25HQOxBtDbu0CBb3M0Ts3jcx2C98-UCAGyzyDzxdVoToRvsIR8diptwy6Hta6C2me9rClmQ43iOd5eiSk7kgA7K%2B76VsuiDFIgISSomIHHmBp4XOeEB9gEA6XNerpwfmCE%2Bj85IABxoaGC4YQkf66gRJ49mRl6ijBNHunR44PlaACcrFhh02hYImf4hCE%2BAgV2fFgORmJXkJUC3qJiGMVyAJWm%2BbEfphmrarKfA8UR6maWAlFQNRum0WOBmPhcFJUiZ76yfJzCWTqNmzmpEEZlB2nirBInuQxnkrDyr4gnkWAkHQLAFAA6jQ7K2eBJGQf20HRcJo5XmJRZcoGvlmR0SgRPAAAiiDoDQWoBapzBpuFF6RYJpVQM88GVUhXIliZdKZIw4h0AaRG4KIy5YDl8B5bOcJ8r1-H9U6On4i8%2BnxVaFIzpN%2BDuHQ2g0K4JAbmUy4Gq4ygJOw7DtrOU5bYVEXFVFLpDQSR0ToZQIUi%2B52uAASogcDMPAq3rVam32QJe2DQdI0eSdqGQ-VrAFCQzCMgBiMcht30rKRGlo4OGPDcD4nkhSLGQwsQyGPQ8D0JQZMgSj2007tdMA5jjNVWDUmQzYET1HwnPGjzfMU6jwtUftelxSDCUBLyr7FGQ6A8G1FrGKYZiGKw5jYOw6UEPGXFkCEB6zoRBVU0VFElaLmsVdj5Lcj55KQAAcogNYm4uWB1nkjDii1110LlDQdMa2G4YmByu7xgsOU52IY77oqjaDFzcmqJkANJ6Mo02zYI9vMky%2BXER7v1e-9EoM1rTOwtyNXB3S81auwojK8jlMBNTefe8OsV%2B8dAcTcH4IMJg9WUE7qVZYgkrFAglrkm7rdT57WkDT7bkL9rVrcmdwcdG1lB0DL%2BT7uCz9lDkwywClkRtiFK0x9VZ-QvnPcqxd-Z9whg-I2iY6BtmIPSPglB054WYAnegyd-wtxAR3MBMUIFOhLjrVUuMV5SG1FgfeSBcG5y2EiGETw0jvUOMA1EQA)

#### Code

```fsharp
let SaveOutgoingTransactionInCache transactionProposal (fee: IBlockchainFeeInfo) txId =
    let amountTransferredPlusFeeIfCurrencyFeeMatches = transactionProposal.Amount.ValueToSend + fee.FeeValue
    ()
```
            

#### Result

```fsharp
let SaveOutgoingTransactionInCache transactionProposal (fee: IBlockchainFeeInfo) txId =
    let amountTransferredPlusFeeIfCurrencyFeeMatches =
        transactionProposal.Amount.ValueToSend
        + fee.FeeValue

    ()

```

#### Expected Result

```fsharp
let SaveOutgoingTransactionInCache transactionProposal (fee: IBlockchainFeeInfo) txId =
    let amountTransferredPlusFeeIfCurrencyFeeMatches =
        transactionProposal.Amount.ValueToSend + fee.FeeValue

    ()

```
            
#### Problem description

Please describe here fantomas problem you encountered.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 07/20/2020 08:56:02 - d42a1565b1b7c532e3dbeaaa4ec0f0cb5ba79f69

| Name | Value |
| ---- | ----- |
| `IndentSize` | `4` |
| `MaxLineLength` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxValueBindingWidth` | `40` |
| `MaxFunctionBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `MaxElmishWidth` | `40` |
| `SingleArgumentWebMode` | `false` |
| `AlignFunctionSignatureToIndentation` | `false` |
| `AlternativeLongMemberDefinitions` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
This looks like correct behaviour as it is following the `MaxInfixOperatorExpression` rule.
![image](https://user-images.githubusercontent.com/2621499/87924799-a9675400-ca7f-11ea-945e-0015b4265b7f.png)

**Comment by knocte** [comment]
Oh sorry, I guess this is a recently implemented new setting? Not sure how I missed it.

**Comment by nojaf** [comment]
`MaxInfixOperatorExpression` is a v4 thing indeed.
