### ISSUE TITLE
Recurse argument short format is not working with the command line tool

### ISSUE THREAD

**Issue by halcwb** [fsprojects/fantomas#985]
Using the fantomas-tool command line tool, the recurse argument works when using `--recurse`, but doesn't recurse when using `-r`:

![Capture](https://user-images.githubusercontent.com/683631/88377486-987c5280-cd9f-11ea-99ca-ad2b8ec4ed03.PNG)

The above sample shows that the `Components` folder is processed with the `--recurse` argument but not with the `-r` argument.

The 5.19.1 version of the fantomas tool was used.

**Comment by nojaf** [comment]
What version are you on? `dotnet fantomas --version`?
`-r` hasn't been around that long.

**Comment by halcwb** [comment]
> What version are you on? `dotnet fantomas --version`?
> `-r` hasn't been around that long.

I have updated my report with the version: 5.19.1

**Comment by nojaf** [comment]
> 5.19.1

Now that is an interesting version number as v4 hasn't been released.
Could I get a screenshot of your output of `dotnet fantomas --version` maybe?

Are you using the MyGet feed?

**Comment by halcwb** [comment]
Sorry, is indeed not the right version, checked it with 3.3.0 but the problem remains.

**Comment by nojaf** [comment]
3.3.0 never had the option `-r`, this was only introduced in v4.
You will need to use `--recurse` for the time being until v4 is released.
