### ISSUE TITLE
Extract editorconfig code to separate NuGet package.

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#986]
## Intro

The merging of the [Fantomas.EditorConfig.Core](https://www.nuget.org/packages/Fantomas.EditorConfig.Core) (which is a fork of [editorconfig](https://www.nuget.org/packages/editorconfig/)) into Fantomas itself is not working out for JetBrains.
They need to strong name the dll and that has proven to be difficult.

## Proposal

I suggest we create a new project `Fantomas.EditorConfig` (that depends on the regular editorconfig package) and move the `CodeFormatter.ReadConfiguration` and `CodeFormatter.TryReadConfiguration` over there.
Fantomas.CoreGlobalTool would then use this package.

## Impact

This will impact mostly editors and maybe library authors.
Breaking changes:
* `CodeFormatter.ReadConfiguration` and `CodeFormatter.TryReadConfiguration` will move.
* FakeHelpers will require a configuration again.

Pinging @auduchinok @deviousasti @baronfel @Krzysztof-Cieslak @jindraivanek

**Comment by deviousasti** [comment]
`fantomas-cli` should be unaffected by the change.
As for VS, I'm not consuming the nuget build, so it should be fine.
Maybe we can skip the ILRepack step, since its purpose is to merge the `Fantomas.EditorConfig.Core` assembly.

**Comment by nojaf** [comment]
Yes, I'm planning on removing the ILRepack thing altogether.
fantomas-cli will indeed not be impacted as those things are shipped slightly different.
