### ISSUE TITLE
Confusing symmetry between infix operators

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#988]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBnAFrAK7rwCSAdtOkUgEqLoCGWAlrBQawA5gBOjAHJMAtojABeADp8pFCBAEBHAHSVqtRLjAAfAHxgAMq1xYViAB4ms2gBQAzIvO4t8YALR6ZchQpdZ8FUNECgBzALA9CTBoIj4BCix1GiQABVcgkPC3AGowAEZveV8wADJSsH83fSNrFSwmAGtxW1j4kKSqFMR0gMywiLz8gEpJGLiEzo001zAAATAAbQF0YTEAXSLfYcgAGnAoXGw2MNxUJYOIUBKoABIsAE9uZDRIVkS9y4VIW4A3JhoLwuNwgAAZ9iCoJQkIkAMqsABeyAhIIALF8IOsvgBfFFXDF3R7Pc5vD5475-AFEIGLAkQfLk3yQACyTAsxgoiGCA3wn0h%2BQATKCCVjfLivtcSj8iUDIAAjWCwdB8qWUwHnWmQgWM76wxAiVhwdAcACCWAAohR4AB5ewc5F0sD2AFHEU48mSpn3J6yhVKlVe-7qtCakEAZh1EEgsJc0EQACFEPZYAJ0nxRNhEHwAyUsHxqW6xR6CdKfSS-cqdT8g9SNY7UZGoDGmHHE8mBIZYAB3LPQJhHSi-WB9tgcHO%2BPMFm6ihTi3yeiky8uKysltW1kOOgCsjejsYTSZTiAAqtxnnw%2BwOKEOR%2BwKOOFM70K7p%2B6JWul68Kw-q1SaY6ADZd2bVtDwEABhZhcFwcCOFMfNoCwFMHwgJ8XxKGcIDnBQFyjb1iS-Fcf3Xf9IQAdmA-c2yPZl9TlLMUKdF1EELWdixuUsCKgb8qxIutIQADkolsD3bRBYONe9GzQljXyLd8OPw30iN4mtSJBABOYS4xNewsCzWCRBEJhGMnWSMLfecPzLQj-VUv9%2BJBfJwUdPcROogQ9QNI0x2k5jWKw9jVU-biVLXNTHJufIGVckDEF0-S%2BC8w0lV8x0zICsBsPxRSQvlMLFIizd%2BW1VzoQ6a0KAAFT4B4AHVWACRiZMy7KwFwwkbNCuzwoc4qnIjWL9xNPhiCtAARRhWANRLTPzczfEwrKgq9PL3iwYiiuBJyG1c1kLDIewqvwEJzWfRBYUIPgsAa%2BAmsbVFhTktiFOCrrSQ2%2Bzg22qKdz2tlKHsVgLGtc8WBTc0LG4ARoLvRityeiz5Ks3L3vWza%2Bp%2Bkp8iA-6LAYOA%2BHgW77vrRHFssnDrK4j6Me%2B0MooovGRvTB5rT4YxTBJ3kHvJhQlrajrONldGvo3LHfHyIS8YANT-eN3ngd5Qm5xjHtalbFzRslevpx18i0vGADEnEQu8FatZXVd5jXXtW96eN18WGZKIVd2ZEg2HQd4E2NaBGnjdN-ewXBKthDMJKIEQpMdFrnsCu2tZpx3Csxl3fAFGLIUgQREC7b3OUTLAexCKqfUmoGKEau8TStWiRHovgzj887bZRt7k4K1UtvThQBVK7OAGlEEQbhDuOkJKHDsR7Wa-z4%2BWxO8LWnXU71rVBuz-azoNAhrbJtuqdRzuerX53HQFXbs-hMJMBG0Io46OrEDlZkEAdSE46Rl72-tk-VzPupG4Ao-rZxNN7UIFATZUFHBQeEkCWBxEQFVWA5VEgsDhi3dCFNkZHw7spU%2B3c04X1xmA9AiUKAYN%2BFyDgoR66Nwru8aucE56twXoLamBCAFEPXiCAUTNr55kNFgN%2BSBWHYP5jiA46wURvFwEbXArBzgtWxEAA)

#### Code

```fsharp
let shouldIncludeRelationship relName =
    req.Includes |> List.exists (fun path ->
      path.Length >= currentIncludePath.Length + 1
      && path |> List.take (currentIncludePath.Length + 1) = currentIncludePath @ [relName]
    )
```
            

#### Result

```fsharp
let shouldIncludeRelationship relName =
    req.Includes
    |> List.exists (fun path ->
        path.Length
        >= currentIncludePath.Length
        + 1
        && path
           |> List.take (currentIncludePath.Length + 1) = currentIncludePath @ [ relName ])

```
            
#### Problem description

The following:

```f#
path.Length
>= currentIncludePath.Length
+ 1
```

Should be on one line:

```f#
path.Length >= currentIncludePath.Length + 1
```

Also, this is weirdly formatted (line break and indentation):

```f#
&& path
   |> List.take (currentIncludePath.Length + 1) = currentIncludePath @ [ relName ])
```

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 07/20/2020 08:56:02 - d42a1565b1b7c532e3dbeaaa4ec0f0cb5ba79f69

| Name | Value |
| ---- | ----- |
| `IndentSize` | `4` |
| `MaxLineLength` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxValueBindingWidth` | `40` |
| `MaxFunctionBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `MaxElmishWidth` | `40` |
| `SingleArgumentWebMode` | `false` |
| `AlignFunctionSignatureToIndentation` | `false` |
| `AlternativeLongMemberDefinitions` | `false` |
| `StrictMode` | `false` |

**Comment by knocte** [comment]
> Should be on one line:

Why? Because compilation breaks?

I think you can workaround this by increasing MaxInfixOperatorExpression

**Comment by cmeeren** [comment]
> Why? Because compilation breaks?

Sorry the short description. Compilation is fine, but I find

```f#
path.Length
>= currentIncludePath.Length
+ 1
```

to be very confusing to read. There shouldn't be visual symmetry between `>=` and `+`. The `>=` operator is the main thing going on here, with `path.Length` and `currentIncludePath.Length + 1` being the two arguments. So if line breaks were really needed, it would be better with

```f#
```f#
path.Length
>= currentIncludePath.Length
   + 1
```

---

> I think you can workaround this by increasing MaxInfixOperatorExpression

Tried increasing it to 120, no effect.

---

By the way, I misread the intentation here:

> Also, this is weirdly formatted (line break and indentation):
> 
> ```fsharp
> && path
>    |> List.take (currentIncludePath.Length + 1) = currentIncludePath @ [ relName ])
> ```

I think the indentation here makes sense.

---

Sorry about the issue title, by the way 😅

**Comment by nojaf** [comment]
Hey @cmeeren 

So 

> Should be on one line:

> path.Length >= currentIncludePath.Length + 1

This is a bit point of view I'm afraid. From a logic perspective, I'd yes agreed. However, Fantomas has no idea what operators like `>=` and `+` mean, it only knows that there is an expression with multiple operators that is longer than the threshold @knocte  mentioned.

There a few exceptions to this: [newLineInfixOps](https://github.com/fsprojects/fantomas/blob/a67f3a3b9f109d3b7e54aa70db9d56c9c5523dc6/src/Fantomas/Context.fs#L721) and [noBreakInfixOps](https://github.com/fsprojects/fantomas/blob/a67f3a3b9f109d3b7e54aa70db9d56c9c5523dc6/src/Fantomas/Context.fs#L724) .
In those cases, we always break or never break.

We could add `>=` and `<=` to those lists but that might still not give your the [desired result](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBnAFrAK7rwCSAdtOkUgEqLoCGWAlrBQawA5gBOjAHJMAtojABeADp8pFCBAEBHAHSVqtRLjAAfAHxgAMq1xYViAB4ms2gBQAzIvO4t8YALR6ZchQpdZ8FUNECgBzALADaCI%2BAQosdRokAAVXIJDwtwBqMABGb3lfMAAyYrB-N30jaxUsJgBrcVto2JCEqiTEVID0sIic3IBKSTAWuPaNFNcwAAEwAG0BdGExAF0C30HIABpwKFxsNjDcVAW9iFAiqAASLABPbmQ0SFZ4nfOFSGuANyYaJ7OVwgAAZdkCoJQkPEAMqsABeyDBQIALB8IKsPgBfJEXNE3e6PU4vN44z4-P5EAHzPEQXKk3yQACyTAsxgoiGCfXw73BuQATMC8RjfNiPpcil8CQDIAAjWCwdA8iXk-6nangvn0z7QxAiVhwdAcACCWAAohR4AB5exsxE0sD2P4HIVY0nihm3B7SuUKpUe36qtDqoEAZi1EEg0Jc0EQACFEPZYAJUnxRNhEHw-UUsHxKS6RW68ZKvUSfYqtV8A5S1fbkeGoFGmDH44mBIZYAB3DPQJgHSjfWA9tgcLO%2BHN5q7ChSi3zuslS0vy8tFlXVoP2gCs9cj0bjCaTiAAqtxHnwe32KAOh%2BwKKOFI70M7J66xSuF88y3fKxSqfaAGzbo2zb7gIADCzC4LgoEcKYubQFgSZ3hAD5PkUU4QDOChzhGnqEh%2BS5fquv7ggA7IBu4tgejK6jKGZIQ6TqIPm06FlcxZ4VAn4VkRNbggAHORTZ7q2iDQYat71ihTHPgWr5sbh3oEdxVbEUCACcgkxka9hYBm0EiCITD0eO0loS%2Bs5viW%2BG%2BspP68UCuSgvaO5CZRAg6nqBojpJjHMRhrHKu%2BnFKSuKn2VcuR0s5QGINpul8B5%2BoKt59omX5YCYbi8lBbKIXyWF668pqzmQm0loUAAKnwdwAOqsAE9FSelmVgNh%2BJWcFNmhXZhUOWG0W7kafDEBaAAijCsHq8XGbmpm%2BOhGUBR6OWvFghEFYCDl1s5zIWGQ9gVfgISmo%2BiDQoQfBYHV8ANfWyKCjJLFyYFHXEmttmBptEVbjtLKUPYrAWJap4sEmpoWNwAiQTe9Ebg9ZmyRZ2Wvat609V9RS5ABv0WAwcB8PA123bW8PzeZWGWRxb1o59wYRWRONDamdyWnwximET3J3aTCgLS1bXsdKqMfWuGO%2BLkAk4wAaj%2BsavPAryhJz9H3c1S3zijJLdbT9q5BpOMAGJOPBN5yxaivK9zavPctr1cdrot00UArboyJBsOgrxxoa0D1LGqa%2B9guDldCaZiUQIgSfaTWPf5Nsa1T9v5ejTu%2BHyUXgpAgiIB2nvsvGWBdiEFVeuNAMUPVN5Gha1EiLRfAnD5p3W0jL2J3lyobanCh8sVmcANKIIg3D7YdISUKHYi2o1vmx4t8c4StWvJzrGr9Znu0nXqBCWyTLcU8j7ddSvjv2ny22Z7CYSYENoQR20NWIDKjIIHa4IxwjT2t7bR-LifqlXD5D9TORpPahAoEbKgw4KCwnASwGIiAKqwFKvEFgMMm6oTJojA%2BbdFLH07inM%2B2MQHoHihQNB3wOQcFCLXeuZdXiVxgjPZuc9%2BaUzwX-Ahq8gR8gZpfHM%2BosAvyQMwzBvMsR7FWEiF4uADa4FYKcJqmIgA).

Not sure what other options we have here.

**Comment by cmeeren** [comment]
> This is a bit point of view I'm afraid. **From a logic perspective, I'd yes agreed.** However, Fantomas has no idea what operators like `>=` and `+` mean

(Emphasis mine) So it's not just a matter of taste, it's more an implementation challenge?

I'll think about this and get back to you.

**Comment by nojaf** [comment]
Indeed, Fantomas has no idea what your code does and if it even makes sense.
For example, we can format valid syntax where inside the project the code does not compile.
That is why it is very difficult to make better decisions here.

**Comment by cmeeren** [comment]
I think this may be solved by Fantomas knowing about [operator precedence](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/symbol-and-operator-reference/#operator-precedence).

Quasi algorithm:
* If line is too long, find lowest precedence operator and break on that (break on all operators with the same precedence)
* If some of the broken lines are still too long, find the next lowest precedence operator(s) in those lines and break on those, but indent as demonstrated in this issue

**Comment by nojaf** [comment]
So if we have `a + b * c` where whole expression is too long:
- We split `a + b` and `c` as `*` takes precedence.
- `a + b` is not too long for example
- the outcome would be:
```fsharp
a + b
* c
```
Like that?

**Comment by knocte** [comment]
If `*` takes precedence over `+` (which I guess it is the case for F#, to mimic math), then IMO the splitting should be done in the opposite way:

```
a +
b * c
```

**Comment by nojaf** [comment]
@knocte yes indeed, my bad, thanks for the correction.
Wishful thinking there is something exposed in the F# compiler (FCS) that can help us here.

**Comment by cmeeren** [comment]
If not, perhaps the order of operators could be hardcoded for now.

**Comment by nojaf** [comment]
Hey, I'm trying to give this issue a shot by having a better way of splitting the infix operators.
I'm working something out along the lines of
```fsharp
type Associativity =
    | Right
    | Left
    | NonAssociative

type InfixOperatorMeta =
    { Priority: int
      Associativity: Associativity
      PreferOnNewline: bool }

// Not sure if a fixed map is workable
// https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/symbol-and-operator-reference/#operator-precedence

let operatorMeta =
    [ "+", { Priority = 1; Associativity = Left; PreferOnNewline = false }
      "-", { Priority = 1; Associativity = Left; PreferOnNewline = false }
      "*", { Priority = 2; Associativity = Left; PreferOnNewline = false }
      "|>", { Priority = 3; Associativity = Left; PreferOnNewline = false }
      "=", { Priority = 3; Associativity = Left; PreferOnNewline = false }
      "&&", { Priority = 4; Associativity = Left; PreferOnNewline = false } ]
    |> Map.ofList
```

And then in the CodePrinter you try and split on the lowest priority.
I've started with some easy samples to wrap my head around it:
```fsharp
[<Test>]
let ``simple math`` () =
    formatSourceString false """let myValue = a + b * c
"""   { config with MaxInfixOperatorExpression = 5 }
    |> prepend newline
    |> should equal """
let myValue =
    a +
    b * c
"""

[<Test>]
let ``simple math in one line`` () =
    formatSourceString false """let myValue = a + b * c
"""   { config with MaxInfixOperatorExpression = 50 }
    |> prepend newline
    |> should equal """
let myValue = a + b * c
"""

[<Test>]
let ``simple math reversed`` () =
    formatSourceString false """let myValue = a * b + c
"""   { config with MaxInfixOperatorExpression = 5 }
    |> prepend newline
    |> should equal """
let myValue =
    a * b
    + c
"""

[<Test>]
let ``multiple sum operators`` () =
    formatSourceString false """let myValue = a + b * c + d
"""  { config with MaxInfixOperatorExpression = 5 }
    |> prepend newline
    |> should equal """
let myValue =
    a +
    b * c +
    d
"""
```

Now the first thing I'm struggling with it deciding when an operator should be added before or after the expression.
How to be consistent here? Always operators at the back? I don't think that always work if you take:
```fsharp
let x =
    a * b +
    c
```

same problem for always at the front
```fsharp
let x =
    a
    + b * c
```

I'm open for suggestions on this.

**Comment by cmeeren** [comment]
> Now the first thing I'm struggling with it deciding when an operator should be added before or after the expression.

IMHO code is easier to read if the operators are at the front. But in any case, if you treat all operators the same (not just arithmetic operators), you kinda have to, because no-one wants:

```f#
let exec f x =
  x |>
  f
```

The only valid option here is:

```f#
let exec f x =
  x
  |> f
```



> same problem for always at the front
> 
> ```fsharp
> let x =
>     a
>     + b * c
> ```

I don't see any problem with this. Of course, it's a bit artificial since the line is so short, but given `MaxInfixOperatorExpression  = 5` this is what I would expect.

**Comment by knocte** [comment]
IMO `|>` should be considered a special operator. That is, the way I see it, it should be formatted as:

```
let exec f x =
  x
  |> f
```

and

```
let x =
    a +
    b * c
```

**Comment by cmeeren** [comment]
I then suggest that it be made configurable whether to break with operators at the end or at the front.

**Comment by cmeeren** [comment]
FWIW, the reason I find front operators more readable is a combination of 1) operators we break at are more "important" for readability given their associativity in the hierarchy, and 2) placing them at the front makes them easier to see since a) they are all aligned, and b) you don't have to hunt for them far to the right if you have long lines.

**Comment by nojaf** [comment]
> I then suggest that it be made configurable whether to break with operators at the end or at the front.

No, just no 🙃. Sorry, this is really unmaintainable to have a setting for each operator. Especially when users can have custom operators.

Maybe Fantomas can store an opinioned preferred location for some operators and have a default at the front.

But then again, I agreed with @cmeeren his last remarks.

**Comment by cmeeren** [comment]
> No, just no 🙃. Sorry, this is really unmaintainable to have a setting for each operator. Especially when users can have custom operators.

I meant one setting for all operators.

> But then again, I agreed with @cmeeren his last remarks.

👍

**Comment by nojaf** [comment]
@cmeeren I was able to resolve the original issue and published an alpha on [NuGet](https://www.nuget.org/packages/fantomas-tool/4.2.0-alpha-004). Could you let me know if anything weird popped up in other places.

**Comment by cmeeren** [comment]
Thanks! I'll let you know.
