### ISSUE TITLE
Removes the first comment above the member of the list

### ISSUE THREAD

**Issue by Thecentury** [fsprojects/fantomas#990]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPMAvGANoA6ATqQHYQQD0dYcAts4lVhdbWAIxc1aDMAEMqsLAAtE5JrFbtOlQRABMAgLqQANOCgBnbFgCWVAOb7UJPRFA8IkACRYAngAdkaSKaw6btJwA3EXQAV09re1oABl0ohwBJKiQOAGVjAC9kOPiAFn8IDX8AXxzbAqhndwjvDj8ooJDwq2IKiF4y%2B0gAWRFcABlTRH72Myl6%2BN5VaIqinlL-Oy6qjytIACNYWHQJnkawiNb4sFVOvdTEZmM4dFgqAEEsAFFkgHkAM0GqbLawd5DDLMSp0lnsVjVNttdgFHMEDi1fgBmM4BVJuETQRAAIUQ71g5EQAAUROQRGwsDJoTwsORwkD5iCKk5XKsvJCdij9s00Ec8iiHGiMdjcfjhrAAO4yaAiQxJQKwaUmO5U2g0ulROa0BY8UEwlkQrYcpmwpqHX4AVn5UEFmJxeIJAFU3B5yNLZVR5YrjMqrf90ICNcDFsb9Wt2SquWbjgA2K2QG3C%2B2IADC6Bl%2BmTd30augWHxKogfoD9k1EG1tF1DnBYcNEZN8J5vwA7HGE3bRd1LutKb6AYh6VrGQ1q2za5z69zIvEAByt9G2kUEzO3KgFv59gdlofLUOjqHjuGT3lRACcc6F93eFPImdYIjXav7gYZweHu6g4YPpoRx14sV%2B8bzomooXFcNw%2Br8RZPiWQY6iG1Q1vuxqHlGkwdABCaXteoHXNsEHHI%2Bm5gOW5Rvghe5GsOKE-pMpwAUkKRYK8VAACrkC4ADqxjjL2-rQTwpbEduYLvhsY7Id%2Bja-siGFAfc5CwKEyQACKIOgxhXNeD60vxtCCSRYCVpUok%2BHW1FSZMuRxr0uAJO8LHSFQTx8akkj4lgXHwDxvy5DMz6Dq%2BO7kVAplfg2U5RLwloATZSTvMYuCvC6Ih5uQTy4G4BL6Po3qrla5p%2BTBL5wWRrIhXUYVHr8vCxjFfQAEqIHA5DwJ53nHL5REGUZzLBbUviVahkUtnVuDyaSLivOQgzZm1khrp1-lboFIl9aFEnhce9i8LOo0AGqmlipjwKYZhzQthUCbBFbwWV-VmZJEXbWeo0AGJKbmuVHckp3nVai1FQFJVBXdn4bVVxzTNZoToCY6nfFitzQAA1lipIo9g%2BjMakZIptsoTMHlkEbktQkrXqfVg1Rj1bTwqjocckAAHKIOK8PClgkrsCx1SqfFVDcbl9zJJ2zDduQli8cWV3FTdpUGkh1Obb8qh0YzADSiCIG4dkOewSQ42wXw-McUFdcJFN3etSsQ-EqgyYzNnOVc%2BiSH9PmXXp12kSDCuUcs5lPXTVkYadmDyWYBOKBxiDrN0CAm-EZuk91t1%2Bw9yuQ9FjP3OpZhUO9VCfXc6T5yloQEixsAMYoKW5WuyeA8twOraD4k20N9iqLVOewzIVB14EYrmKL4t86YgtZg3JNN2TLeW%2Bng00VEqgjYzqQ0tcWDx0g098V1egaDk3j6K9OVWGbxRAA)

#### Code

```fsharp
let x = [
    // comment
    1
    // another comment
    2
]
```
            

#### Result

```fsharp
let x =
    [ 1
      // another comment
      2 ]

```
            
#### Problem description

Fantomas removes the first comment.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 07/20/2020 08:56:02 - d42a1565b1b7c532e3dbeaaa4ec0f0cb5ba79f69

| Name | Value |
| ---- | ----- |
| `IndentSize` | `4` |
| `MaxLineLength` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxValueBindingWidth` | `40` |
| `MaxFunctionBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `MaxElmishWidth` | `40` |
| `SingleArgumentWebMode` | `false` |
| `AlignFunctionSignatureToIndentation` | `false` |
| `AlternativeLongMemberDefinitions` | `false` |
| `StrictMode` | `false` |

**Comment by knocte** [comment]
Removing comments is pretty bad because there's no way to detect this bug (it's failing silently), so using fantomas makes you lose important information. I'd mark this as high priority if you ask me.

**Comment by nojaf** [comment]
The missing comment is now assigned to `SynExpr.CompExpr`.
![image](https://user-images.githubusercontent.com/2621499/89764508-cd550d00-daf4-11ea-8ba9-dc034f84d9e2.png)

Trivia for that node is most likely not being printed somewhere in CodePrinter, so a fix done there.
Alternatively, you could try and assign the comment to SynExpr.Const as that is being printed as you can see for the other comment.

See [video](https://www.youtube.com/watch?v=FCrkUqCCzgI&list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K&index=4&t=0s) to have a better understanding about what I'm talking about.
