### ISSUE TITLE
Bug: Line break before bracket on long method call followed by member access causes semantic change

### ISSUE THREAD

**Issue by reinux** [fsprojects/fantomas#994]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBZAltATrAzrAGYAuAdAGIDKAFgIY4AOZASokQDaLQmawB2lWg0YAVAJ6NEZAOKISAVX59%2BAYTr5E%2BABQlJiYgB5YjXgOOmVhgK7KSAPkez5c-ohzYJUgCLtMdlW0ASjJ0OgBrRFd3T31dIJCAQXxNAFsAIw5xAB0cbP5IABpwKE0SXn4Ac3xUMABtEohQCBaoABI9KVrIfxIixpbINoA3Og5rZDQG1taABmKZwYBJfiR%2BEipMAC9kBcWwABYBiABdAYBfPabj9s7JqF7%2BxaHR8fvp-YBGK5nIMIAPAAy-kQgMQVRINCeXwATLMbmdWpcBs1fh19N10rBYBxoa0XmMJrUPosYT98VREKlsDiBIkSABRVYAeSIwLceJmRDGmgRFx%2BqPx6K6aEgWJxnIgBLexJuEAAzOTBlRGHRoIgAELsWA4RAABQYdFS8nckpaJBwEz5SIFNyGd0x2NxSulRKmcsOSqlKrVmu1usBsAA7u5oBpECthrAw2YCl6wBarYtES1ka1BYNhfcxU6za73h6AKzxyA%2B9Vaog6xAKRhSHBhzSR6N0WNmiDcji85P8lF2rOOiUukaEgv7MAANhLZb9ld1qg4GnwqgE%2BETPB1bbAHa7MxTEDTLQzUv7ovFzr7rzd9Q9AHYp6ry-7EOgqelTfHt4hranbc8T1AzzzYcZXdMcAA5719Csq2XDgBE3T9v33X80QdU9cyHS9R32ABOSD1USUh3GXVJUjoTdEy-bsbV7P80IAjCLxHWUx0%2BeYPVLB8ZyrSlqTgOC4w9RDqJ-WjUIxdDByYkDr1Y74OOnQiSHcXiaQEijLSo3ce3TPt6JzKS-ywljYRLFY1hIZl%2BFEHBxAAdUwSEEJ5LTWj3MAD2uOiJIYwy0WM0CvkVBSuMSPBbHgXwOEwallJwDSk20mjdO8kUHnWICAtkr4DhLAEliIUQaHBBlO0QWgdRIBz4Cc%2BMDnhETkLEoV9MeTDmMCxZPmLDj8v4IhMH%2BZk6xbHUGX%2BRhdRSFRN0LBqktElLxLSnoMvamSSRmT5J16uh-jYOAcHgarao9eqkI8lCWp81a%2BnWq9NtaT4712-4wpwOhxGZHBgVXE6oTq%2Ba3J0w89JutrpIej1Pgg16ADURw1fx4H8Sp-s3c7Gsu5rM1atbIewrq8NeihbB4FQkdWVH0cBi7PLAI9bhuwD7sJmY4Ty6wOF4aK3A1ODoHCDUPsF%2BR8CsqgjUQWDrFSQSx2EhamqW66VpZgmTNJeSx0gAA5RAg15v0SBDcEvEQXwBoCOlVhfDJ3BqD8XLpq7ceZxijI67LSTJDiAGlEEQRgCqK8EVkl412V2ITnax%2BnGftcH8c9jaPRhYKdYBUrqXwGgabOoGWnc%2BOwbVj3-K9x6WhhXKFNRrgwsqWXwSqxB0nQBBo4V2OlexlW3bLvyhSyquIBhHqdcSaLKn4Un%2BHJgRNhnltrF1URYHMluWxmp2ypdnHj309WU6hscYR2yfufcfht%2BGUEBEqO23xwS3-EclRHZjve49dw-3aHzMI804vR1lQC02ASAdyQM5b%2BvdzglBOHsHo%2BAKD4EwLURC5wgA)

#### Code

```fsharp
Microsoft.FSharp.Reflection.FSharpType.GetUnionCases(typeof<option<option<unit>>>.GetGenericTypeDefinition().MakeGenericType(t)).Assembly

```
            

#### Result

```fsharp
Microsoft.FSharp.Reflection.FSharpType.GetUnionCases
    (typeof<option<option<unit>>>.GetGenericTypeDefinition().MakeGenericType(t)).Assembly

```
            
#### Problem description

Because of the line break inserted before the bracket, FSC interprets `GetUnionCases` in the output to be a function rather than a method.

Typed AST of source:

```
[Entity
   (Tmp,
    [InitAction
       Call
  (None, val raise, [], [type Microsoft.FSharp.Core.obj],
   [Const (1, type Microsoft.FSharp.Core.int32)])])]
```

Typed AST of Fantomas output:

```
[Entity
   (Tmp,
    [InitAction
       Call
  (None, val raise, [],
   [type Microsoft.FSharp.Reflection.UnionCaseInfo Microsoft.FSharp.Core.[]],
   [Const (1, type Microsoft.FSharp.Core.int32)])])]
```

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 08/10/2020 06:52:52 - 6d8f0847cc6d56c41369c54055e69169f19bb1cd

| Name | Value |
| ---- | ----- |
| `IndentSize` | `4` |
| `MaxLineLength` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxValueBindingWidth` | `40` |
| `MaxFunctionBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `MaxElmishWidth` | `40` |
| `SingleArgumentWebMode` | `false` |
| `AlignFunctionSignatureToIndentation` | `false` |
| `AlternativeLongMemberDefinitions` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Hey @reinux, would it be possible to provide the full sample code for this?
I'm working on #501 and my changes would change the outcome of this issue to

```fsharp
Microsoft.FSharp.Reflection.FSharpType.GetUnionCases(typeof<option<option<unit>>>
        .GetGenericTypeDefinition()
        .MakeGenericType(t))
    .Assembly
``` 

I'd like to be sure that this code still works when outputted like this.
What is `t` in this case?

**Comment by reinux** [comment]
Hey, I've been trying to find it in my code, but I can't :(

I may have removed it. I can't quite remember what I was trying to do with that code either.

Sorry about that.

I'm trying it out now, and it looks like that `.Assembly` might be misplaced. There's a good chance I just typed up some semi-random stuff in `fantomas-online` that exposed the problem without sharing my own actual code.
