### ISSUE TITLE
Hexadecimal numbers in match arms are output as decimal numbers

### ISSUE THREAD

**Issue by vsinha** [fsprojects/fantomas#995]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzMAFAIZoCWAdlgJRgC8AOuRBALZFbQAWYRANGACMwAd1JZOjZmAA%2BYAAwAPAKxKwAWgB8YAMqwWiQlUnNZAfXVaAcrHLJe4KAGdsWCgHNHqMAG0HEUFIQkAAkWACeAA7IaJAUWJD2gVDBAG5E6ACu0T5%2BgXKJSVAAkuRIlNqkAF52uVIALLVgALq5AL4F-o0h4VFesZQJXanpWV6%2BhWAAjB2BkACyRAoAMhSIS4jkbuKDE5MATHKNLVLtuQGzoZHZkAKwsOg7F2mZ2eOFezNSkNqILKRw6BsAEEsABRUoAeVwK1sjySuHSziObRm5y%2Bl16MVu9zhzBCz1GaDeSQAzJ88doIkRoIgAEKIXCwABOiAACkQmUR9FhEEzcVIsEyssiTqihj1rtiHuT8SNXo0IHVyUFKdS6QzmWtYMJedAiM4SilYHrXDZ%2BcxBcKksdmKcpGi8RjJXdpUMCfKJkplVBVTT6YyWQBVCJRJl6g3kI0m0hm70I9BI60os7iq59KXm2UvMYKsAANm93ypfo1LIAwuh9Y4yzZHJboFhmeaIPHE4EbRA7cwHUEnemXZnhtmibmAOyF33qgOIOa-AS85t4RGIEW2sVJbpprEDmVDwk5CYADgnxanmprgPIi9bK6TopTG7725xu-dOYmAE4T2qgbgeUyaxYNhF0tW922Te1U0xKAM1fOV30KSZ8lzIs1X9TUfj%2BAFY1zG9V07dcLglfsXzdeCR12aYUMnX9-0w-57hwiZQPwsAu06R9iOfV1HzfCjEI%2BFCSjKLAIXIAAVJkwgAdTEThr2XVj2LAHtki4mCdzI4cD0QslqNPIEmVgDJSgAEUQdBSD%2Bf8QKFMCpA7NjCPRdT%2BniODtOJQJJiVFCFgUIpcHEzgNlBBNEG0ThmSwWT4G2b06kOO81wfIitygOJBz4nSkkmL0-MWEpcFIBQIVDdhmVBBQIhZRxHBjK9vSUJLwPvSDOPStysvInLvILAqFAAJUQOAmXgWL4tzRKlOcx1XMyjz9y8qRJnHAbDM5MIISZFY6wm%2BSEpahyIO7KDrgWrSltzSZjwGgA1OVaQoeB3H2xdpuSgjUpczqLt4nrluYSYvwGgAxEyGwap7Sle0g4oOqajuYRzlNUzdoJuTT-s83MDkLOYMnQVxLNsWlAWgABrWlOUp7BHDE7QuUQC8MhYRrcMUz6nO%2BubOtgy6PXeKiJkgSxEGEEn1SwHUNnEq5zOK8gxAaoFSlnFh5yZTw4051qUvatKMf57GromPZBJFgBpRBEAiQLgo2EpGf0GEagmPCudRs6%2Bj%2Bp4AdxvSRf8sK-kcTg3sOmaed7Vzjb9nGzd8kWKk2TBDLcVmNhixABDmBA3cKD29a%2Bg2fqNrH49N958pFoFLLcchwfISGbAqBv2AyFlxNgYSs-YBqFPCqPS958vSJNwWkj2fra6J3lyH7lItU2dXNYVihldrQe22OtrTo6seeMryfAj2Nbk8Ff4sDzpBt-s5G2gcJoCliRxQfqrw8NaIA)

#### Code

```fsharp
let f (a: int) =
    match a, b with
    | 0x55 -> Some ()
    | _ -> None
```
            

#### Result

```fsharp
let f (a: int) =
    match a, b with
    | 85 -> Some()
    | _ -> None

```
            
#### Problem description

Hex numbers in the different match cases are turned to decimal numbers. The reason this is not ideal is that the hex numbers in our use case represent various API results which are documented as hex numbers, and so we'd prefer for the code to continue to have hex numbers as well.

Note this doesn't occur in the non-match case. The following example is unchanged by the formatter.
```fsharp
let f  = 0x55 
```

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 08/10/2020 06:52:52 - 6d8f0847cc6d56c41369c54055e69169f19bb1cd

| Name | Value |
| ---- | ----- |
| `IndentSize` | `4` |
| `MaxLineLength` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxValueBindingWidth` | `40` |
| `MaxFunctionBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `MaxElmishWidth` | `40` |
| `SingleArgumentWebMode` | `false` |
| `AlignFunctionSignatureToIndentation` | `false` |
| `AlternativeLongMemberDefinitions` | `false` |
| `StrictMode` | `false` |

**Comment by vsinha** [comment]
Thanks for fixing this so quickly @nojaf !

**Comment by nojaf** [comment]
Thanks for reporting!
